const fs = require('fs');
const path = require('path');

const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath  = path.join(__dirname, '..', 'src', 'data', 'categories.json');

const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats  = JSON.parse(fs.readFileSync(catsPath, 'utf8'));

const existingIds = new Set(drugs.map(d => d.id));

function mkSearch(d) {
  return [d.nombre, d.nombreGenerico, ...d.nombresComerciales, d.familia, d.clasificacion, ...d.indicaciones]
    .join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

const newDrugs = [
  // ── Cardiovascular adicionales ──
  {
    id: "dronedarona",
    nombre: "Dronedarona",
    nombreGenerico: "Dronedarona",
    nombresComerciales: ["Multaq"],
    familia: "Antiarrítmicos",
    clasificacion: "Antiarrítmico clase III",
    mecanismoAccion: "Bloqueo multicanal (sodio, potasio, calcio) y antagonismo adrenérgico no competitivo. Derivado de amiodarona sin yodo, menor toxicidad tiroidea y pulmonar.",
    indicaciones: ["Fibrilación auricular paroxística o persistente", "Flutter auricular", "Mantenimiento del ritmo sinusal post-cardioversión"],
    contraindicaciones: ["Insuficiencia cardíaca clase IV NYHA", "Bradicardia severa", "Bloqueo AV de 2do o 3er grado", "Insuficiencia hepática severa", "Uso concomitante con inhibidores potentes de CYP3A4", "QTc prolongado > 500 ms"],
    efectosAdversos: ["Diarrea", "Náuseas", "Astenia", "Bradicardia", "Prolongación del QT", "Hepatotoxicidad (rara)", "Elevación de creatinina"],
    interacciones: ["Digoxina (aumenta niveles)", "Warfarina (aumenta INR)", "Inhibidores CYP3A4", "Estatinas (riesgo de miopatía)", "Betabloqueantes (bradicardia aditiva)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "400 mg cada 12 horas con las comidas", pediatria: "No aprobado en pediatría" },
    presentaciones: ["Comprimidos recubiertos 400 mg"],
    embarazo: "Categoría X - Contraindicado",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Administrar con alimentos (duplica biodisponibilidad)",
      "Monitorizar ECG basal y periódico (QTc)",
      "Control de función hepática mensual los primeros 6 meses",
      "Vigilar signos de ICC descompensada",
      "Monitorizar función renal (eleva creatinina sin daño real)"
    ],
    farmacocinetica: { absorcion: "Oral con alimentos (70-94%)", distribucion: "Vd alto, unión a proteínas >98%", metabolismo: "Hepático CYP3A4", eliminacion: "Fecal 84%, renal 6%", vidaMedia: "13-19 horas" },
    almacenamiento: "Temperatura ambiente, proteger de la humedad",
    unidadId: "u03", capituloId: "c0301",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Bradicardia severa, prolongación QT, hipotensión", manejo: "Soporte hemodinámico, marcapasos temporal si bradicardia, monitorización ECG continua" }
  },
  {
    id: "ivabradina",
    nombre: "Ivabradina",
    nombreGenerico: "Ivabradina",
    nombresComerciales: ["Coralan", "Procoralan"],
    familia: "Antianginosos",
    clasificacion: "Inhibidor selectivo de corriente If del nodo sinusal",
    mecanismoAccion: "Inhibe selectivamente la corriente If (funny current) del nodo sinusal, reduciendo la frecuencia cardíaca sin afectar contractilidad, conducción AV ni presión arterial.",
    indicaciones: ["Angina estable crónica", "Insuficiencia cardíaca con FEVI ≤35%", "FC ≥70 lpm en ritmo sinusal", "Intolerancia o contraindicación a betabloqueantes"],
    contraindicaciones: ["FC <60 lpm en reposo", "Shock cardiogénico", "IAM agudo", "Hipotensión severa (<90/50)", "Bloqueo AV 2do-3er grado", "Insuficiencia hepática severa", "Fibrilación auricular"],
    efectosAdversos: ["Fosfenos (fenómenos luminosos)", "Bradicardia", "Cefalea", "Mareo", "Fibrilación auricular", "Visión borrosa"],
    interacciones: ["Verapamilo/Diltiazem (contraindicado)", "Inhibidores CYP3A4", "Otros bradicardizantes", "Jugo de pomelo", "QT prolongadores"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Inicio 5 mg/12h, ajustar a 7.5 mg/12h según FC objetivo 50-60 lpm", pediatria: "No recomendado <18 años" },
    presentaciones: ["Comprimidos 5 mg", "Comprimidos 7.5 mg"],
    embarazo: "Categoría X - Contraindicado",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: [
      "Administrar con alimentos",
      "Monitorizar FC antes de cada dosis (objetivo 50-60 lpm)",
      "Educar sobre fosfenos: fenómenos luminosos transitorios, generalmente en primeros meses",
      "No suspender abruptamente",
      "Verificar ritmo sinusal antes de iniciar"
    ],
    farmacocinetica: { absorcion: "Oral rápida, biodisponibilidad 40%", distribucion: "Unión a proteínas 70%", metabolismo: "Hepático CYP3A4", eliminacion: "Renal y fecal", vidaMedia: "2 horas (metabolito activo 11 horas)" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u03", capituloId: "c0301",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Bradicardia severa, fosfenos intensos, mareo", manejo: "Atropina IV si bradicardia sintomática, isoproterenol si no responde, marcapasos temporal" }
  },
  {
    id: "sacubitril_valsartan",
    nombre: "Sacubitril/Valsartán",
    nombreGenerico: "Sacubitril/Valsartán",
    nombresComerciales: ["Entresto"],
    familia: "Insuficiencia cardíaca",
    clasificacion: "Inhibidor de neprilisina/antagonista de receptor de angiotensina II (ARNI)",
    mecanismoAccion: "Sacubitril inhibe la neprilisina aumentando péptidos natriuréticos (vasodilatación, natriuresis, reducción de fibrosis). Valsartán bloquea receptor AT1 de angiotensina II. Efecto sinérgico en IC.",
    indicaciones: ["Insuficiencia cardíaca con FEVI reducida (IC-FEr)", "Clase funcional NYHA II-IV", "Reemplazo de IECA/ARA-II en IC estable"],
    contraindicaciones: ["Uso concomitante con IECA (esperar 36h de washout)", "Antecedente de angioedema", "Embarazo", "Insuficiencia hepática severa", "Estenosis bilateral de arteria renal"],
    efectosAdversos: ["Hipotensión", "Hiperpotasemia", "Deterioro función renal", "Tos", "Mareo", "Angioedema (raro)"],
    interacciones: ["IECA (contraindicado, angioedema)", "Espironolactona (hiperpotasemia)", "AINE (deterioro renal)", "Litio (toxicidad)", "Alopurinol"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Inicio 49/51 mg o 24/26 mg cada 12h, titular cada 2-4 semanas hasta 97/103 mg cada 12h", pediatria: "Aprobado >1 año según peso" },
    presentaciones: ["Comprimidos 24/26 mg", "Comprimidos 49/51 mg", "Comprimidos 97/103 mg"],
    embarazo: "Categoría X - Contraindicado (fetotóxico)",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Verificar washout de 36h si venía con IECA",
      "Monitorizar PA (riesgo de hipotensión, especialmente al inicio)",
      "Control de potasio y función renal a las 1-2 semanas de inicio/titulación",
      "Titular gradualmente según tolerancia",
      "Educar sobre signos de angioedema (hinchazón facial, dificultad respiratoria)",
      "Pesar diariamente, vigilar signos de retención hídrica"
    ],
    farmacocinetica: { absorcion: "Oral, biodisponibilidad ≥60%", distribucion: "Unión a proteínas 94-97%", metabolismo: "Sacubitril: prodroga activada por esterasas a LBQ657", eliminacion: "Renal (sacubitril) y fecal (valsartán)", vidaMedia: "Sacubitril ~1.4h, LBQ657 ~11.5h, Valsartán ~9.9h" },
    almacenamiento: "Temperatura ambiente, proteger de la humedad",
    unidadId: "u03", capituloId: "c0301",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipotensión severa, hiperpotasemia, insuficiencia renal aguda", manejo: "Fluidos IV, vasopresores si necesario, corrección de potasio, hemodiálisis si refractario" }
  },
  // ── Anticoagulantes/Antitrombóticos ──
  {
    id: "fondaparinux",
    nombre: "Fondaparinux",
    nombreGenerico: "Fondaparinux sódico",
    nombresComerciales: ["Arixtra"],
    familia: "Anticoagulantes",
    clasificacion: "Inhibidor selectivo del factor Xa (pentasacárido sintético)",
    mecanismoAccion: "Se une selectivamente a antitrombina III potenciando su inhibición del factor Xa unas 300 veces. No inhibe trombina directamente. Pentasacárido sintético, no derivado de heparina.",
    indicaciones: ["Profilaxis TVP en cirugía ortopédica/abdominal", "Tratamiento de TVP y TEP", "SCA sin elevación ST", "Trombocitopenia inducida por heparina (HIT)"],
    contraindicaciones: ["Hemorragia activa", "Endocarditis bacteriana", "ClCr <20 ml/min", "Peso <50 kg (en profilaxis)", "Trombocitopenia con test positivo para fondaparinux"],
    efectosAdversos: ["Hemorragia", "Anemia", "Trombocitopenia (rara)", "Edema", "Elevación de transaminasas", "Reacción en sitio de inyección"],
    interacciones: ["Anticoagulantes orales (efecto aditivo)", "Antiagregantes plaquetarios", "AINE", "Trombolíticos"],
    viaAdministracion: ["subcutanea"],
    dosis: { adultos: "Profilaxis: 2.5 mg SC/día. Tratamiento TVP/TEP: <50kg 5mg, 50-100kg 7.5mg, >100kg 10mg SC/día", pediatria: "No aprobado en <17 años" },
    presentaciones: ["Jeringa prellenada 2.5 mg/0.5 mL", "Jeringa prellenada 5 mg/0.4 mL", "Jeringa prellenada 7.5 mg/0.6 mL", "Jeringa prellenada 10 mg/0.8 mL"],
    embarazo: "Categoría B - Usar solo si necesario",
    lactancia: "Precaución, se excreta en leche en animales",
    cuidadosEnfermeria: [
      "Administrar SC en tejido abdominal, alternar sitios",
      "NO administrar IM",
      "No expulsar burbuja de aire de la jeringa prellenada",
      "Monitorizar signos de sangrado",
      "Controlar hemograma y función renal",
      "No tiene antídoto específico (el sulfato de protamina NO revierte su efecto)",
      "Iniciar 6-8h post-cirugía"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 100%", distribucion: "Principalmente en sangre, Vd 7-11 L", metabolismo: "No se metaboliza", eliminacion: "Renal sin cambios (64-77%)", vidaMedia: "17-21 horas" },
    almacenamiento: "Temperatura ambiente (hasta 25°C)",
    unidadId: "u05", capituloId: "c0502",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hemorragia severa", manejo: "Factor VIIa recombinante, sin antídoto específico, soporte transfusional" }
  },
  {
    id: "bivalirudina",
    nombre: "Bivalirudina",
    nombreGenerico: "Bivalirudina",
    nombresComerciales: ["Angiomax", "Angiox"],
    familia: "Anticoagulantes",
    clasificacion: "Inhibidor directo de trombina (parenteral)",
    mecanismoAccion: "Se une directamente a trombina (libre y unida a coágulo) en el sitio catalítico y en el sitio de unión a aniones, inhibiéndola de forma reversible. No requiere antitrombina III.",
    indicaciones: ["Intervención coronaria percutánea (ICP)", "SCA con ICP planificada", "Alternativa a heparina en HIT", "Cirugía cardíaca en pacientes con HIT"],
    contraindicaciones: ["Hemorragia activa mayor", "Hipersensibilidad", "Insuficiencia renal severa (ajustar dosis)"],
    efectosAdversos: ["Hemorragia", "Dolor de espalda", "Náuseas", "Hipotensión", "Cefalea", "Trombosis aguda del stent (si se suspende prematuramente)"],
    interacciones: ["Heparina (efecto aditivo)", "Antiagregantes plaquetarios", "Trombolíticos", "Warfarina"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "ICP: Bolo 0.75 mg/kg IV, luego infusión 1.75 mg/kg/h durante procedimiento. HIT: 0.15-0.2 mg/kg/h ajustando según TTPa", pediatria: "Datos limitados" },
    presentaciones: ["Polvo para reconstitución 250 mg"],
    embarazo: "Categoría B - Usar solo si necesario",
    lactancia: "Precaución",
    cuidadosEnfermeria: [
      "Reconstituir con agua estéril, luego diluir en D5W o SS 0.9%",
      "Monitorizar ACT (tiempo de coagulación activado) durante ICP",
      "Vida media corta: el efecto cesa ~1h post-suspensión",
      "Vigilar sitios de punción arterial",
      "No mezclar con otros medicamentos en la misma línea",
      "Ajustar dosis en insuficiencia renal"
    ],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "No se une significativamente a proteínas", metabolismo: "Proteólisis plasmática y eliminación renal", eliminacion: "Renal 20%", vidaMedia: "25 minutos (normal), hasta 3.5h en diálisis" },
    almacenamiento: "Reconstituido: refrigerar, usar en 24h",
    unidadId: "u05", capituloId: "c0502",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hemorragia severa", manejo: "Suspender infusión (vida media corta ~25 min), soporte transfusional, no hay antídoto específico" }
  },
  // ── Analgésicos/Anestésicos ──
  {
    id: "tapentadol",
    nombre: "Tapentadol",
    nombreGenerico: "Tapentadol",
    nombresComerciales: ["Nucynta", "Palexia", "Yantil"],
    familia: "Analgésicos opioides",
    clasificacion: "Agonista mu opioide / Inhibidor de recaptación de noradrenalina (MOR-NRI)",
    mecanismoAccion: "Mecanismo dual: agonismo del receptor mu opioide (analgesia central) e inhibición de la recaptación de noradrenalina (modulación de vías descendentes inhibitorias del dolor). Menor actividad serotoninérgica que tramadol.",
    indicaciones: ["Dolor agudo moderado a severo", "Dolor crónico severo (formulación retard)", "Dolor neuropático diabético", "Dolor oncológico"],
    contraindicaciones: ["Depresión respiratoria severa", "Íleo paralítico", "Uso de IMAO (últimos 14 días)", "Asma bronquial agudo", "Hipercapnia", "Intoxicación aguda por alcohol/hipnóticos/opioides"],
    efectosAdversos: ["Náuseas", "Mareo", "Somnolencia", "Estreñimiento", "Cefalea", "Vómitos", "Prurito", "Menos depresión respiratoria que otros opioides equipotentes"],
    interacciones: ["IMAO (contraindicado)", "Benzodiazepinas (depresión SNC)", "Serotoninérgicos (síndrome serotoninérgico)", "Alcohol", "Otros depresores del SNC"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Liberación inmediata: 50-100 mg cada 4-6h (máx 700 mg/día 1er día, 600 mg/días siguientes). Liberación prolongada: 50 mg cada 12h, titular", pediatria: "No aprobado en <18 años" },
    presentaciones: ["Comprimidos 50 mg", "Comprimidos 75 mg", "Comprimidos 100 mg", "Comprimidos retard 50 mg", "Comprimidos retard 100 mg", "Comprimidos retard 150 mg", "Comprimidos retard 200 mg", "Comprimidos retard 250 mg"],
    embarazo: "Categoría C - Riesgo de síndrome de abstinencia neonatal",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Evaluar dolor con escala antes y después de administrar",
      "Monitorizar FR, SatO2, nivel de sedación",
      "Los comprimidos retard NO deben triturarse ni partirse",
      "Educar sobre riesgo de dependencia",
      "Menor incidencia de estreñimiento que morfina equivalente",
      "No combinar con IMAO ni dentro de 14 días de su suspensión"
    ],
    farmacocinetica: { absorcion: "Oral, biodisponibilidad 32%", distribucion: "Amplia, unión a proteínas 20%", metabolismo: "Hepático por glucuronidación (UGT1A9, UGT2B7)", eliminacion: "Renal 99% (conjugados)", vidaMedia: "4 horas (liberación inmediata)" },
    almacenamiento: "Temperatura ambiente, almacenar de forma segura (opioide controlado)",
    unidadId: "u02", capituloId: "c0201",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Depresión respiratoria, miosis, sedación profunda, convulsiones", manejo: "Naloxona IV (puede requerir dosis repetidas), ventilación asistida, monitorización prolongada" }
  },
  {
    id: "buprenorfina",
    nombre: "Buprenorfina",
    nombreGenerico: "Buprenorfina",
    nombresComerciales: ["Subutex", "Transtec", "Suboxone", "Buplex"],
    familia: "Analgésicos opioides",
    clasificacion: "Agonista parcial mu / Antagonista kappa opioide",
    mecanismoAccion: "Agonista parcial de alta afinidad del receptor mu opioide y antagonista del receptor kappa. Efecto techo para depresión respiratoria pero no para analgesia a dosis clínicas. Alta afinidad con disociación lenta del receptor.",
    indicaciones: ["Dolor moderado a severo", "Dolor crónico (parches)", "Terapia de sustitución en dependencia a opioides", "Dolor oncológico"],
    contraindicaciones: ["Depresión respiratoria severa", "Insuficiencia hepática severa", "Íleo paralítico", "Delirium tremens", "Uso concomitante de agonistas mu puros a dosis altas"],
    efectosAdversos: ["Náuseas", "Mareo", "Cefalea", "Estreñimiento", "Somnolencia", "Sudoración", "Reacción en sitio de parche", "Síndrome de abstinencia precipitado si se usa con otros opioides"],
    interacciones: ["Benzodiazepinas (depresión respiratoria, REMS)", "Inhibidores CYP3A4 (aumentan niveles)", "Inductores CYP3A4 (reducen niveles)", "Otros opioides (puede precipitar abstinencia)", "Alcohol"],
    viaAdministracion: ["sublingual", "transdermica", "intravenosa", "intramuscular"],
    dosis: { adultos: "Sublingual: 0.2-0.4 mg cada 6-8h. Parche: 5-20 mcg/h cada 7 días. Sustitución opioides: inicio 2-4 mg SL, titular hasta 16-24 mg/día", pediatria: "IV/IM >6 meses: 3-6 mcg/kg cada 6-8h" },
    presentaciones: ["Comprimidos sublinguales 0.2 mg", "Comprimidos sublinguales 2 mg", "Comprimidos sublinguales 8 mg", "Parche transdérmico 5 mcg/h", "Parche transdérmico 10 mcg/h", "Parche transdérmico 20 mcg/h", "Ampolla 0.3 mg/mL"],
    embarazo: "Categoría C - Preferida sobre metadona en algunos protocolos de dependencia",
    lactancia: "Compatible en dosis bajas según algunos protocolos",
    cuidadosEnfermeria: [
      "Sublingual: colocar bajo la lengua hasta disolución completa (5-10 min), no tragar",
      "Parche: aplicar en piel limpia, seca, sin vello, rotar sitios, no cortar el parche",
      "En sustitución de opioides: iniciar en abstinencia leve (escala COWS ≥12)",
      "Monitorizar FR y nivel de sedación",
      "Efecto techo de depresión respiratoria: mayor seguridad que agonistas puros",
      "Naloxona puede ser menos efectiva por alta afinidad al receptor (usar dosis más altas)"
    ],
    farmacocinetica: { absorcion: "SL: 30-50%, Parche: absorción lenta y constante", distribucion: "Amplia, unión a proteínas 96%", metabolismo: "Hepático CYP3A4 a norbuprenorfina", eliminacion: "Fecal 70%, renal 30%", vidaMedia: "SL: 24-42h, IV: 2-3h" },
    almacenamiento: "Temperatura ambiente, almacenamiento seguro (controlado)",
    unidadId: "u02", capituloId: "c0201",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Depresión respiratoria (con efecto techo), sedación, miosis", manejo: "Naloxona IV en dosis altas y repetidas (baja respuesta por alta afinidad), ventilación asistida, doxapram como adyuvante" }
  },
  // ── Antimicrobianos especiales ──
  {
    id: "daptomicina",
    nombre: "Daptomicina",
    nombreGenerico: "Daptomicina",
    nombresComerciales: ["Cubicin"],
    familia: "Antibióticos",
    clasificacion: "Lipopéptido cíclico",
    mecanismoAccion: "Se inserta en la membrana celular bacteriana de forma dependiente de calcio, formando canales iónicos que causan despolarización, salida de potasio intracelular y muerte celular. Bactericida contra gram positivos.",
    indicaciones: ["Bacteriemia por S. aureus (incluyendo MRSA)", "Endocarditis derecha por S. aureus", "Infecciones complicadas de piel y tejidos blandos por gram positivos", "Infecciones por enterococo resistente a vancomicina (ERV)"],
    contraindicaciones: ["Neumonía (el surfactante pulmonar inactiva daptomicina)", "Hipersensibilidad"],
    efectosAdversos: ["Elevación de CPK", "Miopatía", "Diarrea", "Cefalea", "Náuseas", "Neuropatía periférica (rara)", "Neumonía eosinofílica (rara)"],
    interacciones: ["Estatinas (suspender durante tratamiento, riesgo de rabdomiólisis)", "Inhibidores de HMG-CoA reductasa", "Tobramicina (aumenta nefrotoxicidad)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Piel/tejidos blandos: 4 mg/kg IV cada 24h. Bacteriemia/endocarditis: 6-10 mg/kg IV cada 24h. Ajustar en IR (ClCr <30: cada 48h)", pediatria: "1-6 años: 10-12 mg/kg/día. 7-11 años: 7-9 mg/kg/día. 12-17 años: 5-7 mg/kg/día" },
    presentaciones: ["Polvo para reconstitución 350 mg", "Polvo para reconstitución 500 mg"],
    embarazo: "Categoría B",
    lactancia: "Compatible (baja excreción)",
    cuidadosEnfermeria: [
      "Administrar IV en 30 min o push en 2 min",
      "NO usar para neumonía (inactivada por surfactante)",
      "Monitorizar CPK basal y semanal (suspender si CPK >1000 o síntomas musculares)",
      "Suspender estatinas durante el tratamiento",
      "Vigilar signos de miopatía: dolor muscular, debilidad",
      "Reconstituir con SS 0.9% (NO con dextrosa para push directo)"
    ],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Unión a proteínas 90-93%, penetra poco en pulmón", metabolismo: "Mínimo", eliminacion: "Renal 78%", vidaMedia: "8-9 horas" },
    almacenamiento: "Refrigerar. Reconstituido: estable 12h TA o 48h refrigerado",
    unidadId: "u01", capituloId: "c0101",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Miopatía severa, rabdomiólisis, insuficiencia renal", manejo: "Suspender inmediatamente, hidratación agresiva, monitorizar CPK y función renal, hemodiálisis parcialmente efectiva" }
  },
  {
    id: "tedizolid",
    nombre: "Tedizolid",
    nombreGenerico: "Tedizolid fosfato",
    nombresComerciales: ["Sivextro"],
    familia: "Antibióticos",
    clasificacion: "Oxazolidinona",
    mecanismoAccion: "Inhibe la síntesis proteica bacteriana uniéndose a la subunidad 50S del ribosoma (sitio 23S rRNA). 4-16 veces más potente que linezolid. Menor inhibición de MAO que linezolid.",
    indicaciones: ["Infecciones agudas de piel y tejidos blandos por gram positivos", "MRSA", "Enterococo resistente a vancomicina", "Alternativa a linezolid con mejor perfil de seguridad"],
    contraindicaciones: ["Hipersensibilidad a oxazolidinonas"],
    efectosAdversos: ["Náuseas", "Diarrea", "Cefalea", "Vómitos", "Menos mielosupresión que linezolid", "Menos interacción con IMAO"],
    interacciones: ["Menos interacciones que linezolid", "Precaución con serotoninérgicos (menor riesgo que linezolid)", "No requiere restricción dietética de tiramina"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "200 mg cada 24h por 6 días (IV u oral)", pediatria: "≥12 años: 200 mg/día por 6 días" },
    presentaciones: ["Comprimidos 200 mg", "Polvo para infusión 200 mg"],
    embarazo: "Categoría C",
    lactancia: "No recomendado (datos insuficientes)",
    cuidadosEnfermeria: [
      "Tratamiento corto: solo 6 días",
      "Puede administrarse con o sin alimentos",
      "Menor riesgo de trombocitopenia que linezolid",
      "No requiere monitorización de hemograma tan estricta como linezolid",
      "IV: infundir en 1 hora, compatible con SS 0.9% y D5W",
      "Bioequivalencia oral-IV: permite switch sin ajuste"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad ~91%", distribucion: "Amplia, unión a proteínas 70-90%", metabolismo: "Hepático (no CYP dependiente)", eliminacion: "Fecal 82%, renal 18%", vidaMedia: "12 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u01", capituloId: "c0101",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mielosupresión, síndrome serotoninérgico (raro)", manejo: "Suspender, soporte hematológico, ciproheptadina si síndrome serotoninérgico" }
  },
  {
    id: "ceftolozano_tazobactam",
    nombre: "Ceftolozano/Tazobactam",
    nombreGenerico: "Ceftolozano/Tazobactam",
    nombresComerciales: ["Zerbaxa"],
    familia: "Antibióticos",
    clasificacion: "Cefalosporina antipseudomónica + Inhibidor de betalactamasa",
    mecanismoAccion: "Ceftolozano: cefalosporina con alta afinidad por PBP de Pseudomonas aeruginosa, estable frente a betalactamasas AmpC y algunas BLEE. Tazobactam: inhibidor de betalactamasas clase A (TEM, SHV, CTX-M).",
    indicaciones: ["Infecciones intraabdominales complicadas (con metronidazol)", "ITU complicadas incluyendo pielonefritis", "Neumonía nosocomial/asociada a ventilador", "Infecciones por Pseudomonas MDR"],
    contraindicaciones: ["Alergia severa a betalactámicos", "Hipersensibilidad a componentes"],
    efectosAdversos: ["Náuseas", "Diarrea", "Cefalea", "Pirexia", "Elevación de transaminasas", "C. difficile", "Hipopotasemia"],
    interacciones: ["Probenecid (aumenta niveles de tazobactam)", "No interacciones clínicas significativas conocidas"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "ITU/intraabdominal: 1.5g (1g/0.5g) IV cada 8h. Neumonía nosocomial: 3g (2g/1g) IV cada 8h. Ajustar en IR", pediatria: "Datos limitados, en estudio" },
    presentaciones: ["Polvo para reconstitución 1g/0.5g", "Polvo para reconstitución 2g/1g"],
    embarazo: "Categoría B",
    lactancia: "Precaución",
    cuidadosEnfermeria: [
      "Infundir IV en 1 hora",
      "Para infecciones intraabdominales: combinar con metronidazol",
      "Ajustar dosis según ClCr (<50, <30, HD)",
      "Reconstituir con SS 0.9% o D5W",
      "Estable 24h a TA o 7 días refrigerado tras reconstitución",
      "Monitorizar función renal y hemograma",
      "Vigilar diarrea (riesgo de C. difficile)"
    ],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Unión a proteínas: ceftolozano 16-21%, tazobactam 30%", metabolismo: "Mínimo", eliminacion: "Renal >95%", vidaMedia: "Ceftolozano 3h, Tazobactam 1h" },
    almacenamiento: "Refrigerar. Reconstituido estable 24h a TA",
    unidadId: "u01", capituloId: "c0101",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Neurotoxicidad (convulsiones), diarrea severa, nefrotoxicidad", manejo: "Hemodiálisis efectiva (elimina 66% ceftolozano, 56% tazobactam), anticonvulsivantes si necesario" }
  },
  // ── Endocrinología ──
  {
    id: "liraglutida",
    nombre: "Liraglutida",
    nombreGenerico: "Liraglutida",
    nombresComerciales: ["Victoza", "Saxenda"],
    familia: "Antidiabéticos",
    clasificacion: "Agonista del receptor de GLP-1 (análogo de incretina)",
    mecanismoAccion: "Análogo de GLP-1 con 97% de homología. Estimula secreción de insulina dependiente de glucosa, suprime glucagón, enlentece vaciamiento gástrico, promueve saciedad central. Cardioprotector (reduce MACE).",
    indicaciones: ["Diabetes mellitus tipo 2", "Obesidad/sobrepeso con comorbilidades (Saxenda)", "Reducción de riesgo cardiovascular en DM2 con enfermedad CV establecida"],
    contraindicaciones: ["Antecedente personal/familiar de carcinoma medular de tiroides", "NEM tipo 2", "Pancreatitis aguda", "Hipersensibilidad"],
    efectosAdversos: ["Náuseas (frecuente al inicio)", "Vómitos", "Diarrea", "Estreñimiento", "Cefalea", "Hipoglucemia (con SU o insulina)", "Pancreatitis (rara)", "Colelitiasis"],
    interacciones: ["Sulfonilureas/Insulina (mayor riesgo hipoglucemia, reducir dosis)", "Anticoagulantes orales (absorción alterada)", "Medicamentos que requieren absorción rápida"],
    viaAdministracion: ["subcutanea"],
    dosis: { adultos: "DM2 (Victoza): inicio 0.6 mg/día SC x1 semana, luego 1.2 mg/día, máx 1.8 mg/día. Obesidad (Saxenda): escalar de 0.6 a 3.0 mg/día en 5 semanas", pediatria: "DM2 ≥10 años: hasta 1.8 mg/día" },
    presentaciones: ["Pluma prellenada Victoza 6 mg/mL (3 mL)", "Pluma prellenada Saxenda 6 mg/mL (3 mL)"],
    embarazo: "Categoría X - Suspender 2 meses antes de concepción",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Inyectar SC en abdomen, muslo o brazo, rotar sitios",
      "Escalar dosis gradualmente para minimizar náuseas",
      "Educar sobre uso de pluma y cambio de agujas",
      "Refrigerar plumas sin usar; en uso: TA hasta 30 días",
      "Monitorizar glucemia y HbA1c",
      "Vigilar signos de pancreatitis (dolor abdominal severo irradiado a espalda)",
      "Peso semanal si se usa para obesidad"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 55%, Tmax 8-12h", distribucion: "Unión a proteínas >98%", metabolismo: "Degradación endógena (DPP-4, endopeptidasas)", eliminacion: "Renal y fecal como metabolitos", vidaMedia: "13 horas" },
    almacenamiento: "Refrigerar (2-8°C). En uso: temperatura ambiente hasta 30 días",
    unidadId: "u08", capituloId: "c0801",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Náuseas severas, vómitos, hipoglucemia (si combinado con SU/insulina)", manejo: "Soporte sintomático, glucosa IV si hipoglucemia, no requiere diálisis" }
  },
  {
    id: "semaglutida",
    nombre: "Semaglutida",
    nombreGenerico: "Semaglutida",
    nombresComerciales: ["Ozempic", "Wegovy", "Rybelsus"],
    familia: "Antidiabéticos",
    clasificacion: "Agonista del receptor de GLP-1 (análogo de incretina de acción prolongada)",
    mecanismoAccion: "Análogo de GLP-1 con 94% de homología, modificado con ácido graso C18 que se une a albúmina prolongando su vida media. Mismos mecanismos que liraglutida pero con administración semanal. Potente reducción de peso y HbA1c.",
    indicaciones: ["Diabetes mellitus tipo 2", "Obesidad/sobrepeso (Wegovy)", "Reducción de riesgo CV en DM2", "Reducción de eventos CV mayores en obesidad sin DM2 (SELECT trial)"],
    contraindicaciones: ["Carcinoma medular de tiroides (personal/familiar)", "NEM tipo 2", "Pancreatitis", "Hipersensibilidad"],
    efectosAdversos: ["Náuseas", "Vómitos", "Diarrea", "Estreñimiento", "Dolor abdominal", "Retinopatía diabética (empeoramiento transitorio con control glucémico rápido)", "Pancreatitis (rara)", "Colelitiasis"],
    interacciones: ["Sulfonilureas/Insulina (reducir dosis por riesgo de hipoglucemia)", "Anticonceptivos orales (absorción retardada con oral)", "Warfarina (monitorizar INR)"],
    viaAdministracion: ["subcutanea", "oral"],
    dosis: { adultos: "SC DM2: 0.25mg/semana x4sem, luego 0.5mg/sem, máx 2mg/sem. SC Obesidad: escalar 0.25→2.4mg/sem en 16-20 semanas. Oral: 3mg/día x30 días, luego 7mg/día, máx 14mg/día", pediatria: "SC ≥12 años para obesidad (Wegovy)" },
    presentaciones: ["Pluma SC 0.25/0.5 mg", "Pluma SC 1 mg", "Pluma SC 2 mg (Ozempic)", "Pluma SC 2.4 mg (Wegovy)", "Comprimidos 3 mg", "Comprimidos 7 mg", "Comprimidos 14 mg (Rybelsus)"],
    embarazo: "Contraindicado - Suspender 2 meses antes",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "SC: administrar el mismo día cada semana, cualquier hora, con o sin alimentos",
      "Oral (Rybelsus): tomar en AYUNAS con ≤120 mL de agua, esperar 30 min antes de comer/beber/otros medicamentos",
      "Escalar dosis gradualmente para minimizar efectos GI",
      "Refrigerar plumas sin usar; en uso: TA hasta 56 días",
      "Vigilar signos de pancreatitis",
      "Control oftalmológico en DM2 con retinopatía preexistente",
      "Monitorizar HbA1c cada 3 meses, peso mensual"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 89%. Oral: ~1% (requiere ayunas)", distribucion: "Unión a proteínas >99% (albúmina)", metabolismo: "Proteólisis y oxidación del ácido graso", eliminacion: "Renal 30%, fecal 36%", vidaMedia: "~1 semana (168 horas)" },
    almacenamiento: "Refrigerar. En uso (SC): TA hasta 56 días. Oral: temperatura ambiente",
    unidadId: "u08", capituloId: "c0801",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Náuseas severas prolongadas, vómitos, hipoglucemia", manejo: "Soporte sintomático prolongado (vida media ~1 semana), observación extendida, glucosa IV si hipoglucemia" }
  },
  {
    id: "empagliflozina",
    nombre: "Empagliflozina",
    nombreGenerico: "Empagliflozina",
    nombresComerciales: ["Jardiance"],
    familia: "Antidiabéticos",
    clasificacion: "Inhibidor del cotransportador sodio-glucosa tipo 2 (iSGLT2)",
    mecanismoAccion: "Inhibe selectivamente el SGLT2 en el túbulo proximal renal, reduciendo la reabsorción de glucosa y sodio. Produce glucosuria, natriuresis, reducción de presión arterial, y protección cardiorrenal independiente de la glucemia.",
    indicaciones: ["Diabetes mellitus tipo 2", "Insuficiencia cardíaca (con o sin DM2)", "Enfermedad renal crónica", "Reducción de riesgo CV en DM2 con enfermedad CV establecida"],
    contraindicaciones: ["DM tipo 1", "Cetoacidosis diabética", "TFGe <20 mL/min (para DM2; puede continuarse para IC/ERC)", "Infecciones genitourinarias recurrentes severas"],
    efectosAdversos: ["Infecciones urinarias", "Infecciones genitales micóticas", "Poliuria", "Hipotensión ortostática", "Cetoacidosis euglucémica (rara)", "Gangrena de Fournier (muy rara)", "Deshidratación"],
    interacciones: ["Diuréticos (deshidratación aditiva)", "Insulina/SU (reducir dosis por hipoglucemia)", "IECA/ARA-II (efecto aditivo en PA)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "DM2: 10 mg/día, puede aumentar a 25 mg/día. IC/ERC: 10 mg/día", pediatria: "≥10 años DM2: 10-25 mg/día" },
    presentaciones: ["Comprimidos 10 mg", "Comprimidos 25 mg"],
    embarazo: "No recomendado (2do-3er trimestre contraindicado)",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Administrar por la mañana (por poliuria)",
      "Monitorizar glucemia, HbA1c, función renal, electrolitos",
      "Educar sobre higiene genital (prevención de candidiasis)",
      "Mantener hidratación adecuada, especialmente en ancianos",
      "Vigilar signos de cetoacidosis euglucémica: náuseas, vómitos, dolor abdominal, fatiga (glucemia puede ser normal)",
      "Suspender antes de cirugía mayor (48-72h)",
      "Monitorizar PA (efecto diurético osmótico)"
    ],
    farmacocinetica: { absorcion: "Oral, rápida, no afectada por alimentos", distribucion: "Unión a proteínas 86%", metabolismo: "Hepático por glucuronidación (UGT1A3, 1A8, 1A9, 2B7)", eliminacion: "Renal 54%, fecal 41%", vidaMedia: "12.4 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u08", capituloId: "c0801",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipoglucemia (si combinado), deshidratación severa, hipotensión, cetoacidosis", manejo: "Rehidratación IV, corrección de glucemia, tratamiento de cetoacidosis si presente, soporte hemodinámico" }
  },
  // ── Neurología ──
  {
    id: "lacosamida",
    nombre: "Lacosamida",
    nombreGenerico: "Lacosamida",
    nombresComerciales: ["Vimpat"],
    familia: "Antiepilépticos",
    clasificacion: "Aminoácido funcionalizado (inactivación lenta de canales de sodio)",
    mecanismoAccion: "Promueve selectivamente la inactivación lenta de los canales de sodio voltaje-dependientes (a diferencia de otros antiepilépticos que actúan en inactivación rápida). También se une a CRMP-2 (proteína mediadora de respuesta a colapsina).",
    indicaciones: ["Epilepsia focal (crisis parciales) como monoterapia o adyuvante", "Crisis tónico-clónicas generalizadas primarias"],
    contraindicaciones: ["Bloqueo AV de 2do o 3er grado", "Hipersensibilidad"],
    efectosAdversos: ["Mareo", "Cefalea", "Diplopía", "Náuseas", "Ataxia", "Prolongación PR", "Ideación suicida (advertencia clase)"],
    interacciones: ["Otros prolongadores de PR (betabloqueantes, BCC, digoxina)", "Otros antiepilépticos (ajuste fino)", "No interacciones significativas con CYP"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "Inicio 50 mg/12h, titular cada semana 50mg/12h hasta 150-200 mg/12h. IV: misma dosis, infusión 15-60 min", pediatria: "≥4 años: inicio 1 mg/kg/12h, titular hasta 3-6 mg/kg/12h" },
    presentaciones: ["Comprimidos 50 mg", "Comprimidos 100 mg", "Comprimidos 150 mg", "Comprimidos 200 mg", "Solución oral 10 mg/mL", "Solución IV 10 mg/mL"],
    embarazo: "Categoría C - Riesgo de malformaciones",
    lactancia: "Compatible con precaución",
    cuidadosEnfermeria: [
      "Titular gradualmente para minimizar mareo",
      "ECG basal (descartar bloqueo AV o PR prolongado)",
      "Bioequivalencia oral-IV: permite switch directo",
      "Monitorizar signos de depresión/ideación suicida",
      "Puede tomarse con o sin alimentos",
      "No suspender abruptamente (riesgo de crisis rebote)"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad ~100%", distribucion: "Unión a proteínas <15%", metabolismo: "Hepático CYP2C19 (parcial)", eliminacion: "Renal 95% (40% sin cambios)", vidaMedia: "13 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u04", capituloId: "c0401",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mareo severo, náuseas, bloqueo cardíaco, convulsiones paradójicas", manejo: "No hay antídoto, hemodiálisis efectiva (elimina 50%), soporte cardiovascular, monitorización ECG" }
  },
  {
    id: "perampanel",
    nombre: "Perampanel",
    nombreGenerico: "Perampanel",
    nombresComerciales: ["Fycompa"],
    familia: "Antiepilépticos",
    clasificacion: "Antagonista no competitivo del receptor AMPA de glutamato",
    mecanismoAccion: "Primer antagonista selectivo no competitivo del receptor AMPA (ácido α-amino-3-hidroxi-5-metil-4-isoxazolpropiónico) de glutamato. Reduce la excitación neuronal mediada por glutamato en sinapsis postsinápticas.",
    indicaciones: ["Epilepsia focal como adyuvante", "Crisis tónico-clónicas generalizadas primarias como adyuvante"],
    contraindicaciones: ["Hipersensibilidad", "Insuficiencia hepática severa"],
    efectosAdversos: ["Mareo", "Somnolencia", "Irritabilidad/Agresividad", "Ataxia", "Fatiga", "Cefalea", "Caídas", "Ideación suicida", "Aumento de peso"],
    interacciones: ["Inductores enzimáticos (carbamazepina, fenitoína reducen niveles)", "Depresores del SNC", "Anticonceptivos hormonales (levonorgestrel puede reducirse con ≥12mg)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Inicio 2 mg/día al acostarse, titular cada 2 semanas, rango 4-12 mg/día. Con inductores enzimáticos: inicio 4 mg/día", pediatria: "≥4 años (focal) o ≥7 años (CTCG): misma dosificación" },
    presentaciones: ["Comprimidos 2 mg", "Comprimidos 4 mg", "Comprimidos 6 mg", "Comprimidos 8 mg", "Comprimidos 10 mg", "Comprimidos 12 mg", "Suspensión oral 0.5 mg/mL"],
    embarazo: "Categoría C",
    lactancia: "No recomendado (datos insuficientes)",
    cuidadosEnfermeria: [
      "Administrar al acostarse (somnolencia)",
      "Titular MUY lentamente (cada 2 semanas mínimo)",
      "Vigilar cambios de conducta: irritabilidad, agresividad, hostilidad",
      "Monitorizar ideación suicida",
      "No suspender abruptamente",
      "Interacción con inductores enzimáticos requiere dosis más altas"
    ],
    farmacocinetica: { absorcion: "Oral: rápida y completa, no afectada por alimentos", distribucion: "Unión a proteínas 95-96%", metabolismo: "Hepático CYP3A4/CYP3A5 y posterior glucuronidación", eliminacion: "Fecal 48%, renal 22%", vidaMedia: "105 horas (~4.4 días)" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u04", capituloId: "c0401",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Agitación, agresividad, nivel de consciencia disminuido, confusión", manejo: "Soporte vital, carbón activado si reciente (vida media muy larga ~105h), observación prolongada, no dializable" }
  },
  // ── Neumología ──
  {
    id: "omalizumab",
    nombre: "Omalizumab",
    nombreGenerico: "Omalizumab",
    nombresComerciales: ["Xolair"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-IgE (anticuerpo monoclonal humanizado)",
    mecanismoAccion: "Se une selectivamente a la IgE libre circulante, impidiendo su unión al receptor FcεRI de mastocitos y basófilos. Reduce la degranulación mediada por IgE y la cascada inflamatoria alérgica. Disminuye receptores FcεRI en basófilos.",
    indicaciones: ["Asma alérgica moderada-severa persistente", "Urticaria crónica espontánea", "Poliposis nasal", "Alergia alimentaria mediada por IgE (reducción de reacciones accidentales)"],
    contraindicaciones: ["Hipersensibilidad", "Parasitosis activa (IgE necesaria para defensa antiparasitaria)"],
    efectosAdversos: ["Reacción en sitio de inyección", "Cefalea", "Anafilaxia (0.1-0.2%, puede ser tardía)", "Artralgias", "Fatiga", "Eventos tromboembólicos (señal en post-comercialización)"],
    interacciones: ["Inmunosupresores (efecto aditivo teórico)", "No interacciones farmacocinéticas significativas"],
    viaAdministracion: ["subcutanea"],
    dosis: { adultos: "Asma: 150-375 mg SC cada 2-4 semanas según IgE basal y peso. Urticaria: 150-300 mg SC cada 4 semanas", pediatria: "Asma ≥6 años: según IgE y peso. Urticaria ≥12 años: 150-300 mg/4 sem" },
    presentaciones: ["Polvo para reconstitución 150 mg", "Jeringa prellenada 75 mg/0.5 mL", "Jeringa prellenada 150 mg/mL"],
    embarazo: "Categoría B",
    lactancia: "Probablemente compatible (IgG se excreta en leche)",
    cuidadosEnfermeria: [
      "Administrar SOLO en centro con capacidad de tratar anafilaxia",
      "Observar 2h post-inyección en primeras 3 dosis, luego 30 min",
      "Paciente debe portar autoinyector de epinefrina",
      "Reconstituir suavemente (15-20 min, no agitar)",
      "Refrigerar, no congelar",
      "No suspender corticoides inhalados abruptamente al iniciar",
      "La dosis se calcula según IgE total basal y peso corporal"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 62%, Tmax 7-8 días", distribucion: "Vd similar a IgG", metabolismo: "Degradación reticuloendotelial (como IgG)", eliminacion: "Hepática (reticuloendotelial)", vidaMedia: "26 días" },
    almacenamiento: "Refrigerar 2-8°C. No congelar. Proteger de la luz",
    unidadId: "u06", capituloId: "c0601",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No se han reportado sobredosis significativas", manejo: "Observación y soporte" }
  },
  {
    id: "mepolizumab",
    nombre: "Mepolizumab",
    nombreGenerico: "Mepolizumab",
    nombresComerciales: ["Nucala"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-IL-5 (anticuerpo monoclonal humanizado)",
    mecanismoAccion: "Se une a la IL-5 libre, impidiendo su unión al receptor alfa de IL-5 en eosinófilos. Reduce la producción, maduración, activación y supervivencia de eosinófilos. Reduce eosinófilos circulantes ~80%.",
    indicaciones: ["Asma eosinofílica severa (eosinófilos ≥300/μL)", "Granulomatosis eosinofílica con poliangeítis (GEPA)", "Síndrome hipereosinofílico", "Poliposis nasal con eosinofilia"],
    contraindicaciones: ["Hipersensibilidad", "No usar para crisis asmática aguda"],
    efectosAdversos: ["Cefalea", "Reacción en sitio de inyección", "Dolor de espalda", "Fatiga", "Reacciones de hipersensibilidad (raras)", "Herpes zóster"],
    interacciones: ["No interacciones significativas conocidas", "Vacunas vivas: precaución teórica"],
    viaAdministracion: ["subcutanea"],
    dosis: { adultos: "Asma: 100 mg SC cada 4 semanas. GEPA: 300 mg SC cada 4 semanas. HES: 300 mg SC cada 4 semanas", pediatria: "Asma ≥6 años: 40 mg (6-11 años) o 100 mg (≥12 años) SC cada 4 semanas" },
    presentaciones: ["Polvo para reconstitución 100 mg", "Jeringa prellenada 100 mg/mL", "Autoinyector 100 mg/mL"],
    embarazo: "Datos limitados, usar si beneficio supera riesgo",
    lactancia: "Probablemente compatible",
    cuidadosEnfermeria: [
      "Administrar SC en brazo, muslo o abdomen",
      "Puede autoadministrarse tras entrenamiento",
      "NO usar para alivio de crisis aguda",
      "No suspender corticoides inhalados/orales abruptamente al inicio",
      "Reducción gradual de corticoides orales si hay respuesta",
      "Monitorizar recuento de eosinófilos",
      "Vigilar reacciones de hipersensibilidad post-inyección"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 80%, Tmax 4-8 días", distribucion: "Vd 3.6 L", metabolismo: "Proteólisis (como IgG)", eliminacion: "Reticuloendotelial", vidaMedia: "16-22 días" },
    almacenamiento: "Refrigerar 2-8°C. No congelar",
    unidadId: "u06", capituloId: "c0601",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No hay datos de sobredosis. Teórica inmunosupresión excesiva", manejo: "Observación, soporte" }
  },
  // ── Reumatología ──
  {
    id: "tofacitinib",
    nombre: "Tofacitinib",
    nombreGenerico: "Tofacitinib",
    nombresComerciales: ["Xeljanz"],
    familia: "Inmunomoduladores",
    clasificacion: "Inhibidor de JAK (Janus kinasa) 1 y 3",
    mecanismoAccion: "Inhibe selectivamente JAK1 y JAK3 (y en menor grado JAK2), bloqueando la vía de señalización JAK-STAT. Reduce la señalización de múltiples citocinas proinflamatorias (IL-2, 4, 6, 7, 9, 15, 21, IFN).",
    indicaciones: ["Artritis reumatoide moderada-severa", "Artritis psoriásica", "Colitis ulcerosa moderada-severa", "Espondilitis anquilosante"],
    contraindicaciones: ["Infección activa grave", "Linfocitos <500/μL", "Neutrófilos <1000/μL", "Hemoglobina <9 g/dL", "Insuficiencia hepática severa", "Uso con biológicos o inmunosupresores potentes"],
    efectosAdversos: ["Infecciones (vías respiratorias superiores, ITU, herpes zóster)", "Aumento de colesterol LDL", "Linfopenia", "Neutropenia", "Elevación de transaminasas", "Eventos tromboembólicos", "Riesgo de malignidad (advertencia FDA)", "Eventos cardiovasculares mayores"],
    interacciones: ["Inhibidores CYP3A4 potentes (reducir dosis a 5mg/12h)", "Inductores CYP3A4 (reducen eficacia)", "Inmunosupresores biológicos (no combinar)", "Vacunas vivas (contraindicadas)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "AR/AP/EA: 5 mg cada 12h. CU inducción: 10 mg cada 12h x8 semanas, mantenimiento 5 mg cada 12h. Liberación prolongada: 11 mg cada 24h", pediatria: "AIJ ≥2 años: según peso" },
    presentaciones: ["Comprimidos 5 mg", "Comprimidos 10 mg", "Comprimidos XR 11 mg", "Solución oral 1 mg/mL"],
    embarazo: "Contraindicado",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Screening previo: TB latente, hepatitis B/C, hemograma completo, perfil lipídico, función hepática",
      "Vacunar contra herpes zóster ANTES de iniciar (vacuna recombinante, no viva)",
      "Hemograma a las 4-8 semanas de inicio, luego cada 3 meses",
      "Perfil lipídico a las 4-8 semanas",
      "Vigilar signos de infección, trombosis, malignidad",
      "No administrar con biológicos (MTX sí es compatible)",
      "Advertencia FDA box: mayor riesgo de MACE, malignidad y trombosis vs TNFi en >50 años con factores de riesgo CV"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 74%", distribucion: "Unión a proteínas 40%", metabolismo: "Hepático CYP3A4 (70%) y CYP2C19 (30%)", eliminacion: "Renal 30% sin cambios", vidaMedia: "3 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Inmunosupresión severa, infecciones oportunistas, citopenias", manejo: "Suspender, soporte antimicrobiano, factores estimulantes de colonias si neutropenia severa" }
  },
  {
    id: "ustekinumab",
    nombre: "Ustekinumab",
    nombreGenerico: "Ustekinumab",
    nombresComerciales: ["Stelara"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-IL-12/23 (anticuerpo monoclonal humano)",
    mecanismoAccion: "Se une a la subunidad p40 compartida por IL-12 e IL-23, bloqueando su unión a receptores en células inmunes. Inhibe la diferenciación y activación de células Th1 (IL-12) y Th17 (IL-23), claves en autoinmunidad.",
    indicaciones: ["Psoriasis en placas moderada-severa", "Artritis psoriásica", "Enfermedad de Crohn moderada-severa", "Colitis ulcerosa moderada-severa"],
    contraindicaciones: ["Infección activa grave", "Hipersensibilidad", "TB activa no tratada"],
    efectosAdversos: ["Infecciones respiratorias", "Cefalea", "Fatiga", "Reacción en sitio de inyección", "Artralgia", "Riesgo teórico de malignidad (bajo)", "RPLS (muy raro)"],
    interacciones: ["Vacunas vivas (contraindicadas)", "Inmunosupresores (precaución)", "Puede normalizar CYP450 previamente suprimido por inflamación"],
    viaAdministracion: ["subcutanea", "intravenosa"],
    dosis: { adultos: "Psoriasis: ≤100kg: 45mg semana 0, 4, luego cada 12 sem. >100kg: 90mg. Crohn/CU: inducción IV peso-basada, luego 90mg SC cada 8 semanas", pediatria: "Psoriasis ≥6 años según peso" },
    presentaciones: ["Jeringa prellenada 45 mg/0.5 mL", "Jeringa prellenada 90 mg/mL", "Vial IV 130 mg/26 mL"],
    embarazo: "Datos limitados, usar si beneficio supera riesgo",
    lactancia: "Probablemente compatible (IgG en leche en bajas concentraciones)",
    cuidadosEnfermeria: [
      "Screening TB, hepatitis B/C antes de iniciar",
      "SC: administrar en muslo, abdomen o brazo",
      "IV (inducción Crohn/CU): calcular dosis según peso, infundir en ≥1h",
      "Esquema de dosificación largo: cada 8-12 semanas (alta adherencia)",
      "No administrar vacunas vivas",
      "Vigilar signos de infección y reacciones de hipersensibilidad",
      "Mínimo monitoreo de laboratorio requerido (ventaja sobre otros biológicos)"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 57%, Tmax 7-13 días", distribucion: "Vd 4.6-5.6 L", metabolismo: "Proteólisis (como IgG)", eliminacion: "Reticuloendotelial", vidaMedia: "15-32 días" },
    almacenamiento: "Refrigerar 2-8°C. No congelar. Proteger de la luz",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No reportados; dosis hasta 6 mg/kg toleradas", manejo: "Observación, soporte" }
  },
  // ── Gastroenterología ──
  {
    id: "vedolizumab",
    nombre: "Vedolizumab",
    nombreGenerico: "Vedolizumab",
    nombresComerciales: ["Entyvio"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-integrina α4β7 (anticuerpo monoclonal humanizado, selectivo intestinal)",
    mecanismoAccion: "Se une específicamente a la integrina α4β7 en linfocitos T, bloqueando su interacción con MAdCAM-1 en el endotelio intestinal. Inhibe selectivamente la migración de linfocitos al tejido gastrointestinal sin afectar inmunidad sistémica.",
    indicaciones: ["Colitis ulcerosa moderada-severa", "Enfermedad de Crohn moderada-severa", "Pouchitis (uso off-label)"],
    contraindicaciones: ["Hipersensibilidad", "Infección activa severa", "LMP (leucoencefalopatía multifocal progresiva) previa"],
    efectosAdversos: ["Nasofaringitis", "Cefalea", "Artralgia", "Náuseas", "Infecciones respiratorias", "Reacciones a la infusión", "Fatiga"],
    interacciones: ["Natalizumab (no usar secuencialmente sin washout)", "Inmunosupresores (uso combinado aceptado)", "Vacunas vivas (precaución)"],
    viaAdministracion: ["intravenosa", "subcutanea"],
    dosis: { adultos: "IV inducción: 300 mg semanas 0, 2 y 6, luego cada 8 semanas. SC mantenimiento: 108 mg cada 2 semanas tras inducción IV", pediatria: "No aprobado en <18 años (en estudio)" },
    presentaciones: ["Polvo para infusión IV 300 mg", "Jeringa prellenada SC 108 mg/0.68 mL"],
    embarazo: "Datos limitados, usar si beneficio supera riesgo",
    lactancia: "Probablemente compatible",
    cuidadosEnfermeria: [
      "IV: reconstituir suavemente, infundir en 30 minutos",
      "Observar durante y 1-2h post-infusión (reacciones)",
      "Screening TB antes de iniciar",
      "Selectividad intestinal: menor riesgo de infecciones sistémicas que anti-TNF",
      "Respuesta puede tardar hasta 14 semanas (no abandonar prematuramente)",
      "SC: autoadministración tras entrenamiento",
      "Monitorizar respuesta clínica y calprotectina fecal"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad ~75%", distribucion: "Vd 5 L", metabolismo: "Proteólisis (como IgG)", eliminacion: "Reticuloendotelial", vidaMedia: "25 días" },
    almacenamiento: "Refrigerar 2-8°C. No congelar",
    unidadId: "u07", capituloId: "c0701",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No se han reportado sobredosis", manejo: "Observación y soporte" }
  },
  // ── Urgencias/Cuidados críticos ──
  {
    id: "sugammadex",
    nombre: "Sugammadex",
    nombreGenerico: "Sugammadex sódico",
    nombresComerciales: ["Bridion"],
    familia: "Antídotos",
    clasificacion: "Ciclodextrina modificada (agente de reversión de bloqueo neuromuscular)",
    mecanismoAccion: "γ-ciclodextrina modificada que encapsula selectivamente rocuronio y vecuronio formando un complejo 1:1 estable e inactivo. Revierte el bloqueo neuromuscular por secuestro directo del relajante, no por inhibición de acetilcolinesterasa.",
    indicaciones: ["Reversión del bloqueo neuromuscular por rocuronio", "Reversión del bloqueo por vecuronio", "Reversión de emergencia (can't intubate, can't ventilate) tras rocuronio"],
    contraindicaciones: ["Hipersensibilidad"],
    efectosAdversos: ["Disgeusia", "Náuseas", "Bradicardia (rara, puede ser severa)", "Broncoespasmo (raro)", "Anafilaxia (rara, 0.3%)", "Prolongación del TTPa/TP transitoria"],
    interacciones: ["Anticonceptivos hormonales (encapsula progesterona: equivale a olvidar 1 dosis, usar barrera 7 días)", "Toremifeno, ácido fusídico (competición por encapsulación)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Bloqueo moderado (TOF 2): 2 mg/kg IV. Bloqueo profundo (PTC 1-2): 4 mg/kg IV. Reversión inmediata (3 min post-rocuronio): 16 mg/kg IV", pediatria: "≥2 años: mismas dosis que adultos por kg" },
    presentaciones: ["Solución inyectable 100 mg/mL (2 mL)", "Solución inyectable 100 mg/mL (5 mL)"],
    embarazo: "Usar solo si necesario (datos limitados)",
    lactancia: "Compatible (molécula grande, mínima excreción)",
    cuidadosEnfermeria: [
      "Administrar como bolo IV en 10 segundos",
      "Monitorizar con TOF (Train of Four) antes y después",
      "Verificar recuperación completa TOF ratio ≥0.9",
      "Vigilar recurarización (rara, especialmente si dosis insuficiente)",
      "Monitorizar bradicardia post-administración (tener atropina disponible)",
      "Informar a pacientes mujeres sobre interacción con anticonceptivos",
      "No mezclar con otros medicamentos en la misma jeringa",
      "Efectivo en 2-3 min para bloqueo moderado, 3-5 min para profundo"
    ],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Vd 11-14 L, unión a proteínas mínima", metabolismo: "No se metaboliza", eliminacion: "Renal 95% sin cambios (como complejo sugammadex-rocuronio)", vidaMedia: "2 horas (prolongada en IR severa)" },
    almacenamiento: "Temperatura ambiente hasta 30°C. No refrigerar ni congelar",
    unidadId: "u02", capituloId: "c0202",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Bradicardia, hipersensibilidad. Dosis hasta 96 mg/kg toleradas en estudios", manejo: "Atropina si bradicardia, soporte para anafilaxia si ocurre" }
  }
];

// Agregar fármacos con deduplicación
let added = 0;
for (const d of newDrugs) {
  if (existingIds.has(d.id)) continue;
  d.searchText = mkSearch(d);
  drugs.push(d);
  existingIds.add(d.id);
  // Agregar a categorías
  for (const u of cats.unidades) {
    if (u.id === d.unidadId) {
      const cap = u.capitulos.find(c => c.id === d.capituloId);
      if (cap && !cap.drugIds.includes(d.id)) cap.drugIds.push(d.id);
    }
  }
  added++;
}

fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log(`Added: ${added}. Total drugs: ${drugs.length}`);
