const fs = require('fs');
const path = require('path');

const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath = path.join(__dirname, '..', 'src', 'data', 'categories.json');
const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats = JSON.parse(fs.readFileSync(catsPath, 'utf8'));

const existingIds = new Set(drugs.map(d => d.id));

const newDrugs = [
  // ============================================================
  // CARDIOVASCULAR
  // ============================================================
  {
    id: 'trandolapril', nombre: 'Trandolapril', nombreGenerico: 'Trandolapril',
    nombresComerciales: ['Gopten', 'Odrik'],
    familia: 'IECA', clasificacion: 'IECA de acción prolongada',
    mecanismoAccion: 'Profármaco que se convierte en trandolaprilato, inhibiendo la ECA y reduciendo la formación de angiotensina II.',
    indicaciones: ['Hipertensión arterial', 'Insuficiencia cardíaca post-IAM', 'Disfunción ventricular izquierda post-IAM'],
    contraindicaciones: ['Hipersensibilidad a IECA', 'Angioedema previo', 'Embarazo', 'Estenosis bilateral de arterias renales'],
    efectosAdversos: ['Tos seca', 'Hipotensión', 'Hiperpotasemia', 'Mareo', 'Angioedema (raro)'],
    interacciones: ['AINEs: reducen efecto antihipertensivo', 'Suplementos de potasio: riesgo hiperpotasemia', 'Litio: aumento de niveles'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '0.5-4 mg/día en dosis única', ajusteRenal: 'ClCr <30: iniciar 0.5 mg/día' },
    presentaciones: ['Cápsulas 0.5 mg', 'Cápsulas 2 mg', 'Cápsulas 4 mg'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Controlar PA antes de administrar', 'Vigilar potasio sérico', 'Educar sobre tos seca como efecto esperado'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Inhibidores de la enzima convertidora de angiotensina (IECA)',
  },
  {
    id: 'manidipino', nombre: 'Manidipino', nombreGenerico: 'Manidipino',
    nombresComerciales: ['Artedil', 'Manyper'],
    familia: 'Calcioantagonistas dihidropiridínicos', clasificacion: 'Calcioantagonista dihidropiridínico de tercera generación',
    mecanismoAccion: 'Bloquea canales de calcio tipo L con selectividad vascular, produciendo vasodilatación arteriolar con mínimo efecto inotrópico negativo.',
    indicaciones: ['Hipertensión arterial esencial'],
    contraindicaciones: ['Estenosis aórtica severa', 'Shock cardiogénico', 'Angina inestable', 'IAM reciente (<1 mes)'],
    efectosAdversos: ['Edema maleolar', 'Cefalea', 'Rubor facial', 'Palpitaciones', 'Mareo'],
    interacciones: ['CYP3A4 inhibidores: aumentan niveles', 'Zumo de pomelo: aumenta biodisponibilidad', 'Simvastatina: ajustar dosis'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '10-20 mg/día después del desayuno' },
    presentaciones: ['Comprimidos 10 mg', 'Comprimidos 20 mg'],
    embarazo: 'C', lactancia: 'No recomendado',
    cuidadosEnfermeria: ['Administrar después del desayuno', 'Controlar edema periférico', 'Monitorizar PA'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Antagonistas del calcio dihidropiridínicos',
  },
  {
    id: 'cilazapril', nombre: 'Cilazapril', nombreGenerico: 'Cilazapril',
    nombresComerciales: ['Inhibace'],
    familia: 'IECA', clasificacion: 'IECA de acción prolongada',
    mecanismoAccion: 'Profármaco que se convierte en cilazaprilato, inhibiendo la enzima convertidora de angiotensina.',
    indicaciones: ['Hipertensión arterial', 'Insuficiencia cardíaca crónica'],
    contraindicaciones: ['Angioedema por IECA previo', 'Embarazo', 'Estenosis bilateral renal'],
    efectosAdversos: ['Tos seca', 'Hipotensión', 'Cefalea', 'Fatiga', 'Hiperpotasemia'],
    interacciones: ['Diuréticos ahorradores de K: hiperpotasemia', 'AINEs: reducen eficacia', 'Litio: toxicidad'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'HTA: 1-5 mg/día. IC: 0.5-2.5 mg/día', ajusteRenal: 'ClCr 10-40: 0.5 mg/día inicio' },
    presentaciones: ['Comprimidos 0.5 mg', 'Comprimidos 1 mg', 'Comprimidos 2.5 mg', 'Comprimidos 5 mg'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Control de PA y K sérico', 'Precaución en primera dosis (hipotensión)'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Inhibidores de la enzima convertidora de angiotensina (IECA)',
  },

  // ============================================================
  // UROLOGÍA
  // ============================================================
  {
    id: 'dutasterida', nombre: 'Dutasterida', nombreGenerico: 'Dutasterida',
    nombresComerciales: ['Avodart', 'Duagen'],
    familia: 'Inhibidores de 5-alfa-reductasa', clasificacion: 'Inhibidor dual de 5-alfa-reductasa tipo 1 y 2',
    mecanismoAccion: 'Inhibe ambas isoformas (tipo 1 y 2) de la 5-alfa-reductasa, bloqueando la conversión de testosterona a dihidrotestosterona (DHT). Reduce DHT sérica >90%.',
    indicaciones: ['Hiperplasia benigna de próstata (HBP)', 'Reducción de riesgo de retención urinaria aguda', 'HBP + alopecia androgenética (uso off-label)'],
    contraindicaciones: ['Mujeres (especialmente embarazadas)', 'Niños', 'Hipersensibilidad', 'Insuficiencia hepática severa'],
    efectosAdversos: ['Disfunción eréctil', 'Disminución de libido', 'Ginecomastia', 'Trastornos de eyaculación', 'Reduce PSA ~50% (ajustar interpretación)'],
    interacciones: ['Inhibidores CYP3A4: posible aumento de niveles', 'PSA: debe multiplicarse x2 para interpretación oncológica'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '0.5 mg/día (efecto máximo a 3-6 meses)' },
    presentaciones: ['Cápsulas blandas 0.5 mg'],
    embarazo: 'X', lactancia: 'N/A (uso masculino)',
    cuidadosEnfermeria: ['No manipular cápsulas (absorción transdérmica)', 'Las mujeres embarazadas NO deben tocar cápsulas rotas', 'Efecto terapéutico completo a 6 meses', 'Recordar que reduce PSA: multiplicar x2 en screening prostático', 'No donar sangre hasta 6 meses tras suspender'],
    unidadId: 'u07', capituloId: 'c07_09',
    grupoTerapeutico: 'Sistema Genitourinario y Reproductor', grupoFarmacologico: 'Fármacos prostáticos y para disfunción eréctil',
  },
  {
    id: 'terazosina', nombre: 'Terazosina', nombreGenerico: 'Terazosina',
    nombresComerciales: ['Hytrin', 'Deflox', 'Magnurol'],
    familia: 'Alfa-bloqueantes', clasificacion: 'Antagonista alfa-1 adrenérgico no selectivo',
    mecanismoAccion: 'Bloquea receptores alfa-1 adrenérgicos en próstata, cuello vesical y vasos, relajando músculo liso.',
    indicaciones: ['HBP (síntomas obstructivos)', 'Hipertensión arterial'],
    contraindicaciones: ['Hipotensión ortostática severa', 'Síncope previo con alfa-bloqueantes'],
    efectosAdversos: ['Hipotensión ortostática (primera dosis)', 'Mareo', 'Somnolencia', 'Congestión nasal', 'Astenia', 'Síndrome del iris fláccido intraoperatorio'],
    interacciones: ['Otros antihipertensivos: potenciación hipotensora', 'Inhibidores de PDE5: hipotensión severa', 'Verapamilo: aumenta niveles'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Iniciar 1 mg al acostarse, titular hasta 5-10 mg/día' },
    presentaciones: ['Comprimidos 2 mg', 'Comprimidos 5 mg'],
    embarazo: 'C', lactancia: 'No datos suficientes',
    cuidadosEnfermeria: ['Primera dosis al acostarse (riesgo hipotensión)', 'Titular gradualmente', 'Advertir sobre cambios posturales lentos', 'Informar al oftalmólogo si cirugía de cataratas'],
    unidadId: 'u07', capituloId: 'c07_09',
    grupoTerapeutico: 'Sistema Genitourinario y Reproductor', grupoFarmacologico: 'Fármacos prostáticos y para disfunción eréctil',
  },

  // ============================================================
  // OFTALMOLOGÍA
  // ============================================================
  {
    id: 'brimonidina', nombre: 'Brimonidina', nombreGenerico: 'Brimonidina tartrato',
    nombresComerciales: ['Alphagan', 'Brimopress'],
    familia: 'Agonistas alfa-2 adrenérgicos oftálmicos', clasificacion: 'Agonista alfa-2 selectivo para glaucoma',
    mecanismoAccion: 'Agonista alfa-2 selectivo que reduce la producción de humor acuoso y aumenta el flujo uveoescleral, disminuyendo la presión intraocular.',
    indicaciones: ['Glaucoma de ángulo abierto', 'Hipertensión ocular', 'Prevención de picos de PIO post-láser'],
    contraindicaciones: ['Neonatos y lactantes', 'Uso de IMAO', 'Hipersensibilidad'],
    efectosAdversos: ['Sequedad ocular', 'Hiperemia conjuntival', 'Visión borrosa', 'Somnolencia', 'Dermatitis alérgica palpebral', 'Sabor metálico'],
    interacciones: ['IMAO: contraindicados', 'Depresores del SNC: potenciación', 'Antihipertensivos: efecto aditivo'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1 gota en ojo afectado cada 8-12h', pediatrico: 'Contraindicado en <2 años. 2-17 años: usar con precaución' },
    presentaciones: ['Colirio 0.15%', 'Colirio 0.2%'],
    embarazo: 'B', lactancia: 'Precaución',
    cuidadosEnfermeria: ['Enseñar técnica correcta de instilación', 'Presionar punto lagrimal 1-2 min para reducir absorción sistémica', 'Esperar 5 min entre colirios diferentes', 'Retirar lentes de contacto antes'],
    unidadId: 'u09', capituloId: 'c09_08',
    grupoTerapeutico: 'Dermatología', grupoFarmacologico: 'Antisépticos y cicatrizantes',
  },
  {
    id: 'dorzolamida', nombre: 'Dorzolamida', nombreGenerico: 'Dorzolamida clorhidrato',
    nombresComerciales: ['Trusopt', 'Cosopt (con timolol)'],
    familia: 'Inhibidores de anhidrasa carbónica tópicos', clasificacion: 'Inhibidor de anhidrasa carbónica II oftálmico',
    mecanismoAccion: 'Inhibe la anhidrasa carbónica II en procesos ciliares, reduciendo la secreción de humor acuoso y la presión intraocular.',
    indicaciones: ['Glaucoma de ángulo abierto', 'Hipertensión ocular', 'Glaucoma secundario'],
    contraindicaciones: ['Alergia a sulfonamidas', 'Insuficiencia renal severa'],
    efectosAdversos: ['Sabor amargo', 'Quemazón ocular transitoria', 'Visión borrosa', 'Queratitis punctata', 'Reacciones alérgicas locales'],
    interacciones: ['Acetazolamida oral: efecto aditivo (riesgo acidosis)', 'Otros colirios: esperar 5 min'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1 gota en ojo afectado cada 8h (monoterapia) o cada 12h (combinado)' },
    presentaciones: ['Colirio 2%', 'Colirio 2% + timolol 0.5% (Cosopt)'],
    embarazo: 'C', lactancia: 'Precaución',
    cuidadosEnfermeria: ['Advertir sobre sabor amargo transitorio', 'No usar con lentes de contacto blandas', 'Precaución si alergia a sulfas'],
    unidadId: 'u09', capituloId: 'c09_08',
    grupoTerapeutico: 'Dermatología', grupoFarmacologico: 'Antisépticos y cicatrizantes',
  },
  {
    id: 'tropicamida', nombre: 'Tropicamida', nombreGenerico: 'Tropicamida',
    nombresComerciales: ['Mydriacyl', 'Tropicol'],
    familia: 'Midriáticos y ciclopléjicos', clasificacion: 'Anticolinérgico oftálmico de acción corta',
    mecanismoAccion: 'Bloquea receptores muscarínicos del músculo esfínter del iris y del cuerpo ciliar, produciendo midriasis y cicloplejía.',
    indicaciones: ['Exploración de fondo de ojo', 'Refracción ciclopléjica', 'Pre/postoperatorio oftálmico', 'Uveítis anterior (adyuvante)'],
    contraindicaciones: ['Glaucoma de ángulo cerrado', 'Hipersensibilidad'],
    efectosAdversos: ['Fotofobia', 'Visión borrosa (2-6h)', 'Aumento transitorio de PIO', 'Sequedad ocular', 'Efectos sistémicos raros (taquicardia, confusión en niños)'],
    interacciones: ['Pilocarpina: antagonismo', 'Otros anticolinérgicos: potenciación'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1-2 gotas, repetir en 5 min si necesario. Efecto en 20-30 min', pediatrico: '1 gota de concentración 0.5%' },
    presentaciones: ['Colirio 0.5%', 'Colirio 1%'],
    embarazo: 'C', lactancia: 'Compatible con precaución',
    cuidadosEnfermeria: ['Advertir sobre fotofobia 4-6h', 'No conducir hasta resolución', 'Comprimir punto lagrimal en niños', 'Usar concentración 0.5% en niños'],
    unidadId: 'u09', capituloId: 'c09_08',
    grupoTerapeutico: 'Dermatología', grupoFarmacologico: 'Antisépticos y cicatrizantes',
  },
  {
    id: 'ciclopentolato', nombre: 'Ciclopentolato', nombreGenerico: 'Ciclopentolato clorhidrato',
    nombresComerciales: ['Cicloplejico', 'Cyclogyl'],
    familia: 'Midriáticos y ciclopléjicos', clasificacion: 'Anticolinérgico oftálmico ciclopléjico',
    mecanismoAccion: 'Antagonista muscarínico que produce midriasis y cicloplejía más intensa y prolongada que tropicamida.',
    indicaciones: ['Refracción ciclopléjica (especialmente en niños)', 'Exploración fondo de ojo', 'Uveítis anterior'],
    contraindicaciones: ['Glaucoma de ángulo cerrado', 'Hipersensibilidad a atropínicos'],
    efectosAdversos: ['Fotofobia prolongada (12-24h)', 'Visión borrosa', 'Sequedad ocular', 'En niños: toxicidad SNC (ataxia, confusión, convulsiones)', 'Taquicardia'],
    interacciones: ['Pilocarpina: antagonismo', 'Otros anticolinérgicos: potenciación sistémica'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1 gota, repetir en 5-10 min. Efecto ciclopléjico máximo a 30-60 min', pediatrico: '1 gota 0.5-1%, evitar en prematuros' },
    presentaciones: ['Colirio 0.5%', 'Colirio 1%'],
    embarazo: 'C', lactancia: 'Precaución',
    cuidadosEnfermeria: ['Efecto dura 12-24h (más que tropicamida)', 'Comprimir punto lagrimal en niños pequeños', 'Vigilar signos de toxicidad SNC en niños', 'No conducir hasta resolución'],
    unidadId: 'u09', capituloId: 'c09_08',
    grupoTerapeutico: 'Dermatología', grupoFarmacologico: 'Antisépticos y cicatrizantes',
  },
  {
    id: 'atropina_oftalmica', nombre: 'Atropina (Oftálmica)', nombreGenerico: 'Atropina sulfato oftálmica',
    nombresComerciales: ['Atropina Colirio', 'Atropina Cusi'],
    familia: 'Midriáticos y ciclopléjicos', clasificacion: 'Anticolinérgico oftálmico de acción prolongada',
    mecanismoAccion: 'Antagonista muscarínico no selectivo que produce midriasis y cicloplejía máximas y prolongadas (7-14 días).',
    indicaciones: ['Uveítis anterior (prevención de sinequias)', 'Ambliopía (penalización farmacológica)', 'Exploración de fondo de ojo en niños', 'Control de miopía progresiva (dosis baja)'],
    contraindicaciones: ['Glaucoma de ángulo cerrado', 'Sinequia posterior adherida'],
    efectosAdversos: ['Fotofobia prolongada (7-14 días)', 'Visión borrosa prolongada', 'Toxicidad sistémica (especialmente en niños): fiebre, taquicardia, confusión, retención urinaria'],
    interacciones: ['Pilocarpina: antagonismo', 'Anticolinérgicos sistémicos: potenciación'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: 'Uveítis: 1 gota 1% cada 6-8h. Miopía: 1 gota 0.01-0.05% nocturna', pediatrico: 'Ambliopía: 1 gota 1% en ojo sano cada mañana. Miopía: 0.01%' },
    presentaciones: ['Colirio 0.5%', 'Colirio 1%'],
    embarazo: 'C', lactancia: 'Precaución',
    cuidadosEnfermeria: ['Efecto dura 1-2 semanas: informar al paciente', 'Ocluir punto lagrimal en niños (prevenir toxicidad sistémica)', 'Usar gafas de sol durante efecto', 'En ambliopía: educar a padres sobre penalización'],
    unidadId: 'u09', capituloId: 'c09_08',
    grupoTerapeutico: 'Dermatología', grupoFarmacologico: 'Antisépticos y cicatrizantes',
  },

  // ============================================================
  // DIGESTIVO
  // ============================================================
  {
    id: 'alverino', nombre: 'Alverina', nombreGenerico: 'Alverina citrato',
    nombresComerciales: ['Spasmonal', 'Meteospasmyl (con simeticona)'],
    familia: 'Antiespasmódicos', clasificacion: 'Espasmolítico musculotrópico del tracto GI',
    mecanismoAccion: 'Relajante directo del músculo liso gastrointestinal sin efecto anticolinérgico. Modula la hipersensibilidad visceral.',
    indicaciones: ['Síndrome de intestino irritable', 'Dolor abdominal tipo cólico', 'Dismenorrea'],
    contraindicaciones: ['Íleo paralítico', 'Hipersensibilidad', 'Niños <12 años'],
    efectosAdversos: ['Cefalea', 'Mareo', 'Náuseas', 'Reacciones alérgicas cutáneas'],
    interacciones: ['Escasas interacciones conocidas'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '60-120 mg cada 8h antes de comidas' },
    presentaciones: ['Cápsulas 60 mg', 'Cápsulas 60 mg + simeticona 300 mg'],
    embarazo: 'B', lactancia: 'Compatible',
    cuidadosEnfermeria: ['Administrar 20-30 min antes de comidas', 'Evaluar patrón de dolor abdominal'],
    unidadId: 'u05', capituloId: 'c05_08',
    grupoTerapeutico: 'Aparato Digestivo', grupoFarmacologico: 'Procinéticos y espasmolíticos',
  },
  {
    id: 'lubiprostone', nombre: 'Lubiprostona', nombreGenerico: 'Lubiprostona',
    nombresComerciales: ['Amitiza'],
    familia: 'Activadores de canales de cloro', clasificacion: 'Activador de canales de cloro tipo 2 (ClC-2)',
    mecanismoAccion: 'Activa canales de cloro tipo 2 en la membrana apical del epitelio intestinal, aumentando la secreción de fluido intestinal y mejorando el tránsito.',
    indicaciones: ['Estreñimiento crónico idiopático', 'Síndrome de intestino irritable con estreñimiento', 'Estreñimiento inducido por opioides'],
    contraindicaciones: ['Obstrucción intestinal mecánica', 'Embarazo', 'Hipersensibilidad'],
    efectosAdversos: ['Náuseas (30%)', 'Diarrea', 'Cefalea', 'Distensión abdominal', 'Disnea'],
    interacciones: ['No interacciones significativas conocidas via CYP'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Estreñimiento crónico: 24 mcg cada 12h con comida. SII-E: 8 mcg cada 12h' },
    presentaciones: ['Cápsulas 8 mcg', 'Cápsulas 24 mcg'],
    embarazo: 'X', lactancia: 'No datos',
    cuidadosEnfermeria: ['Administrar con comida para reducir náuseas', 'Evaluar efectividad (frecuencia deposiciones)', 'Suspender si diarrea severa'],
    unidadId: 'u05', capituloId: 'c05_05',
    grupoTerapeutico: 'Aparato Digestivo', grupoFarmacologico: 'Laxantes y antidiarreicos',
  },
  {
    id: 'pancrealipasa', nombre: 'Pancrealipasa', nombreGenerico: 'Pancrealipasa (pancreolipasa)',
    nombresComerciales: ['Creon', 'Kreon', 'Zenpep'],
    familia: 'Enzimas pancreáticas', clasificacion: 'Suplemento enzimático pancreático con lipasa, proteasa y amilasa',
    mecanismoAccion: 'Aporta enzimas pancreáticas exógenas (lipasa, proteasa, amilasa) que facilitan la digestión de grasas, proteínas y carbohidratos en insuficiencia pancreática.',
    indicaciones: ['Insuficiencia pancreática exocrina', 'Fibrosis quística', 'Pancreatitis crónica', 'Post-pancreatectomía', 'Post-gastrectomía (Whipple)'],
    contraindicaciones: ['Pancreatitis aguda (fase inicial)', 'Hipersensibilidad a proteínas porcinas'],
    efectosAdversos: ['Dolor abdominal', 'Náuseas', 'Diarrea', 'Colonopatía fibrosante (dosis >10.000 U lipasa/kg/día)', 'Hiperuricemia'],
    interacciones: ['Antiácidos con Ca/Mg: pueden reducir eficacia', 'Acarbosa: posible reducción de efecto'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '25.000-75.000 U de lipasa por comida principal; 10.000-25.000 U por snack', pediatrico: '<4 años: 1.000 U lipasa/kg/comida. >4 años: 500 U lipasa/kg/comida. Máx: 10.000 U/kg/día' },
    presentaciones: ['Cápsulas 10.000 U lipasa', 'Cápsulas 25.000 U lipasa', 'Cápsulas 40.000 U lipasa'],
    embarazo: 'C', lactancia: 'Compatible',
    cuidadosEnfermeria: ['Administrar con cada comida y snack', 'No triturar cápsulas (cubierta entérica)', 'Se pueden abrir y mezclar con alimento ácido (puré de manzana)', 'Monitorizar peso y esteatorrea', 'No exceder 10.000 U lipasa/kg/día (riesgo colonopatía)'],
    unidadId: 'u05', capituloId: 'c05_07',
    grupoTerapeutico: 'Aparato Digestivo', grupoFarmacologico: 'Fármacos pancreáticos y biliares',
  },

  // ============================================================
  // ENDOCRINO
  // ============================================================
  {
    id: 'alfacalcidol', nombre: 'Alfacalcidol', nombreGenerico: 'Alfacalcidol (1-alfa-hidroxicolecalciferol)',
    nombresComerciales: ['One-Alpha', 'Etalpha'],
    familia: 'Análogos de vitamina D', clasificacion: 'Análogo activo de vitamina D3 (1-alfa-hidroxilado)',
    mecanismoAccion: 'Análogo de vitamina D que requiere solo 25-hidroxilación hepática (no renal), útil en insuficiencia renal. Aumenta absorción intestinal de calcio y fósforo.',
    indicaciones: ['Osteodistrofia renal', 'Hipoparatiroidismo', 'Osteomalacia', 'Raquitismo dependiente de vitamina D', 'Osteoporosis con déficit de vitamina D'],
    contraindicaciones: ['Hipercalcemia', 'Hiperfosfatemia', 'Hipervitaminosis D'],
    efectosAdversos: ['Hipercalcemia', 'Hipercalciuria', 'Nefrocalcinosis', 'Náuseas', 'Poliuria', 'Calcificaciones ectópicas'],
    interacciones: ['Tiazidas: aumentan riesgo hipercalcemia', 'Digitálicos: la hipercalcemia potencia toxicidad', 'Anticonvulsivantes: aumentan metabolismo'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '0.25-1 mcg/día (ajustar según calcemia)', pediatrico: '<20 kg: 0.05 mcg/kg/día' },
    presentaciones: ['Cápsulas 0.25 mcg', 'Cápsulas 1 mcg', 'Gotas orales 2 mcg/mL'],
    embarazo: 'C', lactancia: 'Precaución (pasa a leche)',
    cuidadosEnfermeria: ['Monitorizar calcemia y fosfatemia semanalmente al inicio', 'Educar sobre síntomas de hipercalcemia (poliuria, sed, náuseas)', 'Asegurar ingesta adecuada de calcio pero no excesiva'],
    unidadId: 'u06', capituloId: 'c06_07',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Reguladores del metabolismo óseo-mineral',
  },
  {
    id: 'calcifediol', nombre: 'Calcifediol', nombreGenerico: 'Calcifediol (25-hidroxicolecalciferol)',
    nombresComerciales: ['Hidroferol', 'Rayaldee'],
    familia: 'Análogos de vitamina D', clasificacion: 'Metabolito intermedio de vitamina D3 (25-OH-D3)',
    mecanismoAccion: 'Forma 25-hidroxilada de vitamina D3 que solo requiere 1-alfa-hidroxilación renal para activarse. Acción más rápida que colecalciferol.',
    indicaciones: ['Déficit de vitamina D', 'Osteomalacia', 'Hipoparatiroidismo', 'Insuficiencia renal crónica (estadios 3-4)', 'Malabsorción de vitamina D'],
    contraindicaciones: ['Hipercalcemia', 'Hipervitaminosis D'],
    efectosAdversos: ['Hipercalcemia', 'Hipercalciuria', 'Náuseas', 'Estreñimiento'],
    interacciones: ['Tiazidas: riesgo hipercalcemia', 'Colestiramina: reduce absorción'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Déficit: 0.266 mg (16.000 UI) cada 15-30 días. Ajustar según niveles de 25-OH-D' },
    presentaciones: ['Ampollas bebibles 0.266 mg (16.000 UI)', 'Gotas orales'],
    embarazo: 'C', lactancia: 'Compatible con precaución',
    cuidadosEnfermeria: ['Monitorizar 25-OH vitamina D sérica', 'Vigilar calcemia', 'Administración quincenal o mensual mejora adherencia'],
    unidadId: 'u06', capituloId: 'c06_07',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Reguladores del metabolismo óseo-mineral',
  },

  // ============================================================
  // RESPIRATORIO
  // ============================================================
  {
    id: 'alfa_dornasa', nombre: 'Dornasa Alfa', nombreGenerico: 'Dornasa alfa (ADNasa recombinante)',
    nombresComerciales: ['Pulmozyme'],
    familia: 'Mucolíticos enzimáticos', clasificacion: 'ADNasa recombinante humana mucolítica',
    mecanismoAccion: 'Enzima recombinante que hidroliza el ADN extracelular presente en las secreciones purulentas, reduciendo la viscosidad del esputo en fibrosis quística.',
    indicaciones: ['Fibrosis quística (FQ) con CVF >40%', 'Mejora de función pulmonar en FQ'],
    contraindicaciones: ['Hipersensibilidad a dornasa alfa o productos de células CHO'],
    efectosAdversos: ['Disfonía', 'Faringitis', 'Rash', 'Dolor torácico', 'Conjuntivitis'],
    interacciones: ['No mezclar con otros fármacos en nebulizador'],
    viaAdministracion: ['inhalatoria'],
    dosis: { adulto: '2.5 mg (1 ampolla) nebulizada 1 vez/día', pediatrico: '>5 años: misma dosis que adultos' },
    presentaciones: ['Ampollas para nebulización 2.5 mg/2.5 mL'],
    embarazo: 'B', lactancia: 'Compatible',
    cuidadosEnfermeria: ['Nebulizar con compresor (no ultrasónico)', 'No diluir ni mezclar con otros fármacos', 'Administrar antes de fisioterapia respiratoria', 'Refrigerar ampollas (2-8°C)'],
    unidadId: 'u04', capituloId: 'c04_06',
    grupoTerapeutico: 'Sistema Respiratorio', grupoFarmacologico: 'Fármacos para fibrosis quística',
  },

  // ============================================================
  // ONCOLOGÍA SOPORTE
  // ============================================================
  {
    id: 'zoledronato', nombre: 'Ácido Zoledrónico', nombreGenerico: 'Ácido zoledrónico (zoledronato)',
    nombresComerciales: ['Zometa', 'Aclasta'],
    familia: 'Bifosfonatos', clasificacion: 'Bifosfonato nitrogenado de tercera generación',
    mecanismoAccion: 'Inhibe la farnesil pirofosfato sintetasa en osteoclastos, impidiendo su función y supervivencia. El más potente de los bifosfonatos.',
    indicaciones: ['Metástasis óseas', 'Hipercalcemia maligna', 'Mieloma múltiple', 'Osteoporosis postmenopáusica (Aclasta)', 'Enfermedad de Paget'],
    contraindicaciones: ['ClCr <35 mL/min', 'Hipocalcemia no corregida', 'Embarazo/lactancia'],
    efectosAdversos: ['Síndrome gripal post-infusión (fiebre, mialgias)', 'Hipocalcemia', 'Nefrotoxicidad', 'Osteonecrosis mandibular', 'Fractura femoral atípica', 'Uveítis'],
    interacciones: ['Aminoglucósidos: potencian hipocalcemia', 'Nefrotóxicos: mayor riesgo renal'],
    viaAdministracion: ['IV'],
    dosis: { adulto: 'Metástasis: 4 mg IV en 15 min cada 3-4 semanas. Osteoporosis: 5 mg IV anual. Paget: 5 mg dosis única', ajusteRenal: 'ClCr 30-60: reducir dosis. ClCr <30: contraindicado' },
    presentaciones: ['Vial 4 mg/5 mL (Zometa)', 'Solución 5 mg/100 mL (Aclasta)'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Hidratación previa obligatoria', 'Infundir en ≥15 min (no en bolo)', 'Controlar creatinina antes de cada dosis', 'Suplementar calcio y vitamina D', 'Revisión dental antes de iniciar (osteonecrosis mandibular)', 'Monitorizar calcio sérico 7-10 días post-infusión'],
    unidadId: 'u07', capituloId: 'c07_06',
    grupoTerapeutico: 'Sistema Genitourinario y Reproductor', grupoFarmacologico: 'Antirresortivos óseos',
  },
  {
    id: 'amifostina', nombre: 'Amifostina', nombreGenerico: 'Amifostina',
    nombresComerciales: ['Ethyol'],
    familia: 'Citoprotectores', clasificacion: 'Tiofosfato orgánico citoprotector',
    mecanismoAccion: 'Profármaco desfosforilado por fosfatasa alcalina a tiol libre (WR-1065), que protege tejidos normales del daño por radiación y cisplatino mediante quelación de radicales libres.',
    indicaciones: ['Prevención de nefrotoxicidad por cisplatino', 'Reducción de xerostomía por radioterapia en cáncer de cabeza/cuello'],
    contraindicaciones: ['Hipotensión', 'Deshidratación', 'Hipersensibilidad'],
    efectosAdversos: ['Hipotensión (requiere hidratación previa)', 'Náuseas/vómitos', 'Somnolencia', 'Hipocalcemia', 'Reacciones cutáneas (Steven-Johnson raro)'],
    interacciones: ['Antihipertensivos: suspender 24h antes', 'Cisplatino: administrar 30 min antes'],
    viaAdministracion: ['IV'],
    dosis: { adulto: 'Cisplatino: 910 mg/m² IV en 15 min, 30 min antes de QT. Radioterapia: 200 mg/m² IV diario 15-30 min antes' },
    presentaciones: ['Vial 500 mg polvo para reconstitución'],
    embarazo: 'C', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Hidratación previa con SSF', 'PA cada 5 min durante infusión', 'Suspender si PAS <100 o caída >20%', 'Posición supina durante administración', 'Premedicación antiemética'],
    unidadId: 'u12', capituloId: 'c12_06',
    grupoTerapeutico: 'Fármacos Hospitalarios y Antineoplásicos', grupoFarmacologico: 'Soporte oncológico',
  },

  // ============================================================
  // SNC
  // ============================================================
  {
    id: 'tiapride', nombre: 'Tiapride', nombreGenerico: 'Tiapride (tiaprida)',
    nombresComerciales: ['Tiaprizal'],
    familia: 'Benzamidas', clasificacion: 'Antagonista dopaminérgico D2 selectivo (benzamida sustituida)',
    mecanismoAccion: 'Antagonista selectivo de receptores dopaminérgicos D2/D3, con menor efecto sobre otros receptores. Acción preferente sobre sistema mesolímbico.',
    indicaciones: ['Agitación y agresividad en ancianos', 'Discinesias tardías', 'Corea de Huntington', 'Síndrome de abstinencia alcohólica', 'Tics'],
    contraindicaciones: ['Feocromocitoma', 'Tumores prolactina-dependientes', 'Porfiria'],
    efectosAdversos: ['Somnolencia', 'Hiperprolactinemia', 'Síntomas extrapiramidales', 'Hipotensión ortostática', 'Aumento de peso'],
    interacciones: ['Levodopa: antagonismo', 'Depresores SNC: potenciación', 'Alcohol: potenciación'],
    viaAdministracion: ['oral', 'IM', 'IV'],
    dosis: { adulto: 'Agitación: 200-300 mg/día. Abstinencia alcohólica: 400-1200 mg/día 7-10 días', geriatrico: 'Iniciar 50 mg/día, máx 300 mg/día' },
    presentaciones: ['Comprimidos 100 mg', 'Ampollas 100 mg/2 mL'],
    embarazo: 'C', lactancia: 'No recomendado',
    cuidadosEnfermeria: ['Usar dosis bajas en ancianos', 'Vigilar síntomas extrapiramidales', 'Monitorizar PA (hipotensión)'],
    unidadId: 'u01', capituloId: 'c01_06',
    grupoTerapeutico: 'Sistema Nervioso', grupoFarmacologico: 'Antipsicóticos',
  },

  // ============================================================
  // FÁRMACOS ADICIONALES VADEMECUM
  // ============================================================
  {
    id: 'sacubitril_valsartan', nombre: 'Sacubitrilo/Valsartán', nombreGenerico: 'Sacubitrilo + Valsartán',
    nombresComerciales: ['Entresto'],
    familia: 'ARNI', clasificacion: 'Inhibidor de neprilisina + antagonista del receptor de angiotensina II (ARNI)',
    mecanismoAccion: 'Sacubitrilo inhibe la neprilisina (aumentando péptidos natriuréticos, bradicinina y adrenomedulina), mientras valsartán bloquea el receptor AT1 de angiotensina II. Efecto sinérgico vasodilatador, natriurético y antifibrótico.',
    indicaciones: ['Insuficiencia cardíaca crónica con FEVI reducida (HFrEF)', 'IC clase NYHA II-IV como alternativa a IECA/ARA-II'],
    contraindicaciones: ['Uso concomitante con IECA (esperar 36h)', 'Angioedema previo', 'Embarazo', 'Insuficiencia hepática severa'],
    efectosAdversos: ['Hipotensión', 'Hiperpotasemia', 'Mareo', 'Insuficiencia renal', 'Angioedema', 'Tos'],
    interacciones: ['IECA: contraindicado (angioedema, esperar 36h de washout)', 'Ahorradores de K: hiperpotasemia', 'AINEs: reducen eficacia', 'Estatinas: aumento niveles atorvastatina'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Inicio: 24/26 mg o 49/51 mg cada 12h. Objetivo: 97/103 mg cada 12h (titular cada 2-4 semanas)', ajusteRenal: 'ClCr <30: iniciar 24/26 mg cada 12h', ajusteHepatico: 'Moderada: iniciar 24/26 mg cada 12h. Severa: contraindicado' },
    presentaciones: ['Comprimidos 24/26 mg', 'Comprimidos 49/51 mg', 'Comprimidos 97/103 mg'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['OBLIGATORIO: 36h de washout tras suspender IECA', 'Titular gradualmente cada 2-4 semanas', 'Controlar PA, K sérico y función renal', 'Educar sobre síntomas de hipotensión', 'No usar con aliskirén en diabéticos'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Antihipertensivos',
  },
  {
    id: 'empagliflozina_ic', nombre: 'Empagliflozina (IC/ERC)', nombreGenerico: 'Empagliflozina',
    nombresComerciales: ['Jardiance'],
    familia: 'Inhibidores SGLT2', clasificacion: 'Inhibidor del cotransportador sodio-glucosa tipo 2 con indicación cardiovascular y renal',
    mecanismoAccion: 'Inhibe selectivamente SGLT2 en túbulo proximal, reduciendo reabsorción de glucosa y sodio. En IC: reduce precarga/postcarga, mejora metabolismo miocárdico y reduce fibrosis. En ERC: reduce hiperfiltración glomerular.',
    indicaciones: ['Insuficiencia cardíaca (con o sin diabetes)', 'Enfermedad renal crónica', 'Diabetes mellitus tipo 2'],
    contraindicaciones: ['TFGe <20 mL/min (para inicio)', 'Cetoacidosis diabética', 'Diabetes tipo 1'],
    efectosAdversos: ['Infecciones genitourinarias (candidiasis)', 'Poliuria', 'Hipotensión/deshidratación', 'Cetoacidosis euglucémica (raro)', 'Gangrena de Fournier (muy raro)'],
    interacciones: ['Diuréticos: riesgo depleción de volumen', 'Insulina/SU: ajustar dosis (riesgo hipoglucemia)'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'IC/ERC: 10 mg/día. DM2: 10-25 mg/día' },
    presentaciones: ['Comprimidos 10 mg', 'Comprimidos 25 mg'],
    embarazo: 'D', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Puede continuarse hasta diálisis una vez iniciado', 'Vigilar signos de infección genital', 'Educar sobre hidratación adecuada', 'Suspender 3 días antes de cirugía mayor (riesgo CAD)', 'No confundir indicación CV/renal con antidiabética'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Antihipertensivos',
  },
  {
    id: 'tirzepatida', nombre: 'Tirzepatida', nombreGenerico: 'Tirzepatida',
    nombresComerciales: ['Mounjaro', 'Zepbound'],
    familia: 'Agonistas duales GIP/GLP-1', clasificacion: 'Agonista dual de receptores GIP y GLP-1',
    mecanismoAccion: 'Polipéptido sintético que activa simultáneamente receptores de GIP (polipéptido insulinotrópico dependiente de glucosa) y GLP-1 (péptido similar a glucagón tipo 1), potenciando la secreción de insulina, suprimiendo glucagón, retrasando vaciamiento gástrico y reduciendo apetito.',
    indicaciones: ['Diabetes mellitus tipo 2', 'Obesidad/sobrepeso con comorbilidad (IMC ≥30 o ≥27 con comorbilidad)'],
    contraindicaciones: ['Antecedentes personales/familiares de carcinoma medular de tiroides', 'NEM2', 'Pancreatitis activa'],
    efectosAdversos: ['Náuseas (dosis-dependiente)', 'Diarrea', 'Vómitos', 'Dolor abdominal', 'Estreñimiento', 'Disminución de apetito', 'Pancreatitis (raro)', 'Colelitiasis'],
    interacciones: ['Insulina/SU: reducir dosis (hipoglucemia)', 'Anticonceptivos orales: posible reducción absorción (usar método adicional 4 semanas tras inicio o escalada)'],
    viaAdministracion: ['SC'],
    dosis: { adulto: 'Iniciar 2.5 mg SC semanal × 4 semanas, luego 5 mg semanal. Titular cada 4 semanas: 5 → 7.5 → 10 → 12.5 → 15 mg semanal' },
    presentaciones: ['Pluma precargada 2.5 mg', 'Pluma 5 mg', 'Pluma 7.5 mg', 'Pluma 10 mg', 'Pluma 12.5 mg', 'Pluma 15 mg'],
    embarazo: 'X', lactancia: 'No recomendado',
    cuidadosEnfermeria: ['Administrar SC en abdomen, muslo o brazo', 'Rotar sitio de inyección', 'Titular cada 4 semanas según tolerancia GI', 'Refrigerar plumas sin usar (2-8°C), una vez en uso: T ambiente hasta 21 días', 'Advertir sobre método anticonceptivo adicional'],
    unidadId: 'u06', capituloId: 'c06_01',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Antidiabéticos e insulinas',
  },
  {
    id: 'semaglutida_oral', nombre: 'Semaglutida Oral', nombreGenerico: 'Semaglutida (formulación oral)',
    nombresComerciales: ['Rybelsus'],
    familia: 'Agonistas GLP-1', clasificacion: 'Agonista del receptor GLP-1 en formulación oral',
    mecanismoAccion: 'Análogo de GLP-1 con absorción oral potenciada por SNAC (salcaprozato sódico). Estimula secreción de insulina, suprime glucagón, retrasa vaciamiento gástrico y reduce apetito.',
    indicaciones: ['Diabetes mellitus tipo 2'],
    contraindicaciones: ['Carcinoma medular de tiroides personal/familiar', 'NEM2', 'Pancreatitis'],
    efectosAdversos: ['Náuseas', 'Diarrea', 'Dolor abdominal', 'Disminución de apetito', 'Vómitos', 'Estreñimiento'],
    interacciones: ['Insulina/SU: ajustar dosis', 'Levotiroxina: posible alteración de absorción', 'Fármacos orales: tomar ≥30 min después'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Iniciar 3 mg/día × 30 días, luego 7 mg/día. Puede aumentar a 14 mg/día tras 30 días' },
    presentaciones: ['Comprimidos 3 mg', 'Comprimidos 7 mg', 'Comprimidos 14 mg'],
    embarazo: 'X', lactancia: 'No recomendado',
    cuidadosEnfermeria: ['TOMAR EN AYUNAS con ≤120 mL de agua', 'No partir, triturar ni masticar', 'Esperar ≥30 min antes de comer, beber o tomar otros fármacos', 'Titular mensualmente según tolerancia', 'La absorción se reduce con alimentos y mayor volumen de agua'],
    unidadId: 'u06', capituloId: 'c06_01',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Agonistas del receptor GLP-1',
  },
  {
    id: 'dapagliflozina_dm', nombre: 'Dapagliflozina (DM2)', nombreGenerico: 'Dapagliflozina',
    nombresComerciales: ['Forxiga', 'Farxiga'],
    familia: 'Inhibidores SGLT2', clasificacion: 'Inhibidor del cotransportador sodio-glucosa tipo 2',
    mecanismoAccion: 'Inhibe selectivamente SGLT2 en el túbulo proximal renal, aumentando la excreción urinaria de glucosa y sodio. Reduce glucemia independiente de insulina.',
    indicaciones: ['Diabetes mellitus tipo 2', 'Insuficiencia cardíaca', 'Enfermedad renal crónica'],
    contraindicaciones: ['Cetoacidosis diabética', 'DM tipo 1', 'TFGe <25 (para inicio en DM2)'],
    efectosAdversos: ['Infecciones genitales micóticas', 'ITU', 'Poliuria', 'Hipotensión', 'CAD euglucémica', 'Gangrena de Fournier (muy raro)'],
    interacciones: ['Diuréticos: depleción de volumen', 'Insulina: reducir dosis 20%'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'DM2: 5-10 mg/día. IC/ERC: 10 mg/día' },
    presentaciones: ['Comprimidos 5 mg', 'Comprimidos 10 mg'],
    embarazo: 'D', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Vigilar signos de infección genital', 'Hidratación adecuada', 'Suspender 3 días pre-cirugía', 'Monitorizar glucemia y función renal'],
    unidadId: 'u06', capituloId: 'c06_01',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Inhibidores del cotransportador sodio-glucosa tipo 2 (iSGLT2)',
  },
  {
    id: 'mecasermina', nombre: 'Mecasermina', nombreGenerico: 'Mecasermina (IGF-1 recombinante)',
    nombresComerciales: ['Increlex'],
    familia: 'Factor de crecimiento', clasificacion: 'Factor de crecimiento insulinoide tipo 1 (IGF-1) recombinante humano',
    mecanismoAccion: 'IGF-1 recombinante que se une al receptor de IGF-1, estimulando el crecimiento óseo y tisular en pacientes con deficiencia primaria de IGF-1 o resistencia a GH.',
    indicaciones: ['Déficit primario severo de IGF-1', 'Talla baja por resistencia a hormona de crecimiento (síndrome de Laron)', 'Déficit de GH con desarrollo de anticuerpos neutralizantes'],
    contraindicaciones: ['Neoplasia activa', 'Epífisis cerradas', 'Alergia a IGF-1'],
    efectosAdversos: ['Hipoglucemia (frecuente)', 'Hipertrofia amigdalar/adenoidea', 'Cefalea', 'Lipohipertrofia', 'Artralgias'],
    interacciones: ['Insulina: potenciación hipoglucémica', 'GH: uso concomitante no indicado'],
    viaAdministracion: ['SC'],
    dosis: { pediatrico: 'Iniciar 0.04 mg/kg SC cada 12h. Máx: 0.12 mg/kg cada 12h' },
    presentaciones: ['Vial 10 mg/mL (40 mg/4 mL)'],
    embarazo: 'C', lactancia: 'No datos',
    cuidadosEnfermeria: ['Administrar con comida para prevenir hipoglucemia', 'Monitorizar glucemia frecuente', 'Rotar sitios de inyección', 'Vigilar apnea del sueño (hipertrofia amigdalar)'],
    unidadId: 'u06', capituloId: 'c06_05',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Hormonas hipofisarias',
  },

  // ============================================================
  // FÁRMACOS NUEVOS/MODERNOS VADEMECUM 2025-2026
  // ============================================================
  {
    id: 'odevixibat', nombre: 'Odevixibat', nombreGenerico: 'Odevixibat',
    nombresComerciales: ['Bylvay'],
    familia: 'Inhibidores IBAT', clasificacion: 'Inhibidor del transportador ileal de ácidos biliares (IBAT)',
    mecanismoAccion: 'Inhibe selectivamente el transportador ileal de ácidos biliares (IBAT/ASBT), reduciendo la recirculación enterohepática de ácidos biliares y disminuyendo su concentración sérica.',
    indicaciones: ['Colestasis intrahepática familiar progresiva (PFIC)', 'Prurito colestásico en síndrome de Alagille'],
    contraindicaciones: ['Hipersensibilidad', 'Obstrucción biliar completa'],
    efectosAdversos: ['Diarrea', 'Dolor abdominal', 'Hepatotoxicidad', 'Deficiencia de vitaminas liposolubles (A, D, E, K)'],
    interacciones: ['Puede reducir absorción de vitaminas liposolubles y fármacos lipofílicos'],
    viaAdministracion: ['oral'],
    dosis: { pediatrico: 'PFIC: 40 mcg/kg/día en dosis única matutina. Puede aumentar a 120 mcg/kg/día' },
    presentaciones: ['Cápsulas 200 mcg', 'Cápsulas 400 mcg', 'Cápsulas 600 mcg', 'Cápsulas 1200 mcg'],
    embarazo: 'N/A', lactancia: 'N/A (uso pediátrico)',
    cuidadosEnfermeria: ['Administrar por la mañana con comida', 'Suplementar vitaminas liposolubles', 'Monitorizar función hepática y bilirrubina', 'Se puede abrir cápsula y mezclar con comida blanda'],
    unidadId: 'u05', capituloId: 'c05_07',
    grupoTerapeutico: 'Aparato Digestivo', grupoFarmacologico: 'Fármacos pancreáticos y biliares',
  },
  {
    id: 'imeglimina', nombre: 'Imeglimina', nombreGenerico: 'Imeglimina',
    nombresComerciales: ['Twymeeg'],
    familia: 'Gliminas', clasificacion: 'Primera glimina — nueva clase de antidiabético oral',
    mecanismoAccion: 'Mecanismo dual: mejora la función mitocondrial en células beta (restaura secreción de insulina) y en tejidos periféricos (reduce resistencia a insulina). También tiene efecto hepatoprotector.',
    indicaciones: ['Diabetes mellitus tipo 2 (aprobado en Japón 2021, en evaluación EMA/FDA)'],
    contraindicaciones: ['Insuficiencia renal severa', 'Cetoacidosis diabética'],
    efectosAdversos: ['Náuseas', 'Diarrea', 'Dolor abdominal', 'Disminución de apetito'],
    interacciones: ['Insulina/SU: posible hipoglucemia aditiva'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '1000 mg cada 12h con alimentos' },
    presentaciones: ['Comprimidos 500 mg'],
    embarazo: 'N/A', lactancia: 'No datos',
    cuidadosEnfermeria: ['Administrar con comidas', 'Monitorizar glucemia y HbA1c', 'Nueva clase terapéutica: reportar efectos adversos'],
    unidadId: 'u06', capituloId: 'c06_01',
    grupoTerapeutico: 'Sistema Endocrino y Metabolismo', grupoFarmacologico: 'Antidiabéticos e insulinas',
  },
  {
    id: 'finerenona_dm', nombre: 'Finerenona', nombreGenerico: 'Finerenona',
    nombresComerciales: ['Kerendia'],
    familia: 'Antagonistas del receptor mineralocorticoide', clasificacion: 'Antagonista selectivo no esteroideo del receptor mineralocorticoide',
    mecanismoAccion: 'Bloquea selectivamente el receptor mineralocorticoide con alta potencia, reduciendo la inflamación y fibrosis mediadas por aldosterona en riñón y corazón. A diferencia de espironolactona, no tiene actividad esteroide (menos ginecomastia).',
    indicaciones: ['Enfermedad renal crónica asociada a DM2', 'Reducción de riesgo cardiovascular en ERC + DM2'],
    contraindicaciones: ['K >5.0 mEq/L', 'Insuficiencia suprarrenal', 'Uso concomitante con inhibidores fuertes de CYP3A4 + P-gp', 'TFGe <25 mL/min'],
    efectosAdversos: ['Hiperpotasemia (principal)', 'Hipotensión', 'Hiponatremia'],
    interacciones: ['Inhibidores CYP3A4 fuertes (ketoconazol, itraconazol): contraindicados', 'IECA/ARA-II: monitorizar K', 'Suplementos de K: evitar', 'Pomelo: aumenta niveles'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Iniciar 10 mg/día si TFGe ≥60, 20 mg/día si TFGe 25-60. Ajustar según K sérico a 10-20 mg/día', ajusteRenal: 'No iniciar si TFGe <25' },
    presentaciones: ['Comprimidos 10 mg', 'Comprimidos 20 mg'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['MONITORIZAR K sérico antes de inicio, a las 4 semanas y periódicamente', 'Suspender si K >5.5 (reiniciar cuando <5.0 con dosis menor)', 'Vigilar función renal', 'Educar sobre dieta baja en potasio'],
    unidadId: 'u02', capituloId: 'c02_04',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Antagonistas de la aldosterona',
  },
  {
    id: 'vericiguat', nombre: 'Vericiguat', nombreGenerico: 'Vericiguat',
    nombresComerciales: ['Verquvo'],
    familia: 'Estimuladores de guanilato ciclasa soluble', clasificacion: 'Estimulador de la guanilato ciclasa soluble (GCs)',
    mecanismoAccion: 'Estimula directamente la guanilato ciclasa soluble (independiente de NO) y sensibiliza al NO endógeno, aumentando la producción de cGMP. Produce vasodilatación y efectos cardioprotectores.',
    indicaciones: ['Insuficiencia cardíaca crónica sintomática con FEVI reducida', 'Tras descompensación reciente (hospitalización o diuréticos IV)'],
    contraindicaciones: ['Uso con inhibidores de PDE5 (sildenafilo)', 'Uso con nitratos', 'Embarazo'],
    efectosAdversos: ['Hipotensión', 'Anemia', 'Síncope', 'Mareo'],
    interacciones: ['Inhibidores PDE5 (sildenafilo, tadalafilo): hipotensión severa', 'Nitratos: contraindicados', 'Antiácidos: reducen absorción'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Iniciar 2.5 mg/día con comida. Duplicar cada 2 semanas: 2.5 → 5 → 10 mg/día' },
    presentaciones: ['Comprimidos 2.5 mg', 'Comprimidos 5 mg', 'Comprimidos 10 mg'],
    embarazo: 'X', lactancia: 'Contraindicado',
    cuidadosEnfermeria: ['Administrar CON comida', 'Si se olvida una dosis, no duplicar', 'Controlar PA (riesgo hipotensión)', 'NO combinar con sildenafilo ni nitratos', 'Mujeres en edad fértil: anticoncepción obligatoria'],
    unidadId: 'u02', capituloId: 'c02_01',
    grupoTerapeutico: 'Sistema Cardiovascular', grupoFarmacologico: 'Fármacos para insuficiencia cardíaca',
  },
];

let added = 0;
for (const drug of newDrugs) {
  if (existingIds.has(drug.id)) {
    console.log('SKIP (exists):', drug.nombre);
    continue;
  }
  drugs.push(drug);
  existingIds.add(drug.id);
  added++;
  console.log('ADD:', drug.nombre);

  // Update categories
  for (const u of cats.unidades) {
    for (const c of u.capitulos) {
      if (c.id === drug.capituloId && !c.drugIds.includes(drug.id)) {
        c.drugIds.push(drug.id);
      }
    }
  }
}

fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log(`\nDone: ${added} drugs added. Total: ${drugs.length}`);
