const drugs = require('../src/data/drugs.json');

const newDrugs = [
  {id:'noradrenalina',nombre:'Noradrenalina (Norepinefrina)',nombreGenerico:'Norepinefrina bitartrato',nombresComerciales:['Levophed'],familia:'Catecolaminas / Vasopresores',clasificacion:'Agonista alfa-1 y beta-1',mecanismoAccion:'Estimula alfa-1 (vasoconstriccion) y beta-1 (inotropico positivo). Aumenta PA por resistencia vascular.',indicaciones:['Shock septico (vasopresor de 1a linea)','Shock cardiogenico refractario','Hipotension severa refractaria a fluidos'],contraindicaciones:['Hipovolemia no corregida','Trombosis vascular'],efectosAdversos:['Hipertension severa','Bradicardia refleja','Arritmias','Necrosis por extravasacion','Isquemia periferica'],interacciones:['IMAO: potenciacion extrema','Betabloqueantes: hipertension con bradicardia'],viaAdministracion:['IV'],dosis:{adulto:'Infusion IV: 0.05-0.4 mcg/kg/min. Inicio: 0.1 mcg/kg/min. 4mg en 250ml SG5%.',pediatrico:'0.05-2 mcg/kg/min.'},presentaciones:['Ampolla 4mg/4ml','Ampolla 8mg/4ml'],embarazo:'C',lactancia:'Solo si beneficio justifica riesgo.',cuidadosEnfermeria:['EXCLUSIVAMENTE por via central','NUNCA en bolo - infusion continua con bomba','Monitorizacion: PAM, FC, ECG, diuresis horaria','Objetivo PAM >=65 mmHg','Vigilar sitio cada 30 min - extravasacion causa NECROSIS','Si extravasacion: fentolamina 5-10mg en SF local','No suspender abruptamente','Proteger de la luz','Vigilar perfusion distal'],farmacocinetica:{vidaMedia:'2-3 minutos',inicioAccion:'Inmediato'},almacenamiento:'Proteger de la luz.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'adrenalina',nombre:'Adrenalina (Epinefrina)',nombreGenerico:'Epinefrina clorhidrato',nombresComerciales:['Adrenalina Braun','EpiPen'],familia:'Catecolaminas',clasificacion:'Agonista alfa y beta no selectivo',mecanismoAccion:'Estimula alfa-1, beta-1, beta-2. Vasoconstriccion, aumento FC, broncodilatacion.',indicaciones:['PCR','Anafilaxia (1a linea)','Shock anafilactico','Broncoespasmo severo'],contraindicaciones:['Taquiarritmias'],efectosAdversos:['Taquicardia','Arritmias','Hipertension','Temblor','Ansiedad'],interacciones:['IMAO: potenciacion extrema','Digoxina: arritmias'],viaAdministracion:['IV','IM','SC','inhalatoria'],dosis:{adulto:'PCR: 1mg IV/3-5min. Anafilaxia: 0.3-0.5mg IM muslo.',pediatrico:'PCR: 0.01mg/kg IV. Anafilaxia: 0.01mg/kg IM.'},presentaciones:['Ampolla 1mg/1ml (1:1000)','Ampolla 1mg/10ml (1:10000)','EpiPen 0.3mg'],embarazo:'C',lactancia:'Solo en emergencias.',cuidadosEnfermeria:['ANAFILAXIA: IM en muslo anterolateral','PCR: IV en 1:10000','NO confundir: 1:1000 (IM) vs 1:10000 (IV)','ECG, PA, FC, SatO2 continuo','Observar 6-8h tras anafilaxia','Ensenar uso de autoinyector'],farmacocinetica:{vidaMedia:'2-3 minutos',inicioAccion:'IV: inmediato. IM: 3-5 min'},almacenamiento:'Proteger de la luz.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'atropina',nombre:'Atropina',nombreGenerico:'Sulfato de atropina',nombresComerciales:['Atropina Braun'],familia:'Anticolinergicos',clasificacion:'Antagonista muscarinico',mecanismoAccion:'Bloquea receptores muscarinicos. Aumenta FC al bloquear tono vagal.',indicaciones:['Bradicardia sintomatica','Intoxicacion organofosforados','Premedicacion anestesica'],contraindicaciones:['Glaucoma angulo cerrado','Obstruccion urinaria'],efectosAdversos:['Taquicardia','Sequedad de boca','Midriasis','Retencion urinaria','Confusion en ancianos'],interacciones:['Otros anticolinergicos: efecto aditivo'],viaAdministracion:['IV','IM'],dosis:{adulto:'Bradicardia: 0.5mg IV/3-5min (max 3mg). Organofosforados: 2-4mg IV.',pediatrico:'0.02mg/kg IV (min 0.1mg).'},presentaciones:['Ampolla 1mg/1ml'],embarazo:'C',lactancia:'Puede reducir produccion de leche.',cuidadosEnfermeria:['Dosis minima 0.5mg IV (menores causan bradicardia paradojica)','ECG continuo','Objetivo: FC >60 lpm','Vigilar retencion urinaria','En ancianos: vigilar confusion'],farmacocinetica:{vidaMedia:'2-3 horas',inicioAccion:'IV: 1-2 min'},almacenamiento:'Temperatura ambiente.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'dopamina',nombre:'Dopamina',nombreGenerico:'Clorhidrato de dopamina',nombresComerciales:['Intropin'],familia:'Catecolaminas',clasificacion:'Agonista dopaminergico alfa y beta',mecanismoAccion:'Dosis baja: vasodilatacion renal. Media: inotropico. Alta: vasoconstriccion.',indicaciones:['Shock cardiogenico','Hipotension refractaria','Bradicardia (2a linea)'],contraindicaciones:['Feocromocitoma','Taquiarritmias'],efectosAdversos:['Taquicardia','Arritmias','Necrosis extravasacion'],interacciones:['IMAO: reducir dosis 1/10'],viaAdministracion:['IV'],dosis:{adulto:'Infusion: 2-20 mcg/kg/min.',pediatrico:'1-20 mcg/kg/min.'},presentaciones:['Ampolla 200mg/5ml'],embarazo:'C',lactancia:'Solo si necesario.',cuidadosEnfermeria:['Bomba de infusion via central','NUNCA en bolo','Monitorizacion hemodinamica','No mezclar con bicarbonato','Reducir gradualmente','Vigilar extravasacion'],farmacocinetica:{vidaMedia:'2 minutos',inicioAccion:'1-2 min'},almacenamiento:'Proteger de la luz.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'midazolam',nombre:'Midazolam',nombreGenerico:'Clorhidrato de midazolam',nombresComerciales:['Dormicum','Versed'],familia:'Benzodiacepinas',clasificacion:'BZD de accion corta',mecanismoAccion:'Potencia GABA en GABA-A. Sedacion, amnesia anterograda, anticonvulsivante.',indicaciones:['Sedacion procedimientos','Status epileptico','Sedacion UCI'],contraindicaciones:['Miastenia gravis','Insuficiencia respiratoria severa'],efectosAdversos:['Depresion respiratoria','Hipotension','Amnesia anterograda','Agitacion paradojica'],interacciones:['Opioides: depresion respiratoria sinergica','Alcohol: potenciacion'],viaAdministracion:['IV','IM','oral','nasal'],dosis:{adulto:'Sedacion IV: 0.5-2.5mg lento. UCI: 0.02-0.1mg/kg/h.',pediatrico:'IV: 0.05-0.1mg/kg. Nasal: 0.2mg/kg.',geriatrico:'Reducir 50%.'},presentaciones:['Ampolla 5mg/5ml','Ampolla 15mg/3ml'],embarazo:'D',lactancia:'Evitar lactancia 24h.',cuidadosEnfermeria:['IV LENTO: max 1mg/2min','Tener flumazenilo disponible','Monitorizar SatO2 FR PA Ramsay','No administrar si FR <12','NO conducir ni firmar consentimientos','Ancianos: mitad de dosis'],farmacocinetica:{vidaMedia:'1.5-2.5 horas',inicioAccion:'IV: 1-3 min'},almacenamiento:'Proteger de la luz.',unidadId:'1',capituloId:'1-3',searchText:''},
  {id:'adenosina',nombre:'Adenosina',nombreGenerico:'Adenosina',nombresComerciales:['Adenocor'],familia:'Antiarritmicos',clasificacion:'Nucleosido endogeno',mecanismoAccion:'Receptores A1 en nodo AV reduce conduccion interrumpe reentrada.',indicaciones:['TSVP por reentrada','Diagnostico taquicardias'],contraindicaciones:['Bloqueo AV 2-3 grado','Asma severo'],efectosAdversos:['Opresion toracica','Disnea transitoria','Rubor','Asistolia breve'],interacciones:['Dipiridamol: potencia','Cafeina: antagoniza'],viaAdministracion:['IV'],dosis:{adulto:'6mg IV bolo rapido + flush 20ml SF. Si no revierte: 12mg.',pediatrico:'0.1mg/kg (max 6mg).'},presentaciones:['Ampolla 6mg/2ml'],embarazo:'C',lactancia:'Probablemente seguro.',cuidadosEnfermeria:['BOLO IV RAPIDO 1-2 seg + flush 20ml SF','Acceso proximal antecubital','Llave 3 vias','ECG continuo','Advertir sensacion transitoria','Equipo reanimacion disponible','Contraindicada en asmaticos'],farmacocinetica:{vidaMedia:'<10 segundos',inicioAccion:'Inmediato'},almacenamiento:'Refrigerar 2-8C.',unidadId:'2',capituloId:'2-2',searchText:''},
  {id:'glucagon',nombre:'Glucagon',nombreGenerico:'Glucagon recombinante',nombresComerciales:['GlucaGen','Baqsimi'],familia:'Hormonas',clasificacion:'Hormona hiperglucemiante',mecanismoAccion:'Glucogenolisis hepatica y gluconeogenesis. Inotropico positivo.',indicaciones:['Hipoglucemia severa','Sobredosis betabloqueantes','Sobredosis calcioantagonistas'],contraindicaciones:['Feocromocitoma','Insulinoma'],efectosAdversos:['Nauseas','Hiperglucemia','Taquicardia'],interacciones:['Warfarina: aumenta efecto','Insulina: antagonismo'],viaAdministracion:['IM','SC','IV','nasal'],dosis:{adulto:'Hipoglucemia: 1mg IM/SC. Sobredosis BB: 3-10mg IV.',pediatrico:'<25kg: 0.5mg. >25kg: 1mg.'},presentaciones:['Kit 1mg','Spray nasal 3mg'],embarazo:'B',lactancia:'Probablemente seguro.',cuidadosEnfermeria:['Reconstituir antes de usar','Posicion lateral seguridad','Carbohidratos orales al despertar','Glucemia cada 15-20 min','No efectivo si glucogeno depletado','Educar familiares diabeticos'],farmacocinetica:{vidaMedia:'8-18 min',inicioAccion:'IM: 8-10 min'},almacenamiento:'Refrigerar kit.',unidadId:'6',capituloId:'6-1',searchText:''},
  {id:'sulfato-magnesio',nombre:'Sulfato de Magnesio',nombreGenerico:'Sulfato de magnesio',nombresComerciales:['Sulmetin'],familia:'Electrolitos',clasificacion:'Electrolito anticonvulsivante',mecanismoAccion:'Compite con calcio. Estabiliza membranas reduce excitabilidad.',indicaciones:['Eclampsia/preeclampsia','Hipomagnesemia','Torsades de Pointes','Asma severa refractaria'],contraindicaciones:['Bloqueo cardiaco','Insuficiencia renal severa'],efectosAdversos:['Hipotension','Bradicardia','Debilidad muscular','Depresion respiratoria'],interacciones:['Bloqueantes neuromusculares: potenciacion'],viaAdministracion:['IV','IM'],dosis:{adulto:'Eclampsia: 4-6g IV/15-20min + 1-2g/h. Torsades: 1-2g IV.',pediatrico:'25-50mg/kg IV (max 2g).'},presentaciones:['Ampolla 10%','Ampolla 50%'],embarazo:'A',lactancia:'Compatible.',cuidadosEnfermeria:['REFLEJOS ROTULIANOS cada hora','FR cada 15-30 min suspender si <12','Diuresis horaria','GLUCONATO DE CALCIO antidoto','Niveles terapeuticos: 4-7 mEq/L','Toxicidad: reflejos respiracion paro','Mantener 24h post-parto'],farmacocinetica:{vidaMedia:'4-5 horas',inicioAccion:'IV: inmediato'},almacenamiento:'Temperatura ambiente.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'bicarbonato-sodio',nombre:'Bicarbonato de Sodio',nombreGenerico:'Bicarbonato de sodio',nombresComerciales:['Bicarbonato Braun'],familia:'Electrolitos',clasificacion:'Alcalinizante',mecanismoAccion:'Neutraliza H+ aumenta pH. Buffer acido-base.',indicaciones:['Acidosis metabolica severa','PCR prolongada','Hiperpotasemia severa','Intoxicacion triciclicos'],contraindicaciones:['Alcalosis','Hipocalcemia'],efectosAdversos:['Alcalosis metabolica','Hipopotasemia','Hipernatremia'],interacciones:['Inactiva catecolaminas','Precipita con calcio'],viaAdministracion:['IV'],dosis:{adulto:'1 mEq/kg IV.',pediatrico:'1 mEq/kg IV lento.'},presentaciones:['Frasco 8.4% 250ml'],embarazo:'C',lactancia:'Compatible.',cuidadosEnfermeria:['NUNCA mezclar con catecolaminas','NUNCA mezclar con calcio','Via IV separada','Gasometria tras cada dosis','Neonatos: concentracion 4.2%','Vigilar extravasacion'],farmacocinetica:{inicioAccion:'Inmediato'},almacenamiento:'Temperatura ambiente.',unidadId:'12',capituloId:'12-1',searchText:''},
  {id:'dobutamina',nombre:'Dobutamina',nombreGenerico:'Clorhidrato de dobutamina',nombresComerciales:['Dobutrex'],familia:'Catecolaminas / Inotropico',clasificacion:'Agonista beta-1 selectivo',mecanismoAccion:'Estimula beta-1: aumenta contractilidad. Leve vasodilatacion beta-2.',indicaciones:['ICC aguda descompensada','Shock cardiogenico'],contraindicaciones:['Estenosis subaortica hipertrofica'],efectosAdversos:['Taquicardia','Arritmias','Dolor anginoso'],interacciones:['Betabloqueantes: antagonismo'],viaAdministracion:['IV'],dosis:{adulto:'Infusion: 2-20 mcg/kg/min.',pediatrico:'2-20 mcg/kg/min.'},presentaciones:['Ampolla 250mg/20ml'],embarazo:'B',lactancia:'Situacion critica.',cuidadosEnfermeria:['Bomba de infusion siempre','ECG continuo y PA','Vigilar isquemia miocardica','Gasto urinario horario','No mezclar con bicarbonato','Reducir gradualmente'],farmacocinetica:{vidaMedia:'2 minutos',inicioAccion:'1-2 min'},almacenamiento:'Proteger de la luz.',unidadId:'12',capituloId:'12-1',searchText:''}
];

const normalize = s => (s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
newDrugs.forEach(d => {
  d.searchText = normalize([d.nombre,d.nombreGenerico,d.nombresComerciales.join(' '),d.familia,d.indicaciones.join(' '),d.cuidadosEnfermeria.join(' ')].join(' '));
});

const merged = [...drugs, ...newDrugs];
console.log('Total drugs:', merged.length);
require('fs').writeFileSync(require('path').join(__dirname, '../src/data/drugs.json'), JSON.stringify(merged, null, 2));
console.log('drugs.json updated!');
