const fs = require('fs');
const path = require('path');

const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath  = path.join(__dirname, '..', 'src', 'data', 'categories.json');

const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats  = JSON.parse(fs.readFileSync(catsPath, 'utf8'));

const existingIds = new Set(drugs.map(d => d.id));

function mkSearch(d) {
  return [d.nombre, d.nombreGenerico, ...d.nombresComerciales, d.familia, d.clasificacion, ...d.indicaciones]
    .join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

const newDrugs = [
  {
    id: "efedrina",
    nombre: "Efedrina",
    nombreGenerico: "Efedrina (sulfato/clorhidrato)",
    nombresComerciales: ["Efedrina Braun"],
    familia: "Vasopresores",
    clasificacion: "Simpaticomimético mixto (directo e indirecto)",
    mecanismoAccion: "Estimula directamente receptores alfa y beta adrenérgicos, y libera noradrenalina endógena de terminales simpáticas. Aumenta PA, FC y gasto cardíaco. No actúa en receptores dopaminérgicos.",
    indicaciones: ["Hipotensión perioperatoria", "Hipotensión por anestesia espinal/epidural", "Hipotensión inducida por anestesia general", "Broncoespasmo agudo (uso limitado)"],
    contraindicaciones: ["Uso de IMAO", "Feocromocitoma", "Tirotoxicosis", "HTA severa", "Cardiopatía isquémica", "Taquiarritmias"],
    efectosAdversos: ["Taquicardia", "Hipertensión", "Palpitaciones", "Arritmias", "Cefalea", "Ansiedad", "Temblor", "Retención urinaria", "Taquifilaxia (pierde efecto con dosis repetidas)"],
    interacciones: ["IMAO (crisis hipertensiva, contraindicado)", "Halotano (arritmias)", "Oxitocina (HTA severa)", "Betabloqueantes (HTA por efecto alfa sin oposición)", "Otros simpaticomiméticos"],
    viaAdministracion: ["intravenosa", "intramuscular"],
    dosis: { adultos: "Hipotensión: 5-10 mg IV en bolo, repetir cada 3-5 min según PA. Máx 50 mg. IM: 25-50 mg", pediatria: "0.1-0.3 mg/kg IV en bolo" },
    presentaciones: ["Ampolla 50 mg/mL (1 mL)", "Ampolla 30 mg/mL (10 mL)"],
    embarazo: "Usar con precaución (útil en hipotensión por espinal en cesárea, pero fenilefrina preferida)",
    lactancia: "Precaución",
    cuidadosEnfermeria: ["Administrar en bolos lentos IV", "Monitorizar PA y FC continuamente", "Taquifilaxia: pierde efecto con dosis repetidas (no repetir más de 3-4 bolos)", "Preferir fenilefrina en cesárea (menos taquicardia fetal)", "No mezclar con bicarbonato"],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Amplia, cruza BHE", metabolismo: "Hepático por MAO (parcial)", eliminacion: "Renal 40-75% sin cambios", vidaMedia: "3-6 horas" },
    almacenamiento: "Temperatura ambiente, proteger de la luz",
    unidadId: "u03", capituloId: "c0302",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Crisis hipertensiva, taquicardia severa, arritmias, hemorragia cerebral", manejo: "Fentolamina (alfa-bloqueo), betabloqueantes si taquicardia, nitroprusiato si HTA refractaria" }
  },
  {
    id: "esmolol",
    nombre: "Esmolol",
    nombreGenerico: "Esmolol clorhidrato",
    nombresComerciales: ["Brevibloc"],
    familia: "Betabloqueantes",
    clasificacion: "Betabloqueante cardioselectivo (β1) de ultra-corta acción",
    mecanismoAccion: "Bloquea selectivamente receptores β1 adrenérgicos cardíacos. Ultra-corta acción por metabolismo rápido por esterasas eritrocitarias. Reduce FC, contractilidad y conducción AV.",
    indicaciones: ["Taquicardia supraventricular", "Flutter/fibrilación auricular (control de FC)", "Taquicardia sinusal perioperatoria", "Crisis hipertensiva perioperatoria", "Tormenta tiroidea (control de FC)", "Disección aórtica"],
    contraindicaciones: ["Bradicardia sinusal severa", "Bloqueo AV 2do-3er grado", "Shock cardiogénico", "ICC descompensada", "Feocromocitoma no tratado", "Asma severo"],
    efectosAdversos: ["Hipotensión", "Bradicardia", "Mareo", "Diaforesis", "Náuseas", "Dolor en sitio de infusión", "Broncoespasmo (raro, cardioselectivo)"],
    interacciones: ["Verapamilo/Diltiazem (bloqueo AV aditivo)", "Digoxina (bradicardia aditiva)", "Morfina (aumenta niveles de esmolol 46%)", "Insulina (enmascara hipoglucemia)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Bolo: 500 mcg/kg en 1 min, luego infusión 50-200 mcg/kg/min. Titular cada 4 min. Disección aórtica: titular FC <60", pediatria: "100-500 mcg/kg bolo, luego 25-200 mcg/kg/min" },
    presentaciones: ["Solución 10 mg/mL (250 mL premezclado)", "Ampolla 100 mg/10 mL"],
    embarazo: "Categoría C",
    lactancia: "Compatible probablemente (vida media ultra-corta)",
    cuidadosEnfermeria: ["Administrar con bomba de infusión", "Monitorización ECG y PA continua", "Inicio de acción: 1-2 minutos", "Efecto cesa en 10-20 min tras suspender", "NO administrar por vía periférica concentrado (necrosis)", "Usar solución premezclada preferiblemente", "Tener atropina y vasopresores disponibles"],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Vd 3.4 L/kg, unión a proteínas 55%", metabolismo: "Esterasas eritrocitarias (NO hepático)", eliminacion: "Renal (metabolitos)", vidaMedia: "9 minutos" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u03", capituloId: "c0301",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Bradicardia severa, hipotensión, broncoespasmo, ICC", manejo: "Suspender (efecto cesa en 10-20 min), atropina, glucagón IV, vasopresores, isoproterenol" }
  },
  {
    id: "sulfato_magnesio",
    nombre: "Sulfato de Magnesio",
    nombreGenerico: "Sulfato de magnesio heptahidratado",
    nombresComerciales: ["Sulfato de Magnesio"],
    familia: "Electrolitos/Anticonvulsivantes",
    clasificacion: "Electrolito esencial / Anticonvulsivante / Tocolítico",
    mecanismoAccion: "Bloquea la unión neuromuscular al competir con el calcio. Deprime el SNC, relaja musculatura lisa, produce vasodilatación. Cofactor de >300 reacciones enzimáticas. Estabilizador de membrana cardíaca.",
    indicaciones: ["Eclampsia y preeclampsia severa (prevención de convulsiones)", "Hipomagnesemia", "Torsades de pointes", "Asma aguda severa (adyuvante)", "Tocolisis (2da línea)", "Arritmias refractarias", "Neuroprotección fetal <32 semanas"],
    contraindicaciones: ["Bloqueo cardíaco", "Miastenia gravis", "Insuficiencia renal severa (ajustar)", "Daño miocárdico"],
    efectosAdversos: ["Rubor", "Diaforesis", "Hipotensión", "Bradicardia", "Depresión respiratoria", "Hiporreflexia", "Hipotonía", "Hipocalcemia", "Náuseas"],
    interacciones: ["Bloqueantes neuromusculares (potenciación severa)", "BCC (hipotensión y bloqueo NM)", "Aminoglucósidos (potenciación bloqueo NM)", "Digitálicos (arritmias por alteración electrolítica)"],
    viaAdministracion: ["intravenosa", "intramuscular"],
    dosis: { adultos: "Eclampsia: Carga 4-6 g IV en 15-20 min, mantenimiento 1-2 g/h. Hipomagnesemia: 1-4 g IV en 1h. Torsades: 1-2 g IV en 5-20 min. Asma: 2 g IV en 20 min. Neuroprotección fetal: 4 g bolo + 1 g/h", pediatria: "25-50 mg/kg IV (máx 2 g) en 10-20 min" },
    presentaciones: ["Ampolla 50% (500 mg/mL) 10 mL = 5 g", "Ampolla 20% (200 mg/mL) 10 mL = 2 g", "Ampolla 10% (100 mg/mL)"],
    embarazo: "Pilar del manejo de eclampsia/preeclampsia. Neuroprotector fetal <32 sem",
    lactancia: "Compatible",
    cuidadosEnfermeria: ["DILUIR antes de IV (no administrar concentrado al 50% sin diluir en IV)", "Monitorizar reflejo patelar cada hora (pérdida = toxicidad)", "FR ≥12/min (suspender si <12)", "Diuresis ≥25-30 mL/h", "Niveles terapéuticos: 4-7 mEq/L (eclampsia)", "ANTÍDOTO: Gluconato de calcio 1 g IV en 3-5 min", "Monitorizar ECG si dosis altas", "Tener gluconato de calcio siempre disponible junto a la infusión"],
    farmacocinetica: { absorcion: "IV: inmediata. IM: absorción variable", distribucion: "Amplia, cruza placenta", metabolismo: "No se metaboliza", eliminacion: "Renal (filtración glomerular)", vidaMedia: "Variable según función renal, ~4-5h con función normal" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u10", capituloId: "c1001",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Pérdida de reflejos >7 mEq/L, parálisis respiratoria 10-12 mEq/L, paro cardíaco >15 mEq/L", manejo: "Gluconato de calcio 1g IV inmediato, ventilación asistida, calcio repetir cada 5 min si necesario" }
  },
  {
    id: "bicarbonato_sodio",
    nombre: "Bicarbonato de Sodio",
    nombreGenerico: "Bicarbonato de sodio",
    nombresComerciales: ["Bicarbonato de Sodio"],
    familia: "Electrolitos/Alcalinizantes",
    clasificacion: "Agente alcalinizante sistémico",
    mecanismoAccion: "Libera iones bicarbonato que neutralizan iones hidrógeno, elevando el pH sanguíneo y urinario. Actúa como buffer del sistema ácido carbónico-bicarbonato.",
    indicaciones: ["Acidosis metabólica severa (pH <7.1)", "Paro cardíaco prolongado (>10 min, no de primera línea)", "Hiperpotasemia severa (adyuvante)", "Intoxicación por tricíclicos (ensanchamiento QRS)", "Intoxicación por salicilatos (alcalinización urinaria)", "Acidosis tubular renal"],
    contraindicaciones: ["Alcalosis metabólica o respiratoria", "Hipocalcemia (empeora)", "Edema con retención de sodio"],
    efectosAdversos: ["Alcalosis metabólica", "Hipopotasemia", "Hipocalcemia (reduce calcio ionizado)", "Hipernatremia", "Hiperosmolaridad", "Extravasación tisular (necrosis)"],
    interacciones: ["Catecolaminas (inactivación si se mezclan en misma línea)", "Calcio (precipitación si se mezclan)", "Modifica pH urinario (altera excreción de múltiples fármacos)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Acidosis: 1-2 mEq/kg IV, luego según gasometría. Paro cardíaco: 1 mEq/kg IV. Intoxicación tricíclicos: bolos 1-2 mEq/kg hasta QRS <120 ms. Hiperpotasemia: 50 mEq IV en 5 min", pediatria: "1 mEq/kg IV lento, en neonatos diluir al 4.2% (0.5 mEq/mL)" },
    presentaciones: ["Ampolla 8.4% (1 mEq/mL) 10 mL", "Ampolla 8.4% 50 mL", "Ampolla 7.5% (0.89 mEq/mL)", "Solución 1.4% (isotónica) 500 mL"],
    embarazo: "Categoría C - Usar si necesario",
    lactancia: "Compatible",
    cuidadosEnfermeria: ["NO mezclar con calcio ni catecolaminas en misma línea (precipitación/inactivación)", "Administrar por línea IV separada o lavar línea antes/después", "En neonatos: usar SOLO solución 4.2% (diluir al 50%) para evitar hemorragia intraventricular", "Gasometría antes y 15-30 min después", "Monitorizar K+ (el bicarbonato baja el potasio)", "Extravasación causa necrosis tisular grave: verificar permeabilidad de vía", "No usar de rutina en RCP (solo si acidosis documentada o paro prolongado)"],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Espacio extracelular", metabolismo: "H+ + HCO3- → H2O + CO2 (eliminado por pulmones)", eliminacion: "Renal (regulación del exceso)", vidaMedia: "No aplicable (sistema buffer)" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u10", capituloId: "c1001",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Alcalosis metabólica severa, hipopotasemia, hipocalcemia, tetania, arritmias", manejo: "Suspender, corregir electrolitos (K+, Ca++), acetazolamida si alcalosis severa, ventilación" }
  },
  {
    id: "hidrocortisona",
    nombre: "Hidrocortisona",
    nombreGenerico: "Hidrocortisona (succinato sódico)",
    nombresComerciales: ["Solu-Cortef", "Hidrocortisona"],
    familia: "Corticosteroides",
    clasificacion: "Glucocorticoide (actividad mineralo y glucocorticoide)",
    mecanismoAccion: "Glucocorticoide idéntico al cortisol endógeno. Se une al receptor glucocorticoide intracelular modulando la transcripción génica. Potente antiinflamatorio e inmunosupresor. Actividad mineralocorticoide significativa (retención de Na+, pérdida de K+).",
    indicaciones: ["Insuficiencia suprarrenal aguda (crisis addisoniana)", "Shock séptico refractario a vasopresores", "Insuficiencia suprarrenal relativa en UCI", "Anafilaxia (adyuvante)", "Asma aguda severa", "Edema laríngeo", "Estado asmático"],
    contraindicaciones: ["Infección fúngica sistémica (relativa)", "Hipersensibilidad"],
    efectosAdversos: ["Hiperglucemia", "Retención hídrica", "Hipopotasemia", "HTA", "Úlcera péptica", "Inmunosupresión", "Miopatía (uso prolongado)", "Supresión adrenal"],
    interacciones: ["AINE (riesgo GI aditivo)", "Diuréticos (hipopotasemia)", "Insulina/ADO (antagonismo glucémico)", "Anticoagulantes (efecto variable)", "Fenitoína, rifampicina (aumentan metabolismo)"],
    viaAdministracion: ["intravenosa", "intramuscular", "oral"],
    dosis: { adultos: "Crisis adrenal: 100 mg IV bolo, luego 50 mg IV cada 6-8h. Shock séptico: 50 mg IV cada 6h (200 mg/día) x7 días. Anafilaxia: 200 mg IV. Asma: 100-200 mg IV cada 6h", pediatria: "Crisis adrenal: 1-2 mg/kg IV bolo, luego 25-100 mg/día. Asma: 1-2 mg/kg IV cada 6h" },
    presentaciones: ["Polvo para inyección 100 mg", "Polvo para inyección 250 mg", "Polvo para inyección 500 mg", "Comprimidos 10 mg", "Comprimidos 20 mg"],
    embarazo: "Categoría C - Usar si necesario (no cruza bien la placenta, preferida sobre dexa en patología materna)",
    lactancia: "Compatible a dosis fisiológicas",
    cuidadosEnfermeria: ["Bolo IV directo o en 50-100 mL SS en 20-30 min", "En shock séptico: iniciar si hipotensión refractaria a vasopresores", "NO suspender abruptamente si uso >3 días (insuficiencia suprarrenal)", "Monitorizar glucemia (hiperglucemia frecuente)", "Control de electrolitos (K+, Na+)", "Protección gástrica si uso prolongado", "Equivalencia: 20 mg hidrocortisona = 5 mg prednisona = 4 mg metilprednisolona"],
    farmacocinetica: { absorcion: "IV: inmediata. Oral: rápida", distribucion: "Unión a proteínas 90% (transcortina)", metabolismo: "Hepático", eliminacion: "Renal", vidaMedia: "8-12 horas (biológica), 1.5-2h (plasmática)" },
    almacenamiento: "Temperatura ambiente. Reconstituido: usar en 3 días refrigerado",
    unidadId: "u08", capituloId: "c0802",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No toxicidad aguda significativa. Crónico: síndrome de Cushing, supresión adrenal", manejo: "Reducción gradual, soporte metabólico" }
  },
  {
    id: "tacrolimus",
    nombre: "Tacrolimus",
    nombreGenerico: "Tacrolimus",
    nombresComerciales: ["Prograf", "Advagraf", "Envarsus"],
    familia: "Inmunosupresores",
    clasificacion: "Inhibidor de calcineurina (macrólido)",
    mecanismoAccion: "Se une a FKBP-12, y el complejo inhibe la calcineurina, bloqueando la desfosforilación de NFAT y la transcripción de IL-2 y otras citocinas. 10-100 veces más potente que ciclosporina. Inhibe activación de linfocitos T.",
    indicaciones: ["Prevención de rechazo de trasplante (renal, hepático, cardíaco)", "Tratamiento de rechazo agudo", "Dermatitis atópica severa (tópico)", "Síndrome nefrótico refractario", "Enfermedades autoinmunes refractarias"],
    contraindicaciones: ["Hipersensibilidad a tacrolimus o macrólidos", "Uso con ciclosporina (no combinar)"],
    efectosAdversos: ["Nefrotoxicidad (principal)", "Neurotoxicidad (temblor, cefalea, insomnio)", "Hiperglucemia/DM post-trasplante", "Hiperpotasemia", "Hipomagnesemia", "HTA", "Diarrea", "Alopecia", "Linfoma y cáncer de piel (inmunosupresión crónica)"],
    interacciones: ["Inhibidores CYP3A4 (azoles, macrólidos: aumentan niveles drásticamente)", "Inductores CYP3A4 (rifampicina, fenitoína: disminuyen niveles)", "Ciclosporina (contraindicado combinar)", "AINE (nefrotoxicidad aditiva)", "Potasio/diuréticos ahorradores K+ (hiperpotasemia)", "Pomelo/toronja"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "Trasplante renal: oral 0.1-0.2 mg/kg/día dividido en 2 dosis. IV: 0.01-0.05 mg/kg/día en infusión 24h. Ajustar según niveles", pediatria: "0.15-0.3 mg/kg/día oral (niños requieren más que adultos)" },
    presentaciones: ["Cápsulas 0.5 mg", "Cápsulas 1 mg", "Cápsulas 5 mg", "Cápsulas liberación prolongada 0.5 mg", "Cápsulas LP 1 mg", "Cápsulas LP 3 mg", "Cápsulas LP 5 mg", "Ampolla 5 mg/mL", "Pomada 0.03%", "Pomada 0.1%"],
    embarazo: "Categoría C - Usar si beneficio supera riesgo (menor tasa de malformaciones que micofenolato)",
    lactancia: "Se excreta en leche, generalmente no recomendado",
    cuidadosEnfermeria: ["Niveles séricos OBLIGATORIOS (ventana terapéutica estrecha)", "Valle (C0): trasplante renal 5-15 ng/mL (varía según periodo post-trasplante)", "Tomar en AYUNAS o consistentemente con/sin alimentos", "NO con jugo de pomelo", "Formulaciones NO son intercambiables (Prograf ≠ Advagraf ≠ Envarsus)", "Monitorizar: creatinina, K+, Mg++, glucemia semanalmente al inicio", "Vigilar temblor (signo temprano de neurotoxicidad)", "Protección solar estricta (riesgo de cáncer de piel)"],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 20-25% (variable)", distribucion: "Amplia, unión a proteínas 99% (eritrocitos y albúmina)", metabolismo: "Hepático CYP3A4/3A5 (polimorfismo genético importante)", eliminacion: "Fecal y biliar principalmente", vidaMedia: "12 horas (variable 4-41h)" },
    almacenamiento: "Temperatura ambiente. Proteger de la luz y humedad",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Nefrotoxicidad aguda, neurotoxicidad (convulsiones, encefalopatía), hiperpotasemia, hiperglucemia", manejo: "Suspender, monitorizar niveles, soporte renal (no dializable >99% unido a proteínas), anticonvulsivantes si convulsiones" }
  },
  {
    id: "micofenolato",
    nombre: "Micofenolato",
    nombreGenerico: "Micofenolato mofetilo / Ácido micofenólico",
    nombresComerciales: ["CellCept", "Myfortic"],
    familia: "Inmunosupresores",
    clasificacion: "Inhibidor de la síntesis de purinas (IMPDH)",
    mecanismoAccion: "El ácido micofenólico (MPA) inhibe selectivamente la inosina monofosfato deshidrogenasa (IMPDH) tipo II, enzima clave en la síntesis de novo de nucleótidos de guanina. Los linfocitos dependen casi exclusivamente de esta vía (selectividad por linfocitos).",
    indicaciones: ["Prevención de rechazo de trasplante (renal, hepático, cardíaco)", "Nefritis lúpica", "Vasculitis ANCA", "Miastenia gravis refractaria", "Enfermedades autoinmunes refractarias"],
    contraindicaciones: ["Embarazo (teratogénico, categoría D)", "Hipersensibilidad", "Deficiencia de HGPRT"],
    efectosAdversos: ["Diarrea (muy frecuente)", "Náuseas/vómitos", "Leucopenia", "Anemia", "Infecciones oportunistas (CMV)", "Linfoma/neoplasias (uso prolongado)", "Teratogenicidad"],
    interacciones: ["Antiácidos con Mg/Al (reducen absorción)", "Colestiramina (reduce absorción)", "Aciclovir/ganciclovir (competencia tubular, ambos aumentan)", "Azatioprina (no combinar, toxicidad aditiva)", "Rifampicina (reduce niveles 70%)"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "CellCept (mofetilo): 1 g cada 12h oral/IV. Myfortic (sódico): 720 mg cada 12h oral. Trasplante renal: 2 g/día. Nefritis lúpica: 2-3 g/día", pediatria: "Trasplante: 600 mg/m² cada 12h (máx 2 g/día)" },
    presentaciones: ["Cápsulas 250 mg (CellCept)", "Comprimidos 500 mg (CellCept)", "Comprimidos EC 180 mg (Myfortic)", "Comprimidos EC 360 mg (Myfortic)", "Polvo para suspensión 200 mg/mL", "Ampolla IV 500 mg"],
    embarazo: "CONTRAINDICADO (Categoría D) - Anticoncepción obligatoria, test negativo antes de iniciar",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: ["Hemograma SEMANAL el primer mes, QUINCENAL meses 2-3, luego MENSUAL", "Si neutrófilos <1300: considerar reducir dosis o suspender", "CellCept y Myfortic NO son intercambiables", "Tomar con el estómago vacío (CellCept) o con alimentos (Myfortic)", "Mujeres fértiles: 2 métodos anticonceptivos simultáneos", "Vigilar diarrea (puede requerir cambio a Myfortic EC)", "Profilaxis CMV si donante+/receptor-"],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 94% (MPA tras hidrólisis de mofetilo)", distribucion: "Unión a proteínas 97% (MPA)", metabolismo: "Hepático glucuronidación a MPAG (inactivo), recirculación enterohepática", eliminacion: "Renal 93% (como MPAG)", vidaMedia: "MPA: 17.9 horas" },
    almacenamiento: "Temperatura ambiente. Manipular con guantes (teratogénico)",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mielosupresión severa, infecciones oportunistas, GI severos", manejo: "Suspender, soporte hematológico, G-CSF si neutropenia severa, no significativamente dializable" }
  },
  {
    id: "rituximab",
    nombre: "Rituximab",
    nombreGenerico: "Rituximab",
    nombresComerciales: ["MabThera", "Rituxan"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-CD20 (anticuerpo monoclonal quimérico)",
    mecanismoAccion: "Se une al antígeno CD20 en la superficie de linfocitos B pre-B y B maduros. Destruye células B por citotoxicidad dependiente de complemento (CDC), citotoxicidad celular dependiente de anticuerpo (ADCC) y apoptosis directa.",
    indicaciones: ["Linfoma no Hodgkin difuso de células B grandes", "Linfoma folicular", "Leucemia linfocítica crónica", "Artritis reumatoide refractaria", "Granulomatosis con poliangeítis (Wegener)", "Pénfigo vulgar", "PTI refractaria"],
    contraindicaciones: ["Infección activa severa", "Inmunodeficiencia severa", "ICC severa (clase IV NYHA)", "Hepatitis B activa"],
    efectosAdversos: ["Reacciones a la infusión (muy frecuente en 1ra dosis)", "Infecciones", "Neutropenia tardía", "Reactivación de hepatitis B (fatal)", "LMP (muy rara)", "Hipogammaglobulinemia", "Síndrome de lisis tumoral (en onco)"],
    interacciones: ["Vacunas vivas (contraindicadas)", "Otros inmunosupresores (efecto aditivo)", "Cisplatino (puede aumentar nefrotoxicidad)"],
    viaAdministracion: ["intravenosa", "subcutanea"],
    dosis: { adultos: "Linfoma: 375 mg/m² IV cada semana x4 o cada 21 días según protocolo. AR: 1000 mg IV días 1 y 15, repetir cada 6 meses. Vasculitis: 375 mg/m² semanal x4. SC: 1400 mg SC (tras 1ra dosis IV)", pediatria: "375 mg/m² IV (según indicación)" },
    presentaciones: ["Concentrado IV 100 mg/10 mL", "Concentrado IV 500 mg/50 mL", "Solución SC 1400 mg/11.7 mL"],
    embarazo: "Evitar, anticoncepción 12 meses post-última dosis",
    lactancia: "No recomendado",
    cuidadosEnfermeria: ["Premedicar con paracetamol, antihistamínico y corticoide IV (30-60 min antes)", "1ra infusión: iniciar 50 mg/h, escalar cada 30 min (+50 mg/h) hasta 400 mg/h", "Screening hepatitis B OBLIGATORIO (HBsAg, anti-HBc)", "Profilaxis antiviral si anti-HBc positivo", "Monitorizar durante infusión y 1h post (reacciones 80% en 1ra dosis)", "Inmunoglobulinas séricas cada 6 meses (hipogammaglobulinemia)", "Vigilar infecciones tardías (depleción B dura 6-12 meses)"],
    farmacocinetica: { absorcion: "IV: 100%. SC: biodisponibilidad ~70%", distribucion: "Compartimento vascular principalmente", metabolismo: "Reticuloendotelial (como IgG)", eliminacion: "Variable, aclaramiento no lineal", vidaMedia: "22 días (rango 6-52 días)" },
    almacenamiento: "Refrigerar 2-8°C. No congelar. Proteger de la luz",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Depleción B profunda, infecciones severas, hipogammaglobulinemia", manejo: "Soporte antimicrobiano, inmunoglobulina IV si hipogammaglobulinemia sintomática" }
  },
  {
    id: "infliximab",
    nombre: "Infliximab",
    nombreGenerico: "Infliximab",
    nombresComerciales: ["Remicade", "Remsima", "Inflectra"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-TNFα (anticuerpo monoclonal quimérico)",
    mecanismoAccion: "Se une al TNF-α soluble y transmembrana con alta afinidad, neutralizando su actividad proinflamatoria. Induce apoptosis de células que expresan TNF transmembrana. Lisa células productoras de TNF por CDC y ADCC.",
    indicaciones: ["Enfermedad de Crohn moderada-severa", "Colitis ulcerosa moderada-severa", "Artritis reumatoide (con MTX)", "Espondilitis anquilosante", "Artritis psoriásica", "Psoriasis en placas severa"],
    contraindicaciones: ["TB activa no tratada", "Infecciones graves activas", "ICC moderada-severa (clase III-IV NYHA)", "Hipersensibilidad"],
    efectosAdversos: ["Infecciones (TB reactivada, fúngicas invasivas)", "Reacciones a la infusión", "Reacciones tardías (artralgia, fiebre 3-12 días post)", "Anticuerpos anti-infliximab (ATI)", "Hepatotoxicidad", "Linfoma", "Empeoramiento de ICC"],
    interacciones: ["MTX (reduce formación de ATI, combinación recomendada)", "Vacunas vivas (contraindicadas)", "Anakinra, abatacept (no combinar)", "Otros biológicos (no combinar)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Crohn/CU: 5 mg/kg IV semanas 0, 2, 6, luego cada 8 semanas. AR: 3 mg/kg semanas 0, 2, 6, luego cada 8 sem (con MTX). Puede escalar a 10 mg/kg o acortar intervalo", pediatria: "≥6 años Crohn/CU: 5 mg/kg semanas 0, 2, 6, luego cada 8 sem" },
    presentaciones: ["Polvo para infusión 100 mg"],
    embarazo: "No recomendado en 3er trimestre (cruza placenta activamente). Suspender a semana 20-22 si posible",
    lactancia: "Probablemente compatible (mínimo en leche)",
    cuidadosEnfermeria: ["Screening TB OBLIGATORIO antes de iniciar (PPD o IGRA + Rx tórax)", "Si TB latente: tratar ≥1 mes antes de iniciar infliximab", "Infundir en ≥2 horas (puede acelerarse a 1h si bien tolerado en dosis previas)", "Monitorizar durante infusión y 1-2h post", "Premedicar con paracetamol, antihistamínico ± corticoide si reacciones previas", "Monitorizar niveles de infliximab y ATI si pérdida de respuesta", "Vacunaciones al día ANTES de iniciar tratamiento"],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Vd 3-6 L", metabolismo: "Reticuloendotelial", eliminacion: "Degradación proteolítica", vidaMedia: "7.7-9.5 días" },
    almacenamiento: "Refrigerar 2-8°C. Reconstituido: usar en 3h",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Inmunosupresión severa, infecciones oportunistas", manejo: "Soporte antimicrobiano, observación prolongada (vida media ~8 días)" }
  },
  {
    id: "ciclofosfamida",
    nombre: "Ciclofosfamida",
    nombreGenerico: "Ciclofosfamida",
    nombresComerciales: ["Endoxan", "Cytoxan"],
    familia: "Antineoplásicos",
    clasificacion: "Agente alquilante (mostaza nitrogenada)",
    mecanismoAccion: "Prodroga activada hepáticamente a 4-OH-ciclofosfamida y mostaza fosforamida, que forma enlaces cruzados con el ADN entre las cadenas y dentro de ellas, impidiendo la replicación y transcripción. También genera acroleína (responsable de cistitis hemorrágica).",
    indicaciones: ["Linfomas", "Leucemias", "Cáncer de mama", "Cáncer de ovario", "Nefritis lúpica severa", "Vasculitis ANCA", "Preparación para trasplante de médula ósea", "Síndrome nefrótico refractario"],
    contraindicaciones: ["Mielosupresión severa", "Cistitis hemorrágica activa", "Obstrucción del tracto urinario", "Infección activa severa"],
    efectosAdversos: ["Mielosupresión (nadir 8-14 días)", "Cistitis hemorrágica", "Náuseas/vómitos (alta emetogenicidad)", "Alopecia", "Infertilidad", "Cistitis hemorrágica tardía", "Carcinogénesis (leucemia/vejiga)", "SIADH", "Cardiotoxicidad (dosis altas)"],
    interacciones: ["Alopurinol (aumenta mielosupresión)", "Barbitúricos (aumentan activación)", "Cloranfenicol (reduce activación)", "Suxametonio (prolonga bloqueo NM)", "Warfarina (efecto impredecible)"],
    viaAdministracion: ["intravenosa", "oral"],
    dosis: { adultos: "Oncología: variable según protocolo, 500-1500 mg/m² IV. Pulsos de nefritis lúpica: 500-1000 mg/m² IV mensual x6. Oral: 1-3 mg/kg/día", pediatria: "Variable según protocolo, 500-1000 mg/m² IV" },
    presentaciones: ["Polvo para inyección 200 mg", "Polvo para inyección 500 mg", "Polvo para inyección 1 g", "Comprimidos 50 mg"],
    embarazo: "Categoría D - Teratogénico, contraindicado",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: ["HIDRATACIÓN agresiva (≥2-3 L/día) para prevenir cistitis hemorrágica", "MESNA con dosis ≥1 g/m² (protege vejiga)", "Antiemético profiláctico (alta emetogenicidad): ondansetrón + dexametasona + NK1", "Hemograma antes de cada ciclo (nadir día 8-14, recuperación día 21)", "Administrar por la MAÑANA (mayor eliminación vesical antes de acostarse)", "Educción: orinar frecuentemente durante 24-48h post-dosis", "Preservación de fertilidad: criopreservación previa en edad fértil"],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad >75%", distribucion: "Amplia, unión a proteínas 20%", metabolismo: "Hepático CYP2B6 a 4-OH-ciclofosfamida (activo) y acroleína (tóxica)", eliminacion: "Renal 10-20% sin cambios", vidaMedia: "4-6 horas" },
    almacenamiento: "Temperatura ambiente. Reconstituido: 24h TA o 6 días refrigerado",
    unidadId: "u11", capituloId: "c1102",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mielosupresión profunda, cistitis hemorrágica, cardiotoxicidad, SIADH", manejo: "Soporte hematológico, G-CSF, MESNA, hidratación masiva, no significativamente dializable" }
  },
  {
    id: "doxorrubicina",
    nombre: "Doxorrubicina",
    nombreGenerico: "Doxorrubicina clorhidrato",
    nombresComerciales: ["Adriamicina", "Doxil", "Caelyx"],
    familia: "Antineoplásicos",
    clasificacion: "Antraciclina (antibiótico antitumoral)",
    mecanismoAccion: "Se intercala en el ADN e inhibe la topoisomerasa II, causando roturas de doble cadena. Genera radicales libres que dañan membranas y ADN. Cardiotoxicidad mediada por radicales libres y daño mitocondrial en cardiomiocitos.",
    indicaciones: ["Cáncer de mama", "Linfomas Hodgkin y no Hodgkin", "Sarcomas de tejidos blandos y óseos", "Leucemias agudas", "Cáncer de ovario", "Cáncer de vejiga", "Mieloma múltiple", "Hepatocarcinoma (Doxil)"],
    contraindicaciones: ["Mielosupresión severa", "ICC preexistente", "Dosis acumulativa máxima alcanzada (450-550 mg/m²)", "Infarto reciente", "Arritmias severas"],
    efectosAdversos: ["Cardiotoxicidad (aguda y crónica acumulativa)", "Mielosupresión (nadir 10-14 días)", "Náuseas/vómitos", "Alopecia (casi universal)", "Mucositis", "Coloración roja de orina (48h)", "Eritrodisestesia palmoplantar (liposomal)", "Extravasación: NECROSIS tisular (vesicante)"],
    interacciones: ["Trastuzumab (cardiotoxicidad sinérgica)", "Ciclofosfamida (cardiotoxicidad aditiva)", "Paclitaxel (aumenta niveles si administrado antes)", "Verapamilo (aumenta cardiotoxicidad)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Variable según protocolo: 60-75 mg/m² cada 21 días, o 20 mg/m² semanal. Liposomal: 20-50 mg/m² cada 28 días. Dosis acumulativa máxima: 450-550 mg/m²", pediatria: "30-75 mg/m² según protocolo" },
    presentaciones: ["Polvo para inyección 10 mg", "Polvo para inyección 50 mg", "Solución 2 mg/mL", "Liposomal (Doxil/Caelyx) 2 mg/mL"],
    embarazo: "Categoría D - Contraindicado",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: ["VESICANTE: verificar permeabilidad de vía IV antes y durante (extravasación = necrosis)", "Si extravasación: dexrazoxano tópico + frío local (antídoto)", "NO convencional y liposomal son DIFERENTES: NO intercambiar", "Ecocardiograma/MUGA basal y cada 3-6 meses o cada 300 mg/m²", "Antiemético profiláctico (alta emetogenicidad)", "Informar: orina roja 1-2 días (NO es hematuria)", "Controlar dosis acumulativa total: registrar en historia", "Administrar por vía central preferiblemente"],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Amplia, unión a proteínas 75%, NO cruza BHE", metabolismo: "Hepático a doxorrubicinol (activo)", eliminacion: "Biliar 40-50%, renal 5-12%", vidaMedia: "20-48 horas" },
    almacenamiento: "Refrigerar. Proteger de la luz. Reconstituido: 7 días refrigerado",
    unidadId: "u11", capituloId: "c1102",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mielosupresión profunda, mucositis severa, cardiotoxicidad aguda", manejo: "Soporte hematológico, G-CSF, soporte cardíaco, no dializable" }
  },
  {
    id: "imatinib",
    nombre: "Imatinib",
    nombreGenerico: "Imatinib mesilato",
    nombresComerciales: ["Gleevec", "Glivec"],
    familia: "Antineoplásicos",
    clasificacion: "Inhibidor de tirosina quinasa (ITK) de primera generación",
    mecanismoAccion: "Inhibe selectivamente la tirosina quinasa BCR-ABL (fusión del cromosoma Filadelfia), c-KIT y PDGFR. Se une al sitio de unión de ATP de la quinasa en conformación inactiva, bloqueando la proliferación tumoral. Revolucionó el tratamiento de LMC.",
    indicaciones: ["Leucemia mieloide crónica (LMC) Ph+", "Leucemia linfoblástica aguda Ph+", "Tumor del estroma gastrointestinal (GIST)", "Dermatofibrosarcoma protuberans", "Síndrome hipereosinofílico con fusión FIP1L1-PDGFRα"],
    contraindicaciones: ["Hipersensibilidad"],
    efectosAdversos: ["Edema (periorbital, MMII)", "Náuseas", "Diarrea", "Calambres musculares", "Erupción cutánea", "Mielosupresión", "Hepatotoxicidad", "Retención hídrica/derrame pleural", "Cardiotoxicidad (rara)"],
    interacciones: ["Inhibidores CYP3A4 (aumentan niveles)", "Inductores CYP3A4 (reducen niveles: evitar hierba de San Juan)", "Warfarina (usar HBPM en su lugar)", "Paracetamol (imatinib inhibe su glucuronidación)", "Simvastatina (aumenta niveles 3x)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "LMC fase crónica: 400 mg/día. LMC fase acelerada/blástica: 600-800 mg/día. GIST: 400 mg/día, puede escalar a 800 mg/día. LLA Ph+: 600 mg/día", pediatria: "LMC: 260-340 mg/m²/día (máx 600 mg)" },
    presentaciones: ["Comprimidos 100 mg", "Comprimidos 400 mg"],
    embarazo: "Categoría D - Contraindicado (teratogénico)",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: ["Tomar CON alimentos y un vaso grande de agua (reduce irritación GI)", "Hemograma quincenal primer mes, luego mensual", "Función hepática mensual los primeros 6 meses", "Monitorizar peso diario (retención hídrica)", "Evaluar respuesta: citogenética a 3-6 meses, molecular a 12 meses", "Comprimidos se pueden disolver en agua/jugo de manzana si dificultad para tragar", "Adherencia CRÍTICA: respuesta correlaciona directamente con cumplimiento"],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 98%", distribucion: "Unión a proteínas 95%", metabolismo: "Hepático CYP3A4 a N-desmetil-imatinib (activo)", eliminacion: "Fecal 68%, renal 13%", vidaMedia: "18 horas (metabolito activo: 40 horas)" },
    almacenamiento: "Temperatura ambiente, proteger de la humedad",
    unidadId: "u11", capituloId: "c1102",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mielosupresión, hepatotoxicidad, retención hídrica severa, calambres", manejo: "Suspender, soporte hematológico, monitorizar función hepática, diuréticos si retención" }
  },
  {
    id: "hierro_sacarosa",
    nombre: "Hierro Sacarosa",
    nombreGenerico: "Hierro sacarosa (complejo de hidróxido de hierro(III)-sacarosa)",
    nombresComerciales: ["Venofer"],
    familia: "Antianémicos",
    clasificacion: "Hierro parenteral (complejo de hierro polisacárido)",
    mecanismoAccion: "Complejo de hierro(III) con sacarosa que libera hierro de forma controlada al sistema reticuloendotelial. El hierro se transfiere a transferrina y se incorpora a hemoglobina y depósitos de ferritina.",
    indicaciones: ["Anemia ferropénica cuando hierro oral no es tolerable/suficiente", "Anemia en enfermedad renal crónica (pre-diálisis, HD, DP)", "Anemia ferropénica en embarazo (2do-3er trimestre)", "Anemia perioperatoria", "Deficiencia de hierro en IC"],
    contraindicaciones: ["Sobrecarga de hierro (hemocromatosis)", "Anemias no ferropénicas", "1er trimestre de embarazo", "Hipersensibilidad", "Infección activa aguda"],
    efectosAdversos: ["Hipotensión (infusión)", "Náuseas", "Cefalea", "Mareo", "Disgeusia (sabor metálico)", "Dolor en sitio de inyección", "Reacción anafilactoide (rara, <0.1%)", "Hipofosfatemia (menos que hierro carboximaltosa)"],
    interacciones: ["Hierro oral (suspender 5 días antes, no combinar)", "Dimercaprol (forma complejo tóxico)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "100-200 mg IV por sesión, 1-3 veces/semana. Infundir en 15-60 min diluido en 100-200 mL SS 0.9%. Dosis total según déficit: fórmula de Ganzoni. Dosis test NO requerida", pediatria: "≥2 años: 3 mg/kg/sesión (máx 200 mg), en 100 mL SS en 1h" },
    presentaciones: ["Ampolla 100 mg/5 mL (20 mg Fe/mL)"],
    embarazo: "Compatible a partir del 2do trimestre. Contraindicado en 1er trimestre",
    lactancia: "Compatible",
    cuidadosEnfermeria: ["Diluir en SS 0.9% EXCLUSIVAMENTE (no dextrosa)", "Infundir en 15-60 min (100 mg en ≥15 min)", "Monitorizar PA durante infusión (hipotensión)", "Observar 30 min post-infusión", "NO administrar si infección activa (hierro alimenta bacterias)", "Ferritina y saturación de transferrina a las 2-4 semanas post-reposición", "No es necesaria dosis test (perfil de seguridad mejor que dextran)"],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Captado por sistema reticuloendotelial (hígado, bazo, médula)", metabolismo: "Liberación lenta de hierro del complejo", eliminacion: "Renal <5% (como complejo intacto)", vidaMedia: "Complejo: 6 horas. Hierro: incorporación gradual" },
    almacenamiento: "Temperatura ambiente. No refrigerar. Diluido: usar en 12h",
    unidadId: "u05", capituloId: "c0501",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Sobrecarga de hierro: hemosiderosis, daño hepático, cardiotoxicidad", manejo: "Deferoxamina (quelante de hierro), monitorizar ferritina, soporte hepático/cardíaco" }
  },
  {
    id: "prednisolona",
    nombre: "Prednisolona",
    nombreGenerico: "Prednisolona",
    nombresComerciales: ["Meticortelone", "Prelone"],
    familia: "Corticosteroides",
    clasificacion: "Glucocorticoide sistémico (potencia intermedia)",
    mecanismoAccion: "Glucocorticoide sintético, metabolito activo de la prednisona. Se une al receptor glucocorticoide, traslocándose al núcleo y modulando la transcripción de genes antiinflamatorios. Menor actividad mineralocorticoide que hidrocortisona.",
    indicaciones: ["Asma aguda y crónica", "Enfermedades autoinmunes", "Artritis reumatoide", "Nefritis lúpica", "Enfermedad inflamatoria intestinal", "Enfermedades alérgicas severas", "Crup (laringotraqueobronquitis)"],
    contraindicaciones: ["Infección fúngica sistémica", "Vacunas vivas (con dosis inmunosupresoras)", "Hipersensibilidad"],
    efectosAdversos: ["Hiperglucemia", "Aumento de peso", "Osteoporosis", "Supresión adrenal", "Cushing iatrogénico", "Úlcera péptica", "Cataratas/glaucoma", "Retraso de crecimiento (pediátrico)", "Cambios de humor"],
    interacciones: ["AINE (riesgo GI)", "Diuréticos (hipopotasemia)", "Hipoglucemiantes (antagonismo)", "Fenitoína/rifampicina (reducen niveles)", "Vacunas vivas (contraindicadas con >2 mg/kg/día)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Variable: 5-60 mg/día según indicación. Asma exacerbación: 40-50 mg/día x 5-7 días", pediatria: "Asma: 1-2 mg/kg/día (máx 60 mg) x 3-5 días. Crup: 1 mg/kg dosis única. Nefrótico: 2 mg/kg/día x 4-6 semanas" },
    presentaciones: ["Comprimidos 5 mg", "Comprimidos 20 mg", "Solución oral 5 mg/5 mL", "Solución oral 15 mg/5 mL"],
    embarazo: "Categoría C - Compatible si necesario (no cruza placenta eficientemente a diferencia de dexa/beta)",
    lactancia: "Compatible a dosis bajas (<20 mg/día), esperar 4h si dosis altas",
    cuidadosEnfermeria: ["Preferida sobre prednisona en hepatopatía (no requiere activación hepática)", "Administrar por la mañana (mimetiza ritmo circadiano del cortisol)", "Tomar con alimentos", "Si >7-10 días: REDUCCIÓN GRADUAL obligatoria", "Suplementar calcio + vitamina D si uso prolongado", "Monitorizar glucemia, PA, peso", "En pediatría: monitorizar crecimiento y curvas de talla", "Formulación líquida ideal para pediatría"],
    farmacocinetica: { absorcion: "Oral: rápida y completa", distribucion: "Unión a proteínas 70-90%", metabolismo: "Hepático", eliminacion: "Renal", vidaMedia: "Plasmática 2-3.5h, biológica 12-36h" },
    almacenamiento: "Temperatura ambiente. Solución oral: según fabricante",
    unidadId: "u08", capituloId: "c0802",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Agudamente bien tolerado. Crónico: Cushing, supresión adrenal, osteoporosis, hiperglucemia", manejo: "Reducción gradual, tratamiento de complicaciones" }
  },
  {
    id: "dipiridamol",
    nombre: "Dipiridamol",
    nombreGenerico: "Dipiridamol",
    nombresComerciales: ["Persantin", "Aggrenox"],
    familia: "Antiagregantes plaquetarios",
    clasificacion: "Inhibidor de fosfodiesterasa / Inhibidor de recaptación de adenosina",
    mecanismoAccion: "Inhibe la fosfodiesterasa (PDE3 y PDE5) en plaquetas, aumentando AMPc y GMPc. También inhibe la recaptación de adenosina, potenciando su efecto antiplaquetario y vasodilatador. Vasodilatador coronario.",
    indicaciones: ["Prevención secundaria de ACV (con aspirina)", "Prótesis valvulares mecánicas (con warfarina)", "Prueba de estrés farmacológico (perfusión miocárdica)", "Profilaxis de tromboembolismo en válvulas cardíacas"],
    contraindicaciones: ["Hipersensibilidad", "Hipotensión severa", "Enfermedad coronaria severa inestable (para prueba de estrés)"],
    efectosAdversos: ["Cefalea", "Mareo", "Hipotensión", "Náuseas", "Diarrea", "Rubor", "Angina (vasodilatación coronaria con robo coronario)"],
    interacciones: ["Adenosina (potencia efecto, reducir dosis de adenosina)", "Anticoagulantes (efecto aditivo)", "Teofilina (antagoniza efecto, contraindicado en prueba de estrés)", "Antihipertensivos (hipotensión aditiva)"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "ACV secundaria: 200 mg cada 12h (o Aggrenox: 200 mg + ASA 25 mg cada 12h). Válvulas: 75-100 mg cada 6h. Prueba estrés: 0.56 mg/kg IV en 4 min", pediatria: "3-6 mg/kg/día dividido en 3 dosis" },
    presentaciones: ["Comprimidos 75 mg", "Comprimidos 100 mg", "Cápsulas liberación prolongada + ASA (Aggrenox)", "Ampolla 10 mg/2 mL"],
    embarazo: "Categoría B",
    lactancia: "Se excreta en leche, precaución",
    cuidadosEnfermeria: ["Administrar con estómago vacío (1h antes de comidas) para mejor absorción", "Cefalea es muy frecuente al inicio (se reduce con el tiempo)", "En prueba de estrés: tener aminofilina IV disponible como antídoto", "Monitorizar PA (hipotensión)", "Combinado con ASA para prevención de ACV (Aggrenox)", "No usar como sustituto de aspirina en enfermedad coronaria"],
    farmacocinetica: { absorcion: "Oral: variable, biodisponibilidad 37-66%", distribucion: "Unión a proteínas 91-99%", metabolismo: "Hepático por glucuronidación", eliminacion: "Biliar/fecal >95%", vidaMedia: "10-12 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u05", capituloId: "c0502",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipotensión, taquicardia, rubor, angina", manejo: "Aminofilina IV 50-250 mg (antídoto), vasopresores, posición Trendelenburg" }
  }
];

// Agregar fármacos con deduplicación
let added = 0;
for (const d of newDrugs) {
  if (existingIds.has(d.id)) continue;
  d.searchText = mkSearch(d);
  drugs.push(d);
  existingIds.add(d.id);
  for (const u of cats.unidades) {
    if (u.id === d.unidadId) {
      const cap = u.capitulos.find(c => c.id === d.capituloId);
      if (cap && !cap.drugIds.includes(d.id)) cap.drugIds.push(d.id);
    }
  }
  added++;
}

fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log(`Added: ${added}. Total drugs: ${drugs.length}`);