const fs = require('fs');
const path = require('path');

const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath  = path.join(__dirname, '..', 'src', 'data', 'categories.json');

const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats  = JSON.parse(fs.readFileSync(catsPath, 'utf8'));

const existingIds = new Set(drugs.map(d => d.id));

function mkSearch(d) {
  return [d.nombre, d.nombreGenerico, ...d.nombresComerciales, d.familia, d.clasificacion, ...d.indicaciones]
    .join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

const newDrugs = [
  // ── Antiinfecciosos ──
  {
    id: "isavuconazol",
    nombre: "Isavuconazol",
    nombreGenerico: "Isavuconazonio (sulfato)",
    nombresComerciales: ["Cresemba"],
    familia: "Antifúngicos",
    clasificacion: "Triazol de segunda generación",
    mecanismoAccion: "Inhibe la 14-alfa-lanosterol demetilasa (CYP51) fúngica, bloqueando la síntesis de ergosterol esencial para la membrana celular fúngica. Amplio espectro: Aspergillus, Mucorales, Candida, hongos dimórficos.",
    indicaciones: ["Aspergilosis invasiva", "Mucormicosis (alternativa a anfotericina B)", "Infecciones fúngicas invasivas por hongos filamentosos"],
    contraindicaciones: ["Uso concomitante con ketoconazol, inhibidores potentes de CYP3A4", "Síndrome de QT corto familiar", "Insuficiencia hepática severa (Child-Pugh C)"],
    efectosAdversos: ["Náuseas", "Vómitos", "Diarrea", "Cefalea", "Elevación de transaminasas", "Hipopotasemia", "Acortamiento del QT (único entre azoles)", "Reacciones a la infusión"],
    interacciones: ["Rifampicina (contraindicado, reduce niveles 97%)", "Ketoconazol (contraindicado)", "Ciclosporina, tacrolimus (aumenta niveles)", "Warfarina", "Midazolam"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "Carga: 200 mg cada 8h por 6 dosis (48h), luego 200 mg/día. IV u oral. No requiere ajuste renal ni hepático leve-moderado", pediatria: "Datos limitados, en estudio ≥1 año" },
    presentaciones: ["Cápsulas 100 mg (equivale a 186 mg de isavuconazonio)", "Polvo para infusión 200 mg"],
    embarazo: "Contraindicado (teratogénico en animales)",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Cápsulas: tragar enteras, NO abrir, triturar ni masticar",
      "IV: reconstituir con agua estéril, luego diluir en SS 0.9%, infundir en ≥1h",
      "NO requiere monitorización de niveles (farmacocinética predecible)",
      "Ventaja: ACORTA el QT (a diferencia de voriconazol que lo prolonga)",
      "Sin restricción por insuficiencia renal (IV sin ciclodextrina)",
      "Monitorizar función hepática y electrolitos",
      "Menor interacción visual que voriconazol"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 98%, no afectada por alimentos", distribucion: "Vd >450 L, unión a proteínas >99%", metabolismo: "Hepático CYP3A4/3A5 y UGTs", eliminacion: "Fecal 46%, renal 46%", vidaMedia: "130 horas" },
    almacenamiento: "Temperatura ambiente (cápsulas). IV reconstituido: usar en 1h",
    unidadId: "u01", capituloId: "c0103",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hepatotoxicidad, reacciones cutáneas", manejo: "No dializable, soporte hepático, monitorización prolongada por vida media larga" }
  },
  {
    id: "caspofungina",
    nombre: "Caspofungina",
    nombreGenerico: "Caspofungina (acetato)",
    nombresComerciales: ["Cancidas"],
    familia: "Antifúngicos",
    clasificacion: "Equinocandina",
    mecanismoAccion: "Inhibe la síntesis de 1,3-β-D-glucano, componente esencial de la pared celular fúngica (ausente en mamíferos). Fungicida contra Candida spp., fungistática contra Aspergillus. No activa contra Mucorales ni Cryptococcus.",
    indicaciones: ["Candidemia y candidiasis invasiva", "Aspergilosis invasiva (rescate)", "Candidiasis esofágica", "Terapia empírica antifúngica en pacientes febriles neutropénicos"],
    contraindicaciones: ["Hipersensibilidad a equinocandinas"],
    efectosAdversos: ["Fiebre", "Flebitis", "Cefalea", "Náuseas", "Elevación de transaminasas", "Hipopotasemia", "Erupción cutánea", "Síndrome de liberación de histamina (infusión rápida)"],
    interacciones: ["Ciclosporina (aumenta niveles de caspofungina, monitorizar transaminasas)", "Rifampicina, fenitoína, dexametasona (aumentar dosis a 70 mg/día)", "Tacrolimus (disminuye niveles de tacrolimus 20%)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Carga: 70 mg IV día 1, luego 50 mg/día. Insuficiencia hepática moderada: 35 mg/día mantenimiento. Con inductores: 70 mg/día", pediatria: "3 meses-17 años: 70 mg/m² día 1, luego 50 mg/m²/día (máx 70 mg)" },
    presentaciones: ["Polvo para infusión 50 mg", "Polvo para infusión 70 mg"],
    embarazo: "Categoría C",
    lactancia: "Precaución (datos insuficientes)",
    cuidadosEnfermeria: [
      "Infundir LENTAMENTE en 1 hora (riesgo histamina si rápido)",
      "Diluir en SS 0.9%, Ringer o D5W (NO diluir con dextrosa con otros medicamentos)",
      "NO administrar en bolo",
      "No requiere ajuste en insuficiencia renal ni diálisis",
      "Monitorizar función hepática (especialmente si co-administra con ciclosporina)",
      "Compatible con línea central o periférica"
    ],
    farmacocinetica: { absorcion: "IV: 100%", distribucion: "Unión a proteínas 97%, Vd 12 L", metabolismo: "Hidrólisis y N-acetilación (no CYP450 significativo)", eliminacion: "Renal 41%, fecal 35% (como metabolitos)", vidaMedia: "9-11 horas (fase beta), 45h (fase gamma)" },
    almacenamiento: "Refrigerar polvo. Reconstituido: 24h a TA o 48h refrigerado",
    unidadId: "u01", capituloId: "c0103",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No hay experiencia con sobredosis", manejo: "No dializable, soporte general" }
  },
  {
    id: "nitazoxanida",
    nombre: "Nitazoxanida",
    nombreGenerico: "Nitazoxanida",
    nombresComerciales: ["Daxon", "Colufase", "Nitax", "Paramix"],
    familia: "Antiparasitarios",
    clasificacion: "Antiprotozoario/antihelmíntico de amplio espectro",
    mecanismoAccion: "Se metaboliza a tizoxanida, que interfiere con la enzima piruvato:ferredoxina oxidorreductasa (PFOR) dependiente del metabolismo anaeróbico del parásito. Actividad contra protozoos y helmintos.",
    indicaciones: ["Giardiasis", "Criptosporidiosis", "Amebiasis intestinal", "Helmintiasis intestinales", "Gastroenteritis viral (rotavirus, norovirus)", "Infección por Clostridium difficile (off-label)"],
    contraindicaciones: ["Hipersensibilidad"],
    efectosAdversos: ["Dolor abdominal", "Diarrea", "Náuseas", "Cefalea", "Coloración amarillo-verdosa de orina", "Vómitos"],
    interacciones: ["Warfarina (alta unión a proteínas, monitorizar INR)", "Medicamentos altamente unidos a proteínas"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "500 mg cada 12h por 3 días con alimentos", pediatria: "1-3 años: 100 mg cada 12h x 3 días. 4-11 años: 200 mg cada 12h x 3 días. ≥12 años: dosis adulto" },
    presentaciones: ["Comprimidos 500 mg", "Suspensión oral 100 mg/5 mL"],
    embarazo: "Categoría B",
    lactancia: "Precaución (datos limitados)",
    cuidadosEnfermeria: [
      "Administrar CON alimentos (mejora absorción)",
      "Tratamiento corto: solo 3 días",
      "Informar sobre coloración amarillo-verdosa de orina (normal)",
      "Agitar bien la suspensión antes de usar",
      "Eficaz contra Giardia resistente a metronidazol",
      "Monitorizar resolución de diarrea"
    ],
    farmacocinetica: { absorcion: "Oral con alimentos, se convierte rápidamente a tizoxanida", distribucion: "Unión a proteínas >99% (tizoxanida)", metabolismo: "Hepático: nitazoxanida → tizoxanida → glucurónido de tizoxanida", eliminacion: "Renal, fecal y biliar", vidaMedia: "Tizoxanida: 7.3 horas" },
    almacenamiento: "Temperatura ambiente. Suspensión: refrigerar tras abrir, usar en 7 días",
    unidadId: "u01", capituloId: "c0104",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Náuseas, vómitos, diarrea", manejo: "Soporte sintomático, lavado gástrico si reciente" }
  },
  {
    id: "miltefosina",
    nombre: "Miltefosina",
    nombreGenerico: "Miltefosina",
    nombresComerciales: ["Impavido"],
    familia: "Antiparasitarios",
    clasificacion: "Alquilfosfolípido (antileishmaniásico oral)",
    mecanismoAccion: "Altera el metabolismo de fosfolípidos y esteroles de la membrana del parásito Leishmania. Induce apoptosis parasitaria. Único tratamiento oral disponible para leishmaniasis.",
    indicaciones: ["Leishmaniasis visceral (kala-azar)", "Leishmaniasis cutánea", "Leishmaniasis mucocutánea", "Meningoencefalitis amebiana por Naegleria fowleri (off-label, combinado)"],
    contraindicaciones: ["Embarazo (teratogénico)", "Mujeres en edad fértil sin anticoncepción", "Sjögren con queratoconjuntivitis severa", "Insuficiencia hepática o renal severa"],
    efectosAdversos: ["Náuseas/vómitos (muy frecuente)", "Diarrea", "Dolor abdominal", "Elevación de transaminasas", "Elevación de creatinina", "Mareo", "Disminución transitoria de plaquetas"],
    interacciones: ["No interacciones significativas documentadas"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "Leishmaniasis visceral: 2.5 mg/kg/día (máx 150 mg) por 28 días. Cutánea: 2.5 mg/kg/día por 28 días", pediatria: "≥2 años: 2.5 mg/kg/día (máx 150 mg) por 28 días" },
    presentaciones: ["Cápsulas 10 mg", "Cápsulas 50 mg"],
    embarazo: "Categoría X - Absolutamente contraindicado (teratogénico)",
    lactancia: "Contraindicado",
    cuidadosEnfermeria: [
      "Administrar con alimentos (reduce náuseas)",
      "Anticoncepción obligatoria en mujeres fértiles durante y 5 meses post-tratamiento",
      "Test de embarazo negativo antes de iniciar",
      "Monitorizar función hepática y renal semanal",
      "Monitorizar hemograma (plaquetas)",
      "Tratamiento 28 días completos, no suspender prematuramente",
      "Antieméticos profilácticos si náuseas severas"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad ~82%", distribucion: "Amplia, acumulación en membranas celulares", metabolismo: "Fosfolipasas", eliminacion: "Lenta, principalmente intestinal", vidaMedia: "Muy larga: ~7 días (152-183 horas)" },
    almacenamiento: "Temperatura ambiente, proteger de la humedad",
    unidadId: "u01", capituloId: "c0104",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Vómitos severos, diarrea, hepatotoxicidad, nefrotoxicidad", manejo: "Soporte sintomático, no dializable por alta unión a membranas" }
  },
  // ── Hematología ──
  {
    id: "eltrombopag",
    nombre: "Eltrombopag",
    nombreGenerico: "Eltrombopag olamina",
    nombresComerciales: ["Revolade", "Promacta"],
    familia: "Estimulantes de trombopoyesis",
    clasificacion: "Agonista del receptor de trombopoyetina (TPO) oral",
    mecanismoAccion: "Se une al dominio transmembrana del receptor de TPO (c-Mpl) en megacariocitos, activando la vía JAK-STAT para estimular la proliferación y diferenciación de megacariocitos, aumentando la producción de plaquetas.",
    indicaciones: ["Trombocitopenia inmune crónica (PTI)", "Trombocitopenia asociada a hepatitis C (para iniciar interferón)", "Anemia aplásica severa refractaria", "Trombocitopenia asociada a enfermedad hepática crónica pre-procedimiento"],
    contraindicaciones: ["Hipersensibilidad", "Insuficiencia hepática severa (en PTI)"],
    efectosAdversos: ["Cefalea", "Náuseas", "Diarrea", "Elevación de transaminasas", "Trombosis/tromboembolismo", "Mielofibrosis (con uso prolongado)", "Cataratas", "Rebote de trombocitopenia al suspender"],
    interacciones: ["Cationes polivalentes (calcio, hierro, magnesio, zinc, aluminio): separar 4h", "Estatinas (OATP1B1: aumenta rosuvastatina)", "Anticoagulantes (monitorizar, plaquetas altas no son funcionales)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "PTI: inicio 50 mg/día (25 mg en asiáticos/hepatópatas). Hepatitis C: 25 mg/día. Anemia aplásica: inicio 50 mg/día. Titular según plaquetas cada 2 semanas", pediatria: "1-5 años: inicio 25 mg/día. ≥6 años: 50 mg/día" },
    presentaciones: ["Comprimidos 12.5 mg", "Comprimidos 25 mg", "Comprimidos 50 mg", "Comprimidos 75 mg", "Polvo para suspensión oral 25 mg"],
    embarazo: "Categoría C",
    lactancia: "No recomendado (datos insuficientes)",
    cuidadosEnfermeria: [
      "Tomar en AYUNAS (1h antes o 2h después de alimentos)",
      "Separar 4 HORAS de lácteos, antiácidos, suplementos de hierro/calcio",
      "Recuento plaquetario semanal durante titulación, luego mensual",
      "Función hepática cada 2 semanas durante titulación",
      "Objetivo: plaquetas ≥50,000 para reducir sangrado (NO normalizar)",
      "No suspender abruptamente (rebote trombocitopénico)",
      "Examen oftalmológico basal (cataratas)",
      "Vigilar signos de trombosis"
    ],
    farmacocinetica: { absorcion: "Oral: Tmax 2-6h, quelado por cationes", distribucion: "Unión a proteínas >99%", metabolismo: "Hepático CYP1A2, CYP2C8, UGT1A1, UGT1A3", eliminacion: "Fecal 59%, renal 31%", vidaMedia: "21-32 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u05", capituloId: "c0501",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Trombocitosis excesiva, riesgo de trombosis, hepatotoxicidad", manejo: "Suspender, monitorizar plaquetas (caerán por rebote), anticoagulación si trombosis" }
  },
  {
    id: "acido_tranexamico",
    nombre: "Ácido Tranexámico",
    nombreGenerico: "Ácido tranexámico",
    nombresComerciales: ["Transamin", "Espercil", "Lysteda", "Cyklokapron"],
    familia: "Hemostáticos",
    clasificacion: "Antifibrinolítico (análogo de lisina)",
    mecanismoAccion: "Se une reversiblemente al plasminógeno bloqueando los sitios de unión a lisina, impidiendo la unión del plasminógeno a la fibrina y su activación a plasmina. Inhibe la fibrinolisis sin activar la coagulación.",
    indicaciones: ["Hemorragia post-parto", "Hemorragia por trauma (CRASH-2, primeras 3h)", "Menorragia", "Hemorragia dental en hemofílicos", "Cirugía cardíaca/ortopédica (reducción de sangrado)", "Angioedema hereditario", "Hemorragia subaracnoidea"],
    contraindicaciones: ["Enfermedad tromboembólica activa", "CID con fibrinolisis predominante", "Hemorragia subaracnoidea (relativa, depende del contexto)", "Hematuria de origen renal (riesgo de obstrucción ureteral por coágulos)"],
    efectosAdversos: ["Náuseas", "Vómitos", "Diarrea", "Cefalea", "Trombosis (rara a dosis terapéuticas)", "Convulsiones (dosis altas IV)", "Alteraciones visuales (uso prolongado)"],
    interacciones: ["Anticoagulantes (antagonismo teórico)", "Concentrados de complejo protrombínico (riesgo trombótico)", "Estrógenos (riesgo aditivo de trombosis)"],
    viaAdministracion: ["oral", "intravenosa"],
    dosis: { adultos: "Trauma: 1g IV en 10 min + 1g IV en 8h (dentro de 3h del trauma). HPP: 1g IV en 10 min, repetir 1g si sangrado persiste a los 30 min. Menorragia: 1.3g oral cada 8h por 5 días. Dental: 25 mg/kg oral 3-4 veces/día", pediatria: "15-25 mg/kg/dosis cada 6-8h (IV u oral)" },
    presentaciones: ["Comprimidos 500 mg", "Comprimidos 650 mg", "Ampolla 500 mg/5 mL (100 mg/mL)", "Ampolla 1000 mg/10 mL"],
    embarazo: "Compatible - Pilar del manejo de HPP (OMS)",
    lactancia: "Compatible (1% de niveles maternos en leche)",
    cuidadosEnfermeria: [
      "TRAUMA: administrar lo antes posible (<3h, idealmente <1h)",
      "IV: infundir en 10 minutos (NO en bolo rápido, riesgo de hipotensión y convulsiones)",
      "HPP: administrar dentro de 3h del parto, independiente de la causa",
      "Ajustar dosis en insuficiencia renal",
      "Vigilar signos de trombosis",
      "Examen oftalmológico si uso prolongado (>5 días)",
      "Compatible con soluciones de resucitación habituales"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 30-50%", distribucion: "Vd 9-12 L, penetra LCR, sinovial, leche", metabolismo: "Mínimo", eliminacion: "Renal 95% sin cambios", vidaMedia: "2-3 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u05", capituloId: "c0502",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Náuseas, vómitos, convulsiones (dosis muy altas), hipotensión ortostática, trombosis", manejo: "Suspender, anticonvulsivantes si convulsiones, soporte hemodinámico, anticoagulación si trombosis" }
  },
  // ── Psiquiatría ──
  {
    id: "aripiprazol",
    nombre: "Aripiprazol",
    nombreGenerico: "Aripiprazol",
    nombresComerciales: ["Abilify", "Aristada"],
    familia: "Antipsicóticos",
    clasificacion: "Antipsicótico atípico (agonista parcial dopaminérgico)",
    mecanismoAccion: "Agonista parcial de receptores D2 y 5-HT1A, y antagonista de 5-HT2A. Actúa como 'estabilizador dopaminérgico': agonista donde la dopamina es baja (síntomas negativos) y antagonista donde es alta (síntomas positivos). Menor riesgo metabólico.",
    indicaciones: ["Esquizofrenia", "Trastorno bipolar (manía/mixto)", "Depresión mayor (adyuvante)", "Irritabilidad en autismo", "Síndrome de Tourette", "Agitación en esquizofrenia/bipolar (IM)"],
    contraindicaciones: ["Hipersensibilidad", "Demencia con psicosis en ancianos (riesgo de mortalidad)"],
    efectosAdversos: ["Acatisia", "Insomnio", "Cefalea", "Náuseas", "Ansiedad", "Somnolencia", "Menos ganancia de peso y dislipidemia que otros atípicos", "Compulsiones (juego, compras, alimentación - raro)"],
    interacciones: ["Inhibidores CYP2D6 (fluoxetina, paroxetina: reducir dosis 50%)", "Inhibidores CYP3A4 (ketoconazol: reducir dosis 50%)", "Inductores CYP3A4 (carbamazepina: duplicar dosis)", "Depresores del SNC"],
    viaAdministracion: ["oral", "intramuscular"],
    dosis: { adultos: "Esquizofrenia: 10-15 mg/día, máx 30 mg. Bipolar: 15-30 mg/día. Depresión adyuvante: 2-15 mg/día. IM agitación: 9.75 mg, repetir cada 2h, máx 30 mg/día. LAI: 400 mg IM/mes", pediatria: "Esquizofrenia ≥13 años: 2-10 mg/día. Bipolar ≥10 años: 2-10 mg/día. Autismo ≥6 años: 2-15 mg/día" },
    presentaciones: ["Comprimidos 2 mg", "Comprimidos 5 mg", "Comprimidos 10 mg", "Comprimidos 15 mg", "Comprimidos 20 mg", "Comprimidos 30 mg", "Solución oral 1 mg/mL", "Inyectable IM 7.5 mg/mL", "LAI 300 mg", "LAI 400 mg"],
    embarazo: "Categoría C - Riesgo de síntomas extrapiramidales neonatales en 3er trimestre",
    lactancia: "Se excreta en leche, evaluar riesgo/beneficio",
    cuidadosEnfermeria: [
      "Iniciar a dosis bajas y titular gradualmente",
      "Vigilar acatisia (inquietud motora): efecto adverso más frecuente",
      "Monitorizar glucemia, perfil lipídico, peso (aunque menor riesgo que otros)",
      "Observar conductas compulsivas (juego patológico, compras)",
      "La formulación LAI requiere 14 días de overlap con oral",
      "No requiere monitorización de QTc rutinaria",
      "Buena opción en pacientes preocupados por ganancia de peso"
    ],
    farmacocinetica: { absorcion: "Oral: biodisponibilidad 87%", distribucion: "Vd 4.9 L/kg, unión a proteínas >99%", metabolismo: "Hepático CYP2D6 y CYP3A4 a deshidro-aripiprazol (activo)", eliminacion: "Fecal 55%, renal 25%", vidaMedia: "75 horas (metabolito activo: 94h)" },
    almacenamiento: "Temperatura ambiente. Proteger de la luz",
    unidadId: "u04", capituloId: "c0402",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Somnolencia, taquicardia, náuseas, vómitos. Dosis hasta 1080 mg sobrevividas", manejo: "Soporte vital, monitorización cardíaca, carbón activado si reciente, no dializable" }
  },
  {
    id: "paliperidona",
    nombre: "Paliperidona",
    nombreGenerico: "Paliperidona (palmitato)",
    nombresComerciales: ["Invega", "Xeplion", "Invega Sustenna", "Invega Trinza"],
    familia: "Antipsicóticos",
    clasificacion: "Antipsicótico atípico (metabolito activo de risperidona)",
    mecanismoAccion: "Antagonista de receptores D2 y 5-HT2A (como risperidona). Metabolito activo 9-hidroxi-risperidona. Disponible como inyectable de acción prolongada mensual o trimestral, mejorando adherencia.",
    indicaciones: ["Esquizofrenia", "Trastorno esquizoafectivo", "Formulación LAI para manteniimiento y prevención de recaídas"],
    contraindicaciones: ["Hipersensibilidad a paliperidona o risperidona", "Demencia con psicosis en ancianos"],
    efectosAdversos: ["Hiperprolactinemia (alta)", "Ganancia de peso", "Somnolencia", "Acatisia", "Parkinsonismo", "Taquicardia", "Prolongación QT leve", "Reacción en sitio de inyección", "Síndrome post-inyección (PDSS, deltoid)"],
    interacciones: ["Inductores CYP3A4/P-gp (carbamazepina: reducen niveles)", "Depresores del SNC", "Antihipertensivos (hipotensión aditiva)", "Levodopa (antagonismo)"],
    viaAdministracion: ["oral", "intramuscular"],
    dosis: { adultos: "Oral: 6 mg/día, rango 3-12 mg. LAI mensual: inicio 150 mg deltoides día 1, 100 mg deltoides día 8, luego 75-150 mg/mes IM. LAI trimestral: tras estabilización con LAI mensual, 175-525 mg cada 3 meses", pediatria: "Oral ≥12 años: 3-6 mg/día" },
    presentaciones: ["Comprimidos OROS 1.5 mg", "Comprimidos OROS 3 mg", "Comprimidos OROS 6 mg", "Comprimidos OROS 9 mg", "Suspensión LAI 50 mg", "Suspensión LAI 75 mg", "Suspensión LAI 100 mg", "Suspensión LAI 150 mg", "LAI trimestral 175 mg", "LAI trimestral 263 mg", "LAI trimestral 350 mg", "LAI trimestral 525 mg"],
    embarazo: "Categoría C - Riesgo de síntomas extrapiramidales neonatales",
    lactancia: "Se excreta en leche, precaución",
    cuidadosEnfermeria: [
      "Comprimidos OROS: tragar enteros (sistema osmótico, NO partir/triturar)",
      "La carcasa del comprimido aparece en heces (normal, educar al paciente)",
      "LAI mensual: las 2 primeras dosis deben ser en DELTOIDES (absorción)",
      "Observar 3h post-inyección LAI por riesgo de PDSS (somnolencia, síncope)",
      "Monitorizar prolactina, glucemia, peso, perfil lipídico",
      "Control ECG basal (QTc)",
      "LAI trimestral: solo tras 4+ meses de LAI mensual estable"
    ],
    farmacocinetica: { absorcion: "Oral OROS: liberación controlada 24h. LAI: absorción lenta desde sitio de inyección", distribucion: "Unión a proteínas 74%", metabolismo: "Mínimo hepático (no CYP2D6 significativo, ventaja sobre risperidona)", eliminacion: "Renal 59%, fecal 11%", vidaMedia: "Oral: 23h. LAI mensual: 25-49 días. LAI trimestral: 84-95 días" },
    almacenamiento: "Temperatura ambiente (oral). LAI: temperatura ambiente, no refrigerar",
    unidadId: "u04", capituloId: "c0402",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Sedación, taquicardia, hipotensión, síntomas extrapiramidales, prolongación QT", manejo: "Soporte vital, monitorización ECG, no hay antídoto, no dializable" }
  },
  // ── Nefrología ──
  {
    id: "sevelamero",
    nombre: "Sevelámero",
    nombreGenerico: "Sevelámero (carbonato/clorhidrato)",
    nombresComerciales: ["Renvela", "Renagel"],
    familia: "Quelantes de fósforo",
    clasificacion: "Polímero quelante de fosfato no absorbible",
    mecanismoAccion: "Polímero catiónico no absorbido que se une al fosfato dietario en el tracto GI, formando complejos insolubles que se excretan en heces. Reduce la absorción intestinal de fosfato sin aportar aluminio ni calcio.",
    indicaciones: ["Hiperfosfatemia en enfermedad renal crónica (ERC) en diálisis", "Hiperfosfatemia en ERC estadio 3-5 sin diálisis"],
    contraindicaciones: ["Obstrucción intestinal", "Hipofosfatemia", "Íleo"],
    efectosAdversos: ["Náuseas", "Vómitos", "Diarrea o estreñimiento", "Dolor abdominal", "Flatulencia", "Obstrucción intestinal (rara)"],
    interacciones: ["Levotiroxina (reducción absorción: separar 4h)", "Ciprofloxacino (separar 2h)", "Micofenolato (reducción absorción: separar 2h)", "Ciclosporina (separar 2h)", "Antiepilépticos (separar)"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "800-1600 mg con cada comida principal. Titular según fósforo sérico cada 2 semanas. Rango habitual: 2.4-14.4 g/día", pediatria: "BSA-based dosing ≥6 años" },
    presentaciones: ["Comprimidos 800 mg", "Polvo para suspensión oral 0.8 g", "Polvo para suspensión oral 2.4 g"],
    embarazo: "Categoría C (no absorbido, pero puede reducir absorción de vitaminas)",
    lactancia: "Probablemente compatible (no absorbido)",
    cuidadosEnfermeria: [
      "Tomar CON las comidas (se une al fosfato del alimento)",
      "Tragar comprimidos enteros con agua (no triturar)",
      "El polvo puede mezclarse con agua (NO calentar)",
      "Separar de TODOS los otros medicamentos orales por ≥1-2h",
      "Monitorizar fósforo, calcio, PTH, bicarbonato",
      "Ventaja: no aporta calcio (útil si hipercalcemia) ni aluminio",
      "Educar sobre dieta baja en fósforo como complemento"
    ],
    farmacocinetica: { absorcion: "NO se absorbe (actúa localmente en intestino)", distribucion: "No aplicable", metabolismo: "No aplicable", eliminacion: "Fecal 100% como complejo fosfato-polímero", vidaMedia: "No aplicable (no absorbido)" },
    almacenamiento: "Temperatura ambiente, proteger de la humedad",
    unidadId: "u10", capituloId: "c1001",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipofosfatemia, obstrucción intestinal", manejo: "Suspender, suplementar fósforo si necesario, manejo de obstrucción si presente" }
  },
  {
    id: "cinacalcet",
    nombre: "Cinacalcet",
    nombreGenerico: "Cinacalcet clorhidrato",
    nombresComerciales: ["Mimpara", "Sensipar"],
    familia: "Reguladores del metabolismo calcio-fósforo",
    clasificacion: "Calcimimético (modulador alostérico del receptor sensor de calcio)",
    mecanismoAccion: "Modulador alostérico positivo del receptor sensor de calcio (CaSR) en la paratiroides. Aumenta la sensibilidad del receptor al calcio extracelular, reduciendo la secreción de PTH, calcemia y fosfatemia.",
    indicaciones: ["Hiperparatiroidismo secundario en ERC en diálisis", "Hipercalcemia en carcinoma paratiroideo", "Hiperparatiroidismo primario severo cuando no es posible paratiroidectomía"],
    contraindicaciones: ["Hipocalcemia (Ca <8.4 mg/dL)", "Hipersensibilidad"],
    efectosAdversos: ["Náuseas", "Vómitos", "Hipocalcemia", "Parestesias", "Mialgias", "Diarrea", "Mareo", "Prolongación QT (por hipocalcemia)", "Convulsiones (por hipocalcemia)"],
    interacciones: ["Inhibidores CYP3A4 (aumentan niveles)", "Inhibidores CYP2D6 (aumentan niveles)", "Sustratos de CYP2D6 (cinacalcet los inhibe: ajustar dosis de flecainida, tricíclicos)", "Medicamentos que prolongan QT"],
    viaAdministracion: ["oral"],
    dosis: { adultos: "HPT secundario: inicio 30 mg/día con alimentos, titular cada 2-4 semanas (60, 90, 120, 180 mg/día). Carcinoma paratiroideo: inicio 30 mg/12h, máx 360 mg/día", pediatria: "No aprobado en <18 años" },
    presentaciones: ["Comprimidos 30 mg", "Comprimidos 60 mg", "Comprimidos 90 mg"],
    embarazo: "Categoría C",
    lactancia: "No recomendado",
    cuidadosEnfermeria: [
      "Tomar CON alimentos o poco después de comer (aumenta biodisponibilidad 50-80%)",
      "Monitorizar calcio sérico dentro de 1 semana de inicio/ajuste de dosis",
      "Si calcio <7.5 mg/dL o síntomas de hipocalcemia: suplementar calcio y vitamina D",
      "No iniciar si calcio sérico <8.4 mg/dL",
      "Monitorizar PTH 1-4 semanas después de inicio/cambio de dosis",
      "Vigilar síntomas de hipocalcemia: parestesias periorales, calambres, espasmos, convulsiones",
      "No triturar ni partir (sabor muy amargo)"
    ],
    farmacocinetica: { absorcion: "Oral con alimentos: biodisponibilidad 20-25%", distribucion: "Vd 1000 L, unión a proteínas 93-97%", metabolismo: "Hepático CYP3A4, CYP2D6, CYP1A2", eliminacion: "Renal 80%, fecal 15%", vidaMedia: "30-40 horas" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u10", capituloId: "c1001",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipocalcemia severa: tetania, convulsiones, prolongación QT, arritmias", manejo: "Calcio IV inmediato (gluconato de calcio), monitorización ECG, calcitriol" }
  },
  // ── Dermatología ──
  {
    id: "dupilumab",
    nombre: "Dupilumab",
    nombreGenerico: "Dupilumab",
    nombresComerciales: ["Dupixent"],
    familia: "Anticuerpos monoclonales",
    clasificacion: "Anti-IL-4Rα (anticuerpo monoclonal humano)",
    mecanismoAccion: "Se une a la subunidad alfa del receptor de IL-4, bloqueando la señalización de IL-4 e IL-13 (citocinas tipo 2). Reduce la inflamación tipo 2 (eosinófilos, IgE, periostin). No es inmunosupresor sistémico.",
    indicaciones: ["Dermatitis atópica moderada-severa", "Asma eosinofílica/dependiente de corticoides", "Rinosinusitis crónica con poliposis nasal", "Esofagitis eosinofílica", "Prurigo nodular"],
    contraindicaciones: ["Hipersensibilidad", "Parasitosis activa (tratar antes)"],
    efectosAdversos: ["Reacción en sitio de inyección", "Conjuntivitis/queratitis", "Herpes oral", "Eosinofilia transitoria", "Artralgia", "Cefalea"],
    interacciones: ["Vacunas vivas: no administrar concomitantemente", "Puede normalizar CYP450 previamente suprimido por citocinas (monitorizar sustratos con índice terapéutico estrecho)"],
    viaAdministracion: ["subcutanea"],
    dosis: { adultos: "DA: carga 600 mg (2x300 mg), luego 300 mg cada 2 semanas. Asma: 200 mg o 300 mg cada 2 semanas (según corticodependencia)", pediatria: "DA ≥6 meses: según peso. Asma ≥6 años: según peso" },
    presentaciones: ["Jeringa prellenada 200 mg/1.14 mL", "Jeringa prellenada 300 mg/2 mL", "Autoinyector 200 mg", "Autoinyector 300 mg"],
    embarazo: "Datos limitados, IgG cruza placenta en 3er trimestre",
    lactancia: "Probablemente compatible (IgG en leche en bajas cantidades)",
    cuidadosEnfermeria: [
      "Autoadministración SC tras entrenamiento en brazo, muslo o abdomen",
      "Refrigerar. Sacar 45 min antes de inyectar (temperatura ambiente)",
      "Vigilar conjuntivitis (10-15% en DA, derivar a oftalmología si severa)",
      "No es inmunosupresor sistémico: bajo riesgo de infecciones",
      "Puede combinarse con corticoides tópicos",
      "Evaluar EASI/IGA a las 16 semanas para determinar respuesta",
      "No requiere monitoreo de laboratorio rutinario"
    ],
    farmacocinetica: { absorcion: "SC: biodisponibilidad 64%, Tmax 1 semana", distribucion: "Vd 4.8 L", metabolismo: "Proteólisis (como IgG)", eliminacion: "Reticuloendotelial, no renal", vidaMedia: "Variable, estado estable en 16 semanas" },
    almacenamiento: "Refrigerar 2-8°C. Puede mantenerse a TA hasta 14 días",
    unidadId: "u09", capituloId: "c0901",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "No hay datos de sobredosis", manejo: "Observación y soporte" }
  },
  // ── Toxicología/Antídotos ──
  {
    id: "fomepizol",
    nombre: "Fomepizol",
    nombreGenerico: "Fomepizol (4-metilpirazol)",
    nombresComerciales: ["Antizol"],
    familia: "Antídotos",
    clasificacion: "Inhibidor competitivo de alcohol deshidrogenasa",
    mecanismoAccion: "Inhibidor competitivo potente de la alcohol deshidrogenasa (ADH), enzima que metaboliza metanol y etilenglicol a sus metabolitos tóxicos (ácido fórmico y ácido oxálico/glicólico). Previene la formación de metabolitos sin bloquear la eliminación del tóxico padre.",
    indicaciones: ["Intoxicación por metanol", "Intoxicación por etilenglicol", "Intoxicación por dietilenglicol"],
    contraindicaciones: ["Hipersensibilidad"],
    efectosAdversos: ["Cefalea", "Náuseas", "Mareo", "Reacción en sitio de infusión", "Eosinofilia transitoria", "Elevación transitoria de transaminasas"],
    interacciones: ["Etanol (competición por ADH, no administrar juntos)", "Fenitoína (puede aumentar niveles)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Carga: 15 mg/kg IV. Luego 10 mg/kg cada 12h x 4 dosis. A partir de 5ta dosis: 15 mg/kg cada 12h. Si en hemodiálisis: cada 4h", pediatria: "Misma dosis que adultos" },
    presentaciones: ["Ampolla 1 g/mL (1.5 mL)"],
    embarazo: "Categoría C - Usar si beneficio supera riesgo (intoxicación es mayor riesgo)",
    lactancia: "Datos insuficientes, priorizar tratamiento",
    cuidadosEnfermeria: [
      "Diluir en 100 mL SS 0.9% o D5W, infundir en 30 minutos",
      "Es el ANTÍDOTO DE ELECCIÓN (superiora etanol IV)",
      "Iniciar de inmediato si sospecha de intoxicación por metanol/etilenglicol",
      "Monitorizar gases arteriales, brecha aniónica, brecha osmolar",
      "La hemodiálisis es complementaria (elimina el tóxico y metabolitos)",
      "Si en HD: aumentar frecuencia a cada 4h (se dializa el fomepizol)",
      "Continuar hasta que niveles del tóxico <20 mg/dL y paciente asintomático"
    ],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Vd 0.6-1.02 L/kg, unión a proteínas insignificante", metabolismo: "Hepático (oxidación a 4-carboxipirazol)", eliminacion: "Renal 1-3.5% sin cambios, eliminado por HD", vidaMedia: "Variable, autoinducción tras 30-40h" },
    almacenamiento: "Temperatura ambiente. Puede cristalizar: calentar a 25-40°C si cristaliza",
    unidadId: "u02", capituloId: "c0202",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Mareo, náuseas, vértigo. Bien tolerado en amplio rango de dosis", manejo: "Soporte, se elimina por HD si necesario" }
  },
  {
    id: "hidroxocobalamina_antidoto",
    nombre: "Hidroxocobalamina (antídoto)",
    nombreGenerico: "Hidroxocobalamina",
    nombresComerciales: ["Cyanokit"],
    familia: "Antídotos",
    clasificacion: "Antídoto para intoxicación por cianuro (precursor de vitamina B12)",
    mecanismoAccion: "Se une directamente al ion cianuro con mayor afinidad que la citocromo oxidasa, formando cianocobalamina (vitamina B12), que es atóxica y se elimina por vía renal. Restaura la respiración celular aeróbica.",
    indicaciones: ["Intoxicación por cianuro (conocida o sospechada)", "Inhalación de humo con sospecha de cianuro", "Intoxicación por nitroprusiato"],
    contraindicaciones: ["Ninguna absoluta en emergencia por cianuro"],
    efectosAdversos: ["Coloración roja de piel, mucosas, orina (hasta 2 semanas)", "Hipertensión transitoria", "Cefalea", "Náuseas", "Reacciones alérgicas (raras)", "Interferencia con pruebas de laboratorio colorimétricas"],
    interacciones: ["Tiosulfato de sodio (no mezclar en la misma línea)", "Interfiere con cooximetría y pruebas colorimétrica"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "5 g IV en 15 minutos. Repetir 5 g si respuesta insuficiente (máx 10 g total)", pediatria: "70 mg/kg IV (máx 5 g)" },
    presentaciones: ["Kit: Polvo para reconstitución 5 g + dispositivo de infusión"],
    embarazo: "Usar siempre en intoxicación por cianuro (riesgo vital supera todo)",
    lactancia: "Usar, salvar la vida es prioritario",
    cuidadosEnfermeria: [
      "Reconstituir con 200 mL SS 0.9% (agitar/rotar 30-60 seg)",
      "Infundir en 15 minutos (puede acelerarse en paro cardíaco)",
      "ADVERTIR sobre coloración roja de piel y orina (normal, 2-5 días)",
      "Interfiere con laboratorio: extraer muestras ANTES de administrar si posible",
      "No mezclar con tiosulfato de sodio ni otros medicamentos",
      "Monitorizar PA (puede causar hipertensión significativa)",
      "En incendio: considerar cianuro si acidosis metabólica + lactato >8 mmol/L"
    ],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Se une rápidamente a cianuro y proteínas", metabolismo: "Forma cianocobalamina (vit B12)", eliminacion: "Renal como cianocobalamina", vidaMedia: "26-31 horas" },
    almacenamiento: "Temperatura ambiente (hasta 40°C por períodos breves). No refrigerar ni congelar",
    unidadId: "u02", capituloId: "c0202",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipertensión severa, coloración roja prolongada. Dosis hasta 15g toleradas", manejo: "Monitorizar PA, soporte hemodinámico si necesario, eliminación renal" }
  },
  // ── Oftalmología ──
  {
    id: "latanoprost",
    nombre: "Latanoprost",
    nombreGenerico: "Latanoprost",
    nombresComerciales: ["Xalatan", "Galenox"],
    familia: "Antiglaucomatosos",
    clasificacion: "Análogo de prostaglandina F2α",
    mecanismoAccion: "Agonista selectivo del receptor FP de prostaglandina. Aumenta el flujo de humor acuoso por la vía uveoescleral (no convencional). Reduce la presión intraocular (PIO) un 25-35% desde la basal.",
    indicaciones: ["Glaucoma de ángulo abierto", "Hipertensión ocular"],
    contraindicaciones: ["Hipersensibilidad", "Precaución en uveítis activa", "Precaución en edema macular quístico"],
    efectosAdversos: ["Hiperemia conjuntival", "Oscurecimiento del iris (irreversible)", "Crecimiento y oscurecimiento de pestañas", "Prurito ocular", "Hiperpigmentación periocular", "Edema macular (raro)", "Cambio de color periocular"],
    interacciones: ["Timolol (efecto aditivo, combinación frecuente)", "Otros análogos de prostaglandinas (no combinar)"],
    viaAdministracion: ["oftalmica"],
    dosis: { adultos: "1 gota en ojo(s) afectado(s) cada noche (1 vez/día)", pediatria: "Misma dosis ≥1 año" },
    presentaciones: ["Solución oftálmica 0.005% (50 mcg/mL) frasco 2.5 mL"],
    embarazo: "Categoría C - Evitar si posible",
    lactancia: "Precaución (absorción sistémica mínima)",
    cuidadosEnfermeria: [
      "Aplicar UNA gota por la NOCHE (máxima eficacia, menor hiperemia)",
      "Ocluir punto lagrimal 2-3 minutos post-instilación (reduce absorción sistémica)",
      "Informar sobre oscurecimiento IRREVERSIBLE del iris (especialmente en ojos multicolor)",
      "Crecimiento de pestañas es reversible al suspender",
      "Si usa múltiples colirios: separar 5 minutos entre cada uno",
      "Retirar lentes de contacto antes de instilar, esperar 15 min para recolocar",
      "Monitorizar PIO regularmente"
    ],
    farmacocinetica: { absorcion: "Corneal: prodroga hidrolizada a ácido activo", distribucion: "Principalmente intraocular", metabolismo: "Hepático por β-oxidación del ácido activo", eliminacion: "Renal", vidaMedia: "17 minutos en plasma (efecto ocular dura 24h)" },
    almacenamiento: "Refrigerar sin abrir. Abierto: TA hasta 6 semanas",
    unidadId: "u11", capituloId: "c1101",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Irritación ocular. Absorción sistémica: dolor torácico, disnea (prostaglandínico)", manejo: "Lavado ocular, soporte si síntomas sistémicos" }
  },
  // ── Obstetricia ──
  {
    id: "carbetocina",
    nombre: "Carbetocina",
    nombreGenerico: "Carbetocina",
    nombresComerciales: ["Pabal", "Duratocin"],
    familia: "Oxitócicos",
    clasificacion: "Análogo sintético de oxitocina de acción prolongada",
    mecanismoAccion: "Agonista del receptor de oxitocina con mayor vida media y estabilidad que la oxitocina natural. Produce contracción uterina sostenida. Se une al receptor de oxitocina en miometrio estimulando contracciones rítmicas.",
    indicaciones: ["Prevención de hemorragia post-parto tras cesárea", "Prevención de atonía uterina", "Alternativa a oxitocina (OMS: termoestable, dosis única)"],
    contraindicaciones: ["Antes del alumbramiento", "Hipersensibilidad", "Enfermedad vascular severa", "Epilepsia", "Preeclampsia/eclampsia severa"],
    efectosAdversos: ["Dolor abdominal", "Náuseas", "Prurito", "Rubor", "Hipotensión", "Cefalea", "Temblor", "Sabor metálico"],
    interacciones: ["Otros oxitócicos (efecto aditivo, no combinar)", "Prostaglandinas (esperar efecto antes de usar)", "Anestésicos tipo caudal (potencian efecto hipertensor)"],
    viaAdministracion: ["intravenosa", "intramuscular"],
    dosis: { adultos: "Cesárea: 100 mcg IV en bolo lento (>1 min) tras alumbramiento. Parto vaginal: 100 mcg IM. Dosis ÚNICA (no repetir)", pediatria: "No aplicable" },
    presentaciones: ["Ampolla 100 mcg/mL (1 mL)"],
    embarazo: "Solo post-alumbramiento",
    lactancia: "Compatible (análogo de oxitocina, promueve lactancia)",
    cuidadosEnfermeria: [
      "Administrar DESPUÉS del alumbramiento de placenta",
      "Dosis ÚNICA: no repetir (efecto prolongado ~1h vs 15 min de oxitocina)",
      "IV: inyección lenta en ≥1 minuto",
      "Ventaja: formulación termoestable (no requiere refrigeración)",
      "Monitorizar tono uterino y sangrado post-parto",
      "Monitorizar PA (puede causar hipotensión)",
      "No iniciar infusión de oxitocina posterior excepto si sangrado no controlado"
    ],
    farmacocinetica: { absorcion: "IV: inmediata. IM: rápida", distribucion: "Mínima unión a proteínas", metabolismo: "Degradación enzimática (más lenta que oxitocina por modificación N-terminal)", eliminacion: "Renal", vidaMedia: "40 minutos (vs 3-5 min oxitocina)" },
    almacenamiento: "Temperatura ambiente (termoestable hasta 30°C). Ventaja logística en zonas sin cadena de frío",
    unidadId: "u12", capituloId: "c1201",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipertonía uterina, náuseas, hiponatremia (efecto antidiurético)", manejo: "Soporte, tocolíticos si hipertonía, restricción hídrica si hiponatremia" }
  },
  // ── Urgencias ──
  {
    id: "clevidipino",
    nombre: "Clevidipino",
    nombreGenerico: "Clevidipino butirato",
    nombresComerciales: ["Cleviprex"],
    familia: "Antihipertensivos",
    clasificacion: "Bloqueador de canales de calcio dihidropiridínico (IV, ultra-corta acción)",
    mecanismoAccion: "Bloquea selectivamente los canales de calcio tipo L en músculo liso arterial. Vasodilatador arterial puro sin efecto venoso. Ultra-corta acción por metabolismo rápido por esterasas sanguíneas. Titulable segundo a segundo.",
    indicaciones: ["Crisis hipertensiva (urgencia/emergencia)", "Hipertensión perioperatoria", "Hipertensión en UCI", "Cuando se requiere control preciso de PA minuto a minuto"],
    contraindicaciones: ["Alergia a soya, huevo, productos de soya o huevo (emulsión lipídica)", "Defectos del metabolismo lipídico", "Pancreatitis aguda con hiperlipidemia", "Estenosis aórtica severa"],
    efectosAdversos: ["Taquicardia refleja", "Cefalea", "Náuseas", "Hipertrigliceridemia (infusiones prolongadas)", "Fibrilación auricular (raro)", "Hipotensión"],
    interacciones: ["Otros antihipertensivos (efecto aditivo)", "Betabloqueantes (atenúan taquicardia refleja, combinación útil)", "Contribuye a carga lipídica total (0.2 g grasa/mL)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Inicio: 1-2 mg/h IV, titular duplicando cada 90 segundos inicialmente, luego cada 5-10 min. Rango habitual: 4-6 mg/h. Máx 32 mg/h. Máx 72h o 1000 mL/24h", pediatria: "Datos limitados: 0.5-5 mcg/kg/min" },
    presentaciones: ["Emulsión inyectable 0.5 mg/mL (50 mL)", "Emulsión inyectable 0.5 mg/mL (100 mL)"],
    embarazo: "Categoría C",
    lactancia: "Precaución",
    cuidadosEnfermeria: [
      "NO diluir. Administrar con bomba de infusión directamente del vial",
      "Invertir vial suavemente varias veces antes de usar (emulsión)",
      "Usar dentro de 12h de perforar el vial (medio de cultivo bacteriano)",
      "Monitorización PA continua (arterial invasiva recomendada)",
      "Inicio de acción: 2-4 minutos. Recuperación: 5-15 min post-suspensión",
      "Contabilizar aporte lipídico en nutrición total del paciente",
      "Mantener refrigerado hasta uso, no congelar",
      "Línea IV dedicada o compatible con otros medicamentos"
    ],
    farmacocinetica: { absorcion: "IV: inmediata", distribucion: "Inicial rápida, unión a proteínas >99.5%", metabolismo: "Esterasas sanguíneas y tisulares (NO hepático, NO CYP450)", eliminacion: "Renal 63-74%, fecal 7-22%", vidaMedia: "~1 minuto (eliminación inicial)" },
    almacenamiento: "Refrigerar 2-8°C. Proteger de la luz. En uso: TA hasta 12h",
    unidadId: "u03", capituloId: "c0302",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Hipotensión severa, taquicardia refleja", manejo: "Suspender (recuperación en 5-15 min), fluidos IV, vasopresores si necesario" }
  },
  {
    id: "dexmedetomidina",
    nombre: "Dexmedetomidina",
    nombreGenerico: "Dexmedetomidina",
    nombresComerciales: ["Precedex", "Dexdor"],
    familia: "Sedantes",
    clasificacion: "Agonista alfa-2 adrenérgico altamente selectivo",
    mecanismoAccion: "Agonista selectivo de receptores alfa-2A adrenérgicos en el locus coeruleus (sedación/anxiolisis) y en la médula espinal (analgesia). Produce 'sedación cooperativa': paciente sedado pero despertable al estímulo. No causa depresión respiratoria significativa.",
    indicaciones: ["Sedación en UCI (ventilados <24h inicialmente, ahora uso extendido)", "Sedación para procedimientos", "Prevención y tratamiento de delirium en UCI", "Adyuvante analgésico", "Destete difícil de ventilación mecánica"],
    contraindicaciones: ["Bloqueo AV 2do-3er grado sin marcapasos", "Hipotensión severa no corregida", "Bradicardia severa"],
    efectosAdversos: ["Bradicardia", "Hipotensión", "Hipertensión transitoria (bolo/inicio)", "Sequedad bucal", "Náuseas", "Fibrilación auricular (raro)"],
    interacciones: ["Otros sedantes (efecto aditivo, reducir dosis)", "Opioides (efecto aditivo, reducir dosis 50%)", "Betabloqueantes, digoxina (bradicardia aditiva)", "Vasodilatadores (hipotensión aditiva)"],
    viaAdministracion: ["intravenosa"],
    dosis: { adultos: "Carga (opcional): 0.5-1 mcg/kg en 10-20 min. Mantenimiento: 0.2-1.5 mcg/kg/h. Procedimientos: carga 1 mcg/kg en 10 min, luego 0.2-1 mcg/kg/h", pediatria: "0.2-1 mcg/kg/h (sin carga en pediátricos)" },
    presentaciones: ["Solución concentrada 100 mcg/mL (2 mL)", "Solución concentrada 200 mcg/2 mL", "Solución prediluida 4 mcg/mL (100 mL)"],
    embarazo: "Categoría C",
    lactancia: "Precaución (se excreta en leche en animales)",
    cuidadosEnfermeria: [
      "Diluir concentrado en SS 0.9% hasta 4 mcg/mL",
      "Administrar con bomba de infusión",
      "Monitorización continua: ECG, PA, FC, SatO2",
      "Ventaja: sedación sin depresión respiratoria significativa",
      "Paciente puede despertar al hablarle (sedación cooperativa)",
      "Vigilar bradicardia severa (tener atropina disponible)",
      "El bolo puede causar hipertensión transitoria seguida de hipotensión",
      "Escala RASS para titular (objetivo -2 a 0 generalmente)"
    ],
    farmacocinetica: { absorcion: "IV: inmediata. Inicio 5-10 min", distribucion: "Vd 118 L, unión a proteínas 94%", metabolismo: "Hepático CYP2A6, UGT1A4, UGT2B10", eliminacion: "Renal 95% (como metabolitos)", vidaMedia: "2-3 horas (contexto-dependiente con infusiones prolongadas)" },
    almacenamiento: "Temperatura ambiente",
    unidadId: "u02", capituloId: "c0202",
    searchText: "",
    riesgosSobremedicacion: { sintomas: "Bradicardia severa, hipotensión, sedación profunda (pero ventilación preservada)", manejo: "Suspender infusión, atropina si bradicardia, vasopresores si hipotensión, recuperación en 1-2h" }
  }
];

// Agregar fármacos con deduplicación
let added = 0;
for (const d of newDrugs) {
  if (existingIds.has(d.id)) continue;
  d.searchText = mkSearch(d);
  drugs.push(d);
  existingIds.add(d.id);
  for (const u of cats.unidades) {
    if (u.id === d.unidadId) {
      const cap = u.capitulos.find(c => c.id === d.capituloId);
      if (cap && !cap.drugIds.includes(d.id)) cap.drugIds.push(d.id);
    }
  }
  added++;
}

fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log(`Added: ${added}. Total drugs: ${drugs.length}`);
