const fs = require('fs');
const path = require('path');
const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath = path.join(__dirname, '..', 'src', 'data', 'categories.json');
const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats = JSON.parse(fs.readFileSync(catsPath, 'utf8'));
const existingIds = new Set(drugs.map(d => d.id));

function mkSearch(d) {
  return [d.nombre, d.nombreGenerico, ...d.nombresComerciales, d.familia, d.clasificacion, ...d.indicaciones]
    .join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

const newDrugs = [
  {
    id: 'ketoprofeno', nombre: 'Ketoprofeno', nombreGenerico: 'Ketoprofeno',
    nombresComerciales: ['Profenid', 'Fastum', 'Ketoprofeno Gador'],
    familia: 'AINEs', clasificacion: 'Antiinflamatorio no esteroideo (derivado del ácido propiónico)',
    mecanismoAccion: 'Inhibe COX-1 y COX-2, reduciendo la síntesis de prostaglandinas. También inhibe la lipooxigenasa y la bradiquinina.',
    indicaciones: ['Dolor moderado a severo', 'Artritis reumatoide', 'Artrosis', 'Dolor postoperatorio', 'Dismenorrea', 'Espondilitis anquilosante'],
    contraindicaciones: ['Úlcera GI activa', 'Insuficiencia renal grave', 'Tercer trimestre embarazo', 'Asma por AINEs'],
    efectosAdversos: ['Dispepsia', 'Náuseas', 'Dolor abdominal', 'Cefalea', '⚠️ Hemorragia GI', '⚠️ Nefrotoxicidad'],
    interacciones: ['Anticoagulantes: riesgo hemorrágico', 'Metotrexato: toxicidad', 'IECA: reduce efecto', 'Litio: aumenta niveles'],
    viaAdministracion: ['oral', 'IM', 'IV', 'topica', 'rectal'],
    dosis: { adulto: 'Oral: 50-100 mg cada 8-12h. IM/IV: 100 mg cada 8-12h. Máx: 300 mg/día', ajusteRenal: 'Reducir si ClCr <25' },
    presentaciones: ['Cápsulas 50, 100 mg', 'Comprimidos LP 200 mg', 'Ampollas 100 mg/2 mL', 'Gel 2.5%', 'Supositorios 100 mg'],
    embarazo: 'C', lactancia: 'Se excreta. Evitar.',
    cuidadosEnfermeria: ['Administrar con alimentos', 'IV: diluir en 100 mL SF, pasar en 20 min', 'IM: inyección profunda en glúteo', 'No más de 5 días parenteral', 'Mayor potencia antiinflamatoria que ibuprofeno'],
    farmacocinetica: { absorcion: 'Oral rápida, biodisponibilidad >90%', metabolismo: 'Hepático glucuronidación', excrecion: 'Renal 80%', vidaMedia: '2-4 horas', inicioAccion: 'Oral 30 min, IM 15 min', duracionAccion: '6-8 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u08', capituloId: 'c08_01'
  },
  {
    id: 'lornoxicam', nombre: 'Lornoxicam', nombreGenerico: 'Lornoxicam',
    nombresComerciales: ['Xefo', 'Acabel'],
    familia: 'AINEs', clasificacion: 'Antiinflamatorio no esteroideo (oxicam)',
    mecanismoAccion: 'Inhibe COX-1 y COX-2 de forma balanceada. Potente actividad analgésica.',
    indicaciones: ['Dolor postoperatorio', 'Dolor agudo moderado a severo', 'Artrosis', 'Artritis reumatoide', 'Lumbalgia aguda'],
    contraindicaciones: ['Úlcera GI activa', 'Coagulopatía', 'Insuficiencia renal o hepática grave'],
    efectosAdversos: ['Dispepsia', 'Náuseas', 'Diarrea', 'Cefalea', '⚠️ Hemorragia GI'],
    interacciones: ['Anticoagulantes: riesgo hemorrágico', 'Metotrexato: toxicidad', 'Clopidogrel: mayor sangrado'],
    viaAdministracion: ['oral', 'IV', 'IM'],
    dosis: { adulto: 'Oral: 8-16 mg/día en 2-3 tomas. IV/IM: 8 mg cada 12h. Máx: 16 mg/día', ajusteRenal: 'Máx 12 mg/día si ClCr <30' },
    presentaciones: ['Comprimidos 4, 8 mg', 'Ampollas 8 mg'],
    embarazo: 'C', lactancia: 'Evitar.',
    cuidadosEnfermeria: ['IV: administrar lento en 15 seg o diluir en 15 min', 'Potencia analgésica comparable a opioides menores', 'No exceder 5 días parenteral'],
    farmacocinetica: { absorcion: 'Oral rápida', metabolismo: 'Hepático CYP2C9', excrecion: 'Renal 33%, fecal 67%', vidaMedia: '3-4 horas', inicioAccion: '30 min', duracionAccion: '8-12 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u08', capituloId: 'c08_01'
  },
  {
    id: 'ceftolozano_tazobactam', nombre: 'Ceftolozano/Tazobactam', nombreGenerico: 'Ceftolozano + Tazobactam',
    nombresComerciales: ['Zerbaxa'],
    familia: 'Cefalosporinas + inhibidor de betalactamasa', clasificacion: 'Antibiótico betalactámico antipseudomónico',
    mecanismoAccion: 'Ceftolozano con alta afinidad por PBP3 de Pseudomonas. Tazobactam inhibe betalactamasas BLEE.',
    indicaciones: ['Infección urinaria complicada', 'Infección intraabdominal complicada (con metronidazol)', 'Neumonía nosocomial/asociada a ventilador'],
    contraindicaciones: ['Alergia severa a cefalosporinas/betalactámicos'],
    efectosAdversos: ['Náuseas', 'Diarrea', 'Cefalea', 'Fiebre', '⚠️ Colitis por C. difficile'],
    interacciones: ['No interacciones significativas'],
    viaAdministracion: ['IV'],
    dosis: { adulto: 'ITU/IAb: 1.5 g cada 8h. Neumonía: 3 g cada 8h. Infusión 1h', ajusteRenal: 'ClCr 30-50: 750 mg/8h. ClCr 15-29: 375 mg/8h' },
    presentaciones: ['Viales 1.5 g, 3 g'],
    embarazo: 'B', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['Infusión en 1 hora', 'IAb: SIEMPRE con metronidazol', 'Reservar para Pseudomonas multirresistente', 'Monitorizar función renal'],
    farmacocinetica: { metabolismo: 'Mínimo', excrecion: 'Renal >90%', vidaMedia: 'Ceftolozano: 3h. Tazobactam: 1h', inicioAccion: 'Inmediato', duracionAccion: '8 horas' },
    almacenamiento: 'Refrigerar.', unidadId: 'u03', capituloId: 'c03_01'
  },
  {
    id: 'ceftarolina', nombre: 'Ceftarolina', nombreGenerico: 'Ceftarolina fosamil',
    nombresComerciales: ['Teflaro', 'Zinforo'],
    familia: 'Cefalosporinas de 5ª generación', clasificacion: 'Antibiótico betalactámico anti-MRSA',
    mecanismoAccion: 'Única cefalosporina con afinidad por PBP2a de MRSA. Activa contra gram-positivos resistentes y gram-negativos habituales.',
    indicaciones: ['Neumonía adquirida en comunidad', 'Infecciones de piel y tejidos blandos (incluyendo MRSA)'],
    contraindicaciones: ['Alergia severa a cefalosporinas'],
    efectosAdversos: ['Diarrea', 'Náuseas', 'Rash', '⚠️ Test de Coombs positivo'],
    interacciones: ['Probenecid: aumenta niveles'],
    viaAdministracion: ['IV'],
    dosis: { adulto: '600 mg cada 12h en infusión 1h por 5-14 días', pediatrico: '>2 años: 12 mg/kg/12h', ajusteRenal: '400 mg/12h si ClCr 31-50. 300 mg/12h si ClCr 15-30' },
    presentaciones: ['Viales 400, 600 mg'],
    embarazo: 'B', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['Infusión en 60 min', 'ÚNICA cefalosporina anti-MRSA', 'No cubre Pseudomonas', 'Test de Coombs puede positivizarse sin hemólisis'],
    farmacocinetica: { metabolismo: 'Defosforilación, hidrólisis', excrecion: 'Renal 88%', vidaMedia: '2.6 horas', inicioAccion: 'Inmediato', duracionAccion: '12 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u03', capituloId: 'c03_01'
  },
  {
    id: 'ramipril', nombre: 'Ramipril', nombreGenerico: 'Ramipril',
    nombresComerciales: ['Tritace', 'Altace', 'Ramipril Gador'],
    familia: 'Antihipertensivos', clasificacion: 'Inhibidor de la ECA (IECA)',
    mecanismoAccion: 'Profármaco convertido a ramiprilato. Inhibe la ECA reduciendo angiotensina II, vasoconstricción y secreción de aldosterona.',
    indicaciones: ['Hipertensión arterial', 'IC post-IAM', 'Prevención cardiovascular (estudio HOPE)', 'Nefropatía diabética', 'Post-IAM con disfunción ventricular'],
    contraindicaciones: ['Angioedema previo', 'Embarazo', 'Estenosis bilateral renal'],
    efectosAdversos: ['Tos seca (10-15%)', 'Hipotensión', 'Hiperpotasemia', '⚠️ Angioedema', '⚠️ IRA en estenosis renal'],
    interacciones: ['ARA-II: evitar doble bloqueo', 'Espironolactona: hiperpotasemia', 'AINEs: reduce eficacia', 'Litio: toxicidad'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'HTA: 2.5-10 mg/día. IC: inicio 1.25 mg/12h, meta 5 mg/12h. Prevención CV: 10 mg/día', ajusteRenal: 'Inicio 1.25 mg/día si ClCr <40' },
    presentaciones: ['Comprimidos 1.25, 2.5, 5, 10 mg'],
    embarazo: 'D', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Monitorizar PA, potasio, creatinina', 'Primera dosis al acostarse', 'Tos seca: evaluar cambio a ARA-II', 'Vigilar angioedema', 'HOPE demostró reducción mortalidad CV'],
    farmacocinetica: { absorcion: 'Oral 50-60%', metabolismo: 'Hepático a ramiprilato (activo)', excrecion: 'Renal 60%, fecal 40%', vidaMedia: 'Ramiprilato: 13-17h', inicioAccion: '1-2 horas', duracionAccion: '24 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u02', capituloId: 'c02_01'
  },
  {
    id: 'telmisartan', nombre: 'Telmisartán', nombreGenerico: 'Telmisartán',
    nombresComerciales: ['Micardis', 'Pritor', 'Telmisartán Gador'],
    familia: 'Antihipertensivos', clasificacion: 'ARA-II con actividad PPARγ',
    mecanismoAccion: 'Bloqueo selectivo AT1 con actividad agonista parcial PPARγ. Vida media más larga de todos los ARA-II (24h).',
    indicaciones: ['Hipertensión arterial', 'Prevención cardiovascular en alto riesgo', 'Nefroprotección en DM2'],
    contraindicaciones: ['Embarazo', 'Obstrucción biliar', 'Insuficiencia hepática grave'],
    efectosAdversos: ['Mareo', 'Diarrea', 'Hipotensión', 'Hiperpotasemia'],
    interacciones: ['Digoxina: aumenta niveles', 'AINEs: reduce eficacia', 'Litio: toxicidad'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'HTA: 40-80 mg/día. Prevención CV: 80 mg/día' },
    presentaciones: ['Comprimidos 20, 40, 80 mg'],
    embarazo: 'D', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Vida media más larga de los ARA-II: cobertura 24h real', 'Actividad PPARγ: beneficio metabólico', 'Proteger de humedad', 'Monitorizar PA, potasio, creatinina'],
    farmacocinetica: { absorcion: 'Oral, biodisponibilidad 42-58%', metabolismo: 'Glucuronidación (no CYP)', excrecion: 'Fecal >97%', vidaMedia: '24 horas', inicioAccion: '1-2 horas', duracionAccion: '24+ horas' },
    almacenamiento: 'Proteger de humedad.', unidadId: 'u02', capituloId: 'c02_01'
  },
  {
    id: 'repaglinida', nombre: 'Repaglinida', nombreGenerico: 'Repaglinida',
    nombresComerciales: ['Prandin', 'NovoNorm'],
    familia: 'Antidiabéticos', clasificacion: 'Meglitinida (secretagogo rápido)',
    mecanismoAccion: 'Estimula secreción de insulina bloqueando canales de K+ ATP-dependientes. Acción más rápida y corta que sulfonilureas.',
    indicaciones: ['DM2: control glucemia postprandial', 'Alternativa a sulfonilureas con horarios irregulares'],
    contraindicaciones: ['DM tipo 1', 'Cetoacidosis', 'Uso con gemfibrozil'],
    efectosAdversos: ['Hipoglucemia (menor que sulfonilureas)', 'Aumento de peso', 'Cefalea'],
    interacciones: ['Gemfibrozil: CONTRAINDICADO (aumenta 8x)', 'Claritromicina: aumenta niveles', 'Rifampicina: reduce eficacia'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '0.5-4 mg antes de cada comida. Máx: 16 mg/día. No come = no toma' },
    presentaciones: ['Comprimidos 0.5, 1, 2 mg'],
    embarazo: 'C', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Tomar 15-30 min antes de comida', 'Si salta comida: NO tomar dosis', 'Menor hipoglucemia que sulfonilureas', 'Ideal para horarios irregulares'],
    farmacocinetica: { absorcion: 'Oral rápida', metabolismo: 'Hepático CYP2C8, CYP3A4', excrecion: 'Fecal 90%', vidaMedia: '1 hora', inicioAccion: '15-30 min', duracionAccion: '4 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u06', capituloId: 'c06_01'
  },
  {
    id: 'sofosbuvir', nombre: 'Sofosbuvir', nombreGenerico: 'Sofosbuvir',
    nombresComerciales: ['Sovaldi'],
    familia: 'Antivirales', clasificacion: 'Inhibidor NS5B del VHC',
    mecanismoAccion: 'Profármaco nucleotídico que inhibe la ARN polimerasa NS5B del VHC como terminador de cadena.',
    indicaciones: ['Hepatitis C crónica (genotipos 1-6)', 'Siempre en combinación con otros DAA'],
    contraindicaciones: ['Uso con amiodarona', 'Monoterapia'],
    efectosAdversos: ['Fatiga', 'Cefalea', 'Náuseas', '⚠️ Bradicardia severa con amiodarona', 'Reactivación hepatitis B'],
    interacciones: ['Amiodarona: bradicardia fatal', 'Rifampicina: reduce niveles', 'Inductores P-gp: contraindicados'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '400 mg/día en combinación. 8-24 semanas según genotipo' },
    presentaciones: ['Comprimidos 400 mg'],
    embarazo: 'B', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Screening HBV obligatorio', 'NUNCA con amiodarona', 'Curación >95% con combinaciones modernas', 'Adherencia crítica'],
    farmacocinetica: { absorcion: 'Oral >80%', metabolismo: 'Fosforilación intracelular', excrecion: 'Renal 80%', vidaMedia: '0.4h (metabolito activo: 27h)', inicioAccion: 'Horas', duracionAccion: '24 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u03', capituloId: 'c03_04'
  },
  {
    id: 'lacosamida', nombre: 'Lacosamida', nombreGenerico: 'Lacosamida',
    nombresComerciales: ['Vimpat'],
    familia: 'Anticonvulsivantes', clasificacion: 'Modulador canales de sodio (inactivación lenta)',
    mecanismoAccion: 'Favorece selectivamente la inactivación lenta de canales de sodio, a diferencia de otros FAE que actúan sobre la inactivación rápida.',
    indicaciones: ['Epilepsia focal con o sin generalización', 'Status epiléptico refractario (off-label)'],
    contraindicaciones: ['Bloqueo AV 2°-3° grado'],
    efectosAdversos: ['Mareo', 'Diplopía', 'Náuseas', 'Ataxia', '⚠️ Prolongación PR', '⚠️ Ideación suicida'],
    interacciones: ['Fármacos que prolongan PR: riesgo bloqueo AV', 'Pocas interacciones CYP'],
    viaAdministracion: ['oral', 'IV'],
    dosis: { adulto: 'Inicio: 50 mg/12h. Titular 50 mg/semana. Meta: 150-200 mg/12h', ajusteRenal: 'Máx 300 mg/día si ClCr <30' },
    presentaciones: ['Comprimidos 50, 100, 150, 200 mg', 'Jarabe 10 mg/mL', 'Sol. IV 10 mg/mL'],
    embarazo: 'C', lactancia: 'Evaluar riesgo/beneficio.',
    cuidadosEnfermeria: ['ECG basal y durante titulación', 'Conversión IV-oral 1:1', 'Titular gradualmente', 'Mecanismo único: útil cuando otros FAE fallan'],
    farmacocinetica: { absorcion: 'Oral ~100%', metabolismo: 'Hepático CYP2C19', excrecion: 'Renal 95%', vidaMedia: '13 horas', inicioAccion: 'Oral 1-4h', duracionAccion: '12 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u01', capituloId: 'c01_04'
  },
  {
    id: 'perampanel', nombre: 'Perampanel', nombreGenerico: 'Perampanel',
    nombresComerciales: ['Fycompa'],
    familia: 'Anticonvulsivantes', clasificacion: 'Antagonista no competitivo receptor AMPA',
    mecanismoAccion: 'Primer antagonista selectivo de receptores de glutamato AMPA postsinápticos. Reduce excitación glutamatérgica.',
    indicaciones: ['Epilepsia focal (≥4 años)', 'Crisis tónico-clónicas generalizadas (≥12 años)'],
    contraindicaciones: ['Insuficiencia hepática grave'],
    efectosAdversos: ['Mareo', 'Somnolencia', 'Irritabilidad/agresividad', 'Ataxia', '⚠️ Trastornos psiquiátricos'],
    interacciones: ['Carbamazepina/fenitoína: reducen niveles', 'Alcohol: potencia sedación', 'ACO: puede reducir eficacia a ≥12 mg'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Inicio: 2 mg/día al acostarse. Titular 2 mg/semana. Meta: 4-12 mg/día' },
    presentaciones: ['Comprimidos 2, 4, 6, 8, 10, 12 mg', 'Suspensión 0.5 mg/mL'],
    embarazo: 'C', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Administrar al acostarse', 'Monitorizar comportamiento y ánimo', 'Evitar alcohol', 'Mecanismo único (AMPA)'],
    farmacocinetica: { absorcion: 'Oral completa', metabolismo: 'Hepático CYP3A4', excrecion: 'Fecal 48%, renal 22%', vidaMedia: '105 horas', inicioAccion: 'Horas', duracionAccion: '24+ horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u01', capituloId: 'c01_04'
  },
  {
    id: 'timolol_oftalm', nombre: 'Timolol oftálmico', nombreGenerico: 'Timolol maleato',
    nombresComerciales: ['Timoptic', 'Cusimolol'],
    familia: 'Antiglaucomatosos', clasificacion: 'Betabloqueante oftálmico',
    mecanismoAccion: 'Bloquea β1/β2 en cuerpo ciliar, reduciendo producción de humor acuoso y PIO.',
    indicaciones: ['Glaucoma de ángulo abierto', 'Hipertensión ocular'],
    contraindicaciones: ['Asma', 'EPOC severo', 'Bradicardia', 'Bloqueo AV'],
    efectosAdversos: ['Ardor ocular', 'Ojo seco', '⚠️ Bradicardia sistémica', '⚠️ Broncoespasmo'],
    interacciones: ['BB sistémicos: efecto aditivo', 'Verapamilo: bradicardia'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1 gota 0.25-0.5% cada 12h' },
    presentaciones: ['Solución oftálmica 0.25%, 0.5%', 'Gel 0.1%'],
    embarazo: 'C', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['Ocluir punto lagrimal 1-2 min (reduce absorción sistémica)', 'Preguntar por asma/EPOC', 'Esperar 5 min entre colirios', 'Vigilar FC'],
    farmacocinetica: { absorcion: 'Corneal. Absorción sistémica por mucosa nasal', vidaMedia: '4 horas', inicioAccion: '20 min', picoAccion: '1-2 horas', duracionAccion: '12-24 horas' },
    almacenamiento: 'Temperatura ambiente. Descartar 28 días tras abrir.', unidadId: 'u09', capituloId: 'c09_06'
  },
  {
    id: 'latanoprost', nombre: 'Latanoprost', nombreGenerico: 'Latanoprost',
    nombresComerciales: ['Xalatan', 'Galenox Ofteno'],
    familia: 'Antiglaucomatosos', clasificacion: 'Análogo de prostaglandina F2α',
    mecanismoAccion: 'Agonista FP que aumenta drenaje uveoescleral del humor acuoso. El antiglaucomatoso más potente en monoterapia.',
    indicaciones: ['Glaucoma de ángulo abierto', 'Hipertensión ocular (primera línea)'],
    contraindicaciones: ['Uveítis activa (precaución)'],
    efectosAdversos: ['Hiperemia conjuntival', 'Oscurecimiento irreversible del iris', 'Crecimiento de pestañas', '⚠️ Edema macular en pseudofáquicos'],
    interacciones: ['Timolol: combinación frecuente', 'No combinar con otros análogos PG'],
    viaAdministracion: ['oftalmica'],
    dosis: { adulto: '1 gota 0.005% por la noche' },
    presentaciones: ['Solución oftálmica 0.005% (2.5 mL)'],
    embarazo: 'C', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['Administrar POR LA NOCHE', 'Advertir: oscurecimiento iris irreversible', 'Pestañas crecerán más', 'Retirar lentes 15 min antes', 'Ocluir punto lagrimal'],
    farmacocinetica: { absorcion: 'Corneal, activación por hidrólisis', metabolismo: 'Hepático', vidaMedia: '17 min (local)', inicioAccion: '3-4 horas', duracionAccion: '24 horas' },
    almacenamiento: 'Refrigerar sin abrir. Abierto: TA 6 semanas.', unidadId: 'u09', capituloId: 'c09_06'
  },
  {
    id: 'mepolizumab', nombre: 'Mepolizumab', nombreGenerico: 'Mepolizumab',
    nombresComerciales: ['Nucala'],
    familia: 'Anticuerpos monoclonales', clasificacion: 'Anti-IL-5',
    mecanismoAccion: 'Se une a IL-5, reduce eosinófilos circulantes y tisulares.',
    indicaciones: ['Asma eosinofílica grave (≥6 años)', 'GEPA', 'Síndrome hipereosinofílico'],
    contraindicaciones: ['Hipersensibilidad'],
    efectosAdversos: ['Cefalea', 'Dolor en sitio de inyección', '⚠️ Anafilaxia (rara)', 'Herpes zóster'],
    interacciones: ['No significativas'],
    viaAdministracion: ['SC'],
    dosis: { adulto: 'Asma: 100 mg SC/4 sem. GEPA: 300 mg SC/4 sem', pediatrico: '6-11 años: 40 mg SC/4 sem' },
    presentaciones: ['Jeringa precargada 100 mg', 'Vial 100 mg'],
    embarazo: 'B', lactancia: 'Evaluar riesgo/beneficio.',
    cuidadosEnfermeria: ['Eosinófilos ≥150/µL para indicación', 'NO para crisis aguda', 'Se puede autoadministrar', 'No suspender terapia inhalatoria'],
    farmacocinetica: { absorcion: 'SC, biodisponibilidad 80%', vidaMedia: '16-22 días', inicioAccion: 'Semanas', duracionAccion: '4 semanas' },
    almacenamiento: 'Refrigerar 2-8°C.', unidadId: 'u04', capituloId: 'c04_05'
  },
  {
    id: 'tenecteplasa', nombre: 'Tenecteplasa', nombreGenerico: 'Tenecteplasa',
    nombresComerciales: ['Metalyse', 'TNKase'],
    familia: 'Trombolíticos', clasificacion: 'Activador tisular del plasminógeno recombinante modificado',
    mecanismoAccion: 'tPA modificado con mayor afinidad por fibrina y vida media más larga. Convierte plasminógeno en plasmina. Ventaja: dosis única en bolo.',
    indicaciones: ['IAMCEST', 'TEP masivo (off-label)', 'ACV isquémico (investigación)'],
    contraindicaciones: ['Sangrado activo', 'ACV hemorrágico previo', 'Cirugía <3 semanas', 'HTA severa >180/110'],
    efectosAdversos: ['Sangrado', 'Arritmias de reperfusión', '⚠️ Hemorragia intracraneal (0.9%)'],
    interacciones: ['Anticoagulantes/antiplaquetarios: mayor sangrado'],
    viaAdministracion: ['IV'],
    dosis: { adulto: 'Bolo IV único: <60 kg: 30 mg, 60-70: 35 mg, 70-80: 40 mg, 80-90: 45 mg, >90: 50 mg' },
    presentaciones: ['Viales 40, 50 mg'],
    embarazo: 'C', lactancia: 'Uso de emergencia.',
    cuidadosEnfermeria: ['DOSIS ÚNICA en bolo IV (5-10 seg)', 'Puerta-aguja <30 min', 'No requiere infusión continua', 'Evitar punciones 24h post', 'Heparina según protocolo post-trombólisis'],
    farmacocinetica: { metabolismo: 'Hepático', vidaMedia: '20-24 min', inicioAccion: 'Inmediato', duracionAccion: 'Horas' },
    almacenamiento: 'Refrigerar. Usar inmediatamente tras reconstituir.', unidadId: 'u10', capituloId: 'c10_01'
  },
  {
    id: 'torasemida', nombre: 'Torasemida', nombreGenerico: 'Torasemida',
    nombresComerciales: ['Demadex', 'Sutril'],
    familia: 'Diuréticos', clasificacion: 'Diurético de asa',
    mecanismoAccion: 'Inhibe cotransportador Na+/K+/2Cl- en asa de Henle. Absorción más predecible que furosemida.',
    indicaciones: ['IC (edema)', 'Edema hepático', 'Edema renal', 'HTA'],
    contraindicaciones: ['Anuria', 'Coma hepático', 'Hipopotasemia severa'],
    efectosAdversos: ['Hipopotasemia', 'Hiponatremia', 'Hiperuricemia', 'Hipotensión'],
    interacciones: ['Aminoglucósidos: ototoxicidad', 'Digoxina: hipopotasemia peligrosa', 'AINEs: reduce diuresis'],
    viaAdministracion: ['oral', 'IV'],
    dosis: { adulto: 'IC: 10-20 mg/día, máx 200 mg. HTA: 5-10 mg/día' },
    presentaciones: ['Comprimidos 5, 10, 20, 100 mg', 'Ampollas 10, 20 mg'],
    embarazo: 'B', lactancia: 'No recomendado.',
    cuidadosEnfermeria: ['Biodisponibilidad 80% (vs 50% furosemida)', 'Menor ototoxicidad', 'Pesar diariamente en IC', 'Monitorizar K+, Na+', 'Conversión: 20 mg ≈ furosemida 40 mg'],
    farmacocinetica: { absorcion: 'Oral ~80%', metabolismo: 'Hepático CYP2C9', excrecion: 'Renal 80%', vidaMedia: '3.5 horas', inicioAccion: 'Oral 1h, IV 10 min', duracionAccion: '6-8 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u02', capituloId: 'c02_04'
  },
  {
    id: 'bemiparina', nombre: 'Bemiparina', nombreGenerico: 'Bemiparina sódica',
    nombresComerciales: ['Hibor', 'Zibor'],
    familia: 'Anticoagulantes', clasificacion: 'HBPM de 2ª generación (menor peso molecular)',
    mecanismoAccion: 'HBPM con el menor peso molecular (3600 Da). Mayor selectividad anti-Xa/anti-IIa (8:1).',
    indicaciones: ['Profilaxis TVP quirúrgica', 'Tratamiento TVP', 'Profilaxis en pacientes inmovilizados'],
    contraindicaciones: ['Sangrado activo', 'HIT', 'ClCr <15'],
    efectosAdversos: ['Hematoma en sitio', 'Sangrado', '⚠️ HIT tipo II', '⚠️ Hemorragia mayor'],
    interacciones: ['AINEs: sangrado', 'Antiagregantes: sangrado aditivo'],
    viaAdministracion: ['SC'],
    dosis: { adulto: 'Profilaxis: 2500-3500 UI SC/día. Tratamiento: 115 UI/kg/día' },
    presentaciones: ['Jeringas precargadas 2500, 3500, 5000, 7500, 10000 UI'],
    embarazo: 'B', lactancia: 'Compatible.',
    cuidadosEnfermeria: ['SC en abdomen, pliegue cutáneo', 'No aspirar ni frotar', 'Rotar sitios', 'Plaquetas a los 5-7 días (HIT)', 'Menor peso molecular = más predecible'],
    farmacocinetica: { absorcion: 'SC 96%', excrecion: 'Renal', vidaMedia: '5-6 horas', inicioAccion: '30 min', duracionAccion: '18-24 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u10', capituloId: 'c10_01'
  },
  {
    id: 'metocarbamol', nombre: 'Metocarbamol', nombreGenerico: 'Metocarbamol',
    nombresComerciales: ['Robaxin', 'Robaxisal'],
    familia: 'Relajantes musculares', clasificacion: 'Relajante muscular central',
    mecanismoAccion: 'Deprime transmisión polisináptica en médula espinal. No actúa en unión neuromuscular.',
    indicaciones: ['Espasmo muscular doloroso', 'Lumbalgia aguda', 'Cervicalgia', 'Coadyuvante en tétanos'],
    contraindicaciones: ['Miastenia gravis', 'Epilepsia (IV)'],
    efectosAdversos: ['Somnolencia', 'Mareo', 'Orina oscura (normal)', 'Sabor metálico'],
    interacciones: ['Depresores SNC: sedación aditiva', 'Alcohol: potencia efectos'],
    viaAdministracion: ['oral', 'IV', 'IM'],
    dosis: { adulto: 'Oral: 1500 mg cada 6-8h (3 días), luego 750 mg cada 8h. IV: 1 g cada 8h' },
    presentaciones: ['Comprimidos 500, 750 mg', 'Ampollas 1 g/10 mL'],
    embarazo: 'C', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['IV: no exceder 3 mL/min', 'Orina marrón/negra/verde: normal', 'No conducir', 'Uso corto: 2-3 semanas', 'Combinar con AINE + fisioterapia'],
    farmacocinetica: { absorcion: 'Oral rápida', metabolismo: 'Hepático', excrecion: 'Renal', vidaMedia: '1-2 horas', inicioAccion: 'Oral 30 min, IV inmediato', duracionAccion: '4-6 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u08', capituloId: 'c08_02'
  },
  {
    id: 'micafungina', nombre: 'Micafungina', nombreGenerico: 'Micafungina sódica',
    nombresComerciales: ['Mycamine'],
    familia: 'Equinocandinas', clasificacion: 'Antifúngico (inhibidor β-1,3-glucano sintetasa)',
    mecanismoAccion: 'Inhibe síntesis de β-1,3-D-glucano de la pared fúngica. Fungicida vs Candida, fungistático vs Aspergillus.',
    indicaciones: ['Candidemia/candidiasis invasiva', 'Candidiasis esofágica', 'Profilaxis en trasplante hematopoyético'],
    contraindicaciones: ['Hipersensibilidad a equinocandinas'],
    efectosAdversos: ['Cefalea', 'Náuseas', 'Flebitis', '⚠️ Hepatotoxicidad'],
    interacciones: ['Sirolimus: aumenta niveles', 'Nifedipino: aumenta niveles'],
    viaAdministracion: ['IV'],
    dosis: { adulto: 'Candidemia: 100 mg/día. Esofágica: 150 mg/día. Profilaxis: 50 mg/día' },
    presentaciones: ['Viales 50, 100 mg'],
    embarazo: 'C', lactancia: 'Precaución.',
    cuidadosEnfermeria: ['Reconstituir con SF (no dextrosa)', 'Infusión en 1h', 'Proteger de la luz', 'Función hepática semanal', 'Menos interacciones que caspofungina'],
    farmacocinetica: { metabolismo: 'Hepático (no CYP)', excrecion: 'Fecal 71%', vidaMedia: '11-17 horas', inicioAccion: 'Inmediato', duracionAccion: '24 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u03', capituloId: 'c03_04'
  },
  {
    id: 'praziquantel', nombre: 'Praziquantel', nombreGenerico: 'Praziquantel',
    nombresComerciales: ['Biltricide', 'Cisticid'],
    familia: 'Antihelmínticos', clasificacion: 'Antiparasitario de amplio espectro',
    mecanismoAccion: 'Aumenta permeabilidad al calcio del parásito causando contracción muscular, vacuolización y desintegración.',
    indicaciones: ['Esquistosomiasis (todas las especies)', 'Neurocisticercosis', 'Teniasis', 'Difilobotriasis'],
    contraindicaciones: ['Cisticercosis ocular'],
    efectosAdversos: ['Náuseas', 'Dolor abdominal', 'Cefalea', 'Mareo', '⚠️ Convulsiones en neurocisticercosis'],
    interacciones: ['Dexametasona: reduce niveles', 'Rifampicina: reduce eficacia', 'Cimetidina: aumenta niveles'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Esquistosomiasis: 40-60 mg/kg en 1-3 tomas (1 día). Teniasis: 5-10 mg/kg dosis única. Neurocisticercosis: 50 mg/kg/día x 14 días' },
    presentaciones: ['Comprimidos 150, 600 mg'],
    embarazo: 'B', lactancia: 'Suspender 72h.',
    cuidadosEnfermeria: ['Con alimentos y líquido abundante', 'NO masticar (muy amargo)', 'Neurocisticercosis: hospitalizar, premedicar con corticoides + anticonvulsivantes', 'Eficacia >85% esquistosomiasis dosis única'],
    farmacocinetica: { absorcion: 'Oral ~80%', metabolismo: 'Hepático extenso', excrecion: 'Renal >80%', vidaMedia: '0.8-1.5 horas', inicioAccion: '1-3 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u03', capituloId: 'c03_06'
  },
  {
    id: 'carbimazol', nombre: 'Carbimazol', nombreGenerico: 'Carbimazol',
    nombresComerciales: ['Neo-Mercazole'],
    familia: 'Antitiroideos', clasificacion: 'Profármaco de metimazol (tionamida)',
    mecanismoAccion: 'Convertido a metimazol. Inhibe tiroperoxidasa bloqueando síntesis de T3 y T4.',
    indicaciones: ['Hipertiroidismo (Graves)', 'Preparación para tiroidectomía', 'Crisis tirotóxica'],
    contraindicaciones: ['Agranulocitosis previa por tionamidas'],
    efectosAdversos: ['Rash', 'Artralgias', '⚠️ Agranulocitosis (0.1-0.5%)', '⚠️ Hepatotoxicidad'],
    interacciones: ['Warfarina: ajustar al corregir tiroides', 'BB: ajustar al normalizar'],
    viaAdministracion: ['oral'],
    dosis: { adulto: 'Inicio: 15-40 mg/día. Mantenimiento: 5-15 mg/día. Crisis: 60-80 mg/día' },
    presentaciones: ['Comprimidos 5, 10, 20 mg'],
    embarazo: 'D', lactancia: 'Dosis <15 mg/día con monitoreo neonatal.',
    cuidadosEnfermeria: ['Hemograma ante fiebre/odinofagia (URGENTE)', 'TSH y T4L cada 4-6 semanas', 'Efecto tarda 1-3 semanas', 'En 1er trimestre: preferir propiltiouracilo'],
    farmacocinetica: { absorcion: 'Oral rápida', metabolismo: 'Hepático a metimazol', vidaMedia: 'Metimazol: 4-6h (efecto 24h)', inicioAccion: '1-3 semanas', duracionAccion: '24 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u06', capituloId: 'c06_02'
  },
  {
    id: 'acetilcisteina_inhalada', nombre: 'N-Acetilcisteína inhalada', nombreGenerico: 'N-Acetilcisteína',
    nombresComerciales: ['Mucomyst', 'Fluimucil inhalatorio'],
    familia: 'Mucolíticos', clasificacion: 'Mucolítico (ruptura puentes disulfuro)',
    mecanismoAccion: 'Rompe puentes disulfuro de mucoproteínas, reduciendo viscosidad del esputo.',
    indicaciones: ['Fibrosis quística', 'Bronquiectasias con esputo espeso', 'Atelectasia por tapón mucoso'],
    contraindicaciones: ['Asma activa (broncoespasmo)'],
    efectosAdversos: ['Broncoespasmo (premedicar)', 'Náuseas', 'Olor azufre'],
    interacciones: ['Antibióticos inhalados: administrar separados', 'Inactiva aminoglucósidos si se mezclan'],
    viaAdministracion: ['inhalatoria', 'oral', 'IV'],
    dosis: { adulto: '3-5 mL de sol. 20% cada 6-8h nebulizado' },
    presentaciones: ['Solución 10%, 20%'],
    embarazo: 'B', lactancia: 'Probablemente compatible.',
    cuidadosEnfermeria: ['PREMEDICAR con salbutamol 15 min antes', 'Olor a huevo podrido: advertir', 'No mezclar con antibióticos en nebulizador', 'Aspirar si no expectora', 'Monitorizar SatO2'],
    farmacocinetica: { absorcion: 'Inhalada: local', metabolismo: 'Desacetilación', vidaMedia: '5.6h (sistémica)', inicioAccion: '1 min inhalada', duracionAccion: '2-4 horas' },
    almacenamiento: 'Refrigerar abierto. Usar en 96h.', unidadId: 'u04', capituloId: 'c04_03'
  },
  {
    id: 'alvimopan', nombre: 'Alvimopán', nombreGenerico: 'Alvimopán',
    nombresComerciales: ['Entereg'],
    familia: 'Procinéticos hospitalarios', clasificacion: 'Antagonista periférico de receptores opioides mu',
    mecanismoAccion: 'Bloquea receptores mu en tracto GI sin cruzar BHE. Contrarresta íleo por opioides sin afectar analgesia.',
    indicaciones: ['Recuperación acelerada de íleo postoperatorio tras resección intestinal'],
    contraindicaciones: ['Opioides crónicos >7 días pre-cirugía', 'Obstrucción mecánica'],
    efectosAdversos: ['Dispepsia', 'Flatulencia', 'Hipopotasemia'],
    interacciones: ['Opioides: antagoniza efecto GI sin afectar analgesia central'],
    viaAdministracion: ['oral'],
    dosis: { adulto: '12 mg 30 min-5h pre-cirugía. Luego 12 mg/12h post-op. Máx: 15 dosis (7 días)' },
    presentaciones: ['Cápsulas 12 mg'],
    embarazo: 'B', lactancia: 'Uso hospitalario corto.',
    cuidadosEnfermeria: ['Solo intrahospitalario', 'Máx 15 dosis', 'Monitorizar peristaltismo, gases, deposición', 'No usar en opioides crónicos'],
    farmacocinetica: { absorcion: 'Oral, biodisponibilidad 6%', metabolismo: 'Flora intestinal, hepático', excrecion: 'Fecal 80%', vidaMedia: '10-17 horas', duracionAccion: '12 horas' },
    almacenamiento: 'Temperatura ambiente.', unidadId: 'u05', capituloId: 'c05_03'
  }
];

let added = 0;
for (const d of newDrugs) {
  if (existingIds.has(d.id)) { console.log('SKIP:', d.id); continue; }
  d.searchText = mkSearch(d);
  drugs.push(d);
  existingIds.add(d.id);
  for (const u of cats.unidades) {
    for (const c of u.capitulos) {
      if (c.id === d.capituloId && !c.drugIds.includes(d.id)) {
        c.drugIds.push(d.id);
      }
    }
  }
  added++;
}

fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log('Added: ' + added + '. Total drugs: ' + drugs.length);
