const fs = require('fs');
const path = require('path');
const drugsPath = path.join(__dirname, '..', 'src', 'data', 'drugs.json');
const catsPath = path.join(__dirname, '..', 'src', 'data', 'categories.json');
const drugs = JSON.parse(fs.readFileSync(drugsPath, 'utf8'));
const cats = JSON.parse(fs.readFileSync(catsPath, 'utf8'));

function mkSearch(d) {
  return [d.nombre, d.nombreGenerico, ...d.nombresComerciales, d.familia, d.clasificacion].join(' ').toLowerCase();
}
function addDrug(d) {
  d.searchText = mkSearch(d);
  if (drugs.some(x => x.id === d.id)) { console.log('SKIP duplicate:', d.id); return; }
  drugs.push(d);
  for (const u of cats.unidades) {
    for (const c of u.capitulos) {
      if (c.id === d.capituloId) { if (!c.drugIds.includes(d.id)) c.drugIds.push(d.id); return; }
    }
  }
}

const D = [
  {id:"nefopam",nombre:"Nefopam",nombreGenerico:"nefopam",nombresComerciales:["Acupan"],familia:"Analgésicos centrales no opioides",clasificacion:"Analgésico no opioide",mecanismoAccion:"Inhibe la recaptación de serotonina, noradrenalina y dopamina a nivel central sin actuar sobre receptores opioides.",indicaciones:["Dolor agudo moderado","Dolor postoperatorio","Dolor nociceptivo refractario a analgésicos periféricos"],contraindicaciones:["Epilepsia no controlada","Glaucoma de ángulo cerrado","Retención urinaria","Menores de 15 años"],efectosAdversos:["Náuseas","Sudoración","Somnolencia","Taquicardia","Retención urinaria","Sequedad bucal"],interacciones:["Anticolinérgicos (efecto aditivo)","IMAO (contraindicado)","Tramadol (riesgo convulsiones)"],viaAdministracion:["IV","IM","oral"],dosis:{adulto:"20 mg IV/IM cada 6-8h; oral 60 mg/8h",pediatrico:"No recomendado en <15 años",ajusteRenal:"Precaución en IR severa"},presentaciones:["Ampolla 20 mg/2 mL","Comprimidos 30 mg"],embarazo:"C",lactancia:"No recomendado, se excreta en leche materna",cuidadosEnfermeria:["Administrar IV lento en 15-20 min (riesgo taquicardia)","Monitorizar FC y TA durante infusión","No mezclar con otros fármacos en la misma jeringa","Valorar retención urinaria"],farmacocinetica:{absorcion:"Oral biodisponibilidad 36%",distribucion:"UP 71-76%",metabolismo:"Hepático extenso",excrecion:"Renal 87%",vidaMedia:"4-8 horas",inicioAccion:"15-30 min IV",picoAccion:"1 hora",duracionAccion:"4-6 horas"},almacenamiento:"Temperatura ambiente, proteger de la luz",unidadId:"u01",capituloId:"c01_01"},

  {id:"meperidina",nombre:"Meperidina (Petidina)",nombreGenerico:"meperidina",nombresComerciales:["Demerol","Dolantina"],familia:"Opioides",clasificacion:"Agonista mu opioide",mecanismoAccion:"Agonista de receptores opioides mu con efecto anticolinérgico leve. Su metabolito normeperidina es neurotóxico y proconvulsivante.",indicaciones:["Dolor agudo moderado-severo","Escalofríos postanestésicos","Dolor de trabajo de parto"],contraindicaciones:["Uso de IMAO (últimos 14 días)","Insuficiencia renal","Epilepsia","Uso crónico"],efectosAdversos:["Náuseas y vómitos","Sedación","Depresión respiratoria","Convulsiones (normeperidina)","Hipotensión","Mioclonías"],interacciones:["IMAO (crisis serotoninérgica, contraindicado)","Benzodiazepinas (depresión respiratoria)","ISRS (síndrome serotoninérgico)"],viaAdministracion:["IV","IM","SC","oral"],dosis:{adulto:"50-150 mg IM/SC cada 3-4h; IV 25-50 mg lento",pediatrico:"1-1.5 mg/kg IM cada 3-4h (máx 100 mg)",ajusteRenal:"Contraindicado en IR"},presentaciones:["Ampolla 50 mg/mL","Ampolla 100 mg/2 mL"],embarazo:"C",lactancia:"Se excreta en leche, uso con precaución",cuidadosEnfermeria:["No usar más de 48-72h (acumulación normeperidina)","Monitorizar FR, SatO2 y conciencia","IV lento para evitar hipotensión","Tener naloxona disponible","Verificar que no use IMAO"],farmacocinetica:{absorcion:"Oral BD 50-60%",distribucion:"Cruza BHE y placenta, UP 60-80%",metabolismo:"Hepático a normeperidina (neurotóxico)",excrecion:"Renal",vidaMedia:"3-4h (normeperidina 15-30h)",inicioAccion:"10-15 min IM, 5 min IV",picoAccion:"30-60 min IM",duracionAccion:"2-4 horas"},almacenamiento:"Temperatura ambiente. Estupefaciente controlado.",unidadId:"u01",capituloId:"c01_02"},

  {id:"sufentanilo",nombre:"Sufentanilo",nombreGenerico:"sufentanilo",nombresComerciales:["Sufenta","Dsuvia"],familia:"Opioides",clasificacion:"Agonista mu opioide potente",mecanismoAccion:"Agonista selectivo mu. 5-10x más potente que fentanilo, 500-1000x más que morfina.",indicaciones:["Analgesia en anestesia general","Analgesia epidural en trabajo de parto","Dolor postoperatorio severo"],contraindicaciones:["Depresión respiratoria severa","Asma aguda sin ventilación","Hipersensibilidad"],efectosAdversos:["Depresión respiratoria","Rigidez torácica","Bradicardia","Náuseas","Prurito epidural","Retención urinaria"],interacciones:["Benzodiazepinas (depresión respiratoria)","IMAO (contraindicado)","Inhibidores CYP3A4 (aumentan niveles)"],viaAdministracion:["IV","epidural"],dosis:{adulto:"Anestesia: 1-8 mcg/kg IV; Epidural: 10-15 mcg",pediatrico:"Cardíaca pediátrica: 10-25 mcg/kg IV",ajusteRenal:"Reducir dosis"},presentaciones:["Ampolla 50 mcg/mL (1, 2, 5 mL)"],embarazo:"C",lactancia:"Precaución, evitar lactancia post-uso",cuidadosEnfermeria:["Uso exclusivo por anestesia/UCI","Monitorización continua: ECG, SatO2, capnografía","Tener naloxona y reanimación disponible","Vigilar rigidez torácica"],farmacocinetica:{absorcion:"N/A (IV/epidural)",distribucion:"Alta liposolubilidad, UP 93%",metabolismo:"Hepático CYP3A4",excrecion:"Renal 80%",vidaMedia:"2.5 horas",inicioAccion:"1-3 min IV",picoAccion:"3-5 min IV",duracionAccion:"30-60 min IV"},almacenamiento:"Temperatura ambiente. Estupefaciente controlado.",unidadId:"u01",capituloId:"c01_02"},

  {id:"alfentanilo",nombre:"Alfentanilo",nombreGenerico:"alfentanilo",nombresComerciales:["Alfenta","Rapifen"],familia:"Opioides",clasificacion:"Agonista mu opioide de acción ultracorta",mecanismoAccion:"Agonista mu con inicio muy rápido y duración muy corta. 1/4-1/10 potencia de fentanilo.",indicaciones:["Analgesia en procedimientos cortos","Inducción anestésica","Cirugías ambulatorias"],contraindicaciones:["Depresión respiratoria sin ventilación asistida","Uso de IMAO","Hipersensibilidad"],efectosAdversos:["Depresión respiratoria","Rigidez muscular","Bradicardia","Náuseas postoperatorias","Apnea"],interacciones:["Inhibidores CYP3A4 (eritromicina, ketoconazol)","Benzodiazepinas (depresión SNC)","Propofol (sinergia)"],viaAdministracion:["IV"],dosis:{adulto:"Procedimiento corto: 8-20 mcg/kg; Mantenimiento: 5-15 mcg/kg",pediatrico:"10-20 mcg/kg para procedimientos cortos"},presentaciones:["Ampolla 500 mcg/mL (2, 5, 10 mL)"],embarazo:"C",lactancia:"Evitar lactancia 24h post-uso",cuidadosEnfermeria:["Uso solo en áreas con monitorización completa","Inicio muy rápido - tener naloxona lista","Ideal para procedimientos <30 min","No bolo rápido (riesgo rigidez torácica)"],farmacocinetica:{absorcion:"N/A (IV)",distribucion:"Vd 0.4-1 L/kg, UP 92%",metabolismo:"Hepático CYP3A4 extenso",excrecion:"Renal",vidaMedia:"70-90 min",inicioAccion:"30-60 segundos",picoAccion:"1-2 min",duracionAccion:"10-15 min"},almacenamiento:"Temperatura ambiente. Estupefaciente controlado.",unidadId:"u01",capituloId:"c01_02"},

  {id:"isoflurano",nombre:"Isoflurano",nombreGenerico:"isoflurano",nombresComerciales:["Forane"],familia:"Anestésicos inhalados",clasificacion:"Anestésico general inhalatorio",mecanismoAccion:"Potencia GABA-A y bloquea NMDA. Produce anestesia, amnesia y relajación muscular dosis-dependiente.",indicaciones:["Inducción y mantenimiento de anestesia general","Anestesia en cirugías prolongadas"],contraindicaciones:["Hipertermia maligna","Hipersensibilidad a halogenados","Hepatitis previa por halogenados"],efectosAdversos:["Hipotensión dosis-dependiente","Depresión respiratoria","Náuseas y vómitos postoperatorios","Arritmias","Hepatotoxicidad (rara)"],interacciones:["Relajantes musculares no despolarizantes (potenciación)","Opioides (sinergia)","Antihipertensivos (hipotensión aditiva)"],viaAdministracion:["inhalatoria"],dosis:{adulto:"CAM 1.15%; inducción 1.5-3%; mantenimiento 1-2.5%",pediatrico:"CAM neonatos 1.6%, lactantes 1.87%"},presentaciones:["Líquido para inhalación 100 mL, 250 mL"],embarazo:"C",lactancia:"Suspender 24h post-anestesia",cuidadosEnfermeria:["Uso exclusivo por anestesiólogo con vaporizador calibrado","Monitorizar signos vitales, ETCO2, agente espirado","Vigilar hipertermia maligna","Mantener dantroleno disponible"],farmacocinetica:{absorcion:"Rápida vía pulmonar",distribucion:"Coef sangre/gas 1.4",metabolismo:"Hepático mínimo 0.2%",excrecion:"Pulmonar 99.8%",vidaMedia:"Variable",inicioAccion:"2-3 min",picoAccion:"Depende concentración",duracionAccion:"Despertar 5-15 min tras suspensión"},almacenamiento:"Temperatura ambiente, frasco cerrado",unidadId:"u01",capituloId:"c01_03"},

  {id:"oxido_nitroso",nombre:"Óxido Nitroso",nombreGenerico:"óxido nitroso",nombresComerciales:["Entonox","Kalinox"],familia:"Anestésicos inhalados",clasificacion:"Anestésico y analgésico inhalatorio",mecanismoAccion:"Antagonista NMDA. Produce analgesia y sedación consciente a concentraciones subanestésicas.",indicaciones:["Analgesia en trabajo de parto","Sedación consciente en procedimientos","Analgesia en urgencias","Coadyuvante en anestesia general"],contraindicaciones:["Neumotórax","Embolia gaseosa","Obstrucción intestinal","Otitis media aguda","Deficiencia de vitamina B12"],efectosAdversos:["Náuseas y vómitos","Euforia","Difusión hipóxica al suspender","Neuropatía (uso crónico)","Megaloblastosis (prolongado)"],interacciones:["Otros anestésicos (reduce CAM)","Metotrexato (toxicidad B12)","Depresores SNC (sinergia)"],viaAdministracion:["inhalatoria"],dosis:{adulto:"Mezcla 50% N2O/50% O2; anestesia: 50-70% con O2",pediatrico:">1 año: igual que adulto para analgesia"},presentaciones:["Cilindro presurizado mezcla 50/50","Cilindro N2O puro"],embarazo:"C",lactancia:"Seguro, eliminación rápida",cuidadosEnfermeria:["Asegurar O2 mínimo 30%","Áreas bien ventiladas","Paciente debe sostener mascarilla (autorregulación)","O2 puro 5 min post-suspensión (prevenir difusión hipóxica)"],farmacocinetica:{absorcion:"Rápida pulmonar",distribucion:"Coef sangre/gas 0.47 (rápido)",metabolismo:"No se metaboliza",excrecion:"Pulmonar 100%",vidaMedia:"5 min",inicioAccion:"30-60 segundos",picoAccion:"2-5 min",duracionAccion:"3-5 min tras suspensión"},almacenamiento:"Cilindros verticales, lejos del calor",unidadId:"u01",capituloId:"c01_03"},

  {id:"vigabatrina",nombre:"Vigabatrina",nombreGenerico:"vigabatrina",nombresComerciales:["Sabril"],familia:"Anticonvulsivantes",clasificacion:"Inhibidor irreversible de GABA-transaminasa",mecanismoAccion:"Inhibe irreversiblemente la GABA-transaminasa, aumentando niveles de GABA cerebral.",indicaciones:["Espasmos infantiles (síndrome de West)","Epilepsia focal resistente"],contraindicaciones:["Defecto del campo visual preexistente","Hipersensibilidad"],efectosAdversos:["Defectos del campo visual (irreversibles, 30-40%)","Somnolencia","Fatiga","Aumento de peso","Depresión","Psicosis"],interacciones:["Fenitoína (reduce niveles 20-30%)","Antiepilépticos GABAérgicos (sedación aditiva)"],viaAdministracion:["oral"],dosis:{adulto:"500 mg/12h; mantenimiento 1-3 g/día",pediatrico:"Espasmos: 50-150 mg/kg/día",ajusteRenal:"Reducir proporcionalmente al ClCr"},presentaciones:["Comprimidos 500 mg","Sobres 500 mg"],embarazo:"D",lactancia:"No recomendado",cuidadosEnfermeria:["OBLIGATORIO: campimetría basal y cada 6 meses","Educar sobre síntomas de pérdida visual","No suspender bruscamente","Programa REMS de distribución restringida"],farmacocinetica:{absorcion:"Oral completa, BD 80-90%",distribucion:"No se une a proteínas",metabolismo:"No se metaboliza",excrecion:"Renal sin cambios 70%",vidaMedia:"5-8h (efecto dura días)",inicioAccion:"Días",picoAccion:"1-2 horas nivel plasmático",duracionAccion:"Días (inhibición irreversible)"},almacenamiento:"Temperatura ambiente, proteger humedad",unidadId:"u01",capituloId:"c01_04"},

  {id:"zonisamida",nombre:"Zonisamida",nombreGenerico:"zonisamida",nombresComerciales:["Zonegran"],familia:"Anticonvulsivantes",clasificacion:"Antiepiléptico sulfonamida",mecanismoAccion:"Bloquea canales de sodio y calcio tipo T. Inhibe anhidrasa carbónica débilmente.",indicaciones:["Epilepsia focal","Crisis tónico-clónicas generalizadas","Epilepsia mioclónica"],contraindicaciones:["Hipersensibilidad a sulfonamidas","IH grave","Litiasis renal recurrente"],efectosAdversos:["Somnolencia","Anorexia y pérdida de peso","Litiasis renal","Oligohidrosis (niños)","Acidosis metabólica"],interacciones:["Inductores CYP3A4 (reducen niveles)","Topiramato (riesgo litiasis y acidosis aditivo)"],viaAdministracion:["oral"],dosis:{adulto:"100 mg/día inicial; 300-500 mg/día mantenimiento",pediatrico:"1-2 mg/kg/día inicial, hasta 4-8 mg/kg/día",ajusteRenal:"ClCr <20: no recomendado"},presentaciones:["Cápsulas 25, 50, 100 mg"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Monitorizar peso","Asegurar hidratación (prevenir litiasis)","Vigilar temperatura en niños (oligohidrosis)","Controlar bicarbonato sérico"],farmacocinetica:{absorcion:"Oral >90%",distribucion:"Vd 1.45 L/kg, UP 40%",metabolismo:"Hepático CYP3A4",excrecion:"Renal 62%",vidaMedia:"63 horas",inicioAccion:"2-6 horas",picoAccion:"2-6 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_04"},

  {id:"rufinamida",nombre:"Rufinamida",nombreGenerico:"rufinamida",nombresComerciales:["Inovelon","Banzel"],familia:"Anticonvulsivantes",clasificacion:"Antiepiléptico triazol",mecanismoAccion:"Prolonga el estado inactivo de canales de sodio, limitando la descarga neuronal repetitiva.",indicaciones:["Síndrome de Lennox-Gastaut (adyuvante)","Crisis tónicas y atónicas refractarias"],contraindicaciones:["Síndrome QT corto familiar","IH severa"],efectosAdversos:["Somnolencia","Cefalea","Náuseas","Fatiga","Acortamiento QT","Diplopia"],interacciones:["Valproato (aumenta niveles 70%)","Carbamazepina (disminuye niveles)","Anticonceptivos orales (reduce eficacia)"],viaAdministracion:["oral"],dosis:{adulto:"400 mg/día inicial; 1800-3200 mg/día mantenimiento",pediatrico:"≥4 años: 10 mg/kg/día, hasta 45 mg/kg/día"},presentaciones:["Comprimidos 100, 200, 400 mg","Suspensión oral 40 mg/mL"],embarazo:"C",lactancia:"Precaución",cuidadosEnfermeria:["Administrar con alimentos","Titular cada 2 días","ECG si factores riesgo (acortamiento QT)","Comprimidos pueden partirse"],farmacocinetica:{absorcion:"Buena con alimentos",distribucion:"UP 34%",metabolismo:"Hidrólisis por carboxilesterasas",excrecion:"Renal 85%",vidaMedia:"6-10 horas",inicioAccion:"Días",picoAccion:"4-6 horas",duracionAccion:"12 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_04"},

  {id:"estiripentol",nombre:"Estiripentol",nombreGenerico:"estiripentol",nombresComerciales:["Diacomit"],familia:"Anticonvulsivantes",clasificacion:"Modulador GABAérgico",mecanismoAccion:"Potencia GABA-A por modulación alostérica positiva. Inhibe CYP450 prolongando efecto de otros antiepilépticos.",indicaciones:["Síndrome de Dravet (con valproato y clobazam)"],contraindicaciones:["Hipersensibilidad","Psicosis"],efectosAdversos:["Somnolencia marcada","Anorexia","Pérdida de peso","Ataxia","Neutropenia","Trombocitopenia"],interacciones:["Clobazam (aumenta norclobazam 5x)","Carbamazepina (toxicidad)","Fenitoína (toxicidad)"],viaAdministracion:["oral"],dosis:{pediatrico:"50 mg/kg/día en 2-3 tomas con alimentos"},presentaciones:["Cápsulas 250, 500 mg","Polvo 250, 500 mg"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Administrar con alimentos (leche)","Usar con valproato + clobazam","Monitorizar hemograma","Preparar suspensión antes de administrar"],farmacocinetica:{absorcion:"Rápida con alimentos",distribucion:"UP 99%",metabolismo:"Hepático (inhibe CYP1A2, 2C19, 3A4)",excrecion:"Renal 73%",vidaMedia:"4.5-13 horas",inicioAccion:"Días a semanas",picoAccion:"1-2 horas",duracionAccion:"8-12 horas"},almacenamiento:"Temperatura ambiente, proteger de la luz",unidadId:"u01",capituloId:"c01_04"},

  {id:"amantadina",nombre:"Amantadina",nombreGenerico:"amantadina",nombresComerciales:["Symmetrel","Virosol"],familia:"Antiparkinsonianos",clasificacion:"Dopaminérgico / antagonista NMDA",mecanismoAccion:"Aumenta liberación de dopamina, bloquea NMDA y tiene efecto anticolinérgico leve.",indicaciones:["Parkinson leve","Discinesias por levodopa","Fatiga en esclerosis múltiple"],contraindicaciones:["Glaucoma ángulo cerrado","IR grave sin ajuste","Epilepsia no controlada"],efectosAdversos:["Livedo reticularis","Edema periférico","Insomnio","Alucinaciones","Confusión","Hipotensión ortostática"],interacciones:["Anticolinérgicos (efecto aditivo)","Levodopa (potenciación)","Tiazidas (reducen excreción)"],viaAdministracion:["oral"],dosis:{adulto:"100 mg/12h; máx 400 mg/día",pediatrico:">10 años: 100 mg/12h",ajusteRenal:"ClCr 30-50: 200 mg/día; ClCr 15-29: 100 mg/día"},presentaciones:["Cápsulas 100 mg","Jarabe 50 mg/5 mL"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Última dosis antes de las 16h (insomnio)","No suspender bruscamente","Vigilar edema y livedo reticularis","Monitorizar función renal"],farmacocinetica:{absorcion:"BD 86-94%",distribucion:"Vd 3-8 L/kg, UP 67%",metabolismo:"Hepático mínimo",excrecion:"Renal sin cambios 90%",vidaMedia:"10-28 horas",inicioAccion:"48 horas",picoAccion:"2-4 horas",duracionAccion:"12-24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_05"},

  {id:"apomorfina",nombre:"Apomorfina",nombreGenerico:"apomorfina",nombresComerciales:["Apokyn","APO-go"],familia:"Agonistas dopaminérgicos",clasificacion:"Agonista D1/D2",mecanismoAccion:"Agonista no selectivo D1/D2 que estimula directamente receptores dopaminérgicos postsinápticos en estriado.",indicaciones:["Rescate de episodios off en Parkinson avanzado"],contraindicaciones:["Depresión respiratoria","Demencia","Uso con ondansetrón"],efectosAdversos:["Náuseas intensas","Hipotensión ortostática severa","Somnolencia","Nódulos en sitio inyección","Discinesias","Prolongación QT"],interacciones:["Ondansetrón/granisetrón (contraindicados)","Antihipertensivos (hipotensión)","Domperidona (se usa para prevenir náuseas)"],viaAdministracion:["SC"],dosis:{adulto:"Test: 1 mg SC; terapéutico: 2-6 mg/episodio; máx 5 dosis/día"},presentaciones:["Pluma 10 mg/mL","Ampolla 10 mg/mL para bomba"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Premedicar con domperidona 3 días antes","Enseñar autoadministración SC","Rotar sitios inyección","Monitorizar TA bipedestación","NUNCA administrar IV"],farmacocinetica:{absorcion:"SC rápida",distribucion:"UP 99.9%",metabolismo:"Hepático sulfatación/glucuronidación",excrecion:"Renal 93%",vidaMedia:"30-60 min",inicioAccion:"5-15 min SC",picoAccion:"10-60 min",duracionAccion:"60-90 min"},almacenamiento:"Refrigerar 2-8°C. Abierto: 48h.",unidadId:"u01",capituloId:"c01_05"},

  {id:"safinamida",nombre:"Safinamida",nombreGenerico:"safinamida",nombresComerciales:["Xadago"],familia:"Inhibidores MAO-B",clasificacion:"IMAO-B reversible con acción antiglutamatérgica",mecanismoAccion:"Inhibe MAO-B reversiblemente. Además bloquea canales de sodio y modula liberación de glutamato.",indicaciones:["Parkinson con fluctuaciones motoras (adyuvante a levodopa)"],contraindicaciones:["Otros IMAO","Meperidina","IH severa"],efectosAdversos:["Discinesias","Insomnio","Hipotensión ortostática","Náuseas","Cataratas"],interacciones:["IMAO (contraindicado)","Meperidina (serotoninérgico)","Dextrometorfano (evitar)"],viaAdministracion:["oral"],dosis:{adulto:"50 mg/día, puede subir a 100 mg/día tras 2 semanas",ajusteHepatico:"IH moderada: máx 50 mg; IH severa: contraindicado"},presentaciones:["Comprimidos 50, 100 mg"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Administrar siempre a la misma hora","No requiere restricción tiramina (selectivo MAO-B)","Vigilar discinesias","Monitorizar PA"],farmacocinetica:{absorcion:"BD 95%",distribucion:"Vd 165 L, UP 88%",metabolismo:"Hepático amidasa, CYP3A4",excrecion:"Renal 76%",vidaMedia:"20-26 horas",inicioAccion:"Horas",picoAccion:"1.8-2.8 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_05"},

  {id:"lurasidona",nombre:"Lurasidona",nombreGenerico:"lurasidona",nombresComerciales:["Latuda"],familia:"Antipsicóticos atípicos",clasificacion:"Antipsicótico atípico benzisotiazol",mecanismoAccion:"Antagonista D2, 5-HT2A, 5-HT7. Agonista parcial 5-HT1A. Baja afinidad H1/muscarínico (menor sedación/peso).",indicaciones:["Esquizofrenia","Depresión bipolar","Trastorno esquizoafectivo"],contraindicaciones:["Inhibidores potentes CYP3A4 (ketoconazol)","Inductores potentes CYP3A4 (rifampicina)"],efectosAdversos:["Acatisia","Somnolencia","Náuseas","Parkinsonismo","Aumento peso moderado"],interacciones:["Ketoconazol, claritromicina (contraindicados)","Rifampicina (contraindicada)","Diltiazem (reducir dosis)","Pomelo (evitar)"],viaAdministracion:["oral"],dosis:{adulto:"Esquizofrenia: 40-160 mg/día; Bipolar: 20-120 mg/día",pediatrico:"≥13 años: 40-80 mg/día",ajusteRenal:"ClCr <50: máx 80 mg/día",ajusteHepatico:"IH severa: máx 40 mg"},presentaciones:["Comprimidos 20, 40, 60, 80, 120 mg"],embarazo:"C",lactancia:"Evaluar riesgo-beneficio",cuidadosEnfermeria:["DEBE tomarse con alimentos (≥350 kcal)","Monitorizar signos extrapiramidales","Controlar glucemia y lípidos","Bajo riesgo metabólico vs otros atípicos"],farmacocinetica:{absorcion:"Con alimentos BD 9-19%",distribucion:"Vd 6173 L, UP 99.8%",metabolismo:"Hepático CYP3A4",excrecion:"Fecal 80%, renal 9%",vidaMedia:"18 horas",inicioAccion:"1-2 semanas efecto completo",picoAccion:"1-3 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_06"},

  {id:"asenapina",nombre:"Asenapina",nombreGenerico:"asenapina",nombresComerciales:["Saphris","Sycrest"],familia:"Antipsicóticos atípicos",clasificacion:"Antipsicótico atípico sublingual",mecanismoAccion:"Antagonista D2, 5-HT2A, 5-HT2C, alfa-1/2, H1. Perfil farmacológico amplio.",indicaciones:["Esquizofrenia","Manía aguda en bipolar I","Mantenimiento bipolar"],contraindicaciones:["Demencia con psicosis en ancianos","No tragar (solo sublingual)"],efectosAdversos:["Somnolencia","Hipoestesia oral","Aumento peso","Acatisia","Hipotensión ortostática","Prolongación QT"],interacciones:["Fluvoxamina (inhibe CYP1A2)","Antihipertensivos (hipotensión)","No comer ni beber 10 min post sublingual"],viaAdministracion:["sublingual"],dosis:{adulto:"5-10 mg sublingual/12h"},presentaciones:["Comprimidos sublinguales 5, 10 mg"],embarazo:"C",lactancia:"Evaluar riesgo-beneficio",cuidadosEnfermeria:["Administración SUBLINGUAL obligatoria","No comer/beber 10 min después","Dejar disolver completamente bajo la lengua","Hipoestesia oral es normal","Monitorizar TA al inicio"],farmacocinetica:{absorcion:"Sublingual BD 35% (tragado: <2%)",distribucion:"UP 95%",metabolismo:"Hepático CYP1A2, UGT1A4",excrecion:"Renal 50%, fecal 40%",vidaMedia:"24 horas",inicioAccion:"Días",picoAccion:"0.5-1.5 horas",duracionAccion:"12 horas"},almacenamiento:"Temperatura ambiente, proteger humedad",unidadId:"u01",capituloId:"c01_06"},

  {id:"pimozida",nombre:"Pimozida",nombreGenerico:"pimozida",nombresComerciales:["Orap"],familia:"Antipsicóticos típicos",clasificacion:"Antipsicótico difenilbutilpiperidina",mecanismoAccion:"Antagonista potente D2. También bloquea canales de calcio. Alta potencia antipsicótica.",indicaciones:["Síndrome de Tourette","Tics motores severos","Esquizofrenia crónica refractaria"],contraindicaciones:["QT prolongado","Inhibidores CYP3A4/2D6","Síndrome QT largo congénito","Hipocalemia"],efectosAdversos:["Prolongación QT significativa","Síntomas extrapiramidales","SNM","Sedación","Galactorrea"],interacciones:["Claritromicina, ketoconazol (contraindicados)","Paroxetina, fluoxetina (contraindicados)","Antiarrítmicos clase IA/III (riesgo QT)"],viaAdministracion:["oral"],dosis:{adulto:"Tourette: 1-10 mg/día; esquizofrenia: 2-20 mg/día",pediatrico:"≥12 años: 0.5 mg/día inicial, máx 10 mg/día"},presentaciones:["Comprimidos 1, 4 mg"],embarazo:"C",lactancia:"Contraindicado",cuidadosEnfermeria:["ECG OBLIGATORIO basal y periódico","Suspender si QTc >500 ms","Monitorizar K+ y Mg2+","Vigilar SEP y SNM","Titular muy lentamente"],farmacocinetica:{absorcion:"BD 40-50%",distribucion:"UP >99%",metabolismo:"Hepático CYP3A4, CYP2D6",excrecion:"Renal 50%, fecal",vidaMedia:"55 horas",inicioAccion:"Días",picoAccion:"6-8 horas",duracionAccion:"24-48 horas"},almacenamiento:"Temperatura ambiente, proteger de la luz",unidadId:"u01",capituloId:"c01_06"},

  {id:"nortriptilina",nombre:"Nortriptilina",nombreGenerico:"nortriptilina",nombresComerciales:["Pamelor","Noritren"],familia:"Antidepresivos tricíclicos",clasificacion:"Tricíclico amina secundaria",mecanismoAccion:"Inhibe recaptación de noradrenalina predominantemente. Menor efecto anticolinérgico que amitriptilina. Metabolito activo de amitriptilina.",indicaciones:["Depresión mayor","Dolor neuropático","Profilaxis cefalea tensional","Enuresis nocturna"],contraindicaciones:["IMAO (14 días)","IAM reciente","Glaucoma ángulo cerrado","Fase maníaca"],efectosAdversos:["Sequedad bucal","Estreñimiento","Hipotensión ortostática","Taquicardia","Sedación leve","Aumento peso"],interacciones:["IMAO (crisis hipertensiva)","ISRS (serotoninérgico)","Antiarrítmicos clase I (toxicidad cardíaca)","Alcohol (depresión SNC)"],viaAdministracion:["oral"],dosis:{adulto:"25 mg/noche, titular a 75-150 mg/día",pediatrico:"Enuresis ≥6 años: 10-25 mg/noche",ajusteHepatico:"Reducir dosis"},presentaciones:["Cápsulas 10, 25, 50, 75 mg"],embarazo:"D",lactancia:"Bajas concentraciones en leche",cuidadosEnfermeria:["Niveles terapéuticos: 50-150 ng/mL","ECG basal en >40 años","Administrar al acostarse","Vigilar ideación suicida primeras semanas","No suspender bruscamente"],farmacocinetica:{absorcion:"Oral bien absorbida",distribucion:"UP 93-95%",metabolismo:"Hepático CYP2D6",excrecion:"Renal",vidaMedia:"18-44 horas",inicioAccion:"2-4 semanas",picoAccion:"7-8.5 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente, proteger de la luz",unidadId:"u01",capituloId:"c01_07"},

  {id:"imipramina",nombre:"Imipramina",nombreGenerico:"imipramina",nombresComerciales:["Tofranil"],familia:"Antidepresivos tricíclicos",clasificacion:"Tricíclico amina terciaria",mecanismoAccion:"Inhibe recaptación de serotonina y noradrenalina. Bloquea receptores muscarínicos, H1 y alfa-1.",indicaciones:["Depresión mayor","Enuresis nocturna infantil","Trastorno de pánico","Dolor neuropático"],contraindicaciones:["IAM reciente","IMAO","Glaucoma ángulo cerrado","Fase maníaca"],efectosAdversos:["Sedación","Sequedad bucal","Estreñimiento","Retención urinaria","Hipotensión ortostática","Taquicardia","Convulsiones (dosis altas)"],interacciones:["IMAO (contraindicado)","Alcohol (depresión SNC)","Simpaticomiméticos (hipertensión)","Inhibidores CYP2D6 (aumentan niveles)"],viaAdministracion:["oral"],dosis:{adulto:"75 mg/día inicial, titular a 150-300 mg/día",pediatrico:"Enuresis ≥6 años: 25 mg/noche"},presentaciones:["Comprimidos 10, 25, 50 mg"],embarazo:"D",lactancia:"No recomendado",cuidadosEnfermeria:["ECG basal","Administrar al acostarse","Monitorizar niveles si disponible","Riesgo convulsiones en sobredosis"],farmacocinetica:{absorcion:"Oral completa",distribucion:"Vd 10-20 L/kg, UP 86-96%",metabolismo:"Hepático CYP2D6 a desipramina",excrecion:"Renal 70%",vidaMedia:"6-18 horas",inicioAccion:"2-4 semanas",picoAccion:"1-2 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_07"},

  {id:"clomipramina",nombre:"Clomipramina",nombreGenerico:"clomipramina",nombresComerciales:["Anafranil"],familia:"Antidepresivos tricíclicos",clasificacion:"Tricíclico serotoninérgico",mecanismoAccion:"El más serotoninérgico de los tricíclicos. Inhibe potentemente recaptación de serotonina y, via su metabolito, noradrenalina.",indicaciones:["TOC (fármaco de elección tricíclico)","Depresión mayor","Trastorno de pánico","Cataplejia"],contraindicaciones:["IAM reciente","IMAO","Glaucoma","Epilepsia no controlada"],efectosAdversos:["Sequedad bucal","Sedación","Temblor","Sudoración","Disfunción sexual","Convulsiones (>250 mg/día)"],interacciones:["IMAO (serotoninérgico severo)","ISRS (sinergia peligrosa)","Tramadol (convulsiones)","Alcohol (depresión SNC)"],viaAdministracion:["oral","IV"],dosis:{adulto:"TOC: 25 mg/día, titular a 100-250 mg/día",pediatrico:"≥10 años TOC: 25 mg/día, hasta 3 mg/kg/día"},presentaciones:["Comprimidos 10, 25, 50, 75 mg","Ampolla 25 mg/2 mL"],embarazo:"D",lactancia:"No recomendado",cuidadosEnfermeria:["Tricíclico de elección para TOC","ECG basal y periódico","Dosis >250 mg: riesgo convulsiones alto","IV: infusión lenta 1-3h"],farmacocinetica:{absorcion:"BD 50%",distribucion:"UP 97-98%",metabolismo:"Hepático CYP2D6 a desmetilclomipramina",excrecion:"Renal 66%, fecal 32%",vidaMedia:"21 horas (metabolito 36h)",inicioAccion:"2-4 sem antidepresivo; 4-12 sem TOC",picoAccion:"2-6 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente, proteger de la luz",unidadId:"u01",capituloId:"c01_07"},

  {id:"moclobemida",nombre:"Moclobemida",nombreGenerico:"moclobemida",nombresComerciales:["Aurorix","Manerix"],familia:"Inhibidores MAO",clasificacion:"IMAO-A reversible (RIMA)",mecanismoAccion:"Inhibidor reversible y selectivo de MAO-A. Aumenta serotonina, noradrenalina y dopamina con menor riesgo de crisis tiramínica.",indicaciones:["Depresión mayor","Fobia social"],contraindicaciones:["Feocromocitoma","Otros IMAO","Tirotoxicosis"],efectosAdversos:["Insomnio","Náuseas","Mareo","Cefalea","Agitación"],interacciones:["ISRS (serotoninérgico - esperar 1 semana)","Meperidina (contraindicado)","Dextrometorfano (evitar)","Cimetidina (aumenta niveles)"],viaAdministracion:["oral"],dosis:{adulto:"300-600 mg/día en 2-3 tomas después de comidas"},presentaciones:["Comprimidos 150, 300 mg"],embarazo:"C",lactancia:"Precaución",cuidadosEnfermeria:["Después de comidas","Restricción tiramina menos estricta que IMAO clásicos","Efecto relativamente rápido","No combinar con ISRS sin lavado"],farmacocinetica:{absorcion:"Rápida, BD 55-95%",distribucion:"UP 50%",metabolismo:"Hepático CYP2C19",excrecion:"Renal 95%",vidaMedia:"1-2 horas (inhibición MAO 24h)",inicioAccion:"1-2 semanas",picoAccion:"1 hora",duracionAccion:"8-12 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_07"},

  {id:"agomelatina",nombre:"Agomelatina",nombreGenerico:"agomelatina",nombresComerciales:["Valdoxan","Thymanax"],familia:"Antidepresivos melatoninérgicos",clasificacion:"Agonista MT1/MT2 y antagonista 5-HT2C",mecanismoAccion:"Agonista melatoninérgico MT1/MT2 (resincroniza ritmos circadianos) y antagonista 5-HT2C (aumenta NA y DA frontal).",indicaciones:["Depresión mayor en adultos"],contraindicaciones:["IH (Child-Pugh B/C)","Transaminasas >3x LSN","Inhibidores potentes CYP1A2","<18 años"],efectosAdversos:["Hepatotoxicidad","Cefalea","Mareo","Náuseas","Somnolencia"],interacciones:["Fluvoxamina (contraindicado)","Ciprofloxacino (contraindicado)","Alcohol (hepatotoxicidad aditiva)"],viaAdministracion:["oral"],dosis:{adulto:"25 mg al acostarse; puede subir a 50 mg"},presentaciones:["Comprimidos 25 mg"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["OBLIGATORIO: transaminasas basales, 3, 6, 12, 24 sem","Suspender si transaminasas >3x LSN","Administrar al acostarse","No produce disfunción sexual ni aumento peso","No síndrome discontinuación"],farmacocinetica:{absorcion:"Rápida, BD 3% (alto primer paso)",distribucion:"UP 95%",metabolismo:"Hepático CYP1A2 (90%)",excrecion:"Renal 80%",vidaMedia:"1-2 horas",inicioAccion:"2 semanas",picoAccion:"1-2 horas",duracionAccion:"24 horas"},almacenamiento:"Proteger de la luz",unidadId:"u01",capituloId:"c01_07"},

  {id:"esketamina_nasal",nombre:"Esketamina Nasal",nombreGenerico:"esketamina",nombresComerciales:["Spravato"],familia:"Antagonistas NMDA",clasificacion:"Antidepresivo antagonista NMDA",mecanismoAccion:"Enantiómero S de ketamina. Antagonista NMDA que produce rápida sinaptogénesis y restauración de conexiones sinápticas prefrontales.",indicaciones:["Depresión resistente al tratamiento","Depresión mayor con ideación suicida aguda"],contraindicaciones:["Enfermedad vascular aneurismática","HTA no controlada (>180/110)","Hemorragia intracerebral"],efectosAdversos:["Disociación","Mareo","Náuseas","Sedación","Aumento transitorio PA","Ansiedad aguda"],interacciones:["Depresores SNC (sedación aditiva)","Psicoestimulantes (aumento PA)","IMAO (precaución)"],viaAdministracion:["nasal"],dosis:{adulto:"56 mg día 1, luego 56-84 mg 2x/sem x4 sem; mantenimiento semanal o quincenal"},presentaciones:["Dispositivo nasal 28 mg (se usan 2-3 por sesión)"],embarazo:"X",lactancia:"Contraindicado",cuidadosEnfermeria:["SOLO en centro certificado (REMS)","Monitorizar PA antes, 40 min y 2h post","Observar ≥2 horas post-dosis","No conducir hasta día siguiente","Asegurar acompañante para regreso"],farmacocinetica:{absorcion:"Nasal BD 48%",distribucion:"UP 43-45%",metabolismo:"Hepático CYP2B6, CYP3A4",excrecion:"Renal 78%",vidaMedia:"7-12 horas",inicioAccion:"Minutos",picoAccion:"20-40 min",duracionAccion:"Días (efecto prolongado)"},almacenamiento:"Temperatura ambiente. Distribución restringida.",unidadId:"u01",capituloId:"c01_07"},

  {id:"lisdexanfetamina",nombre:"Lisdexanfetamina",nombreGenerico:"lisdexanfetamina",nombresComerciales:["Vyvanse","Elvanse"],familia:"Psicoestimulantes",clasificacion:"Profármaco anfetamínico",mecanismoAccion:"Profármaco hidrolizado en eritrocitos a d-anfetamina. Aumenta liberación y bloquea recaptación de NA y DA en corteza prefrontal.",indicaciones:["TDAH en niños ≥6 años y adultos","Trastorno por atracón moderado-severo"],contraindicaciones:["IMAO (14 días)","Cardiopatía estructural","Hipertiroidismo","Glaucoma"],efectosAdversos:["Insomnio","Anorexia","Cefalea","Taquicardia","Ansiedad","Retraso crecimiento (niños)"],interacciones:["IMAO (contraindicado)","Antihipertensivos (antagonismo)","Ácido ascórbico (aumenta excreción)"],viaAdministracion:["oral"],dosis:{adulto:"30 mg/mañana, titular hasta 70 mg/día",pediatrico:"≥6 años: 30 mg/mañana, hasta 70 mg/día",ajusteRenal:"GFR 15-30: máx 50 mg; <15: máx 30 mg"},presentaciones:["Cápsulas 20, 30, 40, 50, 60, 70 mg"],embarazo:"C",lactancia:"No recomendado",cuidadosEnfermeria:["Administrar por la mañana temprano","Monitorizar peso y talla en niños","Controlar PA y FC","Menor potencial abuso que anfetamina directa","Cápsula puede abrirse y mezclar con agua","Sustancia controlada"],farmacocinetica:{absorcion:"Oral completa como profármaco",distribucion:"Conversión en eritrocitos a d-anfetamina",metabolismo:"Hidrólisis enzimática",excrecion:"Renal 96%",vidaMedia:"<1h (pro); 10-12h (d-anfetamina)",inicioAccion:"1-2 horas",picoAccion:"3.5 horas",duracionAccion:"10-14 horas"},almacenamiento:"Temperatura ambiente. Sustancia controlada.",unidadId:"u01",capituloId:"c01_08"},

  {id:"guanfacina",nombre:"Guanfacina",nombreGenerico:"guanfacina",nombresComerciales:["Intuniv","Tenex"],familia:"Agonistas alfa-2",clasificacion:"Agonista selectivo alfa-2A adrenérgico",mecanismoAccion:"Agonista alfa-2A postsináptico en corteza prefrontal. Mejora atención y memoria de trabajo sin ser estimulante.",indicaciones:["TDAH en niños ≥6 años","Tics (Tourette)","HTA (liberación inmediata)"],contraindicaciones:["Bradicardia severa","Hipotensión sintomática"],efectosAdversos:["Somnolencia","Hipotensión","Bradicardia","Cefalea","Fatiga","Dolor abdominal"],interacciones:["Valproato (aumenta niveles)","Inhibidores CYP3A4 (aumentan niveles)","Antihipertensivos (hipotensión)","Depresores SNC (sedación)"],viaAdministracion:["oral"],dosis:{pediatrico:"≥6 años: 1 mg/día, titular hasta 4 mg/día"},presentaciones:["Comprimidos LP 1, 2, 3, 4 mg"],embarazo:"C",lactancia:"Precaución",cuidadosEnfermeria:["No triturar comprimidos LP","Administrar a la misma hora (preferir noche)","No suspender bruscamente (HTA rebote)","Monitorizar PA y FC","Somnolencia mejora tras 2-3 semanas"],farmacocinetica:{absorcion:"BD 80%",distribucion:"UP 70%",metabolismo:"Hepático CYP3A4",excrecion:"Renal 50%, fecal 50%",vidaMedia:"17 horas",inicioAccion:"1-2 semanas efecto terapéutico",picoAccion:"5 horas (LP)",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_08"},

  {id:"pitolisant",nombre:"Pitolisant",nombreGenerico:"pitolisant",nombresComerciales:["Wakix"],familia:"Antagonistas H3",clasificacion:"Antagonista/agonista inverso receptor H3",mecanismoAccion:"Bloquea autoreceptores H3 presinápticos, aumentando histamina cerebral. Modula liberación de acetilcolina, NA y DA.",indicaciones:["Narcolepsia tipo 1 y 2","Cataplejia"],contraindicaciones:["IH severa","Embarazo","Lactancia"],efectosAdversos:["Insomnio","Cefalea","Náuseas","Ansiedad","Depresión","Prolongación QT (raro)"],interacciones:["Inhibidores CYP2D6 (aumentan niveles)","Inductores CYP3A4 (disminuyen niveles)","Anticonceptivos (puede reducir eficacia)"],viaAdministracion:["oral"],dosis:{adulto:"Sem 1: 9 mg/mañana; Sem 2: 18 mg; Sem 3+: 36 mg",ajusteRenal:"ClCr <15: no recomendado",ajusteHepatico:"IH leve-mod: máx 18 mg; severa: contraindicado"},presentaciones:["Comprimidos 4.45, 17.8 mg"],embarazo:"X",lactancia:"Contraindicado",cuidadosEnfermeria:["Administrar por la mañana","No es sustancia controlada","Titular 3 semanas","Vigilar depresión","Informar reducción eficacia anticonceptivos"],farmacocinetica:{absorcion:"Oral buena",distribucion:"Cruza BHE, UP 91-96%",metabolismo:"Hepático CYP2D6, CYP3A4",excrecion:"Renal 63%",vidaMedia:"10-12 horas",inicioAccion:"1-2 horas",picoAccion:"3-4 horas",duracionAccion:"24 horas"},almacenamiento:"Temperatura ambiente",unidadId:"u01",capituloId:"c01_08"}
];

console.log('Drug count BEFORE:', drugs.length);
D.forEach(d => addDrug(d));
fs.writeFileSync(drugsPath, JSON.stringify(drugs, null, 2), 'utf8');
fs.writeFileSync(catsPath, JSON.stringify(cats, null, 2), 'utf8');
console.log('Drug count AFTER:', drugs.length);
console.log('Added:', D.length, 'new CNS drugs');
