const fs = require('fs');
const path = require('path');
const drugs = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'src', 'data', 'drugs.json'), 'utf8'));
const names = drugs.map(d => (d.nombre + ' ' + d.nombreGenerico + ' ' + (d.nombresComerciales||[]).join(' ')).toLowerCase());

const check = [
  'lactato de ringer', 'ringer lactato', 'hartmann',
  'dextrosa', 'glucosa', 'suero glucosado',
  'bicarbonato de sodio', 'bicarbonato sodico',
  'cloruro de potasio',
  'sulfato de magnesio',
  'gluconato de calcio',
  'manitol',
  'agua esteril',
  'poligelina', 'haemaccel',
  'gelatina succinilada', 'gelafundina',
  'hidroxietilalmidon', 'voluven',
  'desmopresina',
  'vasopresina',
  'terlipresina',
  'fenilefrina',
  'efedrina',
  'isoproterenol', 'isoprenalina',
  'milrinona',
  'nitroglicerina',
  'nitroprusiato',
  'labetalol',
  'hidralazina',
  'protamina',
  'acido tranexamico',
  'fitomenadiona', 'vitamina k',
  'complejo protrombinico',
  'factor viii',
  'inmunoglobulina anti-d',
  'oxigeno medicinal',
  'oxido nitroso',
  'desflurano',
  'etomidato',
  'dexmedetomidina',
  'vecuronio',
  'bupivacaina',
  'ropivacaina',
  'levobupivacaina',
  'carbon activado',
  'azul de metileno',
  'glucagon',
  'insulina regular',
  'solucion dianeal', 'dialisis peritoneal',
  'plasma fresco',
  'concentrado de hematies', 'globulos rojos',
  'plaquetas',
  'soluciones de nutricion parenteral',
  'propofol',
  'fentanilo',
  'morfina',
  'remifentanilo',
  'midazolam',
  'diazepam',
  'haloperidol',
  'metoclopramida',
  'ondansetron',
  'ranitidina',
  'omeprazol',
  'pantoprazol',
  'heparina',
  'enoxaparina',
  'alteplasa',
  'tenecteplasa',
  'noradrenalina', 'norepinefrina',
  'adrenalina', 'epinefrina',
  'dopamina',
  'dobutamina',
  'atropina',
  'amiodarona',
  'adenosina',
  'lidocaina',
  'magnesio',
  'calcio',
  'potasio',
  'fosfato',
  'zinc',
  'selenio',
  'hierro sacarosa', 'hierro iv',
  'eritropoyetina',
  'filgrastim',
  'octreotida',
  'somatostatina',
  'dantroleno',
  'lipidos', 'intralipid',
  'aminoacidos',
  'tiamina', 'vitamina b1',
  'acido folico',
  'cianocobalamina', 'vitamina b12',
  'acido ascorbico', 'vitamina c',
  'calcitriol',
  'colecalciferol', 'vitamina d',
];

const found = new Set();
check.forEach(term => {
  const match = names.some(n => n.includes(term.toLowerCase()));
  if (!match && !found.has(term)) {
    console.log('FALTA:', term);
    found.add(term);
  }
});