#!/usr/bin/env python3
"""Add new drugs for U06 Sistema Endocrino."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ══════════════════════════════════════════════════════════════
# c06_01 Insulinas y Antidiabéticos (+15)
# ══════════════════════════════════════════════════════════════
M("insulina","insulina_glulisina","Insulina Glulisina","Insulina glulisina",["Apidra"],
  "Insulina ultrarrápida","Análogo de insulina de acción ultrarrápida. Sustituciones en B3 (lisina→asparagina) y B29 (lisina→ácido glutámico) reducen autoasociación",
  ["Diabetes mellitus tipo 1","Diabetes mellitus tipo 2 (en combinación)","Control glucémico prandial"],["SC","IV"],
  {"adulto":"0.05-0.3 UI/kg/dosis SC 0-15 min antes de comida. Ajustar según glucemia","pediatrico":"≥4 años: misma dosificación que adultos"},
  ["Vial 10 mL (100 UI/mL)","Cartucho 3 mL","Pluma precargada SoloStar 3 mL"],
  "Compatible con precaución","u06","c06_01",
  alm="Refrigerar sin abrir (2-8°C). En uso: TA máx 25°C hasta 28 días",
  pp={"dilucion":"IV: diluir en SF a 0.05-1 UI/mL","velocidadAdministracion":"Infusión IV continua según protocolo","estabilidad":"48h en SF a TA"}),

M("insulina","insulina_detemir_detalle","Insulina Detemir (detalle clínico)","Insulina detemir",["Levemir"],
  "Insulina basal de acción prolongada","Análogo acilado de insulina. Cadena lateral de ácido mirístico en B29 permite unión a albúmina, prolongando duración a 18-24h",
  ["DM tipo 1 (basal)","DM tipo 2 (basal)","Diabetes gestacional (off-label)"],["SC"],
  {"adulto":"DM2: 10 UI/día o 0.1-0.2 UI/kg/día SC, titular c/3 días. DM1: 50% de dosis total como basal","pediatrico":"≥2 años: 0.2-0.4 UI/kg/día"},
  ["Pluma FlexPen 3 mL (100 UI/mL)","Vial 10 mL (100 UI/mL)"],
  "Compatible con precaución","u06","c06_01",
  alm="Refrigerar (2-8°C). En uso: TA hasta 42 días",
  fk={"absorcion":"SC lenta por unión a albúmina","distribucion":"Unión a albúmina >98%","metabolismo":"Degradación como insulina endógena","vidaMedia":"18-24h","eliminacion":"Renal"}),

M("insulina","insulina_degludec_liraglutida","Insulina Degludec/Liraglutida","Insulina degludec + Liraglutida",["Xultophy"],
  "Combinación fija insulina basal + agonista GLP-1","Combinación de insulina degludec (acción ultralarga) y liraglutida (agonista GLP-1). Efecto complementario: control basal + reducción prandial sin aumento de peso",
  ["DM tipo 2 no controlada con insulina basal o agonista GLP-1 solos"],["SC"],
  {"adulto":"Inicio 16 dosis-pasos (16 UI degludec/0.58 mg liraglutida). Titular 2 pasos c/3-4 días. Máx 50 pasos/día"},
  ["Pluma precargada 3 mL (100 UI degludec + 3.6 mg liraglutida/mL)"],
  "No recomendado","u06","c06_01",
  alm="Refrigerar (2-8°C). En uso: TA máx 21 días",
  ce=["Enseñar sistema de dosis-pasos (1 paso = 1 UI degludec + 0.036 mg liraglutida)","Administrar a la misma hora cada día","Rotar sitios de inyección","Monitorizar glucemia basal para titulación"]),

M("antidiabetico_oral","semaglutida_oral","Semaglutida Oral","Semaglutida oral",["Rybelsus"],
  "Agonista GLP-1 oral","Primer agonista de receptor GLP-1 oral. Coformulado con SNAC (salcaprozato de sodio) que facilita absorción gástrica",
  ["DM tipo 2 (en monoterapia o combinación)"],["oral"],
  {"adulto":"Inicio 3 mg/día x 30 días, luego 7 mg/día. Puede aumentar a 14 mg/día tras 30 días más"},
  ["Comp 3, 7, 14 mg"],
  "No recomendado","u06","c06_01",
  emb="X",
  ea=["Náuseas","Diarrea","Dolor abdominal","Disminución del apetito","Vómitos","Estreñimiento","Pancreatitis (raro)"],
  ci=["Hipersensibilidad a semaglutida","Antecedente personal/familiar de carcinoma medular de tiroides","Neoplasia endocrina múltiple tipo 2"],
  ce=["Tomar en AYUNAS con ≤120 mL de agua","Esperar ≥30 min antes de comer, beber o tomar otros medicamentos","No triturar ni masticar","Monitorizar glucemia y HbA1c"]),

M("antidiabetico_oral","exenatida","Exenatida","Exenatida",["Byetta"],
  "Agonista GLP-1 de acción corta","Análogo sintético de exendina-4 (péptido del monstruo de Gila). Agonista GLP-1 con acción prandial predominante",
  ["DM tipo 2 (en combinación con metformina, sulfonilureas o ambas)"],["SC"],
  {"adulto":"5 mcg SC c/12h x 1 mes, luego 10 mcg SC c/12h. Inyectar 60 min antes de comidas"},
  ["Pluma precargada 5 mcg/dosis (1.2 mL)","Pluma precargada 10 mcg/dosis (2.4 mL)"],
  "No recomendado","u06","c06_01",
  familia="Agonistas GLP-1",
  ci=["Hipersensibilidad","Antecedente de pancreatitis","Carcinoma medular de tiroides","NEM tipo 2"],
  ea=["Náuseas (muy frecuente al inicio)","Vómitos","Diarrea","Hipoglucemia (con sulfonilureas)","Pancreatitis (raro)","Reacción en sitio de inyección"],
  ix=["Sulfonilureas: mayor riesgo hipoglucemia","Anticoagulantes orales: puede alterar absorción","Antibióticos orales: retrasa absorción"],
  ce=["Inyectar 60 min antes del desayuno y cena","Náuseas suelen disminuir con el tiempo","No usar post-prandial","Monitorizar glucemia y función pancreática"],
  alm="Refrigerar (2-8°C). En uso: TA máx 30 días"),

M("antidiabetico_oral","exenatida_semanal","Exenatida semanal","Exenatida de liberación prolongada",["Bydureon","Bydureon BCise"],
  "Agonista GLP-1 de acción prolongada semanal","Exenatida encapsulada en microesferas de polímero biodegradable (PLG) que permiten liberación sostenida durante 7 días",
  ["DM tipo 2"],["SC"],
  {"adulto":"2 mg SC una vez por semana, el mismo día cada semana"},
  ["Pluma precargada 2 mg","Kit de suspensión 2 mg"],
  "No recomendado","u06","c06_01",
  familia="Agonistas GLP-1",
  ci=["Hipersensibilidad a exenatida","Carcinoma medular de tiroides","NEM tipo 2","Antecedente de pancreatitis"],
  ea=["Nódulo subcutáneo en sitio de inyección","Náuseas","Diarrea","Cefalea","Reacción en sitio de inyección"],
  ce=["Reconstituir justo antes de inyectar","Pueden aparecer nódulos SC (normales, se reabsorben)","No requiere ajuste con comidas","Monitorizar HbA1c c/3 meses"],
  alm="Refrigerar (2-8°C). Puede estar a TA máx 4 semanas"),

M("antidiabetico_oral","pramlintida","Pramlintida","Pramlintida",["Symlin"],
  "Análogo de amilina","Análogo sintético de amilina humana. Retrasa vaciamiento gástrico, suprime glucagón postprandial y promueve saciedad",
  ["DM tipo 1 (complemento a insulina)","DM tipo 2 (complemento a insulina)"],["SC"],
  {"adulto":"DM2: inicio 60 mcg SC antes de comidas, titular a 120 mcg. DM1: inicio 15 mcg, titular hasta 60 mcg"},
  ["Pluma precargada 1000 mcg/mL","Vial 600 mcg/mL"],
  "No recomendado","u06","c06_01",
  familia="Análogos de amilina",
  ci=["Hipoglucemia severa recurrente","Gastroparesia","Hipersensibilidad"],
  ea=["Náuseas (muy frecuente)","Hipoglucemia (con insulina)","Anorexia","Vómitos","Cefalea"],
  ix=["Insulina: reducir dosis de insulina 50% al iniciar pramlintida","Fármacos que retrasan absorción: no combinar"],
  ce=["Reducir dosis de insulina prandial 50% al iniciar","Inyectar inmediatamente antes de comidas","Nunca mezclar en misma jeringa que insulina","Vigilar hipoglucemia especialmente al inicio"],
  alm="Refrigerar (2-8°C). En uso: TA máx 30 días"),

M("antidiabetico_oral","miglitol","Miglitol","Miglitol",["Glyset"],
  "Inhibidor de alfa-glucosidasas","Inhibe alfa-glucosidasas intestinales (sacarasa, maltasa, glucoamilasa). Retrasa digestión y absorción de carbohidratos complejos",
  ["DM tipo 2 (control glucémico posprandial)"],["oral"],
  {"adulto":"Inicio 25 mg c/8h con primer bocado. Titular a 50-100 mg c/8h según tolerancia"},
  ["Comp 25, 50, 100 mg"],
  "Compatible con precaución","u06","c06_01",
  ea=["Flatulencia","Diarrea","Dolor abdominal","Distensión abdominal"],
  ci=["Enfermedad inflamatoria intestinal","Obstrucción intestinal","Cetoacidosis diabética","Cirrosis"],
  ce=["Tomar con el PRIMER bocado de cada comida principal","Si hipoglucemia: usar glucosa pura (no sacarosa, no se absorbe bien)","Los efectos GI mejoran con uso continuado","No afecta peso significativamente"]),

M("antidiabetico_oral","tolbutamida","Tolbutamida","Tolbutamida",["Rastinon"],
  "Sulfonilurea de primera generación","Primera generación de sulfonilureas. Estimula secreción de insulina por células beta pancreáticas cerrando canales K-ATP",
  ["DM tipo 2 (en desuso, opciones más seguras disponibles)"],["oral"],
  {"adulto":"500-1000 mg c/12h. Máx 3 g/día","geriatrico":"Iniciar con dosis menores por riesgo de hipoglucemia"},
  ["Comp 500 mg"],
  "Evitar durante lactancia","u06","c06_01",
  ea=["Hipoglucemia","Aumento de peso","Náuseas","Reacciones cutáneas","Ictericia colestásica (raro)"],
  ci=["DM tipo 1","Cetoacidosis diabética","Insuficiencia hepática o renal grave","Hipersensibilidad a sulfonamidas"],
  ix=["Alcohol: efecto disulfiram-like","AINEs: desplazamiento de unión a proteínas","Azoles: inhiben metabolismo","Betabloqueantes: enmascaran hipoglucemia"],
  ce=["En desuso por hipoglucemia prolongada","Acción corta (ventaja relativa en ancianos)","Monitorizar glucemia frecuentemente","Educar sobre signos de hipoglucemia"]),

M("antidiabetico_oral","clorpropamida","Clorpropamida","Clorpropamida",["Diabinese"],
  "Sulfonilurea de primera generación de acción larga","Sulfonilurea con vida media muy prolongada (36h). Alto riesgo de hipoglucemia sostenida. En desuso",
  ["DM tipo 2 (en desuso)","Diabetes insípida central parcial (off-label)"],["oral"],
  {"adulto":"125-500 mg/día en dosis única con desayuno. Máx 750 mg/día"},
  ["Comp 100, 250 mg"],
  "Contraindicado","u06","c06_01",
  ea=["Hipoglucemia prolongada y severa","Hiponatremia (SIADH-like)","Efecto disulfiram con alcohol","Aumento de peso","Ictericia colestásica"],
  ci=["DM tipo 1","Cetoacidosis","Insuficiencia renal","Insuficiencia hepática","Ancianos","Embarazo"],
  ce=["En DESUSO por hipoglucemia severa y prolongada","Vida media 36h: hipoglucemia puede durar días","Efecto antidiurético: uso excepcional en diabetes insípida","No usar en ancianos ni insuficiencia renal"]),

M("antidiabetico_oral","rosiglitazona","Rosiglitazona","Rosiglitazona",["Avandia"],
  "Tiazolidinediona (glitazona)","Agonista PPARγ. Aumenta sensibilidad a insulina en tejido adiposo, músculo e hígado. Controversia cardiovascular histórica",
  ["DM tipo 2 (uso restringido en muchos países)"],["oral"],
  {"adulto":"4-8 mg/día en 1-2 tomas"},
  ["Comp 2, 4, 8 mg"],
  "Contraindicado","u06","c06_01",
  ea=["Edema","Aumento de peso","Insuficiencia cardíaca","Fracturas óseas (mujeres)","Anemia","Mayor riesgo cardiovascular (controvertido)"],
  ci=["Insuficiencia cardíaca clase III-IV NYHA","Enfermedad hepática activa","Embarazo"],
  ix=["Insulina: mayor riesgo de edema e IC","Gemfibrozilo: aumenta niveles de rosiglitazona","Rifampicina: reduce niveles"],
  ce=["Uso restringido por preocupación cardiovascular","Monitorizar función hepática","Vigilar edema y signos de IC","No combinar con insulina si posible"]),

M("antidiabetico_oral","alogliptina","Alogliptina","Alogliptina",["Nesina","Vipidia"],
  "Inhibidor DPP-4","Inhibidor selectivo de dipeptidil peptidasa-4. Aumenta niveles de incretinas activas (GLP-1 y GIP), potenciando secreción de insulina glucosa-dependiente",
  ["DM tipo 2 (en monoterapia o combinación)"],["oral"],
  {"adulto":"25 mg/día en dosis única","ajusteRenal":"ClCr 30-59: 12.5 mg/día. ClCr <30: 6.25 mg/día"},
  ["Comp 6.25, 12.5, 25 mg"],
  "No recomendado","u06","c06_01",
  ea=["Cefalea","Infección respiratoria alta","Nasofaringitis","Pancreatitis (raro)","Artralgias severas (raro)"],
  ci=["Hipersensibilidad","Antecedente de pancreatitis","Cetoacidosis diabética"],
  ce=["Puede tomarse con o sin alimentos","Bajo riesgo de hipoglucemia en monoterapia","Ajustar dosis en insuficiencia renal","Vigilar signos de pancreatitis"]),

M("antidiabetico_oral","sotagliflozina_endo","Sotagliflozina","Sotagliflozina",["Zynquista"],
  "Inhibidor dual SGLT1/SGLT2","Primer inhibidor dual de SGLT1 (intestinal) y SGLT2 (renal). Reduce absorción intestinal de glucosa y glucosuria renal",
  ["DM tipo 1 (aprobado en Europa, como complemento a insulina)","DM tipo 2","Insuficiencia cardíaca"],["oral"],
  {"adulto":"200 mg/día antes del desayuno. Puede aumentar a 400 mg/día"},
  ["Comp 200, 400 mg"],
  "No recomendado","u06","c06_01",
  ea=["Cetoacidosis diabética (riesgo aumentado en DM1)","Diarrea","Infección genital","ITU","Hipoglucemia (con insulina)","Deshidratación"],
  ci=["Hipersensibilidad","Cetoacidosis diabética","Dieta muy baja en carbohidratos"],
  ix=["Insulina: reducir dosis 20% al iniciar","Diuréticos: mayor riesgo de deshidratación"],
  ce=["⚠️ Riesgo de cetoacidosis euglucémica (glucosa normal con cetonas elevadas)","Educar al paciente sobre medición de cetonas","Suspender en enfermedad aguda, cirugía o ayuno","Tomar antes del desayuno"]),

M("antidiabetico_oral","teplizumab","Teplizumab","Teplizumab",["Tzield"],
  "Anticuerpo anti-CD3","Anticuerpo monoclonal anti-CD3 humanizado. Primer fármaco que retrasa la progresión de DM tipo 1 en estadio preclínico",
  ["Retraso del inicio de DM tipo 1 en estadio 2 (preclínico, con autoanticuerpos positivos)"],["IV"],
  {"adulto":"Ciclo de 14 días IV: dosis escalonada desde 65 mcg/m² (día 1) hasta 1030 mcg/m² (días 5-14)","pediatrico":"≥8 años: misma dosificación"},
  ["Vial 2 mg"],
  "No recomendado","u06","c06_01",
  familia="Inmunomoduladores para diabetes",
  ci=["Hipersensibilidad","Infección activa","Inmunodeficiencia"],
  ea=["Linfopenia","Rash","Cefalea","Leucopenia","Síndrome de liberación de citoquinas","Reactivación viral (raro)"],
  ix=["Vacunas vivas: contraindicadas durante y semanas después del tratamiento","Inmunosupresores: mayor riesgo de infección"],
  ce=["Primer fármaco que retrasa aparición de DM1 clínica","Solo para estadio 2 preclínico (autoanticuerpos + disglucemia)","Monitorizar hemograma durante los 14 días","Premedicación con antipiréticos y antihistamínicos"],
  pp={"reconstitucion":"No reconstituir, solución lista","dilucion":"Diluir en 100 mL SF con albúmina 0.01%","velocidadAdministracion":"Infundir en 30 min","estabilidad":"24h refrigerado diluido"}),

M("antidiabetico_oral","diazoxido_hipoglucemia","Diazóxido","Diazóxido oral",["Proglycem"],
  "Activador de canales K-ATP","Abre canales de potasio ATP-dependientes en células beta, inhibiendo secreción de insulina. Efecto hiperglucemiante",
  ["Hiperinsulinismo congénito","Insulinoma inoperable","Hipoglucemia por sulfonilureas refractaria"],["oral"],
  {"adulto":"3-8 mg/kg/día dividido c/8-12h","pediatrico":"Neonatos/lactantes: 8-15 mg/kg/día dividido c/8-12h"},
  ["Cáps 25, 100 mg","Suspensión 50 mg/mL"],
  "No recomendado","u06","c06_01",
  familia="Fármacos para hiperinsulinismo",
  ci=["Hipersensibilidad a tiazidas","Insuficiencia cardíaca","Feocromocitoma"],
  ea=["Retención hídrica","Hipertricosis","Náuseas","Hiperuricemia","Hiperglucemia excesiva","Trombocitopenia","Edema"],
  ix=["Tiazidas: potencian hiperglucemia","Fenitoína: reduce efecto de diazóxido","Antihipertensivos: hipotensión aditiva"],
  ce=["Monitorizar glucemia frecuentemente al inicio","Vigilar retención hídrica (puede requerir diurético)","Hipertricosis frecuente en niños (reversible)","Monitorizar ácido úrico y hemograma"]),

# ══════════════════════════════════════════════════════════════
# c06_02 Hormonas Tiroideas (+5)
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","tiroglobulina","Tiroglobulina (extracto tiroideo)","Tiroglobulina",["Proloid"],
  "Extracto tiroideo natural","Extracto purificado de tiroides porcina que contiene T4 y T3 en proporción fisiológica. En desuso por variabilidad",
  ["Hipotiroidismo (uso histórico, reemplazado por levotiroxina sintética)"],["oral"],
  {"adulto":"30-120 mg/día. Titular según TSH. Equivalencia: 60 mg ≈ 100 mcg levotiroxina"},
  ["Comp 30, 60, 120 mg"],
  "Compatible con precaución","u06","c06_02",
  familia="Hormonas tiroideas naturales",
  ci=["Tirotoxicosis no tratada","IAM reciente","Insuficiencia adrenal no corregida"],
  ea=["Hipertiroidismo iatrogénico","Taquicardia","Arritmias","Temblor","Pérdida de peso","Insomnio","Angina"],
  ix=["Anticoagulantes orales: aumenta efecto","Insulina/antidiabéticos: puede requerir ajuste","Colestiramina: reduce absorción","Hierro/calcio: reduce absorción"],
  ce=["En desuso: levotiroxina sintética es preferida","Variabilidad entre lotes (desventaja)","Contiene T3: puede causar picos","Monitorizar TSH c/6-8 semanas al titular"]),

M("corticoide_sistemico","yodo_131","Yodo-131 (I-131)","Yodo radiactivo I-131",["Theracap I-131"],
  "Radioisótopo terapéutico","Isótopo radiactivo de yodo. Captado selectivamente por tiroides donde emite radiación beta que destruye tejido tiroideo",
  ["Hipertiroidismo (Graves, bocio multinodular tóxico)","Cáncer diferenciado de tiroides (post-tiroidectomía)","Ablación de remanente tiroideo"],["oral"],
  {"adulto":"Hipertiroidismo: 5-15 mCi dosis única. Cáncer: 30-200 mCi según estadio"},
  ["Cápsula o solución oral con actividad variable en mCi"],
  "Contraindicado","u06","c06_02",
  familia="Radiofármacos tiroideos",emb="X",
  ci=["Embarazo","Lactancia","Incapacidad de cumplir medidas de radioprotección","Hipertiroidismo severo no pretratado"],
  ea=["Hipotiroidismo (esperado y frecuente)","Tiroiditis por radiación","Sialoadenitis","Náuseas","Alteración del gusto","Sequedad ocular"],
  ix=["Metimazol/PTU: suspender 3-7 días antes","Amiodarona: interfiere con captación","Medios de contraste yodados: esperar 2-3 meses"],
  ce=["⚠️ Aislamiento del paciente según dosis (radioprotección)","Suspender antitiroideos antes del tratamiento","Hidratación abundante post-tratamiento","Embarazo contraindicado mín 6-12 meses post-tratamiento","Monitorizar TSH: hipotiroidismo es resultado esperado"]),

M("corticoide_sistemico","perclorato_potasio","Perclorato de Potasio","Perclorato potásico",["Irenat"],
  "Inhibidor competitivo del simportador Na/I","Inhibe captación de yodo por tiroides compitiendo con el transportador sodio-yoduro (NIS). Bloquea acumulación de yodo en tiroides",
  ["Hipertiroidismo inducido por amiodarona tipo 1","Bloqueo tiroideo previo a contraste yodado","Hipertiroidismo refractario (adyuvante)"],["oral"],
  {"adulto":"200-1000 mg/día dividido c/6-8h. Duración limitada (semanas)"},
  ["Gotas orales 300 mg/mL","Comp 200 mg"],
  "No recomendado","u06","c06_02",
  familia="Antitiroideos",
  ci=["Anemia aplásica","Agranulocitosis previa por perclorato","Insuficiencia renal severa"],
  ea=["Anemia aplásica (raro pero grave)","Agranulocitosis","Exantema cutáneo","Molestias GI","Nefrotoxicidad"],
  ce=["Uso limitado en tiempo por toxicidad hematológica","Hemograma semanal durante tratamiento","Especialmente útil en hipertiroidismo por amiodarona","No usar como monoterapia prolongada"]),

M("corticoide_sistemico","selenio_tiroide","Selenio (suplemento tiroideo)","Selenio",["Selenium ACE","Selenio"],
  "Oligoelemento esencial para función tiroidea","Cofactor esencial de deiodinasas (conversión T4→T3) y glutatión peroxidasa tiroidea. Papel protector contra estrés oxidativo tiroideo",
  ["Tiroiditis de Hashimoto (reducción de anticuerpos)","Oftalmopatía de Graves leve","Deficiencia de selenio con enfermedad tiroidea"],["oral"],
  {"adulto":"100-200 mcg/día. Oftalmopatía de Graves: 200 mcg/día x 6 meses"},
  ["Comp 100, 200 mcg","Cáps 50, 100 mcg"],
  "Compatible con precaución","u06","c06_02",
  familia="Suplementos tiroideos",emb="A",
  ci=["Hipersensibilidad","Selenosis (toxicidad por selenio)"],
  ea=["Náuseas","Diarrea","Sabor metálico","Selenosis en sobredosis (alopecia, fragilidad ungueal, neuropatía)"],
  ix=["Vitamina C: puede mejorar absorción","Estatinas: selenio no interfiere"],
  ce=["Evidencia limitada pero creciente en autoinmunidad tiroidea","Dosis >400 mcg/día: riesgo de toxicidad","Monitorizar niveles de selenio si tratamiento prolongado","Especialmente útil en áreas con deficiencia endémica de selenio"]),

M("corticoide_sistemico","colestiramina_tiroide","Colestiramina (uso tiroideo)","Colestiramina",["Questran"],
  "Resina secuestrante de ácidos biliares","Resina de intercambio aniónico que une hormonas tiroideas en intestino, interrumpiendo circulación enterohepática de T4/T3",
  ["Tirotoxicosis severa (adyuvante para descenso rápido de T4)","Hipertiroidismo refractario","Tormenta tiroidea (complemento)"],["oral"],
  {"adulto":"4 g c/6-8h (12-16 g/día) como adyuvante antitirodeo"},
  ["Polvo para suspensión 4 g/sobre"],
  "Compatible con precaución","u06","c06_02",
  familia="Resinas secuestrantes (uso tiroideo)",
  ci=["Obstrucción biliar completa","Hipertrigliceridemia severa (tipo I)"],
  ea=["Estreñimiento","Náuseas","Distensión abdominal","Flatulencia","Malabsorción de vitaminas liposolubles"],
  ix=["⚠️ Reduce absorción de MÚLTIPLES fármacos: separar 1h antes o 4h después","Levotiroxina: reduce absorción significativamente","Warfarina: reduce absorción","Digoxina: reduce absorción"],
  ce=["Separar de TODOS los demás fármacos (1h antes o 4-6h después)","Uso temporal como adyuvante en tirotoxicosis severa","Disolver polvo en agua/jugo antes de tomar","Suplementar vitaminas ADEK si uso prolongado"]),

# ══════════════════════════════════════════════════════════════
# c06_03 Corticosteroides (+5)
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","budesonida_sistemica","Budesonida sistémica oral","Budesonida oral",["Entocort","Budenofalk"],
  "Corticosteroide oral con alto metabolismo de primer paso","Glucocorticoide con alta potencia tópica y 90% de metabolismo de primer paso hepático. Menor supresión adrenal sistémica",
  ["Enfermedad de Crohn ileal/ileocecal","Colitis microscópica","Hepatitis autoinmune (alternativa)","Colitis ulcerosa leve-moderada"],["oral"],
  {"adulto":"Crohn: 9 mg/día x 8 semanas, luego reducir 3 mg c/2 semanas. Colitis: 9 mg/día"},
  ["Cáps 3 mg liberación ileal","Comp recubierto 9 mg","Granulado 3, 9 mg"],
  "Compatible con precaución","u06","c06_03",
  ea=["Menores que prednisona sistémica: cefalea, náuseas, síndrome cushingoide (menos frecuente)","Acné","Infecciones oportunistas","Osteoporosis (menor riesgo)"],
  ce=["Menor supresión adrenal que prednisona convencional","No triturar cápsulas de liberación ileal","Reducción gradual obligatoria","Monitorizar glucemia aunque menor efecto sistémico"]),

M("corticoide_sistemico","triamcinolona_sistemica","Triamcinolona sistémica","Triamcinolona acetonida",["Kenalog","Trigon Depot"],
  "Glucocorticoide de acción intermedia-larga (depot)","Glucocorticoide fluorado de potencia intermedia. Formulación depot IM permite efecto prolongado 2-6 semanas",
  ["Dermatitis severa","Artritis inflamatoria","Asma severa (rescate IM)","Rinitis alérgica severa (depot)"],["IM","intraarticular"],
  {"adulto":"IM depot: 40-80 mg cada 4-6 semanas. Intraarticular: 2.5-40 mg según articulación"},
  ["Vial 40 mg/mL (1, 5, 10 mL)","Vial 10 mg/mL"],
  "Evitar durante lactancia","u06","c06_03",
  ea=["Atrofia cutánea en sitio de inyección","Hipopigmentación local","Hiperglucemia","Supresión adrenal","Osteoporosis","Miopatía"],
  ce=["No inyectar IV (formulación depot)","Rotar sitios de inyección IM","Máx 3-4 inyecciones intraarticulares/año por articulación","Puede causar efecto flare articular transitorio 24-48h"]),

M("corticoide_sistemico","parametasona","Parametasona","Parametasona",["Haldrone"],
  "Glucocorticoide de acción prolongada","Glucocorticoide fluorado de larga duración. Potencia 10x hidrocortisona. Uso clínico limitado",
  ["Enfermedades inflamatorias y autoinmunes","Procesos alérgicos severos"],["oral"],
  {"adulto":"2-24 mg/día según patología, en dosis divididas. Reducir gradualmente"},
  ["Comp 1, 2 mg"],
  "Evitar durante lactancia","u06","c06_03",
  ea=["Síndrome de Cushing iatrogénico","Hiperglucemia","Osteoporosis","HTA","Miopatía","Cataratas","Susceptibilidad a infecciones"],
  ce=["Potencia similar a dexametasona","Uso clínico limitado (alternativas más establecidas)","Reducción gradual obligatoria","Suplementar calcio y vitamina D en uso prolongado"]),

M("corticoide_sistemico","rimexolona","Rimexolona","Rimexolona",["Vexol"],
  "Corticosteroide oftálmico","Glucocorticoide con actividad antiinflamatoria ocular potente y baja penetración sistémica",
  ["Inflamación postoperatoria ocular","Uveítis anterior"],["oftalmica"],
  {"adulto":"1-2 gotas c/1-2h la primera semana, luego reducir gradualmente"},
  ["Suspensión oftálmica 1% (5, 10 mL)"],
  "Compatible con precaución","u06","c06_03",
  familia="Corticosteroides oftálmicos",
  ci=["Infección ocular activa (herpes, fúngica, bacteriana)","Glaucoma no controlado"],
  ea=["Elevación de presión intraocular","Cataratas subcapsulares posteriores","Infección secundaria","Retraso en cicatrización"],
  ce=["Medir PIO basal y semanalmente","Agitar bien antes de usar","No usar lentes de contacto durante tratamiento","Reducir gradualmente para evitar rebote inflamatorio"]),

M("corticoide_sistemico","meprednisona","Meprednisona","Meprednisona",["Deltisona"],
  "Glucocorticoide sintético","Derivado metilado de prednisolona. Potencia antiinflamatoria similar a metilprednisolona. Uso extendido en Latinoamérica",
  ["Enfermedades inflamatorias","Procesos alérgicos","Enfermedades autoinmunes","Asma aguda"],["oral","IM"],
  {"adulto":"Oral: 4-48 mg/día según patología. IM: 20-80 mg según indicación","pediatrico":"0.5-2 mg/kg/día"},
  ["Comp 4, 8, 40 mg","Amp 20, 40, 80 mg"],
  "Evitar durante lactancia","u06","c06_03",
  ea=["Hiperglucemia","Retención hidrosalina","Osteoporosis","Síndrome de Cushing","Miopatía proximal","Úlcera péptica","Infecciones"],
  ce=["Equivalencia: 4 mg meprednisona ≈ 5 mg prednisona","Uso extendido en Argentina y otros países de LA","Reducción gradual obligatoria si uso >2 semanas","Protección gástrica en uso prolongado"]),

# ══════════════════════════════════════════════════════════════
# c06_04 Otros Endocrinos (+5)
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","paricalcitol","Paricalcitol","Paricalcitol",["Zemplar"],
  "Análogo de vitamina D activada","Análogo selectivo del receptor de vitamina D (VDR). Suprime PTH sin aumentar significativamente absorción intestinal de calcio y fósforo",
  ["Hiperparatiroidismo secundario a ERC (estadios 3-5)","Prevención de hiperparatiroidismo en diálisis"],["oral","IV"],
  {"adulto":"Oral: 1-2 mcg/día o 2-4 mcg 3 veces/semana. IV: 0.04-0.1 mcg/kg en diálisis","ajusteRenal":"Ajustar según niveles de PTH, calcio y fósforo"},
  ["Cáps 1, 2, 4 mcg","Amp 5 mcg/mL"],
  "No recomendado","u06","c06_04",
  familia="Análogos de vitamina D",
  ci=["Hipercalcemia","Toxicidad por vitamina D","Hipersensibilidad"],
  ea=["Hipercalcemia","Hiperfosfatemia","Náuseas","Prurito","Edema","Calcificaciones metastásicas"],
  ix=["Tiazidas: mayor riesgo hipercalcemia","Digitálicos: hipercalcemia potencia toxicidad digitálica","Ketoconazol: inhibe metabolismo de paricalcitol"],
  ce=["Monitorizar calcio y fósforo sérico semanalmente al inicio","Producto Ca × P no debe superar 55","Suspender si calcio >10.5 mg/dL","Ajustar según niveles de PTH intacta"],
  pp={"dilucion":"Administrar sin diluir por vía IV directa","velocidadAdministracion":"Bolo IV al final de diálisis","estabilidad":"Usar inmediatamente"}),

M("corticoide_sistemico","etelcalcetida","Etelcalcetida","Etelcalcetida",["Parsabiv"],
  "Calcimimético IV","Agonista del receptor sensor de calcio (CaSR) de segunda generación. Administración IV en diálisis (ventaja de adherencia)",
  ["Hiperparatiroidismo secundario en pacientes en hemodiálisis"],["IV"],
  {"adulto":"5 mg IV 3 veces/semana al final de hemodiálisis. Titular según PTH (máx 15 mg 3x/semana)"},
  ["Vial 2.5 mg/0.5 mL","Vial 5 mg/mL","Vial 10 mg/2 mL"],
  "No recomendado","u06","c06_04",
  familia="Calcimiméticos",
  ci=["Hipocalcemia (Ca corregido <8.3 mg/dL)","Hipersensibilidad"],
  ea=["Hipocalcemia","Náuseas","Vómitos","Diarrea","Parestesias","Calambres musculares","Prolongación QT (por hipocalcemia)"],
  ix=["Cinacalcet oral: no combinar","Fármacos que prolongan QT: riesgo por hipocalcemia"],
  ce=["Administrar SOLO al final de hemodiálisis","Monitorizar calcio antes de cada dosis","No administrar si Ca corregido <7.5 mg/dL","Ventaja sobre cinacalcet: adherencia asegurada (IV en diálisis)"],
  pp={"dilucion":"No diluir, administrar directo","velocidadAdministracion":"Bolo IV en línea de diálisis al final de sesión","estabilidad":"Uso único, no reutilizar vial"}),

M("antidiabetico_oral","liraglutida_obesidad","Liraglutida (obesidad)","Liraglutida 3 mg",["Saxenda"],
  "Agonista GLP-1 para manejo de peso","Análogo de GLP-1 a dosis alta (3 mg vs 1.8 mg en diabetes). Actúa sobre centros hipotalámicos de saciedad y retrasa vaciamiento gástrico",
  ["Obesidad (IMC ≥30)","Sobrepeso (IMC ≥27) con comorbilidad","Manejo crónico de peso"],["SC"],
  {"adulto":"Escalonamiento: sem 1: 0.6 mg/día, sem 2: 1.2 mg, sem 3: 1.8 mg, sem 4: 2.4 mg, sem 5+: 3.0 mg/día","pediatrico":"≥12 años: mismo esquema escalonado"},
  ["Pluma precargada 6 mg/mL (3 mL)"],
  "Contraindicado","u06","c06_04",
  familia="Agonistas GLP-1 para obesidad",emb="X",
  ci=["Hipersensibilidad","Carcinoma medular de tiroides personal/familiar","NEM tipo 2","Embarazo"],
  ea=["Náuseas (40-50% al inicio)","Vómitos","Diarrea","Estreñimiento","Cefalea","Pancreatitis (raro)","Colelitiasis"],
  ix=["Insulina: mayor riesgo de hipoglucemia","Anticonceptivos orales: puede alterar absorción"],
  ce=["Escalonamiento obligatorio para minimizar náuseas","Evaluar pérdida de peso a 16 semanas (esperar ≥5%)","Inyectar SC en abdomen, muslo o brazo","No es sustituto de dieta y ejercicio"],
  alm="Refrigerar (2-8°C). En uso: TA o refrigerado máx 30 días"),

M("antidiabetico_oral","semaglutida_obesidad","Semaglutida (obesidad)","Semaglutida 2.4 mg",["Wegovy"],
  "Agonista GLP-1 semanal para manejo de peso","Agonista GLP-1 de acción prolongada semanal a dosis alta. Reducción promedio de peso 15-17% en estudios clínicos (STEP trials)",
  ["Obesidad (IMC ≥30)","Sobrepeso (IMC ≥27) con comorbilidad","Reducción de riesgo cardiovascular en obesidad"],["SC"],
  {"adulto":"Escalonamiento mensual: 0.25→0.5→1.0→1.7→2.4 mg/semana. Dosis objetivo: 2.4 mg/semana","pediatrico":"≥12 años: mismo esquema escalonado"},
  ["Pluma precargada 0.25, 0.5, 1.0, 1.7, 2.4 mg"],
  "Contraindicado","u06","c06_04",
  familia="Agonistas GLP-1 para obesidad",emb="X",
  ci=["Hipersensibilidad a semaglutida","Carcinoma medular de tiroides personal/familiar","NEM tipo 2","Embarazo"],
  ea=["Náuseas","Vómitos","Diarrea","Estreñimiento","Cefalea","Fatiga","Pancreatitis (raro)","Colelitiasis","Ideación suicida (vigilar)"],
  ix=["Insulina/sulfonilureas: ajustar dosis (hipoglucemia)","Anticonceptivos orales: posible alteración de absorción"],
  ce=["Escalonamiento obligatorio de 4 meses hasta dosis plena","Una inyección semanal (mismo día cada semana)","Evaluar respuesta a 16-20 semanas","Suspender al menos 2 meses antes de embarazo planificado"],
  alm="Refrigerar (2-8°C). En uso: TA o refrigerado máx 28 días"),

M("antidiabetico_oral","orlistat","Orlistat","Orlistat",["Xenical","Alli (OTC)"],
  "Inhibidor de lipasa pancreática","Inhibe lipasas gástrica y pancreática. Reduce absorción de grasas dietarias en ~30%",
  ["Obesidad (IMC ≥30)","Sobrepeso (IMC ≥28) con factores de riesgo"],["oral"],
  {"adulto":"120 mg c/8h con cada comida principal que contenga grasa. Alli OTC: 60 mg c/8h"},
  ["Cáps 60 mg (OTC)","Cáps 120 mg (Rx)"],
  "Compatible con precaución","u06","c06_04",
  familia="Inhibidores de absorción de grasas",emb="X",
  ci=["Colestasis","Malabsorción crónica","Hipersensibilidad","Embarazo"],
  ea=["Esteatorrea","Flatulencia con descarga oleosa","Urgencia fecal","Incontinencia fecal","Manchado oleoso","Déficit vitaminas liposolubles (ADEK)"],
  ix=["Ciclosporina: reduce niveles significativamente","Levotiroxina: separar 4h","Anticoagulantes orales: puede alterar INR","Anticonceptivos orales: puede reducir absorción si diarrea severa"],
  ce=["Tomar durante o hasta 1h después de comida con grasa","Efectos GI proporcionales a grasa ingerida (efecto educativo)","Suplementar vitaminas ADEK separadas 2h","Omitir dosis si comida sin grasa"]),

# ══════════════════════════════════════════════════════════════
# c06_06 Hormonas Suprarrenales (+8) — NUEVO
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","mitotano","Mitotano","Mitotano",["Lysodren"],
  "Adrenolítico","Derivado del insecticida DDT. Destruye selectivamente la corteza suprarrenal (adrenolítico). Inhibe esteroidogénesis y modifica metabolismo periférico de esteroides",
  ["Carcinoma suprarrenal (tratamiento y adyuvante post-cirugía)","Síndrome de Cushing refractario"],["oral"],
  {"adulto":"Inicio 2-3 g/día, titular hasta 6-9 g/día dividido c/8h. Mantener niveles 14-20 mcg/mL"},
  ["Comp 500 mg"],
  "Contraindicado","u06","c06_06",
  familia="Adrenolíticos",emb="X",
  ci=["Hipersensibilidad","Embarazo","Lactancia","Insuficiencia hepática severa"],
  ea=["Insuficiencia adrenal (esperada, requiere reemplazo)","Náuseas y vómitos (muy frecuentes)","Diarrea","Neurotoxicidad (ataxia, confusión)","Hepatotoxicidad","Hipercolesterolemia","Ginecomastia"],
  ix=["Warfarina: mitotano es inductor CYP3A4 potente","Corticoides exógenos: requiere dosis mayores (metabolismo acelerado)","Espironolactona: antagoniza efecto de mitotano"],
  ce=["⚠️ SIEMPRE administrar hidrocortisona de reemplazo concomitante","Monitorizar niveles plasmáticos de mitotano (14-20 mcg/mL)","Efecto puede persistir meses tras suspender (acumulación en tejido adiposo)","Tomar con alimentos grasos (mejora absorción)"],
  fk={"absorcion":"Oral 40%, mejora con grasas","distribucion":"Alta acumulación en tejido adiposo","metabolismo":"Hepático, inductor CYP3A4","vidaMedia":"18-159 días (promedio 53 días)","eliminacion":"Fecal principalmente"}),

M("corticoide_sistemico","ketoconazol_cushing","Ketoconazol (uso endocrino)","Ketoconazol",["Nizoral"],
  "Inhibidor de esteroidogénesis","A dosis altas inhibe múltiples enzimas de la esteroidogénesis suprarrenal (CYP11A1, CYP17, CYP11B1). Reduce cortisol de forma dosis-dependiente",
  ["Síndrome de Cushing (todas las etiologías)","Hiperaldosteronismo","Pretratamiento previo a cirugía de Cushing"],["oral"],
  {"adulto":"Cushing: 200-400 mg c/8-12h. Inicio con 200 mg c/12h, titular según cortisol libre urinario. Máx 1200 mg/día"},
  ["Comp 200 mg"],
  "Contraindicado","u06","c06_06",
  familia="Inhibidores de esteroidogénesis",emb="X",
  ci=["Hepatopatía activa","Uso con fármacos hepatotóxicos","Prolongación QT","Insuficiencia adrenal"],
  ea=["⚠️ Hepatotoxicidad (monitorizar obligatorio)","Insuficiencia adrenal","Náuseas","Ginecomastia","Hipogonadismo","Prolongación QT"],
  ix=["Inhibidor potente CYP3A4: múltiples interacciones","Simvastatina: contraindicado (rabdomiólisis)","Fármacos que prolongan QT: no combinar","Antiácidos/IBP: reducen absorción (requiere acidez gástrica)"],
  ce=["Función hepática semanal las primeras 4-6 semanas, luego mensual","Suspender si ALT >3x LSN","Administrar con alimentos ácidos o bebida ácida","Monitorizar cortisol libre urinario y cortisol matutino","Tener hidrocortisona disponible para reemplazo si insuficiencia adrenal"]),

M("corticoide_sistemico","metirapona","Metirapona","Metirapona",["Metopirone"],
  "Inhibidor de 11β-hidroxilasa","Inhibe selectivamente 11β-hidroxilasa (CYP11B1), bloqueando la conversión de 11-desoxicortisol a cortisol en la suprarrenal",
  ["Síndrome de Cushing (control preoperatorio)","Diagnóstico de insuficiencia adrenal (test de metirapona)","Cushing ectópico"],["oral"],
  {"adulto":"Terapéutico: 250-1000 mg c/6-8h. Titular según cortisol. Test diagnóstico: 30 mg/kg (máx 3 g) dosis única nocturna"},
  ["Cáps 250 mg"],
  "No recomendado","u06","c06_06",
  familia="Inhibidores de esteroidogénesis",
  ci=["Insuficiencia adrenal manifiesta","Hipersensibilidad","Porfiria"],
  ea=["Insuficiencia adrenal","Hirsutismo y acné (acumulación de andrógenos precursores)","Náuseas","Mareo","Cefalea","Hipopotasemia","Hipertensión (acumulación de desoxicorticosterona)"],
  ix=["Fenitoína: acelera metabolismo de metirapona","Anticoagulantes: puede alterar efecto","Corticoides exógenos: interfieren con test diagnóstico"],
  ce=["Monitorizar cortisol y electrolitos frecuentemente","Puede causar hipertensión e hipopotasemia por acumulación de DOC","Tomar con alimentos o leche","Tener hidrocortisona de reemplazo disponible"]),

M("corticoide_sistemico","osilodrostat","Osilodrostat","Osilodrostat",["Isturisa"],
  "Inhibidor potente de 11β-hidroxilasa","Inhibidor oral potente y selectivo de CYP11B1 (11β-hidroxilasa). Mayor potencia y selectividad que metirapona",
  ["Enfermedad de Cushing en adultos (cuando cirugía hipofisaria no es viable o ha fallado)"],["oral"],
  {"adulto":"Inicio 2 mg c/12h. Titular c/2-4 semanas según cortisol. Máx 30 mg c/12h"},
  ["Comp recubierto 1, 5, 10 mg"],
  "Contraindicado","u06","c06_06",
  familia="Inhibidores de esteroidogénesis",emb="X",
  ci=["Hipersensibilidad","Insuficiencia adrenal no tratada","Prolongación QTc"],
  ea=["Insuficiencia adrenal","Prolongación QT","Hirsutismo","Acné","Hipopotasemia","Edema","Náuseas","Cefalea","Fatiga","Artralgia"],
  ix=["Sustratos CYP1A2 (teofilina, duloxetina): osilodrostat es inhibidor","Fármacos que prolongan QT: riesgo aditivo"],
  ce=["ECG basal y periódico (QTc)","Monitorizar cortisol libre urinario y matutino","Tener hidrocortisona de rescate disponible","Electrolitos (K+) frecuentes al titular dosis"]),

M("corticoide_sistemico","levoketoconazol","Levoketoconazol","Levoketoconazol",["Recorlev"],
  "Enantiómero 2S,4R del ketoconazol","Enantiómero puro (2S,4R) de ketoconazol con mayor potencia inhibitoria sobre esteroidogénesis y potencialmente menor hepatotoxicidad",
  ["Síndrome de Cushing endógeno"],["oral"],
  {"adulto":"Inicio 150 mg c/12h. Titular c/2 semanas. Máx 600 mg c/12h"},
  ["Comp 150 mg"],
  "Contraindicado","u06","c06_06",
  familia="Inhibidores de esteroidogénesis",emb="X",
  ci=["Hepatopatía","Prolongación QT","Uso con inhibidores CYP3A4 potentes","Insuficiencia adrenal"],
  ea=["Hepatotoxicidad","Insuficiencia adrenal","Prolongación QT","Náuseas","Cefalea","Hipopotasemia","Artralgia"],
  ix=["Inhibidor CYP3A4: múltiples interacciones","Sustratos de CYP3A4 con margen terapéutico estrecho: contraindicado"],
  ce=["Función hepática antes y semanalmente al inicio","Potencialmente menos hepatotóxico que ketoconazol racémico","ECG basal y periódico","Monitorizar cortisol y electrolitos"]),

M("corticoide_sistemico","pasireotida","Pasireotida","Pasireotida",["Signifor","Signifor LAR"],
  "Análogo de somatostatina multiligando","Análogo de somatostatina con afinidad por subtipos de receptor sst1,2,3,5 (alta afinidad sst5). Inhibe secreción de ACTH por adenomas corticotropos",
  ["Enfermedad de Cushing (cuando cirugía no es opción)","Acromegalia (formulación LAR)"],["SC","IM"],
  {"adulto":"Cushing SC: 0.6-0.9 mg c/12h. Acromegalia IM LAR: 40-60 mg c/4 semanas"},
  ["Amp 0.3, 0.6, 0.9 mg SC","Vial LAR 20, 40, 60 mg"],
  "Contraindicado","u06","c06_06",
  familia="Análogos de somatostatina",
  ci=["Hipersensibilidad","Insuficiencia hepática grave"],
  ea=["⚠️ Hiperglucemia (70% de pacientes, muy frecuente)","Diarrea","Colelitiasis","Náuseas","Dolor abdominal","Bradicardia","Insuficiencia adrenal"],
  ix=["Antidiabéticos: requerimientos aumentados significativamente","Ciclosporina: puede requerir ajuste","Fármacos bradicardizantes: efecto aditivo"],
  ce=["Hiperglucemia es el EA más relevante: monitorizar glucemia intensivamente","Muchos pacientes requieren iniciar antidiabéticos","Ecografía vesicular basal y c/6-12 meses","Monitorizar cortisol libre urinario para eficacia"]),

M("corticoide_sistemico","mifepristona_cushing","Mifepristona (Cushing)","Mifepristona",["Korlym"],
  "Antagonista del receptor de glucocorticoides","Antagonista competitivo del receptor de glucocorticoides (GR). Bloquea acción periférica del cortisol sin reducir sus niveles séricos",
  ["Hiperglucemia por Síndrome de Cushing endógeno (cuando cirugía no es opción)"],["oral"],
  {"adulto":"Inicio 300 mg/día con comida. Titular c/2-4 semanas. Máx 1200 mg/día (20 mg/kg/día)"},
  ["Comp 300 mg"],
  "Contraindicado","u06","c06_06",
  familia="Antagonistas de receptor de glucocorticoides",emb="X",
  ci=["Embarazo (efecto antiprogestágeno: abortivo)","Hemorragia uterina no diagnosticada","Endometriosis","Uso de simvastatina/lovastatina","Uso crónico de corticoides"],
  ea=["Insuficiencia adrenal (paradójica: cortisol sube pero acción bloqueada)","Hipopotasemia","Engrosamiento endometrial","Sangrado vaginal","Náuseas","Fatiga","Artralgia","Hipertensión"],
  ix=["⚠️ Potente inhibidor CYP3A4 y sustrato CYP3A4","Simvastatina: contraindicado","Ciclosporina: niveles impredecibles","Corticoides exógenos: bloquea su acción"],
  ce=["No monitorizar cortisol sérico (sube paradójicamente al bloquear receptor)","Evaluar eficacia por glucemia, no por cortisol","Anticoncepción no hormonal obligatoria (efecto antiprogestágeno)","Vigilar insuficiencia adrenal (usar dexametasona a dosis altas si necesario, ya que compite con mifepristona)"]),

M("corticoide_sistemico","cosintropina","Cosintropina (ACTH sintética)","Cosintropina",["Cortrosyn","Synacthen"],
  "ACTH sintética (tetracosactida)","Péptido sintético de los primeros 24 aminoácidos de ACTH. Estimula corteza suprarrenal para producir cortisol. Uso diagnóstico principal",
  ["Diagnóstico de insuficiencia adrenal (test de estimulación con ACTH)","Espasmos infantiles (síndrome de West)"],["IV","IM"],
  {"adulto":"Test ACTH: 250 mcg IV/IM dosis única. Medir cortisol basal, a 30 y 60 min","pediatrico":"Espasmos infantiles: 0.4-0.8 mg (150 UI)/m²/día IM"},
  ["Vial 250 mcg","Amp depot 1 mg/mL"],
  "No recomendado","u06","c06_06",
  familia="Hormonas adrenocorticotrópicas",
  ci=["Hipersensibilidad","Infecciones sistémicas","Úlcera péptica activa (uso terapéutico)"],
  ea=["Uso diagnóstico: mínimos (reacción alérgica rara)","Uso terapéutico: similares a corticoides sistémicos"],
  ix=["Espironolactona: puede interferir con test","Corticoides exógenos: suspender antes del test"],
  ce=["Test estándar: 250 mcg IV. Medir cortisol a 0, 30, 60 min","Normal: cortisol ≥18 mcg/dL a 30 o 60 min","Uso diagnóstico es seguro y rápido","Tener disponible manejo de anafilaxia (muy raro)"],
  pp={"reconstitucion":"Reconstituir con 1 mL SF","dilucion":"Puede diluir en 250 mL SF para infusión","velocidadAdministracion":"Bolo IV directo en 2 min o infusión en 4-8h","estabilidad":"12h a TA reconstituido"}),

# ══════════════════════════════════════════════════════════════
# c06_07 Fármacos para Metabolismo Óseo-Mineral (+8) — NUEVO
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","etelcalcetida_detalle","Etelcalcetida (detalle clínico)","Etelcalcetida",["Parsabiv"],
  "Calcimimético intravenoso de 2ª generación","Péptido D-aminoácido que activa alostéricamente el receptor sensor de calcio (CaSR) en paratiroides. Administración IV exclusiva en hemodiálisis",
  ["Hiperparatiroidismo secundario en hemodiálisis"],["IV"],
  {"adulto":"Inicio 5 mg IV 3x/semana al final de hemodiálisis. Titular 2.5-5 mg c/4 semanas. Máx 15 mg 3x/semana"},
  ["Vial 2.5 mg/0.5mL","Vial 5 mg/mL","Vial 10 mg/2mL"],
  "No recomendado","u06","c06_07",
  familia="Calcimiméticos",
  ci=["Hipocalcemia severa (Ca corregido <7.5 mg/dL)","Hipersensibilidad"],
  ea=["Hipocalcemia (25-60%)","Espasmos musculares","Náuseas","Vómitos","Diarrea","Cefalea","Parestesias","Prolongación QT secundaria a hipocalcemia"],
  ix=["Cinacalcet: no usar juntos","Otros fármacos que reducen calcio: efecto aditivo","QT-prolongantes: riesgo por hipocalcemia"],
  ce=["Administrar SOLO al final de hemodiálisis por línea venosa","Medir Ca corregido antes de cada dosis","No dar si Ca <7.5 mg/dL, suspender si síntomas de hipocalcemia","Ventaja: adherencia garantizada vs cinacalcet oral"],
  pp={"dilucion":"No diluir, bolo directo","velocidadAdministracion":"Bolo IV en la línea venosa del circuito de diálisis","estabilidad":"Uso único, descartar sobrante"}),

M("corticoide_sistemico","paratormona_recombinante","Teriparatida (PTH 1-34)","Teriparatida",["Forteo","Terrosa"],
  "Fragmento recombinante de PTH (1-34)","Fragmento amino-terminal de la hormona paratiroidea humana. Administración intermitente estimula formación ósea (efecto anabólico)",
  ["Osteoporosis severa con alto riesgo de fractura","Osteoporosis por glucocorticoides","Osteoporosis masculina"],["SC"],
  {"adulto":"20 mcg/día SC en muslo o abdomen. Duración máxima: 24 meses"},
  ["Pluma precargada 20 mcg/80 mcL (28 dosis)"],
  "No recomendado","u06","c06_07",
  familia="Agentes anabólicos óseos",
  ci=["Hipercalcemia preexistente","Enfermedad de Paget","Elevación inexplicada de fosfatasa alcalina","Radioterapia esquelética previa","Metástasis óseas","Pacientes pediátricos con epífisis abiertas"],
  ea=["Hipercalcemia","Mareo","Calambres","Náuseas","Artralgias","Cefalea","Hipotensión ortostática"],
  ix=["Digitálicos: hipercalcemia potencia toxicidad","Suplementos de calcio: ajustar para evitar hipercalcemia"],
  ce=["Duración máxima 24 meses (riesgo teórico de osteosarcoma en ratas)","Enseñar autoinyección SC","Administrar preferiblemente al acostarse para reducir hipotensión","Monitorizar calcio sérico al inicio","Seguir con antirresortivo al completar ciclo"],
  alm="Refrigerar (2-8°C). En uso: refrigerar, usar dentro de 28 días"),

M("corticoide_sistemico","abaloparatida","Abaloparatida","Abaloparatida",["Tymlos"],
  "Análogo del péptido relacionado con PTH","Análogo sintético de PTHrP (proteína relacionada con PTH). Acción anabólica ósea selectiva con menor efecto hipercalcémico que teriparatida",
  ["Osteoporosis posmenopáusica con alto riesgo de fractura"],["SC"],
  {"adulto":"80 mcg/día SC en región periumbilical. Duración máxima: 24 meses"},
  ["Pluma precargada 3120 mcg/1.56 mL (30 dosis)"],
  "No recomendado","u06","c06_07",
  familia="Agentes anabólicos óseos",emb="X",
  ci=["Hipercalcemia","Enfermedad ósea metabólica distinta de osteoporosis","Radioterapia esquelética","Hipersensibilidad"],
  ea=["Mareo","Náuseas","Cefalea","Palpitaciones","Fatiga","Dolor abdominal","Hipercalciuria","Hipercalcemia (menos que teriparatida)"],
  ce=["Menor riesgo de hipercalcemia que teriparatida","Duración máxima 24 meses","Enseñar autoinyección SC periumbilical","Seguir con antirresortivo al finalizar ciclo anabólico"],
  alm="Refrigerar (2-8°C). En uso: TA máx 30 días"),

M("corticoide_sistemico","romosozumab","Romosozumab","Romosozumab",["Evenity"],
  "Anticuerpo anti-esclerostina","Anticuerpo monoclonal contra esclerostina. Efecto dual: aumenta formación ósea y reduce resorción ósea simultáneamente",
  ["Osteoporosis severa posmenopáusica con alto riesgo de fractura"],["SC"],
  {"adulto":"210 mg SC/mes (2 inyecciones de 105 mg) durante 12 meses. Luego transicionar a antirresortivo"},
  ["Jeringa precargada 105 mg/1.17 mL"],
  "No recomendado","u06","c06_07",
  familia="Anticuerpos anti-esclerostina",emb="X",
  ci=["Hipocalcemia no corregida","Antecedente de IAM o ACV","Alto riesgo cardiovascular","Hipersensibilidad"],
  ea=["⚠️ Eventos cardiovasculares (IAM, ACV): black box warning","Artralgias","Cefalea","Hipocalcemia","Reacción en sitio de inyección"],
  ix=["Suplementos de calcio y vitamina D: administrar concomitantemente"],
  ce=["Black box: mayor riesgo cardiovascular vs alendronato","No usar si IAM o ACV en el último año","Tratamiento máximo 12 meses (efecto se atenúa)","Corregir hipocalcemia antes de iniciar","2 inyecciones SC consecutivas cada mes"]),

M("corticoide_sistemico","burosumab","Burosumab","Burosumab",["Crysvita"],
  "Anticuerpo anti-FGF23","Anticuerpo monoclonal contra factor de crecimiento fibroblástico 23 (FGF23). Aumenta reabsorción renal de fósforo y síntesis renal de calcitriol",
  ["Hipofosfatemia ligada al X (XLH)","Osteomalacia inducida por tumor (TIO)"],["SC"],
  {"adulto":"TIO: 0.5 mg/kg SC c/4 semanas. Máx 2 mg/kg","pediatrico":"XLH: 0.8 mg/kg SC c/2 semanas (redondeado a 10 mg más cercano)"},
  ["Vial 10, 20, 30, 40 mg"],
  "No recomendado","u06","c06_07",
  familia="Anticuerpos anti-FGF23",
  ci=["Hiperfosfatemia","Uso concomitante de suplementos de fósforo oral o vitamina D activa","Insuficiencia renal severa (TFG <30)"],
  ea=["Reacción en sitio de inyección","Cefalea","Dolor en extremidades","Rash","Absceso dental (niños)","Hiperfosfatemia","Síndrome de piernas inquietas"],
  ce=["Suspender suplementos de fósforo y calcitriol 1 semana antes de iniciar","Monitorizar fósforo sérico (objetivo: límite bajo de normalidad)","Monitorizar calcio sérico y urinario","Ecografía renal periódica (riesgo de nefrocalcinosis)"],
  alm="Refrigerar (2-8°C). No congelar"),

M("corticoide_sistemico","fosfato_oral","Fosfato oral","Fosfato sódico/potásico",["Fosfoenterol","K-Phos"],
  "Suplemento de fósforo","Aporte exógeno de fósforo para corrección de hipofosfatemia. Disponible como fosfato de sodio, potasio o combinación",
  ["Hipofosfatemia","Hipofosfatemia ligada al X (antes de burosumab)","Raquitismo hipofosfatémico","Hiperparatiroidismo (reduce calcio)"],["oral","IV"],
  {"adulto":"Oral: 1-3 g de fósforo elemental/día dividido c/6-8h. IV (severa): 0.08-0.32 mmol/kg en 6h","pediatrico":"Oral: 30-50 mg/kg/día de fósforo elemental dividido c/6h"},
  ["Sol oral fosfato sódico","Comp efervescente 500 mg fósforo","Amp IV fosfato de sodio o potasio"],
  "Compatible con precaución","u06","c06_07",
  familia="Suplementos minerales",emb="C",
  ci=["Hiperfosfatemia","Hipocalcemia severa","Insuficiencia renal avanzada (oral)","Hiperpotasemia (formulación potásica)"],
  ea=["Diarrea","Náuseas","Dolor abdominal","Hipocalcemia","Calcificaciones ectópicas si producto Ca×P >55","Hiperpotasemia (formulación potásica)"],
  ix=["Antiácidos con aluminio: reducen absorción de fósforo","Suplementos de calcio: separar por quelación","Calcitriol: monitorizar calcio estrechamente"],
  ce=["Dividir en 3-4 tomas para minimizar diarrea","Monitorizar calcio y fósforo séricos","Producto Ca × P no debe superar 55","IV solo para hipofosfatemia severa sintomática"],
  pp={"dilucion":"Diluir en 250-500 mL SF o SG5%","velocidadAdministracion":"Infundir en 6 horas mínimo","estabilidad":"24h a TA diluido"}),

M("corticoide_sistemico","carbonato_lantano","Carbonato de Lantano","Carbonato de lantano",["Fosrenol"],
  "Quelante de fósforo no cálcico","Quelante de fosfato a base de lantano (tierra rara). Se une al fosfato dietario en el tracto GI formando complejos insolubles",
  ["Hiperfosfatemia en enfermedad renal crónica en diálisis"],["oral"],
  {"adulto":"Inicio 750-1500 mg/día dividido con comidas. Titular según fosfato sérico. Dosis habitual: 1500-3000 mg/día"},
  ["Comp masticable 250, 500, 750, 1000 mg"],
  "No recomendado","u06","c06_07",
  familia="Quelantes de fósforo",
  ci=["Hipersensibilidad","Hipofosfatemia","Obstrucción intestinal"],
  ea=["Náuseas","Vómitos","Diarrea","Dolor abdominal","Acumulación ósea de lantano (significado clínico incierto)"],
  ix=["Quinolonas: puede reducir absorción (separar 2h)","Levotiroxina: separar tomas","Tetraciclinas: puede quelar"],
  ce=["Masticar completamente antes de tragar (NO tragar enteros)","Tomar CON las comidas o inmediatamente después","No contiene calcio ni aluminio (ventaja)","Monitorizar fósforo sérico c/2-4 semanas al titular"]),

M("corticoide_sistemico","sevelamer_carbonato","Sevelámero carbonato","Sevelámero carbonato",["Renvela"],
  "Quelante de fósforo polimérico","Polímero sintético no absorbible que se une al fosfato dietario en el tracto GI. No contiene calcio ni metales",
  ["Hiperfosfatemia en ERC en diálisis","Hiperfosfatemia en ERC prediálisis"],["oral"],
  {"adulto":"800-1600 mg c/8h con las comidas. Titular según fosfato sérico"},
  ["Comp 800 mg","Polvo para suspensión 0.8, 2.4 g"],
  "Compatible con precaución","u06","c06_07",
  familia="Quelantes de fósforo",
  ci=["Obstrucción intestinal","Hipofosfatemia","Íleo"],
  ea=["Náuseas","Vómitos","Diarrea o estreñimiento","Dolor abdominal","Distensión abdominal","Acidosis metabólica (solo sevelámero HCl, no carbonato)"],
  ix=["Ciprofloxacino: reduce absorción","Levotiroxina: reduce absorción","Ciclosporina, tacrolimus, micofenolato: puede reducir absorción"],
  ce=["Tomar CON las comidas (funciona uniendo fosfato dietario)","No triturar comprimidos","Ventaja: no aporta calcio, reduce LDL colateral","Separar de otros fármacos 1h antes o 3h después"]),

# ══════════════════════════════════════════════════════════════
# c06_08 Fármacos para Obesidad (+7) — NUEVO
# ══════════════════════════════════════════════════════════════
M("antidiabetico_oral","naltrexona_bupropion","Naltrexona/Bupropión","Naltrexona + Bupropión",["Contrave","Mysimba"],
  "Combinación para manejo de peso","Combinación de antagonista opioide (naltrexona) y aminocetona (bupropión). Actúan sinérgicamente sobre circuitos hipotalámicos de apetito y mesolímbicos de recompensa",
  ["Obesidad (IMC ≥30)","Sobrepeso (IMC ≥27) con comorbilidad"],["oral"],
  {"adulto":"Escalonamiento 4 semanas: sem 1: 1 comp AM; sem 2: 1 comp c/12h; sem 3: 2 AM + 1 PM; sem 4+: 2 comp c/12h"},
  ["Comp LP naltrexona 8 mg / bupropión 90 mg"],
  "No recomendado","u06","c06_08",
  familia="Fármacos para obesidad",emb="X",
  ci=["HTA no controlada","Epilepsia","Trastornos alimentarios (bulimia/anorexia)","Uso de IMAO","Uso crónico de opioides","Abstinencia de alcohol/benzodiazepinas"],
  ea=["Náuseas (frecuente al inicio)","Estreñimiento","Cefalea","Vómitos","Mareo","Insomnio","Boca seca","Aumento de PA y FC"],
  ix=["Opioides: naltrexona bloquea su efecto analgésico","IMAO: contraindicado","Fármacos que reducen umbral convulsivo: mayor riesgo convulsiones"],
  ce=["Escalonamiento obligatorio en 4 semanas","Evaluar pérdida ≥5% peso a 12 semanas (si no: suspender)","Monitorizar PA y FC","Advertir que opioides no serán efectivos para dolor"]),

M("antidiabetico_oral","fentermina","Fentermina","Fentermina",["Adipex-P","Ionamin"],
  "Simpaticomimético anorexígeno","Amina simpaticomimética derivada de anfetamina. Libera noradrenalina y dopamina en hipotálamo, suprimiendo apetito",
  ["Obesidad (IMC ≥30, uso a corto plazo ≤12 semanas)"],["oral"],
  {"adulto":"15-37.5 mg/día por la mañana. No usar después del mediodía (insomnio)"},
  ["Cáps 15, 30, 37.5 mg","Comp 37.5 mg"],
  "Contraindicado","u06","c06_08",
  familia="Simpaticomiméticos anorexígenos",emb="X",
  ci=["Enfermedad cardiovascular","HTA no controlada","Hipertiroidismo","Glaucoma","Antecedente de abuso de sustancias","Uso de IMAO (14 días)","Embarazo"],
  ea=["Insomnio","Taquicardia","HTA","Boca seca","Nerviosismo","Cefalea","Potencial de abuso","Hipertensión pulmonar (raro)"],
  ix=["IMAO: crisis hipertensiva","Insulina: puede requerir ajuste","Otros simpaticomiméticos: efectos aditivos cardiovasculares"],
  ce=["Uso máximo 12 semanas (dependencia potencial)","Administrar por la mañana para evitar insomnio","Sustancia controlada (programa IV DEA)","Monitorizar PA y FC"]),

M("antidiabetico_oral","fentermina_topiramato","Fentermina/Topiramato LP","Fentermina + Topiramato",["Qsymia"],
  "Combinación simpaticomimético + anticonvulsivante para peso","Sinergia anorexígena: fentermina (noradrenalina) + topiramato (GABA/glutamato, carbónico anhidrasa). Permite dosis menores de cada componente",
  ["Obesidad (IMC ≥30)","Sobrepeso (IMC ≥27) con comorbilidad"],["oral"],
  {"adulto":"Inicio: 3.75/23 mg/día x 14 días, luego 7.5/46 mg/día. Si necesario: 11.25/69 mg x 14 días, luego 15/92 mg/día"},
  ["Cáps LP 3.75/23, 7.5/46, 11.25/69, 15/92 mg"],
  "Contraindicado","u06","c06_08",
  familia="Fármacos combinados para obesidad",emb="X",
  ci=["Embarazo","Glaucoma","Hipertiroidismo","Uso de IMAO","Enfermedad CV inestable"],
  ea=["Parestesias","Boca seca","Estreñimiento","Insomnio","Disgeusia","Mareo","Nefrolitiasis","Defectos congénitos (topiramato)"],
  ix=["Anticonceptivos: topiramato puede reducir eficacia","IMAO: contraindicado","Depresores del SNC: potenciación"],
  ce=["⚠️ Teratogénico: anticoncepción obligatoria y test de embarazo mensual","Escalonamiento gradual obligatorio","Evaluar respuesta a 12 semanas con dosis 7.5/46","Reducir gradualmente al suspender (no discontinuar abruptamente)"]),

M("antidiabetico_oral","lisdexanfetamina_ta","Lisdexanfetamina (trastorno atracones)","Lisdexanfetamina",["Vyvanse"],
  "Profármaco de anfetamina para trastorno por atracón","Profármaco de d-anfetamina. Indicación específica para trastorno por atracón moderado-severo. Modula circuitos de recompensa y control de impulsos",
  ["Trastorno por atracón (BED) moderado-severo"],["oral"],
  {"adulto":"Inicio 30 mg/día por la mañana. Titular c/semana: 50 mg, luego 70 mg/día. Rango: 50-70 mg/día"},
  ["Cáps 30, 50, 70 mg"],
  "Contraindicado","u06","c06_08",
  familia="Anfetaminas (trastorno alimentario)",emb="C",
  ci=["Enfermedad CV avanzada","Hipertiroidismo","Agitación","Antecedente de abuso de sustancias","Uso de IMAO (14 días)","Glaucoma"],
  ea=["Disminución del apetito","Insomnio","Boca seca","Taquicardia","Nerviosismo","Potencial de abuso (menor que anfetaminas IR)"],
  ix=["IMAO: crisis hipertensiva","Agentes serotonérgicos: síndrome serotoninérgico","Acidificantes urinarios: aumentan excreción"],
  ce=["Solo aprobado para trastorno por atracón, NO para obesidad simple","Sustancia controlada programa II","Administrar por la mañana","Monitorizar PA, FC y salud mental"]),

M("antidiabetico_oral","cellulose_mcp","Carboximetilcelulosa/Ácido Cítrico (hidrogel)","Hidrogel de CMC reticulada",["Plenity"],
  "Hidrogel oral superabsorbente","Cápsulas de hidrogel (carboximetilcelulosa + ácido cítrico) que absorben agua en estómago (~100x su peso), creando sensación de saciedad sin absorción sistémica",
  ["Sobrepeso u obesidad (IMC 25-40) como adyuvante a dieta y ejercicio"],["oral"],
  {"adulto":"3 cápsulas con 500 mL de agua antes del almuerzo y la cena (6 cápsulas/día)"},
  ["Cáps (hidrogel)"],
  "No evaluado","u06","c06_08",
  familia="Dispositivos médicos ingeribles",emb="B",
  ci=["Alergia a celulosa o ácido cítrico","Obstrucción GI","Disfagia","Esofagitis eosinofílica","Embarazo"],
  ea=["Distensión abdominal","Flatulencia","Dolor abdominal","Diarrea","Mínimos (no se absorbe)"],
  ix=["Metformina: puede alterar velocidad de absorción (separar)","Levotiroxina: administrar 30 min antes del hidrogel"],
  ce=["Clasificado como dispositivo médico (no fármaco)","No se absorbe: perfil de seguridad favorable","Tomar con abundante agua (≥500 mL)","Se degrada en intestino y se excreta"]),

M("antidiabetico_oral","setmelanotida","Setmelanotida","Setmelanotida",["Imcivree"],
  "Agonista MC4R","Agonista selectivo del receptor de melanocortina 4 (MC4R). Restaura señalización de saciedad en pacientes con defectos genéticos específicos de la vía leptina-melanocortina",
  ["Obesidad por deficiencia de POMC, PCSK1 o LEPR confirmada genéticamente"],["SC"],
  {"adulto":"Inicio 2 mg/día SC. Si respuesta insuficiente tras 2 semanas: 3 mg/día. ≥12 años: misma dosis","pediatrico":"6-12 años: 1 mg/día, titular a 2-3 mg/día"},
  ["Vial 10 mg/mL multidosis"],
  "No recomendado","u06","c06_08",
  familia="Agonistas de melanocortina",emb="X",
  ci=["Hipersensibilidad","Obesidad sin confirmación de defecto genético POMC/PCSK1/LEPR"],
  ea=["Hiperpigmentación cutánea (esperada, por activación MC1R)","Reacción en sitio de inyección","Erección espontánea/priapismo","Depresión","Ideación suicida"],
  ix=["Mínimas interacciones sistémicas descritas"],
  ce=["Solo para obesidad monogénica confirmada genéticamente","Hiperpigmentación es efecto esperado (informar al paciente)","Monitorizar salud mental (depresión, ideación suicida)","Evaluar eficacia: ≥5% pérdida de peso a 12-16 semanas"],
  alm="Refrigerar (2-8°C). En uso: TA máx 30 días"),

M("antidiabetico_oral","gelesis","Gelesis100 (hidrogel oral)","Ácido cítrico reticulado + CMC",["Plenity"],
  "Hidrogel superabsorbente oral de segunda generación","Partículas de hidrogel que se expanden en estómago y intestino delgado aumentando volumen y viscosidad. Se biodegradan en colon",
  ["Sobrepeso y obesidad (IMC ≥25) como complemento a dieta y ejercicio"],["oral"],
  {"adulto":"3 cápsulas con 500 mL de agua, 20-30 min antes del almuerzo y cena"},
  ["Cáps (partículas de hidrogel)"],
  "No evaluado","u06","c06_08",
  familia="Dispositivos médicos ingeribles",emb="B",
  ci=["Alergia a componentes","Obstrucción GI","Disfagia","Embarazo"],
  ea=["Distensión abdominal","Flatulencia","Dolor abdominal leve","Diarrea"],
  ix=["Puede alterar velocidad de absorción de fármacos orales (separar 30 min)"],
  ce=["Clasificado como dispositivo médico (aprobado por FDA)","No sistémico: perfil de seguridad favorable","Tomar siempre con abundante agua","Se biodegrada completamente en el colon"]),

# ══════════════════════════════════════════════════════════════
# c06_09 Análogos y Antagonistas Hormonales (+11) — NUEVO
# ══════════════════════════════════════════════════════════════
M("corticoide_sistemico","pegvisomant","Pegvisomant","Pegvisomant",["Somavert"],
  "Antagonista del receptor de GH","Análogo peguilado de GH modificado genéticamente. Bloquea receptor de GH impidiendo señalización y producción de IGF-1",
  ["Acromegalia resistente o intolerante a análogos de somatostatina"],["SC"],
  {"adulto":"Carga: 40 mg SC. Mantenimiento: 10-30 mg/día SC. Titular según IGF-1"},
  ["Vial 10, 15, 20, 25, 30 mg"],
  "No recomendado","u06","c06_09",
  familia="Antagonistas del receptor de GH",
  ci=["Hipersensibilidad","Insuficiencia hepática severa"],
  ea=["Elevación de transaminasas","Reacción en sitio de inyección","Lipohipertrofia","Cefalea","Náuseas","Diarrea","Crecimiento de adenoma hipofisario (vigilar)"],
  ix=["Insulina/antidiabéticos: puede mejorar sensibilidad a insulina (ajustar)","Opioides: puede requerir ajuste de dosis"],
  ce=["Monitorizar función hepática mensual x 6 meses, luego c/6 meses","Guiar dosificación por niveles de IGF-1 (normalizar)","No medir GH (niveles suben al bloquear receptor)","RM hipofisaria anual (vigilar crecimiento adenoma)"],
  alm="Refrigerar (2-8°C). Reconstituido: usar inmediatamente"),

M("corticoide_sistemico","cabergolina_prolactinoma","Cabergolina (prolactinoma)","Cabergolina",["Dostinex"],
  "Agonista dopaminérgico D2","Agonista dopaminérgico ergolínico de larga acción. Inhibe secreción de prolactina y reduce tamaño de prolactinomas",
  ["Prolactinoma (micro y macro)","Hiperprolactinemia","Inhibición de lactancia","Acromegalia (adyuvante)"],["oral"],
  {"adulto":"Prolactinoma: 0.25-0.5 mg 2 veces/semana. Titular c/4 semanas según prolactina. Habitual: 1-2 mg/semana. Inhibición lactancia: 0.25 mg c/12h x 2 días"},
  ["Comp 0.5 mg"],
  "Contraindicado (uso como inhibidor de lactancia)","u06","c06_09",
  familia="Agonistas dopaminérgicos",
  ci=["Hipersensibilidad a ergotamínicos","Fibrosis cardíaca, pulmonar o retroperitoneal","Valvulopatía cardíaca"],
  ea=["Náuseas","Hipotensión ortostática","Cefalea","Mareo","Fatiga","Valvulopatía cardíaca (dosis altas/prolongadas)","Trastorno del control de impulsos (ludopatía, hipersexualidad)"],
  ix=["Antipsicóticos: antagonizan efecto dopaminérgico","Macrólidos: pueden aumentar niveles","Antihipertensivos: hipotensión aditiva"],
  ce=["Ecocardiograma basal y anual (vigilar valvulopatía)","Inicio con dosis bajas nocturnas (minimizar hipotensión)","Puede normalizar prolactina y reducir tumor >90% de casos","Vigilar trastornos del control de impulsos"]),

M("corticoide_sistemico","leuprolida","Leuprolida (Leuprorelina)","Leuprolida",["Lupron","Eligard","Viadur"],
  "Agonista GnRH de acción prolongada","Análogo superagonista de GnRH. Administración continua causa desensibilización hipofisaria con supresión gonadal (castración médica)",
  ["Cáncer de próstata avanzado","Endometriosis","Pubertad precoz central","Miomas uterinos","Fertilización in vitro"],["SC","IM"],
  {"adulto":"Próstata: 7.5 mg IM mensual, 22.5 mg c/3 meses, o 45 mg c/6 meses. Endometriosis: 3.75 mg IM mensual x 6 meses","pediatrico":"Pubertad precoz: 50 mcg/kg/día SC o depot 7.5-15 mg IM mensual"},
  ["Vial depot 3.75, 7.5, 11.25, 22.5, 30, 45 mg","Implante SC 65 mg"],
  "Contraindicado","u06","c06_09",
  familia="Agonistas GnRH",emb="X",
  ci=["Embarazo","Hemorragia vaginal no diagnosticada","Hipersensibilidad"],
  ea=["Flare tumoral inicial (1-2 semanas)","Sofocos","Disfunción eréctil","Pérdida de libido","Osteoporosis","Depresión","Aumento de peso","Ginecomastia"],
  ix=["Fármacos que prolongan QT: riesgo por hipogonadismo","Andrógenos: antagonizan efecto de supresión"],
  ce=["⚠️ Flare tumoral las primeras 2 semanas: dar antiandrógeno (bicalutamida) como cobertura","Monitorizar PSA y testosterona","Densitometría ósea anual","Educar sobre sofocos y efectos de hipogonadismo"]),

M("corticoide_sistemico","goserelina","Goserelina","Goserelina",["Zoladex"],
  "Agonista GnRH implantable","Análogo de GnRH en formulación de implante SC de liberación sostenida. Desensibilización hipofisaria con supresión gonadal",
  ["Cáncer de próstata","Cáncer de mama premenopáusico","Endometriosis","Adelgazamiento endometrial prequirúrgico","Fertilización in vitro"],["SC"],
  {"adulto":"Implante 3.6 mg SC c/28 días o 10.8 mg SC c/12 semanas"},
  ["Implante SC 3.6 mg","Implante SC 10.8 mg"],
  "Contraindicado","u06","c06_09",
  familia="Agonistas GnRH",emb="X",
  ci=["Embarazo","Lactancia","Hemorragia vaginal no diagnosticada"],
  ea=["Sofocos","Disminución de libido","Disfunción eréctil","Osteoporosis","Cefalea","Depresión","Flare tumoral inicial","Reacción en sitio de implante"],
  ce=["Implante SC en pared abdominal anterior","Flare tumoral: antiandrógeno concomitante en cáncer de próstata","No superar 6 meses de uso en endometriosis (osteoporosis)","Verificar implantación correcta (palpable SC)"]),

M("corticoide_sistemico","triptorelina","Triptorelina","Triptorelina",["Decapeptyl","Trelstar"],
  "Agonista GnRH depot","Decapéptido análogo superagonista de GnRH. Formulación depot IM con duración 1-6 meses según presentación",
  ["Cáncer de próstata avanzado","Pubertad precoz central","Endometriosis","Miomas uterinos"],["IM"],
  {"adulto":"Próstata: 3.75 mg IM mensual o 11.25 mg c/3 meses. Endometriosis: 3.75 mg IM mensual","pediatrico":"Pubertad precoz: 50 mcg/kg/día o depot mensual"},
  ["Vial depot 3.75, 11.25, 22.5 mg"],
  "Contraindicado","u06","c06_09",
  familia="Agonistas GnRH",emb="X",
  ci=["Embarazo","Hipersensibilidad a GnRH o análogos"],
  ea=["Sofocos","Impotencia","Disminución libido","Osteoporosis","Flare tumoral","Dolor en sitio de inyección","Astenia"],
  ce=["Flare en cáncer de próstata: cubrir con antiandrógeno 2 semanas","Inyección IM profunda (no IV)","Monitorizar testosterona y PSA","Tratamiento de endometriosis máx 6 meses"]),

M("corticoide_sistemico","nafarelina","Nafarelina","Nafarelina",["Synarel"],
  "Agonista GnRH intranasal","Análogo de GnRH en spray nasal. Comodidad de vía intranasal. Desensibilización hipofisaria tras uso continuo",
  ["Endometriosis","Pubertad precoz central"],["intranasal"],
  {"adulto":"Endometriosis: 200 mcg (1 spray) en una narina AM + 200 mcg en otra narina PM. Si necesario: 400 mcg c/12h","pediatrico":"Pubertad precoz: 800-1600 mcg/día dividido c/8h"},
  ["Spray nasal 2 mg/mL (200 mcg/spray, 60 dosis)"],
  "Contraindicado","u06","c06_09",
  familia="Agonistas GnRH",emb="X",
  ci=["Embarazo","Hemorragia vaginal no diagnosticada","Hipersensibilidad"],
  ea=["Sofocos","Cefalea","Sequedad vaginal","Disminución libido","Rinitis","Acné","Mialgias","Pérdida ósea"],
  ce=["Spray nasal: alternar narinas","No usar descongestionantes nasales 30 min antes/después","Tratamiento de endometriosis máx 6 meses","Anticoncepción no hormonal durante tratamiento"]),

M("corticoide_sistemico","degarelix","Degarelix","Degarelix",["Firmagon"],
  "Antagonista GnRH","Antagonista competitivo del receptor de GnRH. Bloqueo inmediato sin flare tumoral inicial (ventaja sobre agonistas)",
  ["Cáncer de próstata avanzado (especialmente cuando flare es peligroso)"],["SC"],
  {"adulto":"Carga: 240 mg SC (2 inyecciones de 120 mg). Mantenimiento: 80 mg SC c/28 días"},
  ["Vial 80, 120 mg"],
  "No aplica","u06","c06_09",
  familia="Antagonistas GnRH",
  ci=["Hipersensibilidad","Prolongación QT severa"],
  ea=["Reacción en sitio de inyección (40%)","Sofocos","Aumento de peso","Fatiga","Elevación transaminasas","Prolongación QT"],
  ix=["Fármacos que prolongan QT: precaución","Antiandrógenos: no es necesario (no hay flare)"],
  ce=["Ventaja principal: sin flare tumoral (supresión inmediata de testosterona)","Inyección SC abdominal (NO IM)","Reacción local frecuente: informar al paciente","ECG basal y periódico (QTc)"],
  pp={"reconstitucion":"Reconstituir con agua estéril incluida. Agitar suavemente","velocidadAdministracion":"SC profunda en abdomen. No administrar IV","estabilidad":"Usar dentro de 1h de reconstitución"}),

M("corticoide_sistemico","cetrorelix","Cetrorelix","Cetrorelix",["Cetrotide"],
  "Antagonista GnRH para reproducción asistida","Antagonista competitivo de GnRH de uso en protocolos de estimulación ovárica. Previene pico prematuro de LH",
  ["Prevención de ovulación prematura en FIV","Protocolos de estimulación ovárica controlada"],["SC"],
  {"adulto":"Protocolo múltiple: 0.25 mg/día SC desde día 5-6 de estimulación hasta día de hCG. Protocolo único: 3 mg SC cuando folículo líder ≥14 mm"},
  ["Vial 0.25, 3 mg + jeringa precargada de solvente"],
  "Contraindicado","u06","c06_09",
  familia="Antagonistas GnRH",emb="X",
  ci=["Embarazo","Lactancia","Insuficiencia renal o hepática severa","Hipersensibilidad a GnRH"],
  ea=["Síndrome de hiperestimulación ovárica","Reacción en sitio de inyección","Cefalea","Náuseas"],
  ix=["Gonadotropinas: uso concomitante (protocolo de FIV)"],
  ce=["Inyectar SC en abdomen inferior","Uso exclusivo bajo supervisión de especialista en reproducción","Almacenar refrigerado, reconstituir antes de uso","Monitorizar ecografía y estradiol durante protocolo"],
  alm="Refrigerar (2-8°C)"),

M("corticoide_sistemico","ganirelix","Ganirelix","Ganirelix",["Orgalutran","Ganirelix"],
  "Antagonista GnRH para reproducción asistida","Decapéptido sintético antagonista de GnRH. Suprime rápidamente gonadotropinas y previene pico prematuro de LH en ciclos de FIV",
  ["Prevención de ovulación prematura en estimulación ovárica para FIV"],["SC"],
  {"adulto":"0.25 mg SC/día desde el día 5 o 6 de estimulación con FSH, hasta el día de la hCG inclusive"},
  ["Jeringa precargada 0.25 mg/0.5 mL"],
  "Contraindicado","u06","c06_09",
  familia="Antagonistas GnRH",emb="X",
  ci=["Embarazo","Hipersensibilidad a GnRH o análogos","Insuficiencia renal o hepática moderada-grave"],
  ea=["Cefalea","Náuseas","Dolor abdominal","Reacción en sitio de inyección","Síndrome de hiperestimulación ovárica"],
  ce=["Jeringa precargada lista para usar","Inyectar SC en muslo superior, rotando sitios","Uso exclusivo en protocolos de FIV","Monitorización folicular obligatoria"],
  alm="TA (no requiere refrigeración). Proteger de luz"),

M("corticoide_sistemico","abiraterona","Abiraterona","Acetato de abiraterona",["Zytiga","Yonsa"],
  "Inhibidor de CYP17 (biosíntesis de andrógenos)","Inhibidor selectivo e irreversible de CYP17A1 (17α-hidroxilasa/C17,20-liasa). Bloquea síntesis de andrógenos en suprarrenales, testículos y tumor",
  ["Cáncer de próstata metastásico resistente a castración","Cáncer de próstata metastásico hormonosensible de alto riesgo"],["oral"],
  {"adulto":"Zytiga: 1000 mg/día en ayunas + prednisona 5 mg c/12h. Yonsa: 500 mg/día con alimentos + prednisona 5 mg c/12h"},
  ["Comp 250, 500 mg (Zytiga)","Comp 125 mg micronizado (Yonsa)"],
  "No aplica","u06","c06_09",
  familia="Inhibidores de biosíntesis de andrógenos",emb="X",
  ci=["Insuficiencia hepática severa","Embarazo (mujeres: no manipular comprimidos)"],
  ea=["Hipertensión","Hipopotasemia","Edema","Fatiga","Infección urinaria","Artralgias","Hepatotoxicidad","Hiperglucemia"],
  ix=["Sustratos CYP2D6: abiraterona inhibe CYP2D6","Inductores CYP3A4 (rifampicina): evitar"],
  ce=["Siempre con prednisona/prednisolona (previene exceso mineralocorticoide)","Zytiga: en ayunas estricto (aumenta absorción 10x con comida)","Función hepática c/2 semanas x 3 meses, luego mensual","Monitorizar PA, K+ y retención hídrica"]),

M("corticoide_sistemico","enzalutamida","Enzalutamida","Enzalutamida",["Xtandi"],
  "Antiandrógeno de nueva generación","Inhibidor del receptor de andrógenos. Triple mecanismo: bloquea unión de andrógenos al receptor, impide translocación nuclear e inhibe unión al ADN",
  ["Cáncer de próstata metastásico resistente a castración","Cáncer de próstata no metastásico resistente a castración","Cáncer de próstata metastásico hormonosensible"],["oral"],
  {"adulto":"160 mg/día (4 cápsulas de 40 mg) en dosis única con o sin alimentos"},
  ["Cáps 40, 80 mg"],
  "No aplica","u06","c06_09",
  familia="Antiandrógenos de nueva generación",emb="X",
  ci=["Embarazo (mujeres: no manipular)","Hipersensibilidad"],
  ea=["Fatiga","Hipertensión","Sofocos","Artralgias","Caídas/fracturas","Convulsiones (raro)","Deterioro cognitivo","Rash"],
  ix=["Inductor potente CYP3A4 y CYP2C9/19: reduce niveles de warfarina, omeprazol, etc.","Sustratos de P-gp: aumenta niveles","Fármacos que reducen umbral convulsivo: precaución"],
  ce=["Puede tomarse con o sin alimentos","Riesgo de convulsiones: evitar en epilepsia o antecedente","Inductor enzimático potente: revisar TODAS las interacciones","Monitorizar PA, función hepática y PSA"]),
]

NEW_CHAPTERS = {
    "c06_06": {"id":"c06_06","nombre":"Hormonas Suprarrenales","unidadId":"u06","drugIds":[]},
    "c06_07": {"id":"c06_07","nombre":"Fármacos para Metabolismo Óseo-Mineral","unidadId":"u06","drugIds":[]},
    "c06_08": {"id":"c06_08","nombre":"Fármacos para Obesidad","unidadId":"u06","drugIds":[]},
    "c06_09": {"id":"c06_09","nombre":"Análogos y Antagonistas Hormonales","unidadId":"u06","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U06 ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u06", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
