#!/usr/bin/env python3
"""Final supplement: U01 (+15), U05 (+12), U06 (+12), U07 (+12), U08 (+10), U09 (+10) = ~71 drugs."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

# ══════════════════════════════════════════════════════════════════════
# U01 — SISTEMA NERVIOSO (+15)
# ══════════════════════════════════════════════════════════════════════

u01_drugs = [
    M("opioide", "oxicodona_naloxona", "Oxicodona/Naloxona", "oxicodona + naloxona",
      ["Targin", "Oxynal"], "Opioide + antagonista periférico para estreñimiento",
      "Oxicodona: agonista mu central; Naloxona oral: antagoniza receptores opioides intestinales reduciendo estreñimiento",
      ["Dolor crónico severo", "Dolor oncológico con estreñimiento inducido por opioides"],
      ["Oral"], "10/5 mg c/12h; titular según dolor (máx 80/40 mg/día)",
      ["Tab LP 5/2.5 mg", "Tab LP 10/5 mg", "Tab LP 20/10 mg", "Tab LP 40/20 mg"], "Contraindicada",
      "u01", "c01_01"),

    M("opioide", "buprenorfina_parche", "Buprenorfina Transdérmica", "buprenorfina",
      ["Transtec", "BuTrans"], "Opioide agonista parcial mu transdérmico",
      "Agonista parcial mu y antagonista kappa; liberación transdérmica continua durante 7 días",
      ["Dolor crónico moderado-severo", "Dolor oncológico", "Dolor no oncológico cuando opioides orales no son factibles"],
      ["Transdérmica"], "Inicio: 5-10 mcg/h; titular cada 72h; cambiar parche cada 7 días",
      ["Parche 5 mcg/h", "Parche 10 mcg/h", "Parche 20 mcg/h", "Parche 35 mcg/h"], "Evitar",
      "u01", "c01_01",
      ce=["Rotar sitio de aplicación", "No aplicar sobre piel irritada o lesionada", "No exponer a calor (baños, saunas)", "Retirar parche anterior antes de aplicar nuevo", "Efecto techo en dosis altas"]),

    M("anticonvulsivante", "stiripentol", "Estiripentol detallado", "estiripentol",
      ["Diacomit detallado"], "Anticonvulsivante para síndrome de Dravet",
      "Potencia transmisión GABAérgica; inhibe CYP450 aumentando niveles de clobazam y valproato",
      ["Síndrome de Dravet (con clobazam y valproato)", "Epilepsias severas de la infancia"],
      ["Oral"], {"pediatrico": "50 mg/kg/día dividido c/8h (con alimentos)"},
      ["Cáps 250 mg", "Cáps 500 mg", "Polvo 250 mg", "Polvo 500 mg"], "Contraindicada",
      "u01", "c01_02"),

    M("anticonvulsivante", "everolimus_epilepsia", "Everolimús (Epilepsia)", "everolimús",
      ["Votubia"], "Inhibidor de mTOR para epilepsia refractaria en CET",
      "Inhibe mTOR reduciendo crecimiento de tuberosidades y actividad epileptógena",
      ["Epilepsia refractaria asociada a complejo esclerosis tuberosa (CET)", "SEGA asociado a CET"],
      ["Oral"], {"pediatrico": "Según superficie corporal y nivel sérico; objetivo: 5-15 ng/mL"},
      ["Tab 2.5 mg", "Tab 5 mg", "Tab dispersable 2 mg", "Tab dispersable 3 mg"], "Contraindicada",
      "u01", "c01_02",
      familia="Inhibidores de mTOR",
      emb="X"),

    M("antipsicotico", "brexpiprazol_detalle", "Brexpiprazol detallado", "brexpiprazol",
      ["Rexulti detallado"], "Antipsicótico atípico agonista parcial D2/5-HT1A",
      "Agonista parcial D2 y 5-HT1A con antagonismo 5-HT2A; perfil metabólico más favorable",
      ["Esquizofrenia", "Tratamiento adjunto en depresión mayor", "Agitación en Alzheimer"],
      ["Oral"], "Esquizofrenia: 2-4 mg/día; Depresión: 0.5-3 mg/día adjunto",
      ["Tab 0.25 mg", "Tab 0.5 mg", "Tab 1 mg", "Tab 2 mg", "Tab 3 mg", "Tab 4 mg"], "Evitar",
      "u01", "c01_04"),

    M("antipsicotico", "pimavanserin", "Pimavanserin", "pimavanserin",
      ["Nuplazid"], "Agonista inverso selectivo 5-HT2A",
      "Agonista inverso/antagonista selectivo de receptores 5-HT2A sin afinidad por dopamina",
      ["Psicosis asociada a enfermedad de Parkinson"],
      ["Oral"], "34 mg/día",
      ["Tab 34 mg", "Cáps 34 mg"], "Evitar",
      "u01", "c01_04",
      ci=["Hipersensibilidad", "Prolongación QT significativa"],
      ea=["Edema periférico", "Confusión", "Alucinaciones paradójicas", "Náuseas", "Prolongación QT"],
      ix=["Inhibidores CYP3A4: reducir dosis", "Fármacos que prolongan QT: riesgo arritmia"],
      ce=["Primer antipsicótico sin bloqueo dopaminérgico", "No empeora síntomas motores del Parkinson", "ECG basal", "No usar con inhibidores CYP3A4 potentes"]),

    M("antidepresivo_isrs", "venlafaxina_xr", "Venlafaxina XR detallado", "venlafaxina",
      ["Effexor XR detallado"], "ISRSN de liberación prolongada",
      "Inhibe recaptación de serotonina y norepinefrina; a dosis altas también dopamina",
      ["Depresión mayor", "Trastorno de ansiedad generalizada", "Trastorno de ansiedad social", "Trastorno de pánico"],
      ["Oral"], "Inicio: 37.5-75 mg/día; Mantenimiento: 150-225 mg/día; Máx: 375 mg/día",
      ["Cáps LP 37.5 mg", "Cáps LP 75 mg", "Cáps LP 150 mg"], "Evitar",
      "u01", "c01_03"),

    M("benzodiacepina", "clobazam_detalle", "Clobazam detallado", "clobazam",
      ["Frisium detallado"], "1,5-benzodiazepina antiepiléptica",
      "Benzodiazepina con selectividad parcial por receptores GABA-A α2 (menos sedación)",
      ["Epilepsia refractaria como adjunto", "Síndrome de Lennox-Gastaut", "Síndrome de Dravet"],
      ["Oral"], {"adulto": "10-40 mg/día dividido c/12h", "pediatrico": "0.5-1 mg/kg/día"},
      ["Tab 5 mg", "Tab 10 mg", "Tab 20 mg", "Susp 1 mg/mL"], "Evitar",
      "u01", "c01_02"),

    M("antiparkinsoniano", "opicapona_detalle", "Opicapona detallado", "opicapona",
      ["Ongentys detallado"], "Inhibidor de COMT de 3ª generación",
      "Inhibe COMT periférica de larga duración; una dosis diaria; sin hepatotoxicidad de tolcapona",
      ["Fluctuaciones motoras en Parkinson (adjunto a levodopa)"],
      ["Oral"], "50 mg/día al acostarse (1h antes o después de levodopa)",
      ["Cáps 50 mg"], "Evitar",
      "u01", "c01_05",
      ea=["Discinesias (por aumento de levodopa)", "Insomnio", "Boca seca", "Mareo", "Estreñimiento", "Coloración anaranjada de orina"],
      ce=["Tomar 1h antes o después de levodopa", "Puede requerir reducción de dosis de levodopa", "No requiere monitorización hepática (a diferencia de tolcapona)", "Dosis única nocturna"]),

    M("antiparkinsoniano", "foslevodopa_foscarbidopa", "Foslevodopa/Foscarbidopa", "foslevodopa + foscarbidopa",
      ["Produodopa"], "Infusión SC continua de levodopa",
      "Profármacos de levodopa/carbidopa para infusión subcutánea continua 24h",
      ["Parkinson avanzado con fluctuaciones motoras severas (alternativa a infusión intestinal)"],
      ["Subcutánea"], "Infusión SC continua 24h por bomba; dosis individualizada según equivalente oral",
      ["Casete 240/12 mL para bomba"], "Evitar",
      "u01", "c01_05",
      familia="Antiparkinsonianos de infusión continua",
      ci=["Hipersensibilidad", "Uso de IMAO no selectivo"],
      ea=["Nódulos/reacciones en sitio de infusión", "Discinesias", "Caídas", "Alucinaciones"],
      ce=["Rotar sitios de infusión SC", "Vigilar nódulos subcutáneos", "Bomba programable 24h", "Alternativa menos invasiva que Duodopa intestinal"]),

    M("esclerosis_multiple", "ofatumumab_em", "Ofatumumab (EM)", "ofatumumab",
      ["Kesimpta"], "Anti-CD20 subcutáneo para EM",
      "Anticuerpo monoclonal anti-CD20 que depleciona linfocitos B; administración SC mensual",
      ["Esclerosis múltiple recurrente activa"],
      ["Subcutánea"], "20 mg SC semanas 0, 1, 2 (carga); luego 20 mg SC mensual",
      ["Jer precargada 20 mg/0.4 mL"], "Contraindicada",
      "u01", "c01_07"),

    M("esclerosis_multiple", "ponesimod", "Ponesimod", "ponesimod",
      ["Ponvory"], "Modulador selectivo del receptor S1P1",
      "Agonista selectivo de S1P1 que secuestra linfocitos en ganglios linfáticos reduciendo infiltración al SNC",
      ["Esclerosis múltiple recurrente"],
      ["Oral"], "Titulación gradual 14 días hasta 20 mg/día de mantenimiento",
      ["Pack de inicio (2-10 mg)", "Tab 20 mg mantenimiento"], "Contraindicada",
      "u01", "c01_07",
      ci=["Hipersensibilidad", "IAM reciente", "IC descompensada", "Bloqueo AV tipo 2 sin marcapasos"],
      ea=["Linfopenia", "Infecciones", "Bradicardia al inicio", "Edema macular", "Cefalea", "Elevación transaminasas"],
      ce=["ECG pre-inicio y monitorización 4h tras primera dosis", "Examen oftalmológico pre-inicio", "Hemograma con linfocitos antes de iniciar", "Titulación gradual obligatoria x14 días"]),

    M("anticonvulsivante", "ganaxolona", "Ganaxolona", "ganaxolona",
      ["Ztalmy"], "Neuroesteroide modulador GABA-A",
      "Análogo sintético de alopregnanolona; modulador alostérico positivo de receptores GABA-A",
      ["Crisis epilépticas asociadas al síndrome CDKL5"],
      ["Oral"], {"pediatrico": "Inicio: 6 mg/kg c/8h; titular hasta 15 mg/kg c/8h (máx 1800 mg/día)"},
      ["Susp 50 mg/mL"], "Evitar",
      "u01", "c01_02",
      familia="Neuroesteroides anticonvulsivantes"),

    M("opioide", "naldemedina", "Naldemedina", "naldemedina",
      ["Symproic", "Rizmoic"], "Antagonista periférico de receptores opioides mu",
      "Antagoniza receptores mu en tracto GI sin cruzar BHE ni revertir analgesia central",
      ["Estreñimiento inducido por opioides en pacientes con dolor crónico no oncológico"],
      ["Oral"], "0.2 mg/día",
      ["Tab 0.2 mg"], "Evitar",
      "u01", "c01_01",
      familia="Antagonistas opioides periféricos (PAMORA)",
      ci=["Obstrucción GI mecánica", "Hipersensibilidad"],
      ea=["Dolor abdominal", "Diarrea", "Náuseas", "Gastroenteritis"],
      ce=["No interfiere con analgesia opioide central", "Puede suspenderse si se suspende opioide", "Administrar sin relación con alimentos"]),

    M("opioide", "metilnaltrexona", "Metilnaltrexona", "metilnaltrexona",
      ["Relistor"], "Antagonista periférico mu opioide SC/oral",
      "Antagonista mu que no cruza BHE; restaura motilidad GI sin revertir analgesia",
      ["Estreñimiento inducido por opioides en cuidados paliativos", "EIO en dolor crónico no oncológico"],
      ["Subcutánea", "Oral"], "SC: 8-12 mg c/48h según peso; Oral: 450 mg/día",
      ["Jer 8 mg/0.4 mL SC", "Jer 12 mg/0.6 mL SC", "Tab 150 mg"], "Evitar",
      "u01", "c01_01",
      familia="Antagonistas opioides periféricos (PAMORA)"),
]

# ══════════════════════════════════════════════════════════════════════
# U05 — DIGESTIVO (+12)
# ══════════════════════════════════════════════════════════════════════

u05_drugs = [
    M("ibp", "vonoprazan_detalle", "Vonoprazán detallado", "vonoprazán",
      ["Voquezna detallado"], "Bloqueador ácido competitivo de potasio (P-CAB)",
      "Inhibe H+/K+-ATPasa de forma competitiva con el potasio; acción más rápida y sostenida que IBP",
      ["Erradicación de H. pylori", "Esofagitis erosiva", "ERGE"],
      ["Oral"], "20 mg c/12h (erradicación); 10-20 mg/día (mantenimiento ERGE)",
      ["Tab 10 mg", "Tab 20 mg"], "Evitar",
      "u05", "c05_01"),

    M("antiemetico", "alizaprida", "Alizaprida", "alizaprida",
      ["Plitican", "Vergentan"], "Antiemético benzamida",
      "Antagonista D2 con menor riesgo de efectos extrapiramidales que metoclopramida",
      ["Náuseas y vómitos postoperatorios", "Náuseas por quimioterapia"],
      ["Intramuscular", "Intravenosa", "Oral"], "50-100 mg c/8h IM/IV; 50 mg c/8h oral",
      ["Amp 50 mg/2 mL", "Tab 50 mg"], "Evitar",
      "u05", "c05_02",
      familia="Antieméticos benzamidas"),

    M("ibp", "tenatoprazol", "Tenatoprazol", "tenatoprazol",
      ["Tenatoprazol"], "IBP imidazopiridina de vida media ultra-larga",
      "Inhibe H+/K+-ATPasa con vida media de ~7h (vs 1h de otros IBP); supresión ácida sostenida",
      ["ERGE refractaria", "Síndrome Zollinger-Ellison", "Esofagitis erosiva severa"],
      ["Oral"], "40 mg/día",
      ["Tab 40 mg"], "Evitar",
      "u05", "c05_01"),

    M("antiemetico", "netupitant_palonos_detalle", "Netupitant/Palonosetrón detallado", "netupitant + palonosetrón",
      ["Akynzeo detallado"], "Antiemético dual NK1 + 5-HT3",
      "Netupitant bloquea NK1 (emesis tardía); Palonosetrón bloquea 5-HT3 (emesis aguda)",
      ["Prevención de náuseas y vómitos por quimioterapia altamente emetógena"],
      ["Oral", "Intravenosa"], "Oral: 1 cápsula 1h pre-QT; IV: infusión 30 min pre-QT",
      ["Cáps 300/0.5 mg", "Fco IV 235/0.25 mg"], "Evitar",
      "u05", "c05_02"),

    M("ibp", "ilaprazol", "Ilaprazol", "ilaprazol",
      ["Noltec", "Adiza"], "IBP de nueva generación",
      "Inhibe H+/K+-ATPasa con metabolismo independiente de CYP2C19 (menos variabilidad interindividual)",
      ["Úlcera péptica", "ERGE", "Erradicación de H. pylori"],
      ["Oral"], "10-20 mg/día",
      ["Tab 5 mg", "Tab 10 mg"], "Evitar",
      "u05", "c05_01"),

    M("antiemetico", "rolapitant_detalle", "Rolapitant detallado", "rolapitant",
      ["Varuby detallado"], "Antagonista NK1 de acción ultra-larga",
      "Bloquea receptor NK1 de sustancia P; vida media de ~180h permite dosis única por ciclo",
      ["Prevención de náuseas tardías por quimioterapia moderada/altamente emetógena"],
      ["Oral"], "180 mg dosis única 1-2h pre-quimioterapia",
      ["Tab 90 mg x2"], "Evitar",
      "u05", "c05_02",
      ci=["Uso con tioridazina", "Hipersensibilidad"],
      ea=["Cefalea", "Hipo", "Dispepsia", "Neutropenia"],
      ce=["Dosis única por ciclo de QT (no repetir)", "Inhibidor de CYP2D6: vigilar interacciones", "Efecto persiste varios días", "Administrar con corticoide y anti-5-HT3"]),

    M("ibp", "esomeprazol_iv_detalle", "Esomeprazol IV", "esomeprazol sódico",
      ["Nexium IV detallado"], "IBP intravenoso",
      "S-isómero de omeprazol IV; para pacientes que no pueden recibir IBP oral",
      ["Hemorragia digestiva alta", "Esofagitis erosiva severa", "Profilaxis de úlcera de estrés en UCI"],
      ["Intravenosa"], "HDA: bolo 80 mg + infusión 8 mg/h x72h; Profilaxis: 20-40 mg c/24h",
      ["Fco 40 mg liofilizado"], "Evitar",
      "u05", "c05_01",
      pp={"dilucion": "En 100 mL SF o SG5%", "velocidadAdministracion": "Bolo en 3 min; Infusión 8 mg/h", "estabilidad": "12h a temperatura ambiente"}),

    M("antiemetico", "trimethobenzamida_detalle", "Trimetobenzamida detallado", "trimetobenzamida",
      ["Tigan detallado"], "Antiemético derivado de benzamida",
      "Actúa en zona gatillo quimiorreceptora sin bloqueo dopaminérgico significativo",
      ["Náuseas y vómitos postoperatorios", "Náuseas asociadas a gastroenteritis"],
      ["Intramuscular", "Oral"], "IM: 200 mg c/6-8h; Oral: 300 mg c/6-8h",
      ["Cáps 300 mg", "Amp 200 mg/2 mL"], "Evitar",
      "u05", "c05_02"),

    M("ibp", "pantoprazol_iv_detalle", "Pantoprazol IV detallado", "pantoprazol sódico",
      ["Controloc IV detallado"], "IBP intravenoso para HDA y úlcera estrés",
      "Inhibe irreversiblemente bomba de protones gástrica; formulación IV para uso hospitalario",
      ["HDA por úlcera péptica", "Profilaxis úlcera de estrés en UCI", "Síndrome Zollinger-Ellison"],
      ["Intravenosa"], "HDA: bolo 80 mg + infusión 8 mg/h x72h; Profilaxis: 40 mg c/12-24h",
      ["Fco 40 mg liofilizado"], "Evitar",
      "u05", "c05_01",
      pp={"dilucion": "En 10-100 mL SF o SG5%", "velocidadAdministracion": "Bolo en 2-15 min; Infusión 8 mg/h", "estabilidad": "12h a temperatura ambiente"}),

    M("antiemetico", "scopolamina_transdermica", "Escopolamina Transdérmica", "escopolamina",
      ["Scopoderm TTS", "Transderm Scop"], "Anticolinérgico transdérmico antiemético",
      "Bloquea receptores muscarínicos en centro del vómito y núcleos vestibulares",
      ["Cinetosis (mareo por movimiento)", "Náuseas postoperatorias (prevención)"],
      ["Transdérmica"], "1 parche retroauricular c/72h (aplicar 4h antes de viaje o noche previa a cirugía)",
      ["Parche 1.5 mg (libera 1 mg/72h)"], "Evitar",
      "u05", "c05_02",
      familia="Anticolinérgicos transdérmicos",
      ci=["Glaucoma de ángulo cerrado", "Obstrucción GI/urinaria", "Miastenia gravis"],
      ea=["Boca seca", "Somnolencia", "Visión borrosa", "Retención urinaria", "Confusión en ancianos"],
      ce=["Aplicar detrás de la oreja en piel seca", "Lavarse manos después de manipular parche", "No cortar el parche", "Retirar antes de RM"]),

    M("antiemetico", "olanzapina_antiemetica", "Olanzapina Antiemética", "olanzapina",
      ["Zyprexa Antiemético"], "Antipsicótico como antiemético en quimioterapia",
      "Bloqueo multirrreceptor (D2, 5-HT3, NK1, H1, M) con potente efecto antiemético",
      ["Prevención de NVIQ altamente emetógena (cuádruple terapia)", "NVIQ irruptivas refractarias"],
      ["Oral"], "10 mg/día x3-4 días con cada ciclo de QT",
      ["Tab 5 mg", "Tab 10 mg"], "Evitar",
      "u05", "c05_02",
      familia="Antieméticos atípicos",
      ea=["Sedación", "Aumento de peso", "Hiperglucemia", "Fatiga"],
      ce=["Usar como parte de régimen cuádruple (con NK1 + 5-HT3 + dexa)", "Advertir sobre sedación", "Vigilar glucemia en diabéticos", "Solo uso corto (3-4 días por ciclo)"]),

    M("ibp", "tegoprazan_detalle", "Tegoprazán detallado", "tegoprazán",
      ["K-CAB detallado"], "P-CAB de segunda generación",
      "Bloquea H+/K+-ATPasa competitivamente con K+; acción rápida y sostenida sin activación ácida previa",
      ["ERGE erosiva y no erosiva", "Úlcera péptica", "Erradicación H. pylori"],
      ["Oral"], "50 mg/día (ERGE); 50 mg c/12h (erradicación H. pylori)",
      ["Tab 50 mg"], "Evitar",
      "u05", "c05_01"),
]

# ══════════════════════════════════════════════════════════════════════
# U06 — ENDOCRINO (+12)
# ══════════════════════════════════════════════════════════════════════

u06_drugs = [
    M("insulina", "insulina_icodec", "Insulina Icodec", "insulina icodec",
      ["Awiqli"], "Insulina basal de una dosis semanal",
      "Análogo de insulina con unión a albúmina que prolonga acción a ~1 semana completa",
      ["Diabetes tipo 2 que requiere insulina basal"],
      ["Subcutánea"], "Individualizada; equivalente semanal = dosis diaria basal × 7",
      ["Pluma 700 UI/mL x1.5 mL", "Pluma 700 UI/mL x3 mL"], "Evitar",
      "u06", "c06_01",
      ce=["Una inyección semanal el mismo día cada semana", "Transición desde insulina diaria: primera dosis icodec + última dosis de insulina diaria", "Monitorizar glucemia durante transición", "Rotar sitios de inyección"]),

    M("antidiabetico_oral", "imeglimina", "Imeglimina", "imeglimina",
      ["Twymeeg"], "Antidiabético oral con mecanismo dual mitocondrial",
      "Mejora función de célula beta y sensibilidad a insulina actuando sobre mitocondrias",
      ["Diabetes tipo 2 (monoterapia o combinación)"],
      ["Oral"], "1000 mg c/12h",
      ["Tab 500 mg"], "Evitar",
      "u06", "c06_01",
      familia="Gliminas"),

    M("corticoide_sistemico", "osilodrostat_detalle", "Osilodrostat detallado", "osilodrostat",
      ["Isturisa detallado"], "Inhibidor de 11β-hidroxilasa",
      "Inhibe CYP11B1 (11β-hidroxilasa) reduciendo síntesis de cortisol",
      ["Síndrome de Cushing endógeno cuando cirugía no es factible"],
      ["Oral"], "Inicio: 2 mg c/12h; titular según cortisol libre urinario (máx 30 mg c/12h)",
      ["Tab 1 mg", "Tab 5 mg", "Tab 10 mg"], "Contraindicada",
      "u06", "c06_03",
      familia="Inhibidores de síntesis de cortisol",
      ci=["Hipersensibilidad", "Insuficiencia adrenal", "Prolongación QT"],
      ea=["Insuficiencia adrenal", "Prolongación QT", "Hipocortisismo", "Náuseas", "Cefalea", "Hirsutismo"],
      ce=["Cortisol libre urinario cada 1-2 semanas durante titulación", "ECG basal y periódico", "Tener hidrocortisona de rescate disponible", "Vigilar signos de insuficiencia adrenal"]),

    M("antidiabetico_oral", "sotagliflozina", "Sotagliflozina", "sotagliflozina",
      ["Zynquista"], "Inhibidor dual SGLT1/SGLT2",
      "Inhibe SGLT1 intestinal (reduce absorción glucosa) y SGLT2 renal (glucosuria)",
      ["Diabetes tipo 1 como adjunto a insulina", "Insuficiencia cardíaca", "Diabetes tipo 2"],
      ["Oral"], "200-400 mg/día antes del desayuno",
      ["Tab 200 mg", "Tab 400 mg"], "Evitar",
      "u06", "c06_01",
      familia="Inhibidores SGLT1/SGLT2",
      ea=["Cetoacidosis diabética (incluso euglucémica)", "Diarrea (efecto SGLT1)", "ITU", "Hipoglucemia", "Depleción de volumen"],
      ce=["Mayor riesgo de CAD que iSGLT2 puros", "Suspender 3 días antes de cirugía", "Monitorizar cetonas si síntomas", "Reducir dosis de insulina al iniciar"]),

    M("corticoide_sistemico", "pasireotida_detalle", "Pasireótida detallado", "pasireótida",
      ["Signifor detallado"], "Análogo de somatostatina multirrreceptor",
      "Se une a receptores SST1,2,3,5 (mayor afinidad SST5); inhibe secreción de ACTH y GH",
      ["Enfermedad de Cushing", "Acromegalia refractaria a octreótida/lanreótida"],
      ["Subcutánea", "Intramuscular"], "Cushing SC: 0.6-0.9 mg c/12h; Acromegalia IM: 40-60 mg c/28 días",
      ["Amp 0.3 mg SC", "Amp 0.6 mg SC", "Amp 0.9 mg SC", "Fco 20 mg IM LP", "Fco 40 mg IM LP", "Fco 60 mg IM LP"],
      "Contraindicada",
      "u06", "c06_03",
      familia="Análogos de somatostatina",
      ea=["Hiperglucemia significativa", "Diarrea", "Colelitiasis", "Náuseas", "Cefalea", "Dolor abdominal"],
      ce=["Monitorizar glucemia intensivamente (alto riesgo hiperglucemia)", "Ecografía biliar cada 6-12 meses", "Puede requerir inicio de antidiabéticos", "HbA1c cada 3 meses"]),

    M("corticoide_sistemico", "lenzilumab", "Relacorilant", "relacorilant",
      ["Korlym-next"], "Antagonista selectivo del receptor glucocorticoide",
      "Bloquea selectivamente receptor glucocorticoide sin efecto antiprogestágeno",
      ["Síndrome de Cushing con hiperglucemia (alternativa a mifepristona)"],
      ["Oral"], "100-400 mg/día",
      ["Tab 100 mg", "Tab 200 mg"], "Contraindicada",
      "u06", "c06_03",
      familia="Antagonistas del receptor glucocorticoide",
      emb="X"),

    M("antidiabetico_oral", "tirzepatida_detalle2", "Tirzepatida (Obesidad)", "tirzepatida",
      ["Zepbound"], "Agonista dual GIP/GLP-1 para obesidad",
      "Estimula receptores GIP y GLP-1: reduce apetito, enlentece vaciado gástrico, mejora saciedad",
      ["Obesidad (IMC ≥30) o sobrepeso (IMC ≥27 con comorbilidad)"],
      ["Subcutánea"], "Inicio: 2.5 mg SC semanal x4 sem; titular cada 4 sem: 5→7.5→10→12.5→15 mg",
      ["Pluma 2.5 mg", "Pluma 5 mg", "Pluma 7.5 mg", "Pluma 10 mg", "Pluma 12.5 mg", "Pluma 15 mg"],
      "Contraindicada",
      "u06", "c06_05",
      familia="Agonistas duales GIP/GLP-1",
      emb="X",
      ci=["NEM2 o antecedente de carcinoma medular tiroideo", "Embarazo", "Hipersensibilidad"],
      ea=["Náuseas", "Diarrea", "Vómitos", "Estreñimiento", "Dolor abdominal", "Pancreatitis (raro)"],
      ce=["Titular gradualmente para tolerancia GI", "Anticoncepción durante y 2 meses post-tratamiento", "Puede reducir absorción de anticonceptivos orales", "Monitorizar por pancreatitis"]),

    M("antidiabetico_oral", "semaglutida_oral_detalle", "Semaglutida Oral detallado", "semaglutida",
      ["Rybelsus detallado"], "Agonista GLP-1 oral (primera formulación oral de GLP-1RA)",
      "Péptido GLP-1 con potenciador de absorción SNAC para administración oral",
      ["Diabetes tipo 2 como adjunto a dieta/ejercicio"],
      ["Oral"], "Inicio: 3 mg/día x30 días; luego 7 mg/día; puede aumentar a 14 mg/día",
      ["Tab 3 mg", "Tab 7 mg", "Tab 14 mg"], "Evitar",
      "u06", "c06_01",
      familia="Agonistas GLP-1 orales",
      ci=["NEM2 o carcinoma medular tiroideo", "Hipersensibilidad"],
      ea=["Náuseas", "Diarrea", "Dolor abdominal", "Disminución de apetito", "Retinopatía (en DM2 con retinopatía preexistente)"],
      ce=["Tomar en ayunas con ≤120 mL de agua", "Esperar ≥30 min antes de comer o tomar otros medicamentos", "No partir, triturar ni masticar", "Menor absorción si no se siguen instrucciones"]),

    M("corticoide_sistemico", "pegvisomant_detalle", "Pegvisomant detallado", "pegvisomant",
      ["Somavert detallado"], "Antagonista del receptor de GH",
      "Análogo de GH modificado que bloquea receptor de GH impidiendo dimerización y señalización",
      ["Acromegalia refractaria a cirugía y análogos de somatostatina"],
      ["Subcutánea"], "Carga: 40 mg SC; Mantenimiento: 10-30 mg SC diario (titular según IGF-1)",
      ["Fco 10 mg", "Fco 15 mg", "Fco 20 mg", "Fco 25 mg", "Fco 30 mg"], "Evitar",
      "u06", "c06_03",
      familia="Antagonistas del receptor GH",
      ea=["Elevación transaminasas", "Lipodistrofia en sitio inyección", "Cefalea", "Crecimiento tumoral hipofisario (teórico)"],
      ce=["IGF-1 cada 4-6 semanas durante titulación", "Función hepática mensual primeros 6 meses", "RM hipófisis cada 6 meses primer año", "Rotar sitios de inyección"]),

    M("antidiabetico_oral", "bexagliflozina", "Bexagliflozina", "bexagliflozina",
      ["Brenzavvy"], "Inhibidor de SGLT2",
      "Inhibe cotransportador SGLT2 en túbulo proximal reduciendo reabsorción renal de glucosa",
      ["Diabetes tipo 2 como adjunto a dieta/ejercicio"],
      ["Oral"], "20 mg/día",
      ["Tab 20 mg"], "Evitar",
      "u06", "c06_01"),

    M("insulina", "insulina_glargina_lixisenatida", "Insulina Glargina/Lixisenatida", "insulina glargina + lixisenatida",
      ["Soliqua"], "Combinación insulina basal + agonista GLP-1 en misma pluma",
      "Glargina: insulina basal 24h; Lixisenatida: agonista GLP-1 que reduce glucemia postprandial",
      ["DM2 no controlada con insulina basal o GLP-1RA solos"],
      ["Subcutánea"], "15-60 unidades/día (1 unidad = 1 UI glargina + 0.33-1 mcg lixisenatida)",
      ["Pluma 100/33 (15-40 UI)", "Pluma 100/50 (30-60 UI)"], "Evitar",
      "u06", "c06_01",
      familia="Combinación insulina/GLP-1"),
]

# ══════════════════════════════════════════════════════════════════════
# U07 — REPRODUCTOR Y ÓSEO (+12)
# ══════════════════════════════════════════════════════════════════════

u07_drugs = [
    M("anticonceptivo_hormonal", "segesterona_etinilestradiol", "Anillo Vaginal Segesterona/EE", "segesterona + etinilestradiol",
      ["Annovera"], "Anillo vaginal anticonceptivo reutilizable por 1 año",
      "Libera segesterona y etinilestradiol continuamente; anillo reutilizable por 13 ciclos",
      ["Anticoncepción (1 año con mismo anillo)"],
      ["Vaginal"], "Insertar x21 días, retirar x7 días; repetir x13 ciclos",
      ["Anillo vaginal (1 año)"], "Contraindicada",
      "u07", "c07_01"),

    M("anticonceptivo_hormonal", "drospirenona_sola", "Drospirenona Sola", "drospirenona",
      ["Slynd", "Slinda"], "Progestágeno solo oral continuo",
      "Inhibe ovulación como mecanismo primario (a diferencia de otros POP); 24/4 régimen",
      ["Anticoncepción (especialmente cuando estrógenos contraindicados)"],
      ["Oral"], "4 mg c/24h (24 comprimidos activos + 4 placebo)",
      ["Comp 4 mg x28 (24+4)"], "No aplica",
      "u07", "c07_01",
      ci=["Insuficiencia renal", "Insuficiencia adrenal", "Insuficiencia hepática grave", "Hiperpotasemia"],
      ea=["Sangrado irregular", "Acné", "Cefalea", "Náuseas", "Tensión mamaria"],
      ce=["Tomar a la misma hora cada día", "Ventana de olvido de 24h (más amplia que otros POP)", "No requiere método de respaldo si olvido <24h", "Vigilar potasio si uso con diuréticos ahorradores"]),

    M("anticonceptivo_hormonal", "etonogestrel_implante_det", "Etonogestrel Implante detallado", "etonogestrel",
      ["Nexplanon detallado"], "Implante anticonceptivo subdérmico radiopaco",
      "Libera etonogestrel continuamente x3 años; suprime ovulación y espesa moco cervical",
      ["Anticoncepción de larga duración (hasta 3 años)"],
      ["Subdérmica"], "1 implante subdérmico en brazo no dominante; efectivo x3 años",
      ["Implante 68 mg (1 varilla)"], "No aplica (in situ)",
      "u07", "c07_01",
      ce=["Inserción por personal entrenado con aplicador específico", "Verificar palpabilidad post-inserción", "Es radiopaco (localizable por Rx)", "Fertilidad retorna rápidamente tras retiro"]),

    M("anticonceptivo_hormonal", "diu_levonorgestrel_52", "DIU-LNG 52 mg", "levonorgestrel intrauterino",
      ["Mirena", "Liletta"], "DIU con levonorgestrel de alta dosis",
      "Libera LNG localmente: atrofia endometrial, espesa moco cervical; efecto anticonceptivo x5-8 años",
      ["Anticoncepción (hasta 8 años)", "Menorragia/sangrado uterino abundante", "Protección endometrial en TRH"],
      ["Intrauterina"], "52 mg; libera ~20 mcg/día inicialmente; efectivo 5-8 años",
      ["DIU 52 mg"], "Compatible (liberación local)",
      "u07", "c07_01",
      ci=["Infección pélvica activa", "Anomalía uterina", "Embarazo", "Cáncer cervical o endometrial"],
      ea=["Sangrado irregular primeros 3-6 meses", "Amenorrea (50% al año)", "Quistes ováricos funcionales", "Cefalea"],
      ce=["Inserción durante menstruación o post-parto", "Ecografía para confirmar posición", "Amenorrea es efecto esperado (no complicación)", "Controles a 4-6 sem post-inserción"]),

    M("anticonceptivo_hormonal", "ulipristal_anticoncepcion", "Ulipristal Anticoncepción Emergencia", "ulipristal acetato",
      ["EllaOne"], "Anticonceptivo de emergencia",
      "Modulador selectivo del receptor de progesterona; retrasa o inhibe ovulación incluso pre-ovulación",
      ["Anticoncepción de emergencia hasta 120h (5 días) post-coito"],
      ["Oral"], "30 mg dosis única lo antes posible (eficaz hasta 120h)",
      ["Tab 30 mg"], "Contraindicada",
      "u07", "c07_01",
      ci=["Embarazo confirmado", "Asma severa con corticoides orales"],
      ea=["Cefalea", "Náuseas", "Dolor abdominal", "Sangrado irregular", "Fatiga"],
      ce=["Más eficaz que levonorgestrel después de 72h", "Eficaz hasta 120h post-coito", "Puede retrasar siguiente menstruación", "Si vómito en 3h: repetir dosis"]),

    # ── Osteoporosis ──
    M("corticoide_sistemico", "romosozumab_detalle", "Romosozumab detallado", "romosozumab",
      ["Evenity detallado"], "Anticuerpo anti-esclerostina",
      "Inhibe esclerostina estimulando formación ósea por osteoblastos y reduciendo resorción",
      ["Osteoporosis posmenopáusica severa con alto riesgo de fractura"],
      ["Subcutánea"], "210 mg SC mensual (2 inyecciones de 105 mg) x12 meses",
      ["Jer 105 mg/1.17 mL x2 por dosis"], "Contraindicada",
      "u07", "c07_06",
      familia="Anticuerpos anti-esclerostina",
      ci=["Hipocalcemia", "IAM o ACV en último año", "Hipersensibilidad"],
      ea=["Artralgia", "Cefalea", "Reacciones en sitio inyección", "Hipocalcemia", "Riesgo cardiovascular (IAM, ACV)"],
      ce=["Normalizar calcio y vitamina D antes de iniciar", "Máximo 12 meses consecutivos", "Transicionar a antirresortivo (denosumab/bisfosfonato) después", "Vigilar síntomas cardiovasculares"]),

    M("corticoide_sistemico", "denosumab_osteo", "Denosumab (Osteoporosis)", "denosumab",
      ["Prolia"], "Anti-RANKL para osteoporosis",
      "Anticuerpo monoclonal contra RANKL que inhibe diferenciación y actividad de osteoclastos",
      ["Osteoporosis posmenopáusica", "Osteoporosis en hombres", "Osteoporosis por glucocorticoides"],
      ["Subcutánea"], "60 mg SC cada 6 meses",
      ["Jer 60 mg/mL"], "Evitar",
      "u07", "c07_06",
      familia="Anticuerpos anti-RANKL",
      ci=["Hipocalcemia no corregida", "Hipersensibilidad"],
      ea=["Dolor musculoesquelético", "Hipocalcemia", "Infecciones cutáneas", "Osteonecrosis mandibular (raro)", "Fractura femoral atípica (raro)"],
      ce=["Suplementar calcio + vitamina D", "NO suspender sin transicionar a bisfosfonato (rebote)", "Evaluación dental antes de iniciar", "Cada 6 meses estricto (no retrasar)"]),

    # ── Fertilidad ──
    M("anticonceptivo_hormonal", "cetrorelix_detalle", "Cetrorelix detallado", "cetrorelix",
      ["Cetrotide detallado"], "Antagonista de GnRH para reproducción asistida",
      "Bloquea receptores de GnRH en hipófisis suprimiendo rápidamente LH y FSH; previene ovulación prematura",
      ["Prevención de pico prematuro de LH en FIV", "Reproducción asistida"],
      ["Subcutánea"], "0.25 mg SC diario desde día 5-6 de estimulación hasta día de hCG",
      ["Fco 0.25 mg + jeringa"], "Contraindicada",
      "u07", "c07_02"),

    # ── Salud ósea ──
    M("corticoide_sistemico", "acido_zoledronico_anual", "Ácido Zoledrónico Anual", "ácido zoledrónico",
      ["Aclasta", "Reclast"], "Bisfosfonato IV de administración anual",
      "Inhibe farnesil pirofosfato sintasa en osteoclastos; una infusión anual para osteoporosis",
      ["Osteoporosis posmenopáusica", "Osteoporosis masculina", "Enfermedad de Paget", "Prevención de osteoporosis por glucocorticoides"],
      ["Intravenosa"], "5 mg IV anual (Paget: 5 mg IV dosis única)",
      ["Fco 5 mg/100 mL"], "Contraindicada",
      "u07", "c07_06",
      familia="Bisfosfonatos IV",
      ci=["Hipocalcemia", "ClCr <35 mL/min", "Embarazo"],
      ea=["Reacción de fase aguda (fiebre, mialgias post-infusión)", "Hipocalcemia", "Osteonecrosis mandibular (raro)", "Fractura femoral atípica (raro)", "Uveítis (raro)"],
      ce=["Hidratación adecuada pre-infusión", "Normalizar calcio y vitamina D antes", "Paracetamol profiláctico para reacción post-infusión", "Evaluación dental antes de inicio", "Función renal antes de cada dosis anual"],
      pp={"dilucion": "Solución lista para infusión", "velocidadAdministracion": "5 mg en ≥15 min IV", "estabilidad": "24h a temperatura ambiente tras apertura"}),

    # ── Urología ──
    M("anticonceptivo_hormonal", "vibegron_detalle", "Vibegrón detallado", "vibegrón",
      ["Gems"], "Agonista beta-3 adrenérgico vesical",
      "Estimula receptores beta-3 en detrusor relajando músculo liso vesical",
      ["Vejiga hiperactiva (urgencia, frecuencia, incontinencia de urgencia)"],
      ["Oral"], "75 mg/día",
      ["Tab 75 mg"], "Evitar",
      "u07", "c07_03",
      familia="Agonistas beta-3 vesicales",
      ci=["Hipersensibilidad", "Retención urinaria"],
      ea=["ITU", "Cefalea", "Nasofaringitis", "Diarrea", "Retención urinaria"],
      ce=["No requiere titulación", "Menor riesgo de boca seca que antimuscarínicos", "Puede tomarse con o sin alimentos"]),

    M("anticonceptivo_hormonal", "mirabegron_detalle", "Mirabegrón detallado", "mirabegrón",
      ["Betmiga detallado"], "Agonista beta-3 adrenérgico",
      "Agonista selectivo de receptores beta-3 en detrusor; alternativa a anticolinérgicos",
      ["Vejiga hiperactiva con síntomas de urgencia/frecuencia/incontinencia"],
      ["Oral"], "25-50 mg/día",
      ["Tab 25 mg", "Tab 50 mg"], "Evitar",
      "u07", "c07_03",
      familia="Agonistas beta-3 vesicales",
      ci=["HTA severa no controlada", "Hipersensibilidad"],
      ea=["HTA", "ITU", "Cefalea", "Nasofaringitis", "Taquicardia"],
      ce=["Control de TA periódico", "No triturar comprimidos LP", "Alternativa en intolerancia a anticolinérgicos"]),
]

# ══════════════════════════════════════════════════════════════════════
# U08 — MUSCULOESQUELÉTICO (+10)
# ══════════════════════════════════════════════════════════════════════

u08_drugs = [
    M("aine", "etoricoxib_detalle", "Etoricoxib detallado", "etoricoxib",
      ["Arcoxia detallado"], "COXIB selectivo COX-2",
      "Inhibición altamente selectiva de COX-2 con ratio COX-1/COX-2 >100; menor riesgo GI",
      ["Artrosis", "Artritis reumatoide", "Artritis gotosa aguda", "Espondilitis anquilosante", "Dolor dental"],
      ["Oral"], "AR: 90 mg/día; OA: 30-60 mg/día; Gota aguda: 120 mg/día x8 días",
      ["Tab 30 mg", "Tab 60 mg", "Tab 90 mg", "Tab 120 mg"], "Contraindicada 3er trimestre",
      "u08", "c08_01",
      ci=["Cardiopatía isquémica", "IC clase III-IV", "HTA no controlada (>140/90)", "ACV previo", "Enfermedad arterial periférica"],
      ea=["Edema", "HTA", "Cefalea", "Dispepsia", "Riesgo cardiovascular aumentado"],
      ce=["Vigilar TA durante tratamiento", "Menor dosis y menor tiempo posible", "Mayor riesgo CV que otros AINEs", "No requiere protección gástrica rutinaria pero vigilar"]),

    M("inmunosupresor", "secukinumab_reum", "Secukinumab (Reumatología)", "secukinumab",
      ["Cosentyx Reum"], "Anti-IL-17A para artritis psoriásica y espondiloartritis",
      "Anticuerpo monoclonal que neutraliza IL-17A reduciendo inflamación articular y cutánea",
      ["Artritis psoriásica", "Espondilitis anquilosante", "Espondiloartritis axial no radiográfica"],
      ["Subcutánea"], "Carga: 150-300 mg SC sem 0,1,2,3,4; Mantenimiento: 150-300 mg SC mensual",
      ["Jer 150 mg", "Pluma 150 mg", "Pluma 300 mg"], "Evitar",
      "u08", "c08_02"),

    M("inmunosupresor", "ixekizumab_reum", "Ixekizumab (Reumatología)", "ixekizumab",
      ["Taltz Reum"], "Anti-IL-17A para artritis psoriásica",
      "Anticuerpo monoclonal anti-IL-17A con alta afinidad; efecto rápido en artritis y piel",
      ["Artritis psoriásica activa", "Espondilitis anquilosante"],
      ["Subcutánea"], "Carga: 160 mg sem 0, luego 80 mg sem 2,4,6,8,10,12; Mantenimiento: 80 mg c/4 sem",
      ["Jer 80 mg", "Pluma 80 mg"], "Evitar",
      "u08", "c08_02"),

    M("inmunosupresor", "apremilast_reum", "Apremilast (Reumatología)", "apremilast",
      ["Otezla Reum"], "Inhibidor de PDE4 oral para artritis psoriásica",
      "Inhibe PDE4 aumentando AMPc intracelular; modula respuesta inflamatoria sin inmunosupresión profunda",
      ["Artritis psoriásica activa (cuando DMARDs insuficientes)"],
      ["Oral"], "Titulación: 10 mg → 30 mg c/12h en 6 días; Mantenimiento: 30 mg c/12h",
      ["Tab inicio (pack titulación)", "Tab 30 mg"], "Evitar",
      "u08", "c08_02",
      familia="Inhibidores de PDE4",
      ci=["Hipersensibilidad"],
      ea=["Diarrea (frecuente al inicio)", "Náuseas", "Cefalea", "Infecciones vías altas", "Pérdida de peso"],
      ce=["Titulación gradual obligatoria", "No es inmunosupresor profundo: menor riesgo infección", "Peso regular (pérdida de peso posible)", "No requiere monitorización de laboratorio rutinaria"]),

    M("inmunosupresor", "deucravacitinib_reum", "Deucravacitinib detallado", "deucravacitinib",
      ["Sotyktu detallado"], "Inhibidor selectivo alostérico de TYK2",
      "Inhibe selectivamente TYK2 (no JAK1/2/3); modula vías de IL-23, IL-12 y IFN tipo I",
      ["Psoriasis en placas moderada a grave", "Artritis psoriásica (en desarrollo)"],
      ["Oral"], "6 mg c/24h",
      ["Tab 6 mg"], "Evitar",
      "u08", "c08_02",
      familia="Inhibidores de TYK2"),

    M("aine", "naproxeno_esomeprazol", "Naproxeno/Esomeprazol", "naproxeno + esomeprazol",
      ["Vimovo"], "AINE + IBP en combinación fija",
      "Naproxeno: inhibe COX-1/2; Esomeprazol: protección gástrica integrada",
      ["Artritis reumatoide", "Artrosis", "Espondilitis anquilosante (en pacientes con riesgo GI)"],
      ["Oral"], "500/20 mg c/12h",
      ["Tab LP 500/20 mg"], "Evitar en 3er trimestre",
      "u08", "c08_01",
      familia="AINE + gastroprotector"),

    M("inmunosupresor", "anifrolumab_detalle", "Anifrolumab detallado", "anifrolumab",
      ["Saphnelo detallado"], "Anti-receptor de interferón tipo I",
      "Anticuerpo monoclonal que bloquea receptor IFNAR1; reduce señalización de IFN tipo I en LES",
      ["Lupus eritematoso sistémico activo moderado-grave como adjunto"],
      ["Intravenosa"], "300 mg IV cada 4 semanas",
      ["Fco 300 mg/2 mL"], "Evitar",
      "u08", "c08_02",
      ci=["Hipersensibilidad", "Infección activa grave"],
      ea=["Infecciones (herpes zóster, respiratorias)", "Reacciones infusionales", "Nasofaringitis"],
      ce=["Vacunación contra herpes zóster antes de iniciar", "No vacunas vivas durante tratamiento", "Monitorizar infecciones", "Infusión en 30 min cada 4 sem"],
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión IV en 30 min", "estabilidad": "4h a temperatura ambiente"}),

    M("aine", "diflunisal_detalle", "Diflunisal detallado", "diflunisal",
      ["Dolobid detallado"], "AINE derivado de ácido salicílico",
      "Inhibe COX-1/2; además estabiliza tetrámeros de transtiretina (uso en amiloidosis)",
      ["Dolor leve-moderado", "Artrosis", "Amiloidosis por transtiretina (off-label estabilizador)"],
      ["Oral"], "Dolor: 500-1000 mg inicial, luego 250-500 mg c/8-12h; Amiloidosis: 250 mg c/12h",
      ["Tab 250 mg", "Tab 500 mg"], "Contraindicada 3er trimestre",
      "u08", "c08_01"),

    M("inmunosupresor", "tofacitinib_detalle", "Tofacitinib detallado", "tofacitinib",
      ["Xeljanz detallado"], "Inhibidor de JAK1/JAK3 oral",
      "Inhibe selectivamente JAK1 y JAK3 modulando señalización de citocinas proinflamatorias",
      ["Artritis reumatoide moderada-grave", "Artritis psoriásica", "Colitis ulcerosa"],
      ["Oral"], "AR: 5 mg c/12h o 11 mg XR c/24h; CU: 10 mg c/12h x8 sem, luego 5 mg c/12h",
      ["Tab 5 mg", "Tab XR 11 mg"], "Contraindicada",
      "u08", "c08_02",
      ci=["Infección activa grave", "Linfocitos <500", "Neutrófilos <1000", "Hb <9"],
      ea=["Infecciones graves", "Herpes zóster", "TEV", "Eventos CV mayores", "Neoplasias", "Perforación GI"],
      ce=["Hemograma y lípidos a las 4-8 semanas", "Cribado TB y hepatitis antes de iniciar", "Vacunación herpes zóster antes si posible", "FDA: caja negra por riesgo CV, TEV, malignidad y mortalidad"],
      emb="X"),

    M("inmunosupresor", "belimumab_reum", "Belimumab", "belimumab",
      ["Benlysta"], "Anti-BLyS/BAFF para lupus",
      "Anticuerpo monoclonal que inhibe BLyS/BAFF reduciendo supervivencia de linfocitos B autorreactivos",
      ["LES activo con anticuerpos positivos (adjunto a tratamiento estándar)", "Nefritis lúpica"],
      ["Intravenosa", "Subcutánea"], "IV: 10 mg/kg sem 0, 2, 4, luego mensual; SC: 200 mg semanal",
      ["Fco 120 mg IV", "Fco 400 mg IV", "Jer 200 mg SC"], "Contraindicada",
      "u08", "c08_02",
      pp={"dilucion": "En 250 mL SF", "velocidadAdministracion": "Infusión IV en 1h", "estabilidad": "8h refrigerado"}),
]

# ══════════════════════════════════════════════════════════════════════
# U09 — DERMATOLOGÍA (+10)
# ══════════════════════════════════════════════════════════════════════

u09_drugs = [
    M("corticoide_topico", "halobetasol_topico", "Halobetasol Tópico", "halobetasol propionato",
      ["Ultravate", "Halobetasol"], "Corticoide tópico de potencia ultra-alta (clase I)",
      "Superpotente: inhibe inflamación, proliferación celular e inmunosupresión local",
      ["Psoriasis en placas refractaria", "Dermatitis severa resistente", "Liquen plano hipertrófico"],
      ["Tópica"], "Aplicar capa fina 1-2 veces/día x2 semanas máx; no ocluir",
      ["Crema 0.05%", "Ungüento 0.05%", "Loción 0.05%"], "Evitar",
      "u09", "c09_01",
      ce=["Máximo 2 semanas de uso continuo", "No usar en cara, axilas ni ingle", "No aplicar en áreas extensas", "Riesgo de atrofia cutánea mayor que otros corticoides", "Descenso gradual tras uso prolongado"]),

    M("corticoide_topico", "mometasona_topica_det", "Mometasona Tópica detallado", "mometasona furoato",
      ["Elocon detallado"], "Corticoide tópico de potencia media-alta (clase III-IV)",
      "Potente antiinflamatorio con menor atrofia cutánea que otros de su potencia",
      ["Dermatitis atópica", "Psoriasis", "Dermatitis de contacto", "Eccema"],
      ["Tópica"], "Aplicar capa fina 1 vez/día",
      ["Crema 0.1%", "Ungüento 0.1%", "Loción 0.1%", "Sol capilar 0.1%"], "Compatible con precaución",
      "u09", "c09_01"),

    M("inmunosupresor", "dupilumab_det", "Dupilumab detallado", "dupilumab",
      ["Dupixent detallado"], "Anti-IL-4Rα para dermatitis atópica",
      "Anticuerpo monoclonal que bloquea señalización de IL-4 e IL-13 vía receptor IL-4Rα",
      ["Dermatitis atópica moderada-grave", "Asma eosinofílica", "Rinosinusitis crónica con pólipos", "Prurigo nodularis", "Esofagitis eosinofílica"],
      ["Subcutánea"], "Carga: 600 mg SC; Mantenimiento: 300 mg SC c/2 sem",
      ["Jer 200 mg", "Jer 300 mg", "Pluma 300 mg"], "Evitar",
      "u09", "c09_02",
      ci=["Hipersensibilidad a dupilumab"],
      ea=["Conjuntivitis", "Reacción en sitio inyección", "Herpes oral", "Eosinofilia transitoria"],
      ce=["Vigilar conjuntivitis (tratar con lágrimas artificiales)", "Rotar sitios de inyección", "Puede usarse con corticoides tópicos", "Sin necesidad de monitorización de laboratorio rutinaria"]),

    M("inmunosupresor", "tralokinumab_det", "Tralokinumab detallado", "tralokinumab",
      ["Adbry detallado"], "Anti-IL-13 para dermatitis atópica",
      "Anticuerpo monoclonal que neutraliza específicamente IL-13 sin afectar IL-4",
      ["Dermatitis atópica moderada-grave en adultos"],
      ["Subcutánea"], "Carga: 600 mg SC; Mantenimiento: 300 mg SC c/2 sem (puede espaciar a c/4 sem)",
      ["Jer 150 mg x2 por dosis"], "Evitar",
      "u09", "c09_02"),

    M("inmunosupresor", "nemolizumab_det", "Nemolizumab detallado", "nemolizumab",
      ["Nemluvio"], "Anti-IL-31Rα para prurito crónico",
      "Anticuerpo monoclonal contra receptor alfa de IL-31; IL-31 es la principal citocina pruritogénica",
      ["Prurigo nodularis", "Dermatitis atópica con prurito severo"],
      ["Subcutánea"], "Carga: 60 mg SC; Mantenimiento: 30 mg SC c/4 sem",
      ["Jer 30 mg"], "Evitar",
      "u09", "c09_02",
      familia="Anti-IL-31"),

    M("corticoide_topico", "roflumilast_topico", "Roflumilast Tópico", "roflumilast",
      ["Zoryve"], "Inhibidor de PDE4 tópico",
      "Inhibe PDE4 en células inflamatorias cutáneas aumentando AMPc; reduce inflamación sin efectos esteroideos",
      ["Psoriasis en placas leve-moderada", "Dermatitis atópica (incluyendo zonas sensibles)"],
      ["Tópica"], "Aplicar crema 0.3% una vez al día",
      ["Crema 0.3%"], "Evitar",
      "u09", "c09_02",
      familia="Inhibidores PDE4 tópicos",
      ci=["Hipersensibilidad"],
      ea=["Diarrea (absorción sistémica leve)", "Dolor en sitio de aplicación", "Cefalea"],
      ce=["Aplicable en zonas sensibles (cara, pliegues, genitales)", "No tiene efectos esteroideos (no atrofia)", "Sin límite de duración como corticoides", "Alternativa a corticoides en zonas delicadas"]),

    M("corticoide_topico", "tapinarof", "Tapinarof", "tapinarof",
      ["Vtama"], "Agonista del receptor AhR tópico",
      "Activa receptor de hidrocarburo arilo (AhR) modulando respuesta inmune cutánea y barrera epidérmica",
      ["Psoriasis en placas leve-moderada"],
      ["Tópica"], "Aplicar crema 1% una vez al día",
      ["Crema 1%"], "Evitar",
      "u09", "c09_02",
      familia="Agonistas AhR tópicos",
      ci=["Hipersensibilidad"],
      ea=["Foliculitis", "Cefalea", "Dermatitis de contacto", "Nasofaringitis"],
      ce=["Primer en su clase (mecanismo AhR)", "Sin límite de duración", "Aplicar capa fina sobre placas", "Efecto remitente: mejoría puede persistir tras suspender"]),

    M("inmunosupresor", "bimekizumab_det", "Bimekizumab detallado", "bimekizumab",
      ["Bimzelx detallado"], "Anti-IL-17A e IL-17F dual",
      "Primer anticuerpo que inhibe tanto IL-17A como IL-17F simultáneamente",
      ["Psoriasis en placas moderada-grave", "Artritis psoriásica", "Espondilitis anquilosante"],
      ["Subcutánea"], "Psoriasis: 320 mg SC sem 0,4,8,12,16; luego 320 mg c/8 sem",
      ["Jer 160 mg x2 por dosis"], "Contraindicada",
      "u09", "c09_02"),

    M("inmunosupresor", "ritlecitinib_det", "Ritlecitinib detallado", "ritlecitinib",
      ["Litfulo detallado"], "Inhibidor de JAK3/TEC para alopecia",
      "Inhibe JAK3 y familia TEC de cinasas; restaura privilegio inmune del folículo piloso",
      ["Alopecia areata severa en adultos y adolescentes ≥12 años"],
      ["Oral"], "Carga: 200 mg/día x4 sem (opcional); Mantenimiento: 50 mg/día",
      ["Cáps 50 mg", "Cáps 200 mg"], "Contraindicada",
      "u09", "c09_03",
      familia="Inhibidores JAK para alopecia",
      ea=["Cefalea", "Diarrea", "Acné", "ITU", "Infecciones", "Elevación CPK"],
      ce=["Hemograma y linfocitos antes de iniciar", "Cribado TB antes de iniciar", "Respuesta visible a partir de semana 24", "Si no respuesta a semana 36: reevaluar"]),

    M("inmunosupresor", "abrocitinib_det", "Abrocitinib detallado", "abrocitinib",
      ["Cibinqo detallado"], "Inhibidor selectivo JAK1 oral para dermatitis atópica",
      "Inhibe selectivamente JAK1 modulando señalización de citocinas pruritogénicas e inflamatorias",
      ["Dermatitis atópica moderada-grave refractaria a terapia tópica"],
      ["Oral"], "100-200 mg/día (200 mg para enfermedad severa)",
      ["Tab 50 mg", "Tab 100 mg", "Tab 200 mg"], "Contraindicada",
      "u09", "c09_02",
      ci=["Infección activa grave", "Linfocitos <500", "Plaquetas <50,000"],
      ea=["Náuseas (frecuente con 200 mg)", "Cefalea", "Acné", "Herpes simple", "Trombocitopenia", "Elevación CPK"],
      ce=["Hemograma antes y a las 4 semanas", "Plaquetas al inicio y periódicamente", "Lípidos a las 4-8 semanas", "Cribado TB y hepatitis antes de iniciar"],
      emb="X"),
]

# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    import os
    os.chdir(os.path.join(os.path.dirname(__file__), ".."))

    all_drugs = u01_drugs + u05_drugs + u06_drugs + u07_drugs + u08_drugs + u09_drugs
    print(f"=== Rest supplement: {len(all_drugs)} drugs ===")
    added = add_drugs_to_file(all_drugs)

    cats = load_categories()

    for d in all_drugs:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])

    save_categories(cats)
    print(f"Done. {added} drugs added.")
