#!/usr/bin/env python3
"""Add new drugs for U03 Antiinfecciosos (part A): antibióticos y antirretrovirales."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c03_01 Penicilinas y Cefalosporinas (+8) ──
M("penicilina","nafcilina","Nafcilina","Nafcilina",["Nallpen"],"Penicilina antiestafilocócica",
  "Penicilina resistente a penicilinasa. Activa contra S. aureus meticilino-sensible (MSSA)",
  ["Infecciones por MSSA (endocarditis, osteomielitis, bacteriemia)"],["IV"],
  {"adulto":"1-2 g IV c/4-6h","pediatrico":"100-200 mg/kg/día IV dividido c/4-6h"},
  ["Vial 1, 2 g"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con agua estéril","dilucion":"Diluir en 100 mL SF","velocidadAdministracion":"Infundir en 30-60 min","estabilidad":"24h refrigerado"}),

M("penicilina","oxacilina","Oxacilina","Oxacilina",["Prostaphlin"],"Penicilina antiestafilocócica",
  "Isoxazolil penicilina resistente a penicilinasa. Tratamiento IV de elección para MSSA severo en muchos países",
  ["Infecciones severas por MSSA","Endocarditis por S. aureus","Osteomielitis estafilocócica"],["IV","IM"],
  {"adulto":"1-2 g IV c/4-6h. Infección severa: 2 g c/4h","pediatrico":"100-200 mg/kg/día dividido c/4-6h"},
  ["Vial 500 mg, 1 g, 2 g"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con agua estéril","dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"Infundir en 15-30 min","estabilidad":"6h a TA, 24h refrigerado"}),

M("cefalosporina","cefaclor","Cefaclor","Cefaclor",["Ceclor"],"Cefalosporina de 2ª generación oral",
  "Cefalosporina oral con buena actividad contra grampositivos y algunos gramnegativos. Buena penetración a oído medio",
  ["OMA","Sinusitis","Faringitis","Infección urinaria no complicada","Bronquitis"],["oral"],
  {"adulto":"250-500 mg c/8h","pediatrico":"20-40 mg/kg/día dividido c/8h"},
  ["Cáps 250, 500 mg","Suspensión 125, 250 mg/5mL"],"Compatible con precaución","u03","c03_01"),

M("cefalosporina","cefoxitina","Cefoxitina","Cefoxitina",["Mefoxin"],"Cefamicina (2ª gen) con cobertura anaerobios",
  "Cefamicina con actividad contra Bacteroides fragilis. Resistente a muchas betalactamasas incluyendo BLEE",
  ["Infecciones intraabdominales","Profilaxis quirúrgica","Infección pélvica","EPI"],["IV","IM"],
  {"adulto":"1-2 g IV c/6-8h. Profilaxis QX: 2 g IV 30-60 min pre-incisión","pediatrico":"80-160 mg/kg/día dividido c/4-6h"},
  ["Vial 1, 2 g"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con agua estéril","dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"Infundir en 15-30 min","estabilidad":"24h a TA, 48h refrigerado"}),

M("penicilina","ticarcilina_clavulanico","Ticarcilina/Clavulánico","Ticarcilina + Ácido clavulánico",["Timentin"],
  "Penicilina antipseudomónica + inhibidor de betalactamasa",
  "Penicilina de espectro extendido con inhibidor de betalactamasa. Cubre Pseudomonas y productores de betalactamasa",
  ["Infecciones severas por gramnegativos","Infecciones polimicrobianas","Infección intraabdominal"],["IV"],
  {"adulto":"3.1 g IV c/4-6h","pediatrico":">3 meses: 200-300 mg/kg/día de ticarcilina dividido c/4-6h"},
  ["Vial 3.1 g (3 g ticarcilina + 0.1 g clavulánico)"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con 13 mL agua estéril","dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"Infundir en 30 min","estabilidad":"6h a TA, 72h refrigerado"}),

M("cefalosporina","cefiderocol","Cefiderocol","Cefiderocol",["Fetroja"],"Cefalosporina siderófora",
  "Primera cefalosporina siderófora: utiliza sistema de transporte de hierro bacteriano para penetrar membrana externa. Activa contra gramnegativos MDR",
  ["Infecciones por gramnegativos multirresistentes (Pseudomonas, Acinetobacter, productores de carbapenemasa)"],["IV"],
  {"adulto":"2 g IV c/8h en infusión de 3h","ajusteRenal":"Ajustar según ClCr: 1.5 g c/8h si ClCr 30-59; 1 g c/8h si ClCr 15-29"},
  ["Vial 1 g"],"No recomendado","u03","c03_01",
  ea=["Diarrea","Elevación transaminasas","Tos","Hipopotasemia","Reacciones de hipersensibilidad","Colitis por C. difficile"],
  ce=["Reservar para infecciones MDR sin otras opciones","Infusión prolongada 3 horas (obligatorio)","Vigilar función renal y hepática","Consultar infectología siempre"],
  pp={"reconstitucion":"Reconstituir con 10 mL SF o agua estéril","dilucion":"Diluir en 100 mL SF","velocidadAdministracion":"Infundir en 3 HORAS (no menos)","estabilidad":"6h a TA, 24h refrigerado"}),

M("cefalosporina","cefmetazol","Cefmetazol","Cefmetazol",["Zefazone"],"Cefamicina de 2ª generación",
  "Cefamicina con actividad contra anaerobios y BLEE. Alternativa a carbapenémicos para BLEE urinarias",
  ["ITU por BLEE","Profilaxis quirúrgica","Infecciones por anaerobios"],["IV"],
  {"adulto":"1-2 g IV c/6-8h","ajusteRenal":"Reducir frecuencia si ClCr <50"},
  ["Vial 1, 2 g"],"Compatible con precaución","u03","c03_01"),

M("penicilina","mecilinam","Mecilinam (Pivmecilinam)","Pivmecilinam",["Selexid"],"Amidinopenicilina oral",
  "Profármaco oral de mecilinam. Alta afinidad por PBP2. Actividad contra enterobacterias incluyendo algunas BLEE",
  ["ITU no complicada (primera línea en algunos países)","Cistitis aguda"],["oral"],
  {"adulto":"400 mg c/8h x 3-7 días para cistitis"},
  ["Comp 200, 400 mg"],"Compatible con precaución","u03","c03_01",
  ea=["Náuseas","Diarrea","Reacciones alérgicas","Deficiencia de carnitina (uso prolongado)"],
  ce=["Primera línea para cistitis en Escandinavia","No efectivo contra Pseudomonas","Puede ser alternativa para BLEE urinario","Tomar con alimentos"]),

# ── c03_02 Quinolonas y Macrólidos (+6) ──
M("quinolona","ofloxacino","Ofloxacino","Ofloxacino",["Floxin","Oflox"],"Fluoroquinolona de 2ª generación",
  "Quinolona con actividad contra gramnegativos y atípicos. Buena biodisponibilidad oral. Ambos enantiómeros",
  ["ITU complicada","Prostatitis crónica","Infección urinaria","Otitis externa (tópica)"],["oral","oftalmica","otica"],
  {"adulto":"200-400 mg c/12h oral. Ótica: 5 gotas c/12h","ajusteRenal":"Reducir dosis si ClCr <50"},
  ["Comp 200, 400 mg","Sol ótica 0.3%","Sol oftálmica 0.3%"],"Evitar durante lactancia","u03","c03_02"),

M("quinolona","delafloxacino","Delafloxacino","Delafloxacino",["Baxdela"],"Fluoroquinolona aniónica",
  "Quinolona no zwiteriónica con actividad mejorada en pH ácido (biofilms, abscesos). Cubre MRSA",
  ["Infección de piel y tejidos blandos (incluyendo MRSA)","Neumonía adquirida en comunidad"],["oral","IV"],
  {"adulto":"Oral: 450 mg c/12h. IV: 300 mg c/12h","ajusteRenal":"No usar IV si ClCr <30"},
  ["Comp 450 mg","Vial 300 mg"],"Evitar durante lactancia","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 10.5 mL SG5%","dilucion":"Diluir en 250 mL SF o SG5%","velocidadAdministracion":"Infundir en 60 min","estabilidad":"24h a TA, 72h refrigerado"}),

M("macrolido","espiramicina","Espiramicina","Espiramicina",["Rovamycine"],"Macrólido natural",
  "Macrólido de 16 átomos con concentración placentaria alta. Uso principal en toxoplasmosis gestacional",
  ["Toxoplasmosis en embarazo (prevención de transmisión fetal)","Infecciones ORL","Infecciones dentales"],["oral"],
  {"adulto":"Toxoplasmosis gestacional: 3 MUI c/8h hasta parto. Infecciones: 1.5-3 MUI c/8-12h"},
  ["Comp 1.5, 3 MUI"],"Compatible (indicación principal en gestación)","u03","c03_02",emb="B",
  ea=["Náuseas","Vómitos","Diarrea","Dolor abdominal","Erupción cutánea"],
  ce=["Fármaco de elección en toxoplasmosis gestacional primer trimestre","Se concentra en placenta (reduce transmisión 60%)","Tomar en ayunas","No confundir dosis: MUI (millones de unidades internacionales)"]),

M("macrolido","roxitromicina","Roxitromicina","Roxitromicina",["Rulid"],"Macrólido semisintético",
  "Derivado semisintético de eritromicina con mejor estabilidad ácida y vida media más larga",
  ["Infecciones respiratorias","Faringoamigdalitis","Infecciones de piel","Uretritis no gonocócica"],["oral"],
  {"adulto":"150 mg c/12h o 300 mg/día. Duración según infección"},
  ["Comp 150, 300 mg"],"Evitar durante lactancia","u03","c03_02"),

M("quinolona","gemifloxacino","Gemifloxacino","Gemifloxacino",["Factive"],"Fluoroquinolona respiratoria",
  "Quinolona de 4ª generación con excelente actividad contra neumococo (incluyendo penicilino-resistente) y atípicos",
  ["Neumonía comunitaria","Exacerbación aguda de bronquitis crónica"],["oral"],
  {"adulto":"320 mg/día x 5-7 días"},
  ["Comp 320 mg"],"Evitar durante lactancia","u03","c03_02"),

M("macrolido","telitromicina","Telitromicina","Telitromicina",["Ketek"],"Cetólido (derivado de macrólido)",
  "Primer cetólido: macrólido modificado con mayor afinidad ribosomal. Activa contra neumococo resistente a macrólidos",
  ["Neumonía comunitaria (reservada para casos específicos)"],["oral"],
  {"adulto":"800 mg/día x 7-10 días"},
  ["Comp 400 mg"],"Contraindicado","u03","c03_02",
  ci=["Miastenia gravis (⚠️ exacerbación fatal reportada)","Hepatopatía previa","Prolongación QT","Uso con estatinas"],
  ea=["Hepatotoxicidad severa","Alteraciones visuales","Náuseas","Diarrea","Prolongación QT","Pérdida de consciencia transitoria"],
  ce=["Uso muy restringido por hepatotoxicidad","Contraindicado en miastenia gravis","Vigilar visión (acomodación alterada)","No conducir durante tratamiento"]),

# ── c03_03 Otros Antibióticos (+8) ──
M("penicilina","minociclina_oral","Minociclina oral","Minociclina",["Minocin"],"Tetraciclina de 2ª generación",
  "Tetraciclina lipofílica con excelente penetración tisular y al SNC. Activa contra MRSA comunitario",
  ["Acné moderado-severo","Infecciones por MRSA comunitario","Artritis reumatoide (off-label)","Rosácea"],["oral"],
  {"adulto":"100 mg c/12h. Acné: 50-100 mg/día","pediatrico":">8 años: 4 mg/kg seguido de 2 mg/kg c/12h"},
  ["Cáps 50, 100 mg","Comp LP 45, 90, 135 mg"],"Evitar durante lactancia","u03","c03_03",
  familia="Tetraciclinas",ci=["Embarazo","Niños <8 años","Hipersensibilidad a tetraciclinas"],
  ea=["Vértigo vestibular (característico)","Hiperpigmentación cutánea y mucosas","Fotosensibilidad","Náuseas","Hepatotoxicidad","Lupus inducido"],
  ce=["Puede causar vértigo significativo (diferenciador de doxiciclina)","Hiperpigmentación dosis-dependiente (piel azul-grisácea)","Tomar con alimentos (reduce náuseas)","No con lácteos ni antiácidos (quelación)"]),

M("cefalosporina","estreptomicina","Estreptomicina","Estreptomicina",["Estreptomicina"],"Aminoglucósido de 1ª generación",
  "Primer aminoglucósido. Inhibe subunidad 30S ribosomal. Uso actual limitado a TB y brucelosis",
  ["Tuberculosis (régimen intensivo)","Brucelosis","Endocarditis por Enterococcus (sinergia con ampicilina)","Peste","Tularemia"],["IM"],
  {"adulto":"TB: 15 mg/kg/día IM (máx 1g). Brucelosis: 1 g/día IM x 14-21 días","geriatrico":"10 mg/kg/día. Máx 750 mg"},
  ["Vial 1 g"],"Contraindicado","u03","c03_03",
  familia="Aminoglucósidos",ci=["Miastenia gravis","Hipersensibilidad a aminoglucósidos","Insuficiencia renal severa"],
  ea=["⚠️ Ototoxicidad vestibular (irreversible)","Nefrotoxicidad","Parestesias peribucales","Bloqueo neuromuscular"],
  ce=["Audiometría basal y periódica","Función renal antes y durante tratamiento","Solo IM (no IV)","Vigilar equilibrio (toxicidad vestibular)"]),

M("cefalosporina","dalvabancina","Dalbavancina","Dalbavancina",["Dalvance","Xydalba"],"Lipoglicopéptido de acción ultralarga",
  "Lipoglicopéptido semisintético con vida media de 14 días. Permite dosificación semanal o dosis única",
  ["Infección de piel y tejidos blandos por grampositivos (incluyendo MRSA)","Osteomielitis","Endocarditis (off-label)"],["IV"],
  {"adulto":"1500 mg IV dosis única O 1000 mg d1 + 500 mg d8"},
  ["Vial 500 mg"],"No recomendado","u03","c03_03",
  familia="Glucopéptidos",ea=["Náuseas","Cefalea","Diarrea","Erupción cutánea","Prurito"],
  ce=["Dosis única IV: revolucionario para adherencia","Ideal para pacientes sin hogar o mala adherencia","Infundir en 30 min","Vigilar síndrome de hombre rojo (como vancomicina)"],
  pp={"reconstitucion":"Reconstituir con 25 mL agua estéril","dilucion":"Diluir en 250 mL SG5%","velocidadAdministracion":"Infundir en 30 min","estabilidad":"48h a TA"}),

M("cefalosporina","oritavancina","Oritavancina","Oritavancina",["Orbactiv"],"Lipoglicopéptido de dosis única",
  "Lipoglicopéptido con triple mecanismo: inhibe transpeptidación, transglicosilación y disrumpe membrana",
  ["Infección aguda de piel y tejidos blandos por grampositivos"],["IV"],
  {"adulto":"1200 mg IV dosis única en infusión de 3 horas"},
  ["Vial 400 mg"],"No recomendado","u03","c03_03",
  familia="Glucopéptidos",ea=["Cefalea","Náuseas","Vómitos","Taquicardia","Diarrea","Absceso de extremidad"],
  ci=["Hipersensibilidad a glucopéptidos","Uso de heparina IV en 120h (interfiere con aPTT)"],
  ce=["Dosis única: tratamiento completo en una visita","Interfiere con pruebas de coagulación 120h","Infundir en 3 horas obligatorio","No usar heparina no fraccionada en 5 días post-dosis"],
  pp={"reconstitucion":"Reconstituir 3 viales con 40 mL agua c/u","dilucion":"Transferir a 1000 mL SG5%","velocidadAdministracion":"Infundir en 3 HORAS","estabilidad":"6h a TA, 12h refrigerado"}),

M("cefalosporina","omadaciclina","Omadaciclina","Omadaciclina",["Nuzyra"],"Aminometilciclina (tetraciclina moderna)",
  "Primera aminometilciclina. Supera mecanismos de resistencia a tetraciclinas (eflujo y protección ribosomal)",
  ["Neumonía comunitaria","Infección de piel y tejidos blandos (incluyendo MRSA)"],["oral","IV"],
  {"adulto":"IV: 200 mg d1, luego 100 mg/día. Oral: 300 mg d1-2, luego 300 mg/día en ayunas"},
  ["Comp 150 mg","Vial 100 mg"],"Contraindicado","u03","c03_03",
  familia="Tetraciclinas modernas",ci=["Embarazo","Niños <8 años","Hipersensibilidad a tetraciclinas"],
  ea=["Náuseas","Vómitos","Diarrea","Elevación transaminasas","Fotosensibilidad"],
  ce=["Oral: tomar en ayunas estricto con agua","Supera resistencia a tetraciclinas clásicas","No con lácteos ni antiácidos","Alternativa oral para MRSA"]),

M("cefalosporina","lefamulina","Lefamulina","Lefamulina",["Xenleta"],"Pleuromutilina sistémica",
  "Primera pleuromutilina para uso sistémico. Inhibe síntesis proteica en sitio CPC del ribosoma 50S (sitio único)",
  ["Neumonía adquirida en comunidad"],["oral","IV"],
  {"adulto":"IV: 150 mg c/12h. Oral: 600 mg c/12h x 5 días"},
  ["Comp 600 mg","Vial 150 mg"],"Contraindicado","u03","c03_03",emb="X",
  familia="Pleuromutilinas",ci=["Prolongación QT","Uso de sustratos CYP3A4 sensibles","Embarazo"],
  ea=["Diarrea","Náuseas","Prolongación QT","Vómitos","Elevación transaminasas"],
  ce=["Clase antibiótica completamente nueva","Alternativa para pacientes alérgicos a múltiples clases","ECG si factores riesgo QT","Oral con alimentos"]),

M("cefalosporina","eravaciclina","Eravaciclina","Eravaciclina",["Xerava"],"Tetraciclina de nueva generación",
  "Fluorociclina totalmente sintética. Supera resistencia por eflujo y protección ribosomal. Cobertura amplia",
  ["Infección intraabdominal complicada"],["IV"],
  {"adulto":"1 mg/kg IV c/12h en 60 min. Duración 4-14 días"},
  ["Vial 50 mg"],"Contraindicado","u03","c03_03",
  familia="Tetraciclinas modernas",ci=["Embarazo","Niños <8 años"],
  ea=["Náuseas","Vómitos","Diarrea","Flebitis","Hipotensión"],
  ce=["Solo IV (no hay formulación oral)","Infundir en 60 min","Ajustar dosis con inductores CYP3A4","Para infecciones intraabdominales polimicrobianas"],
  pp={"reconstitucion":"Reconstituir con 5 mL agua estéril","dilucion":"Diluir en 250 mL SF","velocidadAdministracion":"Infundir en 60 min","estabilidad":"6h a TA"}),

M("cefalosporina","netilmicina","Netilmicina","Netilmicina",["Netromicina"],"Aminoglucósido semisintético",
  "Aminoglucósido derivado de sisomicina. Menor ototoxicidad que gentamicina. Activo contra algunas cepas resistentes a gentamicina",
  ["Infecciones severas por gramnegativos","Sepsis neonatal","Infecciones urinarias complicadas"],["IV","IM"],
  {"adulto":"4-6 mg/kg/día en 1-3 dosis. Dosis única diaria: 5-7 mg/kg","pediatrico":"Neonatos: 4-6.5 mg/kg/día"},
  ["Amp 50, 100, 150, 200 mg"],"Compatible con precaución","u03","c03_03",
  familia="Aminoglucósidos",ci=["Miastenia gravis","Hipersensibilidad a aminoglucósidos"],
  ea=["Nefrotoxicidad","Ototoxicidad","Bloqueo neuromuscular"],
  ce=["Monitorizar niveles: pico 6-10, valle <2 mcg/mL","Función renal diaria","Puede ser menos ototóxico que gentamicina","Dosis única diaria preferida en adultos"],
  pp={"dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"Infundir en 30-60 min","estabilidad":"24h a TA"}),

# ── c03_07 Antirretrovirales (+25) - NUEVO ──
M("antirretroviral","zidovudina","Zidovudina (AZT)","Zidovudina",["Retrovir","AZT"],
  "Inhibidor nucleósido de transcriptasa reversa (INTR) — primer ARV","Primer antirretroviral aprobado (1987). Análogo de timidina que inhibe TR del VIH tras fosforilación intracelular",
  ["Infección por VIH (en combinación)","Prevención transmisión vertical VIH","Profilaxis post-exposición"],["oral","IV"],
  {"adulto":"300 mg c/12h oral. IV: 1-2 mg/kg c/4h","pediatrico":"Neonato: 4 mg/kg c/12h oral x 4-6 sem (prevención vertical)"},
  ["Comp 300 mg","Cáps 100 mg","Jarabe 50 mg/5mL","Vial IV 10 mg/mL"],"Compatible según guías actuales","u03","c03_07",
  ea=["Anemia macrocítica (⚠️ efecto principal)","Neutropenia","Náuseas","Cefalea","Miopatía (uso prolongado)","Lipoatrofia facial","Acidosis láctica (raro)"],
  ce=["Hemograma c/2 semanas inicio, luego mensual","Puede requerir EPO si anemia severa","Histórico: primer fármaco contra VIH","Aún se usa en prevención transmisión vertical"],
  pp={"dilucion":"Diluir en SG5% a concentración ≤4 mg/mL","velocidadAdministracion":"Infundir en 1 hora","estabilidad":"24h a TA, 48h refrigerado"}),

M("antirretroviral","estavudina","Estavudina (d4T)","Estavudina",["Zerit"],
  "INTR análogo de timidina","Análogo de timidina fosforilado intracelularmente. Alta toxicidad mitocondrial limita su uso actual",
  ["Infección por VIH (solo si no hay alternativa)"],["oral"],
  {"adulto":"≥60 kg: 40 mg c/12h. <60 kg: 30 mg c/12h"},
  ["Cáps 15, 20, 30, 40 mg","Sol oral 1 mg/mL"],"Evitar durante lactancia","u03","c03_07",
  ea=["⚠️ Neuropatía periférica","⚠️ Lipoatrofia severa","⚠️ Acidosis láctica","Pancreatitis","Esteatosis hepática","Hiperlipidemia"],
  ce=["En desuso por alta toxicidad mitocondrial","No combinar con zidovudina (antagonismo)","Vigilar neuropatía y pancreatitis","OMS recomienda no usarlo si hay alternativas"]),

M("antirretroviral","nevirapina","Nevirapina","Nevirapina",["Viramune"],
  "Inhibidor no nucleósido de TR (INNTR) de 1ª generación","Se une directamente al sitio alostérico de TR. No requiere fosforilación. Baja barrera genética",
  ["VIH (en combinación)","Prevención transmisión vertical (dosis única intraparto)"],["oral"],
  {"adulto":"200 mg/día x 14 días (lead-in), luego 200 mg c/12h","pediatrico":"Neonato: 2 mg/kg dosis única + AZT"},
  ["Comp 200 mg","Comp LP 400 mg","Suspensión 50 mg/5mL"],"Evitar si alternativas","u03","c03_07",
  ea=["⚠️ Hepatotoxicidad severa (primeras 18 semanas)","⚠️ Rash severo/Stevens-Johnson","Cefalea","Fatiga"],
  ci=["CD4 >250 (mujeres) o >400 (hombres) al iniciar (mayor riesgo hepatotoxicidad)","Insuficiencia hepática moderada-severa"],
  ce=["Lead-in obligatorio 14 días a mitad de dosis","No iniciar si transaminasas >5x LSN","Función hepática c/2 sem x 18 sem","Suspender inmediatamente si rash con síntomas sistémicos"]),

M("antirretroviral","lopinavir_ritonavir","Lopinavir/Ritonavir","Lopinavir + Ritonavir",["Kaletra"],
  "Inhibidor de proteasa potenciado","Lopinavir: inhibidor de proteasa del VIH. Ritonavir a dosis baja: potenciador farmacocinético (booster CYP3A4)",
  ["VIH (en combinación, 2ª línea)","VIH pediátrico"],["oral"],
  {"adulto":"400/100 mg c/12h o 800/200 mg/día con alimentos","pediatrico":"Dosis según peso/superficie corporal"},
  ["Comp 200/50 mg","Sol oral 80/20 mg/mL"],"Evitar durante lactancia","u03","c03_07",
  ea=["Diarrea (muy frecuente)","Náuseas","Hipertrigliceridemia","Hipercolesterolemia","Lipodistrofia","Hiperglucemia","Prolongación QT/PR"],
  ce=["Tomar con alimentos (comprimidos pueden sin alimentos)","Sol oral requiere refrigeración","Múltiples interacciones farmacológicas","Monitorizar perfil lipídico y glucemia"]),

M("antirretroviral","darunavir","Darunavir","Darunavir",["Prezista"],
  "Inhibidor de proteasa de 2ª generación","IP de alta barrera genética. Requiere ritonavir o cobicistat como potenciador. Activo contra VIH resistente a otros IP",
  ["VIH (en combinación, 1ª o 2ª línea)","VIH resistente a otros inhibidores de proteasa"],["oral"],
  {"adulto":"Sin resistencia: 800/100 mg (con rtv) c/24h. Con resistencia: 600/100 mg c/12h"},
  ["Comp 75, 150, 600, 800 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Diarrea","Náuseas","Rash","Cefalea","Hiperlipidemia","Hepatotoxicidad","Hiperglucemia"],
  ce=["Siempre con potenciador (ritonavir o cobicistat)","Tomar con alimentos","Alta barrera genética (ventaja)","Alergia a sulfonamidas: precaución (contiene grupo sulfa)"]),

M("antirretroviral","raltegravir","Raltegravir","Raltegravir",["Isentress"],
  "Inhibidor de integrasa de 1ª generación","Primer inhibidor de integrasa del VIH. Bloquea inserción del ADN viral en genoma del huésped",
  ["VIH (en combinación)","VIH resistente a otras clases"],["oral"],
  {"adulto":"400 mg c/12h o 1200 mg (2x600) c/24h","pediatrico":"Disponible desde neonatos según peso"},
  ["Comp 400, 600 mg","Comp masticable 25, 100 mg","Granulado 100 mg"],"Compatible con precaución","u03","c03_07",
  ea=["Insomnio","Cefalea","Náuseas","Fatiga","CPK elevada","Miopatía/rabdomiólisis (raro)"],
  ce=["Pocas interacciones farmacológicas (ventaja)","No requiere potenciador","Formulación pediátrica disponible","Monitorizar CPK si mialgias"]),

M("antirretroviral","maraviroc","Maraviroc","Maraviroc",["Celsentri","Selzentry"],
  "Antagonista CCR5 (inhibidor de entrada)","Bloquea co-receptor CCR5 en linfocitos CD4, impidiendo entrada del VIH. Solo eficaz contra virus R5-trópicos",
  ["VIH con tropismo CCR5 confirmado (en combinación)"],["oral"],
  {"adulto":"150-600 mg c/12h según interacciones (150 con IP potenciados, 300 estándar, 600 con inductores)"},
  ["Comp 150, 300 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Tos","Infecciones respiratorias superiores","Rash","Mareo","Hepatotoxicidad (raro, precedida por rash alérgico)"],
  ci=["Virus con tropismo X4 o dual/mixto","Hipersensibilidad"],
  ce=["Test de tropismo obligatorio antes de iniciar","Solo eficaz contra virus CCR5-trópico","Ajustar dosis según interacciones","Vigilar función hepática"]),

M("antirretroviral","bictegravir","Bictegravir","Bictegravir",["Biktarvy (con TAF/FTC)"],
  "Inhibidor de integrasa de 2ª generación","Inhibidor de integrasa no potenciado con alta barrera genética. Solo disponible en combinación fija",
  ["VIH (tratamiento de primera línea como Biktarvy)"],["oral"],
  {"adulto":"50 mg/día (en Biktarvy: bictegravir 50/emtricitabina 200/TAF 25 mg) dosis única"},
  ["Comp Biktarvy 50/200/25 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Diarrea","Náuseas","Cefalea","Insomnio","Fatiga"],
  ce=["Primera línea recomendada en guías actuales","Una pastilla al día (alta adherencia)","Alta barrera genética","Vigilar función renal (componente TAF)"]),

M("antirretroviral","cabotegravir","Cabotegravir","Cabotegravir",["Vocabria","Apretude"],
  "Inhibidor de integrasa inyectable de acción prolongada",
  "Inhibidor de integrasa con formulación inyectable de liberación lenta. Permite dosificación mensual o bimensual",
  ["VIH (con rilpivirina inyectable como régimen completo)","PrEP inyectable (prevención VIH)"],["oral","IM"],
  {"adulto":"Oral lead-in: 30 mg/día x 1 mes. IM: 600 mg (+ rilpivirina 900 mg) c/2 meses","pediatrico":"No aprobado en pediátricos"},
  ["Comp 30 mg","Suspensión IM 200 mg/mL"],"No recomendado","u03","c03_07",
  ea=["Reacción en sitio de inyección (muy frecuente)","Cefalea","Fiebre","Fatiga","Mialgias"],
  ce=["Revolucionario: primer régimen ARV inyectable bimensual","Inyección IM glútea por profesional de salud","PrEP: alternativa a tenofovir/emtricitabina oral diario","Asegurar citas puntuales (riesgo resistencia si retraso)"]),

M("antirretroviral","doravirina","Doravirina","Doravirina",["Pifeltro","Delstrigo (combo)"],
  "INNTR de nueva generación","INNTR con actividad contra mutantes K103N y Y181C. Perfil metabólico favorable",
  ["VIH (en combinación, primera línea)"],["oral"],
  {"adulto":"100 mg/día (o Delstrigo: doravirina 100/lamivudina 300/TDF 300 mg/día)"},
  ["Comp 100 mg","Comp Delstrigo 100/300/300 mg"],"No recomendado","u03","c03_07",
  ea=["Mareo","Náuseas","Sueños anormales","Fatiga","Cefalea","Insomnio"],
  ce=["Activo contra mutaciones comunes de resistencia a INNTR","Perfil lipídico neutro (ventaja sobre efavirenz)","Sin interacción con antiácidos","Puede tomarse con o sin alimentos"]),

M("antirretroviral","rilpivirina","Rilpivirina","Rilpivirina",["Edurant"],
  "INNTR de 2ª generación","INNTR con alta potencia a baja dosis. Menor toxicidad neuropsiquiátrica que efavirenz",
  ["VIH con CV <100.000 y CD4 >200 (en combinación)"],["oral","IM"],
  {"adulto":"Oral: 25 mg/día con comida. IM: 900 mg c/2 meses (con cabotegravir)"},
  ["Comp 25 mg","Suspensión IM 300 mg/mL"],"Evitar durante lactancia","u03","c03_07",
  ci=["Uso de IBP (contraindicado)","CV >100.000 al inicio"],
  ea=["Depresión","Insomnio","Cefalea","Rash","Elevación transaminasas"],
  ce=["Tomar SIEMPRE con comida (absorción depende de alimentos)","Contraindicado con IBP (reducen absorción)","Antiácidos: separar 4h antes o 12h después","Disponible como inyectable bimensual con cabotegravir"]),

M("antirretroviral","emtricitabina","Emtricitabina (FTC)","Emtricitabina",["Emtriva"],
  "INTR análogo de citidina fluorado","Análogo fluorado de citidina. Componente clave de la mayoría de regímenes ARV y PrEP",
  ["VIH (en combinación)","PrEP (profilaxis pre-exposición VIH)"],["oral"],
  {"adulto":"200 mg/día","pediatrico":">3 meses: 6 mg/kg/día (máx 240 mg)"},
  ["Cáps 200 mg","Sol oral 10 mg/mL"],"Evitar durante lactancia","u03","c03_07",
  ea=["Cefalea","Náuseas","Diarrea","Insomnio","Hiperpigmentación palmo-plantar","Exacerbación hepatitis B al suspender"],
  ce=["Componente de Truvada, Descovy, Biktarvy, etc.","Descartar hepatitis B antes de iniciar y al suspender","Bien tolerado","Función renal periódica"]),

M("antirretroviral","tenofovir_alafenamida","Tenofovir alafenamida (TAF)","Tenofovir alafenamida",["Vemlidy"],
  "INTR profármaco de tenofovir (2ª gen)","Profármaco que logra mayor concentración intracelular con menor exposición plasmática que TDF. Menor nefro y osteo-toxicidad",
  ["VIH (en combinación)","Hepatitis B crónica"],["oral"],
  {"adulto":"25 mg/día (aislado) o según combinación fija"},
  ["Comp 25 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Cefalea","Náuseas","Fatiga","Aumento peso (vs TDF)","Elevación lípidos (vs TDF)"],
  ce=["Menos nefrotóxico que TDF (tenofovir disoproxil)","Menos pérdida ósea que TDF","Descartar hepatitis B antes de suspender","Puede aumentar peso y lípidos más que TDF"]),

M("antirretroviral","cobicistat","Cobicistat","Cobicistat",["Tybost"],
  "Potenciador farmacocinético (booster)","Inhibidor potente de CYP3A sin actividad antiviral. Aumenta niveles de elvitegravir, atazanavir o darunavir",
  ["Potenciador farmacocinético de ARV (no es antiviral per se)"],["oral"],
  {"adulto":"150 mg/día (siempre con el ARV que potencia)"},
  ["Comp 150 mg"],"No recomendado","u03","c03_07",
  ea=["Elevación creatinina (inhibe secreción tubular, no daño real)","Náuseas","Ictericia (con atazanavir)"],
  ix=["⚠️ Inhibidor potente CYP3A4: múltiples interacciones","Consultar SIEMPRE base de interacciones"],
  ce=["Eleva creatinina sin dañar riñón (nuevo basal)","No usar como tratamiento: solo potenciador","Siempre con ARV específico","Verificar TODAS las interacciones"]),

M("antirretroviral","fostemsavir","Fostemsavir","Fostemsavir",["Rukobia"],
  "Inhibidor de unión (attachment inhibitor)","Profármaco de temsavir que se une a gp120 del VIH, bloqueando unión al receptor CD4. Mecanismo único",
  ["VIH multirresistente en pacientes sin otras opciones terapéuticas"],["oral"],
  {"adulto":"600 mg c/12h"},
  ["Comp LP 600 mg"],"No recomendado","u03","c03_07",
  ea=["Náuseas","Diarrea","Cefalea","Rash","Elevación CPK","Síndrome de reconstitución inmune"],
  ce=["Reservar para VIH altamente resistente","Mecanismo de acción completamente nuevo","No triturar (liberación prolongada)","Consultar con experto en VIH"]),

M("antirretroviral","lenacapavir","Lenacapavir","Lenacapavir",["Sunlenca"],
  "Inhibidor de cápside (primer en su clase)","Primer inhibidor de cápside del VIH. Interfiere en múltiples pasos: ensamblaje, transporte nuclear y maduración viral",
  ["VIH multirresistente (en combinación)","PrEP inyectable semestral (en desarrollo/aprobado)"],["oral","SC"],
  {"adulto":"Oral lead-in → SC: 927 mg SC c/6 meses (dosificación semestral)"},
  ["Comp 300 mg","Vial SC 463.5 mg/1.5mL"],"No recomendado","u03","c03_07",
  ea=["Reacción en sitio de inyección (nódulos SC)","Náuseas","Diarrea"],
  ce=["Revolucionario: dosificación cada 6 MESES","Inyección SC (no IM)","Mecanismo de acción único en su clase","PrEP semestral: potencial de cambiar prevención del VIH"]),
]

NEW_CHAPTERS = {
    "c03_07": {"id":"c03_07","nombre":"Antirretrovirales","unidadId":"u03","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U03a: Antiinfecciosos (part A) ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u03", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
