#!/usr/bin/env python3
"""Add ~100 new drugs for U02 Sistema Cardiovascular."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c02_01 Antihipertensivos (+12) ──
M("ieca","lisinopril","Lisinopril","Lisinopril",["Prinivil","Zestril"],"IECA de larga acción",
  "Inhibidor de ECA que no requiere metabolismo hepático (activo per se). Excreción renal sin cambios",
  ["HTA","Insuficiencia cardíaca","Post-IAM","Nefropatía diabética"],["oral"],
  {"adulto":"HTA: 10-40 mg/día. IC: 2.5-35 mg/día","pediatrico":"≥6 años: 0.07 mg/kg/día","ajusteRenal":"2.5-5 mg/día si ClCr <30"},
  ["Comp 5, 10, 20, 40 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ieca","quinapril","Quinapril","Quinapril",["Accupril","Acuprel"],"IECA",
  "Profármaco convertido a quinaprilato activo. Alta afinidad tisular por ECA",
  ["HTA","Insuficiencia cardíaca"],["oral"],
  {"adulto":"HTA: 10-80 mg/día en 1-2 tomas. IC: 5-20 mg c/12h"},
  ["Comp 5, 10, 20, 40 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ara2","eprosartan","Eprosartán","Eprosartán",["Teveten"],"ARA-II con acción simpaticolítica",
  "Bloquea receptor AT1. Adicionalmente inhibe liberación presináptica de noradrenalina (acción simpaticolítica)",
  ["HTA"],["oral"],{"adulto":"600 mg/día en 1-2 tomas"},
  ["Comp 400, 600 mg"],"Evitar durante lactancia","u02","c02_01"),

M("betabloqueante","labetalol_cv","Labetalol (cardiovascular)","Labetalol",["Trandate"],
  "Alfa y betabloqueante combinado","Bloquea receptores alfa-1, beta-1 y beta-2. Relación alfa:beta = 1:3 oral, 1:7 IV",
  ["HTA severa","Emergencia hipertensiva","HTA en embarazo","Crisis hipertensiva por feocromocitoma"],["oral","IV"],
  {"adulto":"Oral: 100-400 mg c/12h. IV urgencia: 20 mg bolo, repetir c/10 min. Infusión: 0.5-2 mg/min","ajusteHepatico":"Reducir dosis"},
  ["Comp 100, 200 mg","Amp 100 mg/20mL"],"Compatible con precaución","u02","c02_01",
  pp={"dilucion":"Diluir en SG5% o SF","velocidadAdministracion":"Bolo IV lento en 2 min. Infusión: 0.5-2 mg/min","estabilidad":"24h a TA diluido"}),

M("calcioantagonista","isradipino","Isradipino","Isradipino",["DynaCirc"],"Calcioantagonista DHP de 2ª generación",
  "Dihidropiridina con alta selectividad vascular. Mínimo efecto inotrópico negativo",
  ["HTA"],["oral"],{"adulto":"2.5-5 mg c/12h. Máx 20 mg/día"},
  ["Cáps 2.5, 5 mg"],"Evitar durante lactancia","u02","c02_01"),

M("betabloqueante","acebutolol","Acebutolol","Acebutolol",["Sectral"],"Betabloqueante cardioselectivo con ASI",
  "Beta-1 selectivo con actividad simpaticomimética intrínseca (ASI). Menor bradicardia en reposo",
  ["HTA","Arritmias supraventriculares","Extrasístoles ventriculares"],["oral"],
  {"adulto":"200-400 mg c/12h. Máx 1200 mg/día"},
  ["Cáps 200, 400 mg"],"Compatible con precaución","u02","c02_01"),

M("ieca","aliskireno","Aliskirén","Aliskirén",["Tekturna","Rasilez"],"Inhibidor directo de renina",
  "Primer inhibidor directo de renina oral. Bloquea conversión de angiotensinógeno en angiotensina I",
  ["HTA (monoterapia o combinación)"],["oral"],{"adulto":"150-300 mg/día en dosis única"},
  ["Comp 150, 300 mg"],"Evitar durante lactancia","u02","c02_01",
  familia="Inhibidores directos de renina",
  ci=["Embarazo","Uso con IECA o ARA-II en diabéticos","Hiperpotasemia","Estenosis bilateral arteria renal"],
  ea=["Diarrea","Hiperpotasemia","Hipotensión","Angioedema (raro)","Elevación ácido úrico"],
  ce=["No combinar con IECA o ARA-II","Tomar siempre de la misma forma respecto a alimentos","Vigilar potasio y función renal","No usar en diabéticos con IECA/ARA-II"]),

M("calcioantagonista","lacidipino","Lacidipino","Lacidipino",["Lacipil"],"Calcioantagonista DHP lipofílico",
  "Dihidropiridina altamente lipofílica con acción antioxidante vascular. Inicio lento, duración prolongada",
  ["HTA"],["oral"],{"adulto":"2-6 mg/día en dosis única"},
  ["Comp 2, 4, 6 mg"],"Evitar durante lactancia","u02","c02_01"),

M("diuretico","eplerenona","Eplerenona","Eplerenona",["Inspra"],"Antagonista selectivo de mineralocorticoides",
  "Bloquea selectivamente receptor de aldosterona. Menor afinidad por receptores androgénicos/progesterona que espironolactona",
  ["IC post-IAM con FEVI ≤40%","IC con FEVI reducida","HTA"],["oral"],
  {"adulto":"IC post-IAM: 25 mg/día, incrementar a 50 mg/día. HTA: 50-100 mg/día","ajusteRenal":"Contraindicado si ClCr <30"},
  ["Comp 25, 50 mg"],"Evitar durante lactancia","u02","c02_01",
  familia="Antagonistas de aldosterona",ea=["Hiperpotasemia","Mareo","Diarrea","Elevación creatinina"],
  ce=["Monitorizar K+ a los 3 días, 1 sem y mensualmente","Sin ginecomastia (ventaja sobre espironolactona)","No usar con suplementos de K+","Ajustar si K+ >5.5 mEq/L"]),

M("betabloqueante","celiprolol","Celiprolol","Celiprolol",["Cardem"],"Betabloqueante vasodilatador",
  "Beta-1 selectivo con agonismo parcial beta-2 (vasodilatación). No empeora perfil lipídico",
  ["HTA","Angina de pecho"],["oral"],{"adulto":"200-400 mg/día en ayunas"},
  ["Comp 200, 400 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ara2","azilsartan","Azilsartán","Azilsartán medoxomilo",["Edarbi"],"ARA-II de última generación",
  "Antagonista AT1 con mayor afinidad y disociación más lenta del receptor que otros ARA-II",
  ["HTA"],["oral"],{"adulto":"40-80 mg/día en dosis única"},
  ["Comp 20, 40, 80 mg"],"Evitar durante lactancia","u02","c02_01"),

M("calcioantagonista","barnidipino","Barnidipino","Barnidipino",["Vasexten"],"Calcioantagonista DHP",
  "Dihidropiridina lipofílica de liberación lenta. Acción antihipertensiva gradual y sostenida",
  ["HTA leve a moderada"],["oral"],{"adulto":"10-20 mg/día en dosis única por la mañana"},
  ["Cáps 10, 20 mg"],"Evitar durante lactancia","u02","c02_01"),

# ── c02_02 Antiarrítmicos (+5) ──
M("betabloqueante","quinidina","Quinidina","Quinidina",["Cardioquin","Quinidex"],"Antiarrítmico clase IA",
  "Bloquea canales de sodio (clase I), canales de potasio y receptores muscarínicos. Prolonga potencial de acción",
  ["Fibrilación auricular","Flutter auricular","Taquicardia ventricular","Síndrome de Brugada (quinidina específica)"],["oral"],
  {"adulto":"Sulfato: 200-400 mg c/6h. Gluconato: 324-648 mg c/8-12h"},
  ["Comp sulfato 200, 300 mg","Comp LP gluconato 324 mg"],"Evitar durante lactancia","u02","c02_02",
  familia="Antiarrítmicos",ci=["Bloqueo AV completo","Prolongación QT","Miastenia gravis","Trombocitopenia previa por quinidina"],
  ea=["Cinchonismo (tinnitus, cefalea, visión borrosa)","Prolongación QT","Torsade de pointes","Diarrea","Trombocitopenia","Hipotensión"],
  ix=["Digoxina: duplica niveles (reducir 50%)","Warfarina: aumenta INR","Amiodarona: prolonga QT aditivo","CYP2D6: inhibe metabolismo"],
  ce=["ECG basal y monitorización QTc","Monitorizar niveles plasmáticos (2-5 mcg/mL)","Vigilar cinchonismo","Suspender si QTc >500 ms"]),

M("betabloqueante","disopiramida","Disopiramida","Disopiramida",["Norpace","Ritmolept"],"Antiarrítmico clase IA con efecto anticolinérgico",
  "Bloquea canales de sodio y potasio. Potente efecto inotrópico negativo y anticolinérgico periférico",
  ["Fibrilación auricular","Taquicardia supraventricular","Miocardiopatía hipertrófica obstructiva"],["oral"],
  {"adulto":"100-200 mg c/6h. LP: 250-375 mg c/12h. Máx 800 mg/día","ajusteRenal":"Reducir dosis según ClCr"},
  ["Cáps 100, 150 mg","Cáps LP 250 mg"],"Evitar durante lactancia","u02","c02_02",
  familia="Antiarrítmicos",ea=["Boca seca","Retención urinaria","Estreñimiento","Visión borrosa","IC (inotrópico negativo)","Hipoglucemia"],
  ci=["IC descompensada","Bloqueo AV 2-3°","Glaucoma","Retención urinaria","Prolongación QT"],
  ce=["Contraindicado en IC sistólica","Vigilar función vesical","Monitorizar glucemia (puede causar hipoglucemia)","ECG periódico"]),

M("betabloqueante","ajmalina","Ajmalina","Ajmalina",["Gilurytmal"],"Antiarrítmico clase IA (test de Brugada)",
  "Bloqueante de canales de sodio usado diagnósticamente para desenmascarar patrón de Brugada en ECG",
  ["Test farmacológico de Brugada","Taquicardia supraventricular aguda","Síndrome de WPW"],["IV"],
  {"adulto":"Test Brugada: 1 mg/kg IV en 5 min bajo monitorización. Terapéutico: 50 mg IV lento"},
  ["Amp 50 mg/2mL"],"No recomendado","u02","c02_02",
  familia="Antiarrítmicos",ci=["Bloqueo AV","IC severa","Síndrome de Brugada conocido tipo 1"],
  ea=["Hipotensión","Bradicardia","Bloqueo AV","Prolongación QRS","Fibrilación ventricular"],
  ce=["Solo en unidades con monitorización ECG continua","Desfibrilador disponible durante test de Brugada","Inyectar lentamente","Suspender si QRS se ensancha >25%"],
  pp={"dilucion":"Puede administrar sin diluir o en 10 mL SF","velocidadAdministracion":"1 mg/kg en 5 minutos","estabilidad":"Usar inmediatamente"}),

M("betabloqueante","pilsicainida","Pilsicainida","Pilsicainida",["Sunrythm"],"Antiarrítmico clase IC puro",
  "Bloqueante de canales de sodio clase IC con mínimos efectos sobre potasio y calcio. Usado principalmente en Asia",
  ["Fibrilación auricular paroxística","Taquicardia supraventricular"],["oral","IV"],
  {"adulto":"Oral: 50 mg c/8h. IV: 1 mg/kg en 10 min"},
  ["Comp 25, 50 mg","Amp 50 mg"],"No recomendado","u02","c02_02",
  familia="Antiarrítmicos",ea=["Proarritmia","Mareo","Bloqueo AV","Ensanchamiento QRS"],
  ce=["ECG antes de cada aumento de dosis","No usar en cardiopatía estructural","Vigilar ensanchamiento QRS","Uso limitado fuera de Asia"]),

M("betabloqueante","vernakalant_oral","Vernakalant oral","Vernakalant",["Brinavess"],"Antiarrítmico auricular selectivo",
  "Bloquea múltiples canales iónicos con selectividad por tejido auricular. Mínimo efecto ventricular",
  ["Conversión rápida de FA reciente (<7 días) a ritmo sinusal"],["IV"],
  {"adulto":"3 mg/kg IV en 10 min. Si no convierte en 15 min: 2ª dosis 2 mg/kg en 10 min"},
  ["Vial 200 mg/100mL"],"No recomendado","u02","c02_02",
  familia="Antiarrítmicos",ci=["Estenosis aórtica severa","PAS <100","IC clase IV","Prolongación QT","SCA en últimos 30 días"],
  ea=["Disgeusia","Estornudos","Parestesias","Hipotensión","Bradicardia"],
  ce=["Solo uso hospitalario con monitorización","Muy rápida cardioversión (8-14 min)","Alternativa a cardioversión eléctrica","Observar 2h post-infusión"],
  pp={"dilucion":"No diluir, solución lista","velocidadAdministracion":"3 mg/kg en 10 minutos","estabilidad":"Usar dentro de 24h"}),

# ── c02_08 Hipertensión Pulmonar (+10) - NUEVO ──
M("calcioantagonista","treprostinil","Treprostinil","Treprostinil",["Remodulin","Tyvaso","Orenitram"],
  "Análogo de prostaciclina","Análogo estable de prostaciclina. Vasodilatador pulmonar, antiagregante y antiproliferativo",
  ["Hipertensión arterial pulmonar (HAP) clase II-IV"],["SC","IV","inhalatoria","oral"],
  {"adulto":"SC/IV: inicio 1.25 ng/kg/min, titular 1.25 ng/kg/min c/1-2 sem. Inhalado: 3 resp c/6h"},
  ["Vial SC 1, 2.5, 5, 10 mg/mL","Sol inhalación 0.6 mg/mL","Comp LP 0.125-5 mg"],"Contraindicado","u02","c02_08",
  familia="Fármacos para hipertensión pulmonar",
  ci=["Hipersensibilidad a prostanoides","Edema pulmonar venooclusivo"],
  ea=["Cefalea","Dolor mandibular","Diarrea","Náuseas","Dolor en sitio de infusión SC","Rubor","Hipotensión"],
  ix=["Anticoagulantes: mayor sangrado","Antihipertensivos: hipotensión aditiva"],
  ce=["Infusión continua: no interrumpir bruscamente","Dolor en sitio SC es frecuente (rotar sitios)","Enseñar manejo de bomba de infusión","Via inhalada: 9 respiraciones por sesión con dispositivo específico"]),

M("calcioantagonista","epoprostenol","Epoprostenol","Epoprostenol",["Flolan","Veletri"],
  "Prostaciclina IV (PGI2)","Prostaciclina sintética. Potente vasodilatador pulmonar y antiagregante. Vida media 3-5 min",
  ["HAP clase III-IV","Test de vasorreactividad pulmonar"],["IV"],
  {"adulto":"Inicio 2 ng/kg/min, titular 1-2 ng/kg/min c/15 min en test. Mantenimiento: 25-40 ng/kg/min promedio"},
  ["Vial liofilizado 0.5, 1.5 mg"],"Contraindicado","u02","c02_08",
  familia="Fármacos para hipertensión pulmonar",
  ci=["IC izquierda severa","Edema pulmonar venooclusivo"],
  ea=["Cefalea","Dolor mandibular","Diarrea","Náuseas","Rubor","Hipotensión","Dolor musculoesquelético","Sepsis por catéter"],
  ce=["⚠️ Infusión IV continua 24/7: NUNCA interrumpir (hipotensión de rebote fatal)","Requiere catéter venoso central permanente","Preparación estéril (riesgo sepsis por línea)","Refrigerar Flolan; Veletri estable a TA 24h"],
  pp={"reconstitucion":"Reconstituir con diluyente específico","dilucion":"Diluir según concentración deseada","velocidadAdministracion":"Infusión continua vía bomba","estabilidad":"Flolan: 8h a TA, 48h refrigerado. Veletri: 24h a TA"}),

M("calcioantagonista","selexipag","Selexipag","Selexipag",["Uptravi"],
  "Agonista selectivo receptor IP de prostaciclina (oral)","Agonista no prostanoide del receptor IP. Primer agonista de prostaciclina oral selectivo",
  ["HAP clase II-III (en combinación con ERA y/o inhibidor PDE5)"],["oral"],
  {"adulto":"200 mcg c/12h, titular 200 mcg c/semana hasta dosis tolerada. Máx 1600 mcg c/12h"},
  ["Comp 200, 400, 600, 800, 1000, 1200, 1400, 1600 mcg"],"No recomendado","u02","c02_08",
  familia="Fármacos para hipertensión pulmonar",ea=["Cefalea","Diarrea","Dolor mandibular","Náuseas","Mialgias","Dolor de extremidades"],
  ce=["Titular lentamente según tolerancia GI","Tomar con alimentos","EA de clase (prostanoide) esperados","No reemplaza terapia parenteral en HAP severa"]),

M("calcioantagonista","ambrisentan","Ambrisentán","Ambrisentán",["Letairis","Volibris"],
  "Antagonista selectivo receptor ET-A de endotelina","Bloquea selectivamente receptor ET-A, inhibiendo vasoconstricción y proliferación por endotelina-1",
  ["HAP clase II-III"],["oral"],{"adulto":"5 mg/día, puede aumentar a 10 mg/día"},
  ["Comp 5, 10 mg"],"Contraindicado","u02","c02_08",
  familia="Antagonistas de endotelina",ci=["Embarazo","Fibrosis pulmonar idiopática","Hipersensibilidad"],emb="X",
  ea=["Edema periférico","Cefalea","Congestión nasal","Anemia","Palpitaciones"],
  ce=["⚠️ Teratógeno: anticoncepción obligatoria y test embarazo mensual","Programa REMS","Hemoglobina mensual primeros meses","No requiere monitorización hepática (a diferencia de bosentán)"]),

M("calcioantagonista","riociguat","Riociguat","Riociguat",["Adempas"],
  "Estimulador de guanilato ciclasa soluble (sGC)","Estimula directamente sGC y sensibiliza al NO endógeno. Aumenta GMPc → vasodilatación pulmonar",
  ["HAP","Hipertensión pulmonar tromboembólica crónica (HPTEC) inoperable"],["oral"],
  {"adulto":"0.5 mg c/8h, titular 0.5 mg c/2 sem hasta 2.5 mg c/8h según PAS"},
  ["Comp 0.5, 1, 1.5, 2, 2.5 mg"],"Contraindicado","u02","c02_08",
  familia="Estimuladores de sGC",ci=["Embarazo","Uso con PDE5i o NO donantes","PAS <95 mmHg"],emb="X",
  ea=["Hipotensión","Cefalea","Dispepsia","Náuseas","Mareo","Anemia"],
  ce=["Teratógeno: anticoncepción obligatoria","No combinar con sildenafilo ni nitratos","Titular según PAS (no dar si PAS<95)","Tomar con o sin alimentos"]),

M("calcioantagonista","tadalafilo_hp","Tadalafilo (HAP)","Tadalafilo",["Adcirca"],
  "Inhibidor PDE5 para hipertensión pulmonar","Inhibe fosfodiesterasa-5, aumentando GMPc en músculo liso vascular pulmonar → vasodilatación",
  ["HAP clase II-III"],["oral"],{"adulto":"40 mg/día en dosis única"},
  ["Comp 20 mg"],"Evitar durante lactancia","u02","c02_08",
  familia="Inhibidores de PDE5",ci=["Uso de nitratos","Uso de riociguat","Hipotensión severa"],
  ea=["Cefalea","Mialgia","Rubor facial","Nasofaringitis","Dolor de espalda","Dispepsia"],
  ce=["NO combinar con nitratos ni riociguat","Dosis diferente a uso en disfunción eréctil","Puede tomarse con o sin alimentos","Monitorizar PA"]),

M("calcioantagonista","sildenafilo_hp","Sildenafilo (HAP)","Sildenafilo",["Revatio"],
  "Inhibidor PDE5 para HAP","Inhibe PDE5 en vasculatura pulmonar, aumentando vasodilatación mediada por NO/GMPc",
  ["HAP clase II-III"],["oral","IV"],{"adulto":"Oral: 20 mg c/8h. IV: 10 mg c/8h"},
  ["Comp 20 mg","Vial 10 mg/12.5mL"],"Evitar durante lactancia","u02","c02_08",
  familia="Inhibidores de PDE5",ci=["Nitratos","Riociguat","Hipotensión"],
  ea=["Cefalea","Rubor","Dispepsia","Epistaxis","Insomnio","Alteraciones visuales"],
  ce=["Dosis 20 mg (no confundir con 50-100 mg de Viagra)","No combinar con nitratos","Vigilar función visual","Disponible IV para pacientes que no toleran oral"],
  pp={"dilucion":"No diluir, solución lista","velocidadAdministracion":"Bolo IV directo","estabilidad":"Usar inmediatamente"}),

M("calcioantagonista","beraprost","Beraprost","Beraprost",["Dorner","Careload"],
  "Análogo oral de prostaciclina","Primer análogo oral de prostaciclina. Vasodilatador con efecto antiagregante y antiproliferativo",
  ["HAP (principalmente en Asia)","Enfermedad arterial periférica"],["oral"],
  {"adulto":"HAP: 20 mcg c/8h, titular hasta 120 mcg c/8h. EAP: 40 mcg c/8h"},
  ["Comp 20, 40 mcg"],"No recomendado","u02","c02_08",
  familia="Fármacos para hipertensión pulmonar",ea=["Cefalea","Rubor","Diarrea","Dolor mandibular","Palpitaciones"],
  ce=["Disponibilidad limitada fuera de Asia","Tomar con alimentos","Titular gradualmente","EA prostanoides esperados"]),

M("calcioantagonista","sitaxentan_hist","Sitaxentán (histórico)","Sitaxentán",["Thelin (retirado)"],
  "Antagonista ET-A selectivo (retirado)","Era antagonista altamente selectivo de receptor ET-A. Retirado en 2010 por hepatotoxicidad fatal",
  ["(Histórico) HAP — RETIRADO del mercado en 2010"],["oral"],{"adulto":"Fue 100 mg/día — RETIRADO"},
  ["RETIRADO del mercado"],"N/A","u02","c02_08",
  familia="Antagonistas de endotelina (histórico)",
  ea=["⚠️ Hepatotoxicidad fatal (motivo de retiro)","Cefalea","Edema","Congestión nasal"],
  ci=["Fármaco retirado del mercado"],
  ce=["Caso educativo: importancia de farmacovigilancia","Retirado por casos de hepatitis fulminante fatal","Sustituido por ambrisentán y macitentán","Ejemplo de balance beneficio-riesgo post-comercialización"]),

# ── c02_09 Antianginosos Adicionales (+8) - NUEVO ──
M("calcioantagonista","nicorandil","Nicorandil","Nicorandil",["Ikorel","Dancor"],
  "Activador de canales de potasio + nitrato","Doble mecanismo: abre canales KATP (dilatación arteriolar) y libera NO (dilatación venosa)",
  ["Angina estable crónica (2ª línea)","Angina vasoespástica (Prinzmetal)"],["oral"],
  {"adulto":"10-20 mg c/12h. Puede incrementar a 30 mg c/12h"},
  ["Comp 10, 20 mg"],"Evitar durante lactancia","u02","c02_09",
  familia="Antianginosos",ci=["Hipotensión","Shock cardiogénico","Uso de PDE5i","IC aguda"],
  ea=["Cefalea (frecuente al inicio)","Úlceras orales/anales/GI","Mareo","Rubor","Náuseas"],
  ce=["Cefalea inicial mejora con el tiempo","Vigilar úlceras orales o perianales (suspender si aparecen)","No combinar con PDE5i ni nitratos","Inicio gradual para tolerar cefalea"]),

M("calcioantagonista","molsidomina","Molsidomina","Molsidomina",["Corvasal"],
  "Donante de NO (sydnonimina)","Profármaco que libera NO directamente sin necesidad de grupos sulfhidrilo. No desarrolla tolerancia",
  ["Angina estable (profilaxis)","IC como vasodilatador"],["oral"],
  {"adulto":"2-4 mg c/8h. LP: 8 mg c/12h"},
  ["Comp 2, 4 mg","Comp LP 8 mg"],"Evitar durante lactancia","u02","c02_09",
  familia="Vasodilatadores nitroderivados",ci=["Hipotensión","Shock","Uso de PDE5i"],
  ea=["Cefalea","Hipotensión","Mareo","Rubor facial"],
  ce=["Ventaja: no genera tolerancia (a diferencia de nitratos)","Alternativa a nitratos orales","Tomar con alimentos","Monitorizar TA"]),

M("calcioantagonista","dinitrato_isosorbide","Dinitrato de isosorbide","Dinitrato de isosorbide",["Isordil","Isosorb"],
  "Nitrato orgánico de acción intermedia","Profármaco que libera NO tras metabolismo hepático. Vasodilatación venosa predominante (reduce precarga)",
  ["Angina estable (profilaxis)","Angina aguda (sublingual)","IC (reduce precarga)"],["oral","sublingual"],
  {"adulto":"SL: 5-10 mg prn. Oral: 10-40 mg c/8h (con intervalo libre nocturno 12h)"},
  ["Comp SL 5 mg","Comp oral 10, 20, 40 mg"],"Compatible con precaución","u02","c02_09",
  familia="Nitratos",ci=["Hipotensión severa","Uso de PDE5i","Miocardiopatía hipertrófica obstructiva"],
  ea=["Cefalea (muy frecuente)","Hipotensión","Taquicardia refleja","Rubor","Tolerancia con uso continuo"],
  ce=["Intervalo libre de nitrato (8-12h nocturnas) para evitar tolerancia","SL: colocar bajo lengua, no tragar","Cefalea disminuye con uso continuado","No usar con sildenafilo/tadalafilo"]),

M("calcioantagonista","mononitrato_isosorbide","Mononitrato de isosorbide","5-Mononitrato de isosorbide",["Imdur","Ismo"],
  "Nitrato de acción prolongada","Metabolito activo del dinitrato. No requiere metabolismo hepático de primer paso. Mayor biodisponibilidad",
  ["Angina estable (profilaxis)","IC con congestión"],["oral"],
  {"adulto":"LP: 30-60 mg/día en dosis única matutina. Máx 240 mg/día. Regular: 20 mg c/12h con intervalo libre"},
  ["Comp LP 30, 60, 120 mg","Comp 20 mg"],"Compatible con precaución","u02","c02_09",
  familia="Nitratos",ci=["Hipotensión severa","Uso de PDE5i","Hipovolemia"],
  ea=["Cefalea","Mareo","Hipotensión ortostática","Tolerancia"],
  ce=["Tomar por la mañana (LP dosis única)","No triturar formulaciones LP","Intervalo libre nocturno si formulación regular","Paracetamol para cefalea del nitrato"]),

M("calcioantagonista","nimodipino_cv","Nimodipino","Nimodipino",["Nimotop"],
  "Calcioantagonista con selectividad cerebrovascular","DHP con alta lipofilia y selectividad por vasos cerebrales. Cruza barrera hematoencefálica",
  ["Vasoespasmo cerebral post-hemorragia subaracnoidea","Prevención de déficit neurológico isquémico"],["oral","IV"],
  {"adulto":"Oral: 60 mg c/4h x 21 días. IV: 1-2 mg/h en infusión continua"},
  ["Comp 30 mg","Sol oral 30 mg","Sol IV 0.2 mg/mL"],"Evitar durante lactancia","u02","c02_09",
  familia="Calcioantagonistas cerebrovasculares",ci=["Hipotensión severa","Edema cerebral","Hipertensión intracraneal"],
  ea=["Hipotensión","Cefalea","Rubor","Náuseas","Bradicardia","Edema"],
  ce=["⚠️ NO administrar IV directa: solo en infusión continua","Uso exclusivo post-HSA (hemorragia subaracnoidea)","Iniciar dentro de 96h del sangrado","Via oral preferida si paciente puede tragar"],
  pp={"dilucion":"Diluir en SF o SG5%. Proteger de luz","velocidadAdministracion":"Inicio 0.5 mg/h (5 mL/h), incrementar a 1-2 mg/h","estabilidad":"Proteger de luz. Usar tubos opacos"}),

M("calcioantagonista","pentoxifilina","Pentoxifilina","Pentoxifilina",["Trental"],
  "Inhibidor de fosfodiesterasa / hemorreológico","Inhibe PDE no selectivamente, aumentando AMPc. Mejora deformabilidad eritrocitaria y reduce viscosidad",
  ["Claudicación intermitente","Enfermedad vascular periférica","Úlceras venosas (adyuvante)"],["oral","IV"],
  {"adulto":"Oral: 400 mg c/8h con alimentos. IV: 100-300 mg en 250 mL SF en 1-3h"},
  ["Comp LP 400 mg","Amp 100 mg/5mL"],"Compatible con precaución","u02","c02_09",
  familia="Hemorreológicos",ci=["Hemorragia activa","Hemorragia cerebral reciente","Hemorragia retiniana"],
  ea=["Náuseas","Vómitos","Mareo","Cefalea","Rubor","Hemorragia (raro)"],
  ce=["Tomar con alimentos para reducir GI","No triturar LP","Efecto terapéutico en 2-8 semanas","Suspender si hemorragia"]),

M("calcioantagonista","perhexilina","Perhexilina","Perhexilina",["Pexsig"],
  "Modulador metabólico miocárdico","Inhibe CPT-1, cambiando metabolismo miocárdico de ácidos grasos a glucosa (más eficiente en O2)",
  ["Angina refractaria a otros tratamientos","Miocardiopatía hipertrófica obstructiva"],["oral"],
  {"adulto":"100-200 mg c/12h. REQUIERE monitorización de niveles plasmáticos"},
  ["Comp 100 mg"],"Contraindicado","u02","c02_09",
  familia="Antianginosos metabólicos",ci=["Neuropatía periférica","Hepatopatía","Metabolizadores lentos CYP2D6 no genotipados"],
  ea=["⚠️ Neuropatía periférica","⚠️ Hepatotoxicidad","Mareo","Náuseas","Hipoglucemia"],
  ce=["Niveles plasmáticos obligatorios (rango 0.15-0.6 mg/L)","Genotipado CYP2D6 antes de iniciar","Función hepática y neurológica periódica","Solo para angina refractaria a todo lo demás"]),

M("calcioantagonista","fasudil","Fasudil","Fasudil",["Eril"],
  "Inhibidor de Rho-kinasa","Inhibe Rho-kinasa (ROCK), produciendo vasodilatación cerebral y coronaria. Efecto antivasoespástico",
  ["Vasoespasmo cerebral post-HSA","Angina vasoespástica (Japón)"],["IV"],
  {"adulto":"30 mg en 30 min IV c/8h durante fase de riesgo de vasoespasmo (hasta 14 días)"},
  ["Amp 30 mg/20mL"],"No recomendado","u02","c02_09",
  familia="Inhibidores de Rho-kinasa",ci=["Hemorragia intracraneal activa","Hipersensibilidad"],
  ea=["Hipotensión","Rubor","Cefalea","Elevación transaminasas","Hemorragia intracraneal"],
  ce=["Disponibilidad principalmente en Japón/Asia","Administrar en infusión lenta","Monitorizar PA durante infusión","Complementario a nimodipino en HSA"]),

# ── c02_10 Shock y Soporte Hemodinámico (+5) - NUEVO ──
M("vasopressor","angiotensina_ii","Angiotensina II sintética","Angiotensina II",["Giapreza"],
  "Vasopresor peptídico","Péptido endógeno sintético. Actúa directamente sobre receptores AT1 causando vasoconstricción potente",
  ["Shock vasodilatador refractario a catecolaminas"],["IV"],
  {"adulto":"Inicio 20 ng/kg/min, titular c/5 min hasta objetivo de PAM. Rango: 1.25-80 ng/kg/min"},
  ["Vial 2.5 mg/mL"],"No recomendado","u02","c02_10",
  ci=["Hipersensibilidad"],ea=["Trombosis","Taquicardia","Acidosis","Hiperglucemia","Delirium"],
  ce=["Uso en shock séptico refractario a noradrenalina","Profilaxis antitrombótica durante uso","Titular según PAM objetivo","Monitorización hemodinámica invasiva obligatoria"],
  pp={"dilucion":"Diluir en SF a 5000-10000 ng/mL","velocidadAdministracion":"Infusión continua 20 ng/kg/min inicio","estabilidad":"24h a TA, 72h refrigerado"}),

M("vasopressor","metaraminol","Metaraminol","Metaraminol",["Aramine"],
  "Simpaticomimético alfa-1 predominante","Agonista directo alfa-1 e indirecto (libera noradrenalina). Vasoconstricción periférica sin taquicardia refleja",
  ["Hipotensión intraoperatoria","Hipotensión por anestesia espinal/epidural"],["IV","IM"],
  {"adulto":"Bolo: 0.5-1 mg IV, repetir c/5-10 min. Infusión: 15-100 mg en 500 mL SF"},
  ["Amp 10 mg/mL"],"No recomendado","u02","c02_10",
  ea=["HTA","Bradicardia refleja","Arritmias","Isquemia periférica","Necrosis por extravasación"],
  ce=["Uso principal en hipotensión de anestesia neuroaxial","Preferir vía IV (IM absorción errática)","Vigilar extravasación","Puede causar bradicardia refleja (a diferencia de otros vasopresores)"],
  pp={"dilucion":"Puede dar sin diluir o diluir en SF/SG5%","velocidadAdministracion":"Bolo IV lento. Infusión según respuesta","estabilidad":"24h diluido"}),

M("vasopressor","fenilefrina_infusion","Fenilefrina infusión","Fenilefrina",["Neosinefrina IV"],
  "Agonista alfa-1 puro","Agonista selectivo alfa-1 adrenérgico. Vasoconstricción sin efecto beta (sin taquicardia). Bradicardia refleja",
  ["Hipotensión intraoperatoria","Shock vasodilatador","Hipotensión por espinal","Soporte hemodinámico en ICC con taquicardia"],["IV"],
  {"adulto":"Bolo: 50-200 mcg c/1-5 min. Infusión: 0.1-0.5 mcg/kg/min"},
  ["Amp 10 mg/mL"],"No recomendado","u02","c02_10",
  ea=["Bradicardia refleja","HTA","Isquemia periférica","Necrosis por extravasación","Cefalea"],
  ce=["Causa bradicardia refleja (no taquicardia)","Preferir vía central para infusión prolongada","Fentolamina SC como antídoto de extravasación","No mezclar con soluciones alcalinas"],
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"Infusión continua 0.1-0.5 mcg/kg/min","estabilidad":"24h diluido"}),

M("vasopressor","terlipresina_shock","Terlipresina (shock)","Terlipresina",["Glypressin"],
  "Análogo de vasopresina de acción prolongada","Profármaco de lisina-vasopresina. Agonista V1 con duración más larga que vasopresina (4-6h vs 30 min)",
  ["Síndrome hepatorrenal","Hemorragia variceal","Shock séptico refractario"],["IV"],
  {"adulto":"Hemorragia variceal: 2 mg IV bolo, luego 1 mg c/4-6h. SHR: 0.5-2 mg c/4-6h"},
  ["Amp 0.1 mg/mL, 1 mg/5mL"],"No recomendado","u02","c02_10",
  ea=["Isquemia periférica y mesentérica","Bradicardia","HTA","Dolor abdominal","Hiponatremia"],
  ce=["Vigilar isquemia digital y mesentérica","ECG durante tratamiento","Monitorizar sodio","Usar con nitroglicerina IV en hemorragia variceal para reducir EA"],
  pp={"dilucion":"Puede administrar sin diluir","velocidadAdministracion":"Bolo IV lento en 1-2 min","estabilidad":"Refrigerar. Usar inmediatamente tras apertura"}),

M("vasopressor","noradrenalina_titulable","Noradrenalina (protocolo de titulación)","Noradrenalina bitartrato",["Levophed"],
  "Catecolamina vasopresora de primera línea","Agonista alfa-1 potente con efecto beta-1 moderado. Vasoconstricción + aumento contractilidad. Primera línea en shock séptico",
  ["Shock séptico (primera línea)","Shock cardiogénico","Hipotensión refractaria"],["IV"],
  {"adulto":"Inicio 0.05-0.1 mcg/kg/min, titular c/5-10 min según PAM. Rango habitual: 0.1-1 mcg/kg/min"},
  ["Amp 1 mg/mL (4mL, 8mL)"],"No recomendado","u02","c02_10",
  ea=["Taquicardia","Arritmias","Isquemia periférica","HTA","Necrosis por extravasación","Isquemia mesentérica"],
  ce=["Primera línea SIEMPRE en shock séptico (Surviving Sepsis)","VÍA CENTRAL obligatoria idealmente","Fentolamina SC 5-10 mg si extravasación","Titular para PAM ≥65 mmHg","No mezclar con bicarbonato"],
  pp={"dilucion":"4-16 mg en 250 mL SG5% (16-64 mcg/mL)","velocidadAdministracion":"Infusión continua titulada","estabilidad":"24h protegido de luz. No usar si color marrón"}),
]

NEW_CHAPTERS = {
    "c02_08": {"id":"c02_08","nombre":"Hipertensión Pulmonar","unidadId":"u02","drugIds":[]},
    "c02_09": {"id":"c02_09","nombre":"Antianginosos Adicionales","unidadId":"u02","drugIds":[]},
    "c02_10": {"id":"c02_10","nombre":"Shock y Soporte Hemodinámico","unidadId":"u02","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U02: Sistema Cardiovascular ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u02", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
