#!/usr/bin/env python3
"""Add ~60 new drugs for U11 Antídotos y Emergencias."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c11_01 Antídotos Específicos (+20) ──
M("antidoto","succimero","Succímero (DMSA)","Succímero",["Chemet"],"Quelante de metales pesados oral",
  "Ácido dimercaptosuccínico. Quelante oral de plomo, mercurio y arsénico. Forma complejos hidrosolubles excretados por riñón",
  ["Intoxicación por plomo (plumbemia >45 mcg/dL en niños)","Intoxicación por mercurio y arsénico"],["oral"],
  {"adulto":"10 mg/kg c/8h x5d, luego c/12h x14d","pediatrico":"Igual que adulto (dosis por peso)"},
  ["Cáps 100 mg"],"Evitar durante lactancia","u11","c11_01",
  ea=["Náuseas","Vómitos","Diarrea","Erupción cutánea","Elevación transaminasas","Neutropenia transitoria"],
  ce=["Monitorizar plomo sérico durante y post-tratamiento","Función hepática y hemograma semanal","Puede abrir cápsulas y mezclar con alimentos blandos","Hidratación adecuada"]),

M("antidoto","penicilamina_antidoto","Penicilamina (antídoto)","Penicilamina",["Cuprimine"],"Quelante de cobre y metales pesados",
  "Derivado de penicilina sin actividad antibiótica. Quela cobre, plomo, mercurio y cistina",
  ["Enfermedad de Wilson","Intoxicación por cobre","Cistinuria","Artritis reumatoide severa"],["oral"],
  {"adulto":"Wilson: 250-500 mg c/6h en ayunas. Plomo: 25 mg/kg/día","ajusteRenal":"Reducir dosis"},
  ["Cáps 250 mg"],"Evitar durante lactancia","u11","c11_01",
  ea=["Náuseas","Proteinuria","Síndrome nefrótico","Mielosupresión","Lupus-like","Deficiencia de piridoxina"],
  ix=["Hierro/antiácidos: reducen absorción","Digoxina: reduce niveles"],
  ce=["Tomar en ayunas (1h antes de comida)","Suplementar piridoxina 25 mg/día","Proteinuria y hemograma quincenal al inicio","Alergia cruzada con penicilina posible"]),

M("antidoto","deferasirox_antidoto","Deferasirox (antídoto)","Deferasirox",["Exjade","Jadenu"],"Quelante oral de hierro",
  "Quelante tridentado oral de hierro con alta selectividad por Fe3+. Vida media larga permite dosis única diaria",
  ["Sobrecarga transfusional crónica de hierro","Talasemia mayor politransfundida","Anemia falciforme con sobrecarga"],["oral"],
  {"adulto":"Inicio: 20 mg/kg/día (comp dispersable) o 14 mg/kg/día (comp recubierto). Ajustar según ferritina","pediatrico":"≥2 años: misma dosis por peso"},
  ["Comp dispersable 125, 250, 500 mg","Comp recubierto 90, 180, 360 mg"],"Evitar durante lactancia","u11","c11_01",
  ea=["Nefrotoxicidad (aumento creatinina)","Hepatotoxicidad","Diarrea","Náuseas","Erupción cutánea","Pérdida auditiva"],
  ce=["Creatinina sérica mensual","Función hepática mensual","Audiometría y oftalmología anual","Comp dispersable: disolver en agua/jugo antes de tomar"]),

M("antidoto","deferiprone","Deferiprona","Deferiprona",["Ferriprox"],"Quelante oral de hierro bidentado",
  "Quelante bidentado oral de Fe3+. Penetra bien en miocardio. Especialmente útil para siderosis cardíaca",
  ["Sobrecarga de hierro en talasemia mayor cuando deferoxamina contraindicada o insuficiente","Siderosis cardíaca"],["oral"],
  {"adulto":"25 mg/kg c/8h (75 mg/kg/día). Máx 100 mg/kg/día"},
  ["Comp 500 mg","Sol oral 100 mg/mL"],"Evitar durante lactancia","u11","c11_01",
  ea=["Agranulocitosis (1-2%)","Neutropenia","Artropatía","Náuseas","Dolor abdominal","Coloración rojiza orina"],
  ce=["Hemograma SEMANAL obligatorio (agranulocitosis)","Suspender si neutrófilos <1500","Ferritina cada 2-3 meses","Puede combinarse con deferoxamina en terapia intensiva"]),

M("antidoto","leucovorina","Leucovorina (ácido folínico)","Leucovorina cálcica",["Wellcovorin"],"Rescate folínico",
  "Forma reducida de ácido fólico que no requiere dihidrofolato reductasa. Rescata células normales de toxicidad por metotrexato",
  ["Rescate post-metotrexato alta dosis","Toxicidad por metotrexato","Anemia megaloblástica por déficit de folato"],["oral","IV","IM"],
  {"adulto":"Rescate MTX: 15 mg/m² c/6h x10 dosis, inicio 24h post-MTX. Ajustar según niveles de MTX"},
  ["Comp 5, 15, 25 mg","Vial 50, 100, 200, 350 mg"],"Compatible","u11","c11_01",
  ea=["Reacciones alérgicas (raro)","Náuseas (oral)"],
  ix=["Metotrexato: antagoniza toxicidad (uso terapéutico)","Fluorouracilo: potencia efecto antitumoral","Fenobarbital: puede reducir eficacia anticonvulsivante"],
  ce=["Iniciar DENTRO de 24h post-MTX (crítico)","Monitorizar niveles de MTX sérico","Continuar hasta MTX <0.05 µmol/L","Hidratación y alcalinización urinaria concomitantes"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con agua estéril","velocidadAdministracion":"IV en bolo o infusión según protocolo","estabilidad":"24h a TA reconstituido"}),

M("antidoto","glucarpidasa","Glucarpidasa","Glucarpidasa",["Voraxaze"],"Enzima que degrada metotrexato",
  "Carboxipeptidasa G2 recombinante. Degrada metotrexato en metabolitos inactivos (DAMPA y glutamato)",
  ["Toxicidad por metotrexato con niveles tóxicos y fallo renal"],["IV"],
  {"adulto":"50 U/kg IV dosis única"},
  ["Vial 1000 U"],"Datos insuficientes","u11","c11_01",
  ea=["Parestesias","Rubor","Cefalea","Hipotensión","Reacciones alérgicas"],
  ce=["Dosis única IV","No administrar leucovorina 2h antes ni después","Niveles de MTX post-glucarpidasa requieren ensayo cromatográfico (DAMPA interfiere con inmunoensayo)","Uso de última línea en toxicidad grave"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con 1 mL SF","velocidadAdministracion":"Bolo IV en 5 minutos","estabilidad":"Usar inmediatamente"}),

M("antidoto","levocarnitina_antidoto","Levocarnitina (antídoto)","Levocarnitina",["Carnitor"],"Cofactor mitocondrial",
  "L-carnitina facilita transporte de ácidos grasos a mitocondria. Contrarresta toxicidad mitocondrial del valproato",
  ["Toxicidad por valproato (hiperamonemia, hepatotoxicidad)","Deficiencia de carnitina"],["oral","IV"],
  {"adulto":"Toxicidad VPA: 100 mg/kg IV (máx 6 g), luego 50 mg/kg c/8h. Oral: 330 mg-1 g c/8h"},
  ["Comp 330 mg","Sol oral 100 mg/mL","Amp 200 mg/mL x 5 mL"],"Compatible","u11","c11_01",
  ea=["Náuseas","Diarrea","Olor corporal a pescado","Dolor abdominal"],
  ce=["Monitorizar amonio sérico","IV lento en 2-3 min o en infusión","Puede ser coadyuvante en hiperamonemia hepática","Evaluar carnitina sérica si deficiencia sospechada"],
  emb="B",
  pp={"dilucion":"Puede diluir en SF o SG5%","velocidadAdministracion":"IV lento en 2-3 minutos o infusión en 30 min","estabilidad":"24h a TA diluido"}),

M("antidoto","digibind","Anticuerpos anti-digoxina","Fragmentos Fab antidigoxina",["DigiFab","Digibind"],"Antídoto específico para digitálicos",
  "Fragmentos Fab de anticuerpos ovinos anti-digoxina. Se unen a digoxina libre impidiendo efecto en Na+/K+ ATPasa",
  ["Intoxicación digitálica potencialmente mortal","Arritmias graves por digoxina","K+ >5 mEq/L en intoxicación digitálica"],["IV"],
  {"adulto":"Dosis según nivel de digoxina o cantidad ingerida. Empírico: 10-20 viales si desconocido"},
  ["Vial 40 mg (neutraliza ~0.5 mg digoxina)"],"Datos insuficientes","u11","c11_01",
  ea=["Reacción alérgica","Hipopotasemia rápida","Empeoramiento IC (al revertir digital)","Fiebre"],
  ix=["Digoxina: se une formando complejo inactivo","Niveles de digoxina: se elevan falsamente post-administración (medir digoxina libre)"],
  ce=["Dosis según fórmula: viales = [digoxina sérica x peso (kg)] / 100","Monitorizar K+ frecuentemente (cae rápido)","Puede empeorar IC al revertir efecto digitálico","Respuesta en 30 min"],
  emb="C",
  pp={"reconstitucion":"Reconstituir cada vial con 4 mL agua estéril","dilucion":"Diluir en SF a volumen conveniente","velocidadAdministracion":"Infusión IV en 30 min (puede bolo si paro)","estabilidad":"4h refrigerado reconstituido"}),

M("antidoto","octreotida_antidoto","Octreótida (antídoto)","Octreótida",["Sandostatin (antídoto)"],"Análogo de somatostatina como antídoto",
  "Inhibe secreción de insulina. Revierte hipoglucemia refractaria por sulfonilureas cuando glucosa IV es insuficiente",
  ["Hipoglucemia refractaria por sulfonilureas","Hipoglucemia por insulinomas"],["SC","IV"],
  {"adulto":"50-100 mcg SC/IV c/6-12h","pediatrico":"1-2 mcg/kg c/6h"},
  ["Amp 50, 100, 500 mcg/mL"],"Compatible con precaución","u11","c11_01",
  ea=["Dolor abdominal","Diarrea/esteatorrea","Hiperglucemia","Bradicardia","Dolor en sitio inyección"],
  ce=["Monitorizar glucemia horaria","Útil cuando la glucosa IV no mantiene euglucemia","Puede repetir cada 6-12h","Complementa, no reemplaza glucosa IV"],
  emb="B",
  pp={"dilucion":"Puede diluir en SF","velocidadAdministracion":"IV lento en 3 minutos o SC","estabilidad":"24h a TA diluido"}),

M("antidoto","lipidos_iv_antidoto","Emulsión lipídica 20% (antídoto)","Emulsión lipídica IV",["Intralipid 20% (antídoto)"],"Antídoto para toxicidad por anestésicos locales",
  "Emulsión lipídica que actúa como sumidero lipídico ('lipid sink') atrapando fármacos lipofílicos. Restaura metabolismo cardíaco",
  ["Toxicidad sistémica por anestésicos locales (LAST)","Intoxicación por fármacos lipofílicos (betabloqueantes, calcioantagonistas)"],["IV"],
  {"adulto":"Bolo 1.5 mL/kg de intralipid 20%, luego infusión 0.25 mL/kg/min x30-60 min. Repetir bolo si inestabilidad"},
  ["Bolsa 100, 250, 500 mL al 20%"],"No aplica (emergencia)","u11","c11_01",
  ea=["Hipertrigliceridemia transitoria","Pancreatitis (raro)","Interferencia analítica en laboratorio"],
  ce=["DEBE estar disponible donde se usen anestésicos locales","Protocolo LAST: bolo + infusión","Puede repetir bolo x2","Máx 12 mL/kg en 1h","Continuar RCP durante administración"],
  emb="C",
  pp={"velocidadAdministracion":"Bolo IV rápido, luego infusión 0.25 mL/kg/min","estabilidad":"24h tras abrir"}),

M("antidoto","obidoxima","Obidoxima","Obidoxima",["Toxogonin"],"Reactivador de colinesterasa (oxima)",
  "Oxima que reativa acetilcolinesterasa inhibida por organofosforados. Más usada en Europa que pralidoxima",
  ["Intoxicación por organofosforados (complemento a atropina)"],["IV","IM"],
  {"adulto":"250 mg IV lento, repetir 250 mg en 2h si necesario. Máx 750 mg en primeras 24h"},
  ["Amp 250 mg/mL"],"Datos insuficientes","u11","c11_01",
  ea=["Náuseas","Mareo","Taquicardia","Cefalea","Alteraciones visuales","Elevación CPK"],
  ce=["Administrar LO ANTES POSIBLE (antes de envejecimiento de enzima)","Siempre junto con atropina","IV lento (1-2 min)","Ineficaz si transcurridas >36h post-exposición"],
  emb="C",
  pp={"velocidadAdministracion":"IV lento en 1-2 minutos","estabilidad":"Usar inmediatamente"}),

M("antidoto","silibinina","Silibinina","Silibinina",["Legalon SIL"],"Antídoto para intoxicación por Amanita",
  "Flavonolignano del cardo mariano. Inhibe captación hepática de amatoxinas y protege hepatocito",
  ["Intoxicación por Amanita phalloides (seta mortal)"],["IV"],
  {"adulto":"5 mg/kg IV en 1h, luego 20 mg/kg/día en infusión continua durante 5 días"},
  ["Vial 350 mg"],"Datos insuficientes","u11","c11_01",
  ea=["Rubor","Sensación de calor","Náuseas"],
  ce=["Iniciar lo antes posible tras ingestión de Amanita","Junto con medidas de soporte hepático","Monitorizar función hepática, coagulación, glucosa intensivamente","Trasplante hepático si fallo hepático fulminante"],
  emb="C",
  pp={"dilucion":"Diluir en SG5% 500 mL","velocidadAdministracion":"Carga en 1h, luego infusión continua","estabilidad":"6h a TA diluido"}),

M("antidoto","antiveneno_polivalente","Antiveneno polivalente","Suero antiofídico polivalente",["Antivipmyn"],"Antídoto para mordedura de serpiente",
  "Fragmentos F(ab')2 de inmunoglobulinas equinas contra venenos de serpientes regionales. Neutraliza toxinas hemorrágicas y neurotóxicas",
  ["Mordedura de serpiente venenosa con signos de envenenamiento"],["IV"],
  {"adulto":"4-12 viales IV según severidad. Grave: hasta 20+ viales","pediatrico":"Misma dosis que adulto (dosis según veneno, no peso)"},
  ["Vial liofilizado + diluyente"],"No aplica (emergencia)","u11","c11_01",
  ea=["Reacción anafiláctica/anafilactoide","Enfermedad del suero (7-14 días)","Fiebre","Urticaria"],
  ix=["Antihistamínicos: premedicación recomendada"],
  ce=["Premedicar con antihistamínicos y corticoides","Test de sensibilidad NO predice anafilaxia (no retrasar)","Dosis según gravedad clínica, no peso","Tener adrenalina lista","Monitorizar coagulación post-antiveneno"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto, agitar suavemente","dilucion":"Diluir en 250-500 mL SF","velocidadAdministracion":"Inicio lento 25 mL/h x15 min, si tolera aumentar","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("antidoto","antitoxina_botulinica","Antitoxina botulínica","Antitoxina botulínica heptavalente",["BAT"],"Antídoto para botulismo",
  "Anticuerpos equinos contra toxinas botulínicas tipo A-G. Neutraliza toxina circulante libre",
  ["Botulismo alimentario","Botulismo por heridas","Botulismo iatrogénico"],["IV"],
  {"adulto":"1 vial IV (contiene Ac contra 7 serotipos). Dosis única","pediatrico":"10% de dosis adulto en neonatos (BabyBIG para botulismo infantil)"},
  ["Vial dosis única"],"Datos insuficientes","u11","c11_01",
  ea=["Reacción anafiláctica","Enfermedad del suero","Fiebre","Cefalea","Náuseas","Prurito"],
  ce=["Administrar LO ANTES POSIBLE (neutraliza solo toxina libre, no unida)","Premedicación con antihistamínicos","Solo neutraliza toxina circulante (no revierte parálisis establecida)","Obtener de centros de referencia/CDC"],
  emb="C",
  pp={"dilucion":"Diluir 1:10 en SF","velocidadAdministracion":"Inicio 0.5 mL/min, incrementar gradualmente hasta 2 mL/min","estabilidad":"Usar inmediatamente"}),

M("antidoto","nitrito_sodio","Nitrito de sodio","Nitrito de sodio",["Kit cianuro"],"Antídoto para cianuro (parte del kit)",
  "Genera metahemoglobina que compite con citocromo oxidasa por el cianuro, formando cianometahemoglobina",
  ["Intoxicación por cianuro (parte del kit clásico de 3 componentes)"],["IV"],
  {"adulto":"300 mg (10 mL al 3%) IV en 2-4 min","pediatrico":"0.2 mL/kg de sol 3% (6 mg/kg), máx 300 mg"},
  ["Amp 300 mg/10 mL (3%)"],"No aplica (emergencia)","u11","c11_01",
  ea=["Metahemoglobinemia","Hipotensión","Taquicardia","Náuseas","Vómitos","Cianosis"],
  ix=["Hidroxocobalamina: alternativa más segura (no genera MetHb)"],
  ce=["Genera MetHb intencionalmente (10-30%)","PRECAUCIÓN en víctimas de incendio (ya con MetHb por CO)","Monitorizar MetHb y SatO2","Seguir con tiosulfato de sodio"],
  emb="C",
  pp={"velocidadAdministracion":"IV en 2-4 minutos","estabilidad":"Proteger de la luz"}),

M("antidoto","tiosulfato_sodio","Tiosulfato de sodio","Tiosulfato de sodio",["Tiosulfato"],"Antídoto para cianuro (donante de azufre)",
  "Provee azufre para la rodanasa hepática que convierte cianuro en tiocianato no tóxico eliminado por riñón",
  ["Intoxicación por cianuro (parte del kit)","Calcifilaxis","Extravasación de cisplatino"],["IV"],
  {"adulto":"12.5 g (50 mL al 25%) IV en 10-20 min","pediatrico":"400 mg/kg (1.65 mL/kg al 25%), máx 12.5 g"},
  ["Amp 12.5 g/50 mL (25%)"],"No aplica (emergencia)","u11","c11_01",
  ea=["Náuseas","Vómitos","Hipotensión (si IV rápido)"],
  ce=["Administrar DESPUÉS del nitrito de sodio en kit clásico","Puede usarse solo si hidroxocobalamina no disponible","Puede repetir a mitad de dosis en 30 min","Más seguro que nitrito: no genera MetHb"],
  emb="C",
  pp={"velocidadAdministracion":"IV en 10-20 minutos","estabilidad":"Almacenar a TA protegido de luz"}),

M("antidoto","folinato_calcico","Folinato cálcico","Folinato cálcico",["Lederfolin"],"Rescate folínico alternativo",
  "Sal cálcica del ácido 5-formiltetrahidrofólico. Equivalente a leucovorina para rescate post-metotrexato",
  ["Rescate post-metotrexato alta dosis","Potenciación de 5-FU en cáncer colorrectal"],["IV","oral"],
  {"adulto":"Rescate MTX: 15 mg/m² c/6h IV. 5-FU: 200 mg/m² IV pre-5-FU"},
  ["Amp 50, 100, 300 mg","Comp 15 mg"],"Compatible","u11","c11_01",
  ea=["Reacciones alérgicas (raro)"],
  ce=["Equivalente terapéutico a leucovorina","Iniciar a las 24h post-MTX","Ajustar según niveles de MTX sérico","Mayor potenciación de toxicidad de 5-FU (vigilar mucositis)"],
  emb="C",
  pp={"reconstitucion":"Si polvo: reconstituir con agua estéril","velocidadAdministracion":"IV en bolo o infusión según protocolo","estabilidad":"24h refrigerado"}),

M("antidoto","deferoxamina_aguda","Deferoxamina (aguda)","Deferoxamina",["Desferal (aguda)"],"Quelante de hierro para intoxicación aguda",
  "Quelante hexadentado de Fe3+ para intoxicación aguda por hierro. Forma ferrioxamina eliminada por riñón (orina color vin rosé)",
  ["Intoxicación aguda por hierro (Fe sérico >500 mcg/dL o síntomas graves)"],["IV","IM"],
  {"adulto":"15 mg/kg/h IV continua. Máx 6-8 g/día","pediatrico":"15 mg/kg/h IV (mismo que adulto por peso)"},
  ["Vial 500 mg, 2 g polvo"],"Datos insuficientes","u11","c11_01",
  ea=["Hipotensión (IV rápido)","Orina color vin rosé","SDRA (infusiones prolongadas >24h)","Ototoxicidad","Reacciones alérgicas"],
  ce=["Máx velocidad 15 mg/kg/h (hipotensión si más rápido)","Orina rosada indica quelación activa","Limitar infusión a <24h (riesgo SDRA)","Monitorizar PA, función pulmonar"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con 5 mL agua estéril por 500 mg","dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"Máx 15 mg/kg/hora IV","estabilidad":"24h a TA reconstituido"}),

# ── c11_02 Fármacos de Emergencia (+15) ──
M("","adenosina","Adenosina","Adenosina",["Adenocor"],"Antiarrítmico endógeno",
  "Nucleósido endógeno que deprime nodo AV transitoriamente. Interrumpe circuitos de reentrada que involucran nodo AV",
  ["Taquicardia supraventricular paroxística (TSVP)","Diagnóstico diferencial de taquicardias de complejo estrecho"],["IV"],
  {"adulto":"6 mg IV rápido. Si no responde en 1-2 min: 12 mg. Puede repetir 12 mg x1","pediatrico":"0.1 mg/kg (máx 6 mg). 2ª dosis: 0.2 mg/kg (máx 12 mg)"},
  ["Amp 6 mg/2 mL","Vial 30 mg/10 mL"],"Compatible (t½ ultracorta)","u11","c11_02",
  ci=["Bloqueo AV 2°-3° (sin marcapasos)","Síndrome del seno enfermo","Asma severa","Hipersensibilidad"],
  ea=["Asistolia transitoria (segundos)","Rubor facial","Disnea","Opresión torácica","Cefalea","Bradicardia"],
  ix=["Dipiridamol: potencia efecto (usar 3 mg como dosis inicial)","Teofilina/cafeína: antagonizan efecto","Carbamazepina: mayor bloqueo AV"],
  ce=["Administrar en bolo IV lo más rápido posible","Seguir con flush de 20 mL SF rápido","Acceso venoso lo más proximal posible (antecubital)","Avisar al paciente sobre sensación transitoria desagradable","Monitorización ECG continua"],
  emb="C",
  pp={"velocidadAdministracion":"Bolo IV rápido en 1-2 segundos seguido de flush 20 mL SF","estabilidad":"No requiere dilución"}),

M("","amiodarona_emergencia","Amiodarona (emergencia)","Amiodarona",["Cordarone (emergencia)"],"Antiarrítmico clase III para emergencias",
  "Antiarrítmico con propiedades de las 4 clases de Vaughan-Williams. En emergencia: TV/FV refractarias a desfibrilación",
  ["FV/TV sin pulso refractaria a desfibrilación","TV con pulso hemodinámicamente estable"],["IV"],
  {"adulto":"Paro: 300 mg IV push diluido en 20 mL SG5%. Si persiste: 150 mg. Con pulso: 150 mg en 10 min, luego 1 mg/min x6h, luego 0.5 mg/min"},
  ["Amp 150 mg/3 mL"],"Evitar durante lactancia","u11","c11_02",
  ci=["Hipersensibilidad al yodo","Bradicardia sinusal severa","Bloqueo AV sin marcapasos","Shock cardiogénico"],
  ea=["Hipotensión","Bradicardia","Flebitis (venas periféricas)","Prolongación QT","Toxicidad pulmonar/hepática/tiroidea (uso prolongado)"],
  ix=["Digoxina: aumenta niveles 70%","Warfarina: aumenta INR","Fármacos que prolongan QT: riesgo torsades","Betabloqueantes/calcioantagonistas: bradicardia aditiva"],
  ce=["Preferir vía central (flebitis periférica)","En paro: push IV (no infusión)","Con pulso: carga 150 mg en 10 min","Puede causar hipotensión (infundir lentamente)","Monitorización ECG continua"],
  emb="D",
  pp={"dilucion":"En paro: 300 mg en 20 mL SG5%. Con pulso: 150 mg en 100 mL SG5%","velocidadAdministracion":"Paro: push IV. Con pulso: 150 mg en 10 min, luego 1 mg/min x6h","estabilidad":"24h en SG5%, NO usar SF (precipita)"}),

M("","lidocaina_emergencia","Lidocaína (emergencia)","Lidocaína",["Xilocaína (emergencia)"],"Antiarrítmico clase Ib",
  "Bloquea canales de Na+ en tejido isquémico preferentemente. Alternativa a amiodarona en TV/FV",
  ["TV/FV refractaria (alternativa a amiodarona)","TV monomórfica con pulso"],["IV"],
  {"adulto":"Bolo 1-1.5 mg/kg. Puede repetir 0.5-0.75 mg/kg c/5-10 min (máx 3 mg/kg). Infusión: 1-4 mg/min"},
  ["Amp 1% (10 mg/mL)","Amp 2% (20 mg/mL)","Vial 4% para mezcla"],"Compatible con precaución","u11","c11_02",
  ci=["Bloqueo AV 2°-3°","Síndrome de Stokes-Adams","Hipersensibilidad a amidas","Bradicardia severa"],
  ea=["Convulsiones (toxicidad SNC)","Confusión","Parestesias peribucales","Bradicardia","Hipotensión","Paro cardíaco (sobredosis)"],
  ix=["Betabloqueantes: mayor riesgo toxicidad","Amiodarona: precaución en combinación","Inhibidores CYP1A2: aumentan niveles"],
  ce=["Monitorizar ECG y nivel de conciencia continuamente","Signos precoces de toxicidad: adormecimiento peribucal, mareo","Reducir velocidad infusión tras 24h","Ajustar en IC y hepatopatía"],
  emb="B",
  pp={"dilucion":"Puede administrar sin diluir para bolo. Infusión: 1-4 mg/mL en SG5%","velocidadAdministracion":"Bolo: en 1-2 min. Infusión: 1-4 mg/min","estabilidad":"24h a TA diluido"}),

M("","isoprenalina","Isoprenalina (isoproterenol)","Isoprenalina",["Isuprel"],"Agonista beta puro",
  "Agonista beta-1 y beta-2 no selectivo. Aumenta FC, contractilidad y conduce por nodo AV. Sin efecto alfa",
  ["Bradicardia sintomática refractaria a atropina","Torsades de pointes (hasta marcapasos)","Broncoespasmo severo refractario"],["IV"],
  {"adulto":"Infusión: 2-10 mcg/min, titular según FC"},
  ["Amp 0.2 mg/mL"],"Datos insuficientes","u11","c11_02",
  ci=["Taquiarritmias","Intoxicación digitálica","Angina inestable"],
  ea=["Taquicardia","Arritmias","Hipotensión (vasodilatación beta-2)","Temblor","Cefalea","Angor"],
  ix=["Halogenados: arritmias","Betabloqueantes: antagonismo","Simpaticomiméticos: taquicardia aditiva"],
  ce=["Solo infusión continua con bomba","Monitorización ECG y TA continua","Aumentar FC sin sobrepasar 100-110 lpm","Uso temporal hasta marcapasos"],
  emb="C",
  pp={"dilucion":"1 mg en 250 mL SG5% (4 mcg/mL)","velocidadAdministracion":"Infusión 2-10 mcg/min, titular","estabilidad":"24h diluido"}),

M("","glucagon_emergencia","Glucagón (emergencia)","Glucagón",["GlucaGen"],"Hormona hiperglucemiante de emergencia",
  "Hormona peptídica que estimula glucogenólisis y gluconeogénesis hepáticas. También tiene efecto inotrópico y cronotrópico positivo",
  ["Hipoglucemia severa (incapacidad de ingesta oral)","Sobredosis de betabloqueantes","Sobredosis de calcioantagonistas"],["IM","IV","SC"],
  {"adulto":"Hipoglucemia: 1 mg IM/SC/IV. Beta-bloq OD: 3-10 mg IV, luego 1-5 mg/h infusión","pediatrico":"<25 kg: 0.5 mg. ≥25 kg: 1 mg"},
  ["Kit 1 mg polvo + jeringa diluyente"],"Compatible","u11","c11_02",
  ci=["Feocromocitoma","Insulinoma","Glucagonoma"],
  ea=["Náuseas","Vómitos","Hiperglucemia","Hipopotasemia","Taquicardia"],
  ix=["Warfarina: puede aumentar INR","Insulina: antagonismo","Indometacina: puede reducir respuesta hiperglucémica"],
  ce=["Eficacia depende de reservas hepáticas de glucógeno (ineficaz si deplecionadas)","Respuesta en 10-15 min IM, 1-2 min IV","Dar carbohidratos orales al despertar","En OD beta-bloq: dosis mucho mayores (3-10 mg)"],
  emb="B",
  pp={"reconstitucion":"Reconstituir con diluyente provisto","velocidadAdministracion":"IV en 1 minuto. Infusión según indicación","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","hidrocortisona_emergencia","Hidrocortisona (emergencia)","Hidrocortisona succinato",["Solu-Cortef"],"Corticoide de emergencia",
  "Corticosteroide de acción rápida. Efecto antiinflamatorio e inmunosupresor. Reposición fisiológica en crisis adrenal",
  ["Anafilaxia (2ª línea, post-adrenalina)","Crisis adrenal aguda","Broncoespasmo severo","Shock refractario"],["IV","IM"],
  {"adulto":"Crisis adrenal: 100 mg IV bolo, luego 50 mg c/6-8h. Anafilaxia: 200 mg IV. Asma: 100-500 mg IV","pediatrico":"1-2 mg/kg IV, máx 100 mg"},
  ["Vial 100, 250, 500 mg, 1 g"],"Compatible con precaución","u11","c11_02",
  ci=["Infecciones fúngicas sistémicas (relativa en emergencia)"],
  ea=["Hiperglucemia","Retención hídrica","HTA","Inmunosupresión","Úlcera péptica"],
  ix=["Insulina: antagonismo","AINEs: mayor riesgo ulcus","Diuréticos: hipopotasemia"],
  ce=["En crisis adrenal: NO demorar (puede ser mortal)","En anafilaxia: SIEMPRE después de adrenalina","Efecto antiinflamatorio tarda 4-6h","Puede administrar IM si no hay acceso IV"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con agua bacteriostática o SF","velocidadAdministracion":"Bolo IV en 30 seg a 1 min. Infusión en 20-30 min","estabilidad":"24h a TA reconstituido"}),

M("","terbutalina_emergencia","Terbutalina (emergencia)","Terbutalina",["Bricanyl (emergencia)"],"Beta-2 agonista SC para broncoespasmo severo",
  "Agonista beta-2 selectivo. Vía SC cuando el paciente no puede inhalar (broncoespasmo severo, status asmático)",
  ["Broncoespasmo agudo severo cuando inhalación es imposible","Status asmático","Hiperpotasemia aguda (off-label)"],["SC","IV"],
  {"adulto":"SC: 0.25 mg, puede repetir en 15-30 min (máx 0.5 mg en 4h). IV: 0.25-0.5 mg en 5 min"},
  ["Amp 0.5 mg/mL"],"Compatible con precaución","u11","c11_02",
  ci=["Taquiarritmias","Hipersensibilidad"],
  ea=["Taquicardia","Temblor","Palpitaciones","Hipopotasemia","Cefalea","Hiperglucemia"],
  ix=["Betabloqueantes: antagonismo","MAOIs: potencian efecto cardiovascular","Diuréticos: mayor hipopotasemia"],
  ce=["Vía SC cuando paciente no puede inhalar","Monitorizar FC y K+","Máx 0.5 mg en 4h SC","IV solo en UCI con monitorización"],
  emb="B",
  pp={"velocidadAdministracion":"SC o IV lento en 5 minutos","estabilidad":"Proteger de la luz"}),

M("","aminofilina_emergencia","Aminofilina (emergencia)","Aminofilina",["Aminofilina (emergencia)"],"Metilxantina IV para broncoespasmo",
  "Sal de teofilina con etilendiamina (80% teofilina). Inhibe PDE, antagoniza adenosina. Broncodilatación y estimulación respiratoria",
  ["Broncoespasmo severo refractario a beta-2 agonistas","Apnea neonatal"],["IV"],
  {"adulto":"Carga: 5-6 mg/kg IV en 20-30 min (omitir si ya usa teofilina). Mantenimiento: 0.5-0.7 mg/kg/h","pediatrico":"Carga igual. Mantenimiento: 1 mg/kg/h (niños) a 0.5 mg/kg/h (adolescentes)"},
  ["Amp 250 mg/10 mL"],"Compatible con precaución","u11","c11_02",
  ci=["Taquiarritmias no controladas","Convulsiones activas","Hipersensibilidad a xantinas"],
  ea=["Náuseas","Vómitos","Taquicardia","Arritmias","Convulsiones (niveles tóxicos)","Hipotensión","Temblor"],
  ix=["Cimetidina/eritromicina/quinolonas: aumentan niveles","Fenitoína/rifampicina: reducen niveles","Betabloqueantes: antagonismo parcial"],
  ce=["Rango terapéutico estrecho: 10-20 mcg/mL","Niveles séricos a las 12-24h de inicio","IV lento obligatorio (arritmias si rápido)","Ajustar en IC, hepatopatía, fumadores","Múltiples interacciones: revisar"],
  emb="C",
  pp={"dilucion":"Diluir en 100-250 mL SF o SG5%","velocidadAdministracion":"Carga en 20-30 min. Mantenimiento: infusión continua","estabilidad":"24h diluido a TA"}),

M("","dopamina_emergencia","Dopamina (emergencia)","Dopamina",["Intropin (emergencia)"],"Catecolamina dosis-dependiente",
  "Precursor de noradrenalina. Efectos dosis-dependientes: renal (1-3), inotrópico (3-10), vasopresor (>10 mcg/kg/min)",
  ["Shock cardiogénico","Bradicardia sintomática refractaria","Hipotensión post-RCP"],["IV"],
  {"adulto":"2-20 mcg/kg/min. Inotrópico: 5-10. Vasopresor: 10-20 mcg/kg/min"},
  ["Amp 200 mg/5 mL"],"Datos insuficientes","u11","c11_02",
  ci=["Taquiarritmias no corregidas","Feocromocitoma","FV"],
  ea=["Taquicardia","Arritmias","HTA","Vasoconstricción periférica","Necrosis por extravasación","Náuseas"],
  ix=["IMAO: crisis hipertensiva (reducir dosis a 1/10)","Halogenados: arritmias","Fenotiazinas: antagonizan efecto"],
  ce=["SIEMPRE con bomba de infusión","Preferir vía central","Si extravasación: fentolamina local","Monitorizar PA, FC, diuresis continuamente","No mezclar con bicarbonato (inactiva)"],
  emb="C",
  pp={"dilucion":"800 mg en 500 mL SG5% = 1600 mcg/mL. O 400 mg en 250 mL","velocidadAdministracion":"Infusión continua 2-20 mcg/kg/min con bomba","estabilidad":"24h diluido. Descartar si cambia color"}),

M("","fentolamina_emergencia","Fentolamina (emergencia)","Fentolamina",["Regitine (emergencia)"],"Bloqueante alfa-adrenérgico",
  "Bloquea receptores alfa-1 y alfa-2. Vasodilatación rápida. Uso en crisis hipertensiva por exceso de catecolaminas",
  ["Crisis hipertensiva por feocromocitoma","Extravasación de vasopresores (infiltración local)","Interacción IMAO-tiramina"],["IV"],
  {"adulto":"HTA: 2.5-5 mg IV c/5-15 min. Extravasación: 5-10 mg en 10 mL SF infiltrar local","pediatrico":"0.05-0.1 mg/kg IV, máx 5 mg"},
  ["Amp 5 mg/mL","Vial 10 mg"],"Datos insuficientes","u11","c11_02",
  ci=["Hipotensión","Cardiopatía isquémica","Hipersensibilidad"],
  ea=["Hipotensión","Taquicardia refleja","Arritmias","Mareo","Congestión nasal","Diarrea"],
  ix=["Adrenalina: paradójica hipotensión (invierte efecto alfa)","Vasopresores alfa: antagonismo"],
  ce=["Tener preparada en sala de cirugía de feocromocitoma","Monitorizar PA continuamente","Para extravasación: infiltrar en zona dentro de 12h","Taquicardia refleja: puede requerir betabloqueante"],
  emb="C",
  pp={"reconstitucion":"Si polvo: reconstituir con 1 mL agua estéril","velocidadAdministracion":"IV en bolo lento o infusión","estabilidad":"Usar inmediatamente"}),

M("","labetalol_emergencia","Labetalol (emergencia)","Labetalol",["Trandate (emergencia)"],"Alfa+beta bloqueante IV para emergencia hipertensiva",
  "Bloquea alfa-1 y beta-1/2. Relación alfa:beta IV = 1:7. Reduce PA sin taquicardia refleja. Seguro en embarazo",
  ["Emergencia hipertensiva","Preeclampsia/eclampsia","Disección aórtica (con vasodilatador)"],["IV"],
  {"adulto":"Bolo: 20 mg IV en 2 min, repetir 20-80 mg c/10 min (máx 300 mg). Infusión: 0.5-2 mg/min"},
  ["Amp 100 mg/20 mL"],"Compatible con precaución","u11","c11_02",
  ci=["Bradicardia severa","Bloqueo AV 2-3°","Asma","Shock cardiogénico","IC descompensada"],
  ea=["Hipotensión","Bradicardia","Broncoespasmo","Mareo","Náuseas","Fatiga","Hormigueo cuero cabelludo"],
  ix=["Calcioantagonistas no-DHP: bradicardia severa","Halogenados: hipotensión","Insulina: enmascara hipoglucemia"],
  ce=["Paciente en DECÚBITO (hipotensión ortostática)","PA cada 5 min durante titulación","Seguro en embarazo (elección en preeclampsia)","No suspender bruscamente","IV en bolo escalado o infusión"],
  emb="C",
  pp={"dilucion":"200 mg en 200 mL SG5% = 1 mg/mL, o sin diluir para bolos","velocidadAdministracion":"Bolo IV en 2 min. Infusión: 0.5-2 mg/min","estabilidad":"24h diluido a TA"}),

M("","nitroprusiato","Nitroprusiato de sodio","Nitroprusiato",["Nipride"],"Vasodilatador arterial y venoso directo",
  "Genera óxido nítrico (NO). Vasodilatación arterial y venosa. Inicio inmediato, duración 1-2 min. Metabolizado a cianuro",
  ["Emergencia hipertensiva severa","IC aguda con postcarga elevada","Disección aórtica (con betabloqueante)","Hipotensión controlada quirúrgica"],["IV"],
  {"adulto":"0.25-10 mcg/kg/min. Inicio 0.25, titular cada 5 min. Máx 10 mcg/kg/min y máx 48-72h"},
  ["Vial 50 mg polvo"],"Evitar durante lactancia","u11","c11_02",
  ci=["Coartación aórtica","Derivación arteriovenosa","Atrofia óptica de Leber","Insuficiencia hepática grave","Déficit de B12"],
  ea=["Toxicidad por cianuro (uso prolongado/dosis altas)","Hipotensión excesiva","Taquicardia refleja","Acidosis metabólica","Tiocianato tóxico (renal)"],
  ix=["Sildenafilo y otros iPDE5: hipotensión severa","Antihipertensivos: efecto aditivo"],
  ce=["PROTEGER DE LA LUZ (envolver en papel aluminio)","Monitorizar PA intraarterial continua","Titular con bomba de infusión","Si >3 mcg/kg/min >72h: medir cianuro/tiocianato","Tiosulfato puede co-infundir para prevenir toxicidad por CN"],
  emb="C",
  pp={"reconstitucion":"50 mg en 2-3 mL SG5%","dilucion":"Diluir en 250-1000 mL SG5% exclusivamente","velocidadAdministracion":"Infusión continua 0.25-10 mcg/kg/min con bomba","estabilidad":"24h protegido de luz. Descartar si azul/verde"}),

M("","noradrenalina_emergencia","Noradrenalina (emergencia)","Noradrenalina",["Levophed (emergencia)"],"Vasopresor de primera línea en shock séptico",
  "Catecolamina endógena. Agonista alfa-1 potente (vasoconstricción) con actividad beta-1 moderada (inotrópica). Sin beta-2",
  ["Shock séptico (primera línea)","Shock distributivo","Hipotensión refractaria"],["IV"],
  {"adulto":"0.05-0.4 mcg/kg/min (2-30 mcg/min). Inicio bajo, titular según PAM ≥65 mmHg"},
  ["Amp 4 mg/4 mL","Amp 8 mg/8 mL"],"Datos insuficientes","u11","c11_02",
  ci=["Hipotensión por hipovolemia no corregida","Trombosis vascular mesentérica/periférica (relativa)"],
  ea=["HTA severa","Bradicardia refleja","Arritmias","Isquemia periférica/digital","Necrosis por extravasación"],
  ix=["IMAO: crisis hipertensiva","Halogenados: arritmias","Betabloqueantes: HTA sin compensación"],
  ce=["VÍA CENTRAL obligatoria idealmente","Extravación: infiltrar fentolamina","Monitorizar PAM objetivo ≥65 mmHg","Titular con bomba de infusión","Corregir hipovolemia ANTES de iniciar"],
  emb="C",
  pp={"dilucion":"8 mg en 250 mL SG5% = 32 mcg/mL. O 16 mg en 250 mL para concentración doble","velocidadAdministracion":"Infusión continua con bomba, titular según PAM","estabilidad":"24h diluido. No usar si descolorado"}),

# ── c11_03 Antídotos para Síndromes Tóxicos (8) ──
M("antidoto","ciproheptadina","Ciproheptadina","Ciproheptadina",["Periactin"],"Antagonista serotoninérgico para síndrome serotoninérgico",
  "Antihistamínico H1 con potente actividad antiserotoninérgica (5-HT2A). Único antídoto específico para síndrome serotoninérgico",
  ["Síndrome serotoninérgico"],["oral"],
  {"adulto":"12 mg dosis inicial, luego 4-8 mg c/6h hasta resolución. Máx 32 mg/día"},
  ["Comp 4 mg","Jarabe 2 mg/5 mL"],"Compatible con precaución","u11","c11_03",
  ea=["Sedación","Aumento de apetito","Boca seca","Mareo"],
  ce=["Solo vía oral (triturar y por SNG si necesario)","Dosis inicial elevada: 12 mg","Complemento a benzodiazepinas y soporte","Suspender TODOS los serotoninérgicos"]),

M("antidoto","bromocriptina_snm","Bromocriptina (SNM)","Bromocriptina",["Parlodel (SNM)"],"Agonista dopaminérgico para SNM",
  "Agonista D2. Restaura transmisión dopaminérgica en SNM. Alternativa a dantroleno en síndrome neuroléptico maligno",
  ["Síndrome neuroléptico maligno"],["oral"],
  {"adulto":"2.5-5 mg c/8h oral o por SNG. Continuar 10 días post-resolución"},
  ["Comp 2.5 mg"],"Evitar durante lactancia","u11","c11_03",
  ea=["Náuseas","Hipotensión","Confusión","Alucinaciones"],
  ce=["Por SNG si paciente no puede tragar","Junto con medidas de soporte (enfriamiento, hidratación)","Continuar 10 días tras resolver (recaída si suspensión precoz)","Puede combinarse con dantroleno"]),

M("antidoto","dantroleno_snm","Dantroleno (SNM/HM)","Dantroleno",["Dantrium (SNM)"],"Relajante muscular para hipertermia maligna y SNM",
  "Inhibe liberación de Ca2+ del retículo sarcoplásmico. Bloquea contracción muscular. Tratamiento de hipertermia maligna",
  ["Hipertermia maligna","Síndrome neuroléptico maligno","Hipertermia severa por drogas"],["IV"],
  {"adulto":"HM: 2.5 mg/kg IV c/5 min hasta respuesta (máx 10 mg/kg). SNM: 1-2.5 mg/kg IV c/6h"},
  ["Vial 20 mg + 60 mL diluyente estéril"],"Datos insuficientes","u11","c11_03",
  ea=["Debilidad muscular generalizada","Hepatotoxicidad","Flebitis","Somnolencia","Diarrea"],
  ce=["HM: administrar rápidamente hasta cesar rigidez/hipertermia","Cada vial requiere 60 mL de agua: reconstituir MÚLTIPLES viales simultáneamente","Vigilar K+, mioglobina, CK","Hepatotoxicidad con uso prolongado oral"],
  emb="C",
  pp={"reconstitucion":"20 mg en 60 mL agua estéril sin bacteriostático. Agitar vigorosamente","velocidadAdministracion":"Bolo IV rápido (push)","estabilidad":"6h a TA, proteger de la luz"}),

M("antidoto","diazepam_emergencia","Diazepam (emergencia)","Diazepam",["Valium (emergencia)"],"Benzodiazepina para convulsiones y agitación tóxica",
  "Benzodiazepina de acción prolongada. Potencia GABA-A. Anticonvulsivante, ansiolítico, miorrelajante de emergencia",
  ["Convulsiones por tóxicos (cocaína, anfetaminas)","Agitación severa por estimulantes","Abstinencia alcohólica con convulsiones","Status epiléptico (2ª línea)"],["IV","rectal"],
  {"adulto":"5-10 mg IV c/5-10 min según necesidad. Máx 30 mg. Rectal: 10-20 mg","pediatrico":"0.2-0.5 mg/kg IV, máx 5 mg (<5 años) o 10 mg (>5 años)"},
  ["Amp 10 mg/2 mL","Gel rectal 5, 10, 20 mg"],"Compatible con precaución","u11","c11_03",
  ea=["Depresión respiratoria","Sedación excesiva","Hipotensión","Amnesia"],
  ix=["Depresores SNC: efecto aditivo","Opioides: depresión respiratoria severa"],
  ce=["IV lento: 5 mg/min (irritante venoso)","Vigilar respiración","Flumazenilo disponible","En intoxicación por estimulantes: PRIMERA LÍNEA antes de antipsicóticos"],
  emb="D",
  pp={"velocidadAdministracion":"IV máx 5 mg/minuto","estabilidad":"No diluir (precipita). Inyectar en vena grande"}),

M("antidoto","fenobarbital_emergencia","Fenobarbital (emergencia)","Fenobarbital",["Luminal (emergencia)"],"Barbitúrico anticonvulsivante",
  "Potencia inhibición GABA-A y bloquea receptores de glutamato. Anticonvulsivante de amplio espectro. Uso en status epiléptico refractario",
  ["Status epiléptico refractario a benzodiazepinas","Abstinencia alcohólica refractaria a BZD","Convulsiones neonatales"],["IV"],
  {"adulto":"Status: 15-20 mg/kg IV a 50-100 mg/min. Puede dar 5-10 mg/kg adicional","pediatrico":"Neonatal: 20 mg/kg, luego 5 mg/kg/dosis","ajusteRenal":"Reducir dosis","ajusteHepatico":"Reducir dosis"},
  ["Amp 200 mg/mL"],"Evitar durante lactancia","u11","c11_03",
  ea=["Depresión respiratoria","Hipotensión","Sedación prolongada","Laringoespasmo"],
  ix=["Depresores SNC: depresión respiratoria","Inductor CYP potente: reduce eficacia de múltiples fármacos"],
  ce=["Requiere soporte ventilatorio disponible","IV lento: máx 100 mg/min","Monitorizar respiración continuamente","Nivel terapéutico: 15-40 mcg/mL"],
  emb="D",
  pp={"dilucion":"Puede diluir en SF si necesario (precipita en solución ácida)","velocidadAdministracion":"Máx 50-100 mg/min IV","estabilidad":"30 min tras dilución"}),

M("antidoto","clonidina_abstinencia","Clonidina (abstinencia)","Clonidina",["Catapres (abstinencia)"],"Alfa-2 agonista para síndrome de abstinencia",
  "Agonista alfa-2 central que reduce descarga simpática. Alivia síntomas autonómicos de abstinencia opioide y alcohólica",
  ["Síndrome de abstinencia a opioides","Abstinencia alcohólica (coadyuvante)","Crisis hipertensiva"],["oral","transdermica"],
  {"adulto":"Abstinencia: 0.1-0.3 mg c/6-8h oral. Crisis HTA: 0.1-0.2 mg oral c/1h (máx 0.6 mg)"},
  ["Comp 0.1, 0.15, 0.3 mg","Parche transdérmico 0.1, 0.2, 0.3 mg/día"],"Evitar durante lactancia","u11","c11_03",
  ea=["Sedación","Boca seca","Hipotensión","Bradicardia","Rebote hipertensivo si suspensión brusca"],
  ix=["Betabloqueantes: bradicardia aditiva","Depresores SNC: sedación aditiva","Antidepresivos tricíclicos: reducen efecto"],
  ce=["NO suspender bruscamente (HTA de rebote)","Monitorizar PA y FC c/4-8h","Reducción gradual al alta","Complementa pero no sustituye manejo integral"]),

M("antidoto","lorazepam_emergencia","Lorazepam (emergencia)","Lorazepam",["Ativan (emergencia)"],"Benzodiazepina de elección en status epiléptico",
  "Benzodiazepina de acción intermedia. Primera línea en status epiléptico por mayor duración de efecto anticonvulsivante que diazepam",
  ["Status epiléptico (primera línea)","Agitación aguda","Convulsiones por eclampsia","Catatonia"],["IV","IM"],
  {"adulto":"Status: 0.1 mg/kg IV (máx 4 mg/dosis), puede repetir x1. Agitación: 1-2 mg IV/IM","pediatrico":"0.05-0.1 mg/kg IV (máx 4 mg)"},
  ["Amp 2 mg/mL, 4 mg/mL"],"Compatible con precaución","u11","c11_03",
  ea=["Depresión respiratoria","Sedación","Hipotensión","Amnesia"],
  ix=["Depresores SNC: efecto aditivo","Probenecid: aumenta niveles"],
  ce=["Primera línea en status epiléptico (AES/AAN)","Efecto anticonvulsivante más duradero que diazepam","IV lento: 2 mg/min","Refrigerar ampollas (estabilidad)","Puede dar IM si no hay acceso IV"],
  emb="D",
  pp={"dilucion":"Puede diluir 1:1 con SF","velocidadAdministracion":"IV máx 2 mg/min","estabilidad":"REFRIGERAR. 24h a TA fuera de nevera"}),

M("antidoto","naltrexona_emergencia","Naltrexona (emergencia)","Naltrexona",["ReVia (emergencia)"],"Antagonista opioide de larga acción",
  "Antagonista competitivo mu, kappa y delta opioide. Duración prolongada (24-72h). Prevención de recaídas en adicción",
  ["Prevención de recaídas en dependencia a opioides","Alcoholismo (reduce craving)"],["oral","IM"],
  {"adulto":"Oral: 50 mg/día. IM depot: 380 mg mensual"},
  ["Comp 50 mg","Vial IM depot 380 mg"],"Evitar durante lactancia","u11","c11_03",
  ea=["Náuseas","Cefalea","Mareo","Hepatotoxicidad (dosis altas)","Reacción en sitio IM","Disforia"],
  ix=["Opioides: bloquea completamente efecto analgésico","Puede precipitar abstinencia severa si opioides en sistema"],
  ce=["Verificar abstinencia opioide ≥7-10 días antes de iniciar","Prueba de naloxona previa recomendada","Función hepática basal y periódica","Portar tarjeta: 'en tratamiento con naltrexona' (emergencia analgésica)"],
  emb="C",
  pp={"velocidadAdministracion":"IM profunda glútea mensual","estabilidad":"Refrigerado hasta uso"}),

# ── c11_04 Soporte Vital Avanzado (7) ──
M("","adrenalina_autoinyector","Adrenalina autoinyector","Adrenalina",["EpiPen","Jext","Anapen"],"Autoinyector de adrenalina para anafilaxia",
  "Dispositivo precargado de adrenalina IM para autoinyección en anafilaxia fuera del hospital",
  ["Anafilaxia (autoaplicación prehospitalaria)","Reacciones alérgicas graves con riesgo anafiláctico"],["IM"],
  {"adulto":"0.3 mg IM (EpiPen). Repetir en 5-15 min si necesario","pediatrico":"15-30 kg: 0.15 mg (EpiPen Jr). >30 kg: 0.3 mg"},
  ["Autoinyector 0.15 mg (pediátrico)","Autoinyector 0.3 mg (adulto)"],"Compatible (emergencia)","u11","c11_04",
  ci=["Ninguna absoluta en anafilaxia (salvar la vida prevalece)"],
  ea=["Taquicardia","Palpitaciones","Temblor","Ansiedad","Palidez","Cefalea"],
  ix=["Betabloqueantes: pueden requerir dosis mayores de adrenalina","Antidepresivos tricíclicos: potencian efecto"],
  ce=["Enseñar técnica: muslo externo, atraviesa ropa","Sostener 10 segundos","Llamar emergencias DESPUÉS de inyectar","Verificar caducidad periódicamente","Siempre portar 2 autoinyectores"],
  emb="C"),

M("","vasopresina_rcp","Vasopresina RCP","Vasopresina",["Pitressin (RCP)"],"Vasopresor no adrenérgico en RCP",
  "Hormona antidiurética con potente efecto vasoconstrictor (receptores V1). Alternativa/complemento a adrenalina en paro cardíaco",
  ["Paro cardíaco (FV/TV/asistolia): alternativa a 1ª-2ª dosis de adrenalina","Shock vasodilatorio refractario"],["IV"],
  {"adulto":"Paro: 40 UI IV dosis única (reemplaza 1ª o 2ª dosis de adrenalina). Shock: 0.03-0.04 UI/min infusión"},
  ["Amp 20 UI/mL"],"No aplica (emergencia)","u11","c11_04",
  ci=["Ninguna en contexto de paro cardíaco"],
  ea=["Isquemia mesentérica/digital","Bradicardia","Hiponatremia","Vasoconstricción coronaria"],
  ix=["No interacciones relevantes en contexto de emergencia"],
  ce=["En paro: dosis ÚNICA de 40 UI (no repetir)","En shock: infusión baja dosis (no titular)","No reemplaza adrenalina completamente en guías actuales","Guardar en refrigeración"],
  emb="C",
  pp={"velocidadAdministracion":"Paro: bolo IV. Shock: infusión 0.03-0.04 UI/min","estabilidad":"Refrigerado. TA: usar en 24h"}),

M("","calcio_cloruro_rcp","Cloruro de calcio RCP","Cloruro de calcio",["CaCl2 (RCP)"],"Calcio IV de emergencia",
  "Aporta calcio ionizado rápidamente. 3x más calcio elemental que gluconato. Para hiperpotasemia, hipocalcemia, OD de calcioantagonistas",
  ["Hiperpotasemia severa con cambios ECG","Sobredosis de calcioantagonistas","Hipocalcemia sintomática","Hipermagnesemia severa"],["IV"],
  {"adulto":"10-20 mL de CaCl2 10% (1-2 g) IV lento en 10 min","pediatrico":"20 mg/kg (0.2 mL/kg de sol 10%), máx 1 g"},
  ["Amp 10% (100 mg/mL) x 10 mL"],"No aplica (emergencia)","u11","c11_04",
  ci=["Intoxicación digitálica (relativa: puede causar asistolia)","Hipercalcemia"],
  ea=["Necrosis tisular severa si extravasación","Bradicardia","Hipotensión (IV rápido)","Sensación de calor"],
  ix=["Digoxina: hipercalcemia potencia toxicidad","Bicarbonato: precipita (no mezclar)"],
  ce=["VÍA CENTRAL preferentemente (necrosis si extravasa)","IV MUY LENTO: bradicardia/asistolia si rápido","NO mezclar con bicarbonato en misma línea","3x más potente que gluconato de calcio","Monitorizar Ca++ y ECG"],
  emb="C",
  pp={"velocidadAdministracion":"IV lento en 10 minutos mínimo","estabilidad":"TA, proteger de calor"}),

M("","alteplasa_masivo","Alteplasa TEP masivo","Alteplasa",["Actilyse (TEP)"],"Trombolítico para TEP masivo",
  "Activador tisular del plasminógeno recombinante (rt-PA). Convierte plasminógeno en plasmina para lisar trombos",
  ["TEP masivo con inestabilidad hemodinámica","TEP submasivo con deterioro clínico"],["IV"],
  {"adulto":"100 mg IV en 2 horas. Alternativa: 0.6 mg/kg (máx 50 mg) en 15 min (régimen acelerado en paro)"},
  ["Vial 50 mg, 100 mg"],"Evitar durante lactancia","u11","c11_04",
  ci=["Hemorragia activa","ACV hemorrágico","Cirugía intracraneal <3 meses","Neoplasia intracraneal"],
  ea=["Hemorragia mayor","Hemorragia intracraneal","Arritmias de reperfusión","Angioedema (raro con IECA)"],
  ix=["Anticoagulantes: mayor riesgo sangrado","Antiagregantes: hemorragia aditiva"],
  ce=["Riesgo-beneficio: mortalidad TEP masivo >50% sin tratamiento","Suspender heparina durante infusión","Monitorizar sangrado activamente","NO punciones arteriales durante y 24h post","Reiniciar heparina cuando TTPa <2x normal"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con agua estéril provista","dilucion":"50 mg en 50 mL o no diluir","velocidadAdministracion":"100 mg en 2 horas. Acelerado: 50 mg en 15 min","estabilidad":"8h reconstituido refrigerado"}),

M("","efedrina_anestesia","Efedrina (anestesia)","Efedrina",["Efedrina"],"Simpaticomimético mixto para hipotensión anestésica",
  "Estimula liberación de noradrenalina endógena + efecto directo alfa y beta. Aumenta PA y FC. Efecto más suave que fenilefrina",
  ["Hipotensión durante anestesia raquídea/epidural","Hipotensión intraoperatoria","Broncoespasmo perioperatorio"],["IV"],
  {"adulto":"5-10 mg IV c/3-5 min según respuesta. Máx 50 mg"},
  ["Amp 50 mg/mL","Amp 30 mg/mL"],"Compatible con precaución","u11","c11_04",
  ci=["HTA severa","Tirotoxicosis","Glaucoma de ángulo cerrado"],
  ea=["Taquicardia","HTA","Arritmias","Náuseas","Cefalea","Temblor"],
  ix=["IMAO: crisis hipertensiva severa","Halogenados: arritmias","Oxitocina: HTA severa"],
  ce=["Bolos pequeños (5-10 mg) y titular","Taquifilaxia con dosis repetidas","Elección en hipotensión con bradicardia","Fenilefrina preferible si taquicardia"],
  emb="C",
  pp={"dilucion":"Puede diluir a 5 mg/mL con SF","velocidadAdministracion":"Bolo IV lento","estabilidad":"24h diluido a TA"}),

M("","etilefrina","Etilefrina","Etilefrina",["Effortil"],"Simpaticomimético para hipotensión ortostática",
  "Agonista alfa y beta-1. Aumenta PA por vasoconstricción y efecto inotrópico. Para hipotensión crónica y ortostática",
  ["Hipotensión ortostática sintomática","Hipotensión constitucional"],["oral","IV"],
  {"adulto":"Oral: 5-10 mg c/8h. IV emergencia: 1-2 mg IV lento"},
  ["Comp 5 mg","Gotas 7.5 mg/mL","Amp 10 mg/mL"],"Compatible con precaución","u11","c11_04",
  ci=["HTA severa","Hipertiroidismo","Feocromocitoma","Glaucoma de ángulo cerrado"],
  ea=["Taquicardia","Palpitaciones","Cefalea","Insomnio","Náuseas","Arritmias"],
  ix=["IMAO: potenciación severa","Betabloqueantes: antagonismo parcial","Antidepresivos tricíclicos: potenciación"],
  ce=["Tomar al despertar y antes de comidas","Evitar dosis vespertina (insomnio)","Medidas no farmacológicas complementarias","En ortostatismo: medias de compresión + aumento Na+/líquidos"],
  emb="C",
  pp={"velocidadAdministracion":"IV lento","estabilidad":"TA"}),

M("","bicarbonato_rcp","Bicarbonato de sodio RCP","Bicarbonato de sodio",["NaHCO3 (RCP)"],"Buffer para acidosis metabólica severa",
  "Buffer que neutraliza H+ y genera CO2 + agua. Corrige acidosis metabólica. En paro: solo si acidosis preexistente o hiperpotasemia",
  ["Acidosis metabólica severa (pH <7.1)","Hiperpotasemia severa","Intoxicación por tricíclicos","Intoxicación por salicilatos (alcalinización urinaria)"],["IV"],
  {"adulto":"Paro: 1 mEq/kg IV. Acidosis: según déficit de base. Intox TCA: 1-2 mEq/kg bolos, luego infusión","pediatrico":"1 mEq/kg IV (0.5 mEq/kg en neonatos con sol diluida)"},
  ["Amp 8.4% (1 mEq/mL) x 50 mL","Amp 7.5%"],"No aplica (emergencia)","u11","c11_04",
  ci=["Alcalosis metabólica","Hipopotasemia severa (empeora al corregir pH)","Hipocalcemia (reduce Ca++ ionizado)"],
  ea=["Alcalosis metabólica","Hipernatremia","Hipopotasemia","Hipocalcemia","Edema"],
  ix=["NO mezclar con calcio (precipita)","Puede inactivar catecolaminas en misma vía","Anfetaminas: aumenta reabsorción (reduce excreción)"],
  ce=["En paro: NO de rutina (solo si acidosis/hiperpotasemia preexistente)","Gasometría para guiar terapia","NO mezclar con CaCl2, dopamina, adrenalina","En intox TCA: mantener pH 7.45-7.55"],
  emb="C",
  pp={"velocidadAdministracion":"Bolo IV lento en 1-2 min. Infusión según protocolo","estabilidad":"TA"}),
]

NEW_CHAPTERS = {
    "c11_03": {
        "id": "c11_03",
        "nombre": "Antídotos para Síndromes Tóxicos",
        "drugIds": ["ciproheptadina","bromocriptina_snm","dantroleno_snm","diazepam_emergencia",
                     "fenobarbital_emergencia","clonidina_abstinencia","lorazepam_emergencia","naltrexona_emergencia"]
    },
    "c11_04": {
        "id": "c11_04",
        "nombre": "Soporte Vital Avanzado",
        "drugIds": ["adrenalina_autoinyector","vasopresina_rcp","calcio_cloruro_rcp","alteplasa_masivo",
                     "efedrina_anestesia","etilefrina","bicarbonato_rcp"]
    },
}

if __name__ == "__main__":
    print("=== U11 ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        add_chapter(cats, "u11", ch)
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
