#!/usr/bin/env python3
"""Add ~60 new drugs for U12 Fármacos Hospitalarios (parte B)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c12_04 Nutrición Parenteral (+8) ──
M("","lipidos_mct_lct","Lípidos MCT/LCT","Emulsión lipídica MCT/LCT",["Lipofundin MCT/LCT"],"Emulsión lipídica parenteral mixta",
  "Mezcla 50:50 de triglicéridos de cadena media (MCT) y larga (LCT). MCT se oxidan más rápido y no requieren carnitina",
  ["Aporte calórico en nutrición parenteral","Déficit de ácidos grasos esenciales"],["IV"],
  {"adulto":"1-2 g/kg/día (no exceder 2.5 g/kg/día). Inicio 0.5 g/kg/día"},
  ["Bolsa 250, 500 mL al 10% y 20%"],"Compatible","u12","c12_04",
  ci=["Hipertrigliceridemia severa (>400 mg/dL)","Alergia a soja/huevo","Shock severo"],
  ea=["Hipertrigliceridemia","Hepatoesteatosis","Fiebre","Reacciones alérgicas","Tromboflebitis"],
  ix=["Heparina: aclara triglicéridos (interfiere medición)"],
  ce=["Triglicéridos basales y c/48h","Infundir con NP total o separada","Proteger de la luz (vitaminas)","No exceder 0.15 g/kg/h (MCT/LCT)"],
  emb="C",
  pp={"velocidadAdministracion":"Máx 0.15 g/kg/h de lípidos","estabilidad":"24h tras abrir, proteger de la luz"}),

M("","lipidos_omega3","Lípidos omega-3","Emulsión lipídica omega-3",["Omegaven"],"Emulsión lipídica rica en EPA/DHA",
  "Aceite de pescado rico en omega-3 (EPA y DHA). Efecto antiinflamatorio. Para colestasis asociada a NP y como suplemento",
  ["Colestasis asociada a NP (pediátrica)","Suplemento lipídico con efecto antiinflamatorio"],["IV"],
  {"adulto":"0.1-0.2 g/kg/día como complemento o reemplazo parcial","pediatrico":"1 g/kg/día como monoterapia en colestasis por NP"},
  ["Vial 100 mL al 10%"],"Compatible","u12","c12_04",
  ci=["Alergia al pescado","Hipertrigliceridemia severa","Trastornos hemorrágicos"],
  ea=["Sabor a pescado","Hipertrigliceridemia","Prolongación sangrado"],
  ix=["Anticoagulantes: posible potenciación antiplaquetaria"],
  ce=["Revolucionó NP pediátrica (revierte colestasis)","Triglicéridos basales y periódicos","Proteger de la luz","Puede usarse solo o en combinación con otros lípidos"],
  emb="C",
  pp={"velocidadAdministracion":"Máx 0.5 mL/kg/h de Omegaven 10%","estabilidad":"24h tras abrir"}),

M("","smof_lipidos","SMOF Lípidos","Emulsión lipídica SMOF",["SMOFlipid"],"Emulsión lipídica de 4 aceites",
  "Mezcla de soja (30%), MCT (30%), oliva (25%) y pescado (15%). Perfil lipídico balanceado con menos peroxidación",
  ["Nutrición parenteral: aporte lipídico equilibrado"],["IV"],
  {"adulto":"1-2 g/kg/día. Máx 2 g/kg/día"},
  ["Bolsa 250, 500 mL al 20%"],"Compatible","u12","c12_04",
  ci=["Hipertrigliceridemia severa","Alergia a soja/huevo/pescado/cacahuete"],
  ea=["Hipertrigliceridemia","Elevación transaminasas","Reacciones alérgicas"],
  ix=["Similar a otros lípidos IV"],
  ce=["Perfil de 4 aceites: antiinflamatorio y antioxidante","Triglicéridos c/48h","Estándar actual en muchas UCI","Proteger de la luz"],
  emb="C",
  pp={"velocidadAdministracion":"Máx 0.15 g/kg/h","estabilidad":"24h tras abrir"}),

M("","glutamina_iv","Glutamina IV","L-alanil-L-glutamina",["Dipeptiven"],"Aminoácido condicionalmente esencial IV",
  "Dipéptido de glutamina. Combustible para enterocitos e inmunológicos. Condicionalmente esencial en críticos",
  ["Suplemento en NP para pacientes quirúrgicos/quemados","Mucositis por quimioterapia"],["IV"],
  {"adulto":"0.3-0.5 g/kg/día de dipéptido (equivale a 0.2-0.35 g/kg/día de glutamina)"},
  ["Vial 100 mL (200 mg/mL)"],"Compatible","u12","c12_04",
  ci=["Insuficiencia renal severa","Insuficiencia hepática severa (encefalopatía)","Fallo multiorgánico"],
  ea=["Elevación BUN","Náuseas","Hiperamonemia en fallo hepático"],
  ix=["No significativas"],
  ce=["Controvertido en fallo multiorgánico (estudio REDOXS: daño)","Beneficio en quemados y post-quirúrgicos","Añadir a la bolsa de NP","Monitorizar BUN y función renal"],
  emb="C",
  pp={"dilucion":"Añadir a bolsa de NP o diluir en 100 mL aminoácidos","velocidadAdministracion":"Con la NP, no en bolo","estabilidad":"Usar dentro de 24h tras mezcla"}),

M("","multivitaminico_iv","Multivitamínico IV","Vitaminas para NP",["Cernevit"],"Complejo vitamínico parenteral",
  "Contiene vitaminas A, D, E, C, B1, B2, B3, B5, B6, B8, B9, B12. Esencial en NP >7 días",
  ["Suplementación vitamínica en nutrición parenteral","Déficit vitamínico severo con malabsorción"],["IV"],
  {"adulto":"1 vial/día añadido a la NP"},
  ["Vial liofilizado"],"Compatible","u12","c12_04",
  ci=["Hipervitaminosis A o D","Hipersensibilidad"],
  ea=["Reacciones alérgicas (raro)","Hipervitaminosis A/D (si exceso)"],
  ix=["Metotrexato: ác. fólico puede interferir","Levodopa: piridoxina reduce eficacia"],
  ce=["Añadir a la bolsa de NP justo antes de infusión","Proteger de la luz (degrada vitaminas A, B2, B6)","Suplementar vitamina K por separado si indicado","No contiene vitamina K"],
  emb="A",
  pp={"reconstitucion":"Reconstituir con 5 mL agua estéril","dilucion":"Añadir a bolsa de NP","velocidadAdministracion":"Con la NP","estabilidad":"Proteger de luz. Usar dentro de 24h"}),

M("","oligoelementos_iv","Oligoelementos IV","Oligoelementos traza",["Addamel N"],"Elementos traza para NP",
  "Contiene zinc, cobre, manganeso, cromo, selenio, hierro, molibdeno, yodo, flúor. Esenciales en NP prolongada",
  ["Suplementación en NP","Prevención déficit de oligoelementos"],["IV"],
  {"adulto":"1 ampolla/día añadida a NP"},
  ["Amp 10 mL"],"Compatible","u12","c12_04",
  ci=["Colestasis obstructiva (acumulación cobre y manganeso)","Enfermedad de Wilson (cobre)"],
  ea=["Raramente adversos a dosis estándar","Acumulación en colestasis"],
  ix=["No significativas a dosis estándar"],
  ce=["Reducir o eliminar cobre y manganeso en colestasis","Zinc puede requerir suplemento adicional en quemados/diarrea","Añadir a NP antes de infusión","Selenio puede necesitar suplemento extra en UCI"],
  emb="A",
  pp={"dilucion":"Añadir a bolsa de NP","velocidadAdministracion":"Con la NP","estabilidad":"Usar dentro de 24h tras mezcla"}),

M("","fosfato_potasio_iv","Fosfato de potasio IV","Fosfato monopotásico/dipotásico",["KPhos IV"],"Electrolito para NP e hipofosfatemia",
  "Aporte IV de fósforo y potasio. Para hipofosfatemia moderada-severa y componente de NP",
  ["Hipofosfatemia moderada-severa","Componente de NP","Síndrome de realimentación"],["IV"],
  {"adulto":"Hipofosfatemia: 15-45 mmol fosfato en 250-500 mL en 4-6h según severidad"},
  ["Amp 15 mmol fosfato + 22 mEq K+ / 5 mL"],"Compatible","u12","c12_04",
  ci=["Hiperpotasemia","Hiperfosfatemia","Insuficiencia renal oligúrica"],
  ea=["Hiperpotasemia","Hipocalcemia","Calcificación metastásica","Flebitis"],
  ix=["Calcio IV: precipita (NO mezclar)","IECA/ARA-II: hiperpotasemia"],
  ce=["NO mezclar con calcio en misma línea (precipita fosfato cálcico)","Infusión lenta obligatoria","Monitorizar fosfato, calcio, potasio y función renal","En NP: calcular aporte total de K+"],
  emb="C",
  pp={"dilucion":"Diluir en SF o SG5%, mín 250 mL","velocidadAdministracion":"Infusión en 4-6 horas mínimo. NUNCA en bolo","estabilidad":"24h diluido"}),

M("","lipidos_oliva","Lípidos base oliva","Emulsión lipídica base oliva",["ClinOleic"],"Emulsión lipídica de aceite de oliva",
  "80% aceite de oliva + 20% soja. Rica en oleico (monoinsaturado). Menor peroxidación y menor efecto proinflamatorio que soja pura",
  ["Nutrición parenteral: aporte lipídico con menor inflamación"],["IV"],
  {"adulto":"1-2 g/kg/día. Máx 2 g/kg/día"},
  ["Bolsa 250, 500 mL al 20%"],"Compatible","u12","c12_04",
  ci=["Hipersensibilidad a soja/huevo","Hipertrigliceridemia severa"],
  ea=["Hipertrigliceridemia","Reacciones alérgicas (raro)"],
  ix=["Similar a otros lípidos IV"],
  ce=["Menor respuesta inflamatoria que lípidos de soja pura","Triglicéridos c/48h","Ampliamente usado en Europa","Proteger de la luz"],
  emb="C",
  pp={"velocidadAdministracion":"Máx 0.15 g/kg/h","estabilidad":"24h tras abrir"}),

# ── c12_05 Antineoplásicos (+20) ──
M("antineoplasico","rituximab","Rituximab","Rituximab",["MabThera","Rituxan"],"Anti-CD20 monoclonal",
  "Anticuerpo monoclonal quimérico anti-CD20. Depleciona linfocitos B. Piedra angular del tratamiento de linfomas B",
  ["Linfoma no Hodgkin","LLC","Artritis reumatoide","Granulomatosis con poliangeitis"],["IV","SC"],
  {"adulto":"375 mg/m² IV c/3 sem (linfoma). 1000 mg IV x2 (AR). SC: 1400 mg c/3 sem"},
  ["Vial 100 mg/10 mL","Vial 500 mg/50 mL","SC 1400 mg"],"Evitar durante lactancia","u12","c12_05",
  pp={"dilucion":"Diluir en SF o SG5% hasta 1-4 mg/mL","velocidadAdministracion":"1ª: 50 mg/h, incrementar 50 mg/h c/30 min (máx 400 mg/h). Siguientes: 100 mg/h, hasta 400 mg/h","estabilidad":"24h refrigerado, 24h a TA"}),

M("antineoplasico","bortezomib","Bortezomib","Bortezomib",["Velcade"],"Inhibidor del proteasoma",
  "Inhibe proteasoma 26S reversiblemente. Induce apoptosis de células plasmáticas. Pilar del tratamiento del mieloma múltiple",
  ["Mieloma múltiple","Linfoma del manto"],["SC","IV"],
  {"adulto":"1.3 mg/m² los días 1, 4, 8, 11 de ciclo 21d. SC preferida (menos neuropatía)"},
  ["Vial 3.5 mg polvo"],"Evitar durante lactancia","u12","c12_05",
  pp={"reconstitucion":"SC: 3.5 mg en 1.4 mL SF = 2.5 mg/mL. IV: 3.5 mg en 3.5 mL SF = 1 mg/mL","velocidadAdministracion":"IV bolo en 3-5 seg. SC: rotación de sitios","estabilidad":"8h a TA reconstituido"}),

M("antineoplasico","venetoclax","Venetoclax","Venetoclax",["Venclexta"],"Inhibidor de BCL-2",
  "Inhibidor selectivo de BCL-2 (proteína antiapoptótica). Induce apoptosis directa de células tumorales dependientes de BCL-2",
  ["LLC/SLL","LMA en combinación"],["oral"],
  {"adulto":"LLC: rampa semanal 20→50→100→200→400 mg/día. Mantener 400 mg/día","ajusteRenal":"Precaución en IR severa"},
  ["Comp 10, 50, 100 mg"],"Evitar durante lactancia","u12","c12_05",
  ea=["Síndrome de lisis tumoral (SLT)","Neutropenia","Diarrea","Náuseas","Infecciones respiratorias"],
  ce=["Riesgo alto de SLT: rampa de dosis OBLIGATORIA","Hidratación y alopurinol pre-inicio","Labs SLT: c/6-8h las primeras 24h de cada incremento","Tomar con alimentos"]),

M("antineoplasico","azacitidina","Azacitidina","Azacitidina",["Vidaza"],"Agente hipometilante",
  "Análogo de citidina. Se incorpora al ADN/ARN e inhibe ADN-metiltransferasa. Reexpresa genes supresores de tumores silenciados",
  ["Síndromes mielodisplásicos","LMA en no candidatos a QT intensiva"],["SC","IV"],
  {"adulto":"75 mg/m²/día SC o IV x7 días cada 28 días. Mínimo 4-6 ciclos para evaluar respuesta"},
  ["Vial 100 mg polvo"],"Evitar durante lactancia","u12","c12_05",
  pp={"reconstitucion":"Reconstituir con 4 mL agua estéril (agitar vigorosamente)","velocidadAdministracion":"SC: rotación sitios (>2.5 cm entre inyecciones). IV: infusión en 10-40 min","estabilidad":"SC: 8h refrigerado. IV: 1h a TA"}),

M("antineoplasico","citarabina","Citarabina","Citarabina (Ara-C)",["Cytosar"],"Antimetabolito pirimidínico",
  "Análogo de citidina. Inhibe ADN polimerasa alfa durante fase S. Pilar del tratamiento de leucemias agudas mieloides",
  ["LMA: inducción y consolidación","LLA","Linfoma del SNC (intratecal)"],["IV","SC","intratecal"],
  {"adulto":"Inducción LMA: 100-200 mg/m²/día x7d infusión continua. Alta dosis: 1-3 g/m² c/12h x4-6 dosis. IT: 50-70 mg"},
  ["Vial 100, 500 mg, 1 g, 2 g"],"Evitar durante lactancia","u12","c12_05",
  ea=["Mielosupresión severa","Síndrome cerebeloso (alta dosis)","Conjuntivitis","Mucositis","Náuseas","Síndrome Ara-C (fiebre, mialgias)"],
  ce=["Colirio corticoide profiláctico en alta dosis","Función cerebelosa pre-cada dosis alta","Hemograma diario durante inducción","Intratecal: sin conservante"],
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"Estándar: infusión continua 24h. Alta dosis: en 1-3h","estabilidad":"48h a TA diluido"}),

M("antineoplasico","temozolomida","Temozolomida","Temozolomida",["Temodal","Temodar"],"Agente alquilante oral",
  "Alquilante de 2ª generación. Profármaco que genera MTIC a pH fisiológico. Cruza barrera hematoencefálica",
  ["Glioblastoma multiforme","Astrocitoma anaplásico","Melanoma metastásico"],["oral","IV"],
  {"adulto":"GBM con RT: 75 mg/m²/día x42d. Adyuvante: 150-200 mg/m²/día x5d c/28d x6 ciclos"},
  ["Cáps 5, 20, 100, 140, 180, 250 mg","Vial 100 mg IV"],"Evitar durante lactancia","u12","c12_05",
  ea=["Mielosupresión (trombocitopenia dosis-limitante)","Náuseas","Vómitos","Fatiga","Cefalea","Linfopenia severa"],
  ce=["Tomar en ayunas","Hemograma semanal durante concomitancia con RT","Profilaxis anti-PCP (Pneumocystis) si linfocitos <200","Antiemético 30 min antes"]),

M("antineoplasico","cetuximab","Cetuximab","Cetuximab",["Erbitux"],"Anti-EGFR monoclonal",
  "Anticuerpo quimérico anti-EGFR. Bloquea señalización proliferativa. Solo eficaz si KRAS/NRAS wild-type",
  ["Cáncer colorrectal metastásico KRAS wild-type","Cáncer de cabeza y cuello"],["IV"],
  {"adulto":"Carga: 400 mg/m² IV en 2h. Mantenimiento: 250 mg/m² semanal en 1h"},
  ["Vial 5 mg/mL x 20, 100 mL"],"Evitar durante lactancia","u12","c12_05",
  ea=["Rash acneiforme (correlaciona con eficacia)","Diarrea","Hipomagnesemia","Reacciones infusionales severas","Toxicidad cutánea"],
  ce=["KRAS/NRAS wild-type obligatorio antes de tratar","Premedicación con antihistamínico/corticoide","Rash acneiforme: buen pronóstico si aparece","Monitorizar Mg2+ durante tratamiento"],
  pp={"velocidadAdministracion":"Carga: 10 mg/min máx. Mantenimiento: 20 mg/min máx","estabilidad":"48h refrigerado"}),

M("antineoplasico","osimertinib","Osimertinib","Osimertinib",["Tagrisso"],"Inhibidor EGFR 3ª generación",
  "ITK EGFR selectivo 3ª generación. Activo contra mutación T790M de resistencia. Penetra SNC",
  ["CPNM con mutación EGFR (1ª línea)","CPNM con mutación T790M tras ITK previo","Adyuvancia CPNM EGFR+"],["oral"],
  {"adulto":"80 mg/día (puede reducir a 40 mg)"},
  ["Comp 40, 80 mg"],"Evitar durante lactancia","u12","c12_05",
  ea=["Diarrea","Rash","Paroniquia","Enfermedad pulmonar intersticial","Prolongación QTc","Cardiotoxicidad"],
  ce=["Mutación EGFR obligatoria","ECG basal y periódico","Vigilar neumonitis intersticial (disnea, tos)","Puede darse con/sin alimentos"]),

M("antineoplasico","durvalumab","Durvalumab","Durvalumab",["Imfinzi"],"Anti-PD-L1",
  "Anticuerpo monoclonal anti-PD-L1. Bloquea interacción PD-L1/PD-1 y PD-L1/B7.1. Restaura respuesta antitumoral",
  ["CPNM estadio III irresecable post-QT/RT","Cáncer de vejiga","CPNM extenso (con QT)"],["IV"],
  {"adulto":"10 mg/kg c/2 sem o 1500 mg c/3 sem (peso fijo ≥30 kg) en 60 min"},
  ["Vial 120 mg/2.4 mL","Vial 500 mg/10 mL"],"Evitar durante lactancia","u12","c12_05",
  ea=["Neumonitis inmunomediada","Hepatitis","Colitis","Endocrinopatía (hipo/hipertiroidismo, adrenalitis)","Rash","Fatiga"],
  ce=["Función tiroidea basal y c/ciclo","Vigilar neumonitis: Rx tórax basal","Corticoides a dosis altas si toxicidad inmunomediada grado ≥3","No combinar con inmunosupresores basales si posible"],
  pp={"dilucion":"Diluir en SF al 0.9% o SG5% hasta 1-15 mg/mL","velocidadAdministracion":"Infusión en 60 minutos","estabilidad":"24h refrigerado o 4h a TA diluido"}),

M("antineoplasico","ipilimumab","Ipilimumab","Ipilimumab",["Yervoy"],"Anti-CTLA-4",
  "Anticuerpo monoclonal anti-CTLA-4. Potencia activación de linfocitos T al bloquear checkpoint inhibitorio. Primer checkpoint aprobado",
  ["Melanoma metastásico","Melanoma adyuvante","Combinación con nivolumab (renal, pulmón, melanoma)"],["IV"],
  {"adulto":"Melanoma: 3 mg/kg c/3 sem x4 dosis. Combinación: 1 mg/kg c/3 sem x4 dosis"},
  ["Vial 5 mg/mL x 10, 40 mL"],"Evitar durante lactancia","u12","c12_05",
  ea=["Colitis inmunomediada (severa)","Hepatitis","Dermatitis","Hipofisitis","Neumonitis","Nefritis"],
  ce=["Alta tasa de toxicidad inmunomediada (esp. colitis)","Corticoides dosis altas (1-2 mg/kg) si grado ≥3","Función hepática y tiroidea pre-ciclo","Educar: reportar diarrea inmediatamente"],
  pp={"dilucion":"No diluir o diluir en SF/SG5%","velocidadAdministracion":"Infusión en 30 minutos","estabilidad":"24h refrigerado diluido"}),

M("antineoplasico","sunitinib","Sunitinib","Sunitinib",["Sutent"],"Inhibidor multicinasa oral",
  "Inhibe VEGFR, PDGFR, KIT, FLT3. Actividad antiangiogénica y antitumoral directa",
  ["Carcinoma renal metastásico","GIST resistente a imatinib","Tumores neuroendocrinos pancreáticos"],["oral"],
  {"adulto":"50 mg/día x4 sem, descanso 2 sem (ciclo 6 sem). O 37.5 mg/día continuo"},
  ["Cáps 12.5, 25, 37.5, 50 mg"],"Evitar durante lactancia","u12","c12_05",
  ea=["Fatiga","Diarrea","Síndrome mano-pie","HTA","Hipotiroidismo","Mielosupresión","Hepatotoxicidad","Decoloración cutánea amarilla"],
  ce=["PA c/2 sem (HTA frecuente)","TSH c/3 meses (hipotiroidismo)","Función hepática c/ciclo","Coloración amarilla de piel es esperada"]),

M("antineoplasico","palbociclib","Palbociclib","Palbociclib",["Ibrance"],"Inhibidor CDK4/6",
  "Inhibe selectivamente ciclinas dependientes de kinasa 4 y 6. Bloquea progresión G1→S del ciclo celular",
  ["Cáncer de mama HR+/HER2- metastásico (con inhibidor aromatasa o fulvestrant)"],["oral"],
  {"adulto":"125 mg/día x21 días, descanso 7 días (ciclo 28d)"},
  ["Cáps 75, 100, 125 mg"],"Evitar durante lactancia","u12","c12_05",
  ea=["Neutropenia (muy frecuente)","Fatiga","Náuseas","Alopecia","Diarrea","Estomatitis","Trombocitopenia"],
  ce=["Hemograma al inicio y día 14 de primeros 2 ciclos, luego c/ciclo","Tomar con alimentos","Reducir dosis si neutropenia grado 3-4","No usar con inhibidores CYP3A4 potentes"]),

M("antineoplasico","pertuzumab","Pertuzumab","Pertuzumab",["Perjeta"],"Anti-HER2 (dimerización)",
  "Anticuerpo anti-HER2 que bloquea dimerización (diferente de trastuzumab). Combinación con trastuzumab = bloqueo dual HER2",
  ["Cáncer de mama HER2+ metastásico (con trastuzumab+docetaxel)","Neoadyuvancia","Adyuvancia HER2+"],["IV"],
  {"adulto":"Carga: 840 mg IV. Mantenimiento: 420 mg c/3 sem"},
  ["Vial 420 mg/14 mL"],"Evitar durante lactancia","u12","c12_05",
  ea=["Diarrea","Alopecia","Neutropenia","Náuseas","Fatiga","Rash","Cardiotoxicidad (con trastuzumab)"],
  ce=["FEVI basal y c/3 meses","Bloqueo dual HER2: pertuzumab + trastuzumab","Suspender si FEVI <40% o cae >10%","Tolerable: menos cardiotoxicidad sola que trastuzumab"],
  pp={"dilucion":"Diluir en 250 mL SF","velocidadAdministracion":"Carga en 60 min. Mantenimiento en 30-60 min","estabilidad":"24h refrigerado diluido"}),

M("antineoplasico","brentuximab","Brentuximab vedotina","Brentuximab vedotina",["Adcetris"],"Conjugado anticuerpo-fármaco anti-CD30",
  "Anticuerpo anti-CD30 conjugado con monometil auristatina E (MMAE). Internalización y liberación de MMAE citotóxica",
  ["Linfoma de Hodgkin recaído/refractario","Linfoma anaplásico de células grandes sistémico"],["IV"],
  {"adulto":"1.8 mg/kg c/3 sem (máx 180 mg). Hasta 16 ciclos o progresión"},
  ["Vial 50 mg polvo"],"Evitar durante lactancia","u12","c12_05",
  ea=["Neuropatía periférica","Neutropenia","Fatiga","Náuseas","Diarrea","Leucoencefalopatía multifocal progresiva (raro)"],
  ce=["Vigilar neuropatía periférica (reducir dosis si grado 2)","Hemograma pre-ciclo","No exceder 180 mg/dosis","Monitorizar signos neurológicos (LMP)"],
  pp={"reconstitucion":"Reconstituir con 10.5 mL agua estéril = 5 mg/mL","dilucion":"Diluir en SF mínimo 100 mL","velocidadAdministracion":"Infusión en 30 minutos","estabilidad":"24h refrigerado reconstituido"}),

# ── c12_06 Soporte Oncológico (10) ──
M("","mesna","Mesna","Mesna",["Uromitexan"],"Uroprotector frente a ifosfamida/ciclofosfamida",
  "Compuesto sulfhidrilo que se concentra en orina. Inactiva acroleína (metabolito nefrotóxico de ifosfamida/ciclofosfamida)",
  ["Prevención cistitis hemorrágica por ifosfamida","Prevención toxicidad urotelial por ciclofosfamida alta dosis"],["IV","oral"],
  {"adulto":"60% de dosis de ifosfamida, dividido en 3 dosis (0, 4 y 8h post-ifosfamida). O infusión continua"},
  ["Amp 400 mg/4 mL","Comp 400, 600 mg"],"Compatible","u12","c12_06",
  ci=["Hipersensibilidad"],
  ea=["Náuseas","Vómitos","Diarrea","Cefalea","Sabor desagradable (oral)","Reacciones alérgicas"],
  ix=["No reduce eficacia antitumoral de ifosfamida"],
  ce=["Administrar SIEMPRE con ifosfamida (nunca omitir)","Puede dar oral si IV no disponible","Hidratación abundante concomitante","Tira reactiva de orina para detectar hematuria"],
  emb="B",
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"Bolo IV en 15-30 min. O infusión continua","estabilidad":"24h a TA diluido"}),

M("","dexrazoxano","Dexrazoxano","Dexrazoxano",["Cardioxane","Zinecard"],"Cardioprotector frente a antraciclinas",
  "Quelante intracelular de hierro. Previene radicales libres mediados por hierro-antraciclina. Protege miocardio",
  ["Prevención cardiotoxicidad por doxorrubicina (dosis acumulativa ≥300 mg/m²)","Extravasación de antraciclinas"],["IV"],
  {"adulto":"Cardioprotección: 10:1 respecto a doxorrubicina (500 mg/m² si doxa 50 mg/m²). Extravasación: 1000 mg/m² x3 días"},
  ["Vial 500 mg polvo"],"Evitar durante lactancia","u12","c12_06",
  ci=["No usar en primeros ciclos de QT si intención curativa (posible reducción de respuesta)"],
  ea=["Mielosupresión aditiva","Náuseas","Diarrea","Dolor en sitio inyección","Mayor riesgo SMD/LMA secundaria"],
  ix=["Antraciclinas: reduce cardiotoxicidad pero posible reducción eficacia en algunos escenarios"],
  ce=["Administrar 15-30 min ANTES de antraciclina","FEVI basal y periódica igualmente","Riesgo-beneficio: uso cuando dosis acumulativa alta","Para extravasación: iniciar dentro de 6h"],
  emb="D",
  pp={"reconstitucion":"Reconstituir con lactato Ringer","dilucion":"Diluir en 250 mL lactato Ringer","velocidadAdministracion":"Infusión en 15 min, 15-30 min antes de QT","estabilidad":"6h a TA"}),

M("","aprepitant","Aprepitant","Aprepitant",["Emend"],"Antagonista NK1 antiemético",
  "Antagonista selectivo del receptor NK1 de sustancia P. Previene NVIQ agudos y diferidos. Complementa setrones y corticoides",
  ["Prevención NVIQ por QT altamente emetógena","NVIQ moderadamente emetógena en riesgo"],["oral"],
  {"adulto":"Día 1: 125 mg. Días 2-3: 80 mg/día. Con ondansetrón + dexametasona"},
  ["Cáps 80, 125 mg"],"Evitar durante lactancia","u12","c12_06",
  ci=["Uso con pimozida, terfenadina, astemizol, cisaprida"],
  ea=["Fatiga","Hipo","Estreñimiento","Cefalea","Elevación ALT"],
  ix=["Dexametasona: reducir dosis 50% (inhibe CYP3A4)","Warfarina: reduce INR","Anticonceptivos orales: puede reducir eficacia"],
  ce=["Triple esquema: aprepitant + 5-HT3 + dexa","Día 1 antes de QT, días 2-3 sin 5-HT3","Interacciones CYP3A4: ajustar dexa y otros","Revisar medicación concomitante"],
  emb="B"),

M("","palonosetron","Palonosetrón","Palonosetrón",["Aloxi"],"Antagonista 5-HT3 de 2ª generación",
  "Setron de vida media larga (40h) con mayor afinidad por receptor 5-HT3. Único setron eficaz para NVIQ diferidos",
  ["NVIQ agudos y diferidos","QT moderada y altamente emetógena"],["IV","oral"],
  {"adulto":"0.25 mg IV dosis única 30 min pre-QT. Oral: 0.5 mg 1h pre-QT"},
  ["Vial 0.25 mg/5 mL","Cáps 0.5 mg"],"Evitar durante lactancia","u12","c12_06",
  ci=["Hipersensibilidad a setrones"],
  ea=["Cefalea","Estreñimiento","Mareo","Prolongación QT (menor que otros setrones)"],
  ix=["Fármacos que prolongan QT: precaución"],
  ce=["Dosis ÚNICA por ciclo (vida media larga)","Más eficaz para diferidos que ondansetrón","30 min antes de QT","Puede combinarse con NK1 + dexa"],
  emb="B",
  pp={"velocidadAdministracion":"Bolo IV en 30 segundos","estabilidad":"Conservar a TA, proteger de la luz"}),

M("","rasburicasa","Rasburicasa","Rasburicasa",["Fasturtec","Elitek"],"Urato oxidasa recombinante para SLT",
  "Enzima urato oxidasa recombinante. Convierte ácido úrico en alantoína (5-10x más soluble). Reducción ultrarrápida",
  ["Prevención y tratamiento de síndrome de lisis tumoral","Hiperuricemia en neoplasias hematológicas"],["IV"],
  {"adulto":"0.2 mg/kg IV en 30 min, dosis única o diaria hasta control (máx 5 días)","pediatrico":"Misma dosis"},
  ["Vial 1.5 mg, 7.5 mg"],"Evitar durante lactancia","u12","c12_06",
  ci=["Déficit de G6PD (anemia hemolítica severa)","MetHb","Hipersensibilidad"],
  ea=["Reacción anafiláctica","Hemólisis en G6PD","Metahemoglobinemia","Fiebre","Cefalea"],
  ix=["Prueba de ácido úrico: MUESTRA EN HIELO (la enzima sigue actuando ex vivo)"],
  ce=["Cribado G6PD OBLIGATORIO antes de administrar","Muestra de ácido úrico en HIELO (enzima degrada úrico in vitro)","Reducción de úrico en 4h","Más rápida que alopurinol (emergencia)"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto","dilucion":"Diluir en 50 mL SF","velocidadAdministracion":"Infusión en 30 minutos","estabilidad":"24h refrigerado"}),

M("","filgrastim_onco","Filgrastim (oncológico)","Filgrastim",["Neupogen (onco)"],"G-CSF para neutropenia post-QT",
  "Factor estimulante de colonias granulocíticas recombinante. Estimula producción de neutrófilos. Acorta neutropenia post-QT",
  ["Neutropenia febril: tratamiento","Profilaxis de neutropenia post-QT","Movilización de células madre"],["SC","IV"],
  {"adulto":"5-10 mcg/kg/día SC (profilaxis: inicio 24-72h post-QT, hasta recuperación neutrófilos)"},
  ["Jer precargada 300, 480 mcg"],"Compatible","u12","c12_06",
  ci=["Hipersensibilidad","No administrar 24h antes ni después de QT citotóxica"],
  ea=["Dolor óseo (lo más frecuente)","Cefalea","Esplenomegalia","Rotura esplénica (raro)","Leucocitosis"],
  ix=["QT: no dar dentro de 24h","Litio: leucocitosis aditiva"],
  ce=["Inicio 24-72h post-QT","Hemograma biweekly","Dolor óseo manejable con paracetamol","Suspender cuando neutrófilos >10,000 post-nadir","Conservar refrigerado"],
  emb="C",
  pp={"velocidadAdministracion":"SC preferida. IV: infusión en 15-30 min","estabilidad":"Refrigerado 2-8°C, 24h a TA"}),

M("","zoledronic_onco","Ácido zoledrónico (oncológico)","Ácido zoledrónico",["Zometa"],"Bisfosfonato IV para metástasis óseas",
  "Bisfosfonato más potente. Inhibe osteoclastos. Previene eventos esqueléticos en metástasis óseas y mieloma",
  ["Metástasis óseas","Mieloma múltiple","Hipercalcemia maligna"],["IV"],
  {"adulto":"4 mg IV en 15 min c/3-4 sem. Hipercalcemia: 4 mg IV dosis única"},
  ["Vial 4 mg/5 mL"],"Evitar durante lactancia","u12","c12_06",
  ci=["Hipersensibilidad","ClCr <35 mL/min","Embarazo"],
  ea=["Síndrome pseudo-gripal","Hipocalcemia","Nefrotoxicidad","Osteonecrosis mandibular","Fracturas atípicas (uso prolongado)"],
  ix=["Aminoglucósidos: hipocalcemia aditiva","Nefrotóxicos: daño renal aditivo"],
  ce=["Creatinina pre-cada dosis (no dar si >3 mg/dL)","Suplementar calcio 500 mg + vitamina D 400 UI/día","Evaluación dental antes de iniciar (ONM)","Infusión mínimo 15 min (nefrotoxicidad si más rápido)"],
  emb="D",
  pp={"dilucion":"Diluir en 100 mL SF o SG5%","velocidadAdministracion":"Infusión en NO MENOS de 15 minutos","estabilidad":"24h refrigerado diluido"}),

M("","denosumab_onco","Denosumab (oncológico)","Denosumab",["Xgeva"],"Anti-RANKL para metástasis óseas",
  "Anticuerpo anti-RANKL. Inhibe maduración y actividad osteoclástica. Alternativa a zoledrónico sin nefrotoxicidad",
  ["Prevención de eventos esqueléticos en metástasis óseas","Tumor de células gigantes del hueso"],["SC"],
  {"adulto":"120 mg SC c/4 sem. TCG: 120 mg SC días 1, 8, 15, luego mensual"},
  ["Vial 120 mg/1.7 mL"],"Evitar durante lactancia","u12","c12_06",
  ci=["Hipocalcemia no corregida","Hipersensibilidad"],
  ea=["Hipocalcemia","Osteonecrosis mandibular","Fracturas atípicas","Dolor musculoesquelético","Fatiga"],
  ix=["Otros antirresortivos: no combinar"],
  ce=["No requiere ajuste renal (ventaja sobre zoledrónico)","Suplementar Ca2+ y vitamina D","Calcio sérico pre-cada dosis","Evaluación dental pre-inicio","Efecto rebote óseo al suspender"],
  emb="X",
  pp={"velocidadAdministracion":"SC, rotación de sitios","estabilidad":"Refrigerado 2-8°C"}),

# ── c12_07 Fluidoterapia y Electrolitos (10) ──
M("","salina_hipertonica","Solución salina hipertónica 3%","NaCl 3%",["NaCl 3%"],"Cristaloide hipertónico",
  "513 mEq/L de Na+. Para hiponatremia severa sintomática. Eleva natremia de forma controlada",
  ["Hiponatremia severa sintomática (convulsiones, coma)","Herniación cerebral por edema"],["IV"],
  {"adulto":"Bolo 100-150 mL en 10-20 min si convulsiones. Infusión: 15-30 mL/h. Objetivo: Na+ ↑4-6 mEq/L en 24h"},
  ["Bolsa 250, 500 mL al 3%"],"No aplica (emergencia)","u12","c12_07",
  ci=["Hipernatremia","Sobrecarga de volumen","Edema pulmonar"],
  ea=["Mielinolisis pontina central (corrección rápida >8-10 mEq/24h)","Sobrecarga de volumen","Flebitis"],
  ix=["Diuréticos: pueden causar mayor variación de Na+"],
  ce=["Na+ sérico c/2-4h durante corrección","NUNCA superar 8-10 mEq/L en 24h (mielinolisis)","Vía central preferible (flebitis)","Fórmula de Adrogue-Madias para calcular infusión"],
  emb="C",
  pp={"velocidadAdministracion":"Bolo 100-150 mL en 10-20 min (emergencia). Infusión 15-30 mL/h","estabilidad":"TA"}),

M("","dextrosa_5","Dextrosa 5%","Glucosa 5%",["SG5%"],"Solución de mantenimiento",
  "Solución glucosada isotónica que aporta agua libre y 200 kcal/L. Se distribuye como agua libre tras metabolizar glucosa",
  ["Mantenimiento de hidratación","Vehículo para medicamentos","Hipoglucemia leve","Aporte calórico mínimo"],["IV"],
  {"adulto":"Mantenimiento: 1-2 mL/kg/h según necesidad"},
  ["Bolsa 100, 250, 500, 1000 mL"],"Compatible","u12","c12_07",
  ci=["Hiperglucemia no controlada","Edema cerebral (aporta agua libre)","Hiponatremia dilucional (empeora)"],
  ea=["Hiperglucemia","Hiponatremia dilucional","Edema cerebral si exceso en hiponatremias"],
  ix=["Insulina: antagonismo glucémico","Algunos fármacos incompatibles en SG5%"],
  ce=["NO usar como expansor de volumen (se redistribuye como agua libre)","Puede empeorar hiponatremia","Monitorizar glucemia en pacientes diabéticos","No mezclar con amiodarona en SF (solo SG5%)"],
  emb="A"),

M("","bicarbonato_infusion","Bicarbonato de sodio infusión","NaHCO3",["Bicarbonato IV"],"Buffer para acidosis metabólica",
  "Solución buffer. 1 mEq/mL (8.4%) o isotónica (1.4%). Para corrección de acidosis metabólica no respiratoria",
  ["Acidosis metabólica severa (pH <7.1, HCO3 <8)","Alcalinización urinaria","Hiperpotasemia severa"],["IV"],
  {"adulto":"Déficit HCO3 = 0.3 x peso x (24 - HCO3 actual). Dar 50% en 4-8h, resto en 24h"},
  ["Amp 8.4% (1 mEq/mL) x 50 mL","Bolsa 1.4% (isotónica) x 500 mL"],"Compatible","u12","c12_07",
  ci=["Alcalosis metabólica","Hipopotasemia severa","Hipocalcemia (riesgo tetania)"],
  ea=["Alcalosis","Hipernatremia","Hipopotasemia","Hipocalcemia","Edema"],
  ix=["NO mezclar con Ca2+, catecolaminas"],
  ce=["Gasometría c/2-4h durante corrección","Corregir K+ ANTES o simultáneamente","No dar 8.4% sin diluir en neonatos (hiperosmolar)","Cálculo preciso del déficit"],
  emb="C",
  pp={"dilucion":"8.4% puede diluir en SG5%. 1.4% listo para usar","velocidadAdministracion":"50% del déficit en 4-8h","estabilidad":"TA"}),

M("","cloruro_potasio_iv","Cloruro de potasio IV","KCl",["KCl IV"],"Electrolito para hipopotasemia",
  "Aporte IV de potasio para corrección de hipopotasemia. FÁRMACO DE ALTO RIESGO: nunca en bolo",
  ["Hipopotasemia moderada-severa","Suplemento en fluidoterapia","Reposición en cetoacidosis"],["IV"],
  {"adulto":"10-40 mEq en 500-1000 mL en 2-4h. Severa: hasta 40 mEq/h por vía central con monitor ECG. Máx 200 mEq/día"},
  ["Amp 14.9% (2 mEq/mL) x 10 mL","Amp 10% x 10 mL"],"Compatible","u12","c12_07",
  ci=["Hiperpotasemia","Insuficiencia renal oligúrica","Bloqueo cardíaco"],
  ea=["Dolor en sitio IV (periférica)","Flebitis","PARO CARDÍACO SI BOLO","Hiperpotasemia"],
  ix=["IECA/ARA-II/espironolactona: hiperpotasemia aditiva"],
  ce=["NUNCA en bolo IV (paro cardíaco)","Concentración máx periférica: 40 mEq/L","Velocidad máx periférica: 10 mEq/h","Central: hasta 40 mEq/h con ECG continuo","K+ sérico c/2-4h durante reposición","FÁRMACO DE ALTO RIESGO: doble verificación"],
  emb="C",
  pp={"dilucion":"Diluir SIEMPRE. Periférica: máx 40 mEq/L en SF. Central: hasta 80 mEq/L","velocidadAdministracion":"Periférica: máx 10 mEq/h. Central: máx 40 mEq/h con ECG","estabilidad":"24h diluido"}),

M("","gluconato_calcio_iv","Gluconato de calcio IV","Gluconato de calcio",["Gluconato Ca2+ IV"],"Calcio IV de primera línea",
  "Sal de calcio con 9.3 mg Ca2+ elemental por mL de sol 10%. Más seguro que CaCl2 en vena periférica",
  ["Hipocalcemia sintomática","Hiperpotasemia con cambios ECG","Hipermagnesemia sintomática","Intoxicación por calcioantagonistas"],["IV"],
  {"adulto":"Hipocalcemia: 10-20 mL de sol 10% (1-2 g) IV lento en 10-20 min. Hiperpotasemia: 10 mL IV en 2-3 min"},
  ["Amp 10% (100 mg/mL = 9.3 mg Ca2+ elem/mL) x 10 mL"],"Compatible","u12","c12_07",
  ci=["Hipercalcemia","Intoxicación digitálica (relativa)"],
  ea=["Bradicardia","Hipotensión (IV rápido)","Sensación de calor","Necrosis si extravasación (menor que CaCl2)"],
  ix=["Digoxina: hipercalcemia potencia toxicidad","Bicarbonato: precipita (NO mezclar)","Ceftriaxona: precipitado fatal en neonatos"],
  ce=["Más seguro que CaCl2 en vía periférica","3x MENOS calcio elemental que CaCl2","IV lento (bradicardia/asistolia si rápido)","NO mezclar con bicarbonato o ceftriaxona en misma línea","Monitorizar Ca2+ y ECG"],
  emb="C",
  pp={"dilucion":"Puede diluir en SF o SG5%","velocidadAdministracion":"IV lento en 10-20 min (reposición). 2-3 min (emergencia K+)","estabilidad":"24h diluido"}),

M("","sulfato_magnesio_iv","Sulfato de magnesio IV","MgSO4",["MgSO4 IV"],"Magnesio IV para hipomagnesemia",
  "Aporte IV de magnesio para deficiencia. También: anticonvulsivante en eclampsia, antiarrítmico en torsades, tocolítico",
  ["Hipomagnesemia severa","Torsades de pointes","Eclampsia","Asma refractaria"],["IV","IM"],
  {"adulto":"Hipomagnesemia: 1-2 g (8-16 mEq) IV en 1h. Eclampsia: 4-6 g en 20 min, luego 1-2 g/h. Torsades: 2 g IV en 2 min"},
  ["Amp 50% (500 mg/mL) x 10 mL","Amp 10, 20%"],"Compatible","u12","c12_07",
  ci=["Bloqueo cardíaco","Hipersensibilidad","Miastenia gravis (relativa)"],
  ea=["Hipotensión","Bradicardia","Depresión respiratoria","Rubor facial","Hiporreflexia","Hipocalcemia"],
  ix=["Relajantes neuromusculares: potencia bloqueo","Calcioantagonistas: hipotensión aditiva"],
  ce=["Monitorizar reflejos tendinosos (desaparecen antes de depresión respiratoria)","Antídoto: gluconato de calcio","Mg2+ sérico c/4h durante infusión","En eclampsia: protocolo Zuspan o Pritchard"],
  emb="A",
  pp={"dilucion":"Diluir en SF o SG5% (máx 20% concentración)","velocidadAdministracion":"Reposición: 1-2 g en 1h. Eclampsia carga: 4 g en 20 min. Torsades: 2 g en 2 min","estabilidad":"24h diluido"}),

M("","plasmalyte","PlasmaLyte","PlasmaLyte 148",["PlasmaLyte"],"Cristaloide balanceado",
  "Solución isotónica balanceada. Composición similar a plasma: Na 140, K 5, Mg 1.5, Cl 98, acetato 27, gluconato 23 mEq/L. pH 7.4",
  ["Reposición de volumen","Fluidoterapia perioperatoria","Alternativa a SF con menor riesgo de acidosis hiperclorémica"],["IV"],
  {"adulto":"Según necesidad: reanimación 10-30 mL/kg. Mantenimiento: 1-2 mL/kg/h"},
  ["Bolsa 500, 1000 mL"],"Compatible","u12","c12_07",
  ci=["Hiperpotasemia (contiene K+)","Alcalosis metabólica severa"],
  ea=["Sobrecarga de volumen","Edema","Hiperpotasemia (en IR)"],
  ix=["No mezclar con hemoderivados en misma línea"],
  ce=["Menor acidosis hiperclorémica que SF (ventaja)","Contiene K+ (precaución en IR/hiperpotasemia)","Cristaloide de elección en muchos centros","Sin calcio: compatible con citrato de hemoderivados"],
  emb="A"),

M("","gelatina_succinilada","Gelatina succinilada","Gelatina",["Gelafundin"],"Coloide expansor de volumen",
  "Gelatina modificada al 4%. Coloide semisintético. Expansión 70-80% del volumen infundido. Duración 3-4h",
  ["Expansión rápida de volumen intravascular","Shock hipovolémico","Hemorragia aguda"],["IV"],
  {"adulto":"500-1500 mL según respuesta hemodinámica. Máx 2500 mL/día"},
  ["Bolsa 500 mL al 4%"],"Compatible con precaución","u12","c12_07",
  ci=["Hipersensibilidad","Hipervolemia","IC severa"],
  ea=["Reacciones anafilactoides","Prurito (puede durar semanas)","Coagulopatía dilucional","Hipotermia (si no calentada)"],
  ix=["Anticoagulantes: puede alterar hemostasia"],
  ce=["Calentar antes de infundir","Menor efecto sobre coagulación que HEA","Riesgo de anafilaxia: monitorizar","No exceder 2.5 L/día","Alternativa si cristaloides insuficientes"],
  emb="B",
  pp={"velocidadAdministracion":"Según gravedad: hasta 500 mL en 15-30 min en emergencia","estabilidad":"No usar si turbio. TA"}),

M("","solucion_hartmann","Solución de Hartmann","Ringer Lactato/Hartmann",["Hartmann"],"Cristaloide balanceado clásico",
  "Composición: Na 131, K 5, Ca 2, Cl 111, lactato 29 mEq/L. Ligeramente hipotónica. Lactato se metaboliza a bicarbonato",
  ["Reposición de volumen","Fluidoterapia perioperatoria","Quemados (fórmula Parkland)"],["IV"],
  {"adulto":"Reanimación: 20-30 mL/kg. Quemados: 4 mL x %SCQ x peso(kg) en 24h"},
  ["Bolsa 500, 1000 mL"],"Compatible","u12","c12_07",
  ci=["Hiperpotasemia","Hipercalcemia","Insuficiencia hepática severa (no metaboliza lactato)","Alcalosis"],
  ea=["Sobrecarga volumen","Hiperpotasemia (si IR)","Acidosis láctica (si hígado no metaboliza)"],
  ix=["Ceftriaxona: precipita con calcio (precaución en neonatos)","Hemoderivados: no usar como diluyente"],
  ce=["Esencialmente = Ringer Lactato","Contiene Ca2+ y K+ (precaución en IR)","No usar como diluyente de hemoderivados (contiene Ca2+)","Fórmula de Parkland en quemados: mitad en 8h, mitad en 16h"],
  emb="A"),

M("","dextrosa_10","Dextrosa 10%","Glucosa 10%",["SG10%"],"Solución hipertónica para hipoglucemia",
  "Solución glucosada hipertónica. Aporta 100 g glucosa/L (400 kcal/L). Para hipoglucemia y aporte calórico en NP periférica",
  ["Hipoglucemia moderada","Aporte calórico cuando la central no disponible","Componente de NP periférica"],["IV"],
  {"adulto":"Hipoglucemia: 150-250 mL (15-25 g) IV. Mantenimiento: según necesidad calórica"},
  ["Bolsa 250, 500, 1000 mL"],"Compatible","u12","c12_07",
  ci=["Hiperglucemia no controlada","Coma hiperosmolar"],
  ea=["Hiperglucemia","Flebitis (concentraciones >10%)","Hiponatremia dilucional"],
  ix=["Insulina: ajustar dosis","Corticoides: hiperglucemia"],
  ce=["Concentraciones >12.5% requieren vía central","Monitorizar glucemia c/4-6h","Puede usar en periférica (vs SG20% que requiere central)","Precaución en diabéticos y daño neurológico"],
  emb="A"),
]

NEW_CHAPTERS = {
    "c12_06": {
        "id": "c12_06",
        "nombre": "Soporte Oncológico",
        "drugIds": ["mesna","dexrazoxano","aprepitant","palonosetron","rasburicasa","filgrastim_onco","zoledronic_onco","denosumab_onco"]
    },
    "c12_07": {
        "id": "c12_07",
        "nombre": "Fluidoterapia y Electrolitos",
        "drugIds": ["salina_hipertonica","dextrosa_5","bicarbonato_infusion","cloruro_potasio_iv","gluconato_calcio_iv",
                     "sulfato_magnesio_iv","plasmalyte","gelatina_succinilada","solucion_hartmann","dextrosa_10"]
    },
}

if __name__ == "__main__":
    print("=== U12b ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        add_chapter(cats, "u12", ch)
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
