#!/usr/bin/env python3
"""Supplement: add ~80 more drugs for U03 + U04."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ══════════════════════════════════════════════════════════════════
# U03 — ANTIINFECCIOSOS (~50 drugs)
# ══════════════════════════════════════════════════════════════════

# ── c03_01 Penicilinas (+6) ──
M("penicilina","piperacilina_tazobactam_det","Piperacilina/Tazobactam (detalle)","Piperacilina + Tazobactam",
  ["Tazocin","Zosyn"],"Penicilina antipseudomónica + inhibidor de betalactamasa",
  "Piperacilina inhibe PBP de amplio espectro. Tazobactam inhibe betalactamasas clase A. Cobertura: gramnegativos incluyendo Pseudomonas, anaerobios",
  ["Infecciones intraabdominales complicadas","Neumonía nosocomial","Bacteriemia","Infección piel y tejidos blandos","Neutropenia febril"],
  ["IV"],{"adulto":"4.5 g IV c/6-8h. Infusión extendida: 4.5 g en 4h c/8h","pediatrico":"2-9 meses: 80 mg/kg c/8h. >9 meses: 100 mg/kg c/8h (máx 4.5 g)","ajusteRenal":"ClCr 20-40: 2.25 g c/6h"},
  ["Vial 2.25 g, 4.5 g"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con 10-20 mL SF o agua estéril","dilucion":"Diluir en 50-150 mL SF o SG5%","velocidadAdministracion":"Infundir en 30 min (estándar) o 4h (extendida)","estabilidad":"24h a TA, 48h refrigerado"}),

M("penicilina","sultamicilina","Sultamicilina","Sultamicilina",["Unasyn oral","Ampictam"],
  "Profármaco oral de ampicilina/sulbactam",
  "Doble éster que se hidroliza en intestino a ampicilina + sulbactam. Buena absorción oral con cobertura de productores de betalactamasa",
  ["OMA","Sinusitis bacteriana","Infección urinaria no complicada","Infecciones de piel","Exacerbación de bronquitis crónica"],
  ["oral"],{"adulto":"375-750 mg c/12h","pediatrico":"25-50 mg/kg/día dividido c/12h"},
  ["Comp 375 mg","Suspensión 250 mg/5 mL"],"Compatible con precaución","u03","c03_01"),

M("penicilina","ampicilina_sulbactam_det","Ampicilina/Sulbactam (detalle)","Ampicilina + Sulbactam",
  ["Unasyn","Ampibactam"],"Aminopenicilina + inhibidor de betalactamasa",
  "Ampicilina con actividad ampliada por sulbactam que inhibe betalactamasas clase A. Sulbactam tiene actividad intrínseca contra Acinetobacter",
  ["Infecciones intraabdominales","Infecciones ginecológicas","Infección de piel y tejidos blandos","Neumonía por aspiración","Infección por Acinetobacter (sulbactam)"],
  ["IV","IM"],{"adulto":"1.5-3 g IV/IM c/6h","pediatrico":"100-200 mg/kg/día de ampicilina dividido c/6h","ajusteRenal":"ClCr 15-29: c/12h. ClCr <15: c/24h"},
  ["Vial 1.5 g (1 g amp + 0.5 g sulb), 3 g"],"Compatible con precaución","u03","c03_01",
  pp={"reconstitucion":"Reconstituir con 3.2 mL agua estéril (1.5 g) o 6.4 mL (3 g)","dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"IV directa en 10-15 min o infusión en 15-30 min","estabilidad":"8h a TA, 48h refrigerado"}),

M("penicilina","penicilina_v","Penicilina V (Fenoximetilpenicilina)","Fenoximetilpenicilina",
  ["Pen-Vee K","Ospen"],"Penicilina natural oral",
  "Penicilina ácido-estable para uso oral. Espectro limitado a grampositivos sensibles. Primera línea en faringitis estreptocócica",
  ["Faringitis estreptocócica","Profilaxis fiebre reumática","Infecciones leves por estreptococo","Profilaxis en asplenia"],
  ["oral"],{"adulto":"250-500 mg c/6-8h","pediatrico":"25-50 mg/kg/día dividido c/6-8h"},
  ["Comp 500 mg","Suspensión 125, 250 mg/5 mL"],"Compatible","u03","c03_01"),

M("penicilina","penicilina_g_benzatinica","Penicilina G Benzatínica","Bencilpenicilina benzatínica",
  ["Benzetacil","Bicillin L-A"],"Penicilina de depósito IM de acción prolongada",
  "Sal insoluble de penicilina G que forma depósito IM con liberación lenta durante 2-4 semanas. Niveles séricos bajos pero sostenidos",
  ["Sífilis (todas las etapas)","Profilaxis fiebre reumática","Faringitis estreptocócica","Profilaxis en asplenia"],
  ["IM"],{"adulto":"Sífilis temprana: 2.4 MUI IM dosis única. Sífilis tardía: 2.4 MUI IM semanal x 3. Profilaxis FR: 1.2 MUI IM c/3-4 sem",
  "pediatrico":"Sífilis: 50.000 UI/kg IM (máx 2.4 MUI). Profilaxis FR: 600.000 UI si <27 kg, 1.2 MUI si ≥27 kg"},
  ["Vial 600.000, 1.200.000, 2.400.000 UI"],"Compatible","u03","c03_01",
  ce=["SOLO vía IM profunda (glúteo) — NUNCA IV (embolia fatal)","Aspirar antes de inyectar","Inyección dolorosa: aplicar lentamente","Tener adrenalina disponible"]),

M("penicilina","penicilina_g_procainica","Penicilina G Procaínica","Bencilpenicilina procaínica",
  ["Despacilina"],"Penicilina de depósito IM de acción intermedia",
  "Sal de procaína de penicilina G con absorción lenta desde sitio IM. Niveles séricos mantenidos 12-24h",
  ["Sífilis (alternativa)","Neumonía neumocócica","Infecciones estreptocócicas de gravedad intermedia"],
  ["IM"],{"adulto":"600.000-1.200.000 UI IM c/12-24h","pediatrico":"25.000-50.000 UI/kg/día IM"},
  ["Vial 400.000, 800.000 UI"],"Compatible","u03","c03_01",
  ce=["SOLO IM — NUNCA IV","Reacción de Hoigné: ansiedad, alucinaciones transitorias (procaína)","Aspirar antes de inyectar","Tener adrenalina disponible"]),

# ── c03_02 Cefalosporinas (+6) ──
M("cefalosporina","ceftarolina_det","Ceftarolina (detalle)","Ceftarolina fosamil",
  ["Teflaro","Zinforo"],"Cefalosporina anti-MRSA de 5ª generación",
  "Primera cefalosporina con actividad contra MRSA. Se une a PBP2a de S. aureus resistente a meticilina. Amplio espectro incluyendo neumococo PRP",
  ["Neumonía comunitaria","Infección de piel y tejidos blandos (incluyendo MRSA)","Bacteriemia por MRSA (off-label)"],
  ["IV"],{"adulto":"600 mg IV c/12h en 1h","ajusteRenal":"ClCr 31-50: 400 mg c/12h. ClCr 15-30: 300 mg c/12h"},
  ["Vial 400, 600 mg"],"No recomendado","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 20 mL agua estéril","dilucion":"Diluir en 250 mL SF","velocidadAdministracion":"Infundir en 60 min","estabilidad":"6h a TA, 24h refrigerado"}),

M("cefalosporina","cefepima_det","Cefepima (detalle)","Cefepima",
  ["Maxipime"],"Cefalosporina de 4ª generación",
  "Cefalosporina zwitteriónica que penetra rápidamente porinas de gramnegativos. Estable frente a betalactamasas AmpC. Amplio espectro gram+/gram-",
  ["Neutropenia febril","Neumonía nosocomial","Meningitis bacteriana","ITU complicada","Infecciones por Pseudomonas"],
  ["IV","IM"],{"adulto":"1-2 g IV c/8-12h. Neutropenia febril: 2 g c/8h","pediatrico":"50 mg/kg c/8-12h (máx 2 g/dosis)",
  "ajusteRenal":"ClCr 30-60: 2 g c/12h. ClCr 11-29: 2 g c/24h"},
  ["Vial 500 mg, 1 g, 2 g"],"Compatible con precaución","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 5-10 mL agua estéril","dilucion":"Diluir en 50-100 mL SF o SG5%","velocidadAdministracion":"Infundir en 30 min","estabilidad":"24h a TA, 7 días refrigerado"},
  ea=["Diarrea","Náuseas","Flebitis","Neurotoxicidad (dosis altas/IR)","Colitis por C. difficile","Prueba Coombs + falsa"],
  ce=["Vigilar neurotoxicidad en insuficiencia renal (convulsiones, encefalopatía)","Monitorizar función renal","Ajustar dosis en IR estrictamente","Amplio espectro: primera línea en neutropenia febril"]),

M("cefalosporina","ceftolozano_tazobactam_det","Ceftolozano/Tazobactam (detalle)","Ceftolozano + Tazobactam",
  ["Zerbaxa"],"Cefalosporina antipseudomónica + inhibidor de betalactamasa",
  "Ceftolozano tiene alta afinidad por PBPs de Pseudomonas. Con tazobactam cubre BLEE. Activo contra Pseudomonas MDR",
  ["ITU complicada","Infección intraabdominal complicada","Neumonía nosocomial/asociada a ventilación"],
  ["IV"],{"adulto":"ITU/IAB: 1.5 g c/8h. Neumonía: 3 g c/8h en 1h","ajusteRenal":"ClCr 30-50: reducir 50%. ClCr 15-29: reducir 75%"},
  ["Vial 1.5 g (1 g/0.5 g), 3 g (2 g/1 g)"],"No recomendado","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 10 mL SF o agua estéril","dilucion":"Diluir en 100 mL SF o SG5%","velocidadAdministracion":"Infundir en 60 min","estabilidad":"24h a TA, 7 días refrigerado"}),

M("cefalosporina","cefazolina_det","Cefazolina (detalle)","Cefazolina",
  ["Ancef","Kefzol"],"Cefalosporina de 1ª generación parenteral",
  "Cefalosporina IV de primera línea para profilaxis quirúrgica. Buena actividad contra grampositivos. Alta concentración tisular",
  ["Profilaxis quirúrgica (primera línea)","Infección de piel y tejidos blandos","Endocarditis por MSSA","ITU no complicada","Osteomielitis por grampositivos"],
  ["IV","IM"],{"adulto":"Profilaxis QX: 2 g IV 30-60 min pre-incisión (redosificar c/4h en cirugías largas). Tratamiento: 1-2 g c/8h",
  "pediatrico":"25-50 mg/kg/día dividido c/8h","ajusteRenal":"ClCr 35-54: c/8h. ClCr 11-34: c/12h. ClCr ≤10: c/24h"},
  ["Vial 500 mg, 1 g, 2 g"],"Compatible con precaución","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 2.5 mL agua estéril por gramo","dilucion":"Diluir en 50-100 mL SF o SG5%","velocidadAdministracion":"IV directa en 3-5 min o infusión en 30 min","estabilidad":"24h a TA, 10 días refrigerado"}),

M("cefalosporina","cefalexina_det","Cefalexina (detalle)","Cefalexina",
  ["Keflex","Ceporex"],"Cefalosporina de 1ª generación oral",
  "Cefalosporina oral con buena actividad contra grampositivos comunitarios. Absorción GI rápida y casi completa",
  ["Infección de piel y tejidos blandos","ITU no complicada","Faringitis estreptocócica","Profilaxis de ITU","Osteomielitis (paso oral)"],
  ["oral"],{"adulto":"250-500 mg c/6h o 500 mg c/12h","pediatrico":"25-50 mg/kg/día dividido c/6-12h","ajusteRenal":"ClCr 10-50: c/8-12h. ClCr <10: c/12-24h"},
  ["Cáps 250, 500 mg","Suspensión 125, 250 mg/5 mL"],"Compatible","u03","c03_02"),

M("cefalosporina","cefuroxima_det","Cefuroxima (detalle)","Cefuroxima",
  ["Zinnat","Zinacef"],"Cefalosporina de 2ª generación oral/IV",
  "Cefalosporina con estabilidad frente a muchas betalactamasas. Forma oral (axetilo) e IV. Buena penetración a LCR y oído medio",
  ["OMA","Sinusitis","ITU","Neumonía comunitaria","Enfermedad de Lyme precoz","Profilaxis quirúrgica"],
  ["oral","IV","IM"],{"adulto":"Oral: 250-500 mg c/12h con alimentos. IV: 750 mg-1.5 g c/8h",
  "pediatrico":"Oral: 15 mg/kg c/12h. IV: 50-100 mg/kg/día c/8h"},
  ["Comp 250, 500 mg","Suspensión 125, 250 mg/5 mL","Vial 750 mg, 1.5 g"],"Compatible con precaución","u03","c03_02",
  pp={"reconstitucion":"Reconstituir con 8 mL agua estéril (750 mg)","dilucion":"Diluir en 50-100 mL SF","velocidadAdministracion":"IV directa en 3-5 min o infusión en 15-30 min","estabilidad":"24h a TA"}),

# ── c03_03 Aminoglucósidos (+5) ──
M("","tobramicina_sist","Tobramicina sistémica","Tobramicina",["Nebcin","Tobrex"],
  "Aminoglucósido de 2ª generación",
  "Aminoglucósido con actividad superior a gentamicina contra Pseudomonas aeruginosa. Inhibe subunidad 30S ribosomal",
  ["Infecciones graves por Pseudomonas","Sepsis por gramnegativos","Endocarditis (sinergia)","Fibrosis quística (nebulizado)"],
  ["IV","IM","inhalatoria"],{"adulto":"IV: 5-7 mg/kg/día dosis única diaria o 1-2.5 mg/kg c/8h. Nebulizado (FQ): 300 mg c/12h ciclos 28 días on/off",
  "pediatrico":"IV: 6-7.5 mg/kg/día","ajusteRenal":"Ajustar según niveles plasmáticos"},
  ["Vial 80, 240 mg","Sol nebulización 300 mg/5 mL"],"Evitar durante lactancia","u03","c03_03",
  familia="Aminoglucósidos",emb="D",
  ci=["Miastenia gravis","Hipersensibilidad a aminoglucósidos","Embarazo"],
  ea=["Nefrotoxicidad","Ototoxicidad (vestibular y coclear)","Bloqueo neuromuscular","Parestesias"],
  ix=["Otros nefrotóxicos: nefrotoxicidad aditiva","Diuréticos de asa: ototoxicidad aditiva","Relajantes neuromusculares: potenciación"],
  ce=["Monitorizar niveles: pico y valle","Función renal diaria","Audiometría si uso prolongado","Dosis única diaria preferida (menor nefrotoxicidad)"],
  pp={"dilucion":"Diluir en 50-100 mL SF o SG5%","velocidadAdministracion":"Infundir en 20-60 min","estabilidad":"24h a TA, 96h refrigerado"}),

M("","kanamicina","Kanamicina","Kanamicina",["Kantrex"],
  "Aminoglucósido de 1ª generación",
  "Aminoglucósido antiguo con uso limitado a TB resistente y descontaminación intestinal. Inhibe síntesis proteica en 30S",
  ["Tuberculosis MDR (segunda línea)","Descontaminación intestinal prequirúrgica","Infecciones graves por gramnegativos (si sensible)"],
  ["IM","IV","oral"],{"adulto":"IM/IV: 15 mg/kg/día (máx 1 g). Oral (local): 1 g c/6h (no se absorbe)","ajusteRenal":"Reducir dosis según ClCr"},
  ["Vial 500 mg, 1 g","Cáps 500 mg (oral)"],"Contraindicado","u03","c03_03",
  familia="Aminoglucósidos",emb="D",
  ci=["Miastenia gravis","Hipersensibilidad a aminoglucósidos","Embarazo","Insuficiencia renal severa"],
  ea=["Ototoxicidad (irreversible)","Nefrotoxicidad","Bloqueo neuromuscular","Malabsorción (oral prolongado)"],
  ix=["Otros aminoglucósidos: toxicidad aditiva","Diuréticos de asa: ototoxicidad","Cefalosporinas: nefrotoxicidad"],
  ce=["Uso actual muy limitado — reservar para TB-MDR","Monitorizar audición y función renal","Oral: no se absorbe (acción local intestinal)","Reemplazado por amikacina en la mayoría de indicaciones"]),

M("","plazomicina_det","Plazomicina (detalle)","Plazomicina",["Zemdri"],
  "Aminoglucósido de nueva generación",
  "Aminoglucósido sintético resistente a las enzimas modificadoras de aminoglucósidos (AMEs). Actividad contra enterobacterias productoras de carbapenemasa",
  ["ITU complicada y pielonefritis por enterobacterias MDR","Bacteriemia (en combinación)"],
  ["IV"],{"adulto":"15 mg/kg IV c/24h en 30 min. Duración 4-7 días","ajusteRenal":"ClCr 30-60: ajustar según niveles. ClCr <30: no recomendado"},
  ["Vial 500 mg/10 mL"],"No recomendado","u03","c03_03",
  familia="Aminoglucósidos",emb="D",
  ci=["Hipersensibilidad a aminoglucósidos","Miastenia gravis"],
  ea=["Nefrotoxicidad","Ototoxicidad","Diarrea","Náuseas","Hipertensión"],
  ix=["Nefrotóxicos: riesgo aditivo","Diuréticos de asa: ototoxicidad"],
  ce=["Resistente a la mayoría de enzimas modificadoras de aminoglucósidos","Reservar para infecciones por CRE","Monitorizar niveles: valle <3 mcg/mL","Audiometría basal y periódica"],
  pp={"dilucion":"Diluir en 50 mL SF o SG5%","velocidadAdministracion":"Infundir en 30 min","estabilidad":"24h a TA"}),

M("","sisomicina","Sisomicina","Sisomicina",["Sisomicina"],
  "Aminoglucósido semisintético",
  "Aminoglucósido derivado de gentamicina C1a con actividad contra gramnegativos resistentes a gentamicina. Menor sustrato de enzimas AME",
  ["Infecciones graves por gramnegativos resistentes a gentamicina","Sepsis","ITU complicada"],
  ["IV","IM"],{"adulto":"3 mg/kg/día dividido c/8h o dosis única diaria","ajusteRenal":"Ajustar según niveles"},
  ["Amp 50, 100 mg"],"Contraindicado","u03","c03_03",
  familia="Aminoglucósidos",emb="D",
  ci=["Miastenia gravis","Hipersensibilidad a aminoglucósidos"],
  ea=["Nefrotoxicidad","Ototoxicidad","Bloqueo neuromuscular"],
  ix=["Otros nefrotóxicos: toxicidad aditiva","Diuréticos de asa: ototoxicidad"],
  ce=["Alternativa cuando hay resistencia a gentamicina","Monitorizar niveles plasmáticos","Función renal diaria","Poco disponible actualmente"]),

M("","espectinomicina","Espectinomicina","Espectinomicina",["Trobicin"],
  "Aminociclitol (relacionado con aminoglucósidos)",
  "Aminociclitol que inhibe subunidad 30S. Actividad específica contra Neisseria gonorrhoeae. No presenta resistencia cruzada con aminoglucósidos",
  ["Gonorrea no complicada (alternativa en alergia a cefalosporinas)","Infección gonocócica faríngea y rectal"],
  ["IM"],{"adulto":"2 g IM dosis única (gonorrea)"},
  ["Vial 2 g con diluyente"],"Compatible con precaución","u03","c03_03",
  familia="Aminociclitoles",emb="B",
  ci=["Hipersensibilidad"],
  ea=["Dolor en sitio de inyección","Náuseas","Mareo","Urticaria","Fiebre"],
  ix=["Mínimas interacciones conocidas"],
  ce=["Alternativa en gonorrea si alergia a cefalosporinas","Dosis única IM: alta adherencia","No eficaz contra sífilis concomitante","Disponibilidad limitada en muchos países"]),

# ── c03_04 Quinolonas (+4) ──
M("quinolona","norfloxacino_det","Norfloxacino (detalle)","Norfloxacino",["Noroxin"],
  "Fluoroquinolona de 1ª generación",
  "Primera fluoroquinolona. Actividad limitada a vías urinarias (baja concentración sérica). Inhibe topoisomerasa II y IV",
  ["ITU no complicada","Prostatitis bacteriana crónica","Profilaxis peritonitis bacteriana espontánea (cirrosis)","Diarrea del viajero"],
  ["oral"],{"adulto":"400 mg c/12h. Profilaxis PBE: 400 mg/día","ajusteRenal":"ClCr <30: 400 mg c/24h"},
  ["Comp 400 mg"],"Evitar durante lactancia","u03","c03_04"),

M("quinolona","prulifloxacino","Prulifloxacino","Prulifloxacino",["Unidrox"],
  "Fluoroquinolona profármaco de ulifloxacino",
  "Profármaco que se hidroliza a ulifloxacino activo. Buena concentración urinaria y prostática. Uso predominante en Europa",
  ["ITU no complicada","Prostatitis","Exacerbación aguda de bronquitis crónica"],
  ["oral"],{"adulto":"600 mg/día dosis única"},
  ["Comp 600 mg"],"Evitar durante lactancia","u03","c03_04"),

M("quinolona","acido_nalidíxico","Ácido Nalidíxico","Ácido nalidíxico",["Wintomylon","NegGram"],
  "Quinolona de primera generación (no fluorada)",
  "Primera quinolona sintetizada (1962). Actividad limitada a gramnegativos urinarios. No fluorada. Ancestro de todas las fluoroquinolonas",
  ["ITU no complicada por gramnegativos"],
  ["oral"],{"adulto":"1 g c/6h x 7-14 días","pediatrico":">3 meses: 55 mg/kg/día dividido c/6h"},
  ["Comp 500 mg","Suspensión 300 mg/5 mL"],"Evitar durante lactancia","u03","c03_04",
  ea=["Náuseas","Cefalea","Mareo","Fotosensibilidad","Hipertensión intracraneal (raro)","Hemólisis en déficit G6PD"],
  ce=["Interés histórico: primera quinolona","Solo activa en vías urinarias","Resistencia muy elevada actualmente","Puede interferir con pruebas de glucosuria"]),

M("quinolona","acido_pipemidico","Ácido Pipemídico","Ácido pipemídico",["Pipram","Deblaston"],
  "Quinolona de primera generación",
  "Quinolona no fluorada con espectro limitado a gramnegativos urinarios. Mayor actividad que ác. nalidíxico contra Pseudomonas",
  ["ITU no complicada"],
  ["oral"],{"adulto":"400 mg c/12h x 7-10 días"},
  ["Comp 400 mg","Cáps 200 mg"],"Evitar durante lactancia","u03","c03_04",
  ea=["Náuseas","Cefalea","Fotosensibilidad","Trastornos GI","Mareo"],
  ce=["Uso limitado a ITU no complicada","Resistencia creciente","Disponible en Latinoamérica y Asia","Poco usado en Europa/EE.UU."]),

# ── c03_05 Antituberculosos (+4) ──
M("antituberculoso","bedaquilina_det","Bedaquilina (detalle)","Bedaquilina",["Sirturo"],
  "Diarilquinolina antituberculosa (primera en su clase)",
  "Primer fármaco antituberculoso con nuevo mecanismo en 40 años. Inhibe la ATP sintetasa micobacteriana (subunidad c del rotor de F0)",
  ["TB multirresistente (MDR-TB)","TB extensamente resistente (XDR-TB)"],
  ["oral"],{"adulto":"Semanas 1-2: 400 mg/día. Semanas 3-24: 200 mg 3 veces/semana. Siempre con alimentos"},
  ["Comp 100 mg"],"Contraindicado","u03","c03_05",emb="X",
  ea=["Prolongación QT (⚠️ dosis-dependiente)","Náuseas","Artralgia","Cefalea","Hepatotoxicidad","Hemoptisis"],
  ce=["ECG basal y mensual (vigilar QT)","No usar con otros fármacos que prolongan QT","Tomar SIEMPRE con alimentos (duplica absorción)","Tratamiento mínimo 24 semanas","Consultar comité de TB"]),

M("antituberculoso","capreomicina_det","Capreomicina (detalle)","Capreomicina",["Capastat"],
  "Polipéptido antituberculoso inyectable",
  "Antibiótico polipeptídico cíclico con actividad específica contra Mycobacterium tuberculosis. Inhibe síntesis proteica ribosomal",
  ["TB-MDR (segunda línea)","TB cuando aminoglucósidos no tolerados"],
  ["IM","IV"],{"adulto":"15 mg/kg/día IM (máx 1 g) x 60-120 días, luego 2-3 veces/semana","ajusteRenal":"Ajustar intervalo según ClCr"},
  ["Vial 1 g"],"Contraindicado","u03","c03_05",
  ea=["Nefrotoxicidad","Ototoxicidad (hipoacusia)","Desequilibrio electrolítico (hipopotasemia, hipomagnesemia)","Dolor en sitio de inyección"],
  ce=["Audiometría basal y mensual","Electrolitos y función renal semanal","No usar con aminoglucósidos (ototoxicidad aditiva)","Administrar IM profunda"]),

M("antituberculoso","cicloserina_det","Cicloserina (detalle)","Cicloserina",["Seromycin"],
  "Análogo de D-alanina antituberculoso",
  "Análogo estructural de D-alanina que inhibe enzimas de síntesis de peptidoglicano (D-ala racemasa y D-ala-D-ala ligasa). Actividad contra M. tuberculosis",
  ["TB-MDR (segunda línea)","TB-XDR"],
  ["oral"],{"adulto":"250 mg c/12h, aumentar a 250 mg c/8h (máx 1 g/día). Nivel meta: 20-35 mcg/mL","ajusteRenal":"Reducir dosis si ClCr <50"},
  ["Cáps 250 mg"],"Contraindicado","u03","c03_05",
  ea=["⚠️ Neurotoxicidad: convulsiones, psicosis, depresión","Cefalea","Tremor","Confusión","Neuropatía periférica"],
  ce=["Suplementar piridoxina (B6) 100-200 mg/día para prevenir neurotoxicidad","Monitorizar estado mental y neurológico","Niveles plasmáticos si disponible","Contraindicada en epilepsia y depresión severa"]),

M("antituberculoso","acido_paraaminosalicilico_det","Ácido Paraaminosalicílico (PAS)","Ácido paraaminosalicílico",["Paser"],
  "Análogo del ácido fólico antituberculoso",
  "Análogo del ácido paraaminobenzoico que inhibe síntesis de ácido fólico en M. tuberculosis. Actividad bacteriostática",
  ["TB-MDR (segunda línea)","TB-XDR (en combinación)"],
  ["oral"],{"adulto":"4 g c/8h o 8-12 g/día dividido c/8-12h con alimentos","pediatrico":"200-300 mg/kg/día dividido c/6-8h"},
  ["Granulado 4 g/sobre"],"Compatible con precaución","u03","c03_05",
  ea=["Intolerancia GI severa","Hepatotoxicidad","Hipotiroidismo (uso prolongado)","Malabsorción","Cristaluria"],
  ce=["Administrar con alimentos ácidos (yogur, jugo)","Vigilar función tiroidea c/3 meses","Hidratación adecuada (prevenir cristaluria)","Granulado: no triturar ni masticar, mezclar con líquido ácido"]),

# ── c03_06 Antiparasitarios (+5) ──
M("antiparasitario","nitazoxanida_det","Nitazoxanida (detalle)","Nitazoxanida",["Alinia","Daxon","Paramix"],
  "Antiparasitario de amplio espectro (tiazolida)",
  "Tiazolida que interfiere con la enzima piruvato:ferredoxina oxidorreductasa (PFOR). Activa contra protozoos y helmintos. También actividad antiviral",
  ["Giardiasis","Criptosporidiosis","Amebiasis intestinal","Fasciolasis","Rotavirus (uso off-label)"],
  ["oral"],{"adulto":"500 mg c/12h con alimentos x 3 días","pediatrico":"1-3 años: 100 mg c/12h. 4-11 años: 200 mg c/12h. ≥12: 500 mg c/12h"},
  ["Comp 500 mg","Suspensión 100 mg/5 mL"],"Compatible con precaución","u03","c03_06"),

M("antiparasitario","benznidazol_det","Benznidazol (detalle)","Benznidazol",["Rochagan","Abarax"],
  "Nitroimidazol tripanocida",
  "Nitroimidazol con actividad tripanocida. Genera radicales libres y metabolitos electrofílicos que dañan ADN y proteínas de T. cruzi",
  ["Enfermedad de Chagas aguda","Chagas congénito","Chagas crónico reciente (<15 años de infección)","Reactivación en inmunodeprimidos"],
  ["oral"],{"adulto":"5-7 mg/kg/día dividido c/12h x 60 días","pediatrico":"5-10 mg/kg/día dividido c/12h x 60 días"},
  ["Comp 12.5, 50, 100 mg"],"Contraindicado","u03","c03_06",emb="X",
  ea=["Dermatitis alérgica (30%)","Neuropatía periférica (dosis-dependiente)","Leucopenia","Náuseas","Anorexia"],
  ce=["Hemograma c/2 semanas durante tratamiento","Suspender si neuropatía periférica","Evitar alcohol (efecto disulfiram)","Tratamiento 60 días completos es esencial"]),

M("antiparasitario","nifurtimox","Nifurtimox","Nifurtimox",["Lampit"],
  "Nitrofurano tripanocida",
  "Nitrofurano que genera radicales superóxido y peróxido de hidrógeno letales para T. cruzi. Alternativa a benznidazol",
  ["Enfermedad de Chagas aguda (alternativa)","Tripanosomiasis africana (T. b. gambiense, combinación con eflornitina)"],
  ["oral"],{"adulto":"Chagas: 8-10 mg/kg/día c/8h x 90 días","pediatrico":"15-20 mg/kg/día dividido c/6h x 90 días"},
  ["Comp 30, 120 mg"],"Contraindicado","u03","c03_06",emb="X",
  ea=["Anorexia y pérdida de peso (frecuente)","Náuseas y vómitos","Irritabilidad","Insomnio","Neuropatía periférica","Convulsiones (raro)"],
  ce=["Administrar con alimentos para reducir náuseas","Vigilar peso corporal semanalmente","Tratamiento 90 días (más largo que benznidazol)","Disponibilidad a través de OMS/OPS"]),

M("antiparasitario","tinidazol_det","Tinidazol (detalle)","Tinidazol",["Fasigyn","Tindamax"],
  "Nitroimidazol antiprotozoario de segunda generación",
  "Nitroimidazol con mecanismo similar a metronidazol pero vida media más larga. Mayor eficacia en dosis única contra Giardia y ameba",
  ["Giardiasis","Amebiasis intestinal y hepática","Tricomoniasis","Vaginosis bacteriana"],
  ["oral"],{"adulto":"Giardia/ameba intestinal: 2 g dosis única. Absceso hepático: 2 g/día x 3-5 días. Tricomoniasis: 2 g dosis única",
  "pediatrico":">3 años: 50 mg/kg dosis única (máx 2 g)"},
  ["Comp 500 mg, 1 g"],"Evitar durante lactancia","u03","c03_06"),

M("antiparasitario","secnidazol_det","Secnidazol (detalle)","Secnidazol",["Flagentyl","Solosec"],
  "Nitroimidazol de acción ultraprolongada",
  "Nitroimidazol con vida media de 20-25 horas que permite dosis única. Genera metabolitos citotóxicos tras reducción del grupo nitro",
  ["Amebiasis intestinal","Giardiasis","Vaginosis bacteriana (dosis única)","Tricomoniasis"],
  ["oral"],{"adulto":"Amebiasis/giardia: 2 g dosis única. Vaginosis: 2 g dosis única (granulado)","pediatrico":"30 mg/kg dosis única"},
  ["Comp 500 mg, 1 g","Granulado 2 g/sobre"],"Evitar durante lactancia","u03","c03_06"),

# ── c03_10 Antivirales Generales (10) — NUEVO ──
M("","oseltamivir_det","Oseltamivir (detalle)","Oseltamivir",["Tamiflu"],
  "Inhibidor de neuraminidasa (antigripal)",
  "Profármaco que se convierte a carboxilato de oseltamivir. Inhibe neuraminidasa de influenza A y B, bloqueando liberación de viriones",
  ["Influenza A y B (tratamiento y profilaxis)","Gripe aviar H5N1"],
  ["oral"],{"adulto":"Tratamiento: 75 mg c/12h x 5 días. Profilaxis: 75 mg/día x 10 días",
  "pediatrico":"<1 año: 3 mg/kg c/12h. 1-12 años: según peso (30-75 mg c/12h)","ajusteRenal":"ClCr 30-60: 30 mg c/12h. ClCr 10-30: 30 mg c/24h"},
  ["Cáps 30, 45, 75 mg","Suspensión 6 mg/mL"],"Compatible con precaución","u03","c03_10",
  familia="Antivirales antigripales",emb="C",
  ci=["Hipersensibilidad"],
  ea=["Náuseas","Vómitos","Cefalea","Dolor abdominal","Comportamiento anormal (adolescentes, raro)"],
  ix=["Vacuna influenza intranasal: no administrar 2 sem antes ni 48h después","Probenecid: aumenta niveles"],
  ce=["Iniciar dentro de 48h del inicio de síntomas","Máxima eficacia si inicio <12h","Puede prepararse suspensión extemporánea","Vigilar comportamiento en adolescentes"]),

M("","zanamivir","Zanamivir","Zanamivir",["Relenza"],
  "Inhibidor de neuraminidasa inhalado",
  "Análogo del ácido siálico que inhibe neuraminidasa de influenza A y B. Administración por inhalación oral con depósito en vía respiratoria",
  ["Influenza A y B (tratamiento y profilaxis)"],
  ["inhalatoria"],{"adulto":"Tratamiento: 10 mg (2 inhalaciones) c/12h x 5 días. Profilaxis: 10 mg/día x 10-28 días",
  "pediatrico":"≥7 años: igual que adultos"},
  ["Polvo para inhalación 5 mg/dosis (Diskhaler)"],"Compatible con precaución","u03","c03_10",
  familia="Antivirales antigripales",emb="C",
  ci=["Hipersensibilidad","Alergia a proteínas de leche (contiene lactosa)","Asma o EPOC severo (riesgo de broncoespasmo)"],
  ea=["Broncoespasmo","Tos","Cefalea","Mareo","Sinusitis","Náuseas"],
  ix=["Vacuna influenza intranasal: separar 2 semanas"],
  ce=["NO usar en pacientes con asma/EPOC (broncoespasmo potencialmente fatal)","Iniciar dentro de 48h de síntomas","Enseñar uso correcto del Diskhaler","Tener broncodilatador disponible por si broncoespasmo"]),

M("","baloxavir","Baloxavir marboxil","Baloxavir marboxil",["Xofluza"],
  "Inhibidor de endonucleasa dependiente de cap",
  "Primer inhibidor de la endonucleasa dependiente de cap (PA) del virus influenza. Mecanismo novedoso: bloquea transcripción del ARNm viral",
  ["Influenza A y B (tratamiento, dosis única)","Profilaxis post-exposición influenza"],
  ["oral"],{"adulto":"40-80 kg: 40 mg dosis única. ≥80 kg: 80 mg dosis única","pediatrico":"≥5 años, 20-<40 kg: 20 mg dosis única. ≥40 kg: según adultos"},
  ["Comp 20, 40 mg"],"No recomendado","u03","c03_10",
  familia="Antivirales antigripales",emb="X",
  ci=["Hipersensibilidad"],
  ea=["Diarrea","Bronquitis","Náuseas","Sinusitis","Cefalea"],
  ix=["Cationes polivalentes (antiácidos, lácteos, calcio): reducen absorción significativamente","Probenecid: aumenta niveles"],
  ce=["DOSIS ÚNICA: tratamiento completo en 1 toma","Tomar sin alimentos o con comida baja en grasa","No tomar con lácteos ni antiácidos","Iniciar dentro de 48h de síntomas"]),

M("","peramivir","Peramivir","Peramivir",["Rapivab","Rapiacta"],
  "Inhibidor de neuraminidasa IV",
  "Inhibidor de neuraminidasa de uso IV. Permite tratamiento en pacientes que no toleran vía oral ni inhalatoria",
  ["Influenza A y B (tratamiento IV)"],
  ["IV"],{"adulto":"600 mg IV dosis única en 15-30 min","pediatrico":"2-12 años: 12 mg/kg (máx 600 mg) dosis única IV","ajusteRenal":"ClCr 30-49: 200 mg. ClCr 10-29: 100 mg"},
  ["Vial 200 mg/20 mL"],"No recomendado","u03","c03_10",
  familia="Antivirales antigripales",emb="C",
  ci=["Hipersensibilidad a inhibidores de neuraminidasa"],
  ea=["Diarrea","Náuseas","Neutropenia","Elevación transaminasas","Comportamiento anormal (raro)"],
  ix=["Vacuna influenza intranasal: separar 2 semanas"],
  ce=["Dosis única IV: ideal cuando no se tolera oral/inhalado","Infundir en 15-30 min","Ajustar dosis en insuficiencia renal","Iniciar dentro de 48h de síntomas"],
  pp={"dilucion":"Diluir en 100 mL SF","velocidadAdministracion":"Infundir en 15-30 min","estabilidad":"24h a TA"}),

M("","tecovirimat","Tecovirimat","Tecovirimat",["Tpoxx"],
  "Antiviral contra orthopoxvirus",
  "Inhibe la proteína VP37 de orthopoxvirus, bloqueando la liberación de viriones envueltos. Primer antiviral aprobado para viruela/mpox",
  ["Viruela del mono (mpox)","Viruela (bioterrorismo)","Infecciones por orthopoxvirus"],
  ["oral","IV"],{"adulto":"Oral: 600 mg c/12h con alimentos x 14 días (≥40 kg)","pediatrico":"≥13 kg: según peso"},
  ["Cáps 200 mg","Vial 200 mg/20 mL IV"],"No recomendado","u03","c03_10",
  familia="Antivirales (orthopoxvirus)",emb="C",
  ci=["Hipersensibilidad"],
  ea=["Cefalea","Náuseas","Dolor abdominal","Vómitos"],
  ix=["Repaglinida: tecovirimat induce CYP2C8 (reduce eficacia de repaglinida)","Midazolam: reduce niveles"],
  ce=["Tomar con alimentos grasos (mejora absorción)","Aprobado para mpox por uso compasivo/emergencia","Disponibilidad a través de reservas estratégicas","Duración 14 días"]),

M("","cidofovir","Cidofovir","Cidofovir",["Vistide"],
  "Análogo nucleotídico antiviral de amplio espectro",
  "Análogo de citidina fosfonato que inhibe ADN polimerasa viral. No requiere fosforilación por quinasa viral. Amplio espectro anti-ADN virus",
  ["Retinitis por CMV en SIDA","Adenovirus en inmunodeprimidos","Virus BK (off-label)","Condilomas (tópico off-label)"],
  ["IV"],{"adulto":"Inducción: 5 mg/kg IV semanal x 2 sem. Mantenimiento: 5 mg/kg c/2 semanas","ajusteRenal":"Contraindicado si creatinina >1.5 o ClCr <55"},
  ["Vial 75 mg/mL (5 mL)"],"Contraindicado","u03","c03_10",
  familia="Antivirales (CMV y ADN virus)",emb="X",
  ci=["Insuficiencia renal (creatinina >1.5 mg/dL)","Uso con otros nefrotóxicos","Hipersensibilidad a sulfonamidas (probenecid)"],
  ea=["⚠️ Nefrotoxicidad severa","Neutropenia","Uveítis/hipotonía ocular","Acidosis tubular renal","Síndrome de Fanconi"],
  ix=["Nefrotóxicos: contraindicado combinar","Probenecid: se administra obligatoriamente (reduce nefrotoxicidad)"],
  ce=["Hidratación agresiva pre/post: 1 L SF antes, 1 L con/post infusión","Probenecid obligatorio: 2 g oral 3h antes + 1 g a 2h y 8h post","Monitorizar creatinina y proteinuria antes de cada dosis","Suspender si proteinuria ≥2+ o creatinina sube >0.4 mg/dL"],
  pp={"dilucion":"Diluir en 100 mL SF","velocidadAdministracion":"Infundir en 60 min","estabilidad":"24h refrigerado"}),

M("","brincidofovir","Brincidofovir","Brincidofovir",["Tembexa"],
  "Conjugado lipídico de cidofovir (profármaco oral)",
  "Conjugado de cidofovir con lípido hexadeciloxipropilo. Concentra cidofovir intracelularmente sin nefrotoxicidad. Activo contra todos los virus ADN de doble cadena",
  ["Viruela (aprobado para biodefensa)","Adenovirus en inmunodeprimidos (off-label)","CMV (off-label)"],
  ["oral"],{"adulto":"200 mg semanal x 2 dosis (viruela)","pediatrico":"Según peso: 10 mg semanal (10-<25 kg) a 200 mg (>48 kg)"},
  ["Comp 100 mg","Suspensión 10 mg/mL"],"Contraindicado","u03","c03_10",
  familia="Antivirales (ADN virus)",emb="X",
  ci=["Hipersensibilidad"],
  ea=["Diarrea","Náuseas","Vómitos","Dolor abdominal","Elevación transaminasas"],
  ix=["Mínimas interacciones conocidas"],
  ce=["A diferencia de cidofovir: NO es nefrotóxico","Aprobado para viruela (reservas estratégicas)","Administrar con alimentos","Monitorizar función hepática"]),

M("","nirmatrelvir_ritonavir_det","Nirmatrelvir/Ritonavir (detalle)","Nirmatrelvir + Ritonavir",
  ["Paxlovid"],"Inhibidor de proteasa de SARS-CoV-2 + potenciador",
  "Nirmatrelvir inhibe proteasa principal (Mpro/3CLpro) de SARS-CoV-2. Ritonavir inhibe CYP3A4 para mantener niveles terapéuticos",
  ["COVID-19 leve a moderado en pacientes de alto riesgo"],
  ["oral"],{"adulto":"300/100 mg (2 comp nirmatrelvir + 1 comp ritonavir) c/12h x 5 días. Iniciar dentro de 5 días de síntomas",
  "ajusteRenal":"ClCr 30-59: 150/100 mg c/12h. ClCr <30: no recomendado"},
  ["Pack de 30 comp (20 nirmatrelvir 150 mg + 10 ritonavir 100 mg)"],"No recomendado","u03","c03_10",
  familia="Antivirales (SARS-CoV-2)",emb="C",
  ci=["Uso con fármacos altamente dependientes de CYP3A4 (riesgo letal)","Insuficiencia hepática o renal severa"],
  ea=["Disgeusia (sabor metálico)","Diarrea","Hipertensión","Mialgias","Elevación transaminasas"],
  ix=["⚠️ Ritonavir: inhibidor potente CYP3A4 — MUCHAS interacciones","Inmunosupresores: ajustar dosis","Anticoagulantes: riesgo sangrado","Consultar OBLIGATORIAMENTE base de interacciones"],
  ce=["Iniciar dentro de 5 días del inicio de síntomas","Verificar TODAS las interacciones (ritonavir es potente inhibidor CYP3A4)","Posible rebote viral post-tratamiento","No triturar comprimidos"]),

M("","molnupiravir","Molnupiravir","Molnupiravir",["Lagevrio"],
  "Análogo de ribonucleósido (mutagénesis letal viral)",
  "Profármaco que se incorpora al ARN viral como análogo de citidina/uridina, causando acumulación de mutaciones letales (catástrofe por error)",
  ["COVID-19 leve a moderado en pacientes de riesgo sin otras opciones"],
  ["oral"],{"adulto":"800 mg c/12h x 5 días. Iniciar dentro de 5 días de síntomas"},
  ["Cáps 200 mg"],"Contraindicado","u03","c03_10",
  familia="Antivirales (SARS-CoV-2)",emb="X",
  ci=["Embarazo","Menores de 18 años","Hipersensibilidad"],
  ea=["Diarrea","Náuseas","Mareo","Cefalea"],
  ix=["Mínimas interacciones farmacocinéticas (ventaja sobre Paxlovid)"],
  ce=["No usar en embarazo (mutagénico)","Alternativa cuando Paxlovid está contraindicado por interacciones","Menor eficacia que nirmatrelvir/ritonavir","Anticoncepción durante y 4 días post-tratamiento"]),

M("","remdesivir_det","Remdesivir (detalle)","Remdesivir",["Veklury"],
  "Análogo de adenosina antiviral IV",
  "Profármaco de análogo de adenosina que inhibe ARN polimerasa dependiente de ARN (RdRp) viral. Amplio espectro contra virus ARN",
  ["COVID-19 en pacientes hospitalizados","COVID-19 ambulatorio de alto riesgo (3 días)","Ébola (uso investigacional)"],
  ["IV"],{"adulto":"Día 1: 200 mg IV. Días 2-5 (ambulatorio) o 2-10 (hospitalizado): 100 mg IV/día",
  "pediatrico":"≥28 días y ≥3 kg: misma pauta ajustada al peso","ajusteRenal":"No usar si ClCr <30 (excipiente sulfobutiléter-beta-ciclodextrina)"},
  ["Vial 100 mg"],"No recomendado","u03","c03_10",
  familia="Antivirales (amplio espectro ARN)",emb="C",
  ci=["Hipersensibilidad","eGFR <30 (formulación IV, por excipiente)"],
  ea=["Náuseas","Elevación transaminasas","Bradicardia sinusal","Reacciones a la infusión","Erupción cutánea"],
  ix=["Cloroquina: antagonismo in vitro","Mínimas interacciones CYP"],
  ce=["Infundir en 30-120 min","Monitorizar función hepática y renal","Vigilar bradicardia durante infusión","Formulación ambulatoria: 3 días"],
  pp={"reconstitucion":"Reconstituir con 19 mL agua estéril","dilucion":"Diluir en 100-250 mL SF","velocidadAdministracion":"Infundir en 30-120 min","estabilidad":"4h a TA, 24h refrigerado"}),

# ── c03_07 Antirretrovirales (+5) ──
M("antirretroviral","abacavir_det","Abacavir (detalle)","Abacavir",["Ziagen"],
  "INTR análogo de guanosina",
  "Análogo de guanosina con excelente penetración al SNC. Requiere test HLA-B*5701 para prevenir hipersensibilidad potencialmente fatal",
  ["VIH (en combinación)","Componente de Triumeq y Kivexa"],
  ["oral"],{"adulto":"300 mg c/12h o 600 mg c/24h","pediatrico":"≥3 meses: 8 mg/kg c/12h (máx 300 mg c/12h)"},
  ["Comp 300 mg","Sol oral 20 mg/mL"],"Evitar durante lactancia","u03","c03_07",
  ea=["⚠️ Hipersensibilidad (HLA-B*5701+): fiebre, rash, síntomas GI/respiratorios","Náuseas","Cefalea","Insomnio","Mayor riesgo cardiovascular (controvertido)"],
  ci=["HLA-B*5701 positivo (CONTRAINDICACIÓN ABSOLUTA)","Insuficiencia hepática moderada-grave"],
  ce=["Test HLA-B*5701 OBLIGATORIO antes de prescribir","NUNCA reintroducir tras reacción de hipersensibilidad (fatal)","Puede tomarse con o sin alimentos","Tarjeta de alerta para el paciente"]),

M("antirretroviral","didanosina","Didanosina (ddI)","Didanosina",["Videx"],
  "INTR análogo de inosina",
  "Análogo de inosina/adenosina. Primer INTR alternativo tras zidovudina. Alta toxicidad mitocondrial limita uso actual",
  ["VIH (solo si no hay alternativa)"],
  ["oral"],{"adulto":"≥60 kg: 400 mg/día (liberación retardada). <60 kg: 250 mg/día. En ayunas",
  "ajusteRenal":"ClCr 30-59: reducir 50%. ClCr 10-29: reducir 75%"},
  ["Cáps EC 125, 200, 250, 400 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["⚠️ Pancreatitis (potencialmente fatal)","Neuropatía periférica","Acidosis láctica","Lipoatrofia","Hipertensión portal no cirrótica"],
  ci=["Pancreatitis previa","Uso con estavudina (pancreatitis letal)","Uso con alopurinol"],
  ce=["En desuso por toxicidad","Tomar en ayunas estricto (1h antes o 2h después de comida)","Monitorizar amilasa/lipasa","No combinar con estavudina ni ribavirina"]),

M("antirretroviral","efavirenz_det","Efavirenz (detalle)","Efavirenz",["Sustiva","Stocrin"],
  "INNTR de 1ª generación",
  "INNTR con alta eficacia pero efectos neuropsiquiátricos frecuentes. Se une a sitio hidrofóbico cercano al sitio activo de TR",
  ["VIH (en combinación, alternativa)"],
  ["oral"],{"adulto":"600 mg/día al acostarse con estómago vacío","pediatrico":"≥3 meses y ≥3.5 kg: según peso (100-600 mg/día)"},
  ["Comp 200, 600 mg","Cáps 50, 100, 200 mg"],"Evitar durante lactancia","u03","c03_07",emb="D",
  ea=["Efectos neuropsiquiátricos: sueños vívidos, mareo, depresión, ideación suicida","Rash","Hepatotoxicidad","Ginecomastia","Dislipidemia"],
  ce=["Tomar al acostarse (minimiza efectos SNC)","Efectos neuropsiquiátricos suelen mejorar en 2-4 semanas","Evitar en embarazo primer trimestre","Test de embarazo antes de iniciar en mujeres fértiles"]),

M("antirretroviral","dolutegravir_det","Dolutegravir (detalle)","Dolutegravir",["Tivicay"],
  "Inhibidor de integrasa de 2ª generación",
  "Inhibidor de integrasa de alta barrera genética. Bloquea transferencia de cadena del ADN viral. Primera línea OMS",
  ["VIH (primera línea en combinación)","VIH resistente a raltegravir (si no hay mutaciones Q148+)"],
  ["oral"],{"adulto":"50 mg/día (naïve). 50 mg c/12h si resistencia a integrasa o con rifampicina",
  "pediatrico":"≥4 sem y ≥3 kg: según peso"},
  ["Comp 10, 25, 50 mg","Comp dispersable 5 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Insomnio","Cefalea","Náuseas","Aumento de peso","Elevación de CPK","Neuropsiquiátricos (raro: depresión, ideación suicida)"],
  ce=["Primera línea OMS desde 2019","Alta barrera genética (ventaja clave)","Con rifampicina: duplicar a 50 mg c/12h","Separar 2h de cationes polivalentes (Ca, Fe, Mg, Al)"]),

M("antirretroviral","atazanavir_det","Atazanavir (detalle)","Atazanavir",["Reyataz"],
  "Inhibidor de proteasa azapéptido",
  "Inhibidor de proteasa azapéptido con perfil lipídico favorable. Causa hiperbilirrubinemia benigna (inhibe UGT1A1)",
  ["VIH (en combinación, potenciado con ritonavir o cobicistat)"],
  ["oral"],{"adulto":"300 mg + ritonavir 100 mg/día con alimentos. Naïve sin booster: 400 mg/día"},
  ["Cáps 150, 200, 300 mg"],"Evitar durante lactancia","u03","c03_07",
  ea=["Hiperbilirrubinemia indirecta/ictericia (frecuente, benigna)","Náuseas","Cefalea","Rash","Nefrolitiasis","Prolongación PR"],
  ci=["Uso con IBP (contraindicado)","Uso con alfuzosina, rifampicina, triazolam"],
  ce=["Ictericia cosmética (bilirrubina indirecta): benigna pero alarma al paciente, educar","No usar con IBP (reduce absorción)","Tomar con alimentos","Mejor perfil lipídico que otros IP"]),

# ── c03_09 Antifúngicos (+5) ──
M("antifungico_sistemico","caspofungina_det","Caspofungina (detalle)","Caspofungina",["Cancidas"],
  "Equinocandina (inhibidor de síntesis de pared fúngica)",
  "Primera equinocandina. Inhibe síntesis de 1,3-beta-D-glucano de la pared celular fúngica. Fungicida contra Candida, fungistática contra Aspergillus",
  ["Candidiasis invasiva","Candidemia","Aspergilosis invasiva (segunda línea/rescate)","Candidiasis esofágica refractaria","Terapia empírica en neutropenia febril"],
  ["IV"],{"adulto":"Día 1: 70 mg IV. Días siguientes: 50 mg IV/día","pediatrico":"Día 1: 70 mg/m². Luego 50 mg/m²/día (máx 70 mg)","ajusteHepatico":"Child-Pugh B: 35 mg/día mantenimiento"},
  ["Vial 50, 70 mg"],"No recomendado","u03","c03_09",
  pp={"reconstitucion":"Reconstituir con 10.8 mL SF o agua estéril","dilucion":"Diluir en 100-250 mL SF","velocidadAdministracion":"Infundir en 60 min","estabilidad":"24h a TA, 48h refrigerado"}),

M("antifungico_sistemico","micafungina_det","Micafungina (detalle)","Micafungina",["Mycamine"],
  "Equinocandina de segunda generación",
  "Equinocandina con actividad fungicida contra Candida y fungistática contra Aspergillus. No requiere dosis de carga",
  ["Candidiasis invasiva/candidemia","Candidiasis esofágica","Profilaxis antifúngica en trasplante de células madre"],
  ["IV"],{"adulto":"Candidemia: 100 mg/día. Profilaxis: 50 mg/día. Candidiasis esofágica: 150 mg/día","pediatrico":"2-4 mg/kg/día según indicación"},
  ["Vial 50, 100 mg"],"No recomendado","u03","c03_09",
  pp={"reconstitucion":"Reconstituir con 5 mL SF o SG5%","dilucion":"Diluir en 100 mL SF o SG5%","velocidadAdministracion":"Infundir en 60 min","estabilidad":"96h a TA protegido de luz"}),

M("antifungico_sistemico","anidulafungina_det","Anidulafungina (detalle)","Anidulafungina",["Ecalta","Eraxis"],
  "Equinocandina semisintética",
  "Equinocandina que se degrada químicamente (no metabolismo hepático). No requiere ajuste en insuficiencia hepática ni renal",
  ["Candidiasis invasiva/candidemia","Candidiasis esofágica","Peritonitis por Candida"],
  ["IV"],{"adulto":"Día 1: 200 mg. Luego 100 mg/día"},
  ["Vial 100 mg"],"No recomendado","u03","c03_09",
  ea=["Diarrea","Hipopotasemia","Elevación transaminasas","Flebitis","Rubor facial (si infusión rápida)"],
  ce=["No requiere ajuste hepático ni renal (degradación química)","No administrar más rápido de 1.1 mg/min","Vigilar reacciones histamínicas si infusión rápida","Mínimas interacciones farmacológicas"],
  pp={"reconstitucion":"Reconstituir con 15 mL agua estéril (luego 30 mL)","dilucion":"Diluir en 100-250 mL SF o SG5%","velocidadAdministracion":"Infundir en ≥90 min (no >1.1 mg/min)","estabilidad":"24h a TA"}),

M("antifungico_sistemico","posaconazol_det","Posaconazol (detalle)","Posaconazol",["Noxafil"],
  "Triazol de segunda generación de espectro extendido",
  "Triazol con el espectro más amplio de su clase. Activo contra Aspergillus, Candida, Zygomycetes, Fusarium y Coccidioides",
  ["Profilaxis antifúngica en neutropenia prolongada","Aspergilosis invasiva refractaria","Mucormicosis (zigomicosis)","Fusariosis"],
  ["oral","IV"],{"adulto":"Profilaxis: 300 mg/día (comp o IV). Tratamiento: 300 mg c/12h d1, luego 300 mg/día",
  "ajusteRenal":"IV: evitar si ClCr <50 (excipiente ciclodextrina)"},
  ["Comp GR 100 mg","Suspensión 40 mg/mL","Vial 300 mg/16.7 mL"],"Contraindicado","u03","c03_09",
  ea=["Náuseas","Diarrea","Cefalea","Hipopotasemia","Prolongación QT","Hepatotoxicidad","Elevación transaminasas"],
  ce=["Comprimidos GR: con o sin alimentos. Suspensión: con comida grasa","Único azol eficaz contra Mucor/Rhizopus","Monitorizar niveles plasmáticos (meta >1 mcg/mL profilaxis, >1.25 tratamiento)","Vigilar QT y función hepática"]),

M("antifungico_sistemico","isavuconazol_det","Isavuconazol (detalle)","Isavuconazonium sulfato",["Cresemba"],
  "Triazol de nueva generación",
  "Profármaco (isavuconazonium) que se convierte a isavuconazol. Amplio espectro incluyendo Aspergillus y Mucorales. Perfil de seguridad favorable",
  ["Aspergilosis invasiva (primera línea alternativa a voriconazol)","Mucormicosis"],
  ["oral","IV"],{"adulto":"Carga: 200 mg c/8h x 6 dosis (48h). Mantenimiento: 200 mg/día"},
  ["Cáps 100 mg","Vial 200 mg"],"Contraindicado","u03","c03_09",
  ea=["Náuseas","Vómitos","Diarrea","Cefalea","Elevación transaminasas","Hipopotasemia","Acortamiento QT (único)"],
  ce=["Acorta QT (contraindicado en QT corto familiar)","Mejor tolerado que voriconazol (sin efectos visuales)","No requiere ajuste renal (IV sin ciclodextrina)","Puede tomarse con o sin alimentos"],
  pp={"reconstitucion":"Reconstituir con 5 mL agua estéril","dilucion":"Diluir en 250 mL SF o SG5%","velocidadAdministracion":"Infundir en ≥60 min","estabilidad":"6h a TA, 24h refrigerado"}),

# ══════════════════════════════════════════════════════════════════
# U04 — SISTEMA RESPIRATORIO (~30 drugs)
# ══════════════════════════════════════════════════════════════════

# ── c04_01 Broncodilatadores (+6) ──
M("broncodilatador_beta2","formoterol_det","Formoterol (detalle)","Fumarato de formoterol",
  ["Foradil","Oxis","Perforomist"],"Beta-2 agonista de acción prolongada (LABA)",
  "LABA con inicio rápido (1-3 min) y duración 12h. Agonista completo beta-2. Único LABA que puede usarse como rescate (estrategia MART)",
  ["Asma (siempre con CI, estrategia MART)","EPOC mantenimiento","Broncoespasmo inducido por ejercicio"],
  ["inhalatoria"],{"adulto":"Mantenimiento: 12-24 mcg c/12h. MART (con budesonida): 6 mcg PRN","pediatrico":"≥6 años: 12 mcg c/12h"},
  ["Polvo 12 mcg/dosis (Aerolizer)","Sol nebulización 20 mcg/2 mL","IDM 12 mcg/dosis"],"Compatible con precaución","u04","c04_01"),

M("broncodilatador_beta2","indacaterol_det","Indacaterol (detalle)","Indacaterol",["Onbrez","Arcapta"],
  "Beta-2 agonista de acción ultraprolongada (ultra-LABA)",
  "Ultra-LABA con duración de 24h y inicio en 5 min. Permite dosificación una vez al día",
  ["EPOC mantenimiento"],
  ["inhalatoria"],{"adulto":"150-300 mcg inhalados 1 vez al día (Breezhaler)"},
  ["Cáps para inhalación 150, 300 mcg (Breezhaler)"],"Compatible con precaución","u04","c04_01",
  ea=["Tos post-inhalación (frecuente)","Nasofaringitis","Cefalea","Temblor","Palpitaciones"],
  ce=["Tos post-inhalación transitoria es frecuente y esperada","1 inhalación al día","Solo para EPOC (no aprobado en asma como monoterapia)","Dispositivo Breezhaler: perforar cápsula e inhalar"]),

M("broncodilatador_beta2","vilanterol_det","Vilanterol (detalle)","Vilanterol",["Solo en combinaciones fijas"],
  "Ultra-LABA de 24h diseñado para combinaciones",
  "Agonista beta-2 selectivo de 24h. Solo disponible en combinaciones fijas: con fluticasona, umeclidinio o ambos (Trelegy Ellipta)",
  ["Asma (siempre combinado con CI)","EPOC (en combinación)"],
  ["inhalatoria"],{"adulto":"25 mcg/día en combinación fija (1 inhalación)"},
  ["Polvo para inhalación 25 mcg/dosis (solo en Ellipta)"],"Compatible con precaución","u04","c04_01",
  ea=["Nasofaringitis","Cefalea","Infección respiratoria superior","Artralgia"],
  ce=["Nunca como monoterapia en asma","Solo disponible en combinaciones Ellipta","1 inhalación al día","Dispositivo Ellipta: abrir-inhalar-cerrar"]),

M("broncodilatador_beta2","olodaterol_det","Olodaterol (detalle)","Olodaterol",["Striverdi Respimat"],
  "Ultra-LABA de 24h para Respimat",
  "Agonista beta-2 con selectividad superior. Formulación en solución Respimat que no requiere coordinación ni esfuerzo inspiratorio alto",
  ["EPOC mantenimiento","Broncoespasmo en EPOC (no rescate)"],
  ["inhalatoria"],{"adulto":"5 mcg (2 pulsaciones de 2.5 mcg) 1 vez al día"},
  ["Solución Respimat 2.5 mcg/dosis"],"Compatible con precaución","u04","c04_01",
  ea=["Nasofaringitis","Mareo","Rash","Artralgia","Tos"],
  ce=["Dispositivo Respimat: no requiere alto flujo inspiratorio","Ideal para pacientes con EPOC severo (bajo flujo)","1 vez al día","No usar como rescate"]),

M("broncodilatador_beta2","terbutalina_inh","Terbutalina inhalatoria","Terbutalina",
  ["Bricanyl Turbuhaler"],"SABA inhalado",
  "Beta-2 agonista de acción corta para inhalación. Dispositivo polvo seco Turbuhaler activado por flujo inspiratorio",
  ["Broncoespasmo agudo (rescate)","Asma aguda","Prevención de broncoespasmo por ejercicio"],
  ["inhalatoria"],{"adulto":"500 mcg/dosis PRN (máx c/4-6h)","pediatrico":"≥6 años: 500 mcg PRN"},
  ["Turbuhaler 500 mcg/dosis"],"Compatible con precaución","u04","c04_01",
  ea=["Temblor","Taquicardia","Palpitaciones","Cefalea","Calambres"],
  ce=["SABA de rescate alternativo a salbutamol","Turbuhaler: no requiere coordinación, activado por inspiración","No agitar (polvo seco)","Girar base para cargar dosis"]),

M("broncodilatador_beta2","fenoterol_inh","Fenoterol inhalatorio","Fenoterol",
  ["Berotec"],"SABA inhalado",
  "Beta-2 agonista de acción corta con potencia mayor que salbutamol. Inicio rápido, duración 4-6h",
  ["Broncoespasmo agudo","Asma aguda","EPOC con broncoespasmo"],
  ["inhalatoria"],{"adulto":"100-200 mcg PRN (máx c/4-6h)","pediatrico":"≥6 años: 100 mcg PRN"},
  ["IDM 100 mcg/dosis","Sol nebulización 0.5 mg/mL"],"Compatible con precaución","u04","c04_01",
  ea=["Temblor","Taquicardia","Palpitaciones","Cefalea","Hipopotasemia"],
  ce=["Mayor potencia que salbutamol: mayor riesgo de efectos cardíacos","Uso frecuente en Latinoamérica","Disponible en combinación con ipratropio (Duovent)","No exceder 8 pulsaciones/día"]),

# ── c04_02 Anticolinérgicos inhalados (+4) ──
M("anticolinergico_inhalado","aclidinio_det","Aclidinio (detalle)","Bromuro de aclidinio",
  ["Tudorza","Eklira Genuair"],"LAMA de acción prolongada c/12h",
  "Antagonista muscarínico M3 con disociación lenta de receptores bronquiales. Hidrólisis plasmática rápida (mínimos efectos sistémicos)",
  ["EPOC mantenimiento"],
  ["inhalatoria"],{"adulto":"400 mcg c/12h (Genuair/Pressair)"},
  ["Polvo inhalación 400 mcg/dosis (Genuair)"],"Compatible con precaución","u04","c04_02",
  ea=["Boca seca","Cefalea","Nasofaringitis","Tos","Sinusitis"],
  ce=["Dosificación c/12h (vs tiotropio c/24h)","Hidrólisis plasmática rápida: menores efectos sistémicos","Dispositivo Genuair: indicador de dosis y confirmación auditiva","Evitar contacto con ojos"]),

M("anticolinergico_inhalado","glicopirronio_inh_det","Glicopirronio inhalado (detalle)","Bromuro de glicopirronio",
  ["Seebri","Tovanor"],"LAMA de acción prolongada c/24h",
  "LAMA con inicio de acción más rápido que tiotropio (5 min vs 30 min). Selectividad por M1/M3 bronquial. Dosificación c/24h",
  ["EPOC mantenimiento"],
  ["inhalatoria"],{"adulto":"50 mcg (44 mcg liberados) 1 vez al día (Breezhaler)"},
  ["Cáps para inhalación 50 mcg (Breezhaler)"],"Compatible con precaución","u04","c04_02",
  ea=["Boca seca","Nasofaringitis","Insomnio","Dolor orofaríngeo","ITU"],
  ce=["Inicio más rápido que tiotropio","1 vez al día con Breezhaler","Perforar cápsula antes de inhalar","Componente LAMA de Ultibro (con indacaterol)"]),

M("anticolinergico_inhalado","umeclidinio","Umeclidinio","Bromuro de umeclidinio",
  ["Incruse Ellipta"],"LAMA de acción prolongada c/24h",
  "Antagonista muscarínico de larga acción diseñado para dispositivo Ellipta. Alta selectividad M3 bronquial y disociación extremadamente lenta",
  ["EPOC mantenimiento"],
  ["inhalatoria"],{"adulto":"62.5 mcg 1 inhalación al día"},
  ["Polvo inhalación 62.5 mcg/dosis (Ellipta)"],"Compatible con precaución","u04","c04_02",
  ea=["Nasofaringitis","Infección respiratoria superior","Tos","Artralgia"],
  ce=["Componente LAMA de Anoro (con vilanterol) y Trelegy (triple)","1 inhalación al día con Ellipta","Dispositivo Ellipta muy fácil de usar","Mismo dispositivo para monoterapia y combinaciones"]),

M("anticolinergico_inhalado","revefenacina_det","Revefenacina (detalle)","Revefenacina",
  ["Yupelri"],"LAMA para nebulización c/24h",
  "Único LAMA en solución para nebulización. Permite terapia anticolinérgica prolongada en pacientes que no pueden usar inhaladores de mano",
  ["EPOC mantenimiento (pacientes que no pueden usar inhaladores)"],
  ["inhalatoria"],{"adulto":"175 mcg nebulizados 1 vez al día"},
  ["Vial 175 mcg/3 mL para nebulización"],"No recomendado","u04","c04_02",
  ea=["Tos","Nasofaringitis","Infección respiratoria superior","Cefalea","Dolor de espalda"],
  ce=["Único LAMA disponible para nebulización","Nebulizador jet estándar (no ultrasónico)","No mezclar con otros fármacos en nebulizador","Ideal en pacientes ancianos con mala técnica inhalatoria"]),

# ── c04_03 Corticoides inhalados (+4) ──
M("corticoide_inhalado","mometasona_inh","Mometasona inhalada","Furoato de mometasona",
  ["Asmanex Twisthaler"],"Corticoide inhalado de alta potencia",
  "Corticoide inhalado con alta afinidad por receptor glucocorticoide. Baja biodisponibilidad oral (<1%). Dosificación 1-2 veces al día",
  ["Asma persistente (mantenimiento)"],
  ["inhalatoria"],{"adulto":"Dosis baja: 200 mcg/día. Dosis media: 400 mcg/día. Dosis alta: 800 mcg/día",
  "pediatrico":"4-11 años: 110 mcg/día al atardecer"},
  ["Twisthaler 110, 220 mcg/dosis"],"Compatible con precaución","u04","c04_03"),

M("corticoide_inhalado","ciclesonida_det","Ciclesonida (detalle)","Ciclesonida",["Alvesco"],
  "Corticoide inhalado profármaco",
  "Profármaco inactivo activado por esterasas pulmonares a des-ciclesonida. Mínima deposición orofaríngea (menor candidiasis) y alta unión a proteínas",
  ["Asma persistente (mantenimiento)"],
  ["inhalatoria"],{"adulto":"Dosis baja: 80 mcg/día. Dosis media: 160 mcg/día. Dosis alta: 320 mcg/día",
  "pediatrico":"≥12 años: 80-320 mcg/día"},
  ["IDM 80, 160 mcg/dosis (HFA)"],"Compatible con precaución","u04","c04_03",
  ea=["Cefalea","Nasofaringitis","Disfonía (infrecuente)","Candidiasis orofaríngea (muy baja incidencia)"],
  ce=["Profármaco: mínima deposición orofaríngea → menos candidiasis","Partículas extrafinas (HFA): buen depósito periférico","Puede no requerir enjuague bucal (ventaja vs otros CI)","1 inhalación al día en muchos pacientes"]),

M("corticoide_inhalado","beclometasona_inh","Beclometasona inhalada","Dipropionato de beclometasona",
  ["Beclovent","Qvar","Becotide"],"Corticoide inhalado clásico",
  "Primer corticoide inhalado. Profármaco activado por esterasas a beclometasona-17-monopropionato. Formulación HFA extrafina mejora depósito",
  ["Asma persistente (mantenimiento)","EPOC con componente inflamatorio"],
  ["inhalatoria"],{"adulto":"Dosis baja: 100-200 mcg/día. Dosis media: 200-400 mcg/día. Dosis alta: >400 mcg/día (HFA extrafino)",
  "pediatrico":"5-11 años: 50-100 mcg/día (HFA)"},
  ["IDM HFA 50, 100, 200, 250 mcg/dosis"],"Compatible con precaución","u04","c04_03"),

M("corticoide_inhalado","triamcinolona_inh","Triamcinolona inhalada","Acetónido de triamcinolona",
  ["Azmacort"],"Corticoide inhalado de potencia intermedia",
  "Corticoide inhalado con potencia intermedia. Menor supresión adrenal a dosis equivalentes. Formulación descontinuada en varios mercados",
  ["Asma persistente leve a moderada"],
  ["inhalatoria"],{"adulto":"150-600 mcg/día divididos en 2-4 inhalaciones","pediatrico":"6-12 años: 75-300 mcg/día"},
  ["IDM 75 mcg/dosis"],"Compatible con precaución","u04","c04_03",
  ea=["Candidiasis orofaríngea","Disfonía","Tos","Irritación faríngea"],
  ce=["Usar espaciador siempre","Enjuagar boca post-uso","Potencia intermedia: puede requerir más pulsaciones","Descontinuado en algunos mercados"]),

# ── c04_04 Antiasmáticos/Anti-IgE (+6) ──
M("inmunosupresor","mepolizumab_det","Mepolizumab (detalle)","Mepolizumab",["Nucala"],
  "Anti-IL-5 (anticuerpo monoclonal)",
  "Anticuerpo monoclonal humanizado anti-IL-5 que reduce eosinófilos circulantes y tisulares. Específico para asma eosinofílica",
  ["Asma severa eosinofílica (≥6 años)","Granulomatosis eosinofílica con poliangiítis (GEPA)","Síndrome hipereosinofílico"],
  ["SC"],{"adulto":"Asma: 100 mg SC c/4 semanas. GEPA: 300 mg SC c/4 sem","pediatrico":"6-11 años: 40 mg SC c/4 sem"},
  ["Jeringa precargada 100 mg","Pluma 100 mg","Vial 100 mg"],"No recomendado","u04","c04_04",
  ea=["Cefalea","Reacción en sitio de inyección","Dolor de espalda","Fatiga","Reacción alérgica (raro)"],
  ce=["Solo para asma eosinofílica (eosinófilos ≥150/mcL)","No usar para crisis aguda","Administrar SC cada 4 semanas","Puede autoadministrarse (pluma)"]),

M("inmunosupresor","benralizumab_det","Benralizumab (detalle)","Benralizumab",["Fasenra"],
  "Anti-receptor IL-5 (anticuerpo monoclonal depletor de eosinófilos)",
  "Anti-IL-5Rα que produce apoptosis directa de eosinófilos por ADCC (citotoxicidad celular dependiente de anticuerpo). Depleción casi completa de eosinófilos",
  ["Asma severa eosinofílica (≥12 años)"],
  ["SC"],{"adulto":"30 mg SC c/4 sem x 3 dosis, luego c/8 semanas"},
  ["Jeringa precargada 30 mg","Pluma precargada 30 mg"],"No recomendado","u04","c04_04",
  ea=["Cefalea","Faringitis","Reacción en sitio inyección","Fiebre","Reacción anafilactoide (raro)"],
  ce=["Ventaja: dosificación c/8 semanas (tras carga)","Depleción casi total de eosinófilos","Para eosinófilos ≥300/mcL (mejor respuesta)","Observar 30 min post-primera dosis"]),

M("inmunosupresor","dupilumab_asma","Dupilumab (asma)","Dupilumab",["Dupixent"],
  "Anti-IL-4Rα (anticuerpo monoclonal anti-inflamación tipo 2)",
  "Bloquea señalización de IL-4 e IL-13 vía receptor compartido IL-4Rα. Reduce inflamación tipo 2 en asma, dermatitis atópica y rinosinusitis",
  ["Asma severa eosinofílica o dependiente de corticoides","Dermatitis atópica moderada-severa","Rinosinusitis crónica con pólipos nasales"],
  ["SC"],{"adulto":"Asma: 200-300 mg SC c/2 semanas (dosis según peso/indicación)","pediatrico":"≥6 años: según peso"},
  ["Jeringa precargada 200, 300 mg","Pluma precargada 200, 300 mg"],"No recomendado","u04","c04_04",
  ea=["Reacción en sitio inyección","Eosinofilia transitoria","Conjuntivitis","Artralgia","Herpes oral"],
  ce=["Eficaz en asma eosinofílica Y dependiente de corticoides","Puede causar eosinofilia transitoria al inicio","Reducción gradual de corticoides sistémicos","Puede autoadministrarse"]),

M("inmunosupresor","tezepelumab_det","Tezepelumab (detalle)","Tezepelumab",["Tezspire"],
  "Anti-TSLP (anti-alarmina upstream)",
  "Primer anti-TSLP. Bloquea linfopoyetina estromal tímica, alarmina que inicia cascada inflamatoria. Eficaz INDEPENDIENTE del fenotipo inflamatorio",
  ["Asma severa refractaria (≥12 años) — todos los fenotipos"],
  ["SC"],{"adulto":"210 mg SC c/4 semanas","pediatrico":"≥12 años: 210 mg SC c/4 sem"},
  ["Jeringa precargada 210 mg/1.91 mL","Pluma precargada 210 mg"],"No recomendado","u04","c04_04",
  ea=["Faringitis","Artralgia","Dolor de espalda","Reacción en sitio inyección"],
  ce=["Único biológico eficaz independiente del fenotipo (eosinofílico o no)","No necesita nivel de eosinófilos previo para indicar","Administrar SC cada 4 semanas","Rotar sitios de inyección"]),

M("","fevipiprant","Fevipiprant","Fevipiprant",["Fevipiprant"],
  "Antagonista receptor DP2/CRTH2",
  "Antagonista selectivo del receptor prostaglandina D2 tipo 2 (DP2/CRTH2) en eosinófilos, basófilos y linfocitos Th2. Reduce migración eosinofílica a pulmón",
  ["Asma moderada a severa (en investigación/uso limitado)","Reducción de eosinófilos en esputo"],
  ["oral"],{"adulto":"150 mg/día"},
  ["Comp 150 mg"],"No recomendado","u04","c04_04",
  familia="Antagonistas de prostaglandinas",emb="C",
  ci=["Hipersensibilidad"],
  ea=["Cefalea","Nasofaringitis","Elevación transaminasas","Infección respiratoria superior"],
  ix=["Mínimas interacciones conocidas"],
  ce=["Nuevo mecanismo: antagonista DP2/CRTH2 oral","Disponibilidad limitada (desarrollo clínico)","Reduce eosinófilos en esputo","Potencial terapia oral complementaria para asma eosinofílica"]),

M("","zileuton","Zileuton","Zileuton",["Zyflo","Zyflo CR"],
  "Inhibidor de 5-lipoxigenasa",
  "Único inhibidor directo de 5-lipoxigenasa. Bloquea síntesis de TODOS los leucotrienos (LTB4, LTC4, LTD4, LTE4), a diferencia de montelukast que solo bloquea receptor",
  ["Asma persistente (alternativa o complemento)","Asma inducida por aspirina","Urticaria crónica (off-label)"],
  ["oral"],{"adulto":"IR: 600 mg c/6h. LP: 1200 mg c/12h"},
  ["Comp 600 mg","Comp LP 600 mg"],"Contraindicado","u04","c04_04",
  familia="Inhibidores de leucotrienos",emb="C",
  ci=["Insuficiencia hepática activa","Transaminasas >3x LSN","Hipersensibilidad"],
  ea=["Hepatotoxicidad (⚠️ requiere monitorización)","Cefalea","Dispepsia","Mialgias","Insomnio"],
  ix=["Warfarina: aumenta INR","Teofilina: aumenta niveles (reducir dosis teofilina)","Propranolol: aumenta niveles"],
  ce=["Monitorizar ALT mensual x 3 meses, luego c/2-3 meses","Suspender si ALT >5x LSN","Inhibe TODOS los leucotrienos (vs montelukast solo CysLT1)","Eficaz en asma por aspirina"]),

# ── c04_05 Mucolíticos (+3) ──
M("","erdosteina_det","Erdosteína (detalle)","Erdosteína",["Erdos","Vectrine"],
  "Mucolítico tiol con propiedades antioxidantes",
  "Profármaco con 3 metabolitos activos con grupos tiol. Rompe puentes disulfuro del moco, reduce adherencia bacteriana y tiene efecto antioxidante",
  ["EPOC (reducción de exacerbaciones)","Bronquitis aguda y crónica","Bronquiectasias"],
  ["oral"],{"adulto":"300 mg c/12h. Tratamiento agudo: 7-10 días. EPOC: largo plazo"},
  ["Cáps 300 mg","Sobres 175, 225 mg"],"Compatible con precaución","u04","c04_05",
  familia="Mucolíticos",emb="B",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Úlcera péptica activa"],
  ea=["Náuseas","Dolor abdominal","Diarrea","Cefalea","Disgeusia"],
  ix=["Antitusivos: no combinar (retención de moco)","Antibióticos: mejora penetración en secreciones bronquiales"],
  ce=["Estudio RESTORE: reduce exacerbaciones EPOC 20%","Administrar con alimentos","Mejora penetración de antibióticos en moco","No combinar con antitusivos"]),

M("","bromhexina_det","Bromhexina (detalle)","Clorhidrato de bromhexina",["Bisolvon"],
  "Mucolítico derivado de vasicina",
  "Derivado sintético del alcaloide vasicina. Aumenta secreción de surfactante y reduce viscosidad del moco bronquial. Metabolito activo: ambroxol",
  ["Tos productiva","Bronquitis aguda y crónica","Facilitación de expectoración"],
  ["oral"],{"adulto":"8-16 mg c/8h","pediatrico":"<2 años: 2 mg c/8h. 2-6 años: 4 mg c/8h. 6-12 años: 8 mg c/8h"},
  ["Comp 8 mg","Jarabe 4 mg/5 mL","Gotas pediátricas 2 mg/mL"],"Compatible con precaución","u04","c04_05",
  familia="Mucolíticos",emb="B",
  ci=["Hipersensibilidad","Úlcera gastroduodenal activa"],
  ea=["Náuseas","Dolor epigástrico","Diarrea","Elevación transaminasas (raro)"],
  ix=["Antibióticos: aumenta concentración de amoxicilina y eritromicina en secreción bronquial","Antitusivos: evitar combinación"],
  ce=["Precursor de ambroxol (metabolito activo)","Administrar con abundante agua","Aumenta penetración de antibióticos en moco","Buena tolerancia a largo plazo"]),

M("","sobrerrol","Sobrerrol","Sobrerrol",["Sobrepin","Sobrerrol"],
  "Mucolítico terpénico",
  "Derivado terpénico (del pineno) con acción mucolítica y secretolítica. Reduce viscosidad del moco por ruptura de mucopolisacáridos",
  ["Tos productiva","Bronquitis aguda","Catarro de vías respiratorias altas"],
  ["oral","rectal"],{"adulto":"Oral: 200 mg c/8-12h. Rectal: 400 mg c/12h","pediatrico":"Oral: 100 mg c/8h. Rectal: 200 mg c/12h"},
  ["Cáps 200 mg","Sup 200, 400 mg","Jarabe 40 mg/5 mL"],"Compatible con precaución","u04","c04_05",
  familia="Mucolíticos",emb="C",
  ci=["Hipersensibilidad","Tos productiva que no debe suprimirse (no es antitusivo)"],
  ea=["Molestias gástricas leves","Náuseas","Diarrea","Cefalea (raro)"],
  ix=["Antitusivos: evitar combinación"],
  ce=["Mucolítico terpénico natural","Bien tolerado","Disponible en supositorios (útil si vómitos)","Uso predominante en Europa mediterránea"]),

# ── c04_08 Antifibróticos Pulmonares (4) — NUEVO ──
M("","pirfenidona_det","Pirfenidona (detalle)","Pirfenidona",["Esbriet"],
  "Antifibrótico pulmonar",
  "Mecanismo multifactorial: inhibe TGF-beta, reduce proliferación de fibroblastos, disminuye síntesis de colágeno y tiene efecto antiinflamatorio",
  ["Fibrosis pulmonar idiopática (FPI)"],
  ["oral"],{"adulto":"Titulación: 267 mg c/8h x 7 días → 534 mg c/8h x 7 días → 801 mg c/8h (mantenimiento)"},
  ["Comp 267, 801 mg","Cáps 267 mg"],"Contraindicado","u04","c04_08",
  familia="Antifibróticos pulmonares",emb="X",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Insuficiencia renal grave (ClCr <30)","Uso con fluvoxamina"],
  ea=["Náuseas","Anorexia y pérdida de peso","Fotosensibilidad (severa)","Rash","Diarrea","Fatiga","Hepatotoxicidad","Mareo"],
  ix=["Fluvoxamina: contraindicado (inhibidor CYP1A2, quintuplica niveles)","Ciprofloxacino: aumenta niveles (inhibidor moderado CYP1A2)","Omeprazol: puede aumentar niveles","Tabaco: reduce niveles (inductor CYP1A2)"],
  ce=["Titulación gradual obligatoria (reduce náuseas)","Tomar con alimentos (reduce GI)","Fotoprotección estricta: protector solar SPF50+, ropa protectora","Función hepática mensual x 6 meses, luego trimestral","Ralentiza progresión de FPI, no cura"]),

M("","nintedanib_det","Nintedanib (detalle)","Nintedanib",["Ofev"],
  "Inhibidor triple de tirosina quinasa antifibrótico",
  "Inhibidor de VEGFR, FGFR y PDGFR. Reduce proliferación de fibroblastos, migración y transformación a miofibroblastos. Antiangiogénico",
  ["Fibrosis pulmonar idiopática (FPI)","Enfermedad pulmonar intersticial asociada a esclerosis sistémica","Fibrosis pulmonar con patrón fibrosante progresivo"],
  ["oral"],{"adulto":"150 mg c/12h con alimentos","ajusteHepatico":"Child-Pugh A: 100 mg c/12h. Child-Pugh B/C: no recomendado"},
  ["Cáps blandas 100, 150 mg"],"Contraindicado","u04","c04_08",
  familia="Antifibróticos pulmonares",emb="X",
  ci=["Hipersensibilidad","Embarazo","Alergia a soja o cacahuete (excipiente lecitina de soja)"],
  ea=["Diarrea (⚠️ muy frecuente, 62%)","Náuseas","Vómitos","Dolor abdominal","Hepatotoxicidad","Sangrado"],
  ix=["Ketoconazol: aumenta niveles 60%","Rifampicina: reduce niveles 50%","Anticoagulantes: mayor riesgo sangrado"],
  ce=["Diarrea muy frecuente: manejar con loperamida profiláctica","Tomar con alimentos (reduce GI)","Función hepática mensual x 3 meses, luego periódica","Anticoncepción eficaz obligatoria","Tragar cápsulas enteras (no abrir)"]),

M("","pentraxina","Pentraxina 2 recombinante","Pentraxina 2 humana recombinante (PRM-151)",
  ["Pentraxina"],"Proteína antifibrótica recombinante",
  "Forma recombinante de pentraxina 2 (SAP sérica). Promueve diferenciación de monocitos a macrófagos reguladores y reduce fibrosis tisular activa",
  ["Fibrosis pulmonar idiopática (en investigación/uso compasivo)","Mielofibrosis (en investigación)"],
  ["IV"],{"adulto":"10 mg/kg IV c/4 semanas"},
  ["Vial para infusión IV"],"No recomendado","u04","c04_08",
  familia="Antifibróticos pulmonares biológicos",emb="X",
  ci=["Hipersensibilidad"],
  ea=["Fatiga","Tos","Reacciones a la infusión","Artralgia","Náuseas"],
  ix=["No se esperan interacciones significativas por CYP"],
  ce=["En fase de investigación clínica avanzada","Mecanismo novedoso: promueve resolución de fibrosis","Infundir en 60 min en centro especializado","Monitorizar durante infusión"]),

M("","pamrevlumab","Pamrevlumab","Pamrevlumab",["Pamrevlumab"],
  "Anti-CTGF (anticuerpo monoclonal antifibrótico)",
  "Anticuerpo monoclonal completamente humano contra el factor de crecimiento del tejido conectivo (CTGF/CCN2). Inhibe señalización profibrótica downstream de TGF-beta",
  ["Fibrosis pulmonar idiopática (en investigación avanzada)","Distrofia muscular de Duchenne (en investigación)"],
  ["IV"],{"adulto":"35 mg/kg IV c/3 semanas"},
  ["Vial para infusión IV"],"No recomendado","u04","c04_08",
  familia="Antifibróticos pulmonares biológicos",emb="X",
  ci=["Hipersensibilidad"],
  ea=["Infección respiratoria superior","Tos","Fatiga","Reacciones a la infusión","Cefalea"],
  ix=["No interacciones farmacológicas significativas esperadas"],
  ce=["En fase de investigación clínica","Anti-CTGF: bloquea vía fibrótica específica","Infundir en centro especializado","Potencial nueva clase terapéutica para FPI"]),

# ── c04_07 Antitusígenos (+3) ──
M("","levodropropizina_det","Levodropropizina (detalle)","Levodropropizina",["Levotuss","Antux"],
  "Antitusígeno periférico no opioide",
  "Actúa sobre fibras C aferentes en vía aérea reduciendo liberación de neuropéptidos. Acción periférica sin efecto central opioide",
  ["Tos seca no productiva","Tos irritativa","Tos nocturna"],
  ["oral"],{"adulto":"60 mg c/8h","pediatrico":">2 años: 1 mg/kg c/8h"},
  ["Comp 60 mg","Jarabe 30 mg/5 mL","Gotas 60 mg/mL"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos periféricos",emb="B",
  ci=["Hipersensibilidad","Tos productiva","Embarazo primer trimestre"],
  ea=["Somnolencia leve","Náuseas","Diarrea","Palpitaciones (raro)"],
  ix=["Depresores SNC: interacción mínima (acción periférica)"],
  ce=["Acción periférica: sin depresión respiratoria","No genera dependencia","Menor somnolencia que antitusígenos centrales","Alternativa segura a codeína"]),

M("","butamirato_det","Butamirato (detalle)","Citrato de butamirato",
  ["Sinecod","Codeisan sin codeína"],"Antitusígeno central no opioide",
  "Antitusígeno de acción central que actúa sobre centro de la tos sin afinidad por receptores opioides. Propiedades broncodilatadoras y antiinflamatorias leves",
  ["Tos seca no productiva","Tos irritativa","Tos pre y postoperatoria"],
  ["oral"],{"adulto":"Comp LP: 50 mg c/8-12h. Jarabe: 15 mL c/6h","pediatrico":"2-6 años: 5 mL jarabe c/8h. 6-12 años: 10 mL c/8h"},
  ["Comp LP 50 mg","Jarabe 7.5 mg/5 mL","Gotas 5 mg/mL"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos centrales no opioides",emb="C",
  ci=["Hipersensibilidad","Tos productiva"],
  ea=["Somnolencia leve","Náuseas","Mareo","Diarrea","Exantema (raro)"],
  ix=["Expectorantes: no combinar","Depresores SNC: posible sedación aditiva leve"],
  ce=["No genera dependencia (no opioide)","Efecto broncodilatador complementario","No triturar comprimidos LP","Puede usarse en preoperatorio para suprimir tos"]),

M("","cloperastina_det","Cloperastina (detalle)","Clorhidrato de cloperastina",
  ["Sekisan","Flutox"],"Antitusígeno central y periférico con acción antihistamínica",
  "Doble mecanismo: acción central sobre centro de la tos y periférica con propiedades antihistamínicas H1. Efecto broncodilatador leve",
  ["Tos seca","Tos alérgica","Tos irritativa nocturna"],
  ["oral"],{"adulto":"10-20 mg c/8h","pediatrico":"2-6 años: 5 mg c/8h. 6-12 años: 10 mg c/8h"},
  ["Comp 10 mg","Jarabe 3.54 mg/mL","Suspensión 17.7 mg/5 mL"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos centrales",emb="C",
  ci=["Hipersensibilidad","Tos productiva","Embarazo primer trimestre"],
  ea=["Somnolencia","Sequedad bucal","Molestias GI","Mareo"],
  ix=["Depresores SNC: sedación aditiva","Anticolinérgicos: efectos aditivos","Alcohol: mayor sedación"],
  ce=["Componente antihistamínico: útil en tos alérgica","Causa somnolencia: precaución al conducir","No combinar con otros antitusígenos","Uso frecuente en España y Latinoamérica"]),
]

NEW_CHAPTERS = {
    "c03_10": {"id":"c03_10","nombre":"Antivirales Generales","unidadId":"u03","drugIds":[]},
    "c04_08": {"id":"c04_08","nombre":"Antifibróticos Pulmonares","unidadId":"u04","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U03+U04 supplement ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        uid = "u03" if ch["id"].startswith("c03") else "u04"
        add_chapter(cats, uid, ch)
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
