#!/usr/bin/env python3
"""Add ~60 new drugs for U12 Fármacos Hospitalarios (parte A)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c12_01 Anestésicos Generales (+10) ──
M("anestesico_general","midazolam_anestesia","Midazolam (anestesia)","Midazolam",["Dormicum (anestesia)"],"Benzodiazepina de coinducción anestésica",
  "BZD hidrosoluble de acción corta. Reduce dosis de inductor, amnesia anterógrada. Coinducción con propofol",
  ["Coinducción anestésica","Premedicación","Sedación consciente para procedimientos"],["IV","IM","oral"],
  {"adulto":"Coinducción: 0.01-0.05 mg/kg IV. Premedicación: 0.07-0.1 mg/kg IM. Sedación: 0.5-2 mg IV titulando"},
  ["Amp 5 mg/mL x 3, 10 mL","Amp 1 mg/mL x 5 mL"],"Compatible con precaución","u12","c12_01",
  pp={"dilucion":"Puede administrar sin diluir o diluir en SF","velocidadAdministracion":"IV lento: 0.5-1 mg cada 2 min titulando","estabilidad":"24h diluido a TA"}),

M("anestesico_general","fentanilo_anestesia","Fentanilo (anestesia)","Fentanilo",["Fentanest"],"Opioide intraoperatorio potente",
  "Opioide sintético 100x más potente que morfina. Inicio rápido IV (30 seg), duración 30-60 min. Estabilidad hemodinámica",
  ["Analgesia intraoperatoria","Complemento de anestesia general","Analgesia post-quirúrgica precoz"],["IV"],
  {"adulto":"Inducción: 1-2 mcg/kg. Mantenimiento: 1-2 mcg/kg/h. Dosis altas (cardiaca): 5-15 mcg/kg"},
  ["Amp 50 mcg/mL x 2, 10 mL"],"Compatible con precaución","u12","c12_01",
  pp={"velocidadAdministracion":"Bolo IV lento en 1-2 min. O infusión continua","estabilidad":"24h diluido en SF o SG5%"}),

M("anestesico_general","sufentanilo","Sufentanilo","Sufentanilo",["Sufenta"],"Opioide 5-10x más potente que fentanilo",
  "Opioide sintético derivado de fentanilo. 5-10x más potente. Alta estabilidad cardiovascular. Ideal para cirugía cardíaca",
  ["Anestesia cardiotorácica","Analgesia epidural","Anestesia balanceada"],["IV","epidural"],
  {"adulto":"IV: 0.5-1 mcg/kg bolo. Cardíaca: 15-30 mcg/kg total. Epidural: 10-25 mcg"},
  ["Amp 5 mcg/mL x 5 mL","Amp 50 mcg/mL x 1 mL"],"Evitar durante lactancia","u12","c12_01",
  pp={"velocidadAdministracion":"IV lento. Epidural según protocolo","estabilidad":"Proteger de la luz"}),

M("anestesico_general","alfentanilo","Alfentanilo","Alfentanilo",["Rapifen"],"Opioide de acción ultracorta",
  "Derivado de fentanilo con inicio ultrarrápido (60 seg) y duración 10-15 min. Ideal para procedimientos breves",
  ["Procedimientos cortos ambulatorios","Intubación sin relajante","Suplemento analgésico intraoperatorio"],["IV"],
  {"adulto":"Inducción: 10-50 mcg/kg. Mantenimiento: 0.5-3 mcg/kg/min"},
  ["Amp 500 mcg/mL x 2, 10 mL"],"Compatible con precaución","u12","c12_01",
  pp={"dilucion":"Puede diluir en SF o SG5%","velocidadAdministracion":"Bolo IV o infusión continua","estabilidad":"24h diluido"}),

M("anestesico_general","oxido_nitroso","Óxido nitroso","Óxido nitroso (N2O)",["N2O"],"Gas anestésico inhalado",
  "Gas anestésico de baja potencia (MAC 104%). Efecto analgésico, ansiolítico y amnésico. Siempre combinado con otros agentes",
  ["Co-analgesia inhalatoria","Procedimientos menores (mezcla 50/50 con O2)","Sedación en trabajo de parto (Entonox)"],["inhalatoria"],
  {"adulto":"50-70% en mezcla con O2. Entonox: 50/50 N2O/O2 auto-administrado"},
  ["Gas medicinal en cilindros","Mezcla Entonox 50/50"],"Compatible (uso puntual)","u12","c12_01",
  ci=["Neumotórax","Obstrucción intestinal","Embolia aérea","Cirugía de oído medio","Déficit B12 (uso prolongado)"],
  ea=["Náuseas","Vómitos","Expansión de cavidades cerradas","Deficiencia B12 (exposición crónica)","Euforia"],
  ix=["Potencia otros anestésicos: reduce MAC","Metotrexato: toxicidad con exposición prolongada"],
  ce=["SIEMPRE con ≥30% O2","No usar si neumotórax (expande)","Monitorizar SatO2","Ventilación adecuada del área (exposición ocupacional)","Difusión rápida al suspender: administrar O2 100% 5 min post"]),

M("anestesico_general","isoflurano","Isoflurano","Isoflurano",["Forane"],"Anestésico inhalatorio halogenado",
  "Éter halogenado de 2ª generación. MAC 1.15%. Buena relajación muscular. Produce vasodilatación coronaria",
  ["Mantenimiento de anestesia general","Neuroprotección (disminuye metabolismo cerebral)"],["inhalatoria"],
  {"adulto":"Inducción: 1.5-3% en O2/aire. Mantenimiento: 0.5-1.5%. MAC: 1.15%"},
  ["Líquido para vaporización, frasco 100, 250 mL"],"Evitar durante lactancia","u12","c12_01",
  ci=["Hipersensibilidad a halogenados","Hipertermia maligna susceptible","Hepatitis previa por halogenados"],
  ea=["Hipotensión","Depresión respiratoria","Hipertermia maligna","Hepatotoxicidad (raro)","NVPO","Agitación en despertar"],
  ix=["Relajantes musculares: potencia efecto","Opioides: potencia depresión respiratoria","Simpaticomiméticos: arritmias"],
  ce=["Vaporizador calibrado específico","Monitorizar agente en gas espirado (FE)","Dantroleno disponible","Olor pungente: no ideal para inducción inhalatoria"]),

M("anestesico_general","halotano","Halotano","Halotano",["Fluothane"],"Anestésico inhalatorio (uso limitado)",
  "Primer halogenado moderno. MAC 0.75%. No irritante de vía aérea: útil en inducción pediátrica. Hoy reemplazado por sevoflurano",
  ["Inducción inhalatoria pediátrica (donde sevoflurano no disponible)","Anestesia en países con recursos limitados"],["inhalatoria"],
  {"adulto":"Inducción: 2-4%. Mantenimiento: 0.5-2%. MAC: 0.75%"},
  ["Líquido para vaporización, frasco 250 mL"],"Evitar durante lactancia","u12","c12_01",
  ci=["Hepatitis por halotano previa","Hipertermia maligna","Feocromocitoma","Uso de adrenalina (arritmias)"],
  ea=["Hepatitis por halotano (1:35,000 adultos)","Bradicardia","Arritmias","Hipotensión","Hipertermia maligna","Sensibiliza miocardio a catecolaminas"],
  ix=["Adrenalina: arritmias ventriculares (límite <2 mcg/kg)","Relajantes: potencia","Aminofilina: arritmias"],
  ce=["Hepatitis grave: no repetir exposición en <3 meses","Sensibiliza miocardio a catecolaminas (limitar adrenalina)","En desuso en países desarrollados (sevoflurano es alternativa)","Económico: sigue usándose en países de bajos recursos"]),

M("anestesico_general","pancuronio","Pancuronio","Pancuronio",["Pavulon"],"Bloqueante neuromuscular de larga duración",
  "BNMA aminoesteroideo no despolarizante de larga acción (60-90 min). Efecto vagolítico: causa taquicardia",
  ["Relajación muscular en cirugía prolongada","Ventilación mecánica en UCI (uso restringido)"],["IV"],
  {"adulto":"Intubación: 0.08-0.1 mg/kg. Mantenimiento: 0.01-0.02 mg/kg"},
  ["Amp 2 mg/mL x 5 mL"],"Compatible con precaución","u12","c12_01",
  ea=["Taquicardia","HTA","Bloqueo prolongado (renal)","Broncoespasmo (raro)"],
  ix=["Aminoglucósidos: prolongan bloqueo","Inhibidores colinesterasa: revierten bloqueo","Sevoflurano: potencia bloqueo"],
  ce=["Monitorizador TOF obligatorio","Efecto vagolítico: causa taquicardia (diferencia de otros BNMA)","Eliminación renal: prolongado en IR","Sugammadex NO revierte (solo para rocuronio/vecuronio): usar neostigmina"],
  emb="C",
  pp={"velocidadAdministracion":"Bolo IV","estabilidad":"Refrigerado"}),

M("anestesico_general","atracurio","Atracurio","Atracurio",["Tracrium"],"BNMA con eliminación de Hofmann",
  "BNMA bencilisoquinolínico. Eliminación por degradación de Hofmann (independiente de hígado/riñón). Duración intermedia",
  ["Relajación muscular","Ideal en insuficiencia renal/hepática"],["IV"],
  {"adulto":"Intubación: 0.4-0.5 mg/kg. Mantenimiento: 0.08-0.1 mg/kg c/20-30 min o infusión 5-10 mcg/kg/min"},
  ["Amp 10 mg/mL x 2.5, 5 mL"],"Compatible con precaución","u12","c12_01",
  ea=["Liberación de histamina (rubor, hipotensión, broncoespasmo)","Taquicardia (si bolo rápido)"],
  ix=["Aminoglucósidos: prolongan bloqueo","Anestésicos inhalatorios: potencian","Anticonvulsivantes: pueden acortar bloqueo"],
  ce=["Inyección lenta para minimizar liberación de histamina","No requiere ajuste renal/hepático (ventaja principal)","Conservar REFRIGERADO (degrada a TA)","Cisatracurio (isómero R-cis) causa menos histamina"],
  emb="C",
  pp={"dilucion":"Puede diluir en SF o SG5% para infusión","velocidadAdministracion":"Bolo IV lento en >60 seg. Infusión: 5-10 mcg/kg/min","estabilidad":"REFRIGERAR 2-8°C. 24h a TA"}),

M("anestesico_general","mivacurio","Mivacurio","Mivacurio",["Mivacron"],"BNMA de acción corta",
  "BNMA bencilisoquinolínico de acción corta (15-20 min). Metabolizado por butirilcolinesterasa plasmática",
  ["Relajación muscular en procedimientos cortos","Intubación breve"],["IV"],
  {"adulto":"Intubación: 0.15-0.25 mg/kg IV. Mantenimiento: infusión 3-15 mcg/kg/min"},
  ["Amp 2 mg/mL x 5, 10 mL"],"Compatible con precaución","u12","c12_01",
  ea=["Liberación de histamina","Rubor facial","Hipotensión","Broncoespasmo","Bloqueo prolongado en déficit pseudocolinesterasa"],
  ix=["Aminoglucósidos: prolongan","Inhibidores pseudocolinesterasa: prolongan dramáticamente"],
  ce=["Bloqueo muy prolongado si déficit de pseudocolinesterasa","Inyectar lentamente (histamina)","Recuperación espontánea rápida (no necesita reversor)","Prácticamente en desuso (sugammadex permite rocuronio breve)"],
  emb="C",
  pp={"velocidadAdministracion":"IV lento en >30 seg. Infusión: 3-15 mcg/kg/min","estabilidad":"REFRIGERAR"}),

# ── c12_02 Otros Hospitalarios (+15) ──
M("","esmolol","Esmolol","Esmolol",["Brevibloc"],"Betabloqueante de acción ultracorta",
  "Beta-1 selectivo de acción ultracorta (t½ 9 min). Metabolizado por esterasas eritrocitarias. Fácil titulación",
  ["Taquicardia supraventricular perioperatoria","Control de FC en FA rápida","Respuesta a intubación","Emergencia hipertensiva"],["IV"],
  {"adulto":"Carga: 500 mcg/kg en 1 min. Infusión: 50-300 mcg/kg/min"},
  ["Vial 10 mg/mL x 10 mL","Vial 250 mL premezclado"],"Compatible con precaución","u12","c12_02",
  ci=["Bradicardia severa","Bloqueo AV 2-3°","Asma","Shock cardiogénico","IC descompensada"],
  ea=["Hipotensión","Bradicardia","Broncoespasmo","Flebitis","Náuseas","Mareo"],
  ix=["Calcioantagonistas no-DHP: bradicardia severa","Digoxina: bradicardia aditiva","Morfina: aumenta niveles de esmolol"],
  ce=["Efecto cesa en 10-20 min tras parar infusión","Ideal para titulación precisa","Administrar por vía central preferiblemente (flebitis)","Carga puede omitirse si hipotensión basal"],
  emb="C",
  pp={"dilucion":"Premezclado disponible. O diluir en SF/SG5%","velocidadAdministracion":"Carga 500 mcg/kg en 1 min, luego 50-300 mcg/kg/min","estabilidad":"24h a TA"}),

M("","nicardipino_infusion","Nicardipino infusión","Nicardipino",["Cardene IV"],"Calcioantagonista IV para control de PA",
  "Dihidropiridina IV. Vasodilatador arterial selectivo. Predecible y titulable. No efecto inotrópico negativo significativo",
  ["Emergencia hipertensiva","Control de PA perioperatorio","HTA post-quirúrgica"],["IV"],
  {"adulto":"Inicio: 5 mg/h. Titular 2.5 mg/h c/5-15 min. Máx 15 mg/h"},
  ["Amp 25 mg/10 mL"],"Evitar durante lactancia","u12","c12_02",
  ci=["Estenosis aórtica severa","Hipotensión"],
  ea=["Cefalea","Taquicardia","Hipotensión","Flebitis (periférica)","Náuseas"],
  ix=["Betabloqueantes: hipotensión aditiva","Ciclosporina: aumenta niveles"],
  ce=["Cambiar sitio IV periférico c/12h (flebitis)","Preferir vía central","Titular c/5-15 min hasta objetivo","Transición a oral cuando estable"],
  emb="C",
  pp={"dilucion":"25 mg en 250 mL SF = 0.1 mg/mL","velocidadAdministracion":"Infusión 5-15 mg/h","estabilidad":"24h a TA, proteger de la luz"}),

M("","fenoldopam","Fenoldopam","Fenoldopam",["Corlopam"],"Agonista D1 para emergencia hipertensiva",
  "Agonista selectivo del receptor D1 dopaminérgico. Vasodilatador renal y sistémico. Mejora perfusión renal",
  ["Emergencia hipertensiva (especialmente con compromiso renal)","HTA perioperatoria severa"],["IV"],
  {"adulto":"0.1-0.3 mcg/kg/min. Titular c/15 min. Máx 1.6 mcg/kg/min"},
  ["Amp 10 mg/mL"],"Datos insuficientes","u12","c12_02",
  ci=["Hipersensibilidad","Glaucoma o HTA intraocular"],
  ea=["Cefalea","Rubor","Náuseas","Hipotensión","Taquicardia refleja","Aumento de presión intraocular"],
  ix=["Betabloqueantes: efecto aditivo hipotensor"],
  ce=["Ventaja: mejora perfusión renal (vs nitroprusiato)","Titular gradualmente","No contiene cianuro (ventaja sobre nitroprusiato)","Monitorizar PA continuamente"],
  emb="B",
  pp={"dilucion":"40 mg en 1000 mL SF = 40 mcg/mL","velocidadAdministracion":"Infusión 0.1-1.6 mcg/kg/min","estabilidad":"24h a TA diluido"}),

M("","milrinona","Milrinona","Milrinona",["Primacor"],"Inhibidor de PDE3 inodilatador",
  "Inhibe PDE3 en miocardio y vasculatura. Inotrópico positivo + vasodilatador. Independiente de receptores beta",
  ["Insuficiencia cardíaca aguda descompensada","Síndrome de bajo gasto post-cirugía cardíaca","Shock cardiogénico"],["IV"],
  {"adulto":"Carga: 50 mcg/kg en 10 min (opcional). Infusión: 0.375-0.75 mcg/kg/min"},
  ["Amp 1 mg/mL x 10, 20 mL"],"Datos insuficientes","u12","c12_02",
  ci=["Estenosis aórtica/pulmonar severa","Hipotensión severa","Hipovolemia no corregida"],
  ea=["Hipotensión","Arritmias ventriculares","Cefalea","Trombocitopenia"],
  ix=["Furosemida: no mezclar (precipita)","Vasopresores: efecto complementario"],
  ce=["Puede omitir bolo si hipotensión basal","Plaquetas basales y cada 48h","No mezclar con furosemida","Eficaz en pacientes beta-bloqueados (mecanismo independiente)"],
  emb="C",
  pp={"dilucion":"20 mg en 80 mL SF = 200 mcg/mL","velocidadAdministracion":"Carga en 10 min, infusión 0.375-0.75 mcg/kg/min","estabilidad":"24h a TA diluido"}),

M("","levosimendan","Levosimendán","Levosimendán",["Simdax"],"Sensibilizador al calcio",
  "Sensibiliza troponina C al calcio (inotrópico) y abre canales K-ATP vasculares (vasodilatador). No aumenta consumo O2 miocárdico",
  ["Insuficiencia cardíaca aguda descompensada","Shock cardiogénico","Destete de inotrópicos"],["IV"],
  {"adulto":"Carga: 6-12 mcg/kg en 10 min (opcional). Infusión: 0.05-0.2 mcg/kg/min x24h"},
  ["Vial 2.5 mg/mL x 5 mL"],"Evitar durante lactancia","u12","c12_02",
  ci=["Hipotensión severa (TAS <85)","Taquicardia severa","Obstrucción mecánica al llenado/vaciado","IR severa"],
  ea=["Hipotensión","Cefalea","Taquicardia","Hipopotasemia","Arritmias","Náuseas"],
  ix=["Vasodilatadores: hipotensión aditiva","Inotrópicos: efecto aditivo"],
  ce=["Infusión de 24h (metabolito activo dura 7-9 días)","Monitorizar PA y FC continuamente","Omitir bolo si TAS <100","Efecto persiste una semana post-infusión","No repetir antes de 5 días"],
  emb="C",
  pp={"dilucion":"12.5 mg en 500 mL SG5% = 25 mcg/mL","velocidadAdministracion":"Carga opcional en 10 min. Infusión 24h","estabilidad":"24h diluido a TA"}),

M("","terlipresina","Terlipresina","Terlipresina",["Glypressin"],"Análogo de vasopresina para hemorragia variceal",
  "Profármaco de lisina-vasopresina. Vasoconstricción esplácnica selectiva. Reduce presión portal y flujo a varices",
  ["Hemorragia por varices esofágicas","Síndrome hepatorrenal tipo 1"],["IV"],
  {"adulto":"Varices: 1-2 mg IV c/4-6h x48h (después reducir). SHR: 0.5-1 mg c/4-6h + albúmina"},
  ["Amp 1 mg/5 mL"],"Datos insuficientes","u12","c12_02",
  ci=["Cardiopatía isquémica inestable","Arritmias","Arteriopatía periférica severa","Embarazo"],
  ea=["Bradicardia","Vasoconstricción periférica","Isquemia cardíaca/mesentérica","HTA","Dolor abdominal","Hiponatremia"],
  ix=["Propofol: bradicardia aditiva","Betabloqueantes: bradicardia"],
  ce=["ECG basal y monitorizar durante uso","Vigilar isquemia periférica (dedos, intestinal)","En SHR: junto con albúmina IV","Reducir dosis tras control hemorrágico"],
  emb="X",
  pp={"velocidadAdministracion":"Bolo IV lento en 1-2 minutos","estabilidad":"Refrigerado. Usar dentro de 24h tras abrir"}),

M("","octreotida_infusion","Octreótida infusión","Octreótida",["Sandostatin (infusión)"],"Análogo de somatostatina para hemorragia digestiva",
  "Inhibe hormonas GI y reduce flujo esplácnico. Disminuye presión portal y sangrado variceal",
  ["Hemorragia por varices esofágicas","Hemorragia digestiva alta no variceal","Fístula pancreática","Crisis carcinoide"],["IV"],
  {"adulto":"Varices: bolo 50 mcg, infusión 25-50 mcg/h x5 días. Carcinoide: 50-200 mcg c/8h SC"},
  ["Amp 50, 100, 500 mcg/mL"],"Compatible con precaución","u12","c12_02",
  ci=["Hipersensibilidad"],
  ea=["Diarrea/esteatorrea","Dolor abdominal","Hiperglucemia","Bradicardia","Colelitiasis (uso prolongado)"],
  ix=["Ciclosporina: reduce absorción","Insulina/antidiabéticos: ajustar dosis (altera glucemia)","Betabloqueantes: bradicardia aditiva"],
  ce=["En hemorragia variceal: junto con endoscopia terapéutica","Monitorizar glucemia","Ecografía vesicular si uso >2 semanas","Bolo IV seguido de infusión continua"],
  emb="B",
  pp={"dilucion":"250 mcg en 250 mL SF = 1 mcg/mL","velocidadAdministracion":"Bolo 50 mcg en 3 min, infusión 25-50 mcg/h","estabilidad":"24h diluido a TA"}),

M("","heparina_infusion","Heparina infusión continua","Heparina sódica",["Heparina sódica (infusión)"],"Anticoagulación IV en UCI",
  "Heparina no fraccionada en infusión continua. Monitorización con TTPa. Protamina como antídoto. Ideal cuando necesita reversión rápida",
  ["TEP agudo","SCA","Anticoagulación perioperatoria","Circulación extracorpórea"],["IV"],
  {"adulto":"Bolo: 80 UI/kg. Infusión: 18 UI/kg/h. Ajustar según TTPa c/6h (objetivo 1.5-2.5x control)"},
  ["Vial 5000 UI/mL x 5 mL","Vial 1000 UI/mL x 5, 10 mL"],"Compatible con precaución","u12","c12_02",
  ci=["Hemorragia activa","TIH","Coagulopatía severa no corregida"],
  ea=["Hemorragia","TIH","Osteoporosis (uso prolongado)","Hiperpotasemia"],
  ix=["Antiagregantes: mayor sangrado","AINEs: sangrado aditivo","Nitroglicerina IV: puede reducir efecto de heparina"],
  ce=["TTPa cada 6h hasta estable, luego c/12-24h","Plaquetas c/2 días (score TIH si caen >50%)","Protamina: 1 mg por cada 100 UI de heparina de la última hora","No administrar IM"],
  emb="C",
  pp={"dilucion":"25000 UI en 500 mL SF = 50 UI/mL","velocidadAdministracion":"Bolo + infusión continua con bomba","estabilidad":"24h diluido"}),

M("","insulina_infusion","Insulina infusión","Insulina regular humana",["Actrapid (infusión)"],"Control glucémico IV en UCI",
  "Insulina regular (cristalina) en infusión continua. Inicio IV en 15-30 min. Permite control glucémico preciso y predecible",
  ["Hiperglucemia en UCI","Cetoacidosis diabética","Estado hiperosmolar","Control perioperatorio"],["IV"],
  {"adulto":"CAD: 0.1-0.14 UI/kg/h tras bolo 0.1 UI/kg. UCI: 1-10 UI/h, titular según glucemia c/1-2h"},
  ["Vial 100 UI/mL x 10 mL"],"Compatible","u12","c12_02",
  ci=["Hipoglucemia"],
  ea=["Hipoglucemia","Hipopotasemia","Edema (dosis altas)"],
  ix=["Corticoides: antagonismo","Betabloqueantes: enmascaran hipoglucemia","Potasio: monitorizar"],
  ce=["Glucemia capilar c/1h durante infusión","Potasio ANTES de iniciar (no iniciar si K+ <3.3)","Transición a SC: administrar SC 1-2h ANTES de suspender infusión","Purgar línea (insulina se adsorbe al plástico)"],
  emb="B",
  pp={"dilucion":"50-100 UI en 50-100 mL SF (0.5-1 UI/mL)","velocidadAdministracion":"Infusión continua con bomba, titular según glucemia","estabilidad":"24h a TA. Purgar línea 20 mL para saturar adsorción"}),

M("","furosemida_infusion","Furosemida infusión","Furosemida",["Lasix (infusión)"],"Diurético de asa en infusión continua",
  "Infusión continua produce diuresis más uniforme con menos ototoxicidad que bolos. Mayor eficiencia diurética total",
  ["IC aguda descompensada refractaria a bolos","Sobrecarga de volumen en UCI","Edema pulmonar"],["IV"],
  {"adulto":"Carga: 40 mg IV. Infusión: 5-40 mg/h (máx 80-160 mg/h en refractariedad)"},
  ["Amp 20 mg/2 mL","Amp 40 mg/4 mL","Amp 250 mg/25 mL"],"Compatible con precaución","u12","c12_02",
  ci=["Anuria","Hipovolemia severa","Hipopotasemia severa","Encefalopatía hepática"],
  ea=["Hipopotasemia","Hiponatremia","Hipomagnesemia","Ototoxicidad (dosis altas)","Alcalosis metabólica","Hipotensión"],
  ix=["Aminoglucósidos: ototoxicidad y nefrotoxicidad aditivas","Digoxina: hipopotasemia aumenta toxicidad","AINEs: reducen efecto diurético","Litio: aumenta niveles"],
  ce=["Monitorizar electrolitos c/6-12h (K+, Na+, Mg2+)","Balance hídrico estricto","Menor ototoxicidad que bolos a igual dosis total","En anasarca: puede requerir combinación con tiazida"],
  emb="C",
  pp={"dilucion":"500 mg en 500 mL SF = 1 mg/mL (proteger de luz si >24h)","velocidadAdministracion":"Infusión 5-40 mg/h con bomba","estabilidad":"24h a TA, proteger de la luz"}),

M("vasopressor","vasopresina_infusion","Vasopresina infusión","Vasopresina",["Pitressin (infusión)"],"Vasopresor no adrenérgico para shock",
  "Hormona antidiurética exógena. Vasoconstricción vía receptores V1 vasculares. Complemento a noradrenalina en shock séptico",
  ["Shock séptico (coadyuvante con noradrenalina)","Shock vasodilatorio","Diabetes insípida central"],["IV"],
  {"adulto":"Shock: 0.03-0.04 UI/min (dosis fija, no titular). DI: 0.5-4 mUI/kg/h"},
  ["Amp 20 UI/mL"],"Datos insuficientes","u12","c12_02",
  pp={"dilucion":"40 UI en 100 mL SF = 0.4 UI/mL","velocidadAdministracion":"Infusión 0.03-0.04 UI/min (dosis fija)","estabilidad":"24h a TA diluido"}),

M("","hidralazina_iv","Hidralazina IV","Hidralazina",["Apresolina IV"],"Vasodilatador arteriolar directo IV",
  "Vasodilatador arteriolar directo. Reduce resistencia vascular periférica. Taquicardia refleja. Seguro en embarazo",
  ["Emergencia hipertensiva en eclampsia/preeclampsia","HTA severa perioperatoria"],["IV","IM"],
  {"adulto":"5-10 mg IV c/20-30 min. Máx 20 mg (o 0.5-10 mg/h infusión)"},
  ["Amp 20 mg/mL"],"Compatible con precaución","u12","c12_02",
  ci=["Aneurisma disecante de aorta","Cardiopatía isquémica","Lupus inducido (relativa)"],
  ea=["Taquicardia refleja","Cefalea","Rubor facial","Palpitaciones","Retención hídrica","Lupus-like (uso prolongado)"],
  ix=["Betabloqueantes: atenúan taquicardia refleja (combinación útil)","Diazóxido: hipotensión severa"],
  ce=["PA cada 5 min tras cada dosis","Segura en embarazo (1ª línea con labetalol)","Efecto en 10-20 min IV, 30 min IM","Combinar con betabloqueante si taquicardia"],
  emb="C",
  pp={"velocidadAdministracion":"IV lento en 1-2 min. O infusión","estabilidad":"Proteger de la luz, usar inmediatamente"}),

M("","amiodarona_infusion","Amiodarona infusión","Amiodarona",["Cordarone (infusión UCI)"],"Antiarrítmico de amplio espectro en UCI",
  "Antiarrítmico clase III con propiedades de 4 clases. En UCI para arritmias supraventriculares y ventriculares",
  ["FA de reciente inicio","Flutter auricular","TV recurrente","Prevención de arritmias post-cirugía cardíaca"],["IV"],
  {"adulto":"Carga: 150 mg en 10 min. Luego 1 mg/min x6h, después 0.5 mg/min x18h (total ~900 mg/24h)"},
  ["Amp 150 mg/3 mL"],"Evitar durante lactancia","u12","c12_02",
  ci=["Bradicardia sinusal severa","Bloqueo AV sin marcapasos","Alergia al yodo","Shock cardiogénico","Disfunción tiroidea severa"],
  ea=["Hipotensión","Bradicardia","Flebitis severa en vena periférica","Prolongación QT"],
  ix=["Digoxina: aumenta 70-100% (reducir dosis a mitad)","Warfarina: INR sube","Simvastatina: miopatía (máx 20 mg)","QT-prolongers: riesgo torsades"],
  ce=["SOLO SG5% (precipita en SF a >2 mg/mL)","Vía central obligatoria si >24h","Concentración >2 mg/mL requiere vía central","Monitorizar ECG continuo, TA, función tiroidea"],
  emb="D",
  pp={"dilucion":"900 mg en 500 mL SG5% = 1.8 mg/mL","velocidadAdministracion":"150 mg en 10 min, luego 1 mg/min x6h, 0.5 mg/min x18h","estabilidad":"24h en SG5%. NO usar SF a concentración >2 mg/mL"}),

# ── c12_03 Sedación en UCI (+8) ──
M("","propofol_infusion","Propofol infusión UCI","Propofol",["Diprivan (UCI)"],"Sedación IV en UCI",
  "Emulsión lipídica con efecto sedante/hipnótico. Inicio rápido, despertar predecible. Riesgo de síndrome de infusión de propofol",
  ["Sedación en ventilación mecánica","Sedación para procedimientos en UCI"],["IV"],
  {"adulto":"UCI: 0.3-4 mg/kg/h. Procedimiento: 0.5-1 mg/kg bolo, luego titular"},
  ["Vial 10 mg/mL x 20, 50, 100 mL"],"Evitar durante lactancia","u12","c12_03",
  ci=["Alergia a soja/huevo/lecitina","<3 años (sedación UCI)","Hipersensibilidad"],
  ea=["Hipotensión","Bradicardia","Depresión respiratoria","Hipertrigliceridemia","Síndrome de infusión de propofol (>48h, >4 mg/kg/h)","Dolor en inyección"],
  ix=["Opioides: potencian hipotensión","Benzodiazepinas: reducen dosis necesaria"],
  ce=["PRIS (Propofol Related Infusion Syndrome): acidosis, rabdomiólisis, hiperK+, IC → mortal","Máx 4 mg/kg/h y máx 48h a dosis altas","Triglicéridos c/48h","Técnica aséptica estricta (medio de cultivo)","Cambiar línea y vial c/12h"],
  emb="B",
  pp={"velocidadAdministracion":"Infusión 0.3-4 mg/kg/h. NO requiere dilución","estabilidad":"12h tras abrir (riesgo contaminación)"}),

M("","midazolam_infusion","Midazolam infusión UCI","Midazolam",["Dormicum (UCI)"],"Sedación benzodiazepínica en UCI",
  "BZD hidrosoluble en infusión continua para sedación prolongada. Metabolito activo se acumula en IR y uso prolongado",
  ["Sedación en ventilación mecánica (cuando propofol contraindicado)","Status epiléptico refractario"],["IV"],
  {"adulto":"0.02-0.1 mg/kg/h (1-7 mg/h). Titular según escala RASS"},
  ["Amp 5 mg/mL x 3, 10 mL"],"Compatible con precaución","u12","c12_03",
  ci=["Miastenia gravis","Hipersensibilidad a BZD","Insuficiencia respiratoria sin VM"],
  ea=["Sedación excesiva","Acumulación en IR/obesos","Tolerancia rápida","Abstinencia al suspender","Depresión respiratoria"],
  ix=["Opioides: sedación y depresión respiratoria","Inhibidores CYP3A4: aumentan niveles","Rifampicina: reduce niveles"],
  ce=["Escala RASS c/4h","Despertar diario obligatorio (vacaciones de sedación)","Acumulación: despertar prolongado en uso >48h","Flumazenilo disponible","Retirada gradual si >5 días"],
  emb="D",
  pp={"dilucion":"50 mg en 50 mL SF = 1 mg/mL","velocidadAdministracion":"Infusión 0.02-0.1 mg/kg/h","estabilidad":"24h diluido a TA"}),

M("","dexmedetomidina_infusion","Dexmedetomidina infusión","Dexmedetomidina",["Precedex (UCI)"],"Sedación cooperativa alfa-2",
  "Agonista alfa-2 selectivo. Sedación con paciente despertable a estímulos. No depresión respiratoria significativa",
  ["Sedación en UCI (especialmente destete de VM)","Delirium en UCI","Sedación para procedimientos (despierto)"],["IV"],
  {"adulto":"Carga: 1 mcg/kg en 10 min (opcional). Infusión: 0.2-1.5 mcg/kg/h"},
  ["Vial 100 mcg/mL x 2 mL","Vial 200 mcg/2 mL"],"Datos insuficientes","u12","c12_03",
  ci=["Bloqueo AV avanzado sin marcapasos","Bradicardia severa","Hipotensión severa"],
  ea=["Bradicardia","Hipotensión","Boca seca","Hipertensión transitoria (carga rápida)","Náuseas"],
  ix=["Betabloqueantes: bradicardia aditiva","Opioides: sedación aditiva","Anestésicos: reduce requerimiento"],
  ce=["Ventaja: paciente despertable (sedación cooperativa)","No depresión respiratoria significativa","Reduce delirium vs midazolam/propofol","Bradicardia: omitir bolo si FC <60","Máx 24h (aprobado), pero uso off-label más prolongado"],
  emb="C",
  pp={"dilucion":"400 mcg en 100 mL SF = 4 mcg/mL","velocidadAdministracion":"Carga en 10 min (opcional). Infusión 0.2-1.5 mcg/kg/h","estabilidad":"24h diluido a TA"}),

M("","ketamina_sedacion","Ketamina sedación","Ketamina",["Ketalar (sedación)"],"Anestésico disociativo para sedación",
  "Antagonista NMDA. Produce sedación disociativa con analgesia. Preserva reflejos de vía aérea y drive respiratorio",
  ["Sedación para procedimientos dolorosos breves","Analgesia en UCI (dosis bajas)","Depresión refractaria (dosis subanestésica)"],["IV","IM"],
  {"adulto":"Procedimiento: 1-2 mg/kg IV o 4-5 mg/kg IM. Analgesia UCI: 0.1-0.3 mg/kg/h. Subdisociativa: 0.5 mg/kg en 40 min"},
  ["Vial 50 mg/mL x 10 mL","Vial 10 mg/mL x 20 mL"],"Evitar durante lactancia","u12","c12_03",
  ci=["HTA severa no controlada","Eclampsia","IC severa","Psicosis activa","Presión intracraneal elevada (relativa)"],
  ea=["Emergencia delirante (alucinaciones)","HTA","Taquicardia","Nistagmo","Hipersalivación","Náuseas","Laringoespasmo (raro)"],
  ix=["Depresores SNC: sedación aditiva","Teofilina: convulsiones"],
  ce=["Premedicación con midazolam reduce emergencia delirante","Aspiración mínima riesgo (preserva reflejos)","Monitorización de SpO2, PA, FC","Ketamina subdisociativa: analgesia sin sedación completa"],
  emb="C",
  pp={"dilucion":"Puede diluir en SF o SG5%","velocidadAdministracion":"IV lento en 60 seg para sedación. Infusión para analgesia","estabilidad":"24h diluido a TA"}),

M("","fentanilo_infusion","Fentanilo infusión UCI","Fentanilo",["Fentanilo (UCI)"],"Analgesia opioide IV en UCI",
  "Opioide sintético en infusión para analgesia en paciente ventilado. Mejor estabilidad hemodinámica que morfina",
  ["Analgesia en ventilación mecánica","Analgesia post-quirúrgica","Analgesia procedural en UCI"],["IV"],
  {"adulto":"25-200 mcg/h (0.5-3 mcg/kg/h). Bolos rescate: 25-50 mcg"},
  ["Amp 50 mcg/mL x 2, 10 mL"],"Compatible con precaución","u12","c12_03",
  ci=["Depresión respiratoria sin VM","Íleo paralítico","Hipersensibilidad"],
  ea=["Depresión respiratoria","Bradicardia","Rigidez torácica (bolo rápido)","Estreñimiento","Náuseas","Tolerancia"],
  ix=["BZD: sedación/depresión respiratoria aditiva","IMAO: crisis serotoninérgica","Inhibidores CYP3A4: aumentan niveles"],
  ce=["Escala de dolor c/4h (BPS en paciente no comunicativo)","Rigidez torácica: administrar lento","Tolerancia desde 48-72h","Retirada gradual si >5 días (abstinencia)"],
  emb="C",
  pp={"dilucion":"2500 mcg en 50 mL SF = 50 mcg/mL","velocidadAdministracion":"Infusión 25-200 mcg/h","estabilidad":"24h a TA"}),

M("","morfina_infusion","Morfina infusión UCI","Morfina",["Morfina (UCI)"],"Analgesia opioide clásica en UCI",
  "Opioide natural. Libera histamina. Causa más hipotensión que fentanilo. Metabolito activo M6G se acumula en IR",
  ["Analgesia en UCI","Edema agudo de pulmón (reduce precarga)","Dolor severo post-quirúrgico"],["IV"],
  {"adulto":"Infusión: 1-5 mg/h. Bolos: 2-4 mg c/2-4h PRN","ajusteRenal":"M6G se acumula: usar fentanilo en IR"},
  ["Amp 10 mg/mL","Amp 15 mg/mL"],"Compatible con precaución","u12","c12_03",
  ci=["Depresión respiratoria sin VM","Asma aguda","Íleo","Hipersensibilidad"],
  ea=["Depresión respiratoria","Hipotensión (liberación histamina)","Bradicardia","Náuseas","Prurito","Retención urinaria","Estreñimiento"],
  ix=["BZD: depresión respiratoria","IMAO: crisis","Esmolol: aumenta niveles de morfina"],
  ce=["Preferir fentanilo en hemodinámicamente inestables","Evitar en IR (acumulación M6G)","Útil en EAP (reduce precarga)","Naloxona disponible","Escala de dolor regular"],
  emb="C",
  pp={"dilucion":"50 mg en 50 mL SF = 1 mg/mL","velocidadAdministracion":"Infusión 1-5 mg/h. Bolos IV lentos en 2-3 min","estabilidad":"24h a TA"}),

M("","clonidina_sedacion","Clonidina sedación","Clonidina",["Catapres (UCI)"],"Sedación coadyuvante alfa-2 agonista",
  "Agonista alfa-2 central. Efecto sedante, analgésico y simpaticolítico. Reduce requerimiento de opioides y BZD en UCI",
  ["Sedación coadyuvante en UCI","Abstinencia a opioides/alcohol en UCI","Shivering post-operatorio"],["IV","oral"],
  {"adulto":"IV: 0.5-2 mcg/kg/h (infusión). Oral: 0.1-0.3 mg c/8h"},
  ["Amp 150 mcg/mL","Comp 0.1, 0.15, 0.3 mg"],"Evitar durante lactancia","u12","c12_03",
  ci=["Bradicardia severa","Bloqueo AV","Hipotensión severa"],
  ea=["Bradicardia","Hipotensión","Sedación","Boca seca","Rebote hipertensivo si suspensión brusca"],
  ix=["Betabloqueantes: bradicardia aditiva","Depresores SNC: sedación aditiva"],
  ce=["No suspender bruscamente","Reduce dosis de opioides 20-40%","Útil en shivering y abstinencia","Monitorizar PA y FC"],
  emb="C",
  pp={"dilucion":"300 mcg en 50 mL SF = 6 mcg/mL","velocidadAdministracion":"Infusión 0.5-2 mcg/kg/h","estabilidad":"24h diluido a TA"}),

M("","remifentanilo_infusion","Remifentanilo infusión","Remifentanilo",["Ultiva (UCI)"],"Opioide de acción ultracorta en infusión",
  "Opioide mu-agonista metabolizado por esterasas plasmáticas. t½ contexto-sensitivo de 3-4 min independiente de duración de infusión",
  ["Analgesia intraoperatoria","Sedación procedural en UCI (breve)","Despertar rápido necesario"],["IV"],
  {"adulto":"Analgesia: 0.05-0.2 mcg/kg/min. Anestesia: 0.1-0.5 mcg/kg/min"},
  ["Vial 1, 2, 5 mg polvo"],"Evitar durante lactancia","u12","c12_03",
  ci=["Uso epidural/intratecal (contiene glicina)","Hipersensibilidad"],
  ea=["Rigidez muscular (bolo rápido)","Bradicardia","Hipotensión","Depresión respiratoria","Náuseas","Hiperalgesia post-infusión"],
  ix=["BZD: potenciación","IMAO: contraindicado"],
  ce=["Cesar efecto en 5-10 min post-infusión (administrar analgesia antes de parar)","No dar en bolo rápido (rigidez)","Hiperalgesia: planificar transición analgésica","No acumulación: ideal para despertar rápido"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con SF, SG5% o agua estéril","dilucion":"Diluir hasta 20-250 mcg/mL","velocidadAdministracion":"Infusión 0.05-0.5 mcg/kg/min","estabilidad":"24h a TA diluido"}),
]

NEW_CHAPTERS = {}

if __name__ == "__main__":
    print("=== U12a ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
