#!/usr/bin/env python3
"""Add new drugs for U03 Antiinfecciosos (part B)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ══════════════════════════════════════════════════════════════════
# c03_08 — Antivirales Hepatitis y Otros (~10)
# ══════════════════════════════════════════════════════════════════

M("antirretroviral","entecavir","Entecavir","Entecavir",["Baraclude"],
  "Análogo nucleósido antiviral (hepatitis B)",
  "Análogo de guanosina que inhibe la ADN polimerasa del VHB en sus tres funciones: cebado, transcripción inversa y síntesis de ADN de cadena positiva",
  ["Hepatitis B crónica con replicación viral activa","Hepatitis B con cirrosis compensada o descompensada","Hepatitis B con coinfección VIH (con TAR completo)"],
  ["oral"],
  {"adulto":"0.5 mg/día en ayunas (naïve). 1 mg/día si resistencia a lamivudina","ajusteRenal":"ClCr 30-49: 0.25 mg/día. ClCr 10-29: 0.15 mg/día","pediatrico":">2 años y >10 kg: 0.015 mg/kg/día (máx 0.5 mg)"},
  ["Comp 0.5, 1 mg","Sol oral 0.05 mg/mL"],"No recomendado","u03","c03_08",
  familia="Antivirales hepatitis B",emb="C",
  ci=["Hipersensibilidad a entecavir","Coinfección VIH sin TAR completo (riesgo de resistencia VIH)"],
  ea=["Cefalea","Fatiga","Mareo","Náuseas","Acidosis láctica (raro)","Exacerbación hepatitis al suspender","Elevación transaminasas"],
  ix=["Fármacos nefrotóxicos: vigilar función renal","No interacciones significativas por CYP450"],
  ce=["Tomar en ayunas (2h antes o después de alimentos)","No suspender bruscamente: riesgo de rebrote hepatitis","Monitorizar ADN-VHB y transaminasas c/3 meses","En coinfección VIH: solo con TAR activo para evitar resistencia","Función renal basal y periódica"],
  fk={"absorcion":"Oral, reducida por alimentos","metabolismo":"Mínimo, eliminación renal","vidaMedia":"128-149 horas (intracelular)","eliminacion":"Renal (filtración glomerular y secreción tubular)"},
  alm="Temperatura ambiente. Solución oral: usar dentro de la fecha de caducidad una vez abierta."),

M("antirretroviral","adefovir","Adefovir dipivoxilo","Adefovir dipivoxilo",["Hepsera"],
  "Análogo nucleótido antiviral (hepatitis B)",
  "Profármaco del adefovir, análogo acíclico de adenosina monofosfato. Inhibe la ADN polimerasa del VHB tras doble fosforilación intracelular",
  ["Hepatitis B crónica con replicación activa","Hepatitis B resistente a lamivudina"],
  ["oral"],
  {"adulto":"10 mg/día","ajusteRenal":"ClCr 20-49: 10 mg c/48h. ClCr 10-19: 10 mg c/72h. Hemodiálisis: 10 mg c/7 días post-diálisis"},
  ["Comp 10 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales hepatitis B",emb="C",
  ci=["Hipersensibilidad","Insuficiencia renal grave no ajustada"],
  ea=["Nefrotoxicidad (tubulopatía proximal)","Elevación de creatinina","Astenia","Cefalea","Dolor abdominal","Exacerbación hepatitis al suspender","Acidosis láctica (raro)"],
  ix=["Fármacos nefrotóxicos (aminoglucósidos, AINEs, ciclosporina): mayor riesgo nefrotoxicidad","Ibuprofen: aumenta exposición a adefovir"],
  ce=["Creatinina y fósforo sérico antes de iniciar y c/3 meses","Nefrotoxicidad dosis-dependiente: no exceder 10 mg/día","No suspender bruscamente (rebrote hepatitis)","En gran parte reemplazado por entecavir y tenofovir"],
  alm="Temperatura ambiente."),

M("antirretroviral","telbivudina","Telbivudina","Telbivudina",["Tyzeka","Sebivo"],
  "Análogo nucleósido antiviral (hepatitis B)",
  "Análogo de timidina L-nucleósido. Inhibe la ADN polimerasa del VHB. Más potente que lamivudina pero con menor barrera genética que entecavir",
  ["Hepatitis B crónica con replicación activa y evidencia de enfermedad hepática"],
  ["oral"],
  {"adulto":"600 mg/día","ajusteRenal":"ClCr 30-49: 600 mg c/48h. ClCr <30: 600 mg c/72h"},
  ["Comp 600 mg","Sol oral 100 mg/mL"],"No recomendado","u03","c03_08",
  familia="Antivirales hepatitis B",emb="B",
  ci=["Hipersensibilidad","Uso con interferón pegilado (riesgo de neuropatía periférica severa)"],
  ea=["Elevación de CPK (miopatía)","Fatiga","Cefalea","Tos","Náuseas","Neuropatía periférica","Acidosis láctica (raro)"],
  ix=["Interferón pegilado alfa-2a: neuropatía periférica severa (CONTRAINDICADO combinar)","Fármacos que causan miopatía: riesgo aditivo"],
  ce=["Monitorizar CPK periódicamente (riesgo de miopatía/rabdomiólisis)","NUNCA combinar con interferón pegilado","Vigilar neuropatía periférica (hormigueo, debilidad)","Eficacia inferior a entecavir en muchos escenarios"],
  alm="Temperatura ambiente. Solución oral: refrigerar tras abrir."),

M("antirretroviral","ledipasvir_sofosbuvir","Ledipasvir/Sofosbuvir","Ledipasvir + Sofosbuvir",["Harvoni"],
  "Combinación antiviral acción directa (hepatitis C)",
  "Ledipasvir: inhibidor de NS5A del VHC. Sofosbuvir: inhibidor nucleotídico de NS5B (polimerasa). Combinación pangenotípica con alta tasa de curación",
  ["Hepatitis C crónica genotipo 1, 4, 5, 6","Hepatitis C con cirrosis compensada","Hepatitis C post-trasplante hepático"],
  ["oral"],
  {"adulto":"Ledipasvir 90 mg/sofosbuvir 400 mg: 1 comp/día. Duración: 8-24 sem según genotipo, cirrosis y tratamiento previo","pediatrico":">3 años: según peso, formulación pediátrica disponible"},
  ["Comp 90/400 mg","Comp pediátricos 45/200 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="B",
  ci=["Hipersensibilidad","Uso con inductores potentes de P-gp (rifampicina, carbamazepina, fenitoína)","Uso con amiodarona (bradicardia severa con sofosbuvir)"],
  ea=["Fatiga","Cefalea","Náuseas","Insomnio","Astenia","Diarrea"],
  ix=["Amiodarona: bradicardia sintomática severa (CONTRAINDICADO)","IBP: reducen absorción de ledipasvir (máx omeprazol 20 mg simultáneo)","Antiácidos: separar 4 horas","Rifampicina/carbamazepina: reducen niveles drásticamente","Rosuvastatina: aumenta niveles (riesgo miopatía)"],
  ce=["Revolución en tratamiento VHC: curación >95%","Verificar genotipo VHC antes de iniciar","Con amiodarona: monitorización cardíaca 48h (bradicardia fatal reportada)","Separar antiácidos 4h y limitar IBP","Verificar interacciones con TODA la medicación"],
  alm="Temperatura ambiente. Proteger de humedad."),

M("antirretroviral","glecaprevir_pibrentasvir","Glecaprevir/Pibrentasvir","Glecaprevir + Pibrentasvir",["Maviret","Mavyret"],
  "Combinación pangenotípica antiviral hepatitis C",
  "Glecaprevir: inhibidor de proteasa NS3/4A. Pibrentasvir: inhibidor de NS5A. Combinación pangenotípica (genotipos 1-6) con alta barrera genética",
  ["Hepatitis C crónica genotipos 1-6","Hepatitis C sin cirrosis (8 semanas)","Hepatitis C con cirrosis compensada","Hepatitis C con enfermedad renal crónica (incluyendo diálisis)"],
  ["oral"],
  {"adulto":"Glecaprevir 300 mg/pibrentasvir 120 mg (3 comp de 100/40) una vez al día con alimentos. Sin cirrosis naïve: 8 sem. Con cirrosis: 8-16 sem"},
  ["Comp 100/40 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="B",
  ci=["Cirrosis descompensada (Child-Pugh B o C)","Uso con atazanavir","Uso con rifampicina","Insuficiencia hepática grave"],
  ea=["Cefalea","Fatiga","Náuseas","Diarrea","Prurito"],
  ix=["Atazanavir: aumenta niveles de glecaprevir (CONTRAINDICADO)","Rifampicina: reduce niveles drásticamente","Ciclosporina >100 mg/día: aumenta niveles","Dabigatrán: aumenta niveles (precaución)","Estatinas: limitar dosis"],
  ce=["Pangenotípico: cubre genotipos 1-6 (simplifica tratamiento)","8 semanas en la mayoría de pacientes sin cirrosis","TOMAR CON ALIMENTOS (aumenta absorción 83-163%)","Seguro en enfermedad renal crónica y diálisis","Verificar Child-Pugh: contraindicado en descompensada"],
  alm="Temperatura ambiente. Proteger de humedad."),

M("antirretroviral","velpatasvir_sofosbuvir","Velpatasvir/Sofosbuvir","Velpatasvir + Sofosbuvir",["Epclusa"],
  "Combinación pangenotípica antiviral hepatitis C",
  "Velpatasvir: inhibidor de NS5A con actividad pangenotípica. Sofosbuvir: inhibidor nucleotídico de NS5B. Régimen de una pastilla al día para todos los genotipos",
  ["Hepatitis C crónica genotipos 1-6","Hepatitis C con cirrosis compensada","Hepatitis C con cirrosis descompensada (con ribavirina)"],
  ["oral"],
  {"adulto":"Velpatasvir 100 mg/sofosbuvir 400 mg: 1 comp/día x 12 semanas. Cirrosis descompensada: añadir ribavirina"},
  ["Comp 100/400 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="B",
  ci=["Uso con rifampicina u otros inductores potentes de P-gp/CYP","Uso con amiodarona","Hipersensibilidad"],
  ea=["Cefalea","Fatiga","Náuseas","Astenia","Insomnio"],
  ix=["Amiodarona: bradicardia severa (contraindicado con sofosbuvir)","Rifampicina: reduce niveles drásticamente","IBP: reducen absorción velpatasvir (omeprazol máx 20 mg en ayunas)","Efavirenz: reduce niveles de velpatasvir"],
  ce=["Un comprimido al día para TODOS los genotipos","Puede usarse en cirrosis descompensada (a diferencia de IP)","Limitar IBP: máx omeprazol 20 mg con alimentos separados","Tasa de curación >95% en la mayoría de poblaciones","Verificar interacciones con medicación concomitante"],
  alm="Temperatura ambiente."),

M("antirretroviral","elbasvir_grazoprevir","Elbasvir/Grazoprevir","Elbasvir + Grazoprevir",["Zepatier"],
  "Combinación antiviral acción directa (hepatitis C)",
  "Elbasvir: inhibidor de NS5A. Grazoprevir: inhibidor de proteasa NS3/4A. Combinación eficaz en genotipos 1 y 4, con excelente perfil en enfermedad renal",
  ["Hepatitis C crónica genotipo 1 y 4","Hepatitis C con enfermedad renal crónica (incluyendo diálisis)","Hepatitis C con cirrosis compensada"],
  ["oral"],
  {"adulto":"Elbasvir 50 mg/grazoprevir 100 mg: 1 comp/día x 12-16 semanas según genotipo y RVS previa"},
  ["Comp 50/100 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="B",
  ci=["Cirrosis descompensada (Child-Pugh B o C)","Insuficiencia hepática moderada-grave","Uso con inductores potentes de CYP3A (rifampicina, fenitoína)","Uso con inhibidores potentes de CYP3A (ketoconazol)"],
  ea=["Fatiga","Cefalea","Náuseas","Elevación transaminasas (grazoprevir)","Insomnio"],
  ix=["Rifampicina/fenitoína/carbamazepina: reducen niveles","Ketoconazol/ritonavir: aumentan niveles de grazoprevir","Ciclosporina: aumenta niveles 15x (contraindicado)","Estatinas: limitar atorvastatina a 20 mg"],
  ce=["Excelente opción en enfermedad renal crónica: no requiere ajuste","Monitorizar transaminasas: basal, sem 8 y 12","Test de resistencia NS5A en genotipo 1a (extender a 16 sem si polimorfismos)","No requiere ajuste en insuficiencia renal","Contraindicado si ALT/AST >10x LSN"],
  alm="Temperatura ambiente. Proteger de humedad."),

M("antirretroviral","daclatasvir","Daclatasvir","Daclatasvir",["Daklinza"],
  "Inhibidor de NS5A del VHC",
  "Inhibidor pangenotípico del complejo de replicación NS5A del VHC. Alta potencia antiviral. Se combina con sofosbuvir",
  ["Hepatitis C crónica (en combinación con sofosbuvir)","Hepatitis C genotipos 1-6","Hepatitis C con cirrosis compensada o descompensada"],
  ["oral"],
  {"adulto":"60 mg/día (con sofosbuvir 400 mg/día). Ajustar a 30 mg con inhibidores potentes CYP3A4 o a 90 mg con inductores moderados"},
  ["Comp 30, 60, 90 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="X",
  ci=["Hipersensibilidad","Uso con inductores potentes de CYP3A4 y P-gp"],
  ea=["Fatiga","Cefalea","Náuseas","Diarrea","Anemia (con ribavirina)"],
  ix=["Rifampicina/fenitoína: reducen niveles (contraindicado)","Atazanavir/r: reducir daclatasvir a 30 mg","Efavirenz: aumentar daclatasvir a 90 mg","Amiodarona + sofosbuvir: bradicardia severa"],
  ce=["Siempre en combinación con sofosbuvir (nunca en monoterapia)","Ajustar dosis según interacciones (30, 60 o 90 mg)","Importante en países con acceso limitado a combinaciones fijas","Verificar interacciones antes de iniciar"],
  alm="Temperatura ambiente. Proteger de la luz."),

M("antirretroviral","simeprevir","Simeprevir","Simeprevir",["Olysio"],
  "Inhibidor de proteasa NS3/4A del VHC",
  "Inhibidor macrocíclico de la serina proteasa NS3/4A del VHC. Activo principalmente contra genotipo 1. Se combina con sofosbuvir",
  ["Hepatitis C crónica genotipo 1 (en combinación)","Hepatitis C con cirrosis compensada (en combinación con sofosbuvir)"],
  ["oral"],
  {"adulto":"150 mg/día con alimentos (con sofosbuvir 400 mg/día) x 12 semanas"},
  ["Cáps 150 mg"],"No recomendado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="X",
  ci=["Cirrosis descompensada","Hipersensibilidad","Uso con inductores o inhibidores potentes de CYP3A4"],
  ea=["Fotosensibilidad (frecuente)","Rash","Prurito","Náuseas","Hiperbilirrubinemia","Disnea"],
  ix=["Rifampicina/carbamazepina: reducen niveles","Eritromicina/ketoconazol: aumentan niveles","Ciclosporina: aumenta niveles 6x","Uso con ritonavir: no recomendado"],
  ce=["Tomar con alimentos","Fotoprotección estricta (fotosensibilidad significativa)","Test Q80K en genotipo 1a (reduce eficacia si presente)","En gran parte reemplazado por regímenes más modernos","Monitorizar bilirrubina"],
  alm="Temperatura ambiente. Proteger de la luz."),

M("antirretroviral","boceprevir","Boceprevir","Boceprevir",["Victrelis"],
  "Inhibidor de proteasa NS3 del VHC (1ª generación)",
  "Inhibidor de la serina proteasa NS3 del VHC. Primer inhibidor de proteasa para VHC aprobado. Se usaba con interferón pegilado y ribavirina",
  ["Hepatitis C crónica genotipo 1 (uso histórico, en combinación con PEG-IFN/RBV)"],
  ["oral"],
  {"adulto":"800 mg c/8h con alimentos (siempre con PEG-IFN y ribavirina). Duración: 24-44 sem según respuesta"},
  ["Cáps 200 mg"],"Contraindicado","u03","c03_08",
  familia="Antivirales acción directa (AAD) hepatitis C",emb="X",
  ci=["Embarazo (por ribavirina)","Cirrosis descompensada","Hepatitis autoinmune","Uso con inductores potentes CYP3A4"],
  ea=["Anemia (frecuente y severa)","Disgeusia (sabor metálico)","Fatiga","Náuseas","Cefalea","Neutropenia"],
  ix=["Rifampicina: reduce niveles drásticamente","Anticonceptivos hormonales: reduce eficacia","Midazolam/triazolam: contraindicado","Drospirenona: contraindicada (hiperpotasemia)"],
  ce=["Fármaco histórico: ya NO es tratamiento de primera línea","Reemplazado por AAD sin interferón (Harvoni, Maviret, Epclusa)","Requería PEG-interferón y ribavirina (mal tolerado)","Si aún se usa: hemograma c/2 semanas por anemia severa","Tomar SIEMPRE con alimentos (aumenta absorción 60%)"],
  alm="Refrigerar 2-8°C. Puede estar a TA hasta 3 meses."),

# ══════════════════════════════════════════════════════════════════
# c03_09 — Antifúngicos Sistémicos Adicionales (~8)
# ══════════════════════════════════════════════════════════════════

M("antifungico_sistemico","griseofulvina","Griseofulvina","Griseofulvina",["Grisovin","Fulcin"],
  "Antifúngico oral (dermatofitos)",
  "Se une a la tubulina de los dermatofitos, inhibiendo la mitosis fúngica. Se deposita en queratina recién formada, haciéndola resistente a infección fúngica",
  ["Tiña capitis (primera línea en niños)","Tiña corporis refractaria","Tiña unguium (onicomicosis dermatofítica)","Dermatofitosis extensas que no responden a tratamiento tópico"],
  ["oral"],
  {"adulto":"Micronizada: 500-1000 mg/día. Ultramicronizada: 330-750 mg/día. Duración: tiña capitis 6-8 sem, onicomicosis 6-12 meses","pediatrico":"Micronizada: 10-20 mg/kg/día. Ultramicronizada: 5-10 mg/kg/día"},
  ["Comp 250, 500 mg","Suspensión 125 mg/5mL"],"No recomendado","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="X",
  ci=["Embarazo (teratogénico)","Porfiria","Insuficiencia hepática grave","Lupus eritematoso sistémico","Hipersensibilidad a griseofulvina"],
  ea=["Cefalea (frecuente)","Náuseas","Vómitos","Fotosensibilidad","Urticaria","Hepatotoxicidad","Efecto tipo disulfiram con alcohol","Leucopenia (raro)"],
  ix=["Warfarina: reduce efecto anticoagulante (inductor enzimático)","Anticonceptivos orales: reduce eficacia (embarazo no deseado)","Alcohol: reacción tipo disulfiram","Barbitúricos: reducen niveles de griseofulvina","Ciclosporina: reduce niveles"],
  ce=["Tomar con alimentos grasos (aumenta absorción)","Anticoncepción efectiva durante y 1 mes post-tratamiento","Fotoprotección durante tratamiento","Tratamientos prolongados: hemograma y función hepática mensual","Primera línea para tiña capitis pediátrica"],
  alm="Temperatura ambiente. Proteger de la luz."),

M("antifungico_sistemico","terbinafina_sistemica","Terbinafina (Sistémica - Micosis profundas)","Terbinafina",["Lamisil comprimidos"],
  "Antifúngico alilamínico sistémico",
  "Inhibe la escualeno epoxidasa fúngica, bloqueando la síntesis de ergosterol. Acumulación tóxica de escualeno en la membrana fúngica. Fungicida contra dermatofitos",
  ["Onicomicosis dermatofítica","Tiña capitis","Tiña corporis/cruris/pedis refractaria a tratamiento tópico","Esporotricosis cutánea (alternativa)"],
  ["oral"],
  {"adulto":"250 mg/día. Onicomicosis ungueal: 6 sem (manos), 12 sem (pies). Tiña capitis: 4-6 sem","pediatrico":"10-20 kg: 62.5 mg/día. 20-40 kg: 125 mg/día. >40 kg: 250 mg/día"},
  ["Comp 250 mg"],"No recomendado","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="B",
  ci=["Insuficiencia hepática grave","Insuficiencia renal grave (ClCr <50)","Hipersensibilidad a terbinafina"],
  ea=["Cefalea","Diarrea","Dispepsia","Erupción cutánea","Alteración del gusto (ageusia)","Hepatotoxicidad (raro pero grave)","Reacciones cutáneas graves (Stevens-Johnson, raro)","Neutropenia (raro)"],
  ix=["Rifampicina: reduce niveles de terbinafina 50%","Cimetidina: aumenta niveles de terbinafina","Cafeína: terbinafina reduce metabolismo de cafeína","Ciclosporina: terbinafina aumenta aclaramiento","CYP2D6: terbinafina es inhibidor (precaución con ADT, ISRS, betabloqueantes)"],
  ce=["Función hepática basal y a las 4-6 semanas","Suspender si transaminasas >2x LSN","Pérdida de gusto reversible al suspender","Más eficaz que azoles para onicomicosis dermatofítica","Puede tomarse con o sin alimentos"],
  alm="Temperatura ambiente."),

M("antifungico_sistemico","ketoconazol_oral","Ketoconazol (Oral)","Ketoconazol",["Nizoral comprimidos"],
  "Antifúngico azólico oral (uso restringido)",
  "Imidazol que inhibe la 14-alfa-desmetilasa (CYP51) fúngica, bloqueando la síntesis de ergosterol. También inhibe CYP enzimas humanas (endocrinas)",
  ["Síndrome de Cushing (uso off-label como inhibidor de esteroidogénesis)","Micosis sistémicas cuando no hay alternativa","Dermatofitosis severas refractarias"],
  ["oral"],
  {"adulto":"200-400 mg/día. Cushing: 400-1200 mg/día en dosis divididas"},
  ["Comp 200 mg"],"Contraindicado","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="X",
  ci=["Enfermedad hepática aguda o crónica","Uso con fármacos hepatotóxicos","Uso con terfenadina, astemizol, cisaprida, triazolam (prolongación QT fatal)","Embarazo","Hipersensibilidad"],
  ea=["⚠️ Hepatotoxicidad severa (incluyendo casos fatales)","Náuseas","Vómitos","Dolor abdominal","Ginecomastia","Insuficiencia adrenal (dosis altas)","Oligospermia","Prolongación QT"],
  ix=["⚠️ Inhibidor potente CYP3A4: MÚLTIPLES interacciones peligrosas","Simvastatina/lovastatina: rabdomiólisis (contraindicado)","Cisaprida/terfenadina: arritmia fatal","IBP/antiácidos: reducen absorción (requiere acidez gástrica)","Warfarina: aumenta INR"],
  ce=["⚠️ USO ORAL RESTRINGIDO por hepatotoxicidad severa","EMA y FDA recomiendan NO usar como antifúngico de primera línea oral","Monitorizar función hepática SEMANAL las primeras semanas","Uso principal actual: síndrome de Cushing (inhibición esteroidogénesis)","Requiere medio ácido: tomar con bebida ácida si usa IBP"],
  alm="Temperatura ambiente."),

M("antifungico_sistemico","miconazol_oral","Miconazol (Gel oral)","Miconazol",["Daktarin gel oral"],
  "Antifúngico azólico en gel oral",
  "Imidazol que inhibe la síntesis de ergosterol y altera la permeabilidad de la membrana fúngica. Acción local en cavidad oral con mínima absorción sistémica",
  ["Candidiasis orofaríngea","Candidiasis oral en pacientes inmunodeprimidos","Estomatitis protésica por Candida"],
  ["oral"],
  {"adulto":"Gel oral: 2.5 mL (medio cucharadita) c/6h. Retener en boca el mayor tiempo posible antes de tragar. Duración: 7 días tras resolución","pediatrico":">4 meses: 1.25 mL c/6h. >2 años: 2.5 mL c/6h"},
  ["Gel oral 20 mg/g (tubo 40 g, 80 g)"],"Compatible con precaución","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="C",
  ci=["Hipersensibilidad a miconazol","Insuficiencia hepática","Uso con warfarina (interacción significativa incluso con gel oral)","Niños <4 meses o con reflejo de deglución inmaduro"],
  ea=["Náuseas","Vómitos","Diarrea (si se traga)","Alteración del gusto","Boca seca","Reacción alérgica local"],
  ix=["Warfarina: aumenta INR significativamente (incluso gel oral absorbido en mucosa)","Sulfonilureas: riesgo de hipoglucemia","Fenitoína: aumenta niveles","Simvastatina: riesgo de miopatía"],
  ce=["Aplicar gel en encías y mucosa oral, NO solo tragar","Retener en boca el mayor tiempo posible (efecto tópico)","Precaución con warfarina: monitorizar INR incluso con gel oral","En lactantes: aplicar en mejillas, no en garganta (riesgo asfixia)","Retirar prótesis dental antes de aplicar"],
  alm="Temperatura ambiente. No refrigerar."),

M("antifungico_sistemico","natamicina","Natamicina","Natamicina",["Natacyn"],
  "Antifúngico poliénico oftálmico",
  "Macrólido poliénico que se une al ergosterol de la membrana fúngica, aumentando la permeabilidad celular. No se absorbe sistémicamente desde la superficie ocular",
  ["Queratitis fúngica (primera línea)","Blefaritis fúngica","Conjuntivitis fúngica","Infección fúngica ocular por Fusarium"],
  ["oftalmica"],
  {"adulto":"Suspensión oftálmica 5%: 1 gota c/1-2h x 3-4 días, luego 1 gota c/3-4h x 14-21 días. Reducir gradualmente"},
  ["Suspensión oftálmica 5% (15 mL)"],"Compatible (uso tópico)","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="C",
  ci=["Hipersensibilidad a natamicina"],
  ea=["Irritación ocular","Lagrimeo","Hiperemia conjuntival","Edema palpebral","Visión borrosa transitoria"],
  ix=["Corticosteroides tópicos oculares: pueden empeorar infección fúngica (evitar en queratitis fúngica)"],
  ce=["Agitar bien antes de cada uso (SUSPENSIÓN)","Tratamiento prolongado: 14-21 días mínimo","No usar corticosteroides oculares concomitantes","Única opción aprobada para queratitis fúngica en muchos países","Seguimiento oftalmológico estrecho"],
  alm="Refrigerar 2-8°C. Proteger de la luz y congelación."),

M("antifungico_sistemico","oteseconazol","Oteseconazol","Oteseconazol",["Vivjoa"],
  "Azol tetrazólico oral (nuevo mecanismo)",
  "Primer azol tetrazólico: inhibe la CYP51 fúngica con selectividad 2000x superior sobre las CYP humanas. Esto elimina las interacciones medicamentosas y efectos endocrinos de los azoles clásicos",
  ["Candidiasis vulvovaginal recurrente (prevención de recurrencias)"],
  ["oral"],
  {"adulto":"Fase de inducción: 600 mg día 1, 450 mg día 2, luego 150 mg/día x 11 semanas como mantenimiento"},
  ["Cáps 150 mg"],"No recomendado","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="X",
  ci=["Embarazo (teratogénico en animales)","Mujeres en edad fértil sin anticoncepción efectiva","Hipersensibilidad"],
  ea=["Cefalea","Náuseas","Dismenorrea","Infección del tracto urinario","Dolor abdominal"],
  ix=["Mínimas interacciones medicamentosas (ventaja principal sobre otros azoles)","Rosuvastatina: leve aumento de niveles (monitorizar)"],
  ce=["Primer antifúngico con selectividad fúngica real (no afecta CYP humanas)","Anticoncepción obligatoria durante tratamiento y 3 meses post","Indicación específica: prevención de recurrencias en CVV recurrente","Mecanismo selectivo: sin efecto sobre esteroidogénesis humana","Vida media muy larga (138 días)"],
  alm="Temperatura ambiente."),

M("antifungico_sistemico","ibrexafungerp","Ibrexafungerp","Ibrexafungerp",["Brexafemme"],
  "Triterpenoide antifúngico (primera en su clase)",
  "Primer triterpenoide antifúngico. Inhibe la glucano sintasa (como equinocandinas) pero con biodisponibilidad oral. Activo contra Candida resistente a azoles",
  ["Candidiasis vulvovaginal","Candidiasis vulvovaginal recurrente (tratamiento agudo)"],
  ["oral"],
  {"adulto":"CVV aguda: 300 mg c/12h x 1 día (2 dosis). CVV recurrente: 300 mg c/12h x 1 día, luego 300 mg c/12h x 1 día en día 4 y fase de mantenimiento"},
  ["Comp 150 mg"],"No recomendado","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="X",
  ci=["Embarazo (embriotóxico/teratogénico)","Hipersensibilidad","Uso con inhibidores potentes de CYP3A4"],
  ea=["Diarrea","Náuseas","Dolor abdominal","Mareo","Sofocos","Flujo vaginal"],
  ix=["Inhibidores potentes CYP3A4 (itraconazol, ketoconazol): aumentan niveles","Inductores potentes CYP3A4 (rifampicina): reducen niveles"],
  ce=["Primera glucano sintasa oral (mecanismo similar a caspofungina pero oral)","Activo contra cepas resistentes a fluconazol","Anticoncepción obligatoria durante y 4 días post-tratamiento","Test de embarazo antes de cada ciclo de tratamiento","Puede tomarse con o sin alimentos"],
  alm="Temperatura ambiente."),

M("antifungico_sistemico","tavaborol","Tavaborol","Tavaborol",["Kerydin"],
  "Antifúngico a base de boro (oxaborol)",
  "Primer antifúngico oxaborólico. Inhibe la leucil-ARNt sintetasa fúngica, bloqueando la síntesis proteica. Bajo peso molecular permite penetración ungueal",
  ["Onicomicosis de uñas de los pies por dermatofitos (Trichophyton rubrum, T. mentagrophytes)"],
  ["topica"],
  {"adulto":"Solución tópica 5%: aplicar en uña afectada y bajo borde distal c/24h x 48 semanas"},
  ["Solución tópica 5% (10 mL)"],"Compatible (uso tópico)","u03","c03_09",
  familia="Antifúngicos sistémicos",emb="C",
  ci=["Hipersensibilidad a tavaborol","Uso en niños <6 años (no estudiado)"],
  ea=["Dermatitis de contacto periungular","Exfoliación de piel","Eritema","Onicolisis","Prurito"],
  ix=["Mínimas interacciones sistémicas (absorción sistémica <5%)"],
  ce=["Aplicar SOLO en la uña y piel inmediatamente adyacente","Aplicar en uña seca y limpia","Tratamiento prolongado: 48 semanas completas","Penetración ungueal superior a ciclopirox (ventaja)","Resultado completo se evalúa meses después de terminar tratamiento"],
  alm="Temperatura ambiente. Mantener frasco bien cerrado. Inflamable: alejar de llamas."),

# ══════════════════════════════════════════════════════════════════
# c03_05 — Antituberculosos (+5)
# ══════════════════════════════════════════════════════════════════

M("antituberculoso","delamanid","Delamanid","Delamanid",["Deltyba"],
  "Nitro-dihidro-imidazooxazol antituberculoso",
  "Inhibe la síntesis de ácidos micólicos de la pared celular de Mycobacterium tuberculosis (componentes metoxil y cetomicólicos). Mecanismo distinto a todos los antituberculosos clásicos",
  ["Tuberculosis multirresistente (MDR-TB) en combinación con otros fármacos","TB extensamente resistente (XDR-TB)"],
  ["oral"],
  {"adulto":"100 mg c/12h con alimentos x 24 semanas (como parte de régimen combinado)","pediatrico":">3 años y >10 kg: dosis según peso (aprobado en pediátricos en algunos países)"},
  ["Comp 50 mg"],"Contraindicado","u03","c03_05",emb="X",
  ci=["Hipersensibilidad","Albúmina sérica <2.8 g/dL","Prolongación QTcF >500 ms","Uso con inductores potentes de CYP3A4"],
  ea=["Prolongación QT","Náuseas","Vómitos","Mareo","Parestesias","Ansiedad","Temblor","Hipopotasemia"],
  ix=["Fármacos que prolongan QT (bedaquilina, moxifloxacino, clofazimina): efecto aditivo en QT","Rifampicina: reduce niveles drásticamente (EVITAR)","Inhibidores CYP3A4: aumentan niveles"],
  ce=["ECG basal y mensual (prolongación QT)","Monitorizar electrolitos (K+, Ca2+, Mg2+) antes y durante","Tomar SIEMPRE con alimentos (aumenta absorción 2.7x)","Solo en contexto de MDR-TB con régimen supervisado","Corregir hipopotasemia antes de iniciar"],
  alm="Temperatura ambiente. Proteger de humedad."),

M("antituberculoso","pretomanid","Pretomanid","Pretomanid",["Dovprela (en combinación BPaL)"],
  "Nitroimidazooxazina antituberculosa",
  "Bicida: activo contra M. tuberculosis tanto en fase de replicación (inhibe síntesis de ácidos micólicos) como en fase latente anaeróbica (genera óxido nítrico reactivo intracelular)",
  ["TB extensamente resistente (XDR-TB) en régimen BPaL (bedaquilina + pretomanid + linezolid)","TB-MDR intolerante o sin respuesta a tratamiento"],
  ["oral"],
  {"adulto":"200 mg/día con alimentos x 26 semanas (régimen BPaL: bedaquilina + pretomanid + linezolid)"},
  ["Comp 200 mg"],"Contraindicado","u03","c03_05",emb="X",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Prolongación QT significativa"],
  ea=["Hepatotoxicidad","Neuropatía periférica (por linezolid en el régimen)","Acné","Náuseas","Vómitos","Cefalea","Prolongación QT leve"],
  ix=["Rifampicina: reduce niveles drásticamente","Efavirenz: reduce niveles","Ritonavir: aumenta niveles","Fármacos que prolongan QT: precaución"],
  ce=["Solo en régimen BPaL (nunca en monoterapia)","Función hepática semanal x 2 meses, luego mensual","Régimen BPaL: 26 semanas (revolucionario: reduce de 18-20 meses a 6)","ECG basal y periódico","Agudeza visual y sensibilidad periférica mensual (por linezolid)"],
  alm="Temperatura ambiente. Proteger de humedad."),

M("antituberculoso","clofazimina","Clofazimina","Clofazimina",["Lamprene"],
  "Riminofenazina antimicobacteriana",
  "Se une al ADN micobacteriano e interfiere con la cadena de transporte de electrones. Genera radicales libres de oxígeno intracelulares. También tiene efecto antiinflamatorio",
  ["Lepra multibacilar (componente del esquema OMS)","TB multirresistente (uso off-label como parte de régimen combinado)","Infecciones por Mycobacterium avium complex"],
  ["oral"],
  {"adulto":"Lepra: 300 mg/mes supervisado + 50 mg/día x 12 meses (esquema OMS). TB-MDR: 100-200 mg/día","pediatrico":"Lepra: 1-2 mg/kg/día"},
  ["Cáps 50, 100 mg"],"Compatible (uso prolongado necesario en lepra)","u03","c03_05",emb="C",
  ci=["Hipersensibilidad","Dolor abdominal severo o diagnóstico previo de obstrucción intestinal por cristales de clofazimina"],
  ea=["⚠️ Pigmentación cutánea rojo-marrón (reversible, tarda meses)","Ictiosis/sequedad cutánea","Dolor abdominal","Depósito de cristales en intestino","Pigmentación de conjuntiva, lágrimas, sudor","Fotosensibilidad","Prolongación QT"],
  ix=["Dapsona: puede reducir efecto antiinflamatorio de clofazimina","Isoniazida: puede aumentar niveles de clofazimina","Rifampicina: reduce niveles de clofazimina"],
  ce=["Informar al paciente sobre pigmentación cutánea (rojo-marrón): REVERSIBLE al suspender (meses-años)","Tomar con alimentos (mejora absorción y reduce molestias GI)","Pigmenta sudor, lágrimas y orina: no alarmarse","Tratamiento prolongado en lepra: adherencia es crítica","Disponibilidad limitada: solicitar a OMS en muchos países"],
  alm="Temperatura ambiente. Proteger de la luz y humedad."),

M("antituberculoso","acido_paraaminosalicilico","Ácido para-aminosalicílico (PAS)","Ácido 4-aminosalicílico",["Paser"],
  "Antituberculoso de segunda línea",
  "Análogo estructural del ácido para-aminobenzoico (PABA). Inhibe competitivamente la dihidropteroato sintasa y el metabolismo del folato en M. tuberculosis. Bacteriostático",
  ["TB multirresistente (MDR-TB) como parte de régimen de segunda línea","TB cuando no se pueden usar fármacos de primera línea"],
  ["oral"],
  {"adulto":"Gránulos: 4 g c/8h (12 g/día). Tomar con alimentos ácidos o yogur","pediatrico":"150-200 mg/kg/día dividido c/6-8h (máx 12 g/día)"},
  ["Gránulos gastrorresistentes 4 g/sobre"],"Compatible con precaución","u03","c03_05",emb="C",
  ci=["Insuficiencia renal grave","Hipersensibilidad a salicilatos","Enfermedad hepática severa"],
  ea=["Intolerancia GI (muy frecuente: náuseas, vómitos, diarrea)","Hepatotoxicidad","Hipotiroidismo (uso prolongado)","Síndrome de malabsorción","Reacciones de hipersensibilidad","Cristaluria"],
  ix=["Digoxina: reduce absorción","Vitamina B12: reduce absorción","Isoniazida: aumenta niveles de isoniazida (puede ser beneficioso)","Etionamida: hepatotoxicidad aditiva"],
  ce=["Gránulos: NO triturar ni masticar (cubierta gastrorresistente)","Mezclar con alimentos ácidos (yogur, jugo de naranja, compota de manzana)","Hidratación abundante (prevenir cristaluria)","Monitorizar TSH en tratamiento prolongado (bocigénesis)","Uno de los antituberculosos peor tolerados: apoyo al paciente es fundamental"],
  alm="Refrigerar gránulos. Proteger de calor y humedad. Los gránulos que se tornan marrones oscuros están degradados."),

M("antituberculoso","linezolid_tb","Linezolid (Uso antituberculoso)","Linezolid",["Zyvox"],
  "Oxazolidinona en tuberculosis resistente",
  "Inhibe la síntesis proteica al unirse a la subunidad ribosomal 50S (sitio 23S). Activo contra M. tuberculosis incluyendo cepas MDR y XDR. Componente clave del régimen BPaL",
  ["TB multirresistente (MDR-TB)","TB extensamente resistente (XDR-TB) — régimen BPaL","TB cuando han fallado otros esquemas"],
  ["oral","IV"],
  {"adulto":"600 mg/día (puede reducirse a 300 mg/día si toxicidad). Duración: 26 semanas en BPaL, hasta 18-20 meses en otros regímenes","ajusteRenal":"No requiere ajuste (pero metabolitos se acumulan en diálisis)"},
  ["Comp 600 mg","Suspensión 100 mg/5mL","Bolsa IV 2 mg/mL (300 mL)"],"No recomendado","u03","c03_05",emb="C",
  ci=["Hipersensibilidad a oxazolidinonas","Uso con IMAO","Feocromocitoma no tratado","Síndrome carcinoide","Tirotoxicosis no controlada"],
  ea=["⚠️ Mielosupresión (trombocitopenia, anemia)","⚠️ Neuropatía periférica (puede ser irreversible)","⚠️ Neuritis óptica (puede causar ceguera)","Acidosis láctica","Diarrea","Náuseas","Síndrome serotoninérgico (con serotoninérgicos)"],
  ix=["IMAO: efecto IMAO débil del linezolid (crisis hipertensiva)","ISRS/ISRSN: síndrome serotoninérgico","Alimentos ricos en tiramina: precaución (efecto IMAO)","Adrenalina/dopamina: respuesta presora aumentada"],
  ce=["En TB: dosis MENOR que en infecciones bacterianas estándar (600 vs 1200 mg)","Hemograma SEMANAL: trombocitopenia puede ser abrupta","Agudeza visual y visión cromática MENSUAL (neuritis óptica)","Evaluación de neuropatía periférica MENSUAL","Considerar reducción a 300 mg si toxicidad hematológica","Dieta baja en tiramina (quesos curados, embutidos, cerveza)"],
  pp={"dilucion":"Bolsa lista para infusión 2 mg/mL","velocidadAdministracion":"Infundir en 30-120 min","estabilidad":"Bolsa sin abrir: a TA hasta caducidad"},
  alm="Temperatura ambiente. Proteger de la luz. Bolsa IV: no requiere dilución adicional."),

# ══════════════════════════════════════════════════════════════════
# c03_06 — Antiparasitarios (+8)
# ══════════════════════════════════════════════════════════════════

M("antiparasitario","artesunato","Artesunato","Artesunato",["Artesunate"],
  "Derivado de artemisinina (antipalúdico)",
  "Derivado semisintético de artemisinina (Artemisia annua). Genera radicales libres al interactuar con hierro del grupo hemo del parásito, causando daño oxidativo. Acción rápida contra todos los estadios eritrocitarios",
  ["Malaria severa/grave (primera línea OMS)","Malaria por P. falciparum complicada","Malaria cerebral"],
  ["IV","IM"],
  {"adulto":"2.4 mg/kg IV a las 0, 12 y 24h, luego c/24h hasta tolerar oral. Mínimo 24h IV. Luego completar con ACT oral","pediatrico":"Misma dosis mg/kg. <20 kg: 3 mg/kg/dosis (mayor volumen de distribución)"},
  ["Vial 60 mg (polvo) + ampolla de bicarbonato de sodio 5% como diluyente"],"Compatible con precaución","u03","c03_06",emb="C",
  ci=["Hipersensibilidad a derivados de artemisinina","Primer trimestre de embarazo (relativo: beneficio supera riesgo en malaria severa)"],
  ea=["Anemia hemolítica retardada post-tratamiento (PADH)","Neutropenia transitoria","Elevación transitoria de transaminasas","Bradicardia","Reticulocitopenia","Prolongación QT (leve)"],
  ix=["Mefloquina: puede aumentar riesgo de convulsiones si se administra juntos","Antirretrovirales: posibles interacciones farmacocinéticas"],
  ce=["⚠️ PRIMERA LÍNEA en malaria severa (reemplazó a quinina)","Reconstituir con bicarbonato de sodio 5% primero, luego diluir con SF","Hemograma semanal x 4 semanas post-tratamiento (hemólisis retardada PADH)","NUNCA usar como monoterapia (riesgo de resistencia)","Completar con ACT oral al poder tolerar vía oral"],
  pp={"reconstitucion":"Disolver 60 mg en 1 mL de bicarbonato de sodio 5%. Agitar 2-3 min hasta solución clara","dilucion":"Agregar 5 mL de SF (concentración 10 mg/mL)","velocidadAdministracion":"Bolo IV lento en 1-2 min. IM: inyectar en cara anterior del muslo","estabilidad":"Usar inmediatamente tras reconstitución (dentro de 1h)"},
  alm="Temperatura ambiente. No refrigerar. Proteger de la luz y humedad."),

M("antiparasitario","artemeter_lumefantrina","Arteméter/Lumefantrina","Arteméter + Lumefantrina",["Coartem","Riamet"],
  "Terapia combinada basada en artemisinina (ACT)",
  "Arteméter: derivado lipofílico de artemisinina, genera radicales libres que dañan membranas del parásito. Lumefantrina: arilaminoalcohol que inhibe la cristalización del hemo. Acción sinérgica y complementaria en farmacocinética",
  ["Malaria no complicada por P. falciparum (primera línea OMS)","Malaria por P. vivax resistente a cloroquina","Malaria mixta"],
  ["oral"],
  {"adulto":"4 comp (80/480 mg) a las 0, 8, 24, 36, 48 y 60h (total: 24 comp en 3 días)","pediatrico":"5-15 kg: 1 comp por dosis. 15-25 kg: 2 comp. 25-35 kg: 3 comp. >35 kg: 4 comp. Mismo esquema de 6 dosis"},
  ["Comp 20/120 mg"],"No recomendado durante lactancia si el lactante pesa <5 kg","u03","c03_06",emb="C",
  ci=["Hipersensibilidad a arteméter o lumefantrina","Primer trimestre embarazo (usar quinina+clindamicina)","Malaria severa (usar artesunato IV)"],
  ea=["Cefalea","Mareo","Anorexia","Dolor abdominal","Artralgia","Mialgia","Palpitaciones","Prolongación QT (lumefantrina)"],
  ix=["Fármacos que prolongan QT: efecto aditivo (evitar halofantrina)","Inhibidores CYP3A4: aumentan niveles de arteméter","Inductores CYP3A4 (rifampicina, efavirenz): reducen eficacia","Jugo de pomelo: aumenta niveles"],
  ce=["Tomar con alimentos GRASOS o leche entera (absorción de lumefantrina aumenta 16x)","Si vomita dentro de 1h: repetir la dosis","Completar las 6 dosis aunque mejore antes","No usar en malaria severa: requiere artesunato IV","ECG si uso con otros fármacos que prolongan QT"],
  alm="Temperatura ambiente. Proteger de humedad y luz."),

M("antiparasitario","mefloquina","Mefloquina","Mefloquina",["Lariam"],
  "Antipalúdico quinolina-metanol",
  "Esquizonticida sanguíneo. Se acumula en vacuolas digestivas del Plasmodium e inhibe la cristalización del hemo, causando acumulación tóxica de hematina",
  ["Profilaxis de malaria en zonas de P. falciparum resistente a cloroquina","Tratamiento de malaria no complicada (cuando ACT no está disponible)"],
  ["oral"],
  {"adulto":"Profilaxis: 250 mg/sem (iniciar 2-3 sem antes, durante y 4 sem después). Tratamiento: 15-25 mg/kg dividido en 2-3 dosis separadas por 6-12h","pediatrico":"Profilaxis: 5 mg/kg/sem"},
  ["Comp 250 mg"],"Compatible con precaución","u03","c03_06",emb="C",
  ci=["Antecedente de trastornos neuropsiquiátricos (depresión, psicosis, convulsiones, ansiedad severa)","Epilepsia","Hipersensibilidad a mefloquina o quinina","Uso con halofantrina","Trastornos de conducción cardíaca"],
  ea=["⚠️ Neuropsiquiátricos: pesadillas, ansiedad, depresión, psicosis, convulsiones","Mareo","Náuseas","Vómitos","Diarrea","Tinnitus","Alteraciones del equilibrio","Prolongación QT"],
  ix=["Halofantrina: prolongación QT fatal (CONTRAINDICADO)","Quinina/quinidina: potencian cardiotoxicidad","Anticonvulsivantes: mefloquina reduce umbral convulsivo","Betabloqueantes: potencian bradicardia"],
  ce=["Evaluar antecedentes psiquiátricos ANTES de prescribir","Advertir sobre síntomas neuropsiquiátricos: suspender inmediatamente si aparecen","Profilaxis: iniciar 2-3 semanas antes del viaje (para detectar efectos adversos)","No administrar en estómago vacío (náuseas)","Vida media larga (2-3 semanas): efectos adversos pueden persistir"],
  alm="Temperatura ambiente."),

M("antiparasitario","quinina","Quinina","Quinina (sulfato/clorhidrato)",["Qualaquin"],
  "Alcaloide antipalúdico natural",
  "Alcaloide de la corteza de Cinchona. Esquizonticida sanguíneo que se acumula en vacuola digestiva del Plasmodium e interfiere con la digestión de hemoglobina y cristalización del hemo",
  ["Malaria severa (alternativa si artesunato no disponible)","Malaria no complicada por P. falciparum (con doxiciclina o clindamicina)","Calambres nocturnos de piernas (uso restringido por FDA)"],
  ["oral","IV"],
  {"adulto":"Oral: 600 mg c/8h x 3-7 días (con doxiciclina 7 días). IV: 20 mg/kg dosis de carga en SG5% en 4h, luego 10 mg/kg c/8h","pediatrico":"10 mg/kg c/8h oral x 7 días (con clindamicina)"},
  ["Comp 300, 600 mg","Amp 300 mg/mL"],"Compatible con precaución (dosis terapéuticas)","u03","c03_06",emb="C",
  ci=["Déficit de G6PD (riesgo de hemólisis)","Miastenia gravis","Neuritis óptica","Prolongación QT","Hipersensibilidad a quinina o quinidina","Hemoglobinuria (fiebre de aguas negras)"],
  ea=["Cinconismo (tinnitus, cefalea, náuseas, alteraciones visuales, mareo)","Hipoglucemia (estimula secreción de insulina)","Prolongación QT","Trombocitopenia","Hemólisis (en G6PD)","Hipotensión (IV rápida)"],
  ix=["Digoxina: aumenta niveles","Warfarina: aumenta efecto anticoagulante","Mefloquina: cardiotoxicidad aditiva (esperar 12h entre ambos)","Cimetidina: aumenta niveles de quinina","Fármacos que prolongan QT: arritmia"],
  ce=["IV: administrar LENTAMENTE (nunca en bolo: arritmia fatal)","Monitorizar glucemia c/4-6h (hipoglucemia frecuente, especialmente en embarazo)","ECG continuo durante infusión IV","Cinconismo es dosis-dependiente y generalmente reversible","Puede oscurecer la orina (normal)"],
  pp={"dilucion":"Diluir en 500 mL SG5% (dosis de carga) o 250 mL (mantenimiento)","velocidadAdministracion":"Dosis de carga: infundir en 4 horas. Mantenimiento: infundir en 2-4 horas. NUNCA en bolo IV","estabilidad":"Usar inmediatamente tras dilución"},
  alm="Temperatura ambiente. Proteger de la luz."),

M("antiparasitario","pirantel","Pirantel","Pirantel (pamoato)",["Combantrin","Pin-X"],
  "Antihelmíntico agonista neuromuscular",
  "Agonista colinérgico: produce despolarización neuromuscular sostenida en el helminto, causando parálisis espástica. El parásito paralizado es expulsado por peristaltismo intestinal",
  ["Oxiuriasis (Enterobius vermicularis/oxiuros)","Ascariasis (Ascaris lumbricoides)","Uncinariasis (Ancylostoma, Necator)"],
  ["oral"],
  {"adulto":"11 mg/kg dosis única (máx 1 g). Oxiuros: repetir en 2 semanas. Uncinarias: 3 días","pediatrico":">6 meses: misma dosis por kg. Oxiuros: tratar a toda la familia simultáneamente"},
  ["Comp masticable 250 mg","Suspensión 50 mg/mL"],"Compatible (absorción mínima)","u03","c03_06",emb="C",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Uso concomitante con piperazina (antagonismo)"],
  ea=["Dolor abdominal","Náuseas","Diarrea","Cefalea","Mareo","Anorexia","Elevación transitoria de transaminasas (raro)"],
  ix=["Piperazina: antagonismo farmacológico (NO combinar)","Teofilina: pirantel puede aumentar niveles"],
  ce=["Tratar a TODA la familia simultáneamente en oxiuros","Lavado de ropa de cama y toallas el día de tratamiento","Higiene de manos estricta (cortar uñas cortas)","Puede tomarse con alimentos o en ayunas","Comprimidos masticables: masticar antes de tragar"],
  alm="Temperatura ambiente."),

M("antiparasitario","niclosamida","Niclosamida","Niclosamida",["Yomesan","Niclocide"],
  "Antihelmíntico cestodicida",
  "Inhibe la fosforilación oxidativa mitocondrial del parásito y bloquea la captación de glucosa. El escólex y segmentos proximales de la tenia se destruyen, liberándose de la mucosa intestinal",
  ["Teniasis por Taenia saginata (tenia de la vaca)","Teniasis por Taenia solium (tenia del cerdo) — con precaución","Difilobotriasis (Diphyllobothrium latum)","Himenolepiasis (Hymenolepis nana)"],
  ["oral"],
  {"adulto":"T. saginata/solium: 2 g dosis única en ayunas (masticar bien). H. nana: 2 g día 1, luego 1 g/día x 6 días","pediatrico":"11-34 kg: 1 g. >34 kg: 1.5 g. H. nana: mitad de dosis de adulto"},
  ["Comp masticable 500 mg"],"Compatible (no se absorbe)","u03","c03_06",emb="B",
  ci=["Hipersensibilidad"],
  ea=["Náuseas","Dolor abdominal","Diarrea","Mareo","Sabor desagradable","Prurito anal"],
  ix=["Mínimas interacciones (no se absorbe sistémicamente)","Alcohol: evitar el día del tratamiento"],
  ce=["Masticar comprimidos completamente antes de tragar con poca agua","Tomar en AYUNAS con desayuno ligero 2h después","En T. solium: administrar laxante 2h post-dosis (prevenir cisticercosis por autoinfección)","Buscar escólex en heces para confirmar curación","H. nana: tratamiento de 7 días (no dosis única)"],
  alm="Temperatura ambiente."),

M("antiparasitario","proguanil_atovacuona","Atovacuona/Proguanil","Atovacuona + Proguanil",["Malarone"],
  "Combinación antipalúdica sinérgica",
  "Atovacuona: inhibe el complejo citocromo bc1 (complejo III) mitocondrial del Plasmodium. Proguanil: inhibidor de dihidrofolato reductasa. Acción sinérgica en dos blancos mitocondriales distintos",
  ["Profilaxis de malaria (todas las especies)","Tratamiento de malaria no complicada por P. falciparum","Alternativa para zonas con resistencia a cloroquina y mefloquina"],
  ["oral"],
  {"adulto":"Profilaxis: 1 comp (250/100 mg)/día, 1-2 días antes, durante y 7 días después del viaje. Tratamiento: 4 comp/día x 3 días","pediatrico":"Profilaxis: 5-8 kg: 1/2 comp pediátrico/día. 9-10 kg: 3/4 comp ped. 11-20 kg: 1 comp ped. 21-30 kg: 2 comp ped. 31-40 kg: 3 comp ped. >40 kg: dosis adulto"},
  ["Comp adulto 250/100 mg","Comp pediátrico 62.5/25 mg"],"Compatible con precaución","u03","c03_06",emb="C",
  ci=["Hipersensibilidad","Insuficiencia renal grave (ClCr <30) para profilaxis","Embarazo primer trimestre (datos limitados)"],
  ea=["Dolor abdominal","Náuseas","Vómitos","Diarrea","Cefalea","Tos","Prurito","Elevación transitoria de transaminasas"],
  ix=["Metoclopramida: reduce niveles de atovacuona","Tetraciclinas: reducen niveles de atovacuona","Rifampicina/rifabutina: reducen niveles de atovacuona 40-50%","Warfarina: puede aumentar INR"],
  ce=["Tomar con alimentos GRASOS o leche (absorción de atovacuona aumenta 2-3x)","Profilaxis: solo 7 días post-viaje (ventaja sobre mefloquina/doxiciclina)","Si vomita dentro de 1h: repetir la dosis","Mejor perfil neuropsiquiátrico que mefloquina","Menor fotosensibilidad que doxiciclina"],
  alm="Temperatura ambiente."),

M("antiparasitario","amodiaquina","Amodiaquina","Amodiaquina",["Camoquin","Flavoquine"],
  "4-aminoquinolina antipalúdica",
  "Esquizonticida sanguíneo que se acumula en la vacuola digestiva del Plasmodium e inhibe la polimerización del hemo. Profármaco: metabolito activo es desethylamodiaquina",
  ["Malaria no complicada por P. falciparum (en combinación con artesunato: ASAQ)","Quimioprofilaxis estacional de malaria en niños (SMC)","Malaria en zonas de resistencia a cloroquina"],
  ["oral"],
  {"adulto":"Tratamiento (con artesunato): 10 mg/kg/día x 3 días. Dosis fija: según peso en combinados ASAQ","pediatrico":"Igual dosis mg/kg. Formulación pediátrica disponible en combinados"},
  ["Comp 200 mg (base)","Comp combinado ASAQ: artesunato/amodiaquina según peso"],"No recomendado","u03","c03_06",emb="C",
  ci=["Hipersensibilidad a amodiaquina o 4-aminoquinolinas","Hepatopatía previa","Antecedente de agranulocitosis por amodiaquina","Uso como profilaxis individual (solo SMC estacional)"],
  ea=["Prurito","Náuseas","Vómitos","Dolor abdominal","⚠️ Agranulocitosis (uso prolongado)","⚠️ Hepatotoxicidad (uso prolongado)","Pigmentación gris-azulada (uso crónico)"],
  ix=["Efavirenz: reduce niveles de desethylamodiaquina","Fármacos hepatotóxicos: efecto aditivo","Mefloquina: esperar al menos 24h entre ambos"],
  ce=["SIEMPRE en combinación con artesunato (nunca en monoterapia)","No usar como profilaxis individual (hepatotoxicidad con uso prolongado)","Hemograma y función hepática si uso >3 días","En SMC pediátrica: administración mensual durante temporada de transmisión","OMS recomienda ASAQ como una de las ACT de primera línea"],
  alm="Temperatura ambiente. Proteger de la luz y humedad."),
]

NEW_CHAPTERS = {
    "c03_08": {"id":"c03_08","nombre":"Antivirales Hepatitis y Otros","unidadId":"u03","drugIds":[]},
    "c03_09": {"id":"c03_09","nombre":"Antifúngicos Sistémicos Adicionales","unidadId":"u03","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U03b ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u03", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
