#!/usr/bin/env python3
"""Add new drugs for U08 Sistema Musculoesquelético."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ══════════════════════════════════════════════════════════════
# c08_01 AINEs (+10)
# ══════════════════════════════════════════════════════════════
M("aine","flurbiprofeno","Flurbiprofeno","Flurbiprofeno",["Ansaid","Strepfen"],
  "AINE derivado del ácido propiónico",
  "Inhibidor no selectivo de COX-1 y COX-2. Derivado fluorado del ácido propiónico con potente acción antiinflamatoria, analgésica y antipirética. También disponible en formulación oftálmica para inhibir miosis intraoperatoria.",
  ["Artritis reumatoide","Osteoartritis","Espondilitis anquilosante","Dolor musculoesquelético","Dismenorrea","Inhibición de miosis intraoperatoria (oftálmico)"],
  ["oral","oftalmica"],
  {"adulto":"Oral: 50-100 mg c/8-12h (máx 300 mg/día). Oftálmico: 1 gota c/30 min x 4 dosis pre-cirugía",
   "geriatrico":"Iniciar con dosis menores. Mayor riesgo GI y renal"},
  ["Comprimidos 50, 100 mg","Solución oftálmica 0.03%"],
  "Se excreta en leche. Evitar.","u08","c08_01"),

M("aine","sulindaco","Sulindaco","Sulindaco",["Clinoril"],
  "AINE derivado del indeno (profármaco)",
  "Profármaco que se convierte a sulfuro activo en el hígado. Inhibidor no selectivo de COX. Tiene menor efecto renal que otros AINEs porque el riñón inactiva el metabolito activo (ventaja teórica en pacientes con riesgo renal).",
  ["Artritis reumatoide","Osteoartritis","Espondilitis anquilosante","Gota aguda","Hombro doloroso agudo","Poliposis adenomatosa familiar (off-label)"],
  ["oral"],
  {"adulto":"150-200 mg c/12h con alimentos. Máx 400 mg/día. Gota: 200 mg c/12h x 7 días",
   "geriatrico":"Iniciar 150 mg/día"},
  ["Comprimidos 150, 200 mg"],
  "Se excreta en leche. Evitar.","u08","c08_01",
  ea=["Dolor epigástrico","Náuseas","Diarrea","Estreñimiento","Cefalea","Mareo","Pancreatitis (raro)","Síndrome de Stevens-Johnson (raro)","⚠️ Hepatotoxicidad: monitorizar enzimas hepáticas"]),

M("aine","diflunisal","Diflunisal","Diflunisal",["Dolobid"],
  "AINE derivado del ácido salicílico (no acetilado)",
  "Derivado difluorofenil del ácido salicílico. A diferencia de la aspirina, no inhibe irreversiblemente las plaquetas. Tiene efecto analgésico y antiinflamatorio pero mínimo efecto antipirético. Usado off-label en amiloidosis por transtiretina.",
  ["Dolor leve a moderado","Osteoartritis","Artritis reumatoide","Amiloidosis por transtiretina (off-label)"],
  ["oral"],
  {"adulto":"Inicio: 500-1000 mg, luego 250-500 mg c/8-12h. Máx 1500 mg/día",
   "geriatrico":"Reducir dosis. Mayor sensibilidad"},
  ["Comprimidos 250, 500 mg"],
  "Se excreta en leche. Evitar.","u08","c08_01",
  ea=["Dispepsia","Náuseas","Diarrea","Cefalea","Rash","Tinnitus","Edema","⚠️ Síndrome de Reye: no usar en niños con infecciones virales"]),

M("aine","meclofenato","Meclofenato","Ácido meclofenámico",["Meclomen"],
  "AINE derivado del ácido fenámico",
  "Derivado del ácido antranílico (fenamato). Inhibe COX-1 y COX-2. Además tiene actividad antagonista sobre receptores de prostaglandinas. Alta incidencia de efectos GI, especialmente diarrea.",
  ["Artritis reumatoide","Osteoartritis","Dismenorrea primaria","Dolor leve a moderado","Menorragia (sangrado menstrual excesivo)"],
  ["oral"],
  {"adulto":"50-100 mg c/4-6h. Máx 400 mg/día. Dismenorrea: 100 mg c/8h x 3-6 días"},
  ["Cápsulas 50, 100 mg"],
  "Se excreta en leche. Evitar.","u08","c08_01",
  ea=["Diarrea (muy frecuente, hasta 30%)","Dolor abdominal","Náuseas","Dispepsia","Cefalea","Rash","Anemia hemolítica (raro)","⚠️ Diarrea puede ser severa y requiere suspensión"]),

M("aine","tolmetina","Tolmetina","Tolmetina sódica",["Tolectin"],
  "AINE derivado del ácido pirrolacético",
  "Inhibidor no selectivo de COX-1 y COX-2. Derivado del ácido acético heterocíclico con propiedades antiinflamatorias, analgésicas y antipiréticas. Aprobado para uso pediátrico en artritis reumatoide juvenil.",
  ["Artritis reumatoide","Osteoartritis","Artritis reumatoide juvenil"],
  ["oral"],
  {"adulto":"400 mg c/8h. Máx 1800 mg/día","pediatrico":"≥2 años: 20 mg/kg/día dividido en 3-4 dosis. Máx 30 mg/kg/día"},
  ["Comprimidos 200, 600 mg","Cápsulas 400 mg"],
  "Se excreta en leche. Precaución.","u08","c08_01"),

M("aine","nimesulida","Nimesulida","Nimesulida",["Aulin","Nimesil","Mesulid"],
  "AINE con selectividad preferente COX-2",
  "Sulfonanilida con inhibición preferencial de COX-2. Tiene acción antiinflamatoria, analgésica y antipirética. Presenta selectividad parcial por COX-2 sin ser un coxib. Retirado en algunos países por hepatotoxicidad.",
  ["Dolor agudo","Dismenorrea","Dolor postoperatorio","Osteoartritis (tratamiento sintomático corto)"],
  ["oral"],
  {"adulto":"100 mg c/12h. Máx 200 mg/día. Duración máxima 15 días",
   "pediatrico":"Contraindicado en menores de 12 años"},
  ["Comprimidos 100 mg","Granulado para suspensión 100 mg"],
  "Evitar durante lactancia.","u08","c08_01",
  ea=["Náuseas","Dispepsia","Diarrea","Cefalea","Mareo","⚠️ Hepatotoxicidad grave (incluyendo insuficiencia hepática fulminante)","Elevación de transaminasas","Reacciones cutáneas graves (raro)"],
  ci=["Hipersensibilidad a AINEs","Insuficiencia hepática","Antecedente de hepatotoxicidad por nimesulida","Fiebre y síntomas gripales","Menores de 12 años","Embarazo y lactancia","Uso concomitante de hepatotóxicos"],
  ce=["⚠️ Uso máximo 15 días (hepatotoxicidad)","Monitorizar función hepática","Retirado en varios países (Finlandia, España, India parcialmente)","No usar como antipirético (riesgo/beneficio desfavorable)","Suspender ante ictericia, coluria u orina oscura","Administrar con alimentos"]),

M("aine","parecoxib","Parecoxib","Parecoxib sódico",["Dynastat"],
  "Inhibidor selectivo de COX-2 inyectable (profármaco de valdecoxib)",
  "Único coxib inyectable disponible. Profármaco que se convierte rápidamente a valdecoxib por hidrólisis hepática. Selectividad COX-2 similar a celecoxib. Útil como analgesia perioperatoria IV/IM.",
  ["Dolor postoperatorio a corto plazo","Analgesia perioperatoria cuando la vía oral no es factible"],
  ["IV","IM"],
  {"adulto":"40 mg IV/IM inicial, luego 20-40 mg c/6-12h. Máx 80 mg/día. Máximo 3 días",
   "geriatrico":"<50 kg: máx 40 mg/día. Iniciar con 20 mg"},
  ["Vial 40 mg polvo para inyección"],
  "No recomendado.","u08","c08_01",
  ci=["Hipersensibilidad a AINEs o sulfonamidas","Úlcera GI activa","Insuficiencia cardíaca severa (NYHA III-IV)","Post-cirugía de bypass coronario","Insuficiencia hepática severa","Insuficiencia renal severa","Tercer trimestre embarazo"],
  ea=["Náuseas","Dolor abdominal","Insomnio","Mareo","Oliguria","Hipotensión","Rash","⚠️ Riesgo cardiovascular (como otros coxibs)","⚠️ No usar >3 días"],
  ce=["Único coxib parenteral disponible","Máximo 3 días de uso","No mezclar con otros fármacos en la misma jeringa","IV: administrar en bolo directo","IM: inyección profunda en glúteo","Alternativa a ketorolaco en riesgo de sangrado","Reconstituir con SF 0.9% (2 mL)"],
  pp={"reconstitucion":"Reconstituir vial 40 mg con 2 mL SF 0.9%","dilucion":"Administrar directamente sin diluir","velocidadAdministracion":"IV: bolo directo en 15 seg. IM: inyección profunda","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("aine","tenoxicam","Tenoxicam","Tenoxicam",["Tilcotil"],
  "AINE del grupo oxicam de larga duración",
  "Derivado tienotiazínico del grupo de los oxicams. Inhibidor no selectivo de COX-1 y COX-2 con vida media prolongada (~72h) que permite dosificación una vez al día. Similar a piroxicam pero con mejor perfil GI.",
  ["Artritis reumatoide","Osteoartritis","Espondilitis anquilosante","Dolor musculoesquelético agudo","Dolor postoperatorio"],
  ["oral","IV","IM"],
  {"adulto":"Oral: 20 mg/día en dosis única. IV/IM: 20 mg/día x 1-2 días, luego pasar a oral",
   "geriatrico":"Considerar dosis menores. Mayor riesgo de efectos adversos"},
  ["Comprimidos 20 mg","Vial 20 mg polvo para inyección"],
  "Se excreta en leche. Evitar.","u08","c08_01",
  pp={"reconstitucion":"Reconstituir con 2 mL de agua estéril","dilucion":"Puede administrarse directo IV o diluido en SF","velocidadAdministracion":"IV lento en 15-30 seg","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("aine","oxaprozina","Oxaprozina","Oxaprozina",["Daypro"],
  "AINE derivado del ácido propiónico de larga acción",
  "Derivado no naptilénico del ácido propiónico con vida media prolongada (~40-60h) que permite administración una vez al día. Inhibidor no selectivo de COX. Uricosúrico leve.",
  ["Artritis reumatoide","Osteoartritis"],
  ["oral"],
  {"adulto":"600-1200 mg/día en dosis única. Máx 1800 mg/día o 26 mg/kg (lo menor)",
   "geriatrico":"Iniciar con 600 mg/día"},
  ["Comprimidos 600 mg"],
  "Se excreta en leche. Evitar.","u08","c08_01"),

M("aine","fenbufen","Fenbufen","Fenbufen",["Lederfen","Cinopal"],
  "AINE profármaco del ácido bifenil-acético",
  "Profármaco del grupo del ácido propiónico. Se metaboliza a ácido bifenilacético activo. Menor efecto directo sobre la mucosa gástrica al ser profármaco, aunque el riesgo GI sistémico persiste.",
  ["Artritis reumatoide","Osteoartritis","Dolor musculoesquelético","Lesiones de tejidos blandos"],
  ["oral"],
  {"adulto":"300 mg por la mañana + 600 mg por la noche. O bien 450 mg c/12h. Máx 900 mg/día"},
  ["Cápsulas 300 mg","Comprimidos 450 mg"],
  "Evitar durante lactancia.","u08","c08_01",
  ea=["Náuseas","Dispepsia","Diarrea","Rash eritematoso","Cefalea","⚠️ Reacciones cutáneas: eritema multiforme reportado con mayor frecuencia que otros AINEs"],
  ce=["Profármaco: menor irritación gástrica local pero riesgo sistémico persiste","Vigilar reacciones cutáneas","Suspender ante erupción cutánea","Administrar con alimentos"]),

# ══════════════════════════════════════════════════════════════
# c08_02 Relajantes Musculares (+6)
# ══════════════════════════════════════════════════════════════
M("aine","clorzoxazona","Clorzoxazona","Clorzoxazona",["Parafon Forte","Lorzone"],
  "Relajante muscular de acción central (benzoxazol)",
  "Actúa a nivel de la médula espinal y áreas subcorticales del cerebro, inhibiendo los arcos reflejos multisinápticos responsables del espasmo muscular esquelético. No actúa directamente sobre el músculo.",
  ["Espasmo muscular agudo doloroso","Cervicalgia y lumbalgia con contractura","Complemento a fisioterapia y reposo"],
  ["oral"],
  {"adulto":"250-750 mg c/6-8h. Dosis habitual: 500 mg c/8h",
   "geriatrico":"Iniciar con dosis menores por sedación"},
  ["Comprimidos 250, 500 mg"],
  "Se desconoce excreción. Precaución.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad","Insuficiencia hepática","Antecedente de hepatotoxicidad por clorzoxazona"],
  ea=["Somnolencia","Mareo","Náuseas","Orina anaranjada o púrpura (metabolito, benigno)","Molestias GI","⚠️ Hepatotoxicidad grave (raro pero reportado)"],
  ix=["Depresores del SNC: sedación aditiva","Alcohol: potencia sedación","Isoniazida: aumenta niveles de clorzoxazona (inhibición CYP2E1)"],
  ce=["Uso a corto plazo (2-3 semanas)","Advertir sobre orina anaranjada/púrpura (efecto benigno)","No conducir ni operar maquinaria","Monitorizar función hepática","Combinar con fisioterapia y medidas físicas"],
  emb="C"),

M("aine","carisoprodol","Carisoprodol","Carisoprodol",["Soma"],
  "Relajante muscular de acción central (carbamato)",
  "Carbamato con acción a nivel del tronco cerebral y médula espinal. Se metaboliza a meprobamato (ansiolítico barbitúrico-like) lo que contribuye a sedación y potencial de dependencia. Modula transmisión GABAérgica.",
  ["Espasmo muscular agudo doloroso (uso a corto plazo)","Complemento a reposo y fisioterapia"],
  ["oral"],
  {"adulto":"250-350 mg c/8h y al acostarse. Máx 2-3 semanas de uso"},
  ["Comprimidos 250, 350 mg"],
  "Se excreta en leche (como meprobamato). Evitar.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad","Porfiria aguda intermitente","Antecedente de abuso de sustancias"],
  ea=["Somnolencia marcada","Mareo","Cefalea","Taquicardia","Hipotensión ortostática","⚠️ Dependencia y abstinencia (metabolito meprobamato)","⚠️ Abuso potencial: sustancia controlada en muchos países"],
  ix=["Depresores del SNC/opioides: depresión respiratoria","Alcohol: potenciación sedante peligrosa","CYP2C19 inhibidores: aumentan niveles de meprobamato"],
  ce=["⚠️ Potencial de abuso y dependencia (regulado/controlado)","Uso estrictamente a corto plazo (2-3 semanas)","No suspender bruscamente tras uso prolongado","Metabolito meprobamato tiene propiedades ansiolíticas","Vigilar signos de abuso o dependencia","No conducir"],
  emb="C"),

M("aine","metaxalona","Metaxalona","Metaxalona",["Skelaxin","Metaxall"],
  "Relajante muscular de acción central (oxazolidinona)",
  "Derivado de oxazolidinona con acción central. El mecanismo exacto no está completamente elucidado pero se cree que deprime la transmisión polisináptica en la médula espinal. Menor sedación que otros relajantes musculares.",
  ["Espasmo muscular agudo","Dolor musculoesquelético con contractura","Complemento a reposo y fisioterapia"],
  ["oral"],
  {"adulto":"800 mg c/6-8h con alimentos"},
  ["Comprimidos 400, 800 mg"],
  "Se desconoce excreción. Precaución.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad","Anemia hemolítica","Insuficiencia hepática o renal significativa"],
  ea=["Somnolencia (menos que otros relajantes)","Mareo","Cefalea","Náuseas","Irritabilidad","Anemia hemolítica (raro)"],
  ix=["Depresores del SNC: sedación aditiva","Alcohol: potencia efectos","La absorción aumenta significativamente con alimentos grasos"],
  ce=["Menor sedación que ciclobenzaprina o carisoprodol","Tomar con alimentos (mejora absorción)","Uso a corto plazo","Monitorizar hemograma si uso prolongado","Alternativa en pacientes que no toleran sedación de otros relajantes"],
  emb="C"),

M("aine","pridinol_muscular","Pridinol","Pridinol mesilato",["Lyseen","Myolastan Pridinol"],
  "Relajante muscular de acción central con efecto anticolinérgico",
  "Derivado piperidínico con acción anticolinérgica central y periférica. Actúa reduciendo el tono muscular por inhibición de reflejos polisinápticos espinales. Tiene propiedades anticolinérgicas y antihistamínicas adicionales.",
  ["Contracturas musculares dolorosas","Tortícolis","Lumbalgia con espasmo","Espasticidad de origen central"],
  ["oral","IM","IV"],
  {"adulto":"Oral: 4-8 mg/día dividido en 2-3 dosis. IM/IV: 2-4 mg/dosis. Máx 12 mg/día"},
  ["Comprimidos 4 mg","Ampollas 2 mg/mL (2 mL)"],
  "Se desconoce excreción. Precaución.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad","Glaucoma de ángulo cerrado","Retención urinaria","Hipertrofia prostática severa","Miastenia gravis"],
  ea=["Sequedad bucal","Somnolencia","Visión borrosa","Retención urinaria","Taquicardia","Estreñimiento","Mareo"],
  ix=["Anticolinérgicos: efectos aditivos","Depresores del SNC: sedación aditiva","Levodopa: puede reducir eficacia"],
  ce=["Precaución en ancianos (efectos anticolinérgicos)","Vigilar retención urinaria en prostáticos","Administrar IV lento","Complementar con fisioterapia","Puede causar sequedad bucal intensa"],
  pp={"dilucion":"Puede administrarse directo IM o IV lento","velocidadAdministracion":"IV: administrar lentamente en 2-3 min","estabilidad":"Usar inmediatamente"},
  emb="C"),

M("aine","eperisona","Eperisona","Clorhidrato de eperisona",["Myonal","Epry"],
  "Relajante muscular de acción central y vasodilatador",
  "Derivado de la propiopenona con acción dual: relajación muscular por inhibición de reflejos espinales y efecto vasodilatador que mejora la circulación en músculo espástico. Bloquea canales de Na+ y Ca2+. Menor sedación que otros relajantes.",
  ["Espasticidad por enfermedades cerebrovasculares","Mielopatía cervical","Contractura muscular dolorosa","Lumbalgia y cervicalgia","Parálisis espástica"],
  ["oral"],
  {"adulto":"50-150 mg/día dividido en 3 dosis, después de las comidas"},
  ["Comprimidos 50 mg"],
  "Se desconoce excreción. Precaución.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad"],
  ea=["Mareo","Somnolencia (leve)","Náuseas","Molestias GI","Rash","Insomnio","Cefalea","Elevación de transaminasas (raro)"],
  ix=["Depresores del SNC: pueden potenciar efectos","Baclofeno: efecto relajante aditivo"],
  ce=["Menor sedación que otros relajantes musculares (ventaja)","Efecto vasodilatador adicional mejora perfusión muscular","Tomar después de las comidas","Popular en Japón y Latinoamérica","Puede causar hipotensión leve en dosis altas"],
  emb="C"),

M("aine","tiocolchicosido","Tiocolchicósido","Tiocolchicósido",["Muscoril","Miorel","Coltrax"],
  "Relajante muscular derivado de la colchicina",
  "Derivado semisintético de la colchicina con acción agonista GABA-A y glicinérgica. Actúa como relajante muscular por modulación de la neurotransmisión inhibitoria espinal. También tiene propiedades antiinflamatorias y analgésicas.",
  ["Contracturas musculares dolorosas","Lumbalgia aguda","Cervicalgia","Tortícolis","Complemento en rehabilitación"],
  ["oral","IM"],
  {"adulto":"Oral: 4-8 mg c/12h. Máx 7 días consecutivos (oral). IM: 4 mg c/12h x 5 días máx",
   "pediatrico":"No recomendado en menores de 16 años"},
  ["Cápsulas 4 mg","Ampollas 4 mg/2mL"],
  "Evitar durante lactancia.","u08","c08_02",
  familia="Relajantes musculares",
  ci=["Hipersensibilidad","Embarazo y lactancia","Mujeres en edad fértil sin anticoncepción","Parálisis fláccida"],
  ea=["Diarrea","Dolor abdominal","Náuseas","Somnolencia","Reacciones alérgicas","⚠️ EMA restringió uso: máx 7 días oral, por riesgo de aneuploidía"],
  ix=["Depresores del SNC: sedación aditiva","Colchicina: no combinar (estructura relacionada)"],
  ce=["⚠️ Máximo 7 días de uso oral (restricción EMA 2013)","⚠️ Contraindicado en mujeres en edad fértil sin anticoncepción","Inyección IM profunda en cuadrante superior externo del glúteo","Muy utilizado en Latinoamérica y Europa","Complementar siempre con fisioterapia"],
  pp={"dilucion":"Administrar directo IM. No administrar IV","velocidadAdministracion":"IM profunda, lenta","estabilidad":"Usar inmediatamente tras abrir ampolla"},
  emb="X"),

# ══════════════════════════════════════════════════════════════
# c08_03 Antigotosos (+6)
# ══════════════════════════════════════════════════════════════
M("aine","probenecid","Probenecid","Probenecid",["Benemid","Probalan"],
  "Uricosúrico inhibidor de la reabsorción tubular de ácido úrico",
  "Inhibe el transportador URAT1 en el túbulo proximal renal, bloqueando la reabsorción de ácido úrico y aumentando su excreción urinaria. También inhibe la secreción tubular de penicilinas y cefalosporinas (uso como potenciador).",
  ["Gota crónica (hiperuricemia con subexcreción de urato)","Potenciador de niveles de penicilina/cefalosporinas","Hiperuricemia en pacientes sin litiasis renal"],
  ["oral"],
  {"adulto":"Gota: 250 mg c/12h x 1 sem, luego 500 mg c/12h. Máx 2-3 g/día. Potenciador ATB: 500 mg c/6h"},
  ["Comprimidos 500 mg"],
  "Compatible probablemente.","u08","c08_03",
  familia="Antigotosos (uricosúricos)",
  ci=["Litiasis renal por ácido úrico","Hiperuricemia por sobreproducción (no por subexcreción)","Ataque de gota agudo (no iniciar durante crisis)","Menores de 2 años","Insuficiencia renal (ClCr <50)","Uso con aspirina (antagoniza efecto)"],
  ea=["Cefalea","Náuseas y vómitos","Exacerbación de gota al inicio","Litiasis renal (si hidratación inadecuada)","Reacciones de hipersensibilidad","Anemia aplásica (raro)"],
  ix=["Aspirina: antagoniza efecto uricosúrico","Penicilinas/cefalosporinas: aumenta niveles séricos","Metotrexato: aumenta toxicidad (reduce excreción)","AINEs: aumenta niveles de indometacina y naproxeno"],
  ce=["Hidratar abundantemente (≥2L/día) para prevenir litiasis","Alcalinizar orina si uricosuria alta (bicarbonato)","No iniciar durante ataque agudo de gota","Usar con colchicina profiláctica al inicio","Verificar excreción urinaria de ácido úrico antes de prescribir (solo útil en subexcretores)"],
  emb="B"),

M("aine","rasburicasa","Rasburicasa","Rasburicasa",["Elitek","Fasturtec"],
  "Urato oxidasa recombinante",
  "Enzima urato oxidasa recombinante producida en Saccharomyces cerevisiae. Convierte el ácido úrico en alantoína, un metabolito soluble y fácilmente excretable. Reduce los niveles de ácido úrico de forma rápida y drástica.",
  ["Prevención y tratamiento de hiperuricemia en síndrome de lisis tumoral","Hiperuricemia severa en quimioterapia de neoplasias hematológicas"],
  ["IV"],
  {"adulto":"0.2 mg/kg IV en 30 min, dosis única o diaria x 5-7 días según respuesta",
   "pediatrico":"0.2 mg/kg IV en 30 min x hasta 5 días"},
  ["Vial 1.5, 7.5 mg polvo liofilizado"],
  "No recomendado.","u08","c08_03",
  familia="Antigotosos (urato oxidasa)",
  ci=["Deficiencia de G6PD (⚠️ hemólisis severa)","Antecedente de anafilaxia a rasburicasa","Metahemoglobinemia"],
  ea=["Náuseas","Vómitos","Fiebre","Cefalea","⚠️ Anafilaxia (anticuerpos anti-rasburicasa)","⚠️ Hemólisis en deficiencia G6PD","Metahemoglobinemia","Reacciones infusionales"],
  ix=["Alopurinol: no necesario co-administrar (mecanismo diferente y superior)","Muestra de ácido úrico: la enzima degrada urato in vitro en el tubo de sangre"],
  ce=["⚠️ OBLIGATORIO descartar deficiencia de G6PD antes de administrar","Muestra de ácido úrico: recoger en tubo frío y analizar en <4h (la enzima sigue actuando in vitro)","Premedicación con antihistamínicos y corticoides","Monitorizar signos de anafilaxia durante infusión","Mucho más potente que alopurinol para reducción rápida de urato"],
  pp={"reconstitucion":"Reconstituir con diluyente proporcionado. No agitar","dilucion":"Diluir en 50 mL SF 0.9%","velocidadAdministracion":"Infundir en 30 min","estabilidad":"Usar dentro de 24h refrigerado. No congelar"},
  emb="C"),

M("aine","pegloticase","Pegloticasa","Pegloticasa",["Krystexxa"],
  "Uricasa porcina pegilada",
  "Urato oxidasa recombinante porcina conjugada con PEG (pegilada) para prolongar vida media. Convierte ácido úrico en alantoína. Indicada en gota tofácea crónica refractaria a tratamiento convencional.",
  ["Gota crónica refractaria con depósitos tofáceos","Fracaso o intolerancia a alopurinol y febuxostat"],
  ["IV"],
  {"adulto":"8 mg IV cada 2 semanas en infusión de 2 horas mínimo"},
  ["Vial 8 mg/mL (2 mL)"],
  "No recomendado.","u08","c08_03",
  familia="Antigotosos (uricasa pegilada)",
  ci=["Deficiencia de G6PD","IC descompensada","Hipersensibilidad"],
  ea=["Reacciones infusionales (frecuentes)","Exacerbaciones de gota al inicio","Náuseas","Equimosis","Dolor torácico","⚠️ Anafilaxia","⚠️ Pérdida de respuesta por anticuerpos anti-PEG"],
  ix=["Alopurinol/febuxostat: suspender antes de iniciar (enmascaran pérdida de respuesta)","Metotrexato: puede reducir inmunogenicidad (en investigación)"],
  ce=["Reservar para gota refractaria severa con tofos","Premedicación obligatoria: antihistamínicos + corticoides + paracetamol","Monitorizar ácido úrico pre-infusión: si >6 mg/dL, suspender (indica anticuerpos)","Administrar en entorno con equipo de reanimación","Suspender hipouricemiantes orales antes de iniciar"],
  pp={"dilucion":"Diluir en 250 mL SF 0.9%","velocidadAdministracion":"Infundir en mínimo 2 horas (no menos)","estabilidad":"4h a TA tras dilución"},
  emb="C"),

M("aine","benzbromarona","Benzbromarona","Benzbromarona",["Desuric","Urinorm"],
  "Uricosúrico potente inhibidor de URAT1",
  "Potente inhibidor del transportador URAT1 y otros transportadores de urato en el túbulo proximal renal. Aumenta la excreción renal de ácido úrico. Mayor potencia uricosúrica que probenecid. Retirado en algunos países por hepatotoxicidad.",
  ["Gota crónica con hiperuricemia","Hiperuricemia refractaria a alopurinol","Pacientes con insuficiencia renal leve-moderada (más eficaz que probenecid)"],
  ["oral"],
  {"adulto":"Inicio: 25-50 mg/día, aumentar a 100-200 mg/día. Dosis habitual: 100 mg/día"},
  ["Comprimidos 50, 100 mg"],
  "Se desconoce excreción. Precaución.","u08","c08_03",
  familia="Antigotosos (uricosúricos)",
  ci=["Litiasis renal por ácido úrico","Insuficiencia hepática","Insuficiencia renal severa (ClCr <20)","Hiperuricemia por sobreproducción","Hipersensibilidad"],
  ea=["Diarrea","Náuseas","Exacerbación de gota al inicio","⚠️ Hepatotoxicidad grave (incluyendo necrosis hepática fulminante)","Litiasis renal","Elevación de transaminasas"],
  ix=["Aspirina: antagoniza efecto uricosúrico","Warfarina: puede potenciar anticoagulación","Azatioprina: aumenta toxicidad (inhibe metabolismo de 6-mercaptopurina)"],
  ce=["⚠️ Función hepática: ALT/AST basal y periódica (riesgo hepatotoxicidad)","Hidratar ≥2L/día","Retirado en varios países por hepatotoxicidad","Más potente que probenecid","Funciona mejor que probenecid en insuficiencia renal leve-moderada","Suspender ante elevación de transaminasas"],
  emb="C"),

M("aine","lesinurad","Lesinurad","Lesinurad",["Zurampic","Duzallo (combo con alopurinol)"],
  "Inhibidor selectivo de URAT1 y OAT4",
  "Inhibe selectivamente los transportadores URAT1 y OAT4 en el túbulo proximal renal, aumentando la excreción de ácido úrico. Diseñado como terapia complementaria a inhibidores de xantina oxidasa. No usar en monoterapia.",
  ["Hiperuricemia asociada a gota no controlada con inhibidor de xantina oxidasa solo","Terapia combinada con alopurinol o febuxostat"],
  ["oral"],
  {"adulto":"200 mg/día por la mañana con alimentos y agua, SIEMPRE con un inhibidor de xantina oxidasa"},
  ["Comprimidos 200 mg","Comp combinado Duzallo (lesinurad 200/alopurinol 200 o 300 mg)"],
  "No recomendado.","u08","c08_03",
  familia="Antigotosos (uricosúricos selectivos)",
  ci=["Monoterapia sin inhibidor de xantina oxidasa (⚠️ riesgo de IRA)","Síndrome de lisis tumoral","Insuficiencia renal severa (ClCr <30)","Trasplante renal"],
  ea=["Cefalea","ERGE","Exacerbación de gota al inicio","⚠️ Insuficiencia renal aguda (especialmente en monoterapia)","Elevación de creatinina"],
  ix=["Inhibidores de xantina oxidasa: uso combinado obligatorio","Aspirina >325 mg: reduce eficacia","Inductores CYP2C9: pueden reducir niveles"],
  ce=["⚠️ NUNCA usar en monoterapia (riesgo de IRA)","Siempre combinar con alopurinol o febuxostat","Tomar por la mañana con alimentos y abundante agua","Monitorizar función renal periódicamente","Hidratar adecuadamente"],
  emb="C"),

M("aine","sulfinpirazona","Sulfinpirazona","Sulfinpirazona",["Anturane"],
  "Uricosúrico derivado de pirazolona con efecto antiagregante",
  "Derivado de fenilbutazona con potente efecto uricosúrico por inhibición de reabsorción tubular de ácido úrico (URAT1). También tiene efecto antiagregante plaquetario por inhibición de COX plaquetaria y del tromboxano.",
  ["Gota crónica (reducción de uricemia)","Hiperuricemia con subexcreción renal de urato","Profilaxis de eventos trombóticos (uso histórico)"],
  ["oral"],
  {"adulto":"Inicio: 100-200 mg/día con alimentos. Aumento gradual: 200-400 mg c/12h. Máx 800 mg/día"},
  ["Comprimidos 100, 200 mg"],
  "Se desconoce excreción. Precaución.","u08","c08_03",
  familia="Antigotosos (uricosúricos)",
  ci=["Úlcera GI activa","Litiasis renal","Hipersensibilidad a pirazolonas","Insuficiencia renal severa","Discrasias sanguíneas"],
  ea=["Molestias GI (náuseas, dolor abdominal)","Exacerbación de gota al inicio","Úlcera péptica","Nefrolitiasis","Retención hídrica","Discrasias sanguíneas (raro)"],
  ix=["Aspirina: antagoniza efecto uricosúrico","Warfarina: potencia anticoagulación","Sulfonilureas: hipoglucemia","AINEs: mayor riesgo GI"],
  ce=["Tomar con alimentos para reducir irritación GI","Hidratar ≥2L/día y alcalinizar orina","Profilaxis con colchicina al inicio","Menos usado actualmente (alopurinol/febuxostat preferidos)","Monitorizar hemograma y función renal"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c08_04 Inmunosupresores (+8)
# ══════════════════════════════════════════════════════════════
M("inmunosupresor","sarilumab","Sarilumab","Sarilumab",["Kevzara"],
  "Anti-IL-6R (anticuerpo monoclonal humano)",
  "Anticuerpo monoclonal humano IgG1 dirigido contra el receptor de IL-6 (IL-6Rα). Bloquea la señalización de IL-6, una citoquina proinflamatoria clave en la artritis reumatoide. Alternativa a tocilizumab.",
  ["Artritis reumatoide moderada a severa (con respuesta inadecuada a FAMEs)","En combinación con metotrexato o en monoterapia si MTX no tolerado"],
  ["SC"],
  {"adulto":"200 mg SC cada 2 semanas. Reducir a 150 mg si neutropenia, trombocitopenia o elevación transaminasas"},
  ["Jeringa precargada 150, 200 mg","Pluma precargada 150, 200 mg"],
  "Se desconoce excreción en leche. No recomendado.","u08","c08_04",
  ea=["Neutropenia","Elevación de transaminasas","Infecciones respiratorias","Hipercolesterolemia","Reacción en sitio de inyección","Trombocitopenia","⚠️ Perforación GI (raro, mayor riesgo con diverticulosis)","⚠️ Reactivación de TB latente"],
  ce=["Hemograma a las 4-8 semanas de inicio, luego c/3 meses","Perfil hepático y lipídico periódico","Cribado TB obligatorio antes de iniciar","No iniciar si neutrófilos <2000/mm³","Puede usarse en monoterapia (ventaja sobre otros biológicos)","Educar en autoinyección SC","Rotar sitios de inyección"]),

M("inmunosupresor","guselkumab","Guselkumab","Guselkumab",["Tremfya"],
  "Anti-IL-23p19 (anticuerpo monoclonal humano)",
  "Anticuerpo monoclonal IgG1λ humano que se une selectivamente a la subunidad p19 de la IL-23, bloqueando su interacción con el receptor. Inhibe la vía Th17 sin afectar IL-12 (diferencia con ustekinumab que bloquea p40 común).",
  ["Artritis psoriásica","Psoriasis en placas moderada a severa"],
  ["SC"],
  {"adulto":"Artritis psoriásica: 100 mg SC semanas 0, 4, luego c/8 semanas. Psoriasis: 100 mg SC semanas 0, 4, luego c/8 semanas"},
  ["Jeringa precargada 100 mg/mL","Pluma precargada 100 mg/mL"],
  "Se desconoce excreción. Precaución.","u08","c08_04",
  ea=["Infecciones respiratorias superiores","Cefalea","Reacción en sitio de inyección","Artralgia","Diarrea","Gastroenteritis","Tinea (infecciones fúngicas)"],
  ce=["Cribado TB antes de iniciar","Perfil de seguridad favorable comparado con anti-TNF","Dosificación c/8 semanas (conveniente)","Educar en autoinyección","Almacenar refrigerado (2-8°C)","No agitar"]),

M("inmunosupresor","risankizumab_reum","Risankizumab","Risankizumab",["Skyrizi"],
  "Anti-IL-23p19 (anticuerpo monoclonal humanizado)",
  "Anticuerpo monoclonal humanizado IgG1 dirigido contra la subunidad p19 de IL-23. Bloquea selectivamente IL-23 sin afectar IL-12. Inhibe diferenciación y activación de células Th17.",
  ["Artritis psoriásica","Psoriasis en placas moderada a severa","Enfermedad de Crohn (indicación en expansión)"],
  ["SC"],
  {"adulto":"Artritis psoriásica: 150 mg SC semanas 0, 4, luego c/12 semanas. Psoriasis: 150 mg SC semanas 0, 4, luego c/12 semanas"},
  ["Jeringa precargada 75 mg/0.83 mL","Pluma precargada 150 mg/mL"],
  "Se desconoce excreción. Precaución.","u08","c08_04",
  ea=["Infecciones respiratorias superiores","Cefalea","Fatiga","Reacción en sitio de inyección","Tinea","Infección urinaria"],
  ce=["Dosificación c/12 semanas tras inducción (muy conveniente)","Cribado TB antes de iniciar","Buen perfil de seguridad a largo plazo","Educar en autoinyección","Almacenar refrigerado (2-8°C)"]),

M("inmunosupresor","brodalumab","Brodalumab","Brodalumab",["Siliq","Kyntheum"],
  "Anti-IL-17RA (anticuerpo monoclonal humano)",
  "Anticuerpo monoclonal humano IgG2 que bloquea el receptor A de IL-17 (IL-17RA), inhibiendo la señalización de IL-17A, IL-17F, IL-17C, IL-17E y IL-25. Bloqueo más amplio de la vía IL-17 que los anti-IL-17A.",
  ["Psoriasis en placas moderada a severa refractaria a otros biológicos","Artritis psoriásica (en algunos países)"],
  ["SC"],
  {"adulto":"210 mg SC semanas 0, 1, 2, luego c/2 semanas"},
  ["Jeringa precargada 210 mg/1.5 mL"],
  "No recomendado.","u08","c08_04",
  ci=["Hipersensibilidad","Enfermedad de Crohn activa","Infección activa grave","Ideación suicida activa"],
  ea=["Artralgia","Cefalea","Fatiga","Diarrea","Orofaringitis","Náuseas","Candidiasis mucocutánea","⚠️ Ideación y conducta suicida (boxed warning FDA)","⚠️ Exacerbación o aparición de enfermedad de Crohn"],
  ix=["Vacunas vivas: contraindicadas","Sustratos CYP450: la IL-17 puede afectar metabolismo (monitorizar)"],
  ce=["⚠️ Boxed warning: riesgo de ideación suicida (programa REMS)","Evaluar salud mental antes de iniciar y durante tratamiento","Contraindicado en enfermedad de Crohn","Cribado TB antes de iniciar","Solo disponible con programa restringido en algunos países","Educar al paciente sobre buscar ayuda ante síntomas depresivos"]),

M("inmunosupresor","filgotinib_reum","Filgotinib","Filgotinib",["Jyseleca"],
  "Inhibidor selectivo de JAK1 (pequeña molécula)",
  "Inhibidor selectivo de Janus quinasa 1 (JAK1) con alta selectividad sobre JAK2, JAK3 y TYK2. Bloquea la señalización de múltiples citoquinas proinflamatorias (IL-6, IFN, etc.) mediada por JAK1-STAT.",
  ["Artritis reumatoide moderada a severa con respuesta inadecuada a FAMEs","Colitis ulcerosa (en algunos países)"],
  ["oral"],
  {"adulto":"200 mg/día oral. 100 mg/día si ClCr 30-60 o con inhibidores potentes de CYP3A4/P-gp",
   "ajusteRenal":"100 mg/día si ClCr 30-60. No usar si ClCr <30"},
  ["Comprimidos 100, 200 mg"],
  "No recomendado.","u08","c08_04",
  ci=["Hipersensibilidad","Embarazo","Infección activa grave","Linfocitos <500/mm³","Neutrófilos <1000/mm³","Hemoglobina <8 g/dL"],
  ea=["Náuseas","Infecciones respiratorias","Cefalea","Mareo","Hipercolesterolemia","Linfopenia","⚠️ Herpes zóster","⚠️ Riesgo TEV (advertencia de clase JAKi)","⚠️ Eventos cardiovasculares mayores (advertencia de clase)"],
  ix=["Inhibidores potentes CYP3A4/P-gp: reducir dosis a 100 mg","Vacunas vivas: contraindicadas","Otros inmunosupresores potentes: no combinar"],
  ce=["No aprobado en EE.UU. (preocupación sobre espermatogénesis a dosis altas)","Hemograma basal y periódico","Cribado TB y hepatitis antes de iniciar","Vacunación contra herpes zóster antes de iniciar (Shingrix)","Monitorizar perfil lipídico"],
  emb="X"),

M("inmunosupresor","upadacitinib","Upadacitinib","Upadacitinib",["Rinvoq"],
  "Inhibidor selectivo de JAK1 (pequeña molécula)",
  "Inhibidor selectivo y reversible de JAK1 con mayor selectividad que tofacitinib y baricitinib. Bloquea la señalización intracelular de múltiples citoquinas implicadas en inflamación articular.",
  ["Artritis reumatoide moderada a severa","Artritis psoriásica","Espondilitis anquilosante","Dermatitis atópica moderada a severa","Colitis ulcerosa","Enfermedad de Crohn"],
  ["oral"],
  {"adulto":"AR/APs/EA: 15 mg/día. Dermatitis atópica: 15-30 mg/día. CU: inducción 45 mg/día x 8 sem, mantenimiento 15-30 mg/día",
   "geriatrico":">65 años: considerar riesgo/beneficio por advertencias de clase JAKi"},
  ["Comprimidos LP 15, 30, 45 mg"],
  "No recomendado.","u08","c08_04",
  ci=["Hipersensibilidad","Infección activa grave","Embarazo","Insuficiencia hepática severa","Linfocitos <500/mm³","Neutrófilos <1000/mm³"],
  ea=["Infecciones respiratorias","Acné","Hipercolesterolemia","Elevación CPK","Náuseas","⚠️ Herpes zóster","⚠️ TEV (advertencia de clase JAKi)","⚠️ MACE y neoplasias (advertencia FDA en >50 años)"],
  ix=["Inhibidores potentes CYP3A4: no combinar con dosis 45 mg","Vacunas vivas: contraindicadas","Otros JAKi o biológicos: no combinar"],
  ce=["⚠️ Boxed warning FDA: mayor riesgo de MACE, TEV, neoplasias y mortalidad en >50 años con FR CV (estudio ORAL Surveillance extrapolado)","Hemograma, perfil hepático y lipídico basales y periódicos","Cribado TB y hepatitis viral","Vacunación herpes zóster (Shingrix) antes de iniciar","No triturar comprimidos (liberación prolongada)"],
  emb="X"),

M("inmunosupresor","deucravacitinib","Deucravacitinib","Deucravacitinib",["Sotyktu"],
  "Inhibidor selectivo de TYK2 (primera en su clase)",
  "Primer inhibidor selectivo alostérico de tirosina quinasa 2 (TYK2). Se une al dominio regulador (pseudoquinasa) de TYK2, no al sitio catalítico, lo que confiere alta selectividad sobre JAK1, JAK2 y JAK3. Bloquea señalización de IL-23, IL-12, IFN tipo I.",
  ["Psoriasis en placas moderada a severa","Artritis psoriásica (en investigación)","Lupus eritematoso sistémico (en investigación)"],
  ["oral"],
  {"adulto":"6 mg/día oral, con o sin alimentos"},
  ["Comprimidos 6 mg"],
  "No recomendado.","u08","c08_04",
  ci=["Hipersensibilidad","Infección activa grave","Embarazo"],
  ea=["Infecciones respiratorias superiores","Acné","Foliculitis","Herpes simple oral","Úlceras orales","Elevación CPK","⚠️ Perfil de seguridad más favorable que JAK1/2/3i por selectividad TYK2"],
  ix=["Vacunas vivas: contraindicadas","Inmunosupresores potentes: precaución en combinación"],
  ce=["Primera en clase: inhibidor de TYK2 (mecanismo diferente a otros JAKi)","No aplican las advertencias de clase de JAK1/2 inhibidores (diferente selectividad)","No requiere monitorización hematológica estricta (diferencia con otros JAKi)","Cribado TB antes de iniciar","Eficacia oral comparable a biológicos anti-IL-23"],
  emb="X"),

M("inmunosupresor","anifrolumab","Anifrolumab","Anifrolumab",["Saphnelo"],
  "Anti-receptor de interferón tipo I (anticuerpo monoclonal humano)",
  "Anticuerpo monoclonal humano IgG1κ dirigido contra la subunidad 1 del receptor de interferón tipo I (IFNAR1). Bloquea la señalización de todos los interferones tipo I (IFNα, IFNβ, IFNω), que están hiperactivos en lupus eritematoso sistémico.",
  ["Lupus eritematoso sistémico moderado a severo (con tratamiento estándar)","Pacientes con firma de interferón positiva"],
  ["IV"],
  {"adulto":"300 mg IV cada 4 semanas en infusión de 30 min"},
  ["Vial 300 mg/2 mL"],
  "No recomendado.","u08","c08_04",
  ci=["Hipersensibilidad","Infección activa grave","Anafilaxia previa a anifrolumab"],
  ea=["Infecciones respiratorias","Herpes zóster","Reacciones infusionales","Bronquitis","Nasofaringitis","⚠️ Mayor susceptibilidad a infecciones por interferón bloqueado"],
  ix=["Vacunas vivas: contraindicadas","Otros biológicos: no estudiado en combinación"],
  ce=["Primer biológico anti-interferón para LES","Más eficaz en pacientes con firma de interferón alta","Premedicación con antihistamínico antes de infusión","Monitorizar durante infusión por reacciones","Vacunación herpes zóster antes de iniciar","Permite reducción de corticoides en LES"],
  pp={"dilucion":"Diluir 300 mg en 100 mL SF 0.9%","velocidadAdministracion":"Infundir en 30 min mínimo","estabilidad":"24h refrigerado tras dilución"},
  emb="X"),

# ══════════════════════════════════════════════════════════════
# c08_05 Fármacos para Osteoporosis y Osteoartritis (+8) NUEVO
# ══════════════════════════════════════════════════════════════
M("aine","tanezumab","Tanezumab","Tanezumab",["(No comercializado aún — en revisión regulatoria)"],
  "Anti-NGF (anticuerpo monoclonal humanizado)",
  "Anticuerpo monoclonal humanizado IgG2 dirigido contra el factor de crecimiento nervioso (NGF). Bloquea la unión de NGF a sus receptores TrkA y p75, reduciendo la sensibilización periférica al dolor. Mecanismo analgésico completamente diferente a AINEs y opioides.",
  ["Osteoartritis de rodilla o cadera con dolor moderado a severo refractario","Dolor lumbar crónico (en investigación)"],
  ["SC","IV"],
  {"adulto":"SC: 2.5-5 mg cada 8 semanas. IV: 2.5-5-10 mg cada 8 semanas según protocolo"},
  ["Jeringa precargada 2.5, 5 mg (SC)","Vial IV (en desarrollo)"],
  "No recomendado.","u08","c08_05",
  familia="Anticuerpos anti-NGF",
  ci=["Hipersensibilidad","Osteoartritis rápidamente progresiva","Necrosis ósea avascular","Fractura periarticular","Neuropatía periférica preexistente"],
  ea=["Parestesias","Hipoestesia","Artralgia","⚠️ Osteoartritis rápidamente progresiva (RPOA)","⚠️ Osteonecrosis","⚠️ Neuropatía periférica","Mayor tasa de artroplastia"],
  ix=["AINEs: combinación puede aumentar riesgo de RPOA (evitar si posible)","Opioides: puede usarse como alternativa"],
  ce=["⚠️ Riesgo de destrucción articular rápida (RPOA): radiografía basal y de seguimiento","⚠️ Estado regulatorio en revisión (FDA rechazó en 2021, en reconsideración)","Suspender si dolor articular nuevo o empeora","Mecanismo analgésico novedoso (no opioide, no AINE)","Derivar a ortopedia ante sospecha de RPOA"],
  emb="C"),

M("aine","diacereina","Diacereína","Diacereína",["Artrodar","Verboril"],
  "SYSADOA (fármaco sintomático de acción lenta para osteoartritis)",
  "Derivado de antraquinona con propiedades antiinflamatorias e inhibidoras de IL-1β. Reduce la degradación del cartílago al inhibir la producción y actividad de IL-1β, metaloproteasas y NO. Efecto lento (4-6 semanas) pero sostenido.",
  ["Osteoartritis de rodilla y cadera (tratamiento sintomático)","Pacientes con contraindicación o intolerancia a AINEs"],
  ["oral"],
  {"adulto":"50 mg c/12h con alimentos. Iniciar 50 mg/día x 2-4 semanas, luego 50 mg c/12h",
   "geriatrico":">65 años: iniciar 50 mg/día"},
  ["Cápsulas 50 mg"],
  "No recomendado.","u08","c08_05",
  familia="SYSADOA (fármacos de acción lenta para OA)",
  ci=["Hipersensibilidad","Enfermedad inflamatoria intestinal","Obstrucción intestinal","Insuficiencia hepática","Menores de 15 años"],
  ea=["Diarrea (muy frecuente, dosis-dependiente)","Dolor abdominal","Heces blandas","Coloración amarillenta de orina (benigno)","Hepatotoxicidad (raro)","Melanosis coli (uso crónico)"],
  ix=["Laxantes: efecto aditivo (diarrea)","Antibióticos: pueden exacerbar diarrea","Anticoagulantes: precaución (estructura antraquinónica)"],
  ce=["Inicio lento: efecto a las 4-6 semanas (advertir al paciente)","Iniciar con dosis baja para minimizar diarrea","Tomar con alimentos","Orina amarilla oscura es normal (no confundir con ictericia)","No usar como analgesia de rescate","EMA recomienda restringir uso y no usar en >65 años en algunos países"],
  emb="C"),

M("aine","condroitin_sulfato","Condroitín Sulfato","Condroitín sulfato",["Condrosan","Condrosulf","Structum"],
  "SYSADOA (fármaco sintomático de acción lenta para osteoartritis)",
  "Glucosaminoglucano sulfatado constituyente natural del cartílago articular. Inhibe enzimas degradativas (metaloproteasas, elastasa), estimula síntesis de proteoglicanos y ácido hialurónico, y tiene efecto antiinflamatorio leve al inhibir NF-κB y complemento.",
  ["Osteoartritis de rodilla y cadera (tratamiento sintomático)","Enlentecimiento de progresión radiológica de OA (evidencia controvertida)"],
  ["oral"],
  {"adulto":"800-1200 mg/día en 1-3 dosis. Formulación farmacéutica: 800 mg/día dosis única"},
  ["Cápsulas 400 mg","Sobres 800 mg","Comprimidos 800 mg"],
  "Compatible probablemente.","u08","c08_05",
  familia="SYSADOA (fármacos de acción lenta para OA)",
  ci=["Hipersensibilidad","Alergia a mariscos (algunas fuentes de condroitín)"],
  ea=["Molestias GI leves","Náuseas","Diarrea","Cefalea","Dolor abdominal","Muy buena tolerancia general"],
  ix=["Anticoagulantes orales: puede potenciar efecto (estructura similar a heparina)","Interacciones mínimas en general"],
  ce=["Efecto lento: mejoría a partir de 4-8 semanas","Distinguir formulación farmacéutica (regulada) de suplemento dietético (calidad variable)","La calidad del producto influye en eficacia (grado farmacéutico vs suplemento)","ESCEO/OARSI: grado farmacéutico tiene evidencia moderada","Precaución con anticoagulantes","Seguridad a largo plazo excelente"],
  emb="B"),

M("aine","glucosamina","Glucosamina","Sulfato de glucosamina",["Viartril-S","Dona","Xicil"],
  "SYSADOA (fármaco sintomático de acción lenta para osteoartritis)",
  "Aminomonosacárido natural precursor de los glucosaminoglucanos del cartílago articular. Estimula la síntesis de proteoglicanos por condrocitos, inhibe metaloproteasas y tiene efecto antiinflamatorio leve al reducir producción de prostaglandinas y NO.",
  ["Osteoartritis de rodilla (tratamiento sintomático)","Dolor articular asociado a degeneración cartilaginosa"],
  ["oral"],
  {"adulto":"Sulfato de glucosamina cristalino: 1500 mg/día dosis única o dividido en 3 dosis"},
  ["Sobres 1500 mg","Comprimidos 750 mg","Cápsulas 500 mg"],
  "Compatible probablemente.","u08","c08_05",
  familia="SYSADOA (fármacos de acción lenta para OA)",
  ci=["Hipersensibilidad","Alergia a mariscos (fuente habitual)","Diabetes mal controlada (puede afectar glucemia, controvertido)"],
  ea=["Molestias GI leves (náuseas, pirosis)","Diarrea","Estreñimiento","Cefalea","Somnolencia","Reacciones alérgicas en alérgicos a mariscos"],
  ix=["Warfarina: puede potenciar anticoagulación (monitorizar INR)","Antidiabéticos: monitorizar glucemia (efecto probablemente mínimo)"],
  ce=["Efecto lento: mejoría a partir de 4-8 semanas","Solo sulfato de glucosamina cristalino (Rotta) tiene evidencia positiva","Clorhidrato de glucosamina y suplementos: evidencia insuficiente","GAIT trial: resultados mixtos","Puede combinarse con condroitín sulfato","Seguridad a largo plazo excelente"],
  emb="B"),

M("aine","acido_hialuronico_ia","Ácido Hialurónico Intraarticular","Ácido hialurónico (hialuronato sódico)",
  ["Synvisc","Durolane","Hyalgan","Ostenil","Euflexxa"],
  "Viscosuplementación intraarticular",
  "Polisacárido natural de alto peso molecular componente del líquido sinovial. La inyección intraarticular restaura la viscoelasticidad del líquido sinovial (viscosuplementación), mejora la lubricación y amortiguación articular, y puede tener efecto antiinflamatorio local.",
  ["Osteoartritis de rodilla (cuando AINEs/fisioterapia son insuficientes)","Osteoartritis de cadera (según formulación)","Pacientes no candidatos a cirugía"],
  ["intraarticular"],
  {"adulto":"Depende de formulación: 1 inyección semanal x 3-5 semanas (bajo PM) o dosis única (alto PM cross-linked). Repetir ciclo a los 6 meses si necesario"},
  ["Jeringa precargada 2-6 mL según formulación"],
  "No aplica (administración local).","u08","c08_05",
  familia="Viscosuplementación",
  ci=["Infección articular o periarticular activa","Dermatopatía en sitio de inyección","Hipersensibilidad a hialuronato o productos aviares (según origen)","Artritis séptica"],
  ea=["Dolor e hinchazón articular post-inyección (transitorio, 24-48h)","Calor local","Derrame articular reactivo","Pseudogota (reacción inflamatoria aguda, raro)","Infección articular iatrogénica (raro)"],
  ix=["No hay interacciones sistémicas significativas","No inyectar con anestésicos locales en la misma jeringa (algunos)"],
  ce=["Procedimiento por médico entrenado bajo técnica estéril","Reposo articular 24-48h post-inyección","Aplicar hielo local si dolor post-inyección","Efecto máximo a las 4-8 semanas","Eficacia controvertida: AAOS no recomienda, OARSI condicionalmente","Alternativa cuando AINEs están contraindicados"],
  emb="B"),

M("aine","plasma_rico_plaquetas","Plasma Rico en Plaquetas (PRP)","Plasma rico en plaquetas autólogo",
  ["Autólogo (no marca comercial)","Kits: Arthrex ACP","Regen Lab RegenKit"],
  "Terapia biológica autóloga intraarticular",
  "Fracción plasmática autóloga con concentración plaquetaria suprafisiológica (3-5x). Las plaquetas liberan factores de crecimiento (PDGF, TGF-β, VEGF, IGF-1) que promueven reparación tisular, modulan inflamación y estimulan proliferación celular.",
  ["Osteoartritis de rodilla (evidencia moderada)","Tendinopatías crónicas (codo de tenista, fascitis plantar)","Lesiones musculares deportivas","Condropatía rotuliana"],
  ["intraarticular"],
  {"adulto":"1-3 inyecciones separadas por 2-4 semanas. Volumen: 3-8 mL según articulación. Puede repetirse cada 6-12 meses"},
  ["Producto autólogo obtenido por centrifugación de sangre del paciente"],
  "No aplica (producto autólogo).","u08","c08_05",
  familia="Terapias biológicas autólogas",
  ci=["Infección articular activa","Trombocitopenia severa","Neoplasia activa","Infección sistémica","Uso de anticoagulantes (relativa)"],
  ea=["Dolor post-inyección (frecuente, 24-72h)","Hinchazón local","Hematoma","Rigidez articular transitoria","Infección (muy raro con técnica correcta)"],
  ix=["AINEs: suspender 7 días antes del procedimiento (inhiben función plaquetaria)","Corticoides: suspender al menos 2 semanas antes","Anticoagulantes: valorar riesgo/beneficio"],
  ce=["Suspender AINEs 5-7 días antes del procedimiento","Procedimiento: extracción sangre venosa → centrifugación → inyección en la misma sesión","Técnica estéril estricta","No existe estandarización universal de protocolos","Evidencia creciente en OA de rodilla pero heterogénea","Reposo relativo 24-48h post-inyección","No cubierto por todos los sistemas de salud"],
  emb="C"),

M("aine","ranelato_estroncio","Ranelato de Estroncio","Ranelato de estroncio",["Protelos","Osseor"],
  "Fármaco dual para osteoporosis (formador y antirresortivo)",
  "Mecanismo dual: estimula la formación ósea por osteoblastos (vía receptor sensor de calcio CaSR) e inhibe la resorción ósea por osteoclastos. Aumenta la densidad mineral ósea de forma sustancial (incluye incorporación de estroncio al cristal óseo).",
  ["Osteoporosis postmenopáusica severa con alto riesgo de fractura","Solo cuando otros tratamientos están contraindicados o no tolerados (restricción EMA)"],
  ["oral"],
  {"adulto":"2 g/día en ayunas (disolver en agua). Tomar al acostarse, ≥2h después de la cena"},
  ["Sobres granulados 2 g"],
  "Contraindicado en lactancia.","u08","c08_05",
  familia="Fármacos para osteoporosis",
  ci=["⚠️ Cardiopatía isquémica, enfermedad arterial periférica o cerebrovascular establecida","⚠️ HTA no controlada","TEV actual o antecedente","Inmovilización temporal o permanente","Insuficiencia renal severa (ClCr <30)"],
  ea=["Náuseas","Diarrea","Cefalea","Dermatitis","⚠️ Aumento de riesgo cardiovascular (IAM)","⚠️ TEV (TVP, TEP)","⚠️ Síndrome DRESS (raro pero grave)","Elevación de CPK"],
  ix=["Alimentos, leche y calcio: reducen absorción (tomar en ayunas)","Tetraciclinas y quinolonas: quelación (separar ≥2h)"],
  ce=["⚠️ Restricciones EMA: solo para osteoporosis severa sin otras opciones","⚠️ Evaluación cardiovascular antes de iniciar y periódica","Suspender si evento CV o TEV","Tomar al acostarse con agua, ≥2h después de cenar","Interfiere con medición de DMO (estroncio pesa más que calcio)","Retirado del mercado en varios países (2017)","Suplementar calcio y vitamina D"],
  emb="X"),

M("inmunosupresor","romosozumab_musculo","Romosozumab","Romosozumab",["Evenity"],
  "Anti-esclerostina (anticuerpo monoclonal humanizado)",
  "Anticuerpo monoclonal humanizado que se une e inhibe la esclerostina, un inhibidor natural de la vía Wnt en los osteocitos. El bloqueo de esclerostina activa la formación ósea por osteoblastos y simultáneamente reduce la resorción ósea.",
  ["Osteoporosis postmenopáusica con alto riesgo de fractura","Mujeres con fractura osteoporótica reciente"],
  ["SC"],
  {"adulto":"210 mg SC una vez al mes (2 inyecciones de 105 mg) durante 12 meses. Luego continuar con antirresortivo (denosumab o bisfosfonato)"},
  ["Jeringa precargada 105 mg/1.17 mL"],
  "No recomendado.","u08","c08_05",
  ci=["Hipocalcemia no corregida","⚠️ IAM o ACV en el último año","⚠️ Alto riesgo cardiovascular","Hipersensibilidad"],
  ea=["Artralgia","Cefalea","Reacción en sitio de inyección","Dolor musculoesquelético","⚠️ Eventos cardiovasculares (IAM, ACV — boxed warning FDA)","Hipocalcemia","Osteonecrosis mandibular (raro)","Fractura femoral atípica (raro)"],
  ix=["No interacciones farmacológicas significativas conocidas","Suplementar calcio y vitamina D siempre"],
  ce=["⚠️ Boxed warning: aumento de riesgo cardiovascular (IAM, ACV)","No usar si IAM o ACV en el último año","Uso limitado a 12 meses (máximo efecto anabólico)","Tras 12 meses: transicionar a antirresortivo (denosumab o bisfosfonato)","Verificar calcio y vitamina D antes de iniciar","Más potente que teriparatida para formación ósea","Administración SC mensual (2 inyecciones en diferentes sitios)"],
  emb="X"),

# ══════════════════════════════════════════════════════════════
# c08_06 Miopatías y Distrofias (+8) NUEVO
# ══════════════════════════════════════════════════════════════
M("aine","ataluren","Ataluren","Ataluren",["Translarna"],
  "Modulador de lectura de codones de parada prematuros",
  "Molécula pequeña que permite al ribosoma leer a través de codones de parada prematuros (mutaciones nonsense) en el ARNm, produciendo proteína distrofina funcional completa. Solo eficaz en mutaciones nonsense (~10-15% de DMD).",
  ["Distrofia muscular de Duchenne con mutación nonsense en pacientes ambulatorios ≥2 años"],
  ["oral"],
  {"adulto":"No aplica (uso pediátrico)","pediatrico":"≥2 años: 10 mg/kg mañana + 10 mg/kg mediodía + 20 mg/kg noche (total 40 mg/kg/día) con alimentos"},
  ["Granulado para suspensión oral 125, 250, 1000 mg"],
  "No recomendado.","u08","c08_06",
  familia="Terapia de lectura de codones de parada (DMD)",
  ci=["Hipersensibilidad","Uso concomitante de aminoglucósidos IV (antagoniza mecanismo)","Mutaciones no-nonsense de distrofina"],
  ea=["Náuseas","Vómitos","Dolor abdominal","Disminución del apetito","Flatulencia","Cefalea","Hipertrigliceridemia","Elevación de CPK","Infecciones respiratorias"],
  ix=["⚠️ Aminoglucósidos IV: antagonizan mecanismo (contraindicado uso concomitante)","Aciclovir: ataluren puede reducir excreción renal","Anticonceptivos hormonales: ataluren puede reducir eficacia"],
  ce=["Solo eficaz en mutaciones nonsense (confirmar test genético)","Aprobado con autorización condicional en Europa (no aprobado FDA)","Mezclar granulado en líquido o alimento semisólido","Tomar con alimentos","Monitorizar función renal y perfil lipídico","Apoyo multidisciplinario esencial en DMD"],
  emb="C"),

M("aine","eteplirsen","Eteplirsen","Eteplirsen",["Exondys 51"],
  "Oligonucleótido antisentido para exón 51 de distrofina",
  "Oligonucleótido antisentido de morfolino fosforodiamidato (PMO) que induce el salto del exón 51 durante el splicing del ARNm de distrofina. Produce una distrofina truncada pero parcialmente funcional (fenotipo Becker). Aplicable al ~13% de pacientes DMD.",
  ["Distrofia muscular de Duchenne con mutación susceptible de salto de exón 51"],
  ["IV"],
  {"adulto":"No aplica (uso pediátrico)","pediatrico":"30 mg/kg IV semanal en infusión de 35-60 min"},
  ["Vial 100 mg/2 mL (50 mg/mL)","Vial 500 mg/10 mL"],
  "No recomendado.","u08","c08_06",
  familia="Terapia antisentido para distrofinopatías",
  ci=["Hipersensibilidad","Mutaciones no susceptibles de salto de exón 51"],
  ea=["Trastornos del equilibrio","Vómitos","Reacciones infusionales","Dolor en sitio de inyección","Exantema","Artralgia","⚠️ Nefrotoxicidad potencial (monitorizar proteína urinaria)"],
  ix=["No se conocen interacciones farmacológicas significativas","No se metaboliza por CYP450"],
  ce=["Confirmar mutación susceptible de salto exón 51 (test genético obligatorio)","Aprobado FDA por vía acelerada (controvertido: evidencia limitada)","Tratamiento de por vida","Infusión IV semanal","Monitorizar función renal y proteína urinaria","Apoyo multidisciplinario completo para DMD"],
  pp={"dilucion":"Diluir en SF 0.9% hasta volumen adecuado","velocidadAdministracion":"Infundir en 35-60 min","estabilidad":"4h a TA tras dilución"},
  emb="C"),

M("aine","golodirsen","Golodirsen","Golodirsen",["Vyondys 53"],
  "Oligonucleótido antisentido para exón 53 de distrofina",
  "Oligonucleótido antisentido de morfolino fosforodiamidato (PMO) que induce el salto del exón 53 durante el splicing del pre-ARNm de distrofina. Produce distrofina truncada funcional. Aplicable al ~8% de pacientes con DMD.",
  ["Distrofia muscular de Duchenne con mutación susceptible de salto de exón 53"],
  ["IV"],
  {"adulto":"No aplica (uso pediátrico)","pediatrico":"30 mg/kg IV semanal en infusión de 35-60 min"},
  ["Vial 100 mg/2 mL (50 mg/mL)"],
  "No recomendado.","u08","c08_06",
  familia="Terapia antisentido para distrofinopatías",
  ci=["Hipersensibilidad","Mutaciones no susceptibles de salto de exón 53"],
  ea=["Cefalea","Fiebre","Tos","Epistaxis","Dolor abdominal","⚠️ Nefrotoxicidad: daño tubular renal potencial"],
  ix=["No se conocen interacciones significativas","No metabolizado por CYP450"],
  ce=["Confirmar mutación susceptible de salto exón 53","Monitorizar función renal y proteína urinaria","Tratamiento semanal IV de por vida","Aprobado FDA por vía acelerada","Mismo mecanismo que eteplirsen pero diferente exón diana"],
  pp={"dilucion":"Diluir en SF 0.9%","velocidadAdministracion":"Infundir en 35-60 min","estabilidad":"4h a TA tras dilución"},
  emb="C"),

M("aine","casimersen","Casimersen","Casimersen",["Amondys 45"],
  "Oligonucleótido antisentido para exón 45 de distrofina",
  "Oligonucleótido antisentido PMO que induce el salto del exón 45 en el pre-ARNm de distrofina. Aplicable al ~8% de pacientes con DMD que tienen mutaciones susceptibles de salto de este exón.",
  ["Distrofia muscular de Duchenne con mutación susceptible de salto de exón 45"],
  ["IV"],
  {"adulto":"No aplica (uso pediátrico)","pediatrico":"30 mg/kg IV semanal en infusión de 35-60 min"},
  ["Vial 100 mg/2 mL (50 mg/mL)"],
  "No recomendado.","u08","c08_06",
  familia="Terapia antisentido para distrofinopatías",
  ci=["Hipersensibilidad","Mutaciones no susceptibles de salto de exón 45"],
  ea=["Infecciones respiratorias superiores","Tos","Fiebre","Cefalea","Artralgia","Dolor orofaríngeo","⚠️ Nefrotoxicidad potencial"],
  ix=["No se conocen interacciones significativas"],
  ce=["Confirmar mutación susceptible de salto exón 45","Monitorizar función renal y proteína urinaria","Tratamiento IV semanal de por vida","Aprobado FDA por vía acelerada","Familia de PMOs: eteplirsen (ex51), golodirsen (ex53), casimersen (ex45), viltolarsen (ex53)"],
  pp={"dilucion":"Diluir en SF 0.9%","velocidadAdministracion":"Infundir en 35-60 min","estabilidad":"4h a TA tras dilución"},
  emb="C"),

M("aine","viltolarsen","Viltolarsen","Viltolarsen",["Viltepso"],
  "Oligonucleótido antisentido para exón 53 de distrofina",
  "Oligonucleótido antisentido PMO de segunda generación que induce el salto del exón 53. Mismo exón diana que golodirsen pero con diferencias en secuencia y farmacocinética. Desarrollado en Japón con mayor producción de distrofina en estudios.",
  ["Distrofia muscular de Duchenne con mutación susceptible de salto de exón 53"],
  ["IV"],
  {"adulto":"No aplica (uso pediátrico)","pediatrico":"80 mg/kg IV semanal en infusión de 60 min"},
  ["Vial 250 mg/5 mL (50 mg/mL)"],
  "No recomendado.","u08","c08_06",
  familia="Terapia antisentido para distrofinopatías",
  ci=["Hipersensibilidad","Mutaciones no susceptibles de salto de exón 53"],
  ea=["Reacciones infusionales","Tos","Fiebre","Reducción del apetito","Infección respiratoria superior","⚠️ Nefrotoxicidad potencial"],
  ix=["No se conocen interacciones significativas"],
  ce=["Confirmar mutación susceptible de salto exón 53","Dosis mayor que otros PMOs (80 mg/kg vs 30 mg/kg)","Monitorizar función renal","Tratamiento IV semanal de por vida","Aprobado FDA y Japón por vía acelerada"],
  pp={"dilucion":"Diluir en SF 0.9% hasta 100-150 mL","velocidadAdministracion":"Infundir en 60 min","estabilidad":"4h a TA tras dilución"},
  emb="C"),

M("aine","risdiplam","Risdiplam","Risdiplam",["Evrysdi"],
  "Modificador del splicing de SMN2 (molécula pequeña oral)",
  "Molécula pequeña oral que modifica el splicing del pre-ARNm del gen SMN2, aumentando la inclusión del exón 7 y la producción de proteína SMN funcional de longitud completa. Actúa tanto a nivel central como periférico. Alternativa oral a nusinersen.",
  ["Atrofia muscular espinal (AME) tipos 1, 2 y 3 en pacientes ≥2 meses"],
  ["oral"],
  {"adulto":"Adultos y ≥20 kg: 5 mg/día oral con alimentos",
   "pediatrico":"2 meses a <2 años: 0.2 mg/kg/día. ≥2 años y <20 kg: 0.25 mg/kg/día. ≥20 kg: 5 mg/día"},
  ["Solución oral 0.75 mg/mL (polvo para reconstituir)"],
  "No recomendado.","u08","c08_06",
  familia="Modificadores del splicing de SMN2",
  ci=["Hipersensibilidad","Embarazo (teratogénico en animales)"],
  ea=["Fiebre","Diarrea","Rash","Úlceras orales","Artralgia","Infecciones respiratorias","Infección urinaria"],
  ix=["No se conocen interacciones clínicamente significativas","No inhibidor ni inductor de CYP450 relevante"],
  ce=["Primera terapia oral para AME (ventaja sobre nusinersen intratecal)","Administrar con alimentos a la misma hora cada día","Si el paciente vomita: no re-dosificar, esperar siguiente dosis","Monitorizar función motora con escalas validadas","Anticoncepción eficaz obligatoria (mujeres y hombres: teratogénico)","Almacenar solución en refrigeración, usar en 64 días"],
  emb="X"),

M("corticoide_sistemico","deflazacort_dmd","Deflazacort","Deflazacort",["Emflaza","Calcort","Dezacor"],
  "Corticosteroide oxazolínico para DMD",
  "Corticosteroide derivado de la prednisolona con grupo oxazolínico. Reduce la inflamación y degradación muscular en DMD. Enlentece la pérdida de fuerza muscular y función ambulatoria. Único corticoide con indicación específica aprobada por FDA para DMD.",
  ["Distrofia muscular de Duchenne (≥2 años)","Enfermedades inflamatorias (indicaciones generales del corticoide)"],
  ["oral"],
  {"adulto":"Indicaciones antiinflamatorias: 6-90 mg/día según patología","pediatrico":"DMD: 0.9 mg/kg/día oral (equivale a prednisona 0.75 mg/kg/día). No superar 36 mg/día en niños"},
  ["Comprimidos 6, 18, 30, 36 mg","Suspensión oral 22.75 mg/mL"],
  "Se excreta en leche. Precaución.","u08","c08_06",
  ea=["Aumento de peso","Facies cushingoide","Retraso del crecimiento","Osteoporosis","Cataratas","Hiperglucemia","Hipertensión","Inmunosupresión","Fracturas vertebrales","⚠️ Supresión adrenal (no suspender bruscamente)"],
  ce=["Único corticoide con aprobación FDA específica para DMD","Equipotencia: 6 mg deflazacort = 5 mg prednisona","Menor aumento de peso que prednisona (ventaja en DMD)","Suplementar calcio + vitamina D siempre","Protección gástrica si riesgo","Monitorizar glucemia, TA, peso, talla y DMO","No suspender bruscamente (descenso gradual)","Control oftalmológico anual (cataratas)"]),

M("corticoide_sistemico","prednisona_dmd","Prednisona (DMD)","Prednisona",["Meticorten","Deltasone"],
  "Corticosteroide oral para distrofia muscular de Duchenne",
  "Corticosteroide sintético con potente acción antiinflamatoria e inmunosupresora. En DMD, reduce la inflamación muscular, enlentece la degradación de fibras y prolonga la capacidad ambulatoria. Pilar fundamental del tratamiento de DMD desde los años 90.",
  ["Distrofia muscular de Duchenne","Enfermedades inflamatorias y autoinmunes (múltiples indicaciones)"],
  ["oral"],
  {"adulto":"Variable según indicación: 5-60 mg/día","pediatrico":"DMD: 0.75 mg/kg/día oral (régimen diario) o 0.75 mg/kg/día 10 días sí/10 días no. Máx 30-40 mg/día"},
  ["Comprimidos 5, 10, 20, 50 mg","Solución oral 5 mg/5mL"],
  "Se excreta en leche. Precaución a dosis altas.","u08","c08_06",
  ea=["Aumento de peso (más que deflazacort)","Facies cushingoide","Retraso del crecimiento","Osteoporosis","Miopatía esteroidea","Hiperglucemia","HTA","Trastornos del comportamiento","⚠️ Fracturas vertebrales por compresión","⚠️ Supresión adrenal"],
  ce=["Pilar de tratamiento DMD: prolonga marcha 2-5 años","Mayor aumento de peso que deflazacort","Régimen intermitente (10 on/10 off) puede reducir efectos adversos","Suplementar calcio 1000 mg + vitamina D 800 UI diarios","Protección gástrica si riesgo","DEXA basal y anual","Control de talla, peso, TA y glucemia periódico","No suspender bruscamente"]),

# ══════════════════════════════════════════════════════════════
# c08_07 Analgésicos Tópicos y Locales (+8) NUEVO
# ══════════════════════════════════════════════════════════════
M("aine","diclofenaco_topico","Diclofenaco Tópico","Diclofenaco sódico/dietilamina tópico",
  ["Voltaren Emulgel","Voltadol","Flector"],
  "AINE tópico derivado del ácido fenilacético",
  "Inhibe COX-1 y COX-2 localmente tras penetración cutánea. Alcanza concentraciones terapéuticas en tejidos subyacentes (músculos, articulaciones superficiales, tendones) con mínima absorción sistémica (<5% de la dosis oral equivalente).",
  ["Dolor musculoesquelético localizado","Osteoartritis de articulaciones superficiales (rodilla, manos)","Esguinces y distensiones","Tendinitis","Contusiones deportivas"],
  ["topica"],
  {"adulto":"Gel 1-2%: aplicar 2-4 g sobre la zona afectada 3-4 veces/día. Parche: 1 parche c/12h sobre zona dolorosa. Máx 4 semanas"},
  ["Gel 1%, 2% (tubo 50, 100 g)","Emulgel 1.16%","Parche medicado 140 mg","Spray solución cutánea"],
  "Compatible (absorción sistémica mínima).","u08","c08_07",
  familia="AINEs tópicos",
  ci=["Hipersensibilidad a AINEs","Heridas abiertas o piel lesionada","Dermatitis o eczema en zona de aplicación","Tercer trimestre de embarazo"],
  ea=["Irritación cutánea local","Eritema","Prurito","Dermatitis de contacto","Sequedad cutánea","Fotosensibilidad local","Absorción sistémica mínima (efectos sistémicos raros)"],
  ix=["Mínimas interacciones sistémicas","Anticoagulantes: precaución teórica en aplicación extensa","Otros tópicos en misma zona: espaciar aplicación"],
  ce=["Aplicar sobre piel intacta y seca","No cubrir con vendaje oclusivo (salvo indicación)","Lavarse las manos después de aplicar (salvo si la zona tratada son las manos)","Eficaz en OA de rodilla y manos (evidencia buena)","Menor riesgo GI y renal que AINEs orales","Fotoprotección de la zona tratada","Preferir sobre AINEs orales en dolor localizado y en ancianos"],
  emb="C"),

M("aine","ketoprofeno_topico","Ketoprofeno Tópico","Ketoprofeno tópico",["Fastum Gel","Ketoprofen Gel"],
  "AINE tópico derivado del ácido propiónico",
  "Inhibidor no selectivo de COX aplicado tópicamente. Penetra tejidos superficiales alcanzando concentraciones analgésicas y antiinflamatorias locales. Absorción sistémica baja pero mayor que diclofenaco tópico.",
  ["Dolor musculoesquelético localizado","Contusiones y esguinces","Tendinitis","Bursitis superficiales"],
  ["topica"],
  {"adulto":"Gel 2.5%: aplicar 5-10 cm de gel sobre zona afectada 2-3 veces/día con masaje suave. Máx 2 semanas"},
  ["Gel 2.5% (tubo 30, 50, 100 g)"],
  "Compatible (absorción sistémica mínima).","u08","c08_07",
  familia="AINEs tópicos",
  ci=["Hipersensibilidad a ketoprofeno o AINEs","Antecedente de fotosensibilidad a ketoprofeno","Piel lesionada","Exposición solar de la zona tratada","Tercer trimestre de embarazo"],
  ea=["Eritema local","Dermatitis de contacto","⚠️ Fotosensibilidad severa (mayor que otros AINEs tópicos)","Prurito","Eczema de contacto","Reacciones fotoalérgicas graves"],
  ix=["Mínimas interacciones sistémicas","Filtros solares con octocrylene: reacción cruzada de fotosensibilidad"],
  ce=["⚠️ FOTOSENSIBILIDAD: evitar exposición solar de la zona tratada durante y 2 semanas después","Retirado de venta libre en Francia por reacciones fotoalérgicas","No aplicar bajo vendaje oclusivo","Lavarse las manos tras aplicación","Aplicar con masaje suave hasta absorción","No combinar con otros tópicos en la misma zona"],
  emb="C"),

M("aine","capsaicina_topica","Capsaicina Tópica","Capsaicina",["Capsidol","Zacin","Qutenza (parche 8%)"],
  "Agonista vanilloide TRPV1 tópico (rubefaciente)",
  "Agonista del receptor vanilloide TRPV1 en nociceptores C aferentes. La estimulación prolongada produce desensibilización y degeneración reversible de terminales nerviosas epidérmicas, reduciendo la transmisión del dolor. La sustancia P se depleta de los nociceptores.",
  ["Neuropatía diabética dolorosa","Neuralgia postherpética","Osteoartritis de articulaciones superficiales","Dolor neuropático periférico localizado"],
  ["topica"],
  {"adulto":"Crema 0.025-0.075%: aplicar 3-4 veces/día x mínimo 4-8 semanas. Parche 8% (Qutenza): aplicación única por profesional, repetir c/3 meses"},
  ["Crema 0.025%, 0.075% (tubo 30, 45 g)","Parche 8% (179 mg capsaicina — uso hospitalario)"],
  "Compatible probablemente.","u08","c08_07",
  familia="Analgésicos tópicos vanilloides",
  ci=["Hipersensibilidad","Piel lesionada o heridas abiertas","No aplicar en mucosas, ojos o genitales"],
  ea=["Ardor y quemazón local intensa (esperado, disminuye con uso regular)","Eritema","Dolor en sitio de aplicación","Estornudos y tos (si se inhala al aplicar)","⚠️ Parche 8%: dolor severo durante aplicación, requiere anestesia previa"],
  ix=["No se conocen interacciones sistémicas significativas","IECA: tos teórica (depleta sustancia P)"],
  ce=["El ardor INICIAL es esperado y disminuye con uso regular (1-2 semanas)","Aplicar con guantes (o lavar manos inmediatamente después)","No tocar ojos, nariz o mucosas después de aplicar","Uso regular mínimo 4 semanas para eficacia","Parche 8%: aplicación por profesional con anestesia tópica previa (lidocaína)","No calentar la zona tratada (aumenta absorción y ardor)","Educación clave: muchos abandonan por ardor antes de que el efecto aparezca"],
  emb="C"),

M("aine","lidocaina_parche","Lidocaína Parche Tópico","Lidocaína al 5% parche tópico",["Versatis","Lidoderm"],
  "Anestésico local tópico en parche",
  "Bloquea los canales de sodio dependientes de voltaje en los nociceptores dérmicos y subdérmicos, estabilizando las membranas neuronales e impidiendo la generación y conducción de impulsos nerviosos. Efecto local sin anestesia significativa.",
  ["Neuralgia postherpética","Dolor neuropático localizado","Dolor musculoesquelético localizado"],
  ["topica"],
  {"adulto":"Aplicar hasta 3 parches simultáneamente sobre la zona dolorosa. 12h con parche / 12h sin parche. No más de 3 parches a la vez"},
  ["Parche medicado 5% (10x14 cm, 700 mg lidocaína)"],
  "Compatible (absorción sistémica mínima <5%).","u08","c08_07",
  familia="Anestésicos locales tópicos",
  ci=["Hipersensibilidad a lidocaína o anestésicos tipo amida","Piel lesionada, inflamada o infectada en zona de aplicación"],
  ea=["Eritema local leve","Edema leve en sitio de aplicación","Prurito","Rash","Vesículas (raro)","Absorción sistémica mínima (toxicidad sistémica extremadamente rara)"],
  ix=["Otros anestésicos locales: toxicidad aditiva teórica si uso extenso","Antiarrítmicos clase I (lidocaína IV): precaución teórica en uso extenso"],
  ce=["Esquema 12h on / 12h off (no usar 24h continuas)","Máximo 3 parches simultáneamente","Se puede cortar el parche al tamaño necesario","Aplicar sobre piel intacta y seca","Primera línea en neuralgia postherpética","No produce anestesia notable: efecto analgésico sin dormirse la zona","Seguridad excelente en ancianos"],
  emb="B"),

M("aine","metilsalicilato","Metilsalicilato","Metilsalicilato",["Bengay","Icy Hot","Salonpas"],
  "Rubefaciente salicilato tópico (contrairritante)",
  "Salicilato tópico que produce contrairritación por estimulación de receptores cutáneos de calor y dolor. Penetra parcialmente a tejidos subyacentes donde tiene efecto antiinflamatorio local leve. Metabolizado a ácido salicílico tras absorción.",
  ["Dolor muscular y articular localizado","Lumbalgia leve","Contusiones deportivas","Dolor por ejercicio excesivo"],
  ["topica"],
  {"adulto":"Aplicar capa fina sobre zona afectada 3-4 veces/día con masaje suave. No cubrir con vendaje oclusivo ni fuente de calor",
   "pediatrico":"No usar en menores de 12 años"},
  ["Crema, gel, ungüento (múltiples concentraciones 10-30%)","Parche adhesivo medicado","Spray"],
  "Compatible en uso tópico localizado.","u08","c08_07",
  familia="Rubefacientes y contrairritantes",
  ci=["Hipersensibilidad a salicilatos o aspirina","Piel lesionada","Niños <12 años","No aplicar en áreas extensas"],
  ea=["Irritación cutánea local","Sensación de calor o ardor","Eritema","Dermatitis de contacto","⚠️ Toxicidad sistémica por salicilatos si absorción excesiva (aplicación extensa/oclusiva)","⚠️ Intoxicación potencialmente fatal en niños si ingestión accidental"],
  ix=["Anticoagulantes: precaución si uso extenso (absorción de salicilato)","Metotrexato: teórica si absorción sistémica"],
  ce=["⚠️ Mantener fuera del alcance de niños (ingestión accidental es peligrosa)","No aplicar con calor (parches térmicos, mantas eléctricas): aumenta absorción","No usar en áreas extensas ni bajo vendaje oclusivo","1 cucharadita de metilsalicilato = ~7 g de aspirina","Lavarse las manos tras aplicación","No combinar diferentes rubefacientes en la misma zona"],
  emb="C"),

M("aine","mentol_topico","Mentol Tópico","Mentol",["Biofreeze","Tiger Balm","Icy Hot (con mentol)"],
  "Rubefaciente/contrairritante tópico agonista TRPM8",
  "Agonista del receptor TRPM8 (receptor de frío) en terminales nerviosas cutáneas. Produce sensación de frescor y contrairritación que modula la percepción del dolor. También tiene efecto vasodilatador local leve. No tiene acción antiinflamatoria directa.",
  ["Dolor muscular leve","Dolor articular leve","Cefalea tensional (aplicación en sienes)","Prurito localizado","Irritación de garganta (pastillas)"],
  ["topica"],
  {"adulto":"Aplicar sobre zona dolorosa 3-4 veces/día. Concentraciones habituales 1-16% según formulación"},
  ["Gel, crema, spray (concentraciones 1-16%)","Parche adhesivo","Roll-on"],
  "Compatible en uso tópico.","u08","c08_07",
  familia="Rubefacientes y contrairritantes",
  ci=["Hipersensibilidad","Piel lesionada","No aplicar en mucosas o cerca de ojos","Menores de 2 años"],
  ea=["Sensación de frío intensa","Irritación cutánea","Eritema","Dermatitis de contacto (raro)","⚠️ Concentraciones >40% pueden causar quemaduras químicas"],
  ix=["No se conocen interacciones farmacológicas sistémicas significativas"],
  ce=["No aplicar con fuentes de calor ni vendaje oclusivo","Producción de frío: modula percepción del dolor (gate control)","Seguro en la mayoría de poblaciones","No sustituye tratamiento analgésico adecuado","Educación: alivio sintomático temporal","Amplio margen de seguridad en uso tópico convencional"],
  emb="B"),

M("aine","piroxicam_topico","Piroxicam Tópico","Piroxicam tópico",["Feldene Gel","Brexidol"],
  "AINE tópico del grupo oxicam",
  "Inhibidor no selectivo de COX-1 y COX-2 formulado para aplicación tópica. Penetra a tejidos subcutáneos, músculos y articulaciones superficiales. Absorción sistémica limitada (5-10% de la oral).",
  ["Dolor musculoesquelético localizado","Esguinces y distensiones","Tendinitis superficiales","Osteoartritis de articulaciones superficiales"],
  ["topica"],
  {"adulto":"Gel 0.5%: aplicar 1-3 g sobre zona afectada 3-4 veces/día con masaje suave"},
  ["Gel 0.5% (tubo 25, 50 g)"],
  "Compatible (absorción sistémica baja).","u08","c08_07",
  familia="AINEs tópicos",
  ci=["Hipersensibilidad a piroxicam u otros AINEs","Asma por AINEs","Piel lesionada o con eczema","Tercer trimestre de embarazo"],
  ea=["Irritación cutánea local","Eritema","Prurito","Dermatitis de contacto","Sequedad cutánea","Fotosensibilidad local"],
  ix=["Mínimas interacciones sistémicas","Otros tópicos: espaciar aplicación en misma zona"],
  ce=["Aplicar sobre piel intacta y seca","No cubrir con vendaje oclusivo","Lavarse las manos después de aplicar","Proteger zona de exposición solar (fotosensibilidad)","Menor riesgo sistémico que piroxicam oral","Útil en dolor localizado en pacientes de riesgo para AINEs orales"],
  emb="C"),

M("aine","flurbiprofeno_topico","Flurbiprofeno Tópico","Flurbiprofeno tópico",["Strepfen Spray","Transact LAT"],
  "AINE tópico derivado del ácido propiónico (spray/parche)",
  "Inhibidor no selectivo de COX-1 y COX-2 en formulación tópica (parche o spray). Penetra a tejidos superficiales produciendo analgesia local. También disponible como spray bucofaríngeo para dolor de garganta.",
  ["Dolor musculoesquelético localizado","Dolor por esguinces y contusiones","Dolor de garganta (spray bucofaríngeo)","Tendinitis"],
  ["topica"],
  {"adulto":"Parche: 1 parche c/12h sobre zona dolorosa. Spray bucofaríngeo: 1 aplicación c/3-6h. Máx 5 días"},
  ["Parche transdérmico 40 mg","Spray bucofaríngeo 0.25%"],
  "Compatible en uso tópico.","u08","c08_07",
  familia="AINEs tópicos",
  ci=["Hipersensibilidad a flurbiprofeno u otros AINEs","Piel lesionada","Asma por AINEs"],
  ea=["Irritación cutánea local","Eritema","Prurito","Sensación de calor local","Reacciones alérgicas cutáneas"],
  ix=["Mínimas interacciones sistémicas en uso tópico"],
  ce=["Parche: aplicar sobre piel intacta y limpia","No cortar el parche","Spray faríngeo: dirigir a la zona dolorosa","Menor riesgo sistémico que la vía oral","Útil en dolor localizado agudo de corta duración"],
  emb="C"),
]

NEW_CHAPTERS = {
    "c08_05": {"id":"c08_05","nombre":"Fármacos para Osteoporosis y Osteoartritis","unidadId":"u08","drugIds":[]},
    "c08_06": {"id":"c08_06","nombre":"Miopatías y Distrofias","unidadId":"u08","drugIds":[]},
    "c08_07": {"id":"c08_07","nombre":"Analgésicos Tópicos y Locales","unidadId":"u08","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U08: Sistema Musculoesquelético (expansión) ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u08", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
