#!/usr/bin/env python3
"""Add new drugs for U09 Dermatología."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ══════════════════════════════════════════════════════════════
# c09_01 Antibióticos Tópicos (+5)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","bacitracina","Bacitracina","Bacitracina",["Bacitracin","Nebacetin (combo)"],
  "Antibiótico tópico polipeptídico",
  "Inhibe la síntesis de pared celular bacteriana al interferir con la desfosforilación del pirofosfato de isoprenilo (C55). Activa principalmente contra grampositivos.",
  ["Heridas superficiales infectadas","Quemaduras menores","Prevención de infección en heridas limpias","Impétigo leve"],
  ["topica"],
  "Aplicar 1-3 veces/día en capa fina sobre la zona afectada limpia. Duración: 7-10 días",
  ["Ungüento 500 UI/g","Polvo tópico"],
  "Compatible para uso tópico.","u09","c09_01",
  familia="Antibióticos tópicos",
  ci=["Hipersensibilidad a bacitracina","No aplicar en ojos","No usar en grandes superficies (nefrotoxicidad por absorción)"],
  ea=["Dermatitis de contacto alérgica","Prurito local","Eritema","Nefrotoxicidad (rara, en uso extenso)"],
  ix=["Aminoglucósidos tópicos: nefrotoxicidad aditiva si absorción sistémica","No mezclar con otras cremas sin indicación"],
  ce=["Limpiar y secar la herida antes de aplicar","No usar en heridas profundas ni mordeduras","Sensibilización alérgica posible con uso prolongado","No ocluir salvo indicación médica","Vigilar signos de sobreinfección"],
  emb="C"),

M("corticoide_topico","neomicina_topica","Neomicina Tópica","Neomicina sulfato",["Neosporin (combo)","Nebacetin (combo)"],
  "Antibiótico tópico aminoglucósido",
  "Aminoglucósido que se une a la subunidad 30S ribosomal bacteriana, inhibiendo la síntesis proteica. Activa contra grampositivos y gramnegativos aerobios.",
  ["Infecciones cutáneas superficiales","Heridas infectadas","Quemaduras menores infectadas","Dermatitis sobreinfectada"],
  ["topica"],
  "Aplicar 1-3 veces/día sobre la zona afectada. Máximo 7-10 días",
  ["Crema 0.5%","Ungüento 0.5%","Polvo tópico (combinaciones)"],
  "Compatible para uso tópico.","u09","c09_01",
  familia="Antibióticos tópicos",
  ci=["Hipersensibilidad a aminoglucósidos","No aplicar en grandes superficies (ototoxicidad/nefrotoxicidad)","Perforación timpánica (uso ótico)"],
  ea=["Dermatitis de contacto alérgica (frecuente: 5-10%)","Prurito","Eritema","Ototoxicidad y nefrotoxicidad si absorción sistémica"],
  ix=["Otros aminoglucósidos: toxicidad aditiva","No mezclar con múltiples tópicos simultáneos"],
  ce=["Alta tasa de sensibilización alérgica (uno de los más frecuentes)","Realizar prueba de parche si sospecha de alergia","No usar en áreas extensas ni en piel ulcerada","Limpiar herida antes de aplicar","No más de 7-10 días de tratamiento"],
  emb="C"),

M("corticoide_topico","retapamulina","Retapamulina","Retapamulina",["Altabax","Altargo"],
  "Antibiótico tópico pleuromutilina",
  "Primera pleuromutilina de uso tópico. Se une al sitio P de la subunidad 50S ribosomal, inhibiendo la síntesis proteica bacteriana. Activa contra S. aureus (incluido MRSA in vitro) y S. pyogenes.",
  ["Impétigo causado por S. aureus o S. pyogenes","Infecciones cutáneas superficiales menores"],
  ["topica"],
  {"adulto":"Aplicar capa fina 2 veces/día x 5 días","pediatrico":"≥9 meses: misma dosis que adulto"},
  ["Ungüento 1%"],
  "Compatible con precaución.","u09","c09_01",
  familia="Antibióticos tópicos",
  ci=["Hipersensibilidad a retapamulina","No aplicar en mucosas","No usar en área >100 cm² en adultos"],
  ea=["Irritación local","Prurito","Dermatitis de contacto","Cefalea (raro)"],
  ix=["Inhibidores de CYP3A4: precaución teórica si gran absorción","Interacciones mínimas en uso tópico correcto"],
  ce=["Nueva clase antibiótica tópica (sin resistencia cruzada)","Aplicar sobre zona afectada limpia","Puede cubrirse con gasa estéril si necesario","Tratamiento corto: 5 días","No usar en heridas profundas o mordeduras"],
  emb="B"),

M("corticoide_topico","ozenoxacino","Ozenoxacino","Ozenoxacino",["Xepi","Ozanex"],
  "Antibiótico tópico quinolona no fluorada",
  "Quinolona no fluorada de uso tópico. Inhibe la ADN girasa y topoisomerasa IV bacterianas. Activa contra cepas resistentes a ácido fusídico y mupirocina.",
  ["Impétigo no ampolloso","Infecciones cutáneas por S. aureus resistente a mupirocina"],
  ["topica"],
  {"adulto":"Aplicar 2 veces/día x 5 días","pediatrico":"≥2 meses: misma dosis que adulto"},
  ["Crema 1%"],
  "Compatible con precaución.","u09","c09_01",
  familia="Antibióticos tópicos",
  ci=["Hipersensibilidad a ozenoxacino o quinolonas","No aplicar en mucosas"],
  ea=["Rosácea","Dermatitis de contacto","Eccema","Eritema"],
  ix=["Mínimas interacciones sistémicas en uso tópico"],
  ce=["Alternativa ante resistencia a mupirocina/ácido fusídico","Quinolona sin efectos sistémicos de fluoroquinolonas","Tratamiento corto: 5 días","Limpiar zona antes de aplicar","Apto desde los 2 meses de edad"],
  emb="B"),

M("corticoide_topico","gentamicina_topica","Gentamicina Tópica","Gentamicina sulfato",["Garamicina crema","Gentamicina tópica"],
  "Antibiótico tópico aminoglucósido",
  "Aminoglucósido que se une irreversiblemente a la subunidad 30S ribosomal. Activa contra gramnegativos aerobios (Pseudomonas, E. coli, Proteus) y algunos grampositivos.",
  ["Infecciones cutáneas por gramnegativos","Pioderma","Foliculitis","Heridas infectadas","Quemaduras sobreinfectadas"],
  ["topica"],
  "Aplicar 3-4 veces/día sobre la zona afectada limpia. Duración: 7-14 días",
  ["Crema 0.1%","Ungüento 0.1%"],
  "Compatible para uso tópico.","u09","c09_01",
  familia="Antibióticos tópicos",
  ci=["Hipersensibilidad a aminoglucósidos","No aplicar en grandes extensiones quemadas (absorción)"],
  ea=["Irritación local","Dermatitis de contacto","Ototoxicidad/nefrotoxicidad (si absorción extensa)","Sobreinfección fúngica"],
  ix=["Otros aminoglucósidos: toxicidad aditiva sistémica si absorción","Neomicina tópica: no combinar (sensibilización cruzada)"],
  ce=["Útil en infecciones por Pseudomonas cutánea","No usar en quemaduras extensas (absorción sistémica)","Limpiar y desbridar herida antes de aplicar","Vigilar signos de superinfección fúngica","Menor tasa de sensibilización que neomicina"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_02 Corticoides Tópicos (+8)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","fluocinolona","Fluocinolona","Acetonida de fluocinolona",["Synalar","Fluocinolona Gador","Dermalog"],
  "Corticoide tópico de potencia media (Clase IV-V)",
  "Corticoide tópico fluorado de potencia intermedia. Se une a receptores glucocorticoides, inhibiendo la respuesta inflamatoria e inmune local. Reduce eritema, edema, prurito y descamación.",
  ["Dermatitis atópica","Psoriasis en áreas sensibles","Eccema de contacto","Dermatitis seborreica"],
  ["topica"],
  "Aplicar capa fina 2-3 veces/día. Máximo 2-3 semanas continuas. Reducción gradual",
  ["Crema 0.01%, 0.025%","Ungüento 0.025%","Aceite 0.01% (cuero cabelludo)","Solución ótica 0.01%"],
  "Compatible con precaución. No aplicar en mamas.","u09","c09_02"),

M("corticoide_topico","fluocinonida","Fluocinonida","Fluocinonida",["Lidex","Fluocinonida Gador","Topsyn"],
  "Corticoide tópico de alta potencia (Clase II)",
  "Corticoide fluorado de alta potencia. Esterificación aumenta la lipofilia y penetración cutánea. Potente efecto antiinflamatorio, vasoconstricción local e inhibición de la proliferación celular.",
  ["Psoriasis en placas","Dermatitis atópica severa (tronco/extremidades)","Liquen plano","Eccema severo","Lupus discoide cutáneo"],
  ["topica"],
  "Aplicar capa fina 2-3 veces/día. Máximo 2 semanas continuas. No usar en cara ni pliegues",
  ["Crema 0.05%","Gel 0.05%","Ungüento 0.05%","Solución 0.05%"],
  "No aplicar en mamas. Compatible con precaución.","u09","c09_02"),

M("corticoide_topico","halcinonida","Halcinonida","Halcinonida",["Halog"],
  "Corticoide tópico de alta potencia (Clase II)",
  "Corticoide halogenado sintético con alta potencia antiinflamatoria. Penetra la capa córnea y se une a receptores glucocorticoides intracelulares.",
  ["Dermatosis inflamatorias severas","Psoriasis en placas resistente","Dermatitis atópica severa","Liquen simple crónico"],
  ["topica"],
  "Aplicar capa fina 2-3 veces/día. Máximo 2 semanas. No usar en cara, axila ni ingle",
  ["Crema 0.1%","Ungüento 0.1%","Solución 0.1%"],
  "No aplicar en mamas. Compatible con precaución.","u09","c09_02"),

M("corticoide_topico","diflorasona","Diflorasona","Diacetato de diflorasona",["Psorcon","Maxiflor"],
  "Corticoide tópico superpotente (Clase I)",
  "Corticoide difluorado de máxima potencia. Potente inhibición de fosfolipasa A2, reducción de prostaglandinas y leucotrienos. Vasoconstricción local marcada.",
  ["Psoriasis en placas refractaria","Dermatitis atópica severa refractaria","Liquen plano hipertrófico","Dermatosis inflamatorias severas en tronco/extremidades"],
  ["topica"],
  "Aplicar capa fina 1-2 veces/día. Máximo 2 semanas continuas. No >45 g/semana",
  ["Crema 0.05%","Ungüento 0.05%"],
  "No recomendado en lactancia.","u09","c09_02",
  ci=["Infecciones cutáneas no tratadas","Rosácea","Acné","Dermatitis perioral","Cara y pliegues (evitar)","Niños <12 años"],
  ea=["Atrofia cutánea","Estrías permanentes","Telangiectasias","Hipopigmentación","Foliculitis","Supresión adrenal (uso extenso)","Dermatitis de rebote severa"],
  ce=["Superpotente: uso corto plazo exclusivamente (<2 semanas)","NO en cara, pliegues, genitales ni área del pañal","No ocluir (aumenta absorción y riesgo)","Descenso gradual obligatorio en uso prolongado","Vigilar atrofia cutánea en cada visita"]),

M("corticoide_topico","triamcinolona_topica","Triamcinolona Tópica","Acetonida de triamcinolona",["Kenalog tópico","Triamcinolona crema"],
  "Corticoide tópico de potencia media (Clase III-IV)",
  "Corticoide fluorado de potencia intermedia. Amplio uso por su balance eficacia/seguridad. Inhibe liberación de ácido araquidónico y reduce permeabilidad vascular.",
  ["Dermatitis atópica","Psoriasis leve-moderada","Dermatitis de contacto","Dermatitis seborreica","Eccema numular","Liquen simple crónico"],
  ["topica"],
  "Aplicar capa fina 2-3 veces/día. Reducir frecuencia al mejorar. Máximo 3-4 semanas continuas",
  ["Crema 0.025%, 0.1%, 0.5%","Ungüento 0.1%, 0.5%","Loción 0.025%, 0.1%"],
  "Compatible con precaución. No aplicar en mamas.","u09","c09_02"),

M("corticoide_topico","prednicarbato","Prednicarbato","Prednicarbato",["Dermatop"],
  "Corticoide tópico de potencia media-baja (Clase IV-V)",
  "Corticoide no halogenado de nueva generación. Se metaboliza rápidamente en la piel a metabolitos inactivos, reduciendo efectos locales adversos. Buena relación eficacia/seguridad.",
  ["Dermatitis atópica (incluido niños)","Eccema","Dermatitis de contacto","Intertrigo","Dermatosis sensibles a corticoides"],
  ["topica"],
  {"adulto":"Aplicar 2 veces/día capa fina","pediatrico":"≥1 año: aplicar 1-2 veces/día. Menor duración posible"},
  ["Crema 0.25%","Ungüento 0.25%"],
  "Compatible con precaución.","u09","c09_02",
  ci=["Infecciones cutáneas no tratadas","Rosácea","Dermatitis perioral","Hipersensibilidad"],
  ea=["Menor atrofia cutánea que corticoides halogenados","Irritación local leve","Sequedad","Foliculitis (raro)"],
  ce=["Corticoide no halogenado: mejor perfil de seguridad","Apto para zonas sensibles (cara, pliegues) con precaución","Adecuado en pediatría por menor riesgo de atrofia","Aplicar capa fina","Descenso gradual en uso prolongado"]),

M("corticoide_topico","alclometasona","Alclometasona","Dipropionato de alclometasona",["Aclovate"],
  "Corticoide tópico de baja potencia (Clase VI)",
  "Corticoide clorado de baja potencia. Mínima absorción sistémica. Adecuado para áreas sensibles y uso en pediatría.",
  ["Dermatitis atópica leve","Eccema leve","Dermatitis de contacto","Dermatosis en cara y pliegues","Dermatosis en niños"],
  ["topica"],
  {"adulto":"Aplicar 2-3 veces/día capa fina","pediatrico":"≥1 año: aplicar 2 veces/día. Limitar duración"},
  ["Crema 0.05%","Ungüento 0.05%"],
  "Compatible con precaución.","u09","c09_02",
  ci=["Infecciones cutáneas no tratadas","Hipersensibilidad"],
  ea=["Irritación local","Sequedad","Foliculitis (raro)","Atrofia cutánea (menos frecuente que potentes)"],
  ce=["Baja potencia: apto para cara, pliegues e infantil","No requiere descenso gradual en uso corto","Aplicar capa fina","Ideal como transición desde corticoides más potentes","Derivar si no responde en 2 semanas (puede necesitar mayor potencia)"]),

M("corticoide_topico","desoximetasona","Desoximetasona","Desoximetasona",["Topicort"],
  "Corticoide tópico de alta potencia (Clase II-III)",
  "Corticoide fluorado de alta potencia. Excelente penetración en lesiones gruesas e hiperqueratósicas. Efecto antiinflamatorio potente y prolongado.",
  ["Psoriasis en placas","Eccema crónico severo","Dermatitis atópica severa en tronco","Liquen simple crónico"],
  ["topica"],
  "Aplicar capa fina 2 veces/día. Máximo 2 semanas continuas",
  ["Crema 0.05%, 0.25%","Gel 0.05%","Ungüento 0.25%","Spray 0.25%"],
  "No aplicar en mamas. Compatible con precaución.","u09","c09_02"),

# ══════════════════════════════════════════════════════════════
# c09_03 Antifúngicos Tópicos (+5)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","econazol","Econazol","Nitrato de econazol",["Pevaryl","Spectazole","Econazol Gador"],
  "Antifúngico tópico imidazólico",
  "Azol que inhibe la síntesis de ergosterol (enzima 14-alfa-desmetilasa) en la membrana celular fúngica. Actividad contra dermatofitos, Candida y algunos grampositivos.",
  ["Tiña corporis, cruris, pedis","Candidiasis cutánea","Pitiriasis versicolor","Dermatitis seborreica"],
  ["topica"],
  "Aplicar 1-2 veces/día sobre la zona afectada y piel circundante. Duración: 2-4 semanas",
  ["Crema 1%","Polvo 1%","Solución 1%","Óvulo vaginal 150 mg"],
  "Compatible para uso tópico.","u09","c09_03",
  familia="Antifúngicos tópicos",
  ci=["Hipersensibilidad a imidazoles"],
  ea=["Ardor local","Eritema","Prurito","Dermatitis de contacto (raro)"],
  ix=["Warfarina: posible aumento de INR si absorción sistémica en grandes áreas","Mínimas interacciones en uso tópico correcto"],
  ce=["Aplicar en zona afectada más 2 cm de piel sana circundante","Secar bien la piel antes de aplicar (hongos prosperan en humedad)","No suspender al mejorar: completar 2-4 semanas","Evitar calzado cerrado y ropa sintética ajustada","Lavar manos después de aplicar"],
  emb="C"),

M("corticoide_topico","sertaconazol","Sertaconazol","Nitrato de sertaconazol",["Ertaczo","Zalain","Dermofix"],
  "Antifúngico tópico benzotiofeno-imidazólico",
  "Azol con doble mecanismo: inhibe síntesis de ergosterol e interactúa directamente con membranas fúngicas (acción fungicida). Actividad antiinflamatoria adicional.",
  ["Tiña pedis","Tiña corporis y cruris","Candidiasis cutánea","Pitiriasis versicolor","Dermatitis seborreica"],
  ["topica"],
  "Aplicar 2 veces/día x 4 semanas. Tiña pedis: puede requerir hasta 6 semanas",
  ["Crema 2%","Polvo 2%","Óvulo vaginal 300 mg"],
  "Compatible para uso tópico.","u09","c09_03",
  familia="Antifúngicos tópicos",
  ci=["Hipersensibilidad a imidazoles"],
  ea=["Dermatitis de contacto","Sequedad cutánea","Eritema leve","Ardor transitorio"],
  ix=["Mínimas interacciones sistémicas en uso tópico"],
  ce=["Doble mecanismo: antifúngico + antiinflamatorio","Secar bien la zona antes de aplicar","Completar tratamiento aunque mejore clínicamente","Medidas higiénicas: secar pliegues, evitar calzado cerrado","Aplicar 2 cm más allá del borde de la lesión"],
  emb="C"),

M("corticoide_topico","luliconazol","Luliconazol","Luliconazol",["Luzu"],
  "Antifúngico tópico azólico de nueva generación",
  "Azol con inhibición potente de la 14-alfa-desmetilasa fúngica. Mayor potencia que otros azoles tópicos contra dermatofitos. Eficaz en tratamiento corto (1-2 semanas).",
  ["Tiña pedis interdigital","Tiña cruris","Tiña corporis"],
  ["topica"],
  "Tiña pedis: aplicar 1 vez/día x 2 semanas. Tiña cruris/corporis: 1 vez/día x 1 semana",
  ["Crema 1%"],
  "Compatible con precaución.","u09","c09_03",
  familia="Antifúngicos tópicos",
  ci=["Hipersensibilidad a azoles"],
  ea=["Dermatitis de contacto","Celulitis en sitio de aplicación (raro)","Prurito"],
  ix=["Mínimas interacciones sistémicas"],
  ce=["Tratamiento más corto que otros azoles tópicos","Aplicar 1 vez al día (mayor adherencia)","Secar zona afectada antes de aplicar","No se recomienda uso intravaginal","Completar duración prescrita aunque mejore"],
  emb="C"),

M("corticoide_topico","efinaconazol","Efinaconazol","Efinaconazol",["Jublia"],
  "Antifúngico tópico azólico para onicomicosis",
  "Azol triazólico con baja afinidad por queratina, lo que permite mejor penetración en la uña infectada. Inhibe la 14-alfa-desmetilasa del ergosterol fúngico.",
  ["Onicomicosis por dermatofitos (uñas de los pies)"],
  ["topica"],
  "Aplicar 1 vez/día en uña afectada y piel periungular x 48 semanas",
  ["Solución tópica 10%"],
  "Compatible con precaución.","u09","c09_03",
  familia="Antifúngicos tópicos",
  ci=["Hipersensibilidad al fármaco"],
  ea=["Uña encarnada","Dermatitis periungular","Vesículas en sitio de aplicación","Dolor en sitio de aplicación"],
  ix=["Mínimas interacciones sistémicas"],
  ce=["Tratamiento prolongado: 48 semanas (paciencia)","Aplicar sobre toda la superficie de la uña","Incluir piel debajo del borde libre de la uña","No usar esmalte de uñas durante tratamiento","Resultados visibles al crecer la uña sana (meses)"],
  emb="C"),

M("corticoide_topico","ciclopirox","Ciclopirox","Ciclopirox olamina",["Loprox","Ciclopirox","Batrafen"],
  "Antifúngico tópico de amplio espectro (hidroxipiridona)",
  "Inhibe la captación de precursores esenciales (aminoácidos, iones) a nivel de membrana celular fúngica. Quelante de cationes metálicos trivalentes. Amplio espectro: dermatofitos, Candida, Malassezia.",
  ["Tiña pedis, corporis, cruris","Candidiasis cutánea","Pitiriasis versicolor","Dermatitis seborreica","Onicomicosis leve-moderada"],
  ["topica"],
  "Crema/gel: aplicar 2 veces/día x 2-4 semanas. Laca de uñas: aplicar c/48h x 6-12 meses",
  ["Crema 1%","Gel 1%","Champú 1%, 1.5%","Laca de uñas 8%"],
  "Compatible para uso tópico.","u09","c09_03",
  familia="Antifúngicos tópicos",
  ci=["Hipersensibilidad a ciclopirox"],
  ea=["Ardor local transitorio","Eritema","Prurito","Descamación periungular (laca)"],
  ix=["Mínimas interacciones en uso tópico"],
  ce=["Laca de uñas: limar superficie antes de aplicar","Retirar laca vieja con alcohol cada 7 días","Champú: útil en dermatitis seborreica del cuero cabelludo","Mecanismo diferente a azoles (útil en resistencia)","Secar zona antes de aplicar crema/gel"],
  emb="B"),

# ══════════════════════════════════════════════════════════════
# c09_04 Antiparasitarios Tópicos (+3)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","benzoato_bencilo","Benzoato de Bencilo","Benzoato de bencilo",["Ascabiol","Benzoato de bencilo tópico"],
  "Antiparasitario tópico escabicida/pediculicida",
  "Neurotóxico para Sarcoptes scabiei y Pediculus humanus. Penetra el exoesqueleto del ácaro y actúa sobre su sistema nervioso causando parálisis y muerte.",
  ["Escabiosis (sarna)","Pediculosis corporis","Pediculosis pubis"],
  ["topica"],
  {"adulto":"Aplicar al 25% en todo el cuerpo (cuello hacia abajo). Dejar 24h, repetir a las 24h. Baño post-tratamiento","pediatrico":"Diluir al 10-12.5%. Misma pauta"},
  ["Loción 25%","Emulsión 10%, 25%"],
  "Compatible con precaución. No aplicar en mamas durante lactancia.","u09","c09_04",
  familia="Antiparasitarios tópicos",
  ci=["Hipersensibilidad","Piel inflamada o erosionada extensa","Niños <2 años (usar con precaución diluido)"],
  ea=["Irritación cutánea intensa","Ardor y escozor al aplicar","Dermatitis de contacto","Convulsiones (si ingestión accidental)"],
  ix=["No significativas en uso tópico correcto"],
  ce=["Aplicar en TODO el cuerpo de cuello a pies (incluir pliegues, interdigital, genitales)","Tratar a TODOS los convivientes simultáneamente","Lavar toda la ropa y sábanas a >60°C","El prurito puede persistir 2-4 semanas post-tratamiento (no es fallo)","Olor fuerte: advertir al paciente"],
  emb="C"),

M("corticoide_topico","crotamiton","Crotamitón","Crotamitón",["Eurax"],
  "Antiparasitario y antipruriginoso tópico",
  "Mecanismo antiparasitario no completamente elucidado. Efecto acaricida contra Sarcoptes scabiei. Acción antipruriginosa adicional independiente del efecto antiparasitario.",
  ["Escabiosis (alternativa)","Prurito de diversas etiologías","Prurito post-escabiótico"],
  ["topica"],
  {"adulto":"Escabiosis: aplicar del cuello a pies, repetir a las 24h. Baño 48h post-segunda aplicación. Prurito: aplicar TID","pediatrico":"No recomendado en lactantes"},
  ["Crema 10%","Loción 10%"],
  "Compatible con precaución.","u09","c09_04",
  familia="Antiparasitarios tópicos",
  ci=["Hipersensibilidad","Dermatitis aguda exudativa","Piel erosionada extensa"],
  ea=["Irritación cutánea leve","Dermatitis de contacto alérgica","Eritema","Sensación de calor local"],
  ix=["No significativas en uso tópico"],
  ce=["Menos eficaz que permetrina para sarna (alternativa si intolerancia)","Ventaja: efecto antipruriginoso adicional","Aplicar tras baño tibio en piel seca","Tratar contactos cercanos simultáneamente","Puede usarse para prurito post-tratamiento de sarna"],
  emb="C"),

M("corticoide_topico","spinosad","Spinosad","Spinosad",["Natroba"],
  "Pediculicida tópico de origen natural",
  "Insecticida natural derivado de Saccharopolyspora spinosa. Causa hiperexcitación neuronal en piojos al activar receptores nicotínicos de acetilcolina, produciendo parálisis y muerte.",
  ["Pediculosis capitis (piojos de la cabeza)"],
  ["topica"],
  {"adulto":"Aplicar suficiente cantidad en cabello seco, dejar 10 min, enjuagar. Repetir en 7 días si necesario","pediatrico":"≥4 años: misma dosis que adulto"},
  ["Suspensión tópica 0.9%"],
  "Compatible con precaución.","u09","c09_04",
  familia="Antiparasitarios tópicos",
  ci=["Hipersensibilidad a spinosad","Niños <4 años","Contiene alcohol bencílico: precaución en neonatos"],
  ea=["Eritema ocular o periocular","Eritema del cuero cabelludo","Irritación cutánea"],
  ix=["No significativas"],
  ce=["No requiere uso de liendrera (mata también huevos y ninfas)","Aplicar en cabello SECO (no mojado)","Dejar actuar 10 minutos y enjuagar","Revisar a los 7 días: repetir si se ven piojos vivos","Evitar contacto con los ojos"],
  emb="B"),

# ══════════════════════════════════════════════════════════════
# c09_05 Antivirales Tópicos (+3)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","penciclovir","Penciclovir","Penciclovir",["Denavir","Vectavir"],
  "Antiviral tópico análogo nucleósido",
  "Análogo acíclico de guanosina. Tras fosforilación por timidina quinasa viral, inhibe la ADN polimerasa del virus herpes. Más estable intracelularmente que aciclovir en forma trifosforilada.",
  ["Herpes labial recurrente (calenturas)"],
  ["topica"],
  "Aplicar cada 2 horas durante el día (vigilia) x 4 días. Iniciar al primer síntoma (pródromo)",
  ["Crema 1%"],
  "Compatible para uso tópico.","u09","c09_05",
  familia="Antivirales tópicos",
  ci=["Hipersensibilidad a penciclovir o famciclovir","No aplicar en mucosas ni ojos"],
  ea=["Cefalea","Parestesias en sitio de aplicación","Eritema leve","Alteración del gusto"],
  ix=["No significativas en uso tópico"],
  ce=["Iniciar al PRIMER síntoma (hormigueo/ardor): mayor eficacia","Aplicar cada 2 horas durante horas de vigilia","No aplicar dentro de la boca ni en mucosas","Lavarse manos antes y después (evitar diseminación)","Acorta duración en ~1 día si se inicia tempranamente"],
  emb="B"),

M("corticoide_topico","docosanol","Docosanol","Docosanol",["Abreva","Erazaban"],
  "Antiviral tópico (alcohol graso saturado)",
  "Alcohol graso de cadena larga que inhibe la fusión del virus herpes simple con la membrana celular del huésped. Impide la entrada viral a la célula. Mecanismo diferente a análogos nucleósidos.",
  ["Herpes labial recurrente (venta libre)"],
  ["topica"],
  "Aplicar 5 veces/día al primer síntoma. Continuar hasta cicatrización (máx 10 días)",
  ["Crema 10%"],
  "Compatible para uso tópico.","u09","c09_05",
  familia="Antivirales tópicos",
  ci=["Hipersensibilidad al fármaco","No aplicar en ojos ni mucosas","No usar en inmunodeprimidos (consultar médico)"],
  ea=["Cefalea","Reacción en sitio de aplicación","Sequedad cutánea"],
  ix=["No significativas"],
  ce=["Disponible sin receta en muchos países","Iniciar al PRIMER síntoma prodromal","Mecanismo no nucleósido: sin resistencia cruzada","Lavarse manos antes y después de aplicar","No aplicar dentro de la boca"],
  emb="B"),

M("corticoide_topico","imiquimod","Imiquimod","Imiquimod",["Aldara","Zyclara","Imiquimod Gador"],
  "Inmunomodulador tópico (agonista TLR-7)",
  "Agonista del receptor toll-like 7 (TLR-7). Estimula la inmunidad innata y adaptativa: induce producción de interferón alfa, TNF-alfa y otras citocinas. Efecto antiviral, antitumoral e inmunomodulador.",
  ["Verrugas genitales externas (condilomas acuminados)","Queratosis actínica superficial","Carcinoma basocelular superficial (alternativa a cirugía)","Verrugas vulgares (off-label)"],
  ["topica"],
  {"adulto":"Verrugas genitales: 3 veces/semana al acostarse x hasta 16 semanas. Queratosis actínica: 2 veces/semana x 16 semanas. CBC: 5 veces/semana x 6 semanas"},
  ["Crema 5% (Aldara)","Crema 3.75% (Zyclara)","Sobres individuales"],
  "No recomendado durante lactancia.","u09","c09_05",
  familia="Inmunomoduladores tópicos",
  ci=["Hipersensibilidad","No usar en lesiones internas (vagina, cérvix, recto, uretra)","Inmunosupresión severa"],
  ea=["Eritema local intenso (esperado)","Erosiones","Costras","Edema","Dolor/ardor","Síntomas gripales","Fatiga"],
  ix=["Inmunosupresores: pueden reducir eficacia","No aplicar con oclusión"],
  ce=["La inflamación local ES el mecanismo de acción (esperada)","Aplicar capa fina al acostarse, lavar por la mañana (8h de contacto)","Derivar si reacción local severa (descanso de 1-2 semanas)","No relaciones sexuales durante aplicación en genitales (debilita condones)","Educar: la respuesta inflamatoria indica que funciona"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_06 Inmunomoduladores (+6)
# ══════════════════════════════════════════════════════════════
M("inmunosupresor","ruxolitinib_topico","Ruxolitinib Tópico","Ruxolitinib",["Opzelura"],
  "Inhibidor de JAK1/JAK2 tópico",
  "Inhibidor selectivo de las quinasas Janus JAK1 y JAK2. Bloquea la vía de señalización JAK-STAT, reduciendo la producción de citocinas proinflamatorias en la piel.",
  ["Dermatitis atópica leve-moderada (≥12 años)","Vitíligo no segmentario (repigmentación)"],
  ["topica"],
  {"adulto":"Aplicar capa fina 2 veces/día en áreas afectadas. Máximo 20% de superficie corporal","pediatrico":"≥12 años: misma dosis que adulto"},
  ["Crema 1.5%"],
  "No recomendado.","u09","c09_06",
  familia="Inhibidores JAK tópicos",
  ci=["Hipersensibilidad","Inmunodeficiencia","Infección activa en zona de aplicación"],
  ea=["Nasofaringitis","Diarrea","Bronquitis","Infección de oído","Eosinofilia","Urticaria","Foliculitis","Acné"],
  ix=["Inhibidores potentes de CYP3A4: precaución si gran área","Otros inmunosupresores tópicos: no combinar","Vacunas vivas: evitar durante tratamiento"],
  ce=["Primer inhibidor de JAK tópico aprobado","No superar 20% de superficie corporal (absorción sistémica)","Para vitíligo: resultados en 24 semanas de uso continuado","No ocluir","Vigilar signos de infección"],
  emb="C"),

M("inmunosupresor","abrocitinib","Abrocitinib","Abrocitinib",["Cibinqo"],
  "Inhibidor selectivo de JAK1 oral",
  "Inhibidor oral selectivo de JAK1. Bloquea la señalización de múltiples citocinas proinflamatorias Th2 (IL-4, IL-13, IL-31, TSLP) implicadas en la dermatitis atópica.",
  ["Dermatitis atópica moderada a grave refractaria (≥12 años)"],
  ["oral"],
  {"adulto":"100 mg/día oral. Puede aumentarse a 200 mg/día. Reducir a 100 mg al controlar","pediatrico":"≥12 años y ≥40 kg: misma dosis adulto"},
  ["Comp 50, 100, 200 mg"],
  "No recomendado.","u09","c09_06",
  familia="Inhibidores JAK orales",
  ci=["Hipersensibilidad","Infección activa grave","Linfopenia <500/µL","Neutropenia <1000/µL","Hemoglobina <8 g/dL","Embarazo"],
  ea=["Náuseas","Cefalea","Acné","Herpes simple","Herpes zóster","Linfopenia","Trombocitopenia","Elevación CPK","Hiperlipidemia"],
  ix=["Inhibidores potentes CYP2C19: reducir dosis a la mitad","Inductores CYP2C19/CYP2C9: pueden reducir eficacia","No combinar con otros JAK-inhibidores ni biológicos","Vacunas vivas: contraindicadas"],
  ce=["Hemograma completo antes de iniciar y periódico","Vigilar herpes zóster (riesgo aumentado)","Evaluar lípidos a las 4 semanas","No usar con biológicos inmunosupresores","Anticoncepción eficaz obligatoria (teratógeno)"],
  emb="X"),

M("inmunosupresor","tralokinumab","Tralokinumab","Tralokinumab",["Adbry","Adtralza"],
  "Anticuerpo monoclonal anti-IL-13",
  "Anticuerpo monoclonal IgG4 humanizado que se une específicamente a IL-13, neutralizándola. IL-13 es citocina clave en la inflamación tipo 2 y disfunción de barrera cutánea en dermatitis atópica.",
  ["Dermatitis atópica moderada a grave en adultos"],
  ["SC"],
  "Carga: 600 mg (4 inyecciones de 150 mg) SC inicial, luego 300 mg SC cada 2 semanas",
  ["Jeringa precargada 150 mg","Pluma precargada 300 mg"],
  "Probablemente compatible (IgG).","u09","c09_06",
  familia="Anticuerpos monoclonales anti-IL-13",
  ci=["Hipersensibilidad","Infección activa grave"],
  ea=["Infección de vías respiratorias superiores","Conjuntivitis","Reacción en sitio de inyección","Eosinofilia"],
  ix=["Vacunas vivas: evitar durante tratamiento","No interacciones CYP significativas"],
  ce=["Puede autoadministrarse tras entrenamiento","Rotar sitios de inyección SC","Diferente de dupilumab: solo bloquea IL-13 (no IL-4)","Mejoría visible en 2-4 semanas","No es inmunosupresor amplio: menor riesgo infeccioso general"],
  emb="C"),

M("inmunosupresor","nemolizumab","Nemolizumab","Nemolizumab",["Nemluvio"],
  "Anticuerpo monoclonal anti-IL-31Rα",
  "Anticuerpo monoclonal humanizado que se une al receptor alfa de IL-31 (IL-31RA). IL-31 es la principal citocina del prurito en dermatitis atópica. Efecto antipruriginoso potente.",
  ["Prurigo nodular (aprobado)","Dermatitis atópica moderada-severa con prurito intenso"],
  ["SC"],
  "Carga: según peso. Mantenimiento: 30 mg SC cada 4 semanas (prurigo nodular)",
  ["Jeringa precargada 30, 60 mg"],
  "No recomendado.","u09","c09_06",
  familia="Anticuerpos monoclonales anti-IL-31",
  ci=["Hipersensibilidad","Infección activa grave"],
  ea=["Cefalea","Dermatitis atópica (exacerbación paradójica reportada)","Eccema","Infecciones cutáneas"],
  ix=["Vacunas vivas: evitar durante tratamiento","Interacciones mínimas"],
  ce=["Primer fármaco dirigido específicamente contra el prurito","Alivio del prurito rápido (semanas)","Administración SC mensual","Rotar sitios de inyección","Monitorizar posibles exacerbaciones paradójicas de eccema"],
  emb="C"),

M("inmunosupresor","lebrikizumab","Lebrikizumab","Lebrikizumab",["Ebglyss"],
  "Anticuerpo monoclonal anti-IL-13 de alta afinidad",
  "Anticuerpo monoclonal IgG4 humanizado que se une a IL-13 con alta afinidad, impidiendo la formación del heterodímero IL-4Rα/IL-13Rα1. Bloqueo selectivo de la señalización de IL-13.",
  ["Dermatitis atópica moderada a grave en adultos y adolescentes (≥12 años)"],
  ["SC"],
  {"adulto":"Carga: 500 mg (2x250) SC d0 y d14, luego 250 mg SC cada 2 semanas. Posible espaciar a c/4 sem tras control","pediatrico":"≥12 años y ≥40 kg: misma dosis adulto"},
  ["Jeringa precargada 250 mg","Pluma precargada 250 mg"],
  "Probablemente compatible (IgG).","u09","c09_06",
  familia="Anticuerpos monoclonales anti-IL-13",
  ci=["Hipersensibilidad","Infección activa grave","Infestación helmíntica activa no tratada"],
  ea=["Conjuntivitis","Reacción en sitio de inyección","Queratitis","Ojo seco","Herpes simple oral"],
  ix=["Vacunas vivas: evitar","No interacciones farmacocinéticas relevantes"],
  ce=["Posibilidad de dosificación mensual tras respuesta","Autoadministración SC tras entrenamiento","Vigilar conjuntivitis (tratar con lágrimas artificiales)","No requiere monitorización analítica rutinaria","Rotar sitios de inyección"],
  emb="C"),

M("inmunosupresor","bimekizumab","Bimekizumab","Bimekizumab",["Bimzelx"],
  "Anticuerpo monoclonal dual anti-IL-17A/IL-17F",
  "Anticuerpo monoclonal IgG1 humanizado que neutraliza simultáneamente IL-17A e IL-17F. Ambas citocinas participan en la inflamación cutánea de psoriasis. Bloqueo dual más completo que anti-IL-17A solo.",
  ["Psoriasis en placas moderada a grave","Artritis psoriásica","Espondiloartritis axial"],
  ["SC"],
  "Carga: 320 mg SC c/4 semanas x 16 semanas. Mantenimiento: 320 mg SC c/8 semanas",
  ["Jeringa precargada 160 mg","Pluma precargada 160 mg"],
  "No recomendado.","u09","c09_06",
  familia="Anticuerpos monoclonales anti-IL-17",
  ci=["Hipersensibilidad","Infección activa grave","Enfermedad inflamatoria intestinal activa (riesgo exacerbación)"],
  ea=["Candidiasis oral (frecuente)","Infecciones de vías respiratorias","Reacción en sitio de inyección","Foliculitis","Cefalea"],
  ix=["Vacunas vivas: contraindicadas","Otros inmunosupresores biológicos: no combinar"],
  ce=["Vigilar candidiasis oral (frecuente, tratar con antifúngicos tópicos)","Cribado de TB antes de iniciar","Preguntar por síntomas de EII (contraindicado)","Autoadministración SC tras entrenamiento","Dosificación bimensual en mantenimiento (buena adherencia)"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_07 Retinoides y Antiacneicos (+4)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","tazaroteno","Tazaroteno","Tazaroteno",["Tazorac","Zorac","Avage"],
  "Retinoide tópico de 3ra generación (receptor selectivo)",
  "Profármaco retinoide que se convierte en ácido tazaroténico. Se une selectivamente a receptores RAR-beta y RAR-gamma. Normaliza la diferenciación queratinocítica, reduce hiperproliferación y tiene efecto antiinflamatorio.",
  ["Psoriasis en placas leve-moderada","Acné vulgar","Fotoenvejecimiento"],
  ["topica"],
  "Aplicar capa fina 1 vez/día por la noche. Iniciar con 0.05% e ir a 0.1% si tolera",
  ["Crema 0.05%, 0.1%","Gel 0.05%, 0.1%","Loción 0.045%"],
  "Contraindicado.","u09","c09_07",
  familia="Retinoides tópicos",
  ci=["Embarazo (TERATÓGENO)","Hipersensibilidad a retinoides","Eccema o dermatitis en zona de aplicación"],
  ea=["Irritación cutánea (eritema, descamación, ardor)","Sequedad","Fotosensibilidad","Prurito","Dolor local"],
  ix=["Otros retinoides: no combinar","Productos con alcohol o astringentes: mayor irritación","Fotosensibilizantes: mayor riesgo de quemadura solar"],
  ce=["Anticoncepción obligatoria (teratógeno clase X)","Aplicar solo de NOCHE (fotosensibilidad)","Fotoprotección diaria obligatoria","Irritación inicial: reducir a cada 2 noches las primeras 2 semanas","No aplicar en piel húmeda ni sobre eccema","Evitar labios, ojos, mucosas"],
  emb="X"),

M("corticoide_topico","trifaroteno","Trifaroteno","Trifaroteno",["Aklief"],
  "Retinoide tópico de 4ta generación (RAR-gamma selectivo)",
  "Primer retinoide tópico altamente selectivo para RAR-gamma, el receptor más abundante en la piel. Normaliza queratinización folicular con menor irritación teórica que retinoides previos.",
  ["Acné vulgar facial y troncal","Primer retinoide aprobado para acné de tronco"],
  ["topica"],
  "Aplicar capa fina 1 vez/día por la noche en cara y/o tronco",
  ["Crema 0.005%"],
  "No recomendado.","u09","c09_07",
  familia="Retinoides tópicos",
  ci=["Embarazo (TERATÓGENO)","Hipersensibilidad a retinoides","Eccema activo en zona de aplicación"],
  ea=["Irritación cutánea (menor que otros retinoides)","Sequedad","Descamación","Eritema","Fotosensibilidad"],
  ix=["Otros retinoides: no combinar","Agentes irritantes tópicos: mayor irritación"],
  ce=["Primer retinoide aprobado para acné del TRONCO (espalda, pecho)","Selectivo RAR-gamma: potencialmente mejor tolerado","Aplicar de noche en piel seca","Fotoprotección diaria","Anticoncepción en mujeres fértiles (teratógeno)","Respuesta clínica: 8-12 semanas"],
  emb="X"),

M("corticoide_topico","sarecycline_acne","Sareciclina","Sareciclina",["Seysara"],
  "Antibiótico oral tetraciclina de espectro estrecho para acné",
  "Tetraciclina de espectro estrecho diseñada específicamente para acné. Menor actividad contra flora GI normal (menos disbiosis). Inhibe subunidad 30S ribosomal de C. acnes.",
  ["Acné vulgar moderado a severo (inflamatorio)"],
  ["oral"],
  {"adulto":"Según peso: 33-54 kg: 60 mg/día; 55-84 kg: 100 mg/día; ≥85 kg: 150 mg/día","pediatrico":"≥9 años: misma dosificación por peso"},
  ["Comp 60, 100, 150 mg"],
  "Evitar durante lactancia.","u09","c09_07",
  familia="Tetraciclinas",
  ci=["Embarazo","Niños <9 años","Hipersensibilidad a tetraciclinas"],
  ea=["Náuseas","Vómitos","Candidiasis vaginal","Vestibulotoxicidad (raro)","Fotosensibilidad"],
  ix=["Antiácidos, hierro, calcio: reducen absorción (separar 2h)","Anticoagulantes orales: mayor efecto","Retinoides orales: NO combinar (pseudotumor cerebri)","Anticonceptivos: posible reducción eficacia"],
  ce=["Espectro estrecho: menor impacto en microbiota intestinal","Se puede tomar con o sin alimentos","Fotoprotección durante tratamiento","No combinar NUNCA con isotretinoína (pseudotumor cerebri)","Duración del tratamiento: revisar a las 12 semanas"],
  emb="D"),

M("corticoide_topico","clascoterone","Clascoterone","Clascoterone",["Winlevi"],
  "Antiandrógeno tópico (inhibidor del receptor de andrógenos)",
  "Primer antiandrógeno tópico aprobado para acné. Compite con dihidrotestosterona (DHT) por el receptor de andrógenos en la glándula sebácea, reduciendo la producción de sebo. No efectos antiandrogénicos sistémicos.",
  ["Acné vulgar en pacientes ≥12 años"],
  ["topica"],
  {"adulto":"Aplicar capa fina 2 veces/día (mañana y noche) en áreas afectadas","pediatrico":"≥12 años: misma dosis que adulto"},
  ["Crema 1%"],
  "Compatible con precaución.","u09","c09_07",
  familia="Antiandrógenos tópicos",
  ci=["Hipersensibilidad al fármaco"],
  ea=["Eritema","Edema facial","Descamación","Sequedad cutánea","Prurito","Supresión cortisol (teórico, a dosis altas)"],
  ix=["Precaución teórica con corticoides tópicos (estructura similar)","Sin interacciones sistémicas significativas"],
  ce=["Primer antiandrógeno tópico: nuevo mecanismo para acné","Puede usarse en HOMBRES Y MUJERES (a diferencia de antiandrógenos orales)","Efecto local sin feminización sistémica","Aplicar 2 veces/día","Resultados visibles en 12 semanas","Puede combinarse con retinoides o peróxido de benzoílo"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_08 Antisépticos y Cicatrizantes (NUEVO)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","clorhexidina_topica","Clorhexidina Tópica","Digluconato de clorhexidina",["Hibiscrub","Clorhexidina","Baxidin"],
  "Antiséptico tópico biguanida",
  "Antiséptico biguanida catiónico de amplio espectro. Altera la permeabilidad de la membrana celular bacteriana. Efecto bactericida rápido y actividad residual prolongada (6-8 horas) tras unirse a la piel.",
  ["Antisepsia de piel preoperatoria","Lavado de heridas","Desinfección de manos quirúrgica","Antisepsia periumbilical neonatal","Gingivitis (enjuague bucal)"],
  ["topica"],
  "Solución 0.5-2%: aplicar en zona a desinfectar. Lavado quirúrgico: frotar 3-5 min. Enjuague bucal 0.12%: 15 mL BID",
  ["Solución 0.5%, 2%, 4%","Gel 0.2%","Enjuague bucal 0.12%","Toallitas"],
  "Compatible.","u09","c09_08",
  familia="Antisépticos tópicos",
  ci=["Hipersensibilidad a clorhexidina","No aplicar en oídos (ototóxica con membrana perforada)","No usar en SNC ni meninges","Anafilaxia a clorhexidina reportada"],
  ea=["Dermatitis de contacto","Tinción dental (enjuague bucal)","Irritación cutánea","Anafilaxia (raro pero descrita)"],
  ix=["Jabones aniónicos: inactivan la clorhexidina","No mezclar con povidona yodada (antagonismo)"],
  ce=["Actividad residual prolongada (ventaja sobre povidona yodada)","Dejar secar antes de cirugía (actividad óptima)","NO introducir en oído si perforación timpánica","Preguntar SIEMPRE por alergia previa a clorhexidina","Enjuague bucal puede teñir dientes (reversible al suspender)"],
  emb="B"),

M("corticoide_topico","povidona_yodada","Povidona Yodada","Povidona yodada",["Betadine","Pervinox","Isodine"],
  "Antiséptico tópico yodóforo",
  "Complejo de yodo con polivinilpirrolidona que libera yodo libre gradualmente. El yodo libre oxida y sustituye componentes celulares microbianos. Amplio espectro: bacterias, virus, hongos, esporas.",
  ["Antisepsia de heridas","Preparación preoperatoria de piel","Quemaduras menores","Úlceras cutáneas infectadas","Antisepsia perioperatoria"],
  ["topica"],
  "Solución 10%: aplicar en zona afectada. Dejar actuar 2-3 min antes de procedimiento. Heridas: irrigar con solución diluida",
  ["Solución 10%","Jabón 4%, 7.5%","Ungüento 10%","Espuma","Toallitas"],
  "Compatible con precaución. No en lactancia prolongada (paso de yodo).","u09","c09_08",
  familia="Antisépticos tópicos",
  ci=["Hipersensibilidad al yodo","Enfermedad tiroidea (uso extenso/prolongado)","Neonatos prematuros","No usar con oclusión extensa"],
  ea=["Irritación cutánea","Dermatitis de contacto","Disfunción tiroidea (uso prolongado/extenso)","Tinción marrón de piel y ropa","Acidosis metabólica (si absorción masiva)"],
  ix=["Mercurocromo: formación de compuestos tóxicos (NUNCA combinar)","Clorhexidina: antagonismo","Sales de plata: precipitado"],
  ce=["Dejar actuar al menos 2 minutos para efecto óptimo","Se inactiva por sangre y materia orgánica (limpiar primero)","NO usar en grandes superficies ni neonatos (absorción de yodo → hipotiroidismo)","La tinción marrón NO significa infección","Quita manchas: tiosulfato de sodio"],
  emb="D"),

M("corticoide_topico","nitrato_plata","Nitrato de Plata","Nitrato de plata",["AgNO3","Argyrol"],
  "Antiséptico y cauterizante tópico",
  "Ion plata se une a proteínas microbianas y precipita, causando efecto bactericida. A concentración alta, efecto cauterizante por precipitación proteica. Activo contra bacterias, incluyendo Pseudomonas.",
  ["Cauterización de granulomas umbilicales neonatales","Quemaduras (histórico)","Úlceras infectadas (tópico)","Hemorragia nasal (cauterización)","Verrugas (cauterización)"],
  ["topica"],
  "Barras 75%: aplicar directamente sobre granuloma x 2-3 seg. Solución 0.5%: apósitos húmedos en quemaduras",
  ["Barras de cauterización 75%","Solución 0.5%, 1%"],
  "Compatible con precaución.","u09","c09_08",
  familia="Antisépticos y cauterizantes",
  ci=["Hipersensibilidad","No aplicar en ojos","No en grandes superficies (argiria)"],
  ea=["Tinción negro-grisácea de piel (temporal o permanente: argiria)","Dolor/ardor al aplicar","Quemadura química (si concentración excesiva)","Metahemoglobinemia (absorción extensa)"],
  ix=["No significativas en uso localizado"],
  ce=["Tiñe todo de negro: proteger piel circundante con vaselina","Barras: aplicar solo segundos (cauterización controlada)","Granuloma umbilical: aplicar solo sobre granuloma, proteger piel sana","Solución: renovar apósitos húmedos frecuentemente","Almacenar protegido de la luz"],
  emb="C"),

M("corticoide_topico","colagenasa","Colagenasa","Colagenasa clostridial",["Iruxol","Santyl","Collagenase"],
  "Desbridante enzimático tópico",
  "Enzima proteolítica derivada de Clostridium histolyticum. Digiere selectivamente el colágeno desnaturalizado del tejido necrótico sin dañar tejido viable ni colágeno nativo. Facilita el desbridamiento y la granulación.",
  ["Úlceras por presión con tejido necrótico","Úlceras vasculares con esfacelo","Quemaduras de 2°-3° grado con escara","Heridas crónicas con tejido desvitalizado"],
  ["topica"],
  "Aplicar capa fina (2 mm) 1 vez/día sobre tejido necrótico húmedo. Cubrir con apósito",
  ["Ungüento 250 UI/g","Ungüento 1.2 UI/g"],
  "Compatible.","u09","c09_08",
  familia="Desbridantes enzimáticos",
  ci=["Hipersensibilidad a colagenasa","Herida con colección purulenta no drenada"],
  ea=["Dolor local","Eritema perilesional","Maceración de piel circundante"],
  ix=["Antisépticos metálicos (plata, mercurio, zinc): INACTIVAN la colagenasa","Antibióticos tópicos excepto bacitracina: pueden inhibir actividad","No usar con povidona yodada ni clorhexidina directamente"],
  ce=["Humedecer tejido necrótico antes de aplicar (funciona en medio húmedo)","Proteger piel sana circundante con pasta de zinc","NO combinar con antisépticos metálicos (inactivan enzima)","Solo sobre tejido necrótico, NO en tejido de granulación sano","Cubrir con apósito secundario no adherente","Cambio diario evaluando progreso"],
  emb="C"),

M("corticoide_topico","acido_hialuronico_topico","Ácido Hialurónico Tópico","Hialuronato de sodio",["Connettivina","Cicatricure (combo)","Jaloplast"],
  "Cicatrizante tópico (glucosaminoglicano)",
  "Glucosaminoglicano natural componente de la matriz extracelular. Retiene agua (~1000 veces su peso), mantiene hidratación del lecho de la herida. Estimula migración celular, angiogénesis y deposición de colágeno.",
  ["Heridas crónicas y agudas","Úlceras por presión","Úlceras vasculares","Quemaduras superficiales","Postprocedimientos dermatológicos"],
  ["topica"],
  "Aplicar 1-2 veces/día en herida limpia. Cubrir con apósito si necesario",
  ["Crema 0.2%","Gel 0.2%, 0.4%","Gasa impregnada","Spray"],
  "Compatible.","u09","c09_08",
  familia="Cicatrizantes tópicos",
  ci=["Hipersensibilidad al ácido hialurónico","Herida infectada no tratada"],
  ea=["Irritación local leve (raro)","Eritema transitorio"],
  ix=["Compatible con la mayoría de apósitos y tratamientos tópicos"],
  ce=["Mantiene microambiente húmedo óptimo para cicatrización","Aplicar en herida limpia y desbridada","Compatible con apósitos primarios y secundarios","No sustituye el desbridamiento si hay tejido necrótico","Almacenar a temperatura ambiente"],
  emb="B"),

M("corticoide_topico","alantoina","Alantoína","Alantoína",["Alantoína tópica","Cicatricure (ingrediente)"],
  "Cicatrizante y queratoplástico tópico",
  "Estimula la proliferación celular y la síntesis de tejido de granulación. Efecto queratolítico suave que facilita eliminación de tejido necrótico. Acción hidratante y emoliente.",
  ["Cicatrización de heridas superficiales","Dermatitis de pañal","Grietas en pezones","Quemaduras solares","Xerosis cutánea"],
  ["topica"],
  "Aplicar 2-3 veces/día en zona afectada",
  ["Crema 0.5%, 1%, 2%","Ungüento 2%","Loción"],
  "Compatible.","u09","c09_08",
  familia="Cicatrizantes tópicos",
  ci=["Hipersensibilidad (raro)"],
  ea=["Irritación local leve (muy raro)"],
  ix=["No significativas"],
  ce=["Bien tolerado, apto para uso prolongado","Puede combinarse con otros activos (dexpantenol, vitamina E)","Apto para zona del pañal en lactantes","No requiere prescripción en muchos países","Aplicar sobre piel limpia"],
  emb="A"),

M("corticoide_topico","dexpantenol","Dexpantenol","Dexpantenol (provitamina B5)",["Bepanthen","Bepanthol","Dexpantenol crema"],
  "Cicatrizante y protector cutáneo tópico",
  "Profármaco de ácido pantoténico (vitamina B5). Se convierte en coenzima A, esencial para la síntesis de lípidos, proteínas y acetilcolina. Estimula la proliferación de fibroblastos y la epitelización.",
  ["Heridas superficiales y abrasiones","Dermatitis del pañal","Grietas del pezón en lactancia","Quemaduras solares leves","Xerosis cutánea","Post-procedimientos dermatológicos (láser, peelings)"],
  ["topica"],
  "Aplicar 2-3 veces/día en zona afectada. Grietas pezón: aplicar después de cada toma",
  ["Crema 5%","Ungüento 5%","Pomada 5%","Spray"],
  "Compatible. Seguro durante lactancia (grietas de pezón).","u09","c09_08",
  familia="Cicatrizantes tópicos",
  ci=["Hipersensibilidad a dexpantenol (extremadamente raro)"],
  ea=["Dermatitis de contacto alérgica (muy raro)","Irritación local mínima"],
  ix=["No significativas"],
  ce=["Muy bien tolerado: apto para lactantes y embarazadas","Para grietas de pezón: no es necesario retirar antes de amamantar","Uso preventivo en dermatitis del pañal con cada cambio","Compatible con la mayoría de tratamientos tópicos","Aplicar sobre piel limpia y seca"],
  emb="A"),

M("corticoide_topico","centella_asiatica","Extracto de Centella Asiática","Centella asiática (madecasósido/asiticósido)",["Madecassol","Centella crema","Cicatricure centella"],
  "Cicatrizante tópico fitoterapéutico",
  "Los triterpenoides (asiticósido, madecasósido, ácido asiático) estimulan la síntesis de colágeno tipo I, aumentan la actividad de fibroblastos, mejoran la resistencia tensil de la cicatriz y modulan la inflamación.",
  ["Heridas superficiales y postquirúrgicas","Quemaduras menores","Úlceras cutáneas","Cicatrización de injertos de piel","Prevención de cicatrices hipertróficas y queloides"],
  ["topica"],
  "Aplicar 1-2 veces/día en herida limpia o cicatriz. Tratamiento prolongado para cicatrices: 3-6 meses",
  ["Crema 1%","Pomada 1%","Polvo cicatrizante"],
  "Compatible.","u09","c09_08",
  familia="Cicatrizantes fitoterapéuticos",
  ci=["Hipersensibilidad a centella asiática"],
  ea=["Dermatitis de contacto (raro)","Sensación de ardor transitorio"],
  ix=["No significativas"],
  ce=["Base científica sólida para estimulación de colágeno","Uso preventivo post-cicatrización: aplicar al menos 3 meses","Compatible con apósitos de silicona para queloides","Aplicar sobre herida cerrada o en fase de remodelación","Producto fitoterapéutico seguro y bien tolerado"],
  emb="B"),

# ══════════════════════════════════════════════════════════════
# c09_09 Queratolíticos y Emolientes (NUEVO)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","acido_salicilico_topico","Ácido Salicílico Tópico","Ácido salicílico",["Duofilm","Salicílico tópico","Collomack"],
  "Queratolítico tópico (beta-hidroxiácido)",
  "Queratolítico que disuelve el cemento intercelular de los corneocitos, facilitando la descamación de la capa córnea engrosada. A concentraciones bajas es queratolítico; a altas concentraciones, cáustico.",
  ["Psoriasis (descamación)","Verrugas vulgares y plantares","Callosidades y hiperqueratosis","Dermatitis seborreica del cuero cabelludo","Acné comedónico"],
  ["topica"],
  "Psoriasis/descamación: 2-6% 1-2 veces/día. Verrugas: 17-40% aplicar diariamente bajo oclusión. Callos: 40% parche",
  ["Solución 2%, 5%, 17%","Crema 2%, 6%","Gel 2%","Parche 40%","Champú 2-3%"],
  "Compatible para uso tópico.","u09","c09_09",
  familia="Queratolíticos tópicos",
  ci=["Hipersensibilidad a salicilatos","No usar en grandes superficies (toxicidad salicílica)","Diabetes con neuropatía (riesgo lesión inadvertida)","Niños <2 años (intoxicación salicílica)"],
  ea=["Irritación y eritema local","Sensación de ardor","Descamación excesiva","Intoxicación salicílica si absorción extensa (tinnitus, náuseas)"],
  ix=["Metotrexato: mayor toxicidad si absorción sistémica","Anticoagulantes: riesgo si absorción extensa"],
  ce=["Concentración según indicación: 2% caspa, 6% psoriasis, 17-40% verrugas","Proteger piel sana circundante con vaselina (efecto cáustico)","Verrugas: remojar antes y limar tejido muerto entre aplicaciones","No usar en grandes extensiones en niños (intoxicación salicílica)","Combina bien con corticoides tópicos en psoriasis"],
  emb="C"),

M("corticoide_topico","urea_topica","Urea Tópica","Urea",["Ureadin","Nutraplus","Eucerin Urea"],
  "Queratolítico e hidratante tópico",
  "A baja concentración (10%): humectante, atrae y retiene agua en el estrato córneo. A alta concentración (20-40%): queratolítico, rompe puentes de hidrógeno entre queratinas, facilitando descamación.",
  ["Xerosis cutánea severa","Ictiosis","Queratosis pilaris","Hiperqueratosis plantar","Psoriasis (coadyuvante)","Eccema crónico seco"],
  ["topica"],
  "Hidratante: 10% 2-3 veces/día. Queratolítico: 20-40% 1-2 veces/día en áreas engrosadas",
  ["Crema 10%, 20%, 30%, 40%","Loción 10%","Ungüento 40%"],
  "Compatible.","u09","c09_09",
  familia="Queratolíticos e hidratantes",
  ci=["Hipersensibilidad","No aplicar en piel erosionada o inflamada aguda (arde)"],
  ea=["Ardor y escozor en piel agrietada","Irritación local","Eritema leve (concentraciones altas)"],
  ix=["Puede aumentar la absorción de otros tópicos aplicados encima"],
  ce=["10% = hidratante; 20%+ = queratolítico (educar al paciente)","Advertir: arde al aplicar en piel agrietada (normal)","Aplicar en piel húmeda post-baño para mayor hidratación","En talones agrietados: 40% bajo oclusión nocturna","Seguro para uso prolongado"],
  emb="A"),

M("corticoide_topico","acido_lactico_topico","Ácido Láctico Tópico","Ácido láctico",["Amlactin","Lactilol","Ácido láctico crema"],
  "Queratolítico e hidratante tópico (alfa-hidroxiácido)",
  "Alfa-hidroxiácido que reduce la cohesión de los corneocitos, promoviendo la renovación epidérmica. Efecto hidratante por capacidad humectante y disminución del pH cutáneo.",
  ["Xerosis cutánea","Ictiosis","Queratosis pilaris","Hiperqueratosis leve","Piel áspera y escamosa"],
  ["topica"],
  "Aplicar 1-2 veces/día en áreas afectadas. Usar sobre piel húmeda post-baño",
  ["Crema 5%, 12%","Loción 5%, 12%"],
  "Compatible.","u09","c09_09",
  familia="Queratolíticos e hidratantes",
  ci=["Hipersensibilidad","Piel erosionada o inflamada aguda"],
  ea=["Ardor y escozor leve","Eritema","Fotosensibilidad","Sequedad paradójica (concentraciones altas)"],
  ix=["Puede aumentar absorción de otros tópicos","Retinoides: mayor irritación si combinación"],
  ce=["Aplicar sobre piel húmeda para mejor absorción","Fotoprotección durante uso (fotosensibilidad)","Menos irritante que ácido glicólico","Ideal para queratosis pilaris (brazos, muslos)","Uso continuo para mantener resultado"],
  emb="B"),

M("corticoide_topico","vaselina_medicinal","Vaselina Medicinal","Petrolato blanco (vaselina)",["Vaselina pura","Vaseline"],
  "Emoliente oclusivo de referencia",
  "Hidrocarburo semisólido altamente oclusivo. Forma una barrera sobre la piel que previene la pérdida transepidérmica de agua (PTEA) hasta en un 98%. Estándar de oro como emoliente oclusivo.",
  ["Xerosis cutánea severa","Protección de barrera cutánea","Dermatitis atópica (coadyuvante emoliente)","Labios agrietados","Protección perilesional","Base de fórmulas magistrales"],
  ["topica"],
  "Aplicar libremente según necesidad. Ideal post-baño sobre piel húmeda. Sin límite de frecuencia",
  ["Vaselina pura 100%","Vaselina medicinal tarro/tubo"],
  "Compatible. Totalmente seguro.","u09","c09_09",
  familia="Emolientes oclusivos",
  ci=["Hipersensibilidad (extremadamente rara)","No usar como lubricante con preservativos de látex (los degrada)"],
  ea=["Foliculitis (si uso oclusivo excesivo)","Comedogenicidad (en piel con acné)","Sensación grasa"],
  ix=["Puede alterar la absorción de otros tópicos"],
  ce=["Emoliente más efectivo y barato disponible","Aplicar sobre piel HÚMEDA post-baño (sella agua)","No comedogénico en la mayoría de pacientes (mito)","Usar como protector perilesional en desbridamiento","Seguro desde neonatos hasta ancianos"],
  emb="A"),

M("corticoide_topico","parafina_liquida","Parafina Líquida","Parafina líquida (aceite mineral)",["Aceite mineral","Aceite de parafina"],
  "Emoliente tópico e hidratante oclusivo",
  "Hidrocarburo líquido que actúa como emoliente oclusivo al crear una capa lipídica sobre la piel, reduciendo la pérdida transepidérmica de agua. Suaviza la capa córnea.",
  ["Xerosis cutánea","Ictiosis","Costra láctea (dermatitis seborreica infantil)","Base de fórmulas magistrales","Eccema seco crónico"],
  ["topica"],
  "Aplicar 2-3 veces/día o según necesidad. Para costra láctea: aplicar, dejar 15-30 min, peinar suavemente",
  ["Aceite mineral puro","Emulsiones con parafina","Combinaciones con lanolina"],
  "Compatible.","u09","c09_09",
  familia="Emolientes oclusivos",
  ci=["Hipersensibilidad (rara)","No inhalar ni ingerir en grandes cantidades"],
  ea=["Foliculitis","Comedogenicidad potencial","Sensación oleosa"],
  ix=["Puede alterar absorción de otros tópicos"],
  ce=["Útil en costra láctea del lactante","Aplicar con masaje suave para facilitar absorción","Evitar uso cerca de fuentes de calor (inflamable como base pura)","Combina bien con urea o ácido láctico","Económico y ampliamente disponible"],
  emb="A"),

M("corticoide_topico","ceramidas","Ceramidas","Ceramidas (1, 3, 6-II)",["CeraVe","Lipikar Baume (combo)","Ceramidas crema"],
  "Emoliente reparador de barrera cutánea",
  "Lípidos esfingoides esenciales del estrato córneo (~50% de los lípidos de barrera). Restauran la función de barrera cutánea alterada en dermatitis atópica, xerosis y eczema. Mejoran la retención de agua y cohesión intercelular.",
  ["Dermatitis atópica (emoliente de primera línea)","Xerosis cutánea","Eczema seco","Restauración de barrera cutánea dañada","Post-procedimientos dermatológicos"],
  ["topica"],
  "Aplicar 2-3 veces/día o según necesidad. Aplicar sobre piel húmeda post-baño",
  ["Crema con ceramidas","Loción con ceramidas","Bálsamo con ceramidas"],
  "Compatible.","u09","c09_09",
  familia="Emolientes reparadores de barrera",
  ci=["Hipersensibilidad a componentes de la formulación"],
  ea=["Irritación local leve (raro)","Eritema (raro)"],
  ix=["Compatible con la mayoría de tratamientos tópicos"],
  ce=["Emoliente de primera línea en dermatitis atópica (guías NICE/AAD)","Restauran la barrera cutánea deficiente en atópicos","Aplicar como base antes de medicamentos tópicos (esperar 15 min)","Uso continuo: mantiene remisión más tiempo","Educar: los emolientes son TRATAMIENTO, no solo cosmética"],
  emb="A"),

M("corticoide_topico","petrolato","Petrolato Amarillo","Petrolato amarillo",["Vaselina amarilla","Petrolato"],
  "Emoliente oclusivo y protector cutáneo",
  "Similar a vaselina blanca pero con mayor contenido de hidrocarburos insaturados. Propiedades oclusivas que previenen la pérdida transepidérmica de agua. Base común en formulaciones magistrales dermatológicas.",
  ["Protección de piel seca y agrietada","Base de fórmulas magistrales","Protección labial","Prevención de dermatitis del pañal","Barrera protectora cutánea"],
  ["topica"],
  "Aplicar según necesidad sobre piel limpia. Sin límite de frecuencia",
  ["Petrolato amarillo puro","Combinaciones en pomadas"],
  "Compatible.","u09","c09_09",
  familia="Emolientes oclusivos",
  ci=["Hipersensibilidad (muy rara)"],
  ea=["Foliculitis","Comedogenicidad potencial","Sensación grasa"],
  ix=["Puede alterar absorción de otros tópicos aplicados encima"],
  ce=["Más económico que vaselina blanca","Puede teñir ligeramente ropa","Base tradicional de formulaciones magistrales","Aplicar en capa fina sobre piel húmeda","Apto para todas las edades"],
  emb="A"),

M("corticoide_topico","coal_tar","Alquitrán de Hulla","Alquitrán de hulla (Coal tar)",["MG217","Neutrogena T/Gel","Polytar"],
  "Antipsoriásico y queratolítico tópico",
  "Mezcla compleja de miles de compuestos. Mecanismo no completamente entendido. Reduce la hiperproliferación de queratinocitos, tiene efecto antiinflamatorio, antipruriginoso y antibacteriano. Uno de los tratamientos más antiguos para psoriasis.",
  ["Psoriasis en placas leve-moderada","Dermatitis seborreica del cuero cabelludo","Eczema crónico","Prurito crónico"],
  ["topica"],
  "Crema/ungüento 1-5%: aplicar 1-2 veces/día. Champú: aplicar, dejar 5-10 min, enjuagar 2-3 veces/semana",
  ["Crema 1%, 2%, 5%","Champú 0.5%, 1%","Solución 2-5%","Ungüento 1-5%"],
  "Compatible con precaución.","u09","c09_09",
  familia="Antipsoriásicos tópicos clásicos",
  ci=["Hipersensibilidad","Psoriasis pustulosa aguda","Piel inflamada aguda o exudativa","Embarazo (relativo)"],
  ea=["Irritación cutánea","Foliculitis","Fotosensibilidad (efecto fotodinámico)","Mal olor","Tinción de ropa y piel","Dermatitis de contacto"],
  ix=["Fototerapia UV: mayor riesgo quemadura (esquema Goeckerman controlado)","Otros irritantes tópicos: mayor irritación"],
  ce=["Tratamiento clásico de psoriasis (eficaz y barato)","Mancha ropa y sábanas (advertir al paciente)","Olor fuerte: barrera para adherencia","Combinación con UVB (Goeckerman): muy eficaz","Fotoprotección post-aplicación (fotosensibiliza)","Inicio lento: 2-4 semanas para mejoría"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_10 Fotoprotectores y Despigmentantes (NUEVO)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","hidroquinona","Hidroquinona","Hidroquinona",["Tri-Luma (combo)","Neostrata HQ","Dermablend HQ"],
  "Despigmentante tópico",
  "Inhibe la tirosinasa, enzima clave en la síntesis de melanina. Reduce la conversión de DOPA a melanina en los melanocitos. Efecto despigmentante gradual.",
  ["Melasma","Hiperpigmentación postinflamatoria","Léntigos solares","Cloasma gravídico (post-parto)"],
  ["topica"],
  "Aplicar capa fina 1-2 veces/día en zona hiperpigmentada. Máximo 4-6 meses continuos. Descanso obligatorio",
  ["Crema 2% (venta libre)","Crema 4% (prescripción)","Gel 4%","Triple combo: HQ 4% + tretinoína + fluocinolona (Tri-Luma)"],
  "No recomendado durante lactancia.","u09","c09_10",
  familia="Despigmentantes tópicos",
  ci=["Hipersensibilidad","Embarazo","Piel irritada o herida","Uso prolongado >6 meses sin descanso"],
  ea=["Irritación local","Eritema","Dermatitis de contacto","Ocronosis exógena (uso prolongado: pigmentación paradójica azul-negruzca)","Fotosensibilidad"],
  ix=["Peróxido de benzoílo: tinción transitoria de piel","Retinoides: mayor irritación (pero mayor eficacia combinados)"],
  ce=["Fotoprotección SPF50+ OBLIGATORIA (el sol revierte efecto)","Máximo 4-6 meses continuos, luego descansar 2-3 meses","Ocronosis: complicación por uso excesivo/prolongado","Resultados visibles en 4-12 semanas","Aplicar SOLO en zona hiperpigmentada (no toda la cara)","Vigilar signos de irritación o paradójico oscurecimiento"],
  emb="C"),

M("corticoide_topico","acido_azelaico","Ácido Azelaico","Ácido azelaico",["Skinoren","Finacea","Azelex"],
  "Despigmentante y antiacneico tópico",
  "Ácido dicarboxílico natural con múltiples mecanismos: inhibe tirosinasa (despigmentante), es antimicrobiano contra C. acnes, antiinflamatorio y normaliza la queratinización folicular.",
  ["Melasma (primera línea en embarazo)","Acné vulgar leve-moderado","Rosácea papulopustulosa","Hiperpigmentación postinflamatoria"],
  ["topica"],
  "Acné/rosácea: gel 15% 2 veces/día. Melasma: crema 20% 2 veces/día. Mejoría en 4-8 semanas",
  ["Crema 20%","Gel 15%"],
  "Compatible. Seguro en embarazo y lactancia.","u09","c09_10",
  familia="Despigmentantes y antiacneicos tópicos",
  ci=["Hipersensibilidad al ácido azelaico"],
  ea=["Ardor y escozor transitorio (frecuente)","Eritema","Descamación","Prurito","Sequedad"],
  ix=["Mínimas interacciones"],
  ce=["SEGURO en embarazo: primera línea para melasma gestacional","Ardor inicial: disminuye con uso continuado","Fotoprotección complementaria siempre","Doble acción: despigmentante + antiacneico","Puede combinarse con retinoides o peróxido de benzoílo","Resultados en 4-8 semanas (paciencia)"],
  emb="B"),

M("corticoide_topico","acido_kojico","Ácido Kójico","Ácido kójico",["Kojic acid cream","Melano Out (combo)"],
  "Despigmentante tópico natural",
  "Metabolito fúngico que inhibe la tirosinasa al quelar el cobre en el sitio activo de la enzima. Reduce la síntesis de melanina. También efecto antioxidante.",
  ["Melasma","Hiperpigmentación postinflamatoria","Léntigos","Tono desigual de piel"],
  ["topica"],
  "Aplicar crema 1-4% 1-2 veces/día en zonas hiperpigmentadas. Uso continuo mínimo 8-12 semanas",
  ["Crema 1%, 2%, 4%","Sérum 1-2%"],
  "Probablemente compatible.","u09","c09_10",
  familia="Despigmentantes tópicos",
  ci=["Hipersensibilidad al ácido kójico","Dermatitis de contacto previa al producto"],
  ea=["Dermatitis de contacto (frecuente: ~10%)","Eritema","Prurito","Sensibilización cutánea"],
  ix=["Puede combinarse con otros despigmentantes (ác. azelaico, vitamina C)"],
  ce=["Alternativa a hidroquinona con menor riesgo de ocronosis","Alta tasa de dermatitis de contacto: vigilar irritación","Fotoprotección obligatoria","Menos potente que hidroquinona pero más seguro a largo plazo","Realizar prueba en zona pequeña antes de uso extenso","Resultados graduales: 8-12 semanas mínimo"],
  emb="C"),

M("corticoide_topico","acido_tranexamico_topico","Ácido Tranexámico Tópico","Ácido tranexámico",["Ác. tranexámico crema","Melasyl (combo)"],
  "Despigmentante tópico (inhibidor de plasmina)",
  "Análogo de lisina que inhibe la activación de plasminógeno en queratinocitos. Reduce la producción de ácido araquidónico y prostaglandinas que estimulan los melanocitos. Inhibe la melanogénesis por vía no tirosinasa.",
  ["Melasma","Hiperpigmentación postinflamatoria","Despigmentación coadyuvante"],
  ["topica"],
  "Aplicar crema/sérum 2-5% 2 veces/día en zonas hiperpigmentadas",
  ["Crema 3%, 5%","Sérum 2%, 5%"],
  "Probablemente compatible.","u09","c09_10",
  familia="Despigmentantes tópicos",
  ci=["Hipersensibilidad al ácido tranexámico"],
  ea=["Irritación local leve","Eritema","Sequedad"],
  ix=["Compatible con la mayoría de despigmentantes","Puede combinarse con vitamina C, niacinamida"],
  ce=["Mecanismo diferente a hidroquinona: complementarios","Buena tolerancia (menos irritante que hidroquinona)","Fotoprotección SPF50+ obligatoria","Puede usarse como coadyuvante de otros despigmentantes","Resultados en 8-12 semanas","También disponible vía oral para melasma (uso off-label)"],
  emb="B"),

M("corticoide_topico","arbutina","Arbutina","Arbutina (alfa-arbutina, beta-arbutina)",["Alpha Arbutin sérum","Ordinary Alpha Arbutin"],
  "Despigmentante tópico natural (derivado de hidroquinona)",
  "Glucósido de hidroquinona que se hidroliza lentamente a hidroquinona en la piel. Inhibe la tirosinasa con menor irritación que la hidroquinona libre. La alfa-arbutina es más estable y potente que la beta.",
  ["Melasma","Hiperpigmentación","Manchas solares","Tono desigual de piel"],
  ["topica"],
  "Aplicar sérum o crema 1-2% 2 veces/día en zonas hiperpigmentadas",
  ["Sérum 1%, 2%","Crema 1-3%"],
  "Probablemente compatible.","u09","c09_10",
  familia="Despigmentantes tópicos naturales",
  ci=["Hipersensibilidad a arbutina o hidroquinona"],
  ea=["Irritación leve (menos que hidroquinona)","Eritema","Dermatitis de contacto (raro)"],
  ix=["Compatible con vitamina C y niacinamida","Evitar con otros despigmentantes agresivos simultáneamente"],
  ce=["Alternativa más suave a hidroquinona","Alfa-arbutina más eficaz que beta-arbutina","Sin riesgo de ocronosis","Fotoprotección obligatoria","Resultados graduales: 8-12 semanas mínimo","Disponible sin prescripción"],
  emb="B"),

M("corticoide_topico","niacinamida_topica","Niacinamida Tópica","Niacinamida (vitamina B3)",["Niacinamide sérum","CeraVe PM","Ordinary Niacinamide"],
  "Despigmentante, antiinflamatorio y regulador sebáceo tópico",
  "Forma amida de la vitamina B3. Inhibe la transferencia de melanosomas de melanocitos a queratinocitos (no inhibe tirosinasa). Mejora la función de barrera cutánea, reduce producción de sebo e inflamación.",
  ["Hiperpigmentación postinflamatoria","Melasma (coadyuvante)","Rosácea","Acné (regulación de sebo)","Envejecimiento cutáneo","Xerosis"],
  ["topica"],
  "Aplicar sérum 5-10% 2 veces/día. Bien tolerado. Sin límite de duración",
  ["Sérum 5%, 10%","Crema 4%, 5%"],
  "Compatible.","u09","c09_10",
  familia="Despigmentantes y protectores cutáneos",
  ci=["Hipersensibilidad a niacinamida (raro)"],
  ea=["Rubor transitorio (raro, diferente de ácido nicotínico)","Irritación leve en concentraciones >10%"],
  ix=["Vitamina C (ácido ascórbico): mito de incompatibilidad desmentido; se pueden combinar","Compatible con retinoides, ác. hialurónico, etc."],
  ce=["Multifuncional: despigmenta, antiinflamatorio, regula sebo, mejora barrera","No causa flush (diferente de niacina/ác. nicotínico)","Muy bien tolerado en la mayoría de pieles","Puede combinarse con casi cualquier activo","Ideal como base de rutina dermatológica","Fotoprotección complementaria"],
  emb="A"),

M("corticoide_topico","filtro_solar_octocrileno","Octocrileno","Octocrileno",["Componente de protectores solares"],
  "Filtro solar químico UVB",
  "Filtro solar orgánico (químico) que absorbe radiación UVB (280-320 nm). Funciona como cromóforo: absorbe fotones UV y los disipa como calor. También estabiliza otros filtros solares fotoinestables (avobenzona).",
  ["Fotoprotección solar","Prevención de quemaduras solares","Prevención de fotoenvejecimiento y cáncer de piel"],
  ["topica"],
  "Aplicar generosamente (2 mg/cm²) 20-30 min antes de exposición solar. Reaplicar cada 2h y tras baño/sudoración",
  ["Presente en fórmulas de protector solar SPF 15-50+"],
  "Compatible.","u09","c09_10",
  familia="Filtros solares químicos",
  ci=["Hipersensibilidad a octocrileno","Alergia a ketoprofeno (reactividad cruzada)"],
  ea=["Dermatitis de contacto fotoalérgica","Eritema local","Prurito","Preocupación ambiental (daño a corales)"],
  ix=["Ketoprofeno: reactividad cruzada alérgica"],
  ce=["Estabiliza avobenzona (protección UVA más duradera)","Aplicar cantidad generosa: la mayoría subaplica","Reaplicar cada 2 horas (se degrada con radiación)","Reactividad cruzada con ketoprofeno: preguntar por alergia","Uso regular reduce riesgo de melanoma y carcinoma"],
  emb="A"),

M("corticoide_topico","filtro_solar_oxibenzona","Oxibenzona","Oxibenzona (benzofenona-3)",["Componente de protectores solares"],
  "Filtro solar químico UVA/UVB",
  "Filtro solar orgánico que absorbe radiación UVA corta (320-340 nm) y UVB (280-320 nm). Cromóforo que convierte energía UV en calor. Uno de los filtros más utilizados históricamente.",
  ["Fotoprotección solar de amplio espectro","Prevención de quemaduras solares"],
  ["topica"],
  "Presente en fórmulas de protección solar. Aplicar como parte del protector 20-30 min antes de exposición. Reaplicar cada 2h",
  ["Presente en protectores solares SPF variable"],
  "Compatible con precaución.","u09","c09_10",
  familia="Filtros solares químicos",
  ci=["Hipersensibilidad a benzofenona","Fotosensibilidad a benzofenona"],
  ea=["Dermatitis de contacto","Reacción fotoalérgica","Absorción sistémica (se detecta en sangre y orina)","Posible alteración endocrina (discutido)","Preocupación ambiental (blanqueo de corales)"],
  ix=["No significativas en uso tópico normal"],
  ce=["Controversia: absorción sistémica y posible efecto endocrino","Prohibido en Hawaii y Palau (daño a arrecifes de coral)","Alternativas: filtros minerales (óxido de zinc, dióxido de titanio)","Si alergia: cambiar a filtros inorgánicos","La fotoprotección sigue siendo esencial independientemente del filtro"],
  emb="C"),

# ══════════════════════════════════════════════════════════════
# c09_11 Fármacos para Alopecia (NUEVO)
# ══════════════════════════════════════════════════════════════
M("corticoide_topico","finasteride_topico","Finasteride Tópico","Finasteride",["Topilutamide","Finasteride spray"],
  "Inhibidor de 5-alfa-reductasa tópico",
  "Inhibe la 5-alfa-reductasa tipo II a nivel local del folículo piloso, reduciendo la conversión de testosterona a dihidrotestosterona (DHT) en el cuero cabelludo. Menores niveles sistémicos que la formulación oral.",
  ["Alopecia androgénica masculina","Alopecia androgénica femenina (off-label)"],
  ["topica"],
  "Aplicar 1 mL (0.25%) 1 vez/día en cuero cabelludo seco. Masajear suavemente",
  ["Solución 0.1%, 0.25%","Spray 0.25%"],
  "No recomendado. Evitar contacto con embarazadas.","u09","c09_11",
  familia="Antiandrógenos tópicos",
  ci=["Mujeres embarazadas o que planean embarazo (teratógeno por absorción)","Hipersensibilidad a finasteride","Niños y adolescentes"],
  ea=["Irritación del cuero cabelludo","Sequedad local","Disfunción sexual (menor incidencia que oral, pero posible)","Disminución de DHT sérica (menor que oral)"],
  ix=["Minoxidil tópico: puede combinarse (efecto sinérgico)","Otros antiandrógenos: efecto aditivo"],
  ce=["Menores efectos sistémicos que finasteride oral","Mujeres embarazadas NO deben manipular el producto","Resultados en 6-12 meses (tratamiento a largo plazo)","Puede combinarse con minoxidil para mayor eficacia","Al suspender: pérdida gradual de beneficio en meses"],
  emb="X"),

M("corticoide_topico","dutasteride_alopecia","Dutasteride para Alopecia","Dutasteride",["Avodart (off-label)","Dutasteride cáps"],
  "Inhibidor dual de 5-alfa-reductasa para alopecia",
  "Inhibe tanto la 5-alfa-reductasa tipo I como tipo II, produciendo una reducción más completa de DHT sérica (>90%) que finasteride (70%). Uso off-label para alopecia androgénica.",
  ["Alopecia androgénica masculina (off-label, segunda línea)"],
  ["oral"],
  "0.5 mg/día oral (uso off-label para alopecia). Vida media muy larga: ~5 semanas",
  ["Cáps 0.5 mg"],
  "Contraindicado (vida media prolongada).","u09","c09_11",
  familia="Inhibidores de 5-alfa-reductasa",
  ci=["Mujeres (teratógeno)","Embarazo o planificación","Hipersensibilidad","Insuficiencia hepática grave","Niños y adolescentes"],
  ea=["Disfunción eréctil","Disminución de libido","Ginecomastia","Trastornos de eyaculación","Depresión (reportes post-comercialización)","PSA reducido (enmascara cáncer de próstata)"],
  ix=["Inhibidores CYP3A4: aumentan niveles","Puede alterar PSA (reducir valor a la mitad para interpretación)"],
  ce=["Uso OFF-LABEL para alopecia (aprobado para HPB)","Vida media 5 semanas: efectos persisten mucho tras suspender","Mujeres embarazadas NO deben manipular cápsulas rotas","Dona sangre: esperar 6 meses tras suspender","PSA: multiplicar x2 para valor real durante tratamiento","Efectos sexuales: informar antes de iniciar"],
  emb="X"),

M("inmunosupresor","baricitinib_alopecia","Baricitinib para Alopecia","Baricitinib",["Olumiant"],
  "Inhibidor de JAK1/JAK2 oral para alopecia areata",
  "Inhibidor oral selectivo de JAK1 y JAK2. En alopecia areata, bloquea la señalización de interferón gamma y otras citocinas que destruyen el folículo piloso. Primer tratamiento sistémico aprobado para alopecia areata grave.",
  ["Alopecia areata grave en adultos"],
  ["oral"],
  "2-4 mg/día oral. Iniciar con 2 mg, escalar a 4 mg si respuesta insuficiente a las 36 semanas",
  ["Comp 1, 2, 4 mg"],
  "No recomendado.","u09","c09_11",
  familia="Inhibidores JAK orales",
  ci=["Hipersensibilidad","Infección activa grave","Linfopenia <500/µL","Neutropenia <1000/µL","Hemoglobina <8 g/dL","Tromboembolismo activo"],
  ea=["Infecciones de vías respiratorias superiores","Cefalea","Acné","Herpes zóster","Hiperlipidemia","Elevación CPK","Tromboembolismo venoso","Eventos cardiovasculares mayores (riesgo en >65 años)"],
  ix=["Inhibidores CYP3A4 potentes: no combinar","Probenecid: aumenta niveles","No combinar con biológicos ni otros JAK-inhibidores","Vacunas vivas: contraindicadas"],
  ce=["Primer fármaco aprobado específicamente para alopecia areata grave","Hemograma, perfil lipídico y función hepática antes y durante","Cribado de TB antes de iniciar","Vigilar herpes zóster (vacunar antes si posible)","Respuesta en 36 semanas: si no responde, considerar dosis de 4 mg","Recidiva frecuente al suspender"],
  emb="X"),

M("inmunosupresor","ritlecitinib","Ritlecitinib","Ritlecitinib",["Litfulo"],
  "Inhibidor de JAK3/TEC oral para alopecia areata",
  "Inhibidor oral irreversible de JAK3 y de la familia de quinasas TEC. Bloquea la señalización de citocinas implicadas en el ataque autoinmune al folículo piloso, especialmente las dependientes de JAK3.",
  ["Alopecia areata moderada a grave (≥12 años)"],
  ["oral"],
  {"adulto":"50 mg/día oral con o sin alimentos","pediatrico":"≥12 años: 50 mg/día"},
  ["Cáps 50 mg"],
  "No recomendado.","u09","c09_11",
  familia="Inhibidores JAK/TEC orales",
  ci=["Hipersensibilidad","Infección activa grave","Linfopenia <500/µL"],
  ea=["Diarrea","Acné","Infecciones de vías respiratorias","Urticaria","Foliculitis","Cefalea","Herpes zóster"],
  ix=["Evitar con otros JAK-inhibidores","Vacunas vivas: contraindicadas durante tratamiento","Precaución con inmunosupresores concomitantes"],
  ce=["Aprobado desde los 12 años (ventaja pediátrica)","Inhibición irreversible de JAK3: mecanismo diferenciador","Hemograma periódico","Vigilar infecciones, especialmente herpes zóster","Resultados evaluables a partir de 24 semanas","No requiere escalada de dosis"],
  emb="X"),

M("inmunosupresor","deuruxolitinib","Deuruxolitinib","Deuruxolitinib",["CTP-543"],
  "Inhibidor selectivo de JAK1/JAK2 oral para alopecia areata",
  "Deuterado de ruxolitinib con mayor estabilidad metabólica. La sustitución de hidrógeno por deuterio mejora la farmacocinética (vida media más larga). Inhibe selectivamente JAK1/JAK2.",
  ["Alopecia areata moderada a grave (en aprobación/ensayos fase III)"],
  ["oral"],
  "8-12 mg 2 veces/día oral (dosis en estudio)",
  ["Comp 8, 12 mg (en desarrollo)"],
  "No recomendado.","u09","c09_11",
  familia="Inhibidores JAK orales",
  ci=["Hipersensibilidad","Infección activa grave","Linfopenia severa","Insuficiencia hepática grave"],
  ea=["Acné","Infecciones de vías respiratorias","Cefalea","Nasofaringitis","Elevación CPK","Herpes zóster"],
  ix=["Inhibidores CYP3A4 potentes: ajustar dosis","Vacunas vivas: contraindicadas","No combinar con otros JAK-inhibidores"],
  ce=["Deuteración: innovación farmacéutica para mejorar farmacocinética","Tasas de respuesta altas en ensayos clínicos","Monitorización hematológica periódica obligatoria","Pendiente de aprobación regulatoria en algunos países","Mismo perfil de seguridad que otros JAK-inhibidores"],
  emb="X"),

M("corticoide_topico","bimatoprost_pestanas","Bimatoprost Pestañas","Bimatoprost",["Latisse","Lumigan (oftálmico)"],
  "Análogo de prostaglandina para crecimiento de pestañas",
  "Análogo sintético de prostaglandina F2-alfa. Prolonga la fase anágena del ciclo del folículo piloso de la pestaña y aumenta el número de pelos en fase de crecimiento. Originalmente desarrollado para glaucoma.",
  ["Hipotricosis de pestañas (pestañas cortas/escasas)","Alopecia de pestañas por quimioterapia (off-label)"],
  ["topica"],
  "Aplicar 1 gota con aplicador desechable en el margen palpebral SUPERIOR cada noche. No aplicar en párpado inferior",
  ["Solución oftálmica 0.03% con aplicadores estériles"],
  "Compatible con precaución.","u09","c09_11",
  familia="Análogos de prostaglandinas (dermatológico)",
  ci=["Hipersensibilidad a bimatoprost","Infección ocular activa","Edema macular"],
  ea=["Hiperpigmentación periocular (reversible)","Irritación ocular","Hiperemia conjuntival","Oscurecimiento del iris (irreversible, raro con aplicación cutánea)","Enoftalmos periorbital"],
  ix=["Otros análogos de prostaglandinas oftálmicas: no combinar","Mínimas interacciones sistémicas"],
  ce=["Aplicar SOLO en párpado superior (borde de pestañas)","Retirar lentes de contacto antes de aplicar","Oscurecimiento del iris: advertir (más frecuente en ojos multicolor)","Resultados visibles en 8-16 semanas","Si se suspende: pestañas regresan a estado basal en semanas/meses","No aplicar en párpado inferior (migración natural del producto)"],
  emb="C"),

M("corticoide_topico","latanoprost_alopecia","Latanoprost para Alopecia","Latanoprost",["Xalatan (off-label)"],
  "Análogo de prostaglandina para alopecia",
  "Análogo de prostaglandina F2-alfa. Prolonga la fase anágena del ciclo capilar. Uso off-label tópico en cuero cabelludo y cejas para estimular crecimiento del pelo.",
  ["Alopecia areata de cejas (off-label)","Alopecia androgénica (off-label, experimental)","Hipotricosis de cejas"],
  ["topica"],
  "Aplicar solución 0.005% 1 vez/día en zona afectada (cejas/cuero cabelludo). Uso off-label",
  ["Solución oftálmica 0.005% (uso redirigido)"],
  "Compatible con precaución.","u09","c09_11",
  familia="Análogos de prostaglandinas (dermatológico)",
  ci=["Hipersensibilidad a latanoprost","Uso ocular con edema macular","Embarazo"],
  ea=["Hiperpigmentación local","Irritación cutánea","Hipertricosis en zonas adyacentes","Oscurecimiento del iris (si contacto ocular frecuente)"],
  ix=["Otros análogos de prostaglandinas: no combinar","Mínimas interacciones sistémicas"],
  ce=["Uso OFF-LABEL para alopecia (aprobado para glaucoma)","Evidencia limitada pero prometedora en alopecia areata de cejas","Aplicar con precisión solo en zona afectada","Resultados lentos: 3-6 meses mínimo","Advertir sobre posible hiperpigmentación periocular","Menor evidencia que bimatoprost para esta indicación"],
  emb="C"),
]

NEW_CHAPTERS = {
    "c09_08": {"id":"c09_08","nombre":"Antisépticos y Cicatrizantes","unidadId":"u09","drugIds":[]},
    "c09_09": {"id":"c09_09","nombre":"Queratolíticos y Emolientes","unidadId":"u09","drugIds":[]},
    "c09_10": {"id":"c09_10","nombre":"Fotoprotectores y Despigmentantes","unidadId":"u09","drugIds":[]},
    "c09_11": {"id":"c09_11","nombre":"Fármacos para Alopecia","unidadId":"u09","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U09: Dermatología ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u09", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
