#!/usr/bin/env python3
"""Add ~70 new drugs for U10 Hematología."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c10_01 Anticoagulantes y Antiagregantes (+15) ──
M("heparina","tinzaparina","Tinzaparina","Tinzaparina",["Innohep"],"HBPM de alto peso molecular",
  "Heparina de bajo peso molecular con relación anti-Xa/anti-IIa intermedia. Mayor peso molecular que otras HBPM",
  ["TVP","TEP","Profilaxis tromboembólica","Anticoagulación en hemodiálisis"],["SC"],
  {"adulto":"Tratamiento: 175 UI/kg/día SC. Profilaxis: 3500-4500 UI/día SC","ajusteRenal":"Precaución si ClCr <30"},
  ["Jer precargada 10000, 14000, 18000 UI"],"Evitar durante lactancia","u10","c10_01",
  pp={"velocidadAdministracion":"SC profunda, alternar sitios","estabilidad":"No requiere refrigeración"}),

M("heparina","nadroparina","Nadroparina","Nadroparina",["Fraxiparine"],"HBPM",
  "HBPM con alta relación anti-Xa/anti-IIa. Buena biodisponibilidad SC",
  ["TVP","TEP","Profilaxis quirúrgica","SCA sin elevación ST"],["SC"],
  {"adulto":"Profilaxis: 2850-5700 UI/día. Tratamiento: 86 UI/kg c/12h"},
  ["Jer precargada 2850, 3800, 5700 UI"],"Evitar durante lactancia","u10","c10_01"),

M("heparina","dalteparina","Dalteparina","Dalteparina",["Fragmin"],"HBPM de elección en cáncer",
  "HBPM con evidencia específica en trombosis asociada a cáncer (estudio CLOT)",
  ["TVP/TEP en cáncer","Profilaxis quirúrgica","SCA"],["SC"],
  {"adulto":"Cáncer: 200 UI/kg/día x30d, luego 150 UI/kg/día. Profilaxis: 2500-5000 UI/día"},
  ["Jer 2500, 5000, 7500, 10000, 12500, 15000, 18000 UI"],"Compatible con precaución","u10","c10_01"),

M("","prasugrel","Prasugrel","Prasugrel",["Effient"],"Antiagregante tienopiridínico de 3ª generación",
  "Profármaco tienopiridínico. Inhibición irreversible P2Y12 más rápida y potente que clopidogrel",
  ["SCA con ICP programada","Post-stent en SCA"],["oral"],
  {"adulto":"Carga: 60 mg. Mantenimiento: 10 mg/día (5 mg si <60 kg)"},
  ["Comp 5, 10 mg"],"Evitar durante lactancia","u10","c10_01",
  ci=["Hemorragia activa","ACV/AIT previo","Insuficiencia hepática grave"],
  ea=["Hemorragia","Anemia","Hematomas","Epistaxis","Hemorragia GI"],
  ix=["Anticoagulantes: mayor sangrado","AINEs: mayor sangrado","Fibrinolíticos: riesgo hemorrágico"],
  ce=["No usar en >75 años ni <60 kg sin ajuste","Suspender 7 días antes de cirugía","Vigilar signos de sangrado","Más potente que clopidogrel"],
  emb="B"),

M("","ticagrelor","Ticagrelor","Ticagrelor",["Brilinta","Brilique"],"Antiagregante inhibidor P2Y12 reversible",
  "Inhibidor directo y reversible del receptor P2Y12. No requiere activación hepática. Inicio rápido",
  ["SCA (con o sin ICP)","Post-IAM mantenimiento"],["oral"],
  {"adulto":"Carga: 180 mg. Mantenimiento: 90 mg c/12h (60 mg c/12h post-IAM >1 año)"},
  ["Comp 60, 90 mg"],"Evitar durante lactancia","u10","c10_01",
  ci=["Hemorragia activa","ACV hemorrágico previo","Insuficiencia hepática moderada-grave"],
  ea=["Hemorragia","Disnea","Bradicardia","Hiperuricemia","Cefalea","Elevación creatinina"],
  ix=["Inhibidores CYP3A4 potentes: contraindicado","Inductores CYP3A4: reducen eficacia","Digoxina: aumenta niveles"],
  ce=["Tomar con o sin alimentos","NO partir ni triturar","Disnea transitoria es esperada (no suspender)","Suspender 5 días antes de cirugía"],
  emb="C"),

M("","cangrelor","Cangrelor","Cangrelor",["Kengrexal"],"Antiagregante P2Y12 IV",
  "Análogo de ATP que bloquea reversiblemente P2Y12. Acción ultrarrápida IV, t½ 3-6 min",
  ["ICP en pacientes no pretratados con inhibidor P2Y12"],["IV"],
  {"adulto":"Bolo 30 mcg/kg, luego infusión 4 mcg/kg/min durante ICP"},
  ["Vial 50 mg"],"Datos insuficientes","u10","c10_01",
  ci=["Hemorragia activa","Hipersensibilidad"],
  ea=["Hemorragia","Disnea","Hematoma en sitio acceso"],
  ix=["Clopidogrel: administrar DESPUÉS de suspender cangrelor","Anticoagulantes: sangrado aditivo"],
  ce=["Solo uso hospitalario en sala de hemodinamia","Efecto cesa en 60 min post-infusión","Transición a P2Y12 oral según protocolo"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con 5 mL agua estéril","dilucion":"Diluir en SF o SG5% hasta 200 mcg/mL","velocidadAdministracion":"Bolo IV seguido de infusión continua","estabilidad":"24h a TA reconstituido"}),

M("","vorapaxar","Vorapaxar","Vorapaxar",["Zontivity"],"Antagonista PAR-1",
  "Primer antagonista del receptor PAR-1 activado por trombina. Inhibición plaquetaria sin afectar coagulación",
  ["Reducción de eventos trombóticos en pacientes con IAM o EAP previo"],["oral"],
  {"adulto":"2.08 mg/día"},["Comp 2.08 mg"],"Evitar durante lactancia","u10","c10_01",
  ci=["ACV/AIT previo","Hemorragia activa","Insuficiencia hepática grave"],
  ea=["Hemorragia","Anemia","Erupción cutánea","Depresión"],
  ix=["Inhibidores CYP3A4 potentes: aumentan niveles","Anticoagulantes: mayor sangrado"],
  ce=["No usar con antecedente de ACV","Efecto antiagregante persiste semanas tras suspensión","Vigilar sangrado activamente"],
  emb="B"),

M("","cilostazol","Cilostazol","Cilostazol",["Pletal"],"Inhibidor de PDE3 con efecto antiagregante y vasodilatador",
  "Inhibe PDE3 en plaquetas y vasos. Efecto antiagregante, vasodilatador y antiproliferativo",
  ["Claudicación intermitente","Enfermedad arterial periférica"],["oral"],
  {"adulto":"100 mg c/12h, 30 min antes o 2h después de alimentos"},
  ["Comp 50, 100 mg"],"Evitar durante lactancia","u10","c10_01",
  ci=["Insuficiencia cardíaca","Hemorragia activa","Predisposición a sangrado"],
  ea=["Cefalea","Diarrea","Palpitaciones","Mareo","Taquicardia"],
  ix=["Inhibidores CYP3A4/CYP2C19: aumentan niveles","Antiagregantes: sangrado aditivo","Jugo de pomelo: aumenta niveles"],
  ce=["Tomar con el estómago vacío","Beneficio se observa en 2-4 semanas","Contraindicado en IC de cualquier grado","Hemograma periódico"],
  emb="C"),

M("","sulodexida","Sulodexida","Sulodexida",["Vessel"],"Mezcla de glucosaminoglucanos (GAG)",
  "Mezcla de heparan sulfato (80%) y dermatan sulfato (20%). Efecto antitrombótico, profibrinolítico y protector endotelial",
  ["Enfermedad venosa crónica","Úlceras venosas","Protección vascular en diabetes"],["oral","IM"],
  {"adulto":"IM: 600 ULS/día x20d. Oral: 250 ULS c/12h mantenimiento"},
  ["Cáps 250 ULS","Amp 600 ULS/2mL"],"Compatible con precaución","u10","c10_01",
  ci=["Diátesis hemorrágica","Hemorragia activa"],
  ea=["Náuseas","Epigastralgia","Diarrea","Erupciones cutáneas"],
  ix=["Anticoagulantes: posible potenciación","AINEs: mayor riesgo sangrado"],
  ce=["Ciclo IM inicial seguido de oral","Tomar cápsulas en ayunas","Tratamiento prolongado habitual"],
  emb="B"),

M("","defibrotida","Defibrotida","Defibrotida",["Defitelio"],"Agente antitrombótico oligonucleotídico",
  "Mezcla de oligonucleótidos derivados de mucosa porcina. Protege endotelio y tiene actividad antitrombótica y fibrinolítica",
  ["Enfermedad venooclusiva hepática (SOS) post-trasplante de células madre"],["IV"],
  {"adulto":"6.25 mg/kg c/6h IV durante mínimo 21 días","pediatrico":"Igual que adulto"},
  ["Vial 200 mg/2.5 mL"],"Datos insuficientes","u10","c10_01",
  ci=["Uso concomitante de anticoagulantes sistémicos","Hemorragia activa"],
  ea=["Hemorragia","Hipotensión","Náuseas","Vómitos","Diarrea"],
  ix=["Anticoagulantes: contraindicado uso concomitante","Trombolíticos: contraindicado"],
  ce=["Monitorizar signos de sangrado","Administrar en infusión de 2h","Suspender anticoagulantes previo al inicio","Uso exclusivo hospitalario"],
  emb="C",
  pp={"dilucion":"Diluir en SF o SG5% hasta concentración 4-20 mg/mL","velocidadAdministracion":"Infusión IV en 2 horas","estabilidad":"24h refrigerado diluido"}),

M("","danaparoide","Danaparoide","Danaparoide",["Orgaran"],"Heparinoide para TIH",
  "Mezcla de heparan sulfato, dermatan sulfato y condroitin sulfato. Actividad anti-Xa sin reactividad cruzada con anticuerpos TIH en >90%",
  ["Trombocitopenia inducida por heparina (TIH)","Profilaxis tromboembólica si alergia a heparinas"],["SC","IV"],
  {"adulto":"SC: 750 U c/12h. IV: bolo 2250 U + infusión 400 U/h x4h, luego titular"},
  ["Amp 750 U/0.6 mL"],"Datos limitados","u10","c10_01",
  ci=["Hemorragia activa","Trombocitopenia severa","Reactividad cruzada confirmada con Ac anti-TIH"],
  ea=["Hemorragia","Hematoma en sitio inyección","Trombocitopenia","Erupción cutánea"],
  ix=["Anticoagulantes: efecto aditivo","AINEs: mayor riesgo sangrado"],
  ce=["Monitorizar anti-Xa para ajuste de dosis IV","Verificar reactividad cruzada antes si posible","No tiene antídoto específico (protamina NO revierte)","Plaquetas diarias inicialmente"],
  emb="B",
  pp={"velocidadAdministracion":"Bolo IV lento, luego infusión continua","estabilidad":"Conservar refrigerado"}),

M("","caplacizumab","Caplacizumab","Caplacizumab",["Cablivi"],"Anti-vWF para PTT",
  "Nanocuerpo (anticuerpo de dominio único) que bloquea interacción vWF-plaquetas. Previene microtrombosis en PTT",
  ["Púrpura trombocitopénica trombótica adquirida (PTTa)"],["SC","IV"],
  {"adulto":"11 mg IV antes de plasmaféresis, luego 11 mg SC/día hasta 30 días post-plasmaféresis"},
  ["Vial 11 mg"],"Datos insuficientes","u10","c10_01",
  ci=["Hipersensibilidad"],
  ea=["Hemorragia","Epistaxis","Sangrado gingival","Cefalea","Urticaria"],
  ix=["Anticoagulantes: mayor riesgo sangrado","Antiagregantes: mayor sangrado"],
  ce=["Primera dosis IV, resto SC","Monitorizar signos de sangrado","Vigilar recaída al suspender","Uso conjunto con plasmaféresis e inmunosupresión"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con 1 mL agua estéril","velocidadAdministracion":"Bolo IV. SC: inyección abdominal","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","iloprost_iv","Iloprost IV","Iloprost",["Ilomedin"],"Análogo de prostaciclina IV",
  "Análogo sintético de prostaciclina (PGI2). Vasodilatador, antiagregante y citoprotector",
  ["Hipertensión pulmonar","Isquemia crítica de miembros","Fenómeno de Raynaud severo"],["IV"],
  {"adulto":"HAP: 0.5-2 ng/kg/min infusión 6h/día. Isquemia: 0.5-2 ng/kg/min x6h durante 14-28 días"},
  ["Amp 20 mcg/mL, 50 mcg/2.5 mL"],"Evitar durante lactancia","u10","c10_01",
  ci=["Hipersensibilidad","Condiciones con alto riesgo de sangrado","Angina inestable","IAM reciente"],
  ea=["Cefalea","Rubor facial","Hipotensión","Náuseas","Dolor mandibular","Diarrea"],
  ix=["Anticoagulantes: mayor sangrado","Antihipertensivos: hipotensión aditiva"],
  ce=["Infusión diaria de 6h en HAP","Monitorizar TA continuamente","Titular gradualmente","Puede causar rubor facial intenso (esperado)"],
  emb="C",
  pp={"dilucion":"Diluir en SF. Concentración según peso","velocidadAdministracion":"Infusión IV continua durante 6 horas","estabilidad":"24h diluido a TA"}),

M("","pentosano_polisulfato","Pentosano polisulfato sódico","Pentosano polisulfato",["Elmiron"],"Heparinoide oral sintético",
  "Polisacárido sulfatado semisintético con actividad anticoagulante débil y efecto protector del urotelio vesical",
  ["Cistitis intersticial/síndrome de vejiga dolorosa"],["oral"],
  {"adulto":"100 mg c/8h con agua, 1h antes o 2h después de alimentos"},
  ["Cáps 100 mg"],"Datos insuficientes","u10","c10_01",
  ci=["Hemorragia activa","Hipersensibilidad"],
  ea=["Alopecia reversible","Diarrea","Náuseas","Cefalea","Maculopatía retiniana (uso prolongado)"],
  ix=["Anticoagulantes: posible potenciación","AINEs: mayor riesgo sangrado"],
  ce=["Efecto terapéutico tarda 3-6 meses","Control oftalmológico periódico (riesgo maculopatía)","Tomar con estómago vacío","Menor riesgo hemorrágico que heparinas"],
  emb="B"),

# ── c10_02 Hemostáticos y Factores (+15) ──
M("","factor_viii_rec","Factor VIII recombinante","Octocog alfa",["Advate","Kogenate"],"Factor de coagulación recombinante",
  "Factor VIII humano producido por tecnología recombinante. Restaura hemostasia en hemofilia A",
  ["Hemofilia A: tratamiento y profilaxis de sangrado"],["IV"],
  {"adulto":"Según nivel objetivo: UI = peso(kg) x incremento deseado(%) x 0.5","pediatrico":"Misma fórmula, puede requerir dosis mayores por mayor volumen distribución"},
  ["Vial 250, 500, 1000, 1500, 2000, 3000 UI"],"Compatible","u10","c10_02",
  ci=["Hipersensibilidad a proteínas de hámster (según producto)"],
  ea=["Desarrollo de inhibidores (anti-FVIII)","Reacciones alérgicas","Cefalea","Fiebre"],
  ix=["No interacciones significativas conocidas"],
  ce=["Verificar presencia de inhibidores periódicamente","Administrar a velocidad ≤10 mL/min","No mezclar con otros fármacos","Registrar lote y dosis exacta","Conservar refrigerado hasta uso"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto, rotar suavemente","velocidadAdministracion":"IV lento, máx 10 mL/min","estabilidad":"3h a TA reconstituido"}),

M("","factor_ix_rec","Factor IX recombinante","Nonacog alfa",["BeneFIX"],"Factor IX recombinante",
  "Factor IX humano recombinante para hemofilia B. Restaura vía intrínseca de coagulación",
  ["Hemofilia B: tratamiento y profilaxis"],["IV"],
  {"adulto":"UI = peso(kg) x incremento deseado(%) x 1.0 (recuperación ~1 UI/dL por UI/kg)","pediatrico":"Puede requerir dosis mayores por mayor aclaramiento"},
  ["Vial 250, 500, 1000, 2000 UI"],"Compatible","u10","c10_02",
  ci=["Hipersensibilidad","CID"],
  ea=["Desarrollo de inhibidores","Reacciones en sitio infusión","Cefalea","Náuseas","Trombosis (raro, dosis altas)"],
  ix=["Ácido aminocaproico: riesgo trombótico si uso conjunto"],
  ce=["Vigilar desarrollo de inhibidores anti-FIX","No exceder velocidad de infusión recomendada","Puede causar reacciones alérgicas graves en inhibidores positivos","Conservar refrigerado"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto","velocidadAdministracion":"IV a velocidad cómoda para el paciente","estabilidad":"3h a TA tras reconstitución"}),

M("","factor_viia_rec","Factor VIIa recombinante","Eptacog alfa",["NovoSeven"],"Factor VIIa activado recombinante",
  "Factor VIIa humano recombinante. Activa vía extrínseca independiente de FVIII/FIX. Para hemofilia con inhibidores",
  ["Hemofilia A/B con inhibidores","Trombastenia de Glanzmann","Hemorragia refractaria"],["IV"],
  {"adulto":"90 mcg/kg c/2-3h hasta hemostasia. Puede ser 270 mcg/kg dosis única"},
  ["Vial 1, 2, 5, 8 mg"],"Datos limitados","u10","c10_02",
  ci=["Hipersensibilidad","Uso en CID no controlada"],
  ea=["Eventos tromboembólicos","Fiebre","Cefalea","Hipertensión","Reacciones en sitio inyección"],
  ix=["Anticoagulantes: efecto impredecible","Antifibrinolíticos: riesgo trombótico"],
  ce=["Uso restringido a centros especializados","Monitorizar eventos trombóticos","Dosis frecuentes: c/2h al inicio","Costo muy elevado: documentar indicación"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto (1.1 mL por mg)","velocidadAdministracion":"Bolo IV en 2-5 minutos","estabilidad":"3h a TA, 24h refrigerado"}),

M("","fibrinogeno_concentrado","Fibrinógeno concentrado","Fibrinógeno humano",["RiaSTAP","Haemocomplettan"],"Concentrado de fibrinógeno derivado de plasma",
  "Fibrinógeno humano purificado. Sustrato final de la cascada de coagulación para formación de fibrina",
  ["Hipofibrinogenemia adquirida (hemorragia masiva, CID)","Afibrinogenemia congénita"],["IV"],
  {"adulto":"Dosis(g) = [nivel objetivo - nivel actual (g/L)] x peso(kg) / 17. Típico: 1-2 g","pediatrico":"Misma fórmula ajustada a peso"},
  ["Vial 1 g"],"Compatible","u10","c10_02",
  ci=["Hipersensibilidad","Trombosis activa (relativa)"],
  ea=["Tromboembolismo","Fiebre","Reacciones alérgicas"],
  ix=["Antifibrinolíticos: riesgo trombótico si fibrinógeno normalizado"],
  ce=["Monitorizar fibrinógeno plasmático pre y post","No exceder 5 mL/min IV","Alternativa rápida a crioprecipitado","Conservar a TA"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con 50 mL agua estéril por vial","velocidadAdministracion":"IV máx 5 mL/min","estabilidad":"8h a TA tras reconstitución"}),

M("","desmopresina_hemat","Desmopresina (hematológica)","Desmopresina",["DDAVP","Octostim"],"Análogo de vasopresina para trastornos hemorrágicos",
  "Análogo sintético de ADH. Libera FVIII y vWF de depósitos endoteliales. No tiene efecto vasopresor significativo",
  ["Hemofilia A leve","Enfermedad de von Willebrand tipo 1","Disfunción plaquetaria urémica"],["IV","SC","nasal"],
  {"adulto":"IV: 0.3 mcg/kg en 30 min. Intranasal: 300 mcg (1 puff cada fosa). Repetir c/12-24h máx 2-3 dosis"},
  ["Amp 4 mcg/mL, 15 mcg/mL","Spray nasal 150 mcg/dosis"],"Compatible con precaución","u10","c10_02",
  ci=["Enfermedad de von Willebrand tipo 2B","Hiponatremia","Polidipsia habitual","Insuficiencia cardíaca"],
  ea=["Hiponatremia dilucional","Cefalea","Rubor facial","Taquicardia","Retención hídrica"],
  ix=["Indometacina: potencia efecto antidiurético","Clorpropamida: hiponatremia aditiva"],
  ce=["Restringir líquidos durante uso (riesgo hiponatremia)","Na+ sérico pre y post","Taquifilaxia tras 2-3 dosis seguidas","30 min antes de procedimiento"],
  emb="B",
  pp={"dilucion":"Diluir en 50 mL SF","velocidadAdministracion":"Infusión IV en 15-30 minutos","estabilidad":"Usar inmediatamente tras dilución"}),

M("","complejo_coag_activado","FEIBA (complejo coagulante anti-inhibidor)","Complejo coagulante anti-inhibidor",["FEIBA"],"Complejo protrombínico activado",
  "Concentrado de factores II, IX, X (mayormente no activados) y VIIa (activado). Bypassa inhibidores de FVIII/FIX",
  ["Hemofilia A/B con inhibidores: tratamiento de sangrado"],["IV"],
  {"adulto":"50-100 U/kg c/6-12h. Máx 200 U/kg/día"},
  ["Vial 500, 1000, 2500 U"],"Datos limitados","u10","c10_02",
  ci=["CID","Hipersensibilidad","Signos de trombosis activa"],
  ea=["Tromboembolismo","CID","Reacciones anafilácticas","Cefalea","Fiebre"],
  ix=["Antifibrinolíticos: NO usar dentro de 6-12h de FEIBA","Emicizumab: riesgo trombótico aumentado"],
  ce=["No usar con ácido tranexámico (riesgo trombosis)","Máx 200 U/kg/día","Infusión lenta: máx 2 U/kg/min","Precaución especial si paciente en emicizumab"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con diluyente provisto","velocidadAdministracion":"Máx 2 U/kg/min","estabilidad":"3h a TA"}),

M("","fitomenadiona_iv","Fitomenadiona IV (Vitamina K1)","Fitomenadiona",["Konakion"],"Vitamina K1 parenteral",
  "Vitamina K1 (filoquinona). Cofactor esencial para síntesis hepática de factores II, VII, IX, X. Revierte efecto de AVK",
  ["Sobredosis de anticoagulantes cumarínicos","Enfermedad hemorrágica del RN","Déficit de vitamina K"],["IV","oral"],
  {"adulto":"INR elevado sin sangrado: 1-2.5 mg oral. Sangrado activo: 5-10 mg IV lento","pediatrico":"RN: 1 mg IM al nacer. Niños: 1-5 mg"},
  ["Amp 10 mg/mL","Gotas orales 20 mg/mL"],"Compatible","u10","c10_02",
  ci=["Hipersensibilidad"],
  ea=["Reacción anafiláctica (IV rápido)","Dolor en sitio inyección","Resistencia transitoria a AVK tras dosis altas"],
  ix=["Anticoagulantes cumarínicos: revierte efecto","Antibióticos: pueden causar déficit de vit K"],
  ce=["IV MUY LENTO: máx 1 mg/min","Vía IV solo si urgencia (preferir oral)","Efecto en 6-12h (oral) o 1-2h (IV)","Puede dificultar reanticoagulación posterior"],
  emb="C",
  pp={"dilucion":"Puede diluir en SG5% si necesario","velocidadAdministracion":"IV MUY LENTO: máx 1 mg/min","estabilidad":"Proteger de la luz"}),

M("","etamsilato","Etamsilato","Etamsilato",["Dicynone"],"Hemostático capilar",
  "Estabiliza membranas capilares y mejora adhesión plaquetaria. No afecta coagulación normal ni causa hipercoagulabilidad",
  ["Hemorragia capilar","Metrorragia","Profilaxis sangrado quirúrgico","Hemorragia intraventricular neonatal"],["oral","IV","IM"],
  {"adulto":"Oral: 500 mg c/6-8h. IV/IM: 250-500 mg c/6-8h","pediatrico":"10-15 mg/kg/día dividido c/6h"},
  ["Comp 250, 500 mg","Amp 250 mg/2mL"],"Compatible","u10","c10_02",
  ci=["Porfiria","Hipersensibilidad","Asma por sulfitos (ampollas)"],
  ea=["Náuseas","Cefalea","Erupción cutánea","Hipotensión (IV rápido)"],
  ix=["Dextrano: antagoniza efecto hemostático","Anticoagulantes: no antagoniza su efecto"],
  ce=["No reemplaza tratamiento de causa de sangrado","IV lento en 2 min","Compatible con ácido tranexámico","Inicio de efecto: 1-2h oral, 5-15 min IV"],
  emb="B",
  pp={"velocidadAdministracion":"IV lento en al menos 2 minutos","estabilidad":"No mezclar con otros fármacos en jeringa"}),

M("","acido_epsilon_aminocaproico","Ácido epsilon-aminocaproico","Ácido aminocaproico",["Amicar"],"Antifibrinolítico",
  "Inhibe activación del plasminógeno. Antifibrinolítico similar al ácido tranexámico pero menos potente",
  ["Hemorragia por hiperfibrinolisis","Profilaxis post-cirugía cardíaca","Sangrado dental en hemofilia"],["oral","IV"],
  {"adulto":"IV: 4-5 g en 1h, luego 1 g/h x8h. Oral: 3 g c/6h","ajusteRenal":"Reducir dosis si IRC"},
  ["Comp 500 mg","Jarabe 250 mg/mL","Amp 5 g/20 mL"],"Compatible con precaución","u10","c10_02",
  ci=["CID activa","Hematuria de vías altas (riesgo obstrucción)","Hipersensibilidad"],
  ea=["Náuseas","Diarrea","Miopatía (uso prolongado)","Trombosis","Hipotensión (IV rápido)"],
  ix=["Estrógenos: riesgo trombótico aditivo","Factor IX concentrado: riesgo trombosis"],
  ce=["No usar en hematuria de origen renal","Monitorizar CPK en uso prolongado","IV lento: hipotensión si rápido","Menos potente que ác. tranexámico (10:1)"],
  emb="C",
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"4-5 g en al menos 1 hora, luego 1 g/h","estabilidad":"24h diluido a TA"}),

M("","trombina_topica","Trombina tópica","Trombina humana/bovina",["Tisseel","Trombina tópica"],"Hemostático tópico",
  "Trombina que convierte fibrinógeno en fibrina localmente. Hemostasia directa en superficies sangrantes",
  ["Hemostasia quirúrgica local","Sangrado en superficies extensas"],["topica"],
  {"adulto":"Aplicar directamente sobre superficie sangrante"},
  ["Vial 1000, 5000 UI polvo + diluyente"],"No aplica (uso tópico)","u10","c10_02",
  ci=["Hipersensibilidad a trombina bovina (si bovina)","No inyectar IV (riesgo trombosis fatal)"],
  ea=["Reacción alérgica local","Formación de anticuerpos anti-trombina bovina"],
  ix=["No interacciones sistémicas significativas"],
  ce=["NUNCA inyectar intravascularmente","Solo uso tópico","Preferir trombina humana recombinante si disponible","Almacenar según producto"],
  emb="B"),

M("","plasma_fresco","Plasma fresco congelado","Plasma humano",["PFC"],"Hemoderivado",
  "Contiene todos los factores de coagulación, albúmina e inmunoglobulinas. Obtenido por fraccionamiento de sangre total",
  ["Coagulopatía con sangrado activo","Reversión urgente de warfarina","CID","PTT (plasmaféresis)","Déficit múltiple de factores"],["IV"],
  {"adulto":"10-15 mL/kg. Repetir según clínica y laboratorio"},
  ["Bolsa 200-300 mL"],"No aplica","u10","c10_02",
  ci=["Déficit selectivo de IgA con anticuerpos anti-IgA","Sobrecarga de volumen","Incompatibilidad ABO"],
  ea=["Reacciones transfusionales","TRALI","Sobrecarga circulatoria (TACO)","Reacciones alérgicas","Transmisión infecciosa residual"],
  ix=["No mezclar con otros hemoderivados en misma línea"],
  ce=["Descongelar a 30-37°C (no microondas)","Transfundir dentro de 24h post-descongelación","Verificar compatibilidad ABO","Vigilar signos de reacción transfusional","Velocidad: 10-20 mL/min"],
  emb="C",
  pp={"velocidadAdministracion":"10-20 mL/min, ajustar según tolerancia","estabilidad":"24h a 2-6°C tras descongelación, 5 días si descongelado a 1-6°C"}),

M("","concentrado_plaquetas","Concentrado de plaquetas","Plaquetas humanas",["CP"],"Hemoderivado plaquetario",
  "Plaquetas concentradas obtenidas por aféresis o de sangre total. Restaura hemostasia primaria",
  ["Trombocitopenia severa con sangrado","Profilaxis si plaquetas <10,000-20,000","Disfunción plaquetaria con sangrado"],["IV"],
  {"adulto":"1 unidad de aféresis o 1 pool (4-6 concentrados). Incremento esperado: 30,000-50,000/pool"},
  ["Pool de 4-6 unidades (~300 mL)","Unidad de aféresis (~200-300 mL)"],"No aplica","u10","c10_02",
  ci=["PTT (relativa: puede empeorar)","PTI (relativa: se destruyen rápidamente)"],
  ea=["Reacciones febriles no hemolíticas","Reacciones alérgicas","Contaminación bacteriana","TRALI","Aloinmunización HLA"],
  ix=["No mezclar con soluciones en misma línea"],
  ce=["NO refrigerar (conservar 20-24°C con agitación)","Transfundir en 30-60 min","NO pasar por filtro de leucorreducción adicional si ya leucorreducido","Verificar conteo plaquetario 1h post-transfusión","Signos vitales cada 15 min"],
  emb="C",
  pp={"velocidadAdministracion":"Transfundir en 30-60 minutos","estabilidad":"5 días a 20-24°C con agitación constante"}),

# ── c10_03 Antianémicos (+10) ──
M("","hierro_dextrano","Hierro dextrano","Hierro dextrano",["INFeD","CosmoFer"],"Hierro parenteral de alto peso molecular",
  "Complejo de hierro-dextrano. Permite administración de dosis total en infusión única. Requiere dosis de prueba",
  ["Anemia ferropénica cuando oral no tolerado o insuficiente","Reposición rápida de hierro"],["IV","IM"],
  {"adulto":"Dosis total según déficit: mg = peso(kg) x (Hb objetivo - Hb actual) x 2.4 + 500. Máx 20 mg/kg","ajusteRenal":"Puede usarse en ERC"},
  ["Amp 50 mg/mL x 2 mL"],"Compatible con precaución","u10","c10_03",
  ci=["Hipersensibilidad al dextrano","Anemia no ferropénica","Sobrecarga de hierro","Primer trimestre embarazo"],
  ea=["Reacción anafiláctica (mayor que otros hierros IV)","Artralgia","Fiebre","Cefalea","Dolor en sitio inyección","Coloración piel IM"],
  ix=["Cloranfenicol: interfiere con respuesta eritropoyética"],
  ce=["OBLIGATORIA dosis de prueba: 25 mg IV en 15 min","Tener adrenalina y equipo RCP disponible","Observar 60 min post-dosis prueba","IM solo en cuadrante superior externo de glúteo (técnica Z)"],
  emb="C",
  pp={"dilucion":"Diluir dosis total en 500 mL SF","velocidadAdministracion":"Infusión test 25 mg en 15 min. Luego infusión total en 4-6h","estabilidad":"Usar inmediatamente tras dilución"}),

M("","hierro_isomaltoside","Hierro isomaltósido","Hierro isomaltósido 1000",["Monofer","Diafer"],"Hierro parenteral de nueva generación",
  "Complejo hierro-isomaltósido con matriz muy estable. Permite dosis altas sin dosis de prueba. Bajo riesgo anafiláctico",
  ["Anemia ferropénica cuando oral insuficiente","Reposición rápida incluyendo dosis total"],["IV"],
  {"adulto":"Hasta 20 mg/kg en infusión única. Típico: 500-2000 mg según déficit"},
  ["Amp 100 mg/mL x 1, 5, 10 mL"],"Compatible con precaución","u10","c10_03",
  ci=["Hipersensibilidad","Sobrecarga de hierro","Anemia no ferropénica"],
  ea=["Náuseas","Reacción de hipersensibilidad","Cefalea","Rubor","Hipofosfatemia (menor que con carboximaltosa)"],
  ix=["Hierro oral: suspender 5 días tras dosis IV"],
  ce=["No requiere dosis de prueba","Infusión rápida posible (15 min para ≤1000 mg)","Monitorizar 30 min post-infusión","Hipofosfatemia menos frecuente vs carboximaltosa"],
  emb="B",
  pp={"dilucion":"Diluir en 100-500 mL SF según dosis","velocidadAdministracion":"≤1000 mg en 15 min. >1000 mg en 30 min","estabilidad":"Usar dentro de 8h tras dilución"}),

M("","ferumoxitol","Ferumoxitol","Ferumoxitol",["Feraheme"],"Hierro parenteral superparamagnético",
  "Nanopartículas superparamagnéticas de óxido de hierro recubiertas de carbohidrato. Captación por macrófagos del SRE",
  ["Anemia ferropénica en ERC","Intolerancia a hierro oral"],["IV"],
  {"adulto":"510 mg IV, repetir 510 mg 3-8 días después (dosis total: 1020 mg)"},
  ["Vial 510 mg/17 mL"],"Datos limitados","u10","c10_03",
  ci=["Hipersensibilidad","Sobrecarga de hierro"],
  ea=["Reacción anafiláctica grave (boxed warning)","Hipotensión","Náuseas","Mareo","Interfiere con RM durante 3 meses"],
  ix=["RM: interfiere con imágenes hasta 3 meses"],
  ce=["Observar 30 min post-infusión (riesgo anafilaxia)","Informar a radiología si paciente necesita RM","Dos dosis separadas 3-8 días","Tener equipo RCP disponible"],
  emb="C",
  pp={"dilucion":"Diluir en 50-200 mL SF o no diluido","velocidadAdministracion":"IV en al menos 15 minutos (no diluido: 1 mL/seg)","estabilidad":"Usar inmediatamente"}),

M("","luspatercept","Luspatercept","Luspatercept",["Reblozyl"],"Agente de maduración eritroide",
  "Proteína de fusión que atrapa ligandos de superfamilia TGF-beta. Promueve maduración eritroide tardía en médula ósea",
  ["Anemia en SMD con sideroblastos en anillo","Beta-talasemia dependiente de transfusiones"],["SC"],
  {"adulto":"SMD: 1 mg/kg SC c/3 semanas, titular hasta 1.75 mg/kg. Talasemia: 1 mg/kg, titular hasta 1.25 mg/kg"},
  ["Vial 25, 75 mg"],"Evitar durante lactancia","u10","c10_03",
  ci=["Embarazo","Hipersensibilidad"],
  ea=["Fatiga","Diarrea","Astenia","Náuseas","Cefalea","Artralgia","Tromboembolismo"],
  ix=["No interacciones significativas conocidas"],
  ce=["Administración SC c/3 semanas","Verificar hemoglobina pre-dosis","Suspender si Hb >12 g/dL sin transfusiones","Riesgo tromboembólico: vigilar"],
  emb="X",
  pp={"reconstitucion":"Reconstituir con agua estéril: 25 mg en 0.68 mL, 75 mg en 1.6 mL","velocidadAdministracion":"SC, rotar sitios","estabilidad":"Usar dentro de 8h de reconstitución"}),

M("","avatrombopag","Avatrombopag","Avatrombopag",["Doptelet"],"Agonista del receptor TPO oral",
  "Agonista del receptor de trombopoyetina (TPO-R). Estimula megacariocitopoyesis y producción plaquetaria",
  ["Trombocitopenia en hepatopatía crónica pre-procedimiento","PTI crónica"],["oral"],
  {"adulto":"Hepatopatía pre-proc: según plaquetas (40-60 mg/día x5 días). PTI: 20 mg/día"},
  ["Comp 20, 40 mg"],"Datos insuficientes","u10","c10_03",
  ci=["Hipersensibilidad","Trombosis activa"],
  ea=["Cefalea","Fatiga","Fiebre","Dolor abdominal","Trombosis portal (en hepatopatía)"],
  ix=["No interacciones clínicamente significativas"],
  ce=["Tomar con alimentos","Plaquetas antes de procedimiento","Vigilar trombosis portal en pacientes hepáticos","No requiere monitorización hepática (ventaja sobre eltrombopag)"],
  emb="C"),

M("","pegfilgrastim","Pegfilgrastim","Pegfilgrastim",["Neulasta"],"G-CSF pegilado de larga acción",
  "Filgrastim conjugado con PEG. Una sola dosis por ciclo de quimioterapia. Aclaramiento mediado por neutrófilos",
  ["Neutropenia febril: reducción de incidencia post-quimioterapia"],["SC"],
  {"adulto":"6 mg SC una vez por ciclo QT, ≥24h post-quimioterapia"},
  ["Jer precargada 6 mg/0.6 mL"],"Datos limitados","u10","c10_03",
  ci=["Hipersensibilidad a filgrastim/pegfilgrastim","No administrar 14 días antes a 24h después de QT"],
  ea=["Dolor óseo","Cefalea","Mialgia","Artralgia","Esplenomegalia","Rotura esplénica (raro)"],
  ix=["Quimioterapia: no administrar dentro de 24h","Litio: puede potenciar leucocitosis"],
  ce=["Dosis ÚNICA por ciclo","Administrar ≥24h post-QT","Hemograma de control","Dolor óseo manejable con analgésicos","Conservar refrigerado"],
  emb="C",
  pp={"velocidadAdministracion":"SC, inyección única","estabilidad":"Refrigerado 2-8°C, 48h a TA"}),

M("","sargramostim","Sargramostim (GM-CSF)","Sargramostim",["Leukine"],"Factor estimulante de colonias granulocito-macrófago",
  "GM-CSF recombinante humano. Estimula proliferación de progenitores mieloides: neutrófilos, monocitos y eosinófilos",
  ["Recuperación mieloide post-trasplante","Fracaso de injerto","Movilización de progenitores"],["IV","SC"],
  {"adulto":"250 mcg/m²/día IV o SC, iniciar 2-4h post-trasplante"},
  ["Vial 250 mcg"],"Datos insuficientes","u10","c10_03",
  ci=["Leucemia mieloide con blastos >10%","Hipersensibilidad a levadura"],
  ea=["Fiebre","Mialgia","Dolor óseo","Disnea","Taquicardia","Derrame pericárdico/pleural"],
  ix=["Corticoides: pueden reducir eficacia","Litio: leucocitosis aditiva"],
  ce=["Hemograma biweekly","Suspender si leucocitos >50,000","Vigilar retención líquidos y derrames","No usar si blastos en MO"],
  emb="C",
  pp={"reconstitucion":"Reconstituir con agua estéril 1 mL","dilucion":"Diluir en SF al menos 10 mcg/mL","velocidadAdministracion":"Infusión IV en 2-4 horas","estabilidad":"6h a TA reconstituido"}),

M("","plerixafor","Plerixafor","Plerixafor",["Mozobil"],"Antagonista CXCR4 para movilización de células madre",
  "Bloquea receptor CXCR4 en células CD34+, liberándolas de médula ósea a sangre periférica. Uso con G-CSF",
  ["Movilización de células madre para trasplante autólogo en linfoma/mieloma"],["SC"],
  {"adulto":"0.24 mg/kg SC, 11h antes de aféresis, junto con G-CSF x4 días previos"},
  ["Vial 24 mg/1.2 mL"],"Evitar durante lactancia","u10","c10_03",
  ci=["Hipersensibilidad","Leucemia (movilizaría células malignas)"],
  ea=["Diarrea","Náuseas","Fatiga","Cefalea","Artralgia","Mareo","Reacción en sitio inyección"],
  ix=["G-CSF: uso combinado obligatorio (sinérgico)"],
  ce=["Administrar exactamente 11h antes de aféresis","Uso con G-CSF (4+ días previos)","Verificar CD34+ en sangre periférica","Máximo 4 dosis por ciclo de movilización"],
  emb="D"),

# ── c10_04 Trastornos de Coagulación Hereditarios (10) ──
M("","emicizumab_profilaxis","Emicizumab profilaxis","Emicizumab",["Hemlibra"],"Anticuerpo biespecífico anti-FIXa/FX",
  "Ac biespecífico que une FIXa y FX, mimando función del FVIII. Profilaxis SC semanal/quincenal/mensual",
  ["Hemofilia A con o sin inhibidores: profilaxis"],["SC"],
  {"adulto":"Carga: 3 mg/kg/sem SC x4 sem. Mantenimiento: 1.5 mg/kg/sem, 3 mg/kg c/2sem o 6 mg/kg c/4sem","pediatrico":"Misma dosis mg/kg"},
  ["Vial 30, 60, 105, 150 mg"],"Datos limitados","u10","c10_04",
  ci=["Hipersensibilidad"],
  ea=["Reacción en sitio inyección","Cefalea","Artralgia","Microangiopatía trombótica (con FEIBA)","Trombosis (con FEIBA)"],
  ix=["FEIBA: riesgo trombótico/MAT grave (limitar dosis)","Pruebas de coagulación: interfiere con TTPa, dosaje FVIII"],
  ce=["NO interfiere con determinaciones de anti-Xa","SÍ interfiere con TTPa y FVIII coagulométrico","Limitar FEIBA a <100 U/kg/24h si rescate","Enseñar autoinyección SC","Conservar refrigerado"],
  emb="C",
  pp={"velocidadAdministracion":"SC, rotando sitios (abdomen, muslo, brazo)","estabilidad":"Refrigerado 2-8°C, 7 días a TA <30°C"}),

M("","fitusiran","Fitusiran","Fitusiran",["Alhemo"],"siRNA contra antitrombina",
  "ARN de interferencia (siRNA) que reduce síntesis hepática de antitrombina, aumentando generación de trombina en hemofilia",
  ["Hemofilia A o B con o sin inhibidores: profilaxis"],["SC"],
  {"adulto":"80 mg SC mensual (2 mg tras trombosis: suspender y reevaluar)"},
  ["Jer precargada 80 mg"],"Datos insuficientes","u10","c10_04",
  ci=["Trombosis activa","Hipersensibilidad"],
  ea=["Trombosis venosa/arterial","Elevación transaminasas","Cefalea","Reacción en sitio inyección"],
  ix=["Anticoagulantes: interacción compleja","Factores de coagulación: ajustar si rescate"],
  ce=["Monitorizar AT niveles y función hepática","Riesgo trombótico: protocolo específico para manejo hemorrágico","Dosis mensual SC","Restringir uso de agentes bypass"],
  emb="X"),

M("","concizumab","Concizumab","Concizumab",["Alhemo cz"],"Anti-TFPI para hemofilia",
  "Anticuerpo monoclonal contra TFPI (inhibidor de la vía del factor tisular). Restaura generación de trombina",
  ["Hemofilia A o B con inhibidores: profilaxis"],["SC"],
  {"adulto":"Dosis de carga seguida de mantenimiento SC diario (según protocolo)"},
  ["Jer precargada"],"Datos insuficientes","u10","c10_04",
  ci=["Trombosis activa","Hipersensibilidad"],
  ea=["Tromboembolismo","Reacción en sitio inyección","Elevación transaminasas"],
  ix=["Anticoagulantes: interacción compleja","Factores de coagulación: ajustar protocolos"],
  ce=["Monitorizar marcadores trombóticos","Protocolo especial para sangrado intercurrente","Administración SC diaria","Programa de acceso restringido"],
  emb="X"),

M("","sutimlimab","Sutimlimab","Sutimlimab",["Enjaymo"],"Anti-C1s para enfermedad por crioaglutininas",
  "Anticuerpo monoclonal que inhibe C1s del complemento clásico. Bloquea hemólisis mediada por complemento",
  ["Enfermedad por crioaglutininas (anemia hemolítica autoinmune por frío)"],["IV"],
  {"adulto":"<75 kg: 6.5 g IV. ≥75 kg: 7.5 g IV. Día 0, 7, luego c/2 semanas"},
  ["Vial 2.5 g/22 mL"],"Datos insuficientes","u10","c10_04",
  ci=["Hipersensibilidad","Infección activa no tratada"],
  ea=["Infecciones (especialmente encapsuladas)","Cefalea","HTA","Reacciones infusionales"],
  ix=["Vacunas vivas: evitar","Mayor susceptibilidad a Neisseria"],
  ce=["Vacunar contra meningococo antes de inicio","Monitorizar hemoglobina y marcadores hemólisis","Infusión cada 2 semanas","Vigilar signos de infección meningocócica"],
  emb="C",
  pp={"dilucion":"No diluir, usar como viene","velocidadAdministracion":"Infusión IV en 1-2 horas","estabilidad":"4h a TA tras abrir"}),

M("","ravulizumab","Ravulizumab","Ravulizumab",["Ultomiris"],"Anti-C5 de larga duración",
  "Anticuerpo monoclonal anti-C5 de nueva generación. Similar a eculizumab pero con dosificación cada 8 semanas",
  ["Hemoglobinuria paroxística nocturna (HPN)","Síndrome hemolítico urémico atípico (SHUa)"],["IV"],
  {"adulto":"Carga según peso (2400-3000 mg), mantenimiento c/8 semanas (3000-3600 mg)"},
  ["Vial 300 mg/3 mL","Vial 1100 mg/11 mL"],"Datos insuficientes","u10","c10_04",
  ci=["Infección meningocócica activa","No vacunado contra meningococo"],
  ea=["Infecciones meningocócicas","Cefalea","Infecciones respiratorias","Náuseas","Artralgia"],
  ix=["Vacunas vivas: precaución","Eculizumab: transición posible"],
  ce=["Vacunación meningocócica OBLIGATORIA ≥2 sem antes","Antibiótico profiláctico si vacuna reciente","Infusión c/8 semanas (vs c/2 de eculizumab)","Monitorizar LDH y hemólisis"],
  emb="C",
  pp={"dilucion":"Diluir en SF hasta concentración final según peso","velocidadAdministracion":"Primera dosis en 1.7h mínimo. Mantenimiento en 2h","estabilidad":"24h refrigerado diluido"}),

M("","eculizumab_hemat","Eculizumab (hematológico)","Eculizumab",["Soliris"],"Anti-C5 para HPN/SHUa",
  "Anticuerpo monoclonal humanizado anti-C5. Bloquea formación del complejo de ataque de membrana (C5b-9)",
  ["HPN","SHUa","Miastenia gravis refractaria","Neuromielitis óptica"],["IV"],
  {"adulto":"HPN: 600 mg/sem x4, luego 900 mg c/2 sem. SHUa: 900 mg/sem x4, luego 1200 mg c/2 sem"},
  ["Vial 300 mg/30 mL"],"Datos insuficientes","u10","c10_04",
  ci=["Infección meningocócica activa","No vacunado contra meningococo","Hipersensibilidad"],
  ea=["Infecciones meningocócicas","Cefalea","HTA","Infecciones vías respiratorias","Leucopenia"],
  ix=["Vacunas vivas: precaución"],
  ce=["Vacuna meningocócica OBLIGATORIA mín 2 sem antes","Vigilar signos de meningitis","Infusión bisemanal de por vida","Costo muy elevado: programa de acceso"],
  emb="C",
  pp={"dilucion":"Diluir dosis en 120 mL SF por gravedad","velocidadAdministracion":"Infusión IV mínimo 35 minutos","estabilidad":"24h a 2-8°C diluido"}),

M("","iptacopan","Iptacopan","Iptacopan",["Fabhalta"],"Inhibidor oral del factor B del complemento",
  "Primer inhibidor oral del factor B del complemento. Bloquea la vía alternativa proximal",
  ["HPN en adultos con hemólisis residual bajo anti-C5 o como monoterapia"],["oral"],
  {"adulto":"200 mg c/12h"},["Cáps 200 mg"],"Datos insuficientes","u10","c10_04",
  ci=["Infección meningocócica activa","Hipersensibilidad"],
  ea=["Infecciones","Cefalea","Diarrea","Dolor abdominal","Artralgia"],
  ix=["No interacciones CYP significativas conocidas"],
  ce=["Primera terapia oral para HPN","Vacunación meningocócica previa","Monitorizar hemólisis (LDH, reticulocitos)","Puede usarse como monoterapia o add-on"],
  emb="X"),

# ── c10_05 Terapias para Enfermedades Mieloproliferativas (10) ──
M("","ruxolitinib_hemat","Ruxolitinib (hematológico)","Ruxolitinib",["Jakavi","Jakafi"],"Inhibidor de JAK1/JAK2",
  "Inhibidor selectivo de JAK1 y JAK2. Reduce esplenomegalia y síntomas constitucionales en mielofibrosis",
  ["Mielofibrosis (primaria o post-PV/TE)","Policitemia vera resistente/intolerante a hidroxiurea"],["oral"],
  {"adulto":"MF: 5-20 mg c/12h según plaquetas. PV: 10 mg c/12h"},
  ["Comp 5, 10, 15, 20 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Hipersensibilidad"],
  ea=["Anemia","Trombocitopenia","Neutropenia","Hematomas","Mareo","Cefalea","Infecciones","Aumento peso"],
  ix=["Inhibidores CYP3A4 potentes: reducir dosis","Fluconazol: reducir dosis 50%","Inductores CYP3A4: pueden reducir eficacia"],
  ce=["Hemograma c/2-4 semanas inicialmente","No suspender bruscamente (rebote de síntomas)","Ajustar según plaquetas","Vigilar infecciones oportunistas (herpes zoster)"],
  emb="C"),

M("","fedratinib","Fedratinib","Fedratinib",["Inrebic"],"Inhibidor selectivo de JAK2",
  "Inhibidor selectivo de JAK2 con actividad sobre FLT3. Segunda línea en mielofibrosis",
  ["Mielofibrosis intermedia-2 o alto riesgo"],["oral"],
  {"adulto":"400 mg/día con alimentos"},["Cáps 100 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Hipersensibilidad","Tiamina <normal (riesgo encefalopatía Wernicke)"],
  ea=["Diarrea","Náuseas","Vómitos","Anemia","Trombocitopenia","Encefalopatía de Wernicke (raro)"],
  ix=["Inhibidores CYP3A4 potentes: reducir dosis","Inhibidores CYP2C19: precaución"],
  ce=["Verificar tiamina ANTES de iniciar y mensualmente","Hemograma frecuente","Tomar con alimentos","Vigilar signos neurológicos de Wernicke"],
  emb="D"),

M("","anagrelida","Anagrelida","Anagrelida",["Agrylin","Xagrid"],"Reductor plaquetario específico",
  "Inhibe maduración de megacariocitos. Reduce plaquetas sin efecto sobre otras líneas celulares",
  ["Trombocitemia esencial","Trombocitosis en neoplasias mieloproliferativas"],["oral"],
  {"adulto":"Inicio: 0.5 mg c/12h. Ajustar según plaquetas. Máx 10 mg/día"},
  ["Cáps 0.5, 1 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Insuficiencia cardíaca","Insuficiencia hepática grave","Insuficiencia renal grave (ClCr <30)"],
  ea=["Palpitaciones","Cefalea","Diarrea","Astenia","Edema","Taquicardia","Retención hídrica"],
  ix=["Inhibidores PDE3: efecto inotrópico aditivo","Aspirina: mayor riesgo sangrado en dosis altas"],
  ce=["Hemograma semanal primera semana, luego c/2 sem","ECG basal (efecto inotrópico)","Descenso gradual de plaquetas en 7-14 días","Objetivo: plaquetas <600,000"],
  emb="X"),

M("","dasatinib","Dasatinib","Dasatinib",["Sprycel"],"Inhibidor BCR-ABL de 2ª generación",
  "Inhibidor multicinasa BCR-ABL/SRC 325 veces más potente que imatinib in vitro. Activo contra mutaciones resistentes excepto T315I",
  ["LMC en fase crónica, acelerada o blástica","LLA Ph+ refractaria/intolerante a imatinib"],["oral"],
  {"adulto":"LMC crónica: 100 mg/día. Avanzada: 140 mg/día"},
  ["Comp 20, 50, 70, 80, 100, 140 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Hipersensibilidad","Embarazo"],
  ea=["Mielosupresión","Derrame pleural","Diarrea","Cefalea","Fatiga","Edema","Prolongación QT","Hemorragia"],
  ix=["Inhibidores CYP3A4: aumentan niveles","Inductores CYP3A4: reducen niveles","Antiácidos: reducen absorción (separar 2h)"],
  ce=["Hemograma semanal x2 meses, luego mensual","Vigilar derrames pleurales (disnea, tos)","No triturar comprimidos","Monitorización citogenética trimestral"],
  emb="D"),

M("","nilotinib","Nilotinib","Nilotinib",["Tasigna"],"Inhibidor BCR-ABL de 2ª generación",
  "Inhibidor BCR-ABL 30 veces más potente que imatinib. Buena actividad contra mutaciones excepto T315I",
  ["LMC en fase crónica o acelerada","Resistencia/intolerancia a imatinib"],["oral"],
  {"adulto":"Nuevo diagnóstico: 300 mg c/12h. 2ª línea: 400 mg c/12h. En AYUNAS (2h pre y 1h post comida)"},
  ["Cáps 50, 150, 200 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Hipersensibilidad","Hipopotasemia/hipomagnesemia no corregida","Prolongación QTc","Síndrome QT largo congénito"],
  ea=["Mielosupresión","Prolongación QT","Erupción cutánea","Cefalea","Náuseas","Hiperglucemia","Eventos vasculares oclusivos"],
  ix=["Inhibidores CYP3A4 potentes: contraindicado","Inductores CYP3A4: reducen eficacia","Fármacos que prolongan QT: riesgo aditivo","Jugo pomelo: contraindicado"],
  ce=["Tomar en AYUNAS estricto","ECG basal y periódico (QTc)","Electrolitos (K+, Mg2+) antes y durante","Monitorizar glucemia, lipasa y perfil lipídico","Vigilar eventos vasculares (EAP, IC, ACV)"],
  emb="D"),

M("","ponatinib","Ponatinib","Ponatinib",["Iclusig"],"Inhibidor BCR-ABL de 3ª generación",
  "Único inhibidor activo contra mutación T315I. Pan-inhibidor BCR-ABL de 3ª generación",
  ["LMC/LLA Ph+ con mutación T315I","Resistencia a ≥2 inhibidores previos"],["oral"],
  {"adulto":"45 mg/día (puede reducirse a 30 o 15 mg según respuesta y tolerancia)"},
  ["Comp 15, 30, 45 mg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Hipersensibilidad","Embarazo"],
  ea=["Eventos trombóticos arteriales (IAM, ACV, EAP)","HTA","Pancreatitis","Mielosupresión","Erupción","Hepatotoxicidad"],
  ix=["Inhibidores CYP3A4 potentes: reducir dosis","Inductores CYP3A4: evitar","IBP: no afectan significativamente"],
  ce=["Control cardiovascular estricto (alto riesgo trombótico)","TA objetivo <130/80","Lipasa mensual (pancreatitis)","Menor dosis eficaz tras respuesta","Restringido a T315I o ≥3ª línea"],
  emb="D"),

M("","interferón_alfa_mpn","Interferón alfa (NMP)","Interferón alfa-2b",["IntronA (NMP)"],"Interferón para neoplasias mieloproliferativas",
  "Citocina con efecto antiproliferativo y pro-apoptótico sobre clon mieloproliferativo. Puede lograr respuestas moleculares",
  ["Policitemia vera","Trombocitemia esencial (especialmente jóvenes y embarazadas)"],["SC"],
  {"adulto":"3 MUI SC 3 veces/semana, titular según respuesta"},
  ["Vial 3, 5, 10 MUI"],"Evitar durante lactancia","u10","c10_05",
  ci=["Depresión severa/ideación suicida","Hepatitis autoinmune","Enfermedad tiroidea no controlada","Hepatopatía descompensada"],
  ea=["Síndrome gripal","Depresión","Fatiga","Mialgia","Citopenias","Tiroiditis","Hepatotoxicidad"],
  ix=["Teofilina: aumenta niveles","Zidovudina: mielosupresión aditiva"],
  ce=["Evaluación psiquiátrica previa","Función tiroidea trimestral","Hemograma frecuente","Administrar por la noche para minimizar síndrome gripal","Paracetamol pre-dosis"],
  emb="C"),

M("","ropeginterferon","Ropeginterferón alfa-2b","Ropeginterferón alfa-2b",["Besremi"],"Interferón pegilado de larga acción para PV",
  "Interferón alfa-2b con mono-PEGilación. Dosificación cada 2-4 semanas. Aprobado para policitemia vera",
  ["Policitemia vera sin esplenomegalia sintomática"],["SC"],
  {"adulto":"Inicio: 100 mcg SC c/2 sem. Titular hasta 500 mcg c/2 sem según respuesta. Puede espaciar a c/4 sem"},
  ["Jer precargada 250, 500 mcg"],"Evitar durante lactancia","u10","c10_05",
  ci=["Depresión severa","Hepatitis autoinmune","Tiroides no controlada","Hipersensibilidad a interferones"],
  ea=["Síndrome gripal","Artralgia","Fatiga","Mialgia","Prurito","Elevación transaminasas","Depresión"],
  ix=["Teofilina: aumenta niveles","Mielosupresores: efecto aditivo"],
  ce=["Ventaja: dosificación quincenal o mensual","Monitorizar hematocrito, plaquetas y leucocitos","Función tiroidea cada 3-6 meses","Respuesta molecular posible a largo plazo","Autoinyección SC enseñar al paciente"],
  emb="X"),
]

NEW_CHAPTERS = {
    "c10_04": {
        "id": "c10_04",
        "nombre": "Trastornos de Coagulación Hereditarios",
        "drugIds": ["emicizumab_profilaxis","fitusiran","concizumab","sutimlimab","ravulizumab","eculizumab_hemat","iptacopan"]
    },
    "c10_05": {
        "id": "c10_05",
        "nombre": "Neoplasias Mieloproliferativas",
        "drugIds": ["ruxolitinib_hemat","fedratinib","anagrelida","dasatinib","nilotinib","ponatinib","interferón_alfa_mpn","ropeginterferon"]
    },
}

if __name__ == "__main__":
    print("=== U10 ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        add_chapter(cats, "u10", ch)
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
