#!/usr/bin/env python3
"""Supplement batch: U03 Antiinfecciosos (+50) and U04 Respiratorio (+36)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

# ══════════════════════════════════════════════════════════════════════
# U03 — ANTIINFECCIOSOS SUPLEMENTO (+50)
# ══════════════════════════════════════════════════════════════════════

u03_drugs = [
    # ── Penicilinas adicionales ──
    M("penicilina", "penicilina_v", "Penicilina V", "fenoximetilpenicilina",
      ["Pen-V-K", "Ospen", "V-Cillin"], "Penicilina natural oral",
      "Inhibe síntesis de pared celular bacteriana uniéndose a PBPs",
      ["Faringitis estreptocócica", "Profilaxis fiebre reumática", "Infecciones leves por Gram+"],
      ["Oral"], {"adulto": "250-500 mg c/6h", "pediatrico": "25-50 mg/kg/día dividido c/6-8h"},
      ["Tab 250 mg", "Tab 500 mg", "Susp 125 mg/5 mL"], "Compatible con precaución",
      "u03", "c03_01"),

    M("penicilina", "penicilina_benzatinica", "Penicilina Benzatínica", "bencilpenicilina benzatínica",
      ["Benzetacil", "Bicillin"], "Penicilina natural IM de depósito",
      "Liberación lenta desde depósito IM; inhibe síntesis de pared celular",
      ["Sífilis en todos los estadios", "Profilaxis fiebre reumática", "Faringitis estreptocócica"],
      ["Intramuscular"], {"adulto": "1.2-2.4 MUI IM dosis única o semanal", "pediatrico": "600,000-1.2 MUI IM"},
      ["Jer 600,000 UI", "Jer 1,200,000 UI", "Jer 2,400,000 UI"], "Compatible",
      "u03", "c03_01",
      ce=["Administrar SOLO vía IM profunda en glúteo", "NUNCA administrar IV (embolia fatal)", "Aspirar antes de inyectar", "Paciente en observación 30 min post-inyección", "Verificar alergia a penicilina"]),

    M("penicilina", "penicilina_procainica", "Penicilina Procaínica", "bencilpenicilina procaínica",
      ["Penprocilina", "Wycillin"], "Penicilina natural IM de acción intermedia",
      "Liberación sostenida desde depósito IM con procaína",
      ["Infecciones moderadas por estreptococos", "Neumonía neumocócica", "Sífilis"],
      ["Intramuscular"], "600,000-1,200,000 UI/día IM",
      ["Fco 400,000 UI", "Fco 800,000 UI"], "Compatible",
      "u03", "c03_01"),

    M("penicilina", "sultamicilina", "Sultamicilina", "sultamicilina",
      ["Unasyn Oral", "Sulbamox"], "Penicilina + inhibidor de betalactamasa oral",
      "Profármaco de ampicilina + sulbactam; amplio espectro incluyendo productores de betalactamasa",
      ["Sinusitis", "Otitis media", "ITU no complicada", "Infecciones de piel"],
      ["Oral"], {"adulto": "375-750 mg c/12h", "pediatrico": "25-50 mg/kg/día dividido c/12h"},
      ["Tab 375 mg", "Susp 250 mg/5 mL"], "Compatible con precaución",
      "u03", "c03_01"),

    # ── Cefalosporinas adicionales ──
    M("cefalosporina", "cefprozil", "Cefprozil", "cefprozil",
      ["Cefzil", "Procef"], "Cefalosporina de 2ª generación oral",
      "Inhibe síntesis de pared celular; espectro similar a cefuroxima oral",
      ["Faringitis", "Otitis media", "Sinusitis", "Infecciones cutáneas"],
      ["Oral"], {"adulto": "250-500 mg c/12h", "pediatrico": "15 mg/kg c/12h"},
      ["Tab 250 mg", "Tab 500 mg", "Susp 125 mg/5 mL"], "Compatible con precaución",
      "u03", "c03_02"),

    M("cefalosporina", "ceftibuten", "Ceftibuten", "ceftibuten",
      ["Cedax", "Ceftiben"], "Cefalosporina de 3ª generación oral",
      "Inhibe PBPs con alta estabilidad frente a betalactamasas",
      ["ITU", "Otitis media", "Faringitis", "Bronquitis aguda"],
      ["Oral"], {"adulto": "400 mg c/24h", "pediatrico": "9 mg/kg/día c/24h"},
      ["Cáps 400 mg", "Susp 90 mg/5 mL"], "Compatible con precaución",
      "u03", "c03_02"),

    M("cefalosporina", "cefditoren", "Cefditoren", "cefditoren pivoxilo",
      ["Spectracef", "Meiact"], "Cefalosporina de 3ª generación oral",
      "Inhibe PBPs con alta afinidad por PBP2; activo contra neumococos resistentes",
      ["Neumonía comunitaria", "Faringitis", "Infecciones cutáneas no complicadas"],
      ["Oral"], "200-400 mg c/12h con alimentos",
      ["Tab 200 mg", "Tab 400 mg"], "Evitar",
      "u03", "c03_02"),

    M("cefalosporina", "cefoperazona_sulbactam", "Cefoperazona/Sulbactam", "cefoperazona + sulbactam",
      ["Sulperazon", "Cefobid-Sulbactam"], "Cefalosporina 3ª gen + inhibidor betalactamasa IV",
      "Cefoperazona inhibe PBPs; sulbactam inhibe betalactamasas ampliando espectro",
      ["Infecciones intraabdominales", "Sepsis", "Infecciones respiratorias graves", "Peritonitis"],
      ["Intravenosa"], "1-2 g c/12h IV",
      ["Fco 1 g + 1 g", "Fco 2 g + 2 g"], "Evitar",
      "u03", "c03_02",
      pp={"dilucion": "En 100 mL SF o SG5%", "velocidadAdministracion": "Infusión en 30-60 min", "estabilidad": "24h refrigerado reconstituido"}),

    # ── Carbapenémicos/combos ──
    M("cefalosporina", "imipenem_relebactam", "Imipenem/Cilastatina/Relebactam", "imipenem + cilastatina + relebactam",
      ["Recarbrio"], "Carbapenem + inhibidor de betalactamasa clase A/C",
      "Imipenem inhibe PBPs; relebactam inhibe betalactamasas clase A y C incluyendo KPC",
      ["Infecciones por Gram- resistentes a carbapenems", "Neumonía nosocomial", "ITU complicada", "Infección intraabdominal"],
      ["Intravenosa"], "1.25 g (imipenem 500/cilastatina 500/relebactam 250) c/6h",
      ["Fco 500/500/250 mg"], "Evitar",
      "u03", "c03_02",
      familia="Carbapenémicos + inhibidor betalactamasa",
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión IV en 30 min", "estabilidad": "2h a temperatura ambiente"}),

    M("cefalosporina", "aztreonam_avibactam", "Aztreonam/Avibactam", "aztreonam + avibactam",
      ["Emblaveo"], "Monobactam + inhibidor de betalactamasa",
      "Aztreonam inhibe PBP3; avibactam inhibe serina-betalactamasas incluyendo MBL",
      ["Infecciones por Gram- productores de metalo-betalactamasas", "Neumonía nosocomial grave"],
      ["Intravenosa"], "Aztreonam 2g + avibactam 500mg c/6h",
      ["Fco aztreonam 2 g + avibactam 500 mg"], "Evitar",
      "u03", "c03_02",
      familia="Monobactam + inhibidor betalactamasa",
      pp={"dilucion": "En 250 mL SF", "velocidadAdministracion": "Infusión IV en 2h", "estabilidad": "12h refrigerado"}),

    # ── Aminoglucósidos ──
    M("cefalosporina", "kanamicina", "Kanamicina", "kanamicina",
      ["Kantrex"], "Aminoglucósido",
      "Inhibe síntesis proteica al unirse irreversiblemente a subunidad 30S ribosomal",
      ["Tuberculosis multirresistente", "Infecciones graves por Gram-"],
      ["Intramuscular", "Intravenosa"], "15 mg/kg/día IM o IV",
      ["Fco 1 g", "Fco 500 mg"], "Contraindicada",
      "u03", "c03_03",
      familia="Aminoglucósidos",
      ci=["Hipersensibilidad a aminoglucósidos", "Miastenia gravis", "Insuficiencia renal grave"],
      ea=["Ototoxicidad (vestibular y coclear)", "Nefrotoxicidad", "Bloqueo neuromuscular", "Parestesias"],
      ix=["Otros aminoglucósidos: toxicidad aditiva", "Diuréticos de asa: ototoxicidad", "Cefalosporinas: nefrotoxicidad aditiva"],
      ce=["Monitorizar niveles séricos", "Función renal y audiometría periódicas", "Hidratar adecuadamente", "No mezclar con penicilinas en misma jeringa"]),

    M("cefalosporina", "amikacina_inhalada", "Amikacina Inhalada", "amikacina liposomal inhalada",
      ["Arikayce"], "Aminoglucósido liposomal inhalado",
      "Aminoglucósido en liposomas para liberación pulmonar sostenida",
      ["Infección pulmonar por Mycobacterium avium complex (MAC) refractaria"],
      ["Inhalatoria"], "590 mg inhalado 1 vez/día",
      ["Susp inhalación 590 mg/8.4 mL"], "Contraindicada",
      "u03", "c03_03",
      familia="Aminoglucósidos inhalados"),

    M("cefalosporina", "spectinomicina", "Espectinomicina", "espectinomicina",
      ["Trobicin"], "Aminociclitol",
      "Inhibe síntesis proteica al unirse a subunidad 30S ribosomal",
      ["Gonorrea no complicada (alternativa en alergia a cefalosporinas)"],
      ["Intramuscular"], "2 g IM dosis única",
      ["Fco 2 g"], "Compatible con precaución",
      "u03", "c03_03",
      familia="Aminociclitoles"),

    # ── Otros antibacterianos ──
    M("antituberculoso", "rifabutina", "Rifabutina", "rifabutina",
      ["Mycobutin"], "Rifamicina semisintética",
      "Inhibe ARN polimerasa bacteriana; menor inducción CYP450 que rifampicina",
      ["Profilaxis MAC en VIH", "TB en pacientes con interacciones con rifampicina", "Infección por H. pylori refractaria"],
      ["Oral"], "300 mg/día",
      ["Cáps 150 mg"], "Evitar",
      "u03", "c03_04",
      familia="Rifamicinas"),

    M("antituberculoso", "rifapentina", "Rifapentina", "rifapentina",
      ["Priftin"], "Rifamicina de acción prolongada",
      "Inhibe ARN polimerasa bacteriana con vida media más larga que rifampicina",
      ["TB latente (régimen 3HP)", "TB activa fase de continuación"],
      ["Oral"], "900 mg semanal (con isoniazida) x12 dosis; o 600 mg bisemanal",
      ["Tab 150 mg"], "Contraindicada",
      "u03", "c03_04",
      familia="Rifamicinas"),

    M("antituberculoso", "dapsona_lepra", "Dapsona", "dapsona",
      ["Avlosulfon", "Dapsone"], "Sulfona antileprosa",
      "Inhibe síntesis de ácido fólico bacteriano; actividad contra M. leprae y P. jirovecii",
      ["Lepra (esquema multidroga OMS)", "Profilaxis Pneumocystis jirovecii", "Dermatitis herpetiforme"],
      ["Oral"], "100 mg/día",
      ["Tab 25 mg", "Tab 100 mg"], "Compatible con precaución",
      "u03", "c03_04",
      familia="Sulfonas",
      ci=["Hipersensibilidad", "Anemia severa", "Déficit de G6PD grave"],
      ea=["Hemólisis (especialmente en déficit G6PD)", "Metahemoglobinemia", "Agranulocitosis", "Neuropatía periférica", "Síndrome de hipersensibilidad a dapsona"],
      ce=["Hemograma basal y mensual primeros 3 meses", "Vigilar metahemoglobinemia (cianosis labial)", "Determinar G6PD antes de iniciar", "Tratamiento prolongado (mínimo 12 meses en lepra)"]),

    M("quinolona", "prulifloxacino", "Prulifloxacino", "prulifloxacino",
      ["Unidrox", "Chinoplus"], "Fluoroquinolona oral",
      "Profármaco de ulifloxacino; inhibe ADN girasa y topoisomerasa IV bacteriana",
      ["ITU no complicada", "Gastroenteritis bacteriana", "Prostatitis crónica"],
      ["Oral"], "600 mg dosis única o c/24h x3-5 días",
      ["Tab 600 mg"], "Contraindicada",
      "u03", "c03_03"),

    # ── Antivirales ──
    M("antirretroviral", "famciclovir", "Famciclovir", "famciclovir",
      ["Famvir", "Oravir"], "Antiviral análogo nucleosídico (profármaco de penciclovir)",
      "Se convierte en penciclovir; inhibe ADN polimerasa viral del herpes",
      ["Herpes zóster", "Herpes genital recurrente", "Herpes labial"],
      ["Oral"], {"adulto": "Zóster: 500 mg c/8h x7d; Genital: 250 mg c/12h x5d"},
      ["Tab 125 mg", "Tab 250 mg", "Tab 500 mg"], "Evitar",
      "u03", "c03_06",
      familia="Antivirales antiherpéticos",
      ci=["Hipersensibilidad a famciclovir o penciclovir"],
      ea=["Cefalea", "Náuseas", "Diarrea", "Mareo", "Fatiga"],
      ix=["Probenecid: aumenta niveles de penciclovir", "Raloxifeno: interacción potencial"],
      ce=["Iniciar lo antes posible tras síntomas", "Ajustar dosis en insuficiencia renal", "Hidratación adecuada", "No cura la infección latente"]),

    M("antirretroviral", "valaciclovir", "Valaciclovir", "valaciclovir",
      ["Valtrex", "Rapivir"], "Antiviral (profármaco de aciclovir) oral",
      "Se convierte en aciclovir; inhibe ADN polimerasa viral con mayor biodisponibilidad oral",
      ["Herpes zóster", "Herpes genital (tratamiento y supresión)", "Herpes labial", "Profilaxis CMV post-trasplante"],
      ["Oral"], {"adulto": "Zóster: 1 g c/8h x7d; Genital: 500 mg-1 g c/12h"},
      ["Tab 500 mg", "Tab 1 g"], "Compatible con precaución",
      "u03", "c03_06",
      familia="Antivirales antiherpéticos"),

    M("antirretroviral", "molnupiravir", "Molnupiravir", "molnupiravir",
      ["Lagevrio"], "Antiviral análogo ribonucleósido",
      "Introduce errores letales en el ARN viral de SARS-CoV-2 durante replicación",
      ["COVID-19 leve-moderado en adultos con riesgo de progresión"],
      ["Oral"], "800 mg c/12h x5 días (iniciar dentro de 5 días de síntomas)",
      ["Cáps 200 mg"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales anti-SARS-CoV-2",
      emb="X",
      ci=["Hipersensibilidad", "Embarazo", "Menores de 18 años"],
      ea=["Diarrea", "Náuseas", "Mareo", "Cefalea"],
      ce=["Iniciar dentro de 5 días del inicio de síntomas", "No usar en hospitalizados", "Anticoncepción durante y 4 días post-tratamiento", "No requiere ajuste renal"]),

    M("antirretroviral", "baloxavir_marboxil", "Baloxavir Marboxil", "baloxavir marboxil",
      ["Xofluza"], "Inhibidor de endonucleasa cap-dependiente",
      "Inhibe la endonucleasa PA del virus influenza, bloqueando la replicación viral",
      ["Influenza A y B aguda", "Profilaxis post-exposición a influenza"],
      ["Oral"], {"adulto": "40-80 mg dosis única (según peso)", "pediatrico": "≥20 kg: dosis según peso"},
      ["Tab 20 mg", "Tab 40 mg"], "Evitar",
      "u03", "c03_06",
      familia="Antivirales antiinfluenza",
      ci=["Hipersensibilidad"],
      ea=["Diarrea", "Náuseas", "Cefalea", "Bronquitis"],
      ce=["Dosis única: verificar ingesta completa", "Iniciar dentro de 48h de síntomas", "No administrar con lácteos o antiácidos (quelación con cationes)", "Separar 2h de suplementos de calcio/hierro"]),

    M("antirretroviral", "zanamivir", "Zanamivir", "zanamivir",
      ["Relenza"], "Inhibidor de neuraminidasa inhalado",
      "Inhibe neuraminidasa del virus influenza impidiendo liberación de viriones",
      ["Tratamiento de influenza A y B", "Profilaxis de influenza"],
      ["Inhalatoria"], {"adulto": "10 mg (2 inhalaciones) c/12h x5d", "pediatrico": "≥7 años: misma dosis adulto"},
      ["Polvo inhal 5 mg/dosis (Diskhaler)"], "Compatible con precaución",
      "u03", "c03_06",
      familia="Antivirales antiinfluenza",
      ci=["Hipersensibilidad", "Antecedente de broncoespasmo con zanamivir", "Alergia a proteínas de leche"],
      ea=["Broncoespasmo", "Tos", "Cefalea", "Mareo", "Náuseas"],
      ce=["Tener broncodilatador disponible (riesgo broncoespasmo)", "Enseñar uso correcto del Diskhaler", "No usar en nebulizador (obstrucción)", "Iniciar dentro de 48h de síntomas"]),

    M("antirretroviral", "peramivir", "Peramivir", "peramivir",
      ["Rapivab", "Peramiflu"], "Inhibidor de neuraminidasa IV",
      "Inhibe neuraminidasa del virus influenza; única dosis IV",
      ["Influenza aguda cuando la vía oral/inhalatoria no es factible"],
      ["Intravenosa"], {"adulto": "600 mg IV dosis única", "pediatrico": "12 mg/kg (máx 600 mg) IV dosis única"},
      ["Fco 200 mg/20 mL"], "Evitar",
      "u03", "c03_06",
      familia="Antivirales antiinfluenza",
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión IV en 15-30 min", "estabilidad": "24h refrigerado diluido"}),

    M("antirretroviral", "tecovirimat", "Tecovirimat", "tecovirimat",
      ["TPOXX", "Tecovirimat SIGA"], "Antiviral anti-orthopoxvirus",
      "Inhibe proteína VP37 impidiendo la envoltura y liberación de viriones",
      ["Viruela del mono (mpox)", "Viruela", "Vaccinia adversa"],
      ["Oral", "Intravenosa"], "600 mg c/12h x14 días (con alimentos grasos)",
      ["Cáps 200 mg", "Fco 200 mg/20 mL IV"], "Evitar",
      "u03", "c03_06",
      familia="Antivirales anti-orthopoxvirus",
      ci=["Hipersensibilidad"],
      ea=["Cefalea", "Náuseas", "Dolor abdominal", "Vómitos"],
      ce=["Administrar con alimentos grasos para absorción", "Vigilar función hepática", "Uso bajo protocolo de emergencia o uso compasivo", "Monitorizar respuesta clínica"]),

    M("antirretroviral", "cidofovir", "Cidofovir", "cidofovir",
      ["Vistide"], "Antiviral análogo nucleotídico",
      "Inhibe ADN polimerasa viral de CMV y otros virus ADN sin requerir fosforilación viral",
      ["Retinitis por CMV en VIH", "Infecciones graves por adenovirus", "Virus BK post-trasplante"],
      ["Intravenosa"], "5 mg/kg IV semanal x2 semanas, luego c/2 semanas",
      ["Fco 375 mg/5 mL"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales anti-CMV",
      ci=["Hipersensibilidad", "Insuficiencia renal (Cr >1.5 o ClCr <55)", "Uso con otros nefrotóxicos"],
      ea=["Nefrotoxicidad severa", "Neutropenia", "Acidosis metabólica", "Uveítis/hipotonía ocular", "Náuseas"],
      ce=["OBLIGATORIO: probenecid + hidratación con SF pre/post infusión", "Creatinina y proteinuria antes de CADA dosis", "Suspender si Cr aumenta >0.4 sobre basal", "Monitorizar hemograma semanal"],
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión IV en 1h", "estabilidad": "24h refrigerado"}),

    M("antirretroviral", "foscarnet", "Foscarnet", "foscarnet sódico",
      ["Foscavir"], "Antiviral análogo pirofosfato",
      "Inhibe ADN polimerasa viral directamente sin requerir fosforilación por cinasas virales",
      ["CMV resistente a ganciclovir", "VHS/VVZ resistente a aciclovir", "Retinitis CMV en VIH"],
      ["Intravenosa"], "Inducción: 90 mg/kg c/12h x14-21d; Mantenimiento: 90-120 mg/kg/día",
      ["Fco 6 g/250 mL"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales anti-CMV",
      ci=["Hipersensibilidad", "ClCr <0.4 mL/min/kg"],
      ea=["Nefrotoxicidad", "Alteraciones electrolíticas (Ca, Mg, K, P)", "Convulsiones", "Úlceras genitales", "Náuseas"],
      ce=["Hidratación agresiva obligatoria (500-1000 mL SF pre-infusión)", "Electrolitos diarios (Ca, Mg, K, P)", "Función renal antes de cada dosis", "Infundir por vía central preferentemente", "Vigilar parestesias (hipocalcemia)"],
      pp={"dilucion": "Puede diluirse en SF; o infundir sin diluir por vía central", "velocidadAdministracion": "Infusión IV en 1-2h (no bolo)", "estabilidad": "24h a temperatura ambiente"}),

    M("antirretroviral", "maribavir", "Maribavir", "maribavir",
      ["Livtencity"], "Inhibidor de UL97 cinasa de CMV",
      "Inhibe la proteína cinasa UL97 de CMV, bloqueando maduración y egreso viral",
      ["Infección/enfermedad por CMV refractaria post-trasplante"],
      ["Oral"], "400 mg c/12h",
      ["Tab 200 mg"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales anti-CMV"),

    M("antirretroviral", "ribavirina", "Ribavirina", "ribavirina",
      ["Rebetol", "Copegus", "Virazole"], "Análogo nucleosídico de amplio espectro",
      "Múltiples mecanismos: inhibe IMPDH, mutagénesis letal del ARN viral, inhibe capping",
      ["Hepatitis C (con antivirales directos)", "VRS grave en inmunocomprometidos", "Fiebre hemorrágica viral"],
      ["Oral", "Inhalatoria"], {"adulto": "Oral: 800-1200 mg/día dividido c/12h; Inhalado: 6 g en 300 mL x12-18h/día"},
      ["Cáps 200 mg", "Tab 200 mg", "Sol inhalación 6 g"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales de amplio espectro",
      emb="X",
      ci=["Embarazo (teratógeno)", "Hemoglobinopatías", "Cardiopatía grave", "ClCr <50 mL/min"],
      ea=["Anemia hemolítica", "Fatiga", "Irritabilidad", "Rash", "Teratogenicidad", "Tos (inhalada)"],
      ce=["Anticoncepción obligatoria durante y 6 meses post-tratamiento (ambos sexos)", "Hemograma cada 2 semanas al inicio", "Vigilar Hb (suspender si <8.5)", "Test embarazo mensual"]),

    M("antirretroviral", "palivizumab", "Palivizumab", "palivizumab",
      ["Synagis"], "Anticuerpo monoclonal anti-VRS",
      "Se une a la proteína F del VRS impidiendo fusión viral con célula huésped",
      ["Profilaxis de infección grave por VRS en prematuros y cardiopatía congénita"],
      ["Intramuscular"], "15 mg/kg IM mensual durante temporada de VRS (5 dosis)",
      ["Fco 50 mg", "Fco 100 mg"], "Compatible",
      "u03", "c03_06",
      familia="Anticuerpos monoclonales antivirales",
      ci=["Hipersensibilidad a palivizumab"],
      ea=["Fiebre", "Reacción en sitio de inyección", "Rash", "Nerviosismo"],
      ce=["Administrar durante temporada de VRS", "Rotar sitios de inyección IM", "NO es tratamiento de infección activa", "Conservar refrigerado 2-8°C"]),

    M("antirretroviral", "nirsevimab", "Nirsevimab", "nirsevimab",
      ["Beyfortus"], "Anticuerpo monoclonal anti-VRS de larga duración",
      "Se une a proteína F prefusión del VRS; vida media prolongada (~70 días)",
      ["Prevención de enfermedad del tracto respiratorio inferior por VRS en neonatos y lactantes"],
      ["Intramuscular"], {"pediatrico": "<5 kg: 50 mg IM dosis única; ≥5 kg: 100 mg IM dosis única"},
      ["Jer 50 mg/0.5 mL", "Jer 100 mg/1 mL"], "Compatible",
      "u03", "c03_06",
      familia="Anticuerpos monoclonales antivirales"),

    M("antirretroviral", "brincidofovir", "Brincidofovir", "brincidofovir",
      ["Tembexa"], "Profármaco lipídico de cidofovir",
      "Se convierte en cidofovir intracelular; mejor penetración celular sin nefrotoxicidad",
      ["Viruela (tratamiento)", "Infecciones graves por adenovirus post-trasplante"],
      ["Oral"], "200 mg semanal x4 semanas",
      ["Tab 100 mg", "Susp 10 mg/mL"], "Contraindicada",
      "u03", "c03_06",
      familia="Antivirales anti-ADN virus"),

    # ── Antiparasitarios ──
    M("antiparasitario", "nifurtimox", "Nifurtimox", "nifurtimox",
      ["Lampit"], "Antiparasitario nitrofurano",
      "Genera radicales libres tóxicos para Trypanosoma cruzi mediante nitrorreducción",
      ["Enfermedad de Chagas aguda y congénita", "Tripanosomiasis americana"],
      ["Oral"], {"adulto": "8-10 mg/kg/día dividido c/8h x60-90 días", "pediatrico": "15-20 mg/kg/día dividido c/6-8h"},
      ["Tab 30 mg", "Tab 120 mg"], "Contraindicada",
      "u03", "c03_07",
      ci=["Hipersensibilidad", "Insuficiencia renal o hepática grave", "Antecedente de trastornos neuropsiquiátricos graves"],
      ea=["Anorexia", "Pérdida de peso", "Náuseas", "Neuropatía periférica", "Trastornos psiquiátricos", "Convulsiones"],
      ce=["Administrar con alimentos para reducir GI", "Vigilar neuropatía periférica", "Monitorizar peso corporal", "Hemograma periódico", "Tratamiento prolongado (60-90 días)"]),

    M("antiparasitario", "paromomicina", "Paromomicina", "paromomicina",
      ["Humatin", "Gabbroral"], "Aminoglucósido antiparasitario",
      "Inhibe síntesis proteica de protozoos; acción intraluminal contra amebiasis",
      ["Leishmaniasis visceral", "Amebiasis intestinal", "Criptosporidiosis", "Portador asintomático de E. histolytica"],
      ["Oral", "Intramuscular"], {"adulto": "Oral: 25-35 mg/kg/día c/8h; IM: 15 mg/kg/día (leishmaniasis)"},
      ["Cáps 250 mg", "Amp 375 mg/mL IM"], "Contraindicada",
      "u03", "c03_07"),

    M("antiparasitario", "estibogluconato_sodico", "Estibogluconato Sódico", "estibogluconato sódico",
      ["Pentostam"], "Antimonial pentavalente",
      "Inhibe enzimas glucolíticas y oxidación de ácidos grasos del parásito Leishmania",
      ["Leishmaniasis visceral", "Leishmaniasis cutánea", "Leishmaniasis mucocutánea"],
      ["Intramuscular", "Intravenosa"], "20 mg/kg/día IV o IM x28 días",
      ["Fco 100 mg Sb/mL x100 mL"], "Contraindicada",
      "u03", "c03_07",
      ci=["Hipersensibilidad", "Insuficiencia renal grave", "Cardiopatía grave"],
      ea=["Mialgias", "Artralgias", "Pancreatitis", "Prolongación QT", "Hepatotoxicidad", "Dolor en sitio inyección"],
      ce=["ECG basal y semanal (QT)", "Amilasa/lipasa semanal", "Función hepática periódica", "Administración IV lenta (5 min mínimo)"]),

    M("antiparasitario", "suramin", "Suramina", "suramina sódica",
      ["Germanin", "Suramin"], "Poliaminonaftaleno sulfonado",
      "Inhibe múltiples enzimas del Trypanosoma brucei; mecanismo exacto no completamente aclarado",
      ["Tripanosomiasis africana (T. brucei rhodesiense) fase hemolinfática"],
      ["Intravenosa"], "Dosis test 4-5 mg/kg, luego 20 mg/kg los días 1,3,7,14,21",
      ["Fco 1 g polvo para reconstitución"], "Contraindicada",
      "u03", "c03_07",
      ci=["Hipersensibilidad", "Insuficiencia renal grave"],
      ea=["Nefrotoxicidad", "Neuropatía periférica", "Reacciones alérgicas severas", "Agranulocitosis", "Úlceras cutáneas"],
      ce=["Dosis test obligatoria antes del tratamiento", "Uroanálisis antes de cada dosis (proteinuria)", "Vigilar función renal y hemograma", "Solo administrar en centros especializados"]),

    M("antiparasitario", "eflornitina", "Eflornitina", "eflornitina",
      ["Ornidyl", "DFMO"], "Inhibidor de ornitina descarboxilasa",
      "Inhibe la ornitina descarboxilasa del parásito, bloqueando síntesis de poliaminas esenciales",
      ["Tripanosomiasis africana (T. brucei gambiense) fase meningoencefálica"],
      ["Intravenosa"], "400 mg/kg/día IV dividido c/6h x14 días (o NECT: 400 mg/kg/día x7d + nifurtimox)",
      ["Fco 200 mg/mL x100 mL"], "Contraindicada",
      "u03", "c03_07",
      ea=["Mielosupresión", "Convulsiones", "Diarrea", "Alopecia reversible", "Vómitos"],
      ce=["Hemograma 2 veces/semana", "Vigilar convulsiones", "Requiere infusión lenta (4h mínimo)", "Gran volumen de infusión requerido"],
      pp={"dilucion": "Diluir en SF; grandes volúmenes necesarios", "velocidadAdministracion": "Infusión IV en 4h cada dosis", "estabilidad": "24h refrigerado"}),

    M("antiparasitario", "tafenoquina", "Tafenoquina", "tafenoquina",
      ["Krintafel", "Arakoda"], "8-aminoquinolina de acción prolongada",
      "Elimina hipnozoítos hepáticos de P. vivax/ovale; vida media prolongada (~14 días)",
      ["Cura radical de malaria por P. vivax", "Profilaxis de malaria"],
      ["Oral"], "300 mg dosis única (cura radical); 200 mg semanal (profilaxis)",
      ["Tab 100 mg", "Tab 150 mg"], "Contraindicada",
      "u03", "c03_07",
      ci=["Déficit G6PD", "Hipersensibilidad", "Embarazo", "Lactancia si lactante con déficit G6PD", "Psicosis o antecedente"],
      ea=["Hemólisis en déficit G6PD", "Metahemoglobinemia", "Mareo", "Cefalea", "Náuseas", "Vómitos"],
      ce=["OBLIGATORIO: determinar G6PD cuantitativo antes de administrar", "Vigilar hemólisis post-dosis", "Ventaja: dosis única vs 14 días de primaquina", "No administrar si G6PD <70% de lo normal"]),

    M("antiparasitario", "dietilcarbamazina", "Dietilcarbamazina", "dietilcarbamazina",
      ["Hetrazan", "Banocide"], "Antihelmíntico piperazínico",
      "Inmoviliza microfilarias y altera su superficie, facilitando destrucción por sistema inmune",
      ["Filariasis linfática (W. bancrofti, B. malayi)", "Loiasis", "Eosinofilia tropical pulmonar"],
      ["Oral"], {"adulto": "6 mg/kg/día dividido c/8h (escalada gradual)", "pediatrico": "6 mg/kg/día"},
      ["Tab 50 mg", "Tab 100 mg"], "Evitar",
      "u03", "c03_07",
      ci=["Hipersensibilidad", "Oncocercosis (reacción de Mazzotti severa)"],
      ea=["Reacción de Mazzotti (fiebre, prurito, hipotensión con muerte de microfilarias)", "Cefalea", "Mareo", "Náuseas"],
      ce=["Excluir oncocercosis antes de administrar", "Iniciar con dosis bajas y escalar", "Vigilar reacción tipo Mazzotti", "Administrar con alimentos"]),

    M("antiparasitario", "triclabendazol", "Triclabendazol", "triclabendazol",
      ["Egaten", "Fasinex"], "Bencimidazol antihelmíntico",
      "Activo contra formas juveniles y adultas de Fasciola hepática",
      ["Fasciolosis (Fasciola hepatica)", "Paragonimosis"],
      ["Oral"], "10 mg/kg dosis única o c/12h x2 dosis (con alimentos)",
      ["Tab 250 mg"], "Evitar",
      "u03", "c03_07"),

    M("antiparasitario", "furazolidona", "Furazolidona", "furazolidona",
      ["Furoxona", "Giarlam"], "Nitrofurano antiparasitario",
      "Inhibe monoaminooxidasa y vías metabólicas de Giardia y bacterias entéricas",
      ["Giardiasis", "Diarrea bacteriana", "Coadyuvante en H. pylori"],
      ["Oral"], {"adulto": "100 mg c/6h x7-10 días", "pediatrico": "1.25 mg/kg c/6h"},
      ["Tab 100 mg", "Susp 50 mg/15 mL"], "Evitar",
      "u03", "c03_07",
      ci=["Hipersensibilidad", "Menores de 1 mes", "Déficit G6PD"],
      ea=["Náuseas", "Vómitos", "Cefalea", "Hemólisis en G6PD", "Reacción tipo disulfiram con alcohol"],
      ce=["Evitar alcohol durante tratamiento (efecto disulfiram)", "Administrar con alimentos", "Coloración marrón de orina es normal", "Precaución en déficit G6PD"]),

    # ── Antifúngicos sistémicos ──
    M("antifungico_sistemico", "anfotericina_liposomal", "Anfotericina B Liposomal", "anfotericina B liposomal",
      ["AmBisome"], "Antifúngico poliénico liposomal",
      "Se une a ergosterol de membrana fúngica; formulación liposomal reduce nefrotoxicidad",
      ["Aspergilosis invasiva", "Candidiasis sistémica", "Criptococosis meníngea", "Leishmaniasis visceral", "Mucormicosis"],
      ["Intravenosa"], "3-5 mg/kg/día IV (leishmaniasis: 3 mg/kg días 1-5, 14, 21)",
      ["Fco 50 mg liofilizado"], "Contraindicada",
      "u03", "c03_05",
      ci=["Hipersensibilidad a anfotericina B"],
      ea=["Fiebre y escalofríos durante infusión", "Nefrotoxicidad (menor que forma convencional)", "Hipopotasemia", "Hepatotoxicidad", "Anemia"],
      ce=["Premedicación con paracetamol ± difenhidramina", "Función renal y electrolitos diarios", "Reponer K+ y Mg2+ según necesidad", "NO intercambiar con anfotericina B convencional (dosis diferentes)", "Infundir por vía central preferentemente"],
      pp={"dilucion": "Reconstituir con agua estéril, luego diluir en SG5% (NO SF)", "velocidadAdministracion": "Infusión IV en 1-2h", "estabilidad": "24h refrigerado diluido; 6h a temperatura ambiente"}),

    M("antifungico_sistemico", "rezafungina", "Rezafungina", "rezafungina",
      ["Rezzayo"], "Equinocandina de acción prolongada",
      "Inhibe síntesis de 1,3-β-D-glucano de pared fúngica; vida media de ~130h permite dosis semanal",
      ["Candidemia e infecciones invasivas por Candida"],
      ["Intravenosa"], "400 mg IV semana 1, luego 200 mg IV semanal",
      ["Fco 200 mg"], "Evitar",
      "u03", "c03_05",
      pp={"dilucion": "En 250 mL SF", "velocidadAdministracion": "Infusión IV en 1h", "estabilidad": "24h a temperatura ambiente"}),
]

# ══════════════════════════════════════════════════════════════════════
# U04 — RESPIRATORIO SUPLEMENTO (+36)
# ══════════════════════════════════════════════════════════════════════

u04_drugs = [
    # ── Hipertensión Pulmonar (nueva subcategoría c04_10) ──
    M("calcioantagonista", "bosentan_pulmonar", "Bosentán", "bosentán",
      ["Tracleer"], "Antagonista de receptores de endotelina",
      "Bloquea receptores ET-A y ET-B de endotelina-1, reduciendo vasoconstricción pulmonar",
      ["Hipertensión arterial pulmonar (HAP) clase funcional II-IV", "Prevención de úlceras digitales en esclerodermia"],
      ["Oral"], {"adulto": "62.5 mg c/12h x4 semanas, luego 125 mg c/12h", "pediatrico": "2 mg/kg c/12h"},
      ["Tab 62.5 mg", "Tab 125 mg", "Tab dispersable 32 mg"], "Contraindicada",
      "u04", "c04_10",
      familia="Antagonistas de endotelina",
      ci=["Embarazo (teratógeno)", "Insuficiencia hepática moderada-grave", "Uso con ciclosporina o gliburida"],
      ea=["Hepatotoxicidad", "Edema", "Cefalea", "Anemia", "Teratogenicidad", "Rubor facial"],
      ix=["Ciclosporina: aumenta niveles de bosentán", "Sildenafilo: interacción bidireccional", "Anticonceptivos hormonales: reduce eficacia"],
      ce=["Transaminasas mensual obligatorio", "Test embarazo mensual obligatorio", "Anticoncepción doble durante tratamiento", "Hemograma cada 3 meses (anemia)"],
      emb="X"),

    M("calcioantagonista", "ambrisentan", "Ambrisentán", "ambrisentán",
      ["Letairis", "Volibris"], "Antagonista selectivo de receptor ET-A",
      "Bloquea selectivamente receptor ET-A reduciendo vasoconstricción pulmonar",
      ["Hipertensión arterial pulmonar (HAP) clase funcional II-III"],
      ["Oral"], "5-10 mg/día",
      ["Tab 5 mg", "Tab 10 mg"], "Contraindicada",
      "u04", "c04_10",
      familia="Antagonistas de endotelina",
      emb="X",
      ci=["Embarazo", "Fibrosis pulmonar idiopática"],
      ea=["Edema periférico", "Congestión nasal", "Cefalea", "Anemia", "Rubor"],
      ce=["Test embarazo mensual", "Hemograma periódico", "Vigilar edema y retención hídrica", "No requiere monitorización hepática rutinaria"]),

    M("calcioantagonista", "macitentan", "Macitentán", "macitentán",
      ["Opsumit"], "Antagonista dual de receptores de endotelina",
      "Bloquea receptores ET-A y ET-B con alta afinidad tisular y penetración sostenida",
      ["Hipertensión arterial pulmonar para reducir progresión"],
      ["Oral"], "10 mg/día",
      ["Tab 10 mg"], "Contraindicada",
      "u04", "c04_10",
      familia="Antagonistas de endotelina",
      emb="X"),

    M("calcioantagonista", "sildenafilo_pulmonar", "Sildenafilo (HAP)", "sildenafilo",
      ["Revatio"], "Inhibidor de PDE-5 para hipertensión pulmonar",
      "Inhibe PDE-5 aumentando GMPc en músculo liso vascular pulmonar, causando vasodilatación",
      ["Hipertensión arterial pulmonar (HAP) clase funcional II-III"],
      ["Oral", "Intravenosa"], {"adulto": "Oral: 20 mg c/8h; IV: 10 mg c/8h"},
      ["Tab 20 mg", "Fco 10 mg/12.5 mL IV"], "Evitar",
      "u04", "c04_10",
      familia="Inhibidores de PDE-5 pulmonar",
      ci=["Uso concomitante de nitratos", "Hipotensión severa", "Pérdida visual reciente"],
      ea=["Cefalea", "Rubor", "Dispepsia", "Epistaxis", "Hipotensión", "Alteración visual"],
      ce=["NO confundir dosis de HAP (20 mg c/8h) con dosis DE (50-100 mg)", "No administrar con nitratos", "Vigilar TA", "Puede empeorar enfermedad venooclusiva pulmonar"]),

    M("calcioantagonista", "tadalafilo_pulmonar", "Tadalafilo (HAP)", "tadalafilo",
      ["Adcirca"], "Inhibidor de PDE-5 de larga duración para HAP",
      "Inhibe PDE-5 aumentando GMPc; vida media larga permite dosis única diaria",
      ["Hipertensión arterial pulmonar para mejorar capacidad de ejercicio"],
      ["Oral"], "40 mg/día",
      ["Tab 20 mg"], "Evitar",
      "u04", "c04_10",
      familia="Inhibidores de PDE-5 pulmonar"),

    M("calcioantagonista", "riociguat", "Riociguat", "riociguat",
      ["Adempas"], "Estimulador de guanilato ciclasa soluble",
      "Estimula directamente la sGC y sensibiliza la sGC al NO endógeno, aumentando GMPc",
      ["HAP (grupo 1)", "Hipertensión pulmonar tromboembólica crónica (HPTEC) inoperable"],
      ["Oral"], "Inicio: 1 mg c/8h; titular cada 2 sem hasta 2.5 mg c/8h",
      ["Tab 0.5 mg", "Tab 1 mg", "Tab 1.5 mg", "Tab 2 mg", "Tab 2.5 mg"], "Contraindicada",
      "u04", "c04_10",
      familia="Estimuladores de guanilato ciclasa",
      emb="X",
      ci=["Embarazo", "Uso con PDE-5i o nitratos", "Hipotensión severa", "Hipertensión pulmonar con neumopatía idiopática"],
      ea=["Cefalea", "Mareo", "Dispepsia", "Náuseas", "Hipotensión", "Anemia"],
      ce=["Titular gradualmente según TA", "No combinar con sildenafilo/tadalafilo", "Test embarazo mensual", "TA cada 2 semanas durante titulación"]),

    M("calcioantagonista", "epoprostenol", "Epoprostenol", "epoprostenol sódico",
      ["Flolan", "Veletri"], "Prostaciclina IV continua",
      "Análogo de prostaciclina; potente vasodilatador pulmonar, antiagregante y antiproliferativo",
      ["HAP severa (clase III-IV)", "Hipertensión pulmonar refractaria"],
      ["Intravenosa"], "Inicio: 2 ng/kg/min; titular gradualmente; mantenimiento: 20-40 ng/kg/min",
      ["Fco 0.5 mg", "Fco 1.5 mg liofilizado"], "Evitar",
      "u04", "c04_10",
      familia="Prostanoides",
      ci=["ICC severa", "Edema pulmonar", "Hipersensibilidad"],
      ea=["Cefalea", "Rubor", "Dolor mandibular", "Diarrea", "Náuseas", "Hipotensión", "Trombocitopenia"],
      ce=["Infusión continua IV por catéter central OBLIGATORIO", "NUNCA suspender abruptamente (hipertensión pulmonar de rebote fatal)", "Bomba de infusión con batería de respaldo", "Preparación estéril diaria", "Educar paciente sobre manejo de bomba y catéter"],
      pp={"dilucion": "Reconstituir y diluir según protocolo; Veletri en SF o SG5%", "velocidadAdministracion": "Infusión IV continua por bomba", "estabilidad": "Flolan: 8h a temperatura ambiente; Veletri: 72h"}),

    M("calcioantagonista", "treprostinil", "Treprostinil", "treprostinil",
      ["Remodulin", "Tyvaso", "Orenitram"], "Análogo de prostaciclina multirruta",
      "Vasodilatador pulmonar directo; inhibe agregación plaquetaria y proliferación músculo liso",
      ["HAP clase II-IV", "HAP asociada a enfermedad pulmonar intersticial"],
      ["Subcutánea", "Intravenosa", "Inhalatoria", "Oral"],
      {"adulto": "SC/IV: inicio 1.25 ng/kg/min, titular; Inhalado: 3 respiraciones (18 mcg) c/6h; Oral: 0.25 mg c/12h"},
      ["Fco SC/IV 1 mg/mL", "Amp inhal 0.6 mg/mL", "Tab LP 0.25 mg"], "Evitar",
      "u04", "c04_10",
      familia="Prostanoides"),

    M("calcioantagonista", "selexipag", "Selexipag", "selexipag",
      ["Uptravi"], "Agonista selectivo del receptor IP de prostaciclina oral",
      "Actúa sobre receptor IP de prostaciclina con selectividad sobre otros receptores prostanoides",
      ["HAP (grupo 1) para retrasar progresión"],
      ["Oral"], "Inicio: 200 mcg c/12h; titular cada semana +200 mcg hasta 1600 mcg c/12h",
      ["Tab 200 mcg", "Tab 400 mcg", "Tab 600 mcg", "Tab 800 mcg"], "Evitar",
      "u04", "c04_10",
      familia="Agonistas receptor IP prostaciclina",
      ea=["Cefalea", "Dolor mandibular", "Mialgias", "Diarrea", "Náuseas", "Rubor"],
      ce=["Titular lentamente según tolerancia", "Efectos adversos suelen atenuarse con el tiempo", "No suspender abruptamente", "Tomar con alimentos reduce náuseas"]),

    # ── Combinaciones inhaladas ──
    M("broncodilatador_beta2", "salbutamol_ipratropio", "Salbutamol/Ipratropio", "salbutamol + bromuro de ipratropio",
      ["Combivent", "Duoneb"], "Combinación beta-2 + anticolinérgico inhalado",
      "Broncodilatación por doble mecanismo: relajación directa (beta-2) y bloqueo vagal (anticolinérgico)",
      ["EPOC exacerbación", "Asma severa aguda", "Broncoespasmo agudo"],
      ["Inhalatoria", "Nebulización"], "MDI: 2 puffs c/6h; Nebulización: 2.5 mL c/6-8h",
      ["MDI 100/20 mcg x200 dosis", "Sol nebulización 2.5/0.5 mg/2.5 mL"], "Compatible",
      "u04", "c04_01",
      familia="Combinación broncodilatadora"),

    M("broncodilatador_beta2", "fenoterol_ipratropio", "Fenoterol/Ipratropio", "fenoterol + bromuro de ipratropio",
      ["Berodual", "Duovent"], "Combinación beta-2 + anticolinérgico inhalado",
      "Broncodilatación sinérgica por estimulación beta-2 y bloqueo muscarínico",
      ["EPOC", "Asma", "Broncoespasmo agudo"],
      ["Inhalatoria", "Nebulización"], "MDI: 1-2 puffs c/6-8h; Nebulización: 1-2 mL en 3 mL SF",
      ["MDI 50/20 mcg x200 dosis", "Sol nebulización 0.5/0.25 mg/mL"], "Compatible con precaución",
      "u04", "c04_01",
      familia="Combinación broncodilatadora"),

    M("broncodilatador_beta2", "fluticasona_vilanterol", "Fluticasona Furoato/Vilanterol", "fluticasona furoato + vilanterol",
      ["Relvar Ellipta", "Breo Ellipta"], "Combinación corticoide + LABA inhalado",
      "Fluticasona: antiinflamatorio; Vilanterol: LABA 24h. Dosis única diaria",
      ["Asma persistente", "EPOC con exacerbaciones frecuentes"],
      ["Inhalatoria"], "1 inhalación c/24h (misma hora cada día)",
      ["Polvo inhal 92/22 mcg x30 dosis", "Polvo inhal 184/22 mcg x30 dosis"], "Evitar",
      "u04", "c04_02",
      familia="Combinación ICS/LABA"),

    M("anticolinergico_inhalado", "indacaterol_glicopirronio", "Indacaterol/Glicopirronio", "indacaterol + glicopirronio",
      ["Ultibro Breezhaler", "Utibron"], "Combinación LABA + LAMA inhalado",
      "Broncodilatación dual de 24h: estimulación beta-2 + bloqueo muscarínico",
      ["EPOC mantenimiento con disnea persistente"],
      ["Inhalatoria"], "1 cápsula inhalada c/24h",
      ["Cáps inhal 85/43 mcg x30"], "Evitar",
      "u04", "c04_02",
      familia="Combinación LABA/LAMA"),

    M("anticolinergico_inhalado", "aclidinio_formoterol", "Aclidinio/Formoterol", "aclidinio + formoterol",
      ["Duaklir", "Brimica"], "Combinación LAMA + LABA inhalado",
      "Broncodilatación dual: aclidinio (LAMA c/12h) + formoterol (LABA c/12h)",
      ["EPOC mantenimiento"],
      ["Inhalatoria"], "1 inhalación c/12h",
      ["Polvo inhal 340/12 mcg x60 dosis"], "Evitar",
      "u04", "c04_02",
      familia="Combinación LAMA/LABA"),

    M("anticolinergico_inhalado", "tiotropio_olodaterol", "Tiotropio/Olodaterol", "tiotropio + olodaterol",
      ["Stiolto Respimat", "Spiolto"], "Combinación LAMA + LABA solución inhalada",
      "Broncodilatación dual de 24h en dispositivo Respimat",
      ["EPOC mantenimiento con disnea persistente"],
      ["Inhalatoria"], "2 puffs c/24h",
      ["Sol inhal 2.5/2.5 mcg/puff Respimat"], "Evitar",
      "u04", "c04_02",
      familia="Combinación LAMA/LABA"),

    M("anticolinergico_inhalado", "umeclidinio", "Umeclidinio", "umeclidinio",
      ["Incruse Ellipta"], "LAMA inhalado",
      "Antagonista muscarínico de acción prolongada (LAMA); bloquea receptores M3 en músculo liso bronquial",
      ["EPOC mantenimiento"],
      ["Inhalatoria"], "1 inhalación (62.5 mcg) c/24h",
      ["Polvo inhal 62.5 mcg x30 dosis"], "Evitar",
      "u04", "c04_02"),

    # ── Antileucotrienos/cromoglicatos ──
    M("corticoide_inhalado", "zafirlukast", "Zafirlukast", "zafirlukast",
      ["Accolate"], "Antagonista de receptores de leucotrienos",
      "Bloquea receptores CysLT1 de leucotrienos reduciendo broncoconstricción e inflamación",
      ["Asma persistente leve a moderada", "Asma inducida por ejercicio"],
      ["Oral"], {"adulto": "20 mg c/12h en ayunas", "pediatrico": "≥7 años: 10 mg c/12h"},
      ["Tab 10 mg", "Tab 20 mg"], "Evitar",
      "u04", "c04_03",
      familia="Antileucotrienos",
      ci=["Hipersensibilidad", "Insuficiencia hepática"],
      ea=["Cefalea", "Hepatotoxicidad (rara)", "Síndrome de Churg-Strauss (raro)", "Molestias GI"],
      ix=["Warfarina: aumenta INR", "Eritromicina: reduce niveles de zafirlukast", "Teofilina: reduce niveles de zafirlukast"],
      ce=["Administrar en ayunas (1h antes o 2h después de comidas)", "Monitorizar función hepática", "No es rescate: uso regular", "Vigilar signos de vasculitis"]),

    M("corticoide_inhalado", "nedocromil", "Nedocromil", "nedocromil sódico",
      ["Tilade", "Alocril"], "Estabilizador de mastocitos",
      "Inhibe degranulación de mastocitos y liberación de mediadores inflamatorios",
      ["Asma leve persistente", "Profilaxis de broncoespasmo inducido por ejercicio"],
      ["Inhalatoria"], "2 puffs c/6h (puede reducir a c/12h cuando estable)",
      ["MDI 2 mg/puff x112 dosis"], "Compatible",
      "u04", "c04_03",
      familia="Estabilizadores de mastocitos",
      ci=["Hipersensibilidad"],
      ea=["Sabor desagradable", "Cefalea", "Náuseas", "Tos"],
      ce=["No es rescate: uso profiláctico regular", "Efecto terapéutico tarda 2-4 semanas", "Usar 15-20 min antes del ejercicio como profilaxis", "Puede reducirse gradualmente"]),

    # ── Nuevos biológicos/targeted ──
    M("corticoide_inhalado", "ensifentrine", "Ensifentrina", "ensifentrina",
      ["Ohtuvayre"], "Inhibidor dual PDE3/PDE4 inhalado",
      "Inhibe PDE3 (broncodilatación) y PDE4 (antiinflamación) simultáneamente en pulmón",
      ["EPOC mantenimiento"],
      ["Inhalatoria"], "3 mg nebulizado c/12h",
      ["Sol nebulización 3 mg/3 mL"], "Evitar",
      "u04", "c04_03",
      familia="Inhibidores duales PDE3/PDE4"),

    M("corticoide_inhalado", "fevipiprant", "Fevipiprant", "fevipiprant",
      ["Fevipiprant"], "Antagonista de receptor DP2/CRTH2",
      "Bloquea receptor CRTH2 (DP2) de prostaglandina D2, reduciendo inflamación eosinofílica",
      ["Asma eosinofílica moderada-grave (complemento)"],
      ["Oral"], "150 mg c/12h",
      ["Tab 150 mg"], "Evitar",
      "u04", "c04_03",
      familia="Antagonistas CRTH2"),

    M("corticoide_inhalado", "depemokimab", "Depemokimab", "depemokimab",
      ["Depemokimab"], "Anti-IL-5 de acción ultralarga",
      "Anticuerpo monoclonal anti-IL-5 con dosis cada 6 meses",
      ["Asma eosinofílica severa (mantenimiento)"],
      ["Subcutánea"], "100 mg SC cada 6 meses",
      ["Jer 100 mg/mL"], "Evitar",
      "u04", "c04_03",
      familia="Anticuerpos anti-IL-5"),

    # ── Estimulantes respiratorios ──
    M("broncodilatador_beta2", "doxapram", "Doxapram", "doxapram",
      ["Dopram"], "Estimulante respiratorio central",
      "Estimula quimiorreceptores carotídeos y centro respiratorio bulbar",
      ["Depresión respiratoria post-anestesia", "Apnea del prematuro refractaria a cafeína", "Insuficiencia respiratoria aguda con hipercapnia"],
      ["Intravenosa"], "Bolo: 0.5-1 mg/kg; Infusión: 1-3 mg/min",
      ["Amp 20 mg/mL x20 mL"], "Evitar",
      "u04", "c04_04",
      familia="Analépticos respiratorios",
      ci=["Epilepsia", "Hipertensión severa", "ACV", "Insuficiencia coronaria", "Neumotórax"],
      ea=["Hipertensión", "Taquicardia", "Arritmias", "Convulsiones", "Náuseas", "Sudoración"],
      ix=["IMAO: crisis hipertensiva", "Simpaticomiméticos: HTA aditiva", "Anestésicos halogenados: arritmias"],
      ce=["Monitorización continua (TA, FC, SatO2)", "NO usar como sustituto de ventilación mecánica", "Tener equipo de reanimación disponible", "Usar dosis mínima eficaz"],
      pp={"dilucion": "En SG5% o SF", "velocidadAdministracion": "Infusión 1-3 mg/min; bolo en 30s", "estabilidad": "24h diluido"}),

    M("broncodilatador_beta2", "almitrina", "Almitrina", "almitrina bismesylato",
      ["Vectarion"], "Estimulante de quimiorreceptores periféricos",
      "Estimula quimiorreceptores carotídeos aumentando ventilación; mejora V/Q",
      ["EPOC con hipoxemia crónica", "Insuficiencia respiratoria crónica"],
      ["Oral"], "50 mg c/12h (ciclos de 2 meses con 1 mes de descanso)",
      ["Tab 50 mg"], "Contraindicada",
      "u04", "c04_04",
      familia="Analépticos respiratorios",
      ea=["Neuropatía periférica", "Pérdida de peso", "Disnea paradójica", "Parestesias"],
      ce=["Monitorizar neuropatía periférica", "Uso en ciclos para reducir toxicidad", "Suspender si aparece neuropatía", "Gasometría periódica"]),

    # ── Alfa-1 antitripsina ──
    M("broncodilatador_beta2", "alfa1_antitripsina", "Alfa-1 Antitripsina Humana", "alfa-1 antitripsina humana",
      ["Prolastin", "Aralast", "Zemaira"], "Terapia de reemplazo enzimático",
      "Reemplaza alfa-1 antitripsina deficiente; protege alvéolos de degradación por elastasa neutrofílica",
      ["Enfisema por déficit de alfa-1 antitripsina (fenotipo PiZZ o PiSZ)"],
      ["Intravenosa"], "60 mg/kg IV semanal",
      ["Fco 1000 mg liofilizado"], "Compatible con precaución",
      "u04", "c04_04",
      familia="Terapia de reemplazo",
      ci=["Hipersensibilidad", "Déficit selectivo de IgA con anticuerpos anti-IgA"],
      ea=["Cefalea", "Mareo", "Reacción infusional", "Fatiga", "Fiebre"],
      ce=["Velocidad de infusión ≤0.08 mL/kg/min", "Monitorizar durante y 1h post-infusión", "Verificar fenotipo antes de iniciar", "Tratamiento de por vida"],
      pp={"dilucion": "Reconstituir según fabricante", "velocidadAdministracion": "≤0.08 mL/kg/min", "estabilidad": "3h tras reconstitución"}),

    # ── Descongestionantes nasales adicionales ──
    M("broncodilatador_beta2", "nafazolina", "Nafazolina", "nafazolina",
      ["Privina", "Rhinofed"], "Descongestionante nasal alfa-adrenérgico",
      "Agonista alfa-1 adrenérgico que produce vasoconstricción de mucosa nasal",
      ["Congestión nasal aguda", "Rinitis aguda", "Sinusitis"],
      ["Nasal"], "1-2 gotas o pulverizaciones c/8-12h (máx 5 días)",
      ["Sol nasal 0.05%", "Sol nasal 0.025% pediátrica"], "Compatible",
      "u04", "c04_04",
      familia="Descongestionantes nasales",
      ci=["Hipersensibilidad", "Glaucoma de ángulo cerrado", "Rinitis atrófica", "Uso de IMAO"],
      ea=["Congestión de rebote (uso >5 días)", "Sequedad nasal", "Irritación", "Cefalea", "Taquicardia"],
      ce=["Máximo 5 días de uso continuo", "No usar en menores de 6 años (0.05%)", "Educar sobre congestión de rebote", "No compartir dispositivos"]),

    M("broncodilatador_beta2", "cromoglicato_nasal", "Cromoglicato Nasal", "cromoglicato sódico nasal",
      ["NasalCrom", "Rynacrom"], "Estabilizador de mastocitos nasal",
      "Inhibe degranulación de mastocitos en mucosa nasal previniendo liberación de histamina",
      ["Rinitis alérgica estacional y perenne", "Profilaxis de rinitis"],
      ["Nasal"], "1 pulverización en cada fosa c/4-6h",
      ["Spray nasal 4% (40 mg/mL)"], "Compatible",
      "u04", "c04_04",
      familia="Estabilizadores de mastocitos nasales"),

    # ── Surfactantes adicionales y fibrosis ──
    M("broncodilatador_beta2", "surfactante_poractant", "Poractant Alfa", "poractant alfa",
      ["Curosurf"], "Surfactante pulmonar porcino",
      "Reemplaza surfactante deficiente; reduce tensión superficial alveolar previniendo colapso",
      ["Síndrome de dificultad respiratoria neonatal (SDR)", "Rescate en SDR establecido"],
      ["Intratraqueal"], {"pediatrico": "Inicial: 200 mg/kg (2.5 mL/kg); Rescate: 100 mg/kg c/12h x2 dosis"},
      ["Fco 80 mg/mL x1.5 mL", "Fco 80 mg/mL x3 mL"], "No aplica",
      "u04", "c04_04",
      familia="Surfactantes pulmonares",
      ci=["Ninguna absoluta en emergencia neonatal"],
      ea=["Bradicardia transitoria", "Desaturación durante administración", "Hemorragia pulmonar (raro)", "Obstrucción del tubo"],
      ce=["Administrar por tubo endotraqueal", "Aspirar secreciones antes de administrar", "Monitorizar SatO2 y FC continua", "Ajustar FiO2 y ventilador rápidamente post-dosis", "Temperatura del surfactante a ambiente antes de usar"]),

    M("broncodilatador_beta2", "calfactant", "Calfactant", "calfactant",
      ["Infasurf"], "Surfactante pulmonar bovino",
      "Extracto de pulmón bovino rico en fosfolípidos y proteínas SP-B y SP-C",
      ["Profilaxis y tratamiento de SDR neonatal"],
      ["Intratraqueal"], {"pediatrico": "3 mL/kg (105 mg fosfolípidos/kg) intratraqueal; repetir cada 12h x3 dosis"},
      ["Fco 6 mL (35 mg/mL fosfolípidos)"], "No aplica",
      "u04", "c04_04",
      familia="Surfactantes pulmonares"),

    # ── Antifibróticos ──
    M("broncodilatador_beta2", "pamrevlumab", "Pamrevlumab", "pamrevlumab",
      ["Pamrevlumab"], "Anti-CTGF (factor de crecimiento tejido conectivo)",
      "Anticuerpo monoclonal contra CTGF que reduce fibrosis pulmonar",
      ["Fibrosis pulmonar idiopática (investigación avanzada)"],
      ["Intravenosa"], "35 mg/kg IV c/3 semanas",
      ["Fco concentrado para infusión"], "Evitar",
      "u04", "c04_04",
      familia="Antifibróticos pulmonares"),

    # ── Mucolíticos/expectorantes adicionales ──
    M("broncodilatador_beta2", "sobrerrol", "Sobrerol", "sobrerol",
      ["Sobrepin", "Sobrerol"], "Mucolítico terpénico",
      "Derivado terpénico que reduce viscosidad del moco bronquial facilitando su eliminación",
      ["Bronquitis aguda y crónica", "EPOC con hipersecreción mucosa"],
      ["Oral"], "100-200 mg c/8h",
      ["Cáps 200 mg", "Susp 2%"], "Compatible",
      "u04", "c04_05",
      familia="Mucolíticos",
      ci=["Hipersensibilidad"],
      ea=["Molestias gástricas", "Náuseas", "Diarrea"],
      ce=["Hidratación abundante potencia efecto mucolítico", "Administrar con alimentos", "Complementar con fisioterapia respiratoria"]),

    M("broncodilatador_beta2", "caramifeno", "Caramifeno", "caramifeno",
      ["Tuclase"], "Antitusivo no narcótico",
      "Suprime el reflejo tusígeno a nivel del centro de la tos en bulbo raquídeo",
      ["Tos seca no productiva", "Tos irritativa"],
      ["Oral"], {"adulto": "10-20 mg c/6-8h", "pediatrico": "5-10 mg c/8h"},
      ["Tab 10 mg", "Jarabe 5 mg/5 mL"], "Compatible con precaución",
      "u04", "c04_05",
      familia="Antitusivos no narcóticos"),

    M("broncodilatador_beta2", "pranlukast", "Pranlukast", "pranlukast",
      ["Onon", "Azlaire"], "Antagonista de leucotrienos CysLT1",
      "Bloquea receptores de leucotrienos CysLT1 reduciendo broncoespasmo e inflamación",
      ["Asma bronquial", "Rinitis alérgica"],
      ["Oral"], "225 mg c/12h",
      ["Cáps 112.5 mg", "Granulado 100 mg"], "Evitar",
      "u04", "c04_03",
      familia="Antileucotrienos"),
]

# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    import os
    os.chdir(os.path.join(os.path.dirname(__file__), ".."))

    all_drugs = u03_drugs + u04_drugs
    print(f"=== U03+U04 supplement: {len(all_drugs)} drugs ===")
    added = add_drugs_to_file(all_drugs)

    cats = load_categories()

    # New chapters
    add_chapter(cats, "u04", {
        "id": "c04_10",
        "nombre": "Hipertensión Pulmonar",
        "drugIds": []
    })

    for d in all_drugs:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])

    save_categories(cats)
    print(f"Done. {added} drugs added.")
