#!/usr/bin/env python3
"""Add ~60 new drugs for U07 Sistema Reproductor y Óseo."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c07_01 Oxitócicos y Tocolíticos (+5) ──
M("aine","indometacina_tocolitico","Indometacina (tocolítico)","Indometacina",["Indocid","Artrinovo"],
  "AINE inhibidor no selectivo de COX (uso tocolítico)",
  "Inhibe COX-1 y COX-2, reduciendo síntesis de prostaglandinas que estimulan contracciones uterinas",
  ["Tocólisis aguda <32 semanas de gestación","Polihidramnios"],["oral","rectal"],
  {"adulto":"Carga: 50-100 mg oral/rectal, luego 25-50 mg c/6h máx 48-72h"},
  ["Cáps 25, 50 mg","Supositorio 100 mg"],"Evitar en lactancia","u07","c07_01",
  familia="Tocolíticos (AINE)",
  ci=["Gestación >32 semanas","Oligohidramnios","Disfunción renal fetal","Úlcera péptica activa","Insuficiencia renal materna"],
  ea=["Cierre prematuro del ductus arterioso fetal","Oligohidramnios","Enterocolitis necrotizante neonatal","Náuseas maternas","Dispepsia"],
  ix=["Sulfato de magnesio: efectos tocolíticos aditivos","Corticoides: mayor riesgo GI","Betamiméticos: combinar con precaución"],
  ce=["Usar SOLO <32 semanas","Máximo 48-72h de uso","Ecografía para valorar líquido amniótico c/24-48h","Monitorizar diuresis fetal","Ecocardiografía fetal si uso >48h"],
  emb="C"),

M("calcioantagonista","nifedipino_tocolitico","Nifedipino (tocolítico)","Nifedipino",["Adalat","Procardia"],
  "Calcioantagonista dihidropiridínico (uso tocolítico)",
  "Bloquea canales de calcio tipo L en miometrio, reduciendo calcio intracelular y relajando musculatura uterina",
  ["Tocólisis aguda (amenaza parto prematuro 24-34 sem)","Tocólisis de mantenimiento a corto plazo"],["oral"],
  {"adulto":"Carga: 20 mg oral, repetir a los 30 min si persisten contracciones. Mant: 20 mg c/6-8h x 48h"},
  ["Cáps 10 mg","Comp LP 20, 30 mg"],"Compatible con precaución","u07","c07_01",
  familia="Tocolíticos (calcioantagonista)",
  ci=["Hipotensión materna (PAS <90)","Cardiopatía materna","Estenosis aórtica","Uso concomitante con sulfato de magnesio IV"],
  ea=["Hipotensión materna","Taquicardia refleja","Cefalea","Rubor facial","Mareo","Náuseas"],
  ix=["Sulfato de magnesio IV: NO combinar (colapso CV)","Betabloqueantes: hipotensión aditiva","Otros antihipertensivos: hipotensión"],
  ce=["Primera línea tocolítica en muchas guías","NO combinar con sulfato de magnesio IV","Monitorizar PA c/15 min durante carga","Mantener PAS >90 mmHg","Monitorización fetal continua"],
  emb="C"),

M("","hexoprenalina","Hexoprenalina","Hexoprenalina",["Ipradol"],
  "Agonista beta-2 adrenérgico (tocolítico)",
  "Estimula receptores beta-2 en miometrio, aumentando AMPc intracelular y relajando la musculatura uterina",
  ["Tocólisis aguda en amenaza de parto prematuro","Relajación uterina para procedimientos obstétricos"],["IV"],
  {"adulto":"IV: 0.5 mcg/min, titular cada 15 min hasta máx 3 mcg/min según respuesta"},
  ["Amp 25 mcg/5 mL"],"Evitar en lactancia","u07","c07_01",
  familia="Tocolíticos (betamimético)",
  ci=["Taquicardia materna >120 lpm","Cardiopatía materna","Hipertiroidismo","Diabetes descompensada","Desprendimiento de placenta"],
  ea=["Taquicardia materna","Palpitaciones","Temblor","Hiperglucemia","Hipopotasemia","Edema pulmonar (raro)","Taquicardia fetal"],
  ix=["Corticoides: mayor riesgo edema pulmonar","Betabloqueantes: antagonismo","Sulfato de magnesio: efectos CV aditivos"],
  ce=["Monitorizar FC materna (suspender si >120 lpm)","Balance hídrico estricto (máx 2500 mL/24h)","Control de glucemia y potasio","Monitorización cardiotocográfica continua","Posición lateral izquierda"],
  emb="B",
  pp={"dilucion":"Diluir en SG5% 500 mL","velocidadAdministracion":"Infusión continua 0.5-3 mcg/min","estabilidad":"24h a TA"}),

M("broncodilatador_beta2","terbutalina_tocolitica","Terbutalina (tocolítica)","Terbutalina",["Bricanyl"],
  "Agonista beta-2 adrenérgico (uso tocolítico)",
  "Estimula receptores beta-2 en miometrio, aumentando AMPc y reduciendo calcio intracelular con relajación uterina",
  ["Tocólisis aguda a corto plazo","Relajación uterina para versión cefálica externa"],["SC","IV"],
  {"adulto":"SC: 0.25 mg c/20-30 min (máx 3 dosis). IV: 2.5-5 mcg/min titular"},
  ["Amp 0.5 mg/mL","Amp 1 mg/mL"],"Compatible con precaución","u07","c07_01",
  familia="Tocolíticos (betamimético)",
  ci=["Taquicardia materna >120 lpm","Cardiopatía materna","Hipertiroidismo","Diabetes descompensada","Preeclampsia severa"],
  ea=["Taquicardia materna","Palpitaciones","Temblor","Hiperglucemia","Hipopotasemia","Edema pulmonar (raro)","Taquicardia fetal"],
  ix=["Corticoides: mayor riesgo edema pulmonar","Betabloqueantes: antagonismo","Sulfato de magnesio: efectos CV aditivos"],
  ce=["FDA: advertencia contra uso >48-72h","Monitorizar FC materna (suspender si >120 lpm)","Control de glucemia y potasio","Balance hídrico estricto","Monitorización cardiotocográfica continua"],
  emb="B",
  pp={"dilucion":"Diluir en SG5% o SF","velocidadAdministracion":"Infusión continua 2.5-5 mcg/min","estabilidad":"24h a TA"}),

M("","fenoterol_tocolitico","Fenoterol (tocolítico)","Fenoterol",["Berotec","Partusisten"],
  "Agonista beta-2 adrenérgico (tocolítico)",
  "Estimula selectivamente receptores beta-2 adrenérgicos en miometrio, produciendo relajación uterina por aumento de AMPc",
  ["Tocólisis aguda en amenaza de parto prematuro","Relajación uterina intraparto"],["IV"],
  {"adulto":"IV: 1-3 mcg/min en infusión continua, titular según respuesta"},
  ["Amp 0.5 mg/10 mL"],"Evitar en lactancia","u07","c07_01",
  familia="Tocolíticos (betamimético)",
  ci=["Cardiopatía materna","Taquicardia materna >120 lpm","Hipertiroidismo","Diabetes descompensada","Hemorragia anteparto severa"],
  ea=["Taquicardia materna y fetal","Palpitaciones","Temblor fino","Hiperglucemia","Hipopotasemia","Cefalea","Edema pulmonar (raro)"],
  ix=["Betabloqueantes: antagonismo del efecto tocolítico","Corticoides: mayor riesgo edema pulmonar con sobrecarga hídrica","Sulfato de magnesio: efectos cardiovasculares aditivos"],
  ce=["Monitorizar FC materna continuamente (suspender si >120 lpm)","Balance hídrico estricto (no exceder 2500 mL/24h)","Control de glucemia c/4-6h","Monitorizar potasio sérico","Posición lateral izquierda durante infusión"],
  emb="B",
  pp={"dilucion":"Diluir en SG5% 500 mL","velocidadAdministracion":"1-3 mcg/min en infusión continua","estabilidad":"24h a TA"}),

# ── c07_03 Urológicos (+8) ──
M("","solifenacina","Solifenacina","Solifenacina",["Vesicare","Solifenacin"],
  "Antimuscarínico selectivo M3",
  "Antagonista competitivo selectivo del receptor muscarínico M3 en el detrusor vesical, reduciendo contracciones involuntarias",
  ["Vejiga hiperactiva con urgencia, frecuencia e incontinencia de urgencia"],["oral"],
  {"adulto":"5 mg/día, puede aumentar a 10 mg/día","geriatrico":"Iniciar con 5 mg/día","ajusteRenal":"Máx 5 mg/día si ClCr <30","ajusteHepatico":"Máx 5 mg/día en IH moderada. Contraindicado en IH severa"},
  ["Comp 5, 10 mg"],"Evitar en lactancia","u07","c07_03",
  familia="Antimuscarínicos vesicales",
  ci=["Retención urinaria","Glaucoma de ángulo cerrado no tratado","Miastenia gravis","Insuficiencia hepática severa","Íleo paralítico"],
  ea=["Boca seca","Estreñimiento","Visión borrosa","Somnolencia","Retención urinaria","Dispepsia","Infección urinaria"],
  ix=["Inhibidores CYP3A4 (ketoconazol): aumentan niveles","Otros anticolinérgicos: efectos aditivos","Colinérgicos: antagonismo"],
  ce=["Valorar residuo postmiccional antes de iniciar","Vigilar retención urinaria especialmente en varones","Hidratación adecuada para prevenir estreñimiento","Precaución en ancianos (riesgo deterioro cognitivo)","Reevaluar necesidad c/3-6 meses"],
  emb="X"),

M("","tolterodina","Tolterodina","Tolterodina",["Detrusitol","Detrol"],
  "Antimuscarínico no selectivo con selectividad funcional vesical",
  "Antagonista competitivo de receptores muscarínicos con mayor selectividad funcional por vejiga vs glándulas salivales",
  ["Vejiga hiperactiva con síntomas de urgencia, frecuencia e incontinencia"],["oral"],
  {"adulto":"IR: 2 mg c/12h. LP: 4 mg/día","geriatrico":"Puede requerir 1 mg c/12h","ajusteRenal":"1 mg c/12h si ClCr <30","ajusteHepatico":"1 mg c/12h en IH significativa"},
  ["Comp 1, 2 mg","Cáps LP 2, 4 mg"],"Evitar en lactancia","u07","c07_03",
  familia="Antimuscarínicos vesicales",
  ci=["Retención urinaria","Glaucoma de ángulo cerrado no tratado","Miastenia gravis","Colitis ulcerosa severa","Megacolon tóxico"],
  ea=["Boca seca","Cefalea","Estreñimiento","Dispepsia","Visión borrosa","Somnolencia","Xeroftalmia"],
  ix=["Inhibidores CYP3A4/2D6: aumentan niveles","Otros anticolinérgicos: efectos aditivos","Fluoxetina: inhibe metabolismo"],
  ce=["Forma LP tiene menor incidencia de boca seca","Monitorizar residuo postmiccional","Precaución en ancianos","Vigilar estreñimiento y retención urinaria","Reevaluar respuesta a las 4-8 semanas"],
  emb="C"),

M("","oxibutinina","Oxibutinina","Oxibutinina",["Ditropan","Kentera"],
  "Antimuscarínico con acción espasmolítica directa",
  "Antagonista muscarínico con efecto espasmolítico directo sobre el músculo liso del detrusor y propiedades anestésicas locales",
  ["Vejiga hiperactiva","Incontinencia urinaria de urgencia","Enuresis nocturna (>5 años)"],["oral","transdérmico"],
  {"adulto":"Oral: 5 mg c/8-12h. LP: 5-30 mg/día. Parche: 3.9 mg/día c/3-4 días","pediatrico":"≥5 años: 5 mg c/12h","geriatrico":"Iniciar 2.5 mg c/12h"},
  ["Comp 5 mg","Comp LP 5, 10, 15 mg","Parche transdérmico 3.9 mg/día","Jarabe 5 mg/5 mL"],"Evitar en lactancia","u07","c07_03",
  familia="Antimuscarínicos vesicales",
  ci=["Retención urinaria","Glaucoma de ángulo cerrado","Obstrucción GI","Miastenia gravis","Colitis ulcerosa severa"],
  ea=["Boca seca (muy frecuente)","Estreñimiento","Somnolencia","Visión borrosa","Mareo","Deterioro cognitivo en ancianos","Irritación cutánea (parche)"],
  ix=["Otros anticolinérgicos: efectos aditivos","Inhibidores colinesterasa (donepezilo): antagonismo","Depresores SNC: mayor sedación"],
  ce=["Parche transdérmico: menor boca seca que vía oral","Evitar en ancianos frágiles (riesgo deterioro cognitivo)","Rotar sitio del parche","Vigilar retención urinaria y estreñimiento","No triturar formas LP"],
  emb="B"),

M("","darifenacina","Darifenacina","Darifenacina",["Enablex","Emselex"],
  "Antagonista selectivo del receptor muscarínico M3",
  "Alta selectividad por receptor M3 sobre M2, con menor efecto sobre cognición y función cardíaca que antimuscarínicos no selectivos",
  ["Vejiga hiperactiva con urgencia e incontinencia de urgencia"],["oral"],
  {"adulto":"Inicio: 7.5 mg/día. Puede aumentar a 15 mg/día a las 2 semanas","ajusteHepatico":"Máx 7.5 mg/día en IH moderada. Contraindicado en IH severa"},
  ["Comp LP 7.5, 15 mg"],"Evitar en lactancia","u07","c07_03",
  familia="Antimuscarínicos vesicales",
  ci=["Retención urinaria","Glaucoma de ángulo cerrado","Insuficiencia hepática severa","Gastroparesia severa","Miastenia gravis"],
  ea=["Estreñimiento (frecuente)","Boca seca","Dispepsia","Dolor abdominal","Náuseas","Cefalea","Infección urinaria"],
  ix=["Inhibidores CYP3A4 potentes: máx 7.5 mg/día","Inhibidores CYP2D6: aumentan niveles","Otros anticolinérgicos: efectos aditivos"],
  ce=["Selectividad M3: menor efecto cognitivo (ventaja en ancianos)","Vigilar estreñimiento (EA más frecuente)","No triturar comprimidos LP","Reevaluar a las 4-8 semanas","Valorar residuo postmiccional basal"],
  emb="C"),

M("","fesoterodina","Fesoterodina","Fesoterodina",["Toviaz"],
  "Profármaco antimuscarínico convertido a 5-HMT",
  "Profármaco hidrolizado por esterasas plasmáticas a 5-hidroximetil tolterodina (5-HMT), metabolito activo con acción antimuscarínica",
  ["Vejiga hiperactiva con urgencia, frecuencia e incontinencia de urgencia"],["oral"],
  {"adulto":"4 mg/día, puede aumentar a 8 mg/día","ajusteRenal":"Máx 4 mg/día si ClCr <30","ajusteHepatico":"Máx 4 mg/día en IH moderada"},
  ["Comp LP 4, 8 mg"],"Evitar en lactancia","u07","c07_03",
  familia="Antimuscarínicos vesicales",
  ci=["Retención urinaria","Glaucoma de ángulo cerrado","Miastenia gravis","Insuficiencia hepática severa","Obstrucción GI"],
  ea=["Boca seca","Estreñimiento","Cefalea","Insomnio","Disuria","Nasofaringitis"],
  ix=["Inhibidores CYP3A4 potentes: máx 4 mg/día","Otros anticolinérgicos: efectos aditivos","Inductores CYP3A4: pueden reducir eficacia"],
  ce=["No depende de CYP2D6 (ventaja sobre tolterodina)","Tragar entero, no triturar ni masticar","Vigilar retención urinaria en varones con HPB","Monitorizar residuo postmiccional","Precaución en ancianos"],
  emb="C"),

M("","silodosina","Silodosina","Silodosina",["Rapaflo","Silodyx","Urorec"],
  "Antagonista alfa-1A altamente selectivo",
  "Bloquea selectivamente receptores alfa-1A adrenérgicos en próstata y uretra (selectividad 162:1 vs alfa-1B), relajando musculatura lisa prostática",
  ["Hiperplasia benigna de próstata (síntomas del tracto urinario inferior)"],["oral"],
  {"adulto":"8 mg/día con alimentos","ajusteRenal":"4 mg/día si ClCr 30-50. Contraindicado si ClCr <30"},
  ["Cáps 4, 8 mg"],"No aplica","u07","c07_03",
  familia="Alfa-1 bloqueantes (urológicos)",
  ci=["Insuficiencia renal severa (ClCr <30)","Insuficiencia hepática severa","Hipotensión ortostática severa"],
  ea=["Eyaculación retrógrada/aneyaculación (muy frecuente)","Mareo","Congestión nasal","Hipotensión ortostática","Cefalea","Diarrea"],
  ix=["Inhibidores CYP3A4 potentes: contraindicado","Otros alfa-bloqueantes: hipotensión aditiva","Antihipertensivos: mayor riesgo hipotensión","IPDE5: hipotensión"],
  ce=["Alta tasa de eyaculación retrógrada (informar al paciente)","Tomar con alimentos (mejora absorción)","Levantarse lentamente para evitar hipotensión","Informar oftalmólogo antes de cirugía de cataratas (síndrome de iris flácido)","Riesgo síndrome iris flácido intraoperatorio"],
  emb="X"),

M("","alfuzosina","Alfuzosina","Alfuzosina",["Xatral","Alfuzosin"],
  "Antagonista alfa-1 adrenérgico (uroselective)",
  "Bloquea receptores alfa-1 en musculatura lisa prostática, cuello vesical y uretra, mejorando el flujo urinario",
  ["Hiperplasia benigna de próstata","Retención urinaria aguda (facilitar retirada de sonda)"],["oral"],
  {"adulto":"LP: 10 mg/día con alimentos después de cena","ajusteRenal":"Precaución si ClCr <30","ajusteHepatico":"Contraindicado en IH moderada-severa"},
  ["Comp LP 10 mg","Comp 2.5 mg"],"No aplica","u07","c07_03",
  familia="Alfa-1 bloqueantes (urológicos)",
  ci=["Hipotensión ortostática","Insuficiencia hepática","Uso con inhibidores potentes CYP3A4","Prolongación QT conocida"],
  ea=["Mareo","Cefalea","Hipotensión ortostática","Fatiga","Congestión nasal","Taquicardia","Molestias GI"],
  ix=["Inhibidores CYP3A4 (ketoconazol, ritonavir): contraindicado","Otros alfa-bloqueantes: hipotensión","Antihipertensivos: hipotensión aditiva","Nitratos: hipotensión severa"],
  ce=["Tomar después de la cena (misma comida cada día)","No triturar forma LP","Precaución al levantarse (hipotensión ortostática)","Informar oftalmólogo antes de cirugía cataratas","Monitorizar TA al inicio del tratamiento"],
  emb="X"),

M("","doxazosina_urologica","Doxazosina (urológica)","Doxazosina",["Cardura","Carduran"],
  "Antagonista alfa-1 adrenérgico no selectivo",
  "Bloquea receptores alfa-1 adrenérgicos en próstata, cuello vesical y vasos sanguíneos, mejorando flujo urinario y reduciendo TA",
  ["Hiperplasia benigna de próstata","HTA concomitante con HPB"],["oral"],
  {"adulto":"Inicio: 1 mg/día al acostarse. Titular c/1-2 sem hasta 4-8 mg/día. Máx 8 mg/día"},
  ["Comp 1, 2, 4, 8 mg","Comp LP 4, 8 mg"],"No aplica","u07","c07_03",
  familia="Alfa-1 bloqueantes (urológicos)",
  ci=["Hipotensión severa","Insuficiencia hepática severa","Historia de hipotensión ortostática"],
  ea=["Mareo","Hipotensión ortostática","Cefalea","Fatiga","Edema periférico","Somnolencia","Congestión nasal"],
  ix=["Otros antihipertensivos: hipotensión aditiva","IPDE5: hipotensión","Inhibidores CYP3A4: pueden aumentar niveles"],
  ce=["Titulación lenta obligatoria (hipotensión primera dosis)","Primera dosis al acostarse","Advertir sobre hipotensión ortostática","Ventaja: efecto dual en HTA+HPB","Informar oftalmólogo si cirugía de cataratas"],
  emb="C"),

# ── c07_04 Fármacos en Obstetricia (+5) ──
M("","acido_folico_alta_dosis","Ácido Fólico alta dosis","Ácido fólico",["Acfol","Zolico 5"],
  "Vitamina B9 a dosis altas para embarazo de alto riesgo",
  "Coenzima esencial en la síntesis de ácidos nucleicos y metionina. A dosis altas previene defectos del tubo neural en embarazos de alto riesgo",
  ["Prevención DTN en embarazo de alto riesgo","Antecedente de hijo con DTN","Uso de antiepilépticos en gestación","Diabetes pregestacional","Obesidad mórbida en embarazo"],["oral"],
  {"adulto":"5 mg/día desde 1-3 meses pre-concepción hasta sem 12 de gestación"},
  ["Comp 5 mg","Comp 10 mg"],"Compatible","u07","c07_04",
  familia="Vitaminas prenatales (alta dosis)",
  ci=["Hipersensibilidad","Tumores dependientes de folato (raro)","Anemia perniciosa no diagnosticada (puede enmascarar déficit B12)"],
  ea=["Muy raros a estas dosis","Malestar GI leve","Sabor amargo","Reacciones alérgicas (excepcional)"],
  ix=["Metotrexato: antagonismo (ácido folínico es alternativa)","Anticonvulsivantes: pueden reducir niveles de folato","Sulfasalazina: reduce absorción de folato"],
  ce=["Indicar en TODAS las mujeres con antecedente de DTN","Iniciar 1-3 meses antes de concepción","No sustituye el ácido fólico de dosis estándar en dieta","Verificar niveles de B12 antes de suplementar","Mantener hasta semana 12 de gestación"],
  emb="A"),

M("","hierro_iv_obstetrico","Hierro IV (obstétrico)","Hierro carboximaltosa",["Ferinject","Injectafer"],
  "Hierro parenteral para anemia severa en embarazo",
  "Complejo de hierro con carboximaltosa que permite administración de altas dosis en una sola infusión, liberando hierro al sistema reticuloendotelial",
  ["Anemia ferropénica severa en embarazo (Hb <9 g/dL)","Intolerancia o falta de respuesta a hierro oral","Anemia ferropénica postparto","Necesidad de reposición rápida de hierro"],["IV"],
  {"adulto":"Dosis según peso y Hb: 500-1000 mg en dosis única IV. Máx 1000 mg/semana. Repetir según necesidad tras 1 semana"},
  ["Vial 500 mg/10 mL","Vial 100 mg/2 mL"],"Compatible","u07","c07_04",
  familia="Hierro parenteral",
  ci=["Primer trimestre de embarazo","Hipersensibilidad a hierro IV","Sobrecarga de hierro (hemocromatosis)","Anemia no ferropénica","Infección activa"],
  ea=["Hipofosfatemia","Cefalea","Náuseas","Reacción en sitio de inyección","Rubor facial","Hipotensión transitoria","Reacción anafilactoide (raro)"],
  ix=["Hierro oral: suspender 5 días antes","Dimercaprol: contraindicado combinar","Cloranfenicol: puede reducir respuesta al hierro"],
  ce=["Administrar SOLO a partir del 2do trimestre","Infundir en mín 15 min (500 mg) o 30 min (1000 mg)","Monitorizar 30 min post-infusión por reacciones","Tener equipo de reanimación disponible","Control de Hb y ferritina a las 4-8 semanas","No administrar en 1er trimestre"],
  emb="C",
  pp={"dilucion":"Diluir en SF 0.9% (máx 250 mL para 500 mg, 250 mL para 1000 mg). NO usar SG5%","velocidadAdministracion":"500 mg en mín 15 min. 1000 mg en mín 30 min","estabilidad":"Usar inmediatamente tras dilución, máx 12h a TA"}),

M("","progesterona_vaginal","Progesterona vaginal","Progesterona micronizada",["Utrogestan vaginal","Crinone","Endometrin"],
  "Progestágeno natural por vía vaginal",
  "Progesterona idéntica a la endógena, por vía vaginal alcanza altas concentraciones uterinas con menor efecto sistémico (primer paso uterino)",
  ["Prevención de parto prematuro en cérvix corto","Soporte de fase lútea en FIV","Amenaza de aborto en primer trimestre","Insuficiencia lútea"],["vaginal"],
  {"adulto":"Cérvix corto: 200 mg/día vaginal desde sem 16-24 hasta sem 36. FIV: 200-400 mg c/8-12h vaginal"},
  ["Cáps vaginal 100, 200 mg","Gel vaginal 8% (90 mg)","Comp vaginal 100 mg"],"Compatible","u07","c07_04",
  familia="Progestágenos (vaginal)",
  ci=["Sangrado vaginal no diagnosticado","Porfiria","Tromboembolismo activo","Cáncer de mama o genital"],
  ea=["Somnolencia (mínima por vía vaginal)","Irritación vaginal local","Flujo vaginal aumentado","Cefalea","Mastalgia"],
  ix=["Inductores CYP3A4: pueden reducir eficacia","Ketoconazol: aumenta niveles sistémicos","Mínimas interacciones por vía vaginal"],
  ce=["Insertar profundamente en vagina al acostarse","Puede haber flujo residual del excipiente (normal)","No suspender bruscamente en embarazo","Vía vaginal preferida sobre oral en embarazo (menos EA sistémicos)","Mantener en refrigeración si gel"],
  emb="B"),

M("","cervidil_dinoprostone","Dinoprostona vaginal","Dinoprostona (PGE2)",["Cervidil","Propess","Prepidil"],
  "Prostaglandina E2 para maduración cervical",
  "Prostaglandina E2 que actúa sobre el colágeno cervical, produciendo ablandamiento, borramiento y dilatación del cérvix. También estimula contracciones uterinas",
  ["Maduración cervical pre-inducción del parto","Inducción del parto con cérvix desfavorable (Bishop <6)"],["vaginal"],
  {"adulto":"Dispositivo vaginal: 10 mg liberación controlada (0.3 mg/h) x 12-24h. Gel: 0.5 mg intracervical, repetir c/6h si necesario (máx 1.5 mg)"},
  ["Dispositivo vaginal 10 mg","Gel cervical 0.5 mg"],"No aplica","u07","c07_04",
  familia="Prostaglandinas (obstétricas)",
  ci=["Cesárea previa o cirugía uterina","Desproporción cefalopélvica","Placenta previa","Sufrimiento fetal","Infección uterina","Multiparidad (>5 partos)"],
  ea=["Taquisistolia uterina","Hipertonía uterina","Náuseas","Vómitos","Diarrea","Fiebre","Sufrimiento fetal por hiperestimulación"],
  ix=["Oxitocina: esperar mín 6h tras retirar dinoprostona","Otros uterotónicos: hiperestimulación"],
  ce=["Monitorización cardiotocográfica CONTINUA","Retirar dispositivo ante hiperestimulación o inicio de trabajo de parto activo","Mantener en congelación (-20°C) hasta uso","Paciente en decúbito 30 min post-inserción","Esperar 6h mínimo antes de iniciar oxitocina","Tener tocolíticos disponibles (terbutalina SC)"],
  emb="C"),

M("","desmopresina_obstetrica","Desmopresina (obstétrica)","Desmopresina (DDAVP)",["Minirin","Desmopressin"],
  "Análogo de vasopresina para diabetes insípida en embarazo",
  "Análogo sintético de vasopresina (ADH) con alta selectividad por receptor V2 renal, sin efecto vasopresor significativo. Resistente a vasopresinasa placentaria",
  ["Diabetes insípida gestacional","Diabetes insípida central en embarazo","Enfermedad de von Willebrand en embarazo/parto"],["intranasal","oral","IV","SC"],
  {"adulto":"DI gestacional: intranasal 10-20 mcg c/12h o oral 0.1-0.4 mg c/8-12h. VWD periparto: IV 0.3 mcg/kg en 30 min"},
  ["Spray nasal 10 mcg/dosis","Comp 0.1, 0.2 mg","Amp 4 mcg/mL"],"Compatible","u07","c07_04",
  familia="Análogos de vasopresina",
  ci=["Polidipsia psicógena","Insuficiencia cardíaca","Hiponatremia","Enfermedad de von Willebrand tipo IIB"],
  ea=["Hiponatremia dilucional","Cefalea","Náuseas","Congestión nasal","Dolor abdominal","Retención hídrica"],
  ix=["AINEs: potencian efecto antidiurético","Carbamazepina: potencia efecto","Litio: reduce efecto","Loperamida: potencia efecto antidiurético"],
  ce=["Monitorizar natremia estrechamente (riesgo hiponatremia)","Restringir ingesta hídrica 1h antes y 8h después","Diabetes insípida gestacional: resolver postparto (retirar gradualmente)","Pesar diariamente para detectar retención hídrica","En VWD: monitorizar factor VIII y actividad de VWF"],
  emb="B",
  pp={"dilucion":"Diluir en SF 50 mL para infusión IV","velocidadAdministracion":"Infundir en 30 min","estabilidad":"24h refrigerado diluido"}),

# ── c07_05 Hormonas y Anticonceptivos (+10) ──
M("anticonceptivo_hormonal","drospirenona","Drospirenona","Drospirenona",["Yaz (con EE)","Yasmin (con EE)","Slynd (sola)"],
  "Progestágeno con actividad antimineralocorticoide",
  "Progestágeno derivado de espironolactona con actividad antimineralocorticoide (reduce retención hídrica) y antiandrogénica, sin actividad estrogénica ni glucocorticoide",
  ["Anticoncepción oral","Trastorno disfórico premenstrual","Acné moderado","HTA leve (efecto antimineralocorticoide)"],["oral"],
  {"adulto":"Combinado (con EE): 3 mg/día x 21-24 días + placebo. Solo: 4 mg/día x 24 días + placebo 4 días"},
  ["Comp 3 mg + EE 0.03 mg (Yasmin)","Comp 3 mg + EE 0.02 mg (Yaz)","Comp 4 mg solo (Slynd)"],"Evitar en lactancia (combinados)","u07","c07_05"),

M("anticonceptivo_hormonal","gestodeno","Gestodeno","Gestodeno",["Femiane","Gynovin","Harmonet"],
  "Progestágeno de tercera generación",
  "Progestágeno de alta potencia con mínima actividad androgénica. Se combina con etinilestradiol para anticoncepción hormonal combinada",
  ["Anticoncepción oral combinada","Regulación del ciclo menstrual"],["oral"],
  {"adulto":"75 mcg/día + EE 20-30 mcg x 21 días + descanso 7 días"},
  ["Comp 75 mcg + EE 20 mcg","Comp 75 mcg + EE 30 mcg"],"Evitar en lactancia","u07","c07_05"),

M("anticonceptivo_hormonal","desogestrel_solo","Desogestrel solo (minipíldora)","Desogestrel",["Cerazette","Azalia","Nacrez"],
  "Progestágeno solo (minipíldora de nueva generación)",
  "Progestágeno de 3ª generación a dosis que inhibe ovulación en mayoría de ciclos (a diferencia de minipíldoras clásicas). También espesa moco cervical",
  ["Anticoncepción en mujeres con contraindicación a estrógenos","Anticoncepción durante lactancia","Mujeres >35 años fumadoras"],["oral"],
  {"adulto":"75 mcg/día continuo sin descanso"},
  ["Comp 75 mcg"],"Compatible (primera elección en lactancia)","u07","c07_05",
  ci=["TEV activo","Cáncer de mama actual","Hepatopatía activa grave","Sangrado genital no diagnosticado"],
  ea=["Sangrado irregular/spotting","Amenorrea","Cefalea","Acné","Mastalgia","Cambios de humor","Náuseas"],
  ce=["Tomar a la misma hora cada día (ventana de 12h vs 3h de minipíldora clásica)","Sangrado irregular es frecuente los primeros 3 meses","Sin descanso entre blísteres","Primera elección anticonceptiva en lactancia","Menor riesgo TEV que combinados"]),

M("","ciproterona","Ciproterona","Ciproterona",["Diane 35 (con EE)","Androcur"],
  "Antiandrógeno esteroideo y progestágeno",
  "Bloquea competitivamente receptores de andrógenos y reduce secreción de gonadotropinas. También tiene efecto progestágeno potente",
  ["Hirsutismo severo","Acné severo resistente","Síndrome de ovario poliquístico","Cáncer de próstata (varones)","Desviaciones sexuales severas (varones)"],["oral"],
  {"adulto":"Acné/hirsutismo (mujer): 2 mg/día + EE 35 mcg x 21 días. Monoterapia (varón): 50-100 mg c/12h"},
  ["Comp 2 mg + EE 35 mcg (Diane)","Comp 50, 100 mg (Androcur)"],"Contraindicado","u07","c07_05",
  familia="Antiandrógenos",
  ci=["Embarazo","Hepatopatía activa","Tromboembolismo activo","Depresión severa","Meningioma (actual o antecedente)","Anemia falciforme"],
  ea=["Hepatotoxicidad","Tromboembolismo","Depresión","Fatiga","Aumento de peso","Ginecomastia (varones)","Amenorrea","Meningioma (uso prolongado a altas dosis)"],
  ix=["Alcohol: mayor hepatotoxicidad","Inductores CYP3A4: reducen niveles","Estatinas: mayor riesgo hepatotoxicidad","Anticoagulantes: puede alterar efecto"],
  ce=["Función hepática basal y periódica OBLIGATORIA","Riesgo de meningioma con dosis altas prolongadas (>10 mg/día)","Anticoncepción obligatoria en mujeres","Vigilar signos de depresión","En varones: espermatogénesis se normaliza meses tras suspender"],
  emb="X"),

M("","testosterona","Testosterona","Testosterona",["Testogel","Nebido","Reandron","Sustanon"],
  "Andrógeno endógeno (terapia de reemplazo)",
  "Hormona androgénica que se une al receptor de andrógenos, regulando desarrollo sexual masculino, masa muscular, densidad ósea y eritropoyesis",
  ["Hipogonadismo masculino","Pubertad tardía masculina","Terapia hormonal en transición FtM"],["IM","transdérmico","oral"],
  {"adulto":"Gel: 50 mg/día tópico. IM (undecanoato): 1000 mg c/10-14 sem. IM (enantato): 250 mg c/2-4 sem"},
  ["Gel 1% (50 mg/sobre)","Amp undecanoato 1000 mg/4 mL","Amp enantato 250 mg/mL","Comp undecanoato oral 40 mg"],"Contraindicado","u07","c07_05",
  familia="Andrógenos",
  ci=["Cáncer de próstata o mama masculino","Policitemia (Hto >54%)","Apnea del sueño severa no tratada","Embarazo","Insuficiencia cardíaca descompensada"],
  ea=["Policitemia","Acné","Ginecomastia","Alopecia androgénica","Aumento de PSA","Apnea del sueño","Retención hídrica","Hepatotoxicidad (oral)","Infertilidad (suprime espermatogénesis)"],
  ix=["Anticoagulantes: aumenta efecto","Insulina: puede requerir ajuste","Corticoides: retención hídrica aditiva"],
  ce=["Hemograma c/3-6 meses (vigilar policitemia: Hto >54% suspender)","PSA y tacto rectal antes y durante tratamiento","Gel: evitar contacto piel-piel con mujeres/niños","IM undecanoato: inyectar MUY lento (riesgo microembolismo pulmonar)","Informar que suprime fertilidad"],
  emb="X",
  pp={"dilucion":"No diluir preparados IM","velocidadAdministracion":"IM profunda, inyección muy lenta (undecanoato: 2 min)","estabilidad":"Almacenar a TA"}),

M("","danazol","Danazol","Danazol",["Danocrine","Ladogal"],
  "Andrógeno sintético atenuado",
  "Derivado de etisterona que suprime FSH y LH, inhibe esteroidogénesis ovárica y se une a receptores de andrógenos y progesterona. Crea estado hipoestrogénico",
  ["Endometriosis","Enfermedad fibroquística de mama","Angioedema hereditario (prevención)","Púrpura trombocitopénica idiopática refractaria"],["oral"],
  {"adulto":"Endometriosis: 200-400 mg c/12h x 3-6 meses. Angioedema: 200 mg c/8-12h"},
  ["Cáps 50, 100, 200 mg"],"Contraindicado","u07","c07_05",
  familia="Andrógenos sintéticos",
  ci=["Embarazo","Porfiria","Hepatopatía activa","Tromboembolismo activo","Sangrado genital no diagnosticado","Insuficiencia cardíaca o renal severa"],
  ea=["Aumento de peso","Acné","Hirsutismo","Voz grave (puede ser irreversible)","Amenorrea","Sofocos","Hepatotoxicidad","Edema","Cambios lipídicos desfavorables"],
  ix=["Anticoagulantes: aumenta efecto (reducir dosis de warfarina)","Ciclosporina: aumenta niveles","Carbamazepina: aumenta niveles","Estatinas: mayor riesgo miopatía"],
  ce=["Anticoncepción NO hormonal obligatoria durante tratamiento","Función hepática basal y mensual","Iniciar durante menstruación para excluir embarazo","Test embarazo previo","Cambios de voz pueden ser irreversibles (avisar paciente)","Perfil lipídico periódico"],
  emb="X"),

M("","tibolona","Tibolona","Tibolona",["Livial","Tibofem"],
  "Esteroide sintético con actividad estrogénica, progestágena y androgénica",
  "Esteroide que se metaboliza a tres compuestos con actividad estrogénica (hueso, vagina), progestágena (endometrio) y androgénica (cerebro, libido). Actividad tejido-selectiva",
  ["Síntomas vasomotores de la menopausia","Prevención de osteoporosis posmenopáusica","Disfunción sexual en menopausia"],["oral"],
  {"adulto":"2.5 mg/día continuo (iniciar mín 12 meses tras última menstruación)"},
  ["Comp 2.5 mg"],"Contraindicado","u07","c07_05",
  familia="Terapia hormonal (menopausia)",
  ci=["Cáncer de mama o endometrio (actual o antecedente)","TEV activo o antecedente","Sangrado vaginal no diagnosticado","Hepatopatía activa","Cardiopatía isquémica o ACV"],
  ea=["Sangrado vaginal","Aumento de peso","Dolor abdominal","Hirsutismo","Engrosamiento endometrial","Flujo vaginal","Cefalea"],
  ix=["Anticoagulantes: potencia efecto anticoagulante","Anticonvulsivantes inductores: reducen niveles","Rifampicina: reduce eficacia"],
  ce=["Iniciar mín 12 meses después de menopausia (reduce sangrado)","No requiere progestágeno adicional","Menor sangrado que THS convencional","Ecografía transvaginal basal y ante cualquier sangrado","Menor efecto mamario que estrógenos solos","Vigilar signos de TEV"],
  emb="X"),

M("","bazedoxifeno","Bazedoxifeno","Bazedoxifeno",["Conbriza","Duavive (con estrógenos conjugados)"],
  "Modulador selectivo del receptor de estrógenos (SERM) de 3ª generación",
  "SERM que actúa como agonista estrogénico en hueso (previene resorción) y antagonista en mama y útero. Se combina con estrógenos conjugados para THS sin progestágeno",
  ["Osteoporosis posmenopáusica","THS combinada con estrógenos conjugados (sin necesidad de progestágeno)"],["oral"],
  {"adulto":"Monoterapia: 20 mg/día. Combinado (Duavive): 20 mg + EC 0.45 mg/día"},
  ["Comp 20 mg","Comp 20 mg + EC 0.45 mg (Duavive)"],"Contraindicado","u07","c07_05",
  familia="SERM (moduladores selectivos del receptor de estrógenos)",
  ci=["TEV activo o antecedente","Embarazo","Sangrado uterino no diagnosticado","Hipersensibilidad"],
  ea=["Sofocos","Calambres en piernas","Artralgias","Sequedad vaginal","Náuseas"],
  ix=["Inductores CYP3A4: pueden reducir niveles","No interacciones clínicamente significativas mayores"],
  ce=["Ventaja: permite THS con estrógenos sin agregar progestágeno","Suplementar calcio y vitamina D","Vigilar signos de TEV","No usar para tratamiento de síntomas vasomotores sola","DMO basal y de seguimiento"],
  emb="X"),

M("","ospemifeno","Ospemifeno","Ospemifeno",["Osphena","Senshio"],
  "SERM para atrofia vulvovaginal",
  "Modulador selectivo del receptor de estrógenos con actividad agonista estrogénica en epitelio vaginal, mejorando trofismo. Antagonista parcial en mama y endometrio",
  ["Dispareunia moderada a severa por atrofia vulvovaginal posmenopáusica","Sequedad vaginal posmenopáusica"],["oral"],
  {"adulto":"60 mg/día con alimentos"},
  ["Comp 60 mg"],"No aplica","u07","c07_05",
  familia="SERM (moduladores selectivos del receptor de estrógenos)",
  ci=["Sangrado uterino no diagnosticado","Cáncer de mama o endometrio","TEV activo o antecedente","Embarazo"],
  ea=["Sofocos","Flujo vaginal","Espasmos musculares","Hiperhidrosis","Engrosamiento endometrial"],
  ix=["Fluconazol y otros inhibidores CYP2C9/3A4: aumentan niveles","Rifampicina: reduce niveles","Estrógenos: no combinar"],
  ce=["Tomar con alimentos (mejora absorción)","Alternativa oral a estrógenos vaginales locales","Ecografía transvaginal basal y ante sangrado","No combinar con estrógenos sistémicos o vaginales","Evaluar respuesta a las 8-12 semanas"],
  emb="X"),

M("","anastrozol_repro","Anastrozol (reproductivo)","Anastrozol",["Arimidex"],
  "Inhibidor de aromatasa para inducción de ovulación",
  "Inhibe aromatasa, reduciendo conversión de andrógenos a estrógenos. En reproducción, disminuye retroalimentación negativa de estrógenos sobre hipotálamo, aumentando liberación de FSH",
  ["Inducción de ovulación (uso off-label)","Síndrome de ovario poliquístico (alternativa a clomifeno)","Estimulación ovárica en FIV"],["oral"],
  {"adulto":"Inducción ovulación: 1 mg/día x 5 días desde día 3-5 del ciclo (off-label)"},
  ["Comp 1 mg"],"Contraindicado","u07","c07_05",
  familia="Inhibidores de aromatasa (reproductivo)",
  ci=["Embarazo","Premenopausia (uso oncológico)","Osteoporosis severa","Hipersensibilidad"],
  ea=["Sofocos","Artralgias","Cefalea","Quistes ováricos","Náuseas","Pérdida ósea (uso prolongado)"],
  ix=["Tamoxifeno: no combinar (reduce niveles de anastrozol)","Estrógenos: antagonismo farmacológico"],
  ce=["Uso off-label en reproducción (informar a paciente)","Ecografía folicular de seguimiento","Menor riesgo de embarazo múltiple que gonadotropinas","Sin efecto antiestrogénico endometrial (ventaja sobre clomifeno)","No usar más de 6 ciclos consecutivos"],
  emb="X"),

# ── c07_07 Fertilidad y Reproducción Asistida (10) ──
M("","gonadotropina_corionica","Gonadotropina Coriónica Humana (hCG)","Gonadotropina coriónica humana",["Pregnyl","Ovidrel","Choragon"],
  "Gonadotropina con actividad LH para desencadenar ovulación",
  "Mimetiza pico de LH, desencadenando maduración final del ovocito y ovulación. Mantiene cuerpo lúteo y producción de progesterona",
  ["Desencadenar ovulación en ciclos de estimulación","Soporte lúteo en FIV","Criptorquidia en niños","Hipogonadismo hipogonadotrópico masculino"],["IM","SC"],
  {"adulto":"Trigger ovulación: 5000-10000 UI IM o 250 mcg SC (r-hCG). Soporte lúteo: 1500-5000 UI c/3 días","pediatrico":"Criptorquidia: 500-1000 UI IM 2x/sem x 5 sem"},
  ["Amp 5000, 10000 UI (urinaria)","Jeringa 250 mcg (recombinante, Ovidrel)"],"Compatible","u07","c07_07",
  familia="Gonadotropinas",
  ci=["Tumores dependientes de andrógenos o estrógenos","Embarazo confirmado","Quiste ovárico no folicular","Síndrome de hiperestimulación ovárica activo","Sangrado uterino no diagnosticado"],
  ea=["Síndrome de hiperestimulación ovárica (SHO)","Embarazo múltiple","Dolor en sitio de inyección","Cefalea","Fatiga","Ginecomastia (varones)","Retención hídrica"],
  ix=["No interacciones farmacológicas significativas","Danazol: antagonismo"],
  ce=["Administrar según indicación del especialista en reproducción","Ecografía folicular PREVIA para confirmar folículos maduros","Vigilar signos de SHO post-trigger (dolor abdominal, distensión, disnea)","Ovulación ocurre 36-40h post-hCG","Conservar refrigerado (2-8°C)"],
  emb="X",
  pp={"dilucion":"Reconstituir liofilizado con solvente proporcionado","velocidadAdministracion":"IM o SC directa","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","folitropina_alfa","Folitropina alfa (FSH recombinante)","Folitropina alfa",["Gonal-F","Bemfola"],
  "FSH recombinante para estimulación ovárica",
  "Hormona foliculoestimulante recombinante que estimula desarrollo de folículos ováricos múltiples. Producida por tecnología ADN recombinante en células CHO",
  ["Estimulación ovárica controlada para FIV","Inducción de ovulación en anovulación","Estimulación espermatogénesis en hipogonadismo masculino"],["SC"],
  {"adulto":"FIV: 150-300 UI/día SC desde día 2-3 del ciclo, ajustar según respuesta ecográfica. Anovulación: 75-150 UI/día"},
  ["Pluma 300, 450, 900 UI","Vial 75 UI"],"Evitar en lactancia","u07","c07_07",
  familia="Gonadotropinas recombinantes",
  ci=["Tumores ováricos, uterinos o mamarios","Embarazo","Sangrado genital no diagnosticado","Insuficiencia ovárica primaria","Quistes ováricos no funcionales","Malformaciones incompatibles con embarazo"],
  ea=["Síndrome de hiperestimulación ovárica (1-5%)","Embarazo múltiple","Dolor abdominal","Cefalea","Reacción en sitio de inyección","Quistes ováricos","Torsión ovárica (raro)"],
  ix=["Clomifeno: puede potenciar estimulación","Otros análogos GnRH: ajustar según protocolo"],
  ce=["Ecografía folicular y estradiol sérico cada 2-3 días durante estimulación","Ajustar dosis según respuesta folicular","Vigilar signos de SHO: distensión abdominal, dolor, aumento rápido de peso","Enseñar técnica de autoinyección SC","Conservar refrigerado (2-8°C), pluma en uso: máx 28 días"],
  emb="X",
  pp={"dilucion":"Pluma prellenada lista para uso. Vial: reconstituir con solvente","velocidadAdministracion":"SC lenta","estabilidad":"Refrigerado 2-8°C. En uso a TA máx 28 días"}),

M("","folitropina_beta","Folitropina beta (FSH recombinante)","Folitropina beta",["Puregon"],
  "FSH recombinante para estimulación ovárica",
  "FSH humana recombinante producida en células CHO. Estimula crecimiento y maduración de folículos ováricos. Bioactividad equivalente a FSH urinaria",
  ["Estimulación ovárica para FIV/ICSI","Inducción de ovulación","Estimulación espermática en hipogonadismo hipogonadotrópico"],["SC","IM"],
  {"adulto":"FIV: 150-225 UI/día, ajustar c/3-5 días. Anovulación: 50-100 UI/día, incrementos de 25-50 UI"},
  ["Pluma 300, 600, 900 UI","Vial 50, 100 UI"],"Evitar en lactancia","u07","c07_07",
  familia="Gonadotropinas recombinantes",
  ci=["Tumores ováricos, uterinos o mamarios","Embarazo","Insuficiencia ovárica primaria","Sangrado genital no diagnosticado","Malformaciones uterinas incompatibles"],
  ea=["SHO","Embarazo múltiple","Dolor abdominal","Reacción local","Cefalea","Quistes ováricos"],
  ix=["Clomifeno: potenciación de estimulación","Ajustar según protocolo FIV"],
  ce=["Ecografía folicular seriada obligatoria","Monitorizar estradiol sérico","Enseñar autoinyección con pluma","Conservar refrigerado","Cancelar ciclo si respuesta excesiva (>3 folículos en inducción simple)"],
  emb="X"),

M("","menotropina","Menotropinas (hMG)","Menotropinas (FSH+LH urinarias)",["Menopur","HMG-Lepori"],
  "Gonadotropina menopáusica humana (FSH+LH)",
  "Preparado urinario altamente purificado con FSH y LH en proporción 1:1, que estimula crecimiento folicular (FSH) y producción de esteroides (LH)",
  ["Estimulación ovárica para FIV","Inducción ovulación en anovulación con déficit de LH","Estimulación espermática masculina"],["SC","IM"],
  {"adulto":"FIV: 150-300 UI/día desde día 2-3. Anovulación: 75-150 UI/día, ajustar c/7 días"},
  ["Vial 75 UI (FSH+LH)","Vial 150 UI"],"Evitar en lactancia","u07","c07_07",
  familia="Gonadotropinas urinarias",
  ci=["Tumores dependientes de hormonas","Embarazo","Insuficiencia ovárica primaria","Quistes ováricos","Sangrado genital no diagnosticado"],
  ea=["SHO","Embarazo múltiple","Dolor abdominal","Reacción en sitio inyección","Cefalea","Torsión ovárica (raro)"],
  ix=["Clomifeno: puede potenciar respuesta","GnRH análogos: según protocolo de estimulación"],
  ce=["Monitorización ecográfica y hormonal cada 2-3 días","Contiene LH: ventaja en pacientes con déficit de LH","Reconstituir con solvente proporcionado","Enseñar técnica autoinyección","Conservar a TA antes de reconstitución, refrigerado tras reconstitución"],
  emb="X",
  pp={"dilucion":"Reconstituir con solvente estéril proporcionado","velocidadAdministracion":"SC o IM directa","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","lutropina_alfa","Lutropina alfa (LH recombinante)","Lutropina alfa",["Luveris"],
  "LH recombinante para estimulación ovárica",
  "Hormona luteinizante recombinante que complementa la FSH en estimulación ovárica. Esencial en pacientes con déficit severo de LH y FSH",
  ["Estimulación ovárica junto con FSH en déficit severo de LH","Hipogonadismo hipogonadotrópico femenino"],["SC"],
  {"adulto":"75 UI/día SC junto con FSH (folitropina alfa 75-150 UI/día). Ajustar según respuesta"},
  ["Vial 75 UI liofilizado"],"Evitar en lactancia","u07","c07_07",
  familia="Gonadotropinas recombinantes",
  ci=["Tumores hipofisarios o hipotalámicos","Tumores ováricos o mamarios","Embarazo","Insuficiencia ovárica primaria","Quistes ováricos"],
  ea=["SHO","Dolor abdominal","Cefalea","Quistes ováricos","Somnolencia","Náuseas","Reacción en sitio de inyección"],
  ix=["Debe usarse SIEMPRE con FSH","Sin interacciones farmacológicas significativas adicionales"],
  ce=["Siempre administrar junto con FSH (no usar sola)","Indicada en déficit severo de LH (<1.2 UI/L)","Ecografía y estradiol c/2-3 días","Reconstituir con solvente y usar inmediatamente","Conservar refrigerado (2-8°C)"],
  emb="X",
  pp={"dilucion":"Reconstituir con solvente proporcionado","velocidadAdministracion":"SC directa","estabilidad":"Usar inmediatamente"}),

M("","corifolitropina_alfa","Corifolitropina alfa (FSH larga duración)","Corifolitropina alfa",["Elonva"],
  "FSH recombinante de acción prolongada",
  "Molécula híbrida de FSH con cadena C-terminal de hCG que le confiere vida media de 69h (vs 24h FSH). Una sola inyección reemplaza 7 días de FSH diaria",
  ["Estimulación ovárica controlada en FIV con protocolo antagonista GnRH"],["SC"],
  {"adulto":"≤60 kg: 100 mcg SC dosis única día 1 del ciclo. >60 kg: 150 mcg SC dosis única. Continuar con FSH diaria desde día 8 si necesario"},
  ["Jeringa 100 mcg","Jeringa 150 mcg"],"Evitar en lactancia","u07","c07_07",
  familia="Gonadotropinas recombinantes (larga duración)",
  ci=["Tumores ováricos, uterinos o mamarios","SHO activo o antecedente severo","Embarazo","Insuficiencia ovárica primaria","Quistes ováricos >25 mm","SOP (mayor riesgo SHO)"],
  ea=["SHO","Molestias pélvicas","Cefalea","Embarazo múltiple","Fatiga","Náuseas","Quistes ováricos"],
  ix=["Antagonistas GnRH: protocolo estándar combinado","No se conocen interacciones significativas adicionales"],
  ce=["UNA sola inyección sustituye 7 días de FSH diaria (mejora adherencia)","Ecografía y estradiol desde día 5","Solo en protocolo antagonista (NO agonista)","No repetir dosis en mismo ciclo","Mayor riesgo SHO en pacientes con SOP","Conservar refrigerado (2-8°C)"],
  emb="X"),

M("","progesterona_micronizada","Progesterona Micronizada","Progesterona micronizada",["Utrogestan","Prometrium","Crinone"],
  "Progesterona natural micronizada para soporte lúteo",
  "Progesterona idéntica a la endógena en forma micronizada que mejora biodisponibilidad oral y vaginal. Mantiene endometrio secretor y favorece implantación",
  ["Soporte de fase lútea en FIV/RA","Insuficiencia lútea","Amenaza de aborto en primer trimestre","Terapia hormonal sustitutiva (protección endometrial)"],["oral","vaginal"],
  {"adulto":"FIV vaginal: 200 mg c/8h desde punción hasta sem 10-12. Oral: 200 mg/día al acostarse (THS)"},
  ["Cáps 100, 200 mg (oral/vaginal)","Gel vaginal 8% (90 mg)"],"Compatible","u07","c07_07",
  familia="Progestágenos naturales",
  ci=["Sangrado vaginal no diagnosticado","Tromboembolismo activo","Hepatopatía activa grave","Cáncer de mama","Porfiria"],
  ea=["Somnolencia y mareo (oral)","Mastalgia","Distensión abdominal","Náuseas (oral)","Flujo vaginal (vaginal)","Irritación local (vaginal)"],
  ix=["Inductores CYP3A4: reducen niveles","Ketoconazol: aumenta niveles","Ciclosporina: puede aumentar niveles de ciclosporina"],
  ce=["Vía vaginal preferida en RA (menor somnolencia, altas concentraciones uterinas)","Oral: tomar al acostarse por somnolencia","No suspender bruscamente en embarazo","Cápsulas son intercambiables oral/vaginal","En THS: protege endometrio contra hiperplasia"],
  emb="B"),

M("","cetrorrelixida","Cetrorelix","Cetrorelix",["Cetrotide"],
  "Antagonista de GnRH para FIV",
  "Antagonista competitivo del receptor de GnRH que bloquea inmediatamente la liberación de LH y FSH, previniendo ovulación prematura durante estimulación ovárica",
  ["Prevención del pico prematuro de LH en FIV","Protocolo antagonista de estimulación ovárica"],["SC"],
  {"adulto":"0.25 mg/día SC desde día 5-6 de estimulación (o cuando folículo líder ≥14 mm) hasta día del trigger con hCG inclusive"},
  ["Vial 0.25 mg + solvente","Vial 3 mg"],"Evitar en lactancia","u07","c07_07",
  familia="Antagonistas de GnRH",
  ci=["Embarazo","Insuficiencia renal o hepática moderada-severa","Hipersensibilidad a péptidos GnRH","Menopausia"],
  ea=["Reacción local (enrojecimiento, prurito)","Náuseas","Cefalea","SHO (relacionado con estimulación)"],
  ix=["No interacciones significativas conocidas","Usar con gonadotropinas según protocolo"],
  ce=["Inicio flexible: cuando folículo líder ≥14 mm o estradiol >400 pg/mL","Inyectar SC en abdomen periumbilical","Rotar sitios de inyección","Reconstituir suavemente (no agitar)","Bloqueo de LH es inmediato (ventaja del protocolo antagonista)"],
  emb="X",
  pp={"dilucion":"Reconstituir con agua estéril proporcionada","velocidadAdministracion":"SC directa lenta","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","acetato_ganirelixida","Ganirelix","Ganirelix",["Orgalutran","Fyremadel"],
  "Antagonista de GnRH para prevención de ovulación prematura",
  "Antagonista competitivo de GnRH que suprime rápidamente gonadotropinas (LH y FSH). Previene el pico prematuro de LH durante estimulación ovárica controlada",
  ["Prevención ovulación prematura en FIV","Protocolo antagonista de reproducción asistida"],["SC"],
  {"adulto":"0.25 mg/día SC desde día 5-6 de estimulación (o folículo ≥14 mm) hasta día del trigger"},
  ["Jeringa prellenada 0.25 mg/0.5 mL"],"Evitar en lactancia","u07","c07_07",
  familia="Antagonistas de GnRH",
  ci=["Embarazo","Hipersensibilidad a péptidos GnRH","Insuficiencia hepática o renal moderada-severa"],
  ea=["Reacción en sitio inyección","Cefalea","Náuseas","Dolor abdominal","SHO (por estimulación concomitante)"],
  ix=["Sin interacciones farmacológicas significativas conocidas","Usar según protocolo con gonadotropinas"],
  ce=["Jeringa prellenada: facilita autoinyección","Inyectar SC en abdomen inferior o muslo","Rotar sitios","Bloqueo gonadotrópico rápido y reversible","Mantener a TA (no requiere refrigeración)","Administrar a la misma hora cada día"],
  emb="X"),

M("","triptorelina_fiv","Triptorelina (FIV)","Triptorelina",["Decapeptyl","Gonapeptyl"],
  "Agonista de GnRH para protocolos de FIV",
  "Agonista potente de GnRH que inicialmente estimula (flare-up) y luego suprime liberación de gonadotropinas por desensibilización hipofisaria (down-regulation)",
  ["Desensibilización hipofisaria en protocolo largo de FIV","Trigger de ovulación en protocolo antagonista (alternativa a hCG para reducir riesgo SHO)"],["SC","IM"],
  {"adulto":"Protocolo largo: 0.1 mg/día SC desde día 21 del ciclo previo hasta down-regulation. Trigger: 0.2 mg SC dosis única (protocolo antagonista)"},
  ["Vial 0.1 mg","Amp 3.75 mg depot","Jeringa 0.1 mg/mL"],"Evitar en lactancia","u07","c07_07",
  familia="Agonistas de GnRH",
  ci=["Embarazo","Sangrado vaginal no diagnosticado","Hipersensibilidad a GnRH o análogos"],
  ea=["Sofocos","Cefalea","Sangrado vaginal inicial (flare-up)","Quistes ováricos","Fatiga","Cambios de humor","Disminución densidad ósea (uso prolongado)"],
  ix=["Puede alterar respuesta a gonadotropinas","Fármacos que elevan prolactina: interferencia"],
  ce=["Protocolo largo: iniciar día 21 del ciclo previo","Flare-up inicial esperado (aumento transitorio de gonadotropinas)","Como trigger: menor riesgo SHO que hCG (usar en respondedoras altas)","Verificar desensibilización antes de iniciar gonadotropinas (estradiol <50 pg/mL)","Conservar refrigerado"],
  emb="X",
  pp={"dilucion":"Solución lista para inyección SC","velocidadAdministracion":"SC directa","estabilidad":"Refrigerado 2-8°C"}),

# ── c07_08 Menopausia y Terapia Hormonal (10) ──
M("","estradiol_parche","Estradiol transdérmico","Estradiol",["Evopad","Estradot","Climara"],
  "Estrógeno natural por vía transdérmica",
  "17-beta estradiol liberado a través de la piel, evitando primer paso hepático. Mantiene niveles séricos estables con menor impacto sobre triglicéridos y coagulación que vía oral",
  ["Síntomas vasomotores de menopausia","Prevención osteoporosis posmenopáusica","Insuficiencia ovárica prematura","Atrofia urogenital"],["transdérmico"],
  {"adulto":"25-100 mcg/día (parche c/3-4 o c/7 días según producto). Iniciar con dosis baja (25-50 mcg)"},
  ["Parche 25, 37.5, 50, 75, 100 mcg/día"],"Compatible con precaución","u07","c07_08",
  familia="Terapia hormonal (estrógenos transdérmicos)",
  ci=["Cáncer de mama o endometrio","TEV activo o antecedente","Sangrado vaginal no diagnosticado","Hepatopatía activa","ACV o cardiopatía isquémica"],
  ea=["Irritación cutánea en sitio del parche","Mastalgia","Cefalea","Sangrado vaginal","Náuseas (menos que oral)","Retención hídrica"],
  ix=["Inductores CYP3A4: menor impacto que oral","Menor efecto sobre triglicéridos y coagulación que vía oral"],
  ce=["Aplicar en piel limpia y seca del tronco o nalga (NO mamas)","Rotar sitio de aplicación","Añadir progestágeno si útero intacto","Vía transdérmica: menor riesgo TEV que oral","Cambiar según esquema del producto (c/3-4 o c/7 días)","Dosis mínima eficaz por mínimo tiempo"],
  emb="X"),

M("","estradiol_gel","Estradiol gel","Estradiol",["Oestrogel","EstroGel","Divigel"],
  "Estrógeno natural en gel transdérmico",
  "17-beta estradiol en gel hidroalcohólico que permite absorción percutánea. Evita primer paso hepático con menor efecto sobre factores de coagulación",
  ["Síntomas vasomotores de menopausia","Atrofia vulvovaginal","Insuficiencia ovárica prematura"],["transdérmico"],
  {"adulto":"0.5-1.5 mg/día (1-3 pulsaciones según producto). Ajustar según respuesta"},
  ["Gel 0.06% (dosificador 0.75 mg/pulsación)","Gel sachet 0.5, 1 mg"],"Compatible con precaución","u07","c07_08",
  familia="Terapia hormonal (estrógenos transdérmicos)",
  ci=["Cáncer de mama o endometrio","TEV activo","Sangrado vaginal no diagnosticado","Hepatopatía activa","Cardiopatía isquémica o ACV"],
  ea=["Irritación cutánea leve","Mastalgia","Cefalea","Sangrado vaginal","Retención hídrica"],
  ix=["Menor impacto en primer paso hepático que vía oral","Evitar aplicar protector solar en misma zona"],
  ce=["Aplicar en brazos, hombros o muslos internos","Dejar secar 5 min antes de vestirse","No aplicar en mamas ni mucosas","Evitar contacto piel-piel con niños/pareja (transferencia)","Lavarse manos tras aplicación","Añadir progestágeno si útero intacto"],
  emb="X"),

M("","estriol_vaginal","Estriol vaginal","Estriol",["Ovestin","Blissel","Colpotrophine"],
  "Estrógeno débil de acción local vaginal",
  "Estrógeno natural débil con alta afinidad por mucosa vaginal. Acción local con mínima absorción sistémica. Restaura epitelio vaginal atrófico y pH ácido",
  ["Atrofia vulvovaginal posmenopáusica","Dispareunia por sequedad vaginal","Infecciones urinarias recurrentes en posmenopausia","Pre-cirugía vaginal en atrofia"],["vaginal"],
  {"adulto":"Crema/óvulos: 0.5 mg/día x 2-3 sem, luego 0.5 mg 2x/sem como mantenimiento"},
  ["Crema vaginal 1 mg/g","Óvulos vaginales 0.5 mg"],"Compatible","u07","c07_08",
  familia="Estrógenos locales",
  ci=["Cáncer de mama o endometrio","Sangrado vaginal no diagnosticado","TEV activo","Hiperplasia endometrial no tratada"],
  ea=["Irritación vaginal transitoria","Flujo vaginal","Sangrado leve (inicio)","Mastalgia leve (raro)"],
  ix=["Mínima absorción sistémica: pocas interacciones","No requiere progestágeno en la mayoría de guías"],
  ce=["Aplicar al acostarse con aplicador","No requiere progestágeno adicional (consenso mayoritario)","Efecto local con mínima absorción sistémica","Puede usarse largo plazo en atrofia","Puede usar lubricante no hormonal complementario","Seguro incluso en supervivientes de cáncer de mama (según algunas guías)"],
  emb="X"),

M("","prasterona","Prasterona (DHEA vaginal)","Prasterona (dehidroepiandrosterona)",["Intrarosa"],
  "DHEA vaginal para atrofia vulvovaginal",
  "DHEA (prohormona) que se convierte localmente en estrógenos y andrógenos en mucosa vaginal mediante enzimas intracrinas, sin aumento significativo de niveles séricos",
  ["Atrofia vulvovaginal posmenopáusica moderada a severa","Dispareunia por deficiencia estrogénica"],["vaginal"],
  {"adulto":"6.5 mg/día intravaginal al acostarse"},
  ["Óvulos vaginales 6.5 mg"],"No aplica","u07","c07_08",
  familia="Prohormona (DHEA local)",
  ci=["Sangrado vaginal no diagnosticado","Cáncer de mama o endometrio","Hipersensibilidad"],
  ea=["Flujo vaginal","Frotis Pap anormal (sin significancia clínica)","Pérdida de peso"],
  ix=["Sin interacciones sistémicas significativas","Mínima absorción sistémica"],
  ce=["Insertar óvulo profundamente al acostarse","Mecanismo intracrino: acción local sin efecto sistémico","No requiere progestágeno adicional","Almacenar a TA (no refrigerar)","Alternativa en mujeres que prefieren evitar estrógenos","Evaluar respuesta a las 12 semanas"],
  emb="X"),

M("","conjugados_equinos","Estrógenos Conjugados","Estrógenos equinos conjugados",["Premarin","Colpotrofin"],
  "Mezcla de estrógenos equinos para THS",
  "Mezcla de estrógenos sulfatados de origen equino (estrona, equilina y otros). Acción estrogénica sistémica sobre síntomas vasomotores, hueso y tejidos urogenitales",
  ["Síntomas vasomotores de menopausia","Prevención osteoporosis posmenopáusica","Atrofia vulvovaginal","Hipogonadismo femenino"],["oral","vaginal"],
  {"adulto":"Oral: 0.3-0.625 mg/día (dosis mínima eficaz). Vaginal: crema 0.5 g/día x 21 días, descanso 7 días"},
  ["Comp 0.3, 0.625, 1.25 mg","Crema vaginal 0.625 mg/g"],"Evitar en lactancia","u07","c07_08",
  familia="Estrógenos conjugados",
  ci=["Cáncer de mama o endometrio","TEV activo o antecedente","Sangrado vaginal no diagnosticado","Hepatopatía activa","ACV o cardiopatía isquémica"],
  ea=["Mastalgia","Sangrado vaginal","Náuseas","Cefalea","Retención hídrica","Aumento de triglicéridos","Mayor riesgo TEV (oral)"],
  ix=["Inductores CYP3A4: reducen niveles","Inhibidores CYP3A4: aumentan niveles","Levotiroxina: puede requerir ajuste"],
  ce=["Dosis mínima eficaz por mínimo tiempo necesario","Obligatorio añadir progestágeno si útero intacto (oral)","Mamografía anual","Monitorizar presión arterial","Reevaluar necesidad anualmente","Estudio WHI: balance riesgo/beneficio individualizar"],
  emb="X"),

M("","estradiol_drospirenona","Estradiol/Drospirenona","Estradiol + Drospirenona",["Angeliq"],
  "THS combinada continua con progestágeno antimineralocorticoide",
  "Combinación de estradiol (estrógeno) con drospirenona (progestágeno antimineralocorticoide). Menor retención hídrica y efecto favorable sobre TA comparado con otras combinaciones",
  ["Síntomas vasomotores en posmenopausia","Prevención osteoporosis posmenopáusica (con útero intacto)"],["oral"],
  {"adulto":"1 comp/día continuo (estradiol 1 mg + drospirenona 2 mg)"},
  ["Comp estradiol 1 mg + drospirenona 2 mg"],"Evitar en lactancia","u07","c07_08",
  familia="Terapia hormonal combinada",
  ci=["Cáncer de mama o endometrio","TEV activo","Sangrado vaginal no diagnosticado","Hepatopatía activa","Insuficiencia renal severa","Hiperpotasemia"],
  ea=["Mastalgia","Sangrado vaginal","Cefalea","Dolor abdominal","Edema (menor que otras combinaciones)","Hiperpotasemia (raro)"],
  ix=["IECA/ARA-II/espironolactona: riesgo hiperpotasemia por drospirenona","Inductores CYP3A4: reducen niveles","AINEs: posible retención de potasio"],
  ce=["Vigilar potasio si uso con IECA, ARA-II o espironolactona","Menor retención hídrica (ventaja de drospirenona)","Régimen continuo: no hay sangrado por deprivación","Mamografía anual","Reevaluar necesidad cada 6-12 meses"],
  emb="X"),

M("","estradiol_noretisterona","Estradiol/Noretisterona","Estradiol + Noretisterona",["Activelle","Kliogest"],
  "THS combinada continua",
  "Combinación de estradiol con noretisterona (progestágeno) en régimen continuo, que evita sangrado por deprivación al suprimir proliferación endometrial",
  ["Síntomas vasomotores en posmenopausia (>1 año)","Prevención osteoporosis posmenopáusica (con útero intacto)"],["oral"],
  {"adulto":"1 comp/día continuo (estradiol 1 mg + noretisterona 0.5 mg)"},
  ["Comp estradiol 1 mg + noretisterona 0.5 mg"],"Evitar en lactancia","u07","c07_08",
  familia="Terapia hormonal combinada",
  ci=["Cáncer de mama o endometrio","TEV activo o antecedente","Sangrado vaginal no diagnosticado","Hepatopatía activa","ACV o cardiopatía isquémica"],
  ea=["Mastalgia","Sangrado vaginal (primeros meses)","Cefalea","Distensión abdominal","Retención hídrica","Cambios de humor"],
  ix=["Inductores CYP3A4 (rifampicina, antiepilépticos): reducen eficacia","Inhibidores CYP3A4: aumentan niveles"],
  ce=["Iniciar mínimo 12 meses después de última menstruación","Sangrado durante primeros 3-6 meses puede ser normal","Si sangrado persiste >6 meses: investigar","Mamografía anual","Dosis mínima por mínimo tiempo","Reevaluar necesidad anualmente"],
  emb="X"),

M("","isoflavonas_soja","Isoflavonas de Soja","Isoflavonas de soja (genisteína, daidzeína)",["Fisiogen","Phyto Soya","Flavia"],
  "Fitoestrógenos derivados de la soja",
  "Isoflavonas (genisteína, daidzeína) que se unen débilmente a receptores estrogénicos (preferencia por ER-beta). Actividad estrogénica 100-1000 veces menor que estradiol",
  ["Síntomas vasomotores leves de menopausia","Alternativa no hormonal a THS"],["oral"],
  {"adulto":"40-80 mg/día de isoflavonas totales (equivalente a genisteína)"},
  ["Cáps 40 mg isoflavonas","Comp 80 mg"],"Compatible","u07","c07_08",
  familia="Fitoestrógenos",
  ci=["Cáncer de mama estrógeno-dependiente (precaución, evidencia contradictoria)","Hipersensibilidad a soja"],
  ea=["Molestias GI leves","Distensión abdominal","Cefalea (raro)","Generalmente bien tolerado"],
  ix=["Levotiroxina: separar administración 2-4h","Tamoxifeno: teórica interacción (datos limitados)","Sin interacciones significativas en general"],
  ce=["Evidencia de eficacia moderada (variable entre pacientes)","Efecto tarda 4-12 semanas","No sustituye THS en síntomas severos","Suplemento dietético, no fármaco de prescripción","Puede usarse en mujeres con contraindicación a THS (individualizar en ca mama)"],
  emb="A"),

M("","fitoestrogenoa_cimicifuga","Cimicífuga racemosa","Actaea racemosa (Cimicífuga)",["Remifemin","Klimadynon","Menopace"],
  "Fitoterapia para síntomas menopáusicos",
  "Extracto de raíz de Actaea racemosa con mecanismo no completamente elucidado. Posible modulación serotoninérgica y dopaminérgica central más que efecto estrogénico directo",
  ["Síntomas vasomotores de menopausia","Sudoración nocturna","Trastornos del ánimo perimenopáusicos"],["oral"],
  {"adulto":"20 mg de extracto estandarizado c/12h (equivalente a 2.5 mg de triterpenos)"},
  ["Comp 20 mg extracto estandarizado","Gotas"],"Compatible","u07","c07_08",
  familia="Fitoterapia menopáusica",
  ci=["Hepatopatía activa","Hipersensibilidad","Cáncer de mama (precaución)"],
  ea=["Molestias GI","Cefalea","Hepatotoxicidad (rara pero reportada)","Rash cutáneo","Mareo"],
  ix=["Sustratos CYP2D6: posible interacción","Hepatotóxicos: precaución aditiva","Tamoxifeno: datos insuficientes"],
  ce=["Monitorizar función hepática si uso >6 meses","No exceder 6 meses de uso continuo sin reevaluación","Suspender y consultar si ictericia, orina oscura o fatiga inusual","Evidencia de eficacia limitada pero mejor que placebo en algunos estudios","No tiene efecto estrogénico confirmado"],
  emb="C"),

M("","veraliprida","Veraliprida","Veraliprida",["Agreal"],
  "Antagonista dopaminérgico para sofocos menopáusicos",
  "Antagonista del receptor D2 dopaminérgico que reduce sofocos por modulación de termorregulación hipotalámica. Retirada del mercado en muchos países por EA neurológicos",
  ["Sofocos severos refractarios a otros tratamientos"],["oral"],
  {"adulto":"100 mg/día x 20 días, descanso 10 días. Máx 3 meses"},
  ["Cáps 100 mg"],"Contraindicado","u07","c07_08",
  familia="Antidopaminérgicos",
  ci=["Depresión","Enfermedad de Parkinson","Prolactinoma","Epilepsia","Insuficiencia renal o hepática","Feocromocitoma"],
  ea=["Síntomas extrapiramidales","Depresión","Ansiedad","Galactorrea","Aumento de peso","Somnolencia","Discinesia tardía (uso prolongado)"],
  ix=["Levodopa/antiparkinsonianos: antagonismo","Otros antidopaminérgicos: efectos aditivos","Depresores SNC: mayor sedación"],
  ce=["Retirada en muchos países (España, Francia) por EA neuropsiquiátricos","Usar SOLO si otras opciones han fallado","Máximo 3 meses de tratamiento","Vigilar síntomas extrapiramidales y depresión","Suspender gradualmente","Informar a paciente sobre perfil de seguridad desfavorable"],
  emb="X"),

# ── c07_09 Fármacos para Endometriosis y Miomas (7) ──
M("","dienogest_endometriosis","Dienogest (endometriosis)","Dienogest",["Visanne","Dienogest"],
  "Progestágeno selectivo para endometriosis",
  "Progestágeno de 4ª generación con potente efecto progestágeno local sobre endometrio ectópico. Inhibe aromatasa endometrial y reduce estrógenos locales. Suprime parcialmente ovulación",
  ["Endometriosis (tratamiento médico de 1ª línea)","Dolor pélvico asociado a endometriosis"],["oral"],
  {"adulto":"2 mg/día continuo sin descanso. Iniciar cualquier día del ciclo"},
  ["Comp 2 mg"],"Evitar en lactancia","u07","c07_09",
  familia="Progestágenos (endometriosis)",
  ci=["TEV activo","Hepatopatía activa grave","Cáncer de mama","Sangrado vaginal no diagnosticado","Embarazo"],
  ea=["Sangrado irregular/spotting (frecuente primeros meses)","Cefalea","Mastalgia","Acné","Cambios de humor","Disminución de libido","Aumento de peso leve"],
  ix=["Inductores CYP3A4: pueden reducir eficacia","Inhibidores CYP3A4: pueden aumentar niveles","Anticonvulsivantes inductores: reducen eficacia"],
  ce=["Tratamiento continuo sin descanso","Sangrado irregular es frecuente los primeros 3 meses, luego disminuye","No es anticonceptivo fiable (usar barrera adicional)","Eficacia comparable a análogos GnRH con mejor tolerabilidad","Reevaluar respuesta a los 3-6 meses","Mejor perfil óseo que análogos GnRH (no causa pérdida ósea significativa)"],
  emb="X"),

M("","leuprolida_endometriosis","Leuprolida (endometriosis)","Leuprolida",["Lupron Depot","Ginecrin Depot"],
  "Agonista GnRH depot para endometriosis",
  "Agonista de GnRH que tras estimulación inicial (flare-up) produce desensibilización hipofisaria con supresión profunda de estrógenos, creando pseudomenopausia médica reversible",
  ["Endometriosis moderada-severa","Reducción preoperatoria de endometriomas","Miomas uterinos (preoperatorio)","Pubertad precoz"],["IM","SC"],
  {"adulto":"Depot: 3.75 mg IM mensual o 11.25 mg IM trimestral. Máx 6 meses sin add-back"},
  ["Vial depot 3.75 mg mensual","Vial depot 11.25 mg trimestral"],"Contraindicado","u07","c07_09",
  familia="Agonistas de GnRH",
  ci=["Embarazo","Sangrado vaginal no diagnosticado","Hipersensibilidad a GnRH","Osteoporosis severa preexistente"],
  ea=["Sofocos","Sudoración nocturna","Sequedad vaginal","Pérdida ósea","Cefalea","Depresión","Artralgias","Flare-up inicial (empeoramiento transitorio primeras 2 sem)"],
  ix=["Add-back therapy (noretisterona + estradiol): reduce EA sin perder eficacia","Calcio/vitamina D: suplementar siempre"],
  ce=["Máximo 6 meses sin add-back (pérdida ósea)","Con add-back therapy puede extenderse","Flare-up inicial: avisar sobre posible empeoramiento temporal","DMO si uso >6 meses","Suplementar calcio 1000 mg + vit D 400 UI/día","Reconstitución estricta según instrucciones del fabricante"],
  emb="X",
  pp={"dilucion":"Reconstituir depot con diluyente proporcionado (agitar hasta suspensión uniforme)","velocidadAdministracion":"IM profunda inmediata tras reconstitución","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","elagolix","Elagolix","Elagolix",["Orilissa"],
  "Antagonista oral de GnRH para endometriosis",
  "Primer antagonista GnRH oral no peptídico. Produce supresión parcial y dosis-dependiente de estrógenos (no castración completa), manteniendo cierto nivel estrogénico",
  ["Dolor moderado-severo por endometriosis","Dispareunia asociada a endometriosis"],["oral"],
  {"adulto":"Dosis baja: 150 mg/día (dismenorrea). Dosis alta: 200 mg c/12h (dispareunia/dolor no menstrual). Máx 24 meses (baja) o 6 meses (alta)","ajusteHepatico":"Dosis baja: máx 150 mg/día. Contraindicado en IH severa"},
  ["Comp 150, 200 mg"],"Contraindicado","u07","c07_09",
  familia="Antagonistas orales de GnRH",
  ci=["Embarazo","Osteoporosis","Insuficiencia hepática severa","Uso con inhibidores potentes OATP1B1"],
  ea=["Sofocos","Sudoración nocturna","Cefalea","Náuseas","Insomnio","Artralgias","Pérdida ósea (dosis alta)","Amenorrea o sangrado irregular"],
  ix=["Inhibidores OATP1B1 (ciclosporina): contraindicado","Inductores P-gp/CYP3A4: reducen niveles","Anticonceptivos hormonales: no usar combinados (reducen eficacia mutua)"],
  ce=["Primera línea oral antes de análogos GnRH inyectables","Dosis baja: supresión estrogénica parcial (mejor perfil óseo)","Anticoncepción NO hormonal obligatoria","Tomar a la misma hora cada día","DMO si dosis alta >6 meses","Inicio rápido de acción (no requiere flare-up)"],
  emb="X"),

M("","relugolix","Relugolix","Relugolix",["Relumina","Myfembree (combo)","Orgovyx"],
  "Antagonista oral de GnRH para miomas y endometriosis",
  "Antagonista oral no peptídico del receptor de GnRH. Supresión rápida y profunda de gonadotropinas sin flare-up. En combo con estradiol/noretisterona para add-back",
  ["Miomas uterinos sintomáticos","Sangrado uterino abundante por miomas","Cáncer de próstata avanzado (Orgovyx)"],["oral"],
  {"adulto":"Miomas (Myfembree): relugolix 40 mg + estradiol 1 mg + noretisterona 0.5 mg/día. Próstata: 120 mg/día tras carga 360 mg día 1"},
  ["Comp 40 mg combo (Myfembree)","Comp 120 mg (Orgovyx)"],"Contraindicado","u07","c07_09",
  familia="Antagonistas orales de GnRH",
  ci=["Embarazo","Osteoporosis","TEV activo (formulación combo)","Cáncer de mama (combo)","Hepatopatía activa (combo)"],
  ea=["Sofocos","Cefalea","Sangrado vaginal","Alopecia","Disminución de libido","Artralgias","Inestabilidad vasomotora"],
  ix=["Inhibidores P-gp (ciclosporina): aumentan niveles","Inductores P-gp: reducen niveles","IBP: pueden reducir absorción"],
  ce=["Formulación combo incluye add-back (estrógeno + progestágeno) para proteger hueso","Sin flare-up (ventaja sobre agonistas GnRH)","Anticoncepción NO hormonal obligatoria","Tomar con o sin alimentos, misma hora cada día","Evaluar DMO si uso prolongado","Máx 24 meses de tratamiento"],
  emb="X"),

M("","acetato_ulipristal_miomas","Ulipristal (miomas)","Ulipristal acetato",["Esmya"],
  "Modulador selectivo del receptor de progesterona para miomas",
  "Modulador selectivo del receptor de progesterona (SPRM) que reduce proliferación celular en miomas, induce apoptosis e inhibe ovulación sin hipoestronismo",
  ["Miomas uterinos sintomáticos (pretratamiento quirúrgico)","Sangrado uterino abundante por miomas"],["oral"],
  {"adulto":"5 mg/día x 3 meses por curso. Máx 4 cursos intermitentes. Iniciar en primera semana del ciclo"},
  ["Comp 5 mg"],"Contraindicado","u07","c07_09",
  familia="Moduladores del receptor de progesterona",
  ci=["Embarazo","Sangrado genital no por miomas","Cáncer uterino, cervical, ovárico o mamario","Insuficiencia hepática","Edad <18 años"],
  ea=["Amenorrea (efecto deseado)","Cefalea","Sofocos","Mastalgia","Engrosamiento endometrial (PAEC, cambios reversibles)","Quistes ováricos funcionales","Hepatotoxicidad (rara pero grave)"],
  ix=["Inductores CYP3A4: reducen eficacia","Anticonceptivos hormonales: reducir eficacia mutua","Ketoconazol: aumenta niveles"],
  ce=["Función hepática OBLIGATORIA antes, durante y después de cada curso","Suspender inmediatamente si ALT/AST >2x LSN","Máx 4 cursos de 3 meses (con descanso entre cursos)","Cambios endometriales (PAEC) son reversibles y benignos","Usar método anticonceptivo de barrera durante tratamiento","EMA restricción por hepatotoxicidad: solo pre-quirúrgico o si cirugía no es opción"],
  emb="X"),

M("","goserelina_endometriosis","Goserelina (endometriosis)","Goserelina",["Zoladex"],
  "Agonista GnRH implante SC para endometriosis",
  "Agonista de GnRH en implante subcutáneo de liberación prolongada. Tras flare-up inicial, suprime eje gonadal creando pseudomenopausia médica reversible",
  ["Endometriosis","Reducción preoperatoria de miomas","Adelgazamiento endometrial pre-ablación","Cáncer de mama premenopáusico"],["SC"],
  {"adulto":"Implante SC 3.6 mg mensual o 10.8 mg trimestral en pared abdominal anterior"},
  ["Implante SC 3.6 mg (mensual)","Implante SC 10.8 mg (trimestral)"],"Contraindicado","u07","c07_09",
  familia="Agonistas de GnRH",
  ci=["Embarazo","Sangrado vaginal no diagnosticado","Hipersensibilidad","Osteoporosis severa"],
  ea=["Sofocos","Sudoración","Sequedad vaginal","Cefalea","Pérdida ósea","Cambios humor","Depresión","Disminución libido","Reacción en sitio implante"],
  ix=["Add-back therapy: reduce EA óseos y vasomotores","Suplementar calcio/vitamina D siempre"],
  ce=["Implante SC en pared abdominal anterior (técnica específica)","Aspirar antes de inyectar para evitar inyección IV","Máx 6 meses sin add-back therapy","Flare-up primeras 2 semanas: avisar empeoramiento transitorio","DMO basal y de seguimiento","Implante puede palparse bajo la piel (normal)"],
  emb="X"),

M("","nafarelina_endo","Nafarelina (endometriosis)","Nafarelina",["Synarel"],
  "Agonista GnRH intranasal para endometriosis",
  "Agonista de GnRH administrado por vía nasal. Tras desensibilización hipofisaria, suprime estrógenos a niveles posmenopáusicos. Única vía nasal disponible en agonistas GnRH",
  ["Endometriosis","Pubertad precoz central"],["intranasal"],
  {"adulto":"200 mcg (1 spray) en una fosa nasal por la mañana + 200 mcg en otra fosa por la noche. Total 400 mcg/día. Si amenorrea no se logra: 800 mcg/día"},
  ["Spray nasal 200 mcg/dosis (frasco 60 dosis)"],"Contraindicado","u07","c07_09",
  familia="Agonistas de GnRH (nasal)",
  ci=["Embarazo","Sangrado vaginal no diagnosticado","Hipersensibilidad a GnRH","Osteoporosis severa"],
  ea=["Sofocos","Sequedad vaginal","Rinitis/irritación nasal","Cefalea","Cambios emocionales","Pérdida ósea","Acné","Mialgias"],
  ix=["Descongestivos nasales: pueden reducir absorción (separar administración)","Add-back therapy: reduce EA","Calcio/vitamina D: suplementar"],
  ce=["Vía nasal: alternativa no invasiva a inyecciones depot","Alternar fosas nasales mañana/noche","No usar descongestionantes nasales 30 min antes/después","Máx 6 meses sin add-back","Si rinitis severa: absorción puede ser errática","Sonarse la nariz antes de administrar"],
  emb="X"),

# ── c07_06 Antirresortivos y Formadores Óseos (+5) ──
M("","romosozumab_oseo","Romosozumab","Romosozumab",["Evenity"],
  "Anticuerpo anti-esclerostina (formador óseo y antirresortivo)",
  "Anticuerpo monoclonal humanizado que inhibe esclerostina, proteína que inhibe la formación ósea. Efecto dual: aumenta formación ósea y reduce resorción simultáneamente",
  ["Osteoporosis severa posmenopáusica con alto riesgo de fractura","Osteoporosis con fractura previa"],["SC"],
  {"adulto":"210 mg SC mensual x 12 meses (2 inyecciones de 105 mg). Seguir con antirresortivo después"},
  ["Jeringa prellenada 105 mg/1.17 mL (se usan 2 por dosis)"],"Contraindicado","u07","c07_06",
  familia="Anticuerpos anti-esclerostina",
  ci=["Hipocalcemia","IAM o ACV reciente (<1 año)","Alto riesgo cardiovascular","Hipersensibilidad"],
  ea=["Artralgias","Cefalea","Reacción en sitio de inyección","Hipocalcemia","Osteonecrosis mandibular (raro)","Fracturas atípicas de fémur (raro)","Eventos cardiovasculares (precaución)"],
  ix=["Calcio/vitamina D: suplementar siempre (obligatorio)","Sin interacciones farmacológicas significativas"],
  ce=["Administrar 2 inyecciones SC (de 105 mg cada una) en sitios diferentes","Máximo 12 meses de tratamiento (luego continuar con antirresortivo)","Corregir hipocalcemia ANTES de iniciar","Suplementar calcio 1000 mg + vit D 400-800 UI/día","Precaución cardiovascular: evaluar riesgo CV previo","Evaluación dental antes de iniciar"],
  emb="X"),

M("","abaloparatida_oseo","Abaloparatida","Abaloparatida",["Tymlos"],
  "Análogo de PTHrP (formador óseo)",
  "Análogo sintético del péptido relacionado con PTH (PTHrP) que activa receptor PTH1R. Estimula formación ósea con menor efecto sobre resorción que teriparatida",
  ["Osteoporosis posmenopáusica con alto riesgo de fractura"],["SC"],
  {"adulto":"80 mcg SC/día en abdomen. Máximo 18-24 meses"},
  ["Pluma prellenada 80 mcg/dosis (30 dosis)"],"Contraindicado","u07","c07_06",
  familia="Análogos de PTHrP",
  ci=["Hipercalcemia preexistente","Enfermedad de Paget","Elevación inexplicada de fosfatasa alcalina","Radioterapia ósea previa","Metástasis óseas","Hiperparatiroidismo"],
  ea=["Hipercalcemia","Mareo","Náuseas","Cefalea","Palpitaciones","Fatiga","Dolor abdominal","Reacción en sitio de inyección"],
  ix=["Digoxina: hipercalcemia aumenta toxicidad","Calcio/vitamina D: suplementar pero vigilar calcemia"],
  ce=["Máximo 18-24 meses (luego continuar con antirresortivo)","Inyectar SC en región periumbilical","Primera dosis supervisada (riesgo hipotensión ortostática)","Conservar refrigerado (2-8°C)","Calcio sérico a las 4 semanas de inicio","Rotar sitios de inyección en abdomen"],
  emb="X"),

M("","acido_zoledronico_anual","Ácido Zoledrónico anual","Ácido zoledrónico",["Aclasta","Reclast"],
  "Bisfosfonato IV de administración anual",
  "Bisfosfonato nitrogenado de alta potencia que inhibe farnesil difosfato sintasa en osteoclastos. Una infusión anual reduce riesgo de fractura vertebral, cadera y no vertebral",
  ["Osteoporosis posmenopáusica","Osteoporosis masculina","Prevención de fracturas post fractura de cadera","Enfermedad de Paget"],["IV"],
  {"adulto":"Osteoporosis: 5 mg IV en 15 min 1x/año. Paget: 5 mg IV dosis única"},
  ["Vial 5 mg/100 mL solución para infusión"],"Evitar en lactancia","u07","c07_06",
  familia="Bisfosfonatos (IV)",
  ci=["Hipocalcemia","Insuficiencia renal (ClCr <35 mL/min)","Embarazo","Hipersensibilidad a bisfosfonatos"],
  ea=["Síndrome pseudogripal post-infusión (30% primera dosis: fiebre, mialgias, artralgias x 1-3 días)","Hipocalcemia","Osteonecrosis mandibular (raro)","Fractura atípica de fémur (raro)","Uveítis (raro)","Fibrilación auricular (raro)"],
  ix=["Aminoglucósidos: hipocalcemia aditiva","AINEs: mayor nefrotoxicidad","Suplementar calcio/vit D obligatorio"],
  ce=["Hidratación adecuada ANTES de infusión (500 mL SF previo)","Paracetamol puede prevenir síndrome pseudogripal","Verificar ClCr y calcio ANTES de cada infusión","Corrección de hipocalcemia y déficit de vit D previo","Evaluación dental previa (riesgo ONM)","Infundir en mínimo 15 min (no bolo)"],
  emb="X",
  pp={"dilucion":"Solución lista 5 mg/100 mL. No requiere dilución adicional","velocidadAdministracion":"Infusión IV en mínimo 15 minutos. NO administrar en bolo","estabilidad":"24h a TA tras apertura. No refrigerar"}),

M("","estroncio_ranelato","Ranelato de Estroncio","Ranelato de estroncio",["Protelos","Osseor"],
  "Agente óseo de doble acción",
  "Catión divalente que estimula formación ósea (estimula osteoblastos) y reduce resorción (inhibe osteoclastos). Mecanismo dual único entre fármacos antiosteoporóticos",
  ["Osteoporosis severa posmenopáusica (última línea)","Osteoporosis masculina severa (última línea)"],["oral"],
  {"adulto":"2 g/día en granulado disuelto en agua, al acostarse (2h después de cena)"},
  ["Sobres 2 g granulado"],"Contraindicado","u07","c07_06",
  familia="Agentes óseos de acción dual",
  ci=["TEV activo o antecedente","Cardiopatía isquémica","Enfermedad arterial periférica","ACV","HTA no controlada","Inmovilización temporal o permanente"],
  ea=["Náuseas","Diarrea","Cefalea","TEV (riesgo aumentado)","Eventos cardiovasculares","Reacciones cutáneas graves (DRESS, SJS - muy raro)","Dermatitis"],
  ix=["Calcio: reduce absorción (separar 2h)","Tetraciclinas/quinolonas: quelación mutua (separar 2h)","Antiácidos con aluminio/magnesio: separar 2h"],
  ce=["ÚLTIMA línea: solo si otros tratamientos contraindicados","Restricciones EMA por riesgo CV (solo osteoporosis severa sin riesgo CV)","Tomar al acostarse 2h después de cena (absorción)","Disolver en vaso de agua (no leche ni alimentos)","ECG y evaluación CV basal obligatoria","Suspender si aparece evento CV o cutáneo"],
  emb="X"),

M("","lasofoxifeno","Lasofoxifeno","Lasofoxifeno",["Fablyn"],
  "SERM de tercera generación",
  "Modulador selectivo del receptor de estrógenos de 3ª generación con actividad agonista en hueso y metabolismo lipídico y antagonista en mama y útero. Mayor potencia que raloxifeno",
  ["Osteoporosis posmenopáusica","Prevención de fracturas vertebrales y no vertebrales","Cáncer de mama ER+ (en investigación)"],["oral"],
  {"adulto":"0.5 mg/día"},
  ["Comp 0.5 mg"],"Contraindicado","u07","c07_06",
  familia="SERM (moduladores selectivos del receptor de estrógenos)",
  ci=["TEV activo o antecedente","Embarazo","Sangrado uterino no diagnosticado","Hipersensibilidad"],
  ea=["Sofocos","Calambres en piernas","Artralgias","TEV (menor incidencia que raloxifeno en algunos estudios)","Flujo vaginal"],
  ix=["Colestiramina: reduce absorción","Warfarina: monitorizar INR","Sin interacciones CYP significativas"],
  ce=["SERM de 3ª gen: puede tener mejor perfil que raloxifeno","Suplementar calcio y vitamina D","Vigilar signos de TEV","No aprobado en todos los países (verificar disponibilidad)","DMO basal y de seguimiento","Evaluación mamaria periódica"],
  emb="X"),
]

NEW_CHAPTERS = {
    "c07_07": {"id": "c07_07", "nombre": "Fertilidad y Reproducción Asistida", "drugIds": [
        "gonadotropina_corionica", "folitropina_alfa", "folitropina_beta", "menotropina",
        "lutropina_alfa", "corifolitropina_alfa", "progesterona_micronizada",
        "cetrorrelixida", "acetato_ganirelixida", "triptorelina_fiv"]},
    "c07_08": {"id": "c07_08", "nombre": "Menopausia y Terapia Hormonal", "drugIds": [
        "estradiol_parche", "estradiol_gel", "estriol_vaginal", "prasterona",
        "conjugados_equinos", "estradiol_drospirenona", "estradiol_noretisterona",
        "isoflavonas_soja", "fitoestrogenoa_cimicifuga", "veraliprida"]},
    "c07_09": {"id": "c07_09", "nombre": "Fármacos para Endometriosis y Miomas", "drugIds": [
        "dienogest_endometriosis", "leuprolida_endometriosis", "elagolix",
        "relugolix", "acetato_ulipristal_miomas", "goserelina_endometriosis",
        "nafarelina_endo"]},
}

if __name__ == "__main__":
    print("=== U07: Sistema Reproductor y Óseo ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        add_chapter(cats, "u07", ch)
    # Add drugs to existing chapters
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
