#!/usr/bin/env python3
"""Generate new drugs for u03 - Antiinfecciosos (28→68)."""
import sys, os; sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import *

NEW_DRUGS = [
  {
    "id": "cefazolina",
    "nombre": "Cefazolina",
    "nombreGenerico": "Cefazolina sódica",
    "nombresComerciales": ["Cefazolina Northia", "Cefazolina Richmond"],
    "familia": "Cefalosporinas",
    "clasificacion": "Cefalosporina de 1ra generación",
    "mecanismoAccion": "Inhibe la síntesis de pared celular bacteriana uniéndose a proteínas fijadoras de penicilina (PBP). Acción bactericida. Espectro: cocos Gram+, E. coli, Klebsiella.",
    "indicaciones": ["Profilaxis quirúrgica (primera elección)", "Infecciones de piel y tejidos blandos", "Infecciones urinarias no complicadas", "Endocarditis por S. aureus meticilino sensible"],
    "contraindicaciones": ["Alergia a cefalosporinas", "Anafilaxia previa a penicilinas"],
    "efectosAdversos": ["Flebitis en sitio de inyección", "Diarrea", "Náuseas", "Erupción cutánea", "Nefrotoxicidad (rara)"],
    "interacciones": ["Aminoglucósidos: nefrotoxicidad aditiva", "Probenecid: aumenta niveles", "Anticoagulantes: monitorizar INR"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "Profilaxis quirúrgica: 2 g IV 30-60 min pre-incisión. Terapéutica: 1-2 g cada 8h IV/IM",
      "pediatrico": "25-50 mg/kg/día dividido cada 8h",
      "ajusteRenal": "CrCl 10-30: cada 12h. CrCl <10: cada 24h"
    },
    "presentaciones": ["Frasco ampolla 1 g"],
    "embarazo": "B",
    "lactancia": "Compatible. Excreción mínima en leche.",
    "cuidadosEnfermeria": ["Administrar IV en 30 min mínimo", "En profilaxis: redosificar si cirugía >4h o sangrado >1500 mL", "Vigilar signos de flebitis en sitio IV", "Verificar alergia a betalactámicos", "Reconstituir con SF o AD"],
    "farmacocinetica": {"absorcion": "IM: buena", "distribucion": "Unión proteica 80%", "metabolismo": "No se metaboliza", "excrecion": "Renal 80-100%", "vidaMedia": "1.8 horas", "inicioAccion": "IV inmediato, IM 30 min", "picoAccion": "IV fin de infusión, IM 1-2h", "duracionAccion": "8 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "ceftazidima",
    "nombre": "Ceftazidima",
    "nombreGenerico": "Ceftazidima",
    "nombresComerciales": ["Fortaz", "Ceftazidima Northia"],
    "familia": "Cefalosporinas",
    "clasificacion": "Cefalosporina de 3ra generación antipseudomónica",
    "mecanismoAccion": "Inhibe síntesis de pared celular bacteriana. Espectro ampliado a Gram- incluyendo Pseudomonas aeruginosa. Estable frente a muchas betalactamasas.",
    "indicaciones": ["Infecciones por Pseudomonas aeruginosa", "Neumonía nosocomial", "Neutropenia febril (empírico)", "Meningitis por Gram negativos", "Infecciones urinarias complicadas"],
    "contraindicaciones": ["Alergia a cefalosporinas"],
    "efectosAdversos": ["Diarrea", "Náuseas", "Erupción cutánea", "Colitis pseudomembranosa", "Eosinofilia", "Trombocitosis"],
    "interacciones": ["Aminoglucósidos: sinergismo (no mezclar en misma vía)", "Cloranfenicol: antagonismo"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "1-2 g cada 8h IV. Pseudomonas severa: 2 g cada 8h",
      "pediatrico": "100-150 mg/kg/día dividido cada 8h",
      "ajusteRenal": "CrCl 16-30: 1g/12h. CrCl 6-15: 1g/24h. CrCl <5: 1g/48h"
    },
    "presentaciones": ["Frasco ampolla 1 g, 2 g"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Infusión IV en 15-30 min", "No mezclar con aminoglucósidos en misma vía", "Monitorizar función renal si uso prolongado", "Vigilar signos de sobreinfección por Candida", "Solución puede tornarse amarilla sin pérdida de potencia"],
    "farmacocinetica": {"absorcion": "IV/IM", "distribucion": "Penetra LCR. Unión proteica 10%", "metabolismo": "No se metaboliza", "excrecion": "Renal 80-90%", "vidaMedia": "1.6-2 horas", "inicioAccion": "IV inmediato", "picoAccion": "IM: 1h", "duracionAccion": "8 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "cefepime",
    "nombre": "Cefepime",
    "nombreGenerico": "Cefepime diclorhidrato",
    "nombresComerciales": ["Maxipime", "Cefepime Northia"],
    "familia": "Cefalosporinas",
    "clasificacion": "Cefalosporina de 4ta generación",
    "mecanismoAccion": "Cefalosporina de espectro extendido. Penetra porinas de Gram- más eficientemente. Activa contra Pseudomonas, Enterobacterias productoras de AmpC y Gram+. Resistente a muchas betalactamasas.",
    "indicaciones": ["Neutropenia febril (empírico)", "Neumonía nosocomial", "Infecciones urinarias complicadas", "Meningitis bacteriana", "Infecciones intraabdominales (con metronidazol)"],
    "contraindicaciones": ["Alergia a cefalosporinas"],
    "efectosAdversos": ["Erupción cutánea", "Diarrea", "Flebitis", "Neurotoxicidad en IR (confusión, mioclonías)", "Colitis por C. difficile"],
    "interacciones": ["Aminoglucósidos: sinergismo", "Nefrotóxicos: precaución", "Furosemida: puede aumentar nefrotoxicidad"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "1-2 g cada 8-12h IV. Neutropenia febril: 2 g cada 8h",
      "pediatrico": "50 mg/kg/dosis cada 8-12h (máx 2 g/dosis)",
      "ajusteRenal": "CrCl 30-60: dosis normal cada 12h. CrCl 11-29: mitad de dosis cada 12h"
    },
    "presentaciones": ["Frasco ampolla 1 g, 2 g"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Infusión IV en 30 min", "Vigilar neurotoxicidad en insuficiencia renal (confusión, mioclonías)", "Ajustar dosis estricto según clearance", "Monitorizar función renal", "Cultivos antes de iniciar"],
    "farmacocinetica": {"absorcion": "IM buena", "distribucion": "Penetra LCR. Unión proteica 20%", "metabolismo": "Mínimo", "excrecion": "Renal 85%", "vidaMedia": "2 horas", "inicioAccion": "IV inmediato", "picoAccion": "IM 1-2h", "duracionAccion": "8-12 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "imipenem_cilastatina",
    "nombre": "Imipenem/Cilastatina",
    "nombreGenerico": "Imipenem + cilastatina sódica",
    "nombresComerciales": ["Tienam", "Imipenem Northia"],
    "familia": "Carbapenémicos",
    "clasificacion": "Antibiótico carbapenémico",
    "mecanismoAccion": "Imipenem inhibe la síntesis de pared celular con espectro ultralmplio (Gram+, Gram-, anaerobios). Cilastatina inhibe la dehidropeptidasa renal I que degrada al imipenem, manteniendo niveles urinarios terapéuticos.",
    "indicaciones": ["Infecciones severas polimicrobianas", "Neumonía nosocomial", "Infecciones intraabdominales complicadas", "Sepsis", "Infecciones por gérmenes multiresistentes"],
    "contraindicaciones": ["Alergia a carbapenémicos", "Meningitis (usar meropenem)", "Alergia severa a penicilinas (precaución)"],
    "efectosAdversos": ["Náuseas y vómitos (más que meropenem)", "Diarrea", "Convulsiones (especialmente en IR)", "Erupción cutánea", "Flebitis", "Colitis por C. difficile"],
    "interacciones": ["Ganciclovir: riesgo de convulsiones", "Ácido valproico: reduce niveles de valproico 60-100% (EVITAR)", "Probenecid: aumenta niveles"],
    "viaAdministracion": ["IV"],
    "dosis": {
      "adulto": "500 mg cada 6h o 1 g cada 8h IV. Máx: 4 g/día (50 mg/kg/día)",
      "pediatrico": ">3 meses: 15-25 mg/kg cada 6h",
      "ajusteRenal": "CrCl 41-70: 500mg/8h. CrCl 21-40: 500mg/12h. CrCl 6-20: 250mg/12h"
    },
    "presentaciones": ["Frasco ampolla 500 mg/500 mg"],
    "embarazo": "C",
    "lactancia": "Compatible con precaución.",
    "cuidadosEnfermeria": ["Infusión IV lenta en 40-60 min (reduce náuseas y convulsiones)", "NO usar en meningitis (umbral convulsivo)", "EVITAR con ácido valproico (reduce niveles críticamente)", "Vigilar convulsiones en IR o patología SNC", "Cultivos antes de iniciar", "Reservar para infecciones severas (stewardship)"],
    "farmacocinetica": {"absorcion": "IV", "distribucion": "Amplia. Penetra LCR pobremente. Unión proteica 20%", "metabolismo": "Renal (cilastatina protege)", "excrecion": "Renal 70%", "vidaMedia": "1 hora", "inicioAccion": "IV inmediato", "picoAccion": "Fin de infusión", "duracionAccion": "6 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 4h TA, 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_03"
  },
  {
    "id": "ertapenem",
    "nombre": "Ertapenem",
    "nombreGenerico": "Ertapenem sódico",
    "nombresComerciales": ["Invanz"],
    "familia": "Carbapenémicos",
    "clasificacion": "Antibiótico carbapenémico (sin cobertura Pseudomonas)",
    "mecanismoAccion": "Carbapenémico de espectro amplio pero SIN actividad contra Pseudomonas ni Acinetobacter. Excelente contra Enterobacterias, anaerobios y Gram+. Ventaja: una dosis diaria.",
    "indicaciones": ["Infecciones intraabdominales complicadas", "Neumonía adquirida en comunidad", "Infecciones de piel complicadas", "Infecciones urinarias complicadas", "Pie diabético"],
    "contraindicaciones": ["Alergia a carbapenémicos", "Alergia severa a betalactámicos"],
    "efectosAdversos": ["Diarrea", "Náuseas", "Cefalea", "Flebitis", "Elevación de transaminasas", "Convulsiones (raro)"],
    "interacciones": ["Ácido valproico: reduce niveles (EVITAR)", "Probenecid: aumenta niveles"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "1 g/día IV/IM",
      "pediatrico": ">3 meses: 15 mg/kg/12h (máx 1 g/día)",
      "ajusteRenal": "CrCl <30 y hemodiálisis: 500 mg/día"
    },
    "presentaciones": ["Frasco ampolla 1 g"],
    "embarazo": "B",
    "lactancia": "Se excreta en leche. Precaución.",
    "cuidadosEnfermeria": ["Infusión IV en 30 min", "IM: reconstituir con lidocaína 1% (dolor)", "Dosis ÚNICA diaria (conveniencia)", "NO cubre Pseudomonas ni Acinetobacter", "Evitar con ácido valproico"],
    "farmacocinetica": {"absorcion": "IM: biodisponibilidad 92%", "distribucion": "Unión proteica 85-95%", "metabolismo": "Hidrólisis del anillo betalactámico", "excrecion": "Renal 80%", "vidaMedia": "4 horas", "inicioAccion": "IV inmediato. IM: 2h", "picoAccion": "IM: 2.3h", "duracionAccion": "24 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 6h TA, 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_03"
  },
  {
    "id": "claritromicina",
    "nombre": "Claritromicina",
    "nombreGenerico": "Claritromicina",
    "nombresComerciales": ["Klaricid", "Klacid", "Claritromicina Gador"],
    "familia": "Macrólidos",
    "clasificacion": "Antibiótico macrólido",
    "mecanismoAccion": "Inhibe la síntesis proteica uniéndose a la subunidad 50S ribosomal bacteriana. Bacteriostático (bactericida a altas concentraciones). Espectro: Gram+, atípicos (Mycoplasma, Chlamydia), H. pylori, MAC.",
    "indicaciones": ["Infecciones respiratorias superiores e inferiores", "Erradicación de H. pylori (triple terapia)", "Infección por MAC en VIH", "Sinusitis", "Otitis media"],
    "contraindicaciones": ["Hipersensibilidad a macrólidos", "Uso con ergotamínicos", "Insuficiencia hepática severa con IR", "QT prolongado"],
    "efectosAdversos": ["Disgeusia (sabor metálico)", "Diarrea", "Náuseas", "Dolor abdominal", "Prolongación QT", "Hepatotoxicidad (rara)"],
    "interacciones": ["Inhibidor potente CYP3A4: múltiples interacciones", "Estatinas: rabdomiolisis (evitar simvastatina)", "Colchicina: toxicidad severa", "Carbamazepina: toxicidad", "Warfarina: aumenta INR", "Digoxina: toxicidad"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "250-500 mg cada 12h x 7-14 días. H. pylori: 500 mg/12h x 14 días (triple terapia)",
      "pediatrico": "7.5 mg/kg/12h (máx 500 mg/dosis)",
      "ajusteRenal": "CrCl <30: reducir dosis 50% o dar cada 24h"
    },
    "presentaciones": ["Comprimidos 250, 500 mg", "Suspensión 250 mg/5 mL", "Frasco ampolla 500 mg"],
    "embarazo": "C",
    "lactancia": "Compatible con precaución.",
    "cuidadosEnfermeria": ["Puede tomarse con o sin alimentos", "Múltiples interacciones: revisar medicación concomitante", "No usar con simvastatina", "Controlar ECG si riesgo de QT largo", "Para H. pylori: asegurar adherencia a triple terapia completa"],
    "farmacocinetica": {"absorcion": "Oral buena, biodisponibilidad 50%", "distribucion": "Amplia, concentración tisular > plasmática. Unión proteica 70%", "metabolismo": "Hepático CYP3A4 a 14-OH-claritromicina (activo)", "excrecion": "Renal 20-40%, fecal", "vidaMedia": "5-7 horas", "inicioAccion": "2-4 horas", "picoAccion": "2-3 horas", "duracionAccion": "12 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_02"
  },
  {
    "id": "eritromicina",
    "nombre": "Eritromicina",
    "nombreGenerico": "Eritromicina",
    "nombresComerciales": ["Pantomicina", "Eritromicina Northia", "E-Mycin"],
    "familia": "Macrólidos",
    "clasificacion": "Antibiótico macrólido",
    "mecanismoAccion": "Primer macrólido. Inhibe síntesis proteica bacteriana uniéndose a subunidad 50S ribosomal. Efecto procinético gástrico adicional (agonista de receptores de motilina).",
    "indicaciones": ["Infecciones respiratorias en alergia a penicilina", "Tosferina (Bordetella pertussis)", "Conjuntivitis neonatal por Chlamydia", "Acné inflamatorio", "Gastroparesia (procinético, off-label)"],
    "contraindicaciones": ["Hipersensibilidad a macrólidos", "Uso con terfenadina, cisaprida, pimozida", "Hepatopatía severa"],
    "efectosAdversos": ["Náuseas y vómitos (frecuente)", "Dolor abdominal", "Diarrea", "Hepatotoxicidad (estolato)", "Prolongación QT", "Flebitis (IV)"],
    "interacciones": ["Inhibidor CYP3A4", "Warfarina: aumenta INR", "Teofilina: toxicidad", "Carbamazepina: toxicidad", "Digoxina: aumenta niveles"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "250-500 mg cada 6h o 500 mg cada 12h. Gastroparesia: 250 mg/8h oral antes de comidas",
      "pediatrico": "30-50 mg/kg/día dividido cada 6-8h"
    },
    "presentaciones": ["Comprimidos 500 mg", "Suspensión 200, 400 mg/5 mL", "Frasco ampolla 1 g"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Administrar en ayunas (estearato) o con alimentos (etilsuccinato)", "IV: diluir en ≥250 mL y pasar en ≥60 min (flebitis)", "Vigilar hepatograma en tratamiento prolongado", "Interacciones múltiples: revisar medicación", "Profilaxis de tosferina en contactos"],
    "farmacocinetica": {"absorcion": "Oral variable según sal", "distribucion": "Amplia, no penetra LCR. Unión proteica 73-81%", "metabolismo": "Hepático CYP3A4", "excrecion": "Biliar (principal), renal 2-5%", "vidaMedia": "1.5-2 horas", "inicioAccion": "1-4 horas oral", "picoAccion": "1-4 horas", "duracionAccion": "6-8 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_02"
  },
  {
    "id": "moxifloxacino",
    "nombre": "Moxifloxacino",
    "nombreGenerico": "Clorhidrato de moxifloxacino",
    "nombresComerciales": ["Avelox", "Moxifloxacino Northia"],
    "familia": "Quinolonas",
    "clasificacion": "Fluoroquinolona respiratoria (4ta generación)",
    "mecanismoAccion": "Inhibe ADN girasa y topoisomerasa IV bacteriana. Espectro ampliado a Gram+, atípicos y anaerobios vs ciprofloxacino. Llamada quinolona respiratoria por excelente actividad contra S. pneumoniae.",
    "indicaciones": ["Neumonía adquirida en comunidad", "Sinusitis aguda bacteriana", "Exacerbación aguda de bronquitis crónica", "Infecciones de piel complicadas", "Infecciones intraabdominales complicadas"],
    "contraindicaciones": ["Hipersensibilidad a quinolonas", "QT prolongado", "Miastenia gravis", "Menores de 18 años", "Uso con antiarrítmicos clase IA/III"],
    "efectosAdversos": ["Náuseas", "Diarrea", "Mareo", "Prolongación QT", "Tendinopatía/ruptura tendinosa", "Neuropatía periférica", "Disección aórtica (raro)"],
    "interacciones": ["Antiarrítmicos clase IA/III: prolongación QT aditiva", "Antiácidos, hierro, calcio: reducen absorción (separar 4h)", "Warfarina: aumenta INR", "Corticoides: mayor riesgo de tendinopatía"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "400 mg/día oral o IV x 5-14 días"
    },
    "presentaciones": ["Comprimidos 400 mg", "Solución IV 400 mg/250 mL"],
    "embarazo": "C",
    "lactancia": "No recomendado.",
    "cuidadosEnfermeria": ["Dosis única diaria (conveniencia)", "NO en menores de 18 años", "ECG basal si factores de riesgo de QT largo", "Separar 4h de antiácidos/hierro/calcio", "Advertir sobre dolor tendinoso (suspender si aparece)", "Hidratación adecuada"],
    "farmacocinetica": {"absorcion": "Oral: biodisponibilidad 90%", "distribucion": "Amplia. Penetración tisular excelente. Unión proteica 30-50%", "metabolismo": "Hepático (sulfatación, glucuronidación)", "excrecion": "Renal 20%, fecal 25%", "vidaMedia": "12 horas", "inicioAccion": "1-3 horas oral", "picoAccion": "1-3 horas", "duracionAccion": "24 horas"},
    "almacenamiento": "Temperatura ambiente. Proteger de la luz.",
    "unidadId": "u03", "capituloId": "c03_02"
  },
  {
    "id": "voriconazol",
    "nombre": "Voriconazol",
    "nombreGenerico": "Voriconazol",
    "nombresComerciales": ["Vfend", "Voriconazol Northia"],
    "familia": "Antifúngicos sistémicos",
    "clasificacion": "Antifúngico triazólico",
    "mecanismoAccion": "Inhibe la 14-alfa-desmetilasa fúngica (CYP51), bloqueando la síntesis de ergosterol de la membrana fúngica. Espectro amplio: Aspergillus, Candida (incluida C. krusei resistente a fluconazol), Fusarium, Scedosporium.",
    "indicaciones": ["Aspergilosis invasiva (primera línea)", "Candidemia en pacientes no neutropénicos (alternativa)", "Infecciones por Fusarium y Scedosporium", "Candidiasis esofágica refractaria"],
    "contraindicaciones": ["Uso con rifampicina, carbamazepina, barbitúricos", "Uso con sirolimus, alcaloides ergotamínicos", "Insuficiencia hepática severa", "QT prolongado"],
    "efectosAdversos": ["Alteraciones visuales (30%: fotopsia, visión borrosa)", "Hepatotoxicidad", "Erupción cutánea (fotosensibilidad)", "Alucinaciones", "Prolongación QT", "Periostitis (uso prolongado)"],
    "interacciones": ["Metabolismo CYP2C19/3A4: MÚLTIPLES interacciones", "Ciclosporina: duplicar monitoreo", "Tacrolimus: reducir dosis 2/3", "Warfarina: potencia efecto", "Omeprazol: reduce metabolismo", "Fenitoína: interacción bidireccional"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "Carga: 6 mg/kg IV cada 12h (día 1), luego 4 mg/kg IV cada 12h. Oral: 200 mg cada 12h (>40 kg)",
      "ajusteRenal": "IV: evitar si CrCl <50 (excipiente ciclodextrina se acumula). Oral: no requiere ajuste",
      "ajusteHepatico": "Child-Pugh A/B: dosis de mantenimiento 50%. C: evitar"
    },
    "presentaciones": ["Comprimidos 200 mg", "Frasco ampolla 200 mg", "Suspensión 40 mg/mL"],
    "embarazo": "D",
    "lactancia": "Contraindicado.",
    "cuidadosEnfermeria": ["Oral: en ayunas 1h antes o 2h después de comidas", "Monitorizar niveles plasmáticos (valle: 1-5.5 mg/L)", "Hepatograma semanal", "Informar sobre alteraciones visuales (transitorias, no suspender)", "Fotoprotección estricta (riesgo de carcinoma cutáneo)", "Múltiples interacciones: REVISAR toda la medicación"],
    "farmacocinetica": {"absorcion": "Oral: biodisponibilidad 96%. Alimentos reducen absorción", "distribucion": "Amplia. Penetra SNC. Unión proteica 58%", "metabolismo": "Hepático CYP2C19, CYP3A4, CYP2C9. Polimorfismo genético CYP2C19", "excrecion": "Renal <2% inalterado", "vidaMedia": "6-9 horas (dosis dependiente)", "inicioAccion": "1-2 horas oral", "picoAccion": "1-2 horas oral", "duracionAccion": "12 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "caspofungina",
    "nombre": "Caspofungina",
    "nombreGenerico": "Acetato de caspofungina",
    "nombresComerciales": ["Cancidas"],
    "familia": "Antifúngicos sistémicos",
    "clasificacion": "Equinocandina",
    "mecanismoAccion": "Inhibe la síntesis de 1,3-beta-D-glucano, componente esencial de la pared celular fúngica. Fungicida contra Candida spp., fungistático contra Aspergillus. No tiene actividad contra Cryptococcus ni Mucor.",
    "indicaciones": ["Candidemia y candidiasis invasiva (primera línea en neutropénicos)", "Aspergilosis invasiva (rescate)", "Candidiasis esofágica refractaria", "Candidemia empírica en neutropenia febril"],
    "contraindicaciones": ["Hipersensibilidad a equinocandinas"],
    "efectosAdversos": ["Fiebre", "Flebitis", "Erupción cutánea", "Elevación de transaminasas", "Hipopotasemia", "Síndrome tipo histamina (infusión rápida)"],
    "interacciones": ["Ciclosporina: aumenta AUC de caspofungina 35% (precaución)", "Rifampicina, fenitoína, dexametasona: aumentar dosis a 70 mg/día", "Tacrolimus: caspofungina reduce niveles 20%"],
    "viaAdministracion": ["IV"],
    "dosis": {
      "adulto": "Carga: 70 mg IV día 1, luego 50 mg/día IV. Si >80 kg: 70 mg/día mantenimiento",
      "pediatrico": ">3 meses: carga 70 mg/m², luego 50 mg/m²/día",
      "ajusteHepatico": "Child-Pugh B: mantenimiento 35 mg/día. C: no hay datos"
    },
    "presentaciones": ["Frasco ampolla 50, 70 mg"],
    "embarazo": "C",
    "lactancia": "No hay datos. No recomendado.",
    "cuidadosEnfermeria": ["Infusión IV lenta en ≥60 min (evitar síndrome histamínico)", "NO administrar con soluciones glucosadas (incompatible)", "Usar SOLO SF o Ringer Lactato", "Monitorizar hepatograma y potasio", "No requiere ajuste renal (ventaja)"],
    "farmacocinetica": {"absorcion": "IV", "distribucion": "Unión proteica 97%", "metabolismo": "Hidrólisis y N-acetilación (no CYP450)", "excrecion": "Renal 41%, fecal 35%", "vidaMedia": "9-11 horas", "inicioAccion": "Inmediato", "picoAccion": "Fin de infusión", "duracionAccion": "24 horas"},
    "almacenamiento": "Refrigerar 2-8°C. Reconstituido: 24h a TA.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "itraconazol",
    "nombre": "Itraconazol",
    "nombreGenerico": "Itraconazol",
    "nombresComerciales": ["Sporanox", "Itraconazol Gador", "Itrac"],
    "familia": "Antifúngicos sistémicos",
    "clasificacion": "Antifúngico triazólico",
    "mecanismoAccion": "Inhibe la 14-alfa-desmetilasa fúngica, bloqueando síntesis de ergosterol. Espectro: dermatofitos, Candida, Aspergillus, Histoplasma, Blastomyces, Sporothrix.",
    "indicaciones": ["Onicomicosis", "Histoplasmosis", "Blastomicosis", "Aspergilosis (segunda línea)", "Esporotricosis", "Dermatofitosis refractaria"],
    "contraindicaciones": ["ICC o disfunción ventricular", "Uso con cisaprida, quinidina, dofetilida", "Embarazo", "Hepatopatía severa"],
    "efectosAdversos": ["Náuseas", "Dolor abdominal", "Hepatotoxicidad", "Insuficiencia cardíaca (efecto inotrópico negativo)", "Edema", "Hipopotasemia", "Neuropatía periférica"],
    "interacciones": ["Potente inhibidor CYP3A4", "Estatinas: rabdomiolisis", "Inhibidores bomba protones: reducen absorción cápsulas", "Digoxina: toxicidad", "Ciclosporina, tacrolimus: aumenta niveles"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Onicomicosis: 200 mg/día x 3 meses o pulsos. Micosis sistémica: 200-400 mg/día",
      "ajusteHepatico": "Precaución. Monitorizar hepatograma"
    },
    "presentaciones": ["Cápsulas 100 mg", "Solución oral 10 mg/mL"],
    "embarazo": "C",
    "lactancia": "Se excreta en leche. Contraindicado.",
    "cuidadosEnfermeria": ["Cápsulas: con alimentos grasos y bebida ácida (mejor absorción)", "Solución oral: en AYUNAS (diferente de cápsulas)", "Hepatograma mensual", "Evaluar función cardíaca antes de iniciar", "Múltiples interacciones: revisar toda la medicación"],
    "farmacocinetica": {"absorcion": "Cápsulas: variable, requiere pH ácido. Solución: mejor", "distribucion": "Lipofílico. Concentración en piel y uñas muy alta. Unión proteica 99.8%", "metabolismo": "Hepático CYP3A4 a OH-itraconazol (activo)", "excrecion": "Fecal 54%, renal 35% (metabolitos)", "vidaMedia": "21 horas (estado estable)", "inicioAccion": "Días-semanas para efecto clínico", "picoAccion": "2-5 horas", "duracionAccion": "Persiste en tejidos semanas"},
    "almacenamiento": "Temperatura ambiente. Proteger de la luz.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "ganciclovir",
    "nombre": "Ganciclovir",
    "nombreGenerico": "Ganciclovir sódico",
    "nombresComerciales": ["Cymevene", "Ganciclovir Northia"],
    "familia": "Antivirales",
    "clasificacion": "Antiviral análogo nucleosídico anti-CMV",
    "mecanismoAccion": "Análogo de guanosina que se fosforila por la quinasa UL97 del CMV. El trifosfato de ganciclovir inhibe competitivamente la ADN polimerasa viral y se incorpora al ADN viral deteniendo su replicación.",
    "indicaciones": ["Retinitis por CMV en inmunocomprometidos", "Prevención de enfermedad por CMV en trasplante", "Infección congénita por CMV (sintomática)", "Esofagitis/colitis por CMV"],
    "contraindicaciones": ["Neutropenia <500/mm³", "Trombocitopenia <25000/mm³", "Hipersensibilidad", "Embarazo"],
    "efectosAdversos": ["Mielosupresión (neutropenia 40%, trombocitopenia)", "Anemia", "Fiebre", "Nefrotoxicidad", "Teratogenicidad y carcinogenicidad potencial"],
    "interacciones": ["Zidovudina: mielosupresión aditiva severa", "Imipenem: convulsiones", "Nefrotóxicos: aumenta nefrotoxicidad", "Probenecid: aumenta niveles"],
    "viaAdministracion": ["IV"],
    "dosis": {
      "adulto": "Inducción: 5 mg/kg IV cada 12h x 14-21 días. Mantenimiento: 5 mg/kg/día IV",
      "ajusteRenal": "CrCl 50-69: 2.5 mg/kg/12h. CrCl 25-49: 2.5 mg/kg/24h. CrCl 10-24: 1.25 mg/kg/24h"
    },
    "presentaciones": ["Frasco ampolla 500 mg"],
    "embarazo": "X",
    "lactancia": "Contraindicado (potencial mutagénico).",
    "cuidadosEnfermeria": ["Infusión IV en ≥60 min (irritante)", "Hemograma completo cada 48-72h durante inducción", "NO administrar IM ni SC (necrosante)", "Manipulación con guantes (citotóxico)", "Anticoncepción durante y 90 días post-tratamiento", "Mantener hidratación adecuada"],
    "farmacocinetica": {"absorcion": "IV", "distribucion": "Penetra SNC y ojo. Unión proteica 1-2%", "metabolismo": "Mínimo", "excrecion": "Renal 90% inalterado", "vidaMedia": "2.5-3.6 horas (renal normal)", "inicioAccion": "Inmediato", "picoAccion": "Fin de infusión", "duracionAccion": "12 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 12h TA (no refrigerar).",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "valganciclovir",
    "nombre": "Valganciclovir",
    "nombreGenerico": "Clorhidrato de valganciclovir",
    "nombresComerciales": ["Valcyte"],
    "familia": "Antivirales",
    "clasificacion": "Profármaco oral de ganciclovir",
    "mecanismoAccion": "Profármaco oral de ganciclovir. Se convierte rápidamente en ganciclovir por esterasas intestinales y hepáticas. Mismo mecanismo: inhibe ADN polimerasa de CMV.",
    "indicaciones": ["Retinitis por CMV en VIH (inducción y mantenimiento oral)", "Profilaxis de CMV en trasplante de órgano sólido", "CMV congénito sintomático"],
    "contraindicaciones": ["Neutropenia <500/mm³", "Trombocitopenia <25000/mm³", "Embarazo", "Hipersensibilidad"],
    "efectosAdversos": ["Neutropenia", "Anemia", "Trombocitopenia", "Diarrea", "Náuseas", "Cefalea"],
    "interacciones": ["Los mismos que ganciclovir", "Micofenolato: aumento de niveles de ambos en IR"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Inducción: 900 mg/12h x 21 días. Mantenimiento/profilaxis: 900 mg/día con alimentos",
      "pediatrico": "Dosis según superficie corporal",
      "ajusteRenal": "CrCl 40-59: inducción 450 mg/12h. CrCl 25-39: 450 mg/24h. CrCl 10-24: 450 mg/48h"
    },
    "presentaciones": ["Comprimidos 450 mg"],
    "embarazo": "X",
    "lactancia": "Contraindicado.",
    "cuidadosEnfermeria": ["Tomar CON alimentos (aumenta biodisponibilidad 30%)", "NO romper ni triturar comprimidos (citotóxico)", "Hemograma semanal durante inducción", "Anticoncepción doble durante y 30 días post", "Ajustar estrictamente según función renal"],
    "farmacocinetica": {"absorcion": "Oral: se convierte en ganciclovir. Biodisponibilidad de ganciclovir 60% (vs 6% oral directo)", "distribucion": "Como ganciclovir", "metabolismo": "Conversión a ganciclovir por esterasas", "excrecion": "Renal como ganciclovir", "vidaMedia": "4 horas (como ganciclovir)", "inicioAccion": "1-3 horas", "picoAccion": "1-3 horas", "duracionAccion": "12-24 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "pirazinamida",
    "nombre": "Pirazinamida",
    "nombreGenerico": "Pirazinamida",
    "nombresComerciales": ["Pirazinamida Denver Farma", "PZA"],
    "familia": "Antituberculosos",
    "clasificacion": "Antimicobacteriano (fase intensiva)",
    "mecanismoAccion": "Profármaco convertido en ácido pirazinoico por la pirazinamidasa de M. tuberculosis. Actúa en medio ácido (macrófagos). Efecto bactericida sobre bacilos intracelulares semidormantes que otros fármacos no alcanzan.",
    "indicaciones": ["Tuberculosis: fase intensiva (primeros 2 meses)", "Parte del esquema HRZE de primera línea"],
    "contraindicaciones": ["Hepatopatía severa", "Porfiria aguda", "Gota severa", "Hiperuricemia severa"],
    "efectosAdversos": ["Hepatotoxicidad (principal)", "Hiperuricemia/gota", "Artralgias", "Erupción cutánea", "Fotosensibilidad", "Anorexia"],
    "interacciones": ["Otros hepatotóxicos: mayor riesgo", "Alopurinol: necesidad de ajustar por hiperuricemia", "Ciclosporina: reduce niveles de ciclosporina"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "20-25 mg/kg/día (máx 2 g/día). Fase intensiva: 2 meses con HRE",
      "ajusteRenal": "CrCl <30 o hemodiálisis: 25-35 mg/kg 3 veces/semana"
    },
    "presentaciones": ["Comprimidos 500 mg"],
    "embarazo": "C",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Hepatograma basal y mensual (hepatotoxicidad)", "Controlar ácido úrico (hiperuricemia esperada)", "Administrar con los otros fármacos anti-TB (adherencia)", "Informar sobre dolor articular (efecto del ácido úrico)", "DOTS: tratamiento directamente observado", "Solo durante fase intensiva (2 meses)"],
    "farmacocinetica": {"absorcion": "Oral buena", "distribucion": "Amplia. Penetra LCR. Concentración en macrófagos", "metabolismo": "Hepático a ácido pirazinoico", "excrecion": "Renal 70%", "vidaMedia": "9-10 horas", "inicioAccion": "1-2 horas", "picoAccion": "1-2 horas", "duracionAccion": "24 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_05"
  },
  {
    "id": "etambutol",
    "nombre": "Etambutol",
    "nombreGenerico": "Clorhidrato de etambutol",
    "nombresComerciales": ["Myambutol", "Etambutol Denver Farma"],
    "familia": "Antituberculosos",
    "clasificacion": "Antimicobacteriano bacteriostático",
    "mecanismoAccion": "Inhibe la arabinosil transferasa III, enzima clave en la síntesis de arabinogalactano de la pared celular de micobacterias. Bacteriostático. Previene la emergencia de resistencia cuando se usa en combinación.",
    "indicaciones": ["Tuberculosis: esquema HRZE (fase intensiva)", "Micobacterias atípicas (MAC) en combinación"],
    "contraindicaciones": ["Neuritis óptica preexistente", "Niños que no pueden reportar cambios visuales (<6 años)", "Hipersensibilidad"],
    "efectosAdversos": ["Neuritis óptica retrobulbar (dosis-dependiente, reversible)", "Disminución de agudeza visual y discriminación de colores", "Hiperuricemia", "Neuropatía periférica", "Erupción cutánea"],
    "interacciones": ["Antiácidos con aluminio: reducen absorción", "Otros neurotóxicos: efecto aditivo"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "15-20 mg/kg/día (máx 1.6 g/día). Fase intensiva: 2 meses",
      "ajusteRenal": "CrCl <30: 15-25 mg/kg 3 veces/semana"
    },
    "presentaciones": ["Comprimidos 400 mg"],
    "embarazo": "C",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Control oftalmológico BASAL y mensual (agudeza visual, colores)", "Prueba de discriminación rojo-verde mensual", "Si alteración visual: SUSPENDER inmediatamente", "No usar en niños <6 años que no pueden informar cambios visuales", "Educar al paciente: reportar cualquier cambio visual", "Controlar ácido úrico"],
    "farmacocinetica": {"absorcion": "Oral buena, 75-80%", "distribucion": "Penetra LCR en meningitis. Concentración en eritrocitos", "metabolismo": "Hepático parcial", "excrecion": "Renal 50% inalterado, fecal 20%", "vidaMedia": "3-4 horas", "inicioAccion": "2-4 horas", "picoAccion": "2-4 horas", "duracionAccion": "24 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_05"
  },
  {
    "id": "metronidazol_antiparasitario",
    "nombre": "Metronidazol (Antiparasitario)",
    "nombreGenerico": "Metronidazol",
    "nombresComerciales": ["Flagyl", "Metronidazol Northia"],
    "familia": "Antiparasitarios",
    "clasificacion": "Nitroimidazol antiprotozoario",
    "mecanismoAccion": "En anaerobios y protozoos, el grupo nitro se reduce a intermediarios citotóxicos que dañan el ADN. Activo contra Giardia, Entamoeba, Trichomonas y bacterias anaerobias.",
    "indicaciones": ["Giardiasis", "Amebiasis intestinal y hepática", "Tricomoniasis", "Vaginosis bacteriana"],
    "contraindicaciones": ["Primer trimestre de embarazo (relativo)", "Uso con alcohol (efecto disulfiram)", "Hipersensibilidad"],
    "efectosAdversos": ["Sabor metálico", "Náuseas", "Efecto disulfiram con alcohol", "Neuropatía periférica (prolongado)", "Orina oscura", "Cefalea"],
    "interacciones": ["Alcohol: reacción tipo disulfiram", "Warfarina: potencia anticoagulación", "Litio: toxicidad", "Fenitoína: aumenta niveles"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Giardiasis: 250 mg/8h x 5-7 días. Amebiasis: 500-750 mg/8h x 7-10 días. Tricomoniasis: 2 g dosis única o 500 mg/12h x 7 días"
    },
    "presentaciones": ["Comprimidos 250, 500 mg", "Suspensión 125 mg/5 mL", "Óvulos vaginales 500 mg"],
    "embarazo": "B",
    "lactancia": "Suspender lactancia durante tratamiento y 24h después.",
    "cuidadosEnfermeria": ["NO consumir alcohol durante y 48h post-tratamiento", "Informar sobre orina oscura (normal)", "Tricomoniasis: tratar a la pareja sexual", "Giardiasis: higiene de agua y alimentos", "Control parasitológico de materia fecal post-tratamiento"],
    "farmacocinetica": {"absorcion": "Oral completa", "distribucion": "Amplia, penetra SNC y hueso", "metabolismo": "Hepático", "excrecion": "Renal 60-80%", "vidaMedia": "8 horas", "inicioAccion": "1 hora", "picoAccion": "1-2 horas", "duracionAccion": "8 horas"},
    "almacenamiento": "Temperatura ambiente. Proteger de la luz.",
    "unidadId": "u03", "capituloId": "c03_06"
  },
  {
    "id": "tinidazol",
    "nombre": "Tinidazol",
    "nombreGenerico": "Tinidazol",
    "nombresComerciales": ["Fasigyn", "Pletil"],
    "familia": "Antiparasitarios",
    "clasificacion": "Nitroimidazol antiprotozoario",
    "mecanismoAccion": "Similar a metronidazol. Vida media más larga permite dosis únicas. Activo contra Giardia, Entamoeba, Trichomonas. Mejor tolerancia que metronidazol.",
    "indicaciones": ["Giardiasis", "Amebiasis", "Tricomoniasis", "Vaginosis bacteriana"],
    "contraindicaciones": ["Primer trimestre embarazo", "Uso con alcohol", "Hipersensibilidad a nitroimidazoles"],
    "efectosAdversos": ["Sabor metálico (menos que metronidazol)", "Náuseas", "Efecto disulfiram", "Cefalea"],
    "interacciones": ["Alcohol: reacción disulfiram", "Warfarina: potencia", "Fenitoína: aumenta niveles"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Giardiasis: 2 g dosis única. Amebiasis intestinal: 2 g/día x 3 días. Tricomoniasis: 2 g dosis única",
      "pediatrico": "50 mg/kg dosis única (máx 2 g)"
    },
    "presentaciones": ["Comprimidos 500 mg, 1 g"],
    "embarazo": "C",
    "lactancia": "Suspender 72h post-dosis.",
    "cuidadosEnfermeria": ["Ventaja sobre metronidazol: dosis única en varias indicaciones", "NO alcohol durante y 72h post-tratamiento", "Tomar con alimentos", "Tratar pareja en tricomoniasis"],
    "farmacocinetica": {"absorcion": "Oral completa", "distribucion": "Amplia", "metabolismo": "Hepático CYP3A4", "excrecion": "Renal 20-25%, fecal 12%", "vidaMedia": "12-14 horas (vs 8h metronidazol)", "inicioAccion": "1-2 horas", "picoAccion": "1-2 horas", "duracionAccion": "24+ horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_06"
  },
  {
    "id": "benznidazol",
    "nombre": "Benznidazol",
    "nombreGenerico": "Benznidazol",
    "nombresComerciales": ["Abarax", "Benznidazol ELEA"],
    "familia": "Antiparasitarios",
    "clasificacion": "Nitroimidazol tripanocida",
    "mecanismoAccion": "Nitroimidazol con actividad tripanocida. Se reduce enzimáticamente en el parásito generando radicales libres y electrófilos que dañan ADN, lípidos y proteínas del Trypanosoma cruzi.",
    "indicaciones": ["Enfermedad de Chagas aguda", "Chagas crónico reciente (< 15 años desde infección)", "Chagas congénito", "Reactivación en inmunosuprimidos"],
    "contraindicaciones": ["Embarazo", "Insuficiencia hepática o renal severa", "Hipersensibilidad"],
    "efectosAdversos": ["Dermatitis alérgica (30%)", "Neuropatía periférica (dosis-dependiente)", "Leucopenia", "Anorexia", "Náuseas", "Insomnio"],
    "interacciones": ["Alcohol: efecto disulfiram", "Anticoagulantes: puede potenciar"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "5 mg/kg/día dividido en 2 tomas x 60 días",
      "pediatrico": "5-10 mg/kg/día x 60 días"
    },
    "presentaciones": ["Comprimidos 50, 100 mg"],
    "embarazo": "X",
    "lactancia": "Contraindicado.",
    "cuidadosEnfermeria": ["Tratamiento PROLONGADO (60 días): adherencia crítica", "Vigilar erupción cutánea (frecuente, suspender si severa)", "Hemograma quincenal (leucopenia)", "NO alcohol durante tratamiento", "Informar sobre parestesias (neuropatía: suspender)", "Medicamento de distribución estatal gratuita en Argentina"],
    "farmacocinetica": {"absorcion": "Oral buena", "distribucion": "Amplia", "metabolismo": "Hepático", "excrecion": "Renal", "vidaMedia": "12 horas", "inicioAccion": "Variable", "picoAccion": "3-4 horas", "duracionAccion": "12 horas"},
    "almacenamiento": "Temperatura ambiente. Proteger de la luz.",
    "unidadId": "u03", "capituloId": "c03_06"
  },
  {
    "id": "atazanavir",
    "nombre": "Atazanavir",
    "nombreGenerico": "Sulfato de atazanavir",
    "nombresComerciales": ["Reyataz", "Atazanavir Richmond"],
    "familia": "Antivirales (antirretrovirales)",
    "clasificacion": "Inhibidor de proteasa del VIH",
    "mecanismoAccion": "Inhibe la proteasa del VIH-1, impidiendo el clivaje de las poliproteínas Gag-Pol. Produce viriones inmaduros no infectantes. Se administra boosterado con ritonavir o cobicistat.",
    "indicaciones": ["Infección por VIH-1 (en combinación con otros ARV)", "TARV de primera y segunda línea"],
    "contraindicaciones": ["Uso con rifampicina", "Uso con IBP (reducen absorción críticamente)", "Hepatopatía severa (Child-Pugh C)"],
    "efectosAdversos": ["Hiperbilirrubinemia indirecta (ictericia cosmética, no hepatotóxica)", "Náuseas", "Cefalea", "Litiasis renal", "Prolongación PR", "Hiperglucemia"],
    "interacciones": ["IBP: contraindicados", "Ranitidina: separar dosis", "Tenofovir: reduce niveles de atazanavir", "Rifampicina: contraindicada", "Efavirenz: reduce niveles"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "300 mg + ritonavir 100 mg una vez al día con alimentos"
    },
    "presentaciones": ["Cápsulas 150, 200, 300 mg"],
    "embarazo": "B",
    "lactancia": "No recomendado (transmisión VIH por leche).",
    "cuidadosEnfermeria": ["Tomar CON alimentos (aumenta absorción)", "NO usar con inhibidores de bomba de protones", "Ictericia conjuntival: cosmético, no hepatotoxicidad", "Carga viral y CD4 periódicos", "Monitorizar función renal (litiasis)", "Adherencia >95% crucial para evitar resistencia"],
    "farmacocinetica": {"absorcion": "Requiere alimentos y pH ácido", "distribucion": "Unión proteica 86%", "metabolismo": "Hepático CYP3A4", "excrecion": "Fecal 79%, renal 13%", "vidaMedia": "6.5 horas (boosterado: 8.6h)", "inicioAccion": "2 horas", "picoAccion": "2.5 horas", "duracionAccion": "24 horas (boosterado)"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "tenofovir_emtricitabina",
    "nombre": "Tenofovir/Emtricitabina",
    "nombreGenerico": "Tenofovir disoproxil fumarato + emtricitabina",
    "nombresComerciales": ["Truvada", "Emtrivir Plus"],
    "familia": "Antivirales (antirretrovirales)",
    "clasificacion": "ITIAN dual (análogos nucleosídicos/nucleotídicos)",
    "mecanismoAccion": "Ambos son inhibidores de la transcriptasa inversa análogos de nucleósidos/nucleótidos (ITIAN). Se fosforilan intracelularmente e inhiben competitivamente la transcriptasa inversa del VIH, terminando la cadena de ADN viral.",
    "indicaciones": ["Infección por VIH-1 (backbone de TARV, con tercer agente)", "Profilaxis pre-exposición (PrEP) del VIH", "Hepatitis B crónica (tenofovir)"],
    "contraindicaciones": ["CrCl <30 mL/min para TDF (usar TAF)", "Hepatitis B no diagnosticada (riesgo de flare al suspender)"],
    "efectosAdversos": ["Nefrotoxicidad (tubulopatía proximal, TDF)", "Disminución de densidad ósea (TDF)", "Cefalea", "Náuseas", "Diarrea", "Hiperpigmentación palmar (emtricitabina)"],
    "interacciones": ["Nefrotóxicos: evitar combinación", "AINEs: riesgo renal aditivo", "No usar con otro ITIAN de citidina (lamivudina = similar a emtricitabina)"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "1 comprimido/día (TDF 300 mg + FTC 200 mg) con o sin alimentos",
      "ajusteRenal": "CrCl 30-49: cada 48h. CrCl <30: no recomendado (usar TAF)"
    },
    "presentaciones": ["Comprimidos TDF 300 mg + FTC 200 mg"],
    "embarazo": "B",
    "lactancia": "No recomendado (VIH).",
    "cuidadosEnfermeria": ["Descartar infección VIH antes de PrEP (test rápido)", "Función renal y fósforo sérico cada 3-6 meses", "Densitometría ósea en pacientes con riesgo", "PrEP: adherencia diaria crucial (eficacia 99% si adherente)", "NO suspender abruptamente en coinfección HBV (flare)", "Screening VIH y HBV periódico en PrEP"],
    "farmacocinetica": {"absorcion": "TDF: biodisponibilidad 25% (aumenta con alimentos grasos). FTC: biodisponibilidad 93%", "distribucion": "Intracelular (formas fosforiladas)", "metabolismo": "TDF: esterasas. FTC: mínimo", "excrecion": "Renal (ambos)", "vidaMedia": "TDF: 17h. FTC: 10h. Intracelular: 39-120h", "inicioAccion": "Horas", "picoAccion": "TDF: 1-2h. FTC: 1-2h", "duracionAccion": "24 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "efavirenz",
    "nombre": "Efavirenz",
    "nombreGenerico": "Efavirenz",
    "nombresComerciales": ["Stocrin", "Efavirenz Richmond", "Filaxis"],
    "familia": "Antivirales (antirretrovirales)",
    "clasificacion": "ITINN (inhibidor de la transcriptasa inversa no nucleosídico)",
    "mecanismoAccion": "Se une directamente a la transcriptasa inversa del VIH-1 en un sitio alostérico, causando cambio conformacional que inhibe su actividad. No requiere fosforilación intracelular.",
    "indicaciones": ["Infección por VIH-1 (combinado con 2 ITIAN)", "Esquema preferido de primera línea OMS (con TDF/FTC)"],
    "contraindicaciones": ["Embarazo primer trimestre (teratogénico en primates)", "Hepatopatía severa", "Uso con voriconazol a dosis estándar"],
    "efectosAdversos": ["Síntomas neuropsiquiátricos (sueños vívidos, mareo, depresión)", "Erupción cutánea (rash)", "Hepatotoxicidad", "Ginecomastia", "Dislipidemia (aumento LDL/triglicéridos)"],
    "interacciones": ["Inductor CYP3A4/2B6", "Rifampicina: aumentar efavirenz a 800 mg", "Metadona: reduce niveles", "Anticonceptivos orales: reduce eficacia"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "600 mg/día al acostarse (reduce síntomas neuropsiquiátricos)"
    },
    "presentaciones": ["Comprimidos 600 mg", "Comprimido combinado TDF/FTC/EFV (Atripla)"],
    "embarazo": "D",
    "lactancia": "Se excreta en leche. No recomendado.",
    "cuidadosEnfermeria": ["Tomar al acostarse con estómago vacío (reduce efectos neuropsiquiátricos)", "Advertir sobre sueños vívidos y mareo (suelen mejorar en 2-4 semanas)", "Evaluar síntomas depresivos periódicamente", "Anticoncepción eficaz obligatoria en mujeres en edad fértil", "Barrera baja a resistencia: adherencia estricta"],
    "farmacocinetica": {"absorcion": "Oral buena. Alimentos grasos aumentan absorción 50%", "distribucion": "Unión proteica 99.5-99.75%", "metabolismo": "Hepático CYP2B6, CYP3A4 (autoinducción)", "excrecion": "Fecal 16-61%, renal 14-34% (metabolitos)", "vidaMedia": "40-55 horas (estado estable)", "inicioAccion": "Variable", "picoAccion": "3-5 horas", "duracionAccion": "24+ horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_04"
  },
  {
    "id": "cloxacilina",
    "nombre": "Cloxacilina",
    "nombreGenerico": "Cloxacilina sódica",
    "nombresComerciales": ["Cloxacilina Northia", "Orbenin"],
    "familia": "Penicilinas",
    "clasificacion": "Penicilina antiestafilocócica (resistente a penicilinasas)",
    "mecanismoAccion": "Betalactámico resistente a penicilinasa estafilocócica. Inhibe la síntesis de pared celular bacteriana. Espectro estrecho: S. aureus meticilino sensible (SAMS), estreptococos.",
    "indicaciones": ["Infecciones por S. aureus meticilino sensible", "Celulitis", "Osteomielitis estafilocócica", "Endocarditis por SAMS", "Bacteriemia por SAMS"],
    "contraindicaciones": ["Alergia a penicilinas"],
    "efectosAdversos": ["Flebitis (IV)", "Nefritis intersticial", "Hepatotoxicidad", "Diarrea", "Reacciones alérgicas"],
    "interacciones": ["Metotrexato: reduce excreción", "Warfarina: puede alterar INR", "Probenecid: aumenta niveles"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "Oral: 500 mg-1 g cada 6h en ayunas. IV: 1-2 g cada 4-6h. Endocarditis: 2 g cada 4h IV",
      "pediatrico": "50-100 mg/kg/día dividido cada 6h"
    },
    "presentaciones": ["Cápsulas 500 mg", "Frasco ampolla 1 g"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Oral: administrar en AYUNAS (1h antes o 2h después de comidas)", "IV: administrar en 30-60 min", "Fármaco de elección en SAMS", "Monitorizar función hepática en tratamientos prolongados", "Vigilar flebitis en sitio IV", "Verificar antibiograma: solo SAMS"],
    "farmacocinetica": {"absorcion": "Oral: 37-60% (disminuye con alimentos)", "distribucion": "Unión proteica 94-96%", "metabolismo": "Hepático parcial", "excrecion": "Renal 30-45%, biliar", "vidaMedia": "0.5-1 hora", "inicioAccion": "30-60 min oral, inmediato IV", "picoAccion": "1 hora oral", "duracionAccion": "4-6 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "penicilina_g",
    "nombre": "Penicilina G (Bencilpenicilina)",
    "nombreGenerico": "Penicilina G sódica / potásica",
    "nombresComerciales": ["Penicilina G Northia", "Penilevel"],
    "familia": "Penicilinas",
    "clasificacion": "Penicilina natural",
    "mecanismoAccion": "Primera penicilina. Inhibe la síntesis de pared celular uniéndose a PBP. Bactericida. Espectro estrecho: estreptococos, Neisseria, Treponema, Clostridium. Inactiva frente a SAMS productor de penicilinasa.",
    "indicaciones": ["Sífilis (todas las etapas)", "Faringitis estreptocócica", "Endocarditis por estreptococos sensibles", "Meningitis por N. meningitidis", "Gangrena gaseosa", "Tétanos (coadyuvante)"],
    "contraindicaciones": ["Alergia a penicilinas"],
    "efectosAdversos": ["Reacciones alérgicas", "Anafilaxia (raro pero grave)", "Convulsiones (dosis altas IV)", "Diarrea", "Hiperpotasemia (sal potásica en altas dosis)"],
    "interacciones": ["Metotrexato: reduce excreción", "Probenecid: aumenta niveles", "Aminoglucósidos: sinergismo (no mezclar en misma vía)"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "2-4 millones UI cada 4-6h IV. Sífilis primaria: penicilina G benzatínica 2.4 millones UI IM dosis única. Neurosífilis: 18-24 millones UI/día IV x 14 días",
      "pediatrico": "50,000-400,000 UI/kg/día dividido cada 4-6h"
    },
    "presentaciones": ["Frasco ampolla 1, 5, 10 millones UI", "Penicilina G benzatínica 1.2, 2.4 millones UI (IM)"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Preguntar SIEMPRE por alergia a penicilina antes de administrar", "Benzatínica: SOLO IM profunda (nunca IV, riesgo de embolia)", "IM benzatínica: usar aguja 21G, inyectar lentamente", "IV: diluir en 50-100 mL y pasar en 15-30 min", "Vigilar reacción de Jarisch-Herxheimer en sífilis (fiebre, escalofríos)"],
    "farmacocinetica": {"absorcion": "IM: buena. Benzatínica: absorción lenta (depot)", "distribucion": "Amplia. Penetra LCR en meningitis. Unión proteica 60%", "metabolismo": "Hepático mínimo", "excrecion": "Renal 60-90%", "vidaMedia": "Sódica: 30 min. Benzatínica: 14-21 días (depot)", "inicioAccion": "IV: inmediato. IM: 15-30 min", "picoAccion": "IV: fin de infusión. Benzatínica: 12-24h", "duracionAccion": "Sódica: 4-6h. Benzatínica: 3-4 semanas"},
    "almacenamiento": "Refrigerar reconstituida. Benzatínica: temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "teicoplanina",
    "nombre": "Teicoplanina",
    "nombreGenerico": "Teicoplanina",
    "nombresComerciales": ["Targocid"],
    "familia": "Glucopéptidos",
    "clasificacion": "Antibiótico glucopéptido",
    "mecanismoAccion": "Glucopéptido similar a vancomicina. Inhibe la síntesis de pared celular bacteriana uniéndose al dipéptido D-Ala-D-Ala. Bactericida contra Gram+. Ventaja sobre vancomicina: administración IM posible y menor nefrotoxicidad.",
    "indicaciones": ["Infecciones graves por Gram+ resistentes", "SARM (alternativa a vancomicina)", "Endocarditis por enterococo", "Osteomielitis por Gram+", "Pacientes que no toleran vancomicina"],
    "contraindicaciones": ["Hipersensibilidad a glucopéptidos"],
    "efectosAdversos": ["Erupción cutánea", "Fiebre", "Ototoxicidad (menor que vancomicina)", "Trombocitopenia", "Flebitis", "Nefrotoxicidad (menor que vancomicina)"],
    "interacciones": ["Aminoglucósidos: oto/nefrotoxicidad aditiva", "Anfotericina B: nefrotoxicidad aditiva", "Ciclosporina: nefrotoxicidad"],
    "viaAdministracion": ["IV", "IM"],
    "dosis": {
      "adulto": "Carga: 6-12 mg/kg cada 12h x 3-5 dosis. Mantenimiento: 6-12 mg/kg/día IV/IM",
      "ajusteRenal": "Día 4+: CrCl 40-60: dosis cada 48h. CrCl <40: cada 72h"
    },
    "presentaciones": ["Frasco ampolla 200, 400 mg"],
    "embarazo": "C",
    "lactancia": "No recomendado.",
    "cuidadosEnfermeria": ["Puede administrarse IM (ventaja vs vancomicina)", "IV: bolo lento o infusión en 30 min", "Monitorizar niveles valle (>15 mg/L en infecciones graves)", "Función renal y audiometría periódicas", "No produce síndrome del hombre rojo (vs vancomicina)", "Hemograma semanal (trombocitopenia)"],
    "farmacocinetica": {"absorcion": "IM: biodisponibilidad 90%", "distribucion": "Unión proteica 90-95%. Pobre penetración LCR", "metabolismo": "Mínimo", "excrecion": "Renal 80%", "vidaMedia": "70-100 horas (permite dosis diaria o cada 48h)", "inicioAccion": "IV inmediato, IM 2-4h", "picoAccion": "IM: 2-4h", "duracionAccion": "24-48 horas"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_03"
  },
  {
    "id": "fosfomicina",
    "nombre": "Fosfomicina",
    "nombreGenerico": "Fosfomicina trometamol",
    "nombresComerciales": ["Monurol", "Fosfomicina Gador"],
    "familia": "Antibióticos urinarios",
    "clasificacion": "Antibiótico inhibidor de la síntesis de pared celular",
    "mecanismoAccion": "Inhibe la enzima MurA (enolpiruvato transferasa), el primer paso de la síntesis de peptidoglicano. Mecanismo único: resistencia cruzada mínima. Activa contra E. coli, Enterococcus, SARM urinario.",
    "indicaciones": ["Infección urinaria baja no complicada (cistitis)", "ITU por gérmenes multiresistentes (urinaria)", "Profilaxis pre-procedimiento urológico"],
    "contraindicaciones": ["Hipersensibilidad", "Insuficiencia renal severa (CrCl <10)"],
    "efectosAdversos": ["Diarrea", "Náuseas", "Cefalea", "Vulvovaginitis"],
    "interacciones": ["Metoclopramida: reduce niveles urinarios (aumenta tránsito)", "Alimentos: retrasan absorción (tomar en ayunas)"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Cistitis no complicada: 3 g dosis ÚNICA (1 sobre). Puede repetir una dosis a las 48-72h si persisten síntomas"
    },
    "presentaciones": ["Sobre granulado 3 g (dosis única)"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Dosis ÚNICA: alta adherencia", "Disolver sobre en agua, tomar en AYUNAS o 2-3h post-comida", "Recolectar urocultivo ANTES de administrar", "Informar que los síntomas mejoran en 24-48h", "No usar en pielonefritis (solo cistitis baja)", "Útil en ITU por BLEE"],
    "farmacocinetica": {"absorcion": "Oral: biodisponibilidad 33-53%", "distribucion": "Concentración urinaria muy alta (mantiene niveles 48-72h)", "metabolismo": "No se metaboliza", "excrecion": "Renal 95% inalterada", "vidaMedia": "5.7 horas (sérica). Urinaria: hasta 48h", "inicioAccion": "2-4 horas", "picoAccion": "2-4 horas sérica", "duracionAccion": "48-72 horas en orina (dosis única efectiva)"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_03"
  },
  {
    "id": "cefuroxima",
    "nombre": "Cefuroxima",
    "nombreGenerico": "Cefuroxima sódica / axetilo",
    "nombresComerciales": ["Zinnat", "Cefuroxima Northia", "Zinacef"],
    "familia": "Cefalosporinas",
    "clasificacion": "Cefalosporina de 2da generación",
    "mecanismoAccion": "Inhibe síntesis de pared celular. Espectro ampliado vs 1ra generación: mejor cobertura de H. influenzae, Moraxella, E. coli, Klebsiella. Mantiene actividad contra Gram+.",
    "indicaciones": ["Otitis media aguda", "Sinusitis aguda", "Infecciones urinarias", "Infecciones respiratorias bajas", "Enfermedad de Lyme precoz"],
    "contraindicaciones": ["Alergia a cefalosporinas"],
    "efectosAdversos": ["Diarrea", "Náuseas", "Erupción cutánea", "Colitis por C. difficile", "Dolor en sitio IM"],
    "interacciones": ["Probenecid: aumenta niveles", "Aminoglucósidos: nefrotoxicidad aditiva", "Antiácidos/ranitidina: reducen absorción oral"],
    "viaAdministracion": ["oral", "IV", "IM"],
    "dosis": {
      "adulto": "Oral: 250-500 mg cada 12h con alimentos. IV/IM: 750 mg-1.5 g cada 8h",
      "pediatrico": "Oral: 10-15 mg/kg/12h. IV: 50-100 mg/kg/día cada 8h",
      "ajusteRenal": "CrCl 10-30: dosis habitual cada 12h. CrCl <10: cada 24h"
    },
    "presentaciones": ["Comprimidos 250, 500 mg", "Suspensión 125, 250 mg/5 mL", "Frasco ampolla 750 mg, 1.5 g"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Oral: tomar CON alimentos (mejora absorción)", "No triturar comprimidos (sabor amargo)", "IM: reconstituir con agua, inyección profunda", "Lyme precoz: 500 mg/12h x 14-21 días"],
    "farmacocinetica": {"absorcion": "Oral (axetilo): biodisponibilidad 37-52% con alimentos", "distribucion": "Penetra LCR pobremente. Unión proteica 33-50%", "metabolismo": "Axetilo se hidroliza a cefuroxima activa", "excrecion": "Renal 66-100%", "vidaMedia": "1-2 horas", "inicioAccion": "Oral 2-3h. IV inmediato", "picoAccion": "Oral: 2-3h", "duracionAccion": "8-12 horas"},
    "almacenamiento": "Temperatura ambiente. Suspensión reconstituida: refrigerar 10 días.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "norfloxacino",
    "nombre": "Norfloxacino",
    "nombreGenerico": "Norfloxacino",
    "nombresComerciales": ["Noroxin", "Norfloxacino Gador"],
    "familia": "Quinolonas",
    "clasificacion": "Fluoroquinolona de 2da generación (urinaria)",
    "mecanismoAccion": "Inhibe ADN girasa y topoisomerasa IV. Concentración urinaria alta pero sérica baja. Espectro: Gram- urinarios, incluyendo E. coli, Klebsiella, Proteus.",
    "indicaciones": ["Infección urinaria no complicada", "Prostatitis bacteriana", "Profilaxis de peritonitis bacteriana espontánea en cirrosis"],
    "contraindicaciones": ["Menores de 18 años", "Embarazo y lactancia", "Hipersensibilidad a quinolonas", "Miastenia gravis"],
    "efectosAdversos": ["Náuseas", "Mareo", "Cefalea", "Tendinopatía", "Fotosensibilidad", "Cristaluria"],
    "interacciones": ["Antiácidos, hierro, calcio: reducen absorción", "Teofilina: aumenta niveles", "Warfarina: puede aumentar INR", "Ciclosporina: aumenta niveles"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "ITU: 400 mg cada 12h x 3-7 días. Profilaxis PBE: 400 mg/día",
      "ajusteRenal": "CrCl <30: 400 mg/día"
    },
    "presentaciones": ["Comprimidos 400 mg"],
    "embarazo": "C",
    "lactancia": "Contraindicado.",
    "cuidadosEnfermeria": ["Tomar en AYUNAS (1h antes o 2h después de comidas)", "Separar 2h de antiácidos/hierro/lácteos", "Hidratación abundante (prevenir cristaluria)", "Solo útil para infecciones urinarias (mala absorción sistémica)", "No en menores de 18 años"],
    "farmacocinetica": {"absorcion": "Oral 30-40%", "distribucion": "Concentración renal y urinaria alta. Baja concentración sérica", "metabolismo": "Hepático parcial", "excrecion": "Renal 26-32% inalterado, fecal 30%", "vidaMedia": "3-4 horas", "inicioAccion": "1-2 horas", "picoAccion": "1-2 horas", "duracionAccion": "12 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_02"
  },
  {
    "id": "tigeciclina",
    "nombre": "Tigeciclina",
    "nombreGenerico": "Tigeciclina",
    "nombresComerciales": ["Tygacil"],
    "familia": "Glicilciclinas",
    "clasificacion": "Antibiótico glicilciclina (derivado de tetraciclinas)",
    "mecanismoAccion": "Derivado de minociclina que inhibe la subunidad ribosomal 30S. Activa contra bacterias con mecanismos de resistencia a tetraciclinas (bombas de eflujo, protección ribosomal). Espectro: SARM, VRE, BLEE, anaerobios. NO cubre Pseudomonas.",
    "indicaciones": ["Infecciones intraabdominales complicadas", "Infecciones de piel y tejidos blandos complicadas", "Neumonía adquirida en comunidad", "Infecciones por gérmenes multiresistentes (rescate)"],
    "contraindicaciones": ["Hipersensibilidad a tetraciclinas", "Menores de 8 años"],
    "efectosAdversos": ["Náuseas y vómitos (frecuente)", "Diarrea", "Pancreatitis", "Hepatotoxicidad", "Aumento de mortalidad vs comparadores (FDA warning)"],
    "interacciones": ["Warfarina: potencia anticoagulación", "Anticonceptivos orales: puede reducir eficacia"],
    "viaAdministracion": ["IV"],
    "dosis": {
      "adulto": "Carga: 100 mg IV, luego 50 mg IV cada 12h",
      "ajusteHepatico": "Child-Pugh C: carga 100 mg, luego 25 mg cada 12h"
    },
    "presentaciones": ["Frasco ampolla 50 mg"],
    "embarazo": "D",
    "lactancia": "Contraindicado.",
    "cuidadosEnfermeria": ["Infusión IV en 30-60 min", "Alta incidencia de náuseas: premedicar con antiemético", "Reservar para infecciones sin otra alternativa (stewardship)", "NO cubre Pseudomonas", "Monitorizar hepatograma y amilasa/lipasa", "Warning FDA: aumento de mortalidad en algunos ensayos"],
    "farmacocinetica": {"absorcion": "IV", "distribucion": "Gran volumen de distribución. Concentración tisular alta. Unión proteica 71-89%", "metabolismo": "Hepático (glucuronidación)", "excrecion": "Biliar/fecal 59%, renal 33%", "vidaMedia": "42 horas", "inicioAccion": "Inmediato", "picoAccion": "Fin de infusión", "duracionAccion": "12 horas (dosificación)"},
    "almacenamiento": "Temperatura ambiente. Reconstituido: 6h TA, 24h refrigerado.",
    "unidadId": "u03", "capituloId": "c03_03"
  },
  {
    "id": "secnidazol",
    "nombre": "Secnidazol",
    "nombreGenerico": "Secnidazol",
    "nombresComerciales": ["Flagentyl", "Secnidal"],
    "familia": "Antiparasitarios",
    "clasificacion": "Nitroimidazol de acción prolongada",
    "mecanismoAccion": "Nitroimidazol similar a metronidazol pero con vida media mucho más larga, permitiendo tratamiento en dosis única. Activo contra Giardia, Entamoeba, Trichomonas, Blastocystis.",
    "indicaciones": ["Giardiasis", "Amebiasis intestinal", "Tricomoniasis", "Vaginosis bacteriana"],
    "contraindicaciones": ["Embarazo primer trimestre", "Uso con alcohol", "Hipersensibilidad a nitroimidazoles"],
    "efectosAdversos": ["Sabor metálico", "Náuseas (menos que metronidazol)", "Efecto disulfiram", "Cefalea"],
    "interacciones": ["Alcohol: reacción disulfiram", "Warfarina: potencia"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "Giardiasis/amebiasis: 2 g dosis única. Tricomoniasis: 2 g dosis única",
      "pediatrico": "30 mg/kg dosis única"
    },
    "presentaciones": ["Comprimidos 500 mg, 1 g", "Suspensión 500 mg/15 mL"],
    "embarazo": "C",
    "lactancia": "Suspender lactancia 48h post-dosis.",
    "cuidadosEnfermeria": ["Dosis ÚNICA: excelente adherencia", "NO alcohol durante y 48h post-tratamiento", "Tomar con alimentos", "Tratar pareja en tricomoniasis", "Control parasitológico post-tratamiento"],
    "farmacocinetica": {"absorcion": "Oral rápida y completa", "distribucion": "Amplia", "metabolismo": "Hepático", "excrecion": "Renal", "vidaMedia": "17-29 horas (la más larga de los nitroimidazoles)", "inicioAccion": "1-2 horas", "picoAccion": "4 horas", "duracionAccion": "48-72 horas"},
    "almacenamiento": "Temperatura ambiente.",
    "unidadId": "u03", "capituloId": "c03_06"
  },
  {
    "id": "amoxicilina_clavulanico",
    "nombre": "Amoxicilina/Ácido Clavulánico",
    "nombreGenerico": "Amoxicilina + ácido clavulánico",
    "nombresComerciales": ["Augmentin", "Optamox", "Clavulin"],
    "familia": "Penicilinas con inhibidor de betalactamasas",
    "clasificacion": "Betalactámico + inhibidor de betalactamasa",
    "mecanismoAccion": "La amoxicilina inhibe la síntesis de pared celular. El ácido clavulánico inhibe irreversiblemente betalactamasas clase A (TEM, SHV), restaurando la actividad de amoxicilina contra gérmenes productores de betalactamasas: H. influenzae, Moraxella, S. aureus MSSA, E. coli.",
    "indicaciones": ["Otitis media aguda", "Sinusitis aguda bacteriana", "Mordeduras de animales", "Infecciones urinarias", "Neumonía por aspiración", "Infecciones de piel y tejidos blandos"],
    "contraindicaciones": ["Alergia a penicilinas", "Hepatitis colestática previa por amoxicilina/clavulánico", "Mononucleosis infecciosa (rash)"],
    "efectosAdversos": ["Diarrea (más que amoxicilina sola, por clavulánico)", "Náuseas", "Erupción cutánea", "Candidiasis", "Hepatitis colestática (rara)"],
    "interacciones": ["Metotrexato: reduce excreción", "Warfarina: potencia anticoagulación", "Probenecid: aumenta niveles", "Alopurinol: mayor riesgo de rash"],
    "viaAdministracion": ["oral", "IV"],
    "dosis": {
      "adulto": "Oral: 875/125 mg cada 12h o 500/125 mg cada 8h. IV: 1000/200 mg cada 8h",
      "pediatrico": "45-90 mg/kg/día (componente amoxicilina) dividido cada 12h"
    },
    "presentaciones": ["Comprimidos 875/125, 500/125 mg", "Suspensión 250/62.5, 400/57 mg/5 mL", "Frasco ampolla 1000/200 mg"],
    "embarazo": "B",
    "lactancia": "Compatible.",
    "cuidadosEnfermeria": ["Tomar al INICIO de las comidas (reduce diarrea por clavulánico)", "Diarrea frecuente: informar al paciente", "Vigilar signos de sobreinfección (candidiasis)", "Dosis alta (90 mg/kg) en OMA si sospecha neumococo resistente", "Monitorizar hepatograma si tratamiento prolongado"],
    "farmacocinetica": {"absorcion": "Oral buena (ambos componentes)", "distribucion": "Amplia. Amox: unión proteica 20%. Clav: 25%", "metabolismo": "Clavulánico: hepático extenso. Amox: mínimo", "excrecion": "Renal (ambos)", "vidaMedia": "Amox: 1h. Clav: 1h", "inicioAccion": "1-2 horas", "picoAccion": "1-2 horas", "duracionAccion": "8-12 horas"},
    "almacenamiento": "Temperatura ambiente. Suspensión reconstituida: refrigerar 7 días.",
    "unidadId": "u03", "capituloId": "c03_01"
  },
  {
    "id": "trimetoprima",
    "nombre": "Trimetoprima",
    "nombreGenerico": "Trimetoprima",
    "nombresComerciales": ["Triprima"],
    "familia": "Antibióticos urinarios",
    "clasificacion": "Inhibidor de dihidrofolato reductasa",
    "mecanismoAccion": "Inhibe selectivamente la dihidrofolato reductasa bacteriana, bloqueando la síntesis de ácido tetrahidrofólico necesario para la producción de purinas y timidilato. Bacteriostática sola, bactericida combinada con sulfametoxazol.",
    "indicaciones": ["Infecciones urinarias no complicadas", "Profilaxis de ITU recurrente"],
    "contraindicaciones": ["Anemia megaloblástica por déficit de folato", "Insuficiencia renal severa", "Hipersensibilidad"],
    "efectosAdversos": ["Erupción cutánea", "Prurito", "Anemia megaloblástica (prolongado)", "Hiperpotasemia", "Aumento de creatinina (no indica daño renal real)"],
    "interacciones": ["Metotrexato: toxicidad hematológica aditiva", "IECA/ARA-II: hiperpotasemia", "Fenitoína: aumenta niveles", "Dapsona: aumenta niveles de ambos"],
    "viaAdministracion": ["oral"],
    "dosis": {
      "adulto": "ITU: 200 mg/12h o 300 mg/día x 3-7 días. Profilaxis: 100 mg/noche"
    },
    "presentaciones": ["Comprimidos 100, 200 mg"],
    "embarazo": "C",
    "lactancia": "Compatible con precaución.",
    "cuidadosEnfermeria": ["Alternativa en alergia a sulfamidas (vs TMP/SMX)", "Hidratación adecuada", "Monitorizar potasio en pacientes con IR o IECA", "El aumento de creatinina es por inhibición de secreción tubular, no daño renal", "Control de hemograma si uso prolongado"],
    "farmacocinetica": {"absorcion": "Oral: biodisponibilidad 90-100%", "distribucion": "Amplia. Concentración prostática y vaginal alta", "metabolismo": "Hepático 10-20%", "excrecion": "Renal 50-60% inalterada", "vidaMedia": "8-11 horas", "inicioAccion": "1-4 horas", "picoAccion": "1-4 horas", "duracionAccion": "12-24 horas"},
    "almacenamiento": "Temperatura ambiente. Proteger de la luz.",
    "unidadId": "u03", "capituloId": "c03_03"
  }
]

# Chapters and existing chapter additions
NEW_CHAPTERS = []  # No new chapters needed for u03

EXISTING_CHAPTER_ADDITIONS = {
    "c03_01": ["cefazolina", "ceftazidima", "cefepime", "cloxacilina", "penicilina_g", "amoxicilina_clavulanico", "cefuroxima"],
    "c03_02": ["claritromicina", "eritromicina", "moxifloxacino", "norfloxacino"],
    "c03_03": ["imipenem_cilastatina", "ertapenem", "teicoplanina", "fosfomicina", "tigeciclina", "trimetoprima"],
    "c03_04": ["voriconazol", "caspofungina", "itraconazol", "ganciclovir", "valganciclovir", "atazanavir", "tenofovir_emtricitabina", "efavirenz"],
    "c03_05": ["pirazinamida", "etambutol"],
    "c03_06": ["metronidazol_antiparasitario", "tinidazol", "benznidazol", "secnidazol"],
}

PATHOLOGY_LINKS = {
    "pat_neumonia": ["cefuroxima", "moxifloxacino", "claritromicina"],
    "pat_neumonia_nosocomial": ["ceftazidima", "cefepime", "imipenem_cilastatina", "tigeciclina"],
    "pat_sepsis": ["cefepime", "imipenem_cilastatina", "ertapenem"],
    "pat_itu": ["fosfomicina", "cefuroxima", "norfloxacino", "trimetoprima", "cefazolina"],
    "pat_celulitis": ["cloxacilina", "cefazolina", "amoxicilina_clavulanico"],
    "pat_tuberculosis": ["pirazinamida", "etambutol"],
    "pat_neutropenia_febril": ["cefepime", "ceftazidima", "imipenem_cilastatina", "caspofungina"],
}

def main():
    print("=== Generating u03 drugs ===")
    added = add_drugs_to_file(NEW_DRUGS)

    cats = load_categories()
    for ch in NEW_CHAPTERS:
        add_chapter(cats, "u03", ch)
    for ch_id, drug_ids in EXISTING_CHAPTER_ADDITIONS.items():
        for did in drug_ids:
            add_drug_to_chapter(cats, ch_id, did)
    save_categories(cats)
    print("  Updated categories.json")

    pats = load_pathologies()
    for pat_id, drug_ids in PATHOLOGY_LINKS.items():
        for did in drug_ids:
            add_drug_to_pathology(pats, pat_id, did)
    save_pathologies(pats)
    print("  Updated pathologies.json")

if __name__ == "__main__":
    main()
