#!/usr/bin/env python3
"""Supplement: add ~55 more drugs for U02 Cardiovascular."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c02_01 Antihipertensivos (+10) ──
M("ara2","candesartan","Candesartán","Candesartán cilexetilo",["Atacand","Blopress"],
  "ARA-II de alta afinidad por AT1",
  "Profármaco hidrolizado a candesartán activo. Unión prácticamente irreversible al receptor AT1",
  ["HTA","Insuficiencia cardíaca con FEVI reducida"],["oral"],
  {"adulto":"HTA: 8-32 mg/día en dosis única. IC: 4-32 mg/día","pediatrico":"1-6 años: 0.2 mg/kg/día; 6-17 años: 4-16 mg/día",
   "ajusteRenal":"Inicio 4 mg/día si ClCr <30"},
  ["Comp 4, 8, 16, 32 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ara2","telmisartan","Telmisartán","Telmisartán",["Micardis","Pritor"],
  "ARA-II con mayor vida media de la clase",
  "Antagonista AT1 con vida media >24h. Agonista parcial PPARγ (beneficio metabólico)",
  ["HTA","Reducción riesgo cardiovascular en alto riesgo"],["oral"],
  {"adulto":"20-80 mg/día en dosis única"},
  ["Comp 20, 40, 80 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ara2","olmesartan","Olmesartán","Olmesartán medoxomilo",["Benicar","Olmetec"],
  "ARA-II de alta potencia",
  "Profármaco convertido en olmesartán activo. Potente bloqueo AT1 con efecto antihipertensivo dosis-dependiente",
  ["HTA"],["oral"],
  {"adulto":"10-40 mg/día en dosis única","pediatrico":"≥6 años: 10-20 mg/día"},
  ["Comp 10, 20, 40 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ara2","irbesartan","Irbesartán","Irbesartán",["Aprovel","Avapro"],
  "ARA-II con eficacia nefroprotecotra",
  "Antagonista competitivo del receptor AT1. Eficacia demostrada en nefropatía diabética tipo 2",
  ["HTA","Nefropatía diabética en DM2 con HTA"],["oral"],
  {"adulto":"150-300 mg/día en dosis única"},
  ["Comp 75, 150, 300 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ieca","perindopril","Perindopril","Perindopril arginina",["Coversyl","Acertil"],
  "IECA con evidencia en prevención CV",
  "Profármaco convertido a perindoprilato activo. Evidencia en prevención secundaria (EUROPA) y enfermedad coronaria estable",
  ["HTA","Enfermedad coronaria estable","IC con FEVI reducida"],["oral"],
  {"adulto":"HTA: 4-8 mg/día. Coronaria: 8 mg/día. IC: 2-4 mg/día",
   "geriatrico":"Inicio 2 mg/día","ajusteRenal":"2 mg/día si ClCr <30"},
  ["Comp 2, 4, 5, 8, 10 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ieca","ramipril","Ramipril","Ramipril",["Tritace","Altace"],
  "IECA con amplia evidencia cardiovascular",
  "Profármaco convertido a ramiprilato. Estudio HOPE demostró reducción de eventos CV en alto riesgo",
  ["HTA","IC post-IAM","Prevención CV en alto riesgo","Nefropatía diabética y no diabética"],["oral"],
  {"adulto":"HTA: 2.5-10 mg/día. IC: 1.25-10 mg/día. Prevención CV: 10 mg/día",
   "ajusteRenal":"1.25 mg/día si ClCr <40"},
  ["Cáps 1.25, 2.5, 5, 10 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ieca","fosinopril","Fosinopril","Fosinopril sódico",["Monopril","Fosinil"],
  "IECA con doble vía de eliminación",
  "Único IECA con eliminación equilibrada hepato-renal (50/50). No requiere ajuste en IR moderada",
  ["HTA","Insuficiencia cardíaca"],["oral"],
  {"adulto":"HTA: 10-40 mg/día. IC: 10-40 mg/día"},
  ["Comp 10, 20 mg"],"Evitar durante lactancia","u02","c02_01"),

M("ieca","benazepril","Benazepril","Benazepril",["Lotensin","Cibacen"],
  "IECA de acción prolongada",
  "Profármaco convertido a benazeprilato activo. Alta afinidad por ECA tisular y plasmática",
  ["HTA","Nefropatía crónica"],["oral"],
  {"adulto":"10-40 mg/día en 1-2 tomas","ajusteRenal":"5 mg/día si ClCr <30"},
  ["Comp 5, 10, 20, 40 mg"],"Evitar durante lactancia","u02","c02_01"),

M("betabloqueante","nebivolol_cv","Nebivolol","Nebivolol",["Nebilet","Bystolic"],
  "Betabloqueante beta-1 selectivo vasodilatador",
  "Máxima beta-1 selectividad de la clase. Estimula liberación endotelial de NO (vasodilatación). No empeora metabolismo glucídico",
  ["HTA","IC con FEVI reducida (≥70 años)"],["oral"],
  {"adulto":"HTA: 5 mg/día. IC: inicio 1.25 mg/día, titular hasta 10 mg/día",
   "geriatrico":"Inicio 2.5 mg/día","ajusteRenal":"2.5 mg/día si ClCr <30"},
  ["Comp 2.5, 5, 10 mg"],"Evitar durante lactancia","u02","c02_01"),

M("calcioantagonista","lercanidipino","Lercanidipino","Lercanidipino",["Zanidip","Lercapress"],
  "Calcioantagonista DHP de 3ª generación",
  "Dihidropiridina lipofílica con inicio de acción gradual y prolongado. Menor edema periférico que amlodipino",
  ["HTA leve a moderada"],["oral"],
  {"adulto":"10-20 mg/día en dosis única antes del desayuno"},
  ["Comp 10, 20 mg"],"Evitar durante lactancia","u02","c02_01"),

# ── c02_02 Antiarrítmicos (+8) ──
M("","procainamida","Procainamida","Procainamida",["Pronestyl"],
  "Antiarrítmico clase IA",
  "Bloquea canales de sodio (clase IA). Prolonga duración del potencial de acción y período refractario. Metabolito NAPA tiene actividad clase III",
  ["Taquicardia ventricular sostenida","FA estable con preexcitación (WPW)","Taquicardia de complejo ancho estable"],["IV","oral"],
  {"adulto":"IV: 20-50 mg/min hasta control (máx 17 mg/kg). Mantenimiento: 1-4 mg/min infusión",
   "ajusteRenal":"Reducir dosis 25-50% si ClCr <30"},
  ["Amp 100 mg/mL 10mL","Comp 250, 500 mg"],"Compatible con precaución","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["Bloqueo AV 2-3°","Prolongación QT","Lupus eritematoso sistémico","Torsade de pointes","Miastenia gravis"],
  ea=["Hipotensión (IV)","Lupus inducido por fármacos","Prolongación QT","Agranulocitosis","Náuseas","Fiebre"],
  ix=["Amiodarona: prolonga QT aditivo","Digoxina: aumenta niveles","Anticolinérgicos: antagonismo en efecto vagal"],
  ce=["Monitorizar PA cada 5 min durante carga IV","Detener si QRS se ensancha >50% o hipotensión","Anticuerpos antinucleares cada 3-6 meses","Monitorizar niveles de NAPA en IR"],
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"20-50 mg/min, máx 17 mg/kg","estabilidad":"24h a TA diluido"}),

M("betabloqueante","sotalol","Sotalol","Sotalol",["Sotapor","Betapace"],
  "Betabloqueante con actividad antiarrítmica clase III",
  "Betabloqueante no selectivo (clase II) + bloqueo de canales de potasio (clase III). Prolonga QT dosis-dependiente",
  ["Fibrilación auricular (mantenimiento sinusal)","Taquicardia ventricular","Arritmias supraventriculares"],["oral","IV"],
  {"adulto":"Oral: 80-160 mg c/12h. Máx 320 mg/día. IV: 1.5 mg/kg en 5 min",
   "ajusteRenal":"80 mg c/24h si ClCr 30-60; contraindicado si ClCr <30"},
  ["Comp 80, 160 mg","Amp 10 mg/mL"],"Evitar durante lactancia","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["Asma bronquial","Prolongación QT basal","ClCr <40 (formulación IV)","Bradicardia <50 lpm","Hipopotasemia no corregida"],
  ea=["Bradicardia","Prolongación QT","Torsade de pointes","Fatiga","Mareo","Disnea","Hipotensión"],
  ix=["Fármacos que prolongan QT: riesgo aditivo torsade","Diuréticos: hipopotasemia potencia proarritmia","Calcioantagonistas no-DHP: bradicardia severa"],
  ce=["Iniciar con monitorización ECG hospitalaria 3 días","Corregir K+ y Mg2+ antes de iniciar","QTc >500 ms: suspender o reducir dosis","Ajuste renal obligatorio"]),

M("","dronedarona","Dronedarona","Dronedarona",["Multaq"],
  "Antiarrítmico multicanal (derivado de amiodarona sin yodo)",
  "Bloquea canales de Na+, K+, Ca2+ y receptores adrenérgicos. Sin yodo: evita toxicidad tiroidea/pulmonar de amiodarona",
  ["FA/flutter no permanente para mantener ritmo sinusal"],["oral"],
  {"adulto":"400 mg c/12h con alimentos"},
  ["Comp 400 mg"],"Contraindicado","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["IC clase IV o IC descompensada reciente","FA permanente","Bloqueo AV 2-3°","Bradicardia <50","Uso con inhibidores potentes CYP3A4","Insuficiencia hepática severa"],
  ea=["Diarrea","Náuseas","Bradicardia","Prolongación QT","Elevación creatinina","Hepatotoxicidad (raro)"],
  ix=["Inhibidores CYP3A4: aumentan niveles","Digoxina: aumenta niveles 2.5x","Dabigatrán: aumenta niveles","Estatinas: aumenta niveles"],
  ce=["NO usar en IC clase III-IV ni FA permanente","Monitorizar función hepática primeros 6 meses","Tomar siempre con alimentos","Suspender si recurre FA permanente"]),

M("","dofetilida","Dofetilida","Dofetilida",["Tikosyn"],
  "Antiarrítmico clase III puro",
  "Bloquea selectivamente canal de potasio IKr. Prolonga potencial de acción y QT sin efecto sobre contractilidad",
  ["FA/flutter auricular (cardioversión farmacológica y mantenimiento)"],["oral"],
  {"adulto":"125-500 mcg c/12h según ClCr y QTc","ajusteRenal":"250 mcg c/12h si ClCr 40-60; 125 mcg c/12h si ClCr 20-40; contraindicado si ClCr <20"},
  ["Cáps 125, 250, 500 mcg"],"Contraindicado","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["QTc basal >440 ms","ClCr <20","Uso con inhibidores secreción tubular renal","Hipopotasemia/hipomagnesemia"],
  ea=["Prolongación QT","Torsade de pointes (3%)","Cefalea","Dolor torácico","Mareo"],
  ix=["Verapamilo: contraindicado (aumenta niveles)","Cimetidina, ketoconazol: inhiben secreción renal","Diuréticos: hipopotasemia potencia riesgo"],
  ce=["Inicio OBLIGATORIO hospitalario con telemetría 3 días","Medir QTc 2-3h post cada dosis","Suspender si QTc >500 ms","Programa de prescripción restringida (REMS)"]),

M("","ibutilida","Ibutilida","Ibutilida fumarato",["Corvert"],
  "Antiarrítmico clase III para cardioversión IV",
  "Activa corriente lenta de Na+ entrante y bloquea IKr. Prolonga repolarización favoreciendo cardioversión",
  ["Cardioversión farmacológica de FA/flutter reciente (<90 días)"],["IV"],
  {"adulto":"≥60 kg: 1 mg IV en 10 min; puede repetir 1 dosis a los 10 min. <60 kg: 0.01 mg/kg"},
  ["Vial 1 mg/10mL"],"No recomendado","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["Prolongación QT basal","Hipopotasemia o hipomagnesemia no corregida","Uso reciente de amiodarona clase III"],
  ea=["Prolongación QT","Torsade de pointes (4-8%)","Hipotensión","Bradicardia","Bloqueo AV"],
  ix=["Antiarrítmicos clase IA/III: no usar dentro de 4h","Fármacos que prolongan QT: riesgo aditivo"],
  ce=["Monitorización ECG continua durante y 4-6h post-infusión","Desfibrilador disponible","Corregir K+ >4 mEq/L y Mg2+ antes","Más eficaz en flutter que en FA"],
  pp={"dilucion":"Puede diluir en 50 mL SF o SG5%","velocidadAdministracion":"1 mg en 10 minutos","estabilidad":"24h a TA, 48h refrigerado"}),

M("","ranolazina","Ranolazina","Ranolazina",["Ranexa"],
  "Antianginoso inhibidor de corriente tardía de sodio",
  "Inhibe corriente tardía de Na+ (INaL), reduciendo sobrecarga de calcio intracelular. Mejora relajación diastólica sin afectar FC ni PA",
  ["Angina estable crónica (2ª línea, añadida a otros antianginosos)"],["oral"],
  {"adulto":"500 mg c/12h, puede aumentar a 1000 mg c/12h. Máx 1000 mg c/12h"},
  ["Comp LP 500, 1000 mg"],"Evitar durante lactancia","u02","c02_02",
  familia="Antianginosos/Antiarrítmicos",
  ci=["Cirrosis hepática","Uso de inhibidores potentes CYP3A4","Prolongación QT"],
  ea=["Mareo","Náuseas","Estreñimiento","Cefalea","Prolongación QT leve"],
  ix=["Inhibidores CYP3A4 (ketoconazol, claritromicina): contraindicados","Digoxina: aumenta niveles 1.5x","Simvastatina: limitar a 20 mg/día","Metformina: aumenta niveles"],
  ce=["No triturar comprimidos LP","No afecta FC ni PA (ventaja en pacientes límite)","Puede usarse con otros antianginosos","Monitorizar QTc si otros fármacos que prolongan QT"]),

M("","mexiletina","Mexiletina","Mexiletina",["Mexitil"],
  "Antiarrítmico clase IB (análogo oral de lidocaína)",
  "Bloquea canales de sodio con cinética rápida (clase IB). Acorta duración del potencial de acción. Útil en arritmias ventriculares",
  ["Arritmias ventriculares (especialmente asociadas a QT largo congénito tipo 3)","Miotonía en distrofia miotónica"],["oral"],
  {"adulto":"150-200 mg c/8h con alimentos. Máx 1200 mg/día"},
  ["Cáps 150, 200 mg"],"Evitar durante lactancia","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["Bloqueo AV 2-3° sin marcapasos","Shock cardiogénico","IC descompensada"],
  ea=["Náuseas","Temblor","Mareo","Diplopía","Ataxia","Parestesias","Hepatotoxicidad (raro)"],
  ix=["Fármacos que modifican pH urinario: alteran excreción","Inductores CYP1A2 (tabaco): reducen niveles","Inhibidores CYP1A2: aumentan niveles"],
  ce=["Tomar siempre con alimentos (reduce EA GI)","Análogo oral de lidocaína","Monitorizar niveles plasmáticos (0.5-2 mcg/mL)","Uso principal en SQTL tipo 3"]),

M("","adenosina_arritmia","Adenosina (antiarrítmico)","Adenosina",["Adenocor","Adenocard"],
  "Antiarrítmico endógeno ultrarrápido",
  "Nucleósido purínico endógeno. Activa receptores A1 en nodo AV: deprime conducción AV y automatismo sinusal. Vida media <10 segundos",
  ["TSV paroxística (diagnóstico y tratamiento)","Diagnóstico diferencial de taquicardias de complejo estrecho"],["IV"],
  {"adulto":"6 mg IV en bolo rápido; si no responde en 1-2 min: 12 mg; puede repetir 12 mg una vez",
   "pediatrico":"0.1 mg/kg (máx 6 mg), incrementar a 0.2 mg/kg (máx 12 mg)"},
  ["Amp 6 mg/2mL","Vial 30 mg/10mL"],"Compatible con precaución","u02","c02_02",
  familia="Antiarrítmicos",
  ci=["Bloqueo AV 2-3° o disfunción sinusal sin marcapasos","Asma bronquial severa","FA con preexcitación (WPW)"],
  ea=["Rubor facial","Disnea transitoria","Opresión torácica","Bradicardia/asistolia transitoria","Broncoespasmo","Náuseas"],
  ix=["Dipiridamol: potencia efecto (reducir dosis a 3 mg)","Teofilina/cafeína: antagonizan efecto (puede requerir dosis mayores)","Carbamazepina: mayor riesgo bloqueo AV"],
  ce=["Administrar en bolo IV MUY rápido (<2 seg) seguido de flush de 20 mL SF","Usar vía lo más proximal posible al corazón","Avisar al paciente: sensación transitoria desagradable (10-20 seg)","Tener atropina y equipo de RCP disponible","Registrar ritmo ECG durante administración"],
  pp={"dilucion":"No diluir, administrar directo","velocidadAdministracion":"Bolo IV ultrarrápido <2 seg + flush 20 mL SF inmediato","estabilidad":"No refrigerar. Cristales se forman en frío (calentar si ocurre)"}),

# ── c02_03 Insuficiencia Cardíaca (+8) ──
M("","sacubitril_valsartan","Sacubitrilo/Valsartán","Sacubitrilo/Valsartán",["Entresto"],
  "INRA (inhibidor de neprilisina y receptor de angiotensina)",
  "Sacubitrilo inhibe neprilisina (aumenta péptidos natriuréticos) + valsartán bloquea AT1. Doble mecanismo neurohumoral",
  ["IC con FEVI reducida (reemplaza IECA/ARA-II)"],["oral"],
  {"adulto":"Inicio 24/26 mg c/12h (si no tomaba IECA/ARA-II) o 49/51 mg c/12h. Objetivo: 97/103 mg c/12h",
   "ajusteRenal":"24/26 mg c/12h si ClCr <30","ajusteHepatico":"24/26 mg c/12h en Child-Pugh B; contraindicado en C"},
  ["Comp 24/26, 49/51, 97/103 mg"],"Contraindicado","u02","c02_03",
  familia="INRA (inhibidores de neprilisina/ARA-II)",
  ci=["Uso concomitante con IECA (esperar 36h)","Angioedema previo con IECA/ARA-II","Embarazo","Uso con aliskirén en diabéticos"],
  ea=["Hipotensión","Hiperpotasemia","Deterioro función renal","Mareo","Angioedema (raro)"],
  ix=["IECA: angioedema (esperar 36h de lavado)","Aliskirén: contraindicado en diabéticos","AINEs: reducen efecto y nefrotoxicidad","Litio: aumenta niveles"],
  ce=["Esperar 36h tras última dosis de IECA antes de iniciar","Titular cada 2-4 semanas según tolerancia","Monitorizar PA, K+ y función renal","Superior a enalapril en IC (estudio PARADIGM-HF)"]),

M("","ivabradina_ic","Ivabradina (IC)","Ivabradina",["Corlentor","Procoralan"],
  "Inhibidor selectivo de corriente If sinusal",
  "Bloquea selectivamente canales If del nodo sinusal. Reduce FC sin afectar contractilidad, conducción AV ni PA",
  ["IC con FEVI ≤35%, ritmo sinusal ≥70 lpm a pesar de betabloqueante máximo tolerado"],["oral"],
  {"adulto":"Inicio 5 mg c/12h. Ajustar según FC: objetivo 50-60 lpm. Máx 7.5 mg c/12h"},
  ["Comp 5, 7.5 mg"],"Contraindicado","u02","c02_03",
  familia="Inhibidores de corriente If",
  ci=["FC basal <70 lpm","Bloqueo AV 2-3°","Dependencia de marcapasos","IC descompensada aguda","Uso de inhibidores potentes CYP3A4","Insuficiencia hepática severa"],
  ea=["Fosfenos (fenómenos luminosos visuales)","Bradicardia","Cefalea","Mareo","FA"],
  ix=["Inhibidores CYP3A4: aumentan niveles","Verapamilo/diltiazem: bradicardia aditiva (evitar)","Fármacos que prolongan QT: precaución"],
  ce=["Solo añadir si FC ≥70 lpm con betabloqueante máximo","Tomar con alimentos","Advertir sobre fosfenos (luces, transitorios, benignos)","Suspender si FC <50 lpm"]),

M("","hidralazina_ic","Hidralazina (IC)","Hidralazina",["Hydrapres"],
  "Vasodilatador arteriolar directo",
  "Relaja directamente músculo liso arteriolar. Reduce poscarga. En IC se usa combinada con dinitrato de isosorbide",
  ["IC con FEVI reducida intolerante a IECA/ARA-II","IC en pacientes afroamericanos (con dinitrato isosorbide)"],["oral"],
  {"adulto":"IC: 25-75 mg c/6-8h. Combinado con DNIS: 37.5 mg/20 mg c/8h"},
  ["Comp 25, 50 mg"],"Compatible con precaución","u02","c02_03",
  familia="Vasodilatadores directos",
  ci=["Lupus eritematoso sistémico","Taquicardia severa","Aneurisma aórtico disecante","Valvulopatía mitral reumática"],
  ea=["Taquicardia refleja","Cefalea","Rubor","Náuseas","Lupus inducido por fármacos (dosis altas)","Retención hídrica"],
  ix=["Betabloqueantes: atenúan taquicardia refleja (beneficioso)","AINEs: retención hídrica","Diazóxido: hipotensión severa"],
  ce=["Siempre combinar con betabloqueante (evitar taquicardia refleja)","En IC se usa con dinitrato de isosorbide (A-HeFT)","Vigilar ANA si uso prolongado (lupus inducido)","Tomar con alimentos"]),

M("","dinitrato_isosorbide_ic","Dinitrato de isosorbide (IC)","Dinitrato de isosorbide",["Isosorb IC"],
  "Nitrato venodilatador para IC",
  "Libera NO tras metabolismo hepático. Reduce precarga por venodilatación. En IC combinado con hidralazina",
  ["IC con FEVI reducida intolerante a IECA/ARA-II","IC en afroamericanos (con hidralazina)"],["oral"],
  {"adulto":"20-40 mg c/6-8h (con intervalo libre nocturno). Combinado: 20 mg/37.5 mg hidralazina c/8h"},
  ["Comp 20 mg (combinado con hidralazina 37.5 mg)","Comp 10, 20, 40 mg"],"Compatible con precaución","u02","c02_03",
  familia="Nitratos",
  ci=["Hipotensión severa","Uso de PDE5i","Miocardiopatía hipertrófica obstructiva","Hipovolemia"],
  ea=["Cefalea (muy frecuente)","Hipotensión","Mareo","Tolerancia","Taquicardia refleja"],
  ix=["PDE5i (sildenafilo, tadalafilo): hipotensión severa","Antihipertensivos: hipotensión aditiva"],
  ce=["Intervalo libre de nitrato 8-12h para evitar tolerancia","En IC: combinación con hidralazina (estudio A-HeFT)","Cefalea inicial mejora con el tiempo","Paracetamol para cefalea por nitrato"]),

M("","vericiguat","Vericiguat","Vericiguat",["Verquvo"],
  "Estimulador de guanilato ciclasa soluble (sGC) para IC",
  "Estimula directamente sGC y sensibiliza al NO endógeno. Aumenta GMPc con vasodilatación e inhibición de fibrosis/remodelado",
  ["IC crónica con FEVI reducida tras evento de descompensación"],["oral"],
  {"adulto":"Inicio 2.5 mg/día con alimentos. Duplicar c/2 sem. Objetivo: 10 mg/día"},
  ["Comp 2.5, 5, 10 mg"],"No recomendado","u02","c02_03",
  familia="Estimuladores de sGC",
  ci=["Embarazo","Uso con PDE5i o riociguat","Uso con nitratos de acción prolongada"],emb="X",
  ea=["Hipotensión","Anemia","Cefalea","Mareo","Náuseas"],
  ix=["PDE5i y riociguat: contraindicados","Nitratos de acción prolongada: evitar"],
  ce=["Tomar con alimentos (aumenta absorción)","Titular cada 2 semanas según tolerancia de PA","Estudio VICTORIA: reduce hospitalización por IC","Si paciente no puede tragar: triturar y mezclar con agua"]),

M("","omecamtiv","Omecamtiv mecarbil","Omecamtiv mecarbil",["En investigación"],
  "Activador selectivo de miosina cardíaca",
  "Primer activador de miosina cardíaca. Aumenta tiempo de sístole sin aumentar consumo de O2 ni calcio intracelular",
  ["IC con FEVI reducida (en investigación avanzada/aprobación)"],["oral"],
  {"adulto":"25-50 mg c/12h con alimentos"},
  ["Comp 25, 50 mg"],"No hay datos suficientes","u02","c02_03",
  familia="Activadores de miosina cardíaca",
  ci=["Hipersensibilidad","Estenosis aórtica severa sintomática"],
  ea=["Mareo","Isquemia miocárdica (dosis altas)","Elevación de troponina"],
  ix=["Inhibidores CYP3A4: pueden aumentar niveles"],
  ce=["Mecanismo novedoso: no afecta calcio ni AMPc","Monitorizar troponina","Tomar con alimentos","Estudio GALACTIC-HF: beneficio modesto en IC severa"]),

M("","dapagliflozina_ic","Dapagliflozina (IC)","Dapagliflozina",["Forxiga IC"],
  "Inhibidor SGLT2 para insuficiencia cardíaca",
  "Inhibe cotransportador SGLT2 en túbulo proximal renal. Glucosuria, natriuresis y diuresis osmótica. Efecto cardioprotector independiente de glucemia",
  ["IC con FEVI reducida (con o sin DM2)","IC con FEVI preservada"],["oral"],
  {"adulto":"10 mg/día en dosis única"},
  ["Comp 10 mg"],"No recomendado","u02","c02_03",
  familia="Inhibidores SGLT2 (uso cardiovascular)",
  ci=["DM tipo 1","Cetoacidosis diabética","TFGe <20 (inicio)","Hipersensibilidad"],
  ea=["Infecciones genitourinarias (candidiasis)","Hipotensión","Cetoacidosis euglucémica (raro)","Poliuria","Deshidratación"],
  ix=["Diuréticos: deshidratación e hipotensión aditiva","Insulina/sulfonilureas: ajustar dosis (riesgo hipoglucemia en DM)"],
  ce=["Beneficio en IC independiente de diabetes (DAPA-HF)","Vigilar hidratación y función renal","Suspender antes de cirugía mayor (riesgo cetoacidosis)","No requiere ajuste por glucemia en IC sin DM"]),

M("","empagliflozina_ic","Empagliflozina (IC)","Empagliflozina",["Jardiance IC"],
  "Inhibidor SGLT2 para insuficiencia cardíaca",
  "Inhibe SGLT2 renal. Reduce precarga y poscarga por natriuresis/diuresis osmótica. Mejora metabolismo energético miocárdico",
  ["IC con FEVI reducida (con o sin DM2)","IC con FEVI preservada"],["oral"],
  {"adulto":"10 mg/día en dosis única"},
  ["Comp 10 mg"],"No recomendado","u02","c02_03",
  familia="Inhibidores SGLT2 (uso cardiovascular)",
  ci=["DM tipo 1","Cetoacidosis diabética","TFGe <20 (inicio)","Hipersensibilidad"],
  ea=["Infecciones genitourinarias","Hipotensión","Cetoacidosis euglucémica (raro)","Poliuria"],
  ix=["Diuréticos: deshidratación e hipotensión aditiva","Insulina/sulfonilureas: riesgo hipoglucemia en DM"],
  ce=["Estudio EMPEROR-Reduced y EMPEROR-Preserved: beneficio en ambos fenotipos IC","Vigilar hidratación","Suspender 3 días antes de cirugía mayor","Misma dosis para IC que para DM2"]),

# ── c02_04 Antilipémicos (+8) ──
M("","ezetimiba","Ezetimiba","Ezetimiba",["Zetia","Ezetrol"],
  "Inhibidor selectivo de absorción intestinal de colesterol",
  "Bloquea proteína NPC1L1 en borde en cepillo intestinal. Reduce absorción de colesterol dietético y biliar un 50%. Complementario a estatinas",
  ["Hipercolesterolemia (en combinación con estatinas)","Intolerancia a estatinas (monoterapia)","Sitosterolemia"],["oral"],
  {"adulto":"10 mg/día en dosis única, con o sin alimentos"},
  ["Comp 10 mg"],"Evitar durante lactancia","u02","c02_04",
  familia="Inhibidores de absorción de colesterol",
  ci=["Hipersensibilidad","Enfermedad hepática activa (si se combina con estatina)","Embarazo y lactancia (combinada con estatina)"],
  ea=["Diarrea","Dolor abdominal","Fatiga","Mialgia (con estatina)","Elevación transaminasas (raro)"],
  ix=["Fibratos: aumentan niveles de ezetimiba","Colestiramina: reduce absorción (separar 2h)","Ciclosporina: aumenta niveles de ambos"],
  ce=["Reduce LDL adicional 15-20% sobre estatina","Puede tomarse a cualquier hora","Estudio IMPROVE-IT: beneficio CV con simvastatina","Monitorizar perfil hepático si se combina con estatina"]),

M("","fenofibrato","Fenofibrato","Fenofibrato",["Secalip","Lipidil"],
  "Agonista PPARα (fibrato)",
  "Activa receptor PPARα nuclear. Reduce triglicéridos 30-50%, aumenta HDL 10-20%. Efecto modesto sobre LDL",
  ["Hipertrigliceridemia severa","Dislipidemia mixta","Hiperlipidemia combinada"],["oral"],
  {"adulto":"Micronizado: 200 mg/día con alimentos. Nanoparticulado: 145 mg/día",
   "ajusteRenal":"48 mg/día si ClCr 30-80; contraindicado si ClCr <30"},
  ["Comp 145, 160, 200 mg","Cáps 67, 200 mg"],"Evitar durante lactancia","u02","c02_04",
  familia="Fibratos",
  ci=["Insuficiencia hepática","Insuficiencia renal severa","Litiasis biliar","Uso con estatinas (precaución)","Embarazo"],
  ea=["Mialgia","Elevación CPK","Colelitiasis","Elevación transaminasas","Pancreatitis (raro)","Tromboembolismo pulmonar (raro)"],
  ix=["Estatinas: mayor riesgo miopatía/rabdomiólisis","Anticoagulantes orales: aumenta INR","Ciclosporina: nefrotoxicidad","Colestiramina: separar 1h antes o 4-6h después"],
  ce=["Preferir fenofibrato sobre gemfibrozilo si se combina con estatina","Monitorizar CPK y función hepática","Controlar función renal periódicamente","Tomar con alimentos"]),

M("","gemfibrozilo","Gemfibrozilo","Gemfibrozilo",["Lopid"],
  "Fibrato de primera generación",
  "Agonista PPARα. Reduce triglicéridos 40-55%, aumenta HDL 15-25%. Potente inhibidor CYP2C8 y glucuronidación",
  ["Hipertrigliceridemia severa (>500 mg/dL)","Prevención de pancreatitis por TG"],["oral"],
  {"adulto":"600 mg c/12h, 30 min antes del desayuno y cena"},
  ["Comp 600, 900 mg"],"Evitar durante lactancia","u02","c02_04",
  familia="Fibratos",
  ci=["Insuficiencia hepática","Litiasis biliar","Uso con repaglinida","Uso con estatinas (contraindicado con la mayoría)"],
  ea=["Dispepsia","Dolor abdominal","Mialgia","Elevación CPK","Colelitiasis","Anemia"],
  ix=["Estatinas: contraindicado (rabdomiólisis, inhibe glucuronidación)","Repaglinida: hipoglucemia severa (contraindicado)","Warfarina: aumenta INR significativamente"],
  ce=["NO combinar con estatinas (usar fenofibrato en su lugar)","Tomar 30 min antes de comidas","Monitorizar CPK y perfil hepático","Hemograma periódico (riesgo anemia)"]),

M("","alirocumab","Alirocumab","Alirocumab",["Praluent"],
  "Anticuerpo monoclonal anti-PCSK9",
  "Anticuerpo monoclonal IgG1 que se une a PCSK9, impidiendo degradación del receptor de LDL hepático. Aumenta captación y reducción de LDL 50-60%",
  ["Hipercolesterolemia familiar heterocigota","Enfermedad CV aterosclerótica con LDL no controlado con estatina máxima"],["SC"],
  {"adulto":"75 mg SC c/2 sem o 150 mg SC c/2 sem. Alternativa: 300 mg SC c/4 sem"},
  ["Pluma precargada 75, 150 mg/mL"],"Evitar durante lactancia","u02","c02_04",
  familia="Inhibidores de PCSK9",
  ci=["Hipersensibilidad"],
  ea=["Reacción en sitio de inyección","Nasofaringitis","Mialgias","Síntomas gripales","Prurito"],
  ix=["Mínimas interacciones farmacocinéticas","Estatinas: efecto aditivo beneficioso"],
  ce=["Dejar a TA 30-45 min antes de inyectar","Rotar sitios de inyección (abdomen, muslo, brazo)","Refrigerar (2-8°C)","Reduce LDL hasta 50-60% adicional sobre estatina"],
  alm="Refrigerar 2-8°C. Puede mantenerse a TA hasta 30 días"),

M("","evolocumab","Evolocumab","Evolocumab",["Repatha"],
  "Anticuerpo monoclonal anti-PCSK9",
  "Anticuerpo IgG2 anti-PCSK9. Previene unión PCSK9-receptor LDL, manteniendo receptores activos en hepatocito",
  ["Hipercolesterolemia familiar homocigota y heterocigota","Enfermedad CV aterosclerótica","LDL no controlado con estatina máxima"],["SC"],
  {"adulto":"140 mg SC c/2 sem o 420 mg SC c/mes","pediatrico":"HoFH ≥12 años: 420 mg c/mes"},
  ["Pluma 140 mg/mL","Cartucho 420 mg/3.5mL (Pushtronex)"],"Evitar durante lactancia","u02","c02_04",
  familia="Inhibidores de PCSK9",
  ci=["Hipersensibilidad"],
  ea=["Reacción en sitio de inyección","Nasofaringitis","Infección tracto respiratorio superior","Artralgias","Dorsalgia"],
  ix=["Mínimas interacciones","Efecto aditivo con estatinas y ezetimiba"],
  ce=["Estudio FOURIER: reducción eventos CV","Dispositivo Pushtronex para dosis 420 mg en domicilio","Refrigerar; a TA hasta 30 días","Instruir al paciente en autoadministración SC"],
  alm="Refrigerar 2-8°C. Proteger de luz"),

M("","acido_nicotinico","Ácido nicotínico (Niacina)","Ácido nicotínico",["Niaspan","Niacin LP"],
  "Vitamina B3 a dosis farmacológicas",
  "A dosis altas inhibe lipólisis en adipocito (receptor GPR109A). Reduce TG 20-50%, aumenta HDL 15-35%, reduce LDL 5-25%",
  ["Dislipidemia mixta","Hipercolesterolemia (adyuvante)","Hipertrigliceridemia"],["oral"],
  {"adulto":"LP: inicio 500 mg/noche, titular c/4 sem hasta 1000-2000 mg/noche"},
  ["Comp LP 500, 750, 1000 mg"],"Compatible con precaución","u02","c02_04",
  familia="Ácido nicotínico y derivados",
  ci=["Enfermedad hepática activa","Úlcera péptica activa","Hemorragia arterial","Hipersensibilidad"],
  ea=["Rubor facial (flushing) muy frecuente","Prurito","Hepatotoxicidad","Hiperuricemia/gota","Hiperglucemia","Miopatía (con estatinas)"],
  ix=["Estatinas: mayor riesgo miopatía a dosis altas","Antihipertensivos: hipotensión aditiva","Alcohol: potencia flushing"],
  ce=["Aspirina 325 mg o ibuprofeno 30 min antes para reducir flushing","Tomar con snack nocturno (reduce flushing)","Evitar alcohol y bebidas calientes","Monitorizar función hepática, glucemia y ácido úrico"]),

M("","colestiramina_lip","Colestiramina","Colestiramina",["Questran","Efensol"],
  "Resina secuestradora de ácidos biliares",
  "Se une a ácidos biliares en intestino, impidiendo reabsorción. Hígado convierte más colesterol en ácidos biliares, aumentando receptores de LDL",
  ["Hipercolesterolemia","Prurito por colestasis","Diarrea por malabsorción de ácidos biliares"],["oral"],
  {"adulto":"4-16 g/día en 1-2 tomas antes de comidas. Máx 24 g/día"},
  ["Polvo 4 g/sobre"],"Compatible durante lactancia","u02","c02_04",
  familia="Resinas de intercambio iónico",emb="B",
  ci=["Obstrucción biliar completa","Hipertrigliceridemia (>400 mg/dL, empeora TG)","Fenilcetonuria (versiones con aspartamo)"],
  ea=["Estreñimiento (muy frecuente)","Flatulencia","Distensión abdominal","Náuseas","Malabsorción de vitaminas liposolubles"],
  ix=["Reduce absorción de MUCHOS fármacos: administrar otros medicamentos 1h antes o 4-6h después","Warfarina: reduce absorción","Tiroxina: reduce absorción","Digoxina: reduce absorción"],
  ce=["Mezclar polvo en agua o jugo (nunca en seco)","Administrar otros fármacos 1h antes o 4-6h después","Suplementar vitaminas A, D, E, K en uso prolongado","Aumentar fibra e hidratación (estreñimiento)"]),

M("","inclisiran","Inclisirán","Inclisirán sódico",["Leqvio"],
  "ARN interferente pequeño (siRNA) anti-PCSK9",
  "siRNA conjugado con GalNAc que silencia ARNm de PCSK9 en hepatocito. Efecto prolongado: 2 inyecciones/año tras carga",
  ["Hipercolesterolemia primaria o dislipidemia mixta como adyuvante a estatina",
   "Hipercolesterolemia familiar heterocigota"],["SC"],
  {"adulto":"284 mg SC: dosis inicial, repetir a 3 meses, luego cada 6 meses"},
  ["Jeringa precargada 284 mg/1.5mL"],"No recomendado","u02","c02_04",
  familia="Silenciadores de ARN (siRNA)",
  ci=["Hipersensibilidad"],
  ea=["Reacción en sitio de inyección","Artralgias","Infección tracto urinario","Dorsalgia","Bronquitis"],
  ix=["No se han identificado interacciones clínicamente relevantes"],
  ce=["Solo 2 inyecciones al año (gran ventaja de adherencia)","Administración por profesional sanitario","Conservar refrigerado; a TA hasta 24h","Monitorizar LDL a los 3 meses"],
  alm="Refrigerar 2-8°C. No congelar"),

# ── c02_11 Cardiopatía Congénita y Fetal (+6) ── NUEVO
M("","alprostadil_ductus","Alprostadil (ductus)","Alprostadil (PGE1)",["Prostin VR"],
  "Prostaglandina E1 para mantenimiento del ductus arterioso",
  "PGE1 sintética que mantiene ductus arterioso permeable. Permite mezcla de sangre en cardiopatías congénitas ductus-dependientes",
  ["Cardiopatías congénitas ductus-dependientes (transposición grandes vasos, coartación aórtica, atresia pulmonar)"],["IV"],
  {"adulto":"N/A (uso neonatal exclusivo)",
   "pediatrico":"Neonatos: 0.05-0.1 mcg/kg/min inicio, mantenimiento 0.01-0.05 mcg/kg/min"},
  ["Amp 500 mcg/mL"],"N/A (uso neonatal)","u02","c02_11",
  familia="Prostaglandinas (uso cardiovascular neonatal)",emb="X",
  ci=["Síndrome de dificultad respiratoria del recién nacido (relativa)"],
  ea=["Apnea (12%)","Fiebre","Rubor","Bradicardia","Hipotensión","Convulsiones","Hiperplasia gástrica antral (uso prolongado)"],
  ix=["Mínimas interacciones en neonatos"],
  ce=["Monitorización continua en UCIN obligatoria","Tener equipo de intubación disponible (apnea frecuente)","Titular a menor dosis efectiva","Uso temporal hasta corrección quirúrgica"],
  pp={"dilucion":"Diluir en SF o SG5% a 2-20 mcg/mL","velocidadAdministracion":"Infusión continua 0.01-0.1 mcg/kg/min","estabilidad":"24h a TA diluido"}),

M("","indometacina_ductus","Indometacina (cierre ductus)","Indometacina IV",["Indocin IV"],
  "AINE para cierre farmacológico del ductus arterioso permeable",
  "Inhibe ciclooxigenasa, reduciendo síntesis de PGE2 que mantiene ductus abierto. Promueve cierre del ductus arterioso en prematuros",
  ["Ductus arterioso permeable en prematuros (cierre farmacológico)"],["IV"],
  {"pediatrico":"Prematuros: 0.2 mg/kg IV inicial; 2ª y 3ª dosis según edad postnatal: <48h: 0.1 mg/kg; 2-7d: 0.2 mg/kg; >7d: 0.25 mg/kg; c/12-24h"},
  ["Vial liofilizado 1 mg"],"N/A (uso neonatal)","u02","c02_11",
  familia="AINEs (uso cardiovascular neonatal)",
  ci=["Enterocolitis necrotizante activa","Hemorragia intraventricular activa","Trombocitopenia severa","Insuficiencia renal significativa","Cardiopatía ductus-dependiente"],
  ea=["Oliguria/insuficiencia renal","Hemorragia GI","Perforación intestinal","Trombocitopenia","Hiponatremia"],
  ix=["Aminoglucósidos: aumenta niveles (reducir dosis)","Digoxina: aumenta niveles"],
  ce=["Monitorizar diuresis estricta (oliguria frecuente)","Ecocardiograma pre y post tratamiento","Vigilar función renal y plaquetas","No administrar si gasto urinario <0.6 mL/kg/h"],
  pp={"dilucion":"Reconstituir con 1-2 mL SF (sin conservante)","velocidadAdministracion":"IV lento en 20-30 min","estabilidad":"Usar inmediatamente tras reconstitución"}),

M("","ibuprofeno_ductus","Ibuprofeno IV (cierre ductus)","Ibuprofeno lisina IV",["NeoProfen","Pedea"],
  "AINE alternativo para cierre del ductus arterioso",
  "Inhibe COX-1 y COX-2, reduciendo PGE2. Menos efectos renales que indometacina. Alternativa de primera línea en muchos centros",
  ["Ductus arterioso permeable en prematuros"],["IV"],
  {"pediatrico":"Prematuros: dosis 1: 10 mg/kg IV; dosis 2: 5 mg/kg a las 24h; dosis 3: 5 mg/kg a las 48h"},
  ["Amp 10 mg/2mL"],"N/A (uso neonatal)","u02","c02_11",
  familia="AINEs (uso cardiovascular neonatal)",
  ci=["Cardiopatía ductus-dependiente","Enterocolitis necrotizante","Hemorragia activa","IR significativa","Infección no tratada"],
  ea=["Oliguria","Elevación creatinina","Hemorragia GI","Hiperbilirrubinemia","Trombocitopenia"],
  ix=["Aminoglucósidos: reducir dosis","Corticoides: mayor riesgo perforación intestinal"],
  ce=["Menos nefrotóxico que indometacina (preferido en muchos centros)","Ecocardiograma de control post-tratamiento","Vigilar diuresis y función renal","No usar si bilirrubina elevada no tratada"],
  pp={"dilucion":"Diluir en SF a concentración adecuada","velocidadAdministracion":"IV en 15 minutos","estabilidad":"Usar dentro de 30 min"}),

M("","sildenafilo_neonatal","Sildenafilo (hipertensión pulmonar neonatal)","Sildenafilo",["Revatio neonatal"],
  "Inhibidor PDE5 para HTPP neonatal",
  "Inhibe PDE5 en vasculatura pulmonar neonatal. Aumenta GMPc y vasodilatación pulmonar selectiva. Alternativa a NO inhalado",
  ["Hipertensión pulmonar persistente del recién nacido (HTPP)","HTPP refractaria a NO inhalado"],["oral","IV"],
  {"pediatrico":"Neonatos oral: 0.5-2 mg/kg c/6-8h. IV: 0.1-0.5 mg/kg dosis de carga, luego 0.03-0.1 mg/kg/h"},
  ["Susp oral 10 mg/mL","Vial 10 mg/12.5mL"],"N/A (uso neonatal)","u02","c02_11",
  familia="Inhibidores de PDE5 (uso neonatal)",
  ci=["Hipotensión sistémica severa","Uso con nitratos"],
  ea=["Hipotensión sistémica","Taquicardia","Rubor","Retinopatía (uso prolongado en prematuros, controvertido)"],
  ix=["Nitratos: contraindicado","NO inhalado: efecto aditivo (monitorizar PA)","Inhibidores CYP3A4: aumentan niveles"],
  ce=["Monitorizar PA sistémica estrechamente","Alternativa cuando NO inhalado no disponible o insuficiente","Via oral preferida si tolera","Ecocardiograma para evaluar respuesta"],
  pp={"dilucion":"Diluir en SF o SG5%","velocidadAdministracion":"Carga en 30 min, luego infusión continua","estabilidad":"24h a TA"}),

M("","bosentan_congenita","Bosentán (cardiopatía congénita)","Bosentán",["Tracleer"],
  "Antagonista dual de receptores de endotelina ET-A y ET-B",
  "Bloquea receptores ET-A y ET-B, reduciendo vasoconstricción y remodelado vascular pulmonar. Aprobado para HAP asociada a cardiopatía congénita",
  ["HAP asociada a síndrome de Eisenmenger","HAP asociada a cardiopatía congénita corregida"],["oral"],
  {"adulto":"62.5 mg c/12h × 4 sem, luego 125 mg c/12h","pediatrico":"10-20 kg: 31.25 mg c/12h; 20-40 kg: 62.5 mg c/12h; >40 kg: dosis adulto"},
  ["Comp 62.5, 125 mg","Comp dispersable 32 mg (pediátrico)"],"Contraindicado","u02","c02_11",
  familia="Antagonistas de endotelina",emb="X",
  ci=["Embarazo","Elevación transaminasas >3x LSN","Uso con ciclosporina","Uso con gliburida"],
  ea=["Hepatotoxicidad (dosis-dependiente)","Edema","Cefalea","Anemia","Rubor","Teratogenicidad"],
  ix=["Ciclosporina: contraindicado (aumenta niveles de bosentán)","Sildenafilo: reduce niveles de sildenafilo","Inductores CYP3A4: reducen eficacia","Anticonceptivos hormonales: reduce eficacia"],
  ce=["Función hepática MENSUAL obligatoria","Anticoncepción doble obligatoria (teratógeno potente)","Programa REMS/monitorización","Hemoglobina cada 3 meses (anemia)","Formulación pediátrica dispersable disponible"]),

M("","iloprost_congenita","Iloprost inhalado","Iloprost",["Ventavis"],
  "Análogo de prostaciclina inhalado",
  "Análogo estable de prostaciclina administrado por nebulización. Vasodilatación pulmonar selectiva con mínimo efecto sistémico",
  ["HAP clase III-IV","HAP asociada a cardiopatía congénita","HAP refractaria a tratamiento oral"],["inhalatoria"],
  {"adulto":"2.5-5 mcg por inhalación, 6-9 veces/día (c/2-3h durante vigilia)",
   "pediatrico":">4 años: 2.5-5 mcg/inhalación, 6-8 veces/día"},
  ["Amp 10 mcg/mL, 20 mcg/mL para nebulización"],"Contraindicado","u02","c02_11",
  familia="Fármacos para hipertensión pulmonar",
  ci=["Condiciones con alto riesgo de sangrado","Hipotensión severa (PAS <85)","IC no controlada"],
  ea=["Tos","Cefalea","Rubor","Dolor mandibular","Hipotensión","Náuseas","Trismus","Insomnio"],
  ix=["Anticoagulantes: mayor riesgo sangrado","Antihipertensivos: hipotensión aditiva","Otros vasodilatadores pulmonares: efecto aditivo"],
  ce=["Requiere nebulizador específico (I-neb, Breelib)","Inhalación cada 2-3h en vigilia (6-9 veces/día)","Tiempo de inhalación: 4-10 min según dispositivo","No usar con nebulizadores convencionales"]),

# ── c02_05/c02_09 Antianginosos adicionales (+5) ──
M("","trimetazidina","Trimetazidina","Trimetazidina",["Vastarel","Idaptan"],
  "Modulador metabólico miocárdico",
  "Inhibe 3-cetoacil-CoA tiolasa (3-KAT), desviando metabolismo miocárdico de ácidos grasos a glucosa. Mejora eficiencia energética sin afectar hemodinámica",
  ["Angina estable (terapia añadida)","IC con angina"],["oral"],
  {"adulto":"35 mg c/12h con alimentos (formulación MR). Liberación inmediata: 20 mg c/8h"},
  ["Comp MR 35 mg","Comp 20 mg"],"Evitar durante lactancia","u02","c02_05",
  familia="Antianginosos metabólicos",
  ci=["Parkinsonismo","Temblor","Síndrome de piernas inquietas","Insuficiencia renal severa (ClCr <30)"],
  ea=["Trastornos GI","Mareo","Cefalea","Parkinsonismo (raro pero importante)","Temblor","Inestabilidad de la marcha"],
  ix=["Mínimas interacciones farmacocinéticas"],
  ce=["Vigilar aparición de temblor o trastornos de la marcha (suspender)","No es tratamiento de primera línea","Tomar con alimentos","Puede añadirse a betabloqueante o calcioantagonista"]),

M("","ivabradina_angina","Ivabradina (angina)","Ivabradina",["Procoralan"],
  "Inhibidor selectivo de corriente If para angina",
  "Bloquea canales If del nodo sinusal. Reduce FC en reposo y esfuerzo sin afectar contractilidad ni PA. Reduce demanda miocárdica de O2",
  ["Angina estable crónica con FC ≥70 lpm en ritmo sinusal, intolerante o con contraindicación a betabloqueantes"],["oral"],
  {"adulto":"Inicio 5 mg c/12h. Ajustar según FC: objetivo 50-60 lpm. Máx 7.5 mg c/12h"},
  ["Comp 5, 7.5 mg"],"Contraindicado","u02","c02_05",
  familia="Inhibidores de corriente If",
  ci=["FC basal <70 lpm","Bloqueo AV 2-3°","Síndrome del seno enfermo","IC aguda","Dependencia de marcapasos","Uso de inhibidores potentes CYP3A4"],
  ea=["Fosfenos (fenómenos luminosos)","Bradicardia","Cefalea","Mareo","Visión borrosa transitoria","FA"],
  ix=["Verapamilo/diltiazem: contraindicados (bradicardia severa)","Inhibidores CYP3A4 potentes: contraindicados","Fármacos que prolongan QT: precaución"],
  ce=["Solo si FC ≥70 lpm en reposo en ritmo sinusal","Fosfenos son benignos y transitorios","Tomar con alimentos","Puede combinarse con betabloqueante si FC sigue alta"]),

M("","isosorbide_mononitrato_det","Mononitrato de isosorbide retard","5-Mononitrato de isosorbide",["Imdur","Ismo retard"],
  "Nitrato de liberación prolongada para angina",
  "Metabolito activo del dinitrato de isosorbide. Liberación prolongada permite dosis única matutina con intervalo libre nocturno natural",
  ["Angina estable crónica (profilaxis)","Angina vasoespástica"],["oral"],
  {"adulto":"30-60 mg por la mañana. Puede aumentar a 120 mg/día. Máx 240 mg/día"},
  ["Comp LP 30, 60, 120 mg"],"Compatible con precaución","u02","c02_05",
  familia="Nitratos orgánicos",
  ci=["Hipotensión severa (PAS <90)","Uso de PDE5i","Miocardiopatía hipertrófica obstructiva","Hipovolemia","Anemia severa"],
  ea=["Cefalea (frecuente al inicio)","Hipotensión ortostática","Mareo","Taquicardia refleja","Rubor facial"],
  ix=["PDE5i (sildenafilo, tadalafilo): hipotensión severa potencialmente mortal","Antihipertensivos: hipotensión aditiva","Alcohol: potencia hipotensión"],
  ce=["Tomar por la mañana (intervalo libre nocturno con LP)","No triturar ni masticar","Cefalea mejora con uso continuado","Paracetamol para cefalea inicial"]),

M("","dipiridamol_cv","Dipiridamol","Dipiridamol",["Persantin"],
  "Vasodilatador coronario e inhibidor de agregación plaquetaria",
  "Inhibe fosfodiesterasa y captación de adenosina. Vasodilatación coronaria por aumento de adenosina extracelular. También inhibe agregación plaquetaria",
  ["Prevención de tromboembolismo con prótesis valvular mecánica","Prueba de esfuerzo farmacológica con imagen","Prevención de ACV (con aspirina)"],
  ["oral","IV"],
  {"adulto":"Oral: 75-100 mg c/6h. Prueba esfuerzo: 0.56 mg/kg IV en 4 min"},
  ["Comp 25, 50, 75 mg","Amp 10 mg/2mL"],"Compatible con precaución","u02","c02_05",
  familia="Vasodilatadores coronarios/Antiagregantes",
  ci=["Hipotensión severa","Angina inestable (test farmacológico)","Estenosis aórtica severa (test)"],
  ea=["Cefalea","Mareo","Hipotensión","Rubor","Diarrea","Náuseas","Angina (en test de esfuerzo)"],
  ix=["Adenosina: potencia efecto (reducir dosis adenosina)","Anticoagulantes: mayor sangrado","Teofilina: antagoniza efecto vasodilatador (antídoto en test)"],
  ce=["Tomar con el estómago vacío (1h antes comidas)","En test de esfuerzo: tener aminofilina disponible como antídoto","No sustituye a antiagregantes más potentes en SCA","Puede causar robo coronario en estenosis fijas"],
  pp={"dilucion":"Diluir en 50 mL SF","velocidadAdministracion":"0.56 mg/kg en 4 minutos (test)","estabilidad":"24h diluido"}),

M("","papaverina","Papaverina","Papaverina",["Papaverin"],
  "Vasodilatador directo no específico (alcaloide del opio)",
  "Inhibe fosfodiesterasa de forma no selectiva en músculo liso. Relajación directa de músculo liso vascular, cardíaco y otros",
  ["Vasoespasmo cerebral","Vasoespasmo arterial periférico","Espasmo de injerto coronario intraoperatorio","Isquemia mesentérica (complemento)"],
  ["IV","IM","intraarterial"],
  {"adulto":"IV/IM: 30-120 mg c/3-4h. Intraarterial (intraop): 30-60 mg directa"},
  ["Amp 30 mg/mL"],"Compatible con precaución","u02","c02_05",
  familia="Vasodilatadores directos",
  ci=["Bloqueo AV completo","Depresión miocárdica","Inyección IV rápida"],
  ea=["Hipotensión","Taquicardia","Rubor","Cefalea","Hepatotoxicidad (uso crónico)","Arritmias (IV rápido)"],
  ix=["Levodopa: reduce efecto antiparkinsoniano","Morfina: potencia efecto","Diazóxido: hipotensión severa"],
  ce=["Inyección IV debe ser LENTA (evitar arritmias)","Uso principal intraoperatorio en cirugía coronaria","Monitorizar PA y ECG durante IV","Hepatotoxicidad en uso prolongado oral"],
  pp={"dilucion":"Puede dar sin diluir o diluir en SF","velocidadAdministracion":"IV lento en 1-2 minutos","estabilidad":"Proteger de luz. No usar si hay precipitado"}),

# ── c02_06 Vasodilatadores periféricos (+5) ──
M("","cilostazol_cv","Cilostazol","Cilostazol",["Pletal"],
  "Inhibidor de PDE3 con efecto vasodilatador y antiagregante",
  "Inhibe fosfodiesterasa III plaquetaria y vascular. Aumenta AMPc: vasodilatación + inhibición agregación plaquetaria",
  ["Claudicación intermitente","Enfermedad arterial periférica"],["oral"],
  {"adulto":"100 mg c/12h con el estómago vacío (30 min antes o 2h después de comidas)"},
  ["Comp 50, 100 mg"],"Evitar durante lactancia","u02","c02_06",
  familia="Inhibidores de PDE3 (vascular)",
  ci=["IC de cualquier grado (clase I-IV)","Hemorragia activa","Predisposición al sangrado","Embarazo"],
  ea=["Cefalea","Diarrea","Heces blandas","Palpitaciones","Mareo","Edema periférico"],
  ix=["Inhibidores CYP3A4/CYP2C19: aumentan niveles","Antiagregantes/anticoagulantes: mayor sangrado","Omeprazol: aumenta niveles de cilostazol"],
  ce=["Contraindicado en IC (a diferencia de milrinona que es uso agudo)","Tomar en ayunas","Efecto terapéutico en 2-12 semanas","Caminar regularmente complementa efecto"]),

M("","buflomedil","Buflomedilo","Buflomedilo",["Lofton"],
  "Vasodilatador periférico con efecto hemorreológico",
  "Antagonista alfa-adrenérgico no selectivo con efecto inhibitorio sobre agregación plaquetaria y mejora de deformabilidad eritrocitaria",
  ["Claudicación intermitente","Enfermedad de Raynaud","Trastornos circulatorios periféricos"],["oral","IV"],
  {"adulto":"Oral: 150-300 mg c/12h con alimentos. IV: 200 mg en 250 mL SF en 2h"},
  ["Comp 150, 300 mg","Amp 50 mg/5mL"],"Evitar durante lactancia","u02","c02_06",
  familia="Vasodilatadores periféricos",
  ci=["Epilepsia","Hemorragia activa","IAM reciente","Insuficiencia renal severa"],
  ea=["Cefalea","Vértigo","Molestias GI","Erupción cutánea","Convulsiones (sobredosis)"],
  ix=["Anticoagulantes: mayor sangrado","Antihipertensivos: hipotensión aditiva"],
  ce=["Riesgo de convulsiones en sobredosis (margen terapéutico estrecho)","Ajustar en IR","Tomar con alimentos","Eficacia cuestionada en guías recientes"],
  pp={"dilucion":"Diluir en 250 mL SF","velocidadAdministracion":"Infusión en 2 horas","estabilidad":"24h diluido"}),

M("","naftidrofurilo","Naftidrofurilo","Naftidrofurilo (nafronilo)",["Praxilene"],
  "Vasodilatador periférico antagonista 5-HT2",
  "Bloquea receptores 5-HT2 vasculares, reduciendo vasoconstricción y agregación plaquetaria mediadas por serotonina. Mejora metabolismo aeróbico tisular",
  ["Claudicación intermitente","Enfermedad vascular periférica","Trastornos circulatorios cerebrales"],["oral"],
  {"adulto":"100-200 mg c/8h con alimentos"},
  ["Cáps 100, 200 mg"],"Evitar durante lactancia","u02","c02_06",
  familia="Vasodilatadores periféricos",
  ci=["Hipersensibilidad","Oxalato renal (riesgo de cristaluria con ácido oxálico)"],
  ea=["Molestias GI","Erupción cutánea","Cefalea","Hepatotoxicidad (raro)","Ácido oxálico como metabolito"],
  ix=["Mínimas interacciones clínicamente relevantes"],
  ce=["Uno de pocos vasodilatadores periféricos con evidencia en guías europeas","Tomar con alimentos","Hidratación adecuada (metabolito ácido oxálico)","Efecto en 3-6 meses de uso"]),

M("","pentoxifilina_cv","Pentoxifilina (vascular)","Pentoxifilina",["Trental"],
  "Hemorreológico inhibidor de PDE no selectivo",
  "Inhibe fosfodiesterasa, aumentando AMPc. Mejora deformabilidad eritrocitaria, reduce viscosidad sanguínea y agregación plaquetaria",
  ["Claudicación intermitente","Enfermedad vascular periférica","Úlceras venosas (adyuvante)"],["oral"],
  {"adulto":"400 mg c/8h con alimentos. Máx 1200 mg/día","ajusteRenal":"400 mg c/12h si ClCr <30"},
  ["Comp LP 400 mg"],"Compatible con precaución","u02","c02_06",
  familia="Hemorreológicos",
  ci=["Hemorragia activa","Hemorragia cerebral reciente","Hemorragia retiniana masiva"],
  ea=["Náuseas","Vómitos","Mareo","Cefalea","Rubor","Hemorragia (raro)","Agitación"],
  ix=["Anticoagulantes: mayor riesgo sangrado","Antihipertensivos: potencia efecto hipotensor","Teofilina: aumenta niveles"],
  ce=["Tomar con alimentos para reducir intolerancia GI","No triturar formulación LP","Efecto terapéutico en 2-8 semanas","Complementar con ejercicio programado"]),

M("","ginkgo_biloba","Extracto de Ginkgo biloba","Extracto estandarizado de Ginkgo biloba (EGb 761)",["Tanakan","Tebonin","Rokan"],
  "Fitoterapéutico vasodilatador con efecto antioxidante",
  "Contiene ginkgólidos y bilobalida. Inhibe PAF (factor activador plaquetario), efecto antioxidante y mejora microcirculación",
  ["Claudicación intermitente (adyuvante)","Vértigo de origen vascular","Deterioro cognitivo leve (evidencia limitada)"],["oral"],
  {"adulto":"120-240 mg/día en 2-3 tomas de extracto estandarizado EGb 761"},
  ["Comp 40, 80, 120 mg","Sol oral"],"Compatible con precaución","u02","c02_06",
  familia="Fitoterapéuticos vasculares",emb="C",
  ci=["Hipersensibilidad","Epilepsia (reduce umbral convulsivo)"],
  ea=["Cefalea","Molestias GI","Reacción alérgica cutánea","Mayor riesgo sangrado","Convulsiones (raro, altas dosis)"],
  ix=["Anticoagulantes/antiagregantes: mayor riesgo sangrado (inhibe PAF)","Anticonvulsivantes: puede reducir umbral convulsivo","Inhibidores CYP3A4/CYP2C9: interacciones posibles"],
  ce=["Evidencia limitada en guías oficiales","Suspender 2 semanas antes de cirugía","Usar solo extractos estandarizados (EGb 761)","Efecto terapéutico tarda 4-6 semanas"]),

# ── c02_07 Digitálicos (+2) ──
M("","digitoxina","Digitoxina","Digitoxina",["Digitaline"],
  "Glucósido cardíaco de acción prolongada",
  "Inhibe Na+/K+-ATPasa como digoxina. Metabolismo hepático (no renal): ventaja en IR. Vida media 5-7 días. Mayor unión a proteínas",
  ["IC con FEVI reducida (alternativa a digoxina en IR)","FA crónica (control de frecuencia)"],["oral"],
  {"adulto":"Digitalización: 0.6-1.2 mg repartidos en 24h. Mantenimiento: 0.05-0.1 mg/día"},
  ["Comp 0.1 mg"],"Evitar durante lactancia","u02","c02_07",
  familia="Glucósidos cardíacos",
  ci=["Taquicardia ventricular","Miocardiopatía hipertrófica obstructiva","WPW con FA","Hipopotasemia no corregida","Hipercalcemia"],
  ea=["Intoxicación digitálica (náuseas, vómitos, visión amarilla, arritmias)","Bradicardia","Bloqueo AV","Ginecomastia"],
  ix=["Amiodarona: aumenta niveles","Verapamilo: bradicardia aditiva","Diuréticos: hipopotasemia potencia toxicidad","Colestiramina: reduce absorción"],
  ce=["Ventaja sobre digoxina en insuficiencia renal (metabolismo hepático)","Monitorizar niveles plasmáticos (13-25 ng/mL)","Vigilar signos de intoxicación digitálica","Vida media muy larga: acumulación peligrosa"]),

M("","metildigoxina","Metildigoxina","Beta-metildigoxina",["Lanitop"],
  "Glucósido cardíaco de absorción mejorada",
  "Derivado metilado de digoxina con mayor absorción oral (>80% vs 60-80% digoxina). Convertido a digoxina in vivo. Inicio más rápido que digoxina oral",
  ["IC con FEVI reducida","FA crónica (control de frecuencia)"],["oral"],
  {"adulto":"0.1-0.3 mg/día. Equivalencia: 0.1 mg metildigoxina ≈ 0.125 mg digoxina",
   "geriatrico":"0.05-0.1 mg/día","ajusteRenal":"0.05 mg/día si ClCr <30"},
  ["Comp 0.1, 0.2 mg","Gotas 0.6 mg/mL"],"Evitar durante lactancia","u02","c02_07",
  familia="Glucósidos cardíacos",
  ci=["Taquicardia ventricular","WPW con FA","Miocardiopatía hipertrófica obstructiva","Hipopotasemia","Hipercalcemia"],
  ea=["Intoxicación digitálica","Bradicardia","Bloqueo AV","Náuseas","Anorexia","Visión amarilla"],
  ix=["Amiodarona, quinidina, verapamilo: aumentan niveles de digoxina","Diuréticos: hipopotasemia potencia toxicidad","Eritromicina: aumenta absorción"],
  ce=["Se convierte a digoxina in vivo","Monitorizar niveles de digoxina (0.5-0.9 ng/mL para IC)","Mejor absorción que digoxina (ventaja)","Mismas precauciones que digoxina"]),

# ── c02_10 Shock (+3) ──
M("vasopressor","angiotensina_ii_shock","Angiotensina II (shock refractario)","Angiotensina II",["Giapreza"],
  "Vasopresor peptídico para shock refractario",
  "Péptido endógeno sintético. Agonista directo de receptores AT1. Vasoconstricción independiente de catecolaminas. Estimula liberación de aldosterona y ADH",
  ["Shock vasodilatador refractario a catecolaminas en dosis altas","Shock séptico como vasopresor de rescate"],["IV"],
  {"adulto":"Inicio 20 ng/kg/min. Titular c/5 min para PAM ≥65 mmHg. Rango: 1.25-80 ng/kg/min. Máx 80 ng/kg/min"},
  ["Vial 2.5 mg/mL (1mL, 2mL)"],"No recomendado","u02","c02_10",
  ci=["Hipersensibilidad"],
  ea=["Tromboembolismo (13%)","Taquicardia","Fungemia","Delirium","Acidosis","Hiperglucemia","Trombocitopenia"],
  ix=["IECA/ARA-II: antagonizan efecto (suspender durante uso)","Mínimas interacciones farmacocinéticas"],
  ce=["Estudio ATHOS-3: eficaz en shock vasopléjico refractario","Profilaxis antitrombótica OBLIGATORIA durante uso","Monitorización hemodinámica invasiva","Destetar gradualmente cuando vasoplegia mejore"],
  pp={"dilucion":"Diluir en SF a 5000 o 10000 ng/mL","velocidadAdministracion":"Infusión continua, titular c/5 min","estabilidad":"24h a TA, 72h refrigerado"}),

M("vasopressor","milrinona_shock","Milrinona (soporte hemodinámico)","Milrinona",["Primacor"],
  "Inhibidor de PDE3 inotrópico/vasodilatador (inodilatador)",
  "Inhibe PDE3 cardíaca y vascular. Aumenta AMPc: efecto inotrópico positivo + vasodilatación pulmonar y sistémica. No requiere receptores beta",
  ["IC aguda descompensada (soporte transitorio)","Shock cardiogénico (como inodilatador)","Bajo gasto post-cirugía cardíaca","Hipertensión pulmonar aguda postoperatoria"],["IV"],
  {"adulto":"Carga: 50 mcg/kg en 10-15 min (omitir si hipotensión). Mantenimiento: 0.25-0.75 mcg/kg/min",
   "pediatrico":"Carga: 50 mcg/kg en 15 min. Mantenimiento: 0.25-0.75 mcg/kg/min",
   "ajusteRenal":"0.2-0.3 mcg/kg/min si ClCr <30"},
  ["Amp 1 mg/mL (10mL, 20mL)","Bolsa premezclada 200 mcg/mL"],"No recomendado","u02","c02_10",
  ci=["Estenosis aórtica/pulmonar severa","Hipovolemia no corregida","IAM agudo (relativa)"],
  ea=["Hipotensión","Taquicardia","Arritmias ventriculares","Cefalea","Trombocitopenia","Hipopotasemia"],
  ix=["Digoxina: aumenta efecto inotrópico (beneficioso en IC)","Diuréticos: monitorizar K+","Vasopresores: pueden ser necesarios para contrarrestar hipotensión"],
  ce=["Omitir bolo de carga si PA baja","No requiere receptores beta (ventaja en pacientes betabloqueados)","Monitorizar plaquetas (trombocitopenia)","Útil en HTP post-cirugía cardíaca (reduce poscarga VD)"],
  pp={"dilucion":"Diluir en SF o SG5% a 200 mcg/mL","velocidadAdministracion":"Carga en 10-15 min, luego infusión continua","estabilidad":"24h a TA. Compatible con la mayoría de soluciones"}),

M("vasopressor","fenilefrina_shock","Fenilefrina (shock)","Fenilefrina HCl",["Neosinefrina"],
  "Agonista alfa-1 adrenérgico puro",
  "Agonista selectivo alfa-1. Vasoconstricción periférica potente sin efecto beta. Causa bradicardia refleja. Aumenta poscarga",
  ["Hipotensión aguda perioperatoria","Shock vasodilatador con taquicardia","Soporte en shock séptico con FA rápida"],["IV"],
  {"adulto":"Bolo: 50-200 mcg c/1-5 min. Infusión: 0.1-0.5 mcg/kg/min. Máx 3 mcg/kg/min"},
  ["Amp 10 mg/mL (1mL)","Jeringa precargada 100 mcg/mL"],"No recomendado","u02","c02_10",
  ci=["Hipertensión severa","Taquicardia ventricular","Feocromocitoma"],
  ea=["Bradicardia refleja","HTA","Isquemia periférica","Necrosis por extravasación","Cefalea","Piloereccion"],
  ix=["IMAO: respuesta presora exagerada","Betabloqueantes: bradicardia severa","Oxitocina: potencia efecto presor","Antidepresivos tricíclicos: potencian efecto"],
  ce=["Único vasopresor que causa bradicardia refleja (útil en taquiarritmias)","Fentolamina SC como antídoto si extravasación","Preferir vía central si infusión prolongada","No indicado como primera línea en shock séptico"],
  pp={"dilucion":"Diluir en SF o SG5% a 100 mcg/mL","velocidadAdministracion":"Bolo lento o infusión continua","estabilidad":"24h diluido. No usar si hay cambio de color"}),
]

NEW_CHAPTERS = {
    "c02_11": {"id":"c02_11","nombre":"Cardiopatía Congénita y Fetal","unidadId":"u02","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U02 supplement ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch in NEW_CHAPTERS.values():
        add_chapter(cats, "u02", ch)
    for d in DRUGS:
        if d["capituloId"] not in NEW_CHAPTERS:
            add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
