#!/usr/bin/env python3
"""Add new drugs for U05 Sistema Digestivo."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c05_01 Antiulcerosos (+8) ──
M("ibp","famotidina_iv","Famotidina IV","Famotidina",["Pepcid IV"],"Antagonista H2 parenteral",
  "Bloquea competitivamente receptores H2 de histamina en célula parietal, reduciendo secreción ácida basal y estimulada",
  ["Úlcera duodenal activa","Síndrome de Zollinger-Ellison (IV)","Profilaxis de úlcera de estrés en UCI","Hemorragia digestiva alta (cuando IBP IV no disponible)"],["IV"],
  {"adulto":"20 mg IV c/12h. Profilaxis estrés: 20 mg IV c/12h. Infusión continua: 1.7 mg/h","pediatrico":"0.25 mg/kg IV c/12h (máx 40 mg/día)"},
  ["Amp 20 mg/2 mL"],"Compatible","u05","c05_01",
  familia="Antagonistas H2",
  ci=["Hipersensibilidad a antagonistas H2"],
  ea=["Cefalea","Mareo","Estreñimiento","Diarrea","Trombocitopenia (raro)"],
  ix=["Ketoconazol/itraconazol: reduce absorción por menor acidez","Atazanavir: reduce absorción"],
  ce=["Puede administrarse en bolo IV lento (2 min) o infusión (15-30 min)","Ajustar en insuficiencia renal (ClCr <50: reducir 50%)","Menos interacciones CYP que IBP","Alternativa a IBP si contraindicado"],
  pp={"reconstitucion":"Sin reconstitución necesaria","dilucion":"Diluir en 50-100 mL SF o SG5%","velocidadAdministracion":"Bolo IV lento en 2 min o infusión en 15-30 min","estabilidad":"48h a TA diluido"}),

M("ibp","sucralfato_susp","Sucralfato suspensión","Sucralfato",["Carafate","Urbal","Antepsin"],"Citoprotector gástrico",
  "Sal de aluminio de sacarosa sulfatada. En medio ácido polimeriza formando gel viscoso que se adhiere al cráter ulceroso, protegiéndolo de ácido, pepsina y sales biliares",
  ["Úlcera duodenal activa","Úlcera gástrica","Prevención de úlcera de estrés en UCI","Esofagitis por reflujo (coadyuvante)","Mucositis oral por radioterapia"],["oral"],
  {"adulto":"1 g c/6h (1h antes de comidas y al acostarse). Profilaxis estrés: 1 g c/6h por SNG","pediatrico":"40-80 mg/kg/día dividido c/6h"},
  ["Susp 1 g/10 mL","Comp 1 g"],"Compatible","u05","c05_01",
  familia="Citoprotectores gástricos",
  ci=["Hipersensibilidad","Insuficiencia renal grave (acumulación aluminio)"],
  ea=["Estreñimiento (más frecuente)","Boca seca","Náuseas","Bezoar gástrico (raro)","Acumulación de aluminio en IR"],
  ix=["Reduce absorción de: quinolonas, fenitoína, digoxina, levotiroxina, ketoconazol","Separar 2h de otros fármacos"],
  ce=["Administrar en AYUNAS (1h antes de comidas)","Separar 2h de otros medicamentos (reduce absorción)","Agitar bien la suspensión antes de usar","Vigilar estreñimiento","No usar a largo plazo en insuficiencia renal (aluminio)"]),

M("ibp","misoprostol_gastrico","Misoprostol (gastroprotector)","Misoprostol",["Cytotec","Misoprost"],"Análogo de prostaglandina E1",
  "Análogo sintético de PGE1. Reemplaza prostaglandinas endógenas inhibidas por AINEs, restaurando secreción de moco y bicarbonato, y reduciendo secreción ácida",
  ["Prevención de úlcera gástrica por AINEs","Úlcera gástrica refractaria a IBP"],["oral"],
  {"adulto":"200 mcg c/6h con alimentos. Profilaxis AINE: 200 mcg c/6-8h"},
  ["Comp 200 mcg"],"Contraindicado (oxitócico)","u05","c05_01",
  familia="Análogos de prostaglandinas",emb="X",
  ci=["Embarazo (⚠️ abortivo)","Mujeres en edad fértil sin anticoncepción","Hipersensibilidad"],
  ea=["Diarrea (dosis-dependiente, frecuente)","Dolor abdominal","Náuseas","Flatulencia","Sangrado uterino","Contracciones uterinas"],
  ix=["Antiácidos con magnesio: empeoran diarrea","Oxitocina: efecto aditivo uterotónico"],
  ce=["⚠️ CONTRAINDICADO EN EMBARAZO (efecto abortivo)","Exigir test de embarazo negativo antes de prescribir en mujeres fértiles","Tomar CON alimentos para reducir diarrea","Informar sobre diarrea frecuente al inicio (suele ceder)"]),

M("ibp","almagato","Almagato","Almagato",["Almax","Almagel"],"Antiácido de acción local",
  "Hidróxido de aluminio-magnesio modificado. Neutraliza HCl gástrico con efecto tampón sostenido. No causa efecto rebote significativo",
  ["Pirosis","Dispepsia funcional","Hiperacidez gástrica","Esofagitis leve por reflujo"],["oral"],
  {"adulto":"1-1.5 g (1-2 comp) c/6-8h o según síntomas, 1h después de comidas"},
  ["Comp masticable 500 mg","Susp 1 g/7.5 mL"],"Compatible","u05","c05_01",
  familia="Antiácidos",
  ci=["Hipersensibilidad","Insuficiencia renal grave","Hipofosfatemia","Obstrucción intestinal"],
  ea=["Estreñimiento","Diarrea","Hipofosfatemia (uso crónico)","Acumulación de aluminio en IR"],
  ix=["Reduce absorción de: tetraciclinas, quinolonas, hierro, levotiroxina","Separar 2h de otros fármacos","IBP: puede reducir eficacia si se toman juntos"],
  ce=["Tomar 1h después de comidas y al acostarse","Separar 2h de otros medicamentos","No usar de forma crónica sin supervisión","Masticar bien los comprimidos antes de tragar"]),

M("ibp","magaldrato","Magaldrato","Magaldrato",["Riopan","Dynagel"],"Antiácido hidroxicarbonato de aluminio y magnesio",
  "Complejo de hidróxido de aluminio y magnesio con estructura cristalina ordenada. Neutralización ácida gradual y efecto tampón prolongado a pH 3-5",
  ["Hiperacidez gástrica","Pirosis","Gastritis aguda","Dispepsia"],["oral"],
  {"adulto":"800-1600 mg c/6-8h entre comidas y al acostarse"},
  ["Susp 800 mg/10 mL","Comp masticable 800 mg"],"Compatible","u05","c05_01",
  familia="Antiácidos",
  ci=["Hipersensibilidad","Insuficiencia renal severa","Hipofosfatemia"],
  ea=["Diarrea (componente magnesio)","Estreñimiento (componente aluminio)","Hipofosfatemia","Acumulación de aluminio en IR"],
  ix=["Reduce absorción de múltiples fármacos","Separar 2h de tetraciclinas, quinolonas, hierro","Reduce absorción de ketoconazol"],
  ce=["Efecto tampón mantiene pH 3-5 (más fisiológico)","Agitar suspensión antes de usar","No usar a largo plazo sin indicación","Separar de otros fármacos orales"]),

M("ibp","hidroxido_aluminio_magnesio","Hidróxido de Al y Mg","Hidróxido de aluminio + Hidróxido de magnesio",["Maalox","Mylanta","Aludrox"],
  "Antiácido combinado",
  "Combinación de hidróxido de aluminio (astringente) e hidróxido de magnesio (laxante). El efecto opuesto sobre motilidad GI se equilibra mutuamente",
  ["Pirosis","Dispepsia","Reflujo gastroesofágico leve","Gastritis aguda"],["oral"],
  {"adulto":"10-20 mL suspensión o 1-2 comp c/6h, 1h después de comidas y al acostarse"},
  ["Susp oral","Comp masticable"],"Compatible","u05","c05_01",
  familia="Antiácidos",
  ci=["Hipersensibilidad","Insuficiencia renal grave","Apendicitis","Obstrucción intestinal"],
  ea=["Estreñimiento o diarrea","Hipofosfatemia (uso prolongado)","Hipermagnesemia en IR","Acumulación aluminio en IR"],
  ix=["Reduce absorción oral de múltiples fármacos (quinolonas, tetraciclinas, hierro, levotiroxina)","Separar al menos 2h"],
  ce=["Equilibrio Al/Mg minimiza alteración del tránsito","Tomar entre comidas y al acostarse","No usar crónicamente sin supervisión médica","Separar 2h de cualquier otro medicamento oral"]),

M("ibp","pirenzepina","Pirenzepina","Pirenzepina",["Gastrozepin","Tabe"],"Anticolinérgico selectivo M1",
  "Antagonista muscarínico selectivo M1. Inhibe la secreción ácida gástrica al bloquear receptores muscarínicos M1 en células parietales y ganglios intramurales, con menos efectos anticolinérgicos sistémicos",
  ["Úlcera gástrica","Úlcera duodenal","Hiperacidez gástrica"],["oral"],
  {"adulto":"50 mg c/12h antes de comidas. Casos graves: 50 mg c/8h"},
  ["Comp 25, 50 mg"],"Evitar durante lactancia","u05","c05_01",
  familia="Anticolinérgicos selectivos gástricos",
  ci=["Hipersensibilidad","Glaucoma de ángulo cerrado","Estenosis pilórica","Íleo paralítico"],
  ea=["Boca seca","Visión borrosa","Estreñimiento","Retención urinaria (raro)","Cefalea"],
  ix=["Anticolinérgicos: efectos aditivos","Ketoconazol: reducida absorción por menor acidez"],
  ce=["Menor efecto anticolinérgico sistémico que atropina","Tomar 30 min antes de comidas","Vigilar retención urinaria en pacientes prostáticos","Uso actual limitado (desplazado por IBP)"]),

M("ibp","tegoprazan","Tegoprazan","Tegoprazan",["K-Cab"],"Bloqueador ácido competitivo de potasio (P-CAB)",
  "Inhibidor competitivo reversible de la bomba H+/K+ ATPasa (P-CAB). A diferencia de los IBP, no requiere activación ácida, tiene inicio de acción más rápido y efecto nocturno superior",
  ["ERGE","Úlcera gástrica y duodenal","Erradicación de H. pylori (triple terapia)","Esofagitis erosiva"],["oral"],
  {"adulto":"ERGE: 50 mg/día. Úlcera: 50 mg/día x 4-8 sem. H. pylori: 50 mg c/12h + 2 ATB"},
  ["Comp 50 mg"],"No recomendado (datos insuficientes)","u05","c05_01",
  familia="P-CAB (bloqueadores ácidos competitivos de potasio)",
  ci=["Hipersensibilidad","Uso con rilpivirina"],
  ea=["Diarrea","Cefalea","Náuseas","Elevación de gastrina","Dolor abdominal"],
  ix=["Fármacos pH-dependientes: reduce absorción de ketoconazol, atazanavir","Rilpivirina: contraindicado"],
  ce=["Inicio de acción más rápido que IBP (no requiere activación ácida)","Mejor control nocturno de pH que IBP","Puede tomarse con o sin alimentos","Nueva generación de antisecretores (junto a vonoprazan)"]),

# ── c05_02 Antieméticos (+8) ──
M("antiemetico","fosaprepitant","Fosaprepitant","Fosaprepitant",["Emend IV","Ivemend"],"Antagonista NK1 parenteral",
  "Profármaco IV del aprepitant. Se convierte rápidamente en aprepitant (antagonista del receptor NK1 de sustancia P) en 30 min. Bloquea emesis retardada inducida por quimioterapia",
  ["Prevención de náuseas y vómitos por quimioterapia altamente emetógena (NVIQ)","NVIQ retardada (en régimen de 3 fármacos)"],["IV"],
  {"adulto":"150 mg IV dosis única día 1 de quimioterapia (reemplaza aprepitant oral 3 días)"},
  ["Vial 150 mg"],"No recomendado","u05","c05_02",
  ci=["Hipersensibilidad a aprepitant o fosaprepitant","Uso con pimozida o cisaprida"],
  ea=["Reacción en sitio de infusión","Fatiga","Cefalea","Hipo","Elevación ALT","Estreñimiento","Anafilaxia (raro)"],
  ix=["Inhibidor moderado CYP3A4: aumenta niveles de dexametasona (reducir dosis 50%)","Warfarina: puede disminuir INR","Anticonceptivos orales: puede reducir eficacia"],
  ce=["Administrar 30 min antes de quimioterapia","Dosis única reemplaza 3 días de aprepitant oral","Reducir dosis de dexametasona al 50% cuando se combina","Vigilar reacciones de hipersensibilidad durante infusión"],
  pp={"reconstitucion":"Reconstituir 150 mg con 5 mL SF","dilucion":"Diluir en 145 mL SF (total 150 mL)","velocidadAdministracion":"Infundir en 20-30 min","estabilidad":"24h a TA"}),

M("antiemetico","netupitant_palonos","Netupitant/Palonosetrón","Netupitant + Palonosetrón",["Akynzeo"],
  "Combinación fija antagonista NK1 + 5-HT3",
  "Combinación de netupitant (antagonista NK1 de larga duración, t½ 80h) y palonosetrón (antagonista 5-HT3 de larga duración, t½ 40h). Cubre emesis aguda y retardada en una sola toma",
  ["NVIQ altamente emetógena","NVIQ moderadamente emetógena"],["oral"],
  {"adulto":"1 cápsula (300 mg netupitant + 0.5 mg palonosetrón) VO 1h antes de quimioterapia"},
  ["Cáps 300/0.5 mg"],"No recomendado","u05","c05_02",
  ci=["Hipersensibilidad","Uso con pimozida","Embarazo"],emb="X",
  ea=["Cefalea","Estreñimiento","Fatiga","Dispepsia","Eritema"],
  ix=["Inhibidor moderado CYP3A4: precaución con sustratos","Dexametasona: reducir dosis","Benzodiazepinas (midazolam): puede aumentar niveles"],
  ce=["Una sola toma cubre emesis aguda + retardada","Reducir dexametasona al 50% en combinación","Tomar 1h antes de quimioterapia con o sin alimentos","Larga duración de acción (no repetir en ciclo)"]),

M("antiemetico","rolapitant","Rolapitant","Rolapitant",["Varubi"],"Antagonista NK1 de acción ultralarga",
  "Antagonista selectivo del receptor NK1 de sustancia P con vida media extremadamente larga (180h). No inhibe CYP3A4, ventaja frente a aprepitant",
  ["NVIQ retardada por quimioterapia altamente emetógena","NVIQ moderadamente emetógena (en combinación)"],["oral"],
  {"adulto":"180 mg VO dosis única 1-2h antes de quimioterapia (no repetir en 2 semanas)"},
  ["Comp 90 mg"],"No recomendado","u05","c05_02",
  ci=["Hipersensibilidad","Uso con sustratos de CYP2D6 de margen terapéutico estrecho (tioridazina, pimozida)"],emb="X",
  ea=["Mareo","Cefalea","Hipo","Dispepsia","Infección urinaria","Dolor abdominal"],
  ix=["Inhibidor de CYP2D6 (no de CYP3A4, ventaja)","No requiere ajuste de dexametasona (diferencia con aprepitant)","Sustratos CYP2D6: aumenta niveles"],
  ce=["Ventaja: NO inhibe CYP3A4 (menos interacciones que aprepitant)","No requiere reducción de dexametasona","Vida media 180h: una dosis por ciclo","No repetir dosis en menos de 2 semanas"]),

M("antiemetico","trimethobenzamida","Trimetobenzamida","Trimetobenzamida",["Tigan"],
  "Antiemético de acción central",
  "Antiemético que actúa en la zona quimiorreceptora gatillo (CTZ). Mecanismo no completamente elucidado pero distinto a fenotiazinas. Menor sedación que otros antieméticos centrales",
  ["Náuseas y vómitos postoperatorios","Náuseas por gastroenteritis"],["oral","IM"],
  {"adulto":"Oral: 300 mg c/6-8h. IM: 200 mg c/6-8h"},
  ["Cáps 300 mg","Amp 100 mg/mL"],"Evitar durante lactancia","u05","c05_02",
  ci=["Hipersensibilidad","Niños (asociado a síndrome de Reye)","Uso IV (solo IM)"],
  ea=["Somnolencia","Mareo","Cefalea","Visión borrosa","Diarrea","Reacción local IM"],
  ix=["Depresores del SNC: sedación aditiva","Ototóxicos: puede enmascarar síntomas"],
  ce=["Solo IM, NUNCA administrar IV","Menor efecto antiemético que ondansetrón","Inyección IM profunda en glúteo","Alternativa en pacientes que no toleran otros antieméticos"]),

M("antiemetico","dronabinol","Dronabinol","Dronabinol (delta-9-THC sintético)",["Marinol","Syndros"],
  "Cannabinoide sintético antiemético",
  "Delta-9-tetrahidrocannabinol sintético. Agonista de receptores cannabinoides CB1 en SNC, actuando sobre centro del vómito y CTZ. Efecto antiemético y orexígeno",
  ["NVIQ refractaria a antieméticos convencionales","Anorexia asociada a SIDA con pérdida de peso"],["oral"],
  {"adulto":"NVIQ: 5 mg/m² 1-3h antes de QT, luego c/2-4h (máx 4-6 dosis/día). Anorexia-SIDA: 2.5 mg c/12h antes de comidas"},
  ["Cáps 2.5, 5, 10 mg","Sol oral 5 mg/mL"],"Evitar durante lactancia","u05","c05_02",
  ci=["Hipersensibilidad a cannabinoides","Alergia al sésamo (cápsulas)","Trastorno psiquiátrico severo no controlado"],
  ea=["Euforia/disforia","Somnolencia","Mareo","Paranoia","Taquicardia","Hipotensión ortostática","Desorientación","Dependencia psicológica"],
  ix=["Depresores del SNC: sedación aditiva","Simpaticomiméticos: taquicardia aditiva","Anticolinérgicos: efectos aditivos"],
  ce=["⚠️ Sustancia controlada (Schedule III)","Vigilar efectos psicoactivos (euforia, paranoia)","Iniciar con dosis bajas en ancianos","Precaución: puede alterar capacidad de conducción","Reservar para NVIQ refractaria a ondansetrón/aprepitant"]),

M("antiemetico","nabilona","Nabilona","Nabilona",["Cesamet"],"Cannabinoide sintético",
  "Cannabinoide sintético análogo del THC con mayor potencia antiemética y menor efecto psicoactivo que dronabinol. Agonista CB1/CB2",
  ["NVIQ refractaria a antieméticos convencionales"],["oral"],
  {"adulto":"1-2 mg c/12h. Iniciar 1-3h antes de QT. Máx 6 mg/día dividido en 3 tomas"},
  ["Cáps 1 mg"],"Contraindicado","u05","c05_02",
  ci=["Hipersensibilidad a cannabinoides","Antecedente de psicosis"],
  ea=["Somnolencia (muy frecuente)","Mareo","Euforia","Boca seca","Ataxia","Alteraciones visuales","Concentración reducida"],
  ix=["Depresores del SNC: potenciación marcada","Anticolinérgicos: efectos aditivos","Opioides: sedación aditiva"],
  ce=["Reservar para emesis refractaria a primera y segunda línea","Mejor perfil que dronabinol en algunos pacientes","Iniciar dosis baja y titular","Advertir sobre efectos psicoactivos y somnolencia"]),

M("antiemetico","prometazina_antiemetica","Prometazina (antiemética)","Prometazina",["Fenergan","Promethegan"],
  "Fenotiazina con acción antiemética",
  "Fenotiazina con potente efecto antihistamínico H1 y anticolinérgico. Actúa en CTZ y centro del vómito. También tiene actividad antihistamínica, sedante y anticolinérgica",
  ["Náuseas y vómitos postoperatorios","Cinetosis","Náuseas del embarazo (off-label, con precaución)","Premedicación anestésica"],["oral","IM","IV","rectal"],
  {"adulto":"12.5-25 mg c/4-6h VO/IM/IV/rectal. Cinetosis: 25 mg 30 min antes del viaje","pediatrico":">2 años: 0.25-1 mg/kg c/4-6h"},
  ["Comp 25 mg","Amp 25 mg/mL","Supositorio 25 mg"],"Evitar durante lactancia","u05","c05_02",
  ci=["Niños <2 años (depresión respiratoria fatal)","Coma","Depresión severa del SNC","Inyección intraarterial o SC (necrosis)"],
  ea=["Sedación marcada","Boca seca","Visión borrosa","Retención urinaria","Hipotensión","⚠️ Necrosis tisular si extravasación IV"],
  ix=["Depresores del SNC: sedación profunda","Anticolinérgicos: efectos aditivos","IMAO: potenciación de efectos"],
  ce=["⚠️ NUNCA en <2 años (depresión respiratoria fatal)","IV: diluir y administrar lentamente (riesgo necrosis)","Preferir vía IM sobre IV","Vigilar sedación excesiva en ancianos","Si IV: concentración máx 25 mg/mL, infundir lento"],
  pp={"reconstitucion":"No requiere","dilucion":"Diluir hasta 25 mg en 10-20 mL SF para IV","velocidadAdministracion":"No más de 25 mg/min IV","estabilidad":"Proteger de la luz"}),

M("antiemetico","ciclizina","Ciclizina","Ciclizina",["Marezine","Valoid"],"Antihistamínico antiemético piperazínico",
  "Antihistamínico H1 de primera generación del grupo piperazina. Actúa en centro del vómito y sistema vestibular. Eficaz para cinetosis y vértigo",
  ["Cinetosis","Náuseas y vómitos postoperatorios","Vértigo","Náuseas por opioides"],["oral","IM","IV"],
  {"adulto":"50 mg c/8h VO/IM/IV. Cinetosis: 50 mg 30 min antes del viaje","pediatrico":"6-12 años: 25 mg c/8h"},
  ["Comp 50 mg","Amp 50 mg/mL"],"Evitar durante lactancia","u05","c05_02",
  ci=["Hipersensibilidad","Porfiria","Glaucoma de ángulo cerrado","Retención urinaria"],
  ea=["Somnolencia","Boca seca","Visión borrosa","Retención urinaria","Estreñimiento"],
  ix=["Depresores del SNC: sedación aditiva","Anticolinérgicos: efectos aditivos","Opioides: reduce náuseas pero suma sedación"],
  ce=["Útil para náuseas por opioides en cuidados paliativos","No mezclar con SF para IV (precipita): usar agua para inyección","Vigilar retención urinaria en prostáticos","Menos efectivo para NVIQ que ondansetrón"]),

# ── c05_03 Otros Digestivos (+6 biológicos EII) ──
M("inmunosupresor","infliximab_eii","Infliximab (EII)","Infliximab",["Remicade","Remsima","Inflectra"],
  "Anti-TNFα quimérico para EII",
  "Anticuerpo monoclonal quimérico IgG1 anti-TNFα. Se une al TNFα soluble y transmembrana, neutralizando inflamación y promoviendo apoptosis de células T activadas en mucosa intestinal",
  ["Enfermedad de Crohn moderada-severa","Colitis ulcerosa moderada-severa","Enfermedad de Crohn fistulizante","EII refractaria a corticoides e inmunosupresores"],["IV"],
  {"adulto":"Inducción: 5 mg/kg IV semanas 0, 2 y 6. Mantenimiento: 5 mg/kg IV c/8 semanas. Puede escalar a 10 mg/kg","pediatrico":">6 años: mismo esquema que adulto"},
  ["Vial 100 mg"],"Evitar durante lactancia","u05","c05_03",
  ce=["Cribado de TB obligatorio antes de iniciar (Mantoux/IGRA + Rx tórax)","Premedicación: paracetamol + antihistamínico + hidrocortisona IV","Vigilar reacciones infusionales (urticaria, disnea, hipotensión)","Monitorizar niveles séricos si pérdida de respuesta","Suspender ante infección grave"],
  pp={"reconstitucion":"Reconstituir con 10 mL agua estéril por vial","dilucion":"Diluir en 250 mL SF. Usar set con filtro de 1.2 micras","velocidadAdministracion":"Infundir en mínimo 2h (primera dosis). Puede acortarse a 1h si buena tolerancia","estabilidad":"24h refrigerado una vez reconstituido"}),

M("inmunosupresor","adalimumab_eii","Adalimumab (EII)","Adalimumab",["Humira","Amgevita","Hyrimoz"],
  "Anti-TNFα humano para EII",
  "Anticuerpo monoclonal completamente humano anti-TNFα. Menor inmunogenicidad que infliximab al ser 100% humano. Administración subcutánea permite uso domiciliario",
  ["Enfermedad de Crohn moderada-severa","Colitis ulcerosa moderada-severa","EII tras fracaso de infliximab (switch anti-TNF)"],["SC"],
  {"adulto":"Inducción: 160 mg SC sem 0 → 80 mg sem 2 → 40 mg c/2 semanas desde sem 4","pediatrico":">6 años y >40 kg: esquema adulto. <40 kg: ajustar según peso"},
  ["Jeringa/pluma precargada 40 mg/0.4-0.8 mL"],"Evitar durante lactancia","u05","c05_03",
  ce=["Cribado TB obligatorio antes de iniciar","Autoinyección SC: educar al paciente sobre técnica","Rotar sitios de inyección (abdomen, muslo)","Conservar refrigerado (2-8°C), sacar 30 min antes de inyectar","Menor riesgo de reacciones infusionales que infliximab (SC vs IV)"]),

M("inmunosupresor","ustekinumab_eii","Ustekinumab (EII)","Ustekinumab",["Stelara"],
  "Anti-IL-12/IL-23 para EII",
  "Anticuerpo monoclonal humano anti-subunidad p40 compartida por IL-12 e IL-23. Mecanismo distinto a anti-TNF. Eficaz en pacientes refractarios a anti-TNF",
  ["Enfermedad de Crohn moderada-severa (incluido fracaso anti-TNF)","Colitis ulcerosa moderada-severa"],["IV","SC"],
  {"adulto":"Inducción: dosis única IV según peso (≤55 kg: 260 mg; 56-85 kg: 390 mg; >85 kg: 520 mg). Mantenimiento: 90 mg SC c/8-12 semanas"},
  ["Vial IV 130 mg","Jeringa SC 90 mg"],"Evitar durante lactancia","u05","c05_03",
  ce=["Inducción IV → mantenimiento SC (transición)","Eficaz tras fracaso de anti-TNF (mecanismo diferente)","Cribado TB antes de iniciar","Perfil de seguridad favorable vs anti-TNF","Menos monitorización de niveles necesaria"],
  pp={"reconstitucion":"No requiere reconstituir","dilucion":"Diluir dosis calculada en 250 mL SF","velocidadAdministracion":"Infundir IV en mínimo 1h (solo dosis de inducción)","estabilidad":"4h a TA una vez diluido"}),

M("inmunosupresor","tofacitinib_eii","Tofacitinib (EII)","Tofacitinib",["Xeljanz"],
  "Inhibidor JAK oral para colitis ulcerosa",
  "Inhibidor de Janus quinasa (JAK1 y JAK3). Primer tratamiento oral de molécula pequeña para colitis ulcerosa moderada-severa. Interrumpe señalización de múltiples citoquinas inflamatorias",
  ["Colitis ulcerosa moderada-severa refractaria a biológicos o inmunosupresores"],["oral"],
  {"adulto":"Inducción: 10 mg c/12h x 8 semanas (extender a 16 sem si necesario). Mantenimiento: 5 mg c/12h"},
  ["Comp 5, 10 mg"],"Contraindicado","u05","c05_03",emb="X",
  ci=["Embarazo","Infección activa grave","Linfopenia <500","Neutropenia <1000","TB activa","Neoplasia activa (excepto CCNM)"],
  ea=["Infecciones (herpes zóster frecuente)","Cefalea","Diarrea","Nasofaringitis","Elevación de colesterol","Linfopenia","⚠️ Riesgo tromboembólico (dosis altas)","Neoplasia (datos a largo plazo)"],
  ix=["Inmunosupresores potentes: no combinar con azatioprina o ciclosporina","Inhibidores CYP3A4 potentes: reducir dosis","Inductores CYP: pueden reducir eficacia"],
  ce=["Ventaja: vía oral (vs biológicos parenterales)","⚠️ Vacunar contra herpes zóster ANTES de iniciar","No combinar con biológicos ni inmunosupresores potentes","Hemograma, lípidos y función hepática cada 4-8 semanas inicial","Dosis de mantenimiento: la menor eficaz (riesgo cardiovascular)"]),

M("inmunosupresor","ozanimod","Ozanimod","Ozanimod",["Zeposia"],
  "Modulador de receptor S1P para colitis ulcerosa",
  "Agonista selectivo de receptores de esfingosina-1-fosfato (S1P1 y S1P5). Retiene linfocitos en ganglios linfáticos, reduciendo infiltración inflamatoria intestinal. Mecanismo distinto a anti-TNF y JAK",
  ["Colitis ulcerosa moderada-severa"],["oral"],
  {"adulto":"Titulación: día 1-4: 0.23 mg/día → día 5-7: 0.46 mg/día → desde día 8: 0.92 mg/día (dosis de mantenimiento)"},
  ["Cáps 0.23, 0.46, 0.92 mg"],"Contraindicado","u05","c05_03",emb="X",
  ci=["IAM, ACV o AIT reciente (<6 meses)","IC clase III-IV","Bloqueo AV 2°-3° sin marcapasos","Bradicardia severa sintomática"],
  ea=["Bradicardia transitoria (primera dosis)","Elevación ALT/AST","Infecciones respiratorias","Cefalea","HTA","Edema macular (raro)","Linfopenia"],
  ix=["Betabloqueantes: riesgo bradicardia en inicio","Antiarrítmicos clase I/III: contraindicado","IMAO: posible crisis hipertensiva","Vacunas vivas: contraindicadas"],
  ce=["Titulación obligatoria (riesgo bradicardia primera dosis)","ECG y TA antes de primera dosis","Revisión oftalmológica basal (riesgo edema macular)","Hemograma cada 3 meses (linfopenia esperada)","No requiere monitorización cardiaca en inicio (a diferencia de fingolimod)"]),

M("inmunosupresor","filgotinib","Filgotinib","Filgotinib",["Jyseleca"],
  "Inhibidor selectivo JAK1 para colitis ulcerosa",
  "Inhibidor altamente selectivo de JAK1 (30 veces más selectivo para JAK1 sobre JAK2). Mayor selectividad teórica que tofacitinib, potencialmente mejor perfil de seguridad",
  ["Colitis ulcerosa moderada-severa refractaria a tratamiento convencional o biológicos"],["oral"],
  {"adulto":"200 mg/día. En >65 años o factores de riesgo: considerar 100 mg/día","ajusteRenal":"ClCr 15-60: 100 mg/día. ClCr <15: no recomendado"},
  ["Comp 100, 200 mg"],"Contraindicado","u05","c05_03",emb="X",
  ci=["Embarazo","Infección activa grave","Linfopenia <500","TB activa","Insuficiencia hepática grave"],
  ea=["Náuseas","Infección respiratoria alta","Cefalea","Elevación CPK","Colesterol elevado","Herpes zóster"],
  ix=["Inhibidores CYP3A4/P-gp potentes: precaución","No combinar con inmunosupresores biológicos","Probenecid: aumenta exposición"],
  ce=["Mayor selectividad JAK1 vs tofacitinib (teóricamente más seguro)","Una toma diaria (ventaja sobre tofacitinib c/12h)","Hemograma y lípidos basales y periódicos","Vacunación contra HZ antes de iniciar","Ajustar dosis en insuficiencia renal moderada"]),

# ── c05_04 Hepatoprotectores (+6) ──
M("ibp","obeticholic_acid","Ácido obeticólico","Ácido obeticólico",["Ocaliva"],
  "Agonista FXR para colangitis biliar primaria",
  "Agonista del receptor farnesoide X (FXR), 100 veces más potente que el ácido quenodesoxicólico endógeno. Reduce síntesis de ácidos biliares, inflamación portal y fibrosis hepática",
  ["Colangitis biliar primaria (CBP) con respuesta inadecuada a ácido ursodeoxicólico","CBP en intolerantes a AUDC"],["oral"],
  {"adulto":"Inicio: 5 mg/día. Si respuesta inadecuada a 3 meses: aumentar a 10 mg/día","ajusteHepatico":"Child-Pugh B/C: 5 mg/semana, máx 10 mg 2 veces/semana"},
  ["Comp 5, 10 mg"],"Contraindicado","u05","c05_04",
  familia="Agonistas FXR",emb="X",
  ci=["Obstrucción biliar completa","Cirrosis descompensada (Child-Pugh B/C sin ajuste)","Embarazo"],
  ea=["⚠️ Prurito severo (dosis-dependiente, hasta 70%)","Fatiga","Dolor abdominal","Artralgias","Elevación de colesterol LDL","⚠️ Descompensación hepática en cirróticos (sobredosis)"],
  ix=["Warfarina: monitorizar INR","Colestiramina: separar 4-6h (reduce absorción)","Ciclosporina: monitorizar niveles"],
  ce=["Ajuste de dosis obligatorio en cirrosis (riesgo descompensación)","Prurito severo: puede requerir colestiramina o naltrexona","Función hepática cada 3 meses los primeros 12 meses","LDL puede aumentar (evaluar estatinas)","Tratamiento crónico: no curación sino control"]),

M("ibp","elafibranor","Elafibranor","Elafibranor",["Iqirvo"],
  "Agonista dual PPARα/δ para colangitis biliar primaria",
  "Agonista dual de receptores activados por proliferadores de peroxisomas alfa y delta (PPARα/δ). Reduce síntesis de ácidos biliares, inflamación y fibrosis hepática por mecanismo diferente a FXR",
  ["Colangitis biliar primaria con respuesta inadecuada a AUDC"],["oral"],
  {"adulto":"80 mg/día con alimentos"},
  ["Comp 80 mg"],"Contraindicado","u05","c05_04",
  familia="Agonistas PPAR",emb="X",
  ci=["Cirrosis descompensada","Embarazo","Hipersensibilidad"],
  ea=["Dolor abdominal","Diarrea","Náuseas","Mialgias","Elevación CPK","Elevación transaminasas transitoria"],
  ix=["Estatinas: vigilar CPK (miopatía aditiva)","Ciclosporina: aumenta exposición a elafibranor","Warfarina: monitorizar INR"],
  ce=["Nuevo mecanismo alternativo a OCA para CBP","Tomar con alimentos (mejora absorción)","Menos prurito que ácido obeticólico (ventaja)","Monitorizar función hepática y CPK","Aprobación reciente: seguimiento de seguridad a largo plazo en curso"]),

M("ibp","seladelpar","Seladelpar","Seladelpar",["Livdelzi"],
  "Agonista selectivo PPARδ para colangitis biliar primaria",
  "Agonista altamente selectivo de PPARδ. Modula metabolismo de ácidos biliares y reduce inflamación hepática. Selectividad delta evita efectos PPARα (toxicidad muscular) y PPARγ (retención líquidos)",
  ["Colangitis biliar primaria con respuesta inadecuada a AUDC"],["oral"],
  {"adulto":"10 mg/día"},
  ["Cáps 5, 10 mg"],"Contraindicado","u05","c05_04",
  familia="Agonistas PPAR selectivos",emb="X",
  ci=["Cirrosis descompensada","Embarazo","Hipersensibilidad"],
  ea=["Dolor abdominal","Náuseas","Cefalea","Prurito (menos que OCA)"],
  ix=["Ciclosporina: no coadministrar","Estatinas: monitorizar miopatía"],
  ce=["Selectividad PPARδ: menos efectos adversos musculares y edema","Prurito significativamente menor que ácido obeticólico","Monitorizar función hepática periódicamente","Aprobación 2024: fármaco novedoso en CBP"]),

M("ibp","acido_ursodeoxicolico_colestasis","AUDC (colestasis)","Ácido ursodeoxicólico",["Ursofalk","Ursodiol","Ursochol"],
  "Ácido biliar terciario hepatoprotector",
  "Ácido biliar hidrofílico. Desplaza ácidos biliares tóxicos de la circulación enterohepática, estabiliza membranas hepatocitarias, tiene efecto colerético y reduce apoptosis de colangiocitos",
  ["Colangitis biliar primaria","Colangitis esclerosante (controversial)","Colestasis intrahepática del embarazo","Disolución de cálculos biliares de colesterol","Colestasis por nutrición parenteral"],["oral"],
  {"adulto":"CBP: 13-15 mg/kg/día dividido en 2-4 tomas. Cálculos: 8-10 mg/kg/día. Colestasis embarazo: 10-15 mg/kg/día","pediatrico":"10-20 mg/kg/día"},
  ["Cáps 250, 300 mg","Comp 500 mg","Susp 250 mg/5 mL"],"Compatible con precaución","u05","c05_04",
  familia="Ácidos biliares",emb="B",
  ci=["Cálculos biliares calcificados","Obstrucción biliar completa","Colecistitis aguda","Colangitis aguda"],
  ea=["Diarrea (frecuente al inicio)","Dolor abdominal","Prurito (transitorio al inicio)","Calcificación de cálculos (raro)","Elevación transitoria de transaminasas"],
  ix=["Colestiramina: reduce absorción de AUDC (separar 2-4h)","Antiácidos con aluminio: reducen absorción","Ciclosporina: puede aumentar absorción de ciclosporina"],
  ce=["Fármaco de primera línea en CBP","Tomar con alimentos para mejorar absorción","Separar de colestiramina mínimo 2h (idealmente 4h)","Tratamiento crónico en CBP: no suspender","Monitorizar función hepática cada 3-6 meses"]),

M("ibp","colestiramina_prurito","Colestiramina (prurito colestásico)","Colestiramina",["Questran","Efensol"],
  "Resina de intercambio iónico para prurito colestásico",
  "Resina de intercambio aniónico que secuestra ácidos biliares en intestino, impidiendo su reabsorción. Reduce el pool de ácidos biliares circulantes responsables del prurito colestásico",
  ["Prurito por colestasis","Prurito en colangitis biliar primaria","Diarrea por malabsorción de ácidos biliares"],["oral"],
  {"adulto":"4 g c/12-24h (iniciar con dosis baja). Máx: 16 g/día dividido en 2-4 tomas"},
  ["Sobres 4 g polvo"],"Compatible","u05","c05_04",
  familia="Resinas secuestradoras de ácidos biliares",emb="C",
  ci=["Obstrucción biliar completa","Hipersensibilidad","Fenilcetonuria (contiene aspartamo algunos preparados)"],
  ea=["Estreñimiento (frecuente)","Meteorismo","Náuseas","Esteatorrea","Déficit vitaminas liposolubles (uso crónico: A, D, E, K)","Sabor desagradable"],
  ix=["Reduce absorción de MÚLTIPLES fármacos (AUDC, levotiroxina, digoxina, warfarina, anticonceptivos)","Administrar otros fármacos 1h antes o 4-6h después"],
  ce=["Primera línea para prurito colestásico","Tomar otros medicamentos 1h ANTES o 4-6h DESPUÉS","Mezclar polvo en agua o jugo (no seco)","Suplementar vitaminas liposolubles en uso crónico","Sabor desagradable: mezclar con jugo de fruta mejora tolerancia"]),

M("ibp","naltrexona_prurito","Naltrexona (prurito colestásico)","Naltrexona",["Revia","Nalorex"],
  "Antagonista opioide para prurito colestásico refractario",
  "Antagonista de receptores opioides mu. El prurito colestásico se relaciona con aumento del tono opioide endógeno. Naltrexona revierte este prurito mediado por opioides endógenos",
  ["Prurito colestásico refractario a colestiramina","Prurito en colangitis biliar primaria refractario"],["oral"],
  {"adulto":"Inicio: 12.5 mg/día x 3 días → 25 mg/día x 3 días → 50 mg/día. Titular lentamente"},
  ["Comp 50 mg"],"Evitar durante lactancia","u05","c05_04",
  familia="Antagonistas opioides",emb="C",
  ci=["Uso actual de opioides (precipita abstinencia)","Hepatitis aguda","Insuficiencia hepática grave","Hipersensibilidad"],
  ea=["Síndrome de abstinencia opioide-like al inicio","Náuseas","Dolor abdominal","Insomnio","Cefalea","Hepatotoxicidad (dosis altas)"],
  ix=["Opioides: antagonismo completo (precipita abstinencia)","Tioridazina: no combinar"],
  ce=["Segunda-tercera línea para prurito colestásico (tras colestiramina, rifampicina)","Iniciar a dosis MUY bajas (riesgo reacción opioide-like)","Verificar que paciente NO use opioides","Monitorizar función hepática","Titular dosis lentamente durante 1-2 semanas"]),

# ── c05_05 Laxantes (+5) ──
M("ibp","lactitol","Lactitol","Lactitol",["Emportal","Importal"],"Laxante osmótico disacárido",
  "Disacárido sintético no absorbible. Fermentado por bacterias colónicas a ácidos orgánicos de cadena corta, produciendo efecto osmótico y acidificación del contenido colónico similar a lactulosa",
  ["Estreñimiento crónico","Encefalopatía hepática (alternativa a lactulosa)"],["oral"],
  {"adulto":"Estreñimiento: 10-20 g/día en dosis única. Encefalopatía hepática: 30-45 g/día dividido en 3 tomas","pediatrico":"1-6 años: 5-10 g/día. 6-12 años: 10-15 g/día"},
  ["Sobres 10 g polvo"],"Compatible","u05","c05_05",
  familia="Laxantes osmóticos",emb="B",
  ci=["Obstrucción intestinal","Galactosemia","Intolerancia hereditaria a galactosa"],
  ea=["Flatulencia (frecuente al inicio)","Dolor abdominal","Diarrea (sobredosis)","Borborigmos"],
  ix=["Neomicina: reduce fermentación bacteriana (menor eficacia)","Antiácidos: pueden reducir acidificación colónica"],
  ce=["Alternativa a lactulosa con mejor sabor y tolerancia GI","Disolver en agua o jugo antes de tomar","Efecto tarda 24-48h en aparecer","Ajustar dosis hasta lograr 2-3 deposiciones blandas/día en encefalopatía","Menos flatulencia que lactulosa en algunos pacientes"]),

M("ibp","macrogol_electrolitos","Macrogol con electrolitos","Macrogol (PEG) + electrolitos",["Movicol","Molaxole"],
  "Laxante osmótico isoosmótico",
  "Polietilenglicol de alto peso molecular con electrolitos. Actúa por efecto osmótico reteniendo agua en luz intestinal. Los electrolitos previenen intercambio iónico con la mucosa",
  ["Estreñimiento crónico","Impactación fecal (dosis altas)","Preparación intestinal (formulación específica)"],["oral"],
  {"adulto":"Estreñimiento: 1-3 sobres/día. Impactación fecal: 8 sobres en 1L agua en 6h","pediatrico":"<1 año: 0.5-1 sobre/día. 1-6 años: 1 sobre/día. 6-12 años: 2 sobres/día"},
  ["Sobres 13.125 g (equivalente a ~6.9 g macrogol)"],"Compatible","u05","c05_05",
  familia="Laxantes osmóticos",emb="B",
  ci=["Obstrucción intestinal","Perforación GI","Íleo paralítico","Enfermedad inflamatoria intestinal severa con megacolon"],
  ea=["Dolor abdominal","Distensión","Borborigmos","Náuseas","Diarrea (sobredosis)"],
  ix=["Mínimas interacciones sistémicas (no se absorbe)","Otros laxantes: efecto aditivo"],
  ce=["Disolver sobre en 125 mL de agua","No induce tolerancia ni dependencia (seguro a largo plazo)","No altera electrolitos (contiene electrolitos compensadores)","Para impactación fecal: 8 sobres en 1L en 6h","Efecto esperado en 24-48h"]),

M("ibp","metilcelulosa","Metilcelulosa","Metilcelulosa",["Citrucel","Muciplazma"],"Laxante formador de masa",
  "Polisacárido semisintético derivado de celulosa. Absorbe agua en intestino formando gel voluminoso que estimula peristaltismo por distensión. No fermentable (menos gas que psyllium)",
  ["Estreñimiento crónico","Síndrome de intestino irritable (regularización del tránsito)","Diverticulosis (mantenimiento)"],["oral"],
  {"adulto":"2 g c/8-12h con abundante agua (mín 250 mL por dosis)"},
  ["Comp 500 mg","Polvo oral"],"Compatible","u05","c05_05",
  familia="Laxantes formadores de masa",emb="B",
  ci=["Obstrucción intestinal","Disfagia severa","Impactación fecal establecida","Estenosis esofágica"],
  ea=["Distensión abdominal","Flatulencia","Obstrucción esofágica si no se toma con suficiente agua"],
  ix=["Mínimas interacciones sistémicas","Puede retrasar absorción de otros fármacos orales"],
  ce=["Tomar SIEMPRE con abundante agua (mínimo 250 mL)","Menos flatulencia que psyllium (ventaja)","No usar en impactación establecida","Efecto tarda 12-72h","No administrar acostado (riesgo aspiración)"]),

M("ibp","docusato","Docusato sódico","Docusato sódico",["Colace","Dulcoease"],"Laxante emoliente (surfactante)",
  "Surfactante aniónico que reduce tensión superficial en interfaz agua-grasa en contenido fecal. Facilita penetración de agua y grasa en masa fecal, ablandándola. Mínimo efecto estimulante",
  ["Estreñimiento por heces duras","Prevención de esfuerzo defecatorio (postoperatorio, hemorroides, fisura anal)","Impactación fecal (coadyuvante)"],["oral","rectal"],
  {"adulto":"Oral: 50-300 mg/día dividido en 1-3 tomas. Enema: 1 enema (283 mg) PRN","pediatrico":"<3 años: 10-40 mg/día. 3-6 años: 20-60 mg/día. 6-12 años: 40-120 mg/día"},
  ["Cáps 100 mg","Sol oral 50 mg/5 mL","Enema 283 mg"],"Compatible","u05","c05_05",
  familia="Laxantes emolientes",emb="C",
  ci=["Obstrucción intestinal","Dolor abdominal agudo no diagnosticado","Náuseas y vómitos"],
  ea=["Cólico abdominal leve","Diarrea","Sabor amargo","Irritación faríngea"],
  ix=["Aceite mineral: aumenta absorción y toxicidad (no combinar)","Mínimas interacciones sistémicas"],
  ce=["Prevención, no tratamiento de impactación establecida","Efecto tarda 1-3 días","Útil en postoperatorio para evitar esfuerzo","No combinar con aceite mineral (aumenta absorción tóxica)","Tomar con vaso completo de agua"]),

M("ibp","prucaloprida_detalle","Prucaloprida (detalle)","Prucaloprida",["Resolor","Motegrity"],
  "Agonista 5-HT4 procinético colónico",
  "Agonista selectivo de alta afinidad del receptor serotoninérgico 5-HT4. Estimula motilidad colónica propulsiva (complejo motor migratorio). Alta selectividad 5-HT4 evita prolongación QT de cisaprida",
  ["Estreñimiento crónico idiopático refractario a laxantes","Estreñimiento crónico en mujeres (población mejor estudiada)"],["oral"],
  {"adulto":"2 mg/día. ≥65 años: iniciar con 1 mg/día","ajusteRenal":"ClCr <30: 1 mg/día","ajusteHepatico":"Child-Pugh C: 1 mg/día"},
  ["Comp 1, 2 mg"],"Evitar durante lactancia","u05","c05_05",
  familia="Procinéticos serotoninérgicos",emb="B",
  ci=["Obstrucción intestinal","Perforación GI","Enfermedad inflamatoria intestinal activa severa","Hipersensibilidad","Diálisis"],
  ea=["Cefalea (frecuente, primer día)","Dolor abdominal","Náuseas","Diarrea","Mareo","Fatiga"],
  ix=["Mínimas interacciones (no inhibidor ni inductor CYP)","Procinéticos: efecto aditivo sobre motilidad"],
  ce=["Reservar para estreñimiento refractario a laxantes osmóticos y formadores de masa","La cefalea del primer día suele ser transitoria","Sin prolongación QT (seguro vs cisaprida)","Una toma diaria a cualquier hora","Evaluar respuesta a las 4 semanas"]),

# ── c05_06 Enfermedad Inflamatoria Intestinal (NUEVO, 8 fármacos) ──
M("inmunosupresor","balsalazida","Balsalazida","Balsalazida",["Colazal","Giazo"],
  "Aminosalicilato profármaco de mesalazina",
  "Profármaco de mesalazina (5-ASA) unido a una molécula transportadora inerte (4-aminobenzoil-β-alanina). Se libera selectivamente en colon por acción bacteriana, maximizando concentración local",
  ["Colitis ulcerosa leve a moderada (inducción y mantenimiento)"],["oral"],
  {"adulto":"Inducción: 2.25 g c/8h x 8-12 semanas. Mantenimiento: 1.5-3 g c/12h","pediatrico":"5-17 años: 750 mg-2.25 g c/8h x 8 semanas"},
  ["Cáps 750 mg"],"Compatible con precaución","u05","c05_06",
  familia="Aminosalicilatos (5-ASA)",emb="B",
  ci=["Hipersensibilidad a salicilatos","Insuficiencia renal grave","Hipersensibilidad"],
  ea=["Cefalea","Dolor abdominal","Diarrea","Náuseas","Artralgias","Nefritis intersticial (raro)"],
  ix=["Azatioprina/6-MP: aumenta mielotoxicidad","AINEs: puede empeorar nefrotoxicidad","Heparinas: mayor riesgo sangrado"],
  ce=["Libera mesalazina selectivamente en colon (ventaja)","Monitorizar función renal cada 6-12 meses","Puede tragarse entero o abrir cápsula y mezclar con alimento","Adherencia al tratamiento de mantenimiento es clave","Menor incidencia de efectos GI altos que sulfasalazina"]),

M("inmunosupresor","olsalazina","Olsalazina","Olsalazina",["Dipentum"],"Aminosalicilato dimérico",
  "Dímero de dos moléculas de mesalazina unidas por enlace azo. Se escinde en colon por azorreductasas bacterianas liberando 2 moléculas de 5-ASA. Doble carga de mesalazina por molécula",
  ["Colitis ulcerosa leve-moderada (mantenimiento)","Intolerancia a sulfasalazina"],["oral"],
  {"adulto":"500 mg c/12h con alimentos. Puede aumentar a 1 g c/12h"},
  ["Cáps 250, 500 mg"],"Compatible con precaución","u05","c05_06",
  familia="Aminosalicilatos (5-ASA)",emb="C",
  ci=["Hipersensibilidad a salicilatos","Insuficiencia renal grave","Obstrucción intestinal"],
  ea=["Diarrea acuosa (secretora, hasta 17%)","Dolor abdominal","Náuseas","Cefalea","Artralgias","Exacerbación de colitis (raro)"],
  ix=["Azatioprina/6-MP: aumenta riesgo mielosupresión","Warfarina: posible aumento de INR","Vacuna varicela: puede aumentar riesgo de Reye"],
  ce=["Diarrea secretora frecuente (no confundir con brote de colitis)","Tomar CON alimentos para reducir diarrea","Alternativa en intolerancia a sulfasalazina (sin sulfa)","Monitorizar función renal periódicamente","Libera doble cantidad de 5-ASA por molécula vs balsalazida"]),

M("inmunosupresor","azatioprina_eii","Azatioprina (EII)","Azatioprina",["Imurel","Azasan","Imuran"],
  "Inmunosupresor purínico para EII",
  "Profármaco de 6-mercaptopurina. Inhibe síntesis de purinas y proliferación de linfocitos T. Efecto lento (3-6 meses). Fundamental como ahorrador de corticoides en EII",
  ["Enfermedad de Crohn (mantenimiento y ahorro de corticoides)","Colitis ulcerosa corticodependiente","Mantenimiento de remisión en EII"],["oral"],
  {"adulto":"2-2.5 mg/kg/día (ajustar según TPMT). Iniciar con 50 mg/día y titular","pediatrico":"1.5-2.5 mg/kg/día"},
  ["Comp 50 mg"],"Contraindicado","u05","c05_06",emb="D",
  ci=["Hipersensibilidad","Déficit completo de TPMT (mielotoxicidad letal)","Embarazo (relativo, se usa en EII si beneficio>riesgo)","Leucopenia severa preexistente"],
  ea=["Mielosupresión (leucopenia, pancitopenia)","Hepatotoxicidad","Pancreatitis aguda (idiosincrásica)","Infecciones oportunistas","Mayor riesgo linfoma (uso prolongado)","Náuseas","Alopecia"],
  ix=["Alopurinol: ⚠️ reducir dosis 75% (inhibición xantina oxidasa → toxicidad letal)","5-ASA (mesalazina): aumenta mielotoxicidad","Warfarina: antagonismo"],
  ce=["⚠️ Genotipar TPMT ANTES de iniciar (riesgo mielosupresión letal)","Si TPMT bajo: reducir dosis significativamente","Hemograma cada 1-2 semanas al inicio, luego mensual","Función hepática mensual los primeros 3 meses","Efecto terapéutico tarda 3-6 meses","Si pancreatitis: suspender permanentemente (no reintroducir)"]),

M("inmunosupresor","mercaptopurina_eii","6-Mercaptopurina (EII)","Mercaptopurina",["Purinethol","Puri-Nethol"],
  "Antimetabolito purínico para EII",
  "Análogo de purina que inhibe síntesis de ADN y ARN en linfocitos. Metabolito activo de azatioprina, pero puede usarse directamente. Ahorrador de corticoides en EII",
  ["Enfermedad de Crohn corticodependiente","Colitis ulcerosa corticodependiente","EII con intolerancia a azatioprina (puede tolerar 6-MP)"],["oral"],
  {"adulto":"1-1.5 mg/kg/día (ajustar según TPMT y metabolitos)","pediatrico":"1-1.5 mg/kg/día"},
  ["Comp 50 mg"],"Contraindicado","u05","c05_06",emb="D",
  ci=["Déficit completo de TPMT","Hipersensibilidad","Leucopenia severa"],
  ea=["Mielosupresión","Hepatotoxicidad","Pancreatitis","Infecciones","Riesgo neoplásico (linfoma)","Náuseas"],
  ix=["Alopurinol: ⚠️ reducir dosis 75%","Febuxostat: misma precaución que alopurinol","5-ASA: aumenta toxicidad","Warfarina: disminuye efecto anticoagulante"],
  ce=["Algunos pacientes toleran 6-MP pero no azatioprina","Genotipado TPMT obligatorio","Monitorizar metabolitos 6-TGN y 6-MMP para optimizar dosis","Hemograma semanal al inicio, luego mensual","Tomar por la noche con el estómago vacío"]),

M("inmunosupresor","certolizumab_eii","Certolizumab pegol (EII)","Certolizumab pegol",["Cimzia"],
  "Anti-TNFα pegilado sin Fc",
  "Fragmento Fab' de anticuerpo anti-TNFα conjugado con PEG. Carece de fracción Fc: no induce CDC ni ADCC, no atraviesa placenta. Único anti-TNF seguro en embarazo confirmado",
  ["Enfermedad de Crohn moderada-severa","EII en mujeres que desean embarazo (anti-TNF de elección)"],["SC"],
  {"adulto":"Inducción: 400 mg SC semanas 0, 2, 4. Mantenimiento: 200 mg SC c/2 semanas o 400 mg c/4 semanas"},
  ["Jeringa precargada 200 mg"],"Compatible (no se transfiere a leche por ausencia de Fc)","u05","c05_06",emb="B",
  ci=["Hipersensibilidad","Infección activa grave","TB activa no tratada"],
  ea=["Infecciones respiratorias","Reacción en sitio de inyección","Cefalea","Artralgias","Rash","Reactivación TB"],
  ix=["Inmunosupresores: riesgo aditivo de infección","Vacunas vivas: contraindicadas","Abatacept/anakinra: no combinar"],
  ce=["Anti-TNF de elección en mujeres que desean embarazo (no cruza placenta)","Cribado TB obligatorio","Sin Fc: menor riesgo de ADCC y CDC","Puede ser útil tras fracaso de otro anti-TNF","Educar autoinyección SC"]),

M("inmunosupresor","golimumab_eii","Golimumab (EII)","Golimumab",["Simponi"],
  "Anti-TNFα humano mensual para colitis ulcerosa",
  "Anticuerpo monoclonal completamente humano anti-TNFα. Se une a TNFα soluble y transmembrana. Aprobado específicamente para colitis ulcerosa (no Crohn). Administración mensual",
  ["Colitis ulcerosa moderada-severa"],["SC"],
  {"adulto":"Inducción: 200 mg SC sem 0 → 100 mg sem 2. Mantenimiento: 50-100 mg SC c/4 semanas (según peso)"},
  ["Pluma/jeringa precargada 50, 100 mg"],"Evitar durante lactancia","u05","c05_06",
  ci=["Hipersensibilidad","Infección activa grave","TB latente no tratada","IC moderada-grave (NYHA III-IV)"],
  ea=["Infecciones respiratorias altas","Reacción en sitio de inyección","Nasofaringitis","Elevación transaminasas","Reactivación TB"],
  ix=["Inmunosupresores: mayor riesgo infección","Vacunas vivas: contraindicadas","Metotrexato: uso combinado frecuente pero mayor riesgo infección"],
  ce=["Solo aprobado para colitis ulcerosa (no Crohn)","Administración mensual (mejor adherencia)","Cribado TB antes de iniciar","Autoinyección SC: educar paciente","Conservar refrigerado (2-8°C)"]),

M("inmunosupresor","risankizumab_eii","Risankizumab (EII)","Risankizumab",["Skyrizi"],
  "Anti-IL-23 selectivo p19 para enfermedad de Crohn",
  "Anticuerpo monoclonal humanizado anti-subunidad p19 de IL-23. Más selectivo que ustekinumab (que bloquea p40 compartida por IL-12 e IL-23). Preserva respuestas IL-12 (inmunidad antitumoral/infecciosa)",
  ["Enfermedad de Crohn moderada-severa (incluido fracaso de anti-TNF y otros biológicos)"],["IV","SC"],
  {"adulto":"Inducción: 600 mg IV semanas 0, 4, 8. Mantenimiento: 360 mg SC c/8 semanas"},
  ["Vial IV 600 mg","Jeringa/pluma SC 360 mg"],"Datos limitados","u05","c05_06",
  ci=["Hipersensibilidad","Infección activa grave"],
  ea=["Infecciones respiratorias altas","Cefalea","Artralgias","Reacción en sitio inyección","Anemia"],
  ix=["Vacunas vivas: no administrar durante tratamiento","Inmunosupresores: precaución con combinación"],
  ce=["Anti-IL-23 selectivo: perfil de seguridad favorable","Eficaz tras fracaso de anti-TNF y ustekinumab","Inducción IV → mantenimiento SC","Menos inmunogenicidad que anti-TNF quiméricos","Cribado de TB antes de iniciar"],
  pp={"reconstitucion":"No requiere","dilucion":"Diluir en 250 mL SF","velocidadAdministracion":"Infundir en mínimo 1h","estabilidad":"4h a TA una vez diluido"}),

M("inmunosupresor","mirikizumab","Mirikizumab","Mirikizumab",["Omvoh"],
  "Anti-IL-23 p19 para colitis ulcerosa",
  "Anticuerpo monoclonal humanizado anti-subunidad p19 de IL-23. Primer anti-IL-23 aprobado para colitis ulcerosa. Bloqueo selectivo preserva función IL-12",
  ["Colitis ulcerosa moderada-severa"],["IV","SC"],
  {"adulto":"Inducción: 300 mg IV semanas 0, 4, 8. Mantenimiento: 200 mg SC c/4 semanas"},
  ["Vial IV 300 mg","Pluma/jeringa SC 100 mg"],"Datos limitados","u05","c05_06",
  ci=["Hipersensibilidad","Infección activa grave","TB activa"],
  ea=["Infecciones respiratorias","Reacción en sitio de inyección","Artralgias","Cefalea","Erupción cutánea"],
  ix=["Vacunas vivas: evitar","Inmunosupresores: mayor riesgo infección"],
  ce=["Primer anti-IL-23 para colitis ulcerosa","Inducción IV → mantenimiento SC","Perfil de seguridad favorable","Cribado TB obligatorio","Conservar plumas refrigeradas (2-8°C), sacar 30 min antes de inyectar"],
  pp={"reconstitucion":"No requiere","dilucion":"Diluir en 100 mL SF","velocidadAdministracion":"Infundir en mínimo 30 min","estabilidad":"Usar dentro de 4h de preparación"}),

# ── c05_07 Fármacos Pancreáticos y Biliares (NUEVO, 6 fármacos) ──
M("ibp","pancrelipasa","Pancrelipasa","Pancrelipasa",["Creon","Zenpep","Pancreaze","Pertzye"],
  "Enzimas pancreáticas de reemplazo",
  "Combinación de lipasa, proteasa y amilasa de origen porcino en cápsulas con microesferas de liberación entérica. Reemplaza enzimas pancreáticas deficientes para digestión de grasas, proteínas y carbohidratos",
  ["Insuficiencia pancreática exocrina (pancreatitis crónica, FQ, post-pancreatectomía)","Esteatorrea por insuficiencia pancreática","Malabsorción pancreática"],["oral"],
  {"adulto":"Dosis según lipasa: 500-2500 U lipasa/kg/comida. Iniciar 25000-50000 U lipasa/comida. Titular según esteatorrea","pediatrico":"<4 años: 1000 U lipasa/kg/comida. >4 años: 500 U lipasa/kg/comida. Máx 2500 U/kg/comida o 10000 U/kg/día"},
  ["Cáps 3000-36000 U lipasa (múltiples presentaciones)"],"Compatible","u05","c05_07",
  familia="Enzimas pancreáticas",emb="C",
  ci=["Hipersensibilidad a proteínas porcinas","Pancreatitis aguda (fase inicial)"],
  ea=["Dolor abdominal","Náuseas","Diarrea o estreñimiento","Hiperuricemia","Colonopatía fibrosante (dosis muy altas crónicas, >6000 U/kg/comida)","Reacciones alérgicas a porcino"],
  ix=["Antiácidos con calcio/magnesio: pueden reducir eficacia","IBP: mejoran eficacia (protegen enzimas del ácido)","Acarbosa: reduce eficacia del antidiabético"],
  ce=["Tomar al INICIO de cada comida y con snacks","No triturar ni masticar microesferas (liberación entérica)","Si no puede tragar: abrir cápsula y mezclar con alimento ácido (manzana)","Combinar con IBP para maximizar actividad enzimática","Vigilar colonopatía fibrosante si dosis >6000 U/kg/comida"]),

M("ibp","creon","Creon","Pancrelipasa (formulación Creon)",["Creon"],"Enzima pancreática de referencia",
  "Formulación de referencia de enzimas pancreáticas con microesferas de liberación entérica pH-sensible. Cápsulas de diferentes potencias permiten individualización precisa de la dosis",
  ["Insuficiencia pancreática exocrina por fibrosis quística","Insuficiencia pancreática por pancreatitis crónica","Post-cirugía pancreática"],["oral"],
  {"adulto":"25000-75000 U lipasa/comida. Snacks: 50% de dosis de comida principal","pediatrico":"Lactantes: 2000-4000 U lipasa por 120 mL fórmula. Niños: 1000 U/kg/comida, máx 2500 U/kg/comida"},
  ["Cáps 6000, 12000, 24000, 36000 U lipasa"],"Compatible","u05","c05_07",
  familia="Enzimas pancreáticas",emb="C",
  ci=["Alergia a proteínas porcinas","Pancreatitis aguda"],
  ea=["Dolor abdominal","Flatulencia","Diarrea","Estreñimiento","Náuseas","Colonopatía fibrosante (dosis excesivas)"],
  ix=["IBP/anti-H2: pueden mejorar eficacia","Antiácidos: pueden reducir activación entérica","Acarbosa: reducción de eficacia"],
  ce=["Formulación de referencia en insuficiencia pancreática","Múltiples potencias: individualizar dosis","Administrar con CADA comida y snack","Abrir cápsulas para pacientes con SNG: mezclar con bicarbonato","Monitorizar peso, esteatorrea y nutrición"]),

M("ibp","acido_quenodesoxicolico","Ácido quenodesoxicólico","Ácido quenodesoxicólico",["Chenodiol","Chenofalk"],
  "Ácido biliar primario para disolución litiásica",
  "Ácido biliar primario que reduce secreción biliar de colesterol y promueve desaturación de bilis. Disuelve gradualmente cálculos biliares de colesterol radiotransparentes. También usado en xantomatosis cerebrotendinosa",
  ["Disolución de cálculos biliares de colesterol (radiotransparentes, <15 mm)","Xantomatosis cerebrotendinosa (enfermedad rara)"],["oral"],
  {"adulto":"Litiasis: 13-16 mg/kg/día dividido en 2 tomas con alimentos. Xantomatosis: 250 mg c/8h"},
  ["Cáps 250 mg"],"Contraindicado","u05","c05_07",
  familia="Ácidos biliares",emb="X",
  ci=["Embarazo","Hepatitis crónica","Cirrosis","Cálculos calcificados o pigmentarios","Obstrucción biliar","Colecistitis aguda","Enfermedad inflamatoria intestinal"],
  ea=["Diarrea (dosis-dependiente)","Elevación transitoria de transaminasas","Dolor abdominal","Prurito","Hepatotoxicidad"],
  ix=["Colestiramina: reduce absorción (separar 2h)","Anticonceptivos orales: posible reducción de eficacia","Antiácidos de aluminio: reducen absorción"],
  ce=["Solo efectivo en cálculos de colesterol radiotransparentes <15 mm","Tratamiento prolongado: 6-24 meses","Ecografía de control cada 6 meses","Función hepática mensual los primeros 3 meses","Anticoncepción obligatoria durante tratamiento"]),

M("ibp","fenofibrato_colestasis","Fenofibrato (colestasis)","Fenofibrato",["Lipidil","Tricor","Secalip"],
  "Agonista PPARα para prurito colestásico",
  "Agonista de PPARα que reduce síntesis de ácidos biliares y tiene efecto antiinflamatorio hepatobiliar. Uso off-label creciente en colangitis biliar primaria refractaria como complemento a AUDC",
  ["Prurito colestásico refractario (off-label)","Colangitis biliar primaria (complemento a AUDC, off-label)"],["oral"],
  {"adulto":"200 mg/día (micronizado) o 145-160 mg/día (formulación nano)"},
  ["Cáps 200 mg","Comp 145, 160 mg"],"Contraindicado","u05","c05_07",
  familia="Fibratos",emb="C",
  ci=["Enfermedad hepática activa","Insuficiencia renal severa","Enfermedad biliar preexistente (cálculos)","Uso con estatinas (precaución)"],
  ea=["Mialgias","Elevación CPK","Elevación transaminasas","Molestias GI","Colelitiasis","Fotosensibilidad"],
  ix=["Estatinas: riesgo de rabdomiólisis","Anticoagulantes orales: potencia efecto (reducir dosis)","Ciclosporina: aumenta nefrotoxicidad"],
  ce=["Uso off-label en CBP (evidencia creciente)","Monitorizar CPK y función hepática","No combinar con gemfibrozilo+estatina","Mejora prurito y marcadores hepáticos en CBP","Tomar con comida principal para mejor absorción"]),

M("ibp","colesevelam_prurito","Colesevelam (colestasis)","Colesevelam",["Cholestagel","Welchol"],
  "Resina secuestradora de ácidos biliares de nueva generación",
  "Polímero no absorbible que secuestra ácidos biliares en intestino. Mayor afinidad y selectividad que colestiramina, con mejor tolerancia GI y menos interferencia con absorción de fármacos",
  ["Prurito colestásico","Diarrea por malabsorción de ácidos biliares","Hipercolesterolemia (indicación principal)","DM2 (reduce HbA1c modestamente)"],["oral"],
  {"adulto":"Prurito/diarrea: 625 mg c/8h con comidas. Puede aumentar hasta 3.75 g/día"},
  ["Comp 625 mg","Susp oral"],"Compatible","u05","c05_07",
  familia="Resinas secuestradoras de ácidos biliares",emb="B",
  ci=["Obstrucción biliar","Obstrucción intestinal","Triglicéridos >500 mg/dL","Hipertrigliceridemia familiar"],
  ea=["Estreñimiento","Dispepsia","Flatulencia","Hipertrigliceridemia"],
  ix=["Menos interacciones que colestiramina","Levotiroxina: tomar 4h antes de colesevelam","Anticonceptivos orales: tomar 4h antes"],
  ce=["Mejor tolerada que colestiramina (comprimidos vs polvo)","Menos interferencia con absorción de otros fármacos","Tomar con comidas y abundante agua","Puede combinar con estatinas para efecto aditivo","Monitorizar triglicéridos (puede elevarlos)"]),

M("ibp","bezafibrato_colestasis","Bezafibrato (colestasis)","Bezafibrato",["Bezalip","Cedur"],
  "Agonista pan-PPAR para colestasis",
  "Agonista de PPARα, PPARγ y PPARδ (pan-PPAR). Reduce síntesis de ácidos biliares por activación de FXR y PPARα. Evidencia creciente en CBP: reduce prurito y mejora marcadores colestásicos",
  ["Prurito colestásico refractario (off-label)","Colangitis biliar primaria refractaria a AUDC (off-label)","Dislipidemia (indicación aprobada)"],["oral"],
  {"adulto":"400 mg/día (liberación prolongada) o 200 mg c/8h"},
  ["Comp LP 400 mg","Comp 200 mg"],"Evitar durante lactancia","u05","c05_07",
  familia="Fibratos",emb="C",
  ci=["Insuficiencia hepática grave","Insuficiencia renal grave","Enfermedad biliar","Hipoalbuminemia"],
  ea=["Mialgias","Elevación CPK","Molestias GI","Elevación transaminasas","Litiasis biliar"],
  ix=["Estatinas: riesgo rabdomiólisis (no combinar con gemfibrozilo)","Anticoagulantes orales: potenciación","Ciclosporina: nefrotoxicidad"],
  ce=["Pan-PPAR: puede ser más eficaz que fenofibrato en CBP (actúa en múltiples receptores)","Mejor evidencia que fenofibrato en algunos ensayos CBP","Monitorizar CPK, función hepática y renal","Uso off-label: informar al paciente","Tomar con alimentos"]),

# ── c05_08 Procinéticos y Antiespasmódicos (NUEVO, 10 fármacos) ──
M("antiemetico","cinitaprida","Cinitaprida","Cinitaprida",["Cidine","Blaston"],"Procinético benzamida",
  "Agonista de receptores 5-HT4 y antagonista 5-HT2A. Estimula liberación de acetilcolina en plexo mientérico, aumentando motilidad gastroesofágica y acelerando vaciamiento gástrico",
  ["Reflujo gastroesofágico","Dispepsia funcional","Gastroparesia leve"],["oral"],
  {"adulto":"1 mg c/8h, 15 min antes de comidas"},
  ["Comp 1 mg"],"Evitar durante lactancia","u05","c05_08",
  familia="Procinéticos",emb="B",
  ci=["Hemorragia GI","Obstrucción mecánica GI","Perforación GI","Feocromocitoma","Prolactinoma"],
  ea=["Diarrea","Dolor abdominal","Somnolencia","Cefalea","Hiperprolactinemia leve"],
  ix=["Anticolinérgicos: antagonizan efecto procinético","Opioides: reducen motilidad GI","Depresores SNC: sedación aditiva"],
  ce=["Tomar 15 min antes de cada comida principal","Menor riesgo extrapiramidal que metoclopramida","Disponible principalmente en Europa y Latinoamérica","No exceder dosis recomendada","Útil en dispepsia funcional con plenitud postprandial"]),

M("antiemetico","mosapride","Mosapride","Mosapride",["Gasmotin","Mosarela"],"Procinético agonista 5-HT4 selectivo",
  "Agonista selectivo de receptores 5-HT4 sin actividad antidopaminérgica. Estimula liberación de ACh en plexo mientérico. No causa efectos extrapiramidales ni hiperprolactinemia",
  ["Dispepsia funcional","Gastroparesia","ERGE (coadyuvante)","Estreñimiento funcional"],["oral"],
  {"adulto":"5 mg c/8h antes de comidas"},
  ["Comp 5 mg"],"Evitar durante lactancia","u05","c05_08",
  familia="Procinéticos",emb="C",
  ci=["Hipersensibilidad","Obstrucción GI mecánica","Hemorragia GI"],
  ea=["Diarrea","Dolor abdominal","Boca seca","Cefalea","Erupción cutánea (raro)"],
  ix=["Anticolinérgicos: antagonizan efecto","Eritromicina: efecto procinético aditivo"],
  ce=["Sin efectos extrapiramidales (ventaja sobre metoclopramida)","No eleva prolactina","Tomar antes de comidas","Disponible principalmente en Asia y Latinoamérica","Puede usarse a largo plazo con mayor seguridad que metoclopramida"]),

M("antiemetico","itopride","Itopride","Itopride",["Ganaton","Itomed"],"Procinético dual (anti-D2 + anti-AChE)",
  "Mecanismo dual: antagonista dopaminérgico D2 + inhibidor de acetilcolinesterasa. La doble acción potencia liberación y disponibilidad de ACh en plexo mientérico",
  ["Dispepsia funcional","Gastroparesia","Náuseas y vómitos funcionales"],["oral"],
  {"adulto":"50 mg c/8h antes de comidas"},
  ["Comp 50 mg"],"Evitar durante lactancia","u05","c05_08",
  familia="Procinéticos",emb="C",
  ci=["Hipersensibilidad","Hemorragia GI","Obstrucción mecánica","Perforación GI"],
  ea=["Diarrea","Dolor abdominal","Cefalea","Mareo","Elevación de prolactina (menos que metoclopramida)","Ginecomastia (raro)"],
  ix=["Anticolinérgicos: antagonizan componente colinérgico","Antiácidos: no afectan significativamente"],
  ce=["Mecanismo dual: más potente que procinéticos simples","Menor elevación de prolactina que metoclopramida","Tomar 30 min antes de comidas","No metabolizado por CYP: pocas interacciones","Popular en Asia y Latinoamérica"]),

M("antiemetico","trimebutina","Trimebutina","Trimebutina",["Debridat","Polibutin","Colbutina"],"Regulador de motilidad GI (agonista opioide periférico)",
  "Agonista no selectivo de receptores opioides periféricos mu, kappa y delta en tracto GI. Efecto paradójico: estimula motilidad cuando está reducida y la reduce cuando está aumentada (regulador)",
  ["Síndrome de intestino irritable","Dispepsia funcional","Íleo postoperatorio","Colon irritable con alternancia diarrea/estreñimiento"],["oral","IV"],
  {"adulto":"Oral: 200 mg c/8h antes de comidas. IV: 50-100 mg IV lento","pediatrico":">2 años: 3-5 mg/kg/día dividido c/8h"},
  ["Comp 200 mg","Susp 24 mg/5 mL","Amp 50 mg/5 mL"],"Compatible con precaución","u05","c05_08",
  familia="Reguladores de motilidad GI",emb="B",
  ci=["Hipersensibilidad","Obstrucción intestinal mecánica"],
  ea=["Somnolencia","Mareo","Boca seca","Estreñimiento o diarrea","Reacciones cutáneas (raro)"],
  ix=["Anticolinérgicos: puede potenciar efecto","Procinéticos: interacción variable","Tubocurarina: puede potenciar bloqueo neuromuscular"],
  ce=["Efecto regulador (no solo pro ni anticinético)","Útil en SII por su acción dual","Tomar antes de comidas","Bien tolerado a largo plazo","Si IV: administrar lento"]),

M("antiemetico","mebeverina","Mebeverina","Mebeverina",["Duspatalin","Colotal","Mebeverin"],"Antiespasmódico musculotrópico",
  "Actúa directamente sobre músculo liso GI: bloquea canales de sodio y reduce entrada de calcio. Efecto antiespasmódico sin acción anticolinérgica sistémica. No afecta motilidad normal",
  ["Síndrome de intestino irritable","Espasmo colónico","Dolor abdominal por espasmo GI"],["oral"],
  {"adulto":"135 mg c/8h o 200 mg (LP) c/12h, 20 min antes de comidas"},
  ["Comp 135 mg","Cáps LP 200 mg"],"Compatible con precaución","u05","c05_08",
  familia="Antiespasmódicos musculotrópicos",emb="B",
  ci=["Hipersensibilidad","Íleo paralítico","Obstrucción intestinal"],
  ea=["Rara vez efectos adversos significativos","Reacciones alérgicas cutáneas (raro)","Mareo (raro)","Cefalea (raro)"],
  ix=["Mínimas interacciones (acción local)","Anticolinérgicos: efecto aditivo teórico"],
  ce=["Excelente perfil de seguridad (acción musculotrópica directa)","Sin efectos anticolinérgicos sistémicos","Tomar 20 min antes de comidas","No afecta motilidad normal (solo espasmo)","Seguro en embarazo y ancianos"]),

M("antiemetico","otilonio","Otilonio bromuro","Otilonio",["Spasmomen"],"Antiespasmódico cuaternario de amonio",
  "Amonio cuaternario con acción antiespasmódica directa sobre músculo liso colónico. Bloquea canales de calcio tipo L y receptores muscarínicos a nivel local. Mínima absorción sistémica",
  ["Síndrome de intestino irritable","Espasmo colónico","Dolor abdominal funcional"],["oral"],
  {"adulto":"40 mg c/8h antes de comidas"},
  ["Comp 40 mg"],"Compatible","u05","c05_08",
  familia="Antiespasmódicos",emb="B",
  ci=["Hipersensibilidad","Obstrucción intestinal"],
  ea=["Muy bien tolerado","Náuseas ocasionales","Boca seca (leve)","Cefalea (raro)"],
  ix=["Mínimas interacciones (absorción sistémica insignificante)","Anticolinérgicos: efecto aditivo teórico"],
  ce=["Absorción sistémica mínima: excelente seguridad","Acción predominantemente local en colon","Tomar antes de comidas","Bien tolerado a largo plazo","Popular en Europa y Latinoamérica para SII"]),

M("antiemetico","pinaverio","Pinaverio bromuro","Pinaverio",["Dicetel"],"Antiespasmódico bloqueador de calcio",
  "Bloqueador selectivo de canales de calcio en músculo liso GI. Reduce contracción y espasmo colónico sin efecto cardiovascular significativo (selectividad GI)",
  ["Síndrome de intestino irritable","Discinesia biliar","Espasmo colónico"],["oral"],
  {"adulto":"50-100 mg c/8h con alimentos. No triturar"},
  ["Comp 50, 100 mg"],"Compatible con precaución","u05","c05_08",
  familia="Antiespasmódicos bloqueadores de calcio selectivos",emb="C",
  ci=["Hipersensibilidad","Intolerancia a galactosa","Obstrucción intestinal"],
  ea=["Dolor abdominal","Diarrea","Náuseas","Disfagia (si se disuelve en esófago)","Cefalea"],
  ix=["Mínimas interacciones sistémicas","Anticolinérgicos: efecto aditivo teórico"],
  ce=["Tomar con alimentos y agua suficiente (evitar lesión esofágica)","NO partir ni triturar (irritante esofágico)","No acostarse 30 min después de tomar","Selectividad GI: sin efecto cardiovascular","Bien tolerado a largo plazo"]),

M("antiemetico","hioscina_butilbromuro","Hioscina butilbromuro","Hioscina butilbromuro (escopolamina butilbromuro)",["Buscapina","Buscopan"],
  "Anticolinérgico antiespasmódico cuaternario",
  "Derivado cuaternario de escopolamina con mínimo paso de barrera hematoencefálica. Anticolinérgico muscarínico que relaja músculo liso GI, biliar y genitourinario. Acción periférica sin efectos centrales significativos",
  ["Espasmo GI agudo","Cólico biliar","Cólico renal (coadyuvante)","Dismenorrea espástica","Espasmo del tracto urinario"],["oral","IV","IM","rectal"],
  {"adulto":"Oral: 10-20 mg c/6-8h. IV/IM: 20 mg c/6-8h (máx 100 mg/día). Rectal: 10 mg c/6-8h","pediatrico":">6 años: 10 mg c/8h oral"},
  ["Comp 10 mg","Amp 20 mg/mL","Supositorio 10 mg"],"Compatible con precaución","u05","c05_08",
  familia="Anticolinérgicos antiespasmódicos",emb="B",
  ci=["Glaucoma de ángulo cerrado","Miastenia gravis","Megacolon","Estenosis pilórica","Taquicardia"],
  ea=["Boca seca","Taquicardia (IV)","Retención urinaria","Mareo","Midriasis","Reacción anafilactoide (IV, raro)"],
  ix=["Anticolinérgicos: efectos aditivos","Metoclopramida: antagonismo","Betahistina: reducción de eficacia","Antidepresivos tricíclicos: efectos anticolinérgicos aditivos"],
  ce=["IV: administrar LENTO (riesgo hipotensión y taquicardia)","Vía oral: absorción errática (biodisponibilidad <8%)","Vía parenteral: mucho más efectiva que oral","Vigilar retención urinaria en prostáticos","No cruza BHE: sin sedación central significativa"],
  pp={"reconstitucion":"No requiere","dilucion":"Puede administrarse sin diluir o en 10-20 mL SF","velocidadAdministracion":"Bolo IV lento en 1-2 min","estabilidad":"Usar inmediatamente"}),

M("antiemetico","dicyclomine","Diciclomina (Dicicloverina)","Diciclomina",["Bentyl","Notensyl"],"Anticolinérgico antiespasmódico terciario",
  "Amina terciaria con doble mecanismo: efecto anticolinérgico muscarínico y acción directa sobre músculo liso GI. Cruza parcialmente BHE, pudiendo causar efectos centrales",
  ["Síndrome de intestino irritable","Espasmo GI funcional","Cólico intestinal"],["oral","IM"],
  {"adulto":"Oral: 10-20 mg c/6-8h (iniciar 10 mg, titular). Máx 160 mg/día. IM: 20 mg c/6h (usar máx 1-2 días)"},
  ["Cáps 10 mg","Comp 20 mg","Amp 10 mg/mL"],"Evitar durante lactancia","u05","c05_08",
  familia="Anticolinérgicos antiespasmódicos",emb="B",
  ci=["Lactantes <6 meses (apnea reportada)","Glaucoma de ángulo cerrado","Miastenia gravis","Obstrucción urinaria","Estenosis pilórica","Colitis ulcerosa severa"],
  ea=["Boca seca","Visión borrosa","Somnolencia","Mareo","Retención urinaria","Estreñimiento","Taquicardia"],
  ix=["Anticolinérgicos: efectos aditivos","Antidepresivos tricíclicos: potenciación","Opioides: estreñimiento aditivo","Antihistamínicos sedantes: sedación aditiva"],
  ce=["⚠️ CONTRAINDICADO en lactantes <6 meses (riesgo de apnea)","Cruza BHE: puede causar somnolencia y confusión","Iniciar con dosis baja y titular","Precaución en ancianos (efectos anticolinérgicos centrales)","IM solo si no tolera oral, máx 1-2 días"]),

M("antiemetico","alverine","Alverina","Alverina citrato",["Spasmonal","Meteospasmyl"],"Antiespasmódico musculotrópico derivado de papaverina",
  "Derivado de papaverina con acción directa sobre músculo liso GI y uterino. Inhibe contracción inducida por serotonina (5-HT). Puede combinarse con simeticona para meteorismo",
  ["Síndrome de intestino irritable","Dismenorrea","Espasmo GI funcional con meteorismo"],["oral"],
  {"adulto":"60-120 mg c/8h. Combinación con simeticona: 60/300 mg c/8h antes de comidas"},
  ["Cáps 60 mg","Cáps 60 mg alverina + 300 mg simeticona"],"Compatible con precaución","u05","c05_08",
  familia="Antiespasmódicos musculotrópicos",emb="C",
  ci=["Hipersensibilidad","Íleo paralítico","Obstrucción intestinal"],
  ea=["Náuseas","Cefalea","Mareo","Reacciones alérgicas (raro)","Hepatitis (muy raro)"],
  ix=["Mínimas interacciones conocidas","Anticolinérgicos: efecto antiespasmódico aditivo"],
  ce=["La combinación con simeticona reduce meteorismo asociado","Sin efectos anticolinérgicos significativos","Tomar antes de comidas","Bien tolerada a largo plazo","Disponible en combinación fija con simeticona en muchos países"]),

# ── c05_09 Antidiarreicos y Absorbentes (NUEVO, 8 fármacos) ──
M("ibp","diosmectita","Diosmectita","Diosmectita",["Smecta","Diosmectite"],"Adsorbente intestinal arcilloso",
  "Silicato de aluminio y magnesio natural (arcilla) con alta capacidad adsorbente. Se une a toxinas, virus y bacterias en luz intestinal. Refuerza barrera mucosa por interacción con moco glicoproteico",
  ["Diarrea aguda infecciosa","Diarrea funcional","Esofagitis (protección mucosa)","Diarrea infantil aguda"],["oral"],
  {"adulto":"3 g c/8h (1 sobre c/8h). Disolver en agua","pediatrico":"<1 año: 1 sobre/día. 1-2 años: 1-2 sobres/día. >2 años: 2-3 sobres/día"},
  ["Sobres 3 g"],"Compatible","u05","c05_09",
  familia="Adsorbentes intestinales",emb="A",
  ci=["Hipersensibilidad","Intolerancia a fructosa (algunas formulaciones)"],
  ea=["Estreñimiento (raro)","Flatulencia"],
  ix=["Puede reducir absorción de otros fármacos orales (separar 2h)","No mezclar con otros medicamentos"],
  ce=["Disolver sobre en medio vaso de agua y agitar","Tomar preferiblemente entre comidas","Separar 2h de otros medicamentos","Seguro en lactantes y embarazo","Eficaz en diarrea por rotavirus en niños"]),

M("ibp","caolin_pectina","Caolín + Pectina","Caolín + Pectina",["Kaopectate","Kaomycin"],"Adsorbente antidiarreico combinado",
  "Caolín (silicato de aluminio hidratado) adsorbe toxinas y bacterias. Pectina (polisacárido) forma gel protector sobre mucosa intestinal. Acción sinérgica adsorbente y protectora",
  ["Diarrea aguda no específica","Diarrea del viajero (sintomático)","Diarrea por intoxicación alimentaria (coadyuvante)"],["oral"],
  {"adulto":"30-60 mL después de cada deposición líquida (máx 6 dosis/día)","pediatrico":"3-6 años: 15 mL/dosis. 6-12 años: 30 mL/dosis"},
  ["Susp oral (típicamente 5.85 g caolín + 130 mg pectina por 30 mL)"],"Compatible","u05","c05_09",
  familia="Adsorbentes intestinales",emb="B",
  ci=["Obstrucción intestinal","Diarrea por C. difficile (no usar adsorbentes solos)"],
  ea=["Estreñimiento","Impactación fecal (uso excesivo)","Interferencia con absorción de fármacos"],
  ix=["Reduce absorción de múltiples fármacos orales (separar 2-3h)","Quinolonas: reducida absorción","Digoxina: reducida absorción"],
  ce=["Agitar bien antes de administrar","Separar 2-3h de otros medicamentos","No usar como único tratamiento en diarrea infecciosa severa","Efecto cosmético: mejora consistencia pero no reduce pérdida de líquidos","Hidratación oral es lo prioritario en diarrea"]),

M("ibp","colestiramina_diarrea","Colestiramina (diarrea biliar)","Colestiramina",["Questran"],
  "Resina secuestradora para diarrea por ácidos biliares",
  "Resina de intercambio aniónico que secuestra ácidos biliares en luz intestinal. En diarrea por malabsorción de ácidos biliares, estos llegan al colon donde causan diarrea secretora. Colestiramina los atrapa",
  ["Diarrea por malabsorción de ácidos biliares","Diarrea post-colecistectomía","Diarrea por resección ileal","Diarrea por enfermedad de Crohn ileal"],["oral"],
  {"adulto":"4 g c/8-12h (ajustar según respuesta, máx 16 g/día)"},
  ["Sobres 4 g polvo"],"Compatible","u05","c05_09",
  familia="Resinas secuestradoras de ácidos biliares",emb="C",
  ci=["Obstrucción biliar completa","Hipertrigliceridemia severa"],
  ea=["Estreñimiento","Meteorismo","Náuseas","Déficit vitaminas liposolubles (uso crónico)","Sabor desagradable"],
  ix=["Reduce absorción de múltiples fármacos","Levotiroxina, digoxina, warfarina: tomar 1h antes o 4-6h después"],
  ce=["Indicación clave: diarrea post-colecistectomía o post-resección ileal","Diagnóstico de diarrea biliar: prueba terapéutica con colestiramina","Tomar otros medicamentos 1h ANTES o 4-6h DESPUÉS","Mezclar en agua o jugo (no tomar polvo seco)","Suplementar vitaminas liposolubles si uso prolongado"]),

M("ibp","sales_rehidratacion","Sales de Rehidratación Oral","SRO (Sales de Rehidratación Oral)",["Pedialyte","Electrolit","SRO-OMS"],
  "Terapia de rehidratación oral",
  "Solución isoosmolar o hipoosmolar de glucosa y electrolitos. La glucosa facilita absorción intestinal de sodio y agua por cotransporte Na+/glucosa (SGLT1) incluso en mucosa dañada. Pilar del tratamiento de la deshidratación",
  ["Deshidratación leve-moderada por diarrea","Prevención de deshidratación en gastroenteritis","Rehidratación oral en cólera","Rehidratación en ejercicio intenso"],["oral"],
  {"adulto":"Deshidratación leve: 50-100 mL/kg en 4h. Mantenimiento: sorbos frecuentes + reposición pérdidas","pediatrico":"Deshidratación leve: 50 mL/kg en 4h. Moderada: 100 mL/kg en 4h. Mantener lactancia materna"},
  ["Sobres para disolver en 1L agua (fórmula OMS: Na 75, K 20, Cl 65, citrato 10, glucosa 75 mmol/L)"],"Compatible","u05","c05_09",
  familia="Soluciones de rehidratación oral",emb="A",
  ci=["Vómitos incoercibles (requerirá IV)","Íleo paralítico","Deshidratación severa (requiere IV)","Shock hipovolémico"],
  ea=["Náuseas (si se bebe muy rápido)","Vómitos (administrar en pequeños sorbos frecuentes)","Hipernatremia si preparación incorrecta"],
  ix=["Sin interacciones significativas"],
  ce=["⚠️ Disolver 1 sobre en 1L de agua EXACTO (no más ni menos)","Administrar a sorbos pequeños y frecuentes (no de golpe)","Si vomita: esperar 10 min y reiniciar en sorbos más pequeños","No agregar azúcar ni otros ingredientes","Una vez preparada: usar en 24h (refrigerada) o 1h (TA)","'La TRO ha salvado más vidas que cualquier otro tratamiento médico'"]),

M("ibp","probioticos_saccharomyces","Saccharomyces boulardii","Saccharomyces boulardii",["Floratil","Ultralevura","Perenterol"],
  "Probiótico levadura no patógena",
  "Levadura tropical no patógena resistente a antibióticos. Múltiples mecanismos: neutraliza toxinas bacterianas (toxina A y B de C. difficile), estimula IgA secretora, refuerza barrera intestinal, efecto trófico sobre enterocitos",
  ["Prevención de diarrea asociada a antibióticos","Diarrea aguda infecciosa (coadyuvante)","Prevención de recurrencia de C. difficile","Diarrea del viajero (prevención)","SII con predominio diarrea"],["oral"],
  {"adulto":"250-500 mg c/12h","pediatrico":"250 mg c/12-24h"},
  ["Cáps 250 mg","Sobres 250 mg"],"Compatible","u05","c05_09",
  familia="Probióticos",emb="B",
  ci=["Pacientes con catéter venoso central (riesgo fungemia)","Inmunosupresión severa","Pacientes en UCI con acceso venoso central"],
  ea=["Flatulencia","Fungemia (muy raro, solo en pacientes con catéter central o gravemente inmunocomprometidos)"],
  ix=["Antifúngicos sistémicos: destruyen S. boulardii (no coadministrar)","Antibióticos orales: S. boulardii es resistente (ventaja)"],
  ce=["Resistente a antibióticos: puede tomarse durante antibioticoterapia","⚠️ NO abrir cápsulas cerca de pacientes con catéter central (riesgo de fungemia por contaminación)","Separar 2h de antifúngicos (lo matan)","Almacenar en lugar fresco y seco","No requiere refrigeración (a diferencia de muchos probióticos)"]),

M("ibp","tintura_opio","Tintura de opio","Tintura de opio (tintura deodorizada)",["Paregoric","Laudanum"],
  "Antidiarreico opioide natural",
  "Contiene opio natural con múltiples alcaloides (morfina 10 mg/mL). Actúa en receptores mu opioides en plexo mientérico: reduce peristaltismo, aumenta tono de esfínteres, reduce secreción intestinal y aumenta absorción de agua",
  ["Diarrea severa refractaria a otros tratamientos","Síndrome de intestino corto (reduce volumen de efluente)","Diarrea intratable en cuidados paliativos"],["oral"],
  {"adulto":"0.3-1 mL c/6h (equivalente a 3-10 mg morfina/dosis). Titular según respuesta. Máx: 6 mL/día"},
  ["Sol oral 10 mg morfina/mL (tintura deodorizada)"],"Contraindicado","u05","c05_09",
  familia="Antidiarreicos opioides",emb="C",
  ci=["Diarrea infecciosa por patógenos invasivos","Colitis por C. difficile","Niños","Depresión respiratoria","Íleo paralítico"],
  ea=["Estreñimiento","Sedación","Náuseas","Dependencia física","Depresión respiratoria (sobredosis)","Retención urinaria"],
  ix=["Depresores del SNC: sedación aditiva","Anticolinérgicos: estreñimiento aditivo","IMAO: crisis hipertensiva"],
  ce=["⚠️ Sustancia controlada: uso restringido","Solo para diarrea REFRACTARIA a loperamida y otros","NO usar en diarrea infecciosa invasiva (empeora)","Medir dosis con exactitud (jeringa oral calibrada)","Riesgo de dependencia: uso a corto plazo preferible"]),

M("ibp","difenoxilato_atropina","Difenoxilato/Atropina","Difenoxilato + Atropina",["Lomotil"],
  "Antidiarreico opioide con atropina disuasoria",
  "Difenoxilato es opioide sintético que actúa en receptores mu del plexo GI reduciendo motilidad. La atropina se añade en dosis subterapéutica como disuasorio de abuso (causa efectos desagradables a dosis altas)",
  ["Diarrea aguda como coadyuvante de rehidratación","Diarrea crónica funcional"],["oral"],
  {"adulto":"5/0.05 mg (2 comp) c/6-8h inicialmente, luego reducir a dosis efectiva mínima. Máx: 20 mg difenoxilato/día","pediatrico":"2-12 años: 0.3-0.4 mg/kg/día de difenoxilato dividido en 4 dosis"},
  ["Comp 2.5 mg difenoxilato + 0.025 mg atropina","Sol oral 2.5/0.025 mg por 5 mL"],"Evitar durante lactancia","u05","c05_09",
  familia="Antidiarreicos opioides",emb="C",
  ci=["Niños <2 años","Diarrea por C. difficile o patógenos invasivos","Ictericia obstructiva","Colitis ulcerosa aguda severa"],
  ea=["Boca seca (atropina)","Somnolencia","Mareo","Estreñimiento","Retención urinaria","Taquicardia (dosis altas)","Íleo paralítico","Megacolon tóxico (en colitis)"],
  ix=["Depresores del SNC: sedación aditiva","IMAO: crisis hipertensiva","Anticolinérgicos: efectos aditivos","Naloxona: revierte efecto"],
  ce=["Atropina incluida como disuasorio de abuso (no dosis terapéutica)","NO usar en diarrea por patógenos invasivos (E. coli, Shigella, C. difficile)","Menos potente que loperamida y con más efectos adversos","Vigilar signos de toxicidad atropínica a dosis altas","Rehidratación es siempre lo prioritario"]),

M("ibp","crofelemer","Crofelemer","Crofelemer",["Mytesi"],"Antisecretor intestinal de origen vegetal",
  "Proantocianidina oligomérica derivada del látex de Croton lechleri (sangre de drago). Inhibe dos canales de cloruro (CFTR y CaCC) en superficie luminal de enterocitos, reduciendo secreción de cloruro y agua sin afectar motilidad",
  ["Diarrea no infecciosa en pacientes VIH/SIDA en tratamiento antirretroviral"],["oral"],
  {"adulto":"125 mg c/12h"},
  ["Comp 125 mg de liberación retardada"],"No recomendado","u05","c05_09",
  familia="Antisecretores intestinales",emb="C",
  ci=["Hipersensibilidad","Diarrea infecciosa (descartar antes de iniciar)"],
  ea=["Infección respiratoria alta","Tos","Flatulencia","Náuseas","Dolor abdominal","Infección urinaria"],
  ix=["Mínimas interacciones sistémicas (absorción insignificante)","No afecta absorción de antirretrovirales"],
  ce=["Primer antisecretor aprobado para diarrea por ARV","Acción local: mínima absorción sistémica","Debe descartarse causa infecciosa antes de prescribir","No triturar ni masticar (liberación retardada)","Derivado de planta amazónica (sangre de drago): origen natural"]),
]

NEW_CHAPTERS = {
    "c05_06": {"id":"c05_06","nombre":"Enfermedad Inflamatoria Intestinal","unidadId":"u05","drugIds":[]},
    "c05_07": {"id":"c05_07","nombre":"Fármacos Pancreáticos y Biliares","unidadId":"u05","drugIds":[]},
    "c05_08": {"id":"c05_08","nombre":"Procinéticos y Antiespasmódicos","unidadId":"u05","drugIds":[]},
    "c05_09": {"id":"c05_09","nombre":"Antidiarreicos y Absorbentes","unidadId":"u05","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U05: Sistema Digestivo ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u05", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
