#!/usr/bin/env python3
"""Add ~50 new drugs for U01 Sistema Nervioso (part B): migrañas, EM, ansiolíticos, neuro especial, adicciones."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c01_08 Psicoestimulantes (+3) ──
M("anticonvulsivante","dextroanfetamina","Dextroanfetamina","Dextroanfetamina",["Dexedrine","ProCentra"],
  "Psicoestimulante anfetamínico","Libera dopamina y noradrenalina de terminales presinápticas. Inhibe recaptación",
  ["TDAH","Narcolepsia"],["oral"],
  {"adulto":"5-40 mg/día en 1-3 tomas","pediatrico":"≥6 años: 5 mg/día inicio, incrementar 5 mg/sem"},
  ["Comp 5, 10 mg","Cáps LP 5, 10, 15 mg"],"Contraindicado","u01","c01_08",
  familia="Psicoestimulantes",ci=["Cardiopatía estructural","HTA severa","Glaucoma","Uso de IMAO","Ansiedad severa","Antecedente abuso sustancias"],
  ea=["Insomnio","Anorexia","Taquicardia","Ansiedad","Cefalea","Pérdida de peso","Potencial de abuso"],
  ce=["Sustancia controlada: receta especial","Monitorizar peso y talla en niños","Control PA y FC periódico","No administrar después de mediodía (insomnio)"]),

M("anticonvulsivante","solriamfetol","Solriamfetol","Solriamfetol",["Sunosi"],
  "Inhibidor recaptación dopamina-noradrenalina","Inhibe recaptación de dopamina y noradrenalina sin liberar monoaminas. No es anfetamínico",
  ["Somnolencia excesiva en narcolepsia","Somnolencia excesiva en apnea obstructiva del sueño"],["oral"],
  {"adulto":"Narcolepsia: 75-150 mg/día. SAOS: 37.5-150 mg/día por la mañana","ajusteRenal":"Máx 75 mg si ClCr 15-59"},
  ["Comp 75, 150 mg"],"No recomendado","u01","c01_08",
  familia="Promotores de vigilia",ea=["Cefalea","Náuseas","Disminución apetito","Ansiedad","Insomnio","Elevación PA"],
  ce=["Tomar por la mañana (no después de mediodía)","No sustituye CPAP en SAOS","Monitorizar PA","Bajo potencial de abuso"]),

M("anticonvulsivante","armodafinilo","Armodafinilo","Armodafinilo",["Nuvigil"],
  "Promotor de vigilia (R-enantiómero)","Enantiómero R de modafinilo. Promueve vigilia vía dopamina. Vida media más larga que modafinilo",
  ["Narcolepsia","Somnolencia excesiva en SAOS","Trastorno del sueño por trabajo en turnos"],["oral"],
  {"adulto":"150-250 mg por la mañana (narcolepsia/SAOS) o 150 mg antes del turno"},
  ["Comp 50, 150, 200, 250 mg"],"No recomendado","u01","c01_08",
  familia="Promotores de vigilia",ea=["Cefalea","Náuseas","Mareo","Insomnio","Ansiedad","Stevens-Johnson (raro)"],
  ce=["Tomar por la mañana","Puede reducir eficacia anticonceptivos hormonales","Vigilar reacciones cutáneas","Menor potencial abuso que anfetaminas"]),

# ── c01_09 Migraña (+10) ──
M("triptan","rizatriptan","Rizatriptán","Rizatriptán",["Maxalt","Maxalt RPD"],
  "Agonista selectivo 5-HT1B/1D","Agonista serotoninérgico que produce vasoconstricción craneal selectiva y bloquea neuropéptidos",
  ["Migraña aguda con o sin aura"],["oral","sublingual"],
  {"adulto":"10 mg al inicio. Repetir en 2h si necesario. Máx 30 mg/día","pediatrico":"≥6 años: 5 mg dosis única"},
  ["Comp 5, 10 mg","Liofilizado oral (obleas) 5, 10 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","zolmitriptan","Zolmitriptán","Zolmitriptán",["Zomig"],
  "Agonista selectivo 5-HT1B/1D","Agonista 5-HT1B/1D con acción periférica (vasoconstricción) y central (inhibición trigeminal)",
  ["Migraña aguda con o sin aura","Cefalea en racimos (nasal)"],["oral","nasal"],
  {"adulto":"2.5 mg oral, repetir en 2h. Máx 10 mg/día. Nasal: 5 mg en fosa nasal"},
  ["Comp 2.5, 5 mg","Spray nasal 5 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","naratriptan","Naratriptán","Naratriptán",["Amerge","Naramig"],
  "Agonista 5-HT1B/1D de acción prolongada","Triptán con vida media más larga (6h). Menor tasa de recurrencia. Menos potente que sumatriptán",
  ["Migraña aguda con o sin aura","Migraña menstrual (profilaxis a corto plazo)"],["oral"],
  {"adulto":"2.5 mg al inicio. Repetir en 4h si necesario. Máx 5 mg/día"},
  ["Comp 1, 2.5 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","almotriptan","Almotriptán","Almotriptán",["Axert","Almogran"],
  "Agonista 5-HT1B/1D bien tolerado","Triptán con perfil de tolerabilidad favorable. Menor incidencia de opresión torácica",
  ["Migraña aguda con o sin aura"],["oral"],
  {"adulto":"12.5 mg al inicio. Repetir en 2h. Máx 25 mg/día","pediatrico":"≥12 años: 6.25-12.5 mg"},
  ["Comp 6.25, 12.5 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","eletriptan","Eletriptán","Eletriptán",["Relpax"],
  "Agonista 5-HT1B/1D de alta potencia","Triptán con alta afinidad por receptores 5-HT1B. Eficacia superior en algunos estudios",
  ["Migraña aguda con o sin aura"],["oral"],
  {"adulto":"40 mg al inicio. Repetir en 2h si necesario. Máx 80 mg/día"},
  ["Comp 20, 40 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","frovatriptan","Frovatriptán","Frovatriptán",["Frova","Migard"],
  "Agonista 5-HT1B/1D de acción ultralarga","Triptán con vida media más larga (26h). Menor recurrencia. Ideal para migraña menstrual",
  ["Migraña aguda","Profilaxis de migraña menstrual a corto plazo"],["oral"],
  {"adulto":"2.5 mg al inicio. Repetir en 2h. Máx 7.5 mg/día. Menstrual: 2.5 mg c/12h x 6 días"},
  ["Comp 2.5 mg"],"Evitar durante lactancia","u01","c01_09"),

M("triptan","lasmiditan","Lasmiditán","Lasmiditán",["Reyvow"],
  "Agonista 5-HT1F (no vasoconstricción)","Agonista selectivo 5-HT1F. NO produce vasoconstricción. Seguro en cardiopatía isquémica",
  ["Migraña aguda en adultos (incluyendo pacientes con riesgo cardiovascular)"],["oral"],
  {"adulto":"50-100 mg dosis única. Puede usar 200 mg. No conducir 8h post-dosis"},
  ["Comp 50, 100, 200 mg"],"No recomendado","u01","c01_09",
  ci=["Hipersensibilidad"],ea=["Mareo (significativo)","Somnolencia","Parestesias","Fatiga","Náuseas"],
  ce=["No conducir ni operar maquinaria 8h post-dosis","Seguro en pacientes con cardiopatía","Sustancia controlada V (EE.UU.)","Sin vasoconstricción coronaria"]),

M("triptan","erenumab","Erenumab","Erenumab",["Aimovig"],
  "Anticuerpo anti-CGRP receptor","Anticuerpo monoclonal humano que bloquea receptor de CGRP. Profilaxis, no tratamiento agudo",
  ["Profilaxis de migraña episódica y crónica (≥4 días/mes)"],["SC"],
  {"adulto":"70 mg SC c/mes. Puede aumentar a 140 mg/mes"},
  ["Jeringa precargada 70, 140 mg","Autoinyector 70, 140 mg"],"No recomendado","u01","c01_09",
  familia="Anticuerpos anti-CGRP",ci=["Hipersensibilidad"],
  ea=["Estreñimiento","Reacción en sitio de inyección","Espasmos musculares","HTA (raro)"],
  ix=["Sin interacciones clínicas significativas conocidas"],
  ce=["Enseñar técnica de autoinyección SC","Rotar sitios de inyección","Efecto terapéutico en 1-3 meses","Refrigerar, sacar 30 min antes de inyectar"]),

M("triptan","galcanezumab","Galcanezumab","Galcanezumab",["Emgality"],
  "Anticuerpo anti-CGRP ligando","Anticuerpo monoclonal que se une directamente al péptido CGRP, impidiendo su actividad",
  ["Profilaxis de migraña episódica y crónica","Cefalea en racimos episódica"],["SC"],
  {"adulto":"Carga: 240 mg (2x120 mg) SC. Mantenimiento: 120 mg/mes"},
  ["Jeringa precargada 120 mg","Autoinyector 120 mg"],"No recomendado","u01","c01_09",
  familia="Anticuerpos anti-CGRP",ci=["Hipersensibilidad"],
  ea=["Reacción en sitio de inyección","Estreñimiento","Prurito","Urticaria"],
  ix=["Sin interacciones clínicas significativas"],
  ce=["Dosis de carga doble el primer mes","Autoinyección SC en abdomen, muslo o brazo","Refrigerar entre 2-8°C","Evaluar eficacia a los 3 meses"]),

M("triptan","fremanezumab","Fremanezumab","Fremanezumab",["Ajovy"],
  "Anticuerpo anti-CGRP ligando (mensual o trimestral)","Anticuerpo que se une al péptido CGRP. Opción de dosificación mensual o trimestral",
  ["Profilaxis de migraña episódica y crónica"],["SC"],
  {"adulto":"225 mg SC mensual O 675 mg SC trimestral (3 inyecciones de 225 mg)"},
  ["Jeringa precargada 225 mg","Autoinyector 225 mg"],"No recomendado","u01","c01_09",
  familia="Anticuerpos anti-CGRP",ci=["Hipersensibilidad"],
  ea=["Reacción en sitio de inyección","Endurecimiento zona inyección"],
  ix=["Sin interacciones significativas"],
  ce=["Opción trimestral mejora adherencia","Inyectar a temperatura ambiente","Rotar sitios SC","Evaluar respuesta en 3 meses"]),

# ── c01_10 Esclerosis Múltiple (+8) ──
M("esclerosis_multiple","fingolimod","Fingolimod","Fingolimod",["Gilenya"],
  "Modulador del receptor S1P","Agonista funcional de receptores S1P que secuestra linfocitos en ganglios, reduciendo infiltración al SNC",
  ["Esclerosis múltiple remitente-recurrente"],["oral"],
  {"adulto":"0.5 mg/día"},
  ["Cáps 0.25, 0.5 mg"],"Contraindicado","u01","c01_10",
  ci=["IAM o ACV reciente","Bloqueo AV 2°-3°","Bradicardia severa","Infección activa"],
  ea=["Bradicardia (primera dosis)","Edema macular","Infecciones","Cefalea","Elevación transaminasas","Linfopenia"],
  ce=["Monitorización cardíaca 6h tras primera dosis (ECG continuo)","Examen oftalmológico previo y a los 3-4 meses","Hemograma previo","Vacunación VVZ si seronegativo antes de iniciar"]),

M("esclerosis_multiple","dimetilfumarato","Dimetilfumarato","Dimetilfumarato",["Tecfidera"],
  "Inmunomodulador oral (fumarato)","Activa vía Nrf2 con efecto antiinflamatorio y neuroprotector. Reduce linfocitos activados",
  ["Esclerosis múltiple remitente-recurrente"],["oral"],
  {"adulto":"120 mg c/12h x 7 días, luego 240 mg c/12h"},
  ["Cáps 120, 240 mg"],"No recomendado","u01","c01_10",
  ea=["Rubor facial (flushing)","Diarrea","Náuseas","Dolor abdominal","Linfopenia (monitorizar)","Elevación transaminasas"],
  ce=["Tomar con alimentos reduce flushing y GI","ASA 325 mg 30 min antes puede reducir flushing","Hemograma c/3 meses primer año, luego c/6 meses","Suspender si linfocitos <500 sostenido"]),

M("esclerosis_multiple","natalizumab","Natalizumab","Natalizumab",["Tysabri"],
  "Anticuerpo anti-integrina alfa-4","Anticuerpo monoclonal que bloquea integrina alfa-4, impidiendo migración de linfocitos al SNC",
  ["EM remitente-recurrente activa","Enfermedad de Crohn refractaria"],["IV"],
  {"adulto":"300 mg IV c/4 semanas en infusión de 1h"},
  ["Vial 300 mg/15mL"],"Contraindicado","u01","c01_10",
  ea=["⚠️ Leucoencefalopatía multifocal progresiva (LMP)","Reacciones infusionales","Cefalea","Fatiga","Infecciones","Hepatotoxicidad"],
  ci=["LMP previa","Inmunosupresión activa","Infección activa"],
  ce=["Determinar anticuerpos anti-JCV antes de iniciar","Programa de farmacovigilancia obligatorio","Vigilar signos neurológicos nuevos (LMP)","Observar 1h post-infusión por reacciones"],
  pp={"dilucion":"Diluir 300 mg en 100 mL SF","velocidadAdministracion":"Infundir en 1 hora","estabilidad":"Usar dentro de 8h de preparación"}),

M("esclerosis_multiple","ocrelizumab","Ocrelizumab","Ocrelizumab",["Ocrevus"],
  "Anticuerpo anti-CD20","Anticuerpo humanizado anti-CD20 que depleciona linfocitos B. Eficaz en formas recurrentes y progresivas",
  ["EM remitente-recurrente","EM primariamente progresiva"],["IV"],
  {"adulto":"Inicio: 300 mg IV d1 + 300 mg d15. Mantenimiento: 600 mg IV c/6 meses"},
  ["Vial 300 mg/10mL"],"Contraindicado","u01","c01_10",
  ea=["Reacciones infusionales","Infecciones respiratorias","Herpes","Neutropenia","Hipogammaglobulinemia"],
  ce=["Premedicar con metilprednisolona 100 mg IV + antihistamínico + paracetamol","Observar durante y 1h post-infusión","Vacunar antes de iniciar (no vivas)","Cribado hepatitis B previo"]),

M("esclerosis_multiple","teriflunomida","Teriflunomida","Teriflunomida",["Aubagio"],
  "Inhibidor de dihidroorotato deshidrogenasa","Inhibe síntesis de pirimidinas en linfocitos activados, reduciendo proliferación",
  ["EM remitente-recurrente"],["oral"],
  {"adulto":"7 o 14 mg/día"},
  ["Comp 7, 14 mg"],"Contraindicado","u01","c01_10",emb="X",
  ea=["Alopecia","Diarrea","Náuseas","Elevación ALT","Neuropatía periférica","Teratogenicidad"],
  ce=["⚠️ Teratógeno: anticoncepción obligatoria","Función hepática mensual x 6 meses","Procedimiento de eliminación acelerada con colestiramina si necesario","Monitorizar PA (puede elevar)"]),

M("esclerosis_multiple","glatiramer","Glatirámero","Acetato de glatirámero",["Copaxone","Glatopa"],
  "Inmunomodulador (copolímero sintético)","Péptido sintético que simula proteína básica de mielina. Desvía respuesta inmune hacia Th2 antiinflamatoria",
  ["EM remitente-recurrente","Síndrome clínico aislado"],["SC"],
  {"adulto":"20 mg SC diario O 40 mg SC 3 veces/semana"},
  ["Jeringa precargada 20 mg/mL, 40 mg/mL"],"Compatible con precaución","u01","c01_10",
  ea=["Reacción en sitio de inyección (muy frecuente)","Reacción post-inyección inmediata (rubor, opresión, disnea transitoria)","Lipoatrofia"],
  ce=["Rotar sitios de inyección estrictamente","Reacción inmediata post-inyección es benigna y autolimitada","Vigilar lipoatrofia en sitios repetidos","No requiere monitorización de laboratorio"]),

M("esclerosis_multiple","siponimod","Siponimod","Siponimod",["Mayzent"],
  "Modulador selectivo S1P1/S1P5","Modulador selectivo de receptores S1P1 y S1P5. No requiere monitorización cardíaca de primera dosis en todos",
  ["EM secundariamente progresiva activa"],["oral"],
  {"adulto":"Titulación: 0.25→0.25→0.5→0.75→1.25 mg (d1-5), luego 2 mg/día. Según genotipo CYP2C9"},
  ["Comp 0.25, 2 mg"],"Contraindicado","u01","c01_10",
  ea=["Bradicardia (primera dosis, menos que fingolimod)","Cefalea","HTA","Edema macular","Linfopenia","Elevación transaminasas"],
  ce=["Genotipado CYP2C9 obligatorio antes de iniciar","CYP2C9 *3/*3: contraindicado","Monitorización cardíaca según titulación","Examen oftalmológico previo"]),

M("esclerosis_multiple","cladribina_oral","Cladribina oral","Cladribina",["Mavenclad"],
  "Análogo purínico inmunosupresor selectivo","Análogo de adenosina que se acumula selectivamente en linfocitos, causando depleción sostenida",
  ["EM remitente-recurrente altamente activa"],["oral"],
  {"adulto":"3.5 mg/kg dosis total en 2 años. Año 1: 1.75 mg/kg en 2 ciclos. Año 2: igual"},
  ["Comp 10 mg"],"Contraindicado","u01","c01_10",emb="X",
  ea=["Linfopenia (esperada y terapéutica)","Infecciones","Herpes zóster","Cefalea","Riesgo neoplasia (teórico)"],
  ce=["Anticoncepción durante tratamiento y 6 meses después","Hemograma previo y antes de cada ciclo","Cribado infecciones previo","No iniciar si linfocitos <500"]),

# ── c01_11 Ansiolíticos y Sedantes (+8) ──
M("benzodiacepina","clorazepato","Clorazepato","Clorazepato dipotásico",["Tranxilium"],
  "Benzodiazepina de acción prolongada","Profármaco que se convierte en desmetildiazepam en estómago ácido. Acción ansiolítica prolongada",
  ["Ansiedad generalizada","Abstinencia alcohólica","Epilepsia (adyuvante)"],["oral"],
  {"adulto":"Ansiedad: 7.5-15 mg c/8-12h. Abstinencia OH: 30 mg inicio, reducir gradualmente","geriatrico":"3.75-7.5 mg c/12h"},
  ["Cáps 5, 10, 15 mg","Comp LP 22.5 mg"],"Evitar durante lactancia","u01","c01_11"),

M("benzodiacepina","bromazepam","Bromazepam","Bromazepam",["Lexotanil","Lexotan"],
  "Benzodiazepina ansiolítica","Benzodiazepina de potencia intermedia con predominio ansiolítico sobre sedante e hipnótico",
  ["Ansiedad generalizada","Tensión emocional","Ansiedad prequirúrgica"],["oral"],
  {"adulto":"1.5-3 mg c/8h. Ansiedad severa: 6-12 mg c/8h. Máx 36 mg/día","geriatrico":"Mitad de dosis"},
  ["Comp 1.5, 3, 6 mg"],"Evitar durante lactancia","u01","c01_11"),

M("benzodiacepina","lormetazepam","Lormetazepam","Lormetazepam",["Noctamid","Loramet"],
  "Benzodiazepina hipnótica","Benzodiazepina de acción intermedia con predominio hipnótico. Vida media 10-12h",
  ["Insomnio (tratamiento a corto plazo)"],["oral"],
  {"adulto":"1-2 mg antes de acostarse. Máx 2 mg","geriatrico":"0.5-1 mg"},
  ["Comp 1, 2 mg"],"Evitar durante lactancia","u01","c01_11"),

M("benzodiacepina","eszopiclona","Eszopiclona","Eszopiclona",["Lunesta"],
  "Hipnótico no benzodiazepínico (Z-drug)","Agonista selectivo de subunidad alfa-1 del receptor GABA-A. Enantiómero S de zopiclona",
  ["Insomnio de conciliación y mantenimiento"],["oral"],
  {"adulto":"1-3 mg antes de acostarse. Inicio: 1 mg","geriatrico":"1 mg (máx 2 mg)"},
  ["Comp 1, 2, 3 mg"],"Evitar durante lactancia","u01","c01_11",
  familia="Hipnóticos Z",ea=["Sabor metálico/amargo","Somnolencia residual","Mareo","Boca seca","Conductas complejas dormido (raro)"],
  ce=["Tomar inmediatamente antes de acostarse","Asegurar 7-8h de sueño disponibles","Vigilar conductas del sueño complejas","Menor riesgo de dependencia que BZD"]),

M("benzodiacepina","ramelteon","Ramelteon","Ramelteon",["Rozerem"],
  "Agonista de receptores de melatonina","Agonista selectivo de receptores MT1/MT2 de melatonina. No actúa sobre GABA. Sin potencial de abuso",
  ["Insomnio de conciliación"],["oral"],
  {"adulto":"8 mg 30 min antes de acostarse. No triturar"},
  ["Comp 8 mg"],"No recomendado","u01","c01_11",
  familia="Agonistas melatoninérgicos",ci=["Hipersensibilidad","Uso con fluvoxamina","Insuficiencia hepática grave"],
  ea=["Somnolencia","Mareo","Fatiga","Náuseas","Elevación prolactina"],
  ix=["Fluvoxamina: contraindicado (aumenta niveles 70x)","Inhibidores CYP1A2: precaución"],
  ce=["No tiene potencial de abuso ni dependencia","No es sustancia controlada","No tomar con/después de comida grasa","Puede usarse a largo plazo"]),

M("benzodiacepina","suvorexant","Suvorexant","Suvorexant",["Belsomra"],
  "Antagonista dual de receptores de orexina (DORA)","Bloquea receptores OX1 y OX2 de orexina/hipocretina, promoviendo sueño fisiológico",
  ["Insomnio de conciliación y mantenimiento"],["oral"],
  {"adulto":"10 mg antes de acostarse. Puede aumentar a 20 mg. Máx 20 mg","geriatrico":"5-10 mg"},
  ["Comp 5, 10, 15, 20 mg"],"No recomendado","u01","c01_11",
  familia="Antagonistas de orexina",ci=["Narcolepsia","Hipersensibilidad"],
  ea=["Somnolencia diurna","Parálisis del sueño","Alucinaciones hipnagógicas","Cataplejía leve","Conductas complejas dormido"],
  ce=["Mecanismo fisiológico del sueño","No tomar si no puede dormir 7h","Vigilar somnolencia diurna","Menor tolerancia y dependencia que BZD"]),

M("benzodiacepina","lemborexant","Lemborexant","Lemborexant",["Dayvigo"],
  "Antagonista dual de orexina (DORA 2ª gen)","Antagonista competitivo de receptores OX1R/OX2R de segunda generación. Mayor selectividad",
  ["Insomnio de conciliación y mantenimiento"],["oral"],
  {"adulto":"5 mg antes de acostarse. Puede aumentar a 10 mg","geriatrico":"5 mg"},
  ["Comp 5, 10 mg"],"No recomendado","u01","c01_11",
  familia="Antagonistas de orexina",ci=["Narcolepsia","Hipersensibilidad"],
  ea=["Somnolencia","Fatiga","Cefalea","Parálisis del sueño","Alucinaciones hipnagógicas"],
  ce=["No usar con inhibidores potentes CYP3A4","Asegurar mínimo 7h de sueño","Puede usarse a largo plazo","Menor riesgo de abuso que BZD"]),

M("benzodiacepina","zaleplon","Zaleplon","Zaleplon",["Sonata"],
  "Hipnótico ultracorto no benzodiazepínico","Agonista selectivo subunidad alfa-1 GABA-A. Vida media ultracorta (1h). Solo para conciliación",
  ["Insomnio de conciliación (dificultad para dormirse)"],["oral"],
  {"adulto":"10 mg antes de acostarse. Puede tomar si despierta con ≥4h restantes","geriatrico":"5 mg"},
  ["Cáps 5, 10 mg"],"Evitar durante lactancia","u01","c01_11",
  familia="Hipnóticos Z",ea=["Cefalea","Mareo","Somnolencia mínima residual","Parestesias","Amnesia"],
  ce=["Vida media ultracorta: solo para conciliación","No tomar con comida grasa (retrasa absorción)","Puede tomarse en medio de la noche si quedan ≥4h","Menor efecto resaca que otros hipnóticos"]),

# ── c01_12 Neurofármacos Especiales (+8) ──
M("anticonvulsivante","riluzol","Riluzol","Riluzol",["Rilutek"],
  "Neuroprotector antiglutamatérgico","Inhibe liberación de glutamato y bloquea receptores NMDA. Único fármaco que modifica curso de ELA",
  ["Esclerosis lateral amiotrófica (ELA)"],["oral"],
  {"adulto":"50 mg c/12h en ayunas (1h antes o 2h después de alimentos)"},
  ["Comp 50 mg","Sol oral 5 mg/mL"],"Contraindicado","u01","c01_12",
  familia="Neuroprotectores",ci=["Insuficiencia hepática","Hipersensibilidad"],
  ea=["Elevación transaminasas","Astenia","Náuseas","Diarrea","Mareo","Neutropenia (raro)"],
  ce=["Función hepática mensual x 3 meses, luego periódica","Prolonga supervivencia ~3 meses en ELA","No cura: explica expectativas","Tomar en ayunas estricto"]),

M("anticonvulsivante","tetrabenazina","Tetrabenazina","Tetrabenazina",["Xenazine"],
  "Inhibidor de VMAT2","Inhibe transportador vesicular de monoaminas tipo 2 (VMAT2), deplecionando dopamina presináptica",
  ["Corea de Huntington","Discinesia tardía","Otros movimientos involuntarios hipercinéticos"],["oral"],
  {"adulto":"12.5 mg/día inicio. Titular hasta 25 mg c/8h. Máx 100 mg/día"},
  ["Comp 12.5, 25 mg"],"Contraindicado","u01","c01_12",
  familia="Fármacos para movimientos involuntarios",ci=["Depresión activa o ideación suicida","Uso de IMAO","Hepatopatía","Uso reserpina"],
  ea=["Depresión y suicidio (⚠️ riesgo principal)","Sedación","Acatisia","Parkinsonismo","Náuseas","Insomnio"],
  ce=["Evaluar depresión antes y durante tratamiento","Suspender si ideación suicida","Genotipado CYP2D6 si dosis >50 mg/día","No combinar con IMAO ni reserpina"]),

M("anticonvulsivante","valbenazina","Valbenazina","Valbenazina",["Ingrezza"],
  "Inhibidor selectivo VMAT2 (1ª aprobación para DT)","Inhibidor altamente selectivo de VMAT2. Primer fármaco aprobado específicamente para discinesia tardía",
  ["Discinesia tardía en adultos"],["oral"],
  {"adulto":"40 mg/día x 1 semana, luego 80 mg/día. Dosis única diaria"},
  ["Cáps 40, 60, 80 mg"],"No recomendado","u01","c01_12",
  familia="Fármacos para movimientos involuntarios",ci=["Hipersensibilidad","Uso de IMAO"],
  ea=["Somnolencia","Acatisia","Prolongación QT","Cefalea","Fatiga"],
  ce=["Evaluar AIMS periódicamente","ECG basal si factores riesgo QT","Metabolizadores lentos CYP2D6: 40 mg/día","No suspender antipsicótico causante sin valorar"]),

M("anticonvulsivante","toxina_botulinica_a","Toxina Botulínica tipo A","Toxina botulínica A",["Botox","Dysport","Xeomin"],
  "Neurotoxina que bloquea acetilcolina","Bloquea liberación de acetilcolina en unión neuromuscular, causando parálisis muscular localizada reversible",
  ["Distonía cervical","Espasticidad focal","Blefaroespasmo","Migraña crónica (profilaxis)","Hiperhidrosis axilar"],["IM"],
  {"adulto":"Varía según indicación. Migraña: 155-195 U en 31-39 puntos c/12 sem. Distonía cervical: 100-300 U"},
  ["Vial 50, 100, 200 U (Botox)","Vial 300, 500 U (Dysport)"],"No recomendado (uso localizado)","u01","c01_12",
  familia="Toxinas terapéuticas",ci=["Infección en sitio de inyección","Miastenia gravis","Síndrome Lambert-Eaton"],
  ea=["Debilidad muscular excesiva","Disfagia (inyección cervical)","Ptosis","Dolor local","⚠️ Diseminación a distancia (raro, potencialmente fatal)"],
  ix=["Aminoglucósidos: potencian bloqueo neuromuscular","Otros bloqueantes NM: efecto aditivo"],
  ce=["Efecto tarda 2-7 días, dura 3-4 meses","Unidades NO intercambiables entre marcas","Vigilar disfagia y debilidad generalizada","Técnica de inyección requiere entrenamiento específico"]),

M("anticonvulsivante","edaravona","Edaravona","Edaravona",["Radicava","Radicut"],
  "Eliminador de radicales libres","Antioxidante que elimina radicales libres peroxilo e hidroxilo, reduciendo estrés oxidativo neuronal",
  ["Esclerosis lateral amiotrófica (ELA)"],["IV","oral"],
  {"adulto":"IV: 60 mg en 60 min x 14 días, luego 10 de 14 días c/mes. Oral: 105 mg/día"},
  ["Vial 30 mg/20mL","Suspensión oral 105 mg/5mL"],"No recomendado","u01","c01_12",
  familia="Neuroprotectores",ci=["Hipersensibilidad a sulfitos (formulación IV)"],
  ea=["Hematomas","Mareo","Cefalea","Dermatitis","Reacciones de hipersensibilidad","Insuficiencia renal"],
  ce=["Beneficio modesto: explicar expectativas","Formulación oral disponible (más práctica)","Vigilar función renal","Monitorizar reacciones alérgicas post-infusión"]),

M("anticonvulsivante","nusinersen","Nusinersén","Nusinersén",["Spinraza"],
  "Oligonucleótido antisentido para AME","Oligonucleótido antisentido que modifica splicing de gen SMN2, aumentando producción de proteína SMN funcional",
  ["Atrofia muscular espinal (AME) tipos 1, 2 y 3"],["intratecal"],
  {"adulto":"12 mg intratecal. Carga: días 0, 14, 28, 63. Mantenimiento: c/4 meses","pediatrico":"Misma dosis en todos los grupos de edad"},
  ["Vial 12 mg/5mL"],"No hay datos suficientes","u01","c01_12",
  familia="Terapias génicas/antisentido",ci=["Hipersensibilidad"],
  ea=["Cefalea post-punción lumbar","Infección vías respiratorias","Trombocitopenia","Nefrotoxicidad","Dolor lumbar"],
  ix=["Anticoagulantes: mayor riesgo sangrado en PL"],
  ce=["Administración intratecal exclusivamente por especialista","Monitorizar plaquetas y función renal","Hidratación post-PL","Revolucionario para AME: mejora función motora"]),

M("anticonvulsivante","betahistina","Betahistina","Betahistina",["Serc","Betaserc"],
  "Análogo de histamina para vértigo","Agonista parcial H1 y antagonista H3 que mejora microcirculación del oído interno y vestíbulo",
  ["Vértigo de Ménière","Vértigo vestibular periférico"],["oral"],
  {"adulto":"8-16 mg c/8h. Puede incrementar hasta 48 mg/día"},
  ["Comp 8, 16, 24 mg"],"Compatible con precaución","u01","c01_12",
  familia="Fármacos para vértigo",ci=["Feocromocitoma","Úlcera péptica activa","Hipersensibilidad"],
  ea=["Cefalea","Náuseas","Dispepsia","Dolor abdominal"],
  ix=["Antihistamínicos: pueden reducir eficacia","IMAO: precaución"],
  ce=["Tomar con alimentos","Eficacia se evalúa en 2-4 semanas","No es tratamiento agudo de crisis de vértigo","Usar a largo plazo para prevención de crisis"]),

M("anticonvulsivante","flunarizina","Flunarizina","Flunarizina",["Sibelium"],
  "Calcioantagonista con selectividad cerebral","Bloqueante de canales de calcio con selectividad por vasos cerebrales. Antihistamínico H1 y antidopaminérgico leve",
  ["Profilaxis de migraña","Vértigo vestibular periférico recurrente"],["oral"],
  {"adulto":"5-10 mg/día por la noche. Ciclos de 2-6 meses","geriatrico":"5 mg/día"},
  ["Cáps 5, 10 mg"],"Evitar durante lactancia","u01","c01_12",
  familia="Profilácticos de migraña",ci=["Depresión activa","Parkinsonismo","Embarazo","Porfiria"],
  ea=["Somnolencia","Aumento de peso (significativo)","Depresión","Parkinsonismo (uso prolongado)"],
  ix=["Depresores SNC: sedación aditiva","Antiepilépticos: potenciación"],
  ce=["Tomar por la noche por somnolencia","Usar por ciclos, no continuo indefinido","Vigilar estado de ánimo (depresión)","Pesar periódicamente"]),

# ── c01_13 Adicciones (+6) ──
M("adiccion","acamprosato","Acamprosato","Acamprosato",["Campral"],
  "Modulador glutamatérgico para alcoholismo","Análogo de GABA que modula transmisión glutamatérgica, reduciendo hiperexcitabilidad neuronal del alcoholismo",
  ["Mantenimiento de abstinencia alcohólica (tras desintoxicación)"],["oral"],
  {"adulto":"≥60 kg: 666 mg c/8h. <60 kg: 333 mg c/8h. Iniciar tras completar desintoxicación","ajusteRenal":"Contraindicado si ClCr <30"},
  ["Comp 333 mg"],"No recomendado","u01","c01_13"),

M("adiccion","disulfiram","Disulfiram","Disulfiram",["Antabuse"],
  "Inhibidor de aldehído deshidrogenasa","Inhibe irreversiblemente aldehído deshidrogenasa, causando acumulación de acetaldehído si se consume alcohol",
  ["Aversión al alcohol como apoyo a abstinencia"],["oral"],
  {"adulto":"Inicio: 500 mg/día x 1-2 sem. Mantenimiento: 250 mg/día (rango 125-500 mg)"},
  ["Comp 250, 500 mg"],"Contraindicado","u01","c01_13",
  ci=["Consumo actual de alcohol","Enfermedad coronaria severa","Psicosis","Hepatopatía grave","Uso de metronidazol o alcohol en cualquier forma"],
  ea=["⚠️ Reacción disulfiram-alcohol (rubor, taquicardia, hipotensión, vómitos, disnea)","Hepatotoxicidad","Neuropatía periférica","Somnolencia","Sabor metálico"],
  ce=["Paciente debe estar abstinente ≥12h antes de iniciar","Informar sobre reacción con CUALQUIER fuente de alcohol (colutorios, vinagre, perfumes)","Función hepática periódica","Portar tarjeta identificativa de uso de disulfiram"]),

M("adiccion","vareniclina","Vareniclina","Vareniclina",["Champix","Chantix"],
  "Agonista parcial de receptores nicotínicos alfa-4/beta-2","Agonista parcial que reduce craving y satisfacción del tabaco. Bloquea efecto reforzante de nicotina",
  ["Cesación tabáquica"],["oral"],
  {"adulto":"Días 1-3: 0.5 mg/día. Días 4-7: 0.5 mg c/12h. Día 8 en adelante: 1 mg c/12h x 12 sem"},
  ["Comp 0.5, 1 mg","Kit de inicio"],"No recomendado","u01","c01_13",
  ci=["Hipersensibilidad","Insuficiencia renal terminal sin diálisis"],
  ea=["Náuseas (muy frecuente)","Insomnio","Sueños vívidos/anormales","Cefalea","Cambios de humor","Ideación suicida (vigilar)"],
  ce=["Iniciar 1-2 semanas antes de fecha de cesación","Tomar con alimentos y vaso de agua completo","Puede combinar con parches de nicotina","Evaluar estado de ánimo semanalmente"]),

M("adiccion","buprenorfina_naloxona","Buprenorfina/Naloxona","Buprenorfina + Naloxona",["Suboxone","Zubsolv"],
  "Agonista parcial mu + antagonista para dependencia a opioides",
  "Buprenorfina: agonista parcial mu con efecto techo. Naloxona: antagonista que previene uso IV indebido",
  ["Trastorno por uso de opioides (tratamiento de mantenimiento)","Desintoxicación de opioides"],["sublingual"],
  {"adulto":"Inducción: 2/0.5-4/1 mg SL. Mantenimiento: 8/2-24/6 mg/día"},
  ["Comp SL 2/0.5, 8/2 mg","Film SL 2/0.5, 4/1, 8/2, 12/3 mg"],"Evitar durante lactancia","u01","c01_13",
  ci=["Uso activo de agonistas opioides completos (precipita abstinencia)","Insuficiencia respiratoria grave"],
  ea=["Cefalea","Náuseas","Sudoración","Estreñimiento","Insomnio","Síndrome abstinencia si usa opioides"],
  ix=["Benzodiazepinas: depresión respiratoria","Depresores SNC: sedación","Inhibidores CYP3A4: aumentan niveles"],
  ce=["Iniciar en abstinencia leve-moderada (escala COWS ≥12)","Sublingual: no tragar, dejar disolver","Prescripción requiere certificación especial","Vigilar precipitación de abstinencia"]),

M("adiccion","naloxona_nasal","Naloxona nasal","Naloxona",["Narcan nasal"],
  "Antagonista opioide de emergencia nasal","Antagonista competitivo de receptores opioides mu, kappa y delta. Vía nasal para uso comunitario",
  ["Reversión de emergencia de sobredosis por opioides (uso comunitario y profesional)"],["nasal"],
  {"adulto":"4 mg en una fosa nasal. Repetir c/2-3 min si no responde, alternando fosas","pediatrico":"Misma dosis que adultos"},
  ["Spray nasal 4 mg/0.1mL"],"Compatible","u01","c01_13",
  ci=["Hipersensibilidad a naloxona"],
  ea=["Síndrome de abstinencia agudo a opioides","Taquicardia","HTA","Náuseas y vómitos","Diaforesis"],
  ix=["Opioides: antagonismo (precipita abstinencia)"],
  ce=["Enseñar uso a pacientes, familiares y cuidadores","Llamar emergencias SIEMPRE además de administrar","Puede requerir múltiples dosis (fentanilo)","Observar ≥2h post-administración (renarcotización)"]),

M("adiccion","lofexidina","Lofexidina","Lofexidina",["Lucemyra"],
  "Agonista alfa-2 adrenérgico para abstinencia opioide",
  "Agonista alfa-2 central que reduce liberación de noradrenalina, atenuando síntomas de abstinencia opioide",
  ["Mitigación de síntomas de abstinencia aguda a opioides"],["oral"],
  {"adulto":"3 comp (0.54 mg) c/6h x 5-7 días. Máx 2.88 mg/día. Reducir gradualmente"},
  ["Comp 0.18 mg"],"No recomendado","u01","c01_13",
  ci=["Hipersensibilidad","Bradicardia severa","Hipotensión severa"],
  ea=["Hipotensión ortostática","Bradicardia","Somnolencia","Boca seca","Prolongación QT"],
  ce=["Monitorizar PA y FC antes de cada dosis","No suspender opioides bruscamente antes","Máx 14 días de tratamiento","Levantar lentamente por hipotensión"]),
]

NEW_CHAPTERS = {
    "c01_10": {"id":"c01_10","nombre":"Esclerosis Múltiple","unidadId":"u01","drugIds":[]},
    "c01_11": {"id":"c01_11","nombre":"Ansiolíticos y Sedantes","unidadId":"u01","drugIds":[]},
    "c01_12": {"id":"c01_12","nombre":"Neurofármacos Especiales","unidadId":"u01","drugIds":[]},
    "c01_13": {"id":"c01_13","nombre":"Fármacos para Adicciones","unidadId":"u01","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U01b: Sistema Nervioso (part B) ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u01", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
