#!/usr/bin/env python3
"""Supplement: add ~60 more drugs for units with small gaps (U01, U05, U06, U08, U09)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── U01 (+18): fill to ~207 ──
M("opioide","tapentadol","Tapentadol","Tapentadol",["Palexia","Nucynta"],"Opioide dual MOR-NRI",
  "Agonista mu opioide + inhibidor de recaptación de noradrenalina. Mecanismo dual para dolor nociceptivo y neuropático",
  ["Dolor crónico moderado-severo","Dolor neuropático","Dolor oncológico"],["oral"],
  {"adulto":"Liberación inmediata: 50-100 mg c/4-6h. Retardado: 50-250 mg c/12h"},
  ["Comp 50, 100 mg","Comp retard 50, 100, 150, 200, 250 mg"],"Evitar durante lactancia","u01","c01_01"),

M("opioide","meperidina","Meperidina (Petidina)","Meperidina",["Demerol"],"Opioide fenilpiperidínico",
  "Agonista mu con débil efecto anticolinérgico. Metabolito neurotóxico normeperidina se acumula en IR",
  ["Dolor agudo moderado-severo","Tiritona post-anestésica","Rigidez por anfotericina B"],["oral","IV","IM"],
  {"adulto":"50-100 mg IM/IV c/3-4h. Oral: 50-150 mg c/3-4h","ajusteRenal":"CONTRAINDICADO en IR (normeperidina)"},
  ["Comp 50 mg","Amp 50, 100 mg/mL"],"Evitar durante lactancia","u01","c01_01",
  pp={"velocidadAdministracion":"IV lento en 2-3 min","estabilidad":"TA"}),

M("anticonvulsivante","brivaracetam","Brivaracetam","Brivaracetam",["Briviact"],"Análogo de levetiracetam",
  "Alta afinidad selectiva por proteína SV2A. Análogo más potente del levetiracetam con menor irritabilidad",
  ["Epilepsia focal como coadyuvante"],["oral","IV"],
  {"adulto":"50-200 mg/día en 2 tomas. IV: misma dosis"},
  ["Comp 25, 50, 75, 100 mg","Sol oral","Vial 50 mg/5 mL"],"Evitar durante lactancia","u01","c01_03",
  pp={"velocidadAdministracion":"Bolo IV en 2 min o infusión en 15 min","estabilidad":"24h a TA diluido"}),

M("anticonvulsivante","perampanel","Perampanel","Perampanel",["Fycompa"],"Antagonista AMPA no competitivo",
  "Primer antagonista selectivo no competitivo del receptor AMPA de glutamato. Mecanismo único antiepiléptico",
  ["Epilepsia focal","Crisis tónico-clónicas generalizadas (coadyuvante)"],["oral"],
  {"adulto":"Inicio: 2 mg/día al acostarse. Titular 2 mg/sem. Mantenimiento: 4-12 mg/día"},
  ["Comp 2, 4, 6, 8, 10, 12 mg"],"Evitar durante lactancia","u01","c01_03"),

M("anticonvulsivante","lacosamida","Lacosamida","Lacosamida",["Vimpat"],"Antiepiléptico bloqueador de Na+ (inactivación lenta)",
  "Potencia selectivamente la inactivación lenta de canales de Na+ voltaje-dependientes (mecanismo único)",
  ["Epilepsia focal como monoterapia o coadyuvante","Status epiléptico (off-label)"],["oral","IV"],
  {"adulto":"Inicio: 50 mg c/12h. Titular 100 mg/sem. Mantenimiento: 100-200 mg c/12h"},
  ["Comp 50, 100, 150, 200 mg","Jarabe 10 mg/mL","Vial 200 mg/20 mL"],"Evitar durante lactancia","u01","c01_03",
  pp={"velocidadAdministracion":"Infusión en 15-60 min. Bolo posible en 15 min","estabilidad":"24h a TA"}),

M("antipsicotico","brexpiprazol","Brexpiprazol","Brexpiprazol",["Rexulti"],"Antipsicótico atípico agonista parcial D2",
  "Agonista parcial D2 y 5-HT1A, antagonista 5-HT2A. Similar a aripiprazol con menor acatisia",
  ["Esquizofrenia","Coadyuvante en depresión mayor","Agitación en Alzheimer"],["oral"],
  {"adulto":"Esquizofrenia: 1-4 mg/día. Depresión: 0.5-3 mg/día"},
  ["Comp 0.25, 0.5, 1, 2, 3, 4 mg"],"Evitar durante lactancia","u01","c01_05"),

M("antidepresivo_isrs","vilazodona","Vilazodona","Vilazodona",["Viibryd"],"ISRS + agonista parcial 5-HT1A",
  "Inhibidor selectivo de recaptación de serotonina con agonismo parcial 5-HT1A. Menor disfunción sexual que ISRS clásicos",
  ["Trastorno depresivo mayor"],["oral"],
  {"adulto":"Inicio: 10 mg/día x7d, luego 20 mg/día x7d, mantenimiento 40 mg/día. Con alimentos"},
  ["Comp 10, 20, 40 mg"],"Evitar durante lactancia","u01","c01_06"),

M("antidepresivo_isrs","vortioxetina","Vortioxetina","Vortioxetina",["Brintellix","Trintellix"],"Antidepresivo multimodal",
  "Inhibidor de recaptación de serotonina + agonista 5-HT1A + antagonista 5-HT3/5-HT7. Beneficio cognitivo",
  ["Trastorno depresivo mayor","Depresión con déficit cognitivo"],["oral"],
  {"adulto":"5-20 mg/día. Inicio 10 mg/día"},
  ["Comp 5, 10, 15, 20 mg"],"Evitar durante lactancia","u01","c01_06"),

M("","pramipexol","Pramipexol","Pramipexol",["Mirapex","Sifrol"],"Agonista dopaminérgico D3 preferente",
  "Agonista selectivo D2/D3 con preferencia por D3. No requiere metabolismo hepático. Excreción renal",
  ["Enfermedad de Parkinson","Síndrome de piernas inquietas"],["oral"],
  {"adulto":"PD: inicio 0.125 mg c/8h, titular hasta 0.5-1.5 mg c/8h. SPI: 0.125-0.5 mg 2-3h antes de acostarse"},
  ["Comp 0.125, 0.25, 0.5, 1, 1.5 mg","Comp liberación prolongada 0.375-4.5 mg"],"Evitar durante lactancia","u01","c01_04",
  ci=["Hipersensibilidad"],
  ea=["Somnolencia diurna excesiva","Náuseas","Hipotensión ortostática","Alucinaciones","Trastorno del control de impulsos","Edema"],
  ix=["Antipsicóticos: antagonismo","Metoclopramida: antagonismo","Cimetidina: aumenta niveles 50%"],
  ce=["Advertir sobre somnolencia súbita (no conducir)","Vigilar control de impulsos (ludopatía, compras, hipersexualidad)","Ajustar en IR","No suspender bruscamente"],
  emb="C"),

M("","ropinirol","Ropinirol","Ropinirol",["Requip"],"Agonista dopaminérgico D2/D3",
  "Agonista dopaminérgico no ergótico. Alta afinidad D3. Metabolismo hepático CYP1A2",
  ["Enfermedad de Parkinson","Síndrome de piernas inquietas"],["oral"],
  {"adulto":"PD: inicio 0.25 mg c/8h, titular hasta 3-8 mg c/8h. SPI: 0.25-4 mg antes de dormir"},
  ["Comp 0.25, 0.5, 1, 2, 5 mg","Comp LP 2, 4, 8 mg"],"Evitar durante lactancia","u01","c01_04",
  ci=["Hipersensibilidad"],
  ea=["Náuseas","Somnolencia","Hipotensión ortostática","Alucinaciones","Trastorno impulsos","Discinesias"],
  ix=["Ciprofloxacino: aumenta niveles (CYP1A2)","Tabaco: disminuye niveles","Antipsicóticos: antagonismo"],
  ce=["CYP1A2: ajustar si fuma o deja de fumar","Vigilar control de impulsos","Titular gradualmente","No suspender bruscamente"],
  emb="C"),

M("","memantina","Memantina","Memantina",["Ebixa","Namenda"],"Antagonista NMDA para demencia",
  "Antagonista no competitivo del receptor NMDA. Bloquea excitotoxicidad glutamatérgica sin afectar neurotransmisión normal",
  ["Alzheimer moderado a severo","Demencia vascular (off-label)"],["oral"],
  {"adulto":"Inicio: 5 mg/día. Aumentar 5 mg/sem. Mantenimiento: 10 mg c/12h","ajusteRenal":"Máx 5 mg c/12h si ClCr 5-29"},
  ["Comp 5, 10, 20 mg","Sol oral 2 mg/mL"],"Evitar durante lactancia","u01","c01_07",
  ci=["Hipersensibilidad"],
  ea=["Mareo","Cefalea","Estreñimiento","Confusión","Somnolencia"],
  ix=["Amantadina: efectos aditivos","Dextrometorfano: precaución","Alcalinizantes urinarios: aumentan niveles"],
  ce=["Puede combinarse con donepezilo","Ajustar en IR","Titular gradualmente en 4 semanas","Beneficio modesto pero significativo"],
  emb="B"),

M("","galantamina","Galantamina","Galantamina",["Reminyl"],"Inhibidor de AChE + modulador nicotínico",
  "Inhibidor reversible de acetilcolinesterasa + modulador alostérico de receptores nicotínicos. Mecanismo dual",
  ["Alzheimer leve a moderado"],["oral"],
  {"adulto":"Inicio: 4 mg c/12h x4 sem. Luego 8 mg c/12h x4 sem. Mantenimiento: 12 mg c/12h"},
  ["Comp 4, 8, 12 mg","Cáps LP 8, 16, 24 mg","Sol oral 4 mg/mL"],"Evitar durante lactancia","u01","c01_07",
  ci=["Insuficiencia hepática grave","IR severa (ClCr <9)","Hipersensibilidad"],
  ea=["Náuseas","Vómitos","Diarrea","Anorexia","Mareo","Bradicardia","Pérdida peso"],
  ix=["Anticolinérgicos: antagonismo","Betabloqueantes: bradicardia aditiva","Inhibidores CYP2D6/3A4: aumentan niveles"],
  ce=["Titular gradualmente (reduce náuseas)","Tomar con alimentos","Monitorizar peso","No combinar con anticolinérgicos"],
  emb="B"),

M("","rivastigmina","Rivastigmina","Rivastigmina",["Exelon"],"Inhibidor dual AChE/BuChE",
  "Inhibe tanto acetilcolinesterasa como butirilcolinesterasa. Disponible en parche transdérmico (menos efectos GI)",
  ["Alzheimer leve a moderado","Demencia asociada a Parkinson"],["oral","transdermica"],
  {"adulto":"Oral: 1.5 mg c/12h, titular hasta 6 mg c/12h. Parche: 4.6→9.5→13.3 mg/24h"},
  ["Cáps 1.5, 3, 4.5, 6 mg","Parche 4.6, 9.5, 13.3 mg/24h"],"Evitar durante lactancia","u01","c01_07",
  ci=["Hipersensibilidad a carbamatos"],
  ea=["Náuseas","Vómitos","Diarrea","Anorexia","Dermatitis en sitio de parche","Bradicardia"],
  ix=["Anticolinérgicos: antagonismo","Betabloqueantes: bradicardia","Succinilcolina: prolonga bloqueo"],
  ce=["Parche: menos náuseas que oral","Rotar sitio del parche (no repetir en 14 días)","Titular cada 4 semanas mínimo","Con alimentos si oral"],
  emb="B"),

M("","donepezilo","Donepezilo","Donepezilo",["Aricept"],"Inhibidor selectivo de AChE",
  "Inhibidor reversible selectivo de acetilcolinesterasa. T½ larga permite dosis única diaria. El más usado para Alzheimer",
  ["Alzheimer leve, moderado y severo"],["oral"],
  {"adulto":"5 mg/día x4-6 sem, luego 10 mg/día. Severo: 23 mg/día"},
  ["Comp 5, 10 mg","Comp bucodispersable 5, 10 mg"],"Evitar durante lactancia","u01","c01_07",
  ci=["Hipersensibilidad a piperidinas"],
  ea=["Náuseas","Diarrea","Insomnio","Calambres musculares","Bradicardia","Anorexia"],
  ix=["Anticolinérgicos: antagonismo","Betabloqueantes: bradicardia","AINE: mayor riesgo ulcus"],
  ce=["Dosis única nocturna","Puede combinar con memantina","Monitorizar FC y peso","Efecto modesto pero demostrado"],
  emb="C"),

M("","cannabidiol","Cannabidiol (CBD)","Cannabidiol",["Epidiolex"],"Cannabinoide antiepiléptico",
  "Componente no psicoactivo del cannabis. Mecanismo antiepiléptico no completamente elucidado (múltiples dianas moleculares)",
  ["Síndrome de Dravet","Síndrome de Lennox-Gastaut","Esclerosis tuberosa (epilepsia)"],["oral"],
  {"adulto":"Inicio: 2.5 mg/kg c/12h. Mantenimiento: 5-10 mg/kg c/12h"},
  ["Sol oral 100 mg/mL"],"Evitar durante lactancia","u01","c01_03",
  ci=["Hipersensibilidad"],
  ea=["Somnolencia","Diarrea","Hepatotoxicidad","Disminución de apetito","Fatiga","Elevación transaminasas"],
  ix=["Valproato: mayor riesgo hepatotoxicidad","Clobazam: aumenta niveles de norclobazam","Inductores CYP: reducen niveles"],
  ce=["Función hepática basal, mensual x6 meses, luego trimestral","Especial precaución con valproato (hepatotoxicidad)","Almacenar a TA","Requiere prescripción especial en muchos países"],
  emb="C"),

M("","esketamina","Esketamina","Esketamina",["Spravato"],"Antidepresivo nasal de acción rápida",
  "Enantiómero S de ketamina. Antagonista NMDA. Acción antidepresiva rápida (horas vs semanas de ISRS)",
  ["Depresión resistente a tratamiento","Ideación suicida aguda (con antidepresivo oral)"],["nasal"],
  {"adulto":"56-84 mg intranasal, supervisado en centro. 2 veces/sem x4 sem, luego semanal, luego quincenal"},
  ["Spray nasal 28 mg/dispositivo"],"Evitar durante lactancia","u01","c01_06",
  ci=["Enfermedad vascular aneurismática","HTA no controlada","Hemorragia intracerebral reciente"],
  ea=["Disociación","Mareo","Náuseas","Sedación","HTA transitoria","Ansiedad","Cefalea","Abuso potencial"],
  ix=["Depresores SNC: sedación aditiva","IMAO: precaución","Psicoestimulantes: HTA"],
  ce=["Administración SUPERVISADA en centro certificado","Monitorizar PA y estado mental 2h post-dosis","No conducir hasta el día siguiente","Programa REMS obligatorio en USA"],
  emb="N/A"),

M("benzodiacepina","clobazam","Clobazam","Clobazam",["Onfi","Frisium"],"Benzodiazepina 1,5 antiepiléptica",
  "Benzodiazepina 1,5 (no 1,4). Menos sedación que otras BZD. Coadyuvante antiepiléptico especialmente en Lennox-Gastaut",
  ["Síndrome de Lennox-Gastaut (coadyuvante)","Epilepsia refractaria (coadyuvante)"],["oral"],
  {"adulto":"Inicio: 5-10 mg/día. Mantenimiento: 20-40 mg/día en 1-2 tomas","pediatrico":"≥2 años: 5 mg/día, titular hasta 20-40 mg/día"},
  ["Comp 5, 10, 20 mg","Susp oral 2.5 mg/mL"],"Evitar durante lactancia","u01","c01_03"),

# ── U05 (+15) ──
M("ibp","dexlansoprazol","Dexlansoprazol","Dexlansoprazol",["Dexilant"],"IBP de liberación dual retardada",
  "R-enantiómero de lansoprazol con sistema de liberación dual: 2 picos de actividad. Puede tomarse sin relación con comidas",
  ["ERGE","Esofagitis erosiva","Mantenimiento de cicatrización esofágica"],["oral"],
  {"adulto":"ERGE: 30 mg/día. Esofagitis: 60 mg/día x8 sem"},
  ["Cáps 30, 60 mg"],"Evitar durante lactancia","u05","c05_01"),

M("ibp","rabeprazol","Rabeprazol","Rabeprazol",["Aciphex","Pariet"],"IBP con activación rápida a pH más alto",
  "IBP que se activa a pH más alto que otros (hasta pH 5). Menos dependiente del polimorfismo CYP2C19",
  ["ERGE","Úlcera péptica","H. pylori (en triple terapia)","Zollinger-Ellison"],["oral"],
  {"adulto":"20 mg/día (úlcera/ERGE). Zollinger-Ellison: 60-120 mg/día"},
  ["Comp 10, 20 mg"],"Evitar durante lactancia","u05","c05_01"),

M("","loperamida","Loperamida","Loperamida",["Imodium"],"Antidiarreico opioide periférico",
  "Agonista opioide mu periférico. No cruza BHE a dosis terapéuticas. Reduce motilidad y secreción intestinal",
  ["Diarrea aguda no infecciosa","Diarrea crónica","Ileostomía (reducción volumen)"],["oral"],
  {"adulto":"Aguda: 4 mg inicial, luego 2 mg tras cada deposición. Máx 16 mg/día","pediatrico":"No recomendado <2 años"},
  ["Comp 2 mg","Cáps 2 mg"],"Compatible con precaución","u05","c05_09",
  ci=["Diarrea sanguinolenta","Colitis por C. difficile","Obstrucción intestinal","Niños <2 años"],
  ea=["Estreñimiento","Dolor abdominal","Distensión","Náuseas","Mareo","Íleo (sobredosis)"],
  ix=["Quinidina/ritonavir: aumentan niveles (inhiben P-gp)","Opioides: estreñimiento aditivo"],
  ce=["No usar en disentería (retiene toxinas)","Máx 48h en diarrea aguda sin mejoría","Sobredosis: depresión SNC en niños","No requiere receta en muchos países"],
  emb="B"),

M("","ranitidina","Ranitidina","Ranitidina",["Zantac"],"Antagonista H2 (retirada en muchos países)",
  "Antagonista competitivo del receptor H2 de histamina. Reduce secreción ácida basal y estimulada. Retirada por NDMA",
  ["Úlcera péptica (histórico)","ERGE leve","Profilaxis de úlcera por estrés"],["oral","IV"],
  {"adulto":"Oral: 150 mg c/12h o 300 mg/noche. IV: 50 mg c/6-8h"},
  ["Comp 150, 300 mg","Amp 50 mg/2 mL"],"Compatible con precaución","u05","c05_01",
  ci=["Hipersensibilidad","Porfiria (relativa)"],
  ea=["Cefalea","Mareo","Diarrea/estreñimiento","Trombocitopenia (raro)","Ginecomastia (uso prolongado)"],
  ix=["Ketoconazol/itraconazol: reduce absorción","Warfarina: puede aumentar INR"],
  ce=["RETIRADA del mercado en 2020 por contaminación con NDMA","Famotidina es alternativa H2 preferida","Si aún disponible: uso a corto plazo","Ajustar en IR"],
  emb="B",
  pp={"dilucion":"Diluir 50 mg en 20 mL SF","velocidadAdministracion":"IV lento en 5 min o infusión en 15-20 min","estabilidad":"48h refrigerado"}),

M("antiemetico","domperidona","Domperidona","Domperidona",["Motilium"],"Procinético antagonista D2 periférico",
  "Antagonista dopaminérgico D2 que no cruza BHE significativamente. Antiemético y procinético con mínimos efectos extrapiramidales",
  ["Náuseas y vómitos","Gastroparesia","Reflujo"],["oral"],
  {"adulto":"10 mg c/8h antes de comidas. Máx 30 mg/día. Máx 7 días"},
  ["Comp 10 mg","Susp 1 mg/mL"],"Compatible con precaución","u05","c05_02",
  ci=["Prolactinoma","Hemorragia GI","Obstrucción","Prolongación QT","Insuficiencia hepática moderada-grave"],
  ea=["Galactorrea","Ginecomastia","Amenorrea","Prolongación QT","Cefalea","Boca seca"],
  ix=["Ketoconazol/eritromicina: aumentan niveles y riesgo QT","Fármacos que prolongan QT: contraindicado"],
  ce=["Máximo 30 mg/día y 7 días (riesgo cardíaco)","No usar con prolongadores de QT","ECG previo en mayores de 60","Menos efectos extrapiramidales que metoclopramida"],
  emb="C"),

M("","pancreatina","Pancreatina","Pancreatina (enzimas pancreáticas)",["Creon","Kreon"],"Suplemento enzimático pancreático",
  "Mezcla de lipasa, amilasa y proteasa porcinas. Suple función exocrina pancreática. Cápsulas con microesferas entéricas",
  ["Insuficiencia pancreática exocrina","Fibrosis quística","Pancreatitis crónica","Post-pancreatectomía"],["oral"],
  {"adulto":"25,000-75,000 U lipasa/comida, 10,000-25,000 U/snack. Titular según esteatorrea"},
  ["Cáps 10,000, 25,000, 40,000 U lipasa"],"Compatible","u05","c05_07",
  ci=["Hipersensibilidad a proteínas porcinas"],
  ea=["Dolor abdominal","Náuseas","Diarrea","Colonopatía fibrosante (dosis muy altas)","Hiperuricemia"],
  ix=["Antiácidos: pueden degradar capa entérica","Acarbosa: reduce eficacia"],
  ce=["Tomar al INICIO de cada comida","No triturar las microesferas","Titular según grasa en heces","Máx 10,000 U lipasa/kg/día (colonopatía fibrosante)","Almacenar a TA"],
  emb="B"),

M("","ácido_ursodeoxicólico","Ácido ursodeoxicólico","Ácido ursodeoxicólico",["Ursofalk","Actigall"],"Ácido biliar hepatoprotector",
  "Ácido biliar hidrofílico. Desplaza ácidos biliares tóxicos hidrofóbicos. Citoprotector, inmunomodulador y colerético",
  ["Cirrosis biliar primaria","Colangitis esclerosante","Cálculos biliares de colesterol","Colestasis del embarazo"],["oral"],
  {"adulto":"CBP: 13-15 mg/kg/día en 2-4 tomas. Litiasis: 8-10 mg/kg/día"},
  ["Cáps 250, 300 mg","Comp 500 mg"],"Compatible con precaución","u05","c05_04",
  ci=["Cálculos biliares calcificados","Vesícula no funcionante","Obstrucción biliar completa"],
  ea=["Diarrea","Dolor abdominal","Calcificación de cálculos","Prurito (transitorio al inicio)"],
  ix=["Colestiramina: reduce absorción (separar 2h)","Ciclosporina: puede aumentar niveles"],
  ce=["Tomar con alimentos","Tratamiento de litiasis: 6-24 meses","Ecografía de control cada 6 meses","En CBP: tratamiento de por vida"],
  emb="B"),

M("","sulfasalazina","Sulfasalazina","Sulfasalazina",["Azulfidine","Salazopyrin"],"Aminosalicilato pro-droga",
  "Pro-droga: bacterias colónicas liberan 5-ASA (antiinflamatorio local) y sulfapiridina. Doble acción: EII y AR",
  ["Colitis ulcerosa leve-moderada","Enfermedad de Crohn colónica","Artritis reumatoide"],["oral"],
  {"adulto":"EII: 1-2 g c/6-8h (mantenimiento 500 mg c/6h). AR: 500-1000 mg c/12h"},
  ["Comp 500 mg","Comp entérico 500 mg"],"Evitar durante lactancia","u05","c05_06",
  ci=["Alergia a sulfonamidas o salicilatos","Porfiria","Obstrucción intestinal/urinaria","Déficit G6PD"],
  ea=["Cefalea","Náuseas","Anorexia","Oligospermia reversible","Coloración naranja de orina","Rash","Agranulocitosis (raro)"],
  ix=["Digoxina: reduce absorción","Ácido fólico: reduce absorción","Warfarina: puede aumentar efecto"],
  ce=["Suplementar ácido fólico 1 mg/día","Hemograma c/2-4 semanas x3 meses, luego trimestral","Coloración naranja de orina/lágrimas (avisar)","Buena hidratación"],
  emb="B"),

M("","mesalazina","Mesalazina (5-ASA)","Mesalazina",["Pentasa","Asacol","Salofalk"],"Aminosalicilato de acción local",
  "5-ASA puro (sin sulfapiridina). Antiinflamatorio local en mucosa colónica. Formulaciones de liberación específica",
  ["Colitis ulcerosa (inducción y mantenimiento)","Enfermedad de Crohn leve"],["oral","rectal"],
  {"adulto":"Oral: 2.4-4.8 g/día. Rectal: sup 500 mg-1g/día o enema 1-4 g/noche"},
  ["Comp 400, 500 mg, 1 g","Granulado 1, 2 g","Sup 250, 500 mg, 1 g","Enema 1, 2, 4 g"],"Compatible con precaución","u05","c05_06",
  ci=["Alergia a salicilatos","IR severa","Insuficiencia hepática severa"],
  ea=["Cefalea","Náuseas","Diarrea","Dolor abdominal","Nefritis intersticial (raro)","Pancreatitis (raro)"],
  ix=["Azatioprina/6-MP: aumenta mielosupresión","Warfarina: posible aumento de efecto"],
  ce=["Creatinina y orina pre-inicio y c/6 meses","Menos efectos que sulfasalazina","Formulación determina sitio de liberación","Sin efecto sobre fertilidad masculina (ventaja vs sulfasalazina)"],
  emb="B"),

M("","bismuto_subsalicilato","Bismuto subsalicilato","Bismuto subsalicilato",["Pepto-Bismol"],"Protector gástrico y antidiarreico",
  "Efecto antisecretor, antiinflamatorio local y bactericida. Componente de cuádruple terapia anti-H. pylori",
  ["Diarrea aguda","Dispepsia","Cuádruple terapia H. pylori (con tetraciclina, metronidazol, IBP)"],["oral"],
  {"adulto":"525 mg c/30 min hasta 8 dosis. H. pylori: 524 mg c/6h x14d"},
  ["Comp 262 mg","Susp 262 mg/15 mL"],"Evitar durante lactancia","u05","c05_01",
  ci=["Alergia a salicilatos","Niños con fiebre (Reye)","Uso de anticoagulantes","Insuficiencia renal"],
  ea=["Heces y lengua negras (benigno)","Estreñimiento","Tinnitus (dosis altas)"],
  ix=["Tetraciclinas: reduce absorción","Anticoagulantes: riesgo sangrado (salicilato)"],
  ce=["Lengua y heces negras son normales (sulfuro de bismuto)","Suspender si tinnitus","No en niños con fiebre (riesgo Reye)","Cuádruple terapia: efectiva en resistencia a claritromicina"],
  emb="C"),

# ── U06 (+15) ──
M("antidiabetico_oral","linagliptina","Linagliptina","Linagliptina",["Tradjenta"],"Inhibidor DPP-4 sin ajuste renal",
  "Inhibidor de dipeptidil peptidasa-4 (DPP-4). Único iDPP-4 que no requiere ajuste renal (excreción biliar)",
  ["DM tipo 2 como mono o terapia combinada"],["oral"],
  {"adulto":"5 mg/día"},["Comp 5 mg"],"Evitar durante lactancia","u06","c06_01"),

M("antidiabetico_oral","saxagliptina","Saxagliptina","Saxagliptina",["Onglyza"],"Inhibidor DPP-4",
  "Inhibidor selectivo de DPP-4. Prolonga acción de incretinas GLP-1 y GIP endógenas",
  ["DM tipo 2"],["oral"],
  {"adulto":"2.5-5 mg/día","ajusteRenal":"2.5 mg/día si ClCr ≤50"},
  ["Comp 2.5, 5 mg"],"Evitar durante lactancia","u06","c06_01"),

M("insulina","insulina_aspart","Insulina Aspart","Insulina aspart",["NovoRapid","Fiasp"],"Insulina ultrarrápida",
  "Análogo de insulina con sustitución B28 Pro→Asp. Inicio más rápido que regular. Fiasp: formulación ultrarrápida con niacinamida",
  ["DM tipo 1 y 2: cobertura prandial","Bombas de insulina"],["SC","IV"],
  {"adulto":"Individualizar según glucemia. Típico: 0.05-0.1 UI/kg/comida","pediatrico":"≥2 años: misma indicación"},
  ["Vial 100 UI/mL","FlexPen 100 UI/mL","PumpCart 100 UI/mL"],"Compatible con precaución","u06","c06_01"),

M("insulina","insulina_glargina","Insulina Glargina","Insulina glargina",["Lantus","Toujeo"],"Insulina basal de 24h",
  "Análogo de insulina con pH 4 que precipita al pH fisiológico SC formando depósito de liberación lenta. Duración ~24h sin pico",
  ["DM tipo 1 y 2: cobertura basal"],["SC"],
  {"adulto":"Inicio: 10 UI/día o 0.2 UI/kg/día. Titular según glucemia en ayunas"},
  ["Lantus: 100 UI/mL pen, vial","Toujeo: 300 UI/mL pen"],"Compatible con precaución","u06","c06_01"),

M("","liraglutida","Liraglutida","Liraglutida",["Victoza","Saxenda"],"Agonista GLP-1 de acción prolongada",
  "Análogo de GLP-1 (97% homología) unido a albumina. Secreción insulina glucosa-dependiente + saciedad + retrasa vaciamiento gástrico",
  ["DM tipo 2 (Victoza: 1.8 mg/día)","Obesidad (Saxenda: 3 mg/día)","Reducción riesgo cardiovascular en DM2"],["SC"],
  {"adulto":"DM: inicio 0.6 mg/día x1 sem, luego 1.2 mg, máx 1.8 mg. Obesidad: titular hasta 3 mg/día"},
  ["Pen 6 mg/mL (Victoza)","Pen 6 mg/mL (Saxenda)"],"Evitar durante lactancia","u06","c06_01",
  ci=["Carcinoma medular de tiroides personal/familiar","NEM tipo 2","Hipersensibilidad"],
  ea=["Náuseas","Vómitos","Diarrea","Pancreatitis (raro)","Colelitiasis","Pérdida de peso"],
  ix=["Insulina/sulfonilureas: mayor riesgo hipoglucemia (reducir dosis)","Retrasa vaciamiento: puede afectar absorción de otros orales"],
  ce=["Titular gradualmente (reduce náuseas)","Monitorizar lipasa/amilasa si dolor abdominal","No usar en DM tipo 1","Pérdida de peso: beneficio adicional"],
  emb="X"),

M("","levotiroxina","Levotiroxina","Levotiroxina (T4)",["Eutirox","Synthroid"],"Hormona tiroidea sintética",
  "T4 sintética idéntica a la endógena. Se convierte a T3 activa. Vida media 7 días permite dosis única diaria",
  ["Hipotiroidismo","Supresión TSH en cáncer tiroideo","Mixedema comatoso"],["oral","IV"],
  {"adulto":"Hipotiroidismo: inicio 25-50 mcg/día (jóvenes: 1.6 mcg/kg/día). Cáncer: 2-2.5 mcg/kg/día","pediatrico":"10-15 mcg/kg/día (neonatal)","geriatrico":"Inicio 12.5-25 mcg/día"},
  ["Comp 25, 50, 75, 88, 100, 112, 125, 137, 150, 175, 200 mcg","Vial 200, 500 mcg"],"Compatible","u06","c06_02",
  ci=["Tirotoxicosis no tratada","IAM agudo (relativa)","Insuficiencia adrenal no corregida"],
  ea=["Hipertiroidismo (sobredosis)","Taquicardia","Arritmias","Osteoporosis (supresión excesiva)","Angina"],
  ix=["Hierro/calcio/antiácidos: reducen absorción (separar 4h)","Warfarina: aumenta efecto","Colestiramina: reduce absorción"],
  ce=["Tomar en AYUNAS 30-60 min antes del desayuno","TSH c/6-8 semanas hasta estable, luego anual","Separar 4h de hierro/calcio/antiácidos","En mixedema: 200-500 mcg IV carga"],
  emb="A",
  pp={"reconstitucion":"Reconstituir con SF","velocidadAdministracion":"IV lento","estabilidad":"4h a TA"}),

M("","metimazol","Metimazol (Tiamazol)","Metimazol",["Tapazol","Thyrozol"],"Antitiroideo",
  "Inhibe TPO (tiroperoxidasa) bloqueando síntesis de T3/T4. No afecta hormona ya liberada. Inicio efecto 1-2 semanas",
  ["Hipertiroidismo (Graves, bocio multinodular tóxico)","Preparación pre-tiroidectomía","Crisis tirotóxica"],["oral"],
  {"adulto":"Inicio: 15-30 mg/día (leve: 5-10 mg/día). Mantenimiento: 5-15 mg/día"},
  ["Comp 5, 10 mg"],"Evitar durante lactancia (preferir PTU si necesario)","u06","c06_02",
  ci=["Hipersensibilidad","Embarazo primer trimestre (usar PTU)"],
  ea=["Agranulocitosis (0.2-0.5%)","Rash","Artralgia","Hepatotoxicidad colestásica","Hipotiroidismo"],
  ix=["Warfarina: inicialmente aumenta efecto (metabolismo T4)","Betabloqueantes: ajustar al normalizar función"],
  ce=["Hemograma si fiebre o faringitis (agranulocitosis)","Función tiroidea c/4-6 semanas","PTU preferido en 1er trimestre embarazo","Avisar: consultar URGENTE si fiebre con faringitis"],
  emb="D"),

M("","propiltiouracilo","Propiltiouracilo (PTU)","Propiltiouracilo",["PTU"],"Antitiroideo (1er trimestre embarazo)",
  "Inhibe TPO + inhibe conversión periférica T4→T3 (ventaja en tormenta tiroidea). Hepatotoxicidad limita uso a situaciones específicas",
  ["Hipertiroidismo en 1er trimestre embarazo","Tormenta tiroidea","Alergia a metimazol"],["oral"],
  {"adulto":"Inicio: 100-200 mg c/8h. Tormenta: 200-300 mg c/6h. Mantenimiento: 50-100 mg c/8-12h"},
  ["Comp 50 mg"],"Evitar durante lactancia","u06","c06_02",
  ci=["Hepatopatía","Hipersensibilidad"],
  ea=["Hepatotoxicidad fulminante (boxed warning)","Agranulocitosis","Vasculitis ANCA","Rash","Artralgia"],
  ix=["Warfarina: interacción variable","Betabloqueantes: ajustar"],
  ce=["Solo 1er trimestre embarazo o tormenta tiroidea (hepatotoxicidad)","Función hepática basal y ante síntomas","Cambiar a metimazol en 2do trimestre","Hemograma si fiebre"],
  emb="D"),

M("corticoide_sistemico","fludrocortisona","Fludrocortisona","Fludrocortisona",["Florinef"],"Mineralocorticoide sintético",
  "Análogo de cortisol con potente actividad mineralocorticoide (100-200x cortisol). Retiene Na+ y excreta K+",
  ["Insuficiencia adrenal primaria (Addison)","Hipotensión ortostática severa","Hiperplasia suprarrenal congénita"],["oral"],
  {"adulto":"0.05-0.2 mg/día (Addison). Ortostatismo: 0.1-0.3 mg/día"},
  ["Comp 0.1 mg"],"Evitar durante lactancia","u06","c06_06",
  ci=["Hipertensión severa","Hipopotasemia no corregida","IC"],
  ea=["HTA","Hipopotasemia","Edema","Cefalea","Supresión adrenal"],
  ix=["Diuréticos: antagonismo mineral","IECA/ARA-II: pueden reducir efecto","AINEs: retención Na+ aditiva"],
  ce=["Monitorizar PA y K+ regularmente","Ajustar con ingesta de sal","Puede necesitar suplemento de K+","En Addison: siempre junto con hidrocortisona"],
  emb="C"),

M("","octreótida","Octreótida","Octreótida",["Sandostatin","Sandostatin LAR"],"Análogo de somatostatina",
  "Análogo octapeptídico de somatostatina 20-30x más potente. Inhibe GH, insulina, glucagón y secreciones GI",
  ["Acromegalia","Tumores neuroendocrinos","Varices esofágicas","Diarrea refractaria","Fístula pancreática"],["SC","IM"],
  {"adulto":"SC: 50-200 mcg c/8h. LAR: 20-30 mg IM c/4 semanas"},
  ["Amp 50, 100, 500 mcg/mL","Vial LAR 10, 20, 30 mg"],"Evitar durante lactancia","u06","c06_04",
  ci=["Hipersensibilidad"],
  ea=["Dolor abdominal","Diarrea/esteatorrea","Colelitiasis (30% en uso prolongado)","Hiperglucemia","Bradicardia","Hipotiroidismo"],
  ix=["Ciclosporina: reduce absorción","Insulina: ajustar dosis (altera glucemia)","Bromocriptina: aumenta biodisponibilidad"],
  ce=["Ecografía biliar anual (colelitiasis)","Monitorizar glucemia","LAR mensual permite mejor adherencia","Autoadministración SC: enseñar rotación sitios"],
  emb="B"),

# ── U08 (+6) ──
M("aine","piroxicam","Piroxicam","Piroxicam",["Feldene"],"AINE oxicam de larga duración",
  "Oxicam con vida media de 50h. Dosis única diaria. Inhibidor no selectivo COX-1/COX-2",
  ["Artritis reumatoide","Osteoartrosis","Espondilitis anquilosante","Dolor musculoesquelético"],["oral","topica"],
  {"adulto":"10-20 mg/día dosis única"},
  ["Cáps 10, 20 mg","Gel 0.5%"],"Evitar durante lactancia","u08","c08_01"),

M("aine","tenoxicam","Tenoxicam","Tenoxicam",["Tilcotil"],"AINE oxicam con t½ larga",
  "Oxicam de vida media 60-75h. Máxima concentración articular. Inhibidor no selectivo COX",
  ["Artritis reumatoide","Osteoartrosis","Gota aguda","Dolor post-quirúrgico"],["oral","IV","IM"],
  {"adulto":"20 mg/día. Gota aguda: 40 mg/día x2d, luego 20 mg/día x5d"},
  ["Comp 20 mg","Amp 20 mg"],"Evitar durante lactancia","u08","c08_01",
  pp={"velocidadAdministracion":"IV lento en 15 seg o IM profunda","estabilidad":"Usar inmediatamente"}),

M("","alopurinol","Alopurinol","Alopurinol",["Zyloprim","Zyloric"],"Inhibidor de xantina oxidasa",
  "Inhibe xantina oxidasa reduciendo producción de ácido úrico. Disminuye uricemia gradualmente",
  ["Gota crónica: prevención de crisis","Hiperuricemia","Profilaxis SLT","Litiasis úrica"],["oral"],
  {"adulto":"Inicio: 100 mg/día, titular 100 mg/mes. Mantenimiento: 200-600 mg/día. Máx 800 mg/día","ajusteRenal":"100 mg/día si ClCr <60, reducir según ClCr"},
  ["Comp 100, 300 mg"],"Compatible con precaución","u08","c08_03",
  ci=["Crisis gotosa aguda (no iniciar)","Hipersensibilidad (síndrome DRESS letal)"],
  ea=["Crisis gotosa al inicio","Rash (puede ser DRESS)","Hepatotoxicidad","Eosinofilia","Síndrome de hipersensibilidad grave"],
  ix=["Azatioprina/6-MP: aumenta toxicidad dramáticamente (reducir dosis 75%)","Ciclofosfamida: mayor mielosupresión","Amoxicilina/ampicilina: mayor riesgo rash"],
  ce=["Iniciar SOLO fuera de crisis aguda","Profilaxis colchicina 3-6 meses al iniciar","HLA-B*5801: predictor de DRESS (testar en grupos de riesgo)","Titular gradualmente","Evitar en crisis aguda (empeora)"],
  emb="C"),

M("","febuxostat","Febuxostat","Febuxostat",["Uloric","Adenuric"],"Inhibidor selectivo de xantina oxidasa",
  "Inhibidor no purínico selectivo de xantina oxidasa. No requiere ajuste renal leve-moderado",
  ["Hiperuricemia crónica en gota cuando alopurinol contraindicado o ineficaz"],["oral"],
  {"adulto":"40-80 mg/día"},["Comp 40, 80, 120 mg"],"Evitar durante lactancia","u08","c08_03",
  ci=["Uso con azatioprina/mercaptopurina","Hipersensibilidad"],
  ea=["Elevación transaminasas","Náuseas","Artralgia","Rash","Mayor riesgo cardiovascular vs alopurinol (CARES trial)"],
  ix=["Azatioprina/6-MP: contraindicado (misma interacción que alopurinol)","Teofilina: posible aumento niveles"],
  ce=["Reservar para intolerancia/fallo de alopurinol","Mayor riesgo CV: precaución en cardiópatas","Profilaxis colchicina al iniciar","Función hepática periódica"],
  emb="C"),

M("inmunosupresor","adalimumab","Adalimumab","Adalimumab",["Humira"],"Anti-TNFα humano completo",
  "Anticuerpo monoclonal 100% humano anti-TNFα. Primer anti-TNF completamente humano. Múltiples indicaciones autoinmunes",
  ["AR","Espondilitis anquilosante","Psoriasis","Artritis psoriásica","EII","Uveítis","Hidradenitis supurativa"],["SC"],
  {"adulto":"40 mg SC c/2 semanas. Puede aumentar a semanal en algunas indicaciones"},
  ["Jer precargada 40 mg/0.8 mL","Pen 40 mg"],"Evitar durante lactancia","u08","c08_04"),

M("inmunosupresor","etanercept","Etanercept","Etanercept",["Enbrel"],"Receptor soluble TNF (proteína de fusión)",
  "Proteína de fusión: porción Fc IgG1 + dominio extracelular receptor TNF p75. Neutraliza TNFα soluble y unido a membrana",
  ["AR","Artritis idiopática juvenil","Psoriasis","Espondilitis anquilosante","Artritis psoriásica"],["SC"],
  {"adulto":"50 mg SC semanal o 25 mg 2 veces/semana","pediatrico":"≥2 años: 0.8 mg/kg/semana (máx 50 mg)"},
  ["Jer precargada 25, 50 mg","Pen 50 mg"],"Evitar durante lactancia","u08","c08_04"),

# ── U09 (+5) ──
M("","isotretinoina","Isotretinoína","Isotretinoína",["Roaccutane","Accutane"],"Retinoide sistémico para acné severo",
  "Isómero 13-cis del ácido retinoico. Reduce producción de sebo, queratinización folicular, P. acnes y inflamación. Cura el acné",
  ["Acné nódulo-quístico severo","Acné resistente a tratamiento convencional","Acné con cicatrización"],["oral"],
  {"adulto":"0.5-1 mg/kg/día x16-20 semanas. Dosis acumulativa: 120-150 mg/kg"},
  ["Cáps 10, 20, 40 mg"],"CONTRAINDICADA en lactancia","u09","c09_04",
  ci=["EMBARAZO (categoría X: teratogénico severo)","Hipervitaminosis A","Hepatopatía","Hiperlipidemia severa","Tetraciclinas concomitantes"],
  ea=["Sequedad mucocutánea (labios, piel, ojos)","Queilitis","Epistaxis","Mialgias","Elevación TG y colesterol","Hepatotoxicidad","Teratogenicidad","Depresión/ideación suicida (controvertido)"],
  ix=["Tetraciclinas: pseudotumor cerebri","Vitamina A: hipervitaminosis","Metotrexato: hepatotoxicidad"],
  ce=["ANTICONCEPCIÓN OBLIGATORIA: 2 métodos 1 mes antes, durante y 1 mes después","Prueba embarazo mensual negativa","Perfil lipídico y hepático mensual","No donar sangre durante ni 1 mes después","Programa iPLEDGE en USA"],
  emb="X"),

M("corticoide_topico","mometasona_topica","Mometasona tópica","Mometasona furoato",["Elocon"],"Corticoide tópico de potencia media-alta",
  "Corticoide sintético con alta relación actividad tópica/sistémica. Potencia media-alta. Una aplicación diaria",
  ["Dermatitis atópica","Psoriasis","Eccema","Dermatitis de contacto"],["topica"],
  {"adulto":"Aplicar capa fina 1 vez al día"},
  ["Crema 0.1%","Ungüento 0.1%","Loción 0.1%"],"Compatible con precaución (uso tópico)","u09","c09_01"),

M("","tacrolimus_topico","Tacrolimus tópico","Tacrolimus",["Protopic"],"Inmunomodulador tópico",
  "Inhibidor de calcineurina. Suprime activación de linfocitos T sin atrofia cutánea. Alternativa a corticoides tópicos",
  ["Dermatitis atópica moderada-severa","Áreas sensibles (cara, pliegues) donde corticoides no recomendados"],["topica"],
  {"adulto":"0.1% dos veces al día. Reducir a mantenimiento 2 veces/semana"},
  ["Ungüento 0.03% (pediátrico)","Ungüento 0.1% (adulto)"],"Compatible con precaución","u09","c09_06",
  ci=["Síndrome de Netherton","Inmunodeficiencia","Eritrodermia generalizada"],
  ea=["Ardor/prurito al inicio (mejora en días)","Infecciones cutáneas","Intolerancia al alcohol (rubor)","Riesgo teórico linfoma (boxed warning)"],
  ix=["Inhibidores CYP3A4: posible absorción sistémica en piel dañada"],
  ce=["Ardor inicial: desaparece en 1 semana","No aplicar en piel infectada","Fotoprotección durante uso","Sin riesgo de atrofia cutánea (ventaja vs corticoides)","Mantenimiento proactivo 2x/sem en áreas recurrentes"],
  emb="C"),

M("","acitretina","Acitretina","Acitretina",["Soriatane","Neotigason"],"Retinoide sistémico para psoriasis",
  "Retinoide de 2ª generación. Regula diferenciación y proliferación epidérmica. Efecto sinérgico con fototerapia",
  ["Psoriasis severa en placas","Psoriasis pustulosa","Psoriasis eritrodérmica","Ictiosis"],["oral"],
  {"adulto":"25-50 mg/día con alimentos. Inicio 25 mg/día"},
  ["Cáps 10, 25 mg"],"CONTRAINDICADA en lactancia","u09","c09_04",
  ci=["Embarazo (teratogénico severo: anticoncepción 3 AÑOS post-uso)","Hepatopatía","Hiperlipidemia severa","Donación de sangre"],
  ea=["Sequedad mucocutánea","Queilitis","Alopecia","Hiperlipidemia","Hepatotoxicidad","Hiperostosis (largo plazo)","Teratogenicidad prolongada (3 años)"],
  ix=["Metotrexato: hepatotoxicidad","Tetraciclinas: pseudotumor cerebri","Vitamina A: toxicidad aditiva","ETANOL: convierte acitretina en etretinato (teratógeno por 3 años)"],
  ce=["Anticoncepción 3 AÑOS post-suspensión (se convierte en etretinato con alcohol)","NO consumir alcohol durante ni 2 meses después","Lípidos y función hepática c/1-2 meses","No donar sangre durante ni 3 años después"],
  emb="X"),

M("","calcipotriol","Calcipotriol","Calcipotriol (Calcipotriene)",["Daivonex","Dovonex"],"Análogo de vitamina D3 tópico",
  "Análogo sintético de vitamina D3. Inhibe proliferación de queratinocitos e induce diferenciación. Modulación inmune local",
  ["Psoriasis en placas leve a moderada","Psoriasis del cuero cabelludo"],["topica"],
  {"adulto":"Aplicar 2 veces al día. Máx 100 g/semana (riesgo hipercalcemia)"},
  ["Crema 50 mcg/g","Ungüento 50 mcg/g","Sol capilar 50 mcg/mL","Gel combinado con betametasona"],"Compatible con precaución","u09","c09_07",
  ci=["Hipercalcemia","Trastornos del metabolismo del calcio","No aplicar en cara"],
  ea=["Irritación local","Eritema","Sequedad","Prurito","Hipercalcemia (si excede dosis)","Dermatitis perilesional"],
  ix=["Ácido salicílico tópico: inactiva calcipotriol (no combinar)"],
  ce=["Máx 100 g/semana para evitar hipercalcemia","No aplicar en cara (irritación)","Combinación con betametasona: más eficaz","Calcemia si uso extenso o en IR"],
  emb="C"),
]

NEW_CHAPTERS = {}

if __name__ == "__main__":
    print("=== Supplement small units ===")
    added = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {added} drugs added.")
