#!/usr/bin/env python3
"""Add new drugs for U04 Sistema Respiratorio."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

DRUGS = [
# ── c04_01 Broncodilatadores (+7) ──
M("anticolinergico_inhalado","aclidinio","Aclidinio","Bromuro de aclidinio",["Tudorza","Eklira","Bretaris"],
  "Anticolinérgico inhalado de acción prolongada (LAMA)",
  "Antagonista muscarínico de acción prolongada con alta selectividad por receptores M3 bronquiales. Rápido inicio de acción vs tiotropio",
  ["EPOC (mantenimiento)","Broncoespasmo en EPOC"],["inhalatoria"],
  {"adulto":"400 mcg inhalados c/12h (Genuair/Pressair)","geriatrico":"No requiere ajuste de dosis"},
  ["Polvo para inhalación 400 mcg/dosis (dispositivo Genuair/Pressair)"],"Compatible con precaución","u04","c04_01",
  fk={"absorcion":"Biodisponibilidad pulmonar ~30%, oral <5%","metabolismo":"Hidrólisis plasmática rápida (no CYP)","eliminacion":"Renal 65%, fecal 33%","vidaMedia":"10-14 horas"},
  alm="Conservar a temperatura ambiente (≤25°C). No extraer del blíster hasta uso. Proteger de la humedad."),

M("broncodilatador_beta2","revefenacina","Revefenacina","Revefenacina",["Yupelri"],
  "Anticolinérgico de acción prolongada para nebulización (LAMA)",
  "Antagonista muscarínico de acción prolongada formulado para nebulización. Único LAMA en solución para nebulizar aprobado para EPOC",
  ["EPOC mantenimiento (pacientes que no pueden usar inhaladores de polvo seco)"],["inhalatoria"],
  {"adulto":"175 mcg nebulizados 1 vez al día","geriatrico":"No requiere ajuste"},
  ["Solución para nebulización 175 mcg/3 mL (vial unitario)"],"No recomendado","u04","c04_01",
  familia="Anticolinérgicos inhalados",
  ci=["Hipersensibilidad a revefenacina o ipratropio","Glaucoma de ángulo cerrado no tratado","Retención urinaria"],
  ea=["Tos","Nasofaringitis","Infección respiratoria superior","Cefalea","Dolor de espalda"],
  ce=["Único LAMA disponible para nebulización","Administrar con nebulizador jet estándar","No mezclar con otros fármacos en el nebulizador","Para pacientes con dificultad para usar inhaladores de mano"],
  fk={"absorcion":"Depósito pulmonar por nebulización","metabolismo":"Hidrólisis a metabolito activo","eliminacion":"Fecal 54%, renal 27%","vidaMedia":"22-70 horas"},
  alm="Refrigerar (2-8°C). Puede mantenerse a TA (≤25°C) hasta 4 semanas. Proteger de la luz."),

M("broncodilatador_beta2","olodaterol","Olodaterol","Olodaterol",["Striverdi"],
  "Beta-2 agonista de acción ultraprolongada (ultra-LABA)",
  "Agonista beta-2 adrenérgico de acción ultraprolongada con selectividad beta-2 superior al formoterol. Inicio de acción en 5 min, duración 24h",
  ["EPOC (mantenimiento)","Broncoespasmo en EPOC (no rescate)"],["inhalatoria"],
  {"adulto":"5 mcg (2 inhalaciones de 2.5 mcg) 1 vez al día mediante Respimat"},
  ["Solución para inhalación 2.5 mcg/dosis (dispositivo Respimat)"],"Compatible con precaución","u04","c04_01",
  fk={"absorcion":"Biodisponibilidad ~30% pulmonar","metabolismo":"Glucuronidación y CYP","eliminacion":"Renal 38%, fecal 53%","vidaMedia":"45 horas (terminal)"},
  alm="Conservar a temperatura ambiente (≤25°C). Desechar 3 meses después de insertar cartucho."),

M("broncodilatador_beta2","vilanterol","Vilanterol","Vilanterol",["Disponible en combinaciones"],
  "Beta-2 agonista de acción ultraprolongada (ultra-LABA)",
  "Agonista beta-2 selectivo de acción ultraprolongada diseñado para dosificación cada 24 horas. Solo disponible en combinaciones fijas",
  ["EPOC (en combinación con LAMA y/o CI)","Asma (siempre con CI)"],["inhalatoria"],
  {"adulto":"25 mcg/día inhalados (siempre en combinación fija)"},
  ["Polvo para inhalación 25 mcg/dosis (solo en combinaciones: Ellipta)"],"Compatible con precaución","u04","c04_01",
  ea=["Cefalea","Nasofaringitis","Infección respiratoria superior","Artralgia","Tos"],
  ce=["NUNCA usar como monoterapia en asma","Solo disponible en combinaciones fijas (Ellipta)","1 inhalación al día (24h de acción)","Enseñar uso del dispositivo Ellipta"],
  fk={"absorcion":"Biodisponibilidad pulmonar ~27%","metabolismo":"CYP3A4 hepático","eliminacion":"Fecal 70%, renal 30%","vidaMedia":"21 horas"},
  alm="Conservar a temperatura ambiente (≤30°C). No refrigerar. Desechar 6 semanas después de abrir la bandeja."),

M("broncodilatador_beta2","terbutalina","Terbutalina","Terbutalina",["Bricanyl","Brethaire"],
  "Beta-2 agonista de acción corta (SABA)",
  "Agonista beta-2 selectivo de acción corta. Disponible oral, SC e inhalado. Uso SC único en emergencias cuando no se puede nebulizar",
  ["Broncoespasmo agudo","Asma aguda (rescate)","Amenaza de parto prematuro (off-label, IV/SC)"],["oral","SC","inhalatoria"],
  {"adulto":"Oral: 2.5-5 mg c/8h. SC: 0.25 mg, repetir en 15-30 min si necesario (máx 0.5 mg/4h). Inhalado: 500 mcg/dosis c/6h PRN",
   "pediatrico":"Oral: 0.05 mg/kg/dosis c/8h. SC: 5-10 mcg/kg (máx 0.25 mg)"},
  ["Comp 2.5, 5 mg","Amp 0.5 mg/mL","Turbuhaler 500 mcg/dosis","Solución para nebulización 2.5 mg/mL"],"Compatible con precaución","u04","c04_01",
  pp={"dilucion":"SC: administrar sin diluir. IV (tocólisis): diluir en SG5%","velocidadAdministracion":"SC: directa. IV: infusión continua según protocolo obstétrico","estabilidad":"24h a TA diluido"},
  fk={"absorcion":"Oral: biodisponibilidad 14-15%. SC: rápida","metabolismo":"Hepático parcial","eliminacion":"Renal 60%","vidaMedia":"3-4 horas"},
  alm="Conservar a temperatura ambiente. Proteger de la luz. Solución para nebulización: usar inmediatamente una vez abierta."),

M("broncodilatador_beta2","bambuterol","Bambuterol","Bambuterol",["Bambec"],
  "Profármaco oral de terbutalina de acción prolongada",
  "Profármaco de terbutalina que se hidroliza lentamente por butirilcolinesterasa plasmática, liberando terbutalina de forma sostenida durante 24h",
  ["Asma (mantenimiento nocturno)","EPOC con predominio de broncoespasmo","Reversibilidad bronquial"],["oral"],
  {"adulto":"10-20 mg 1 vez al día al acostarse","pediatrico":"≥6 años: 10 mg/día al acostarse"},
  ["Comp 10, 20 mg"],"Compatible con precaución","u04","c04_01",
  ci=["Hipersensibilidad","Taquiarritmias","Pacientes con niveles bajos de butirilcolinesterasa","Uso con inhibidores de colinesterasa"],
  ea=["Temblor","Palpitaciones","Cefalea","Calambres musculares","Hipopotasemia"],
  ix=["Betabloqueantes: antagonismo","Inhibidores de colinesterasa: bloquean conversión a terbutalina","Halotano: arritmias"],
  ce=["Administrar al acostarse (acción nocturna y matutina)","Profármaco oral de terbutalina de 24h","Contraindicado con inhibidores de colinesterasa","Alternativa oral cuando el paciente no tolera inhaladores"],
  fk={"absorcion":"Oral: biodisponibilidad ~20% de terbutalina liberada","metabolismo":"Hidrólisis por butirilcolinesterasa plasmática → terbutalina","eliminacion":"Renal","vidaMedia":"13 horas (bambuterol), 21h (terbutalina liberada)"},
  alm="Conservar a temperatura ambiente. Proteger de la humedad."),

M("broncodilatador_beta2","procaterol","Procaterol","Procaterol",["Meptin","Pro-Air"],
  "Beta-2 agonista de acción corta-intermedia",
  "Agonista beta-2 selectivo con inicio rápido y duración intermedia (~6-8h). Uso frecuente en Asia y Latinoamérica",
  ["Asma bronquial","Bronquitis asmática","EPOC","Broncoespasmo inducido por ejercicio"],["oral","inhalatoria"],
  {"adulto":"Oral: 25-50 mcg c/12h. Inhalado: 10-20 mcg PRN (máx c/6h)","pediatrico":"Oral: 0.5-1 mcg/kg/dosis c/12h"},
  ["Comp 25, 50 mcg","IDM 10 mcg/dosis","Jarabe 5 mcg/mL"],"Compatible con precaución","u04","c04_01",
  fk={"absorcion":"Oral: buena absorción","metabolismo":"Hepático","eliminacion":"Renal","vidaMedia":"6-8 horas"},
  alm="Conservar a temperatura ambiente. Proteger de la luz."),

# ── c04_02 Antiinflamatorios Inhalados (+5) ──
M("corticoide_inhalado","fluticasona_furoato","Fluticasona furoato","Fluticasona furoato",["Arnuity","Ellipta"],
  "Corticoide inhalado de alta potencia y dosificación única diaria",
  "Corticoide inhalado con afinidad por receptor glucocorticoide superior a fluticasona propionato. Permite dosificación cada 24 horas por retención prolongada en pulmón",
  ["Asma (mantenimiento, a partir de 5 años)","EPOC (en combinación)"],["inhalatoria"],
  {"adulto":"100-200 mcg 1 vez al día (Ellipta)","pediatrico":"≥5 años: 50 mcg/día (Ellipta)"},
  ["Polvo para inhalación 50, 100, 200 mcg/dosis (dispositivo Ellipta)"],"Compatible con precaución","u04","c04_02",
  fk={"absorcion":"Biodisponibilidad pulmonar ~15%, oral <2%","metabolismo":"CYP3A4 hepático","eliminacion":"Fecal 101%, renal <1%","vidaMedia":"24 horas (retención pulmonar prolongada)"},
  alm="Conservar a temperatura ambiente (≤30°C). Desechar 6 semanas después de abrir la bandeja. Mantener seco."),

M("corticoide_inhalado","triamcinolona_inhalada","Triamcinolona inhalada","Acetónido de triamcinolona",["Azmacort"],
  "Corticoide inhalado de potencia intermedia",
  "Corticoide inhalado con potencia antiinflamatoria intermedia. Menor supresión adrenal que dosis equivalentes de otros CI",
  ["Asma persistente leve a moderada (mantenimiento)"],["inhalatoria"],
  {"adulto":"150-600 mcg/día divididos en 2-4 inhalaciones","pediatrico":"6-12 años: 75-300 mcg/día"},
  ["IDM 75 mcg/dosis"],"Compatible con precaución","u04","c04_02",
  fk={"absorcion":"Depósito pulmonar variable según técnica","metabolismo":"Hepático CYP3A4","eliminacion":"Renal y fecal","vidaMedia":"88 minutos (plasmática)"},
  alm="Conservar a temperatura ambiente. No exponer a temperaturas >50°C. No perforar ni quemar envase."),

M("corticoide_inhalado","beclometasona_formoterol","Beclometasona/Formoterol","Beclometasona + Formoterol",["Foster","Innovair"],
  "Combinación CI + LABA en partículas extrafinas",
  "Formulación de partículas extrafinas (HFA-BDP + formoterol) que alcanza vías aéreas pequeñas (<2 mm). Mayor depósito pulmonar periférico que formulaciones convencionales",
  ["Asma persistente moderada a severa","EPOC con componente inflamatorio"],["inhalatoria"],
  {"adulto":"Asma: 100/6 mcg 1-2 inhalaciones c/12h. EPOC: 100/6 mcg 2 inhalaciones c/12h. Máx: 800/48 mcg/día"},
  ["IDM 100/6 mcg/dosis (beclometasona/formoterol) partículas extrafinas","IDM 200/6 mcg/dosis"],"Compatible con precaución","u04","c04_02",
  ci=["Hipersensibilidad a cualquier componente","TB pulmonar activa","Taquiarritmias (formoterol)"],
  ea=["Candidiasis orofaríngea","Disfonía","Temblor","Palpitaciones","Cefalea","Hipopotasemia"],
  ix=["Betabloqueantes: antagonizan efecto del formoterol","Inhibidores CYP3A4: aumentan exposición a beclometasona","Diuréticos: mayor hipopotasemia"],
  ce=["Partículas extrafinas: NO requiere coordinación perfecta con IDM","Mayor depósito en vías pequeñas vs formulaciones estándar","Enjuagar boca siempre después de uso","Puede usarse como MART (mantenimiento y rescate) con formulación 100/6"],
  fk={"absorcion":"Depósito pulmonar ~31% (extrafino vs ~10-20% convencional)","metabolismo":"Beclometasona: esterasas → beclometasona-17-monopropionato activo. Formoterol: glucuronidación","eliminacion":"Renal y fecal","vidaMedia":"BDP activo: 2.7h; Formoterol: 10h"},
  alm="Conservar a temperatura ambiente (≤25°C). No exponer a temperaturas >50°C. No perforar."),

M("corticoide_inhalado","fluticasona_umeclidinio_vilanterol","Fluticasona/Umeclidinio/Vilanterol","Fluticasona furoato + Umeclidinio + Vilanterol",["Trelegy Ellipta"],
  "Triple terapia inhalada en dispositivo único (CI + LAMA + LABA)",
  "Primera combinación triple fija en un solo inhalador. Fluticasona furoato (antiinflamatorio) + umeclidinio (LAMA) + vilanterol (LABA). Dosificación cada 24h",
  ["EPOC moderada a severa con exacerbaciones frecuentes","Asma severa no controlada con CI/LABA"],["inhalatoria"],
  {"adulto":"1 inhalación/día (92/55/22 mcg para EPOC; 100/62.5/25 mcg para asma)"},
  ["Polvo para inhalación 92/55/22 mcg/dosis (Ellipta, EPOC)","Polvo para inhalación 100/62.5/25 mcg/dosis (Ellipta, asma)"],"Compatible con precaución","u04","c04_02",
  ci=["Hipersensibilidad a cualquier componente","Alergia severa a proteínas de leche (contiene lactosa)","Glaucoma de ángulo cerrado no tratado","Retención urinaria"],
  ea=["Candidiasis orofaríngea","Disfonía","Cefalea","Nasofaringitis","Infección respiratoria superior","Tos","Dolor de espalda","Artralgia"],
  ix=["Betabloqueantes: antagonizan vilanterol","Inhibidores CYP3A4: aumentan exposición a fluticasona y umeclidinio","Otros anticolinérgicos: efectos aditivos","Diuréticos: mayor hipopotasemia"],
  ce=["Triple terapia en un solo dispositivo: mejora adherencia","1 inhalación al día siempre a la misma hora","Enjuagar boca después de CADA uso","Enseñar uso correcto del Ellipta (abrir-inhalar-cerrar)","No necesita cebar ni agitar"],
  fk={"absorcion":"Pulmonar. Oral mínima por primer paso","metabolismo":"Fluticasona: CYP3A4. Umeclidinio: CYP2D6. Vilanterol: CYP3A4","eliminacion":"Fecal predominante","vidaMedia":"FF: 24h; UMEC: 19h; VI: 21h"},
  alm="Conservar a temperatura ambiente (≤30°C). No refrigerar. Desechar 6 semanas después de abrir bandeja."),

M("corticoide_inhalado","budesonida_glicopirronio_formoterol","Budesonida/Glicopirronio/Formoterol","Budesonida + Glicopirronio + Formoterol",["Breztri Aerosphere","Trixeo"],
  "Triple terapia inhalada CI + LAMA + LABA en IDM presurizado",
  "Triple combinación fija en inhalador presurizado con tecnología co-suspensión. Budesonida (CI) + glicopirronio (LAMA) + formoterol (LABA). Dosificación c/12h",
  ["EPOC moderada a severa con exacerbaciones frecuentes","EPOC no controlada con doble terapia"],["inhalatoria"],
  {"adulto":"2 inhalaciones c/12h (160/14.4/4.8 mcg por inhalación)"},
  ["IDM 160/14.4/4.8 mcg/dosis (budesonida/glicopirronio/formoterol)"],"Compatible con precaución","u04","c04_02",
  ci=["Hipersensibilidad a cualquier componente","Glaucoma de ángulo cerrado","Retención urinaria severa","Taquiarritmias"],
  ea=["Candidiasis orofaríngea","Disfonía","Cefalea","Tos","Boca seca","Nasofaringitis","Infección urinaria"],
  ix=["Betabloqueantes: antagonizan formoterol","Inhibidores CYP3A4: aumentan exposición a budesonida","Otros anticolinérgicos: efectos aditivos","Diuréticos: hipopotasemia"],
  ce=["Agitar bien antes de cada uso (IDM presurizado)","2 inhalaciones cada 12 horas","Enjuagar boca después de uso","Usar espaciador si dificultad con coordinación","Limpiar boquilla semanalmente"],
  fk={"absorcion":"Pulmonar con tecnología co-suspensión","metabolismo":"Budesonida: CYP3A4. Glicopirronio: hidrólisis. Formoterol: glucuronidación","eliminacion":"Renal y fecal","vidaMedia":"Budesonida: 2-3h; Glicopirronio: 6-11h; Formoterol: 10h"},
  alm="Conservar a temperatura ambiente (15-30°C). No exponer a temperaturas >50°C. No perforar ni quemar."),

# ── c04_03 Mucolíticos (+7) ──
M("aine","erdosteina","Erdosteína","Erdosteína",["Erdos","Vectrine"],
  "Mucolítico tiol con propiedades antioxidantes",
  "Profármaco con 3 metabolitos activos con grupos tiol libres. Rompe puentes disulfuro del moco, reduce adherencia bacteriana y tiene efecto antioxidante en vía aérea",
  ["EPOC (reducción de exacerbaciones)","Bronquitis aguda y crónica","Bronquiectasias"],["oral"],
  {"adulto":"300 mg c/12h durante 7-10 días (agudo) o largo plazo (EPOC)"},
  ["Cáps 300 mg","Sobres 175, 225 mg (pediátrico)"],"Compatible con precaución","u04","c04_03",
  familia="Mucolíticos",emb="B",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Úlcera péptica activa","Cistinuria homocigota"],
  ea=["Náuseas","Dolor abdominal","Diarrea","Cefalea","Urticaria (raro)","Disgeusia"],
  ix=["Antitusivos: contraindicación relativa (retención de moco)","Antibióticos: erdosteína mejora penetración de amoxicilina y ciprofloxacino en secreción bronquial"],
  ce=["Estudio RESTORE: reduce exacerbaciones EPOC 20% vs placebo","Administrar con alimentos","No combinar con antitusivos","Puede mejorar penetración de antibióticos en moco"],
  fk={"absorcion":"Oral rápida, mejorada con alimentos","metabolismo":"Hepático a 3 metabolitos activos con grupos -SH","eliminacion":"Renal 40%, fecal 60%","vidaMedia":"5.5 horas"}),

M("aine","carbocisteina","Carbocisteína","Carbocisteína",["Mucodyne","Rhinathiol","Flemex"],
  "Mucoregulador con acción sobre sialomucinas",
  "Mucoregulador que normaliza la composición del moco bronquial actuando sobre células caliciformes. Restaura relación sialomucinas/fucomucinas. No rompe moco existente sino que regula su producción",
  ["Bronquitis crónica","EPOC","Rinosinusitis","Otitis media serosa"],["oral"],
  {"adulto":"750 mg c/8h (fase aguda), luego 750 mg c/12h (mantenimiento)","pediatrico":"2-5 años: 125-250 mg c/8h. >5 años: 250-500 mg c/8h"},
  ["Cáps 375 mg","Jarabe 250 mg/5 mL","Jarabe infantil 125 mg/5 mL"],"Compatible con precaución","u04","c04_03",
  familia="Mucolíticos",emb="B",
  ci=["Hipersensibilidad","Úlcera gastroduodenal activa"],
  ea=["Náuseas","Diarrea","Epigastralgia","Erupción cutánea (raro)"],
  ix=["Antitusivos: evitar combinación (retención de secreciones)"],
  ce=["Mucoregulador: actúa sobre producción de moco, no lo rompe","Efecto máximo tras 7-10 días de uso","Puede usarse a largo plazo en EPOC","Administrar lejos de comidas para mejor absorción"],
  fk={"absorcion":"Oral rápida","metabolismo":"Hepático a S-óxido activo","eliminacion":"Renal 30-60%","vidaMedia":"2-3 horas"}),

M("inmunosupresor","dornasa_alfa","Dornasa alfa","Dornasa alfa (DNasa recombinante humana)",["Pulmozyme"],
  "Enzima mucolítica recombinante (DNasa)",
  "ADNasa recombinante humana que hidroliza el ADN extracelular presente en las secreciones purulentas. El ADN de neutrófilos muertos es el principal responsable de la viscosidad del esputo purulento",
  ["Fibrosis quística (≥5 años)","Bronquiectasias con esputo purulento (off-label)"],["inhalatoria"],
  {"adulto":"2.5 mg nebulizados 1 vez al día","pediatrico":"≥5 años: 2.5 mg nebulizados 1 vez al día"},
  ["Ampolla 2.5 mg/2.5 mL para nebulización"],"Compatible con precaución","u04","c04_03",
  familia="Enzimas mucolíticas",emb="B",
  ci=["Hipersensibilidad a dornasa alfa o componentes (CHO cell products)"],
  ea=["Disfonía","Faringitis","Laringitis","Rash","Dolor torácico","Conjuntivitis"],
  ix=["No mezclar con otros fármacos en el nebulizador"],
  ce=["Nebulizar con nebulizador jet recomendado (no ultrasónico)","No diluir ni mezclar con otros fármacos","Administrar separado de fisioterapia respiratoria","Eficacia demostrada en FQ: mejora FEV1 ~5-8%","Mantener cadena de frío"],
  fk={"absorcion":"Depósito pulmonar por nebulización","metabolismo":"Proteólisis local","eliminacion":"No significativa sistémica","vidaMedia":"Indetectable en suero a dosis terapéuticas"},
  alm="Refrigerar 2-8°C. NO congelar. Proteger de la luz. Usar inmediatamente tras abrir ampolla."),

M("aine","guaifenesina","Guaifenesina","Guaifenesina (guayacolato de glicerilo)",["Mucinex","Robitussin"],
  "Expectorante de acción refleja",
  "Expectorante que estimula las glándulas secretoras del tracto respiratorio aumentando el volumen y reduciendo la viscosidad de las secreciones bronquiales. Mecanismo vagal-gástrico",
  ["Tos productiva","Congestión bronquial","Facilitación de la expectoración"],["oral"],
  {"adulto":"200-400 mg c/4h o 600-1200 mg c/12h (LP). Máx: 2400 mg/día","pediatrico":"2-5 años: 50-100 mg c/4h. 6-11 años: 100-200 mg c/4h"},
  ["Comp 200 mg","Comp LP 600, 1200 mg","Jarabe 100 mg/5 mL"],"Compatible con precaución","u04","c04_03",
  familia="Expectorantes",emb="C",
  ci=["Hipersensibilidad"],
  ea=["Náuseas","Vómitos","Molestias gastrointestinales","Mareo","Cefalea","Urticaria (raro)"],
  ix=["Puede interferir con prueba de ácido 5-HIAA urinario (falso positivo)"],
  ce=["Aumentar ingesta de líquidos para potenciar efecto","No triturar comprimidos de liberación prolongada","Eficacia como expectorante cuestionada por algunos estudios","Uso más extendido en América que en Europa"]),

M("aine","levodropropizina","Levodropropizina","Levodropropizina",["Levotuss","Antux"],
  "Antitusígeno periférico no opioide",
  "Antitusígeno de acción periférica. Actúa sobre las fibras C aferentes en la vía aérea reduciendo la liberación de neuropéptidos. No tiene acción central ni efecto opioide",
  ["Tos seca no productiva","Tos irritativa"],["oral"],
  {"adulto":"60 mg c/8h","pediatrico":">2 años: 1 mg/kg c/8h. Máx 3 dosis/día"},
  ["Comp 60 mg","Jarabe 30 mg/5 mL","Gotas 60 mg/mL"],"Compatible con precaución","u04","c04_03",
  familia="Antitusígenos periféricos",emb="B",
  ci=["Hipersensibilidad","Tos productiva (no suprimir)","Embarazo primer trimestre"],
  ea=["Somnolencia leve","Náuseas","Diarrea","Palpitaciones (raro)","Fatiga"],
  ix=["Depresores del SNC: mínima interacción (acción periférica)","No presenta interacción con opioides"],
  ce=["Ventaja: acción periférica sin depresión respiratoria","No suprime el reflejo tusígeno central","Menor somnolencia que antitusígenos centrales","No genera dependencia","Alternativa a codeína en tos seca"]),

M("aine","oxolamina","Oxolamina","Citrato de oxolamina",["Perebron","Oxotussin"],
  "Antitusígeno con actividad antiinflamatoria bronquial",
  "Antitusígeno de acción central y periférica con propiedades antiinflamatorias y broncodilatadoras leves. Inhibe liberación de histamina y tiene acción sobre centro de la tos",
  ["Tos seca o irritativa","Tos asociada a faringolaringitis","Tos postinfecciosa"],["oral"],
  {"adulto":"100-200 mg c/8-12h","pediatrico":"2-6 años: 50 mg c/8h. 6-12 años: 100 mg c/8h"},
  ["Comp 100, 200 mg","Jarabe 50 mg/5 mL"],"Compatible con precaución","u04","c04_03",
  familia="Antitusígenos",emb="C",
  ci=["Hipersensibilidad","Tos productiva"],
  ea=["Molestias gástricas","Somnolencia leve","Náuseas","Erupción cutánea (raro)"],
  ix=["Depresores del SNC: precaución por somnolencia aditiva"],
  ce=["Doble acción: antitusígena y antiinflamatoria","Menor potencia antitusígena que codeína","Administrar con alimentos si molestias GI","No genera dependencia"]),

M("aine","benzonatato","Benzonatato","Benzonatato",["Tessalon Perles"],
  "Antitusígeno periférico tipo anestésico local",
  "Anestésico local relacionado con tetracaína. Actúa anestesiando los receptores de estiramiento en el pulmón y la pleura, reduciendo el reflejo tusígeno. No tiene acción central opioide",
  ["Tos seca no productiva","Tos crónica refractaria"],["oral"],
  {"adulto":"100-200 mg c/8h. Máx 600 mg/día","pediatrico":"≥10 años: 100 mg c/8h"},
  ["Cáps blandas (perlas) 100, 200 mg"],"Compatible con precaución","u04","c04_03",
  familia="Antitusígenos periféricos",emb="C",
  ci=["Hipersensibilidad","Niños <10 años (riesgo de muerte por masticación accidental de cápsula)"],
  ea=["Adormecimiento orofaríngeo (si se mastica)","Náuseas","Estreñimiento","Mareo","Cefalea","Erupción cutánea"],
  ix=["Mínimas interacciones conocidas"],
  ce=["NUNCA masticar ni chupar la cápsula (anestesia orofaríngea → aspiración)","Tragar entera con agua","Peligro mortal en niños pequeños si se mastica","Inicio de acción: 15-20 minutos","No genera dependencia"]),

# ── c04_04 Antihistamínicos (+8) ──
M("aine","levocetirizina","Levocetirizina","Levocetirizina",["Xyzal","Xusal"],
  "Antihistamínico H1 de 3ª generación (enantiómero R de cetirizina)",
  "Enantiómero R activo de cetirizina con el doble de afinidad por receptor H1. Mayor potencia con la mitad de la dosis de cetirizina. Mínima penetración en SNC",
  ["Rinitis alérgica estacional y perenne","Urticaria crónica","Dermatitis alérgica"],["oral"],
  {"adulto":"5 mg/día por la noche","pediatrico":"2-5 años: 1.25 mg/día. 6-11 años: 2.5 mg/día. ≥12 años: 5 mg/día",
   "ajusteRenal":"ClCr 30-50: 2.5 mg/día. ClCr 10-30: 2.5 mg c/72h. <10: contraindicado"},
  ["Comp 5 mg","Gotas 5 mg/mL","Jarabe 2.5 mg/5 mL"],"Compatible con precaución","u04","c04_04",
  familia="Antihistamínicos H1 de segunda/tercera generación",emb="B",
  ci=["Hipersensibilidad a cetirizina o levocetirizina","Insuficiencia renal grave (ClCr <10)","Niños <2 años"],
  ea=["Somnolencia leve","Boca seca","Fatiga","Cefalea"],
  ix=["Alcohol: mayor sedación","Depresores SNC: sedación aditiva","Teofilina: puede reducir aclaramiento"],
  ce=["Mitad de dosis que cetirizina con igual eficacia","Puede administrarse con o sin alimentos","Menor sedación que cetirizina racémica","Ajustar en insuficiencia renal"]),

M("aine","ebastina","Ebastina","Ebastina",["Ebastel","Kestine"],
  "Antihistamínico H1 de segunda generación de larga acción",
  "Antihistamínico H1 selectivo de segunda generación. Profármaco metabolizado a carebastina activa. Mínimos efectos anticolinérgicos y sedantes",
  ["Rinitis alérgica estacional y perenne","Urticaria crónica idiopática","Conjuntivitis alérgica"],["oral"],
  {"adulto":"10-20 mg/día en dosis única","pediatrico":"6-11 años: 5 mg/día. ≥12 años: 10 mg/día"},
  ["Comp 10, 20 mg","Comp bucodispersable 10, 20 mg","Jarabe 5 mg/5 mL"],"Compatible con precaución","u04","c04_04",
  familia="Antihistamínicos H1 de segunda generación",emb="B",
  ci=["Hipersensibilidad","Insuficiencia hepática grave","Uso con ketoconazol o eritromicina en dosis altas"],
  ea=["Cefalea","Somnolencia leve","Boca seca","Dolor abdominal","Dispepsia"],
  ix=["Ketoconazol/eritromicina: aumentan niveles → riesgo prolongación QT","Jugo de pomelo: aumenta niveles"],
  ce=["Puede tomarse con o sin alimentos","Presentación bucodispersable útil en pacientes con disfagia","No requiere ajuste en insuficiencia renal","Acción prolongada: 1 toma diaria"]),

M("aine","azelastina","Azelastina","Clorhidrato de azelastina",["Astelin","Astepro","Allergodil"],
  "Antihistamínico H1 tópico nasal y oftálmico",
  "Antihistamínico H1 de segunda generación de uso tópico con inicio de acción rápido (15 min). Además de bloqueo H1, inhibe liberación de leucotrienos y reduce permeabilidad vascular nasal",
  ["Rinitis alérgica estacional y perenne","Rinitis vasomotora no alérgica","Conjuntivitis alérgica (forma oftálmica)"],["nasal","oftalmica"],
  {"adulto":"Nasal: 1-2 pulsaciones por fosa nasal c/12h. Oftálmico: 1 gota en cada ojo c/12h",
   "pediatrico":"≥6 años nasal: 1 pulsación por fosa nasal c/12h. ≥3 años oftálmico: 1 gota c/12h"},
  ["Spray nasal 137 mcg/dosis","Colirio 0.05%"],"Compatible con precaución","u04","c04_04",
  familia="Antihistamínicos H1 tópicos",emb="C",
  ci=["Hipersensibilidad"],
  ea=["Sabor amargo (nasal, frecuente)","Somnolencia","Cefalea","Epistaxis","Ardor nasal transitorio"],
  ix=["Alcohol: mayor sedación","Depresores SNC: precaución por absorción sistémica parcial"],
  ce=["Inicio rápido: 15 minutos (más rápido que antihistamínicos orales)","El sabor amargo es efecto adverso frecuente: inclinar cabeza adelante al aplicar","Combinación azelastina nasal + fluticasona nasal superior a cada uno solo","Útil en rinitis no alérgica (a diferencia de antiH1 orales)"]),

M("aine","olopatadina","Olopatadina","Clorhidrato de olopatadina",["Patanol","Pataday","Opatanol"],
  "Antihistamínico H1 tópico con estabilización de mastocitos",
  "Antihistamínico H1 selectivo con doble mecanismo: bloquea receptor H1 y estabiliza mastocitos inhibiendo liberación de histamina. Acción rápida y prolongada",
  ["Conjuntivitis alérgica","Rinitis alérgica (spray nasal)"],["oftalmica","nasal"],
  {"adulto":"Oftálmico 0.1%: 1 gota c/12h. 0.2%: 1 gota/día. 0.7%: 1 gota/día. Nasal: 2 pulsaciones por fosa c/12h",
   "pediatrico":"≥2 años (oftálmico): 1 gota c/12h. ≥6 años (nasal): 1 pulsación c/12h"},
  ["Colirio 0.1%, 0.2%, 0.7%","Spray nasal 665 mcg/dosis"],"Compatible con precaución","u04","c04_04",
  familia="Antihistamínicos H1 tópicos/estabilizadores de mastocitos",emb="C",
  ci=["Hipersensibilidad","No usar con lentes de contacto puestos (oftálmico)"],
  ea=["Ardor ocular transitorio","Cefalea","Sabor amargo (nasal)","Somnolencia leve","Sequedad ocular"],
  ix=["Mínimas interacciones sistémicas por uso tópico"],
  ce=["Retirar lentes de contacto antes de aplicar colirio (esperar 10 min para reinsertar)","Acción dual: antihistamínico + estabilizador de mastocitos","No tocar la punta del gotero con el ojo","Pataday 0.2-0.7%: una sola gota diaria"]),

M("aine","ketotifeno","Ketotifeno","Fumarato de ketotifeno",["Zaditen","Zaditor"],
  "Antihistamínico H1 con estabilización de mastocitos",
  "Antihistamínico H1 no competitivo con acción estabilizadora de mastocitos e inhibición de eosinófilos. Uso oral profiláctico en asma alérgica y tópico en conjuntivitis",
  ["Profilaxis del asma alérgica (oral)","Conjuntivitis alérgica (tópico)","Rinitis alérgica","Urticaria crónica"],["oral","oftalmica"],
  {"adulto":"Oral: 1-2 mg c/12h. Oftálmico: 1 gota c/8-12h","pediatrico":"6 meses-3 años oral: 0.5 mg c/12h. >3 años: 1 mg c/12h. Oftálmico ≥3 años: 1 gota c/8-12h"},
  ["Comp 1 mg","Jarabe 1 mg/5 mL","Colirio 0.025%, 0.05%"],"Compatible con precaución","u04","c04_04",
  familia="Antihistamínicos/estabilizadores de mastocitos",emb="C",
  ci=["Hipersensibilidad","Uso oral con antidiabéticos orales (puede causar trombocitopenia reversible)"],
  ea=["Somnolencia (frecuente al inicio, disminuye en días)","Aumento de peso","Aumento de apetito","Boca seca","Mareo"],
  ix=["Antidiabéticos orales: trombocitopenia reversible","Depresores SNC: mayor sedación","Antihistamínicos: efecto aditivo"],
  ce=["Profiláctico: efecto terapéutico tarda 2-4 semanas vía oral","No es tratamiento de crisis asmática","Precaución al conducir (somnolencia inicial)","Uso oftálmico: inicio rápido de acción"]),

M("aine","clemastina","Clemastina","Fumarato de clemastina",["Tavegil","Tavist"],
  "Antihistamínico H1 de primera generación con acción prolongada",
  "Antihistamínico H1 de primera generación con duración de acción de 12h. Efectos anticolinérgicos moderados. Disponible en formas oral e inyectable",
  ["Rinitis alérgica","Urticaria aguda y crónica","Reacciones alérgicas","Angioedema","Anafilaxia (adyuvante)"],["oral","IV","IM"],
  {"adulto":"Oral: 1 mg c/12h. Máx 6 mg/día. IV/IM: 2 mg c/12h en urgencias",
   "pediatrico":"1-3 años: 0.25-0.5 mg c/12h. 3-6 años: 0.5 mg c/12h. 6-12 años: 0.5-1 mg c/12h"},
  ["Comp 1 mg","Jarabe 0.5 mg/5 mL","Amp 2 mg/2 mL"],"Evitar durante lactancia","u04","c04_04",
  familia="Antihistamínicos H1 de primera generación",emb="B",
  ci=["Hipersensibilidad","Neonatos y prematuros","Asma aguda","Retención urinaria","Glaucoma de ángulo cerrado"],
  ea=["Somnolencia","Boca seca","Retención urinaria","Estreñimiento","Espesamiento de secreciones bronquiales","Visión borrosa"],
  ix=["Depresores SNC/alcohol: mayor sedación","IMAO: prolongan efecto anticolinérgico","Anticolinérgicos: efectos aditivos"],
  ce=["Causa somnolencia significativa: advertir sobre conducción","Disponible IV para urgencias alérgicas","Puede espesar secreciones: no ideal en pacientes con mucosidad","Administrar IV lenta en 2-3 min"],
  pp={"dilucion":"Puede administrarse sin diluir IV lento o diluir en 10 mL SF","velocidadAdministracion":"IV lento en 2-3 minutos","estabilidad":"Usar inmediatamente"}),

M("aine","meclizina","Meclizina","Clorhidrato de meclizina",["Antivert","Bonamine","Bonadoxina"],
  "Antihistamínico H1 con acción antivertiginosa y antiemética",
  "Antihistamínico H1 de primera generación con acción predominantemente antivertiginosa y antiemética. Actúa sobre centros vestibulares y zona quimiorreceptora del gatillo",
  ["Vértigo periférico","Cinetosis (mareo por movimiento)","Náuseas y vómitos asociados a vértigo","Enfermedad de Ménière"],["oral"],
  {"adulto":"Vértigo: 25-50 mg c/8-24h. Cinetosis: 25-50 mg 1h antes del viaje",
   "pediatrico":"≥12 años: dosis de adulto","geriatrico":"Iniciar con 12.5 mg, titular según respuesta"},
  ["Comp 12.5, 25, 50 mg","Comp masticable 25 mg"],"Evitar durante lactancia","u04","c04_04",
  familia="Antihistamínicos/antieméticos",emb="B",
  ci=["Hipersensibilidad","Glaucoma de ángulo cerrado","Obstrucción urinaria"],
  ea=["Somnolencia","Boca seca","Visión borrosa","Fatiga","Estreñimiento"],
  ix=["Depresores SNC: sedación aditiva","Alcohol: mayor sedación","Anticolinérgicos: efectos aditivos"],
  ce=["Principal indicación: vértigo y cinetosis (más que alergia)","Para cinetosis: tomar 1h antes del viaje","Causa somnolencia: advertir sobre conducción","Precaución en ancianos (efectos anticolinérgicos)"]),

M("aine","dimenhidrinato","Dimenhidrinato","Dimenhidrinato",["Dramamine","Biodramina","Gravol"],
  "Antihistamínico H1 antiemético y antivertiginoso",
  "Sal de difenhidramina con 8-cloroteofilina. Acción antiemética, antivertiginosa y anticolinérgica. Actúa sobre centro del vómito y sistema vestibular",
  ["Cinetosis (mareo por movimiento)","Náuseas y vómitos","Vértigo periférico","Náuseas postoperatorias"],["oral","IV","IM","rectal"],
  {"adulto":"Oral: 50-100 mg c/4-6h. Máx 400 mg/día. IV/IM: 50 mg c/4-6h","pediatrico":"2-6 años: 12.5-25 mg c/6-8h. 6-12 años: 25-50 mg c/6-8h"},
  ["Comp 50 mg","Comp masticable 50 mg","Jarabe 12.5 mg/5 mL","Sup 25, 50 mg","Amp 50 mg/mL"],"Evitar durante lactancia","u04","c04_04",
  familia="Antihistamínicos/antieméticos",emb="B",
  ci=["Hipersensibilidad","Neonatos y prematuros","Porfiria"],
  ea=["Somnolencia marcada","Boca seca","Visión borrosa","Retención urinaria","Mareo paradójico (niños)","Excitabilidad paradójica (niños)"],
  ix=["Depresores SNC/alcohol: sedación intensa","Aminoglucósidos: puede enmascarar ototoxicidad","Anticolinérgicos: efectos aditivos"],
  ce=["Para cinetosis: administrar 30 min antes del viaje","Causa somnolencia marcada: advertir conducción","Puede enmascarar ototoxicidad de aminoglucósidos (no combinar)","En niños puede causar excitabilidad paradójica"],
  pp={"dilucion":"Diluir en 10 mL SF para IV","velocidadAdministracion":"IV lento en 2 min mínimo","estabilidad":"Usar inmediatamente"}),

# ── c04_05 Otros Respiratorios (+8) ──
M("inmunosupresor","tezepelumab","Tezepelumab","Tezepelumab",["Tezspire"],
  "Anti-TSLP (anti-linfopoyetina estromal tímica)",
  "Primer anticuerpo monoclonal anti-TSLP. Bloquea la linfopoyetina estromal tímica (alarmina upstream) que inicia la cascada inflamatoria en asma. Eficaz independiente del fenotipo (eosinofílico y no eosinofílico)",
  ["Asma severa refractaria (≥12 años) como terapia de mantenimiento adicional"],["SC"],
  {"adulto":"210 mg SC c/4 semanas","pediatrico":"≥12 años: 210 mg SC c/4 semanas"},
  ["Jeringa precargada 210 mg/1.91 mL","Pluma precargada 210 mg/1.91 mL"],"No recomendado","u04","c04_05",
  ci=["Hipersensibilidad a tezepelumab"],
  ea=["Faringitis","Artralgia","Dolor de espalda","Reacción en sitio de inyección","Erupción cutánea"],
  ix=["No interacciones significativas conocidas","Vacunas vivas: precaución teórica"],
  ce=["Eficaz en asma severa INDEPENDIENTE del fenotipo (vs mepolizumab/benralizumab solo eosinofílico)","No usar para crisis aguda","Administrar SC en muslo, abdomen o brazo","Rotar sitios de inyección","No necesita monitorizar eosinófilos previamente"],
  fk={"absorcion":"SC: biodisponibilidad ~77%","metabolismo":"Catabolismo proteolítico","eliminacion":"Catabolismo","vidaMedia":"26 días"},
  alm="Refrigerar 2-8°C. No congelar. Puede mantenerse a TA (≤30°C) hasta 30 días."),

M("inmunosupresor","reslizumab","Reslizumab","Reslizumab",["Cinqair","Cinqaero"],
  "Anti-IL-5 intravenoso",
  "Anticuerpo monoclonal humanizado anti-IL-5. Único biológico anti-IL-5 de administración intravenosa. Reduce eosinófilos circulantes y tisulares",
  ["Asma eosinofílica severa (≥18 años) como tratamiento adicional de mantenimiento"],["IV"],
  {"adulto":"3 mg/kg IV c/4 semanas en infusión de 20-50 min"},
  ["Vial 100 mg/10 mL"],"No recomendado","u04","c04_05",
  ci=["Hipersensibilidad a reslizumab","No usar en menores de 18 años"],
  ea=["Reacciones anafilácticas (0.3%)","Mialgia","Orofaringitis","Elevación de CPK"],
  ix=["No interacciones significativas conocidas"],
  ce=["Único anti-IL-5 intravenoso (requiere administración en centro sanitario)","Dosis basada en peso: calcular cuidadosamente","Observar 20 min post-infusión por riesgo anafilaxis","Tener equipo de reanimación disponible","Solo para asma eosinofílica (eosinófilos ≥400/mcL)"],
  pp={"dilucion":"Diluir en 50 mL SF (no usar SG)","velocidadAdministracion":"Infundir en 20-50 min","estabilidad":"Usar dentro de 16h desde preparación (refrigerado)"},
  fk={"absorcion":"IV: 100% biodisponibilidad","metabolismo":"Catabolismo proteolítico","eliminacion":"Catabolismo","vidaMedia":"24 días"},
  alm="Refrigerar 2-8°C. No congelar. No agitar. Proteger de la luz."),

M("inmunosupresor","itepekimab","Itepekimab","Itepekimab",["En investigación (Fase 3)"],
  "Anti-IL-33 (anti-alarmina)",
  "Anticuerpo monoclonal anti-IL-33 que bloquea una alarmina clave liberada por epitelio dañado. La IL-33 activa eosinófilos, mastocitos, ILC2 e inicia la cascada inflamatoria tipo 2 en asma",
  ["Asma moderada a severa (en investigación/aprobación reciente)","Asma con fenotipo mixto eosinofílico"],["SC"],
  {"adulto":"300 mg SC c/2 semanas (dosis en estudio)"},
  ["Jeringa precargada 300 mg (en desarrollo)"],"No recomendado","u04","c04_05",
  ci=["Hipersensibilidad","Infecciones helmínticas activas (IL-33 participa en defensa antiparasitaria)"],
  ea=["Reacción en sitio de inyección","Nasofaringitis","Cefalea","Artralgia"],
  ix=["Vacunas vivas: precaución teórica","No interacciones significativas conocidas"],
  ce=["Mecanismo: bloquea IL-33, alarmina upstream en cascada alérgica","Potencial para asma sin predominio eosinofílico","En investigación clínica avanzada","Podría complementarse con anti-IL-4/13 (dupilumab)"],
  fk={"absorcion":"SC: biodisponibilidad estimada ~60-80%","metabolismo":"Catabolismo proteolítico","eliminacion":"Catabolismo","vidaMedia":"~22-25 días (estimada)"},
  alm="Refrigerar 2-8°C. No congelar."),

M("broncodilatador_beta2","doxofylina","Doxofylina","Doxofylina",["Ansimar","Doxobron"],
  "Metilxantina de nueva generación",
  "Derivado de metilxantina con mecanismo diferenciado: inhibición de PDE (no selectiva) sin antagonismo significativo de receptores de adenosina. Mejor perfil de seguridad que teofilina",
  ["Asma bronquial","EPOC","Broncoespasmo"],["oral","IV"],
  {"adulto":"Oral: 400-600 mg c/12h. IV: 100 mg infusión lenta","pediatrico":"6-12 años: 6 mg/kg/dosis c/12h"},
  ["Comp 200, 400 mg","Jarabe 100 mg/5 mL","Amp 200 mg/10 mL"],"Compatible con precaución","u04","c04_05",
  familia="Metilxantinas",emb="C",
  ci=["Hipersensibilidad","IAM agudo","Hipotensión arterial severa","Lactancia"],
  ea=["Náuseas","Cefalea","Pirosis","Palpitaciones","Insomnio (menor que teofilina)","Temblor (menos que teofilina)"],
  ix=["Eritromicina/ciprofloxacino: pueden aumentar niveles (menor efecto que con teofilina)","Litio: doxofylina puede reducir niveles"],
  ce=["Perfil de seguridad superior a teofilina (no requiere monitorización de niveles habitualmente)","Menor riesgo de convulsiones y arritmias que teofilina","Menor interacción con adenosina","Administrar con alimentos si molestias GI"],
  pp={"dilucion":"Diluir en 100 mL SF o SG5%","velocidadAdministracion":"Infundir lentamente en 20-30 min","estabilidad":"Usar inmediatamente"},
  fk={"absorcion":"Oral: rápida, biodisponibilidad ~60%","metabolismo":"Hepático (sin metabolitos activos principales)","eliminacion":"Renal 90%","vidaMedia":"6-8 horas"}),

M("broncodilatador_beta2","epinefrina_inhalada","Epinefrina inhalada","Epinefrina (adrenalina) racémica",["Vaponefrin","S2"],
  "Simpaticomimético inhalado de acción corta",
  "Epinefrina racémica (mezcla de isómeros D y L) para nebulización. Potente efecto vasoconstrictor y broncodilatador sobre mucosa laríngea y bronquial. Reduce edema subglótico",
  ["Crup (laringotraqueítis) moderado-severo","Estridor postextubación","Bronquiolitis severa (controvertido)","Angioedema de vía aérea superior"],["inhalatoria"],
  {"adulto":"Epinefrina racémica 2.25%: 0.5 mL en 3 mL SF nebulizado. L-epinefrina: 3-5 mL (1:1000) nebulizado",
   "pediatrico":"Crup: Epinefrina racémica 2.25%: 0.05 mL/kg (máx 0.5 mL) en 3 mL SF. L-epinefrina: 0.5 mL/kg (máx 5 mL) de solución 1:1000"},
  ["Sol racémica 2.25% para nebulización","Sol L-epinefrina 1:1000 (1 mg/mL) para nebulización"],"Compatible en situación de emergencia","u04","c04_05",
  familia="Simpaticomiméticos inhalados",emb="C",
  ci=["Ninguna absoluta en emergencia","Epiglotitis (no retrasa intubación)"],
  ea=["Taquicardia","Palidez","Temblor","Efecto rebote (empeoramiento 2-3h post-dosis)","Hipertensión transitoria"],
  ix=["Betabloqueantes: pueden antagonizar efecto broncodilatador"],
  ce=["En crup: observar mínimo 2-4 HORAS post-dosis por efecto rebote","El efecto rebote es la principal preocupación: los síntomas pueden empeorar","No sustituye a intubación si hay compromiso grave","Combinar con dexametasona en crup moderado-severo","Monitorizar FC y SatO2 durante y después"],
  fk={"absorcion":"Inhalada: efecto en 1-5 min","metabolismo":"COMT y MAO","eliminacion":"Renal","vidaMedia":"Efecto: 1-2 horas (rebote posible en 2-3h)"}),

M("aine","acetilcisteina_iv","N-Acetilcisteína IV (respiratoria)","N-Acetilcisteína",["Fluimucil IV","Parvolex"],
  "Mucolítico y antioxidante por vía intravenosa",
  "N-Acetilcisteína por vía IV como mucolítico en situaciones donde la vía oral/inhalada no es posible. Precursor del glutatión con efecto antioxidante pulmonar. Reduce viscosidad del moco por ruptura de puentes disulfuro",
  ["Mucosidad bronquial severa con imposibilidad de vía oral/inhalatoria","Bronquitis severa en UCI","Síndrome de distrés respiratorio (adyuvante, off-label)"],["IV"],
  {"adulto":"300 mg IV c/12h en infusión lenta","ajusteRenal":"Precaución en insuficiencia renal: reducir dosis"},
  ["Amp 300 mg/3 mL"],"Compatible con precaución","u04","c04_05",
  familia="Mucolíticos/antioxidantes",emb="B",
  ci=["Hipersensibilidad","Asma severa activa (riesgo broncoespasmo IV)","Úlcera péptica activa"],
  ea=["Reacciones anafilactoides (más frecuentes que oral)","Náuseas","Vómitos","Rubor","Broncoespasmo (en asmáticos)","Urticaria"],
  ix=["Antibióticos: no mezclar en la misma infusión (inactivación)","Nitroglicerina: potenciación de hipotensión"],
  ce=["Vía IV reservada cuando oral/inhalada no es posible","Riesgo de reacciones anafilactoides: administrar lentamente","Tener adrenalina disponible","No confundir dosificación mucolítica con protocolo de intoxicación por paracetamol","Separar de antibióticos IV"],
  pp={"dilucion":"Diluir en 100-200 mL SG5% (preferido) o SF","velocidadAdministracion":"Infundir en 30-60 min lentamente","estabilidad":"24h a TA diluido"},
  fk={"absorcion":"IV: inmediata","metabolismo":"Hepático: desacetilación → cisteína → glutatión","eliminacion":"Renal","vidaMedia":"6 horas"}),

M("aine","heliox","Heliox","Helio-Oxígeno (mezcla 80:20 o 70:30)",["Heliox"],
  "Gas medicinal de baja densidad para obstrucción de vía aérea",
  "Mezcla de helio (70-80%) y oxígeno (20-30%). El helio, 7 veces menos denso que el nitrógeno, convierte flujo turbulento en laminar en vías aéreas estrechas, reduciendo el trabajo respiratorio",
  ["Crup severo (adyuvante)","Asma aguda severa (puente a tratamiento)","Obstrucción de vía aérea superior","Estridor postextubación"],["inhalatoria"],
  {"adulto":"Heliox 80:20 o 70:30 por mascarilla con reservorio a flujo alto (10-15 L/min)","pediatrico":"Misma mezcla que adultos. Administrar por mascarilla sin fugas"},
  ["Balón de Heliox 80:20 (80% He/20% O2)","Balón de Heliox 70:30 (70% He/30% O2)"],"Compatible","u04","c04_05",
  familia="Gases medicinales",emb="A",
  ci=["Hipoxemia significativa (si se requiere FiO2 >30%, la mezcla 70:30 puede ser insuficiente)"],
  ea=["Voz aguda (por baja densidad del gas, transitorio)","Hipotermia si el gas no se calienta","Ineficaz si FiO2 requerida >40%"],
  ix=["No interacciones farmacológicas"],
  ce=["Eficaz solo si la proporción de helio es ≥60% (pierde efecto con FiO2 >40%)","No es tratamiento definitivo: es puente mientras actúan otros fármacos","El flujo laminar reduce trabajo respiratorio, no trata la causa","Usar con mascarilla sin fugas (alto flujo para evitar arrastre de aire)","No usar en neumotórax (el helio puede expandir el espacio pleural)"],
  alm="Almacenar balones en posición vertical, fijos y asegurados. Lugar ventilado. No requiere refrigeración."),

M("corticoide_sistemico","surfactante_beractant","Surfactante pulmonar (Beractant)","Beractant",["Survanta"],
  "Surfactante pulmonar natural de origen bovino",
  "Extracto de pulmón bovino que contiene fosfolípidos, lípidos neutros y proteínas surfactantes SP-B y SP-C. Reduce tensión superficial alveolar previniendo colapso alveolar",
  ["Síndrome de distrés respiratorio neonatal (tratamiento y profilaxis)","Déficit de surfactante en prematuros"],["intratraqueal"],
  {"pediatrico":"Neonatos: 100 mg/kg/dosis (4 mL/kg) intratraqueal. Puede repetirse c/6h hasta 4 dosis"},
  ["Vial 200 mg/8 mL (suspensión intratraqueal)"],"No aplica (uso neonatal)","u04","c04_05",
  familia="Surfactantes pulmonares",emb="No aplica (uso neonatal)",
  ci=["Ninguna absoluta en emergencia neonatal"],
  ea=["Bradicardia transitoria durante administración","Desaturación transitoria","Obstrucción del tubo endotraqueal","Hemorragia pulmonar (raro)","Neumotórax"],
  ix=["No interacciones significativas"],
  ce=["Temperar a temperatura ambiente (≥8 min) antes de administrar, NO calentar artificialmente","Administrar por tubo endotraqueal en 4 alícuotas con cambio de posición","Verificar posición correcta del TET antes de administrar","Monitorizar SatO2 y FC durante instilación: pausar si bradicardia <80 o SatO2 <85%","Puede requerir ajuste rápido de parámetros ventilatorios post-dosis (mejora rápida de compliance)"],
  fk={"absorcion":"Intratraqueal: distribución alveolar directa","metabolismo":"Reciclaje por neumocitos tipo II","eliminacion":"Catabolismo pulmonar","vidaMedia":"Efecto: 12-24 horas por dosis"},
  alm="Refrigerar 2-8°C. NO congelar. No agitar vigorosamente (voltear suavemente). Proteger de la luz."),

# ── c04_06 Fibrosis Quística (+8) ──
M("aine","ivacaftor","Ivacaftor","Ivacaftor",["Kalydeco"],
  "Potenciador de CFTR (modulador de canal)",
  "Primer modulador de CFTR aprobado. Potencia la probabilidad de apertura del canal CFTR defectuoso en la superficie celular. Eficaz en mutaciones de compuerta (gating) como G551D",
  ["Fibrosis quística con mutación G551D u otras mutaciones de compuerta (gating) respondedoras"],["oral"],
  {"adulto":"150 mg c/12h con alimentos ricos en grasas","pediatrico":"4 meses-<6 años: 25-75 mg c/12h según peso. ≥6 años y ≥25 kg: 150 mg c/12h"},
  ["Comp 150 mg","Gránulos 25, 50, 75 mg"],"No recomendado","u04","c04_06",
  familia="Moduladores de CFTR",emb="B",
  ci=["Hipersensibilidad"],
  ea=["Cefalea","Dolor abdominal","Diarrea","Erupción cutánea","Mareo","Infección respiratoria superior","Elevación transaminasas","Cataratas (pediátricos, monitorizar)"],
  ix=["Inhibidores CYP3A4 potentes (ketoconazol, itraconazol): reducir dosis a 150 mg 2 veces por SEMANA","Inductores CYP3A4 (rifampicina): evitar combinación","Jugo de pomelo: evitar"],
  ce=["SIEMPRE tomar con alimentos ricos en grasas (absorción triple)","Función hepática cada 3 meses el primer año, luego anual","Examen oftalmológico basal y periódico en niños (riesgo cataratas)","Solo eficaz en mutaciones respondedoras: verificar genotipo CFTR","Mejora FEV1 ~10% en G551D"],
  fk={"absorcion":"Oral: mejorada 2-3x con alimentos grasos","metabolismo":"CYP3A4 extenso","eliminacion":"Fecal 88%","vidaMedia":"12 horas"}),

M("aine","lumacaftor_ivacaftor","Lumacaftor/Ivacaftor","Lumacaftor + Ivacaftor",["Orkambi"],
  "Corrector + potenciador de CFTR (doble modulación)",
  "Primera combinación corrector-potenciador. Lumacaftor corrige el plegamiento defectuoso de CFTR-F508del para que alcance la superficie celular; ivacaftor potencia la apertura del canal ya en membrana",
  ["Fibrosis quística homocigota para F508del (≥2 años)"],["oral"],
  {"adulto":"2 comp c/12h (400/250 mg c/12h) con alimentos grasos","pediatrico":"2-5 años: gránulos según peso. 6-11 años: 2 comp c/12h (200/250 mg c/12h). ≥12 años: dosis adulto"},
  ["Comp 200/125 mg (lumacaftor/ivacaftor)","Gránulos 100/125 mg, 150/188 mg"],"No recomendado","u04","c04_06",
  familia="Moduladores de CFTR",emb="B",
  ci=["Hipersensibilidad a lumacaftor o ivacaftor"],
  ea=["Disnea y opresión torácica al inicio","Náuseas","Diarrea","Infección respiratoria superior","Elevación transaminasas","Irregularidades menstruales"],
  ix=["Lumacaftor es inductor CYP3A4: reduce eficacia de anticonceptivos hormonales","Inhibidores CYP3A4: aumentan niveles de ivacaftor","Reduce niveles de: anticonceptivos, benzodiacepinas, itraconazol"],
  ce=["Tomar con alimentos ricos en grasas","Puede causar disnea/opresión en primeros días: iniciar con precaución en FEV1 <40%","Lumacaftor induce CYP3A: las mujeres necesitan anticoncepción NO hormonal o DIU","Función hepática trimestral el primer año","Mejoría modesta de FEV1 (~2.6-4%) vs placebo"],
  fk={"absorcion":"Mejorada con alimentos grasos","metabolismo":"Lumacaftor: mínimo. Ivacaftor: CYP3A4 (pero lumacaftor lo induce)","eliminacion":"Fecal predominante","vidaMedia":"Lumacaftor: 26h; Ivacaftor: 9h (reducida por inducción)"}),

M("aine","tezacaftor_ivacaftor","Tezacaftor/Ivacaftor","Tezacaftor + Ivacaftor",["Symdeko","Symkevi"],
  "Corrector de 2ª gen + potenciador de CFTR",
  "Corrector de segunda generación (tezacaftor) con mejor perfil que lumacaftor + potenciador (ivacaftor). Tezacaftor corrige plegamiento F508del con menos interacciones farmacológicas",
  ["Fibrosis quística homocigota F508del (≥6 años)","FQ heterocigota F508del con mutación residual respondedora"],["oral"],
  {"adulto":"1 comp tezacaftor/ivacaftor (100/150 mg) por la mañana + 1 comp ivacaftor (150 mg) por la noche, con alimentos grasos",
   "pediatrico":"6-11 años: 50/75 mg mañana + 75 mg ivacaftor noche. ≥12 años: dosis adulto"},
  ["Comp 100/150 mg (tezacaftor/ivacaftor) + comp 150 mg (ivacaftor)","Comp 50/75 mg + comp 75 mg (pediátrico)"],"No recomendado","u04","c04_06",
  familia="Moduladores de CFTR",emb="B",
  ci=["Hipersensibilidad a tezacaftor o ivacaftor"],
  ea=["Cefalea","Náuseas","Nasofaringitis","Sinusitis","Infección respiratoria","Elevación transaminasas"],
  ix=["Inhibidores CYP3A4 potentes: reducir dosis","Inductores CYP3A4: evitar","NO induce CYP3A4 (ventaja sobre lumacaftor): menor impacto en anticonceptivos"],
  ce=["Ventaja clave vs Orkambi: NO induce CYP3A (no afecta anticonceptivos)","Mejor tolerabilidad respiratoria que lumacaftor","Tomar con alimentos grasos","Función hepática trimestral el primer año","Mejora FEV1 ~4% en homocigotos F508del"],
  fk={"absorcion":"Mejorada con grasas","metabolismo":"CYP3A4","eliminacion":"Fecal predominante","vidaMedia":"Tezacaftor: 15h; Ivacaftor: 12h"}),

M("aine","elexacaftor_tezacaftor_ivacaftor","Elexacaftor/Tezacaftor/Ivacaftor","Elexacaftor + Tezacaftor + Ivacaftor",["Trikafta","Kaftrio"],
  "Triple modulador de CFTR (2 correctores + 1 potenciador)",
  "Triple terapia moduladora de CFTR: elexacaftor (corrector next-gen) + tezacaftor (corrector) + ivacaftor (potenciador). Revolucionó el tratamiento de FQ al ser eficaz en >90% de pacientes con al menos una copia de F508del",
  ["Fibrosis quística con al menos una mutación F508del (≥2 años)","FQ con mutaciones respondedoras a moduladores"],["oral"],
  {"adulto":"Mañana: 2 comp ELX/TEZ/IVA (200/100/150 mg) con grasas. Noche: 1 comp IVA (150 mg) con grasas (separado 12h)",
   "pediatrico":"2-5 años: gránulos según peso. 6-11 años: ELX/TEZ/IVA 100/50/75 mg mañana + IVA 75 mg noche. ≥12 años: dosis adulto"},
  ["Comp 100/50/75 mg + comp IVA 75 mg (6-11 años)","Comp 200/100/150 mg + comp IVA 150 mg (≥12 años)","Gránulos (pediátrico)"],"No recomendado","u04","c04_06",
  familia="Moduladores de CFTR",emb="B",
  ci=["Hipersensibilidad a cualquier componente"],
  ea=["Erupción cutánea","Cefalea","Infección respiratoria superior","Dolor abdominal","Diarrea","Elevación transaminasas (hasta 5x en 8-10%)","Aumento de CPK","Cataratas en pediátricos"],
  ix=["Inhibidores CYP3A4 potentes (ketoconazol): reducir a dosificación intermitente","Inductores CYP3A4 (rifampicina, carbamezapina): evitar","Ivacaftor: sustrato e inhibidor CYP3A4"],
  ce=["REVOLUCIONARIO: mejora FEV1 ~14% en F508del heterocigotos (sin precedentes en FQ)","Cubre ≥90% de pacientes con FQ (al menos 1 F508del)","SIEMPRE con alimentos ricos en grasas (ambas dosis)","Función hepática: basal, c/3 meses primer año, luego anual","Examen ocular en niños (riesgo cataratas con ivacaftor)","Ha cambiado el pronóstico vital de la FQ"],
  fk={"absorcion":"Mejorada 2-3x con grasas","metabolismo":"CYP3A4/5","eliminacion":"Fecal predominante","vidaMedia":"ELX: 28h; TEZ: 15h; IVA: 12h"}),

M("penicilina","tobramicina_inhalada","Tobramicina inhalada","Tobramicina",["TOBI","TOBI Podhaler","Bethkis"],
  "Aminoglucósido inhalado para colonización por Pseudomonas",
  "Tobramicina formulada para nebulización o inhalación de polvo seco. Alcanza concentraciones bactericidas en esputo 10-25x superiores a la CIM de Pseudomonas con mínima absorción sistémica",
  ["Infección crónica por Pseudomonas aeruginosa en fibrosis quística (≥6 años)","Bronquiectasias con colonización crónica por Pseudomonas"],["inhalatoria"],
  {"adulto":"Nebulización: 300 mg c/12h en ciclos alternos (28 días on / 28 días off). Podhaler: 112 mg (4 cáps) c/12h en ciclos alternos",
   "pediatrico":"≥6 años: misma dosis que adultos"},
  ["Sol para nebulización 300 mg/5 mL","Cáps de polvo para inhalación 28 mg (Podhaler)"],"Evitar durante lactancia","u04","c04_06",
  familia="Aminoglucósidos inhalados",emb="D",
  ci=["Hipersensibilidad a aminoglucósidos"],
  ea=["Disfonía","Tos","Broncoespasmo","Tinnitus","Acúfenos","Hemoptisis"],
  ix=["Otros aminoglucósidos (IV): nefro/ototoxicidad aditiva","Diuréticos de asa: mayor riesgo ototoxicidad","Vancomicina: mayor nefrotoxicidad si absorción sistémica significativa"],
  ce=["Régimen ALTERNO: 28 días de tratamiento seguidos de 28 días sin tratamiento","Nebulizar con PARI LC PLUS o similar (no ultrasónico)","Audiometría basal y periódica","Función renal periódica","Administrar broncodilatador 15 min antes si broncoespasmo","Orden de administración en FQ: broncodilatador → fisioterapia → dornasa → tobramicina"],
  fk={"absorcion":"Mínima absorción sistémica (niveles séricos ~1 mcg/mL)","metabolismo":"No metabolizada","eliminacion":"Renal (la fracción absorbida)","vidaMedia":"Esputo: 2h. Sérica (fracción absorbida): 2-3h"},
  alm="Sol nebulización: refrigerar 2-8°C o TA hasta 28 días. Podhaler: TA ≤30°C. Proteger de humedad."),

M("penicilina","aztreonam_inhalado","Aztreonam lisina inhalado","Aztreonam lisina",["Cayston"],
  "Monobactámico inhalado para Pseudomonas en FQ",
  "Formulación de aztreonam con lisina para nebulización (la formulación IV con arginina causa broncoespasmo). Cobertura exclusiva de gramnegativos con mínima absorción sistémica",
  ["Infección crónica por Pseudomonas aeruginosa en fibrosis quística (≥6 años)"],["inhalatoria"],
  {"adulto":"75 mg nebulizados c/8h en ciclos alternos (28 días on / 28 días off)","pediatrico":"≥6 años: 75 mg c/8h en ciclos alternos"},
  ["Vial liofilizado 75 mg + ampolla de diluyente (sol. salina 0.17%)"],"Compatible con precaución","u04","c04_06",
  familia="Monobactámicos inhalados",emb="B",
  ci=["Hipersensibilidad a aztreonam"],
  ea=["Tos","Congestión nasal","Sibilancias","Fiebre","Dolor torácico","Dolor abdominal","Vómitos"],
  ix=["Mínimas interacciones sistémicas","No presenta reactividad cruzada significativa con penicilinas"],
  ce=["Usar SOLO con nebulizador Altera (no otros)","Reconstituir con el diluyente proporcionado (NO SF normal)","Régimen alterno: 28 días on / 28 días off","Administrar broncodilatador antes","En FQ: administrar después de otros tratamientos inhalados, tobramicina primero"],
  fk={"absorcion":"Mínima sistémica por vía inhalada","metabolismo":"No metabolizado","eliminacion":"Renal (fracción absorbida)","vidaMedia":"Esputo: ~2h. Sérica: ~2.1h"},
  alm="Refrigerar 2-8°C. Puede mantenerse a TA ≤25°C hasta 28 días. Reconstituido: usar inmediatamente."),

M("aine","dornasa_alfa_fq","Dornasa alfa (protocolo FQ)","Dornasa alfa",["Pulmozyme FQ"],
  "ADNasa recombinante en esquema específico para FQ",
  "Dornasa alfa en el contexto de la terapia secuencial de fibrosis quística. Hidroliza ADN extracelular de neutrófilos degenerados, reduciendo la viscosidad del esputo purulento característico de FQ",
  ["Fibrosis quística: reducción de viscosidad del esputo y mejora de función pulmonar (≥5 años)"],["inhalatoria"],
  {"adulto":"2.5 mg nebulizados 1 vez al día (30 min antes de fisioterapia)","pediatrico":"≥5 años: 2.5 mg/día nebulizados"},
  ["Ampolla unidosis 2.5 mg/2.5 mL"],"Compatible con precaución","u04","c04_06",
  familia="Enzimas mucolíticas",emb="B",
  ci=["Hipersensibilidad a dornasa alfa o productos de células CHO"],
  ea=["Disfonía","Rash","Dolor torácico","Conjuntivitis","Laringitis","Faringitis"],
  ix=["No mezclar con otros fármacos en el nebulizador"],
  ce=["ORDEN en FQ: broncodilatador → dornasa alfa (30 min antes de fisio) → fisioterapia → corticoide inhalado → tobramicina","Nebulizar con nebulizador jet (NO ultrasónico: desnaturaliza la enzima)","Mejoría de FEV1: 5-8% sostenida","No diluir ni mezclar en nebulizador","Mantener cadena de frío estricta"],
  fk={"absorcion":"Depósito pulmonar directo","metabolismo":"Proteólisis en vía aérea","eliminacion":"No significativa sistémica","vidaMedia":"No cuantificable (acción local)"},
  alm="Refrigerar 2-8°C. No congelar. Proteger de la luz intensa. Desechar ampolla abierta inmediatamente."),

M("aine","solucion_salina_hipertonica","Solución salina hipertónica inhalada","Cloruro de sodio hipertónico",["HyperSal","MucoClear","Nebusal"],
  "Solución osmótica para aclaramiento mucociliar",
  "Solución de NaCl al 3-7% nebulizada. Actúa por mecanismo osmótico: atrae agua hacia la luz de la vía aérea, hidrata el moco, restaura la capa de líquido periciliar y mejora el aclaramiento mucociliar",
  ["Fibrosis quística: hidratación de secreciones y mejoría de aclaramiento mucociliar","Bronquiolitis (NaCl 3%)","Bronquiectasias","Inducción de esputo para diagnóstico"],["inhalatoria"],
  {"adulto":"NaCl 7%: 4 mL nebulizados c/12h (FQ). NaCl 3%: 4 mL nebulizados c/4-8h (bronquiolitis)",
   "pediatrico":"FQ ≥6 años: NaCl 7% 4 mL c/12h. Bronquiolitis: NaCl 3% 4 mL c/4-8h"},
  ["Sol NaCl 3% 4 mL vial unidosis","Sol NaCl 7% 4 mL vial unidosis"],"Compatible","u04","c04_06",
  familia="Soluciones osmóticas inhaladas",emb="A",
  ci=["Hiperreactividad bronquial severa sin premedicación broncodilatadora"],
  ea=["Tos (muy frecuente)","Broncoespasmo","Sabor salado desagradable","Opresión torácica"],
  ix=["Broncodilatadores: administrar ANTES para prevenir broncoespasmo"],
  ce=["SIEMPRE premedicar con broncodilatador 15 min antes (riesgo broncoespasmo)","En FQ: alternativa económica y eficaz a dornasa alfa","Test de tolerancia antes de primera dosis (espirometría pre/post)","En bronquiolitis infantil: NaCl 3% tiene evidencia moderada, 7% no recomendado","Almacenamiento sencillo: temperatura ambiente"],
  fk={"absorcion":"Acción osmótica local","metabolismo":"No aplica","eliminacion":"Aclaramiento mucociliar","vidaMedia":"Efecto: 6-8 horas"}),

# ── c04_07 Antitusígenos y Descongestionantes (+8) ──
M("broncodilatador_beta2","fenilefrina_oral","Fenilefrina oral (descongestionante)","Fenilefrina",["Sudafed PE","Neo-Sinefrina oral"],
  "Descongestionante nasal oral alfa-1 agonista",
  "Agonista alfa-1 adrenérgico oral usado como descongestionante nasal. Vasoconstricción de mucosa nasal. Eficacia cuestionada por FDA (baja biodisponibilidad oral tras primer paso hepático extenso)",
  ["Congestión nasal por resfriado","Rinitis alérgica (alivio sintomático)","Congestión sinusal"],["oral"],
  {"adulto":"10 mg c/4h. Máx 60 mg/día","pediatrico":"6-11 años: 5 mg c/4h. ≥12 años: dosis adulto"},
  ["Comp 10 mg","Jarabe 2.5 mg/5 mL","Comp combinado con antihistamínicos"],"Compatible con precaución","u04","c04_07",
  familia="Descongestionantes orales",emb="C",
  ci=["HTA severa no controlada","IMAO (14 días)","Cardiopatía isquémica","Hipertiroidismo no tratado"],
  ea=["Insomnio","Nerviosismo","Cefalea","Elevación leve de TA","Mareo","Náuseas"],
  ix=["IMAO: crisis hipertensiva","Betabloqueantes: HTA refleja","Antihipertensivos: reducción de eficacia"],
  ce=["FDA cuestionó eficacia oral en 2023 (biodisponibilidad ~38%)","Pseudoefedrina es alternativa más eficaz","No usar por más de 7 días","Medir TA en pacientes hipertensos","No combinar con otros simpaticomiméticos"]),

M("broncodilatador_beta2","pseudoefedrina","Pseudoefedrina","Pseudoefedrina",["Sudafed","Galpseud"],
  "Descongestionante nasal oral simpaticomimético indirecto",
  "Simpaticomimético indirecto que promueve liberación de noradrenalina endógena. Potente vasoconstrictor de mucosa nasal con buena biodisponibilidad oral. Descongestionante más eficaz por vía oral",
  ["Congestión nasal por resfriado común","Rinitis alérgica (sintomático)","Congestión sinusal","Congestión tubárica (barotrauma)"],["oral"],
  {"adulto":"60 mg c/4-6h o 120 mg c/12h (LP). Máx 240 mg/día","pediatrico":"6-11 años: 30 mg c/4-6h. ≥12 años: dosis adulto"},
  ["Comp 60 mg","Comp LP 120, 240 mg","Jarabe 30 mg/5 mL"],"Compatible con precaución","u04","c04_07",
  familia="Descongestionantes orales",emb="C",
  ci=["HTA severa","IMAO (14 días)","Glaucoma de ángulo cerrado","Retención urinaria","Hipertiroidismo","Cardiopatía isquémica"],
  ea=["Insomnio","Nerviosismo","Taquicardia","Elevación de TA","Temblor","Retención urinaria","Sequedad de boca"],
  ix=["IMAO: crisis hipertensiva grave","Betabloqueantes: HTA","Antihipertensivos: antagonismo","Cafeína: mayor estimulación"],
  ce=["Descongestionante oral más eficaz (superior a fenilefrina oral)","Regulado como precursor de metanfetamina en muchos países (venta restringida)","No usar por más de 7 días","Evitar dosis nocturnas (insomnio)","Contraindicado en deportistas (control antidopaje)"]),

M("aine","noscapina","Noscapina","Noscapina",["Tusscaps","Longatin"],
  "Antitusígeno central no narcótico (alcaloide del opio)",
  "Alcaloide bencilisoquinolínico del opio sin efecto analgésico ni depresor respiratorio. Actúa selectivamente sobre el centro de la tos sin afectar el centro respiratorio. No genera dependencia",
  ["Tos seca no productiva","Tos irritativa crónica"],["oral"],
  {"adulto":"15-30 mg c/4-6h. Máx 180 mg/día","pediatrico":"6-12 años: 7.5-15 mg c/6-8h"},
  ["Comp 15, 30 mg","Jarabe 15 mg/5 mL"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos centrales no opioides",emb="C",
  ci=["Hipersensibilidad","Tos productiva","Embarazo primer trimestre"],
  ea=["Náuseas leves","Somnolencia leve","Cefalea","Mareo"],
  ix=["Warfarina: noscapina puede potenciar efecto anticoagulante (monitorizar INR)"],
  ce=["Antitusígeno central SIN efecto depresor respiratorio ni adictivo","Derivado del opio pero sin propiedades narcóticas","Interacción importante con warfarina: vigilar INR","Alternativa segura a codeína en tos seca"]),

M("aine","butamirato","Butamirato","Citrato de butamirato",["Sinecod","Codiclear"],
  "Antitusígeno central no opioide con acción broncodilatadora",
  "Antitusígeno de acción central no relacionado con opioides. Actúa sobre el centro de la tos y además posee efecto broncodilatador y antiinflamatorio leves. No deprime respiración ni genera dependencia",
  ["Tos seca no productiva de cualquier etiología","Tos irritativa","Tos preoperatoria y postoperatoria"],["oral"],
  {"adulto":"Gotas: 20-40 gotas c/8h. Jarabe: 15 mL c/8h. Comp LP: 50 mg c/8-12h","pediatrico":"2-3 años: 10 gotas c/8h. 3-6 años: 15 gotas c/8h. 6-12 años: 5-10 mL jarabe c/8h"},
  ["Gotas 5 mg/mL","Jarabe 7.5 mg/5 mL","Comp LP 50 mg"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos centrales no opioides",emb="B",
  ci=["Hipersensibilidad","Tos productiva","Primer trimestre embarazo"],
  ea=["Somnolencia leve","Náuseas","Diarrea","Mareo","Exantema (raro)"],
  ix=["Expectorantes: no combinar (efectos opuestos)","Mínimas interacciones conocidas"],
  ce=["No genera dependencia ni tolerancia","No deprime centro respiratorio","Seguro en pediatría (desde 2 meses en algunas presentaciones)","No combinar con mucolíticos/expectorantes","Ampliamente usado en Europa y Latinoamérica"]),

M("aine","cloperastina","Cloperastina","Cloperastina",["Flutox","Sekisan"],
  "Antitusígeno de acción central y periférica con efecto antihistamínico",
  "Antitusígeno con doble mecanismo: acción central sobre el centro de la tos y acción periférica antihistamínica H1. Efecto broncodilatador leve asociado",
  ["Tos seca irritativa","Tos alérgica","Tos nocturna"],["oral"],
  {"adulto":"10-20 mg c/8h","pediatrico":"2-6 años: 5 mg c/8h (jarabe). 6-12 años: 10 mg c/8h"},
  ["Comp 10, 20 mg","Jarabe 3.54 mg/mL"],"Compatible con precaución","u04","c04_07",
  familia="Antitusígenos centrales/antihistamínicos",emb="C",
  ci=["Hipersensibilidad","Tos productiva","Insuficiencia respiratoria","Primer trimestre embarazo"],
  ea=["Somnolencia","Sequedad de boca","Molestias gástricas","Mareo"],
  ix=["Depresores SNC: mayor sedación","Alcohol: sedación aditiva","Mucolíticos: evitar combinación"],
  ce=["Efecto dual: antitusígeno + antihistamínico","Causa somnolencia: precaución al conducir","Útil en tos de componente alérgico","No combinar con mucolíticos"]),

M("aine","difenhidramina_jarabe","Difenhidramina jarabe (antitusígeno)","Difenhidramina",["Benadryl Tos","Tussinol"],
  "Antihistamínico H1 con acción antitusígena en formulación OTC",
  "Antihistamínico H1 de primera generación con acción antitusígena central y efecto secante de secreciones. En jarabe para tos, actúa sobre centro de la tos y reduce secreciones por efecto anticolinérgico",
  ["Tos seca nocturna","Tos asociada a alergia respiratoria","Tos del resfriado común"],["oral"],
  {"adulto":"25-50 mg c/6-8h (jarabe antitusivo)","pediatrico":"6-12 años: 12.5-25 mg c/6-8h"},
  ["Jarabe 12.5 mg/5 mL","Jarabe combinado (con dextrometorfano y/o pseudoefedrina)"],"Evitar durante lactancia","u04","c04_07",
  familia="Antihistamínicos/antitusígenos",emb="B",
  ci=["Neonatos y prematuros","Asma aguda (espesa secreciones)","Glaucoma de ángulo cerrado","Retención urinaria","IMAO"],
  ea=["Somnolencia marcada","Boca seca","Retención urinaria","Espesamiento de secreciones","Excitabilidad paradójica en niños"],
  ix=["Depresores SNC: sedación profunda","IMAO: prolongan efecto anticolinérgico","Alcohol: sedación aditiva"],
  ce=["Causa somnolencia significativa: útil para tos nocturna","NO usar en tos productiva (seca secreciones → impide expectoración)","Efecto anticolinérgico: no ideal en pacientes con mucosidad","Precaución extrema en ancianos (efectos anticolinérgicos)","Riesgo de excitabilidad paradójica en niños pequeños"]),

M("broncodilatador_beta2","oxymetazolina","Oximetazolina","Clorhidrato de oximetazolina",["Afrin","Iliadin","Drixoral"],
  "Descongestionante nasal tópico alfa-agonista de acción prolongada",
  "Simpaticomimético imidazolínico con potente acción vasoconstrictora sobre mucosa nasal. Agonista alfa-1 y alfa-2 directo. Inicio rápido (5-10 min) y duración prolongada (10-12h)",
  ["Congestión nasal aguda","Rinitis aguda","Sinusitis (alivio sintomático)","Facilitación de rinoscopia/procedimientos nasales"],["nasal"],
  {"adulto":"2-3 gotas o 2-3 pulsaciones de spray al 0.05% en cada fosa nasal c/12h. Máx 3 días",
   "pediatrico":"2-6 años: 0.025%, 2-3 gotas c/12h. ≥6 años: 0.05% como adulto. Máx 3 días"},
  ["Spray nasal 0.05%","Gotas nasales 0.025% (pediátrico)","Gotas nasales 0.05%"],"Compatible con precaución","u04","c04_07",
  familia="Descongestionantes nasales tópicos",emb="C",
  ci=["Uso >3 días (rinitis medicamentosa)","IMAO","Glaucoma de ángulo cerrado","Cirugía transesfenoidal reciente"],
  ea=["Ardor nasal transitorio","Estornudos","Sequedad nasal","Rinitis de rebote (>3 días)","Cefalea","Insomnio (raro con tópico)"],
  ix=["IMAO: riesgo hipertensivo","Otros vasoconstrictores nasales: no combinar"],
  ce=["USO MÁXIMO 3 DÍAS (riesgo de rinitis medicamentosa/rebote)","Educar al paciente: uso prolongado causa dependencia nasal","Rinitis medicamentosa es iatrogénica y difícil de tratar","Alternativa: solución salina nasal para uso crónico","Espaciar al menos 12h entre dosis"]),

M("broncodilatador_beta2","xilometazolina","Xilometazolina","Clorhidrato de xilometazolina",["Otrivin","Olynth"],
  "Descongestionante nasal tópico imidazolínico",
  "Derivado imidazolínico con acción vasoconstrictora sobre mucosa nasal por agonismo alfa-adrenérgico. Inicio rápido (5-10 min), duración 8-10 horas. Ampliamente utilizado mundialmente",
  ["Congestión nasal por resfriado","Rinitis aguda","Sinusitis aguda (alivio sintomático)","Otitis media (facilita drenaje de trompa de Eustaquio)"],["nasal"],
  {"adulto":"2-3 gotas o 1-2 pulsaciones al 0.1% en cada fosa nasal c/8-12h. Máx 3-5 días",
   "pediatrico":"<2 años: 0.025% 1 gota c/12h (bajo supervisión). 2-6 años: 0.05% 1-2 gotas c/8-12h. ≥6 años: 0.1% como adulto"},
  ["Spray nasal 0.1%","Gotas nasales 0.05% (pediátrico)","Gotas nasales 0.025% (lactantes)","Spray 0.1% con mentol"],"Compatible con precaución","u04","c04_07",
  familia="Descongestionantes nasales tópicos",emb="C",
  ci=["Uso >5 días (rinitis medicamentosa)","Rinitis seca/atrófica","IMAO","Cirugía nasal reciente","Glaucoma de ángulo cerrado"],
  ea=["Ardor nasal","Sequedad nasal","Estornudos","Rinitis de rebote (uso prolongado)","Cefalea"],
  ix=["IMAO: crisis hipertensiva","Antidepresivos tricíclicos: potenciación vasoconstrictora"],
  ce=["Máximo 3-5 días de uso continuo (rinitis de rebote)","Descongestionante nasal más usado en Europa","No usar en lactantes <3 meses sin indicación médica","La formulación 0.025% para lactantes requiere prescripción en muchos países","Educar sobre riesgo de rinitis medicamentosa crónica"]),
]

NEW_CHAPTERS = {
    "c04_06": {"id":"c04_06","nombre":"Fibrosis Quística","unidadId":"u04","drugIds":[]},
    "c04_07": {"id":"c04_07","nombre":"Antitusígenos y Descongestionantes","unidadId":"u04","drugIds":[]},
}

if __name__ == "__main__":
    print("=== U04 ===")
    count = add_drugs_to_file(DRUGS)
    cats = load_categories()
    for ch_data in NEW_CHAPTERS.values():
        add_chapter(cats, "u04", ch_data)
    for d in DRUGS:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])
    save_categories(cats)
    print(f"Done. {count} drugs added.")
