#!/usr/bin/env python3
"""Supplement batch: U12 Hospitalarios (+35), U10 Hematología (+25), U11 Antídotos (+20)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from drug_helper import add_drugs_to_file, load_categories, save_categories, add_chapter, add_drug_to_chapter
from drug_templates import make_drug as M

# ══════════════════════════════════════════════════════════════════════
# U12 — HOSPITALARIOS SUPLEMENTO (+35)
# ══════════════════════════════════════════════════════════════════════

u12_drugs = [
    # ── Anestesia regional / analgesia epidural ──
    M("anestesico_local", "bupivacaina_epidural", "Bupivacaína Epidural", "bupivacaína",
      ["Marcaine", "Sensorcaine"], "Anestésico local amida para analgesia epidural",
      "Bloquea canales de Na+ dependientes de voltaje; larga duración de acción",
      ["Analgesia epidural para parto", "Anestesia regional quirúrgica", "Bloqueos nerviosos"],
      ["Epidural", "Intratecal"], {"adulto": "Epidural: 0.0625-0.25% a 6-15 mL/h; Intratecal: 7.5-15 mg"},
      ["Amp 0.25% x20 mL", "Amp 0.5% x20 mL", "Amp hiperbárica 0.5%"], "Compatible con precaución",
      "u12", "c12_01",
      pp={"dilucion": "Puede combinarse con fentanilo epidural", "velocidadAdministracion": "Infusión epidural continua 6-15 mL/h", "estabilidad": "24h a temperatura ambiente"}),

    M("anestesico_local", "levobupivacaina_epidural", "Levobupivacaína", "levobupivacaína",
      ["Chirocaine"], "Enantiómero S de bupivacaína; menor cardiotoxicidad",
      "Bloquea canales de Na+; perfil farmacológico similar a bupivacaína pero más seguro",
      ["Analgesia epidural", "Bloqueos nerviosos periféricos", "Anestesia intratecal"],
      ["Epidural", "Intratecal", "Perineural"], "Epidural: 0.125-0.25% a 6-15 mL/h",
      ["Amp 0.25% x10 mL", "Amp 0.5% x10 mL", "Amp 0.75% x10 mL"], "Compatible con precaución",
      "u12", "c12_01"),

    M("anestesico_local", "clorprocaina_epidural", "Clorprocaína", "clorprocaína",
      ["Nesacaine"], "Anestésico local éster de acción ultracorta",
      "Rápida hidrólisis por colinesterasas plasmáticas; muy corta duración",
      ["Anestesia epidural para cirugía ambulatoria", "Anestesia infiltrativa"],
      ["Epidural", "Infiltración"], "Epidural: 2-3% (15-25 mL)",
      ["Fco 2% x20 mL", "Fco 3% x20 mL"], "Compatible",
      "u12", "c12_01"),

    # ── Relajantes neuromusculares ──
    M("anestesico_general", "cisatracurio_detalle2", "Cisatracurio (Infusión UCI)", "cisatracurio",
      ["Nimbex"], "Relajante neuromuscular no despolarizante para UCI",
      "Bloquea receptor nicotínico en unión neuromuscular; degradación de Hofmann (no renal/hepática)",
      ["Relajación en ventilación mecánica UCI", "Facilitación de IOT", "SDRA severo"],
      ["Intravenosa"], "Bolo: 0.15-0.2 mg/kg; Infusión: 1-3 mcg/kg/min",
      ["Amp 2 mg/mL x5 mL", "Amp 2 mg/mL x10 mL"], "Evitar",
      "u12", "c12_01",
      ce=["TOF (Train-of-Four) para monitorizar bloqueo", "Sedación OBLIGATORIA antes de relajación", "Degradación de Hofmann: no requiere ajuste renal/hepático", "Sugammadex NO revierte (usar neostigmina)"],
      pp={"dilucion": "En SF o SG5%", "velocidadAdministracion": "Infusión 1-3 mcg/kg/min", "estabilidad": "24h refrigerado"}),

    # ── Infusiones UCI avanzadas ──
    M("vasopressor", "fenilefrina_infusion", "Fenilefrina Infusión", "fenilefrina",
      ["Neosynephrine IV"], "Agonista alfa-1 puro IV",
      "Vasoconstricción por estimulación directa de receptores alfa-1 adrenérgicos",
      ["Hipotensión intraoperatoria", "Shock distributivo refractario a norepinefrina", "Hipotensión post-anestesia espinal"],
      ["Intravenosa"], "Bolo: 50-200 mcg; Infusión: 0.1-0.5 mcg/kg/min",
      ["Amp 10 mg/mL"], "Evitar",
      "u12", "c12_02",
      ea=["Bradicardia refleja", "HTA", "Isquemia periférica", "Necrosis por extravasación"],
      ce=["Monitorización hemodinámica continua", "Preferible por vía central", "Titular según PAM objetivo", "Vigilar bradicardia refleja (por hipertensión)"],
      pp={"dilucion": "10 mg en 250 mL SF (40 mcg/mL)", "velocidadAdministracion": "0.1-0.5 mcg/kg/min", "estabilidad": "24h a temperatura ambiente"}),

    M("vasopressor", "angiotensina_ii_synth", "Angiotensina II Sintética", "angiotensina II",
      ["Giapreza"], "Vasopressor peptídico",
      "Actúa sobre receptores AT1 causando vasoconstricción directa y liberación de aldosterona",
      ["Shock vasodilatador refractario a catecolaminas"],
      ["Intravenosa"], "Inicio: 20 ng/kg/min; titular según PAM (rango 1.25-80 ng/kg/min)",
      ["Fco 2.5 mg/mL x1 mL"], "Evitar",
      "u12", "c12_02",
      pp={"dilucion": "En SF a concentración 5000-10000 ng/mL", "velocidadAdministracion": "Inicio 20 ng/kg/min; titular", "estabilidad": "24h refrigerado"}),

    M("vasopressor", "isoproterenol_infusion", "Isoproterenol Infusión", "isoproterenol",
      ["Isuprel"], "Agonista beta no selectivo IV",
      "Estimula receptores beta-1 (cronotropo, inotropo) y beta-2 (vasodilatación, broncodilatación)",
      ["Bradicardia severa refractaria a atropina", "Torsade de pointes", "Broncoespasmo severo refractario", "Rechazo agudo post-trasplante cardíaco"],
      ["Intravenosa"], "Infusión: 2-10 mcg/min; titular según FC",
      ["Amp 0.2 mg/mL x1 mL"], "Evitar",
      "u12", "c12_02",
      ci=["Taquiarritmias", "Cardiopatía isquémica activa", "Intoxicación digitálica"],
      ea=["Taquicardia severa", "Arritmias ventriculares", "Isquemia miocárdica", "Temblor", "Cefalea"],
      ce=["Monitorización ECG continua OBLIGATORIA", "Titular para FC objetivo", "Suspender si arritmias ventriculares", "No usar como primera línea en bradicardia (atropina primero)"],
      pp={"dilucion": "1 mg en 250 mL SG5% (4 mcg/mL)", "velocidadAdministracion": "2-10 mcg/min", "estabilidad": "24h protegido de luz"}),

    M("vasopressor", "levosimendan_infusion", "Levosimendán Infusión", "levosimendán",
      ["Simdax"], "Sensibilizador al calcio e inodilatador",
      "Sensibiliza troponina C al calcio (inotropismo) y abre canales KATP (vasodilatación)",
      ["IC aguda descompensada", "Shock cardiogénico", "Destete difícil de inotrópicos"],
      ["Intravenosa"], "Bolo: 6-12 mcg/kg en 10 min (opcional); Infusión: 0.05-0.2 mcg/kg/min x24h",
      ["Fco 2.5 mg/mL x5 mL"], "Evitar",
      "u12", "c12_02",
      familia="Inodilatadores",
      ea=["Hipotensión", "Cefalea", "Taquicardia", "Hipopotasemia", "Fibrilación auricular"],
      ce=["Efecto persiste 7-10 días post-infusión (metabolito activo)", "Monitorización hemodinámica 24-72h", "Puede repetirse cada 2-4 semanas", "No requiere dosis crecientes"],
      pp={"dilucion": "12.5 mg en 250 mL SG5%", "velocidadAdministracion": "0.05-0.2 mcg/kg/min x24h", "estabilidad": "24h protegido de luz"}),

    M("vasopressor", "nitroprusiato_infusion", "Nitroprusiato de Sodio", "nitroprusiato sódico",
      ["Nipride", "Nitropress"], "Vasodilatador arterial y venoso directo",
      "Libera óxido nítrico que activa guanilato ciclasa aumentando GMPc; vasodilatación universal",
      ["Crisis hipertensiva", "IC aguda con congestión", "Hipotensión controlada intraoperatoria", "Disección aórtica (con betabloqueante)"],
      ["Intravenosa"], "Inicio: 0.25-0.5 mcg/kg/min; Máx: 10 mcg/kg/min (>2 mcg/kg/min vigilar cianuro)",
      ["Fco 50 mg liofilizado"], "Evitar",
      "u12", "c12_02",
      familia="Vasodilatadores directos",
      ci=["Hipotensión severa", "Insuficiencia hepática grave", "Déficit vitamina B12 (Leber)", "Derivaciones arteriovenosas"],
      ea=["Hipotensión", "Toxicidad por cianuro", "Toxicidad por tiocianato (uso prolongado)", "Cefalea", "Náuseas", "Acidosis láctica"],
      ce=["Proteger de luz (envolver en papel aluminio)", "Monitorizar PA continua con línea arterial", "Vigilar signos toxicidad cianuro si >48h o >2 mcg/kg/min", "Tiosulfato sódico como antídoto de cianuro", "Desechar si solución cambia de color"],
      pp={"dilucion": "50 mg en 250-1000 mL SG5% (PROTEGER DE LUZ)", "velocidadAdministracion": "0.25-10 mcg/kg/min", "estabilidad": "24h protegido de luz; desechar si marrón/azul"}),

    # ── Medicación intratecal ──
    M("anestesico_local", "baclofeno_intratecal", "Baclofeno Intratecal", "baclofeno",
      ["Lioresal Intratecal", "Gablofen"], "Agonista GABA-B intratecal",
      "Inhibe reflejos espinales mono y polisinápticos; administración intratecal minimiza efectos centrales",
      ["Espasticidad severa de origen cerebral o espinal", "Espasticidad en EM, LME, parálisis cerebral"],
      ["Intratecal"], "Dosis test: 50-100 mcg; Mantenimiento: 100-1000 mcg/día por bomba",
      ["Amp intratecal 0.05 mg/mL", "Amp 0.5 mg/mL", "Amp 2 mg/mL"], "Evitar",
      "u12", "c12_03",
      familia="Antiespasmódicos intratecales",
      ci=["Hipersensibilidad", "Infección en sitio de implantación de bomba"],
      ea=["Somnolencia", "Mareo", "Náuseas", "Retención urinaria", "Debilidad muscular", "Síndrome de abstinencia si suspensión abrupta"],
      ce=["NUNCA suspender bruscamente (riesgo fatal: hipertermia, rabdomiólisis)", "Verificar funcionamiento de bomba regularmente", "Recarga de bomba en fechas programadas", "Vigilar signos de sobredosis: somnolencia extrema, depresión respiratoria"],
      pp={"dilucion": "No diluir para uso en bomba intratecal", "velocidadAdministracion": "Infusión continua por bomba intratecal programable", "estabilidad": "Según fabricante de bomba"}),

    # ── Nutrición parenteral avanzada ──
    M("anestesico_general", "dipeptiven", "Alanil-Glutamina", "L-alanil-L-glutamina",
      ["Dipeptiven"], "Dipéptido de glutamina para nutrición parenteral",
      "Provee glutamina (aminoácido condicionalmente esencial en estado crítico) para enterocitos e inmunidad",
      ["Suplemento de nutrición parenteral en pacientes críticos", "Soporte inmunológico en UCI"],
      ["Intravenosa"], "0.3-0.5 g/kg/día (máx 20% del aporte aminoacídico)",
      ["Fco 100 mL (200 mg/mL)"], "Compatible con precaución",
      "u12", "c12_04",
      familia="Suplementos parenterales",
      pp={"dilucion": "Agregar a bolsa de NPT o diluir en SF", "velocidadAdministracion": "Según velocidad de NPT", "estabilidad": "24h en mezcla NPT"}),

    M("anestesico_general", "selenio_iv", "Selenio IV", "selenito de sodio",
      ["Selenase", "Selenium IV"], "Oligoelemento esencial IV",
      "Cofactor de glutatión peroxidasa; función antioxidante crítica en sepsis",
      ["Deficiencia de selenio en NPT", "Sepsis severa (soporte antioxidante)", "Nutrición parenteral prolongada"],
      ["Intravenosa"], "100-500 mcg/día IV; Sepsis: hasta 1000 mcg/día",
      ["Amp 100 mcg/2 mL", "Amp 500 mcg/10 mL"], "Compatible",
      "u12", "c12_04",
      familia="Oligoelementos parenterales"),

    M("anestesico_general", "vitamina_c_iv", "Vitamina C Intravenosa", "ácido ascórbico IV",
      ["Ascorbic Acid IV", "Cenolate"], "Vitamina hidrosoluble IV",
      "Cofactor enzimático antioxidante; soporte en sepsis y quemados",
      ["Escorbuto", "Déficit en NPT", "Sepsis (protocolo adjunto)", "Quemados extensos"],
      ["Intravenosa"], "200 mg-1.5 g/día IV; Sepsis: 1.5 g c/6h (protocolos)",
      ["Amp 500 mg/5 mL", "Fco 1 g/5 mL"], "Compatible",
      "u12", "c12_04",
      familia="Vitaminas parenterales",
      pp={"dilucion": "En SF o SG5%", "velocidadAdministracion": "Infusión en 30-60 min", "estabilidad": "Usar inmediatamente tras diluir"}),

    # ── Antineoplásicos adicionales ──
    M("antineoplasico", "carfilzomib", "Carfilzomib", "carfilzomib",
      ["Kyprolis"], "Inhibidor irreversible de proteosoma",
      "Se une irreversiblemente al proteosoma 20S inhibiendo degradación proteica y causando apoptosis",
      ["Mieloma múltiple recaído/refractario"],
      ["Intravenosa"], "20-56 mg/m² IV días 1,2,8,9,15,16 de ciclo 28 días",
      ["Fco 10 mg", "Fco 30 mg", "Fco 60 mg liofilizado"], "Contraindicada",
      "u12", "c12_05",
      pp={"dilucion": "Reconstituir con agua estéril; puede infundir directo o en 50 mL SG5%", "velocidadAdministracion": "Infusión IV en 10-30 min", "estabilidad": "24h refrigerado"}),

    M("antineoplasico", "lenvatinib", "Lenvatinib", "lenvatinib",
      ["Lenvima"], "Inhibidor multiquinasa oral",
      "Inhibe VEGFR1-3, FGFR1-4, PDGFRα, RET y KIT; antiangiogénico y antiproliferativo",
      ["Carcinoma tiroideo diferenciado resistente a yodo", "Carcinoma hepatocelular (con pembrolizumab)", "Carcinoma endometrial avanzado"],
      ["Oral"], "24 mg/día (tiroides); 8-12 mg/día (CHC combo)",
      ["Cáps 4 mg", "Cáps 10 mg"], "Contraindicada",
      "u12", "c12_05",
      ea=["Hipertensión", "Diarrea", "Fatiga", "Proteinuria", "Hipotiroidismo", "Palmoplantar (mano-pie)"],
      ce=["Control TA semanal al inicio", "Proteinuria regular", "Función tiroidea periódica", "Vigilar sangrado y perforación GI"]),

    M("antineoplasico", "abiraterona_onco", "Abiraterona (Oncología)", "abiraterona",
      ["Zytiga"], "Inhibidor de CYP17A1",
      "Inhibe 17α-hidroxilasa/C17,20-liasa suprimiendo síntesis de andrógenos tumoral y adrenal",
      ["Cáncer de próstata metastásico resistente a castración"],
      ["Oral"], "1000 mg/día en ayunas (con prednisona 5 mg c/12h)",
      ["Tab 250 mg", "Tab 500 mg"], "Contraindicada",
      "u12", "c12_05"),

    M("antineoplasico", "ibrutinib", "Ibrutinib", "ibrutinib",
      ["Imbruvica"], "Inhibidor de tirosina cinasa de Bruton (BTK)",
      "Inhibe irreversiblemente BTK bloqueando señalización del receptor de células B",
      ["LLC/LLP", "Linfoma de células del manto", "Macroglobulinemia de Waldenström"],
      ["Oral"], "420-560 mg/día (según indicación)",
      ["Cáps 140 mg", "Tab 140 mg", "Tab 420 mg", "Tab 560 mg"], "Contraindicada",
      "u12", "c12_05",
      ea=["Sangrado", "Fibrilación auricular", "Infecciones", "Diarrea", "Artralgias", "HTA"],
      ce=["Suspender 3-7 días antes de cirugía", "Vigilar FA y arritmias", "Evitar anticoagulantes y antiagregantes si posible", "No triturar ni abrir cápsulas"]),

    M("antineoplasico", "olaparib", "Olaparib", "olaparib",
      ["Lynparza"], "Inhibidor de PARP oral",
      "Inhibe poli(ADP-ribosa) polimerasa impidiendo reparación del ADN en tumores con déficit de HR (BRCA)",
      ["Cáncer de ovario con mutación BRCA", "Cáncer de mama HER2- con BRCA germinal", "Cáncer de próstata con HRR mutado", "Cáncer de páncreas con BRCA germinal"],
      ["Oral"], "300 mg c/12h",
      ["Tab 100 mg", "Tab 150 mg"], "Contraindicada",
      "u12", "c12_05"),

    M("antineoplasico", "lorlatinib", "Lorlatinib", "lorlatinib",
      ["Lorbrena"], "Inhibidor de ALK/ROS1 de 3ª generación",
      "Inhibe ALK y ROS1 incluyendo mutaciones de resistencia; penetra barrera hematoencefálica",
      ["NSCLC ALK+ avanzado (1ª línea o tras progresión)"],
      ["Oral"], "100 mg/día",
      ["Tab 25 mg", "Tab 100 mg"], "Contraindicada",
      "u12", "c12_05"),

    M("antineoplasico", "enfortumab_vedotin", "Enfortumab Vedotina", "enfortumab vedotina",
      ["Padcev"], "Conjugado anticuerpo-fármaco anti-Nectina-4",
      "Anti-Nectina-4 conjugado con MMAE; internalización y liberación de citotóxico intracelular",
      ["Carcinoma urotelial avanzado (con pembrolizumab 1ª línea o monoterapia)"],
      ["Intravenosa"], "1.25 mg/kg (máx 125 mg) IV días 1, 8, 15 c/28 días",
      ["Fco 20 mg", "Fco 30 mg liofilizado"], "Contraindicada",
      "u12", "c12_05",
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión IV en 30 min", "estabilidad": "24h refrigerado"}),

    M("antineoplasico", "trastuzumab_deruxtecan", "Trastuzumab Deruxtecán", "trastuzumab deruxtecán",
      ["Enhertu"], "Conjugado anticuerpo-fármaco anti-HER2",
      "Anti-HER2 conjugado con inhibidor de topoisomerasa I; efecto bystander en células vecinas",
      ["Cáncer de mama HER2+ metastásico", "Cáncer de mama HER2-low", "NSCLC con mutación HER2", "Cáncer gástrico HER2+"],
      ["Intravenosa"], "5.4 mg/kg IV c/3 semanas",
      ["Fco 100 mg liofilizado"], "Contraindicada",
      "u12", "c12_05",
      ea=["Enfermedad pulmonar intersticial (EPI)", "Neutropenia", "Náuseas", "Fatiga", "Alopecia", "Anemia"],
      ce=["Vigilar EPI: disnea, tos, fiebre (suspender si sospecha)", "Hemograma antes de cada ciclo", "Premedicación antiemética", "Radiografía/TC tórax basal"],
      pp={"dilucion": "En 100 mL SG5% (NO SF)", "velocidadAdministracion": "Primera infusión: 90 min; Siguientes: 30 min si tolera", "estabilidad": "24h refrigerado"}),

    # ── Fluidos avanzados ──
    M("anestesico_general", "albumina_5", "Albúmina 5%", "albúmina humana 5%",
      ["Albutein 5%", "Plasbumin 5"], "Expansor plasmático isooncótico",
      "Expande volumen plasmático de forma isooncótica sin efecto osmótico excesivo",
      ["Reposición de volumen en quemados", "Paracentesis de gran volumen", "Hipoalbuminemia sintomática"],
      ["Intravenosa"], "250-500 mL IV según necesidad; Post-paracentesis: 6-8 g/L de ascitis drenada",
      ["Fco 250 mL al 5%", "Fco 500 mL al 5%"], "Compatible",
      "u12", "c12_07",
      familia="Soluciones coloides",
      pp={"dilucion": "No requiere dilución", "velocidadAdministracion": "1-2 mL/min; más rápido en emergencia", "estabilidad": "4h tras apertura"}),

    M("anestesico_general", "hidroxietilalmidon", "Hidroxietilalmidón", "HES 130/0.4",
      ["Voluven", "Volulyte"], "Coloide sintético expansor de volumen",
      "Aumenta presión oncótica intravascular expandiendo volumen plasmático",
      ["Reposición aguda de volumen cuando cristaloides son insuficientes"],
      ["Intravenosa"], "Máx 30 mL/kg/día",
      ["Fco 500 mL HES 6% en SF", "Fco 500 mL HES 6% en solución balanceada"], "Evitar",
      "u12", "c12_07",
      familia="Soluciones coloides",
      ci=["Sepsis", "Pacientes críticos", "Insuficiencia renal", "Coagulopatía", "Quemados"],
      ea=["Nefrotoxicidad", "Coagulopatía", "Prurito prolongado", "Anafilaxia"],
      ce=["CONTRAINDICADO en sepsis y UCI (mayor mortalidad)", "Función renal antes y después", "Máximo 24h de uso", "Preferir cristaloides balanceados como primera línea"]),

    M("anestesico_general", "manitol_cerebral", "Manitol (Neurología)", "manitol",
      ["Osmitrol"], "Diurético osmótico para hipertensión intracraneal",
      "Crea gradiente osmótico que reduce edema cerebral y presión intracraneal",
      ["Hipertensión intracraneal", "Edema cerebral", "Glaucoma agudo (reducción presión intraocular)"],
      ["Intravenosa"], "0.25-1 g/kg IV en 15-20 min; repetir c/4-6h (osmolalidad sérica <320 mOsm)",
      ["Fco 20% x250 mL", "Fco 20% x500 mL"], "Compatible con precaución",
      "u12", "c12_07",
      familia="Diuréticos osmóticos",
      ci=["Anuria establecida", "Hemorragia intracraneal activa", "Deshidratación severa", "Edema pulmonar"],
      ea=["Depleción de volumen", "Hipernatremia", "Hipopotasemia", "Rebote de PIC", "Insuficiencia renal"],
      ce=["Osmolalidad sérica cada 6h (mantener <320)", "Balance hídrico estricto", "Electrolitos cada 6h", "Usar filtro en línea (cristales)", "No administrar si solución tiene cristales"],
      pp={"dilucion": "No diluir; puede calentar para disolver cristales", "velocidadAdministracion": "En 15-20 min (bolo)", "estabilidad": "Usar tras calentar si cristalizó"}),

    M("anestesico_general", "solucion_salina_3", "Solución Salina Hipertónica 3%", "cloruro de sodio 3%",
      ["NaCl 3%"], "Solución hipertónica para hiponatremia severa y HIC",
      "Eleva osmolalidad sérica corrigiendo hiponatremia y reduciendo edema cerebral",
      ["Hiponatremia severa sintomática", "Hipertensión intracraneal refractaria a manitol", "Herniación cerebral inminente"],
      ["Intravenosa"], "HIC: bolo 150 mL en 20 min; Hiponatremia: 1-2 mL/kg/h (corregir Na+ ≤8-10 mEq/24h)",
      ["Fco 500 mL NaCl 3%"], "Evitar",
      "u12", "c12_07",
      familia="Soluciones hipertónicas",
      ci=["Hipernatremia"],
      ea=["Sobrecarga de volumen", "Hipernatremia", "Mielinólisis pontina central (corrección rápida Na+)", "Flebitis"],
      ce=["Na+ sérico cada 2-4h durante corrección", "NO corregir >8-10 mEq en 24h (riesgo mielinólisis)", "Administrar por vía central si concentración >3%", "Monitorizar osmolalidad y balance hídrico"],
      pp={"dilucion": "No requiere dilución", "velocidadAdministracion": "1-2 mL/kg/h o bolo 150 mL en 20 min", "estabilidad": "Estable a temperatura ambiente"}),

    # ── Sedoanalgesia avanzada ──
    M("opioide", "metadona_iv", "Metadona IV", "metadona clorhidrato",
      ["Metadona IV"], "Opioide sintético IV de larga duración",
      "Agonista mu; también antagonista NMDA y recaptación de serotonina/norepinefrina",
      ["Dolor severo refractario a otros opioides", "Rotación opioidea en tolerancia", "Sedoanalgesia UCI prolongada"],
      ["Intravenosa"], "2.5-10 mg IV c/8-12h; titular según respuesta",
      ["Amp 10 mg/mL x1 mL"], "Evitar",
      "u12", "c12_03",
      ci=["Hipersensibilidad", "Depresión respiratoria severa", "Íleo paralítico", "Prolongación QT basal"],
      ea=["Prolongación QT", "Depresión respiratoria", "Sedación", "Estreñimiento", "Acumulación con dosis repetidas"],
      ce=["ECG basal y periódico (QT)", "Vida media muy variable (8-59h): riesgo de acumulación", "Interacciones CYP3A4 y CYP2B6 extensas", "Iniciar con dosis bajas y titular lentamente"],
      pp={"dilucion": "Puede administrar sin diluir IV lenta o en 50 mL SF", "velocidadAdministracion": "IV lenta en 3-5 min", "estabilidad": "Estable a temperatura ambiente"}),

    M("anestesico_general", "oxido_nitroso_analg", "Óxido Nitroso 50%/O2 50%", "óxido nitroso + oxígeno",
      ["Entonox", "Kalinox"], "Mezcla equimolar de N2O/O2 para analgesia",
      "Analgesia por acción sobre receptores NMDA y opioides endógenos; efecto rápido y reversible",
      ["Analgesia para procedimientos dolorosos breves", "Trabajo de parto", "Curas y cambios de apósitos", "Procedimientos pediátricos"],
      ["Inhalatoria"], "Autoadministración por mascarilla durante el procedimiento",
      ["Cilindro N2O 50%/O2 50% x5L", "Cilindro 170L"], "Compatible con precaución",
      "u12", "c12_03",
      familia="Analgesia inhalatoria",
      ci=["Neumotórax", "Embolia gaseosa", "Obstrucción intestinal (distensión por N2O)", "Traumatismo facial", "Estado de conciencia alterado"],
      ea=["Náuseas", "Mareo", "Euforia", "Sedación leve", "Déficit vitamina B12 (uso prolongado)"],
      ce=["Paciente AUTOCONTROLA la mascarilla (seguridad)", "Ventilación adecuada de la sala", "Monitorizar SatO2", "Contraindicado si riesgo de espacio cerrado con gas"]),

    # ── Soporte transfusional ──
    M("anestesico_general", "crioprecipitado", "Crioprecipitado", "crioprecipitado",
      ["Crioprecipitado"], "Hemoderivado rico en fibrinógeno y factor VIII",
      "Concentrado de fibrinógeno, factor VIII, factor XIII, vWF y fibronectina obtenido del plasma",
      ["Hipofibrinogenemia (<100 mg/dL)", "CID con sangrado", "Déficit de factor XIII", "Sangrado masivo"],
      ["Intravenosa"], "1 unidad por cada 5 kg de peso; o 10 unidades (adulto estándar)",
      ["Bolsa individual (~15 mL)"], "Compatible",
      "u12", "c12_07",
      familia="Hemoderivados",
      ci=["Hipersensibilidad a componentes plasmáticos"],
      ea=["Reacción transfusional", "Reacción alérgica", "Sobrecarga de volumen", "Transmisión infecciosa (raro)"],
      ce=["Verificar compatibilidad ABO", "No descongelar a >37°C", "Administrar dentro de 6h post-descongelación", "Monitorizar fibrinógeno post-transfusión", "Signos vitales cada 15 min durante transfusión"]),

    M("anestesico_general", "concentrado_fibrinogeno", "Concentrado de Fibrinógeno", "fibrinógeno humano",
      ["RiaSTAP", "Fibryga"], "Factor de coagulación I purificado",
      "Reemplaza fibrinógeno deficiente restaurando formación de coágulo de fibrina",
      ["Hipofibrinogenemia congénita o adquirida", "Sangrado quirúrgico con fibrinógeno bajo", "CID"],
      ["Intravenosa"], "Dosis: (nivel objetivo - nivel actual en mg/dL) ÷ 1.7 × peso en kg; típico: 1-4 g IV",
      ["Fco 1 g liofilizado"], "Compatible con precaución",
      "u12", "c12_07",
      familia="Factores de coagulación",
      pp={"dilucion": "Reconstituir con agua estéril según fabricante", "velocidadAdministracion": "≤5 mL/min IV", "estabilidad": "8h tras reconstitución"}),
]

# ══════════════════════════════════════════════════════════════════════
# U10 — HEMATOLOGÍA SUPLEMENTO (+25)
# ══════════════════════════════════════════════════════════════════════

u10_drugs = [
    # ── Anticoagulantes especiales ──
    M("anticoagulante_oral", "apixaban_detalle", "Apixabán Tromboprofilaxis", "apixabán",
      ["Eliquis Profilaxis"], "ACOD anti-Xa para tromboprofilaxis",
      "Inhibición directa y selectiva del factor Xa; dosis reducida para profilaxis quirúrgica",
      ["Tromboprofilaxis en cirugía de cadera/rodilla", "Prevención TEV en pacientes oncológicos"],
      ["Oral"], "2.5 mg c/12h (inicio 12-24h post-cirugía); cadera: 32-38 días; rodilla: 10-14 días",
      ["Tab 2.5 mg"], "Evitar",
      "u10", "c10_01"),

    M("heparina", "heparina_bajo_peso", "Heparina bajo peso molecular genérica", "heparina de bajo peso molecular",
      ["HBPM genérica"], "Heparina fraccionada genérica",
      "Inhibe preferentemente factor Xa con menor efecto sobre trombina que HNF",
      ["Tromboprofilaxis en cirugía mayor", "Profilaxis TVP en inmovilización", "Tratamiento TEV"],
      ["Subcutánea"], "Profilaxis: 20-40 mg SC c/24h; Tratamiento: 1 mg/kg SC c/12h según preparado",
      ["Jeringas precargadas según marca"], "Compatible con precaución",
      "u10", "c10_01"),

    M("anticoagulante_oral", "rivaroxaban_profilaxis", "Rivaroxabán Tromboprofilaxis", "rivaroxabán",
      ["Xarelto Profilaxis"], "ACOD anti-Xa para tromboprofilaxis quirúrgica",
      "Inhibición directa y selectiva del factor Xa oral",
      ["Tromboprofilaxis post-cirugía cadera/rodilla", "Prevención TEV en hospitalización médica"],
      ["Oral"], "10 mg c/24h (inicio 6-10h post-cirugía); cadera: 35 días; rodilla: 14 días",
      ["Tab 10 mg"], "Evitar",
      "u10", "c10_01"),

    # ── Trombolíticos y manejo de trombosis ──
    M("heparina", "alteplasa_tvp", "Alteplasa para TEP masivo", "alteplasa",
      ["Activase TEP"], "Trombolítico tPA para TEP masivo",
      "Activa plasminógeno a plasmina disolviendo trombos; indicación específica para TEP con inestabilidad",
      ["TEP masivo con inestabilidad hemodinámica", "TEP submasivo con deterioro clínico"],
      ["Intravenosa"], "100 mg IV en 2h; o régimen acelerado: 0.6 mg/kg (máx 50 mg) en 15 min",
      ["Fco 50 mg", "Fco 100 mg"], "Contraindicada",
      "u10", "c10_01",
      familia="Trombolíticos",
      pp={"dilucion": "En SF a 1 mg/mL o usar sin diluir", "velocidadAdministracion": "100 mg en 2h estándar; 50 mg en 15 min acelerado", "estabilidad": "8h reconstituido"}),

    # ── Antiagregantes especiales ──
    M("anticoagulante_oral", "ticlopidina", "Ticlopidina", "ticlopidina",
      ["Ticlid", "Ticlopidina"], "Tienopiridina antiagregante de 1ª generación",
      "Inhibe irreversiblemente receptor P2Y12 de ADP plaquetario",
      ["Prevención secundaria de ACV", "Prevención trombosis de stent (alternativa a clopidogrel)"],
      ["Oral"], "250 mg c/12h con alimentos",
      ["Tab 250 mg"], "Evitar",
      "u10", "c10_01",
      familia="Antiagregantes plaquetarios",
      ci=["Hipersensibilidad", "Diátesis hemorrágica", "Leucopenia/neutropenia", "TTP previa"],
      ea=["Neutropenia/agranulocitosis (1-2%)", "TTP", "Diarrea", "Rash", "Hepatotoxicidad"],
      ce=["Hemograma cada 2 semanas los primeros 3 meses", "Suspender si neutrófilos <1200", "Riesgo de TTP en primeras semanas", "Tomar con alimentos para absorción"]),

    # ── Factores de crecimiento hematopoyético ──
    M("heparina", "trombopoietina_romiplostim", "Romiplostim detallado", "romiplostim",
      ["Nplate detallado"], "Agonista de receptor de trombopoyetina",
      "Péptido Fc-fusionado que estimula receptor c-Mpl aumentando producción de plaquetas",
      ["Trombocitopenia inmune (PTI) crónica refractaria a corticoides e inmunoglobulinas"],
      ["Subcutánea"], "Inicio: 1 mcg/kg SC semanal; titular según plaquetas (máx 10 mcg/kg/sem)",
      ["Fco 125 mcg", "Fco 250 mcg", "Fco 500 mcg liofilizado"], "Evitar",
      "u10", "c10_03",
      familia="Agonistas de trombopoyetina",
      ci=["Hipersensibilidad"],
      ea=["Cefalea", "Trombosis (por elevación excesiva de plaquetas)", "Fibrosis medular (uso prolongado)", "Artralgias"],
      ce=["Plaquetas semanales durante titulación", "No superar plaquetas >400,000 (ajustar dosis)", "Vigilar trombosis", "Biopsia de médula si fibrosis sospechada"]),

    M("heparina", "luspatercept_detalle", "Luspatercept detallado", "luspatercept",
      ["Reblozyl detallado"], "Agente de maduración eritroide",
      "Ligando trampa para TGF-β superfamilia; promueve maduración eritroide tardía",
      ["Anemia en síndromes mielodisplásicos con sideroblastos en anillo", "Anemia dependiente de transfusión en beta-talasemia"],
      ["Subcutánea"], "Inicio: 1 mg/kg SC c/3 semanas; máx 1.75 mg/kg",
      ["Fco 25 mg", "Fco 75 mg liofilizado"], "Evitar",
      "u10", "c10_03",
      familia="Agentes de maduración eritroide"),

    M("heparina", "eltrombopag_detalle", "Eltrombopag detallado", "eltrombopag",
      ["Revolade detallado"], "Agonista de TPO oral",
      "Agonista oral del receptor de trombopoyetina c-Mpl; estimula megacariopoyesis",
      ["PTI crónica", "Anemia aplásica severa (con inmunosupresión)", "Trombocitopenia por hepatitis C"],
      ["Oral"], "PTI: 50 mg/día (25 mg en asiáticos); AA: 150 mg/día; ajustar según plaquetas",
      ["Tab 25 mg", "Tab 50 mg", "Tab 75 mg"], "Evitar",
      "u10", "c10_03",
      familia="Agonistas de trombopoyetina",
      ci=["Hipersensibilidad", "Insuficiencia hepática grave"],
      ea=["Hepatotoxicidad", "Trombosis", "Cataratas", "Fibrosis medular"],
      ce=["Función hepática cada 2 semanas al inicio", "Tomar en ayunas (2h antes/1h después de comidas)", "No tomar con lácteos ni antiácidos (quelación)", "Plaquetas semanales durante titulación"]),

    # ── Hemostáticos avanzados ──
    M("heparina", "acido_aminocaproico_iv", "Ácido Aminocaproico IV", "ácido aminocaproico",
      ["Amicar IV"], "Antifibrinolítico IV",
      "Inhibe activación de plasminógeno a plasmina; estabiliza coágulos de fibrina",
      ["Sangrado post-cirugía cardíaca", "Hemorragia por hiperfibrinólisis", "Sangrado post-trombolítico"],
      ["Intravenosa", "Oral"], "Carga: 4-5 g IV en 1h; Mantenimiento: 1-1.25 g/h IV (máx 30 g/24h)",
      ["Amp 250 mg/mL x20 mL", "Tab 500 mg", "Jarabe 250 mg/mL"], "Compatible con precaución",
      "u10", "c10_02",
      familia="Antifibrinolíticos",
      pp={"dilucion": "En SF, SG5% o Ringer", "velocidadAdministracion": "Carga: 4-5 g en 1h; Mantenimiento: 1 g/h", "estabilidad": "24h diluido"}),

    M("heparina", "trombina_recombinante", "Trombina Recombinante Tópica", "trombina humana recombinante",
      ["Recothrom"], "Hemostático tópico recombinante",
      "Convierte fibrinógeno en fibrina formando coágulo directamente en superficie de sangrado",
      ["Hemostasia quirúrgica tópica", "Sangrado de superficies capilares"],
      ["Tópica"], "Aplicar directamente sobre superficie sangrante",
      ["Fco 5000 UI polvo + diluyente", "Kit con esponja"], "No aplica",
      "u10", "c10_02",
      familia="Hemostáticos tópicos",
      ci=["Hipersensibilidad", "NO inyectar (uso tópico exclusivo)"],
      ea=["Raros: anticuerpos anti-trombina"],
      ce=["USO TÓPICO EXCLUSIVO: nunca inyectar", "Aplicar con esponja de gelatina absorbible", "Controlar fuente si sangrado arterial"]),

    M("heparina", "sellador_fibrina", "Sellador de Fibrina", "fibrinógeno + trombina humana",
      ["Tisseel", "Evicel"], "Adhesivo tisular hemostático",
      "Reproduce la etapa final de la coagulación: trombina convierte fibrinógeno en coágulo de fibrina",
      ["Hemostasia quirúrgica complementaria", "Sellado de suturas vasculares", "Fijación de injertos de piel"],
      ["Tópica"], "Aplicar directamente sobre tejido según extensión",
      ["Kit doble jeringa (fibrinógeno + trombina)"], "No aplica",
      "u10", "c10_02",
      familia="Adhesivos tisulares",
      ci=["Hipersensibilidad", "NO inyectar intravascularmente"],
      ea=["Reacción alérgica (raro)", "Tromboembolismo si inyección intravascular accidental"],
      ce=["Mezclar componentes al momento de aplicar", "No inyectar intravascularmente", "Superficie debe estar seca para adherencia"]),

    # ── Nuevos anticoagulantes/antitrombóticos ──
    M("anticoagulante_oral", "abelacimab", "Abelacimab", "abelacimab",
      ["Abelacimab"], "Anticuerpo anti-factor XI",
      "Anticuerpo monoclonal que inhibe factor XI y XIa; anticoagulación sin aumento significativo de sangrado",
      ["Prevención de TEV post-cirugía ortopédica", "Prevención de ACV en FA (en investigación)"],
      ["Subcutánea"], "150 mg SC mensual",
      ["Jer 150 mg"], "Evitar",
      "u10", "c10_01",
      familia="Anticuerpos anti-factor XI"),

    M("anticoagulante_oral", "milvexian", "Milvexián", "milvexián",
      ["Milvexian"], "Inhibidor oral de factor XIa",
      "Inhibe selectivamente factor XIa de coagulación; menor riesgo hemorrágico teórico",
      ["Prevención secundaria post-ACV (en investigación)", "Prevención TEV"],
      ["Oral"], "25-200 mg c/12h (dosis en estudio)",
      ["Tab 25 mg", "Tab 50 mg", "Tab 100 mg", "Tab 200 mg"], "Evitar",
      "u10", "c10_01",
      familia="Inhibidores de factor XIa"),

    # ── Terapia celular ──
    M("heparina", "tisagenlecleucel", "Tisagenlecleucel", "tisagenlecleucel",
      ["Kymriah"], "Terapia CAR-T anti-CD19",
      "Linfocitos T autólogos modificados con receptor quimérico anti-CD19 que atacan células B tumorales",
      ["LLA-B recaída/refractaria en pediátrico/adulto joven", "Linfoma difuso de células B grandes recaído"],
      ["Intravenosa"], "Dosis única basada en peso: 0.2-5 × 10⁸ células CAR-T+",
      ["Bolsa IV personalizada (producto autólogo)"], "Contraindicada",
      "u10", "c10_05",
      familia="Terapia celular CAR-T",
      ci=["Infección activa no controlada", "Enfermedad injerto contra huésped activa"],
      ea=["Síndrome de liberación de citocinas (SLC)", "Neurotoxicidad (ICANS)", "Citopenias prolongadas", "Hipogammaglobulinemia", "Infecciones"],
      ce=["Tocilizumab y dexametasona disponibles para SLC", "Monitorización en UCI durante primeros días", "Vigilar fiebre, hipotensión, hipoxia (SLC)", "Evaluación neurológica frecuente (ICE score)", "Inmunoglobulinas de reemplazo si IgG <400"]),

    M("heparina", "axicabtagene_ciloleucel", "Axicabtagén Ciloleucel", "axicabtagén ciloleucel",
      ["Yescarta"], "Terapia CAR-T anti-CD19",
      "Linfocitos T autólogos con receptor quimérico anti-CD19; diferente constructo que tisagenlecleucel",
      ["Linfoma difuso de células B grandes refractario", "Linfoma folicular refractario"],
      ["Intravenosa"], "2 × 10⁶ células CAR-T/kg (máx 2 × 10⁸)",
      ["Bolsa IV personalizada"], "Contraindicada",
      "u10", "c10_05",
      familia="Terapia celular CAR-T"),

    # ── Tratamiento de hemoglobinopatías ──
    M("heparina", "voxelotor", "Voxelotor", "voxelotor",
      ["Oxbryta"], "Inhibidor de polimerización de HbS",
      "Se une a hemoglobina S estabilizando estado oxi, previniendo polimerización y falciformación",
      ["Anemia hemolítica en enfermedad de células falciformes"],
      ["Oral"], {"adulto": "1500 mg/día", "pediatrico": "≥4 años: 900-1500 mg/día según peso"},
      ["Tab 300 mg", "Tab 500 mg"], "Evitar",
      "u10", "c10_03",
      familia="Anti-falciformación",
      ci=["Hipersensibilidad"],
      ea=["Cefalea", "Diarrea", "Dolor abdominal", "Rash", "Fatiga"],
      ce=["Hemograma cada 2 semanas primeros 2 meses", "Puede elevar Hb total y reducir reticulocitos", "Administrar con o sin alimentos", "No triturar tabletas"]),

    M("heparina", "crizanlizumab", "Crizanlizumab", "crizanlizumab",
      ["Adakveo"], "Anticuerpo anti-P-selectina",
      "Bloquea P-selectina en endotelio impidiendo adhesión de células falciformes y leucocitos",
      ["Prevención de crisis vasooclusivas en enfermedad de células falciformes"],
      ["Intravenosa"], "5 mg/kg IV semanas 0, 2, y luego cada 4 semanas",
      ["Fco 100 mg/10 mL"], "Evitar",
      "u10", "c10_03",
      familia="Anti-adhesión celular",
      pp={"dilucion": "En 100 mL SF o SG5%", "velocidadAdministracion": "Infusión IV en 30 min", "estabilidad": "4h a temperatura ambiente"}),

    M("heparina", "hidroxiurea_falciforme", "Hidroxiurea (Falciforme)", "hidroxiurea",
      ["Siklos", "Droxia"], "Antimetabolito para enfermedad de células falciformes",
      "Aumenta producción de hemoglobina fetal (HbF) que inhibe polimerización de HbS",
      ["Enfermedad de células falciformes: prevención de crisis y síndrome torácico agudo"],
      ["Oral"], {"adulto": "Inicio: 15 mg/kg/día; titular cada 8 sem hasta 35 mg/kg/día o MTD", "pediatrico": "≥2 años: 20 mg/kg/día; titular"},
      ["Cáps 200 mg", "Cáps 300 mg", "Cáps 400 mg", "Tab 100 mg", "Tab 1000 mg"], "Contraindicada",
      "u10", "c10_03",
      familia="Inductores de HbF",
      ci=["Mielosupresión severa", "Embarazo (teratógeno)"],
      ea=["Mielosupresión", "Macrocitosis", "Úlceras en piernas", "Melanoniquia"],
      ce=["Hemograma cada 2-4 semanas durante titulación", "Suspender si neutrófilos <2000 o plaquetas <80,000", "Anticoncepción obligatoria", "Respuesta HbF tarda semanas-meses"],
      emb="X"),

    # ── Antídotos de anticoagulantes ──
    M("antidoto", "protamina_detalle", "Protamina detallado", "protamina sulfato",
      ["Protamine detallado"], "Antídoto de heparina no fraccionada",
      "Se une a heparina formando complejo inactivo; neutralización estequiométrica",
      ["Reversión de anticoagulación con HNF", "Sangrado post-cirugía con CEC"],
      ["Intravenosa"], "1 mg neutraliza ~100 UI de heparina; máx 50 mg por dosis",
      ["Fco 10 mg/mL x5 mL", "Fco 10 mg/mL x25 mL"], "Evitar",
      "u10", "c10_02",
      ci=["Alergia a protamina, insulina NPH, o pescado"],
      ea=["Hipotensión", "Bradicardia", "Disnea", "Reacción anafilactoide", "Hipertensión pulmonar transitoria", "Efecto anticoagulante paradójico si exceso"],
      ce=["Administrar IV lenta (≤5 mg/min)", "Calcular dosis según heparina administrada y tiempo transcurrido", "Monitorizar TTPa post-administración", "Mayor riesgo alérgico en alérgicos a pescado o insulina NPH", "Tener epinefrina disponible"],
      pp={"dilucion": "Puede diluirse en 50 mL SF", "velocidadAdministracion": "≤5 mg/min IV; máx 50 mg en 10 min", "estabilidad": "24h refrigerado"}),
]

# ══════════════════════════════════════════════════════════════════════
# U11 — ANTÍDOTOS SUPLEMENTO (+20)
# ══════════════════════════════════════════════════════════════════════

u11_drugs = [
    # ── Antídotos específicos adicionales ──
    M("antidoto", "sugammadex_detalle", "Sugammadex detallado", "sugammadex",
      ["Bridion detallado"], "Antagonista selectivo de relajantes neuromusculares aminoesteroideos",
      "Ciclodextrina que encapsula rocuronio y vecuronio formando complejo inactivo",
      ["Reversión de bloqueo neuromuscular por rocuronio o vecuronio", "Reversión de emergencia 'can't intubate, can't ventilate'"],
      ["Intravenosa"], "Rutinario: 2-4 mg/kg; Emergencia: 16 mg/kg",
      ["Fco 200 mg/2 mL", "Fco 500 mg/5 mL"], "Evitar",
      "u11", "c11_01",
      ci=["Hipersensibilidad a sugammadex"],
      ea=["Bradicardia", "Náuseas", "Disgeusia", "Broncoespasmo (raro)", "Anafilaxia (raro)"],
      ix=["Anticonceptivos hormonales: reduce eficacia por 7 días", "Toremifeno: puede desplazar del complejo"],
      ce=["Monitorizar TOF para confirmar reversión completa", "Dosis 16 mg/kg solo en emergencia real", "Advertir sobre reducción de eficacia anticonceptiva", "No revierte benzilisoquinolinas (cisatracurio, atracurio)"],
      pp={"dilucion": "Puede administrar sin diluir", "velocidadAdministracion": "Bolo IV en 10 segundos", "estabilidad": "24h fuera de refrigeración"}),

    M("antidoto", "idarucizumab_detalle", "Idarucizumab detallado", "idarucizumab",
      ["Praxbind detallado"], "Antídoto específico de dabigatrán",
      "Fragmento de anticuerpo monoclonal que se une a dabigatrán con afinidad 350x mayor que la trombina",
      ["Reversión de dabigatrán en cirugía urgente", "Sangrado potencialmente mortal en paciente con dabigatrán"],
      ["Intravenosa"], "5 g IV (2 frascos de 2.5 g) en bolo o infusión rápida",
      ["Fco 2.5 g/50 mL x2"], "Evitar",
      "u11", "c11_01",
      ci=["Hipersensibilidad (pero no demorar en emergencia)"],
      ea=["Cefalea", "Hipopotasemia", "Trombosis (al revertir anticoagulación)"],
      ce=["Administrar los 2 frascos consecutivamente", "Reversión completa en minutos", "Reiniciar anticoagulación en 24h si indicada", "Medir TTPa o dTT pre y post para confirmar efecto"],
      pp={"dilucion": "No diluir; administrar directamente", "velocidadAdministracion": "Bolo IV x2 o infusión en 5-10 min", "estabilidad": "6h fuera de refrigeración"}),

    M("antidoto", "andexanet_detalle", "Andexanet Alfa detallado", "andexanet alfa",
      ["Ondexxya detallado"], "Antídoto de inhibidores del factor Xa",
      "Factor Xa recombinante modificado (inactivo) que actúa como señuelo, capturando anti-Xa",
      ["Reversión de rivaroxabán o apixabán en sangrado potencialmente mortal"],
      ["Intravenosa"], "Dosis baja: bolo 400 mg + infusión 480 mg/2h; Dosis alta: bolo 800 mg + infusión 960 mg/2h",
      ["Fco 200 mg liofilizado"], "Evitar",
      "u11", "c11_01",
      ci=["Hipersensibilidad a proteínas de hámster"],
      ea=["Trombosis (TEV, ACV, IAM)", "Reacciones infusionales", "Anticuerpos anti-factor Xa"],
      ce=["Elegir dosis según fármaco y tiempo desde última dosis", "Monitorizar anti-Xa para confirmar reversión", "Reiniciar anticoagulación apenas sea seguro", "Vigilar eventos trombóticos post-reversión"],
      pp={"dilucion": "Reconstituir cada vial con 20 mL agua estéril", "velocidadAdministracion": "Bolo IV a ~30 mg/min; Infusión: 4-8 mg/min", "estabilidad": "8h refrigerado tras reconstitución"}),

    M("antidoto", "acido_folínico_rescue", "Ácido Folínico (Rescate)", "ácido folínico",
      ["Leucovorin Rescue"], "Rescate de folato tras metotrexato alta dosis",
      "Provee tetrahidrofolato reducido bypaseando bloqueo de DHFR por metotrexato",
      ["Rescate leucovorínico tras metotrexato alta dosis", "Toxicidad por metotrexato", "Anemia megaloblástica por déficit de folato"],
      ["Intravenosa", "Intramuscular", "Oral"], "Rescate: 15 mg/m² IV c/6h iniciando 24h post-MTX hasta niveles <0.05 µM",
      ["Tab 15 mg", "Amp 50 mg/5 mL", "Amp 200 mg/20 mL"], "Compatible",
      "u11", "c11_01",
      ce=["Iniciar a las 24h exactas del inicio de MTX", "Niveles de MTX a 24, 48, 72h post-infusión", "Continuar hasta MTX <0.05 µmol/L", "Hidratación alcalina concomitante", "Si MTX >1 µmol/L a 48h: aumentar dosis de leucovorin"]),

    M("antidoto", "fomepizol_detalle", "Fomepizol detallado", "fomepizol",
      ["Antizol detallado"], "Inhibidor de alcohol deshidrogenasa",
      "Inhibe competitivamente alcohol deshidrogenasa previniendo metabolismo de metanol y etilenglicol a metabolitos tóxicos",
      ["Intoxicación por metanol", "Intoxicación por etilenglicol", "Intoxicación por dietilenglicol"],
      ["Intravenosa"], "Carga: 15 mg/kg IV; luego 10 mg/kg c/12h x4 dosis; luego 15 mg/kg c/12h",
      ["Fco 1 g/mL x1.5 mL"], "Contraindicada",
      "u11", "c11_01",
      ci=["Hipersensibilidad a fomepizol o pirazoles"],
      ea=["Cefalea", "Náuseas", "Mareo", "Reacción en sitio de infusión", "Eosinofilia transitoria"],
      ce=["Iniciar ante sospecha SIN esperar niveles confirmatorios", "Continuar hasta nivel de tóxico <20 mg/dL y pH normalizado", "Durante hemodiálisis: doblar frecuencia a c/4h", "Monitorizar osmolalidad, gases, anion gap, niveles de tóxico"],
      pp={"dilucion": "En 100 mL SF o SG5%", "velocidadAdministracion": "Infusión IV en 30 min", "estabilidad": "24h diluido"}),

    M("antidoto", "hidroxocobalamina_detalle", "Hidroxocobalamina (Antídoto)", "hidroxocobalamina",
      ["Cyanokit detallado"], "Antídoto de intoxicación por cianuro",
      "Se une al cianuro formando cianocobalamina (vitamina B12) no tóxica que se excreta renalmente",
      ["Intoxicación por cianuro (inhalación de humo, industrial)", "Sospecha de intoxicación cianhídrica"],
      ["Intravenosa"], "Adulto: 5 g IV en 15 min; puede repetir 5 g si persisten síntomas",
      ["Kit 5 g polvo liofilizado + diluyente 200 mL"], "Compatible",
      "u11", "c11_01",
      ci=["Ninguna en situación de emergencia"],
      ea=["Cromaturia roja (hasta 5 semanas)", "Coloración roja de piel", "HTA transitoria", "Cefalea", "Interferencia con pruebas de laboratorio"],
      ce=["Administrar ante SOSPECHA sin esperar confirmación", "La cromaturia es normal y esperada", "Interfiere con colorimetría de laboratorio durante días", "Puede repetirse la dosis", "Alternativa a kit nitrito/tiosulfato"],
      pp={"dilucion": "Reconstituir 5 g en 200 mL SF (NO SG ni Ringer)", "velocidadAdministracion": "5 g en 15 min", "estabilidad": "6h tras reconstitución"}),

    # ── Emergencias toxicológicas ──
    M("antidoto", "emulsion_lipidica_20", "Emulsión Lipídica 20% (Antídoto)", "intralipid 20%",
      ["Intralipid 20% Rescue"], "Antídoto de toxicidad por anestésicos locales",
      "Actúa como 'sumidero lipídico': captura fármacos lipofílicos del plasma; también aporta sustrato energético miocárdico",
      ["Toxicidad sistémica por anestésicos locales (LAST)", "Sobredosis de fármacos lipofílicos (calcioantagonistas, betabloqueantes, antidepresivos tricíclicos)"],
      ["Intravenosa"], "Bolo: 1.5 mL/kg en 1 min; Infusión: 0.25 mL/kg/min x30-60 min; Máx 12 mL/kg",
      ["Fco Intralipid 20% x100 mL", "Fco 20% x250 mL"], "No aplica",
      "u11", "c11_02",
      ci=["Alergia a componentes (huevo, soja)", "No demorar en emergencia LAST"],
      ea=["Lipemia transitoria", "Interferencia con análisis de laboratorio", "Pancreatitis (teórico con dosis altas)"],
      ce=["Debe estar DISPONIBLE donde se usen anestésicos locales", "Protocolo LAST: bolo 1.5 mL/kg + infusión inmediata", "Puede repetir bolo 2 veces si no responde", "NO usar propofol como sustituto", "Continuar RCP durante administración"]),

    M("antidoto", "glucosa_50_detalle", "Glucosa 50% (Emergencia)", "dextrosa 50%",
      ["Dextrosa 50% Emergencia"], "Solución hipertónica de glucosa para hipoglucemia severa",
      "Elevación inmediata de glucemia en hipoglucemia con compromiso neurológico",
      ["Hipoglucemia severa con alteración de consciencia", "Coma hipoglucémico", "Hipoglucemia en paciente que no puede ingerir oral"],
      ["Intravenosa"], "25-50 mL (12.5-25 g de glucosa) IV bolo; repetir según glucemia",
      ["Amp 50% x50 mL"], "Compatible",
      "u11", "c11_02",
      ci=["Hiperglucemia"],
      ea=["Flebitis (solución hiperosmolar)", "Hiperglucemia rebote", "Necrosis tisular si extravasación"],
      ce=["Administrar por vía de buen calibre (preferible central)", "Glucemia capilar cada 15 min post-administración", "Seguir con infusión SG10% para prevenir recurrencia", "Identificar y tratar causa de hipoglucemia", "Administrar tiamina IV antes de glucosa en sospecha de Wernicke"],
      pp={"dilucion": "No diluir para emergencia; o diluir a 10-25% para infusión", "velocidadAdministracion": "Bolo IV en 1-3 min", "estabilidad": "Estable a temperatura ambiente"}),

    M("antidoto", "diazepam_status", "Diazepam Status Epilepticus", "diazepam",
      ["Valium Status"], "Benzodiazepina para estatus epiléptico",
      "Potencia efecto GABA-A; tratamiento de primera línea en convulsiones prolongadas",
      ["Status epilepticus", "Convulsiones prolongadas (>5 min)", "Convulsiones febriles prolongadas"],
      ["Intravenosa", "Rectal"], {"adulto": "IV: 10 mg a 5 mg/min, repetir c/5-10 min (máx 30 mg); Rectal: 20 mg", "pediatrico": "IV: 0.2-0.5 mg/kg (máx 10 mg); Rectal: 0.5 mg/kg"},
      ["Amp 10 mg/2 mL IV", "Gel rectal 10 mg", "Gel rectal 20 mg"], "Evitar",
      "u11", "c11_02",
      familia="Anticonvulsivantes de emergencia",
      ce=["Primera línea en status con lorazepam", "Administrar IV lenta (máx 5 mg/min) por riesgo de apnea", "Equipo de ventilación disponible", "No diluir (precipita)", "Vía rectal como alternativa prehospitalaria"]),

    M("antidoto", "midazolam_emergencia", "Midazolam Emergencia", "midazolam",
      ["Midazolam Bucal/IM"], "Benzodiazepina para convulsiones prehospitalarias",
      "Potencia GABA-A; administración IM o bucal sin acceso IV",
      ["Status epilepticus prehospitalario", "Convulsiones cuando no hay acceso IV", "Sedación de emergencia"],
      ["Intramuscular", "Bucal", "Intranasal"], {"adulto": "IM: 10 mg; Bucal: 10 mg; IN: 5 mg", "pediatrico": "IM: 0.2 mg/kg; Bucal: 0.2-0.5 mg/kg"},
      ["Sol bucal 10 mg/mL", "Amp 5 mg/mL IM", "Sol intranasal 5 mg/0.1 mL"], "Evitar",
      "u11", "c11_02",
      familia="Anticonvulsivantes de emergencia"),

    M("antidoto", "tiamina_iv_emergencia", "Tiamina IV (Emergencia)", "tiamina (vitamina B1)",
      ["Tiamina IV Emergencia"], "Vitamina B1 IV para prevención/tratamiento de Wernicke",
      "Cofactor esencial para metabolismo de carbohidratos; previene encefalopatía de Wernicke",
      ["Sospecha de encefalopatía de Wernicke", "Alcoholismo crónico con desnutrición", "SIEMPRE antes de glucosa IV en alcohólicos/desnutridos"],
      ["Intravenosa", "Intramuscular"], "Profilaxis: 100-250 mg IV/IM c/24h x3-5 días; Wernicke: 500 mg IV c/8h x3 días",
      ["Amp 100 mg/mL x2 mL"], "Compatible",
      "u11", "c11_02",
      familia="Vitaminas de emergencia",
      ci=["Hipersensibilidad (raro pero grave: anafilaxia)"],
      ea=["Dolor en sitio de inyección", "Anafilaxia (rara, más con IM)", "Rubor"],
      ce=["Administrar ANTES de glucosa en alcohólicos", "Vía IV lenta (riesgo anafilaxia)", "Tratamiento empírico ante sospecha", "Tríada Wernicke: confusión + ataxia + oftalmoplejía"],
      pp={"dilucion": "En 100 mL SF", "velocidadAdministracion": "Infusión en 30 min (no bolo rápido)", "estabilidad": "24h diluido"}),

    M("antidoto", "octreotida_hipoglucemia", "Octreótida para Hipoglucemia", "octreótida",
      ["Sandostatin Hipoglucemia"], "Análogo de somatostatina para hipoglucemia refractaria",
      "Inhibe secreción de insulina pancreática; útil en sobredosis de sulfonilureas",
      ["Hipoglucemia por sobredosis de sulfonilureas refractaria a glucosa", "Hipoglucemia por quinina"],
      ["Subcutánea", "Intravenosa"], "50-100 mcg SC c/6-12h (o infusión IV 25-50 mcg/h)",
      ["Amp 0.1 mg/mL", "Amp 0.5 mg/mL"], "Evitar",
      "u11", "c11_01"),

    M("antidoto", "dantroleno_hipertermia", "Dantroleno IV (Hipertermia Maligna)", "dantroleno sódico IV",
      ["Dantrium IV", "Ryanodex"], "Antídoto de hipertermia maligna",
      "Bloquea liberación de calcio del retículo sarcoplásmico a través del receptor rianodina",
      ["Hipertermia maligna", "Síndrome neuroléptico maligno (segunda línea)"],
      ["Intravenosa"], "Carga: 2.5 mg/kg IV rápido, repetir c/5 min hasta respuesta (máx 10 mg/kg); Mantenimiento: 1-2 mg/kg c/4-6h x24-48h",
      ["Fco 20 mg liofilizado + 60 mL agua estéril", "Fco Ryanodex 250 mg"], "Evitar",
      "u11", "c11_01",
      ci=["Ninguna en hipertermia maligna (emergencia vital)"],
      ea=["Debilidad muscular", "Flebitis", "Insuficiencia respiratoria", "Hepatotoxicidad"],
      ce=["Reconstituir rápidamente (cada vial necesita 60 mL agua)", "Administrar en cuanto se sospecha HM", "Preparar múltiples viales simultáneamente", "Enfriar activamente al paciente", "Ryanodex: solo necesita 1 vial (250 mg en 5 mL)"],
      pp={"dilucion": "Reconstituir 20 mg en 60 mL agua estéril (no SF ni SG)", "velocidadAdministracion": "Bolo IV rápido; repetir c/5 min", "estabilidad": "6h tras reconstitución"}),

    M("antidoto", "flumazenilo_detalle", "Flumazenilo detallado", "flumazenilo",
      ["Anexate detallado"], "Antagonista de receptor benzodiazepínico",
      "Antagonista competitivo en sitio de unión de BZD en receptor GABA-A; revierte sedación y depresión respiratoria",
      ["Reversión de sedación con benzodiazepinas", "Diagnóstico diferencial de coma", "Sobredosis de benzodiazepinas"],
      ["Intravenosa"], "0.2 mg IV en 30s; repetir 0.2 mg c/60s hasta respuesta (máx 3-5 mg total)",
      ["Amp 0.1 mg/mL x5 mL", "Amp 0.1 mg/mL x10 mL"], "Evitar",
      "u11", "c11_01",
      ci=["Dependencia a benzodiazepinas (riesgo convulsiones)", "Uso de BZD para control de epilepsia", "Intoxicación mixta con tricíclicos o cocaína"],
      ea=["Convulsiones (en dependientes)", "Náuseas", "Agitación", "Arritmias (en intoxicaciones mixtas)"],
      ce=["NO usar en sospecha de ingesta de tricíclicos", "Efecto corto (45-90 min): riesgo de resedación", "Titular lentamente", "Monitorización prolongada post-administración", "Dosis repetidas según necesidad"],
      pp={"dilucion": "Puede usarse sin diluir o en SG5%/SF", "velocidadAdministracion": "0.2 mg IV en 30 segundos", "estabilidad": "24h en SG5%"}),

    M("antidoto", "acido_tranexamico_masivo", "Ácido Tranexámico (Hemorragia Masiva)", "ácido tranexámico",
      ["CRASH-2 protocol"], "Antifibrinolítico en trauma y hemorragia masiva",
      "Inhibe activación de plasminógeno; reduce mortalidad en hemorragia traumática si se administra en <3h",
      ["Hemorragia post-traumática", "Hemorragia postparto", "Protocolo de transfusión masiva"],
      ["Intravenosa"], "1 g IV en 10 min (dentro de 3h post-trauma); luego 1 g en infusión de 8h",
      ["Amp 100 mg/mL x10 mL"], "Compatible",
      "u11", "c11_02",
      familia="Antifibrinolíticos de emergencia",
      ce=["Administrar dentro de las PRIMERAS 3 HORAS post-trauma", "No beneficio si >3h (puede ser perjudicial)", "Primera dosis en bolo; segunda en infusión lenta", "Incluir en protocolo de transfusión masiva"],
      pp={"dilucion": "1 g en 100 mL SF", "velocidadAdministracion": "Primera dosis: 1 g en 10 min; Segunda: 1 g en 8h", "estabilidad": "24h diluido"}),

    M("antidoto", "epinefrina_anafilaxia", "Epinefrina Autoinyector (Anafilaxia)", "epinefrina",
      ["EpiPen", "Jext", "Anapen"], "Adrenalina IM para anafilaxia en comunidad",
      "Agonista alfa y beta adrenérgico: revierte broncoespasmo, hipotensión y edema de anafilaxia",
      ["Anafilaxia (tratamiento de primera línea)", "Reacciones alérgicas severas con riesgo vital"],
      ["Intramuscular"], {"adulto": "0.3-0.5 mg IM en muslo anterolateral (autoinyector: 0.3 mg)", "pediatrico": "0.01 mg/kg IM (autoinyector: 0.15 mg si 15-30 kg; 0.3 mg si >30 kg)"},
      ["Autoinyector 0.15 mg", "Autoinyector 0.3 mg", "Amp 1 mg/mL"], "Compatible en emergencia",
      "u11", "c11_02",
      ci=["Ninguna absoluta en anafilaxia (es tratamiento vital)"],
      ea=["Taquicardia", "Palpitaciones", "Temblor", "Palidez", "Cefalea", "Ansiedad"],
      ce=["SIEMPRE IM en cara anterolateral del muslo", "Puede repetir cada 5-15 min si no responde", "Posición supina con piernas elevadas (excepto si vómito/disnea)", "Observación mínima 4-6h post-anafilaxia", "Prescribir 2 autoinyectores siempre", "Educar sobre uso y portabilidad"]),

    M("antidoto", "atropina_organofosforado", "Atropina (Intoxicación Organofosforados)", "atropina",
      ["Atropina Tóxico"], "Anticolinérgico para intoxicación por organofosforados",
      "Antagoniza efectos muscarínicos del exceso de acetilcolina causado por inhibición de colinesterasa",
      ["Intoxicación por organofosforados", "Intoxicación por carbamatos", "Intoxicación por agentes nerviosos"],
      ["Intravenosa"], "Dosis agresiva: 2-4 mg IV c/5-10 min hasta control de secreciones; luego infusión 0.5-1 mg/h",
      ["Amp 1 mg/mL x1 mL", "Amp 0.5 mg/mL x5 mL"], "Evitar",
      "u11", "c11_01",
      ci=["Ninguna en intoxicación por organofosforados"],
      ea=["Taquicardia", "Boca seca", "Midriasis", "Retención urinaria", "Agitación"],
      ce=["Endpoint: secado de secreciones bronquiales (no midriasis)", "Dosis pueden ser ENORMES (centenares de mg en 24h)", "Combinar con pralidoxima si organofosforado", "No atropinizar por FC: guiarse por secreciones", "Descontaminación del paciente con EPP"]),
]

# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    import os
    os.chdir(os.path.join(os.path.dirname(__file__), ".."))

    all_drugs = u12_drugs + u10_drugs + u11_drugs
    print(f"=== U12+U10+U11 supplement: {len(all_drugs)} drugs ===")
    added = add_drugs_to_file(all_drugs)

    cats = load_categories()

    # New chapters
    add_chapter(cats, "u10", {
        "id": "c10_05",
        "nombre": "Terapia Celular y Génica",
        "drugIds": []
    })

    for d in all_drugs:
        add_drug_to_chapter(cats, d["capituloId"], d["id"])

    save_categories(cats)
    print(f"Done. {added} drugs added.")
